class proto_noble_class : pb_monster_base
{

default
{
	Radius 24;
	Height 88;
	
	pb_monster_base.headshot_multiplier 3;
	pb_monster_base.head_starting_position 80;
	pb_monster_base.legs_height_max -1;//nobles cant get an arrow in the knee
}

states
{
	Death.Blackhole://exluding belphegors
		TNT1 A 0 {A_Scream(); A_NoBlocking(); A_PlaySound("redburn",6,1,1);}
		tnt1 a 0
		{
			name class_name = getclassname();
			switch( class_name )
			{
				case 'pb_Infernus' : setstatelabel("infernus_holed"); break;
				case 'pb_Cyber_Paladin' : setstatelabel("paladin_holed");break;
				case 'pb_Phasic_Knight_X' : setstatelabel("cyber_k_holed");break;
				default : break;
			}
		}
		ID56 AABCDEFGHIJK 4;
		TNT1 A 0 A_StopSound(2);
	Stop;

	infernus_holed:
		ID69 AAABCDEFGHIJ 4;
		TNT1 A 0 A_StopSound(2);
	Stop;

	paladin_holed:
		ID70 AAABCDEFGH 4;
		TNT1 A 0 A_StopSound(2);
		Stop;

	cyber_k_holed:
		ID71 AAABCDEFGHI 4;
		TNT1 A 0 A_StopSound(2);
	Stop;
}

}

class knight_base : proto_noble_class {}


class baron_base : proto_noble_class {}






//stuff for DELETION
CLASS Knight_Attack : pb_projectile_base
{
Default
{
	Radius 24;
	Height 16;
	DamageType "HKFT";
	Projectile;
	+RANDOMIZE;
	+FORCEXYBILLBOARD;
	+THRUGHOST;
	RenderStyle "Add";
	Alpha 0.6;
	Damage 10;
	Speed 42;
	//HitObituary "$OB_IMPHIT"
	SeeSound "none";
	DeathSound "none";
	Decal "none";
}

States
{
	Spawn:
		TNT1 A 2 BRIGHT;
		TNT1 A 2;//A_PlaySound("weapons/gswing")
	Goto Death;

	Death:
		TNT1 A 0 BRIGHT;
	Stop;
}

}


CLASS Knight_Slam : pb_projectile_base
{ 
Default
{		
	+NOBLOCKMAP;
	+MISSILE;
	Radius 2;
	Height 2;
	Damagetype "ExplosiveImpact";
}

States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Explode(random(52,63),118,0);
	Stop;
}
	
}



CLASS noble_head_explosion: pb_blood_and_gore_base
{ 
Default
{
	+noclip
	+nointeraction
	Decal "BloodSuper";
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("HellKnightHeadPiece", 0, 0, random(0, 360), 2, random(50, 80));
		TNT1 A 0 a_spawnprojectile("HellKnightHeadPiece", 0, 0, random(0, 360), 2, random(50, 80));
		TNT1 AA 0 a_spawnprojectile("WallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Teeth", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 80));
		TNT1 A 10;
	Stop;
}

}


CLASS noble_head_explosion_2: pb_blood_and_gore_base { 
Default {
	+noclip
	+nointeraction
	Decal "BloodSuper";
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAA 0 a_spawnprojectile("brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("HellKnightHeadPiece", 0, 0, random(0, 360), 2, random(50, 80));
		TNT1 A 0 a_spawnprojectile("WallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAA 0 a_spawnprojectile("Teeth", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 80));
		TNT1 A 10;
		Stop;
}
}