class proto_noble_class : pb_monster_base
{

default
{
	Radius 24;
	Height 88;
	
	pb_monster_base.headshot_multiplier 3;
	pb_monster_base.head_starting_position 80;
	pb_monster_base.legs_height_max -1;//nobles cant have an arrow in the knee
}

states
{
	Death.Blackhole://exluding belphegors
		TNT1 A 0 {A_Scream(); A_NoBlocking(); A_PlaySound("redburn",6,1,1);}
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		ID55 AABCDEFGHIJK 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
	Stop;
}

}

class knight_base : proto_noble_class {}
class baron_base : proto_noble_class {}

//stuff for DELETION
CLASS Knight_Attack : pb_projectile_base
{
Default
{
	Radius 24;
	Height 16;
	DamageType "HKFT";
	Projectile;
	+RANDOMIZE;
	+FORCEXYBILLBOARD;
	+THRUGHOST;
	RenderStyle "Add";
	Alpha 0.6;
	Damage 10;
	Speed 42;
	//HitObituary "$OB_IMPHIT"
	SeeSound "none";
	DeathSound "none";
	Decal "none";
}

States
{
	Spawn:
		TNT1 A 2 BRIGHT;
		TNT1 A 2;//A_PlaySound("weapons/gswing")
	Goto Death;

	Death:
		TNT1 A 0 BRIGHT;
	Stop;
}

}


CLASS Knight_Slam : pb_projectile_base
{ 
Default
{		
	+NOBLOCKMAP;
	+MISSILE;
	Radius 2;
	Height 2;
	Damagetype "ExplosiveImpact";
}

States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Explode(random(52,63),118,0);
	Stop;
}
	
}