class proto_noble_class : pb_monster_base
{

default
{
	Radius 24;
	Height 88;
	
	pb_monster_base.headshot_multiplier 3;
	pb_monster_base.head_starting_position 80;
	pb_monster_base.legs_height_max -1;//nobles cant have an arrow in the knee
}

states
{
	Death.Blackhole://exluding belphegors
		TNT1 A 0 {A_Scream(); A_NoBlocking(); A_PlaySound("redburn",6,1,1);}
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		tnt1 a 0
		{
			name class_name = getclassname();
			switch ( class_name )
			{
				case 'pb_Infernus' : setstatelabel("infernus_holed"); break;
				case 'pb_Cyber_Paladin' : setstatelabel("paladin_holed");break;
				case 'pb_Phasic_Knight_X' : setstatelabel("cyber_k_holed");break;
				default : break;
			}
		}
		ID56 AABCDEFGHIJK 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
	Stop;

	infernus_holed:
		ID69 AAABCDEFGHIJ 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 50, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
	Stop;

	paladin_holed:
		ID70 AAABCDEFGH 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 50, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;

	cyber_k_holed:
		ID71 AAABCDEFGHI 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 50, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
	Stop;
}

}

class knight_base : proto_noble_class {}
class baron_base : proto_noble_class {}

//stuff for DELETION
CLASS Knight_Attack : pb_projectile_base
{
Default
{
	Radius 24;
	Height 16;
	DamageType "HKFT";
	Projectile;
	+RANDOMIZE;
	+FORCEXYBILLBOARD;
	+THRUGHOST;
	RenderStyle "Add";
	Alpha 0.6;
	Damage 10;
	Speed 42;
	//HitObituary "$OB_IMPHIT"
	SeeSound "none";
	DeathSound "none";
	Decal "none";
}

States
{
	Spawn:
		TNT1 A 2 BRIGHT;
		TNT1 A 2;//A_PlaySound("weapons/gswing")
	Goto Death;

	Death:
		TNT1 A 0 BRIGHT;
	Stop;
}

}


CLASS Knight_Slam : pb_projectile_base
{ 
Default
{		
	+NOBLOCKMAP;
	+MISSILE;
	Radius 2;
	Height 2;
	Damagetype "ExplosiveImpact";
}

States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Explode(random(52,63),118,0);
	Stop;
}
	
}

































CLASS BaronHeadPiece : pb_blood_and_gore_base { 
	Default {
	Radius 2;
	Height 2;
	Speed 6;
	Mass 1;
	Decal "BrutalBloodSplat";
	+CLIENTSIDEONLY;
	BounceFactor 0.4;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	+FLOORCLIP;
	Scale 1.2;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		XHE5 IJKL 4 a_spawnprojectile("Brutal_FlyingBlood"/*Green_FlyingBrutal_FlyingBloodTrail*/, 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		XHE5 I 1;
		TNT1 A 0 A_QueueCorpse;
 	Rest:
		XHE5 I 800;
		XHE5 I -1;
		Stop;
	DoNothing:
		TNT1 A 0;
		Stop;
	}
}

CLASS HellKnightHeadPiece: BaronHeadPiece { 
	Default {
	Scale 1.0;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		HKHE IJKL 4 a_spawnprojectile("Brutal_FlyingBlood"/*Green_FlyingBrutal_FlyingBloodTrail*/, 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		HKHE I 2;
		TNT1 A 0 A_QueueCorpse;
 	Rest:
		HKHE I 800;
		HKHE I -1;
		Stop;
	DoNothing:
		TNT1 A 0;
		Stop;
	}
}

CLASS HellKnightHeadPiece2: HellKnightHeadPiece { 
	Default {
	XScale -1.0;
	}
}


CLASS XDeathCyberPaladinRipped: XDeathBullArm1 { 
	Default {
	
	-CLIENTSIDEONLY;
	Scale 1.0;
	Speed 4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		CP4L AA 6;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		CP4L B 1;
		CP4L B -1;
		Stop;
	}
}


CLASS XDeathCyberKnightRipped: XDeathBullArm1 { 
	Default {
	
	-CLIENTSIDEONLY;
	Scale 1.0;
	Speed 4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		CP4L CC 6;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		CP4L D 1;
		CP4L D -1;
		Stop;
	}
}



CLASS HellKnightHead: LimbBase { 
	Default {
	
	damagefactor "Kick", 9.0;
	damagefactor "Melee", 9.0;
	damagefactor "SuperPunch", 9.0;
	-CLIENTSIDEONLY;
	+SHOOTABLE;
	-NOBLOCKMAP;
	+SOLID;
	+THRUACTORS;
	BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	damagefactor "Crush", 50.0;
	Radius 10;
	Mass 12;
	Health 60;
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		HKHE G 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		HKHE G -1;
		Stop;
	Death:
		TNT1 A 0 a_spawnprojectile("HellKnightHeadExplode", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		Stop;
	Death.plasma:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL A 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0;
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		HKHE ABCDEFGH 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathHellKnightHeadKicked", 5, 0, random(170, 190), 2, random(20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		HKHE ABCDEFGH 1;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		HKHE ABCDEFGH 6;
		HKHE I 0 A_SpawnItem("HellKnightHead");
		Stop;
		
}}


CLASS XDeathHellKnightHeadKicked: XDeathHellKnightHead { 
	Default {
	
	-BOUNCEONACTORS;
	Damage 4;
	Speed 13;
	BounceFactor 0.4;
	}
}





CLASS XDeathBaronHead5: XDeathBullArm1 { 
	Default {
	
	BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	-CLIENTSIDEONLY;
	Scale 1.2;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		XHE5 ABCDEFGH 6;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		XHE5 A 1;
		XHE5 A 1 A_SpawnItem("BaronHead",0,0,0,1);
		Stop;
	}
}



CLASS BaronHead: LimbBase { 
	Default {
	
	BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	damagefactor "Kick", 9.0;
	damagefactor "Melee", 9.0;
	damagefactor "SuperPunch", 9.0;
	-CLIENTSIDEONLY;
	Radius 10;
	
	Mass 12;
	Health 60;
	Scale 1.2;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		XHE5 A 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		XHE5 A -1;
		Stop;
		
	Death:
		TNT1 AAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 a_spawnprojectile("BaronOfHellHeadExplode", 5, 0, random(0, 360), 2, random(60, 140));
		Stop;
	Death.Trample:
	Crush:
		//TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
		TNT1 AAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS1 B 5;
		CRS1 B 9009;
		Stop;
	Death.plasma:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL A 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0;
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		XHE5 A 1 A_Pain;
		XHE5 A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeathBaronHeadKicked", 5, 0, random(170, 190), 2, random(20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		XHE5 ABCD 3;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		XHE5 ABCD 6;
		//XHE5 I 0 A_SpawnItem("XDeathBaronHead");
		Stop;
		
}}


CLASS XDeathBaronHeadKicked: XDeathBaronHead5 { 
	Default {
	
	-BOUNCEONACTORS;
	Damage 4;
	Speed 13;
	BounceFactor 0.4;
	}
}


CLASS Gib_HellKnightTorso: LimbBase { 
	Default {
	
	Scale 1.1;
	BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	BloodColor "DarkGreen";
	}
	States
	{
	Spawn:
		GHKT I 1;
		TNT1 A 0 A_QueueCorpse;
		GHKT I 1900;
		GHKT I -1;
		Stop;
	Death:    
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("MuchBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 5, 0, random(0, 360), 2, random(10, 80));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 5, 0, random(0, 360), 2, random(10, 80));
		TNT1 A 0 a_spawnprojectile("GenericHKGib1", 5, 0, random(0, 360), 2, random(10, 80));
		TNT1 A 0 a_spawnprojectile("XDeathHellKnightArm", 5, 0, random(0, 360), 2, random(10, 80));
Stop;}}



CLASS XDeathBaronofHellTorso: XDeathArm1 { 
	Default {
	
	Scale 1.3;
	Speed 12;
	BounceFactor 0.4;
	Decal "GreenBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		GORD ABCD 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		GORD E 1;
		HNDC A 0 A_SpawnItem("Gib_BaronofHellTorso",0,0,0,1);
		Stop;
	}
}

CLASS XDeathCyberKnightTorso: XDeathArm1 { 
	Default {
	
	Scale 1.3;
	Speed 12;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		G0RC ABCD 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		G0RC E 1;
		HNDC A 0 A_SpawnItem("Gib_CyberKnightTorso",0,0,0,1);
		Stop;
	}
}

CLASS Gib_BaronofHellTorso: LimbBase { 
	Default {
	
	Scale 1.3;
	BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	BloodColor "DarkGreen";
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		GORD E -1;
		Stop;
	Death:    
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("MuchBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 5, 0, random(0, 360), 2, random(10, 80));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 5, 0, random(0, 360), 2, random(10, 80));
		TNT1 AA 0 a_spawnprojectile("GenericBaronGib1", 5, 0, random(0, 360), 2, random(10, 80));
		TNT1 A 0 a_spawnprojectile("GenericBaronGib2", 5, 0, random(0, 360), 2, random(10, 80));
Stop;}}

CLASS Gib_CyberKnightTorso: LimbBase { 
	Default {
	
	Scale 1.3;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		G0RC E -1;
		sTOP;
Death.plasma: Death.Burn: Death.Flames:
	    TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
        Stop;
Death:    
	TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 AAAAAAA 0 a_spawnprojectile("named_BloodTr", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 AAAAA 0 a_spawnprojectile("Xdeath1", 0, 0, random(0, 360), 2, random(0, 360));
Stop;}}


CLASS GenericHKGib1: XDeathArm1 { 
	Default {
	
	Scale 0.9;
	Speed 5;
	BounceFactor 0.4;
	BounceCount 3;
	+CLIENTSIDEONLY;
	Gravity 0.8;
	}
	protected int frame_num;
	States
	{
	Spawn:
		tnt1 a 0 nodelay {frame_num = random(0, 3);}
		GG71 A 4 {
			a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
			frame = frame_num;
		}
		Loop;
	Death:
		TNT1 A 0 A_QueueCorpse;
		GG71 A -1 {frame = frame_num;}
		Stop;
	}
}


CLASS GenericBaronGib1: GenericHKGib1 { 
	Default {
	
	Scale 1.0;
	}
	States
	{
	Spawn:
		GG71 E 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		GG71 E -1;
		Stop;
	}
}

CLASS GenericBaronGib1b: GenericBaronGib1 { 
	Default {
	
	YScale 0.8;
	XScale -1.0;
	}
}


CLASS GenericBaronGib2: GenericHKGib1 { 
	Default {
	
	Scale 1.0;
	}
	States
	{
	Spawn:
		GG71 F 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		GG71 F -1;
		Stop;
	}
}


CLASS GenericBaronGib2b: GenericBaronGib2 { 
	Default {
	
	YScale 1.1;
	XScale -1.0;
	}
}







CLASS XDeathHellKnightArm: XDeathArm1 { 
	Default {
	
	Scale 1.1;
	Speed 12;
	BounceFactor 0.4;
	BounceCount 3;
	Decal "GreenBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		GHKA ABCDEFGH 4 a_spawnprojectile("brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		GHKA I 1;
		TNT1 A 0 A_SpawnItem("Gib_HellKnightArm", 1);
		Stop;
	}
}

CLASS XDeathBaronOfHellArm: XDeathArm1 { 
	Default {
	
	Scale 1.1;
	Speed 12;
	BounceFactor 0.4;
	BounceCount 3;
	Decal "GreenBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		GORD FGHIJKLM 4 a_spawnprojectile("brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		GORD N 1;
		TNT1 A 0 A_SpawnItem("Gib_BaronOfHellArm", 1);
		Stop;
	}
}

CLASS XDeathCyberKnightArm: XDeathArm1 { 
	Default {
	
	Scale 1.1;
	Speed 12;
	BounceFactor 0.4;
	BounceCount 3;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		G0RB ABCD 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		G0RB E 1;
		TNT1 A 0 A_SpawnItem("Gib_CyberKnightArm", 1);
		Stop;
	}
}

CLASS Gib_HellKnightArm: LimbBase { 
	Default {
	
	Scale 1.1;
	BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	BloodColor "DarkGreen";
	}
	States
	{
	Spawn:
		GHKA I 1;
		TNT1 A 0 A_QueueCorpse;
		GHKA I 1900;
		GHKA I -1;
		Stop;

	Death:   
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 a_spawnprojectile("PB_blood", 2, 0, random(0, 360), 2, random(0, 360));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 2, 0, random(0, 360), 2, random(10, 90));
		TNT1 AA 0 a_spawnprojectile("GenericHKGib1", 2, 0, random(0, 360), 2, random(10, 90));
		Stop;

	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		GHKA ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
Death.Kick: Death.SuperPunches: Death.Melee:
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,30,0,1);
	GHKA A 5;
	GHKA ABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
Landz:
	XDT5 I 0 A_SpawnItem("Gib_HellKnightArm");
Stop;}}

CLASS Gib_BaronOfHellArm: LimbBase { 
	Default {
 
    Scale 1.1;
	BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	BloodColor "DarkGreen";
	}
    States
    {
    Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
        GORD N 1900;
	GORD N -1;
	Stop;
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
        Stop;
    Death:    
    TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
    TNT1 AAAAAAA 0 a_spawnprojectile("named_BloodTr", 0, 0, random(0, 360), 2, random(0, 360));
    TNT1 A 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 360));
Stop;}}

CLASS Gib_CyberKnightArm: LimbBase { 
	Default {
 
    Scale 1.1;
	}
    States
    {
    Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
        G0RB E 1900;
	G0RB E -1;
	Stop;
	
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160)); 
       Stop;
    Death:    
    TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
    TNT1 AAAAAAA 0 a_spawnprojectile("named_BloodTr", 0, 0, random(0, 360), 2, random(0, 360));
    TNT1 A 0 a_spawnprojectile("Xdeath1", 0, 0, random(0, 360), 2, random(0, 360));
Stop;}}



CLASS XDeathHellKnightLeg: XDeathArm1 { 
	Default {
 
    Scale 1.1;
    Speed 12;
bounceFactor 0.4;
	Decal "GreenBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		GHKL ABCDEFGH 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		GHKL A 1;
		TNT1 A 0 A_SpawnItem("Gib_HellKnightLeg", 1);
		Stop;
	}
}

CLASS XDeathCyberKnightLeg: XDeathArm1 { 
	Default {
	
	Scale 1.1;
	Speed 12;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		G0RA ABCD 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		G0RA A 1;
		TNT1 A 0 A_SpawnItem("Gib_CyberKnightLeg", 1);
		Stop;
	}
}

CLASS Gib_CyberKnightLeg: LimbBase { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		G0RA A 1900;
		G0RA A -1;
		Stop;
		
	Death:   
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 a_spawnprojectile("BloodMist", 2, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAA 0 a_spawnprojectile("Xdeath1", 2, 0, random(0, 360), 2, random(10, 90));
		TNT1 AAA 0 a_spawnprojectile("Xdeath2", 2, 0, random(0, 360), 2, random(10, 90));
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		G0RA ABCD 4;
		Goto Spawn;
		
	Death.ExplosiveImpact:
Death.Kick: Death.SuperPunches: Death.Melee:
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,40,0,1);
	G0RA ABCD 5 A_CheckFloor("Landz");
	Goto Landz;
Landz:
	XDT5 I 0 A_SpawnItem("Gib_CyberKnightLeg");
Stop;}}

CLASS Gib_HellKnightLeg: LimbBase { 
	Default {
 
    Scale 1.1;
	BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	BloodColor "DarkGreen";
	}
    States
    {
	Spawn:
		GHKL I 1;
		TNT1 A 0 A_QueueCorpse;
		GHKL A 1900;
		GHKL A -1;
	Stop;

	Death:   
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 a_spawnprojectile("PB_blood", 2, 0, random(0, 360), 2, random(0, 360));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 2, 0, random(0, 360), 2, random(10, 90));
		TNT1 A 0 a_spawnprojectile("GenericHKGib1", 2, 0, random(0, 360), 2, random(10, 90));
		TNT1 A 0 a_spawnprojectile("GenericHKGib1", 2, 0, random(0, 360), 2, random(10, 90));
	Stop;

	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		GHKL ABCDEFGH 2;
	Goto Spawn;
	
	Death.ExplosiveImpact:
	Death.Kick: Death.SuperPunches: Death.Melee:
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,40,0,1);
	GHKL A 5;
	GHKL ABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
	Landz:
	XDT5 I 0 A_SpawnItem("Gib_HellKnightLeg");
	Stop;}}





CLASS XDeathHellKnightTorso: XDeathArm1 { 
	Default {
 
    Scale 1.1;
    Speed 12;
bounceFactor 0.4;
	Decal "GreenBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		GHKT ABCDEFGH 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		GHKT I 1;
		HNDC A 0 A_SpawnItem("Gib_HellKnightTorso",0,0,0,1);
		Stop;
	}
}


CLASS XDeathHellKnightHead: XDeathBullArm1 { 
	Default {
	
	-CLIENTSIDEONLY;
	Scale 1.0;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		HKHE ABCDEFGH 6;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		HKHE G 1;
		HKHE G 1 A_SpawnItem("HellKnightHead",0,0,0,1);
		Stop;
	}
}

CLASS XDeathCyberPaladinHead: XDeathBullArm1 { 
	Default {
	
	-CLIENTSIDEONLY;
	Scale 1.0;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		G0RH ABCD 6;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		G0RH E 1;
		G0RH E -1;
		Stop;
	}
}


CLASS KnightXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "GreenBloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 AAAA 0 a_spawnprojectile("MuchBlood", 55, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("WallRedBlood", 32, 0, random(0, 360), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathHellKnightArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHellKnightTorso", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathHellKnightLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath2", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath3", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHellKnightHead", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("GreenSuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
}
}

CLASS BaronXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "GreenBloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 AAAA 0 a_spawnprojectile("MuchBlood", 55, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("WallRedBlood", 32, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathBaronOfHellTorso", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathHellKnightLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath2", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath3", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("GreenSuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
}
}

CLASS CyberNobleXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		TNT1 A 0 a_spawnprojectile("XDeathCyberKnightTorso", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathCyberKnightArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathCyberKnightLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
		
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("SuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
}
}

CLASS CyberXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(70, 90));
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 100, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 AAAAA 0 a_spawnprojectile("XDeathBrain1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("XDeathBrain2", 32, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 A 0 a_spawnprojectile("XDeathCyberdemonHeadPiece", 82, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathCyberdemonGun", 42, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathCyberdemonArm", 36, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathCyberdemonTorso1", 36, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathCyberdemonTorso2", 36, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathCyberdemonTorso3", 36, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathCyberdemonLeg1", 22, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathCyberdemonLeg2", 22, 0, random(0, 360), 2, random(0, 160));
		
		
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 10, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 AAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 25, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 35, 0, random(0, 180), 2, random(0, 180));
		TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("SuperGoreMist", 54, 0, random(0, 360), 2, random(0, 90));
		TNT1 A 0 A_SpawnItem("PB_pot");
	Death:
		TNT1 A 0;
		Stop;
}
}


CLASS HellKnightHeadExplode: ZombieXDeath { 
Default {
	
	Decal "GreenBloodSuper";
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		//TNT1 A 0 a_spawnprojectile("GreenBrainPiece", 0, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("GreenBrainPiece", 0, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("HellKnightHeadPiece", 0, 0, random(0, 360), 2, random(50, 80));
		//TNT1 A 0 a_spawnprojectile("HellKnightHeadPiece2", 0, 0, random(0, 360), 2, random(50, 80));
		//TNT1 AAA 0 a_spawnprojectile("GreenBrainPiece", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		//TNT1 AAAAA 0 a_spawnprojectile("GreenBrainPiece", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("WallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Teeth", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 80));
		TNT1 A 10;
		Stop;
}
}

CLASS HellKnightHeadExplodeHalf: ZombieXDeath { 
Default {
	
	Decal "GreenBloodSuper";
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAA 0 a_spawnprojectile("brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		//TNT1 A 0 a_spawnprojectile("GreenBrainPiece", 0, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("GreenBrainPiece", 0, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("HellKnightHeadPiece2", 0, 0, random(0, 360), 2, random(50, 80));
		//TNT1 AAAAA 0 a_spawnprojectile("GreenBrainPiece", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("WallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAA 0 a_spawnprojectile("Teeth", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 80));
		TNT1 A 10;
		Stop;
}
}


CLASS BaronOfHellHeadExplode: ZombieXDeath { 
Default {
	
	Decal "GreenBloodSuper";
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
//			TNT1 A 0 a_spawnprojectile("GreenBrainPiece", 0, 0, random(0, 360), 2, random(0, 160));
//			TNT1 A 0 a_spawnprojectile("GreenBrainPiece", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("BaronHeadPiece", 62, 0, random(0, 360), 2, random(0, 160));
//			TNT1 AAA 0 a_spawnprojectile("GreenBrainPiece", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
//			TNT1 AAAAA 0 a_spawnprojectile("GreenBrainPiece", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("WallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAA 0 a_spawnprojectile("Teeth", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 80));
		TNT1 A 10;
		Stop;
}
}


//Infernus Leg
CLASS XDeathInfernusLeg : pb_blood_and_gore_base { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.1;
		BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			G0RZ ABCDEFGH 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("PB_blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_InfernusLeg",0,0,0,1);
			Stop;
	}
}

CLASS Gib_InfernusLeg: BigGibBase { 
	Default {
		
		BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
		Scale 1.0;
	}
	States
	{
		Spawn:
			G0RZ A 1;
			G0RZ A -1;
Stop;    }}
	   
//Infernus Arm
CLASS XDeathInfernusArm : pb_blood_and_gore_base { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			G0RX ABCDEFG 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("PB_blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_InfernusArm",0,0,0,1);
			Stop;
	}
}

CLASS Gib_InfernusArm: BigGibBase { 
	Default {
		
		BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
		Scale 1.0;
	}
	States
	{
		Spawn:
			G0RX H 1;
			G0RX H -1;
Stop;    }}
	   
//Infernus Torso
CLASS XDeathInfernusTorso : pb_blood_and_gore_base { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.1;
		BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			G0RW ABCDEFGH 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("PB_blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_InfernusTorso",0,0,0,1);
			Stop;
	}
}

CLASS Gib_InfernusTorso: BigGibBase { 
	Default {
		
		BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
		Scale 1.0;
	}
	States
	{
		Spawn:
			G0RW I 1;
			G0RW I -1;
Stop;    }}
	   
//Infernus Head
CLASS XDeathInfernusHead : pb_blood_and_gore_base { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.1;
		BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			G0RV ABCDEFGH 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("PB_blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_InfernusHead",0,0,0,1);
			Stop;
	}
}

CLASS Gib_InfernusHead: BigGibBase { 
	Default {
		
		BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
		Scale 1.08;
	}
	States
	{
		Spawn:
			G0RV I 1;
			G0RV I -1;
Stop;    }}
	   
//Infernus Torso Upper
CLASS XDeathInfernusUpperTorso : pb_blood_and_gore_base { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.1;
		BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	}
	States
	{
		Spawn:
			BT02 ABC 4;
		Falling:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			BT02 CC 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("PB_blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_InfernusUpperTorso",0,0,0,1);
			Stop;
	}
}

CLASS Gib_InfernusUpperTorso: BigGibBase { 
	Default {
		
		BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
		Scale 1.08;
	}
	States
	{
		Spawn:
			BT02 D 1;
			BT02 D -1;
Stop;    }}
	   
CLASS InfernusXDeath : pb_blood_and_gore_base { 
	Default {
		
		Radius 1;
		Height 1;
		Scale 0.8;
		Speed 0;
		Mass 1;
		Decal "BloodSuper";
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+NOGRAVITY;
		+NOCLIP;
		+DONTSPLASH;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Pain;
			TNT1 A 0 A_FaceTarget;
			
			TNT1 AAAA 0 a_spawnprojectile("WallRedBlood", 40, 0, random(0, 360), 2, random(-15, 15));
			TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
			TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
			TNT1 AAAA 0 a_spawnprojectile("XDeath2", 15, 0, random(0, 360), 2, random(0, 160));
			TNT1 AAAA 0 a_spawnprojectile("XDeath3", 15, 0, random(0, 360), 2, random(0, 160));
			//TNT1 AAA 0 a_spawnprojectile("Green_Instestin", 24, 0, random(0, 360), 2, random(0, 160));
			TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
			TNT1 AA 0 a_spawnprojectile("XDeathInfernusArm", 32, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("XDeathInfernusTorso", 48, 0, random(0, 360), 2, random(0, 160));
			TNT1 AA 0 a_spawnprojectile("XDeathInfernusLeg", 32, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 A_SpawnItem("PB_pot");
			TNT1 A 1;
			TNT1 A 2;
			TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
			Stop;
		LowBlood:
			TNT1 A 2;
			Stop;
		LotsOfBlood:
			TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
			TNT1 AAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
			Stop;
		AbsurdBlood:
			TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
			TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("GreenSuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
			TNT1 AAAAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
			Stop;
	}
}


