
CLASS DeadSkeleton: pb_blood_and_gore_base { 
Default {
	Radius 4;
	Height 18;
	Scale 1.0;
	+SHOOTABLE;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CORPSE;
	+FLOORCLIP;
	-SOLID;
	+NORADIUSDMG;
	damagefactor "Crusher", 50.0;
	Mass 1000;
	Health 200;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	damagefactor "Saw", 0.3;
	bloodtype "RevenantBlood";
}
States
{
	Spawn:
		SKEL Q -1;
	Stop;
	
	Raise:
		SKEL Q 5;
		SKEL PONML 5;
		TNT1 A 0 A_SpawnItem("pb_Revenant", 3);
	Stop;

	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 7, 0, random(0, 360), 2, random(30, 150));
		TNT1 AAA 0 a_spawnprojectile("RevenantBones", 7, 0, random(0, 360), 2, random(30, 150));
		TNT1 AA 0 a_spawnprojectile("RevenantArm", 7, 0, random(0, 360), 2, random(30, 150));
		TNT1 A 0 a_spawnprojectile("GibHalfSkeleton", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("XDeadSkeleton", 1);
	Stop;

	Death.flames:
	Death.burn:
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL AAAAAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		CARB NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN 10 a_spawnprojectile("Explosion_Smoke", 1, 0, random(0, 360), 2, random(0, 160));
		CARB N -1;
	Stop;
	
	Death.Cut:
	Death.Saw:
		TNT1 A 0;
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 7, 0, random(0, 360), 2, random(30, 150));
		TNT1 AAA 0 a_spawnprojectile("RevenantBones", 7, 0, random(0, 360), 2, random(30, 150));
		TNT1 AA 0 a_spawnprojectile("RevenantArm", 7, 0, random(0, 360), 2, random(30, 150));
		TNT1 A 0 a_spawnprojectile("GibHalfSkeleton", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("XDeadSkeleton", 1);
	Stop;
}}

CLASS NotDeadSkeleton: DeadSkeleton { 
	Default {
 Health 50; 
Damagefactor "Kick", 50.0;
	-THRUACTORS;
	-CORPSE;
	Radius 1;
	}
	States{Spawn:
	SKEL Q 500;
	SKEL PONML 5;
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_fall();
	TNT1 A 0 A_SpawnItem("pb_Revenant", 3);
	TNT1 A 1;
	//TNT1 A 0 A_SpawnItem("KillMe");
	Stop;
}}


CLASS DeadSkeletonNoHead: DeadSkeleton { 
	Default {
	Health 200;
	+SHOOTABLE;
	Radius 4;
	Height 18;
	}
States{
	Spawn:
	REVH D 1;
	REVH D -1;
Stop; }}

CLASS XDeadSkeleton: DeadSkeleton { 
	Default
{Health 200;} States{Spawn:
	DKEL I -1;
	Stop;
Death.Cutless:        Death.Cut: Death: Death.Saw:
	TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
Stop;}}
	
	
	
CLASS DeadSkeletonSKL5E: DeadSkeleton { 
	Default
{Health 200;} States{Spawn:
	SKL5 E -1;
        Stop;    
       Death.Cutless:	        Death.Cut: Death: Death.Saw:
  	    	 TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
	Stop;}}
	
	
CLASS DeadSkeletonSKL5J: DeadSkeleton { 
	Default
{Health 200;} States{Spawn:
	SKL5 J -1;
        Stop;    
       Death.Cutless:	        Death.Cut: Death: Death.Saw:
  	    	 TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
	Stop;}}
	
	
CLASS DeadSkeletonSKL8L: DeadSkeleton { 
	Default 
{Health 200;} States{Spawn:
	SKL8 L -1;
        Stop;    
       Death.Cutless:	        Death.Cut: Death: Death.Saw:
  	    	 TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
	Stop;}}	
	
CLASS DeadSkeletonSKL9H: DeadSkeleton { 
	Default 
{Health 200;} States{Spawn:
	SKL9 H -1;
        Stop;    
       Death.Cutless:	        Death.Cut: Death: Death.Saw:
  	    	 TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
	Stop;}}
	
CLASS DeadSkeletonSKL9K: DeadSkeleton { 
	Default
{Health 200;} States{Spawn:
	SKL9 K -1;
        Stop; 
       Death.Cutless:	        Death.Cut: Death: Death.Saw:
  	    	 TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
	Stop;}}	

	
CLASS RevenantPiece : ACTOR { 
Default {
    Radius 2;
    Height 2;
    Speed 7;
	Mass 3;
	BounceFactor 0.4;
	BounceCount 4;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+THRUACTORS;
	Scale 0.4;
}
States
{
	Spawn:
		TNT1 A 0 A_Jump(128,9);
		SPIC ABCDEFGH 2;
	wait;
		SPIC HGFEDCBA 2;
	wait;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128,2);
		SPIC A 401;
	Stop;
		SPIC E 1;
		SPIC E 401;
	Stop;
	}
}


CLASS RevenantDust: RevenantPiece { 
	Default {
	
	Speed 10;
	BounceFactor 0.3;
	Scale 0.6;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		SPIC I 5;
		Loop;
	Death:
		TNT1 A 0;
		SPIC I 401;
	Stop;
	}
}


CLASS RevenantDust2: RevenantDust { 
	Default {
	
	Speed 8;
	BounceFactor 0.2;
	Scale 0.3;
	}
}

CLASS RevenantBlood : Blood { 
	Default {
	
	Decal "BrutalBloodSplat";
	
	+FORCEXYBILLBOARD;
	+GHOST;
	+NOBLOCKMAP;
	+NOGRAVITY;
	+NOCLIP;
	-DONTSPLASH;
	-ALLOWPARTICLES;
	Speed 0;
	}
	states
	{
	Spawn:
		TNT1 A 0;
		TNT1 AAAAA 0 a_spawnprojectile("named_BloodTr", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("RevenantDust", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("RevenantDust2", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
		TNT1 A 0 a_spawnprojectile("Brutal_FlyingBlood", 7, 0, random(0, 360), 2, random(30, 150));
		TNT1 A 0 a_spawnprojectile("RevenantPiece", 7, 0, random(0, 360), 2, random(30, 150));
		TNT1 A 0 A_SpawnItem("BloodHit");
		BLOD BCD 0;
	Stop;
		
	Splash:
		BLOD A 0;
		TNT1 AAA 0 a_spawnprojectile("Underblood1", 7, 0, random(0, 360), 2, random(30, 150));
	Stop;
	}
}




CLASS RevenantBones: RevenantPiece { 
	Default {
	
	Speed 9;
	BounceFactor 0.3;
	Scale 1.0;
	}
	States
	{
	Spawn:
		BNP1 ABCDEFGH 4;
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		Loop;
	Death:
		TNT1 A 0;
		BNP1 A 4000;
	Stop;
	}
}


CLASS RevenantBonesFast: RevenantPiece { 
	Default {
	
	Speed 14;
	BounceFactor 0.3;
	Scale 1.0;
	}
	States
	{
	Spawn:
		BNP1 ABCDEFGH 4;
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		Loop;
	Death:
		TNT1 A 0;
		BNP1 A 4000;
	Stop;
	}
}





CLASS RevenantArm: RevenantPiece { 
	Default {
	
	Speed 10;
	BounceFactor 0.1;
	Scale 1.0;
	}
	States
	{
	Spawn:
		BNP2 ABCDEFGH 4;
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		Loop;
	Death:
		TNT1 A 0;
		BNP2 A 4000;
	Stop;
	}
}


CLASS RevenantTorso5: RevenantPiece { 
	Default {
	
	Speed 5;
	BounceFactor 0.2;
	Scale 1.0;
	}
	States
	{
	Spawn:
		BNP3 ABCD 8;
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		Loop;
	Death:
		TNT1 A 0;
		BNP3 A -1;
	Stop;
	}
}

CLASS RevenantTorso6: RevenantPiece { 
	Default {
	
	Speed 5;
	BounceFactor 0.2;
	Scale 1.0;
	}
	States
	{
	Spawn:
		BNP4 ABCD 8;
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		Loop;
	Death:
		TNT1 A 0;
		BNP4 D -1;
	Stop;
	}
}




CLASS RevenantU : ACTOR { 
	Default {
	
	GibHealth 45;
	Health 150;
	Monster;
	MeleeThreshold 196;
	+FLOORCLIP;
	+MISSILEMORE;
	Speed 6;
	damagefactor "Crush", 10.0;
	damagefactor "Plasma", 0.5;
	damagefactor "MinorHead", 1.2;
	damagefactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	damagefactor "Head", 1.2;
	PainChance "Kick", 255;
	BloodType "RevenantBlood";
	SeeSound "skeleton/sight";
	PainSound "skeleton/pain";
	DeathSound "skeleton/death";
	ActiveSound "skeleton/active";
	MeleeSound "skeleton/melee";
	HitObituary "$OB_UNDEADHIT";
	Obituary "$OB_UNDEAD";
	damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0; damagefactor "GreenBlood", 0.0;
	MaxStepHeight 24;
	+NOPAIN;
	+LOOKALLAROUND;
	+NOTARGET;
	MaxDropOffHeight 32;
	Radius 20;
	Height 40;
	}
	States
	{
	Spawn:
		UKEL A 6 A_Look();
		Loop;
		
	See:
		UKEL AAABBBCCC 2 A_chase(null,null);
		UKEL CDDD 2 A_Chase();
		Loop;
		
	Missile:
		UKEL E 10 A_FaceTarget();
		TNT1 A 0 A_Jump(128, "Missile2");
		UKEL F 10 a_spawnprojectile("RevenantBalls",20,15,0,0);
	Goto See;
		
	Missile2:
		UKEL E 1 A_FaceTarget();
		UKEL F 10 a_spawnprojectile("RevenantBalls",20,-15,0,0);
	Goto See;
		
		
	Death:
		TNT1 AAA 0 a_spawnprojectile("RevenantDust", 5, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAA 0 a_spawnprojectile("RevenantDust2", 5, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("RevenantHead", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(30, 150));
		TNT1 AA 0 a_spawnprojectile("RevenantBones", 5, 0, random(0, 360), 2, random(30, 150));
		TNT1 AA 0 a_spawnprojectile("RevenantArm", 5, 0, random(0, 360), 2, random(30, 150));
		TNT1 AA 0 a_spawnprojectile("MetalShard1", 5, 0, random(0, 360), 2, random(30, 160));
		TNT1 AA 0 a_spawnprojectile("MetalShard1", 5, 0, random(0, 360), 2, random(30, 160));
		TNT1 AA 0 a_spawnprojectile("MetalShard1", 5, 0, random(0, 360), 2, random(30, 160));
		TNT1 AAA 0 a_spawnprojectile("RevenantBonesFast", 5, 0, random(0, 360), 2, random(30, 150));
		TNT1 AAA 0 a_spawnprojectile("RevenantPiece", 5, 0, random(0, 360), 2, random(30, 150));
 		TNT1 A 0 A_SpawnItem("HellishMissileLauncher");
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Scream();
		TNT1 A 10;
	Stop;
		
		
	Pain.KillMe:
	Pain.Taunt:
		TNT1 A 0;
	Goto Missile;
	Death.KillMe:
	Death.Taunt:
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 A_SpawnItem("RevenantU");
	Stop;
	}
}

CLASS RevenantSeeker : ACTOR 
{ 
Default
{
	//SpawnID 53;
	Radius 11;
	Height 8;
	Speed 11;
	FastSpeed 15;
	DamageFunction 2;
	PROJECTILE;
	+THRUGHOST;
	+SEEKERMISSILE;
	+FORCEXYBILLBOARD;
	Scale 1.0;
	damagetype "ExplosiveImpact";
	SeeSound "skeleton/attack";
	DeathSound "LightExplosion";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_PlaySound("weapons/rocketloop",6,1,1);
	Fly:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
		FATB AB 1 BRIGHT A_SpawnItem("Red_FlareSmall",0,0);
		TNT1 A 0 A_SeekerMissile(4,8);
		TNT1 A 0 A_SpawnItemEx("RevenantProjectileTrails", 0, 0, 0, 0, 0, 0, 0, 128);
		TNT1 A 0 A_SpawnItem("ExplosionSmoke");
		Loop;
		
		
	SpawnUnderwater:
		FATB A 1 BRIGHT A_SpawnItem("Red_FlareSmall",0,0);
		TNT1 A 0 A_SeekerMissile(4,8);
		TNT1 A 0 a_spawnprojectile("underwater_bubles", 0, 0, random(0, 360), 2, random(0, 180));
		FATB B 1 BRIGHT A_SpawnItem("Red_FlareSmall",0,0);
		TNT1 A 0 a_spawnprojectile("underwater_bubles", 0, 0, random(0, 360), 2, random(0, 180));
	Goto Spawn;
		
		
	Death:
		TNT1 A 0 A_StopSound(6);
		EXPL A 0 Radius_Quake(2, 54, 0, 15, 0);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		BFE1 A 0 Bright A_Explode(7, 120, 1);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
		EXPL A 0;
		TNT1 AAAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 10;
	Stop;
	}
}

CLASS RevenantSeeker2 : RevenantSeeker
{ 
Default
{
	Damage 17;
	SeeSound "HMLF1";
}

States
{
	Death:
		TNT1 A 0 A_StopSound(6);
		EXPL A 0 Radius_Quake(2, 54, 0, 15, 0);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		BFE1 A 0 Bright A_Explode(15, 120, 1);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
		EXPL A 0;
		TNT1 AAAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 10;
	Stop;
	}
}

CLASS RevenantSeeker3 : RevenantSeeker { 
	Default {
	
	Damage 17;
	SeeSound "HMLF2";
	}
	States
	{
	Death:
		TNT1 A 0 A_StopSound(6);
		EXPL A 0 Radius_Quake(2, 54, 0, 15, 0);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		BFE1 A 0 Bright A_Explode(15, 120, 1);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
		EXPL A 0;
		TNT1 AAAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 10;
	Stop;
	}
}



CLASS DyingRevenantNoArm : ACTOR { 
Default {
	Radius 18;
	Height 24;
	Speed 9;
	Health 40;
	PainSound "skeleton/pain";
	DeathSound "skeleton/death";
	+SHOOTABLE;
	+FLOORCLIP;
	+LOOKALLAROUND;
	+FRIGHTENED;
	+SOLID;
	+FLOORCLIP;
	DamageFactor "Kick", 6.0;
	DamageFactor "SuperKick", 6.0;
	DamageFactor "ExtremePunches", 6.0;
	DamageFactor "trample", 2.0;
	DamageFactor "bloodsplasher", 0.0; DamageFactor "tinybloodsplasher", 0.0;
	DamageFactor "superbloodsplasher", 0.0; DamageFactor "smallbloodsplasher", 0.0;
	PainChance "Kick", 255;
	PainChance "SuperKick", 255;
	DamageFactor "Leg", 0.0;
	DamageFactor "BlueBloodSplasher", 0.0;
	DamageFactor "BlueSuperBloodSplasher", 0.0;
}

States
{
	Spawn:
		SKL9 CDED 7
		{
			if(frame == 2) A_PlaySound("skeleton/pain");
			a_spawnprojectile("Brutal_LiquidBlood2", 20, 12, random(0, 360), 2, random(0, 160));
		}
		tnt1 a 0 a_jumpif(random(0, 10) < 7, "spawn");
	Collapse:
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_PlaySound("skeleton/death");
		SKL9 FG 7 a_spawnprojectile("pb_blood", 15, 0, random(0, 360), 2, random(0, 160));
		SKL9 H 1 A_SpawnItem("DeadSkeletonSKL9H");
	Stop;
		
	Death.head:
	Death.minorhead:
		//TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAAA 0 a_spawnprojectile("Xdeath1", 72, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("BloodMist", 70, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SmallLSPart1", 70, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAA 0 a_spawnprojectile("LSpart1", 72, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_NoBlocking();
		SKL9 IJ 8;
		TNT1 A 0 A_PlaySound("skeleton/death");
		SKL9 K 1 A_SpawnItem("DeadSkeletonSKL9K");
	Stop;
		
	Crush:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		R3V9 K -1;
	Stop;
		
	Death.Plasma: Death.Plasma2:
	TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		XBRN AA 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
		TNT1 AAAA 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 A_SpawnItem("CrueltyBonus5Armor");
		XBRN BB 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
		TNT1 A 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
		XBRN CC 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
		TNT1 AAAAAAAA 0 a_spawnprojectile("PlasmaParticleX", 48, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0;
	Stop;
}
}


CLASS DyingRevenantNoChest : ACTOR { 
Default
{
	Radius 24;
	Height 24;
	Speed 9;
	Health 80;
	PainSound "skeleton/pain";
	DeathSound "skeleton/death";
	+SHOOTABLE;
	+LOOKALLAROUND;
	+FRIGHTENED;
	+SOLID;
	+FLOORCLIP;

	DamageFactor "Kick", 6.0;
	DamageFactor "ExtremePunches", 6.0;
	DamageFactor "SuperKick", 6.0;
	DamageFactor "trample", 2.0;
	DamageFactor "bloodsplasher", 0.0;
	DamageFactor "tinybloodsplasher", 0.0;
    DamageFactor "superbloodsplasher", 0.0;
	DamageFactor "smallbloodsplasher", 0.0;
	DamageFactor "Leg", 0.0;
	DamageFactor "BlueBloodSplasher", 0.0;
	DamageFactor "BlueSuperBloodSplasher", 0.0;

	PainChance "Kick", 255;
	PainChance "SuperKick", 255;
}

States
{	
	Spawn:
		SKL4 DF 10
		{
			if(frame == 3) A_PlaySound("skeleton/pain");
			a_spawnprojectile("Brutal_LiquidBlood3", 10, 12, random(0, 360), 2, random(0, 160));
		}
		tnt1 a 0 a_jumpif(random(0, 10) < 7, "Spawn");	
	Collapse:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_PlaySound("skeleton/death");
		SKL4 EEEEEEEEEEEEEEEEEEEEEEE 3 a_spawnprojectile("Brutal_LiquidBlood3", 9, 0, random(0, 360), 2, random(0, 160));
		SKL4 E -1;
		Stop;
		
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		XBRN AA 0 BRIGHT A_SpawnItem("Blue_Flare",0,43);
		TNT1 AAAA 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 A_SpawnItem("CrueltyBonus5Armor");
		TNT1 A 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("PlasmaParticleX", 48, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("PlasmaParticleX", 42, 0, random(0, 360), 2, random(0, 360));
		RVDP GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG 10 a_spawnprojectile("Explosion_Smoke", 1, 0, random(0, 360), 2, random(0, 160));
		RVDP G -1;
		Stop;
		
	Death:
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 30, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("RevenantDust", 30, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAA 0 a_spawnprojectile("RevenantDust2", 30, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 37, 0, random(0, 360), 2, random(30, 150));
		TNT1 AAAA 0 a_spawnprojectile("RevenantBones", 37, 0, random(0, 360), 2, random(30, 150));
		TNT1 AAAAAAA 0 a_spawnprojectile("RevenantPiece", 37, 0, random(0, 360), 2, random(30, 150));
 		TNT1 A 0 A_SpawnItem("HellishMissileLauncher");
		TNT1 AA 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0;
		SKL4 G -1;
	Stop;
}
}


CLASS BigBlastedRevenant : ACTOR
{ 
Default
{
	Radius 16;
	Height 58;
	Health 50;
	BloodType "pb_blood", "BloodSPlatterReplacer", "AxeBlood";
	PainSound "null";
	PainChance 255;
	Mass 999999;
	-SOLID
	+SHOOTABLE
	+NORADIUSDMG
	+FLOORCLIP
	+DONTSPLASH
	+FRIENDLY//
	Scale 1.0;
}

States
{		
	Spawn:
	TNT1 A 0;
        TNT1 A 0 A_PlaySound("misc/xdeath2c");
		SKL8 FFFHHHGGG 2 a_spawnprojectile("Bloodmist", 58, 0, random(0, 360), 2, random(10, 90));
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		SKL8 HHHFFFHHH 2 a_spawnprojectile("Bloodmist", 58, 0, random(0, 360), 2, random(10, 90));
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		SKL8 GGGHHHFFF 2 a_spawnprojectile("Bloodmist", 58, 0, random(0, 360), 2, random(10, 90));
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		SKL8 HHHGGGHHH 2 a_spawnprojectile("Bloodmist", 58, 0, random(0, 360), 2, random(10, 90));
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		SKL8 FFFHHHGGGHHH 2 a_spawnprojectile("Bloodmist", 58, 0, random(0, 360), 2, random(10, 90));
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
    DieNow:
		SKL8 I 8;
		SKL8 JJJJJJJ 2 a_spawnprojectile("Brutal_LiquidBlood2", 45, 0, random(0, 360), 2, random(10, 90));
		SKL8 K 6;
		TNT1 A 0 A_PlaySound("BODYF");
		SKL8 L 6;
		TNT1 A 0 A_SpawnItem("DeadSkeletonSKL8L");
	Stop;
	
	Death:
	    TNT1 AAA 0 a_spawnprojectile("XDeath1", 30, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("RevenantDust", 30, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAA 0 a_spawnprojectile("RevenantDust2", 30, 0, random(0, 360), 2, random(0, 360));
        TNT1 AA 0 a_spawnprojectile("XDeath2", 47, 0, random(0, 360), 2, random(30, 150));
        TNT1 A 0 a_spawnprojectile("XDeath4", 47, 0, random(0, 360), 2, random(30, 150));
        TNT1 AAA 0 a_spawnprojectile("XDeath3", 37, 0, random(0, 360), 2, random(30, 150));
		TNT1 AAAAA 0 a_spawnprojectile("MetalShard1", 50, 0, random(0, 360), 2, random(30, 160));
		TNT1 AAAA 0 a_spawnprojectile("MetalShard1", 50, 0, random(0, 360), 2, random(30, 160));
		TNT1 AAAAA 0 a_spawnprojectile("MetalShard1", 50, 0, random(0, 360), 2, random(30, 160));
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 46, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAA 0 a_spawnprojectile("RevenantBones", 37, 0, random(0, 360), 2, random(30, 150));
		TNT1 AAAAAAA 0 a_spawnprojectile("RevenantPiece", 37, 0, random(0, 360), 2, random(30, 150));
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_XScream();
	    SKEX AAAAAAAAAAAAAAAA 2 a_spawnprojectile("Brutal_LiquidBlood2", 20, 12, random(0, 360), 2, random(0, 160));//A_SpawnItem("RevenantU", 0, 40)
		SKEX BCDE 4;
        TNT1 A 0 A_SpawnItem("GibHalfSkeletonJustLegs", 1);
    Stop;
}

}


CLASS RoamingLegs : ACTOR { 
	Default {
	
	Radius 8;
	Height 32;
	Speed 5;
	Health 80;
	BloodType "RevenantBlood";
	+SHOOTABLE;
	+FLOORCLIP;
	+LOOKALLAROUND;
	}
    States
    {
	Spawn:
		DKEL AABBCCDD 2
		{
			A_Wander();
			a_spawnprojectile("Brutal_FlyingBlood", 42, 0, random(170, 190), 2, random(0, 40));
		}
		tnti a 0 a_jumpif(random(0, 10) < 8, "spawn");
	Death:
		TNT1 A 0 A_NoBlocking();
		DKEL EFGHI 4;
		TNT1 A 0 A_SpawnItem("XDeadSkeleton", 1);
	Stop;

	Death.Shotgun:
	Death.Cutless:
	XDeath:
		TNT1 AAAA 0 a_spawnprojectile("RevenantBones", 37, 0, random(0, 360), 2, random(30, 150));
		TNT1 AAAAAAA 0 a_spawnprojectile("RevenantPiece", 37, 0, random(0, 360), 2, random(30, 150));
	Stop;

	Crush:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS2 A 5;
		CRS2 A -1;
	Stop;
}
}

