
CLASS dead_knight : actor
{ 
Default
{
	Radius 24;
	Height 12;
	Scale 1.0;
	+SHOOTABLE;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CORPSE;
	+FLOORCLIP;
	-SOLID;
	+THRUACTORS;
	damagefactor "Crusher", 50.0;
	Mass 1000;
	Health 200;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	BloodType "Green_Blood", "GreenAxeBlood", "GreenAxeBlood";
}

States
{
	Spawn:
		HKDD D -1;
	Stop;

	Death.Plasma: Death.Plasma2:
	Death.Flames:
	Death.Burn:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		EXPL AAAAA 0 A_SpawnProjectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		BOSB ABCDE 9 A_SpawnProjectile("ExplosionSmoke", 24, 0, random(0, 180), 2, random(0, 180));
		BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 8 A_SpawnProjectile("ExplosionSmoke", 16, 0, random(0, 180), 2, random(0, 180));
		BOSB E -1;
	Stop;
	
	Death:
		TNT1 AAAA 0 A_SpawnProjectile("Bloodmist", 9, 0, random(0, 360), 2, random(30, 90));
		//TNT1 AAA 0 ;//pb_spawn_blood_color(green, "XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 A_SpawnProjectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 A_SpawnProjectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 A_SpawnProjectile("Xdeath4", 5, 0, random(0, 360), 2, random(0, 160));
		KSA6 O -1;//death handler
	Stop;
}

}