//fatality
CLASS RapedHK : dead_knight
{ 
States
{
	Spawn:
		HKF1 I -1;
	Stop;
}

}

CLASS OmgSoDeadHK : dead_knight
{ 
States
{
	Spawn:
		HKF2 O -1;
	Stop;
}

}

CLASS NoArmNoHeadFatalizedHK: dead_knight { 
States{Spawn:  
HKF3 JKLM 5;       
HKF3 N -1;        
Stop;}}

CLASS Dead_HellKnightFatality4 : dead_knight
{ 
States
{
	Spawn:
		KAD1 FFFFFFFFFFFFFFFFFFF 15 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
		KAD1 FFFFF 1 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
		KAD1 F -1;
	Stop;
}

}






































CLASS Dying_Hell_Knight : ACTOR
{ 
Default
{
	Radius 16;
	Height 30;
	Speed 9;
	Health 70;
	PainSound "PSXDPN";
	DeathSound "knight/death";
	damagefactor "Kick", 0.1;
	damagefactor "Crush", 2.0;
	damagefactor "Fatality", 20.1;
	PainChance "Kick", 255;
	+SHOOTABLE;
	+FLOORCLIP;
	+LOOKALLAROUND;
	+FRIGHTENED;
	+FLOORCLIP;
	-SOLID;
	+THRUACTORS;
	+NOBLOODDECALS;
	BloodType "Green_Blood", "GreenAxeBlood", "GreenAxeBlood";
}

States
{
	Spawn:
		tnt1 a 0 {self.bsolid = true; self.bthruactors = false;}
	See:
		BTC1 ABCD 10
		{
			A_Chase();
			if(frame == 2)
			{
				A_SpawnItemEx("brutal_LiquidBlood", 0, 0, 10, 0, 0);
				A_Pain();
			}
		}
		tnt1 a 0 a_jumpif(random(0, 10) > 7, "death");
	Loop;

	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Pain();
		BTO1 D -1;
	Stop;
			


	Pain.Kick:
		TNT1 A 0 A_SpawnProjectile("Teeth", 30, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 ;//pb_spawn_blood_color(green, "FlyingBlood", 30, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnProjectile("TeethNoBounce", 30, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 A_SpawnItem("CrueltyBonus1health");
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_FaceTarget();
		BTCK ABA 3;
		BTC1 B 20;
	Goto See;
			
	Death.Kick:
	Death.Fatality:
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("HKFatality2", 1);
		TNT1 A 0 A_NoBlocking();
	Stop;
			
			
			
	Death.Stomp:
	Death.SSG:
	XDeath:
		//TNT1 AAAAAA 0 bright ;//pb_spawn_blood_color(green, "XDeath1", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright A_SpawnProjectile("XDeath2", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright A_SpawnProjectile("XDeath3", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 A 1;
		TNT1 A 1 A_XScream();
		TNT1 A 1 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("GibsZ",0,0,0,1);
		TNT1 AAA 0 A_SpawnItem("CrueltyBonus5Health");
	Stop;
}

}





//fatality ends


CLASS StopKickingMyBallsMotherFucker : Inventory
{ 
Default {inventory.maxamount 1;}
}











CLASS XDeathHalfHK : ACTOR
{ 
Default
{
	+FLOORCLIP;
    Radius 0;
    Height 8;
    Speed 10;
	Mass 8;
	BounceFactor 0.3;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/XDeath1";
}

States
{
	Spawn:
		BTO1 AABBCC 4 A_SpawnProjectile("PB_Blood",0,0,180,2);
		TNT1 A 0 A_Jump(128, "Crawl");
		BTO1 D -1;
	Stop;

	Crawl:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("Dying_Hell_Knight");
		TNT1 A 0;
	Stop;
}

}





























CLASS Gib_PinnedHellKnightTorso: dead_knight
{ 
States{	
	Spawn:
		BTO1 E -1;
	Stop;
		
	Death:
		//TNT1 AAAAAA 0 bright ;//pb_spawn_blood_color(green, "XDeath1", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright A_SpawnProjectile("XDeath2", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright A_SpawnProjectile("XDeath3", 55, 0, random(0, 360), 2, random(30, 180));
		//TNT1 A 0 A_SpawnItem("GibsZ",0,0,0,1);
	Stop;
}

}

CLASS Pinned_Hell_Knight_Torso : ACTOR
{ 
Default
{
	Radius 4;
	Height 4;
	Speed 20;
	Scale 1.1;
	Mass 15;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+RIPPER;
	+BLOODLESSIMPACT;
	-DONTSPLASH;
	+THRUGHOST;
	+THRUACTORS;
	+FLOORCLIP;
	+NOGRAVITY;
	damagetype "Blood";
	SeeSound "misc/xdeath4";
	DeathSound "misc/xdeath1";
	Decal "GreenBloodSplat";
	BloodType "Green_Blood", "GreenAxeBlood", "GreenAxeBlood";
}

States
{
	Spawn:
		TNT1 A 0 A_FaceTarget();
		BTO1 E 4 A_SpawnProjectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		TNT1 A 0 A_CheckFloor("HitTheFloor");
	Loop;
		
	Death:
	PinToWall:
		BTO1 F 3 A_SpawnProjectile("brutal_LiquidBlood", 19, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0;
		BTO1 F 3 A_SpawnProjectile("brutal_LiquidBlood", 19, 0, random(0, 360), 2, random(30, 60));
		
		TNT1 A 0 A_CheckFloor("HitTheFloor");
		BTO1 F 3 A_SpawnProjectile("brutal_LiquidBlood", 19, 0, random(0, 360), 2, random(30, 60));
		
		TNT1 A 0 A_CheckFloor("HitTheFloor");
		BTO1 F 3 A_SpawnProjectile("brutal_LiquidBlood", 19, 0, random(0, 360), 2, random(30, 60));
		
		TNT1 A 0 A_CheckFloor("HitTheFloor");
		BTO1 F 3 A_SpawnProjectile("brutal_LiquidBlood", 19, 0, random(0, 360), 2, random(30, 60));
		
		TNT1 A 0 A_CheckFloor("HitTheFloor");
		BTO1 F 3 A_SpawnProjectile("brutal_LiquidBlood", 19, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_CheckFloor("HitTheFloor");
	Pinned:
		TNT1 A 0 A_Recoil(6);
		BTO1 F 4;
		TNT1 A 0 A_CheckFloor("HitTheFloor");
		TNT1 A 0 A_JumpIf(vel.x < 0, "HitTheFloor");
		TNT1 A 0 A_JumpIf(vel.y < 0, "HitTheFloor");
		TNT1 A 0 A_JumpIf(vel.x > 0, "HitTheFloor");
		TNT1 A 0 A_JumpIf(vel.y > 0, "HitTheFloor");
	Loop;
		
	HitTheFloor:
		TNT1 A 0 A_SetFloorClip;
		BTO1 E -1;
	Stop;
}

}



CLASS Brutalized_HellKnight1 : ACTOR
{ 
Default
{	
	Radius 18;
	Height 54;
	Speed 9;
	Health 110;
	PainSound "PSXDPN";
	DeathSound "knight/death";
	damagefactor "Kick", 0.1;
	damagefactor "Crush", 2.0;
	damagefactor "Fatality", 20.1;
	PainChance "Kick", 255;
	+SHOOTABLE;
	+FLOORCLIP;
	+LOOKALLAROUND;
	+FRIGHTENED;
	+FLOORCLIP;
	-SOLID;
	+THRUACTORS;
	+NOBLOODDECALS;
	BloodType "Green_Blood", "GreenAxeBlood", "GreenAxeBlood";
}

States
{
	Spawn:
		tnt1 a 0 {self.bsolid = true; self.bthruactors = false;}
		KSA2 A 1 A_Look();
	See:
		KSA2 ACABACAB 7
		{
			if(frame == 2) a_pain();
			A_SpawnProjectile("brutal_LiquidBlood", 35, -15, random(0, 360), 2, random(30, 60));
			A_SpawnItemEx("brutal_LiquidBlood", 40, -10, 10, 0, 0);
		}
	Die:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Scream();
		KSA2 DEF 7;
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		//TNT1 A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");
		KSA2 G -1;//death handler
	Stop;
		
	Death:
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Pain();
		//TNT1 A 0 ;//pb_spawn_blood_color(green, "FlyingBlood", 38, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 A_SpawnProjectile("Bloodmist", 45, 0, random(0, 360), 2, random(0, 160));
		//TNT1 AAA 0 ;//pb_spawn_blood_color(green, "XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnProjectile("XdeathHellKnightArm", 55, 10, random(0, 360), 2, random(0, 160));
		KSA3 A 1 A_SpawnItem("BrutalizedHellKnight");
	Stop;
		
		
	Death.Stomp:
	Death.SSG:
	XDeath:
		TNT1 A 0 A_SpawnItem("GibsZ",0,0,0,1);
		TNT1 A 0 A_SpawnProjectile("KnightXDeath", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 A_SpawnItem("CrueltyBonus5Health");
	Stop;
}

}


CLASS BrutalizedHellKnight : Brutalized_HellKnight1
{ 
States
{	
	Spawn:
		tnt1 a 0 {self.bsolid = true; self.bthruactors = false;}
		KSA3 A 1 A_Look();
	See:
		KSA3 ACABACAB 7
		{
			if(frame == 2) a_pain();
			A_SpawnProjectile("brutal_LiquidBlood", 35, -15, random(0, 360), 2, random(30, 60));
			A_SpawnItemEx("brutal_LiquidBlood", 40, -10, 10, 0, 0);
		}

	Die:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Scream();
		KSA3 DEF 7;
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		//TNT1 A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");
		KSA3 G -1;//death handler
	Stop;
		
	Death:
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 A 0 A_SpawnItem("noble_head_explosion", 0, 62);
		TNT1 AA 0 A_SpawnProjectile("Bloodmist", 55, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 ;//pb_spawn_blood_color(green, "FlyingBlood", 38, 0, random(0, 360), 2, random(0, 160));
		//TNT1 AA 0 ;//pb_spawn_blood_color(green, "XDeath1", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		KSA3 A 1 A_SpawnItem("BrutalizedHellKnight3");
	Stop;
		
		
	Death.Stomp:
	Death.SSG:
	XDeath:
		TNT1 A 0 A_SpawnItem("GibsZ",0,0,0,1);
		TNT1 A 0 A_SpawnProjectile("KnightXDeath", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 A_SpawnItem("CrueltyBonus5Health");
	Stop;
}

}


CLASS BrutalizedHellKnight3 : Brutalized_HellKnight1
{ 
States
{	
	Spawn:
		TNT1 A 0 nodelay {self.BSOLID = true; self.bTHRUACTORS = false;}
		KSA4 A 1 A_Look();
	See:
		KSA4 ACABACAB 7
		{
			if(frame == 2) a_pain();
			A_SpawnProjectile("brutal_LiquidBlood", 35, -15, random(0, 360), 2, random(30, 60));
			A_SpawnItemEx("brutal_LiquidBlood", 40, -10, 10, 0, 0);
		}
	Die:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		KSA4 DEF 7;
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		//TNT1 A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");
		KSA4 G -1;//death handler
	Stop;
		
	Death:
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_XScream();
		//TNT1 AAA 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 AAAA 0 A_SpawnProjectile("Bloodmist", 45, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 ;//pb_spawn_blood_color(green, "XDeath1", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 A_SpawnProjectile("XDeath2", 39, 0, random(130, 210), 2, random(0, 40));
		TNT1 AAA 0 A_SpawnProjectile("XDeath3", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 A_SpawnProjectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 ;//pb_spawn_blood_color(green, "FlyingBlood", 48, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		KSA6 AAAAA 2 A_SpawnProjectile("brutal_LiquidBlood", 55, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");
		KSA6 BCDE 6 A_SpawnProjectile("brutal_LiquidBlood", 25, -4, random(0, 360), 2, random(30, 60));
		KSA6 E -1;//death handler
	Stop;
		
	Death.Stomp:
	Death.SSG:
	XDeath:
		TNT1 A 0 A_SpawnItem("GibsZ",0,0,0,1);
		TNT1 A 0 A_SpawnProjectile("KnightXDeath", 0, 0, random(0, 360), 2, random(0, 160));
		//TNT1 AA 0 A_SpawnItem("CrueltyBonus5Health");
	Stop;
}

}


CLASS HellKnightHeadPiece: BaronHeadPiece { 
Default {
	Scale 1.0;
}
States
{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		tnt1 a 0 {scale.x = randompick(-1, 1);}
	looper:
		HKHE IJKL 4 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		HKHE I 2;
		TNT1 A 0 A_QueueCorpse;
 	Rest:
		HKHE I -1;
	Stop;
	}
}



CLASS HellKnightHead: Limbs_Base { 
Default {
	damagefactor "Kick", 9.0;
	damagefactor "Melee", 9.0;
	damagefactor "SuperPunch", 9.0;
	-CLIENTSIDEONLY;
	+SHOOTABLE;
	-NOBLOCKMAP;
	+SOLID;
	+THRUACTORS;
	BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	damagefactor "Crush", 50.0;
	Radius 10;
	Mass 12;
	Health 60;
	Scale 1.1;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		HKHE G 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		HKHE G -1;
	Stop;
	
	Death:
		TNT1 A 0 a_spawnprojectile("noble_head_explosion", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
	Stop;
	
	Death.plasma:
		TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL A 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		Stop;
	
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		HKHE ABCDEFGH 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathHellKnightHeadKicked", 5, 0, random(170, 190), 2, random(20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
	Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		HKHE ABCDEFGH 1;
	Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		HKHE ABCDEFGH 6;
		HKHE I 0 A_SpawnItem("HellKnightHead");
	Stop;
}

}


CLASS XDeathHellKnightHeadKicked: XDeathHellKnightHead { 
	Default {
	
	-BOUNCEONACTORS;
	Damage 4;
	Speed 13;
	BounceFactor 0.4;
	}
}




CLASS Gib_HellKnightTorso: Limbs_Base { 
	Default {
	
	Scale 1.1;
	BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	BloodColor "DarkGreen";
	}
	States
	{
	Spawn:
		GHKT I 1;
		TNT1 A 0 A_QueueCorpse;
		GHKT I 1900;
		GHKT I -1;
		Stop;
	Death:    
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 5, 0, random(0, 360), 2, random(10, 80));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 5, 0, random(0, 360), 2, random(10, 80));
		TNT1 A 0 a_spawnprojectile("GenericHKGib1", 5, 0, random(0, 360), 2, random(10, 80));
		TNT1 A 0 a_spawnprojectile("XDeathHellKnightArm", 5, 0, random(0, 360), 2, random(10, 80));
Stop;}}


CLASS GenericHKGib1: XDeathArm1 { 
Default {
	Scale 0.9;
	Speed 5;
	BounceFactor 0.4;
	BounceCount 3;
	+CLIENTSIDEONLY;
	Gravity 0.8;
}

protected int frame_num;

States
	{
	Spawn:
		tnt1 a 0 nodelay {frame_num = random(0, 3);}
	looper:
		GG71 A 4 {
			a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
			frame = frame_num;
		}
	Loop;

	Death:
		TNT1 A 0 A_QueueCorpse;
		GG71 A -1 {frame = frame_num;}
		Stop;
	}
}


CLASS XDeathHellKnightArm: XDeathArm1 { 
Default {
	
	Scale 1.1;
	Speed 12;
	BounceFactor 0.4;
	BounceCount 3;
	Decal "GreenBloodSplat";
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		GHKA ABCDEFGH 4 a_spawnprojectile("brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		GHKA I 1;
		TNT1 A 0 A_SpawnItem("Gib_HellKnightArm", 1);
		Stop;
	}
}

CLASS Gib_HellKnightArm: Limbs_Base { 
	Default {
	
	Scale 1.1;
	BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	BloodColor "DarkGreen";
	}
	States
	{
	Spawn:
		GHKA I 1;
		TNT1 A 0 A_QueueCorpse;
		GHKA I 1900;
		GHKA I -1;
	Stop;

	Death:   
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 a_spawnprojectile("PB_blood", 2, 0, random(0, 360), 2, random(0, 360));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 2, 0, random(0, 360), 2, random(10, 90));
		TNT1 AA 0 a_spawnprojectile("GenericHKGib1", 2, 0, random(0, 360), 2, random(10, 90));
	Stop;

	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		GHKA ABCDEFGH 2;
	Goto Spawn;
		
	Death.ExplosiveImpact:
	Death.Kick: Death.SuperPunches: Death.Melee:
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		GHKA A 5;
		GHKA ABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Landz:
		XDT5 I 0 A_SpawnItem("Gib_HellKnightArm");
	Stop;
}

}


CLASS XDeathHellKnightLeg: XDeathArm1 { 
Default {
    Scale 1.1;
    Speed 12;
	bounceFactor 0.4;
	Decal "GreenBloodSplat";
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		GHKL ABCDEFGH 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		GHKL A 1;
		TNT1 A 0 A_SpawnItem("Gib_HellKnightLeg", 1);
		Stop;
	}
}


CLASS Gib_HellKnightLeg: Limbs_Base { 
	Default {
 
    Scale 1.1;
	BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	BloodColor "DarkGreen";
	}
    States
    {
	Spawn:
		GHKL I 1;
		TNT1 A 0 A_QueueCorpse;
		GHKL A 1900;
		GHKL A -1;
	Stop;

	Death:   
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 a_spawnprojectile("PB_blood", 2, 0, random(0, 360), 2, random(0, 360));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 2, 0, random(0, 360), 2, random(10, 90));
		TNT1 A 0 a_spawnprojectile("GenericHKGib1", 2, 0, random(0, 360), 2, random(10, 90));
		TNT1 A 0 a_spawnprojectile("GenericHKGib1", 2, 0, random(0, 360), 2, random(10, 90));
	Stop;

	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		GHKL ABCDEFGH 2;
	Goto Spawn;
	
	Death.ExplosiveImpact:
	Death.Kick: Death.SuperPunches: Death.Melee:
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		GHKL A 5;
		GHKL ABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Landz:
		XDT5 I 0 A_SpawnItem("Gib_HellKnightLeg");
	Stop;
}

}





CLASS XDeathHellKnightTorso: XDeathArm1 { 
Default {
    Scale 1.1;
    Speed 12;
	bounceFactor 0.4;
	Decal "GreenBloodSplat";
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		GHKT ABCDEFGH 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
	Loop;
	
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		GHKT I 1;
		HNDC A 0 A_SpawnItem("Gib_HellKnightTorso",0,0,0,1);
	Stop;
}
}


CLASS XDeathHellKnightHead: XDeathBullArm1 { 
Default {
	-CLIENTSIDEONLY;
	Scale 1.0;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		HKHE ABCDEFGH 6;
		Loop;
	Death:
		HKHE G 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		HKHE G 1 A_SpawnItem("HellKnightHead",0,0,0,1);
		Stop;
	}
}


CLASS KnightXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "GreenBloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 AAAA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAAAA 0 a_spawnprojectile("WallRedBlood", 32, 0, random(0, 360), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathHellKnightArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHellKnightTorso", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathHellKnightLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath2", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath3", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHellKnightHead", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
	Stop;
}
}





class DyingHellKnight : actor
{
Default
{
	Radius 16;
	Height 50;
	Health 100;
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "Blood", 0.0;
	BloodType "PB_Blood", "SawBlood", "SawBlood";
	damagefactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	damagefactor "Shrapnel", 0.0;
	damagefactor "KillMe", 0.0;
	damagefactor "Cutless", 0.6;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	+FLOORCLIP;
	+NOPAIN;
	+DONTSPLASH;
	Scale 1.1;
}

states
{
	Death.Cutless:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHellKnightArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHellKnightHead", 32, 0, random(0, 360), 2, random(0, 160));
		BBO1 AABCD 8;
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		BBO1 D -1 ;       
	stop;

	XDeath:
	Death.SSG:
	Death.Railgun:
	Death.Cut:
	Death.Saw:
	Death.ExplosiveImpact:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfHK", 24, 0, random(0, 360), 2, random(0, 160));
		BBO1 AAAAAAAAAABBBBBCCCCC 2 a_spawnprojectile("Brutal_FlyingBlood", 30, 0, random(0, 360), 2, random(30, 110));
		BBO1 DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 1 a_spawnprojectile("Brutal_FlyingBlood", 10, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		BBO1 D -1 ;       
		stop;
}

}

CLASS DyingHellKnight1 : DyingHellKnight
{
States
	{
	Spawn:
		KSA1 ABCB 6;
		TNT1 A 0 A_SpawnItem("Brutal_FlyingBlood", 0, 30);
		TNT1 A 0 A_PlaySound("PSXDPN");
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Fall;
		TNT1 A 0 A_PlaySound("knight/death");
		BTN3 ABCD 6;
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		BTN3 D -1;
	stop;
		
	NotDeadYet:
		TNT1 A 0 {self.bTHRUACTORS = true;}
		TNT1 A 0 A_SpawnItemEx("HellknightLastStand1",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION | SXF_TRANSFERAMBUSHFLAG ,0);
		stop;
		
		
	Death.Head:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Fall;
		TNT1 A 0 A_SpawnItem("noble_head_explosion", 0, 56);
		BTN4 ABCD 6;
		TNT1 A 0 A_SpawnItem("healthbonus");
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		BTN4 D -1;//death handler
	stop;
		
	Death.Decapitate:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Fall;
		TNT1 AAAAA 0 a_spawnprojectile("SmallSuperGore", 50, 0, random(0, 360), 2, random(10, 170));
		TNT1 AAAAA 0 a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathHellKnightHead", 62, 0, random(0, 360), 2, random(50, 130));
		BTN4 ABCD 6;
		TNT1 A 0 A_SpawnItem("healthbonus");
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		BTN4 D -1;//death handler
	stop;

	XDeath:
	Death.ExplosiveImpact:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_SpawnItem("healthbonus");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("KnightXDeath", 0, 0, random(0, 360), 2, random(0, 160));
		stop;
}

}

CLASS DyingHellKnight2 : DyingHellKnight
{ 
States
{
	Spawn:
		KSA7 EDEFE 6;
		TNT1 A 0 A_PlaySound("PSXDPN",1);
		TNT1 A 0 A_PlaySound("misc/xdeath2c",2);
		TNT1 A 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAA 0 a_spawnprojectile("PB_Blood", 30, 0, random(0, 360), 2, random(0, 160));
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Fall;
		TNT1 A 0 A_PlaySound("knight/death");
		TNT1 AAAAAAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAA 0 a_spawnprojectile("PB_Blood", 30, 0, random(0, 360), 2, random(0, 160));
		KAD1 ABCDEF 5 a_spawnprojectile("Brutal_FlyingBlood", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		KAD1 FFFFFFFFFFFFFFFFFFF 15 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
		KAD1 FFFFF 1 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
		KAD1 F -1;
	stop;
		
	Death.Head:
		TNT1 A 0 A_SpawnItem("noble_head_explosion", 0, 62);
		TNT1 A 0 A_SpawnItem("healthbonus");
		BOH2 A 10 A_Scream;
		TNT1 A 0 A_PlaySound("misc/xdeath");
		BOH2 B 10 A_NoBlocking;
		BOH2 C 10;
		BOH2 DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 a_spawnprojectile("Brutal_FlyingBlood", 10, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		BOH2 D -1;//death handler
		stop;
}

}



CLASS DyingHellKnightHeadShot : DyingHellKnight { 
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("PSXDPN",1);
		BTN5 AABBAACC 2 a_spawnprojectile("Brutal_FlyingBlood", 62, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_PlaySound("PSXDPN",1);
		BTN5 AAABBBAAACCC 2 a_spawnprojectile("Brutal_FlyingBlood", 62, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_PlaySound("PSXDPN",1);
	Death:
		TNT1 A 0 A_PlaySound("knight/death");
		BTN5 DDD 2 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_NoBlocking;
		BTN5 EEE 2 a_spawnprojectile("Brutal_FlyingBlood", 30, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		BTN5 FFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 a_spawnprojectile("Brutal_FlyingBlood", 10, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		BTN5 F -1;//death handler
	stop;
		
		
	Death.Head:
		TNT1 A 0 A_SpawnItem("noble_head_explosion", 0, 62);
		BTN2 AAAAAAAAAAA 2 a_spawnprojectile("Brutal_FlyingBlood", 62, 0, random(0, 360), 2, random(30, 110));
		BTN2 BBBBB 2 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_NoBlocking;
		BTN2 CCCCC 2 a_spawnprojectile("Brutal_FlyingBlood", 30, 0, random(0, 360), 2, random(30, 110));
		BTN2 DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 a_spawnprojectile("Brutal_FlyingBlood", 10, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		BTN2 D -1;//death handler
	stop;
		
		
	Death.SSG:
	XDeath:
	Death.ExplosiveImpact:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfHK", 24, 0, random(0, 360), 2, random(0, 160));
		BBO1 AAAAAAAAAABBBBBCCCCC 2 a_spawnprojectile("Brutal_FlyingBlood", 30, 0, random(0, 360), 2, random(30, 110));
		BBO1 DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 1 a_spawnprojectile("Brutal_FlyingBlood", 10, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		BBO1 D -1 ;       
		stop;
}

}



CLASS HellknightLastStand1: DyingHellKnight1 { 
	Default {
	
	Health 145;
	Speed 0;
	MONSTER;
	+MISSILEMORE;
	+MISSILEEVENMORE;
	+LOOKALLAROUND;
	BloodType "PB_Blood", "SawBlood", "SawBlood";
	}
States
	{
	Spawn:
		DAHK D 1 A_Look;
	See:
		DAHK DDDD 1
		{
			A_Chase();
			a_spawnprojectile("Brutal_FlyingBlood", 40, 6, random(0, 360), 2, random(30, 60));
			a_spawnprojectile("Brutal_FlyingBlood", 42, 6, random(170, 190), 2, random(0, 40));
		}
	Loop;
		
	Missile:
		DAHK B 2 A_FaceTarget;
		DAHK AAAAAAAA 2
		{
			A_FaceTarget();
			a_spawnprojectile("FlameTrails", 64, -30, random(0, 360), 2, random(70, 110));
			a_spawnprojectile("FlameTrails", 64, -30, random(0, 140), 2, random(0, 160));
		}

		DAHK B 8 A_FaceTarget;
		DAHK C 8 a_spawnprojectile("BaronBall", 36, 0, 0, 1);
		DAHK DDDD 2 a_spawnprojectile("Brutal_FlyingBlood", 40, 6, random(0, 360), 2, random(30, 60));
	Goto See;
}

}