CLASS pb_Hell_Knight : knight_base// Replaces HellKnight
{
	//SpawnID 2210;
Default
{
	Scale 1.0;
	Speed 10;
	Health 575;
	//Height 56;
	GibHealth 30;
	Mass 2000;
	MaxStepHeight 24;
	MaxDropOffHeight 32;
	MeleeDamage 5;
	-BOSSDEATH;
	+DONTHARMSPECIES;
	+NOBLOODDECALS;


	PainChance 20;
	PainChance "Kick", 255;
	PainChance "ExtremePunches", 255;
	PainChance "Explosive", 255;
	PainChance "Stun", 255;
	PainChance "Head", 150;
	PainChance "Saw", 100;
	PainChance "Cut", 100;
	
	damagefactor "Crush", 10.0;
	damagefactor "SSG", 0.95;
	damagefactor "Head", 0.8;
	damagefactor "Avoid", 0.0; damagefactor "killme", 0.0; damagefactor "TeleportRemover", 0.0;
	damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0; damagefactor "GreenBlood", 0.0;
	DamageFactor "CauseObjectsToSplash", 0.0; damagefactor "GibRemoving", 0.0;

	BloodType "Green_Blood", "GreenBloodSplat", "Green_Blood";
	BloodColor "DarkGreen";
	Obituary "%o was slain by a Hell Knight.";
	DamageType "HKFT";
	Species "Noble";
	PainSound "PSXDPN";
	
	////DropItem "DemonStrengthRune", 3;
	////DropItem "Demonpickup2", 50;
	////DropItem "Demonpickup", 196;
}

States
{
	Spawn:
		BOS2 B 1 A_Look();
	Stand:
		BOS2 B 10 A_Look();
	Loop;

	See: 
	RAGE:
		BTS2 ABCDEDFDEDF 3;
		BTS2 CBA 2 A_FaceTarget();
		TNT1 A 0 HealThing(200);
		TNT1 A 0 A_Jump(96, "MissileInRage");
	SeeContinue:
		TNT1 A 0 pb_monster_memory();
		BOS2 AAAABBBBZCCCCDDDDZ 2
		{
			A_Chase();
			if(frame > 5) 
			{
				tics = 0;
				A_PlaySound("knight/step",4);
			}
		}
	Loop;

	Melee:
		BOS2 EFG 6
		{
			A_FaceTarget();
			if(frame == 5) A_PlaySound("weapons/gswing");
			if(frame == 6) A_SpawnProjectile("Knight_Attack",10,0,0,0);
		}
	Goto seecontinue;

	Idle:
	LookingForPlayer:
		BOS2 BBBZBBBBBBB 10
		{
			A_Look();
			if(frame > 3)
			{
				self.angle += randompick(-40, 40);
				tics = 0;
			}
		}
		BOS2 AAAABBBBCCCCDDDD 2
		{
			A_Look();
			A_Recoil(-2);
			A_Wander();
		}
	loop;
			

			
			
	Missile:
		TNT1 A 0 
		{
			vector3 vec_to = self.vec3to(target);
			if((vec_to.x * vec_to.x + vec_to.y * vec_to.y + vec_to.z * vec_to.z)  > 902500/*950 ^ 2*/ && random(0, 2) > 1 )
			{self.setstatelabel('CHARGE');}
		}

	JustMissile:
		TNT1 A 0
		{
			if(target is "proto_cyberdemon" || target is "proto_spider_mind")
			{setstatelabel("CheckRetreat");}
		}
		TNT1 A 0 A_JumpIfCloser(900, 3);
		BOS2 FEEEEEEE 2
		{
			A_FaceTarget();
			A_SpawnProjectile("GreenFlameTrails", 64, 30, random(0, 360), 2, random(70, 110));
			A_SpawnProjectile("BallGettingReadyGreen", 64, 30, random(0, 140), 2, random(0, 160));
		}
		BOS2 F 8 A_FaceTarget();
		BOS2 G 8 A_SpawnProjectile("BaronBall", 36, 0, 0, 1);
	Goto seecontinue;
			
	CHARGE:
		BSCG ABCD 4
		{
			if( (frame == 1 || frame == 3) )
			{
				A_PlaySound("knight/step",5);
			}
			A_FaceTarget();
			A_Recoil(-4);

			If(vel.x == 0 || vel.y == 0)
			{
				setstatelabel("JustMissile");
			}

			if(distance2d(target) <= 50)
			{
				setstatelabel("POUNCE");
			}
		}
	loop;
			
	POUNCE:
		TNT1 A 0 A_Recoil(-8);
		TNT1 A 0 {self.vel.z += 17; }
		TNT1 A 0 A_PlaySound("weapons/fistwhoosh", 1);
		BSPC AB 3 A_FaceTarget();
		BSPC CCC 3;
		TNT1 A 0
		{
			A_PlaySound("CLAP", 2);
			A_SpawnProjectile("Cyber_Step",10,0,0,0);
			A_SpawnProjectile("Knight_Slam",10,0,0,0);
			A_SpawnProjectile("BigRicoChet");
			A_SpawnItem("BigRicoChet", 0, -30);
			Radius_Quake(2, 24, 0, 15, 0);
		}
		BSPC D 25;
	Goto seecontinue;
			
	MissileInRage:
		BOS2 EFGEFGEFG 6
		{
			A_FaceTarget();
			if(frame == 5)
			{
				A_SpawnProjectile("BaronBall", 36, 0, 0, 1);
			}
		}
	Goto seecontinue;
			
	CheckRetreat:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfCloser(500, "Retreat");
	Goto JustMissile+5;
			
	Retreat:
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0);
		TNT1 A 0 A_FaceTarget();
		BOS2 DDDDCCCCBBBBAAAA 2 {A_Recoil(2); A_FaceTarget();}
	Goto JustMissile+5;
			
	Pain:
		BOS2 H 3 A_TakeInventory("StopKickingMyBallsMotherFucker", 1);
		BOS2 H 3 A_Pain();
	Goto seecontinue;
			
	Possession:
		TNT1 A 0 {self.binvulnerable = true;}
		BOS2 H 3;
		BOS2 H 3 A_Pain();
 		TNT1 A 0 {self.binvulnerable = false;}
	Goto See;
			
			
	Pain.Kick:
	Pain.ExtremePunches:
		TNT1 A 0 {self.bMISSILEMORE = true; self.bMISSILEEVENMORE = true;}
		TNT1 A 0 {self.bNOPAIN = true; }
		KNRJ ABCDABCDABCDABCD 4
		{
			if(frame == 2)
			{
				A_Pain();
			}
		}
		TNT1 A 0 {self.bNOPAIN = false;}
	Goto Missile;

	Death.Shotgun:
		TNT1 A 0 A_JumpIfCloser(120, "Death.Blast");
	Goto Death;
			
	Death.Stomach:
		TNT1 A 0 ;//pb_spawn_blood_color(green, "muchblood", 55, random(0, 360), random(0, 160) );
		TNT1 AAAAAAA 0 A_SpawnProjectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 ;//pb_spawn_blood_color(green, "muchblood", 55, random(0, 360), random(0, 160) );
		TNT1 AAA 0 ;//pb_spawn_blood_color(green, "pb_blood", 30, random(0, 360), random(0, 160) );
		TNT1 A 0 A_SpawnItem("Dying_Hell_Knight");
	Stop;
			
	Death:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "Death2", "Death3", "Death4");
		TNT1 A 0 A_Jump(64, "Death.Arm", "DeathArm2");
		HKDD A 10;
		HKDD B 10 A_Scream();
		HKDD C 10;
		HKDD D 10 A_NoBlocking();
		TNT1 A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("dead_knight");
	Stop;
			
	Death4:
		TNT1 A 0;
		TNT1 AA 0 A_SpawnProjectile("Instestin", 28, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 A_SpawnProjectile("Bloodmist", 28, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//pb_spawn_blood_color(green, "XDeath1", 32, random(150, 210), 2, random(0, 40));
		HKDD I  10;
		HKDD J  10 A_Scream();
		HKDD K  10;
		HKDD L  10 A_NoBlocking();
		TNT1 A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");
		HKDD L -1;//death handler
	Stop;

	Death2_Big:
		TNT1 AA 0 A_SpawnProjectile("Bloodmist", 45, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//pb_spawn_blood_color(green, "XDeath1", 32, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 A_SpawnProjectile("XDeath3", 26, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 A_SpawnProjectile("XDeath2", 31, 0, random(130, 210), 2, random(0, 40));
		TNT1 AAAAAA 0 A_SpawnProjectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 ;//pb_spawn_blood_color(green, "muchblood", 55, random(0, 360), random(0, 160) );
		TNT1 AAA 0 ;//pb_spawn_blood_color(green, "pb_blood", 30, random(0, 360), random(0, 160) );
		TNT1 A 0 ;//pb_spawn_blood_color(green, "FlyingBlood", 28, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 ;//pb_spawn_blood_color(green, "XDeath1", 40, random(0, 360), 2, random(0, 160));
		BTN7 AAAA  2 A_SpawnProjectile("brutal_LiquidBlood", 37, 0, random(0, 360), 2, random(30, 60));
		BTN7 B  6 A_Scream();
		BTN7 CCC  2 A_SpawnProjectile("brutal_LiquidBlood", 19, 0, random(0, 360), 2, random(30, 60));
		BTN7 D  6 A_NoBlocking();
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		BTN7 EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 2 A_SpawnProjectile("brutal_LiquidBlood", 10, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");//;//pb_spawn_blood_color(green, "GrowingBloodPool");
		BTN7 E -1;
	Stop;

	Death.Nailgun:
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Jump(96, "Death.Blast");
		TNT1 AA 0 A_SpawnProjectile("Bloodmist", 45, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//pb_spawn_blood_color(green, "XDeath1", 32, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 A_SpawnProjectile("XDeath3", 26, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 A_SpawnProjectile("XDeath2", 31, 0, random(130, 210), 2, random(0, 40));
		TNT1 AAAAAA 0 A_SpawnProjectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 ;//pb_spawn_blood_color(green, "muchblood", 55, random(0, 360), random(0, 160) );
		TNT1 A 0 ;//pb_spawn_blood_color(green, "FlyingBlood", 28, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 ;//pb_spawn_blood_color(green, "XDeath1", 40, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnProjectile("Pinned_Hell_Knight_Torso", 49, 0, 180, 2, random(-2, 2));
		KSA6 FFFFFF  2 A_SpawnProjectile("brutal_LiquidBlood", 37, 0, random(0, 360), 2, random(30, 60));
		KSA6 G  6 A_Scream();
		KSA6 HHH  2 A_SpawnProjectile("brutal_LiquidBlood", 19, 0, random(0, 360), 2, random(30, 60));
		KSA6 I  6 A_NoBlocking();
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		KSA6 JJJJJJJJJJ 2 A_SpawnProjectile("brutal_LiquidBlood", 10, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");
		KSA6 J -1;//death handler
	Stop;

	Death.Blast:
		TNT1 A 0 A_Jump(128, "DeathBlast2");
		TNT1 AA 0 A_SpawnProjectile("Bloodmist", 45, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//pb_spawn_blood_color(green, "XDeath1", 32, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 A_SpawnProjectile("XDeath3", 26, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 A_SpawnProjectile("XDeath2", 31, 0, random(130, 210), 2, random(0, 40));
		TNT1 AAAA 0 A_SpawnProjectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 ;//pb_spawn_blood_color(green, "muchblood", 55, random(0, 360), random(0, 160) );
		TNT1 A 0 ;//pb_spawn_blood_color(green, "FlyingBlood", 28, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 ;//pb_spawn_blood_color(green, "XDeath1", 40, random(0, 360), 2, random(0, 160));
		KSA5 AAAAA  2 A_SpawnProjectile("brutal_LiquidBlood", 37, 0, random(0, 360), 2, random(30, 60));
		KSA5 D  6 A_Scream();
		KSA5 EEE  2 A_SpawnProjectile("brutal_LiquidBlood", 19, 0, random(0, 360), 2, random(30, 60));
		KSA5 F  6 A_NoBlocking();
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		KSA5 GGGGGGGGGGGG 2 A_SpawnProjectile("brutal_LiquidBlood", 10, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");
		KSA5 G -1;//death handler
	Stop;
			
	DeathBlast2:
		TNT1 A 0 A_SpawnProjectile("XdeathHellKnightArm", 55, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 A_SpawnProjectile("Bloodmist", 45, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//pb_spawn_blood_color(green, "XDeath1", 32, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 A_SpawnProjectile("XDeath3", 26, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 A_SpawnProjectile("XDeath2", 31, 0, random(130, 210), 2, random(0, 40));
		TNT1 AAAAAA 0 A_SpawnProjectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 ;//pb_spawn_blood_color(green, "muchblood", 55, random(0, 360), random(0, 160) );
		TNT1 A 0 ;//pb_spawn_blood_color(green, "FlyingBlood", 28, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 ;//pb_spawn_blood_color(green, "XDeath1", 40, random(0, 360), 2, random(0, 160));
		KSA6 FFFFF  2 A_SpawnProjectile("brutal_LiquidBlood", 37, 0, random(0, 360), 2, random(30, 60));
		KSA6 G  6 A_Scream();
		KSA6 HHH  2 A_SpawnProjectile("brutal_LiquidBlood", 19, 0, random(0, 360), 2, random(30, 60));
		KSA6 I  6 A_NoBlocking();
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		KSA6 JJJJJJJJJJ 2 A_SpawnProjectile("brutal_LiquidBlood", 10, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");
		KSA6 J -1;//death handler
	Stop;
			
	Death2:
		TNT1 A 0 ;//pb_spawn_blood_color(green, "FlyingBlood", 28, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 ;//pb_spawn_blood_color(green, "XDeath1", 40, random(0, 360), 2, random(0, 160));
		BTN6 AAA  2 A_SpawnProjectile("brutal_LiquidBlood", 37, 0, random(0, 360), 2, random(30, 60));
		BTN6 B 6 A_Scream();
		BTN6 CCC  2 A_SpawnProjectile("brutal_LiquidBlood", 19, 0, random(0, 360), 2, random(30, 60));
		BTN6 D 6 A_NoBlocking();
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		TNT1 A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");
		BTN6 E -1;//death handler
	Stop;
		
	Death3:
		TNT1 A 0 ;//pb_spawn_blood_color(green, "FlyingBlood", 28, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 ;//pb_spawn_blood_color(green, "XDeath1", 40, random(0, 360), 2, random(0, 160));
		HKDD EEE  2 A_SpawnProjectile("brutal_LiquidBlood", 37, 0, random(0, 360), 2, random(30, 60));
		HKDD F 6 A_Scream();
		HKDD GGG  2 A_SpawnProjectile("brutal_LiquidBlood", 19, 0, random(0, 360), 2, random(30, 60));
		HKDD H 6 A_NoBlocking();
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		TNT1 A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");
		HKDD H -1;//death handler
	Stop;
		
	DeathArm2:
		TNT1 A 0 A_SpawnProjectile("XdeathHellKnightArm", 55, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//pb_spawn_blood_color(green, "muchblood", 55, random(0, 360), random(0, 160) );
		TNT1 A 0 ;//pb_spawn_blood_color(green, "FlyingBlood", 28, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 ;//pb_spawn_blood_color(green, "XDeath1", 40, random(0, 360), 2, random(0, 160));
		KSA2 AAA  2 A_SpawnProjectile("brutal_LiquidBlood", 37, 0, random(0, 360), 2, random(30, 60));
		KSA2 D 6 A_Scream();
		KSA2 E  2 A_SpawnProjectile("brutal_LiquidBlood", 19, 0, random(0, 360), 2, random(30, 60));
		KSA2 F 6 A_NoBlocking();
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		TNT1 A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");
		KSA2 G -1;//death handler
	Stop;
			
	Death.Arm:
		TNT1 A 0 A_SpawnProjectile("XdeathHellKnightArm", 55, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//pb_spawn_blood_color(green, "muchblood", 55, random(0, 360), random(0, 160) );
		TNT1 A 0 A_Fall();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("Dying_Hell_Knight");
	Stop;
		
	DeathBrutalized:
		TNT1 A 0 A_SpawnProjectile("XdeathHellKnightArm", 55, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//pb_spawn_blood_color(green, "XDeath1", 48, random(150, 210), 2, random(0, 40));
		TNT1 A 0 ;//pb_spawn_blood_color(green, "muchblood", 55, random(0, 360), random(0, 160) );
		TNT1 A 0 A_Fall();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("Brutalized_HellKnight1");
	Stop;
		
	XDeath:
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnProjectile("KnightXDeath", 0, 0, random(0, 360), 2, random(0, 160));
	Stop;

	Death.SSG:
		TNT1 A 0 A_Jump(110, "Death.Saw");
		TNT1 A 0 A_XScream();
		TNT1 AA 0 A_SpawnProjectile("XdeathHellKnightArm", 55, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnProjectile("XdeathHellKnightHead", 62, 0, random(0, 360), 2, random(50, 130));
		TNT1 AA 0 A_SpawnProjectile("Bloodmist", 45, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//pb_spawn_blood_color(green, "XDeath1", 32, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 A_SpawnProjectile("XDeath3", 26, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 A_SpawnProjectile("XDeath2", 31, 0, random(130, 210), 2, random(0, 40));
		TNT1 AAAAAA 0 A_SpawnProjectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 ;//pb_spawn_blood_color(green, "muchblood", 55, random(0, 360), random(0, 160) );
		TNT1 A 0 ;//pb_spawn_blood_color(green, "FlyingBlood", 28, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 ;//pb_spawn_blood_color(green, "XDeath1", 40, random(0, 360), 2, random(0, 160));
		KSA6 AAAAA  2 A_SpawnProjectile("brutal_LiquidBlood", 37, 0, random(0, 360), 2, random(30, 60));
		KSA6 B  6;
		KSA6 CCC  2 A_SpawnProjectile("brutal_LiquidBlood", 19, 0, random(0, 360), 2, random(30, 60));
		KSA6 D  6 A_NoBlocking();
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		KSA6 EEEEEEEEE 2 A_SpawnProjectile("brutal_LiquidBlood", 10, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");
		KSA6 E -1;//death handler
	Stop;
	
	Death.Railgun:
	Death.Cut:
	Death.Saw:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAAA 0 ;//pb_spawn_blood_color(green, "XDeath1", 40, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 ;//pb_spawn_blood_color(green, "FlyingBlood", 15, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 A_SpawnProjectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnProjectile("Dying_Hell_Knight", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnProjectile("XdeathStomachGreen", 40, 0, random(0, 360), 2, random(0, 160));
		BBO1 AAAAAAAAAABBBBBCCCCC 2 A_SpawnProjectile("brutal_LiquidBlood", 30, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		BBO1 DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 1 A_SpawnProjectile("brutal_LiquidBlood", 10, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");
		BBO1 D -1 ;       
	Stop;
			
	Death.Tear:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAAA 0 ;//pb_spawn_blood_color(green, "XDeath1", 40, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 ;//pb_spawn_blood_color(green, "FlyingBlood", 15, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 A_SpawnProjectile("XDeath2", 45, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 A_SpawnProjectile("XDeath3", 45, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 A_SpawnProjectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnProjectile("XdeathStomachGreen", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 A_SpawnProjectile("XdeathBrain1", 60, 0, random(0, 360), 2, random(0, 160));
		B0S2 PQRSTU 6;
		TNT1 A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		B0S2 VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 1 A_SpawnProjectile("brutal_LiquidBlood", 20, 0, random(0, 360), 2, random(30, 110));
		B0S2 V -1;//death handler
	Stop;

	Death.CutLess:
		TNT1 A 0;
		TNT1 A 0 A_Jump(160, "DeathBrutalized");
		TNT1 A 0 A_Jump(120, "Death.Arm");
		TNT1 A 0 A_Jump(64, "Death.Stomach", "Death2_Big");
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAAA 0 ;//pb_spawn_blood_color(green, "XDeath1", 40, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 ;//pb_spawn_blood_color(green, "FlyingBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 A_SpawnProjectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnProjectile("Dying_Hell_Knight", 24, 0, random(0, 360), 2, random(0, 160));
		BBO1 AAAAAAAAAABBBBBCCCCC 2 A_SpawnProjectile("brutal_LiquidBlood", 30, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		BBO1 DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 1 A_SpawnProjectile("brutal_LiquidBlood", 10, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");
		BBO1 D -1;
	Stop;

	Death.head:
		//TNT1 A 0 A_JumpIfIntargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		//TNT1 A 0 A_JumpIfIntargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
		//TNT1 A 0 A_JumpIfIntargetInventory("HasCutingWeapon", 1, "Death.decaptate");
		TNT1 A 0 A_JumpIfHealthLower(-80, "Death.HeadExplode");
		TNT1 A 0 A_Jump(98, "Death.HeadExplode");
		TNT1 A 0 A_Playsound("MinorHeadshot", 0);
		TNT1 A 0 A_SpawnItem("noble_head_explosion_2", 0, 62);
		TNT1 A 0 A_Fall();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("Dying_Hell_Knight");
	Stop;
	
		BOH2 a 0;
		BTN2 a 0;
	Death.HeadExplode:
		tnt1 a 0
		{
			switch(random(0, 1))
			{
				case 1: sprite = getspriteindex("BOH2"); break;
				case 0: sprite = getspriteindex("BTN2"); break;
			}
		}
		//TNT1 A 0 A_JumpIfIntargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
		"####" A 0 A_SpawnItem("noble_head_explosion", 0, 62);
		"####" AAAAAAAAAAA 2 A_SpawnProjectile("brutal_LiquidBlood", 62, 0, random(0, 360), 2, random(30, 110));
		"####" BBBBB 2 A_SpawnProjectile("brutal_LiquidBlood", 50, 0, random(0, 360), 2, random(30, 110));
		"####" A 0 A_NoBlocking();
		"####" CCCCC 2 A_SpawnProjectile("brutal_LiquidBlood", 30, 0, random(0, 360), 2, random(30, 110));
		"####" A 0 A_PlaySound("BIG_BODYF", 9);
		"####" DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 A_SpawnProjectile("brutal_LiquidBlood", 10, 0, random(0, 360), 2, random(30, 110));
		"####" A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");
		"####" D -1;//death handler
	Stop;

	Death.decaptate:
		TNT1 AAAAA 0 ;//pb_spawn_blood_color(green, "XDeath1", 62, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_SpawnProjectile("XdeathHellKnightHead", 62, 0, random(0, 360), 2, random(50, 130));
		BTN2 AAAAAAAAAAA 2 A_SpawnProjectile("brutal_LiquidBlood", 62, 0, random(0, 360), 2, random(30, 110));
		BTN2 BBBBB 2 A_SpawnProjectile("brutal_LiquidBlood", 50, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_NoBlocking();
		BTN2 CCCCC 2 A_SpawnProjectile("brutal_LiquidBlood", 30, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		BTN2 DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 A_SpawnProjectile("brutal_LiquidBlood", 10, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");
		BTN2 D -1;//death handler
	Stop;
			
		
	Death.ExplosiveImpact:
	Death.ExtremePunches:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,35,0,1);
		TNT1 A 0 A_SpawnProjectile("XdeathHellKnightArm", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnProjectile("XdeathHellKnightLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 ;//pb_spawn_blood_color(green, "XDeath1", 62, random(0, 360), random(0, 160));
		TNT1 AAA 0 ;//pb_spawn_blood_color(green, "muchblood", 62, random(0, 360), random(0, 160));
		TNT1 A 0 A_Jump(255, "Death.ExplosiveImpact1", "Death.ExplosiveImpact2");
	Death.ExplosiveImpact1:
		BAH3 A  8 A_Scream();
		BAH3 B  8 A_NoBlocking();
		BAH3 CCCCCC  8 A_CheckFloor("Land1");
	Land1:
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		BAH3 D -1;
	Stop;

	Death.ExplosiveImpact2:
		BAH3 E  8 A_Scream();
		BAH3 F  8 A_NoBlocking();
		BAH3 GGGGGG  8 A_CheckFloor("Land2");
	Land2:
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		BAH3 H -1;
	Stop;

	Raise:
		BOS2 O 8;
		BOS2 NMLKJI 8;
	Goto seecontinue;

	CurbstompMarine:
		TNT1 A 0 {self.bInvulnerable = true;}
		KTFP AAA 3;
		KTFP BCDE 3;
		TNT1 A 0 A_SpawnItemEx("FootStep5", 0, 0, 40, 0, 0);
		EXPL A 0 Radius_Quake(2, 24, 0, 15, 0);
		TNT1 A 0 A_PlaySound("CLAP", 2);
		KTFP E 5;
		KTFP F 14;
		KTFP MGGGG 3;
		KTFP H 2;
		EXPL A 0 Radius_Quake(2, 24, 0, 15, 0);
		TNT1 AAA 0 A_SpawnProjectile("SmallBrainPiece", 11, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 A_SpawnProjectile("Brains2", 11, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnProjectile("Brains4", 11, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnProjectile("Brains4", 11, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 A_SpawnProjectile("Xdeath1", 1, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAAAAA 0 A_SpawnProjectile("Bloodmist", 1, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItemEx("SplatteredSmall", 0);
		KTFP IJ 2;
		KTFP KLLLLL 3;
		//TNT1 A 0 A_TakeInventory("Curbstomp_Marine",1);
		TNT1 A 0 {self.bInvulnerable = false;}
		//TNT1 A 0 A_SpawnItem("CurbstompedMarine", 1);
	Goto seecontinue;

	Death.Fatality:
		TNT1 A 0 A_Pain();
		//TNT1 A 0 A_JumpIfIntargetInventory("FistsSelected", 1, 1);
	Goto Death.ExplosiveImpact;

		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_Jump(128, "Death.Fatality3", "Death.Fatality4");
		//TNT1 A 0 A_GiveToTarget("HKFatality", 1);
		TNT1 A 1 A_NoBlocking();
		TNT1 A 0 A_BossDeath();
	Stop;

	Death.Fatality3:
		//TNT1 A 0 A_GiveToTarget("HKFatality3", 1);
		TNT1 A 1 A_NoBlocking();
		TNT1 A 0 A_BossDeath();
	Stop;

	Death.Fatality4:
		//TNT1 A 0 A_GiveToTarget("HKFatality4", 1);
		TNT1 A 1 A_NoBlocking();
		TNT1 A 0 A_BossDeath();
	Stop;

	Pain.KillMe:
	Pain.Taunt:
		TNT1 A 0;
	Goto Missile;

	Death.KillMe:
	Death.Taunt:
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 A_SpawnItem("HellKnight");
	Stop;
		
	Crush:
	Death.Stomp:
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAA 0 bright A_SpawnProjectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AAAAAA 0 bright ;//pb_spawn_blood_color(green, "XDeath1", 5, random(0, 360), random(30, 180));
		TNT1 AA 0 bright A_SpawnProjectile("XDeath2", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright A_SpawnProjectile("XDeath3", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 A 0 ;//pb_spawn_blood_color(green, "GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("CrushedRemains");
		TNT1 A 1;
		TNT1 A 1 A_XScream();
		TNT1 A 1 A_NoBlocking();
	Stop;
}

} 