//Watcher
CLASS pb_watch_maker : proto_head 
{ //30126
Default
{
	Health 100;
	Radius 24;
	Height 40;
	Mass 150;
	Speed 10;
	MONSTER;
	+NOGRAVITY;
	+FLOAT;

	DamageFactor "Crush", 10.0;
	DamageFactor "SSG", 10.0;
	DamageFactor "Saw", 0.9;
	damagefactor "killme", 0.0;
	DamageFactor "Blood", 0.0; DamageFactor "BlueBlood", 0.0; DamageFactor "GreenBlood", 0.0;

	PainChance 160;
	PainChance "Kick", 255;
	PainChance "Avoid", 190;
	PainChance "Saw", 255;
	PainChance "Stun", 255;

	SeeSound "monster/watsit";
	PainSound "monster/watpai";
	DeathSound "monster/watdth";
	ActiveSound "monster/watact";
	AttackSound "caco/melee";
	Obituary "%o was fried by a watcher.";
	HitObituary "Looks like a watcher thought %o was tasty.";

	//DropItem "DemonStrengthRune", 2;
}

States 
{ 
	Spawn: 
		WATC A 10 A_Look;
	Loop;

	Pain.Avoid:
		TNT1 A 0;
		TNT1 A 0 A_Jump(255, "AvoidLeft", "AvoidRight");
		Goto AvoidLeft;
		
	AvoidLeft:
		WATC A 1 A_FaceTarget;
		TNT1 A 0 ThrustThing(angle*256/360+192, 15, 0, 0);
		WATC A 5 A_FaceTarget;
		Goto Missile;
	AvoidRight:
		WATC A 1 A_FaceTarget;
		TNT1 A 0 ThrustThing(angle*256/360+64, 15, 0, 0);
		WATC A 5 A_FaceTarget;
		Goto Missile;
	See: 
		WATC A 3 A_Chase;
		TNT1 A 0 A_JumpIfCloser(99, "Melee");
		Loop;
	Missile: 
		TNT1 A 0 A_JumpIfCloser(140, "Melee");
		TNT1 A 0 A_Jump (198, 3);
	Goto Avoid;
		WATC E 5 A_FaceTarget;
		WATC F 5 A_FaceTarget;
		WATC G 5 BRIGHT a_spawnprojectile("WatcherShot",12,0,0);
		WATC E 12 A_FaceTarget;
	Goto See;

	Melee:
		WATC A 4 A_Recoil(-5);
		TNT1 A 0 a_spawnprojectile("WatcherBite", 34, 0, 0, 0);
		WATC BCD 5 A_FaceTarget;
		WATC A 5 A_MeleeAttack;
	Goto See;

	Pain: 
		WATC H 3;
		WATC H 3 A_Pain;
		Goto Avoid;
		TNT1 AAA 0;
		WATC A 6;
		Goto See;
		
	Possession:
		TNT1 A 0 A_SetInvulnerable;
		WATC H 3;
		WATC H 3 A_Pain;
		"####" "#" 35;// ACS_NamedExecuteAlways("Pos - Flicker effect");
		TNT1 A 0 A_UnSetInvulnerable;
	Goto See;
		
	Pain.Stun:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx ("StunElectrocute", random (-4, 4), random (-4, 4),  random (16, 32), 0, 0);
		WATC H 1 A_Pain;
		WATC HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		WATC H 1 A_Pain;
		WATC HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		WATC H 1 A_Pain;
		WATC HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		WATC H 1 A_Pain;
		WATC HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		WATC H 1 A_Pain;
		WATC HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		WATC H 1 A_Pain;
		Goto See;
		
	FatalityMarine:
		W4FT A 1 A_SetInvulnerable;
		TNT1 AA 0 a_spawnprojectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		W4FT A 8;
		TNT1 A 0 A_Playsound("caco/melee", 2);
		W4FT B 9;
		W4FT C 8;
		TNT1 A 0 a_spawnprojectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("XDeath3", 32, 0, random (150, 210), 2, random (0, 40));
		W4FT D 9;
		W4FT EF 7;
		TNT1 AAA 0 a_spawnprojectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		//TNT1 A 0 A_TakeInventory("Curbstomp_Marine",1);
		TNT1 A 0 A_UnSetInvulnerable;
		TNT1 A 0 A_SpawnItem ("MarineEattenByWatcher", 1);
		Goto See;
		
	Death.Shotgun:
		TNT1 A 0 A_JumpIfCloser(300, "Death.Strong");
		Goto Death+4;
		
	Death:
		TNT1 A 0 A_Jump(127, "AltDeath");
		WATC I 6 A_scream;
		WATC JKLM 6 a_spawnprojectile ("Blood", 0, 0, random (0, 360), 2, random (0, 160));
		WATC N 6 A_noblocking;
		TNT1 AAA 0 a_spawnprojectile ("XDeathGuts", 0, 0, random (0, 360), 2, random (0, 160));
		WATC N 0 A_SetFloorClip;
		WATC O -1;
		stop;
		
	AltDeath:
		WAT5 A 6 A_scream;
		WAT5 BCDE 6 a_spawnprojectile ("Blood", 0, 0, random (0, 360), 2, random (0, 160));
		WAT5 F 6 A_noblocking;
		TNT1 AAA 0 a_spawnprojectile ("XDeathGuts", 0, 0, random (0, 360), 2, random (0, 160));
		WAT5 F 0 A_SetFloorClip;
		WAT5 G -1;
		stop;
		
	Death.Massacre:
	Death.Saw:
	Death.Cut:
	Death.Tear:
	Death.Strong:
		WAT4 A 6 A_scream;
		TNT1 AA 0 a_spawnprojectile ("MuchBlood", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBrain1", 60, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeathBrain2", 60, 0, random (0, 360), 2, random (0, 160));
		WAT4 B 3 A_noblocking;
		TNT1 AA 0 a_spawnprojectile ("WatcherGib1", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("WatcherGib2", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		WAT4 C 2 A_SetFloorClip;
		WAT4 DEF 6 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("XDeath2b", 45, 0, random (0, 360), 2, random (0, 160));
		WAT4 G -1;
		stop;
		
	Death.Greenfire:
	Death.Plasma: Death.Plasma2:
	TNT1 A 0;
	TNT1 A 0 A_Scream;
	TNT1 A 0 A_NoBlocking;
	EXPL AAAAA 0 a_spawnprojectile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
	EXPL AAA 0 a_spawnprojectile ("PlasmaSmoke", 24, 0, random (0, 180), 2, random (0, 180));
	TNT1 AAAAAAAAA 0 a_spawnprojectile ("Ashes2", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("XDeathBurnedBlueMeat1", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAA 0 a_spawnprojectile ("XDeathBurnedBlueMeat2", 0, 0, random (0, 360), 2, random (0, 160));
	Stop;
	
	
	Death.SuperPlasma:
	TNT1 A 0;
	TNT1 A 0 A_XScream;
	TNT1 A 0 A_NoBlocking;
		TNT1 AAAA 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("Ashes1", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("PlasmaParticleX", 48, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAA 0 a_spawnprojectile ("BigPlasmaParticleX", 42, 0, random (0, 360), 2, random (0, 360));
	Stop;
	
	Death.SuperPunch:
	Death.Blast:
	Death.BlackHole:
	Death.ExplosiveImpact:
	Death.Railgun:
	Death.Desintegrate:
	XDeath:
		WAT4 B 1 A_XScream;
		WAT4 C 1 A_NoBlocking;
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 40));
		TNT1 AAAAAA 0 a_spawnprojectile ("WatcherGib2", 32, 0, random(0, 360), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 32, 0, random (0, 360), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random(0, 360), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (0, 360), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (0, 360), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (0, 360), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (0, 360), 2, random (0, 40));
		TNT1 AAAAAA 0 a_spawnprojectile ("WatcherGib1", 32, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_SpawnItem ("BigBloodSpot");
	Stop;
	
	
	Death.SSG:
	WAT4 B 1 A_XScream;
	WAT4 C 1 A_NoBlocking;
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAA 0 a_spawnprojectile ("WatcherGib2", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAA 0 a_spawnprojectile ("WatcherGib1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnItem ("BigBloodSpot");
	Stop;
	
	Avoid:
	NULL A 0 A_FaceTarget;
	WATC A 6 A_FastChase;
	NULL A 0 A_FaceTarget;
	WATC A 6 A_FastChase;
	NULL A 0 A_FaceTarget;
	WATC A 6 A_FastChase;
	NULL A 0 A_FaceTarget;
	WATC A 6 A_FastChase;
	WATC B 5 A_FaceTarget;
	WATC C 5 A_FaceTarget;
	WATC D 5 BRIGHT A_HeadAttack;
	Goto See;
	Raise: 
	WATC ONMLKJI 8;
	Goto See;
} 
}

CLASS WatcherShot : ACTOR { 
	Default {
	
	Radius 4;
	Height 8;
	Speed 18;
	Fastspeed 19;
	Damage 2;
	RENDERSTYLE "Add";
	DamageType "Plasma";
	ALPHA 0.67;
	PROJECTILE;
	+THRUGHOST;
	+FORCEXYBILLBOARD;
	SeeSound "monster/watatk";
	DeathSound "monster/wathit";
	}
   States
   {
	Spawn:
	FWAT AB 3 Bright ;//A_SpawnItem("PinkIonFlare",0,0);
	loop;
	Death:
	//TNT1 A 0 A_SpawnItem ("IonPuff", 0);
	TNT1 A 0 A_SpawnItemEx("PurpleTrailSparksSmall", 0, 0, 0, 0, 0, 0, 0, 128);
	TNT1 AA 15 a_spawnprojectile ("PlasmaSmoke", 1, 0, random (0, 360), 2, random (0, 160));
	FWAT CDE 3 Bright;
	stop;
}
}

CLASS WatcherBite: pb_projectile_base { 
	Default {
	
	+THRUGHOST;
	DamageType "HKFT";
	Damage 5;
	}
}
//End of Watcher

CLASS WatcherGib1: pb_dismembered_monster_base { 
	Default {
	
	Scale 0.95;
	}
    States
    {
	Spawn:
	TNT1 AA 0 a_spawnprojectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
	XWAT ABCDEFG 2;
	Loop;
	Death:
	TNT1 A 0 A_SpawnItem("pb_blood_Spot",0,0,0,1);
	XWAT H -1;
	Loop;
}}

CLASS WatcherGib2: pb_dismembered_monster_base { 
	Default {
	Scale 0.95;
	}
    States
    {
	Spawn:
	TNT1 AA 0 a_spawnprojectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
	XWBT ABCD 2;
	Loop;
	Death:
	TNT1 A 0 A_SpawnItem("pb_blood_Spot",0,0,0,1);
	XWBT E -1;
	Loop;
}}

   
CLASS MarineEattenByWatcher: pb_blood_and_gore_base { 
	Default
	{	
	Health 100;
	Height 16;
	Radius 8;
	MONSTER;
	-GHOST;
	+THRUACTORS;
	+FRIENDLY;
}

States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 {self.bTHRUACTORS = false;}
		TNT1 A 0 A_GiveInventory("ComeEatMeDemon");
		TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
		XPL4 GGG 6;// A_SpawnItem("KillMe");
		XPL4 G -1;
	stop;
}

}
