CLASS pb_Inhalator: The_Cyber_demon// Replaces Cyberdemon
{ 
Default
{
	//SpawnID 2410;

	damagefactor "BFG", .5;
	DamageFactor "Plasma", 0.75;
	DamageFactor "Desintegrate", .5;
	DamageFactor "GreenFire", .5;
	DamageFactor "SSG", .75;
	DamageFactor "Blast", .75;
	DamageFactor "Cut", .75;
	DamageFactor "Freeze", .25;
	DamageFactor "Ice", .25;
	DamageFactor "Frost", .25;
	damagefactor "Explosive", 1.1;
	damagefactor "HKFT", 0.05;
	damagefactor "Decaptate", 5.0;
	damagefactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	damagefactor "GibRemoving", 0.0;
	damagefactor "TeleportRemover", 0.0;
	DamageFactor "CauseObjectsToSplash", 0.0;
	DamageFactor "Blackhole", 0.75;
	DamageFactor "ExtremePunches", 1.0;
	DamageFactor "Crush", 20.0;
	DamageFactor "Blood", 0.0; DamageFactor "BlueBlood", 0.0; DamageFactor "GreenBlood", 0.0;

	PainChance 55;
	PainChance "Taunt", 255;
	PainChance "Head", 80;

	Health 7000;
	MaxStepHeight 24;
	MaxDropOffHeight 32;
	Scale 1.1;
	Radius 45;
	Height 98;

	+MISSILEMORE;
	+DONTHARMSPECIES;
	+MISSILEEVENMORE;
	+DONTRIP;
	// +NORADIUSDMG
	Speed 8;
	FastSpeed 12;
	mass 5000;
/*	
	//DropItem "DemonStrengthRune", 25;
	//DropItem "DemonMorphRune", 25;
	//DropItem "RageSphere", 25;
	//DropItem "DoubleSphere", 25;
	//DropItem "ShieldSphere", 20;
	//DropItem "Demonpickup2", 255;
	//DropItem "Demonpickup2", 255;
	//DropItem "Demonpickup2", 255;
	//DropItem "Demonpickup2", 255;
	//DropItem "Demonpickup2", 255;
	//DropItem "Demonpickup2", 255;
	//DropItem "Demonpickup2", 255;
*/
	BloodType "Brutal_Blood";
	Obituary "%o was destroyed by an Annihilator";
	Species "CyberDemon";
	SeeSound "monster/annsit";
	PainSound "monster/annpain";
	DeathSound "monster/anndth";
	ActiveSound "monster/annidle";
}
States
{
	Death.KillMe:
	Death.Taunt:
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 A_SpawnItem("The_Cyber_demon");
	Stop;
		
	ReplaceToggle:
		TNT1 A 0 {self.bTHRUACTORS = true;}
		TNT1 A 0 A_ChangeCountFlags(false);
		TNT1 A 0 A_SpawnItemEx("The_Cyber_demon",0,0,0,0,0,0,0,288);
	Stop;

	Spawn:
 	Stand:
		TNT1 A 0;
		4NNI D 10 A_Look();
	loop;
		
	See: 
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("monster/anhoof",4);
	RAGE:
		TNT1 A 0;
		TNT1 A 0 A_CheckSight("See2");
		EXPL A 0 Radius_Quake(6, 100, 0, 22, 0);
		ANBT AB 2;
		ANBT CDEDCDCDEDCDCDEDCD 3;
		ANBT EDCBA 2;
		TNT1 A 0 {health += 4000;}
		TNT1 A 0 A_Jump(96, "Missile3");
	Goto See2;
		
	See2:
		4NNI A 3 A_Playsound("monster/anhoof", 3);
		4NNI AAABBBBC 2 A_Chase();
		4NNI C 0 A_Playsound("monster/anhoof",2);
		4NNI CCCDDD 2 A_Chase();
	Loop;
		
	Missile:
		TNT1 A 0 A_Jump(96, "Missile2");
		TNT1 A 0 A_Jump(64, "Missile3");
		TNT1 A 0 A_JumpIfCloser(16, "Missile4");
		4NNI ABCDE 1 A_FaceTarget();
		4NNI E 4 A_FaceTarget();
		4NNI F 3 BRIGHT a_spawnprojectile("CyberBalls",60,-25,0,0);
		4NNI E 3 A_FaceTarget();
		4NNI F 3 BRIGHT a_spawnprojectile("CyberBalls",60,25,-7,0);
		4NNI E 3 A_FaceTarget();
		4NNI F 3 BRIGHT a_spawnprojectile("CyberBalls",60,-25,7,0);
		4NNI E 3 A_FaceTarget();
		4NNI F 3 BRIGHT a_spawnprojectile("CyberBalls",60,25,0,0);
		4NNI E 3 A_FaceTarget();
		4NNI EDCBA 1 A_FaceTarget();
	Goto See2;
		
	Missile2:
		4NNI ABCDE 1 A_FaceTarget();
		4NNI E 8 A_FaceTarget();
		4NNI F 3 BRIGHT a_spawnprojectile("CyberBalls",60,-25,0,0);
		4NNI E 6 A_FaceTarget();
		4NNI F 3 BRIGHT a_spawnprojectile("CyberBalls",60,25,-7,0);
		4NNI E 6 A_FaceTarget();
		4NNI F 3 BRIGHT a_spawnprojectile("CyberBalls",60,-25,7,0);
		4NNI E 6 A_FaceTarget();
		4NNI F 3 BRIGHT a_spawnprojectile("CyberBalls",60,25,0,0);
		4NNI E 6 A_FaceTarget();
		4NNI F 3 BRIGHT a_spawnprojectile("CyberBalls",60,-25,0,0);
		4NNI E 6 A_FaceTarget();
		4NNI F 3 BRIGHT a_spawnprojectile("CyberBalls",60,25,0,0);
		4NNI E 6 A_FaceTarget();
		4NNI EDCBA 1 A_FaceTarget();
	Goto See2;
		
	Missile3:
		4NNI ABCDE 1 A_FaceTarget();
		4NNI E 10 A_FaceTarget();
		4NNI F 3 BRIGHT a_spawnprojectile("CyberBalls",60,25,0,0);
		4NNI E 8 A_FaceTarget();
		4NNI F 3 BRIGHT a_spawnprojectile("CyberBalls",60,-25,-7,0);
		4NNI E 6 A_FaceTarget();
		4NNI F 3 BRIGHT a_spawnprojectile("CyberBalls",60,25,7,0);
		4NNI E 4 A_FaceTarget();
		4NNI F 3 BRIGHT a_spawnprojectile("CyberBalls",60,-25,0,0);
		4NNI E 3 A_FaceTarget();
		4NNI F 3 BRIGHT a_spawnprojectile("CyberBalls",60,25,0,0);
		4NNI E 3 A_FaceTarget();
		4NNI F 3 BRIGHT a_spawnprojectile("CyberBalls",60,-25,0,0);
		4NNI E 3 A_FaceTarget();
		4NNI F 3 BRIGHT a_spawnprojectile("CyberBalls",60,25,0,0);
		4NNI EDCBA 1 A_FaceTarget();
	Goto See2;
		
	Missile4:
		4NNI ABCDE 1 A_FaceTarget();
		4NNI E 6 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("CyberBalls",60,25,-7,0);
		4NNI F 3 BRIGHT;
		4NNI E 6 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("CyberBalls",60,-25,-7,0);
		4NNI F 3 BRIGHT;
		4NNI E 6 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("CyberBalls",60,25,-7,0);
		4NNI F 3 BRIGHT;
		TNT1 A 0 A_Jump(32, "Missile3");
		4NNI EDCBA 1 A_FaceTarget();
	Goto See2;
		
	Stomp:
		4NNI A 5 {A_FaceTarget(); self.bNORADIUSDMG = true;}
		ANMA A 7 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("CyberStomp",10,0,0,0);
		ANMA B 7;
		ANMA B 7 {self.bNORADIUSDMG = false;}
	Goto See2;
		
	Pain: 
		4NNI G 10 A_Pain();
	Goto See2;
		
	Death:
		4NNI HHHHH 2
		{
			for(int i = 0; i < 2; i++)
			{
				A_PlaySound("FAREXPL");
				A_PlaySound("Explosion", 1);
				a_spawnprojectile("CasingSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
			}
		}
		EXPL A 0 Radius_Quake(6, 100, 0, 22, 0);
		TNT1 A 0
		{
			for(int i = 0; i < 8; i++)
			{
				A_PlaySound("FAREXPL");
				A_PlaySound("Explosion", 1);
				a_spawnprojectile("CasingSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
			}
		}
		TNT1 AAAAAAAAAA 0 {pb_blood_and_gore_event.ultra_gore_spawner(self);}
		TNT1 A 0 a_spawnprojectile("CyberdemonHead", 120, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("cyberdemon_death", 0, 0, random(0, 360), 2, random(0, 160));
		4NNI I 5 A_Scream();
		4NNI JKL 1;
		4NNI M 1 A_NoBlocking();
		4NNI NOP 1;
		4NNI P 120;
		4NNI P -1 A_BossDeath();
	Stop;
		
	Death.Decaptate:
	Death.Head:
	Death.MinorHead:
		TNT1 A 0 a_spawnprojectile("CyberdemonHead", 120, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnItem("ShoqueAzul");
		TNT1 A 0 A_PlaySound("caco/shotx");
		TNT1 AAAAAAAAA 0 a_spawnprojectile("XDeath1", 120, 0, random(0, 360), 2, random(0, 180));
 		CYBB AAAAAABCABCB 8 {pb_blood_and_gore_event.much_blood(self);}
		EXPL A 0 Radius_Quake(6, 100, 0, 22, 0);
		TNT1 A 0
		{
			for(int i = 0; i < 8; i++)
			{
				A_PlaySound("FAREXPL");
				A_PlaySound("Explosion", 1);
				a_spawnprojectile("CasingSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
			}
		}
		TNT1 AAAAAAAAAA 0 {pb_blood_and_gore_event.ultra_gore_spawner(self);}
		TNT1 A 0 a_spawnprojectile("cyberdemon_death", 0, 0, random(0, 360), 2, random(0, 160));
		CYBR I 0 A_Fall();
		CYBR JKL 0;
		CYBR M 0 A_NoBlocking();
		CYBR NOP 0;
		CYBR P 120;
		CYBR P -1 A_BossDeath();
	Stop;
		
	Crush:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS3 A 5;
		CRS3 A -1;
	Stop;
		
	Pain.Taunt:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("Enraged", 1, "Missile4");
		SPOS B 0
		{
			if(self.rage == true){self.setstatelabel("SpecialAttack");}
			A_Pain(); self.bMISSILEMORE = true; self.bMISSILEEVENMORE = true;
		}
		TNT1 A 0 A_PlaySound("monster/annsit");
		ANBT ABCDEDCDCDEDCDCDEDCD 3;
		ANBT BA 2;
		TNT1 A 0 A_GiveInventory("Enraged", 1);
	Goto Missile;
		
	SpecialAttack:
		CYBR E 6 A_FaceTarget();
		CYBR F 4 BRIGHT a_spawnprojectile("CyberBalls",60,-25,0,0);
		TNT1 A 0 A_JumpIfCloser(180, "Stomp");
		CYBR E 4 A_FaceTarget();
		CYBR F 4 BRIGHT a_spawnprojectile("CyberBalls",60,-25,-7,0);
		TNT1 A 0 A_JumpIfCloser(180, "Stomp");
		CYBR E 4 A_FaceTarget();
		CYBR F 4 BRIGHT a_spawnprojectile("CyberBalls",60,-25,7,0);
		TNT1 A 0 A_JumpIfCloser(180, "Stomp");
		CYBR E 4 A_FaceTarget();
		CYBR F 4 BRIGHT a_spawnprojectile("CyberBalls",60,-25,0,0);
		TNT1 A 0 A_JumpIfCloser(180, "Stomp");
		CYBR E 4 A_FaceTarget();
		CYBR F 4 BRIGHT a_spawnprojectile("CyberBalls",60,-25,0,0);
		CYBR E 4 A_FaceTarget();
		CYBR F 4 BRIGHT a_spawnprojectile("CyberBalls",60,-25,0,0);
	Goto See;
}

}