CLASS The_Cyber_demon : proto_cyberdemon// Replaces Cyberdemon
{ 
Default
{	
	//SpawnID 2400;
	damagefactor "BFG", .5;
	DamageFactor "Plasma", 0.75;
	DamageFactor "Desintegrate", .5;
	DamageFactor "GreenFire", .5;
	DamageFactor "SSG", .75;
	DamageFactor "Blast", .75;
	DamageFactor "Cut", .75;
	DamageFactor "Freeze", .25;
	DamageFactor "Ice", .25;
	DamageFactor "Frost", .25;
	damagefactor "Explosive", 1.1;
	damagefactor "HKFT", 0.05;
	damagefactor "Decaptate", 5.0;
	damagefactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	damagefactor "GibRemoving", 0.0;
	damagefactor "TeleportRemover", 0.0;
	DamageFactor "CauseObjectsToSplash", 0.0;
	DamageFactor "Blackhole", 0.75;
	DamageFactor "ExtremePunches", 1.0;
	
	+NOICEDEATH;
	Health 5000;
	damagefactor "Crush", 20.0;
	MaxStepHeight 24;
	MaxDropOffHeight 32;
	Scale 1.2;
	+MISSILEMORE;
	+MISSILEEVENMORE;
	+DONTRIP;
	+DONTHARMSPECIES;
	+DONTHARMCLASS;
	//+NORADIUSDMG
	Species "CyberDemon";
	
	Speed 16;
	FastSpeed 22;
	mass 5000;
	PainChance "Head", 80;
	PainChance "KillMe", 64;
	PainChance "Taunt", 255;
	BloodType "CyberDemon_Blood", "AxeBlood", "AxeBlood";
	damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0; damagefactor "GreenBlood", 0.0;

/*	//DropItem "DemonStrengthRune", 25;
	//DropItem "DemonMorphRune", 15;
	//DropItem "Demonpickup2", 255;
	//DropItem "Demonpickup2", 255;
	//DropItem "Demonpickup2", 255;
	//DropItem "Demonpickup2", 255;
	//DropItem "Demonpickup2", 255;*/
}
protected state laser_charging;
protected int charge_level;
States
{
	Spawn:
 	Stand:
		CYBR D 10 A_Look;
		CYBR Z 10 A_Look;
	Loop;

	See:
		TNT1 A 0 A_SpawnItem("HeavyFootSteps32");
		CYBR A 3 A_Playsound("monster/anhoof",5);
		CYBR A 3;
		CYBR AA 2 A_Chase;
		TNT1 A 0 A_JumpIfCloser(120, "Stomp");
		CYBR BB 2 A_Chase;
		CYBR BBC 2 A_Chase;
		TNT1 A 0 A_SpawnItem("HeavyFootSteps32");
		CYBR C 2 A_Chase;
		CYBR C 2;
		CYBR C 2 A_Playsound("cyber/metal",6);
		CYBR DDDD 2 A_Chase;
	Loop;
		
	Missile:
		TNT1 A 0 A_Jump(98, "LaserBlast");
	FireRockets:
		TNT1 A 0 { IF(self.rage == true) {self.setstatelabel("SpecialAttack"); } }
		CYBR E 6 A_FaceTarget;
		CYBR F 6 BRIGHT a_spawnprojectile("CyberBalls",60,-25,0,0);
		CYBR E 6 A_FaceTarget;
		CYBR F 6 BRIGHT a_spawnprojectile("CyberBalls",60,-25,-7,0);
		CYBR E 6 A_FaceTarget;
		CYBR F 6 BRIGHT a_spawnprojectile("CyberBalls",60,-25,7,0);
		CYBR E 6 A_FaceTarget;
		CYBR F 6 BRIGHT a_spawnprojectile("CyberBalls",60,-25,0,0);
		CYBR E 6 A_FaceTarget;
	Goto See;
		
	LaserBlast:
		TNT1 A 0 
		{
			if( !(target is "playerpawn") ) 
			{
				self.setstatelabel("FireRockets");
				return;
			}
		}
		CYMA D 6 A_FaceTarget;
		TNT1 A 0 A_Playsound("CYBRLZR");
		CYMA E 7
		{
			A_FaceTarget();
			laser_charging = curstate.nextstate;
			charge_level = random(20, 30);
		}

		//Charging up animation
		CYMA F 2 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("Red_Flare",66,-21,0,0);
		TNT1 AA 0 a_spawnprojectile("bfg_4_laser_train",66,-21,0,0);
		TNT1 A 0 A_CustomRailgun(0, -20, "", "Red", RGF_SILENT || RGF_NOPIERCING || RGF_FULLBRIGHT , 1, 0, "NullPuff", 0, 0, 0, 2, 0.98, 1.0, "CyberDemonLaserPointer", 18);
		tnt1 a 0
		{
			if(charge_level > 0)
			{
				charge_level--;
				setstate(laser_charging);
			}
		}

		TNT1 A 0 A_PlaySound("Weapons/StachanovFire");
		CYMA G 8 a_spawnprojectile("CyberDemonLaserCannon",60,-25,random(-1,1));
		CYMA H 10;
	Goto See;

	Stomp:
		TNT1 A 0 {self.bNORADIUSDMG = true;}
		CYBR Z 5 A_FaceTarget;
		CYMA A 7 {A_FaceTarget(); a_spawnprojectile("CyberStomp",10,0,0,0);}
		CYMA B 7;
		CYMA B 7 {self.bNORADIUSDMG = false;}
	Goto See;

	Death:
		CYBR H 10;
 		EXPL A 0 Radius_Quake(6, 100, 0, 22, 0);
		TNT1 AAAA 0 a_spawnprojectile("SpawnedExplosion", 90, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAA 0 a_spawnprojectile("SpawnedExplosion", 90, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAA 0 a_spawnprojectile("UltraGoreSPawner", 90, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("CyberdemonHead", 120, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAA 0 a_spawnprojectile("UltraGoreSpawner", 90, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("cyberdemon_death", 0, 0, random(0, 360), 2, random(0, 160));
		CYBR I 5 A_Scream;
		CYBR JKL 5;
		CYBR M 5 A_NoBlocking;
		CYBR NOP 5;
		CYBR P 120;
		TNT1 A 0 A_BossDeath;
		CYBR P -1 A_BossDeath;
	Stop;

	Death.Decaptate:
		TNT1 A 0 a_spawnprojectile("CyberdemonHead", 120, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("XDeath1", 120, 0, random(0, 360), 2, random(0, 180));
 		CYBB AAAAA 8 A_SpawnItem("MuchBlood", 0, 120);
		CYBB ABCABCB 8 A_SpawnItem("MuchBlood", 0, 120);
		EXPL A 0 Radius_Quake(6, 100, 0, 22, 0);
		TNT1 AAAAAAAAAA 0 a_spawnprojectile("SpawnedExplosion", 90, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAA 0 a_spawnprojectile("UltraGoreSPawner", 90, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("cyberdemon_death", 0, 0, random(0, 360), 2, random(0, 160));
		CYBR I 0 A_Fall;
		CYBR JKL 0;
		CYBR M 0 A_NoBlocking;
		CYBR NOP 0;
		CYBR P 120;
		TNT1 A 0 A_BossDeath;
		CYBR P -1 A_BossDeath;
	Stop;

	Crush:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS3 A 5;
		CRS3 A -1;
	Stop;
		
	Pain.Taunt:
		SPOS B 0
		{
			if(self.rage == true){self.setstatelabel("SpecialAttack");}
			A_Pain();
			self.bMISSILEMORE = true; 
			self.bMISSILEEVENMORE = true;
			A_PlaySound("demon/pain", 0, 1, 0, ATTN_NONE);
		}
		CYBT A 1 A_FaceTarget;
		CYBT ABCCBADE 4;
		TNT1 A 0 A_PlaySound("CYBTAT", 1);
		CYBT FGHGFGHGFGHGFGHG 3;
		CYBT EDA 4 {self.rage - true;}
	Goto LaserBlast;

		
	SpecialAttack:
		CYBR E 6 A_FaceTarget;
		CYBR F 4 BRIGHT a_spawnprojectile("CyberBalls",60,-25,0,0);
		CYBR E 4 A_FaceTarget;
		CYBR F 4 BRIGHT a_spawnprojectile("CyberBalls",60,-25,-7,0);
		CYBR E 4 A_FaceTarget;
		CYBR F 4 BRIGHT a_spawnprojectile("CyberBalls",60,-25,7,0);
		CYBR E 4 A_FaceTarget;
		CYBR F 4 BRIGHT a_spawnprojectile("CyberBalls",60,-25,0,0);
		CYBR E 4 A_FaceTarget;
		CYBR F 4 BRIGHT a_spawnprojectile("CyberBalls",60,-25,0,0);
		CYBR E 4 A_FaceTarget;
		CYBR F 4 BRIGHT a_spawnprojectile("CyberBalls",60,-25,0,0);
		Goto See;
		
	}
}

CLASS CyberDemonLaserCannon : pb_projectile_base
{ 
Default
{	
	Speed 100;
	Radius 12;
	Height 8;
	Damage 0;
	Renderstyle "Add";
	-CANNOTPUSH;
	+NODAMAGETHRUST;
	+EXTREMEDEATH;
	+FORCERADIUSDMG;
	DamageType "ExplosiveImpact";
	MissileType "CyberDemonLaserTrail";
	MissileHeight 10;
	Decal "BFGLightning";
	Decal "BigScorch";
}
states
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("Weapons/StachanovFly",6,1.0,1);
	Fly:
		TNT1 A 1;
	Loop;

	Death:
		TNT1 A 0;
		TNT1 A 0 A_StopSound(6);
		TNT1 A 0 A_PlaySound("Weapons/YamatoExp",5);
		TNT1 AAAAA 0 A_SpawnItemEx("bfg_4_laser_train", random(19,-19), random(19,-19), random(19,-19), 0, 0, 0, 0, 128, 0);
		TNT1 A 0 A_SpawnItemEx("bfg_4_laser_explode",0,0,0,0,0,0,0,128,0);
		TNT1 A 0 A_Explode(175,80,0,1);
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -15);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 a_spawnprojectile("NewRocketExploFX", random(1,5), random(-10,10), random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("FireworkSFXType1", 0, 0, random(0, 360), 2, random(30, 60));
		tnt1 AAA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(0, 90));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 180));
		tnt1 A 0 Radius_Quake(3, 120, 0, 120, 0);
		tnt1 B 0 BRIGHT A_playsound("belphegor/missile");
		EXP1 ABCDEFGHIJKLMN 2 BRIGHT;
		TNT1 AAA 10 a_spawnprojectile("BigBlackSmoke", 0, 0, random(0, 360), 2, random(40, 160));
	stop;
}

}


CLASS CyberDemonLaserTrail : pb_special_effect_base
{ 
Default
{	
	RenderStyle "Add";
	Scale 0.11;
	Alpha 0.9;
	+NOGRAVITY;
	+CLIENTSIDEONLY;
}
	States
	{
	Spawn:
		TNT1 A 0;
		YAE4 A 3 bright;
	Trolololo:
		YAE4 A 0 A_SetScale(scale.x -0.01, scale.y -0.01);
		YAE4 A 1 bright A_FadeOut(0.1);
	Loop;
}

}


CLASS CyberDemonLaserPointer : pb_special_effect_base
{ 
Default
{
	RenderStyle "Add";
	Scale 0.03;
	Alpha 0.8;
	Translation "0:255=%[0,0,0]:[1,0,0]";
	+NOINTERACTION;
	+NOGRAVITY;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SetScale(scale.x+0.05, scale.y -0.01);
		YAE5 A 1 bright;
		YAE5 A 1 bright A_FadeOut(0.020);
	Trolololo:
		YAE5 A 0 A_SetScale(scale.x -0.01, scale.y -0.01);
		YAE5 A 1 bright A_FadeOut(0.1);
	Loop;
}

}