CLASS pb_Juggernaut : proto_Spider_mind//Fatso Replaces SpiderMastermind
{ 
	//SpawnID 2440;
Default
{
	Speed 1;
	Mass 99999;
	MinMissileChance 150;
	Health 7000;
	Scale 1.5;
	GibHealth 20;
	MaxStepHeight 24;
	MaxDropOffHeight 32;

	Painchance 10;
	Painchance "Explosive", 50;
	PainChance "Kick", 255;

	DamageFactor "Avoid", 0.0;
	damagefactor "BFG", 0.38;
	DamageFactor "Plasma", 0.75;
	DamageFactor "Desintegrate", .38;
	DamageFactor "GreenFire", .38;
	damagefactor "HKFT", 0.05;
	DamageFactor "Freeze", .25;
	DamageFactor "Ice", .25;
	DamageFactor "Frost", .25;
	damagefactor "Explosive", 1.5;
	damagefactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	damagefactor "Decaptate", 0.95;
	damagefactor "Head", 1.50;
	damagefactor "Stomp", 0.0;
	damagefactor "GibRemoving", 0.0;
	damagefactor "Trample", 0.0;
	damagefactor "TeleportRemover", 0.0;
	DamageFactor "Freeze", .45;
	DamageFactor "Ice", .45;
	DamageFactor "Frost", .45;
	DamageFactor "CauseObjectsToSplash", 0.0;
	DamageFactor "Blood", 0.0; DamageFactor "BlueBlood", 0.0; DamageFactor "GreenBlood", 0.0;
	DamageFactor "Shrapnel", 0.9;
	DamageFactor "Cutless", 1.1;
	DamageFactor "Explosive", 1.5;

	+NOICEDEATH;
	-NOTELEFRAG;
	+BOSS;
	+FLOORCLIP;
	+NODROPOFF;
	+MISSILEMORE;
	+MISSILEEVENMORE;
	+DONTHARMSPECIES;
	+DONTHARMCLASS

	BloodType "Brutal_Blood";
	Obituary "%o was destroyed by the Juggernaut";
	PainSound "juggernaut/pain";
	DeathSound "juggernaut/death";
	ActiveSound "juggernaut/roam";
	SeeSound "juggernaut/see";
	
	//DropItem "Demonpickup2", 255;
	//DropItem "Demonpickup2", 255;
	//DropItem "Demonpickup2", 255;
	//DropItem "Demonpickup2", 255;
	//DropItem "Demonpickup2", 255;
	//DropItem "Demonpickup2", 255;
	//DropItem "DemonMorphRune", 25;
}
States
{
	Spawn:
		BS1W A 1;
		TNT1 A 0 A_SpawnItemEx("KillTreads",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	Goto Standby;

	Standby:
		BS1W A 1;
		BS1W AC 10 A_Look();
	Loop;

	See:
		BS1W A 1;
	Goto Rolling;

	Rolling:
		TNT1 A 0 A_PlaySound("juggernaut/engine");
		BS1W A 2 A_Chase(null,null);
		BS1W B 2 A_Recoil(-2);
		TNT1 A 0 A_SpawnItem("TreadsDamage",65);
		
		BS1W A 2 A_Recoil(-2);
		BS1W B 2 A_Recoil(-2);
		TNT1 A 0 A_SpawnItem("TreadsDamage",65);
		
		BS1W C 2 A_Recoil(-2);
		BS1W D 2 A_Recoil(-2);
		TNT1 A 0 A_SpawnItem("TreadsDamage",65);
		
		BS1W C 2 A_Recoil(-2);
		BS1W D 2 A_Recoil(-2);
		TNT1 A 0 A_SpawnItem("TreadsDamage",65);
		
		BS1W A 2 A_Chase(null,null);
		BS1W B 2 A_Recoil(-2);
		TNT1 A 0 A_SpawnItem("TreadsDamage",65);
		
		BS1W A 2 A_Recoil(-2);
		BS1W B 2 A_Recoil(-2);
		TNT1 A 0 A_SpawnItem("TreadsDamage",65);
		
		BS1W C 2 A_Recoil(-2);
		BS1W D 2 A_Recoil(-2);
		TNT1 A 0 A_SpawnItem("TreadsDamage",65);
		
		BS1W C 2 A_Recoil(-2);
		BS1W D 2 A_Recoil(-2);
		TNT1 A 0 A_Jump(128, "Rolling2");
		TNT1 A 0 A_SpawnItem("TreadsDamage",65);
	Loop;
		
	Rolling2:
		TNT1 A 0 A_PlaySound("juggernaut/engine");
		
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		BS1B A 2 A_Chase(null,null);
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		BS1B A 2 A_Recoil(-2);
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		BS1B A 2 A_Recoil(-2);
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		BS1B A 2 A_Recoil(-2);
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		BS1B A 2 A_Chase(null,null);
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		BS1B A 2 A_Recoil(-2);
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		BS1B A 2 A_Recoil(-2);
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		BS1B A 2 A_Recoil(-2);
		TNT1 A 0 A_CheckSight("See");
	Goto Missile;
		
		///////////////////	
		
	Missile:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfCloser(150, "Rolling");
		TNT1 A 0 A_Jump(128, "FireRockets");
	Goto FireMachinegun;
	FireMachinegun:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("juggernaut/engine");
		
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		BS1B A 2 A_Chase(null,null);
		
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		BS1B A 2 A_Recoil(-2);
		TNT1 A 0 a_spawnprojectile("JuggernautBody2", 0);
		TNT1 A 0 a_spawnprojectile("MonsterMinigunTracer", 72, 42, random(-8, 8), 0);
		TNT1 A 0 a_spawnprojectile("MonsterMinigunTracer", 72, -42, random(-8, 8), 0);
		TNT1 A 0 a_spawnprojectile("YellowFlareSmall", 72, 42, 0, 0);
		TNT1 A 0 a_spawnprojectile("YellowFlareSmall", 72, -42, 0, 0);
		TNT1 A 0 a_spawnprojectile("RifleCaseSpawn", 72, 42, 0, 0);
		TNT1 A 0 a_spawnprojectile("RifleCaseSpawn", 72, -42, 180, 0);
		TNT1 A 0 A_SpawnItem("TreadsDamage",65);
		BS1B A 2 A_Recoil(-2);
		
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		BS1B A 2 A_Recoil(-2);
		
		TNT1 A 0 a_spawnprojectile("JuggernautBody2", 0);
		TNT1 A 0 a_spawnprojectile("MonsterMinigunTracer", 72, 42, random(-8, 8), 0);
		TNT1 A 0 a_spawnprojectile("MonsterMinigunTracer", 72, -42, random(-8, 8), 0);
		TNT1 A 0 a_spawnprojectile("YellowFlareSmall", 72, 42, 0, 0);
		TNT1 A 0 a_spawnprojectile("YellowFlareSmall", 72, -42, 0, 0);
		TNT1 A 0 a_spawnprojectile("RifleCaseSpawn", 72, 42, 0, 0);
		TNT1 A 0 a_spawnprojectile("RifleCaseSpawn", 72, -42, 180, 0);
		TNT1 A 0 A_SpawnItem("TreadsDamage",65);
		TNT1 A 0 A_GiveInventory("JuggernautMachinegunAmmo", 1);
		TNT1 A 0 A_JumpIfInventory("JuggernautMachinegunAmmo", 30, "stopfiring");
		TNT1 A 0 A_CheckSight("StopFiring");
		Loop;
		
	FireRockets:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("juggernaut/engine");
		
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		BS1B A 2 A_Chase(null,null);
		
		TNT1 A 0 a_spawnprojectile("CyberBalls", 110, -42, random(-3, 3), 0);
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		BS1B A 2 A_Recoil(-2);
		
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		TNT1 A 0 A_SpawnItem("TreadsDamage",65);
		BS1B A 2 A_Recoil(-2);
		
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		BS1B A 2 A_Recoil(-2);
		
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		BS1B A 2 A_Chase(null,null);
		TNT1 A 0 a_spawnprojectile("CyberBalls", 110, 42, random(-3, 3), 0);
		
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		BS1B A 2 A_Recoil(-2);
		
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		TNT1 A 0 A_SpawnItem("TreadsDamage",65);
		BS1B A 2 A_Recoil(-2);
		
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		BS1B A 2 A_Recoil(-2);
		
		TNT1 A 0 a_spawnprojectile("JuggernautBody1", 0);
		
		
		TNT1 A 0 A_SpawnItem("TreadsDamage",65);
		TNT1 A 0 A_GiveInventory("JuggernautRocketAmmo", 2);
		TNT1 A 0 A_JumpIfInventory("JuggernautRocketAmmo", 6, "stopfiring");
		TNT1 A 0 A_CheckSight("StopFiring");
		Loop;
		
	StopFiring:
		TNT1 A 0;
		TNT1 A 0 A_TakeInventory("JuggernautMachinegunAmmo", 30);
		TNT1 A 0 A_TakeInventory("JuggernautRocketAmmo", 6);
	Goto See;
		////////////////////
	Pain:
		TNT1 A 0;
		BS1W A 2;
		BS1W A 2 A_Pain();
	Goto Rolling;
		///////////////////////
	Death:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("KillTreads");
		EXPL A 0 Radius_Quake(6, 100, 0, 22, 0);
		TNT1 AAAA 0 ;//a_spawnprojectile("SpawnedExplosion", 90, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAA 0 ;//a_spawnprojectile("SpawnedExplosion", 90, 0, random(0, 180), 2, random(0, 180));
		TNT1 AAAA 0 a_spawnprojectile("UltraGoreSPawner", 90, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAA 0 a_spawnprojectile("UltraGoreSpawner", 90, 0, random(0, 180), 2, random(0, 180));
		
		TNT1 AAAAAA 0 ;//a_spawnprojectile("SpawnedExplosion", 50, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAA 0 a_spawnprojectile("SuperGoreSPawner", 110, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAA 0 a_spawnprojectile("Bloodmist", 90, 0, random(0, 360), 2, random(70, 90));
		//TNT1 AAAAAA 0 ;//a_spawnprojectile("SpawnedExplosion", 10, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAA 0 a_spawnprojectile("UltraGoreSPawner", 80, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAA 0 a_spawnprojectile("Bloodmist", 90, 0, random(0, 360), 2, random(70, 90));
		TNT1 AAAA 0 a_spawnprojectile("MuchMeatDeath", 0, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("SpawnedExplosion", 30, 0, random(0, 360), 2, 90);
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PEPart2SuperFast", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("UltraGoreSPawner", 30, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAA 0 a_spawnprojectile("UltraGoreSpawner", 30, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(70, 90));
		TNT1 AAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 100, 0, random(0, 360), 2, random(20, 90));
		
		TNT1 A 0;
		BS1B B 5 a_spawnprojectile("ExplosionSmoke", 60, 0, random(0, 360), 2, random(70, 110));
		BS1B B 5 a_spawnprojectile("RealFlameTrailsSmall", 60, 0, random(0, 360), 2, random(0, 160));
		BS1B B 5 a_spawnprojectile("ExplosionSmoke", 60, 0, random(0, 360), 2, random(70, 110));
		BS1B B 5 a_spawnprojectile("RealFlameTrailsSmall", 60, 0, random(0, 360), 2, random(0, 160));
		BS1B B 5 a_spawnprojectile("ExplosionSmoke", 60, 0, random(0, 360), 2, random(70, 110));
		BS1B B 5 a_spawnprojectile("RealFlameTrailsSmall", 60, 0, random(0, 360), 2, random(0, 160));
		BS1B B 5 a_spawnprojectile("ExplosionSmoke", 60, 0, random(0, 360), 2, random(70, 110));
		BS1B B 5 a_spawnprojectile("RealFlameTrailsSmall", 60, 0, random(0, 360), 2, random(0, 160));
		BS1B B 5 a_spawnprojectile("ExplosionSmoke", 60, 0, random(0, 360), 2, random(70, 110));
		BS1B B 5 a_spawnprojectile("RealFlameTrailsSmall", 60, 0, random(0, 360), 2, random(0, 160));
		BS1B B 5 a_spawnprojectile("ExplosionSmoke", 60, 0, random(0, 360), 2, random(70, 110));
		BS1B B 5 a_spawnprojectile("RealFlameTrailsSmall", 60, 0, random(0, 360), 2, random(0, 160));
		BS1B B 5 a_spawnprojectile("ExplosionSmoke", 60, 0, random(0, 360), 2, random(70, 110));
		BS1B B 5 a_spawnprojectile("RealFlameTrailsSmall", 60, 0, random(0, 360), 2, random(0, 160));
		BS1B B 5 a_spawnprojectile("ExplosionSmoke", 60, 0, random(0, 360), 2, random(70, 110));
		BS1B B 5 a_spawnprojectile("RealFlameTrailsSmall", 60, 0, random(0, 360), 2, random(0, 160));
		BS1B B 5 a_spawnprojectile("ExplosionSmoke", 60, 0, random(0, 360), 2, random(70, 110));
		BS1B B 5 a_spawnprojectile("RealFlameTrailsSmall", 60, 0, random(0, 360), 2, random(0, 160));
		BS1B B 5 a_spawnprojectile("ExplosionSmoke", 60, 0, random(0, 360), 2, random(70, 110));
		BS1B B 5 a_spawnprojectile("RealFlameTrailsSmall", 60, 0, random(0, 360), 2, random(0, 160));
		BS1B B 5 a_spawnprojectile("ExplosionSmoke", 60, 0, random(0, 360), 2, random(70, 110));
		BS1B B 5 a_spawnprojectile("RealFlameTrailsSmall", 60, 0, random(0, 360), 2, random(0, 160));
		BS1B B 1 A_BossDeath();
	Goto Decay;
		
	Decay:
		BS1B B 8 a_spawnprojectile("ExplosionSmoke", 60, 0, random(0, 360), 2, random(70, 110));
	Loop;
}

} 

CLASS Juggernaut_Base : pb_dismembered_monster_base
{ 
Default
{
	Health 8000;
	DamageFactor "Explosive", 1.5;
	DamageFactor "Killme", 9999.0;
	DamageFactor "Shrapnel", 0.9;
	DamageFactor "Cutless", 1.1;
	Radius 64;
	Height 2;
	Scale 1.5;
	Monster;
	+NOBLOOD;
	+SOLID;
	+FLOORCLIP;
	-NOBLOCKMAP;
	-COUNTKILL;
	Mass 99999;
	}
	States
	{
	Spawn:
		BS1B A 5;
		Loop;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		Stop;
	}
}

CLASS KillTreads : ACTOR { 
	Default {
	
	+NOTARGET;
	Radius 1;
	Height 1;
	DamageType "Killme";
	+NOGRAVITY;
	+NOTELEPORT;
	+NODAMAGETHRUST;
	+THRUGHOST;
	+NORADIUSDMG;
	+NOEXTREMEDEATH;
	+FORCERADIUSDMG;
	PROJECTILE;
	+DEHEXPLOSION;
	-ACTIVATEMCROSS;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Explode(20,80,0);
		Stop;
	}
}


CLASS TreadsDamage : ACTOR { 
	Default {
	
	+NOTARGET;
	Radius 1;
	Height 1;
	DamageType "Stomp";
	+NOGRAVITY;
	+NOTELEPORT;
	+NODAMAGETHRUST;
	+THRUGHOST;
	+NORADIUSDMG;
	+NOEXTREMEDEATH;
	+FORCERADIUSDMG;
	PROJECTILE;
	+DEHEXPLOSION;
	-ACTIVATEMCROSS;
	+EXPLODEONWATER;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Explode(500,40,0);
		TNT1 A 1 A_Noblocking();
		Stop;
	}
}

CLASS JuggernautBody1 : ACTOR { 
	Default {
	
	+RANDOMIZE;
	+FORCEXYBILLBOARD;
	+DONTSPLASH;
	+NOEXTREMEDEATH;
	+THRUACTORS;
	+NOGRAVITY;
	+NOCLIP;
	Projectile;
	damage 0;
	DamageFactor "Explosive", 1.5;
	radius 2;
	height 0;
	speed 1;
	Scale 1.5;
	}
	states
	{
	Spawn:
		BS1T AAAA 1;
		Stop;
	Goto Death;
	Death:
		TNT1 A 0;
		Stop;
	XDeath:
		TNT1 A 0;
		Stop;
	}
}

CLASS JuggernautBody2: JuggernautBody1 { 
	Default {
	
	}
	states
	{
	Spawn:
		BS1T BBBB 1 BRIGHT;
		Stop;
	Goto Death;
	}
}

CLASS JuggernautMachinegunAmmo : Inventory { 
	Default {
	
	inventory.maxamount 30;
	}
}

CLASS JuggernautRocketAmmo : Inventory { 
	Default {
	
	inventory.maxamount 6;
	}
}
