
CLASS CyberBalls : pb_projectile_base { 
Default {
		
	Radius 10;
	Height 8;
	Projectile;
	Speed 28;
	Damage 8;
	DamageType "Explosive";
	Gravity 0.00;
	Decal "Scorch";
	Renderstyle "Add";
	-NOGRAVITY;
	+EXTREMEDEATH;
	+THRUGHOST;
	Scale 0.65;
	SeeSound "DSCANFIR";
	//SeeSound "RLANSHOT"
	DeathSound "Explosion";
	Obituary "$OB_MPROCKET";
}
States
{
	Spawn:
		TNT1 A 0;
 			
	Spawn1:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
		WYVB A 1 Bright A_SpawnItem("Red_FlareSmall22",0,0);
		TNT1 A 0 a_spawnprojectile("ExplosionSmoke", 2, 0, random(160, 210), 2, random(-30, 30));
	Loop;
			
	SpawnCheap:
		TNT1 A 0;
		WYVB A 1 Bright A_SpawnItem("Red_FlareSmall22",0,0);
		Loop;
			
			
	SpawnUnderwater:
		WYVB A 1 Bright A_SpawnItem("YellowFlareSmall",0,0);
		TNT1 A 0 a_spawnprojectile("underwater_bubles", 0, 0, random(0, 360), 2, random(0, 180));
		Goto Spawn1;
			
			
	Death:
		EXPL A 0 Radius_Quake(2, 16, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
		//TNT1 A 0 A_SpawnItem("SuperExpensiveParticleSpawner")
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -30);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0  A_Explode(120, 150, damagetype:"ExplosiveImpact");
		TNT1 A 0
		{
			pb_effect_event(effects).show_some_effect(self, "NewRocketExploFX");
		}
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0
		{
			pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");
		}
		TNT1 AAAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		EXPL AAAAA 0 a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 1;
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		Stop;
			
	DeathCheap:
		EXPL A 0 Radius_Quake(2, 16, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -30);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0  A_Explode(120, 150, damagetype:"ExplosiveImpact");
		TNT1 A 0
		{
			pb_effect_event(effects).show_some_effect(self, "NewRocketExploFX");
		}
		TNT1 AAAAAAAAAA 0
		{
			//effects.show_some_effect(self, "ExplosionParticle");
		}
		TNT1 AAAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 1;
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		Stop;
}
}

CLASS FastCyberballs: Cyberballs { 
Default {
		
	Speed 40;
	Damage 30;
}
}

CLASS CyberballTrail : ACTOR { 
Default {
		
	Radius 0;
	Height 0;
	Alpha 1.0;
	RenderStyle "Add";
	Scale 0.9;
	Speed 2;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+DONTSPLASH;
	+MISSILE;
	+FORCEXYBILLBOARD;
	+CLIENTSIDEONLY;
	Damage 0;
	+NOINTERACTION;
}
States
{
	Spawn:
		TNT1 A 2;
		WYVB CDE 1;
			
		Stop;
}
}