//===========================================================================
//
// Ice Vile(Code used from realm 667 and sprites mostly made by PA1NKI113R)
//
//===========================================================================

CLASS pb_ICE_VILE : proto_arch_vile // Replaces Archvile
{ 
Default
{
	//SpawnID 2310;
	Mass 500;
	Speed 17;
	PainChance 30;
	Alpha 0.90;
	Monster;
	+QUICKTORETALIATE;
	+FLOORCLIP;
	+NOTARGET;
	RENDERSTYLE "Translucent";
	MaxTargetRange 896;

	PainChance "Kick", 90;
	PainChance "Stun", 255;

	DamageFactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	DamageFactor "Crush", 10.0;
	DamageFactor "Ice", 0.0;
	DamageFactor "Freeze", 0.0;//THE FUCKER CAN'T BE KILLED BY THE FREEZER
	DamageFactor "Blood", 0.0; DamageFactor "BlueBlood", 0.0; DamageFactor "GreenBlood", 0.0;
	DamageFactor "Saw", 0.8;
	DamageFactor "Fire", 1.45;//KILL IT WITH FIRE
	DamageFactor "Flames", 1.45;//KILL IT WITH FIRE

	BloodType "Blue_Blood";
	BloodColor "DarkBlue";
	StencilColor "AA FF FF";
	DamageType "Freeze";
	SeeSound "icevile/see";
	PainSound "icevile/pain";
	DeathSound "icevile/death";
	ActiveSound "icevile/active";
	MeleeSound "icevile/pain";
	Obituary "%o was iced by an Ice-Vile.";

/*	//DropItem "DemonStrengthRune", 8;
	//DropItem "DemonMorphRune", 5;
	//DropItem "RageSphere", 7;
	//DropItem "DoubleSphere", 7;
	//DropItem "TimeSphere", 7;
	//DropItem "Demonpickup2", 255;
	//DropItem "Demonpickup2", 255;*/
}
States
{		
	Spawn:
 		TNT1 AA 0;
		DIAF B 10 A_Look;
	loop;

	See:
		DIAF AA 2 A_Chase;
		TNT1 A 0 A_PlaySound("vile/step",5);
		DIAF BBCC 2 A_Chase;
		TNT1 A 0 A_PlaySound("vile/step",5);
		DIAF DDCC 2 A_Chase;
		TNT1 A 0 A_PlaySound("vile/step",5);
		//DIAF BB 2 A_Chase;
	Loop;

	Missile:
		TNT1 A 0 A_Jump(128, "SeekerMissiles");
		TNT1 A 0 A_Jump(64, "ImpSpawn");
		//TNT1 A 0 A_Jump(32, "TornadoForm") Stupid.
		DIAF E 0 A_VileStart;
		DIAF E 10 A_FaceTarget;
		DIAF E 1 A_VileTarget("CryoSmoke3");
		DIAF E 7 A_VileTarget("CryoSmoke3");

		DIAF E 1 A_VileTarget("CryoSmoke3");
		TNT1 A 0 a_spawnprojectile("SmallIceTrails", 85, 35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("SmallIceTrails", 85, -35, random(0, 40), 2, random(0, 160));
		DIAF E 3 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("SmallIceTrails", 85, 35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("SmallIceTrails", 85, -35, random(0, 40), 2, random(0, 160));
		DIAF F 3 A_FaceTarget;
		DIAF F 3 A_FaceTarget;
		DIAF E 1 A_VileTarget("CryoSmoke3");
		TNT1 A 0 a_spawnprojectile("SmallIceTrails", 85, 35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("SmallIceTrails", 85, -35, random(0, 40), 2, random(0, 160));
		DIAF E 3 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("SmallIceTrails", 85, 35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("SmallIceTrails", 85, -35, random(0, 40), 2, random(0, 160));
		DIAF F 3 A_FaceTarget;
		DIAF E 1 A_VileTarget("CryoSmoke3");
		TNT1 A 0 a_spawnprojectile("SmallIceTrails", 85, 35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("SmallIceTrails", 85, -35, random(0, 40), 2, random(0, 160));
		DIAF E 3 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));
		DIAF F 3 A_FaceTarget;
		DIAF E 1 A_VileTarget("CryoSmoke3");
		TNT1 A 0 a_spawnprojectile("SmallIceTrails", 85, 35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("SmallIceTrails", 85, -35, random(0, 40), 2, random(0, 160));
		DIAF E 3 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("SmallIceTrails", 85, 35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("SmallIceTrails", 85, -35, random(0, 40), 2, random(0, 160));
		DIAF F 3 A_FaceTarget;
		DIAF JKLMN 3 BRIGHT A_FaceTarget;
		DIAF O 3 BRIGHT A_VileAttack("weapons/cryobowhit", 15, 40, 45, 1.0, "Freeze");
		DIAF P 3 BRIGHT;
	Goto See;
		
	ImpSpawn:
		TNT1 A 0 A_Playsound("DSDIASIT",4);
		DIAF E 7;
		BXPL A 0 Bright A_Explode(13, 80, 0);// Freezy radius damage.(was 128)
		TNT1 A 0 A_PlaySound("weapons/cryobowhit");
		BXPL AAAAA 0 Bright A_SpawnItemEx("CryoSmoke", 0, 0, 0, random(10, 30)*0.1, 0, random(0, 10)*0.1, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION);
		DIAF F 2 A_FaceTarget;
		TNT1 A 0 BRIGHT A_SpawnItem("Blue_Flare",0,0);
		DIAF JKLMN 2 BRIGHT A_FaceTarget;
		CYUS F 0 A_PlaySound("Weapons/FreezerFire");
		DIAF O 2 BRIGHT a_spawnprojectile("IceImpComet", 40, 30, random(-25,25), CMF_OFFSETPITCH, random(-25,25));
		TNT1 A 0 BRIGHT a_spawnprojectile("IceImpComet", 30, 35, random(-25,25), CMF_OFFSETPITCH, random(-25,25));
		TNT1 A 0 BRIGHT a_spawnprojectile("IceImpComet", 30, 30, random(-25,15), CMF_OFFSETPITCH, random(-25,25));
		DIAF P 2;
	Goto See;
		
	SeekerMissiles:
		DIAF F 2 A_FaceTarget;
		DIAF F 2 Bright A_FaceTarget;
		DIAF F 2 A_FaceTarget;
		DIAF F 2 Bright A_FaceTarget;
		DIAF F 2 A_FaceTarget;
		DIAF F 2 Bright A_FaceTarget;
		TNT1 A 0 BRIGHT A_SpawnItem("Blue_Flare",0,0);
		DIAF JKLMN 2 BRIGHT A_FaceTarget;
		CYUS F 0 A_PlaySound("Weapons/FreezerFire");
		DIAF O 2 BRIGHT a_spawnprojectile("VileFreezer", 40, 30, random(-15,15), CMF_OFFSETPITCH, random(-15,15));
		TNT1 A 0 BRIGHT a_spawnprojectile("VileFreezer", 30, 35, random(-15,15), CMF_OFFSETPITCH, random(-15,15));
		TNT1 A 0 BRIGHT a_spawnprojectile("VileFreezer", 30, 30, random(-15,15), CMF_OFFSETPITCH, random(-15,15));
		DIAF P 2 BRIGHT;
	Goto See;
		
	TornadoForm:
		SPIN A 0 {self.binvulnerable = true;}
		SPIN ABCDEFGHABCDEFGHABCDEFGHABCDEFGH 1;
		FX07 ABC 2;
	wander_loop:
		FX07 A 1 A_PlaySound("tornado/form");
		FX07 A 0 a_spawnprojectile("KnockbackTornado",32,0,0,0);
		FX07 A 0 a_spawnprojectile("MiniVileFreezer",Random(16,64),Random(-32,32),Random(0,360),0,0);
		FX07 A 0 a_spawnprojectile("MiniVileFreezer",Random(16,64),Random(-32,32),Random(0,360),0,0);
		FX07 A 0 a_spawnprojectile("MiniVileFreezer",Random(16,64),Random(-32,32),Random(0,360),0,0);
		FX07 A 0 a_spawnprojectile("MiniVileFreezer",Random(16,64),Random(-32,32),Random(0,360),0,0);
		FX07 ABC 2 A_Wander;
		tnt1 a 0 a_jumpif(random(0,100) <= 10, 1);
	loop;
		SPIN ABCDEFGHABCDEFGHABCDEFGHABCDEFGH 1;
		SPIN A 0 {self.binvulnerable = false;}
	Goto See;
		
		/*Heal:
			DIHE "[\]" 10 BRIGHT
		Goto See*/
	Pain:
		DIAF Q 5;
		DIAF Q 5 A_Pain;
	Goto See;
		
	Possession:
		SPIN A 0 {self.binvulnerable = true;}
		DIAF Q 3;
		DIAF Q 3 A_Pain;
 		SPIN A 0 {self.binvulnerable = false;}
	Goto See;
		
	Pain.Stun:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx("StunElectrocute", random(-4, 4), random(-4, 4),  random(16, 32), 0, 0);
		DIAF Q 1 A_Pain;
		DIAF QQQQQQQQQQ 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		DIAF Q 1 A_Pain;
		DIAF QQQQQQQQQQ 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		DIAF Q 1 A_Pain;
		DIAF QQQQQQQQQQ 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		DIAF Q 1 A_Pain;
		DIAF QQQQQQQQQQ 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		DIAF Q 1 A_Pain;
		DIAF QQQQQQQQQQ 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		DIAF Q 1 A_Pain;
	Goto See;
		
	Pain.Kick:
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil(8);
		DIAF Q 10 A_Pain ;
		DIAF Q 10;
	Goto See;
		
	Death:
		TNT1 A 0 A_JumpIfHealthLower(-250, "Death.Lucky");
		TNT1 A 0 A_Jump(128, "Death.Lucky");
		DIAF Q 4;
		BXPL A 0 Bright A_Explode(13, 64, 0);// Freezy radius damage.(was 128)
		TNT1 A 0 A_PlaySound("weapons/cryobowhit");
		BXPL AAAAA 0 Bright A_SpawnItemEx("CryoSmoke", 0, 0, 0, random(10, 30)*0.1, 0, random(0, 10)*0.1, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION);
		BXPL AAA 0 Bright A_SpawnItemEx("CryoSmoke3", 0, 0, 0, random(10, 30)*0.04, 0, random(0, 10)*0.04, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION,64);
		TNT1 A 0 {self.bSHOOTABLE = false; self.bPUSHABLE = false; self.bSOLID = false;}
		//TNT1 A 0 A_SpawnItem("FrozenIcevile");
	Stop;
		
	Death.Lucky:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_PlaySound("DSBOTTLE");
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 ;//a_spawnprojectile("XIceChunk1", 48, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 ;//a_spawnprojectile("XIceChunk2", 48, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 ;//a_spawnprojectile("XIceChunk3", 48, 0, random(0, 360), 2, random(40, 120));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 48, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 48, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 48, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAA 0 a_spawnprojectile("MuchBlood", 48, 0, random(0, 360), 2, random(0, 160));
		FZDB C -1;
		//FZDB CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 1 A_FadeOut(0.0;1)
	Stop;
		
	Death.Fatality:
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("IceVileFatality", 1);
		TNT1 A 1 A_BossDeath;
		TNT1 A 0;
	Stop;
		
	Crush:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS2 A 5;
		CRS2 A -1;
	Stop;
		
	Pain.KillMe:
	Pain.Taunt:
		TNT1 A 0;
	Goto Missile;
		/*
			Death:
			TNT1 A 0 {self.bSHOOTABLE", 0)
			TNT1 A 0 {self.bSOLID", 0)
			TNT1 A 0 A_SpawnItem("FrozenArchvile")
			Stop */
	}
}

CLASS VileFreezer: pb_projectile_base
{
Default
{
	Radius 8;
	Height 8;
	Speed 20;
	Damage 3;
	DamageType "Freeze";
	Decal "Scorch";
	Projectile;
	+RANDOMIZE;
	+THRUGHOST;
	+SEEKERMISSILE;
	renderstyle "Add";
	alpha 0.90;
	Scale 0.30;
	DeathSound "weapons/cryobowhit";
	//SeeSound "PLSM9"
	SeeSound "dimp/missile";
	Species "FrozenMonsters";
	-MTHRUSPECIES;
	-THRUSPECIES;
	Obituary "$OB_MPPLASMARIFLE";
	Decal "IceScorch";
}
States
{
	Spawn:
		PBAL C 1 BRIGHT A_SpawnItem("Blue_Flare",0,0);
		TNT1 A 0 a_spawnprojectile("Icetracer", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_SeekerMissile(4,6);
	Loop;
		
	Xdeath:
		BXPL AA 0 Bright A_SpawnItemEx("CryoSmoke", 0, 0, 0, random(10, 30)*0.1, 0, random(0, 10)*0.1, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION);
		BXPL AA 0 Bright A_SpawnItemEx("CryoSmoke3", 0, 0, 0, random(10, 30)*0.04, 0, random(0, 10)*0.04, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION,64);
		BXPL AAA 0 Bright A_SpawnItemEx("FreezerTrailSparksSmall", random(5,-5), random(5,-5), random(5,-5), random(10, 30)*0.04, 0, random(0, 10)*0.04, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION,64);
		BXPL AAA 0 Bright A_SpawnItemEx("CryoSmoke2", 0, 0, 0, random(10, 30)*0.04, 0, random(0, 10)*0.04, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION,64);
		TNT1 B 1 A_Explode(5,90,0);
	Stop;
		
	Death:
		//TNT1 A 0 A_SpawnItem("PlasmaPuff", 0)
		//TNT1 A 0 A_SpawnItem("RailPuff", 0)
		TNT1 B 1 A_Explode(5,90,1);
		BXPL AA 0 Bright A_SpawnItemEx("CryoSmoke", 0, 0, 0, random(10, 30)*0.1, 0, random(0, 10)*0.1, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION);
		BXPL AA 0 Bright A_SpawnItemEx("CryoSmoke3", 0, 0, 0, random(10, 30)*0.04, 0, random(0, 10)*0.04, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION,64);
		BXPL AAA 0 Bright A_SpawnItemEx("FreezerTrailSparksSmall", random(5,-5), random(5,-5), random(5,-5), random(10, 30)*0.04, 0, random(0, 10)*0.04, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION,64);
		BXPL AAA 0 Bright A_SpawnItemEx("CryoSmoke2", 0, 0, 0, random(10, 30)*0.04, 0, random(0, 10)*0.04, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION,64);
	Stop;
		
	}
}

CLASS MiniVileFreezer: VileFreezer { 
	Default {
	
	Radius 10;
	Height 10;
	Speed 27;
	Damage 2;
	Scale 0.19;
	-SEEKERMISSILE;
	}
}

CLASS KnockbackTornado : ACTOR
{ 
Default
{
	StencilColor "AA FF FF";
	Height 4;
	Speed 50;
	Radius 50;
	Height 16;
	PROJECTILE;
	+Randomize;
}

states
{
	Spawn:
		tnt1 aBCDEFGHIJK 1 A_RadiusThrust(128,255,0);
	Stop;
}

}

CLASS IceImpComet : ACTOR { 
Default
{
	Radius 6;
	Height 8;
	Speed 5;
	Damage 5;
	DamageType "Ice";
	Scale 1.5;
	Projectile;
	+DoomBounce;
	BounceFactor 0.6;
	Gravity 0.5;
	SeeSound "Afrit/CometFire";
	DeathSound "Afrit/CometHit";
	Decal "Scorch";
}

States
{
	Spawn:
		SHEX AAABBBCCCDDDDEEE  1 Bright A_SpawnItemEx("IceTracer", 0, 0, 0, 0, 0, 0, 0, 128);
	Goto Death;
	Death:
		SHEX D 3 Bright A_SpawnItemEx("ExplosionSmoke", 0, 0, 0, 0, 0, 0, 0, 128);
		SHEX E 3;
		TNT1 A 0 Bright A_SpawnItem("pb_Ice_Imp");
	Stop;
}

}

CLASS FatalizedIceVile : ACTOR
{ 
States
{
	Spawn:
		TNT1 A 0;
		FZDB C -1;
	Stop;
}

}
	














//===========================================================================
//
//  Ice Imp
//
//===========================================================================
CLASS pb_Ice_Imp : proto_imp_class
{ 
Default
{
	////SpawnID 2315;
	Scale 1.04;
	health 100;
	Mass 100;
	GibHealth 35;
	Monster;
	Speed 12;
	MaxStepHeight 24;
	MaxDropOffHeight 32;
	+DONTHARMCLASS;
	+FLOORCLIP;

	PainChance 200;
	PainChance "Taunt", 255;
	PainChance "Kick", 255;
	PainChance "SuperKick", 255;
	PainChance "ExplosiveImpact", 255;
	PainChance "Minorhead", 255;
	PainChance "Stun", 255;

	DamageFactor "Saw", 0.15;
	DamageFactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	DamageFactor "Ice", 0.0;
	DamageFactor "Freeze", 0.0;
	DamageFactor "bloodsplasher", 0.0;    DamageFactor "tinybloodsplasher", 0.0;
	DamageFactor "superbloodsplasher", 0.0;    DamageFactor "smallbloodsplasher", 0.0;
	DamageFactor "Blood", 0.0;	DamageFactor "BlueBlood", 0.0; DamageFactor "GreenBlood", 0.0;
	DamageFactor "BlueBloodSplasher", 0.0; DamageFactor "BlueSuperBloodSplasher", 0.0;
	DamageFactor "SuperKick", 0.5; 	DamageFactor "MinorHead", 0.8;
	DamageFactor "Fatality", 0.5;	DamageFactor "SuperPunch", 0.5;
	DamageFactor "Head", 2.5;	DamageFactor "SSG", 5.0;
	DamageFactor "explosiveimpact", 2.0;
	DamageFactor "Shrapnel", 0.3;
	DamageFactor "Kick", 0.5;

	BloodType "XIceChunk1";
	//BloodColor DarkBlue
	DamageType "Ice";
	SeeSound "imp/sight";
	PainSound "imp/pain";
	DeathSound "imp/death";
	ActiveSound "imp/active";

	////DropItem "DemonStrengthRune", 1;
}
States
{
	Spawn:
		SIMP AB 6 A_Look;
		SIMP B 6 A_Look;
	Loop;
		
	See:
		SIMP AABBCCDD 3 A_Chase;
	Loop;
		
	Melee:
		SIMP EF 5 A_FaceTarget;
		SIMP G 4 a_spawnprojectile("ImpAttack",10,0,0,0);
		SIMP FE 5;
	Goto See;
		
	Missile:
		SIMP EF 3 A_FaceTarget;
		CYUS F 0 A_PlaySound("Weapons/FreezerFire", 7);
		SIMP G 2 a_spawnprojectile("MiniImpFreezer",32,6);
		CYUS F 0 A_PlaySound("Weapons/FreezerFire", 7);
		SIMP G 2 a_spawnprojectile("MiniImpFreezer",32,-6);
		SIMP EF 3 A_FaceTarget;
		CYUS F 0 A_PlaySound("Weapons/FreezerFire", 7);
		SIMP G 2 a_spawnprojectile("MiniImpFreezer",32,-6);
		CYUS F 0 A_PlaySound("Weapons/FreezerFire", 7);
		SIMP G 2 a_spawnprojectile("MiniImpFreezer",32,6);
	Goto See;
		
	Pain:
		SIMP H 2;
		SIMP H 2 A_Pain;
	Goto See;
		
	Possession:
		TNT1 A 0 A_SetInvulnerable;
		SIMP H 3;
		SIMP H 3 A_Pain;
 		TNT1 A 0 A_UnSetInvulnerable;
	Goto See;
		
	Pain.Stun:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx("StunElectrocute", random(-4, 4), random(-4, 4),  random(16, 32), 0, 0);
		SIMP H 1 A_Pain;
		SIMP HHHHHHHHHH 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		SIMP H 1 A_Pain;
		SIMP HHHHHHHHHH 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		SIMP H 1 A_Pain;
		SIMP HHHHHHHHHH 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		SIMP H 1 A_Pain;
		SIMP HHHHHHHHHH 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		SIMP H 1 A_Pain;
		SIMP HHHHHHHHHH 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		SIMP H 1 A_Pain;
	Goto See;
		
		
	Death.Shotgun:
		TNT1 A 0 A_JumpIfCloser(320, "Death.Blast");
	Death:
		TNT1 A 0 A_Jump(192, "Death.Blast");
		TNT1 A 0 {self.bSHOOTABLE = false; self.bSOLID = false;}
		BXPL AAA 0 Bright A_SpawnItemEx("CryoSmoke", 0, 0, 0, random(10, 30)*0.1, 0, random(0, 10)*0.1, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION);
		BXPL AA 0 Bright A_SpawnItemEx("CryoSmoke3", 0, 0, 0, random(10, 30)*0.04, 0, random(0, 10)*0.04, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION,64);
		//TNT1 A 0 A_SpawnItem("FrozenIceImp");
	Stop;
		
	Death.Blast:
	Death.SSG:
	Death.Railgun:
	Death.SuperPunch:
	Death.QuadBlast:
	Death.SuperKick:
	Death.ExplosiveImpact:
	XDeath:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_PlaySound("DSBOTTLE");
		TNT1 AAAAAAAAAAAAAAAAAAA 0 ;//a_spawnprojectile("XIceChunk1", 48, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAA 0 ;//a_spawnprojectile("XIceChunk2", 48, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 ;//a_spawnprojectile("XIceChunk3", 48, 0, random(0, 360), 2, random(40, 120));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 48, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 48, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 48, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("MuchBlood", 48, 0, random(0, 360), 2, random(0, 160));
		FZD4 C -1;
	Stop;
	}
}


CLASS MiniImpFreezer: VileFreezer
{ 
Default
{
	Radius 8;
	Height 8;
	Speed 20;
	Damage 1;
	Scale 0.125;
	SeeSound "dimp/missile";
	-SEEKERMISSILE;
}
States
{
	Spawn:
		PBAL C 1 BRIGHT A_SpawnItem("Blue_Flare",0,0);
		BXPL A 0 Bright A_SpawnItemEx("FreezerTrailSparksSmall", random(5,-5), random(5,-5), random(5,-5), random(10, 30)*0.04, 0, random(0, 10)*0.04, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION,64);
		TNT1 A 0 a_spawnprojectile("Icetracer", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0;//A_SeekerMissile(4,6)
	Loop;
		
	Xdeath:
		BXPL A 0 Bright A_SpawnItemEx("CryoSmoke", 0, 0, 0, random(10, 30)*0.1, 0, random(0, 10)*0.1, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION);
		BXPL A 0 Bright A_SpawnItemEx("CryoSmoke3", 0, 0, 0, random(10, 30)*0.04, 0, random(0, 10)*0.04, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION,64);
		BXPL AA 0 Bright A_SpawnItemEx("FreezerTrailSparksSmall", random(5,-5), random(5,-5), random(5,-5), random(10, 30)*0.04, 0, random(0, 10)*0.04, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION,64);
		BXPL AA 0 Bright A_SpawnItemEx("CryoSmoke2", 0, 0, 0, random(10, 30)*0.04, 0, random(0, 10)*0.04, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION,64);
		TNT1 B 1 A_Explode(4,90,0);
		TNT1 B 4;
	Stop;
		
	Death:
		TNT1 B 1 A_Explode(5,90,1);
		BXPL A 0 Bright A_SpawnItemEx("CryoSmoke", 0, 0, 0, random(10, 30)*0.1, 0, random(0, 10)*0.1, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION);
		BXPL A 0 Bright A_SpawnItemEx("CryoSmoke3", 0, 0, 0, random(10, 30)*0.04, 0, random(0, 10)*0.04, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION,64);
		BXPL AA 0 Bright A_SpawnItemEx("FreezerTrailSparksSmall", random(5,-5), random(5,-5), random(5,-5), random(10, 30)*0.04, 0, random(0, 10)*0.04, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION,64);
		BXPL AA 0 Bright A_SpawnItemEx("CryoSmoke2", 0, 0, 0, random(10, 30)*0.04, 0, random(0, 10)*0.04, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION,64);
	Stop;
		
	}
}

CLASS StoneImp : pb_Ice_Imp
{
Default 
{
	health 180;
}

}