class proto_arch_vile : pb_monster_base
{
Default
{
	Radius 20;
	Height 72;
}
states
{
	Death.Blackhole:
		TNT1 A 0
		{
			A_Scream();
			A_NoBlocking();
			A_PlaySound("redburn",6,1,1);
			if(self is "pb_flesh_wizard") {self.scale.x = 0.3;}
		}
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 35, 0, 0, 0, 0, 128);
		ID61 AAABCDEFGHI 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 35, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
	Stop;
}

}