CLASS ExplosiveBarrel1 : pb_monster_base Replaces ExplosiveBarrel { 
Default {
	damagefactor "Trample", 0.0;
	damagefactor "Kick", 0.1;
	damagefactor "LowKick", 0.1;
	damagefactor "Melee", 0.1;
	damagefactor "Extremepunches", 0.1;
	damagefactor "Fatality", 10.1;
	damagefactor "SuperPunch", 10.1;
	damagefactor "ExplosiveImpact", 0.4;
	damagefactor "Fire", 3.5;
	damagefactor "GibRemoving", 0.0;
	damagefactor "BHFTOnBarrel", 500.0;
	damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0 ;   damagefactor "Avoid", 0.0;
	damagefactor "Shrapnel", 0.0; damagefactor "KillMe", 0.0;
	damagefactor "TeleportRemover", 0.0;
	Health 25;
	Radius 10;
	Height 34;
	Mass 200;
	DamageType "ExplosiveImpact";
	MONSTER;
	-COUNTKILL;
	+NOBLOOD;
	+FRIENDLY;
	+NOICEDEATH;
	+PUSHABLE;
	+SLIDESONWALLS;
	+WINDTHRUST;
	+TELESTOMP;
	+NOBLOCKMONST;
	+MISSILEMORE;
	+MISSILEEVENMORE;
	+EXTREMEDEATH;
	+DOHARMSPECIES;
	+usespecial;
	+ACTIVATEMCROSS;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	Speed 0;
	MaxTargetRange 200;
	DamageFactor "BHFT", 10.0;
	Painchance "Blood", 255;
	PainChance "Kick", 255;
	PainChance "SuperKick", 255;
	PainChance "SuperPunch", 255;
	PainChance "ExtremePunches", 255;
	DeathSound "excavator/explode";
	PainSound "barrel/pain";
	Obituary "$OB_BARREL";
	PainChance "DontCallTheBaron", 255;
	Painchance 255;
}

States
{
	Spawn:
		BAR1 ABCDEFGHIJKLM 2;//A_JumpIfInventory("RedBloodSplatterz", 1, "Pain.Blood");
	Loop;

	//bloody sprites
		BARB ABCDEFGHIJKLM 2;

	Pain.Kick:
	Pain.SuperKick:
	Pain.ExtremePunches:
	Pain.SuperPunch:
		TNT1 A 0 {self.bFRIENDLY = false;}
		BAR1 A 1 A_Pain;
		BAR1 A 0 A_Chase(null,null);
		TNT1 A 0 ThrustThingZ(0,8,0,1);
		BAR1 A 1 A_FaceTarget;
		TNT1 A 0 HealThing(100);
		TNT1 A 0 ThrustThing(angle*256/360+128, 10, 0, 0);
		TNT1 A 0 ThrustThingZ(0,8,0,1);
		TNT1 A 0 {self.bFRIENDLY = true;}
	Goto spawn;
		
		
		
	Death:
		BEXP AB 2 BRIGHT;
		BEXP C 3 BRIGHT;
		TNT1 A 0 A_Stop;
		BEXP D 1 BRIGHT;
		TNT1 AAAA 0 a_spawnprojectile("Shrapnel", 64, 0, random(0, 360), 2, random(30, 60));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ShrapnelParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("NewRocketExploFX", 0, 0, 20);
		TNT1 A 0
		{
			for(int i = 0; i < 4; i++)
			{
				A_PlaySound("FAREXPL");
				A_PlaySound("Explosion", 1);
				a_spawnprojectile("CasingSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
			}
		}
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Fall;
		
		
		TNT1 AAAA 0 a_spawnprojectile("FireworkSFXType1", 64, 0, random(0, 360), 2, random(30, 60));
		TNT1 AA 0 a_spawnprojectile("NewRocketExploFX", random(10, 20), 0, random(0, 360), 2, random(10, 90));
		EXPL AA 0 a_spawnprojectile("BigBlackSmoke", 20, 0, random(0, 360), 2, random(10, 90));
		TNT1 AAA 0 a_spawnprojectile("BDExplosionparticles", 64, 0, random(0, 360), 2, random(40, 90));
		TNT1 AAA 0 a_spawnprojectile("BDExplosionparticles", 64, 0, random(0, 360), 2, random(40, 90));
		EXPL A 0 Radius_Quake(2, 24, 0, 15, 0);
		BEXP B 0 BRIGHT A_Scream;
		
		TNT1 AA 0 a_spawnprojectile("BarrelShrapnel1", 25, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("BarrelShrapnel1", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("BarrelShrapnel1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("BarrelShrapnel1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece", random(-35, 35), random(-35, 35));
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece", random(-45, 45), random(-45, 35));
		TNT1 A 0 A_Jump(64, 2);
		TNT1 A 0 A_SpawnItem("ExplosiveBarrelPartialRemains", 0);
		BEXP E 1;
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -15);
		
		TNT1 AAA 8 
		{
			pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");
		}
		BEXP Z 300 BRIGHT A_BarrelDestroy;
		BEXP Z 5 A_Respawn;
	sTOP;

	Active:
		BAR1 B 1 A_FaceTarget;
 		//TNT1 A 0 A_JumpIfInTargetInventory("HasBarrel",1, "See");
		//TNT1 A 0 A_JumpIfInTargetInventory("HasBurningBarrel",1, "See");
		//TNT1 A 0 A_JumpIfInTargetInventory("PowerStrength",1, "GiveBarrel");
	Goto spawn;
		
	GiveBarrel:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 {self.bSHOOTABLE = true;}
		BAR1 A 1 A_FaceTarget;
		BAR1 ABCD 2;
		TNT1 A 0 A_PlaySound("barrel/pain");
	Stop;
}

}

CLASS ExplosiveBarrelPartialRemains : ACTOR { 
Default {
	-Solid;
}
states
{
	Spawn:
		BEXP RST 4 bright Light("BarrelDeadLight");
		tnt1 a 0 {if(random(0, 10) > 8) {setstatelabel("null");} }
	loop;
}
}