CLASS ExplosiveBarrelPartialRemains : ACTOR { 
Default {
	
	-Solid;
	
}
states
{
	Spawn:
		BEXP RSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRST 4 bright Light("BarrelDeadLight");
		BEXP U -1;
		Stop;
}
}

CLASS NewBarrelExploFX : ACTOR { 
Default {
	
	Radius 0;
	Height 0;
	RenderStyle "Add";
	Alpha 1;
	Scale 1.45;
	+NOGRAVITY;
	+NOINTERACTION;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+ForceXYBillboard;
	+CLIENTSIDEONLY;
}
States
{
	Spawn:
		X005 ABCDEFGHIJKLMNOPQRSTUVWX 1 bright;
		stop;
}
}

CLASS ExplosiveBarrel1 : SwitchableDecoration Replaces ExplosiveBarrel { 
Default {
	damagefactor "Trample", 0.0;
	damagefactor "Kick", 0.1;
	damagefactor "LowKick", 0.1;
	damagefactor "Melee", 0.1;
	damagefactor "Extremepunches", 0.1;
	damagefactor "Fatality", 10.1;
	damagefactor "SuperPunch", 10.1;
	damagefactor "ExplosiveImpact", 0.4;
	damagefactor "Fire", 3.5;
	damagefactor "GibRemoving", 0.0;
	damagefactor "BHFTOnBarrel", 500.0;
	damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0 ;   damagefactor "Avoid", 0.0;
	damagefactor "Shrapnel", 0.0; damagefactor "KillMe", 0.0;
	damagefactor "TeleportRemover", 0.0;
	//Species "Marines"
	Health 25;
	Radius 10;
	Height 34;
	Mass 200;
	DamageType "ExplosiveImpact";
	MONSTER;
	-COUNTKILL;
	+NOBLOOD;
	+FRIENDLY;
	+NOICEDEATH;
	+PUSHABLE;
	+SLIDESONWALLS;
	+WINDTHRUST;
	+TELESTOMP;
	+NOBLOCKMONST;
	+MISSILEMORE;
	+MISSILEEVENMORE;
	+EXTREMEDEATH;
	+DOHARMSPECIES;
	+usespecial;
	+ACTIVATEMCROSS;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	Speed 0;
	MaxTargetRange 200;
	DamageFactor "BHFT", 10.0;
	Painchance "Blood", 255;
	PainChance "Kick", 255;
	PainChance "SuperKick", 255;
	PainChance "SuperPunch", 255;
	PainChance "ExtremePunches", 255;
	DeathSound "excavator/explode";
	PainSound "barrel/pain";
	Obituary "$OB_BARREL";
	PainChance "DontCallTheBaron", 255;
	Painchance 255;
}
States
{
	
	Spawn:
		TNT1 A 0;
 		BAR1 A 4;//A_SpawnItem("Flare_Barrel_Green",0,32)
		BAR1 B 4;//A_SpawnItem("Flare_Barrel_Green",0,32)
		TNT1 A 0 A_Look;
		Goto See;
		
	NormalBarrel:
		BAR1 BCDEFGHIJKLM 2 ;//;//;//A_JumpIfInventory("RedBloodSplatterz", 1, "Pain.Blood");
		loop;
		
	NormalBarrel2:
		BAR1 ABCDEFGHIJKLM 2;
		Goto NormalBarrel;
		
	See:
		BAR1 ABCDEFGHIJKLM 2 ;//;//A_JumpIfInventory("RedBloodSplatterz", 1, "Pain.Blood");
	Loop;
		
	SpawnValientExplosiveBarrel:
		Stop;
		//
	Missile:
		TNT1 A 0;//A_CheckSight
		//TNT1 A 0 A_JumpIfInventory("NoBaronBarrels", 1, "NormalBarrel");
		//TNT1 A 0 A_JumpIfInTargetInventory("TargetIsABaronOfHell", 1, "TauntTHeBaron");
		BAR1 ABCDEFGHIJKLM 2;
		TNT1 A 0 A_ClearTarget;
		Goto See;
		
	TauntTheBaron:
		TNT1 A 0;
		BAR1 A 2;
		TNT1 A 0 A_JumpIfCloser(280, 1);
		Goto See;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("CallingTheBaronAFaggot", 36, 0, 0, 1);
	DoingNothing:
		BAR1 ABCDEFGHIJKLM 2;
		Goto See;
		
	Pain:
		TNT1 A 0 A_JumpIfInventory("GotBloody", 1, "BloodyPain");
		BEXP A 6;
		Goto See;
		
	BloodyPain:
		BARB AB 3;
		Goto StayBloody;
		
	Pain.Blood:
		TNT1 A 0;
		TNT1 A 0 A_GiveInventory("GotBloody", 1);
		Goto StayBloody;
	StayBloody:
		BARB ABCDEFGHIJKLM 2;
		Loop;
		
	Pain.Kick:
	Pain.SuperKick:
	Pain.ExtremePunches:
	Pain.SuperPunch:
		TNT1 A 0 A_JumpIfInventory("GotBloody", 1, "BloodyThrust1");
		TNT1 A 0 {self.bFRIENDLY = false;}
		BAR1 A 1 A_Pain;
		BAR1 A 0 A_Chase(null,null);
		TNT1 A 0 ThrustThingZ(0,8,0,1);
		BAR1 A 1 A_FaceTarget;
		TNT1 A 0 HealThing(100);
		TNT1 A 0 ThrustThing(angle*256/360+128, 10, 0, 0);
		TNT1 A 0 ThrustThingZ(0,8,0,1);
		TNT1 A 0 {self.bFRIENDLY = true;}
		Goto See;
		
	BloodyThrust1:
		TNT1 A 0 {self.bFRIENDLY = false;}
		BARB A 1 A_Pain;
		BAR1 A 0 A_Chase(null,null);
		TNT1 A 0 ThrustThingZ(0,8,0,1);
		BARB B 1 A_FaceTarget;
		TNT1 A 0 HealThing(100);
		TNT1 A 0 ThrustThing(angle*256/360+128, 10, 0, 0);
		TNT1 A 0 ThrustThingZ(0,8,0,1);
		TNT1 A 0 {self.bFRIENDLY = true;}
		Goto StayBloody;
		
	Pain.Melee:
		TNT1 A 0 A_JumpIfInventory("GotBloody", 1, "BloodyThrust2");
		TNT1 A 0 {self.bFRIENDLY = false;}
		BAR1 A 1 A_Pain;
		BAR1 A 0 A_Chase(null,null);
		BAR1 A 1 A_FaceTarget;
		TNT1 A 0 HealThing(100);
		TNT1 A 0 ThrustThing(angle*256/360+128, 5, 0, 0);
		TNT1 A 0 ThrustThingZ(0,10,0,1);
		TNT1 A 0 {self.bFRIENDLY = true;}
		Goto See;
		
	BloodyThrust2:
		TNT1 A 0 {self.bFRIENDLY = false;}
		BARB A 1 A_Pain;
		BAR1 A 0 A_Chase(null,null);
		BARB B 1 A_FaceTarget;
		TNT1 A 0 HealThing(100);
		TNT1 A 0 ThrustThing(angle*256/360+128, 5, 0, 0);
		TNT1 A 0 ThrustThingZ(0,10,0,1);
		TNT1 A 0 {self.bFRIENDLY = true;}
		Goto See;
		
		
	Death:
		BAR1 A 0;
		
		BEXP AB 2 BRIGHT;
		BEXP C 3 BRIGHT;
		TNT1 A 0 A_Stop;
		//TNT1 A 0 A_SpawnItemEx("BarrelExplosion",0,0,30,0,0,0,0,SXF_NOCHECKPOSITION,0);
		BEXP D 1 BRIGHT;
		TNT1 AAAA 0 a_spawnprojectile("Shrapnel", 64, 0, random(0, 360), 2, random(30, 60));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ShrapnelParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItem("WhiteShockwaveBig");
		TNT1 A 0 A_SpawnItemEx("NewBarrelExploFX", 0, 0, 20);
		TNT1 A 0 A_SpawnItemEx("BarrelKaboom",0,0,15,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Fall;
		
		
		TNT1 AAAA 0 a_spawnprojectile("FireworkSFXType1", 64, 0, random(0, 360), 2, random(30, 60));
		TNT1 AA 0 a_spawnprojectile("HighExplosiveFlames", random(10, 20), 0, random(0, 360), 2, random(10, 90));
		EXPL AA 0 a_spawnprojectile("BigBlackSmokeLarger", 20, 0, random(0, 360), 2, random(10, 90));
		TNT1 AAA 0 a_spawnprojectile("BDExplosionparticles", 64, 0, random(0, 360), 2, random(40, 90));
		TNT1 AAA 0 a_spawnprojectile("BDExplosionparticles", 64, 0, random(0, 360), 2, random(40, 90));
		EXPL A 0 Radius_Quake(2, 24, 0, 15, 0);
		BEXP B 0 BRIGHT A_Scream;
		
		TNT1 AA 0 a_spawnprojectile("BarrelShrapnel1", 25, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("BarrelShrapnel1", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("BarrelShrapnel1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("BarrelShrapnel1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece", random(-35, 35), random(-35, 35));
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece", random(-45, 45), random(-45, 35));
		TNT1 A 0 A_Jump(64, 2);
		TNT1 A 0 A_SpawnItem("ExplosiveBarrelPartialRemains", 0);
		BEXP E 1;
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -15);
		
		TNT1 AAA 8 a_spawnprojectile("ExplosionSmoke", 1, 0, random(0, 360), 2, random(50, 130));
		
		BEXP Z 300 BRIGHT A_BarrelDestroy;
		BEXP Z 5 A_Respawn;
		sTOP;
		
	ExplodeLessEffects:
		BEXP D 0;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Fall;
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ShrapnelParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_SpawnItemEx("BarrelKaboom",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("NewBarrelExploFX", 15, 0, 20);
		TNT1 AAA 0 a_spawnprojectile("FireworkSFXType1", 64, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 a_spawnprojectile("BDExplosionparticles", 64, 0, random(0, 360), 2, random(40, 90));
		EXPL A 0 Radius_Quake(2, 24, 0, 15, 0);
		BEXP B 0 BRIGHT A_Scream;
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		
		TNT1 A 4;
		
		//BEXP Z 300 BRIGHT A_BarrelDestroy
		//BEXP Z 5 A_Respawn
		sTOP;
		
	ExplodeMedium:
		TNT1 A 0 A_SpawnItemEx("BarrelKaboom",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("NewBarrelExploFX", 15, 0, 20);
		TNT1 AA 0 a_spawnprojectile("FireworkSFXType1", 64, 0, random(0, 360), 2, random(30, 60));
		TNT1 AAA 0 a_spawnprojectile("HighExplosiveFlames", random(30, 50), 0, random(0, 360), 2, random(10, 90));
		EXPL A 0 a_spawnprojectile("BigBlackSmokeLarger", 20, 0, random(0, 360), 2, random(10, 90));
		TNT1 A 0 a_spawnprojectile("BDExplosionparticles", 124, 0, random(0, 360), 2, random(40, 90));
		TNT1 A 0 a_spawnprojectile("BDExplosionparticles", 124, 0, random(0, 360), 2, random(40, 90));
		EXPL A 0 Radius_Quake(2, 24, 0, 15, 0);
		BEXP B 0 BRIGHT A_Scream;
		
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-35, 35), random(-35, 35));
		
		TNT1 A 4;
		
		TNT1 AAA 8 a_spawnprojectile("ExplosionSmoke", 1, 0, random(0, 360), 2, random(50, 130));
		
		BEXP Z 300 BRIGHT A_BarrelDestroy;
		BEXP Z 5 A_Respawn;
		sTOP;
		
		
	ExplodebIG:
		TNT1 A 0;
		TNT1 A 0 {self.bFORCERADIUSDMG = true;}
		TNT1 A 1;
		TNT1 AA 0 a_spawnprojectile("HighExplosiveFlames", random(25, 300), 0, random(0, 360), 2, random(10, 90));
		EXPL A 0 Radius_Quake(8, 4, 0, 250, 0);
		TNT1 A 0 A_Explode(500,400, 1, 1, 1);
		BEXP B 0 BRIGHT A_Scream;
		TNT1 A 100;
		
		EXPL A 0 Radius_Quake(4, 4, 0, 250, 0);
		TNT1 A 100;
		sTOP;
		
		
		
	ExplodeHuge:
		TNT1 A 0;
		TNT1 A 0 {self.bFORCERADIUSDMG = true;}
		TNT1 A 1;
		TNT1 A 0 a_spawnprojectile("HighExplosiveFlames", random(100, 500), 0, random(0, 360), 2, random(10, 90));
		EXPL A 0 Radius_Quake(8, 4, 0, 250, 0);
		TNT1 A 0 A_Explode(2000,700, 1, 1, 1);
		BEXP B 0 BRIGHT A_Scream;
		TNT1 A 0  A_SpawnItem("SpawnedExplosion");
		TNT1 A 100;
		
		EXPL A 0 Radius_Quake(4, 4, 0, 250, 0);
		TNT1 A 100;
		sTOP;
		
	ExplodeNuke:
		TNT1 A 0;
		TNT1 A 0 {self.bFORCERADIUSDMG = true;}
		TNT1 A 1;
		TNT1 A 0 a_spawnprojectile("SpawnedExplosion", 30, 0, random(0, 360), 2, random(10, 60));
		EXPL A 0 Radius_Quake(8, 4, 0, 250, 0);
		TNT1 A 0 A_Explode(2000,700, 1, 1, 1);
		BEXP B 0 BRIGHT A_Scream;
		TNT1 A 8;
		TNT1 A 0 A_Explode(2000,1200, 1, 1, 1);
		TNT1 A 100;
		
		EXPL A 0 Radius_Quake(4, 4, 0, 250, 0);
		TNT1 A 100;
		sTOP;
		
		
		
	Active:
		BAR1 B 1 A_FaceTarget;
 		//TNT1 A 0 A_JumpIfInTargetInventory("HasBarrel",1, "See");
		//TNT1 A 0 A_JumpIfInTargetInventory("HasBurningBarrel",1, "See");
		//TNT1 A 0 A_JumpIfInTargetInventory("PowerStrength",1, "GiveBarrel");
		Goto See;
	Death.Fatality:
		TNT1 A 0 A_NoBlocking;
		//TNT1 A 0 A_GiveToTarget("GoSpecial", 1);
		//TNT1 A 0 A_GiveToTarget("HasBarrel", 1);
		Stop;
		
	GiveBarrel:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 {self.bSHOOTABLE = true;}
		BAR1 A 1 A_FaceTarget;
		BAR1 ABCD 2;
		TNT1 A 0 A_PlaySound("barrel/pain");
		Stop;
		
	Death.Massacre:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 1;
		TNT1 A 0 A_SPawnItem("ExplosiveBarrel1");
		Stop;
		
	Death.BHFT:
	Death.BHFTOnBarrel:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FAll;
		TNT1 A 1;
		Stop;
		
	Death.Kick:
	Death.ExtremePunches:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 {self.bTHRUACTORS = true;}
		TNT1 A 1;
		TNT1 A 0 A_SpawnItemEx("ExplosiveBarrel",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION);
		TNT1 A 1;
		Stop;
		
		
}
}


CLASS GotBloody : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}



CLASS BarrelShrapnel1 : ACTOR { 
Default {
	
	Radius 2;
	Height 2;
	Speed 8;
	Mass 1;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	//+CLIENTSIDEONLY
	+THRUACTORS;
	+FLOORCLIP;
	+DOOMBOUNCE;
	+NOGRAVITY;
	BounceFactor 0.5;
	Gravity 0.9;
	Mass 1;
}
States
{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Underwater");
		BRPT ABCDEFGH 1;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		Goto Spawn2;
	Spawn2:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Underwater");
		BRPT ABCDEFGH 2;
		Loop;
		
	Death:
		TNT1 A 0;
		BRPT I 300;
		BRPT IIIIIIIII 2 A_FadeOut(0.1);
		Stop;
	Underwater:
	Splash:
		Goto Death;
}
}






CLASS GreatKaboom: DeadMarine { 
States
{
	Spawn:
		TNT1 A 50;
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -15);
		TNT1 AAAA 0 a_spawnprojectile("ExplosionSpawner", 20, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAA 0 a_spawnprojectile("ExplosionSpawner", 20, 0, random(0, 360), 2, random(0, 180));
		Stop;
}
}


CLASS UltraKaboom: DeadMarine { 
States
{
	Spawn:
		TNT1 A 50;
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -15);
		TNT1 AAAA 0 a_spawnprojectile("ExplosionSpawner", 20, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAA 0 a_spawnprojectile("ExplosionSpawner", 20, 0, random(0, 360), 2, random(0, 180));
		Stop;
}
}


CLASS BarrelKaboom: DeadMarine { 
States
{
	Spawn:
		TNT1 A 1;
		TNT1 AAAA 0 a_spawnprojectile("ExplosionSpawner", 20, 0, random(0, 360), 2, random(0, 180));
		Stop;
}
}







CLASS ExplosionSpawner : ACTOR { 
Default {
	
	+MISSILE;
	+FORCEXYBILLBOARD;
	//+DOOMBOUNCE
	// +BLOODSPLATTER 
	damage 0;
	radius 6;
	height 6;
	speed 40;
	renderstyle "Add";
	alpha 0.9;
	scale .01;
	BounceFactor 0.5;
	Decal "FireworxScorch";
}
states
{
	Spawn:
		TNT1 AAAA 2 A_SpawnItem("SpawnedExplosion");
		Stop;
	Death:
		MISG A 1;
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 10;
		Stop;
	XDeath:
		MISG A 1;
		TNT1 A 10;
		Stop;
}
}





CLASS SpawnedExplosion : ACTOR { 
Default {
	
	+NOCLIP;
	+NOGRAVITY;
}
states
{
	Spawn:
		TNT1 A 2;
		TNT1 A 2 A_PlaySound("FAREXPL");
		EXPL A 0 a_spawnprojectile("CasingSmoke", 0, 0, random(0, 360), 2, random(0, 360));
		EXPL A 0 a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		Stop;
}
}






CLASS SpawnedFlamers : ACTOR { 
Default {
	
	+NOCLIP;
	+NOGRAVITY;
	DamageType "Flames";
}
states
{
	Spawn:
		TNT1 A 2;
		TNT1 A 0 A_Explode(12,40);
		TNT1 AAAA 0 a_spawnprojectile("CoolandNewFlameTrails", 0, 0, random(0, 360), 2, random(0, 360));
		Stop;
}
}








CLASS FireworkSFXType1 : ACTOR { 
Default {
	
	Radius 4;
	Height 4;
	Speed 18;
	PROJECTILE;
	+THRUGHOST;
	RenderStyle "Add";
	+MISSILE;
	-NOGRAVITY;
	Gravity 1;
	Alpha 1.0;
}
States
{
	Spawn:
		//TNT1 A 0 a_spawnprojectile("FlameTrails", 2, 0, random(170, 200), 2, random(-20, 20))
		TNT1 A 0 A_SpawnItem("FlameTrails");
		TNT1 A 1 A_SpawnItem("Red_FlareSmall");
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 2, 0, random(0, 360), 2, random(0, 290));
		TNT1 A 1 A_SpawnItem("Red_FlareSmall");
		Loop;
		
	Death:
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		Stop;
}
}





CLASS BigExplosion1112: DeadMarine { 
States
{
	Spawn:
		TNT1 A 1;
		EXPL A 0 Radius_Quake(2, 100, 0, 22, 0);
		TNT1 AAA 0 a_spawnprojectile("FireworkSFXType1", 64, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 a_spawnprojectile("ExplosionSpawner", 10, 0, random(0, 360), 2, random(80, 90));
		TNT1 AAA 0 a_spawnprojectile("ExplosionSpawner", 10, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 10;
		TNT1 AAAA 0 a_spawnprojectile("FireworkSFXType1", 94, 0, random(0, 360), 2, random(30, 60));
		EXPL A 0 Radius_Quake(3, 100, 0, 22, 0);
		TNT1 A 0 a_spawnprojectile("ExplosionSpawner",10, 0, random(0, 360), 2, random(80, 90));
		TNT1 A 10;
		TNT1 AAAAAAA 0 a_spawnprojectile("FireworkSFXType1", 128, 0, random(0, 360), 2, random(30, 60));
		EXPL A 0 Radius_Quake(6, 100, 0, 22, 0);
		TNT1 A 0 a_spawnprojectile("ExplosionSpawner", 10, 0, random(0, 360), 2, random(80, 90));
		TNT1 A 0 a_spawnprojectile("ExplosionSpawner", 10, 0, random(0, 360), 2, 90);
		TNT1 A 200;
		Stop;
}
}

CLASS KaboomWithSound: DeadMarine { 
States
{
	Spawn:
		TNT1 A 1;
		TNT1 AA 0 a_spawnprojectile("ExplosionSpawner", 20, 0, random(0, 360), 2, random(0, 180));
		TNT1 AA 0 a_spawnprojectile("ExplosionSpawner", 20, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 A 0 A_PlaySound("Explosion", 1);
		TNT1 A 300;
		Stop;
}
}