// --------------------------------------------------------------------------
//
// Grenade Launcher
//
// --------------------------------------------------------------------------
CLASS Excavator : weapon_slot_5_proto_class
{
enum weapon_mode
{ digger_charge, drop_charge };

weapon_mode actual_weapon_mode;

Default
{
	Weapon.SlotNumber 5;
	Weapon.SelectionOrder 1;
	Weapon.slotpriority 1;

	Weapon.AmmoUse1 0;
	Weapon.AmmoUse2 0;
	Weapon.AmmoGive 5;
	Weapon.AmmoType1 "HighExplosiveGrenadeRounds";
	Weapon.AmmoType2 "ExcavatorRounds";
	+FLOORCLIP;
	+DONTGIB;
	Inventory.PickupSound "misc/ROCKBOXA";
	+WEAPON.NOAUTOAIM;
	+WEAPON.EXPLOSIVE;
	+WEAPON.NOAUTOFIRE;
	Tag "Excavator Launcher";
	Inventory.PickupMessage "You got the Excavator! (Slot 5)";
}

override bool, bool weapon_dual_and_special()
{return false, true;}

override void activate_special()
{ self.set_weapon_state("change_charge_type"); }

States
{
	Spawn:
		5DUN A -1;
	Stop;

	Select:
		TNT1 A 0 A_Overlay(-10, "FirstPersonLegsStand");
		TNT1 A 1 A_Raise(90);
	Wait;

	Ready:
		TNT1 A 0 A_PlaySound("RLANDRAW");
		5DKS DCBA 1;
	Ready_loop:
		//TNT1 A 0 A_JumpIfInventory("DropShotMode",1,"Ready2");
		5DKG A 1
		{
			if(invoker.actual_weapon_mode == drop_charge) {invoker.change_weapon_psprite("6DKG");}
			A_Weaponready(WRF_allowreload);
		}
	loop;
	//dummy state to load in memory 6dkg sprites names
	6DKG A 1;

	Fire:
		TNT1 A 0 A_WeaponOffset(0,32);
		TNT1 A 0 A_JumpIfInventory("ExcavatorRounds",1,1);
	Goto Reload;
		TNT1 A 0 { if(invoker.actual_weapon_mode == drop_charge) {invoker.set_weapon_state("FireDropShot");} }
		TNT1 AAAAAA 0 BRIGHT a_fireprojectile("ShotgunParticles", random(-16,16), 0, -1, random(-9,9));
		TNT1 A 0 A_FireBullets(0, 0, 1, 50, "shotpuff", 0, 130);
		TNT1 A 0 a_fireprojectile("RedFlareSpawn",-5,0,0,0);
		TNT1 A 0 A_PlaySound ("excavator/firedigger", 18);
		TNT1 A 0 A_AlertMonsters;
		TNT1 A 0 BRIGHT a_fireprojectile("Alerter");
		TNT1 A 0 A_ZoomFactor(0.96);
		TNT1 A 0 a_fireprojectile("ExcavatorDrill", 0, False, 0, 0, True, -3);
		5DKF A 2 BRIGHT;
		TNT1 A 0 A_TakeInventory("ExcavatorRounds",1);
		TNT1 A 0 a_fireprojectile("ShakeYourAssDouble", 0, 0, 0, 0);
		5DKF B 1 BRIGHT A_ZoomFactor(0.97);
		5DKF C 1 BRIGHT A_ZoomFactor(0.98);
		5DKF D 1 BRIGHT A_ZoomFactor(0.99);
		TNT1 A 0 A_ZoomFactor(1.0);
		5DKG AAAAAAA 1 A_WeaponReady(WRF_NOPRIMARY);
		TNT1 A 0 A_PlaySound("RLCYCLE2", 5);
		5DKG AAAAA 1 A_WeaponReady(WRF_NOPRIMARY);
		5DKG A 1 A_ReFire;
	Goto Ready_loop;
		
	FireDropShot:
		TNT1 AAAAAA 0 BRIGHT a_fireprojectile("ShotgunParticles", random(-16,16), 0, -1, random(-9,9));
		TNT1 A 0 A_FireBullets(0, 0, 1, 50, "shotpuff", 0, 130);
		TNT1 A 0 a_fireprojectile("RedFlareSpawn",-5,0,0,0);
		TNT1 A 0 A_PlaySound ("excavator/firedropshot", 18);
		TNT1 A 0 A_AlertMonsters;
		TNT1 A 0 BRIGHT a_fireprojectile("Alerter");
		TNT1 A 0 A_ZoomFactor(0.96);
		TNT1 A 0 a_fireprojectile("ExcavatorDropShot", 0, False, 0, 0, True, 0);
		6DKF A 2 BRIGHT;
		TNT1 A 0 A_TakeInventory("ExcavatorRounds",1);
		TNT1 A 0 a_fireprojectile("ShakeYourAssDouble", 0, 0, 0, 0);
		6DKF B 2 BRIGHT A_ZoomFactor(0.97);
		6DKF C 2 BRIGHT A_ZoomFactor(0.98);
		6DKF D 1 BRIGHT A_ZoomFactor(0.99);
		TNT1 A 0 A_ZoomFactor(1.0);
		6DKG AAAAAAA 1 A_WeaponReady(WRF_NOPRIMARY);
		TNT1 A 0 A_PlaySound("RLCYCLE2", 5);
		6DKG AAAAA 1 A_WeaponReady(WRF_NOPRIMARY);
		6DKG A 1 A_ReFire;
	Goto Ready_loop;















	change_charge_type:
	drop_charge_type:
		tnt1 a 0 { if(invoker.actual_weapon_mode == drop_charge) {invoker.set_weapon_state("SwitchToDigger");} }
		TNT1 A 0 A_Print("Drop Charge Mode Activated");
		5DKF D 2;
		5DKS ABC 2;
		TNT1 A 0 A_PlaySound("excavator/switch");
		5DKS CBA 2;
		6DKF D 2;
		6DKG A 2{invoker.actual_weapon_mode = drop_charge; }
	Goto Ready_loop;
		
	SwitchToDigger:
		TNT1 A 0 A_Print("Drill Charge Mode Activated");
		6DKF D 2;
		5DKS ABC 2;
		TNT1 A 0 A_PlaySound("excavator/switch");
		5DKS CBA 2;
		5DKF D 2;
		5DKG A 2 { invoker.actual_weapon_mode = digger_charge; }
	Goto Ready_loop;

	AltFire:
		TNT1 A 0 A_WeaponOffset(0,32);
		//TNT1 A 0 A_JumpIfInventory("DropShotMode", 1, "DetonateDropShot");
		7DKG A 1 Thing_Projectile(1743,205,0,0,0);
		DETO B 0 A_PlaySound("excavator/detonate");
		TNT1 A 0 Thing_ReMove(1743);
		7DKG BC 1;
		7DKG C 1;
	Goto Ready_loop;
		
	DetonateDropShot:
		7DKG A 1;
		MGLG B 0;
		MGLG B 0 Thing_Projectile(1744,208,0,0,0);
		DETO B 0 A_PlaySound("excavator/detonate");
		TNT1 A 0 Thing_ReMove(1744);
		7DKG BC 1;
		7DKG C 1;
	Goto Ready_loop;
		





	Reload:
		5DKR A 1 A_WeaponReady;
		TNT1 A 0 A_JumpIfInventory("ExcavatorRounds",5,61);
		TNT1 A 0 A_JumpIfInventory("HighExplosiveGrenadeRounds",1,3);
	Goto Ready_loop;
		TNT1 AAAA 0;
		TNT1 A 0 A_PlaySound("5OCKLOAD", 3);
		5DKR ABCDE 2;
		TNT1 A 0 a_fireprojectile("RocketCaseSpawn",-30,0,-4,-4);
		5DKR EFJKLMNOP 2;
		TNT1 AAAA 0;
		TNT1 A 0 A_PlaySound("5OCKSLAP", 4);
		5DKR QRST 2;
		TNT1 A 0 A_PlaySound("RLCYCLE2", 2);
		5DKR A 10;
		TNT1 A 0;
		TNT1 AAA 0;
		
		TNT1 AAAAAA 0;
		TNT1 A 0 A_JumpIfInventory("ExcavatorRounds",5,15);
		TNT1 A 0 A_JumpIfInventory("HighExplosiveGrenadeRounds",1,3);
	Goto Ready_loop;
		TNT1 AAAAAA 0;
		TNT1 A 0 A_Giveinventory("ExcavatorRounds",1);
		TNT1 A 0 A_Takeinventory("HighExplosiveGrenadeRounds",1);
	Goto Reload+45;
		
		TNT1 AAAAAAAAA 0;
		TNT1 A 0;
		MGLG A 0 A_Refire;
	Goto Ready_loop;


	Deselect:
		TNT1 A 0 A_PlaySound("weapons/changing", 1);
		5DKS ABCD 1;
		TNT1 A 0 A_Lower(70);
	Wait;
		



	

		
	
		

		
		

		
		
		

		
	FlashKicking:
		5DKK A 1;
		5DKK B 1;
		5DKK C 1;
		5DKK D 3;
		5DKK E 3;
		5DKK D 3;
		5DKK C 1;
		5DKK B 1;
		5DKK AAA 1;
		Stop;
		
	FlashAirKicking:
		5DKK A 1;
		5DKK B 1;
		5DKK C 1;
		5DKK D 3;
		5DKK E 3;
		5DKK D 3;
		5DKK C 1;
		5DKK B 1;
		5DKK AA 1;
		5DKK AA 1;
		Stop;
		
	FlashSlideKicking:
		5DKK AA 2;
		5DKK BBCCDDEDDCBA 2 ;
		Stop;
		
	FlashSlideKickingStop:
		//TNT1 A 0
		5DKK AAAA 1;
		5DKK A 1;
		Stop;
		
	FlashPunching:
		5DKK A 1;
		5DKK B 1;
		5DKK C 1;
		5DKK D 3;
		5DKK E 3;
		5DKK D 3;
		5DKK C 1;
		5DKK B 1;
		5DKK AA 1;
		5DKK AAA 1;
		Stop;
	}
}