CLASS pb_Baron_of_Hell : Baron_guts_death_right
{ 
Default
{
	//SpawnID 2240;
	Scale 1.1;
	GibHealth 25;
	Health 1100;
	MaxStepHeight 24;
	MaxDropOffHeight 32;
	Speed 8;

	+QUICKTORETALIATE;
	+DONTHARMSPECIES;
	+NOBLOODDECALS;
	monster;

	PainChance "Stun", 255;
	PainChance "Saw", 100;
	PainChance "Cut", 100;
	PainChance "Kick", 100;
	PainChance "ExtremePunches", 224;
	PainChance "CallingTheBaronAFaggot", 255;
	PainChance "Head", 120;
	PainChance 25;
	PainChance "Explosive", 255;

	damagefactor "Crush", 10.0;
	damagefactor "GibRemoving", 0.0;
	damagefactor "TeleportRemover", 0.0;
	damagefactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	damagefactor "SSG", 0.75;
	damagefactor "Head", 0.6;
	damagefactor "DontCallTheBaron", 0.0;
	DamageFactor "CauseObjectsToSplash", 0.0;
	damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0; damagefactor "Blood", 0.0;
	damagefactor "Shrapnel", 0.4;

	Species "Noble";
	PainSound "PSXDPN";
	BloodType "PB_Blood", "AxeBlood", "AxeBlood";
	BloodColor "Dark";
	Obituary "%o was brutalized by a Baron of Hell.";

	////DropItem "DemonStrengthRune", 9;
	////DropItem "Demonpickup2", 76;
	////DropItem "Demonpickup2", 76;
}

States
{		
	Spawn:
 	Stand:
		//TNT1 A 0 A_JumpIfInventory("ZombiemanFatality", 1, "FatalityZombieman");
		//TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
		//TNT1 A 0 A_JumpIfInventory("ImpFatality3", 1, "FatalityImp");
		//TNT1 A 0 A_JumpIfInventory("DemonFatality", 1, "FatalityDemon");
		BOSS B 10 A_Look();
	Loop;

	See:
		//TNT1 A 0 A_JumpIfInventory("HasExplosiveBarrel", 1, "MissileBarrel");
        BTS3 ABC 1;
		TNT1 A 0 A_FaceTarget();
		BTS3 DEDFD 4;
		BTS3 CBA 1;
		TNT1 A 0 A_FaceTarget();
		BTS3 CBA 1;
		TNT1 A 0 HealThing(200);
	See2:
	See4:
		TNT1 A 0 pb_monster_memory();
		BOSS AA 3 A_Chase();
		TNT1 A 0 A_PlaySound("baron/step", 5);
		BOSS BBCC 3 A_Chase();
		TNT1 A 0 A_PlaySound("baron/step", 5);
		BOSS DD 3 A_Chase();
		TNT1 A 0 
		{
			if(target is "proto_cyberdemon" || target is "proto_spider_mind")
			{setstatelabel("CheckRetreat");}
		}
	Loop;
		

		
	Idle:
	LookingForPlayer:
		BOSS BBB 10 A_Look();
		TNT1 A 0 {self.angle += randompick(-40, 40);}
		BOSS BBBBBB 10 A_Look();
		BOSS AA 2
		{
			A_Look();
			A_Wander();
		}
		TNT1 A 0 A_PlaySound("baron/step", 5);
		BOSS BBCC 2
		{
			A_Look();
			A_Wander();
		}
		TNT1 A 0 A_PlaySound("baron/step", 5);
		BOSS DD 2
		{
			A_Look();
			A_Wander();
		}
	loop;


	Melee:
		TNT1 A 0
		{
			if(target is "proto_cyberdemon" || target is "proto_spider_mind")
			{setstatelabel("CheckRetreat");}
		}
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("BaronAttackOnBarrel",10,0,0,0);
		BOSS E 1;
		//TNT1 A 0 A_JumpIfInventory("HasExplosiveBarrel", 1, "MissileBarrel");
		BOSS E 6;
		TNT1 A 0 A_PlaySound("weapons/gswing");
		BOSS F 6 A_FaceTarget();
		BOSS G 6 a_spawnprojectile("BaronAttack",10,0,0,0);
	Goto See2;
		
	Melee2:
		BOSS EF 6 A_FaceTarget();
		BOSS G 6 a_spawnprojectile("BaronAttack",10,0,0,0);
		//TNT1 A 0 A_JumpIfInventory("ZombiemanFatality", 1, "FatalityZombieman");
		//TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
		//TNT1 A 0 A_JumpIfInventory("DemonFatality", 1, "FatalityDemon");
		//TNT1 A 0 A_JumpIfInventory("ImpFatality3", 1, "FatalityImp");
	Goto See2;

	RAGE:
		TNT1 A 0 A_CheckSight("See");
		BTS3 ABC 2;
		BTS3 DEDF 3;
		BTS3 DEDF 3;
		BTS3 CBA 2;
		TNT1 A 0 HealThing(200);
		TNT1 A 0 A_Jump(96, "SpecialAttack");
	Goto See2;



	Missile:
		BOSS A 1
		{
			if(target is "proto_cyberdemon" || target is "proto_spider_mind")
			{setstatelabel("CheckRetreat");}
		}
		//TNT1 A 0 A_TakeInventory("StopKickingMyBallsMotherFucker", 1)
		//TNT1 A 0 A_JumpIfInventory("ZombiemanFatality", 1, "FatalityZombieman");
		//TNT1 A 0 A_JumpIfInTargetInventory("TypeZombieman", 1, "See2");
		//TNT1 A 0 A_JumpIfInTargetInventory("TypeSergeant", 1, "See2");
		TNT1 A 0 A_Jump(64, "SpecialAttack");
		//TNT1 A 0 A_TakeInventory("CantFire", 1);
		TNT1 A 0 A_JumpIfCloser(900, 3);
		//TNT1 A 0 a_spawnprojectile("MonsterTargetCheck", 34, 0, 0, 0);
		//TNT1 A 0 a_spawnprojectile("MonsterTargetCheckFaster", 34, 0, 0, 0);
		BOSS F 3 A_FaceTarget();
		//TNT1 A 0 A_JumpIfInventory("CantFire",1, "See4");
		BOSS EEEEE 2
		{
			A_FaceTarget();
			a_spawnprojectile("FlameTrails", 78, 40, random(0, 360), 2, random(70, 110));
			a_spawnprojectile("BallGettingReadygreen", 79, 40, random(0, 140), 2, random(0, 160));
		}
		BOSS F 3 A_FaceTarget();
		BOSS G 8 a_spawnprojectile("BaronBall", 36, 0, 0, 1);
		//BOSS G 8 a_spawnprojectile("ThrowedZombieMan2", 36, 0, 0, 1)
		//TNT1 A 0 A_TakeInventory("ComingToGetTheBarrel", 1);
	Goto See2;
		
	SpecialAttack:
		BOSS RQ 4 A_FaceTarget();
		TNT1 A 0 A_Playsound("SavageImp/Attack");
		BOSS PPPPPPPPPPPPP 2
		{
			A_FaceTarget();
			a_spawnprojectile("FlameTrails", 78, 40, random(0, 360), 2, random(70, 110));
			a_spawnprojectile("BallGettingReadygreen", 79, 40, random(0, 140), 2, random(0, 160));
			a_spawnprojectile("BallGettingReadygreen", 79, -40, random(0, 140), 2, random(0, 160));
			a_spawnprojectile("FlameTrails", 78, -40, random(0, 360), 2, random(70, 110));
		}


		BOSS QQ 3
		{
			A_FaceTarget();
			a_spawnprojectile("FlameTrails", 58, 30, random(0, 360), 2, random(70, 110));
			a_spawnprojectile("FlameTrails", 58, -30, random(0, 360), 2, random(70, 110));
		}
		BOSS Q 3 A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile("FlameTrails", 48, 30, random(0, 360), 2, random(70, 110));
		TNT1 A 0 bright a_spawnprojectile("FlameTrails", 48, -30, random(0, 360), 2, random(70, 110));

		BOSS R 6
		{
			a_spawnprojectile("BaronBall", 36, 15, 0, 11);
			a_spawnprojectile("BaronBall", 36, 15, 9, 11);
			a_spawnprojectile("BaronBall", 36, 15, -9, 11);
			a_spawnprojectile("BaronBall", 36, 15, 22, 11);
			a_spawnprojectile("BaronBall", 36, 15, -22, 11);
		}
		//TNT1 A 0 A_TakeInventory("ComingToGetTheBarrel", 1);
	Goto See2;













		

		
		
	CheckRetreat:
		TNT1 A 0 A_JumpIfCloser(600, "Retreat");
	Goto Missile+5;
		
	Retreat:
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0);
		BOSS DDDD 2 {A_Recoil(2);A_FaceTarget();}
		BOSS CCCC 2 {A_Recoil(2);A_FaceTarget();}
		BOSS BBBB 2 {A_Recoil(2);A_FaceTarget();}
		BOSS AAAA 2 {A_Recoil(2);A_FaceTarget();}
	Goto Missile+5;
		//ComingToGetTheBarrel
	Pain.CallingTheBaronAFaggot:
		//TNT1 A 0 A_GiveInventory("ComingToGetTheBarrel", 1);
	Goto See2;
		
	MissileBarrel:
		BOBA A 1 {A_Chase(null,null); self.bNOPAIN = true;}
		BOBA ABC 4;
		BOBA D 1 {A_PlaySound("baron/sight"); }//A_SpawnItem("BaronHoldingBarrel", 0, 76,0);}
		BOBA D 8;
		BOBA E 16;
		BOBA D 8;		
	ThrowBarrel:
		BOSS P 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("ThrowedBarrel", 46, 15, 0, 11);
		BOSS Q 4 A_FaceTarget();
		BOSS R 8;
		//TNT1 A 0 A_TakeInventory("ComingToGetTheBarrel", 1);
		//TNT1 A 0 A_TakeInventory("HasExplosiveBarrel", 1);
		BOBA A 0 {self.bNOPAIN = false;}
	Goto See2;
		
	WithBarrelLookFOrTheplayer:
		TNT1 A 0 A_ClearTarget();
		BOSS P 2 A_Chase();
	Goto See2;

	Pain:
		BOSS H 3;
		BOSS H 3 A_Pain();
	Goto See2;
		
	Possession:
		TNT1 A 0 {self.binvulnerable = true;}
		BOSS H 3;
		BOSS H 3 A_Pain();
 		TNT1 A 0 {self.binvulnerable = false;}
	Goto See;
		
	Pain.Kick:
	Pain.ExtremePunches:
		TNT1 A 0 {self.bMISSILEMORE = true; self.bMISSILEEVENMORE = true;}
		//TNT1 A 0 A_JumpIfInventory("StopKickingMyBallsMotherFucker", 1, "Missile");
		//TNT1 A 0 A_GiveInventory("StopKickingMyBallsMotherFucker", 1);
		TNT1 A 0 ThrustThingZ(0,15,0,1);
		TNT1 A 0 {self.bNOPAIN = true;}
		BNRJ ABCDABCDABCDABCD 4
		{
			if(frame == 3) A_Pain();
		}
		TNT1 A 0 {self.bNOPAIN = false;}
	Goto Missile;

	Death:
		TNT1 A 0 A_Jump(30, "Death.Arm");
		TNT1 A 0 A_Jump(152, "Death2", "Death3", "Death4");
		BADD A 6 A_Scream();
		BADD BC 6;
		BADD D 6 A_BossDeath();
		BADD EF 6;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		BADD G -1 simple_death_handler();
	Stop;
		
	Death.Arm:
		TNT1 A 0 a_spawnprojectile("XDeathBaronOfHellArm", 55, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 A_Fall();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_BossDeath();
		TNT1 A 0 A_SpawnItem("baron_no_arm_death");
	Stop;
		
	Death2:
		BADD H 6 A_Scream();
		BADD IJ 6;
		BADD K 6 A_BossDeath();
		BADD LM 6 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		BADD N -1 simple_death_handler();
	Stop;

	Death3:
		TNT1 A 0 A_Jump(16, "DeathGutless2");
		TNT1 A 0 A_NoBlocking();
		BSA1 F 3 A_Scream();
		BSA1 G 3 A_BossDeath();
		BSA1 HIJ 6;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		BSA1 K 6;
		BSA1 K -1 simple_death_handler();
	Stop;
		
	Death4:
		TNT1 AA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeath1", 42, 0, random(150, 210), 2, random(0, 40));
		BADD U 10 A_Scream();
		BADD V 10;
		BADD W 10 A_BossDeath();
		BADD X 9 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		BADD X -1 simple_death_handler();
	Stop;
		
	XDeath:
		TNT1 A 0 a_spawnprojectile("BaronXDeath", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBaronHead5", 62, 0, random(0, 360), 2, random(0, 160));
		BXDE B  0 A_xScream();
		BXDE C  0 A_BossDeath();
		BXDE D  0 A_NoBlocking();
	Stop;

	Death.ExplosiveImpact:
	Death.ExtremePunches:
		TNT1 A 0 A_BossDeath();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 ThrustThingZ(0,35,0,1);
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHellKnightLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 A_Jump(255, "Death.ExplosiveImpact1", "Death.ExplosiveImpact2");
	Death.ExplosiveImpact1:
		BOH3 A  8 A_Scream();
		BOH3 B  8 A_NoBlocking();
		BOH3 CCCCCC  8 A_CheckFloor("Land1");
	Land1:
		TNT1 A 0 A_SpawnItem("DeadBaronExplosiveImpact1", 1);
	Stop;
		
	Death.ExplosiveImpact2:
		BOH3 E  8 A_Scream();
		BOH3 F  8 A_NoBlocking();
		BOH3 GGGGGG  8 A_CheckFloor("Land2");
	Goto Land2;
		
	Land2:
		TNT1 A 0 A_SpawnItem("DeadBaronExplosiveImpact2", 1);
	Stop;
		
	Death.Desintegrate:
		TNT1 A 0 A_BossDeath();
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		
		TNT1 AAAA 0 a_spawnprojectile("SuperWallredBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		
		TNT1 AAAA 0 a_spawnprojectile("PlasmaParticleX", 48, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("PlasmaParticleX", 42, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("PlasmaParticleX", 48, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("PlasmaParticleX", 42, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallredBlood", 32, 0, random(170, 190), 2, random(0, 40));
		BRUD LM 5 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		BRUD NOP 5  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAAAA 0 a_spawnprojectile("brutal_LiquidBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("RevenantDust2", 30, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("PlasmaParticleX", 48, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("PlasmaParticleX", 42, 0, random(0, 360), 2, random(0, 360));
		BRUD QRS 5 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("PlasmaParticleX", 42, 0, random(0, 360), 2, random(0, 360));
		BRUD TUV 5;
		BRUD WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW 8 a_spawnprojectile("ExplosionSmoke", 24, 0, random(0, 180), 2, random(0, 180));
		BRUD W -1;
	Stop;
		
	Death.Cut:
	Death.Saw:
	Death.Crush:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_BossDeath();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("brutal_LiquidBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfBOH", 24, 0, random(0, 360), 2, random(0, 160));
		BSA1 PPPPPPPPQQQQQQRRRRRSSSSSS 2 a_spawnprojectile("brutal_LiquidBlood", 30, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		BSA1 TTTTTTTTUUUUUUUU 1 a_spawnprojectile("brutal_LiquidBlood", 10, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		BSA1 U -1 simple_death_handler();
	Stop;

	Death.Tear:
		BS12 A 6;
		TNT1 AAAAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("brutal_LiquidBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 45, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 45, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeathBrain1", 60, 0, random(0, 360), 2, random(0, 160));
		BS12 B 6 A_XScream();
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		BS12 C 6 A_NoBlocking();
		TNT1 A 0 A_BossDeath();
		TNT1 AA 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		BS12 DEF 6  {pb_blood_and_gore_event.much_blood(self);}
		BS12 G -1;
	Stop;
		
	Death.SSG:
	Death.Railgun:
		TNT1 AAAA 0 a_spawnprojectile("SuperWallredBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("XDeathStomach", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 45, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 45, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_BossDeath();
		TNT1 AAAAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("brutal_LiquidBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBaronOfHellTorso", 48, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBaronOfHellArm", 55, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBaronHead5", 62, 0, random(0, 360), 2, random(50, 130));
		BBO2 AABCD 10;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		BBO2 D -1 simple_death_handler();
	Stop;
		
	Death.Shotgun:
		//TNT1 A 0 A_JumpIfInTargetInventory("SSGSelected", 1, "Death.SSG");
		TNT1 A 0 A_JumpIfCloser(160, "Death.Blast");
		TNT1 A 0 A_Jump(16, "DeathGutless2");
	Goto Death;
	Death.CutLess:
		TNT1 A 0 A_Jump(24, "Death.Cut");
		TNT1 A 0 A_Jump(36, "DeathGutless");
		TNT1 A 0 A_Jump(210, "DeathBrutalized");
	Goto Death;

	DeathGutless:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_BossDeath();
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		tnt1 a 0 a_jump(36, 1);
		KSA8 A 6 A_SpawnItem("Baron_guts_death_left");
		BSA1 F 6 A_SpawnItem("Baron_guts_death_right");
	Stop;


	Death.Blast:
	Death.Nailgun:
		TNT1 A 0 A_Jump(129, "DeathBlast2");
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_BossDeath();
		TNT1 A 0 a_spawnprojectile("XDeathBaronOfHellArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBaronHead5", 62, 0, random(0, 360), 2, random(50, 130));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 46, 0, random(130, 210), 2, random(0, 40));
		TNT1 AAAAAAAA 0 a_spawnprojectile("brutal_LiquidBlood", 42, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallredBlood", 52, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 44, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		BSA1 AAAAAAAAAA 1 a_spawnprojectile("brutal_LiquidBlood", 40, 0, random(0, 360), 2, random(30, 60));
		BSA1 BBBBCCCCDDD 2 a_spawnprojectile("brutal_LiquidBlood", 25, 0, random(0, 360), 2, random(30, 60));
		BSA1 EEEEEEEE 2 a_spawnprojectile("brutal_LiquidBlood", 10, 0, random(0, 360), 2, random(30, 60));
		BSA1 E -1 simple_death_handler();
	Stop;
		
	DeathBlast2:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_BossDeath();
		TNT1 AAAAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 46, 0, random(130, 210), 2, random(0, 40));
		TNT1 AAAAAAAA 0 a_spawnprojectile("brutal_LiquidBlood", 42, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallredBlood", 52, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 44, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		BSA1 VVVVVVVVV 1 a_spawnprojectile("brutal_LiquidBlood", 40, 0, random(0, 360), 2, random(30, 60));
		BSA1 WWWXXXYYY 2 a_spawnprojectile("brutal_LiquidBlood", 25, 0, random(0, 360), 2, random(30, 60));
		BSA1 ZZZZZZ 2 a_spawnprojectile("brutal_LiquidBlood", 10, 0, random(0, 360), 2, random(30, 60));
		BSA1 Z -1 simple_death_handler();
	Stop;
		
	Death.head:
		//TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		//TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
		TNT1 A 0 A_SpawnItem("BaronOfHellHeadExplode", 0, 62);
		TNT1 A 0 A_Jump(128, "HeadExplode2");
		BADH A 9;
		BADH B 9;
		BADH C 9 A_BossDeath();
		BADH D  9 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		BADH D -1 simple_death_handler();
	Stop;

	HeadExplode2:
		TNT1 A 0 A_BossDeath();
		TNT1 A 0 A_NoBlocking();
		BSA2 AAAAA 2 a_spawnprojectile("brutal_LiquidBlood", 57, 0, random(0, 360), 2, random(30, 60));
		BSA2 BCD 7;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		BSA2 E 1 a_spawnprojectile("brutal_LiquidBlood", 9, 0, random(0, 360), 2, random(30, 60));
		BSA2 E -1 simple_death_handler();
	Stop;

	Death.decaptate:
		TNT1 AAAAA 0 a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathBaronHead5", 62, 0, random(0, 360), 2, random(50, 130));
		BADH A 9;
		BADH B 9;
		BADH C 9 A_BossDeath();
		BADH D  9 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		BADH D -1 simple_death_handler();
	Stop;

	Death.Fatality:
		TNT1 A 0 A_Pain();
		//TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, 1);
	Goto XDeath;
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("BaronFatality", 1);
		TNT1 A 1 A_NoBlocking();
		TNT1 A 0 A_BossDeath();
	Stop;

	Death.SuperPlasma:
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_BossDeath();
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAA 0 a_spawnprojectile("PlasmaParticleX", 48, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("PlasmaParticleX", 42, 0, random(0, 360), 2, random(0, 360));
		BOSC ABC 7 a_spawnprojectile("ExplosionSmoke", 28, 0, random(0, 180), 2, random(0, 180));
		TNT1 AAAAA 0 a_spawnprojectile("PlasmaParticleX", 48, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("PlasmaParticleX", 42, 0, random(0, 360), 2, random(0, 360));
		BOSC DEF 7 a_spawnprojectile("ExplosionSmoke", 14, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 8 a_spawnprojectile("ExplosionSmoke", 24, 0, random(0, 180), 2, random(0, 180));
		BOSB E -1;
	Stop;
	
	Death.Fire:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAA 0 a_spawnprojectile("PB_blood", 30, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("FlameTrails", 50, 0, random(0, 360), 2, random(0, 360));
		XBRN AAAA 2 BRIGHT A_SpawnItem("Green_Flare",0,43);
	Stop;
	
	Death.Incinerate:
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_Playsound("MELT");
		TNT1 A 0 A_NoBlocking();
		tnt1 AAAAAAAAAAAAAAAAAAa 0
		{
			pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");
		}
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,32,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAA 0 A_SpawnItemEx("TinyBurningPiece", random(-45, 45), random(-45, 45));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("Ashes1", 28, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("Ashes2", 40, 0, random(0, 360), 2, random(0, 180));
		TNT1 AA 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),40,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		B4UD AAAABBBBCCCCCDDDDDEEEEEFFFFFGGGG 1 BRIGHT Light("IncinerationGlow")
		{
			pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");
			A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),32,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			if(frame > 20) A_Playsound("SZZLL", 3);
		}
		B4UD HHGGHHGGHHGGHHGGHHGGHHGGHHGGHHGGHHGGHHGGHHGGHHGG 2 BRIGHT Light("IncinerationGlow")
		{
			a_spawnprojectile("ExplosionSmoke", 14, 0, random(0, 360), 2, random(0, 160));
			A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		}
		B4UD IIIIIII 12 a_spawnprojectile("ExplosionSmoke", 14, 0, random(0, 360), 2, random(0, 160));
		B4UD I -1;
	Stop;
	
	
	Death.fire:
	Death.Flames:
	Death.Burn:
		//TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		TNT1 A 0 A_Jump(189, "Fire2");
		TNT1 A 0 A_BossDeath();
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		BOSB AAAABBBBCCCCDDDD 2 a_spawnprojectile("FlameTrails", 45 - (frame * 10), 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Playsound("props/redfire");
		BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 2 a_spawnprojectile("FlameTrails", 25, 0, random(0, 360), 2, random(50, 130));
		BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 10 a_spawnprojectile("Explosion_Smoke", 25, 0, random(0, 360), 2, random(70, 110));
		BOSB E -1;
	Stop;
	
	Fire2:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_BossDeath();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("BurningBaron", 0, 10);
	Stop;
	
	Raise:
		BOSS O 8;
		BOSS NMLKJI  8;
	Goto See2;
	
	CurbstompMarine:
		KNTF A 10;
		TNT1 A 0 A_PlaySound("NECK_BRK", 3);
		TNT1 AAAA 0 a_spawnprojectile("XDeath2", 25, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath3", 25, 0, random(0, 360), 2, random(0, 160));
		KNTF BCD 4  {pb_blood_and_gore_event.much_blood(self);}
		tnt1 A 0 Radius_Quake(2, 24, 0, 15, 0);
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 1, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_PlaySound("misc/gibbed", 8);
		TNT1 AAAAAAAA 0 a_spawnprojectile("PlayerFlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
		KNTF DDDDDDDDDDDDDDD 3  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 A_PlaySound("NECK_BRK", 9);
		TNT1 A 0 a_spawnprojectile("RipGuts", 20, 0, random(0, 360), 2, random(0, 160));
		KNTF EEEFFFGGG 3  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 a_spawnprojectile("RipGuts", 20, 0, random(0, 360), 2, random(0, 160));
		KNTF GGGGGGGG 4  {pb_blood_and_gore_event.much_blood(self);}
		//TNT1 A 0 A_TakeInventory("Curbstomp_Marine",1);
		//TNT1 A 0 A_SpawnItem("RappedMarine", 1);
	Goto See2;
	
	
	FatalityZombieman:
		3HF1 A 20;
		TNT1 A 0 A_PlaySound("grunt/death");
		3HF1 BC 5;
		TNT1 AA 0 a_spawnprojectile("XDeath1", 55, 0, random(0, 360), 2, random(0, 160));
		3HF1 BCBC 5 a_spawnprojectile("XDeath1", 55, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0  {pb_blood_and_gore_event.much_blood(self);}
		3HF1 D 10;
		3HF1 E 5;
		TNT1 A 0 a_spawnprojectile("XDeathZombieManHead", 65, 0, random(0, 360), 2, random(70, 120));
		3HF1 F 30;
		3HF1 G 10;
		//TNT1 A 0 A_TakeInventory("ZombieManFatality",1);
		3HF1 H 8 A_Chase();
		BOSS E 8 A_FaceTarget();
		BOSS F 8 a_spawnprojectile("ThrowedZombieMan2", 64, 0, 0, 0);
		BOSS G 8;
	Goto See2;

	FatalitySergeant:
		3HF1 I 15;
		TNT1 A 0 A_PlaySound("grunt/death");
		3HF1 I 5;
		TNT1 AAAA 0 a_spawnprojectile("Instestin2", 30, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 45, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 45, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 55, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 A_SpawnItem("SergeantFatalizedByBaron");
		3HF1 J 10;
		3HF1 KLM 15;
		//TNT1 A 0 A_TakeInventory("SergeantFatality",1);
		3HF1 M 1 A_Chase();
		BOSS E 8 A_FaceTarget();
		BOSS F 8 a_spawnprojectile("ThrowedSergeantPiece", 64, 0, 0, 0);
		BOSS G 8;
	Goto See2;
	
	
	FatalityDemon:
		TNT1 A 0 A_PlaySound("demon/pain");
		3HF1 N 20;
		TNT1 A 0 a_spawnprojectile("XDeathStomach", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 45, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 45, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 55, 0, random(0, 360), 2, random(0, 160));
		3HF1 OPQQQ 8 a_spawnprojectile("Bloodmist", 25, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("DeadDemonHalf", 1);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 A 0 A_TakeInventory("DemonFatality",1);
	Goto See2;
	
	
	FatalityImp:
		TNT1 A 0 A_PlaySound("imp/pain");
		3HF2 ABABAB 4;
		TNT1 AAAAAA 0 A_SpawnItem("Bloodmist", 40);
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 45, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 45, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 55, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 42, 0, random(0, 360), 2, random(0, 160));
		3HF2 CDE 6;
		3HF2 F 1 A_Chase(null,null);
		3HF2 FFF 15;
		3HF2 GGHHIJ 3;
		TNT1 A 0 A_SpawnItem("DeadImp_BaronFatality");
		//TNT1 A 0 A_TakeInventory("ImpFatality3",1);
	Goto See2;

	Pain.KillMe:
	Pain.Taunt:
		TNT1 A 0;
	Goto Missile;

	Death.KillMe:
	Death.Taunt:
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 A_SpawnItem("BaronOfHell");
	Stop;
	
	Death.Ice:
	Death.Freeze:
	Death.Frost:
		TNT1 A 0 A_BossDeath();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		//TNT1 A 0 A_SpawnItem("FrozenBaronOfHell");
	Stop;
	
	Crush:
	Death.Stomp:
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AAAAAA 0 bright a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright a_spawnprojectile("XDeath2", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright a_spawnprojectile("XDeath3", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("CrushedRemains");
		TNT1 A 1;
		TNT1 A 1 A_XScream();
		TNT1 A 0 A_BossDeath();
		TNT1 A 0 A_NoBlocking();
	Stop;
}

} 

