CLASS DeadBaron: pb_blood_and_gore_base
{ 
Default
{
	Radius 8;
	Height 12;
	Scale 1.1;
	+SHOOTABLE;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CORPSE;
	+nopain
	-SOLID;
	+THRUACTORS;
	damagefactor "Crusher", 50.0;
	Mass 1000;
	Health 200;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	BloodType "PB_Blood", "AxeBlood", "AxeBlood";
}
States
{
	Spawn:
		BADD G -1;
	Stop;

	Death:
		TNT1 A 0 a_spawnprojectile("Bloodmist", 9, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		BSA1 U -1;// simple_death_handler();
	Stop;

	Death.Plasma: Death.Plasma2:
	Death.Flames:
	Death.Burn:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		EXPL AAAAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		BOSB ABCDE 9 a_spawnprojectile("ExplosionSmoke", 24, 0, random(0, 180), 2, random(0, 180));
		BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 8 a_spawnprojectile("ExplosionSmoke", 16, 0, random(0, 180), 2, random(0, 180));
		BOSB E -1;
	Stop;
}

}

/////fatality
CLASS FatalizedBaron2: DeadBaron { 
States{Spawn:        BHF2 W -1;
Stop;}}

CLASS DeadBaronNoHead: DeadBaron { 
States{Spawn:        BADH D -1;
Stop;}}
/////fatality end












CLASS BaronDeath2: DeadBaron { 
Default {
	Radius 0;
    Height 12;
	Translation "48:63=16:31", "96:111=32:47", "128:143=32:46", "144:151=32:47", "13:15=0:0";
}
States
{
	Spawn:
		TNT1 A 0 a_spawnprojectile("brutal_LiquidBlood", 28, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		BTN6 AAA  2 a_spawnprojectile("brutal_LiquidBlood", 37, 0, random(0, 360), 2, random(30, 60));
		BTN6 B 6;
		BTN6 CCC 2 a_spawnprojectile("brutal_LiquidBlood", 19, 0, random(0, 360), 2, random(30, 60));
		BTN6 D  6;
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		BTN8 E -1;// simple_death_handler();
	Stop;
		
	}
}


CLASS BaronDeath2_Big: DeadBaron { 
Default {
	Radius 0;
    Height 12;
	Translation "48:63=16:31", "96:111=32:47", "128:143=32:46", "144:151=32:47", "13:15=0:0";
}
States
{
	Spawn:
		TNT1 AA 0 a_spawnprojectile("Bloodmist", 45, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 26, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 31, 0, random(130, 210), 2, random(0, 40));
		TNT1 AAAAAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("muchblood", 55, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("PB_blood", 30, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("brutal_LiquidBlood", 28, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		BTN7 AAAA  2 a_spawnprojectile("brutal_LiquidBlood", 37, 0, random(0, 360), 2, random(30, 60));
		BTN7 B 6;
		BTN7 CCCC  2 a_spawnprojectile("brutal_LiquidBlood", 19, 0, random(0, 360), 2, random(30, 60));
		BTN7 D 6;
		TNT1 A 0 A_PlaySound("BIG_BODYF", 9);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		BTN8 FFFFFFFFFFFFFFFFFFFFFFFFF 2 a_spawnprojectile("brutal_LiquidBlood", 10, 0, random(0, 360), 2, random(30, 110));
		BTN8 F -1;// simple_death_handler();
	Stop;
}

}

CLASS XDeathHalfBOH : ACTOR { 
Default {
    Radius 1;
    Height 8;
    Speed 10;
	Mass 8;
	bounceFactor 0.3;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/XDeath1";
}
States
{
	Spawn:
		BTO2 AABBCC 4 a_spawnprojectile("brutal_LiquidBlood",0,0,180,2);
		BTO2 D -1;// simple_death_handler();
	Stop;
	}
}








CLASS BaronHeadPiece : pb_blood_and_gore_base
{
Default
{
	Radius 2;
	Height 2;
	Speed 6;
	Mass 1;
	Decal "BrutalBloodSplat";
	+CLIENTSIDEONLY;
	BounceFactor 0.4;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	+FLOORCLIP;
	Scale 1.2;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		XHE5 IJKL 4 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		XHE5 I 1;
		TNT1 A 0 A_QueueCorpse;
 	Rest:
		XHE5 I 800;
		XHE5 I -1;
		Stop;
	DoNothing:
		TNT1 A 0;
		Stop;
	}
}



CLASS XDeathBaronHead5: XDeathBullArm1 { 
	Default {
	
	BloodType "PB_blood", "AxeBlood", "AxeBlood";
	-CLIENTSIDEONLY;
	Scale 1.2;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		XHE5 ABCDEFGH 6;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		XHE5 A 1;
		XHE5 A 1 A_SpawnItem("BaronHead",0,0,0,1);
		Stop;
	}
}



CLASS BaronHead: Limbs_Base { 
	Default {
	
	BloodType "PB_blood", "AxeBlood", "AxeBlood";
	damagefactor "Kick", 9.0;
	damagefactor "Melee", 9.0;
	damagefactor "SuperPunch", 9.0;
	-CLIENTSIDEONLY;
	Radius 10;
	
	Mass 12;
	Health 60;
	Scale 1.2;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		XHE5 A 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		XHE5 A -1;
		Stop;
		
	Death:
		TNT1 AAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 a_spawnprojectile("BaronOfHellHeadExplode", 5, 0, random(0, 360), 2, random(60, 140));
		Stop;
	Death.Trample:
	Crush:
		//TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
		TNT1 AAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS1 B 5;
		CRS1 B 9009;
		Stop;
	Death.plasma:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL A 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0;
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		XHE5 A 1 A_Pain;
		XHE5 A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeathBaronHeadKicked", 5, 0, random(170, 190), 2, random(20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		XHE5 ABCD 3;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		XHE5 ABCD 6;
		//XHE5 I 0 A_SpawnItem("XDeathBaronHead");
		Stop;
		
}}


CLASS XDeathBaronHeadKicked: XDeathBaronHead5 { 
	Default {
	
	-BOUNCEONACTORS;
	Damage 4;
	Speed 13;
	BounceFactor 0.4;
	}
}


CLASS XDeathBaronofHellTorso: XDeathArm1 { 
	Default {
	
	Scale 1.3;
	Speed 12;
	BounceFactor 0.4;
	Decal "BloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		GORD ABCD 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		GORD E 1;
		HNDC A 0 A_SpawnItem("Gib_BaronofHellTorso",0,0,0,1);
		Stop;
	}
}



CLASS Gib_BaronofHellTorso: Limbs_Base { 
	Default {
	
	Scale 1.3;
	BloodType "PB_blood", "AxeBlood", "AxeBlood";
	BloodColor "Dark";
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		GORD E -1;
		Stop;
	Death:    
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("MuchBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 5, 0, random(0, 360), 2, random(10, 80));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 5, 0, random(0, 360), 2, random(10, 80));
		TNT1 AA 0 a_spawnprojectile("GenericBaronGib1", 5, 0, random(0, 360), 2, random(10, 80));
		TNT1 A 0 a_spawnprojectile("GenericBaronGib1", 5, 0, random(0, 360), 2, random(10, 80));
Stop;}}


CLASS GenericBaronGib1: GenericHKGib1 { 
Default
{
	Scale 1.0;
}
States
{
	Spawn:
		tnt1 a 0 nodelay
		{
			double scal = frandom(-1, 0.8);
			scale = (scal, scal);
		}
		tnt1 a 0 a_jump(126, "spawn2");
	looper:
		GG71 E 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		GG71 E -1;
		Stop;


	spawn2:
		GG71 F 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
	Loop;

	Death:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		GG71 F -1;
	Stop;
}

}


CLASS XDeathBaronOfHellArm: XDeathArm1 { 
	Default {
	
	Scale 1.1;
	Speed 12;
	BounceFactor 0.4;
	BounceCount 3;
	Decal "BloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		GORD FGHIJKLM 4 a_spawnprojectile("brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		GORD N 1;
		TNT1 A 0 A_SpawnItem("Gib_BaronOfHellArm", 1);
		Stop;
	}
}



CLASS Gib_BaronOfHellArm: Limbs_Base { 
	Default {
 
    Scale 1.1;
	BloodType "PB_blood", "AxeBlood", "AxeBlood";
	BloodColor "Dark";
	}
    States
    {
    Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
        GORD N 1900;
	GORD N -1;
	Stop;
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
        Stop;
    Death:    
    TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
    TNT1 AAAAAAA 0 a_spawnprojectile("named_BloodTr", 0, 0, random(0, 360), 2, random(0, 360));
    TNT1 A 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 360));
Stop;}}








CLASS BaronXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 AAAA 0 a_spawnprojectile("MuchBlood", 55, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("WallRedBlood", 32, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathBaronOfHellTorso", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathHellKnightLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath2", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath3", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("SuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
}
}


CLASS BaronOfHellHeadExplode: ZombieXDeath { 
Default {
	
	Decal "BloodSuper";
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("Brains2", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("BaronHeadPiece", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Brains2", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAAA 0 a_spawnprojectile("Brains4", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("WallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAA 0 a_spawnprojectile("Teeth", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 80));
		TNT1 A 10;
	Stop;
}
}

