
CLASS BaronAttack: BaronBall { 
	Default {
	
	Radius 24;
	Height 16;
	DamageType "BHFT";
	Projectile;
	+RANDOMIZE;
	+FORCEXYBILLBOARD;
	+THRUGHOST;
	RenderStyle "Add";
	Alpha 0.6;
	Damage 16;
	Speed 28;
	//HitObituary "$OB_IMPHIT"
	SeeSound "none";
	DeathSound "none";
	Decal "none";
	}
	States
	{
	Spawn:
		TNT1 A 2 BRIGHT;
		TNT1 A 2 A_PlaySound("weapons/gswing");
	Stop;
	}
}

CLASS DeadBaronExplosiveImpact2: actor//DeadKnight
{ 
	States{Spawn:        BOH3 H -1;
Stop;}}

CLASS DeadBaronExplosiveImpact1: actor//DeadKnight
{ 
States{Spawn:        BOH3 D -1;
Stop;}}
