//Sergeant Gibs

//Sergeant Arm
CLASS XDeathNewSergeantArm1: XDeathArm1 { 
	Default {
		
		Scale 1.0;
		Speed 10;
		Gravity 0.4;
		BounceFactor 0.4;
		+SKYEXPLODE;
		Species "Marines";
		+THRUSPECIES;
		BounceCount 5;
		Radius 10;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			4N09 ABCDEFGH 3 a_spawnprojectile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 a_spawnprojectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160))        Stop
Death:
	4N09 I 1;
	4N09 I -1;
	HND8 A 0 A_SpawnItem("Gib_NewSergeantArm1",0,0,0,1);
	Stop;
}
}

CLASS Gib_NewSergeantArm1: LimbBase { 
	Default {
 
    Scale 1.2
	}
    States
    {
    Spawn:
	4N09 I 1900 A_SpawnItem("Brutal_BloodSpot",0,0,0,1)
       Loop
    Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 a_spawnprojectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160))        Stop
    Death:    
    TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360))
    TNT1 A 0 a_spawnprojectile ("GibHand", 0, 0, random (0, 180), 2, random (0, 180))
    TNT1 A 0 a_spawnprojectile ("GibArmPart", 0, 0, random (0, 180), 2, random (0, 180))
Stop
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
	    4N09 II 1 A_FaceTarget
		TNT1 A 0 a_spawnprojectile ("XDeathNewSergeantArm1Kicked", 5, 0, random (170, 190), 2, random (20, 40))
		Stop
	Pain:
	TNT1 A 0
	TNT1 A 0 ThrustThingZ(0,20,0,1)
	4N09 ABCD 3
	Goto Spawn
	
	Death.ExplosiveImpact:
	TNT1 A 0
	TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0)
	TNT1 A 0 ThrustThingZ(0,50,0,1)
	4N09 A 6
	4N09 ABCDABCDABCD 6 A_CheckFloor("Landz")
	Goto Landz
	Landz:
	4N09 I 0 A_SpawnItem("Gib_NewSergeantArm1")
	Stop
}}

CLASS XDeathNewSergeantArm1Kicked: XDeathNewSergeantArm1 { 
	Default {
 
+ACTIVATEMCROSS
+ACTIVATEIMPACT
+CANUSEWALLS
	}
    States
    {
    Spawn:
	    TNT1 A 0 A_ChangeFlag("NOCLIP", 1)
	    4N09 A 2
		TNT1 A 0 A_ChangeFlag("NOCLIP", 0)
		TNT1 A 0
        TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1)
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Death")
		4N09 ABCD 6 a_spawnprojectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360))
		Goto Spawn+3
	}
}

//Sergeant Upper Torso
CLASS XDeathNewSergeantUpperTorso : ACTOR { 
	Default {
 
    Radius 8
    Height 8
    
	Speed 10
	Gravity 0.7
	Mass 4
	Decal BrutalBloodSplat
CLASSceFactor 0.01 : ACTOR { 
	Default {
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			4N06 ABCDEFGHI 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_NewSergeantUpperTorso",0,0,0,1);
			Stop;
	}
}

CLASS Gib_NewSergeantUpperTorso: BigGibBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			4N06 J 1;
			4N06 J -1;
Stop    }}
	   
//Sergeant Lower Torso
CLASS XDeathNewSergeantLowerTorso : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			4N05 ABCDEFGHI 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_NewSergeantLowerTorso",0,0,0,1);
			Stop;
	}
}

CLASS Gib_NewSergeantLowerTorso: BigGibBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			4N05 J 1;
			4N05 J -1;
Stop    }}

//Sergeant Leg
CLASS XDeathNewSergeantLeg1: XDeathArm1 { 
	Default {
		
		Scale 1.35;
		Speed 10;
		Gravity 0.4;
		BounceFactor 0.4;
		+SKYEXPLODE;
		Species "Marines";
		+THRUSPECIES;
		BounceCount 5;
		Radius 10;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			4N07 ABCDEFGH 3 a_spawnprojectile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 a_spawnprojectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160))        Stop
Death:
	4N07 I 1;
	4N07 I -1;
	HND8 A 0 A_SpawnItem("Gib_NewSergeantLeg1",0,0,0,1);
	Stop;
}
}

CLASS Gib_NewSergeantLeg1: LimbBase { 
	Default {
 
    Scale 1.35
	}
    States
    {
    Spawn:
	4N07 I 1900 A_SpawnItem("Brutal_BloodSpot",0,0,0,1)
       Loop
    Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 a_spawnprojectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160))        Stop
    Death:    
    TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360))
    TNT1 A 0 a_spawnprojectile ("GibHand", 0, 0, random (0, 180), 2, random (0, 180))
    TNT1 A 0 a_spawnprojectile ("GibArmPart", 0, 0, random (0, 180), 2, random (0, 180))
Stop
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
	    4N07 II 1 A_FaceTarget
		TNT1 A 0 a_spawnprojectile ("XDeathNewSergeantLeg1Kicked", 5, 0, random (170, 190), 2, random (20, 40))
		Stop
	Pain:
	TNT1 A 0
	TNT1 A 0 ThrustThingZ(0,20,0,1)
	4N07 ABCD 3
	Goto Spawn
	
	Death.ExplosiveImpact:
	TNT1 A 0
	TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0)
	TNT1 A 0 ThrustThingZ(0,50,0,1)
	4N07 A 6
	4N07 ABCDABCDABCD 6 A_CheckFloor("Landz")
	Goto Landz
	Landz:
	4N07 I 0 A_SpawnItem("Gib_NewSergeantLeg1")
	Stop
}}

CLASS XDeathNewSergeantLeg1Kicked: XDeathNewSergeantLeg1 { 
	Default {
 
+ACTIVATEMCROSS
+ACTIVATEIMPACT
+CANUSEWALLS
	}
    States
    {
    Spawn:
	    TNT1 A 0 A_ChangeFlag("NOCLIP", 1)
	    4N07 A 2
		TNT1 A 0 A_ChangeFlag("NOCLIP", 0)
		TNT1 A 0
        TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1)
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Death")
		4N07 ABCD 6 a_spawnprojectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360))
		Goto Spawn+3
	}
}

//Imps Gibs

//Imp Upper Torso
CLASS XDeathNewImpUpperTorso : ACTOR { 
	Default {
 
    Radius 8
    Height 8
    
	Speed 10
	Gravity 0.7
	Mass 4
	Decal BrutalBloodSplat
CLASSceFactor 0.01 : ACTOR { 
	Default {
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			4N04 ABCDEFGHI 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_NewImpUpperTorso",0,0,0,1);
			Stop;
	}
}

CLASS Gib_NewImpUpperTorso: BigGibBase { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			4N04 J 1;
			4N04 J -1;
Stop    }}
	   
//Imp Lower Torso
CLASS XDeathNewImpLowerTorso : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			4N03 ABCDEFGHI 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_NewImpLowerTorso",0,0,0,1);
			Stop;
	}
}

CLASS Gib_NewImpLowerTorso: BigGibBase { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			4N03 J 1;
			4N03 J -1;
Stop    }}
	   
//Infernus Leg
CLASS XDeathInfernusLeg : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.1;
		BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			G0RZ ABCDEFGH 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Green_Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_InfernusLeg",0,0,0,1);
			Stop;
	}
}

CLASS Gib_InfernusLeg: BigGibBase { 
	Default {
		
		BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood";
		Scale 1.0;
	}
	States
	{
		Spawn:
			G0RZ A 1;
			G0RZ A -1;
Stop    }}
	   
//Infernus Arm
CLASS XDeathInfernusArm : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood";
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			G0RX ABCDEFG 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Green_Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_InfernusArm",0,0,0,1);
			Stop;
	}
}

CLASS Gib_InfernusArm: BigGibBase { 
	Default {
		
		BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood";
		Scale 1.0;
	}
	States
	{
		Spawn:
			G0RX H 1;
			G0RX H -1;
Stop    }}
	   
//Infernus Torso
CLASS XDeathInfernusTorso : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.1;
		BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			G0RW ABCDEFGH 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Green_Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_InfernusTorso",0,0,0,1);
			Stop;
	}
}

CLASS Gib_InfernusTorso: BigGibBase { 
	Default {
		
		BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood";
		Scale 1.0;
	}
	States
	{
		Spawn:
			G0RW I 1;
			G0RW I -1;
Stop    }}
	   
//Infernus Head
CLASS XDeathInfernusHead : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.1;
		BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			G0RV ABCDEFGH 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Green_Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_InfernusHead",0,0,0,1);
			Stop;
	}
}

CLASS Gib_InfernusHead: BigGibBase { 
	Default {
		
		BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood";
		Scale 1.08;
	}
	States
	{
		Spawn:
			G0RV I 1;
			G0RV I -1;
Stop    }}
	   
//Infernus Torso Upper
CLASS XDeathInfernusUpperTorso : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.1;
		BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood";
	}
	States
	{
		Spawn:
			BT02 ABC 4;
		Falling:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			BT02 CC 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Green_Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_InfernusUpperTorso",0,0,0,1);
			Stop;
	}
}

CLASS Gib_InfernusUpperTorso: BigGibBase { 
	Default {
		
		BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood";
		Scale 1.08;
	}
	States
	{
		Spawn:
			BT02 D 1;
			BT02 D -1;
Stop    }}
	   
CLASS InfernusXDeath : ACTOR { 
	Default {
		
		Radius 1;
		Height 1;
		Scale 0.8;
		Speed 0;
		Mass 1;
		Decal BloodSuper;
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+NOGRAVITY;
		+NOCLIP;
		+DONTSPLASH;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Pain();
			TNT1 A 0 A_FaceTarget();
			
			TNT1 AAAA 0 a_spawnprojectile ("SuperWallGreenBlood", 40, 0, random (0, 360), 2, random (-15, 15));
			TNT1 A 0 a_spawnprojectile ("XDeathOrgan1Green", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 a_spawnprojectile ("XDeathOrgan2Green", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 a_spawnprojectile ("XDeath1Green", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 a_spawnprojectile ("XDeath2Green", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 a_spawnprojectile ("XDeath3Green", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 a_spawnprojectile ("XDeath4Green", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 a_spawnprojectile ("XDeath2bGreen", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 a_spawnprojectile ("XDeath3bGreen", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 a_spawnprojectile ("Green_Instestin", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 a_spawnprojectile ("GreenBloodMistBig", 30, 0, random (0, 360), 2, random (20, 90));
			TNT1 AA 0 a_spawnprojectile ("XDeathInfernusArm", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 a_spawnprojectile ("XDeathInfernusTorso", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 a_spawnprojectile ("XDeathInfernusLeg", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem ("GreenBigBloodSpot");
			TNT1 A 1;
			TNT1 A 0 ACS_NamedExecuteAlways("DetermineUserBloodAmount", 0, 0, 0, 0);//Check Blood density
			TNT1 A 2;
			TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile ("GreenBloodMistBig", 30, 0, random (0, 360), 2, random (20, 90));
			Stop;
		LowBlood:
			TNT1 A 2;
			Stop;
		LotsOfBlood:
			TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile ("GreenBloodMistExtraBig", 30, 0, random (0, 360), 2, random (20, 90));
			TNT1 AAAAAA 0 a_spawnprojectile ("GreenSuperGoreSpawner2", 64, 0, random (0, 360), 2, random (20, 40));
			Stop;
		AbsurdBlood:
			TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile ("GreenBloodMistExtraBig", 30, 0, random (0, 360), 2, random (20, 90));
			TNT1 AAAAAAAAAAAA 0 a_spawnprojectile ("GreenSuperGoreMist", 24, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAAAAAAA 0 a_spawnprojectile ("GreenSuperGoreSpawner2", 64, 0, random (0, 360), 2, random (20, 40));
			Stop;
	}
}
