CLASS BigGibBase : ACTOR { 
	Default {
		Radius 10;
		Height 10;
		+CLIENTSIDEONLY;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+DONTSPLASH;
		+NOBLOCKMONST;
		-NOBLOCKMAP;
		+GHOST;
		+THRUACTORS;
		+FLOORCLIP;
		+SLIDESONWALLS;
		+FORCEXYBILLBOARD;
		+NOTAUTOAIMED;
		DamageFactor "CauseObjectsToSplash", 0.0;
		DamageFactor "GibRemoving", 0.5;
		//+SOLID
		-SOLID;
		+SHOOTABLE;
		damagefactor "Crush", 50.0;
		damagefactor "Shrapnel", 100.0;
		damagefactor "Plasma", 20.0;
		damagefactor "Fire", 0.0;
		damagefactor "TeleportRemover", 1000.0;
		Mass 1000;
		Health 100;
		damagefactor "Blood", 0.0    damagefactor "GreenBlood", 0.0    damagefactor "BlueBlood", 0.0    damagefactor "Taunt", 0.0    damagefactor "KillMe", 0.0  damagefactor "Avoid", 0.0  damagefactor "Taunt", 0.0;
		damagefactor "Trample", 5000.0;
		painchance 255;
	}
	States    {
		Spawn:
			TNT1 A 1900 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			Loop;
		Death:
			TNT1 AAAAAAA 0 A_CustomMissile ("XDeathSkinPiece2", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_CustomMissile ("XDeathSkinPiece1", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_CustomMissile ("SmallSuperGore", 10, 0, random (0, 360), 2, random (10, 170));
			TNT1 AA 0 A_CustomMissile ("BloodMistBig", 10, 0, random (0, 360), 2, random (30, 90));
			TNT1 AA 0 A_CustomMissile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_CustomMissile ("XDeath3b", 10, 0, random (0, 360), 2, random (50, 90));
			TNT1 AAA 0 A_CustomMissile ("XDeath2b", 10, 0, random (0, 360), 2, random (50, 90));
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_XScream();
			TNT1 A 0 A_NoBlocking();
			TNT1 AAA 0 A_CustomMissile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_CustomMissile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_CustomMissile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL AAA 0 A_CustomMissile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0;
			Stop;
		Death.Trample:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
		Death.Crush:
		Death.Stomp:
		Death.SuperPunch:
		Death.ExtremePunches:
			TNT1 AAA 0 A_CustomMissile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 30));
			TNT1 AAAA 0 A_CustomMissile ("BloodMist", 5, 0, random (0, 360), 2, random (0, 30));
			TNT1 AAAAAAA 0 A_CustomMissile ("XDeathSkinPiece2", 5, 0, random (0, 360), 2, random (10, 30));
			TNT1 AAAA 0 A_CustomMissile ("XDeathSkinPiece1", 5, 0, random (0, 360), 2, random (10, 130));
			TNT1 AAAA 0 A_CustomMissile ("SmallSuperGore", 10, 0, random (0, 360), 2, random (10, 30));
			TNT1 A 0 A_SpawnItem("SplatteredSmall");
			XME2 L 1;
			XME2 L -1;
			Stop;
		Death.TeleportRemover:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOCLIP", 1);
			TNT1 A 0 A_ChangeFlag("SHOOTABLE", 0);
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 1);
			TNT1 A 0 A_NoBlocking();
			Stop;
		Death.GibRemoving:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOCLIP", 1);
			TNT1 A 0 A_ChangeFlag("SHOOTABLE", 0);
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 1);
			TNT1 A 0 A_NoBlocking();
			Stop;
		Death.Desintegrate:
			TNT1 A 0;
			TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodFake", 0, 0, random (0, 360), 2, random (0, 90));
			TNT1 A 0 A_CustomMissile ("Brutal_FlyingBlood", 7, 0, random (0, 360), 2, random (30, 60));
			TNT1 A 0 A_CustomMissile ("BloodMistSmall", 7, 0, random (0, 360), 2, random (30, 60));
			Stop;
}}

CLASS LimbBase: BigGibBase { 
	Default {
		Radius 6;
		Height 10;
		Mass 1000;
		Painchance 256;
		Health 35;
		+FORCEXYBILLBOARD;
		+DONTSPLASH;
		+SHOOTABLE;
		-CLIENTSIDEONLY;
		+NOBLOCKMONST;
		//+SOLID
		+THRUACTORS;
		+FLOORCLIP;
		damagefactor "Crush", 50.0;
		DeathSound "misc/xdeath4";
		damagefactor "Blood", 0.0    damagefactor "GreenBlood", 0.0    damagefactor "BlueBlood", 0.0    damagefactor "Taunt", 0.0    damagefactor "KillMe", 0.0  damagefactor "Avoid", 0.0  damagefactor "Taunt", 0.0;
		//damagefactor "Plasma", 99000.0
		damagefactor "Trample", 2.0;
		damagefactor "Kick", 9.0;
		damagefactor "Explosive", 0.1;
		damagefactor "ExplosiveImpact", 9.1;
		damagefactor "Shrapnel", 100.0;
		damagefactor "Melee", 9.0;
		damagefactor "SuperPunch", 9.0;
		damagefactor "Plasma", 20.0;
		painchance 255;
	}
	States    {
		Spawn:
			TNT1 A 1900 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			Loop;
		Death:
			TNT1 AAAAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			XDT3 BCDEFGH 3;
		Death.Crush:
			TNT1 A 1 A_CustomMissile ("XDeath1", 5, 5, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_CustomMissile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_CustomMissile ("XDeath3", 5, -5, random (0, 360), 2, random (0, 160));
			
			CRSB A 9009;
			Stop ;
Stop}}
		

CLASS TinyGib : ACTOR { 
	Default {
		
		Radius 2;
		Height 8;
		Speed 6;
		Mass 1;
		gravity 0.5;
		Scale 0.8;
		Decal BrutalBloodSplat;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MISSILE;
		+FORCEXYBILLBOARD;
		+DONTSPLASH;
		+NOBLOCKMONST;
		seesound "bloood";
		deathsound "bloood";
	}
	States
	{
		Spawn:
			TNT1 A 1;
			Loop;
	}
}



CLASS BloodTrails : ACTOR { 
	Default {
		
		Decal BrutalBloodSplat;
		game Doom;
		Alpha 0.4;
		+FORCEXYBILLBOARD;
		+GHOST;
		+NOBLOCKMAP;
		Gravity 0.05;
		+NOCLIP;
		+DontSplash;
		-EXPLODEONWATER;
		-ALLOWPARTICLES;
		+CLIENTSIDEONLY;
		-NOGRAVITY;
		Scale 1.2;
	}
	states
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			//BLER GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG 1 A_FadeOut(0.01)
			TNT1 AAAAAA 0 A_CustomMissile ("BloodTr255G", 0, 0, random (0, 360), 2, random (0, 180));
			//BLOD A 0 A_SpawnItem ("Big_Blood", 0, 10)
			stop;
	}
}


// Blood trails spawned by FlyingBlood
CLASS Brutal_FlyingBloodTrail8 : ACTOR { 
	Default {
		
		game Doom;
		scale 0.70;
		mass 1;
		Decal BrutalBloodSplat;
		+LOWGRAVITY;
		+NOTELEPORT;
		+NOBLOCKMAP;
		+NOCLIP;
		+FORCEXYBILLBOARD;
		+CLIENTSIDEONLY;
		-DONTSPLASH;
		+MISSILE;
		-NOGRAVITY;
		Speed 3;
	}
	states
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			BTRL A 8;
			BTRL B 8;
			BTRL C 8;
			BTRL D 8;
			stop;
			
		Splash:
			BLOD A 0;
			stop;
			
	}
}

CLASS GreenBloodTrail : ACTOR { 
	Default {
		
		-NOGRAVITY;
		+NOCLIP;
		radius 16;
		height 16;
		gravity 0.5;
		Scale 1.5;
translation "168:191=112:127","16:47=120:127"
	+FORCEXYBILLBOARD;
	+NOBLOCKMAP;
	}
states
	{
Spawn:
	TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
	TNT1 A 0;
	TNT1 A 0 Thing_ChangeTid(0,386);
	BLOD ABCD 2;
	stop;
Splash:
	TNT1 A 0;
	Stop;
}
}


CLASS BlueBloodTrail : ACTOR { 
	Default {
 
-NOGRAVITY
+NOCLIP
radius 16
height 16
gravity 0.5
Scale 1.5
translation "168:191=192:207","16:47=240:247"
decal CacoBloodSplat
+FORCEXYBILLBOARD
	}
states
	{
	Spawn:
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash")
		TNT1 A 0
		TNT1 A 0 Thing_ChangeTid(0,386)
		BLOD ABCD 2
		stop
    Splash:
        TNT1 A 0
        Stop
	}
}



CLASS XDeath1 : ACTOR { 
	Default {
 
    Radius 8
    Height 8
    Speed 10
    Scale 1.2
	Mass 1
    +NOBLOCKMAP
	+MISSILE
    +NOTELEPORT
    +MOVEWITHSECTOR
    +CLIENTSIDEONLY
    +RIPPER
    +BLOODLESSIMPACT 
	-DONTSPLASH
	+THRUGHOST
CLASSUACTORS : ACTOR { 
	Default {
		+FLOORCLIP;
		damagetype Blood;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal BrutalBloodSuper;
		Mass 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Underwater");
			BLOD A 4 A_CustomMissile ("XDeath1Trail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 ACS_EXecuteAlways(373, 0, 0, 0, 0);
			XDT1 EF 3;
			TNT1 A 0 A_JumpIfInventory("IsOverWater", 1, "IsOverLiquid");
			TNT1 A 0 A_JumpIfInventory("IsOverSlime", 1, "IsOverLiquid");
			XDT1 GHIJKL 3;
			Stop;
			TNT1 A 1;
		Underwater:
		Splash:
			BLUD C 0 ThrustThingZ (0,35,1,0);
			XDT1 AB 3 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			BLUD C 0 ThrustThingZ (0,35,1,0);
			XDT1 CD 3 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
			
		IsOverLiquid:
			TNT1 A 1;
			TNT1 A 0 A_CheckFloor("SpawnOnWater");
			
		SpawnOnWater:
			TNT1 A 1;
			TNT1 A 0 A_SpawnItem ("WaterBloodSpot", 5);
			Stop;
	}
}

CLASS XDeath2: XDeath1 { 
	Default {
		
		+CLIENTSIDEONLY;
		+DONTSPLASH;
		Speed 10;
		Gravity 0.4;
		DeathSound "misc/xdeath2";
		Decal BrutalBloodSuper;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			XME1 ABCD 3 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 AAAAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 180), 2, random (0, 180));
			
			
			TNT1 A 0 A_CheckFloor("SpawnFloor");
			TNT1 A 0 A_SpawnItemEx ("DetectCeilBloodSimplerLarge",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("DetectCeilXDeath2",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		SpawnFloor:
			XME1 E 1;
			TNT1 A 0 A_QueueCorpse();
			XME1 E -1;
			TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
			TNT1 A 0();
			XME1 E 3;
			TNT1 A 0 A_SpawnItemEx ("Brutal_BloodSpot", 0, 0, 1);
		Living:
			XME1 E -1;
			XME1 E 600;
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "Vanish");
			Loop;
		Vanish:
			TNT1 A 5;
			Stop;
	}
}


CLASS XDeath2b: XDeath2 { 
	Default {
		
		Speed 4;
	}
}

CLASS XDeath3: XDeath2 { 
	Default {
		
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Decal BrutalBloodSuper;
		Scale 1.1;
		Speed 10;
		Gravity 1.2;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			XME2 ABCD 3 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 AAAAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_CheckFloor("SpawnFloor");
			TNT1 A 0 A_SpawnItemEx ("DetectCeilBloodSimplerLarge",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("DetectCeilXDeath3",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		SpawnFloor:
			XME2 E 1;
			TNT1 A 0 A_QueueCorpse();
			XME2 E -1;
			TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
			TNT1 A 0();
			XME2 E 3;
			TNT1 A 0 A_SpawnItemEx ("Brutal_BloodSpot", 0, 0, 1);
		Living:
			XME2 E 600;
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "Vanish");
			Loop;
		Vanish:
			TNT1 A 5;
			Stop;
	}
}

CLASS XDeath3b: XDeath3 { 
	Default {
		
		Speed 4;
		Gravity 0.7;
	}
}


CLASS XDeath4: XDeath2 { 
	Default {
		
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Scale 1.1;
		+DOOMBOUNCE;
		BounceFactor 0.3;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			XME3 ABCDEFGH 3 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_Jump(255, "Death1", "Death2");
			GOto Death1;
			
		Death1:
			TNT1 A 0;
			TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
			XME3 GH 3;
			XME3 A 1;
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
		Living1:
			TNT1 A 0 A_QueueCorpse();
			XME3 A -1;
			XME3 A 600;//duration
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "Vanish");
			Loop;
		Death2:
			XME3 I 1;
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			XME3 I 1;
		Living2:
			XME3 I 600;//duration
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "Vanish");
			Loop;
		Vanish:
			TNT1 A 1;
			Stop;
	}
}

CLASS XDeath4b: XDeath2 { 
	Default {
		
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Scale 1.0;
		+DOOMBOUNCE;
		BounceFactor 0.01;
		Gravity 1.0;
		wallbouncefactor 0.2;
		Speed 4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			GIB4 AAAAAA 3 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			GIB4 B 1;
			TNT1 A 0 A_QueueCorpse();
			GIB4 B -1;
			TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
			TNT1 A 0();
			GIB4 B 1;
			TNT1 A 0 A_SpawnItemEx ("Brutal_BloodSpot", 0, 0, 1);
		Living1:
			GIB4 B 600;//duration
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "Vanish");
			Loop;
		Vanish:
			TNT1 A 1;
			Stop;
	}
}

CLASS XDeath5: XDeath2 { 
	Default {
		
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			XME5 ABCD 3 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 AAAAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_SpawnItemEx ("Brutal_BloodSpot", 0, 0, 1);
			XME5 E 1;
			TNT1 A 0 A_QueueCorpse();
			XME5 E -1;
			TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
			XME5 E 3;
		Living:
			XME5 E 800;//duration
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "Vanish");
			Loop;
		Vanish:
			TNT1 A 1;
			Stop;
			
	}
}


CLASS XDeathOrgan1: XDeath2 { 
	Default {
		
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Scale 0.9;
		Speed 4;
	}
	States
	{
		Spawn:
			XME8 A 4 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			XME8 A 1;
			TNT1 A 0 A_QueueCorpse();
			XME8 A -1;
			Stop;
	}
}

CLASS XDeathOrgan1b: XDeathOrgan1 { 
	Default {
		
		XScale -0.7;
		YScale 0.5;
	}
}

CLASS XDeathOrgan2: XDeathOrgan1 { 
	Default {
		
	}
	States
	{
		Spawn:
			XME8 B 4 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			XME8 B 1;
			TNT1 A 0 A_QueueCorpse();
			XME8 B -1;
			Stop;
	}
}

CLASS XDeathGuts: XDeath2 { 
	Default {
		
		Scale 1.1;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			XME4 AAAABBBBCCCCDDDD 2;
			Loop;
		Death:
			TNT1 AAAAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_QueueCorpse();
			XME4 E -1;
			Stop;
	}
}


CLASS WaterBloodCHecker: XDeath1 { 
	Default {
		
		Speed 4;
		Scale 1.2;
		Radius 1;
		+DOOMBOUNCE;
		BounceFactor 0.01;
		+EXPLODEONWATER;
		+DONTSPLASH;
		Height 1;
		SeeSound "none";
		DeathSound "none";
		Decal none;
	}
	States
	{
		Spawn:
			TNT1 A 5;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 ACS_EXecuteAlways(373, 0, 0, 0, 0);
			TNT1 A 5;
			TNT1 A 0 A_JumpIfInventory("IsOverWater", 1, "IsOverLiquid");
			TNT1 A 0 A_JumpIfInventory("IsOverSlime", 1, "IsOverLiquid");
			TNT1 A 0 A_JumpIfInventory("IsOverBlood", 1, "IsOverLiquid");
			TNT1 A 0 A_JumpIfInventory("IsOverSludge", 1, "IsOverLiquid");
			TNT1 A 10;
			Stop;
			
		IsOverLiquid:
			TNT1 A 1;
			TNT1 A 0 A_CheckFloor("SpawnOnWater");
			
		SpawnOnWater:
			TNT1 A 1;
			TNT1 A 0 A_SpawnItem ("WaterBloodSpot", 5);
			Stop;
	}
}

CLASS WaterBloodCHeckerBlue: XDeath1 { 
	Default {
		
		Decal "BlueBloodSplat";
	}
	States
	{
		Spawn:
			TNT1 A 5;
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 ACS_EXecuteAlways(373, 0, 0, 0, 0);
			TNT1 A 5;
			TNT1 A 0 A_JumpIfInventory("IsOverWater", 1, "IsOverLiquid");
			TNT1 A 0 A_JumpIfInventory("IsOverSlime", 1, "IsOverLiquid");
			TNT1 A 0 A_JumpIfInventory("IsOverBlood", 1, "IsOverLiquid");
			TNT1 A 0 A_JumpIfInventory("IsOverSludge", 1, "IsOverLiquid");
			TNT1 A 10;
			Stop;
			
		IsOverLiquid:
			TNT1 A 1;
			TNT1 A 0 A_CheckFloor("SpawnOnWater");
			
		SpawnOnWater:
			TNT1 A 1;
			TNT1 A 0 A_SpawnItem ("WaterBloodSpotBlue", 5);
			Stop;
	}
}

CLASS WaterBloodCHeckerGreen: XDeath1 { 
	Default {
		
		Decal "GreenBloodSplat";
	}
	States
	{
		Spawn:
			TNT1 A 5;
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 ACS_EXecuteAlways(373, 0, 0, 0, 0);
			TNT1 A 5;
			TNT1 A 0 A_JumpIfInventory("IsOverWater", 1, "IsOverLiquid");
			TNT1 A 0 A_JumpIfInventory("IsOverSlime", 1, "IsOverLiquid");
			TNT1 A 0 A_JumpIfInventory("IsOverBlood", 1, "IsOverLiquid");
			TNT1 A 0 A_JumpIfInventory("IsOverSludge", 1, "IsOverLiquid");
			TNT1 A 10;
			Stop;
			
		IsOverLiquid:
			TNT1 A 1;
			TNT1 A 0 A_CheckFloor("SpawnOnWater");
			
		SpawnOnWater:
			TNT1 A 1;
			TNT1 A 0 A_SpawnItem ("WaterBloodSpotGreen", 5);
			Stop;
	}
}

CLASS GoreSound: XDeath2 { 
	Default {
		
		SeeSound "misc/xdeath4";
		DeathSound "none";
		Decal "None";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			TNT1 A 2;
			Loop;
		Death:
			TNT1 BCDE 1;
			Stop;
		Splash:
			TNT1 A 1;
			Stop;
	}
}


CLASS ShakeShakeShake: XDeath2 { 
	Default {
		
		SeeSound "none";
		DeathSound "none";
		Decal "None";
		Gravity 1.0;
		Speed 1;
	}
	States
	{
		Spawn:
			TNT1 A 5;
			Goto Death;
		Death:
			TNT1 A 1;
			EXPL A 0 Radius_Quake (4, 24, 0, 15, 0);
			TNT1 A 20;
			Stop;
	}
}

//ACTOR XDeathMarineHead
//{
//    Radius 8
 //   Height 8
 //   Speed 16
	//Mass 6
CLASSunceFactor 0.4 : ACTOR { 
	Default {
		//	+DOOMBOUNCE
		//  +NOBLOCKMAP
		//	+MISSILE
		//   +NOTELEPORT
		//   +DONTSPLASH
		//   +MOVEWITHSECTOR
		//  DeathSound "misc/xdeath1"
		//	Decal BrutalBloodSplat
	}
	//  States
	//  {
	//  Spawn:
	//    TNT1 A 0 A_JumpIf(waterlevel > 1, "Death")
	//     MHEA A 15 A_CustomMissile("Brutal_FlyingBloodTrail",0,0,180,2)
	//    Loop
	// Death:
	//     MHEA A 9009
	//    Stop
	//   }
	//}
	
	
	
	
	
	
	
	
	
	
	
	
	/////////////////
	//ARMS
	/////////////////
	
	
	ACTOR XDeathArm1;
	{
		Radius 8;
		Height 8;
		Scale 1.2;
		Speed 8;
		Mass 1;
		gravity 0.5;
		Decal BrutalBloodSplat;
		BounceFactor 0.4;
		BounceCount 3;
		+DOOMBOUNCE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MISSILE;
		+EXPLODEONWATER;
		+SKYEXPLODE;
		-DONTSPLASH;
		seesound "bloood";
		deathsound "bloood";
		States;
		{
			Spawn:
				TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
				TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
				XARM AEBCFDG 5 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
				Loop;
			Death:
				XDT5 I 1;
				TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
				XDT5 I 0 A_SpawnItem("Gib_Arm");
				Stop;
		}
	}
	
	ACTOR XDeathLabGuyArm: XDeathArm1
		{
			States;
			{
			Spawn:
				TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
				TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
				XLRM ABCDEFGH 4 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
				Loop;
			Death:
				XLRM I 1;
				XLRM I 0 A_SpawnItem("Gib_LabGuyArm",0,0,0,1);
				Stop;
		}
	}
	
	actor Gib_Arm: LimbBase
		{
			Scale 1.2;
			States;
			{
			Spawn:
				TNT1 A 0;
				TNT1 A 0 A_QueueCorpse();
				XDT5 I 1 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
				XDT5 I -1;
				Stop;
	Death.plasma: Death.Burn: Death.Flames:    
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece2", random (-15, 15), random (-15, 15));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random (-15, 15), random (-15, 15));
		TNT1 A 0 A_CustomMissile ("XDeathBurnedArm", 2, 0, random (0, 360), 2, 270)    ();
		Stop;
	Death:    
		TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 0 A_CustomMissile ("GibHand", 0, 0, random (0, 180), 2, random (0, 180));
		TNT1 A 0 A_CustomMissile ("GibArmPart", 0, 0, random (0, 180), 2, random (0, 180));
		Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		XDT5 II 1 A_FaceTarget();
		TNT1 A 0 A_CustomMissile ("XDeathArm1Kicked", 5, 0, random (170, 190), 2, random (20, 40));
		Stop;
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		XARM ABCD 3;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		XARM A 6;
		XARM ABCDABCDABCD 6 A_CheckFloor("Landz");
		Goto Landz;
	Landz:
		XDT5 I 0 A_SpawnItem("Gib_Arm");
		Stop;
}}

CLASS Gib_LabguyArm: LimbBase { 
	Default {
	
	Scale 1.2;
	}
    States
    {
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse();
		XLRM I 1 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
		XLRM I -1;
		Stop;
		
		Loop;
Death.plasma: Death.Burn: Death.Flames:	    
	TNT1 A 0 A_SpawnItemEx("TinyBurningPiece2", random (-15, 15), random (-15, 15));
	TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random (-15, 15), random (-15, 15));
	TNT1 A 0 A_CustomMissile ("XDeathBurnedArm", 2, 0, random (0, 360), 2, 270)    ();
	Stop;
Death:    
	TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
	TNT1 A 0 A_CustomMissile ("GibHand", 0, 0, random (0, 180), 2, random (0, 180));
	TNT1 A 0 A_CustomMissile ("GibArmPart", 0, 0, random (0, 180), 2, random (0, 180));
	Stop;
Death.Kick:
Death.Melee:
Death.SuperPunch:
	XLRM II 1 A_FaceTarget();
	TNT1 A 0 A_CustomMissile ("XDeathLabGuyArm", 5, 0, random (170, 190), 2, random (20, 40));
	Stop;
Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	XLRM ABCD 3;
	Goto Spawn;
	
Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	XLRM A 6;
	XLRM ABCDEFGHABCD 6 A_CheckFloor("Landz");
	Goto Landz;
Landz:
	XLRM I 0 A_SpawnItem("Gib_LabguyArm");
	Stop;
}}

CLASS XDeathArm1Kicked: XDeathArm1 { 
	Default {
 
+ACTIVATEMCROSS
+ACTIVATEIMPACT
+CANUSEWALLS
	}
    States
    {
    Spawn:
	    TNT1 A 0 A_ChangeFlag("NOCLIP", 1)
	    XARM A 2
		TNT1 A 0 A_ChangeFlag("NOCLIP", 0)
		TNT1 A 0
        TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1)
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Death")
		XARM ABCD 6 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360))
		Goto Spawn+3
	}
}

CLASS GibArmPart: TinyGib { 
	Default {
 
    Scale 1.0
	}
    States
    {
	Spawn:
		XDT5 Z 1
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
		XDT5 Z -1
		Stop
    Death:
XDT5 Z 1
       Loop
}}

CLASS GibHand: TinyGib { 
	Default {
 
    Scale 1.0
	}
    States
    {
	Spawn:
		XDT5 Y 1
		TNT1 A 0 A_QueueCorpse
		XDT5 Y -1
       Stop
    Death:
XDT5 Y 1
       Loop
}}


CLASS XDeathArm2: XDeathArm1 { 
	Default {
 
	Speed 10
	}
}

CLASS XDeathArchvileHeadPiece: XDeathArm1 { 
	Default {
 
    Scale 1.1
    Speed 10
	Gravity 0.4
CLASSceFactor 0.4 : ACTOR { 
	Default {
		+SKYEXPLODE;
		Species "Marines";
		+THRUSPECIES;
		BounceCount 5;
		Radius 10;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			D6AX ABCD 3 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			D6AX E 1;
			D6AX E 0 A_SpawnItem("Gib_ArchvileHeadPiece",0,0,0,1);
			Stop;
	}
}

CLASS Gib_ArchvileHeadPiece: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			D6AX E 2;
			Goto Spawn1;
			
		Spawn1:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			D6AX E 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			D6AX E -1();
			Stop;
		Death:    
			TNT1 AAA 0 A_CustomMissile ("BloodMist", 2, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAAAA 0 A_CustomMissile ("Brutal_FlyingBlood", 2, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAA 0 A_CustomMissile ("SmallBrainPieceFast", 2, random (5, -5), random (170, 190), 2, random (-10, 10));
			TNT1 AA 0 A_CustomMissile ("SmallBrainPiece", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_CustomMissile ("XDeath1", 3, 0, random (0, 360), 2, random (0, 160));
			Stop;
			
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			D6AX AA 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathArchvileHeadPiece", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			D6AX ABCD 3;
			Goto Spawn1;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			D6AX A 5;
			D6AX ABCDABCDABCDABCD 5 A_CheckFloor("Landz");
			Goto Landz;
			
		Landz:
			XDT5 I 0 A_SpawnItem("Gib_ArchvileHeadPiece");
			Stop;
}}

CLASS XDeathArchvileHead: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 10;
		Gravity 0.4;
		BounceFactor 0.4;
		+SKYEXPLODE;
		Species "Marines";
		+THRUSPECIES;
		BounceCount 5;
		Radius 10;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			VILP CDEFGHIJ 3 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			VILP J 1;
			D6AX E 0 A_SpawnItem("Gib_ArchvileHead",0,0,0,1);
			Stop;
	}
}

CLASS Gib_ArchvileHead: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			VILP J 2;
			Goto Spawn1;
			
		Spawn1:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			VILP J 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			VILP J -1;
			Stop;
		Death:    
			TNT1 AAAAA 0 A_CustomMissile ("BloodMistBig", 2, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAAAA 0 A_CustomMissile ("Brutal_FlyingBlood", 2, 0, random (0, 360), 2, random (30, 90));
			TNT1 A 0 A_CustomMissile ("Brains2", 2, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_CustomMissile ("XDeathArchvileHeadPiece", 2, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_CustomMissile ("Brains3", 2, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_CustomMissile ("SmallBrainPieceFast", 2, random (5, -5), random (170, 190), 2, random (-10, 10));
			TNT1 AAAAA 0 A_CustomMissile ("SmallBrainPiece", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_CustomMissile ("Teeth", 4, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_CustomMissile ("XDeath1", 3, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath2", 3, 0, random (0, 360), 2, random (0, 160));
			VILP K -1;
			Stop;
			
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			VILP C 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathArchvileHead", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			VILP CDEFGHIJ 2;
			Goto Spawn1;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			VILP CDEFGHIJ 3 A_CheckFloor("Landz");
			Goto Landz;
			
		Landz:
			XDT5 I 0 A_SpawnItem("Gib_ArchvileHead");
			Stop;
}}

CLASS XDeathArchvileLegPiece: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 10;
		Gravity 0.4;
		BounceFactor 0.4;
		+SKYEXPLODE;
		Species "Marines";
		+THRUSPECIES;
		BounceCount 5;
		Radius 10;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			D4AX ABCD 3 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			D4AX E 1;
			D4AX E 0 A_SpawnItem("Gib_ArchvileLegPiece",0,0,0,1);
			Stop;
	}
}

CLASS Gib_ArchvileLegPiece: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			D4AX E 2;
			Goto Spawn1;
			
		Spawn1:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			D4AX E 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			D4AX E -1;
			Stop;
		Death:    
			TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AA 0 A_CustomMissile ("Xdeath1", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 AA 0 A_CustomMissile ("BloodMistBig", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
			
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			D4AX AA 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathArchvileLegPiece", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			D4AX ABCD 3;
			Goto Spawn1;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			D4AX A 5;
			D4AX ABCDABCDABCDABCD 5 A_CheckFloor("Landz");
			Goto Landz;
			
		Landz:
			XDT5 I 0 A_SpawnItem("Gib_ArchvileLegPiece");
			Stop;
}}

CLASS XDeathArchvileLeg: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 10;
		Gravity 0.4;
		BounceFactor 0.4;
		+SKYEXPLODE;
		Species "Marines";
		+THRUSPECIES;
		BounceCount 5;
		Radius 10;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			DIAG IJKLMNOP 3 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			DIAG Q 1;
			D4AX E 0 A_SpawnItem("Gib_ArchvileLeg",0,0,0,1);
			Stop;
	}
}

CLASS Gib_ArchvileLeg: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			DIAG Q 2;
			Goto Spawn1;
			
		Spawn1:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			DIAG Q 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			DIAG Q -1;
			Stop;
		Death:    
			TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AA 0 A_CustomMissile ("Xdeath1", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_CustomMissile ("XDeathArchvileLegPiece", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 AA 0 A_CustomMissile ("BloodMistBig", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
			
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			DIAG Q 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathArchvileLeg", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			DIAG IJKLMNOP 3;
			Goto Spawn1;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			DIAG IJKLMNOP 4 A_CheckFloor("Landz");
			Goto Landz;
			
		Landz:
			XDT5 I 0 A_SpawnItem("Gib_ArchvileLeg");
			Stop;
}}


CLASS XDeathArchvileTorso: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 10;
		Gravity 0.4;
		BounceFactor 0.4;
		+SKYEXPLODE;
		Species "Marines";
		+THRUSPECIES;
		BounceCount 5;
		Radius 10;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			D3AX ABCD 3 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			D3AX E 1;
			D3AX E 0 A_SpawnItem("Gib_ArchvileTorso",0,0,0,1);
			Stop;
	}
}

CLASS Gib_ArchvileTorso: LimbBase { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			D3AX E 2;
			Goto Spawn1;
			
		Spawn1:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			D3AX E 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			D3AX E -1;
			Stop;
		Death:    
			TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAA 0 A_CustomMissile ("Xdeath1", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 AA 0 A_CustomMissile ("Xdeath2", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 AAA 0 A_CustomMissile ("BloodMistBig", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
			
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			D3AX AA 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathArchvileTorso", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			D3AX ABCD 3;
			Goto Spawn1;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			D3AX A 5;
			D3AX ABCDABCDABCDABCD 5 A_CheckFloor("Landz");
			Goto Landz;
			
		Landz:
			XDT5 I 0 A_SpawnItem("Gib_ArchvileTorso");
			Stop;
}}

CLASS XDeathArchvileArmPiece: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 10;
		Gravity 0.4;
		BounceFactor 0.4;
		+SKYEXPLODE;
		Species "Marines";
		+THRUSPECIES;
		BounceCount 5;
		Radius 10;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			D7AX ABCD 3 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			D7AX E 1;
			D7AX E 0 A_SpawnItem("Gib_ArchvileArmPiece",0,0,0,1);
			Stop;
	}
}

CLASS Gib_ArchvileArmPiece: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			D7AX E 2;
			Goto Spawn1;
			
		Spawn1:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			D7AX E 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			D7AX E -1;
			Stop;
		Death:    
			TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AA 0 A_CustomMissile ("Xdeath1", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 AA 0 A_CustomMissile ("BloodMistBig", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
			
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			D7AX AA 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathArchvileArmPiece", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			D7AX ABCD 3;
			Goto Spawn1;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			D7AX A 5;
			D7AX ABCDABCDABCDABCD 5 A_CheckFloor("Landz");
			Goto Landz;
			
		Landz:
			XDT5 I 0 A_SpawnItem("Gib_ArchvileArmPiece");
			Stop;
}}

CLASS XDeathArchvileArm: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 10;
		Gravity 0.4;
		BounceFactor 0.4;
		+SKYEXPLODE;
		Species "Marines";
		+THRUSPECIES;
		BounceCount 5;
		Radius 10;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			DIAG ABCDEFGH 3 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			DIAG R 1;
			D7AX E 0 A_SpawnItem("Gib_ArchvileArm",0,0,0,1);
			Stop;
	}
}

CLASS Gib_ArchvileArm: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			DIAG R 2;
			Goto Spawn1;
			
		Spawn1:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			DIAG R 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			DIAG R -1;
			Stop;
		Death:    
			TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AA 0 A_CustomMissile ("Xdeath1", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_CustomMissile ("XDeathArchvileArmPiece", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 AA 0 A_CustomMissile ("BloodMistBig", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
			
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			DIAG R 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathArchvileArm", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			DIAG ABCDEFGH 3;
			Goto Spawn1;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			DIAG ABCDEFGH 3 A_CheckFloor("Landz");
			Goto Landz;
			
		Landz:
			XDT5 I 0 A_SpawnItem("Gib_ArchvileArm");
			Stop;
}}


CLASS XDeathBullArm1: XDeathArm1 { 
	Default {
		
		Scale 1.0;
		Speed 10;
		Gravity 0.4;
		BounceFactor 0.4;
		+SKYEXPLODE;
		Species "Marines";
		+THRUSPECIES;
		BounceCount 5;
		Radius 10;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			HND8 ABCDEFGH 3 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 A_CustomMissile ("XDeathBurnedDemonArm", 32, 0, random (0, 360), 2, random (0, 160))        Stop
Death:
	HND8 I 1;
	HND8 A 0 A_SpawnItem("Gib_DemonArm",0,0,0,1);
	Stop;
}
}

CLASS Gib_DemonArm: LimbBase { 
	Default {
 
    Scale 1.1
	}
    States
    {
    Spawn:
	HND8 GH 2
	Goto Spawn1
	
	Spawn1:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
		HND8 I 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1)
		HND8 I -1
        Stop
    Death:    
    TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360))
    TNT1 A 0 A_CustomMissile ("GibDemonHand", 0, 0, random (0, 180), 2, random (0, 180))
    TNT1 A 0 A_CustomMissile ("GibDemonArmPart", 0, 0, random (0, 180), 2, random (0, 180))
Stop
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
	    HND8 AA 1 A_FaceTarget
		TNT1 A 0 A_CustomMissile ("XDeathBullArm1Kicked", 5, 0, random (170, 190), 2, random (20, 40))
		Stop
		
	Pain:
	TNT1 A 0
	TNT1 A 0 ThrustThingZ(0,20,0,1)
	HND8 ABCDEFGH 2
	Goto Spawn1
	
	Death.ExplosiveImpact:
	TNT1 A 0
	TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0)
	TNT1 A 0 ThrustThingZ(0,50,0,1)
	HND8 A 5
	HND8 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz")
	Goto Landz
	Landz:
	
	XDT5 I 0 A_SpawnItem("Gib_DemonArm")
	Stop	
}}


CLASS XDeathBloodDemonArm1: XDeathArm1 { 
	Default {
 
    Scale 1.0
    Speed 10
	Gravity 0.4
CLASSceFactor 0.4 : ACTOR { 
	Default {
		+SKYEXPLODE;
		Species "Marines";
		+THRUSPECIES;
		BounceCount 5;
		Radius 10;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			M3G8 ABCDEFGH 3 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 A_CustomMissile ("XDeathBurnedDemonArm", 32, 0, random (0, 360), 2, random (0, 160))        Stop
Death:
	M3G8 I 1;
	HND8 A 0 A_SpawnItem("Gib_BloodDemonArm",0,0,0,1);
	Stop;
}
}

CLASS Gib_BloodDemonArm: LimbBase { 
	Default {
 
    Scale 1.1
	}
    States
    {
    Spawn:
	M3G8 GH 2
	Goto Spawn1
	
	Spawn1:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
		M3G8 I 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1)
		M3G8 I -1
        Stop
    Death:    
    TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360))
    TNT1 A 0 A_CustomMissile ("GibDemonHand", 0, 0, random (0, 180), 2, random (0, 180))
    TNT1 A 0 A_CustomMissile ("GibDemonArmPart", 0, 0, random (0, 180), 2, random (0, 180))
Stop
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
	    M3G8 AA 1 A_FaceTarget
		TNT1 A 0 A_CustomMissile ("XDeathBullArm1Kicked", 5, 0, random (170, 190), 2, random (20, 40))
		Stop
		
	Pain:
	TNT1 A 0
	TNT1 A 0 ThrustThingZ(0,20,0,1)
	M3G8 ABCDEFGH 2
	Goto Spawn1
	
	Death.ExplosiveImpact:
	TNT1 A 0
	TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0)
	TNT1 A 0 ThrustThingZ(0,50,0,1)
	M3G8 A 5
	M3G8 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz")
	Goto Landz
	Landz:
	
	M3G8 I 0 A_SpawnItem("Gib_BloodDemonArm")
	Stop	
}}

CLASS XDeathVoidSpectreArm: XDeathArm1 { 
	Default {
 
    Scale 1.0
    Speed 10
	Gravity 0.4
CLASSceFactor 0.4 : ACTOR { 
	Default {
		+SKYEXPLODE;
		Species "Marines";
		+THRUSPECIES;
		BounceCount 5;
		Decal GreenBloodSplat;
		Radius 10;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			ND6M ABCDEFGH 3 A_CustomMissile ("Green_FlyingBlood", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 A_CustomMissile ("XDeathBurnedDemonArm", 32, 0, random (0, 360), 2, random (0, 160))        Stop
Death:
	ND6M I 1;
	ND6M A 0 A_SpawnItem("Gib_VoidSpectreArm",0,0,0,1);
	Stop;
}
}

CLASS Gib_VoidSpectreArm: LimbBase { 
	Default {
 
    Scale 1.1
	BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood"
	BloodColor "DarkGreen"
	}
    States
    {
    Spawn:
	ND6M GH 2
	Goto Spawn1
	
	Spawn1:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
		ND6M I 1 A_SpawnItem("Green_BloodSpot",0,0,0,1)
		ND6M I -1
        Stop
    Death:    
    TNT1 AAAA 0 A_CustomMissile ("Green_FlyingBlood", 0, 0, random (0, 360), 2, random (0, 360))
    TNT1 A 0 A_CustomMissile ("Xdeath1Green", 0, 0, random (0, 180), 2, random (0, 180))
    TNT1 A 0 A_CustomMissile ("Xdeath2Green", 0, 0, random (0, 180), 2, random (0, 180))
	Stop
	
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
	    ND6M AA 1 A_FaceTarget
		TNT1 A 0 A_CustomMissile ("XDeathVoidSpectreKicked", 5, 0, random (170, 190), 2, random (20, 40))
		Stop
		
	Pain:
	TNT1 A 0
	TNT1 A 0 ThrustThingZ(0,20,0,1)
	ND6M ABCDEFGH 2
	Goto Spawn1
	
	Death.ExplosiveImpact:
	TNT1 A 0
	TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0)
	TNT1 A 0 ThrustThingZ(0,50,0,1)
	ND6M A 5
	ND6M ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz")
	Goto Landz
	Landz:
	
	XDT5 I 0 A_SpawnItem("Gib_VoidSpectreArm")
	Stop	
}}

CLASS XDeathDemonArm: XDeathBullArm1 { 
	Default {
 
    Scale 1.1
	}
}

CLASS XDeathVoidSpectreKicked: XDeathVoidSpectreArm { 
	Default {
 
+ACTIVATEMCROSS
+ACTIVATEIMPACT
+CANUSEWALLS
	}
}

CLASS XDeathBullArm1Kicked: XDeathBullArm1 { 
	Default {
 
+ACTIVATEMCROSS
+ACTIVATEIMPACT
+CANUSEWALLS
	}
}

CLASS GibDemonArmPart: TinyGib { 
	Default {
 
    Scale 1.1
	}
    States
    {
Spawn:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
		HND8 Z -1
        Stop
    Death:
HND8 Z 1
       Loop
}}

CLASS GibDemonHand: TinyGib { 
	Default {
 
    Scale 0.8
	}
    States
    {
Spawn:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
		HND8 Y -1
       Loop
    Death:
HND8 Y 1
       Loop
}}






CLASS XDeathImpArm: XDeathArm1 { 
	Default {
 
    Scale 1.1
    Speed 8
	Gravity 0.4
CLASSceFactor 0.4 : ACTOR { 
	Default {
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			HND4 ABCDEFGH 4 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death.plasma:    TNT1 A 0 A_CustomMissile ("XDeathBurnedImpArm", 32, 0, random (0, 360), 2, random (0, 160))        Stop
		Death:
			HND4 X 1;
			//HND4 X -1
			HND4 X 0 A_SpawnItem("Gib_ImpArm",0,0,0,1);
			Stop;
	}
}

CLASS XDeathSavageImpArm: XDeathImpArm { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			9ND4 ABCDEFGH 4 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
			
		Death.plasma:    TNT1 A 0 A_CustomMissile ("XDeathBurnedImpArm", 32, 0, random (0, 360), 2, random (0, 160))        Stop
		Death:
			9ND4 X 1;
			//9ND4 X -1
			9ND4 X 0 A_SpawnItem("Gib_SavageImpArm",0,0,0,1);
			Stop;
	}
}


CLASS Gib_ImpArm: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			HND4 X 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			HND4 X -1;
			Stop;
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 A_CustomMissile ("XDeathBurnedImpArm", 32, 0, random (0, 360), 2, random (0, 160))        Stop
Death:    
	TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
	TNT1 A 0 A_CustomMissile ("GibImpHand", 0, 0, random (0, 180), 2, random (0, 180));
	TNT1 A 0 A_CustomMissile ("GibImpArmPart", 0, 0, random (0, 180), 2, random (0, 180));
	Stop;
	Stop;
Death.Kick:
Death.Melee:
Death.SuperPunch:
	HND4 AA 1 A_FaceTarget();
	TNT1 A 0 A_CustomMissile ("XDeathImpArm", 5, 0, random (170, 190), 2, random (20, 40));
	Stop;
	
Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	HND4 ABCDEFGH 3;
	Goto Spawn;
	
Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	HND4 X 5;
	HND4 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
Landz:
	XDT5 I 0 A_SpawnItem("Gib_ImpArm");
	Stop;
}}

CLASS Gib_SavageImpArm: Gib_ImpArm { 
	Default {
 
	}
    States
    {
    Spawn:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
        9ND4 X 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1)
        9ND4 X -1
        Stop
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 A_CustomMissile ("XDeathBurnedImpArm", 32, 0, random (0, 360), 2, random (0, 160))        Stop
    Death:    
    TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360))
    TNT1 A 0 A_CustomMissile ("GibSavageImpHand", 0, 0, random (0, 180), 2, random (0, 180))
    TNT1 A 0 A_CustomMissile ("GibSavageImpArmPart", 0, 0, random (0, 180), 2, random (0, 180))
Stop
Stop
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
	    9ND4 AA 1 A_FaceTarget
		TNT1 A 0 A_CustomMissile ("XDeathSavageImpArm", 5, 0, random (170, 190), 2, random (20, 40))
		Stop
	
	Pain:
	TNT1 A 0
	TNT1 A 0 ThrustThingZ(0,20,0,1)
	9ND4 ABCDEFGH 3
	Goto Spawn
	
	Death.ExplosiveImpact:
	TNT1 A 0
	TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0)
	TNT1 A 0 ThrustThingZ(0,50,0,1)
	9ND4 X 5
	9ND4 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz")
	Goto Landz
	Landz:
	XDT5 I 0 A_SpawnItem("Gib_SavageImpArm")
	Stop	
}}

CLASS GibImpArmPart: TinyGib { 
	Default {
 
    Scale 1.1
	}
    States
    {
Spawn:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
        HND4 Z -1
        Stop
    Death:
        HND4 Z 1
       Loop
}}

CLASS GibImpHand: TinyGib { 
	Default {
 
    Scale 0.8
	}
    States
    {
Spawn:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
        HND4 Y -1
        Stop
    Death:
        HND4 Y 1
       Loop
}}


CLASS GibSavageImpArmPart: TinyGib { 
	Default {
 
    Scale 1.1
	}
    States
    {
Spawn:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
        9ND4 Z -1
        Stop
    Death:
        9ND4 Z 1
       Loop
}}

CLASS GibSavageImpHand: TinyGib { 
	Default {
 
    Scale 0.8
	}
    States
    {
Spawn:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
        9ND4 Y -1
        Stop
    Death:
        9ND4 Y 1
       Loop
}}


CLASS XDeathHalfImpUpperPart32 : ACTOR { 
	Default {
 
    Radius 2
    Height 2
    Scale 1.1
	Speed 12
	Gravity 0.3
	Mass 4
	Decal BrutalBloodSplat
CLASSceFactor 0.2 : ACTOR { 
	Default {
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			//TNT1 A 0 A_SpawnItem("Brutal_LiquidBlood",0,0,0,1)
			HND4 IJKLMNOPQ 3 A_CustomMissile("Brutal_LiquidBlood",0,0,0,1);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 AAA 0 A_spawnItem("Blood", 0, 10);
			HND4 Q 1 A_SpawnItem("Gib_HalfImpUpperPart32",0,0,0,1);
			TNT1 A 0;
			Stop;
	}
}

CLASS XDeathHalfSavageImpUpperPart32 : ACTOR { 
	Default {
		
		Radius 2;
		Height 2;
		Scale 1.1;
		Speed 12;
		Gravity 0.3;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.2;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			//TNT1 A 0 A_SpawnItem("Brutal_LiquidBlood",0,0,0,1)
			9ND4 IJKLMNOPQ 3 A_CustomMissile("Brutal_LiquidBlood",0,0,0,1);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 AAA 0 A_spawnItem("Blood", 0, 10);
			9ND4 Q 1 A_SpawnItem("Gib_HalfSavageImpUpperPart32",0,0,0,1);
			TNT1 A 0;
			Stop;
	}
}

CLASS Gib_HalfImpUpperPart32: BigGibBase { 
	Default {
		
		damagefactor "ExplosiveImpact", 5.0;
		Mass 10;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			HND4 Q -1;
			Stop   ();
		Death.ExplosiveImpact:
		Death.Explosive:
		Death.Kick:
		Death.SuperPunches:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			Goto Fly;
		Fly:
			HND4 IJKLMNOPQ 3 A_CheckFloor("Land");
			Loop;
		Land:
			HND4 Q 1 A_SpawnItem("Gib_HalfImpUpperPart32",0,0,0,1);
Stop }}	 

CLASS Gib_HalfSavageImpUpperPart32: BigGibBase { 
	Default {
		
		damagefactor "ExplosiveImpact", 5.0;
		Mass 10;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			9ND4 Q -1;
			Stop   ();
		Death.ExplosiveImpact:
		Death.Explosive:
		Death.Kick:
		Death.SuperPunches:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			Goto Fly;
		Fly:
			9ND4 IJKLMNOPQ 3 A_CheckFloor("Land");
			Loop;
		Land:
			9ND4 Q 1 A_SpawnItem("Gib_HalfSavageImpUpperPart32",0,0,0,1);
Stop }}	



CLASS XDeathHalfArchvile : ACTOR { 
	Default {
		
		Radius 2;
		Height 2;
		Scale 1.1;
		Speed 4;
		Gravity 2.3;
		Mass 200;
		Decal BrutalBloodSplat;
		BounceFactor 0.2;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			//TNT1 A 0 A_SpawnItem("Brutal_LiquidBlood",0,0,0,1)
			D6AX FFFF 3 A_CustomMissile("Brutal_LiquidBlood",0,0,0,1);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 AAA 0 A_spawnItem("BloodMist", 0, 10);
			D6AX F 1 A_SpawnItem("Gib_HalfArchvile",0,0,0,1);
			TNT1 A 0;
			Stop;
	}
}

CLASS Gib_HalfArchvile: BigGibBase { 
	Default {
		
		damagefactor "ExplosiveImpact", 5.0;
		Mass 100;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			D6AX G -1;
Stop  }}	 


CLASS XDeathHalfArchvile2 : ACTOR { 
	Default {
		
		Radius 2;
		Height 2;
		Scale 1.1;
		Speed 4;
		Gravity 2.3;
		Mass 200;
		Decal BrutalBloodSplat;
		BounceFactor 0.2;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			//TNT1 A 0 A_SpawnItem("Brutal_LiquidBlood",0,0,0,1)
			VILP AAAA 3 A_CustomMissile("Brutal_LiquidBlood",0,0,0,1);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 AAA 0 A_spawnItem("BloodMist", 0, 10);
			VILP B 1 A_SpawnItem("Gib_HalfArchvile2",0,0,0,1);
			TNT1 A 0;
			Stop;
	}
}

CLASS Gib_HalfArchvile2: BigGibBase { 
	Default {
		
		damagefactor "ExplosiveImpact", 5.0;
		Mass 100;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			VILP B -1;
Stop  }}

/////////////////////
//LEGS
/////////////////////

CLASS XDeathZombieLeg: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			LEG1 ABCDEFGH 5 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			LEG1 E 1;
			LEG1 E 0 A_SpawnItem("Gib_ZombieLeg1");
			Stop;
	}
}


CLASS Gib_ZombieLeg1: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LEG1 E 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			LEG1 E -1;
			Stop;
		Death.plasma:    TNT1 A 0 A_CustomMissile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160))        Stop
		Death:    
			TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_CustomMissile ("GibZombieLegPart", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_CustomMissile ("GibZombieBoot", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			LEG1 EE 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathZombieLeg", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			LEG1 ABCDEFGH 2;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			LEG1 A 5;
			LEG1 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
			Goto Landz;
		Landz:
			XDT5 I 0 A_SpawnItem("Gib_ZombieLeg2");
			Stop;
			
}}


CLASS XDeathPlasmaZombieLeg: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			ZM42 ABCDEFGH 5 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			ZM42 I 1;
			ZM42 E 0 A_SpawnItem("Gib_PlasmaZombieLeg");
			Stop;
	}
}


CLASS Gib_PlasmaZombieLeg: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			ZM42 I 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			ZM42 I -1;
			Stop;
		Death.plasma:    TNT1 A 0 A_CustomMissile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160))        Stop
		Death:    
			TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_CustomMissile ("GibZombieLegPart", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_CustomMissile ("GibZombieBoot", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			ZM42 I 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathPlasmaZombieLeg", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			ZM42 ABCDEFGH 2;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			ZM42 I 5;
			ZM42 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
			Goto Landz;
		Landz:
			XDT5 I 0 A_SpawnItem("Gib_PlasmaZombieLeg");
			Stop;
			
}}

CLASS GibZombieLegPart: TinyGib { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LEG1 Z -1;
			Stop;
		Death:
			LEG1 Z 1;
			Loop;
}}

CLASS GibZombieBoot: TinyGib { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LEG1 Y -1;
			Stop;
		Death:
			LEG1 Y 1;
			Loop;
}}


CLASS XDeathZombieLeg2: XDeathZombieLeg { 
	Default {
		
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			LEG1 ABCDEFGH 5 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			LEG1 A 1;
			TNT1 A 0 A_SpawnItem("Gib_ZombieLeg2");
			Stop;
	}
}


CLASS Gib_ZombieLeg2: LimbBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LEG1 A 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			LEG1 A -1;
			Stop;
		Death.plasma:    TNT1 A 0 A_CustomMissile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160))        Stop
		Death:    
			TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_CustomMissile ("GibZombieLegPart", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_CustomMissile ("GibZombieBoot", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			LEG1 AA 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathZombieLegKicked", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			LEG1 ABCDEFGH 2;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			LEG1 A 5;
			LEG1 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
			Goto Landz;
		Landz:
			XDT5 I 0 A_SpawnItem("Gib_ZombieLeg1");
			Stop;
}}

CLASS XDeathZombieLegKicked: XDeathZombieLeg { 
	Default {
		
		+ACTIVATEMCROSS;
		+ACTIVATEIMPACT;
	}
}




CLASS XDeathImpLeg: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			LEG4 ABCDEFGH 5 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			LEG4 I 1;
			LEG4 I 1 A_SpawnItem("Gib_ImpLeg");
			Stop;
			
	}
}

CLASS XDeathSavageImpLeg: XDeathImpLeg { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			1EG4 ABCDEFGH 5 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			1EG4 I 1;
			1EG4 I 1 A_SpawnItem("Gib_SavageImpLeg");
			Stop;
			
	}
}

CLASS Gib_ImpLeg: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LEG4 I 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			LEG4 I -1;
			Stop;
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 A_CustomMissile ("XDeathBurnedImpLeg", 32, 0, random (0, 360), 2, random (0, 160))        Stop
Death:    
	TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
	TNT1 A 0 A_CustomMissile ("GibImpLegPart", 0, 0, random (0, 180), 2, random (0, 180));
	TNT1 A 0 A_CustomMissile ("GibImpPaw", 0, 0, random (0, 180), 2, random (0, 180));
	Stop;
Death.Kick:
Death.Melee:
Death.SuperPunch:
	LEG4 A 1 A_FaceTarget();
	TNT1 A 0 A_CustomMissile ("XDeathImpLeg", 5, 0, random (170, 190), 2, random (20, 40));
	Stop;
	
Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	LEG4 ABCDEFGH 2;
	Goto Spawn;
	
Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	LEG4 A 5;
	LEG4 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
Landz:
	XDT5 I 0 A_SpawnItem("Gib_ImpLeg");
	Stop;
}}

CLASS Gib_SavageImpLeg: LimbBase { 
	Default {
 
    Scale 1.1
	}
    States
    {
    Spawn:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
		1EG4 I 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1)
		1EG4 I -1
        Stop
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 A_CustomMissile ("XDeathBurnedImpLeg", 32, 0, random (0, 360), 2, random (0, 160))        Stop
    Death:    
    TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360))
    TNT1 A 0 A_CustomMissile ("GibSavageImpLegPart", 0, 0, random (0, 180), 2, random (0, 180))
    TNT1 A 0 A_CustomMissile ("GibSavageImpPaw", 0, 0, random (0, 180), 2, random (0, 180))
Stop
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
	    1EG4 A 1 A_FaceTarget
		TNT1 A 0 A_CustomMissile ("XDeathImpLeg", 5, 0, random (170, 190), 2, random (20, 40))
		Stop
		
	Pain:
	TNT1 A 0
	TNT1 A 0 ThrustThingZ(0,20,0,1)
	1EG4 ABCDEFGH 2
	Goto Spawn
	
	Death.ExplosiveImpact:
	TNT1 A 0
	TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0)
	TNT1 A 0 ThrustThingZ(0,50,0,1)
	1EG4 A 5
	1EG4 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz")
	Goto Landz
	Landz:
	1EG4 I 0 A_SpawnItem("Gib_SavageImpLeg")
	Stop		
}}

CLASS GibImpLegPart: TinyGib { 
	Default {
 
    Scale 1.1
	}
    States
    {
Spawn:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
		LEG4 Z -1
        Stop
    Death:
LEG4 Z 1
       Loop
}}

CLASS GibImpPaw: TinyGib { 
	Default {
 
    Scale 1.1
	}
    States
    {
Spawn:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
		LEG4 Y -1
        Stop
    Death:
LEG4 Y 1
       Loop
}}

CLASS GibSavageImpLegPart: TinyGib { 
	Default {
 
    Scale 1.1
	}
    States
    {
Spawn:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
		1EG4 Z -1
        Stop
    Death:
1EG4 Z 1
       Loop
}}

CLASS GibSavageImpPaw: TinyGib { 
	Default {
 
    Scale 1.1
	}
    States
    {
Spawn:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
		1EG4 Y -1
        Stop
    Death:
1EG4 Y 1
       Loop
}}


CLASS XDeathBullLeg12: XDeathArm1 { 
	Default {
 
    Scale 1.1
    Speed 8
	Gravity 0.4
CLASSceFactor 0.4 : ACTOR { 
	Default {
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			LEG8 ABCDEFGH 4 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			LEG8 I 1;
			LEG8 I 0 A_SpawnItem("Gib_DemonLeg");
			Stop;
	}
}

CLASS Gib_DemonLeg: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			LEG8 GH 2;
			Goto Spawn1;
		Spawn1:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LEG8 I 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			LEG8 I -1;
			Stop;
			
			
		Death.plasma:    TNT1 A 0 A_CustomMissile ("XDeathBurnedDemonLeg", 32, 0, random (0, 360), 2, random (0, 160))        Stop
		Death:    
			TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_CustomMissile ("GibDemonLegPart", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_CustomMissile ("GibDemonPaw", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			LEG8 A 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathBullLeg12", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			LEG8 ABCDEFGH 2;
			Goto Spawn1;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			LEG8 A 5;
			LEG8 ABCDEFGH 5;
			XDT5 I 0 A_SpawnItem("Gib_DemonLeg");
Stop}}
	
CLASS XDeathBloodDemonLeg12: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			M3G7 ABCDEFGH 4 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			M3G7 I 1;
			M3G7 I 0 A_SpawnItem("Gib_BloodDemonLeg");
			Stop;
	}
}

CLASS Gib_BloodDemonLeg: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			M3G7 I 0;
			M3G7 I 0 A_Jump(128, "Spawn2");
			Goto Spawn1;
			
		Spawn1:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			M3G7 I 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			M3G7 I -1;
			Stop;
			
		Spawn2:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			M3G7 J 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			M3G7 J -1;
			Stop;
			
			
		Death.plasma:    TNT1 A 0 A_CustomMissile ("XDeathBurnedDemonLeg", 32, 0, random (0, 360), 2, random (0, 160))        Stop
		Death:    
			TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_CustomMissile ("GibDemonLegPart", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_CustomMissile ("GibDemonPaw", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			M3G7 A 0 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathBloodDemonLeg12", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			M3G7 ABCDEFGH 2;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			M3G7 A 5;
			M3G7 ABCDEFGH 5;
			XDT5 I 0 A_SpawnItem("Gib_BloodDemonLeg");
Stop}}

CLASS XDeathVoidSpectreLeg: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
		Decal GreenBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			L3G8 ABCDEFGH 4 A_CustomMissile ("Green_FlyingBlood", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			L3G8 H 1;
			L3G8 I 0 A_SpawnItem("Gib_VoidSpectreLeg");
			Stop;
	}
}

CLASS Gib_VoidSpectreLeg: LimbBase { 
	Default {
		
		Scale 1.1;
		BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood";
		BloodColor "DarkGreen";
	}
	States
	{
		Spawn:
			L3G8 GH 2;
		Spawn1:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			L3G8 H 1 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			L3G8 H -1;
			Stop;
			
			
		Death.plasma:    TNT1 A 0 A_CustomMissile ("XDeathBurnedDemonLeg", 32, 0, random (0, 360), 2, random (0, 160))        Stop
		Death:    
			TNT1 AAAA 0 A_CustomMissile ("Green_FlyingBlood", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_CustomMissile ("XDeath1Green", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_CustomMissile ("XDeath2Green", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			L3G8 A 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathVoidSpectreLeg", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			L3G8 ABCDEFGH 2;
			Goto Spawn1;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			L3G8 A 5;
			L3G8 ABCDEFGH 5;
			XDT5 I 0 A_SpawnItem("Gib_VoidSpectreLeg");
Stop}}

CLASS GibDemonLegPart: TinyGib { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LEG8 Z -1;
			Stop;
		Death:
			LEG8 Z 1;
			Loop;
}}

CLASS GibDemonPaw: TinyGib { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LEG8 Y 1;
			Stop;
		Death:
			LEG8 Y 1;
			Loop;
}}







CLASS XDeathSargeLeg1: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			LEG2 ABCDEFGH 5 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			LEG2 A 1;
			LEG2 A 0 A_SpawnItem("Gib_SargeLeg");
			Stop;
	}
}

CLASS Gib_SargeLeg: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LEG2 A 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			LEG2 A -1;
			Stop;
		Death.plasma:    TNT1 A 0 A_CustomMissile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160))        Stop
		Death:    
			TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_CustomMissile ("GibSargeLegPart", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_CustomMissile ("GibSargeBoot", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			LEG2 A 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathSargeLeg1", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			LEG2 ABCDEFGH 2;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			LEG2 ABCDEFGH 5;
			XDT5 I 0 A_SpawnItem("Gib_SargeLeg");
			Stop;
			
}}

CLASS GibSargeLegPart: TinyGib { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LEG2 Z -1;
			Stop;
		Death:
			LEG2 Z 1;
			Loop;
}}

CLASS GibSargeBoot: TinyGib { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LEG2 Y -1;
			Stop;
		Death:
			LEG2 Y 1;
			Loop;
}}



CLASS XDeathSargeLeg2: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			LEG2 ABCDEFGH 5 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			LEG2 E 1;
			LEG2 E 1 A_SpawnItem("Gib_SargeLeg2");
			Stop;
	}
}

CLASS Gib_SargeLeg2: Gib_SargeLeg { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LEG2 E 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			LEG2 E -1;
			Stop;
		Death.plasma:    TNT1 A 0 A_CustomMissile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160))        Stop
		Death:    
			TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_CustomMissile ("GibSargeLegPart", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_CustomMissile ("GibSargeBoot", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			LEG2 A 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathSargeLeg1", 5, 0, random (170, 190), 2, random (20, 40));
Stop}}






CLASS XDeathChainLeg: XDeathArm1 { 
	Default {
		
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			LEG3 ABCDEFGH 5;
			Loop;
		Death:
			LEG3 A 1;
			LEG3 A 0 A_SpawnItem("Gib_ChainLeg");
			Stop;
	}
}

CLASS Gib_ChainLeg: LimbBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LEG3 I 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			LEG3 I -1;
			Stop;
		Death.plasma:    TNT1 A 0 A_CustomMissile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160))        Stop
		Death:    
			TNT1 AAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Stop;
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			LEG3 A 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathChainLeg", 5, 0, random (170, 190), 2, random (20, 40));
Stop}}



CLASS XDeathChainArm: XDeathArm1 { 
	Default {
		
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			HND3 ABCDEFGH 5;
			Loop;
		Death:
			HND3 A 1;
			HND3 A 0 A_SpawnItem("Gib_ChainArm");
			Stop;
	}
}

CLASS Gib_ChainARm: LimbBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Jump (128, "Spawn2");
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			HND3 E 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			HND3 E -1;
			Stop;
		Spawn2:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			HND3 A 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			HND3 A -1;
			Stop;
		Death.plasma:    TNT1 A 0 A_CustomMissile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160))        Stop
		Death:    
			TNT1 AAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Stop;
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			HND3 A 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathChainArm", 5, 0, random (170, 190), 2, random (20, 40));
Stop}}




//////////////
//GUTS
//////////////


CLASS XDeathStomach: XDeathArm1 { 
	Default {
		
		-DOOMBOUNCE;
		BounceFactor 0.0;
		Speed 2;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			XSTO A 24 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			XSTO EEEEEEEEE 0 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 180), 2, random (0, 180));
			XSTO E -1;
			Stop;
	}
}

CLASS XDeathStomachGreen: XDeathArm1 { 
	Default {
		
translation "168:191=112:127","16:47=120:127"
	-DOOMBOUNCE;
	BounceFactor 0.0;
	Speed 2;
	}
    States
    {
Spawn:
	TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
	XSTO A 24 A_CustomMissile ("Green_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
	Loop;
Death:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse();
	TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
	XSTO EEEEEEEEE 0 A_CustomMissile ("Green_FlyingBloodTrail", 0, 0, random (0, 180), 2, random (0, 180));
	XSTO E -1;
	Stop;
}
}



CLASS XDeathDemonHead : ACTOR { 
	Default {
 
    Radius 8
    Height 8
    Scale 0.8
	Speed 10
	Mass 1
    gravity 0.5
	Decal BrutalBloodSplat
CLASSceFactor 0.4 : ACTOR { 
	Default {
		BounceCount 5;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			DEMH ABCDEF 7 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_SpawnItem("Gib_DemonHead");
			Stop;
	}
}

CLASS Gib_DemonHead: LimbBase { 
	Default {
		
		Scale 0.9;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Jump (128, "Spawn2");
		Stay:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			DEMH I -1;
			Stop;
			
		Spawn2:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			DEMH J -1;
			Stop;
			
		Death.plasma:    TNT1 A 0 A_CustomMissile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160))        Stop
		Death:    
			TNT1 A 0 A_SpawnItem("MeatDeathSmall");
			TNT1 AA 0 A_CustomMissile ("XDeathBrain1", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeathBrain2", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath3", 10, random (5, -5), random (160, 200), 2, random (-10, 10));
			TNT1 AA 0 A_CustomMissile ("XDeath2", 10, random (5, -5), random (160, 200), 2, random (-10, 10));
			TNT1 AAAA 0 A_CustomMissile ("BloodMistBig", 10, 0, random (0, 360), 2, random (30, 90));
			TNT1 AA 0 A_CustomMissile ("PinkyHeadPiece", 12, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_CustomMissile ("PinkyJaw", 12, 0, random (0, 360), 2, random (0, 160));
			
			Stop;
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			HND3 A 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathDemonHead", 5, 0, random (170, 190), 2, random (20, 40));
Stop}}
		
CLASS XDeathBloodDemonHead : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.8;
		Speed 10;
		Mass 1;
		gravity 0.5;
		Decal BrutalBloodSplat;
		BounceFactor 0.4;
		BounceCount 5;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			M3G6 ABCDEFGH 7 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_SpawnItem("Gib_BloodDemonHead");
			Stop;
	}
}

CLASS Gib_BloodDemonHead: LimbBase { 
	Default {
		
		Scale 0.9;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Jump (128, "Spawn2");
		Stay:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			M3G6 I -1;
			Stop;
			
		Spawn2:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			M3G6 J -1;
			Stop;
			
		Death.plasma:    TNT1 A 0 A_CustomMissile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160))        Stop
		Death:    
			TNT1 A 0 A_SpawnItem("MeatDeathSmall");
			TNT1 AA 0 A_CustomMissile ("XDeathBrain1", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeathBrain2", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath3", 10, random (5, -5), random (160, 200), 2, random (-10, 10));
			TNT1 AA 0 A_CustomMissile ("XDeath2", 10, random (5, -5), random (160, 200), 2, random (-10, 10));
			TNT1 AAAA 0 A_CustomMissile ("BloodMistBig", 10, 0, random (0, 360), 2, random (30, 90));
			TNT1 AA 0 A_CustomMissile ("PinkyHeadPiece", 12, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_CustomMissile ("PinkyJaw", 12, 0, random (0, 360), 2, random (0, 160));
			
			Stop;
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			M3G6 A 0 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathBloodDemonHead", 5, 0, random (170, 190), 2, random (20, 40));
Stop}}

CLASS XDeathVoidSpectreHead : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.8;
		Speed 10;
		Mass 1;
		gravity 0.5;
		Decal BrutalBloodSplat;
		BounceFactor 0.4;
		BounceCount 5;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			E3G9 ABCDEF 7 A_CustomMissile ("Green_FlyingBlood", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			TNT1 A 0 A_SpawnItem("Gib_VoidSpectreHead");
			Stop;
	}
}

CLASS Gib_VoidSpectreHead: LimbBase { 
	Default {
		
		Scale 0.9;
	}
	States
	{
		Spawn:
			TNT1 A 0;
		Stay:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			E3G9 I -1;
			Stop;
			
			
		Death.plasma:    TNT1 A 0 A_CustomMissile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160))        Stop
		Death:    
			TNT1 AA 0 A_CustomMissile ("XDeath1Green", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath3Green", 10, random (5, -5), random (160, 200), 2, random (-10, 10));
			TNT1 AA 0 A_CustomMissile ("XDeath2Green", 10, random (5, -5), random (160, 200), 2, random (-10, 10));
			TNT1 AAAA 0 A_CustomMissile ("GreenBloodMistBig", 10, 0, random (0, 360), 2, random (30, 90));
			TNT1 AA 0 A_CustomMissile ("VoidSpectreHeadPiece", 12, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_CustomMissile ("XDeathVoidSpectreEyeball", 12, 0, random (0, 360), 2, random (0, 160));
			Stop;
			
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			HND3 A 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathVoidSpectreHead", 5, 0, random (170, 190), 2, random (20, 40));
Stop}}

CLASS XDeathHalfMarine : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 4;
		Mass 8;
		BounceFactor 0.2;
		BounceCount 3;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal BrutalBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			HPLA A 12 A_CustomMissile("Brutal_FlyingBloodTrail",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			HPLA A 0 A_SpawnItem("HalfMarineGib",0,0,0,1);
			Stop;
	}
}

CLASS HalfMarineGib: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			HPLA A 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			HPLA A -1;
Stop    }}


CLASS XDeathHalfImp : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 7;
		Mass 8;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal BrutalBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TROG I 12 A_CustomMissile("Brutal_FlyingBloodTrail",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TROG I 0 A_SpawnItem("HalfImpGib",0,0,0,1);
			Stop;
	}
}


CLASS HalfImpGib: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TROG J 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TROG J -1;
Stop    }}


CLASS XDeathHalfZombieman : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 1.0;
		Speed 6;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			POSX F 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			POSX F 1 A_SpawnItem("Gib_HalfZombieman",0,0,0,1);
			TNT1 A 0;
			Stop;
	}
}

CLASS XDeathHalfZSpecOPs : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 1.0;
		Speed 6;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			ZP3X B 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			ZP3X B 1 A_SpawnItem("Gib_HalfZSpecOPs",0,0,0,1);
			TNT1 A 0;
			Stop;
	}
}

CLASS XDeathHalfHelmetZombieman : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 1.0;
		Speed 6;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			4OSX F 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			4OSX F 1 A_SpawnItem("Gib_HalfHelmetZombieman",0,0,0,1);
			TNT1 A 0;
			Stop;
	}
}

CLASS XDeathHalfHFQSZ : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 1.0;
		Speed 6;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			QP3X F 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			QP3X F 1 A_SpawnItem("Gib_HalfHFQSZ",0,0,0,1);
			TNT1 A 0;
			Stop;
	}
}

CLASS Gib_HalfZombieMan: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			POSX F 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			POSX F -1;
Stop    }}
	   
CLASS Gib_HalfHelmetZombieMan: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			4OSX F 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			4OSX F -1;
Stop    }}
	   
CLASS Gib_HalfHFQSZ: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			QP3X G 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			QP3X G -1;
Stop    }}
	   
CLASS Gib_HalfZSpecOPs: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			ZP3X C 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			ZP3X C -1;
Stop    }}
	   

CLASS XDeathHalfZombiemanNoArmNoHead : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.3;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			POSX GHIJKLMN 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_HalfZombiemanNoArmNoHead",0,0,0,1);
			Stop;
	}
}

CLASS Gib_HalfZombieManNoArmNoHead: BigGibBase { 
	Default {
		
		Scale 1.3;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			POSX O -1;
Stop    }}
	   
	   
CLASS XDeathHalfPlasmaZombiemanNoArmNoHead : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.3;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			ZM40 ABCDEFGH 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_HalfPlasmaZombieManNoArmNoHead",0,0,0,1);
			Stop;
	}
}

CLASS Gib_HalfPlasmaZombieManNoArmNoHead: BigGibBase { 
	Default {
		
		Scale 1.3;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			ZM40 I -1;
Stop    }}	
	   
CLASS XDeathHalfLabGuyNoArmNoHead : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.3;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			PLSX GHIJKLMN 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_HalfLabguyNoArmNoHead",0,0,0,1);
			Stop;
	}
}

CLASS Gib_HalfLabguyNoArmNoHead: BigGibBase { 
	Default {
		
		Scale 1.3;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			PLSX O -1;
Stop    }}



CLASS XDeathHalfShotgunguyNoArmNoHead : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.3;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			SPSX GHIJKLMN 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_HalfShotgunguyNoArmNoHead",0,0,0,1);
			Stop;
	}
}

CLASS XDeathHalfChaingunMajorNoArmNoHead : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.55;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			4CH7 ABCDEFGH 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_HalfChaingunMajorNoArmNoHead",0,0,0,1);
			Stop;
	}
}

CLASS Gib_HalfShotgunguyNoArmNoHead: BigGibBase { 
	Default {
		
		Scale 1.3;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			SPSX O -1;
Stop    }}	
	   
CLASS Gib_HalfChaingunMajorNoArmNoHead: BigGibBase { 
	Default {
		
		Scale 1.55;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			4CH7 I -1;
Stop    }}	


CLASS XDeathHalfZombiemanDown : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 1.1;
		Speed 6;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
		Stay:
			POSX D 2000;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			POSX E 0 A_SpawnItem("GibHalfZombiemanDown",0,0,0,1);
			Stop;
	}
}

CLASS GibHalfZombiemanDown: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			POSX E 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			POSX E -1;
Stop    }}



CLASS XDeathHalfSergeant : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 7;
		Mass 8;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal BrutalBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			SP2X F 12 A_CustomMissile("BloodTrails",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			SP2X G 0 A_SpawnItem("GibHalfSergeant",0,0,0,1);
			Stop;
	}
}


CLASS XDeathHalfPlasmaZombie2 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 1;
		Mass 8;
		BounceFactor 0.1;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal BrutalBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			ZMS0 FG 7;
		Fly:
			ZMS0 H 12 A_CustomMissile("BloodTrails",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			ZMS0 I 6;
			TNT1 A 0 A_SpawnItem("GibHalfPlasmaZombie2",0,0,0,1);
			Stop;
	}
}

CLASS GibHalfPlasmaZombie2: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			ZMS0 I 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			ZMS0 I -1;
Stop    }}


CLASS XDeathHalfSergeant2 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 1;
		Mass 8;
		BounceFactor 0.1;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal BrutalBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			SXD1 JK 7;
		Fly:
			SXD1 L 12 A_CustomMissile("BloodTrails",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			SXD1 M 6;
			SXD1 N 0 A_SpawnItem("GibHalfSergeant2",0,0,0,1);
			Stop;
	}
}

CLASS GibHalfSergeant2: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			SXD1 N 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			SXD1 N -1;
Stop    }}

CLASS XDeathHalfHelmetSergeant : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 7;
		Mass 8;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal BrutalBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			SP4X F 12 A_CustomMissile("BloodTrails",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			SP4X G 0 A_SpawnItem("GibHalfHelmetSergeant",0,0,0,1);
			Stop;
	}
}

CLASS GibHalfHelmetSergeant: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			SP4X G 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			SP4X G -1;
Stop    }}


CLASS XDeathHalfChaingunGuy1 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 7;
		Mass 8;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal BrutalBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			CP04 W 12 A_CustomMissile("BloodTrails",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 G 0 A_SpawnItem("GibHalfChaingunGuy1",0,0,0,1);
			Stop;
	}
}

CLASS GibHalfChaingunGuy1: CurbstompedMarine { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			CP04 X 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			CP04 X -1;
Stop    }}
	   
CLASS XDeathHalfChaingunGuy2 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 7;
		Mass 8;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal BrutalBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			CP06 K 12 A_CustomMissile("BloodTrails",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 G 0 A_SpawnItem("GibHalfChaingunGuy2",0,0,0,1);
			Stop;
	}
}

CLASS GibHalfChaingunGuy2: CurbstompedMarine { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			CP06 L 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			CP06 L -1;
			Stop;
}}
////////////////////////////////

CLASS XDeathHalfHelmetChaingunGuy1 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 7;
		Mass 8;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal BrutalBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			C404 W 12 A_CustomMissile("BloodTrails",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 G 0 A_SpawnItem("GibHalfHelmetChaingunGuy1",0,0,0,1);
			Stop;
	}
}

CLASS GibHalfHelmetChaingunGuy1: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			C404 X 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			C404 X -1;
Stop    }}
	   
CLASS XDeathHalfHelmetChaingunGuy2 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 7;
		Mass 8;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal BrutalBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			C404 K 12 A_CustomMissile("BloodTrails",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 G 0 A_SpawnItem("GibHalfHelmetChaingunGuy2",0,0,0,1);
			Stop;
	}
}

CLASS GibHalfHelmetChaingunGuy2: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			C404 L 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			C404 L -1;
Stop    }}

////////////////////////////////
CLASS XDeathHalfZombieman2 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 7;
		Mass 8;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal BrutalBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			PP2X F 12 A_CustomMissile("BloodTrails",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 G 0 A_SpawnItem("GibHalfZombieman2",0,0,0,1);
			Stop;
	}
}

CLASS GibHalfZombieman2: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			PP2X G 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			PP2X G -1;
Stop    }}

CLASS XDeathHalfHelmetZombieman2 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 7;
		Mass 8;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal BrutalBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			4P2X F 12 A_CustomMissile("BloodTrails",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_SpawnItem("GibHalfHelmetZombieman2",0,0,0,1);
			Stop;
	}
}

CLASS GibHalfHelmetZombieman2: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			4P2X G 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			4P2X G -1;
Stop    }}

CLASS GibHalfSergeant: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			SP2X G 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			SP2X G -1;
Stop    }}

CLASS XDeathHellionLeg: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			03AG ABCDEFGH 5 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			03AG I 1;
			03AG E 0 A_SpawnItem("Gib_HellionLeg");
			Stop;
	}
}


CLASS Gib_HellionLeg: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			03AG I 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			03AG I -1;
			Stop;
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 A_CustomMissile ("XDeathBurnedImpLeg", 32, 0, random (0, 360), 2, random (0, 160))        Stop
Death:    
	TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
	TNT1 AAA 0 A_CustomMissile ("XDeath1", 0, 0, random (0, 180), 2, random (0, 180));
	Stop;
Death.Kick:
Death.Melee:
Death.SuperPunch:
	03AG A 1 A_FaceTarget();
	TNT1 A 0 A_CustomMissile ("XDeathHellionLeg", 5, 0, random (170, 190), 2, random (20, 40));
	Stop;
	
Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	03AG ABCDEFGH 2;
	Goto Spawn;
	
Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	03AG A 5;
	03AG ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
Landz:
	03AG I 0 A_SpawnItem("Gib_HellionLeg");
	Stop;
}}

CLASS XDeathHellionArm: XDeathArm1 { 
	Default {
 
    Scale 1.1
    Speed 8
	Gravity 0.4
CLASSceFactor 0.4 : ACTOR { 
	Default {
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			01AG ABCDEFGH 5 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			01AG I 1;
			01AG E 0 A_SpawnItem("Gib_HellionArm");
			Stop;
	}
}


CLASS Gib_HellionArm: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			01AG I 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			01AG I -1;
			Stop;
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 A_CustomMissile ("XDeathBurnedImpArm", 32, 0, random (0, 360), 2, random (0, 160))        Stop
Death:    
	TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
	TNT1 AAA 0 A_CustomMissile ("XDeath1", 0, 0, random (0, 180), 2, random (0, 180));
	Stop;
Death.Kick:
Death.Melee:
Death.SuperPunch:
	01AG A 1 A_FaceTarget();
	TNT1 A 0 A_CustomMissile ("XDeathHellionArm", 5, 0, random (170, 190), 2, random (20, 40));
	Stop;
	
Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	01AG ABCDEFGH 2;
	Goto Spawn;
	
Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	01AG A 5;
	01AG ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
Landz:
	03AG I 0 A_SpawnItem("Gib_HellionArm");
	Stop;
}}


CLASS XDeathHellionTorso: XDeathArm1 { 
	Default {
 
    Scale 1.1
    Speed 10
	Gravity 0.4
CLASSceFactor 0.4 : ACTOR { 
	Default {
		+SKYEXPLODE;
		Species "Marines";
		+THRUSPECIES;
		BounceCount 5;
		Radius 10;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			04AG ABCD 3 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			D3AX E 1;
			D3AX E 0 A_SpawnItem("Gib_HellionTorso",0,0,0,1);
			Stop;
	}
}

CLASS Gib_HellionTorso: LimbBase { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			04AG E 2;
			Goto Spawn1;
			
		Spawn1:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			04AG E 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			04AG E -1;
			Stop;
		Death:    
			TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAA 0 A_CustomMissile ("Xdeath1", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 AA 0 A_CustomMissile ("Xdeath2", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 AAA 0 A_CustomMissile ("BloodMistBig", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
			
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			04AG AA 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathHellionTorso", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			04AG ABCD 3;
			Goto Spawn1;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			04AG A 5;
			04AG ABCDABCDABCDABCD 5 A_CheckFloor("Landz");
			Goto Landz;
			
		Landz:
			XDT5 I 0 A_SpawnItem("Gib_HellionTorso");
			Stop;
}}

CLASS XDeathHellionPelvis: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 10;
		Gravity 0.4;
		BounceFactor 0.4;
		+SKYEXPLODE;
		Species "Marines";
		+THRUSPECIES;
		BounceCount 5;
		Radius 10;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			05AG ABCDEFGHIJKLMNOP 1 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			05AG Q 1;
			D3AX E 0 A_SpawnItem("Gib_HellionPelvis",0,0,0,1);
			Stop;
	}
}

CLASS Gib_HellionPelvis: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			05AG Q 2;
			Goto Spawn1;
			
		Spawn1:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			05AG Q 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			05AG Q -1;
			Stop;
		Death:    
			TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAA 0 A_CustomMissile ("Xdeath1", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 AA 0 A_CustomMissile ("Xdeath2", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 AAA 0 A_CustomMissile ("BloodMistBig", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
			
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			05AG QQ 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathHellionPelvis", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			05AG ABCDEFGHIJKLMNOP 1;
			Goto Spawn1;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			05AG ABCDEFGHIJKLMNOP 1 A_CheckFloor("Landz");
			Goto Landz;
			
		Landz:
			XDT5 I 0 A_SpawnItem("Gib_HellionPelvis");
			Stop;
}}

CLASS XDeathHellionHead: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 10;
		Gravity 0.4;
		BounceFactor 0.4;
		+SKYEXPLODE;
		Species "Marines";
		+THRUSPECIES;
		BounceCount 5;
		Radius 10;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			02AG ABCDEFGHI 3 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			02AG i 1;
			02AG E 0 A_SpawnItem("Gib_HellionHead",0,0,0,1);
			Stop;
	}
}

CLASS Gib_HellionHead: LimbBase { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			02AG I 2;
			Goto Spawn1;
			
		Spawn1:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			02AG I 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			02AG I -1;
			Stop;
		Death:    
			TNT1 AAAAA 0 A_CustomMissile ("BloodMistBig", 2, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAAAA 0 A_CustomMissile ("Brutal_FlyingBlood", 2, 0, random (0, 360), 2, random (30, 90));
			TNT1 A 0 A_CustomMissile ("Brains2", 2, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_CustomMissile ("Brains3", 2, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_CustomMissile ("SmallBrainPieceFast", 2, random (5, -5), random (170, 190), 2, random (-10, 10));
			TNT1 AAAAA 0 A_CustomMissile ("SmallBrainPiece", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_CustomMissile ("Teeth", 4, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_CustomMissile ("XDeath1", 3, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath2", 3, 0, random (0, 360), 2, random (0, 160));
			Stop;
			
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			02AG I 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathHellionHead", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			02AG CDEFGHI 2;
			Goto Spawn1;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			02AG CDEFGHI 3 A_CheckFloor("Landz");
			Goto Landz;
			
		Landz:
			XDT5 I 0 A_SpawnItem("Gib_HellionHead");
			Stop;
}}

CLASS RipUndeadMarine : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 4;
		Mass 8;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal BrutalBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			UDM3 E 4 A_CustomMissile("Brutal_FlyingBloodTrail",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			UDM3 E -1;
			Stop;
	}
}

CLASS XDeathHalfSkeleton : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 9;
		Mass 8;
		BounceFactor 0.4;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal BrutalBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			SKEX F 12 A_CustomMissile("Brutal_FlyingBloodTrail",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			SKEX F 0 A_SpawnItem("GibHalfSkeleton",0,0,0,1);
			Stop;
	}
}

CLASS XDeathHalfDraugr : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 9;
		Mass 8;
		BounceFactor 0.4;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal BrutalBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BNP4 E 12 A_CustomMissile("Brutal_FlyingBloodTrail",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			BNP4 E 0 A_SpawnItem("GibHalfDraugr",0,0,0,1);
			Stop;
	}
}

CLASS GibHalfDraugr: BigGibBase { 
	Default {
		
		Radius 8;
		damagefactor "Kick", 12.0;
		damagefactor "ExtremePunches", 12.0;
		damagefactor "Melee", 12.0;
		damagefactor "Fatality", 12.0;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			BNP4 E 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			BNP4 E -1;
			Stop   ();
		Death.Trample:
		Death:
			TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("CheckTraditional")==1,2);
			TNT1 A 0 A_SpawnItem("HellishMissileLauncher");
			TNT1 AA 0 A_CustomMissile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
			Stop;
}}

CLASS GibHalfSkeleton: BigGibBase { 
	Default {
		
		Radius 8;
		damagefactor "Kick", 12.0;
		damagefactor "ExtremePunches", 12.0;
		damagefactor "Melee", 12.0;
		damagefactor "Fatality", 12.0;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			SKEX F 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			SKEX F -1();
			Stop   ();
		Death.Trample:
		Death:
			TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("CheckTraditional")==1,2);
			TNT1 A 0 A_SpawnItem("HellishMissileLauncher");
			TNT1 AA 0 A_CustomMissile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
			Stop;
}}
		
CLASS GibHalfSkeletonJustLegs: BigGibBase { 
	Default {
		
		Radius 8;
		damagefactor "Kick", 12.0;
		damagefactor "ExtremePunches", 12.0;
		damagefactor "Melee", 12.0;
		damagefactor "Fatality", 12.0;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			SKEX E 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			SKEX E -1();
			Stop   ();
		Death.Trample:
		Death:
			TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("CheckTraditional")==1,2);
			TNT1 AA 0 A_CustomMissile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
			Stop;
}}

CLASS XDeathMeat2 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.8;
		Speed 11;
		Mass 1;
		BounceFactor 0.4;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDT5 D 2;
			Goto Death;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XDT5 D -1;
			Stop;
	}
}

CLASS XDeathBrain1 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.8;
		Speed 13;
		Mass 1;
		BounceFactor 0.3;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+MISSILE;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDB5 ABCD 6;
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_Jump(128, "Death2");
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XDT5 B -1;
			Stop;
		Death2:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XDT5 O -1;
			Stop;
	}
}

CLASS XDeathBrain2 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.8;
		Speed 12;
		Mass 1;
		BounceFactor 0.3;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+MISSILE;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDB5 EFGH 6;
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XDT5 C -1;
			Stop;
	}
}

CLASS XDeathSmashedBrain : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.8;
		Speed 10;
		Mass 1;
		BounceFactor 0.4;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BRS1 A 4;
			Goto Death;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			BRS1 A -1;
			Stop;
	}
}

CLASS XDeathStomachHeavy : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.8;
		Speed 2;
		Mass 4;
		Decal BrutalBloodSplat;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			XDT5 F 1;
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XDT5 F -1;
			Stop;
	}
}

CLASS XDeathTripe : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.8;
		Speed 13;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.4;
		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			XDT5 H 1;
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XDT5 H -1;
			Stop;
	}
}

CLASS XDeathTripeHeavy : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.8;
		Speed 2;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.4;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			XDT5 H 1;
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XDT5 H -1;
			Stop;
	}
}


CLASS XDeathArchVile : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Mass 1;
		BounceFactor 0.4;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			VILP A 4 A_CustomMissile("BloodTrails",0,0,180,2);
			Goto Death;
		Death:
			VILP B 0;
			VILP B 0 A_SpawnItem("GibArchVile",0,0,0,1);
			Stop;
	}
}

CLASS GibArchVile: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			VILP B 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			VILP B -1;
Stop    }}

CLASS XDeathArchVileLeg1 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Mass 1;
		BounceFactor 0.4;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			VILP C 4 A_CustomMissile("BloodTrails",0,0,180,2);
			Goto Death;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			VILP C -1;
			Stop;
	}
}


CLASS XDeathGreen : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 18;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+DOOMBOUNCE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Decal GreenBloodSuper;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 4 A_CustomMissile("GreenBloodTrail",0,0,180,2);
			Loop;
		Death:
			TNT1 A 1;
			Stop;
	}
}

CLASS XDeathBlue1 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+DOOMBOUNCE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Decal BlueBloodSplat;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDT6 A 6 A_CustomMissile("Blue_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XDT6 A -1;
			Stop;
	}
}

CLASS XDeathBlue2 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+DOOMBOUNCE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Decal BlueBloodSplat;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDT6 B 6 A_CustomMissile("Blue_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XDT6 B -1;
			Stop;
	}
}

CLASS XDeathBlue3 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Decal BlueBloodSuper;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDT6 C 6 A_CustomMissile("Blue_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XDT6 C -1;
			Stop;
	}
}

CLASS XDeathBlue4 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Decal BlueBloodSuper;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDT6 D 6 A_CustomMissile("Blue_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XDT6 D -1;
			Stop;
	}
}

CLASS XDeathBlue5 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Decal BlueBloodSuper;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDT6 E 6 A_CustomMissile("Blue_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XDT6 E -1;
			Stop;
	}
}

CLASS SpiderLeg : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+DOOMBOUNCE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		BounceFactor 0.3;
		BounceCount 3;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDSL ABCDEFGH 2;
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XDSL I -1;
			Stop;
	}
}

CLASS Instestin : ACTOR { 
	Default {
		
		Radius 8;
		Height 12;
		Speed 6;
		Mass 1;
		BounceFactor 0.4;
		Renderstyle "Translucent";
		Alpha 0.9;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+FORCEXYBILLBOARD;
		-EXPLODEONWATER;
		DeathSound "misc/xdeath2";
		Decal BrutalBloodSplat;
		Scale 0.8;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3", "Spawn4");
			
		Spawn1:
			GUTS A 4;
			Loop;
			
		Spawn2:
			GUTS B 4;
			Loop;
			
		Spawn3:
			GUTS C 4;
			Loop;
			
		Spawn4:
			GUTS D 4;
			Loop;
			
		Death:
			
			GUTS E 0;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Water");
			TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
			Goto Rest;
			
			
		Rest:
			TNT1 A 0;
			TNT1 A 0 A_SetAngle(random(0,360));
			TNT1 A 0 A_ChangeFlag("FLATSPRITE", 1);
			TNT1 A 0 A_QueueCorpse();
			TNT1 A 0 A_Jump(255, "Rest1", "Rest2");
		Rest1:
			GUTS Y -1;
			Stop;
			
		Rest2:
			GUTS Z -1;
			Stop;
		DoNothing:
			TNT1 A 0;
			Stop;
			
		Water:
			TNT1 A 0;
			TNT1 A 0 A_Jump(128, "Water2");
			Goto Water1;
			
		Water1:
			GUTS GH 10;
			//TNT1 A 0 A_JumpIf(waterlevel == 0, "Death")
			Loop;
			
		Water2:
			GUTS IJ 10;
			//TNT1 A 0 A_JumpIf(waterlevel == 0, "Death")
			Loop;
	}
}

CLASS Instestin2: Instestin { 
	Default {
		
		Speed 3;
	}
}

CLASS DyingDemon : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 0;
		Mass 6;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+DONTSPLASH;
		+CLIENTSIDEONLY;
		+FORCEXYBILLBOARD;
	}
	States
	{
		Spawn:
			SARH AAA 4 A_SpawnItem ("Big_Blood", 0, 50);
			SARH BBB 4 A_SpawnItem ("Big_Blood", 0, 40);
			SARH CCC 4 A_SpawnItem ("Big_Blood", 0, 30);
			SARH DDDDDDDDDDDDDDD 4 A_SpawnItem ("Big_Blood", 0, 20);
			TNT1 A 0 A_SpawnItem ("DeadDemonNoHead", 1);
			Stop;
	}
}











CLASS GenericHKGib1: XDeathArm1 { 
	Default {
		
		Scale 0.9;
		Speed 5;
		BounceFactor 0.4;
		BounceCount 3;
		+CLIENTSIDEONLY;
		Gravity 0.8;
	}
	States
	{
		Spawn:
			GG71 A 4 A_CustomMissile ("Green_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			GG71 A -1;
			Stop;
	}
}

CLASS GenericHKGib2: GenericHKGib1 { 
	Default {
		
		Scale 1.2;
	}
	States
	{
		Spawn:
			GG71 B 4 A_CustomMissile ("Green_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			GG71 B -1;
			Stop;
	}
}

CLASS GenericHKGib3: GenericHKGib1 { 
	Default {
		
		Scale 0.8;
	}
	States
	{
		Spawn:
			GG71 C 4 A_CustomMissile ("Green_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			GG71 C -1;
			Stop;
	}
}

CLASS GenericHKGib4: GenericHKGib1 { 
	Default {
		
		Scale 0.7;
	}
	States
	{
		Spawn:
			GG71 D 4 A_CustomMissile ("Green_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			GG71 D -1;
			Stop;
	}
}


CLASS GenericBaronGib1: GenericHKGib1 { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			GG71 E 4 A_CustomMissile ("Green_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			GG71 E -1;
			Stop;
	}
}

CLASS GenericBaronGib1b: GenericBaronGib1 { 
	Default {
		
		YScale 0.8;
		XScale -1.0;
	}
}


CLASS GenericBaronGib2: GenericHKGib1 { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			GG71 F 4 A_CustomMissile ("Green_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			GG71 F -1;
			Stop;
	}
}


CLASS GenericBaronGib2b: GenericBaronGib2 { 
	Default {
		
		YScale 1.1;
		XScale -1.0;
	}
}







CLASS XDeathHellKnightArm: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 12;
		BounceFactor 0.4;
		BounceCount 3;
		Decal GreenBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			GHKA ABCDEFGH 4 A_CustomMissile ("Green_FlyingBlood", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			GHKA I 1;
			TNT1 A 0 A_SpawnItem ("Gib_HellKnightArm", 1);
			Stop;
	}
}

CLASS XDeathBaronOfHellArm: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 12;
		BounceFactor 0.4;
		BounceCount 3;
		Decal GreenBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			GORD FGHIJKLM 4 A_CustomMissile ("Green_FlyingBlood", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			GORD N 1;
			TNT1 A 0 A_SpawnItem ("Gib_BaronOfHellArm", 1);
			Stop;
	}
}

CLASS XDeathCyberKnightArm: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 12;
		BounceFactor 0.4;
		BounceCount 3;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			G0RB ABCD 4 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			G0RB E 1;
			TNT1 A 0 A_SpawnItem ("Gib_CyberKnightArm", 1);
			Stop;
	}
}

CLASS Gib_HellKnightArm: LimbBase { 
	Default {
		
		Scale 1.1;
		BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood";
		BloodColor "DarkGreen";
	}
	States
	{
		Spawn:
			GHKA I 1;
			TNT1 A 0 A_QueueCorpse();
			GHKA I 1900;
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "DoNothing");
			GHKA I -1;
			Stop;
			
		Death:   
			TNT1 A 0 A_NoBlocking();
			TNT1 AA 0 A_CustomMissile ("Green_BLood", 2, 0, random (0, 360), 2, random (0, 360));
			TNT1 AA 0 A_CustomMissile ("Xdeath1Green", 2, 0, random (0, 360), 2, random (10, 90));
			TNT1 AA 0 A_CustomMissile ("GenericHKGib4", 2, 0, random (0, 360), 2, random (10, 90));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			GHKA ABCDEFGH 2;
			Goto Spawn;
			
		Death.ExplosiveImpact:
Death.Kick: Death.SuperPunches: Death.Melee:
	TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,30,0,1);
	GHKA A 5;
	GHKA ABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
Landz:
	XDT5 I 0 A_SpawnItem("Gib_HellKnightArm");
Stop}}

CLASS Gib_BaronOfHellArm: LimbBase { 
	Default {
 
    Scale 1.1
	BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood"
	BloodColor "DarkGreen"
	}
    States
    {
    Spawn:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
        GORD N 1900
		TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "DoNothing")
		GORD N -1
		Stop
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 A_CustomMissile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160))        Stop
    Death:    
    TNT1 AAAA 0 A_CustomMissile ("Green_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360))
    TNT1 AAAAAAA 0 A_CustomMissile ("BloodTr", 0, 0, random (0, 360), 2, random (0, 360))
    TNT1 A 0 A_CustomMissile ("XDeath1Green", 0, 0, random (0, 360), 2, random (0, 360))
Stop}}

CLASS Gib_CyberKnightArm: LimbBase { 
	Default {
 
    Scale 1.1
	}
    States
    {
    Spawn:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
        G0RB E 1900
		TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "DoNothing")
		G0RB E -1
		Stop
		
        Loop
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 A_CustomMissile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160))        Stop
    Death:    
    TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360))
    TNT1 AAAAAAA 0 A_CustomMissile ("BloodTr", 0, 0, random (0, 360), 2, random (0, 360))
    TNT1 A 0 A_CustomMissile ("Xdeath1", 0, 0, random (0, 360), 2, random (0, 360))
Stop}}



CLASS XDeathHellKnightLeg: XDeathArm1 { 
	Default {
 
    Scale 1.1
    Speed 12
CLASSceFactor 0.4 : ACTOR { 
	Default {
		Decal GreenBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			GHKL ABCDEFGH 4 A_CustomMissile ("Green_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			GHKL A 1;
			TNT1 A 0 A_SpawnItem ("Gib_HellKnightLeg", 1);
			Stop;
	}
}

CLASS XDeathCyberKnightLeg: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 12;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			G0RA ABCD 4 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			G0RA A 1;
			TNT1 A 0 A_SpawnItem ("Gib_CyberKnightLeg", 1);
			Stop;
	}
}

CLASS Gib_CyberKnightLeg: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			G0RA A 1900;
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "DoNothing");
			G0RA A -1;
			Stop;
			
		Death:   
			TNT1 A 0 A_NoBlocking();
			TNT1 AA 0 A_CustomMissile ("BloodMist", 2, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAA 0 A_CustomMissile ("Xdeath1", 2, 0, random (0, 360), 2, random (10, 90));
			TNT1 AAA 0 A_CustomMissile ("Xdeath2", 2, 0, random (0, 360), 2, random (10, 90));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			G0RA ABCD 4;
			Goto Spawn;
			
		Death.ExplosiveImpact:
Death.Kick: Death.SuperPunches: Death.Melee:
	TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,40,0,1);
	G0RA ABCD 5 A_CheckFloor("Landz");
	Goto Landz;
Landz:
	XDT5 I 0 A_SpawnItem("Gib_CyberKnightLeg");
Stop}}

CLASS Gib_HellKnightLeg: LimbBase { 
	Default {
 
    Scale 1.1
	BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood"
	BloodColor "DarkGreen"
	}
    States
    {
		Spawn:
		GHKL I 1
		TNT1 A 0 A_QueueCorpse
		GHKL A 1900
		TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "DoNothing")
		GHKL A -1
       Stop
	   
	  Death:   
	    TNT1 A 0 A_NoBlocking
		TNT1 AA 0 A_CustomMissile ("Green_BLood", 2, 0, random (0, 360), 2, random (0, 360))
		TNT1 AA 0 A_CustomMissile ("Xdeath1Green", 2, 0, random (0, 360), 2, random (10, 90))
		TNT1 A 0 A_CustomMissile ("GenericHKGib1", 2, 0, random (0, 360), 2, random (10, 90))
		TNT1 A 0 A_CustomMissile ("GenericHKGib2", 2, 0, random (0, 360), 2, random (10, 90))
		Stop
	
	Pain:
	TNT1 A 0
	TNT1 A 0 ThrustThingZ(0,30,0,1)
	GHKL ABCDEFGH 2
	Goto Spawn
	
	Death.ExplosiveImpact:
	Death.Kick: Death.SuperPunches: Death.Melee:
	TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0)
	TNT1 A 0
	TNT1 A 0 ThrustThingZ(0,40,0,1)
	GHKL A 5
	GHKL ABCDEFGHABCDEFGH 5 A_CheckFloor("Landz")
	Goto Landz
	Landz:
	XDT5 I 0 A_SpawnItem("Gib_HellKnightLeg")
	Stop}}





CLASS XDeathHellKnightTorso: XDeathArm1 { 
	Default {
 
    Scale 1.1
    Speed 12
CLASSceFactor 0.4 : ACTOR { 
	Default {
		Decal GreenBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			GHKT ABCDEFGH 4 A_CustomMissile ("Green_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			GHKT I 1;
			HNDC A 0 A_SpawnItem("Gib_HellKnightTorso",0,0,0,1);
			Stop;
	}
}

CLASS Gib_HellKnightTorso: LimbBase { 
	Default {
		
		Scale 1.1;
		BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood";
		BloodColor "DarkGreen";
	}
	States
	{
		Spawn:
			GHKT I 1;
			TNT1 A 0 A_QueueCorpse();
			GHKT I 1900;
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "DoNothing");
			GHKT I -1;
			Stop;
		Death:    
			TNT1 A 0 A_NoBlocking();
			TNT1 AAA 0 A_CustomMissile ("XDeath1Green", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_CustomMissile ("MuchBloodGreen", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath2bGreen", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath3bGreen", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_CustomMissile ("XDeathOrgan1Green", 5, 0, random (0, 360), 2, random (10, 80));
			TNT1 A 0 A_CustomMissile ("XDeathOrgan2Green", 5, 0, random (0, 360), 2, random (10, 80));
			TNT1 A 0 A_CustomMissile ("GenericHKGib3", 5, 0, random (0, 360), 2, random (10, 80));
			TNT1 A 0 A_CustomMissile ("XDeathHellKnightArm", 5, 0, random (0, 360), 2, random (10, 80));
Stop}}



CLASS XDeathBaronofHellTorso: XDeathArm1 { 
	Default {
		
		Scale 1.3;
		Speed 12;
		BounceFactor 0.4;
		Decal GreenBloodSplat;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			GORD ABCD 4 A_CustomMissile ("Green_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			GORD E 1;
			HNDC A 0 A_SpawnItem("Gib_BaronofHellTorso",0,0,0,1);
			Stop;
	}
}

CLASS XDeathCyberKnightTorso: XDeathArm1 { 
	Default {
		
		Scale 1.3;
		Speed 12;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			G0RC ABCD 4 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			G0RC E 1;
			HNDC A 0 A_SpawnItem("Gib_CyberKnightTorso",0,0,0,1);
			Stop;
	}
}

CLASS Gib_BaronofHellTorso: LimbBase { 
	Default {
		
		Scale 1.3;
		BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood";
		BloodColor "DarkGreen";
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			GORD E -1;
			Stop;
		Death:    
			TNT1 A 0 A_NoBlocking();
			TNT1 AAA 0 A_CustomMissile ("XDeath1Green", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_CustomMissile ("MuchBloodGreen", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath2bGreen", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath3bGreen", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_CustomMissile ("XDeathOrgan1Green", 5, 0, random (0, 360), 2, random (10, 80));
			TNT1 A 0 A_CustomMissile ("XDeathOrgan2Green", 5, 0, random (0, 360), 2, random (10, 80));
			TNT1 AA 0 A_CustomMissile ("GenericBaronGib1", 5, 0, random (0, 360), 2, random (10, 80));
			TNT1 A 0 A_CustomMissile ("GenericBaronGib2", 5, 0, random (0, 360), 2, random (10, 80));
Stop}}

CLASS Gib_CyberKnightTorso: LimbBase { 
	Default {
		
		Scale 1.3;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			G0RC E -1();
			sTOP;
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 A_CustomMissile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160))        Stop
Death:    
	TNT1 AAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
	TNT1 AAAAAAA 0 A_CustomMissile ("BloodTr", 0, 0, random (0, 360), 2, random (0, 360));
	TNT1 AAAAA 0 A_CustomMissile ("Xdeath1", 0, 0, random (0, 360), 2, random (0, 360));
Stop}}


CLASS XDeathVolcabusArm: XDeathArm1 { 
	Default {
 
    +SKYEXPLODE
	-CLIENTSIDEONLY
    Scale 1.2
    Speed 9
	Gravity 0.4
CLASSceFactor 0.4 : ACTOR { 
	Default {
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			VOLA ABCDEFGH 3;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			VOLA I -1;
			Stop;
	}
}

CLASS XDeathMancubusTorso: XDeathArm1 { 
	Default {
		
		+SKYEXPLODE;
		-CLIENTSIDEONLY;
		Scale 1.2;
		Speed 9;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			MANA IJKLMNOP 3;
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
		Rest:
			MANA QRSTTT 4;
			Loop;
	}
}

CLASS XDeathMancubusLeg: XDeathArm1 { 
	Default {
		
		+SKYEXPLODE;
		-CLIENTSIDEONLY;
		Scale 1.2;
		Speed 9;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			MAN4 ABCDEFGH 3;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			MAN4 I -1;
			Stop;
	}
}

CLASS XDeathDaedabusTorso: XDeathArm1 { 
	Default {
		
		+SKYEXPLODE;
		-CLIENTSIDEONLY;
		Scale 1.2;
		Speed 9;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			M4NA IJKLMNOP 3;
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
		Rest:
			M4NA QRSTTT 4;
			Loop;
	}
}

CLASS XDeathDaedabusLeg: XDeathArm1 { 
	Default {
		
		+SKYEXPLODE;
		-CLIENTSIDEONLY;
		Scale 1.2;
		Speed 9;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			M4N4 ABCDEFGH 3;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			M4N4 I -1;
			Stop;
	}
}

CLASS XDeathMancubusArm: XDeathArm1 { 
	Default {
		
		+SKYEXPLODE;
		-CLIENTSIDEONLY;
		Scale 1.1;
		Speed 9;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			MANA ABCDEFG 3;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			HND8 A 0;
			TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("CheckTraditional")==1,2);
			HND8 A 0 A_SpawnItem("FlameCannon",0,0,0,1);
			Stop;
			TNT1 A 0;
			MANA H -1;
			Stop;
	}
}

CLASS XDeathSpiderPart1: XDeathArm1 { 
	Default {
		
		+SKYEXPLODE;
		-CLIENTSIDEONLY;
		Scale 1.1;
		Speed 9;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TRP1 ABCDEFGH 3;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TRP1 G -1;
			Stop;
	}
}

CLASS XDeathSpiderPart2: XDeathArm1 { 
	Default {
		
		+SKYEXPLODE;
		-CLIENTSIDEONLY;
		Scale 1.1;
		Speed 9;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TRP2 ABCDEFGH 3;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TRP2 E -1;
			Stop;
	}
}

CLASS XDeathSpiderPart3: XDeathArm1 { 
	Default {
		
		+SKYEXPLODE;
		-CLIENTSIDEONLY;
		Scale 1.1;
		Speed 9;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TRP3 ABCDEFGH 3;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TRP3 E -1;
			Stop;
	}
}

CLASS XDeathSpiderPart4: XDeathArm1 { 
	Default {
		
		+SKYEXPLODE;
		-CLIENTSIDEONLY;
		Scale 1.1;
		Speed 9;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TRP4 ABCDEFGH 3;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TRP4 E -1;
			Stop;
	}
}

CLASS XDeathSpiderPart5: XDeathArm1 { 
	Default {
		
		+SKYEXPLODE;
		-CLIENTSIDEONLY;
		Scale 1.1;
		Speed 9;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TRP5 ABCDEFGH 3;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TRP5 E -1;
			Stop;
	}
}

CLASS XDeathSpiderPart6: XDeathArm1 { 
	Default {
		
		+SKYEXPLODE;
		-CLIENTSIDEONLY;
		Scale 1.1;
		Speed 9;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TRP6 ABCDEFGH 3;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TRP6 A -1;
			Stop;
	}
}




CLASS XDeathZombieManHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		Radius 10;
		Scale 1.0;
	}
	States
	{
		Spawn:
		Spawn1:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			XHE2 AB 3;// A_CustomMissile("ShortWallRedBlood", 0, 0, 0, 2)//
			TNT1 A 0 A_ChangeFlag("THRUSPECIES", 0);
			XHE2 CDEFGH 3;// A_CustomMissile("ShortWallRedBlood", 0, 0, 0, 2)//
			Loop;
		Death:
			XHE2 E 1;
			XHE2 E 1 A_SpawnItem("ZombieManHead",0,0,0,1);
			Stop;
	}
}


CLASS XDeathZombiemanHeadBeheaded: XDeathZombieManHead { 
	Default {
		
		Speed 5;
		Gravity 0.5;
	}
}


CLASS XDeathZombiemanHeadOnXDeath: XDeathZombieManHead { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_jump(96, "ExplodeOnAir");
			Goto Spawn1;
		ExplodeOnAir:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ZombiemanHeadExplode");
			Stop;
}}

CLASS ZombiemanHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 99.0;
		damagefactor "Melee", 99.0;
		damagefactor "SuperPunch", 99.0;
		-CLIENTSIDEONLY;
		+SHOOTABLE;
		+THRUACTORS;
		damagefactor "Crush", 50.0;
		Radius 10;
		
		Mass 12;
		Health 40;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
		Spawn1:
			XHE2 C 1;
			XHE2 C -1;
			Stop;
		Spawn2:
			XHE2 G 1;
			XHE2 G -1;
			Stop;
		Spawn3:
			XHE2 H 1;
			XHE2 H -1;
			Stop;
			
		Death.Trample:
		Death.Stomp:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
			Goto Death;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ZombiemanHeadExplode");
			Stop;
		Crush:
			TNT1 AAAAAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_CustomMissile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 A_CustomMissile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0;
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			XHE2 EE 1 A_FaceTarget();
			TNT1 AAAA 0 A_SpawnItemEx("Blood", 0, 0, 10);
			TNT1 A 0 A_CustomMissile ("XDeathZombieManHeadKicked", 5, 0, random (170, 190), 2, random (20, 30));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHE2 ABCDEFGH 2;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			XHE2 ABCD 6;
			XDT5 I 0 A_SpawnItem("ZombiemanHead");
			Stop;
			
}}


CLASS XDeathZombieManHeadKicked: XDeathZombieManHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
	}
}



CLASS XDeathSergeantHead: XDeathZombieManHead { 
	Default {
		
	}
	States
	{
		Spawn:
		Spawn1:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			XHE1 AB 3;// A_CustomMissile("ShortWallRedBlood", 0, 0, 0, 2)//
			TNT1 A 0 A_ChangeFlag("THRUSPECIES", 0);
			XHE1 CDEFGH 3;// A_CustomMissile("ShortWallRedBlood", 0, 0, 0, 2)//
			Loop;
		Death:
			XHE1 E 1;
			XHE1 E 1 A_SpawnItem("SergeantHead",0,0,0,1);
			Stop;
			
	}
}

CLASS XDeathLabguyHead: XDeathZombieManHead { 
	Default {
		
	}
	States
	{
		Spawn:
		Spawn1:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			FSHD AB 3;// A_CustomMissile("ShortWallRedBlood", 0, 0, 0, 2)//
			TNT1 A 0 A_ChangeFlag("THRUSPECIES", 0);
			FSHD CDEFGH 3;// A_CustomMissile("ShortWallRedBlood", 0, 0, 0, 2)//
			Loop;
		Death:
			FSHD A 1;
			FSHD A 1 A_SpawnItem("LabguyHead",0,0,0,1);
			Stop;
			
	}
}

CLASS LabguyHead: ZombieManHead { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot");
			TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
		Spawn1:
			FSHD A 1;
			FSHD A -1;
			Stop;
		Spawn2:
			FSHD G 1;
			FSHD G -1;
			Stop;
		Spawn3:
			FSHD H 1;
			FSHD H -1;
			Stop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode");
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			FSHD EE 1 A_FaceTarget();
			TNT1 AAAA 0 A_SpawnItemEx("Blood", 0, 0, 10);
			TNT1 A 0 A_CustomMissile ("XDeathLabguyHead", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHE1 ABCDEFGH 2;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			FSHD ABCDEFGH 3;
			XDT5 I 0 A_SpawnItem("LabguyHead");
			Stop;
			
}}

CLASS XDeathPlasmaZombieHead: XDeathZombieManHead { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("THRUSPECIES", 0);
		Spawn1:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			ZM41 ABCDEFGH 3;// A_CustomMissile("ShortWallRedBlood", 0, 0, 0, 2)//
			Loop;
		Death:
			ZM41 A 0;
			ZM41 A 0 A_SpawnItem("PlasmaZombieHead",0,0,0,1);
			Stop;
			
	}
}

CLASS PlasmaZombieHead: ZombieManHead { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot");
			TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
		Spawn1:
			ZM41 A 1;
			ZM41 A -1;
			Stop;
		Spawn2:
			ZM41 G 1;
			ZM41 G -1;
			Stop;
		Spawn3:
			ZM41 H 1;
			ZM41 H -1;
			Stop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("PlasmaZombieHeadExplode");
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			ZM41 A 1 A_FaceTarget();
			TNT1 AAAA 0 A_SpawnItemEx("Blood", 0, 0, 10);
			TNT1 A 0 A_CustomMissile ("XDeathPlasmaZombieHead", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			ZM41 ABCDEFGH 2;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			ZM41 ABCDEFGH 3;
			XDT5 I 0 A_SpawnItem("PlasmaZombieHead");
			Stop;
			
}}



CLASS XDeathZSpecOpsHead: XDeathZombieManHead { 
	Default {
		
	}
	States
	{
		Spawn:
		Spawn1:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			ZHE2 ABCD 3;// A_CustomMissile("ShortWallRedBlood", 0, 0, 0, 2)//
			Loop;
		Death:
			ZHE2 E 1;
			ZHE2 E 1 A_SpawnItem("ZSpecOpsHead",0,0,0,1);
			Stop;
			
	}
}

CLASS ZSpecOpsHead: ZombieManHead { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot");
		Spawn1:
			ZHE2 E 1;
			ZHE2 E -1;
			Stop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode");
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			ZHE2 EE 1 A_FaceTarget();
			TNT1 AAAA 0 A_SpawnItemEx("Blood", 0, 0, 10);
			TNT1 A 0 A_CustomMissile ("XDeathZSpecOpsHead", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			ZHE2 ABCD 2;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			ZHE2 ABCDEFGH 3;
			TNT1 A 0 A_SpawnItem("ZSpecOpsHead");
			Stop;
			
}}


CLASS XDeathSergeantHeadBeheaded: XDeathSergeantHead { 
	Default {
		
		Speed 5;
		Gravity 0.5;
	}
}

CLASS XDeathSergeantHeadOnXDeath: XDeathSergeantHead { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_jump(96, "ExplodeOnAir");
			Goto Spawn1;
		ExplodeOnAir:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode");
			Stop;
}}

CLASS SergeantHead: ZombieManHead { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot");
			TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
		Spawn1:
			XHE1 C 1;
			XHE1 C -1;
			Stop;
		Spawn2:
			XHE1 G 1;
			XHE1 G -1;
			Stop;
		Spawn3:
			XHE1 H 1;
			XHE1 H -1;
			Stop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode");
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			XHE1 EE 1 A_FaceTarget();
			TNT1 AAAA 0 A_SpawnItemEx("Blood", 0, 0, 10);
			TNT1 A 0 A_CustomMissile ("XDeathSergeantHead", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHE1 ABCDEFGH 2;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			XHE1 ABCDEFGH 3;
			XDT5 I 0 A_SpawnItem("SergeantHead");
			Stop;
			
}}


CLASS SergeantHeadThrown: XDeathSergeantHead { 
	Default {
		
		+BOUNCEONACTORS;
		Damage (random (30, 40));
		DamageType "Kick";
		-CLIENTSIDEONLY;
		Speed 20;
		Gravity 0.4;
	}
}


CLASS XDeathChaingunguyHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		BounceCount 3;
		Scale 1.0;
	}
	States
	{
		Spawn:
		Spawn1:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			CHHE AB 3;// A_CustomMissile("ShortWallRedBlood", 0, 0, 0, 2)//
			TNT1 A 0 A_ChangeFlag("THRUSPECIES", 0);
			CHHE CDEFGH 3;// A_CustomMissile("ShortWallRedBlood", 0, 0, 0, 2)//
			Loop;
		Death:
			XHE2 E 0;
			XHE2 E 0 A_SpawnItem("ChaingunguyHead",0,0,0,1);
			Stop;
	}
}

CLASS XDeathHelmetChaingunguyHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		BounceCount 3;
		Scale 1.0;
	}
	States
	{
		Spawn:
		Spawn1:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			C1HE AB 3;// A_CustomMissile("ShortWallRedBlood", 0, 0, 0, 2)//
			TNT1 A 0 A_ChangeFlag("THRUSPECIES", 0);
			C1HE CDEFGH 3;// A_CustomMissile("ShortWallRedBlood", 0, 0, 0, 2)//
			Loop;
		Death:
			XHE2 E 0;
			XHE2 E 0 A_SpawnItem("HelmetChaingunguyHead",0,0,0,1);
			Stop;
	}
}

CLASS XDeathChaingunguyHeadBeheaded: XDeathChaingunguyHead { 
	Default {
		
		Speed 5;
		Gravity 0.5;
	}
}


CLASS XDeathChaingunguyHeadOnXDeath: XDeathChaingunguyHead { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_jump(96, "ExplodeOnAir");
			Goto Spawn1;
		ExplodeOnAir:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ChaingunguyHeadExplode");
			Stop;
}}

CLASS ChaingunguyHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		damagefactor "SuperPunch", 9.0;
		-CLIENTSIDEONLY;
		+SHOOTABLE;
		+SOLID;
		+THRUACTORS;
		damagefactor "Crush", 50.0;
		Radius 10;
		
		Mass 12;
		Health 40;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TNT1 A 0 A_Jump(256, "Spawn1", "SPawn2");
		Spawn1:
			CHHE A -1;
			Stop;
		Spawn2:  
			CHHE E -1;
			Stop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ChaingunguyHeadExplode");
			Stop;
		Death.Trample:
		Crush:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
			TNT1 AAAAAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_CustomMissile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 A_CustomMissile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0;
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			CHHE EE 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathChaingunguyHeadKicked", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			CHHE ABCDEFGH 2;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			CHHE ABCDEFGH 3;
			XDT5 I 0 A_SpawnItem("ChaingunguyHead");
			Stop;
			
}}

CLASS HelmetChaingunguyHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		damagefactor "SuperPunch", 9.0;
		-CLIENTSIDEONLY;
		+SHOOTABLE;
		+SOLID;
		+THRUACTORS;
		damagefactor "Crush", 50.0;
		Radius 10;
		
		Mass 12;
		Health 40;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TNT1 A 0 A_Jump(256, "Spawn1", "SPawn2");
		Spawn1:
			C1HE A -1;
			Stop;
		Spawn2:  
			C1HE E -1;
			Stop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ChaingunguyHeadExplode");
			Stop;
		Death.Trample:
		Crush:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
			TNT1 AAAAAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_CustomMissile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 A_CustomMissile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0;
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			C1HE EE 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathHelmetChaingunguyHeadKicked", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			C1HE ABCDEFGH 2;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			CHHE ABCDEFGH 3;
			XDT5 I 0 A_SpawnItem("ChaingunguyHead");
			Stop;
			
}}


CLASS XDeathChaingunguyHeadKicked: XDeathChaingunguyHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
	}
}

CLASS XDeathHelmetChaingunguyHeadKicked: XDeathHelmetChaingunguyHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
	}
}



CLASS XDeathImpHead: XDeathChaingunguyHead { 
	Default {
		
	}
	States
	{
		Spawn:
		Spawn1:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			XHE4 AB 3;// A_CustomMissile("ShortWallRedBlood", 0, 0, 0, 2)//
			TNT1 A 0 A_ChangeFlag("THRUSPECIES", 0);
			XHE4 CDEFGH 3;// A_CustomMissile("ShortWallRedBlood", 0, 0, 0, 2)//
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			XHE4 E 1;
			XHE4 E 1 A_SpawnItem("ImpHead",0,0,0,1);
			Stop;
	}
}

CLASS XDeathSavageImpHead: XDeathChaingunguyHead { 
	Default {
		
	}
	States
	{
		Spawn:
		Spawn1:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			7HE4 AB 3;// A_CustomMissile("ShortWallRedBlood", 0, 0, 0, 2)//
			TNT1 A 0 A_ChangeFlag("THRUSPECIES", 0);
			7HE4 CDEFGH 3;// A_CustomMissile("ShortWallRedBlood", 0, 0, 0, 2)//
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			7HE4 E 1;
			7HE4 E 1 A_SpawnItem("SavageImpHead",0,0,0,1);
			Stop;
	}
}


CLASS XDeathImpHeadBeheaded: XDeathImpHead { 
	Default {
		
		Speed 5;
		Gravity 0.5;
	}
}

CLASS XDeathImpHeadOnXDeath: XDeathImpHead { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_jump(96, "ExplodeOnAir");
			Goto Spawn1;
		ExplodeOnAir:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ImpHeadExplode");
			Stop;
}}

CLASS XDeathSavageImpHeadOnXDeath: XDeathSavageImpHead { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_jump(96, "ExplodeOnAir");
			Goto Spawn1;
		ExplodeOnAir:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("SavageImpHeadExplode");
			Stop;
}}

CLASS ImpHead: ZombieManHead { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot");
			TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
		Spawn1:
			XHE4 C 1;
			XHE4 C -1;
			Stop;
		Spawn2:
			XHE4 G 1;
			XHE4 G -1;
			Stop;
		Spawn3:
			XHE4 H 1;
			XHE4 H -1;
			Stop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ImpHeadExplode");
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			XHE4 EE 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathImpHead", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHE4 ABCDEFGH 2;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			XHE4 ABCDEFGH 3;
			XDT5 I 0 A_SpawnItem("ImpHead");
			Stop;
			
}}

CLASS SavageImpHead: ZombieManHead { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot");
			TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
		Spawn1:
			7HE4 C 1;
			7HE4 C -1;
			Stop;
		Spawn2:
			7HE4 G 1;
			7HE4 G -1;
			Stop;
		Spawn3:
			7HE4 H 1;
			7HE4 H -1;
			Stop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("SavageImpHeadExplode");
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			7HE4 EE 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathSavageImpHead", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			7HE4 ABCDEFGH 2;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			7HE4 ABCDEFGH 3;
			XDT5 I 0 A_SpawnItem("SavageImpHead");
			Stop;
			
}}


CLASS BurningFlyingMeatPiece : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 16;
		Scale 0.8;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		BounceFactor 0.4;
		damagetype Blood;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal BloodSuper;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			XME1 ABCD 2 A_CustomMissile ("SmallFlameTrails", 2, 0, random (0, 360), 2, random (70, 110));
			TNT1 A 0 A_CustomMissile("BloodTrails",0,0,180,2);
			Loop;
		Death:
			XME1 E 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 AAAAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 180), 2, random (0, 180));
			XME1 EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 7 A_CustomMissile ("FlameTrails", 10, 0, random (0, 360), 2, random (70, 110));
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XME1 E -1;
			Stop;
		Splash:
			TNT1 A 0;
			Stop;
	}
}





CLASS Teeth : ACTOR { 
	Default {
		
		Height 2;
		Radius 2;
		Speed 6;
		Scale 0.15;
		+DOOMBOUNCE;
		- NOGRAVITY;
		+WINDTHRUST;
		+CLIENTSIDEONLY;
		+MOVEWITHSECTOR;
		+MISSILE;
		+NOBLOCKMAP;
		-DROPOFF;
		+NOTELEPORT;
		+FORCEXYBILLBOARD;
		+NOTDMATCH;
		+THRUACTORS;
		+GHOST;
	}
	States
	{
		Spawn:
			XTET ABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGH 3;
			Stop;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LCPJ A 0 A_Jump(256,"Rest1","Rest2");
			Goto Rest1;
		Rest1:
			XTET C 250;
			TNT1 A 0 A_CheckSight("Vanish");
		Rest2:
			XTET G 250;
			TNT1 A 0 A_CheckSight("Vanish");
			Loop;
			
		Vanish:
			TNT1 A 0;
			Stop;
	}
}


CLASS TeethNoBounce: Teeth { 
	Default {
		
		-DOOMBOUNCE;
	}
}


CLASS XDeathHellKnightHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		Scale 1.0;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			HKHE ABCDEFGH 6;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			HKHE G 1;
			HKHE G 1 A_SpawnItem("HellKnightHead",0,0,0,1);
			Stop;
	}
}

CLASS XDeathCyberPaladinHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		Scale 1.0;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			G0RH ABCD 6;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			G0RH E 1;
			G0RH E -1;
			Stop;
	}
}

CLASS XDeathCyberPaladinRipped: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		Scale 1.0;
		Speed 4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			CP4L AA 6;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			CP4L B 1;
			CP4L B -1;
			Stop;
	}
}


CLASS XDeathCyberKnightRipped: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		Scale 1.0;
		Speed 4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			CP4L CC 6;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			CP4L D 1;
			CP4L D -1;
			Stop;
	}
}

CLASS XDeathPinkyDemonHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		Speed 10;
		Scale 1.3;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			DEMH AB 3;// A_CustomMissile("ShortWallRedBlood", 0, 0, 0, 2)//
			TNT1 A 0 A_ChangeFlag("THRUSPECIES", 0);
			DEMH CDEFGH 3;// A_CustomMissile("ShortWallRedBlood", 0, 0, 0, 2)//
			Loop;
		Death:
			DEMH I 1;
			DEMH I 1 A_SpawnItem("PinkyDemonHead",0,0,0,1);
			Stop;
	}
}



CLASS PinkyDemonHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		damagefactor "SuperPunch", 9.0;
		-CLIENTSIDEONLY;
		Radius 10;
		
		Mass 12;
		Health 60;
		Scale 1.5;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			DEMH I 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			DEMH I -1;
			Stop;
			
		Death:
			TNT1 AAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 A_SpawnItem("MeatDeathSmall");
			TNT1 AA 0 A_CustomMissile ("XDeathBrain1", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeathBrain2", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("XDeath3", 10, random (5, -5), random (160, 200), 2, random (-10, 10));
			TNT1 AA 0 A_CustomMissile ("XDeath2", 10, random (5, -5), random (160, 200), 2, random (-10, 10));
			TNT1 AAAA 0 A_CustomMissile ("BloodMistBig", 10, 0, random (0, 360), 2, random (30, 90));
			TNT1 AA 0 A_CustomMissile ("PinkyHeadPiece", 12, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_CustomMissile ("PinkyJaw", 12, 0, random (0, 360), 2, random (0, 160));
			Stop;
		Death.Trample:
		Crush:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
			TNT1 AAAAAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			DEMH I 5;
			DEMH I 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_CustomMissile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 A_CustomMissile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0;
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			DEMH A 1 A_Pain();
			DEMH A 1 A_FaceTarget();
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_CustomMissile ("XDeathPinkyDemonHeadKicked", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			DEMH ACEGI 3;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			DEMH ABCDEFGH 3;
			DEMH I 0 A_SpawnItem("PinkyDemonHead");
			Stop;
			
}}



CLASS XDeathPinkyDemonHeadKicked: XDeathPinkyDemonHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
		Scale 1.3;
		BounceFactor 0.4;
	}
}




CLASS HellKnightHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		damagefactor "SuperPunch", 9.0;
		-CLIENTSIDEONLY;
		+SHOOTABLE;
		-NOBLOCKMAP;
		+SOLID;
		+THRUACTORS;
		BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood";
		damagefactor "Crush", 50.0;
		Radius 10;
		Mass 12;
		Health 60;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			HKHE G 1 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			HKHE G -1;
			Stop;
		Death:
			TNT1 A 0 A_CustomMissile ("HellKnightHeadExplode", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_CustomMissile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 A_CustomMissile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0;
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			HKHE ABCDEFGH 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathHellKnightHeadKicked", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			HKHE ABCDEFGH 1;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			HKHE ABCDEFGH 6;
			HKHE I 0 A_SpawnItem("HellKnightHead");
			Stop;
			
}}


CLASS XDeathHellKnightHeadKicked: XDeathHellKnightHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
		BounceFactor 0.4;
	}
}





CLASS XDeathBaronHead5: XDeathBullArm1 { 
	Default {
		
		BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood";
		-CLIENTSIDEONLY;
		Scale 1.2;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			XHE5 ABCDEFGH 6;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			XHE5 A 1;
			XHE5 A 1 A_SpawnItem("BaronHead",0,0,0,1);
			Stop;
	}
}



CLASS BaronHead: LimbBase { 
	Default {
		
		BloodType "Green_Blood", "GreenSawBlood", "GreenSawBlood";
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		damagefactor "SuperPunch", 9.0;
		-CLIENTSIDEONLY;
		Radius 10;
		
		Mass 12;
		Health 60;
		Scale 1.2;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XHE5 A 1 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			XHE5 A -1;
			Stop;
			
		Death:
			TNT1 AAAAA 0 A_CustomMissile ("Green_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 A_CustomMissile ("BaronOfHellHeadExplode", 5, 0, random (0, 360), 2, random (60, 140));
			Stop;
		Death.Trample:
		Crush:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
			TNT1 AAAAAAAA 0 A_CustomMissile ("Green_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_CustomMissile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 A_CustomMissile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0;
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			XHE5 A 1 A_Pain();
			XHE5 A 1 A_FaceTarget();
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_CustomMissile ("XDeathBaronHeadKicked", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHE5 ABCD 3;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			XHE5 ABCD 6;
			XHE5 I 0 A_SpawnItem("XDeathBaronHead");
			Stop;
			
}}


CLASS XDeathBaronHeadKicked: XDeathBaronHead5 { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
		BounceFactor 0.4;
	}
}








CLASS XDeathRevenantHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		Scale 1.0;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			XHE6 ABCD 6;
			Loop;
		Death:
			XHE6 A 1;
			XHE6 A 1 A_SpawnItem("RevenantHead",0,0,0,1);
			Stop;
	}
}




CLASS RevenantHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		damagefactor "SuperPunch", 9.0;
		BloodType "RevenantBlood";
		-CLIENTSIDEONLY;
		Radius 10;
		
		Mass 12;
		Health 60;
		Scale 1.0;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XHE6 B -1;
			Stop;
			
		Death.Trample:
		Crush:
			TNT1 AAAAAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_CustomMissile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 A_CustomMissile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0;
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			XHE6 A 1 A_Pain();
			XHE6 A 1 A_FaceTarget();
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_CustomMissile ("XDeathRevenantHeadKicked", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Death:
			TNT1 A 0 A_NoBlocking();
			TNT1 AAA 0 A_CustomMissile ("LSpart1", 2, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_CustomMissile ("LSpart3", 2, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_CustomMissile ("LSpart2", 2, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 AAAA 0 A_CustomMissile ("Brains1", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 AAAAAA 0 A_CustomMissile ("SmallBrainPiece", 5, 0, random (0, 360), 2, random (60, 140));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHE6 ABCD 3;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			Goto Fly293;
		Fly293:
			XHE6 ABCD 6;
			TNT1 A 0 A_JumpIf(momz == 0, "Land293");
			
		Land293:
			XHE6 I 0 A_SpawnItem("XDeathRevenantHead");
			Stop;
			
}}


CLASS XDeathRevenantHeadKicked: XDeathRevenantHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
		BounceFactor 0.4;
	}
}

CLASS XDeathRevenantHeadKicked2: XDeathRevenantHead { 
	Default {
		
		+BOUNCEONACTORS;
		+NOEXTREMEDEATH;
		Damage 15;
		Speed 24;
		BounceFactor 0.2;
	}
}








CLASS XDeathMancubusHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		Scale 0.9;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			XHE7 ABCD 6;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			XHE5 A 1;
			XHE5 A 1 A_SpawnItem("MancubusHead",0,0,0,1);
			Stop;
	}
}



CLASS MancubusHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		damagefactor "SuperPunch", 9.0;
		-CLIENTSIDEONLY;
		Radius 10;
		
		Mass 12;
		Health 60;
		Scale 0.9;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XHE7 B 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			XHE7 B -1;
			Stop;
			
		Death:
			TNT1 AAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 AAAA 0 A_CustomMissile ("Brains1", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_CustomMissile ("Brains2", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_CustomMissile ("Brains3", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_CustomMissile ("Brains4", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_CustomMissile ("Brains5", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 AAAAAA 0 A_CustomMissile ("SmallBrainPiece", 5, 0, random (0, 360), 2, random (60, 140));
			Stop;
		Death.Trample:
		Crush:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
			TNT1 AAAAAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_CustomMissile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 A_CustomMissile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0;
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			XHE7 A 1 A_Pain();
			XHE7 A 1 A_FaceTarget();
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_CustomMissile ("XDeathMancubusHeadKicked", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHE7 ABCD 3;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			XHE7 ABCD 6;
			XHE7 I 0 A_SpawnItem("MancubusHead");
			Stop;
			
}}

CLASS XDeathDaedabusHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		Scale 0.9;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			XH37 ABCD 6;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			XH37 A 1;
			XH37 A 1 A_SpawnItem("DaedabusHead",0,0,0,1);
			Stop;
	}
}



CLASS DaedabusHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		damagefactor "SuperPunch", 9.0;
		-CLIENTSIDEONLY;
		Radius 10;
		
		Mass 12;
		Health 60;
		Scale 0.9;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XH37 B 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			XH37 B -1;
			Stop;
			
		Death:
			TNT1 AAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 AAAA 0 A_CustomMissile ("Brains1", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_CustomMissile ("Brains2", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_CustomMissile ("Brains3", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_CustomMissile ("Brains4", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_CustomMissile ("Brains5", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 AAAAAA 0 A_CustomMissile ("SmallBrainPiece", 5, 0, random (0, 360), 2, random (60, 140));
			Stop;
		Death.Trample:
		Crush:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
			TNT1 AAAAAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_CustomMissile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 A_CustomMissile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0;
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			XH37 A 1 A_Pain();
			XH37 A 1 A_FaceTarget();
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_CustomMissile ("XDeathDaedabusHead", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XH37 ABCD 3;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			XH37 ABCD 6;
			XH37 I 0 A_SpawnItem("DaedabusHead");
			Stop;
			
}}



CLASS XDeathMancubusHeadKicked: XDeathMancubusHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
		BounceFactor 0.4;
	}
}







CLASS XDeathCyberdemonHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		+SKYEXPLODE;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			XHE8 ABCD 6;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			XHE8 A 1;
			XHE8 A 1 A_SpawnItem("CyberdemonHead",0,0,0,1);
			Stop;
	}
}



CLASS CyberdemonHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		damagefactor "SuperPunch", 9.0;
		-CLIENTSIDEONLY;
		Radius 20;
		
		Mass 100;
		Health 60;
		Scale 1.2;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XHE8 B 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			XHE8 B -1;
			Stop;
			
		Death:
		Death.Trample:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
		Crush:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			
			TNT1 AAAAAAAAA 0 A_CustomMissile ("BloodMistBig", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAAAA 0 A_CustomMissile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAA 0 A_CustomMissile ("Brains6Big", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_CustomMissile ("Brains7Big", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_CustomMissile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_CustomMissile ("XDeath3b", 10, 0, random (0, 360), 2, random (50, 90));
			TNT1 AAAAA 0 A_CustomMissile ("XDeath2b", 10, 0, random (0, 360), 2, random (50, 90));
			TNT1 A 0 A_Stop();
			XHE8 I 10;
			XHE8 I -1;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_CustomMissile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 A_CustomMissile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0;
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			XHE8 A 1 A_Pain();
			XHE8 A 1 A_FaceTarget();
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_CustomMissile ("XDeathCyberdemonHeadKicked", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,5,0,1);
			XHE8 B 3;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			XHE8 ABCD 6;
			XHE8 I 0 A_SpawnItem("XDeathCyberdemonHead");
			Stop;
			
}}


CLASS XDeathCyberdemonHeadKicked: XDeathCyberdemonHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 5;
		BounceFactor 0.4;
	}
}





CLASS Ashes1: XDeath1 { 
	Default {
		
		Speed 5;
		Gravity 0.2;
		DeathSound "none";
		SeeSound "none";
		+DOOMBOUNCE;
		+DONTSPLASH;
		BounceFactor 0.01;
		Decal none;
		Scale 1.0;
	}
	States
	{
		Spawn:
			ASHZ ABCB 3;
			Loop;
		Death:
			ASHZ B 2000;
			Stop;
		Splash:
			TNT1 A 0;
			TNT1 A 0;
			Stop;
	}
}


CLASS Ashes2: XDeath1 { 
	Default {
		
		Speed 5;
		Gravity 0.2;
		+DONTSPLASH;
		DeathSound "none";
		SeeSound "none";
		Decal none;
		Scale 1.0;
	}
	States
	{
		Spawn:
			ASHY ABCB 3;
			Loop;
		Death:
			ASHY B 2000;
			Stop;
		Splash:
			TNT1 A 0;
			TNT1 A 0;
			Stop;
	}
}

CLASS XDeathArachnotronHead: XDeath1 { 
	Default {
		
		Speed 12;
		Gravity 0.9;
		+DONTSPLASH;
		DeathSound "none";
		SeeSound "none";
		+SKYEXPLODE;
		Decal none;
		Scale 1.0;
	}
	States
	{
		Spawn:
			NAHA ABCDEFGH 4;
			Loop;
		Death:
			TNT1 A 0;
			//TNT1 A 0 A_Jump(128, "CleanDeath")
			TNT1 A 0 A_SpawnItem("CrawlingDyingSpider");
			Stop;
		CleanDeath:
			TNT1 AAAAAAAAAAAA 0 A_CustomMissile ("SmallBrainPiece", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_CustomMissile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
			NAHC IJKLMN 5;
			NAHC N -5;
			Stop;
			Stop;
	}
}









CLASS BasicGib : ACTOR { 
	Default {
		
		Radius 6;
		Height 6;
		+NOBLOCKMAP;
		+CLIENTSIDEONLY;
		Mass 50;
	}
	States
	{
		Spawn:
			TNT1 A 1;
			Stop;
	}
}




CLASS BasicMarineGib1: BasicGib { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 ThrustThingZ(0,40,0,1);
			TNT1 A 0 A_SetAngle(random(0, 359));
			TNT1 A 0 A_Recoil(3);
			XDMG A -1;
			Stop;
	}
}


CLASS BasicMarineGib2: BasicGib { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 ThrustThingZ(0,40,0,1);
			TNT1 A 0 A_SetAngle(random(0, 359));
			TNT1 A 0 A_Recoil(3);
			XDMG B -1;
			Stop;
	}
}


CLASS BasicMarineGib3: BasicGib { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 ThrustThingZ(0,40,0,1);
			TNT1 A 0 A_SetAngle(random(0, 359));
			TNT1 A 0 A_Recoil(3);
			XDMG C -1;
			Stop;
	}
}


CLASS BasicMarineGib4: BasicGib { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 ThrustThingZ(0,40,0,1);
			TNT1 A 0 A_SetAngle(random(0, 359));
			TNT1 A 0 A_Recoil(3);
			XDMG D -1;
			Stop;
	}
}


CLASS XDeathHalfDemon : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 1.0;
		Speed 6;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			SARC E 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			SARC F 1 A_SpawnItem("Gib_HalfDemon",0,0,0,1);
			TNT1 A 0;
			Stop;
	}
}

CLASS Gib_HalfDemon: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			SARC F 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			SARC F -1;
Stop    }}
	   
CLASS XDeathHalfVoidSpectre : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 1.0;
		Speed 6;
		Mass 4;
		Decal GreenBloodSplat;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			ND3M X 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			ND3M Y 1 A_SpawnItem("Gib_HalfVoidSpectre",0,0,0,1);
			TNT1 A 0;
			Stop;
	}
}

CLASS Gib_HalfVoidSpectre: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			ND3M Y 1 A_SpawnItem("Green_BloodSpot",0,0,0,1);
			ND3M Y -1;
Stop    }}
	 


CLASS XDeathPainElementalNew1: XDeath1 { 
	Default {
		
		Speed 12;
		Gravity 0.4;
		Decal BrutalBloodSplat;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath4";
Translation "64:72=133:142", "73:75=13:15", "76:79=236:239"
	Scale 1.1;
	}
    States
    {
Spawn:
	TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
	CAGI ABCDEFGH 2 A_CustomMissile ("Brutal_FlyingBloodTrail", 5, 0, random (0, 360), 2, random (0, 360));
	Loop;
Death:
	
	TNT1 A 0;
	TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
	TNT1 A 0 A_CheckFloor("SpawnFloor");
	TNT1 A 0 A_SpawnItemEx ("DetectCeilBloodSimpler",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 A_SpawnItemEx ("DetectCeilXDeath2",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse();
	CAGI Q -1;
	Stop;
SpawnFloor:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse();
	CAGI Q -1;
	Stop;
}
}



CLASS XDeathPainElementalNew2: XDeathPainElementalNew1 { 
	Default {
 
    Speed 12
	Gravity 0.6
    Decal BrutalBloodSplat
    Scale 1.1
	}
    States
    {
    Spawn:
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash")
        CAGI IJKLMNOP 2 A_CustomMissile ("Brutal_FlyingBloodTrail", 5, 0, random (0, 360), 2, random (0, 360))
        Loop
    Death:
	    
		TNT1 A 0
        TNT1 AAA 0 A_SpawnItem("Blood", 0, 5)
	    TNT1 A 0 A_CheckFloor("SpawnFloor")
		TNT1 A 0 A_SpawnItemEx ("DetectCeilBloodSimpler",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0)
		TNT1 A 0 A_SpawnItemEx ("DetectCeilXDeath2",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0)
		
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
        CAGI R -1
        Stop
	SpawnFloor:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
	    CAGI R -1
		Stop
    }
}

CLASS XDeathPainElementalGreen1: XDeath1 { 
	Default {
 
    Speed 12
	Gravity 0.4
    Decal BrutalBloodSplat
	SeeSound "misc/xdeath4"
    DeathSound "misc/xdeath4"
	Translation "16:47=112:127", "192:207=80:111", "168:191=64:79"
    Scale 1.1
	}
    States
    {
    Spawn:
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash")
        CAGI ABCDEFGH 2 A_CustomMissile ("GreenBloodTrails", 5, 0, random (0, 360), 2, random (0, 360))
        Loop
    Death:
	    
		TNT1 A 0
        TNT1 AAA 0 A_SpawnItem("GreenBloodTrails", 0, 5)
	    TNT1 A 0 A_CheckFloor("SpawnFloor")
		TNT1 A 0 A_SpawnItemEx ("DetectCeilBloodSimpler",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0)
		TNT1 A 0 A_SpawnItemEx ("DetectCeilXDeath2",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0)
		
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
        CAGI Q -1
        Stop
	SpawnFloor:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
	    CAGI Q -1
		Stop
    }
}



CLASS XDeathPainElementalGreen2: XDeathPainElementalGreen1 { 
	Default {
 
    Speed 12
	Gravity 0.6
    Decal BrutalBloodSplat
    Scale 1.1
	}
    States
    {
    Spawn:
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash")
        CAGI IJKLMNOP 2 A_CustomMissile ("GreenBloodTrails", 5, 0, random (0, 360), 2, random (0, 360))
        Loop
    Death:
	    
		TNT1 A 0
        TNT1 AAA 0 A_SpawnItem("GreenBloodTrails", 0, 5)
	    TNT1 A 0 A_CheckFloor("SpawnFloor")
		TNT1 A 0 A_SpawnItemEx ("DetectCeilBloodSimpler",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0)
		TNT1 A 0 A_SpawnItemEx ("DetectCeilXDeath2",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0)
		
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
        CAGI R -1
        Stop
	SpawnFloor:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
	    CAGI R -1
		Stop
    }
}

CLASS XDeathSpiderNew1: XDeathPainElementalNew1 { 
	Default {
 
    Scale 0.8
	Speed 7
	}
}

CLASS XDeathSpiderNew2: XDeathPainElementalNew2 { 
	Default {
 
    Scale 0.7
	Speed 7
	}
}

// QSZ ARM

CLASS XDeathHFQSZArm1 : ACTOR { 
	Default {
 
    Radius 8
    Height 8
    Scale 0.8
	Speed 8
	Mass 1
    gravity 0.5
	Decal BrutalBloodSplat
CLASSceFactor 0.4 : ACTOR { 
	Default {
		BounceCount 3;
		+DOOMBOUNCE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MISSILE;
		seesound "bloood";
		deathsound "bloood";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			QARM ABCDEFGH 5 A_CustomMissile ("brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			QARM X 1;
			TNT1 A 0 A_SpawnItem("brutal_BloodSpot",0,0,0,1);
			QARM X 0 A_SpawnItem("Gib_HFQSZ_Arm");
			Stop;
	}
}

CLASS Gib_HFQSZ_Arm: LimbBase { 
	Default {
		
		Scale 0.8;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			QARM X 1 A_SpawnItem("brutal_BloodSpot",0,0,0,1);
			QARM X -1;
			Stop;
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 A_CustomMissile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160))        Stop
Death:    
	TNT1 AAAA 0 A_CustomMissile ("brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
	TNT1 A 0 A_CustomMissile ("GibHFQSZHand", 0, 0, random (0, 180), 2, random (0, 180));
	TNT1 A 0 A_CustomMissile ("GibHFQSZArmPart", 0, 0, random (0, 180), 2, random (0, 180));
	Stop;
Death.Kick:
Death.Melee:
Death.SuperPunch:
	QARM XX 1 A_FaceTarget();
	TNT1 A 0 A_CustomMissile ("XDeathHFQSZArm1Kicked", 5, 0, random (170, 190), 2, random (20, 40));
	Stop;
Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	QARM ABCDEFGH 3;
	Goto Spawn;
	
Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	QARM GH 3;
	QARM ABCDEFGHABDCEFGHABCDEFGH 3 A_CheckFloor("Landz");
	Goto Landz;
Landz:
	QARM X 0 A_SpawnItem("Gib_HFQSZ_Arm");
	Stop;
}}

CLASS XDeathHFQSZArm1Kicked: XDeathArm1 { 
	Default {
 
+ACTIVATEMCROSS
+ACTIVATEIMPACT
+CANUSEWALLS
	}
    States
    {
    Spawn:
	    TNT1 A 0 A_ChangeFlag("NOCLIP", 1)
	    QARM A 2
		TNT1 A 0 A_ChangeFlag("NOCLIP", 0)
		TNT1 A 0
        TNT1 A 0 A_SpawnItem("brutal_BloodSpot",0,0,0,1)
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Death")
		QARM ABCDEFGH 3 A_CustomMissile ("brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360))
		Goto Spawn+3
	}
}

CLASS GibHFQSZArmPart: TinyGib { 
	Default {
 
    Scale 0.8
	}
    States
    {
Spawn:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
		QARM Z -1
        Stop
    Death:
QARM Z 1
       Loop
}}

CLASS GibHFQSZHand: TinyGib { 
	Default {
 
    Scale 0.8
	}
    States
    {
Spawn:
		TNT1 A 0
		TNT1 A 0 A_QueueCorpse
		QARM Y -1
        Stop
    Death:
QARM Y 1
       Loop
}}


CLASS XDeathHFQSZArm2: XDeathArm1 { 
	Default {
 
	Speed 10
	}
}

// QSZ LEG

CLASS XDeathHFQSZLeg1: XDeathHFQSZArm1 { 
	Default {
 
    Scale 1.1
    Speed 8
	Gravity 0.4
CLASSceFactor 0.4 : ACTOR { 
	Default {
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			LEGQ ABCDEFGH 5 A_CustomMissile ("brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("brutal_BloodSpot",0,0,0,1);
			LEGQ A 1;
			LEGQ A 0 A_SpawnItem("Gib_HFQSZLeg",0,0,0,1);
			Stop;
	}
}

CLASS Gib_HFQSZLeg: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LEGQ A 1 A_SpawnItem("brutal_BloodSpot",0,0,0,1);
			LEGQ A -1;
			Stop;
		Death.plasma:    TNT1 A 0 A_CustomMissile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160))        Stop
		Death:    
			TNT1 AAAA 0 A_CustomMissile ("brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_CustomMissile ("GibHFQSZLegPart", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_CustomMissile ("GibHFQSZBoot", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			LEGQ A 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathHFQSZLeg1", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			LEGQ ABCDEFGH 2;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			LEGQ ABCDEFGH 5;
			XDT5 I 0 A_SpawnItem("Gib_HFQSZLeg");
			Stop;
			
}}

CLASS GibHFQSZLegPart: TinyGib { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LEGQ Z -1;
			Stop;
		Death:
			LEGQ Z 1;
			Loop;
}}

CLASS GibHFQSZBoot: TinyGib { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LEGQ Y -1;
			Stop;
		Death:
			LEGQ Y 1;
			Loop;
}}



CLASS XDeathHFQSZLeg2: XDeathHFQSZArm1 { 
	Default {
		
		Scale 1.1;
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			LEGQ ABCDEFGH 5 A_CustomMissile ("brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("brutal_BloodSpot",0,0,0,1);
			LEGQ E 1;
			LEGQ A 0 A_SpawnItem("Gib_HFQSZLeg2",0,0,0,1);
			Stop;
	}
}

CLASS Gib_HFQSZLeg2: Gib_HFQSZLeg { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LEGQ E 1 A_SpawnItem("brutal_BloodSpot",0,0,0,1);
			LEGQ E -1;
			Stop;
		Death.plasma:    TNT1 A 0 A_CustomMissile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160))        Stop
		Death:    
			TNT1 AAAA 0 A_CustomMissile ("brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_CustomMissile ("GibHFQSZLegPart", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_CustomMissile ("GibHFQSZBoot", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
		Death.Kick:
		Death.Melee:
		Death.SuperPunch:
			LEGQ A 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathHFQSZLeg1", 5, 0, random (170, 190), 2, random (20, 40));
Stop}}
		
CLASS XDeathHalfHFQSZDown : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 1.1;
		Speed 6;
		Mass 4;
		Decal BrutalBloodSplat;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("brutal_BloodSpot",0,0,0,1);
			QZD1 G 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("brutal_BloodSpot",0,0,0,1);
			QZD1 H 0 A_SpawnItem("GibHalfHFQSZDown",0,0,0,1);
			Stop;
	}
}

CLASS GibHalfHFQSZDown: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			QZD1 H 1 A_SpawnItem("brutal_BloodSpot",0,0,0,1);
			QZD1 H -1;
Stop    }}
	   
CLASS HFQSZFatality1Aftermath: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			QZFT A 1 A_SpawnItem("brutal_BloodSpot",0,0,0,1);
			QZFT A -1;
Stop    }}
	   

CLASS GibHalfHFQSZ: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			QP3X G 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			QP3X G -1;
Stop    }}
	   
CLASS XDeathHFQSZHead: XDeathZombieManHead { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			XHEQ ABCD 6;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			QHED A 1;
			QHED A 1 A_SpawnItem("HFQSZHead",0,0,0,1);
			Stop;
			
	}
}

CLASS HFQSZHead: ZombieManHead { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			QHED A 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			QHED A -1;
			Stop;
		Death:
			TNT1 AAAAA 0 A_CustomMissile ("Brutal_FlyingBloodTrail5", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 AAAA 0 A_CustomMissile ("Brains1", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_CustomMissile ("Brains2", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_CustomMissile ("Brains3", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_CustomMissile ("Brains4", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_CustomMissile ("Brains5", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 AAAAAA 0 A_CustomMissile ("SmallBrainPiece", 5, 0, random (0, 360), 2, random (60, 140));
			HEDQ A -1;
			Stop;
		Death.Melee:
		Death.SuperPunch:
		Death.Kick:
			HEDQ AA 1 A_FaceTarget();
			TNT1 A 0 A_CustomMissile ("XDeathHFQSZHead", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHEQ ABCD 3;
			Goto Spawn;
			
		Death.ExplosiveImpact:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("NOBLOCKMAP", 0);
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			XHEQ ABCD 6;
			XDT5 I 0 A_SpawnItem("HFQSZHead");
			Stop;
			
}}


CLASS XDeathCyberdemonHeadPiece: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		+SKYEXPLODE;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			HEDC ABCDEFGH 5;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			HEDC A 1;
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			HEDC A -1;
			Stop;
	}
}

CLASS XDeathCyberdemonGun: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		+SKYEXPLODE;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			HND7 ABCDEFGH 5;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			HND7 E 1;
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			HND7 E -1;
			Stop;
	}
}

CLASS XDeathCyberdemonArm: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		+SKYEXPLODE;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			HND9 ABCDEFGH 5;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			HND9 A 1;
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			HND9 A -1;
			Stop;
	}
}

CLASS XDeathCyberdemonLeg1: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		+SKYEXPLODE;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			LEG7 ABCDEFGH 5;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			LEG7 A 1;
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LEG7 A -1;
			Stop;
	}
}

CLASS XDeathCyberdemonLeg2: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		+SKYEXPLODE;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			LEG9 ABCDEFGH 5;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			LEG9 A 1;
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			LEG9 A -1;
			Stop;
	}
}

CLASS XDeathCyberdemonTorso1: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		+SKYEXPLODE;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			TRC1 ABCDDDDDDDBCDD 5;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TRC1 E 1;
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TRC1 E -1;
			Stop;
	}
}

CLASS XDeathCyberdemonTorso2: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		+SKYEXPLODE;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			TRC2 ABCDDDDDDDBCDD 5;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TRC2 E 1;
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TRC2 E -1;
			Stop;
	}
}

CLASS XDeathCyberdemonTorso3: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		+SKYEXPLODE;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			TRC3 ABCDDDDDDDBCDD 5;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TRC3 E 1;
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			TRC3 E -1;
			Stop;
	}
}

CLASS XDeathCyberdemonHead2: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		+SKYEXPLODE;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(momz == 0, "Death");
			HED7 ABCDEFGH 5;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			HED7 H 1;
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			HED7 H -1;
			Stop;
	}
}


CLASS SpiderLeg2 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+DOOMBOUNCE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		BounceFactor 0.3;
		BounceCount 3;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDS2 ABCDEFGH 2;
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_QueueCorpse();
			XDS2 I -1;
			Stop;
	}
}

CLASS XDeathArachnotronHead2: XDeath1 { 
	Default {
		
		Speed 12;
		Gravity 0.9;
		+DONTSPLASH;
		DeathSound "none";
		SeeSound "none";
		+SKYEXPLODE;
		Decal none;
		Scale 1.0;
	}
	States
	{
		Spawn:
			NAHB ABCDEFGH 4;
			Loop;
		Death:
			TNT1 A 0;
			//TNT1 A 0 A_Jump(128, "CleanDeath")
			TNT1 A 0 A_SpawnItem("CrawlingDyingSpider2");
			Stop;
		CleanDeath:
			TNT1 AAAAAAAAAAAA 0 A_CustomMissile ("SmallBrainPiece", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_CustomMissile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
			NAHD IJKLMN 5;
			NAHD N -5;
			Stop;
	}
}	   

CLASS XDeathArachnotronHead3: XDeath1 { 
	Default {
		
		Speed 12;
		Gravity 0.9;
		+DONTSPLASH;
		DeathSound "none";
		SeeSound "none";
		+SKYEXPLODE;
		Decal none;
		Scale 1.0;
	}
	States
	{
		Spawn:
			AAHB ABCDEFGH 4;
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_Jump(16, "CleanDeath");
			TNT1 A 0 A_SpawnItem("CrawlingDyingSpider3");
			Stop;
		CleanDeath:
			TNT1 AAAAAAAAAAAA 0 A_CustomMissile ("SmallBrainPiece", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_CustomMissile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
			AAHD IJKLMN 5;
			AAHD N -5;
			Stop;
	}
}

CLASS XDeathSkinPiece1: Xdeath1 { 
	Default {
		
		Radius 2;
		Height 2;
		Speed 10;
		Scale 1.0;
		Mass 1;
		SeeSound "none";
		DeathSound "none";
		Mass 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Underwater");
			XSKI A 4;
			Loop;
		Death:
			XSKI B 1;
			TNT1 A 0 A_QueueCorpse();
			XSKI B -1;
			Stop;
			TNT1 A 1;
		Underwater:
		Splash:
			Goto Death;
	}
}	


CLASS XDeathSkinPiece2: Xdeath1 { 
	Default {
		
		Radius 2;
		Height 2;
		Speed 10;
		Scale 1.0;
		Mass 1;
		SeeSound "none";
		DeathSound "none";
		Mass 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Underwater");
			XSKI C 4;
			Loop;
		Death:
			XSKI D 1;
			TNT1 A 0 A_QueueCorpse();
			XSKI D -1;
			Stop;
			TNT1 A 1;
		Underwater:
		Splash:
			Goto Death;
	}
}
