CLASS RevenantBalls66: RevenantBalls { 
	Default {
	Damage 10;
	Speed 20;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,random(20, 0),0,1);
		Goto Spawn1;
	}
}

CLASS RevenantMissileFriendAttackSummon : ACTOR { 
	Default {
	
	Radius 1;
	Height 1;
	Speed 0;
	Health 1;
	gravity 0.5;
	Decal "BloodSuper";
	+NOCLIP;
	MONSTER;
	+FRIENDLY;
	+LOOKALLAROUND;
	-SHOOTABLE;
	+MISSILEMORE;
	+MISSILEEVENMORE;
	+DONTTHRUST;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_Look;
		TNT1 AAA 0 A_Chase;
		TNT1 AAAAAA 1 A_Chase;
		Stop;
	Missile:
		TNT1 A 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("RevenantBalls66");
		Stop;
	}
}

cLASS RevenantRocketFire1823 : Inventory { 
	Default {
	
	inventory.maxamount 1;
	}
}

CLASS DoomerRevenantSeeker2 : RevenantSeeker { 
	Default {
	
	Damage 26;
	SeeSound "HMLF1";
	Speed 35;
	Species "Marine";
	+MTHRUSPECIES;
	+THRUSPECIES;
	-THRUGHOST;
	+Screenseeker;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_PlaySound("weapons/rocketloop",6,1,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
		FATB AB 1 BRIGHT A_SpawnItem("Red_FlareSmall",0,0);
		TNT1 A 0 A_SeekerMissile (20,30,SMF_LOOK );
		TNT1 A 0 A_SpawnItemEx("RevenantProjectileTrails", 0, 0, 0, 0, 0, 0, 0, 128);
		TNT1 A 0 A_SpawnItem ("ExplosionSmoke");
		
		FATB AB 1 BRIGHT A_SpawnItem("Red_FlareSmall",0,0);
		TNT1 A 0 A_SeekerMissile (20,30,SMF_LOOK );
		TNT1 A 0 A_SpawnItemEx("RevenantProjectileTrails", 0, 0, 0, 0, 0, 0, 0, 128);
		TNT1 A 0 a_spawnprojectile ("ExplosionSmoke", 2, 0, random (70, 110), 2, random (0, 360));
		Loop;
		
	Death:
		EXPL A 0 Radius_Quake (2, 54, 0, 15, 0);
		TNT1 A 0 A_SpawnItemEx ("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		BFE1 A 0 Bright A_Explode(18, 120, 1);
		TNT1 A 0 A_SpawnItemEx ("NewRocketExploFX_Small",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
		EXPL A 0;
		TNT1 AAAAA 0 a_spawnprojectile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 10;
		Stop;
	}
}

CLASS DoomerRevenantSeeker3 : RevenantSeeker { 
	Default {
	
	Damage 27;
	Speed 35;
	SeeSound "HMLF2";
	Species "Marine";
	+MTHRUSPECIES;
	+THRUSPECIES;
	-THRUGHOST;
	+SCREENSEEKER;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_PlaySound("weapons/rocketloop",6,1,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
		FATB AB 1 BRIGHT A_SpawnItem("Red_FlareSmall",0,0);
		TNT1 A 0 A_SeekerMissile (20,30,SMF_LOOK );
		TNT1 A 0 A_SpawnItemEx("RevenantProjectileTrails", 0, 0, 0, 0, 0, 0, 0, 128);
		TNT1 A 0 A_SpawnItem ("ExplosionSmoke");
		
		FATB AB 1 BRIGHT A_SpawnItem("Red_FlareSmall",0,0);
		TNT1 A 0 A_SeekerMissile (20,30,SMF_LOOK );
		TNT1 A 0 A_SpawnItemEx("RevenantProjectileTrails", 0, 0, 0, 0, 0, 0, 0, 128);
		TNT1 A 0 a_spawnprojectile ("ExplosionSmoke", 2, 0, random (70, 110), 2, random (0, 360));
		Loop;
		
	Death:
		EXPL A 0 Radius_Quake (2, 54, 0, 15, 0);
		TNT1 A 0 A_SpawnItemEx ("NewRocketExploFX_Small",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		BFE1 A 0 Bright A_Explode(18, 120, 1);
		TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
		EXPL A 0;
		TNT1 AAAAA 0 a_spawnprojectile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 10;
		Stop;
	}
}

CLASS DoomerRevenantMissile2 : RevenantMissile { 
	Default {
	
	Damage 27;
	Speed 35;
	SeeSound "HMLF1";
	Damagetype "explosiveimpact";
	Species "Marine";
	-MTHRUSPECIES;
	+DONTHURTSPECIES;
	}
	States
	{
	Death:
		EXPL A 0 Radius_Quake (2, 54, 0, 15, 0);
		TNT1 A 0 A_SpawnItemEx ("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		BFE1 A 0 Bright A_Explode(16, 120, 1);
		TNT1 A 0 A_SpawnItemEx("ExplosionParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		
		EXPL A 0;
		TNT1 A 0 A_SpawnItemEx ("NewRocketExploFX_Small",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAA 0 a_spawnprojectile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 10;
		Stop;
	}
}

CLASS DoomerRevenantMissile3 : RevenantMissile { 
	Default {
	
	Damage 27;
	Speed 35;
	SeeSound "HMLF2";
	Damagetype "explosiveimpact";
	Species "Marine";
	-MTHRUSPECIES;
	}
	States
	{
	Death:
		EXPL A 0 Radius_Quake (2, 54, 0, 15, 0);
		TNT1 A 0 A_SpawnItemEx ("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		BFE1 A 0 Bright A_Explode(16, 120, 1);
		TNT1 A 0 A_SpawnItemEx("ExplosionParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		
		EXPL A 0;
		TNT1 A 0 A_SpawnItemEx ("NewRocketExploFX_Small",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAA 0 a_spawnprojectile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 10;
		Stop;
	}
}

CLASS MiniMissile1 : RevenantMissile { 
	Default {
	
	DamageFunction (random(32,34));
	DamageType "explosiveimpact";
	Speed 38;
	Scale 1.15;
	SeeSound "weapons/RLL";
	}
	States
	{
	Death:
		EXPL A 0 Radius_Quake (2, 54, 0, 15, 0);
		TNT1 A 0 A_SpawnItemEx ("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		BFE1 A 0 Bright A_Explode(55, 125, 1);
		TNT1 A 0 A_SpawnItemEx("ExplosionParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		
		EXPL A 0;
		TNT1 A 0 A_SpawnItemEx ("NewRocketExploFX_Small",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAA 0 a_spawnprojectile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 10;
		Stop;
	}
}

CLASS DoomerRevBeamTrail : ACTOR { 
	Default {
	
	RenderStyle "Add";
	Scale 0.08;
	Alpha 1;
	+NOINTERACTION;
	+NOGRAVITY;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SetScale(Scale.X, Scale.Y -0.0875);
		YAE4 A 2 bright;//A_SpawnItemEx("ObeliskTrailSpark", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, 128, 0)
		YAE4 A 2 bright;
	Trolololo:
		YAE4 A 0 A_JumpIf(Scale.Y <= 0, "NULL");
		YAE4 A 0 A_SetScale(Scale.X -0.005, Scale.Y -0.005);
		YAE4 A 1 bright A_FadeOut(0.295);
		Loop;
	}
}

CLASS DoomerRevBeam : FastProjectile { 
	Default {
	
	Speed 225;
	Radius 4;
	Height 4;
	Damage 12;
	Renderstyle "Add";
	DamageType "Incinerate";
	// +RIPPER
	-CANNOTPUSH;
	+NODAMAGETHRUST;
	-EXTREMEDEATH;
	// +FORCERADIUSDMG
	Species "Marine";
	+MTHRUSPECIES;
	+THRUSPECIES;
	DeathSound "weapons/StachanovHit";
	MissileType "DoomerRevBeamTrail";
	MissileHeight 10;
	Decal "BFGLightning";
	Decal "BigScorch";
}
states
{
	Spawn:
		TNT1 A 0;
		TNT1 A 1 A_PlaySound("Weapons/StachanovFly",5,1.0,1);
	Loop;

	Death:
		TNT1 A 0 A_PlaySound("Weapons/YamatoExp",5);
		TNT1 A 0 A_Explode(random(18,22),8,0,0);
		TNT1 AAAAAAAAAA 0 A_SpawnItemEx("ObeliskTrailSpark", random(19,-19), random(19,-19), random(19,-19), 0, 0, 0, 0, 128, 0);
		TNT1 A 0 A_SpawnItemEx("ObeliskExplode",0,0,0,0,0,0,0,128,0);
		TNT1 BCD 4;
	stop;
}

}