version "3.6"
const C_TID	= 1000;	//Default camera tid
const  MAX_R	= 56+32;	//Maximum radius (or distance from the player)
const  ADJUST_R = 8;	//Amount to adjust the camera by
const  VIEW_HEIGHT = 61.0;	//The approximate hight of the player's view


//base must be in first lines, since gzdoom load actors definition
//in order it placed here, in root zscript file
//in other case, it breaks with error "unknows class/state can be defined only for actors/etc."
#include "zscript/project_brutality/basic_base.zsc"
#include "zscript/project_brutality/events.zsc"
#include "zscript/project_brutality/player_base.zsc"
#include "zscript/project_brutality/weapon_base.zsc"

#include "zscript/project_brutality/monsters/T1-Grunts/proto_zombie.zsc"
#include "zscript/project_brutality/monsters/T1-Imps/proto_imp.zsc"
#include "zscript/project_brutality/monsters/T2-Pinkies/proto_pinky.zsc"

#include "zscript/project_brutality/monsters/T4-Viles/proto_arch.zsc"
#include "zscript/project_brutality/monsters/T4-Viles/ARCHVILE.zsc"
#include "zscript/project_brutality/monsters/T4-Viles/Hellion.zsc"
#include "zscript/project_brutality/monsters/T4-Viles/FleshWizard.zsc"
#include "zscript/project_brutality/monsters/T4-Viles/IceVile.zsc"//imps included in icevile definitions


#include "zscript/project_brutality/monsters/t4-nobles/proto_noble.zsc"
#include "zscript/project_brutality/monsters/T4-Nobles/CyberBaron.zsc"
#include "zscript/project_brutality/monsters/T4-Nobles/Infernus.zsc"
#include "zscript/project_brutality/monsters/T4-Nobles/BARON.zsc"
#include "zscript/project_brutality/monsters/t4-nobles/knigth.zsc"
#include "zscript/project_brutality/monsters/T4-Nobles/BELPHEGOR.zsc"
#include "zscript/project_brutality/monsters/T4-Nobles/CyberKnight.zsc"
#include "zscript/project_brutality/monsters/T4-Nobles/CyberPaladin.zsc"

#include "zscript/project_brutality/monsters/Tz-Bosses/proto_bosses.zsc"
#include "zscript/project_brutality/monsters/Tz-Bosses/CYBERDEMON.zsc"
#include "zscript/project_brutality/monsters/Tz-Bosses/MASTERMIND.zsc"
#include "zscript/project_brutality/monsters/Tz-Bosses/BossBrain.zsc"
#include "zscript/project_brutality/monsters/Tz-Bosses/Abomination.zsc"
#include "zscript/project_brutality/monsters/Tz-Bosses/Motherdemon.zsc"
#include "zscript/project_brutality/monsters/Tz-Bosses/ANNIHILATOR.zsc"
#include "zscript/project_brutality/monsters/Tz-Bosses/Demolisher.zsc"

#include "zscript/project_brutality/monsters/T3-Revies/proto_skeleton.zsc"
#include "zscript/project_brutality/monsters/T3-Revies/REVENANT.zsc"
#include "zscript/project_brutality/monsters/T3-Revies/BeamRev.zsc"
#include "zscript/project_brutality/monsters/T3-Revies/Draugr.zsc"

#include "zscript/project_brutality/monsters/T3-Floaters/proto_puffballs.zsc"
#include "zscript/project_brutality/monsters/T3-Floaters/CACODEMON.zsc"
#include "zscript/project_brutality/monsters/T3-Floaters/PAIN.zsc"
#include "zscript/project_brutality/monsters/T3-Floaters/proto_skull.zsc"
#include "zscript/project_brutality/monsters/T3-Floaters/TriteElem.zsc"//trite include in trite elemntal definition
#include "zscript/project_brutality/monsters/T3-Floaters/Phantasm.zsc"
#include "zscript/project_brutality/monsters/T3-Floaters/SufferingElemental.zsc"
#include "zscript/project_brutality/monsters/T3-Floaters/Overlord.zsc"
#include "zscript/project_brutality/monsters/T3-Floaters/Watcher.zsc"
#include "zscript/project_brutality/monsters/T3-Floaters/Afrit.zsc"
#include "zscript/project_brutality/monsters/T3-Floaters/InfernalCaco.zsc"
#include "zscript/project_brutality/monsters/T3-Floaters/LOSTSOUL.zsc"

#include "zscript/project_brutality/monsters/T3-Fats/proto_fat.zsc"
#include "zscript/project_brutality/monsters/T3-Fats/MANCUBUS.zsc"
#include "zscript/project_brutality/monsters/T3-Fats/Daedabus.zsc"
#include "zscript/project_brutality/monsters/T3-Fats/Volcabus.zsc"

#include "zscript/project_brutality/monsters/T3-Arachnos/proto_spider.zsc"
#include "zscript/project_brutality/monsters/T3-Arachnos/Aracnorb.zsc"
#include "zscript/project_brutality/monsters/T3-Arachnos/InfernalArachnotron.zsc"
#include "zscript/project_brutality/monsters/T3-Arachnos/Arachnophyte.zsc"
#include "zscript/project_brutality/monsters/T3-Arachnos/EliteArachnotron.zsc"
#include "zscript/project_brutality/monsters/T3-Arachnos/Arachnotron.zsc"
/*
#include "zscript/project_brutality/monsters/T1-Imps/IMPS.zsc"

#include "zscript/project_brutality/monsters/T1-Grunts/ZOMBIEMEN.zsc"

#include "zscript/project_brutality/monsters/T1-Grunts/SERGEANTS.zsc"
#include "zscript/project_brutality/monsters/T1-Grunts/Commando.zsc"
#include "zscript/project_brutality/monsters/T2-Pinkies/DEMONS.zsc"
#include "zscript/project_brutality/monsters/T2-Pinkies/VOIDSPECTRE.zsc"
#include "zscript/project_brutality/monsters/T2-Pinkies/SPECTRE.zsc"




//ST Monsters
#include "zscript/project_brutality/monsters/Tz-Bosses/JUGGERNAUT.zsc"
#include "zscript/project_brutality/monsters/T0-Marines/MARINESPAWNER.zsc"
#include "zscript/project_brutality/monsters/T1-Grunts/ZombiemanVariants.zsc"
#include "zscript/project_brutality/monsters/T1-Grunts/CarbineZombie.zsc"
#include "zscript/project_brutality/monsters/T1-Grunts/MinigunGuy.zsc"
#include "zscript/project_brutality/monsters/T1-Grunts/ZombieScientist.zsc"
#include "zscript/project_brutality/monsters/T1-Grunts/ChainsawZombie.zsc"
#include "zscript/project_brutality/monsters/T1-Grunts/SergeantVariant.zsc"
#include "zscript/project_brutality/monsters/T1-Grunts/RocketZombie.zsc"
#include "zscript/project_brutality/monsters/T1-Grunts/Kamikaze.zsc"
#include "zscript/project_brutality/monsters/T1-Grunts/DemonTechTroop.zsc"
#include "zscript/project_brutality/monsters/T1-Grunts/QuadSGGuy.zsc"
#include "zscript/project_brutality/monsters/T1-Grunts/ZSpecOps.zsc"
#include "zscript/project_brutality/monsters/T1-Grunts/AutoShottyGuy.zsc"

#include "zscript/project_brutality/monsters/T1-Imps/ImpVariants.zsc"
#include "zscript/project_brutality/monsters/T1-Imps/ImpVariant1.zsc"
#include "zscript/project_brutality/monsters/T1-Imps/ImpVariant2.zsc"
#include "zscript/project_brutality/monsters/T1-Imps/SavageImp.zsc"
#include "zscript/project_brutality/monsters/T1-Imps/DarkImpNami.zsc"
#include "zscript/project_brutality/monsters/T1-Imps/DarkImpNether.zsc"
#include "zscript/project_brutality/monsters/T1-Imps/DarkImpST.zsc"
#include "zscript/project_brutality/monsters/T1-Imps/DarkImpVoid.zsc"

#include "zscript/project_brutality/monsters/T1-Grunts/RifleCommando.zsc"
#include "zscript/project_brutality/monsters/T1-Grunts/HMGMajor.zsc"
#include "zscript/project_brutality/monsters/T1-Grunts/PlasmaZombie.zsc"
#include "zscript/project_brutality/monsters/T1-Grunts/ClassicCommando.zsc"
#include "zscript/project_brutality/monsters/T1-Grunts/HelmetCommando.zsc"


#include "zscript/project_brutality/monsters/T2-Pinkies/MeanDemon.zsc"
#include "zscript/project_brutality/monsters/T2-Pinkies/MechDemon.zsc"

#include "zscript/project_brutality/monsters/T1-Grunts/ZombieFlyer.zsc"

////////////////////////////////////////////////////////////////////////////
/*
//New Death System
#include "zscript/project_brutality/monsters/T1-Grunts/ZOMBIEMEN_DeathAnim.zsc"

//Lil Guys!
#include "zscript/project_brutality/monsters/Tz-Shrinks/ZombieShrinks.zsc"
#include "zscript/project_brutality/monsters/Tz-Shrinks/SergeantShrinks.zsc"
#include "zscript/project_brutality/monsters/Tz-Shrinks/CommandoShrinks.zsc"
#include "zscript/project_brutality/monsters/Tz-Shrinks/ImpShrinks.zsc"
#include "zscript/project_brutality/monsters/Tz-Shrinks/DemonShrinks.zsc"
#include "zscript/project_brutality/monsters/Tz-Shrinks/NoblesShrinks.zsc"
#include "zscript/project_brutality/monsters/Tz-Shrinks/MancubusShrinks.zsc"

#include "zscript/project_brutality/monsters/T0-Marines/CapturedMarine.zsc"
#include "zscript/project_brutality/monsters/T0-Marines/Marine-AutoShotgun.zsc"
#include "zscript/project_brutality/monsters/T0-Marines/Marine-BFG.zsc"
#include "zscript/project_brutality/monsters/T0-Marines/Marine-Chaingun.zsc"
#include "zscript/project_brutality/monsters/T0-Marines/Marine-Plasmagun.zsc"
#include "zscript/project_brutality/monsters/T0-Marines/Marine-PulseCannon.zsc"
#include "zscript/project_brutality/monsters/T0-Marines/Marine-RocketLauncher.zsc"
#include "zscript/project_brutality/monsters/T0-Marines/Marine-Shotgun.zsc"


#include "zscript/project_brutality/monsters/T1-Grunts/DyingGuys.zsc"
#include "zscript/project_brutality/monsters/T1-Grunts/DyingNewGuys.zsc"

#include "zscript/project_brutality/monsters/T1-Grunts/LastStandMonsters.zsc"

#include "zscript/project_brutality/monsters/T1-Grunts/NAZIS.zsc"

#include "zscript/project_brutality/monsters/T1-Imps/DyingDarkImps.zsc"

#include "zscript/project_brutality/monsters/Tz-Bosses/SpecialDoom1Bosses.zsc"

#include "zscript/project_brutality/monsters/Frozen.zsc"
#include "zscript/project_brutality/monsters/realm667monsters.zsc"
#include "zscript/project_brutality/monsters/StealthMonsters.zsc"
#include "zscript/project_brutality/monsters/UnderwaterMonsters.zsc"

//Special Monsters
#include "zscript/project_brutality/monsters/Tz-Special/EVIL.zsc"
#include "zscript/project_brutality/monsters/Tz-Special/Epic2Sstuff.zsc"
*/

//all classes must be moved from here to specific zscript files
//much of which are just a plug for gzdoom zscript compile
//to shut down it "Unknown base class!!! ERROR STOP Ex000000000000000000"



class zscript_CurbstompedMarine : actor
{
default
{
    Mass 5000;
    Health 300;
	PainChance 255;
	Mass 6000;
	bloodtype "DeadBlood";
	Radius 10;
	Height 6;
 
    +MOVEWITHSECTOR
	+FLOORCLIP
	+NOBLOCKMONST
	//+CANPASS
	+THRUACTORS;
	+FORCEXYBILLBOARD
	+SHOOTABLE
	+CLIENTSIDEONLY
	+CORPSE
	+NEVERTARGET
	+NOTELEPORT;

	damagefactor "Kick", 3.0;
	damagefactor "SuperKick", 3.0;
	damagefactor "ExtremePunches", 2.0;
	damagefactor "SuperPunch", 2.0;
	damagefactor "TeleportRemover", 1000.0;
	damagefactor "GibRemoving", 0.5;
	damagefactor "Normal", 2.0;
	damagefactor "Desintegrate", 990.0;
	damagefactor "BFG", 990.0;
	damagefactor "Blood", 0.0;	damagefactor "GreenBlood", 0.0; damagefactor "BlueBlood", 0.0;
    damagefactor "Taunt", 0.0;	damagefactor "KillMe", 0.0;
	damagefactor "Crush", 9999.00;
	damagefactor "Crusher", 9999.00;
	damagefactor "CrushedBodies", 9999.00;
	
}
States
{
    Spawn:
		PLDH A 3000 ;
	Loop;

    Death:
	Death.Stomp:
  	   TNT1 A 0 A_SpawnItem("GibsZ");
	   TNT1 A 0 A_NoBlocking();
		 TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
		 TNT1 AA 0 A_SpawnProjectile ("XDeath2b", 5, 0, random (0, 360), 2, random (0, 160));
		 TNT1 AA 0 A_SpawnProjectile ("XDeath3b", 5, 0, random (0, 360), 2, random (0, 160));
		 TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 5, 0, random (0, 360), 2, random (0, 160));
		 TNT1 AAAAAAA 0 A_SpawnProjectile ("XDeathSkinPiece2", 5, 0, random (0, 360), 2, random (0, 160));
		 TNT1 AAAA 0 A_SpawnProjectile ("XDeathSkinPiece1", 5, 0, random (0, 360), 2, random (0, 160));
		 TNT1 AAAAAAAA 0 A_SpawnProjectile ("SmallSuperGore", 10, 0, random (0, 360), 2, random (10, 170));
		 TNT1 AAAAA 0 A_SpawnProjectile ("BloodMistSmall", 15, 0, random (0, 360), 2, random (40, 90));
		 Stop;

    Death.plasma:
        TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
        TNT1 A 0 A_XScream();
        TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
	    TNT1 A 0 A_SpawnProjectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
	    TNT1 A 0 A_SpawnProjectile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
		EXPL AAA 0 A_SpawnProjectile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
        TNT1 A 0;
        Stop;
		
	Death.TeleportRemover:
	Death.GibRemoving:
	    TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 {self.bNOCLIP = true;}
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0  A_ChangeLinkFlags(true);
		Stop;
		
	Death.CrushedBodies:
	Death.Crush:
	Crush:
		TNT1 A 0 A_NoBlocking();
		TNT1 AA 0 A_SpawnItem("MeatDeathSmall");
		
		TNT1 A 0 A_SetAngle(0);
		TNT1 A 0 bright A_SpawnProjectile ("SuperGoreSpawner2", 1, -40, random (0, 360), 2, random (25, 45));
		TNT1 A 0 bright A_SpawnProjectile ("SuperGoreSpawner2", 1, 40, random (0, 360), 2, random (25, 45));
		 TNT1 A 0 A_SpawnProjectile("XDeath1", 1, random (-30, 30), random (0, 360), 2, random (0, 160));
		 TNT1 A 0 A_SpawnProjectile ("XDeath2b", 1, random (-30, 30), random (0, 360), 2, random (0, 160));
		 TNT1 A 0 A_SpawnProjectile ("XDeath3b", 1, random (-30, 30), random (0, 360), 2, random (0, 160));
		 TNT1 AA 0 A_SpawnProjectile ("BloodMistBig", 1, -40, random (0, 360), 2, random (30, 90));
		 TNT1 AA 0 A_SpawnProjectile ("BloodMistBig", 1, 40, random (0, 360), 2, random (30, 90));
		 TNT1 A 0 A_SetAngle(90);
		 TNT1 A 0 bright A_SpawnProjectile ("SuperGoreSpawner2", 1, -40, random (0, 360), 2, random (25, 45));
		 TNT1 A 0 bright A_SpawnProjectile ("SuperGoreSpawner2", 1, 40, random (0, 360), 2, random (25, 45));
		 TNT1 A 0 A_SpawnProjectile ("XDeath1", 1, random (-30, 30), random (0, 360), 2, random (0, 160));
		 TNT1 A 0 A_SpawnProjectile ("XDeath2b", 1, random (-30, 30), random (0, 360), 2, random (0, 160));
		 TNT1 A 0 A_SpawnProjectile ("XDeath3b", 1, random (-30, 30), random (0, 360), 2, random (0, 160));
		 TNT1 AA 0 A_SpawnProjectile ("BloodMistBig", 1, -40, random (0, 360), 2, random (30, 90));
		 TNT1 AA 0 A_SpawnProjectile ("BloodMistBig", 1, 40, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnItem ("CrushedRemains");
		TNT1 A 1;
		TNT1 A 1 A_XScream();
	Stop ;
	
	Death.Desintegrate:
		 TNT1 A 0;
		 TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodFake", 0, 0, random (0, 360), 2, random (0, 90));
         TNT1 A 0 A_SpawnProjectile ("Brutal_FlyingBlood", 7, 0, random (0, 360), 2, random (30, 60));
		 TNT1 AA 0 A_SpawnProjectile ("BloodMistSmall", 7, 0, random (0, 360), 2, random (30, 60));
		 TNT1 A 0 A_SpawnItem("GibsZ");
		 TNT1 A 0 A_SpawnItem("MeatDeathSmall");
	Stop;
}

}

class BossBrainBase : Actor
{
	void RemoveCubes()
	{
		ThinkerIterator ti = ThinkerIterator.Create("Actor");
		Actor a;
		while (a = Actor(ti.Next()))
		{
			if (a is "SpawnShot" || a is "BossEye") a.Destroy();
			if (a.bISMONSTER && a.bCOUNTKILL) a.A_Die("Massacre");
		}
	}
}

class InvisiblePuff : BulletPuff
{
	Default
	{
		-ALLOWPARTICLES
	}
}
class InvisiblePuffAlways : InvisiblePuff
{
	Default
	{
		+ALWAYSPUFF
		+THRUACTORS
		+ALLOWTHRUFLAGS
	}
}

class GreenPlasmaBall : fastprojectile
{}