//===========================================================================
//
// Imp aka pimp my imp
//
//===========================================================================

CLASS pb_imp: proto_imp_class// Replaces DoomImp
{ 
Default
{	
	Scale 1.04;
	//SpawnID 1400;
	Health 75;

	Mass 100;
	GibHealth 35;
	Monster;
	MaxStepHeight 24;
	MaxDropOffHeight 32;
	Speed 8;

	+SLIDESONWALLS;
	+FLOORCLIP;

	PainChance 200;
	PainChance "Stun", 255;
	PainChance "Avoid", 35;
	PainChance "Head", 255;
	PainChance "Taunt", 255;
	PainChance "Kick", 255;
	PainChance "ExtremePunches", 255;
	PainChance "Melee", 255;
	PainChance "Fatality", 255;
	PainChance "ExplosiveImpact", 255;
	PainChance "Trample", 255;

	damagefactor "TeleportRemover", 0.0;
	damagefactor "GibRemoving", 0.0;
	damagefactor "Avoid", 1.0;
	damagefactor "Trample", 1.5;
	damagefactor "Crush", 10.0;
	DamageFactor "CauseObjectsToSplash", 0.0;
	damagefactor "killme", 0.0;
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0;
	damagefactor "Shrapnel", 0.3;
	damagefactor "explosiveimpact", 2.0;
	damagefactor "Kick", 0.5;
	damagefactor "SSG", 5.0;

	
	BloodType "pb_blood", "BloodSPlatterReplacer", "AxeBlood";
	Species "Imp";
	SeeSound "imp/sight";
	PainSound "imp/pain";
	DeathSound "imp/death";
	ActiveSound "imp/active";
	
//	//DropItem "DemonStrengthRune", 1;
//	//DropItem "Demonpickup", 60;
}

States
{	
	Spawn:
		TROO A 0;
 		TNT1 A 0 A_JumpIf(waterlevel >= 2, "Swim");
		TNT1 A 0 {self.on_floor = true;}
	Stand:
		TROS AB 11 A_Look();
	Loop;
		
	See:
		TNT1 A 0 A_TakeInventory("EnemyMemory", 15);
		tnt1 a 0 a_jumpif(first_seeing == true , 4);
		TROT A 4 A_faceTarget();
		TROT B 4 {first_seeing = true;}
		TROT C 10;//waving his arms here
		tnt1 a 0 a_spawnitemEx("FootStep", 0, 0, 10, 0, 0);
		TNT1 A 0 A_JumpIf(waterlevel >= 2, "Swim");
		TNT1 A 0 A_JumpIfInventory("EnemyMemory", 25, "ForgetTarget");
		TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
		TROO AAA 2 A_Chase();		
		TROO A 2 {A_Chase(); A_PlaySound("flesh/step",4); }
		TROO BBBBCCC 2 A_Chase();
		TROO C 2 {A_Chase(); A_PlaySound("flesh/step",4);}
		TROO DDDD 2 A_Chase();
		TNT1 A 0 A_Jump(236, 3);
		TNT1 A 0 A_JumpIfCloser(800, "jump_to_ceiling");
		TNT1 AAAAA 0;
	Loop;

	Idle:
	LookingForPlayer:
		//TNT1 A 0 A_GiveInventory("SKImp", 1);
		TNT1 A 0 {self.angle -= 40;}
		TROO BBB 10 A_Look();
		TNT1 A 0 {self.angle += 40;}
		TROO BBB 10 A_Look();
		TROO AA 2 {A_Wander(); A_Look(); A_PlaySound("flesh/step",4); A_Recoil(-2);}
		TROO BB 2 {A_Wander(); A_Look(); A_Recoil(-2);}
		TROO CC 2 {A_Wander(); A_Look(); A_PlaySound("flesh/step",4); A_Recoil(-2);}
		TROO DD 2 {A_Wander(); A_Look(); A_Recoil(-2);}
	Loop;

	Advancing:
		//TNT1 A 0 A_TAkeInventory("CantFire", 1);
		//TNT1 A 0 A_takeInventory("SKImp", 1);
		tnt1 a 0 a_spawnitemEx("FootStep", 0, 0, 10, 0, 0);
		TNT1 A 0 A_JumpIfInventory("EnemyMemory", 20, "ForgetTarget");
		TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
		TROO AAAA 2 A_Chase();
		TROO BBBB 2 A_Chase();
		TROO CCCC 2 A_Chase();
		TROO DDDD 2 A_Chase();
	Loop;
		
	jump_to_ceiling:
		TNT1 A 0
		{
			if(pb_imp_ceiling_jump() == false)
			{setstatelabel("see");}//ceiling too high or there ara sky
		}
		1M40 A 6
		{
			A_PlaySound("imp/sight",6);
			//self.vel.z += 110;
		}

		2M40 AAABBBBCCCCDDDD 1
		{
			if((pos.z + height) >= ceilingz)
			{
				pb_change_flags_for_jump();
				self.ceiling_jump = false; 
				self.on_ceiling = true;
				setstatelabel("CeilingLatch");
			}
		}
		
	jump_up:
		2M40 D 1
		{
			if((self.pos.z + self.height) >= self.ceilingz)
			{
				self.ceiling_jump = false; self.on_ceiling = true; self.on_floor = false;
				setstatelabel("CeilingLatch");
			}
		}
		tnt1 a 0 a_jumpif( self.vel.z <= 0, 1);
	loop;
		//jumps fail, make a good appearance
		2M40 EEEEFFFFGGGG 1
		{
			if( self.pos.z <= self.floorz)
			{
				self.ceiling_jump = false; self.on_ceiling = false;
				self.on_floor = true;
				setstatelabel("See");
			}
		}

	falling_down:
		1M40 A 1
		{
			if( self.pos.z <= self.floorz)
			{
				pb_change_flags_for_jump();
				self.ceiling_jump = false; self.on_ceiling = false;
				self.on_floor = true; setstatelabel("CeilingLatch");
			}
		}
	loop;
		
	CeilingCrawl:
		tnt1 a 0 a_spawnitemEx("FootStep", 0, 0, 10, 0, 0);
		TNT1 A 0 A_JumpIf(waterlevel >= 2, "Swim");

 		//TNT1 A 0 A_JumpIf(vel.z != 0, "jump_from_ceiling")
		//TNT1 A 0 ThrustThingZ(0,500,0,1);
		2M40 II 2 A_Chase("jump_from_ceiling", "CeilingMissile");

		2M40 HH 2 A_Chase("jump_from_ceiling", "Maybe_jump_from_ceiling");
		TNT1 A 0 A_PlaySound("flesh/step",4);
 		TNT1 A 0 A_JumpIf(vel.z != 0, "jump_from_ceiling");
		TNT1 A 0 A_JumpIfTargetInLOS(1);//this is too costly function, must be replaced by line tracer
	Goto CeilingDrop;
		TNT1 A 0;
		TNT1 A 0 A_Jump(224, 3);
		TNT1 A 0 A_JumpIfCloser(1200, "CeilingDrop");
		TNT1 AAAAA 0;
	Loop;
		
	CeilingDrop:
		TNT1 AAA 0;
		TNT1 A 0 {self.on_ceiling = false; self.bNOGRAVITY = false; self.bCEILINGHUGGER = false;}
		2M40 DCBA 1 A_FaceTarget();
	CeilingDropping:
		TROT F 1 A_JumpIf(vel.z == 0, "CeilingLanding");
	Loop;

	CeilingLanding:
		TNT1 A 0 A_PlaySound("flesh/step",4);
		TROT GHCD 5 A_FaceTarget();
	Goto see;

	CeilingMissile:
		2M40 L 4 A_FaceTarget();
		//TNT1 A 0 A_JumpIfCloser(150, "jump_from_ceiling");
		TNT1 A 0 A_Playsound("IMPCHARG");
		TNT1 A 0 a_spawnprojectile("FlameTrails", 25, -30, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ImBallGettingReady", 25, -30, random(0, 140), 2, random(0, 160));
		2M40 L 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("FlameTrails", 25, -30, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ImBallGettingReady", 25, -30, random(0, 140), 2, random(0, 160));
		//TNT1 A 0 ThrustThingZ(0,500,0,1);
		2M40 L 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("FlameTrails", 25, -30, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ImBallGettingReady", 25, -30, random(0, 140), 2, random(0, 160));
		//TNT1 A 0 ThrustThingZ(0,500,0,1);
		2M40 L 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("FlameTrails", 25, -30, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ImBallGettingReady", 25, -30, random(0, 140), 2, random(0, 160));
		//TNT1 A 0 ThrustThingZ(0,500,0,1);
		2M40 L 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("FlameTrails", 25, -30, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ImBallGettingReady", 25, -30, random(0, 140), 2, random(0, 160));
		//TNT1 A 0 ThrustThingZ(0,500,0,1);
		2M40 L 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("FlameTrails", 25, -30, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ImBallGettingReady", 25, -30, random(0, 140), 2, random(0, 160));
		//TNT1 A 0 ThrustThingZ(0,500,0,1);
		2M40 M 2 A_FaceTarget();
		//TNT1 A 0 ThrustThingZ(0,500,0,1);
		2M40 N 6 a_spawnprojectile("pb_imp_fireball", 22, 0, 0, 0);
		//TNT1 A 0 ThrustThingZ(0,500,0,1);
		2M40 M 4;
	Goto CeilingCrawl;
		
	Maybe_jump_from_ceiling:
		TNT1 A 0 A_Jump(28, 3);
	Goto CeilingCrawl;
	
	jump_from_ceiling:
		TNT1 AAA 0;
		TNT1 A 0 
		{
			self.on_ceiling = false; self.bNOGRAVITY = false;
			self.bCEILINGHUGGER = false; self.bTHRUSPECIES = false;
		}
		TNT1 A 0 A_Recoil(-18);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_PlaySound("weapons/fistwhoosh");
		TNT1 A 0 a_spawnprojectile("ImpAttack2",10,0,0,0);
		2M40 CDEFG 4 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("ImpAttack2",10,0,0,0);
		1M40 EEE 1 a_spawnprojectile("ImpAttack2",10,0,0,0);
		TNT1 A 0 {self.ceiling_jump = false;}
		
		TNT1 A 0 A_Jump(24, 3);
		1M40 A 6;
	Goto see;
		TNT1 AAA 0;
	Goto Melee+1;

	ForgetTarget:
		TNT1 A 0 A_ClearTarget();
		TNT1 A 0 A_TakeInventory("EnemyMemory", 25);
	Goto Stand;

	Melee:
		TNT1 A 0 A_Jump(132, "Melee3");
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_PlaySound("imp/sight",6);
		1M40 ABCD 4 A_Recoil(-1);
		1M40 A 5 A_FaceTarget();
		TNT1 A 0 A_JumpIfCloser(60, "Melee2");
		//TNT1 A 0 A_takeInventory("SKImp", 1);
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(-10);
		1M40 E 6;
		TNT1 A 0 {self.ceiling_jump = true;}
		TNT1 A 0 A_PlaySound("weapons/fistwhoosh");
		TNT1 A 0 A_FaceTarget();
		1M40 E 4 a_spawnprojectile("ImpAttack2",10,0,0,0);
		TNT1 A 0 {self.ceiling_jump = false;}
		1M40 A 4 a_spawnprojectile("ImpAttack2",10,0,0,0);
	Goto see;
		
	Melee2:
		TROO EF 4 A_FaceTarget();
		//TNT1 A 0 A_takeInventory("SKImp", 1);
		TROO G 4 a_spawnprojectile("ImpAttack",10,0,0,0);
		TROO FE 4;
	Goto see;
		
		
	Melee3:
		TROO E 1 A_FaceTarget();
		TNT1 A 0 A_JumpIfCloser(50, "Melee2");
		
		TROT CD 4;
		//TNT1 A 0 A_takeInventory("SKImp", 1);
		TNT1 A 0 ThrustThingZ(0,25,0,1);
		TNT1 A 0 A_FaceTarget();
		
		TNT1 A 0 A_Recoil(-10);
		TROT E 2;
		TROT F 2;
		TNT1 A 0 {self.ceiling_jump = true;}
		TNT1 A 0 A_PlaySound("weapons/fistwhoosh");
		TNT1 A 0 A_FaceTarget();
		TROT F 6;
		TNT1 A 0 a_spawnprojectile("ImpAttack2",10,0,0,0);
		TNT1 A 0 {self.ceiling_jump = false;}
		//TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
		TROT G 1;
		TROT GG 2 a_spawnprojectile("ImpAttack2",10,0,0,0);
		TROT G 1;
		//TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
		//TROT HHH 2 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
	Goto see;
		
	Missile:
		TNT1 A 0 {if(self.on_ceiling == true) { setstatelabel("CeilingMissile");} }
		TNT1 A 0 A_JumpIfCloser(150, "Melee");
		
		//TNT1 A 0 A_takeInventory("SKImp", 1);
		TNT1 A 0 A_JumpIfCloser(1200, 3);
		//TNT1 A 0 a_spawnprojectile("MonsterTargetCheck", 34, 0, 0, 0);
		//TNT1 A 0 a_spawnprojectile("MonsterTargetCheckFaster", 34, 0, 0, 0);
		TROO E 4 A_FaceTarget();
		//TNT1 A 0 A_JumpIfInventory("CantFire",1, "Advancing");
		TNT1 A 0 A_JumpIfCloser(170, "Melee");
		TNT1 A 0 A_Playsound("IMPCHARG");
		TNT1 A 0 a_spawnprojectile("FlameTrails", 35, 30, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ImBallGettingReady", 35, 30, random(0, 140), 2, random(0, 160));
		TROO E 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("FlameTrails", 35, 30, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ImBallGettingReady", 35, 30, random(0, 140), 2, random(0, 160));
		TROO E 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("FlameTrails", 35, 30, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ImBallGettingReady", 35, 30, random(0, 140), 2, random(0, 160));
		TROO E 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("FlameTrails", 35, 30, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ImBallGettingReady", 35, 30, random(0, 140), 2, random(0, 160));
		TROO E 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("FlameTrails", 35, 30, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ImBallGettingReady", 35, 30, random(0, 140), 2, random(0, 160));
		TROO E 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("FlameTrails", 35, 30, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ImBallGettingReady", 35, 30, random(0, 140), 2, random(0, 160));
		TNT1 A 0 A_Jump(100, "specialattack");
		TROO F 2 A_FaceTarget();
		TROO G 6 a_spawnprojectile("pb_imp_fireball", 34, 0, 0, 0);
		TROO F 4;
	Goto see;
		
	SpecialAttack:
		TROO F 2 A_FaceTarget();
		TROO G 6 a_spawnprojectile("pb_imp_fireball", 34, 0, 0, 0);
		TROO F 4;
		TROO I 2 A_FaceTarget();
		TROA H 6 a_spawnprojectile("pb_imp_fireball", 34, 0, 0, 0);
		TROO I 4;
	Goto see;
		
	Death.Eat:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Scream();
		//TNT1 A 0 A_GiveToTarget("ImpFatality",1);
		TNT1 A 0;
	stop;		
	Death.HelperMarineFatallity:
	Death.RVFT:
		TNT1 A 0;
		TNT1 A 1 A_Pain();
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_GiveToTarget("ImpFatality3", 1);
		//TNT1 A 0 A_GiveToTarget("ImpFatality", 1);
	stop;		
	Death.Fatality:
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_JumpIfIntargetInventory("FistsSelected", 1, 1);
	Goto Death.ExplosiveImpact;
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_Jump(255, "Death.Fatality", "Death.Fatality1", "Death.Fatality2", "Death.Fatality2", "Death.Fatality3", "Death.Fatality3", "Death.Fatality4", "Death.Fatality5");
	Death.Fatality1:
		//TNT1 A 0 A_GiveToTarget("ImpFatality", 1);
	stop;
	Death.Fatality2:
		//TNT1 A 0 A_GiveToTarget("ImpFatality2", 1);
	stop;	Death.Fatality3:
	Death.BHFT:
		//TNT1 A 0 A_GiveToTarget("ImpFatality3", 1);
	stop;	Death.Fatality4:
		//TNT1 A 0 A_GiveToTarget("ImpFatality4", 1);
	stop;	Death.Fatality5:
		//TNT1 A 0 A_GiveToTarget("ImpFatality5", 1);
	stop;		
		
	Pain.Melee:
		TNT1 A 0 {self.bNOGRAVITY = false; self.bTHRUSPECIES = false; self.bCEILINGHUGGER = false;}
		TNT1 D 0;
		TROO A 2;
		//TNT1 A 0 A_JumpIfInventory("SKImp", 1, "GotoStealthKill");
		TROO A 2 A_Pain();
	Goto see;
		
	GotoStealthKill:
		TNT1 A 1;
		//TNT1 A 0 A_GiveToTarget("SKImp");
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 1 A_Die("Stealthy");
	stop;
	
	Death.Stealthy:
		TNT1 A 0 A_NoBlocking();
	stop;
	
	Pain:
		TROO H 0;
		TNT1 A 0 {self.bNOGRAVITY = false; self.bTHRUSPECIES = false; self.bCEILINGHUGGER = false;}
		TNT1 A 0 { if( self.on_ceiling == true) { setstatelabel("PainCanFallFromCeiling");} }
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain.IsDown");
		//TNT1 A 0 A_takeInventory("SKImp", 1);
		TROO H 3;
		TROO H 3 A_Pain();
	Goto see;
		
	Possession:
		TNT1 A 0 A_SetInvulnerable();
		TROO H 3;
		TROO H 3 A_Pain();
 		TNT1 A 0 A_UnSetInvulnerable();
	Goto See;
		
	Pain.IsDown:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		ID11 B 1;
		ID11 B 5 A_Pain();
	Goto GetUp;
		
		
	Pain.KillMe:
	Pain.Taunt:
		TNT1 A 0;
	Goto Missile;

	Death.KillMe:
	Death.Taunt:
	Death.Avoid:
		TNT1 A 0 {self.bSOLID = false;}
	stop;
	
	Pain.head:
	Pain.minorhead:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 { if( self.on_ceiling == true) { setstatelabel("PainCanFallFromCeiling");} }
		//TNT1 A 0 A_takeInventory("SKImp", 1);
		TROO H 6;
		TROO H 6 A_Pain();
	Goto see;
		
	Pain.ExplosiveImpact:
	Pain.Explosive:
	Pain.ExtremePunches:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain");
		//TNT1 A 0 A_takeInventory("SKImp", 1);
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		IZD4 KL 8;
	Goto FallingAfterImpact;
		
		
	Pain.Kick:
	Pain.ExtremePunches:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		IZD4 K 1 A_Pain();
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain");
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		ID11 E 1;// A_Chase(null,null)
		IZD4 K 1 A_facetarget();
		IZD4 K 6 ThrustThing(angle*256/360+128, 5, 0, 0);
		IZD4 L 8;
	Goto FallingAfterImpact;
		
		
	PainCanFallFromCeiling:
		TNT1 A 0 {self.bNOGRAVITY = false; self.bTHRUSPECIES = false; self.bCEILINGHUGGER = false;}
		TNT1 A 0 { self.on_ceiling = false;}

	FallingAfterImpact:
		IZD4 L 1 A_GiveInventory("FallingHeight", 1);
		TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim");
		TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim");
		IZD4 L 1 A_CheckFloor("GetUp");
		TNT1 A 0 A_JumpIf(vel.z == 0, "GetUp");
	Loop;
		
	GetUp:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("LargeMassWaterImpact");
		TNT1 A 0 A_SpawnItem("Underwater_Explosion");
		TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim");
		TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim");
		TNT1 A 0 {self.bGHOST = true;}
		TNT1 A 0 {self.bNOPAIN = false;}
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 {self.bFORCEXYBILLBOARD = true;}
		TNT1 A 0 A_GiveInventory("ISDOWN", 1);
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 8, "FallingDie");
		IZD4 MMMMMMMM 5 A_JumpIf(vel.z < 0, "FallingAfterImpact");
		TNT1 A 0 {self.bSOLID = true;}
		TNT1 A 0 A_TakeInventory("ISDOWN", 1);
		TNT1 A 0 {self.bFORCEXYBILLBOARD = false;}
		TNT1 A 0 A_TakeInventory("FallingHeight", 100);
		TNT1 A 0 A_TakeInventory("ISDOWN", 1);
		IZD4 NO 7;
	Goto see;
		
		
	FallingDie:
		TNT1 A 0;
		TNT1 A 0 {self.bSHOOTABLE = false;}//
		TNT1 A 0 {self.bCOUNTKILL = false;}
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 30, "Death.Stomp");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 20, "FallingSuperDeath");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 6, "FallingDeath");
	FallingDeath:
	Death.FellFromALongFall:
		TNT1 A 0;
		TROO M 1;
		TNT1 A 1;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("DeadImp1");
		//TROO M -1
	stop;

	FallingSuperDeath:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	Goto Death.ExplosiveImpact+1;
		
	PainHurt:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TROO H 1;
		TROO H 1 A_Pain();
	Goto see;

	Pain.Avoid:
		TNT1 A 0
		{
			int direct = randompick(90, -90);//choose left or right
			self.vel.x = cos(self.angle + direct) * 10;
			self.vel.y = sin(self.angle + direct) * 10;
			self.vel.z = 5;
		}
		TROO NNNOOO 2 A_FaceTarget();
	Goto Missile+26;

		
	Pain.BlackHole:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		IZD4 K 1 A_Pain();
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,6,0,1);
		IZD4 K 1 A_facetarget();
		IZD4 K 6 ThrustThing(angle*256/360+128, 5, 0, 0);
		IZD4 L 8;
	Goto FallingAfterImpact;
		
	Death.Shotgun:
		TNT1 A 0 {self.bSLIDESONWALLS = false;}
		TNT1 A 0 A_Jump(42, "Death.Shotgunontheface");
		TNT1 A 0 A_JumpIfCloser(80, "Death.Blast");
		TNT1 A 0 A_JumpIfCloser(320, "Death.Shotgunontheface");
	Goto Death;
		
	Death.Shotgunontheface:
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Jump(128, "DeathJump");
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 A_Jump(32, "Death.ARm");
		TNT1 A 0 A_Jump(96, "DeathNoGuts");
		TNT1 A 0 A_Jump(128, "DeathShotgunontheface2");
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_Pain();
		TROO H 1 A_FaceTarget();
		TNT1 A 0 A_Recoil(13);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		TNT1 A 0 A_Scream();
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AA 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		TR06 ABCDE 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TR06 FGHIJK 4 A_JumpIf((vel.Y == 0), "DSFStop");
	Goto DSFStop+1;
		
	DSFStop:
		//TNT1 A 0 A_Explode(20,30, 0);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 a_spawnprojectile("SuperWallRedBlood", 2, 0, random(170, 190), 2, random(0, 0));
		TNT1 A 0 A_SpawnItem("DeadImpTR06K");
	stop;

	DeathShotgunontheface2:
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_Pain();
		TROO H 1 A_FaceTarget();
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_Recoil(13);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AA 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		TR06 LMNO 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TR06 QRSTU 4 A_JumpIf((vel.Y == 0), "DSFStop2");
	Goto DSFStop2+1;
		
	DSFStop2:
		//TNT1 A 0 A_Explode(20,30, 0);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 a_spawnprojectile("SuperWallRedBlood", 2, 0, random(170, 190), 2, random(0, 0));
		TNT1 A 0 A_SpawnItem("DeadImpTR06V");
	stop;	Death.MinorLeg:
		TNT1 A 0;
		TNT1 A 0 A_Jump(48, "Death.Leg");
	Goto Death+5;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false; self.bTHRUSPECIES = false; self.bCEILINGHUGGER = false;}
		TNT1 A 0 {if(self.ceiling_jump == true ) { setstatelabel("DeathJump");} }
		TNT1 A 0 A_Jump(32, "Death.Arm");
		TNT1 A 0 A_Jump(24,"DeathNoGuts");
		TNT1 A 0 A_Jump(32,"Myocardial_infarction");
		TNT1 A 0 A_Jump(128, "DeathMirror");
		TR97 A 8;
		TR97 B 8 A_Scream();
		TR97 C 6;
		TR97 D 6 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadImp1");
	stop;

	Death.Down:
	Death.Trample:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Stop();
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 2, 0, random(0, 360), 2, random(0, 40));
		ID11 DC 6;
		TNT1 A 0 A_SpawnItem("DeadImp1");
	stop;		

		
		
	Death.Arm:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 a_spawnprojectile("XDeathImpArm", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Jump(110, "Arm2");
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TR08 A 8 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 A_SpawnItem("DyingImpNoArm", 2);
	stop;		
	Arm2:
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		T408 A 8 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 A_SpawnItem("DyingImpNoArm2", 2);
	stop;		
	Death.Leg:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false; self.bTHRUSPECIES = false; self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Jump(64, "DeathLeg2");
		TNT1 A 0 {if( self.ceiling_jump == true ) { setstatelabel("Death.LegInTheAir");} }
		TNT1 A 0 a_spawnprojectile("XDeathImpLeg", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TR09 A 9;
		TR09 A 3 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TR09 B 3 A_Scream();
		TR09 C 3 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("DyingImpNoLeg", 5);
	stop;		
	DeathLeg2:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Fall();
		TNT1 A 0 a_spawnprojectile("XDeathImpLeg", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		//TNT1 A 0 A_SpawnItem("ImpSaciLol");
	stop;		
		
		
	DeathJump:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Stop();
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 {self.bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(10);
		ID11 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		ID11 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		ID11 B 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		ID11 B 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		ID11 C 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		ID11 C 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		ID11 D 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		ID11 D 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadImp1");
	stop;		
	
	TakeASit:
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		ID11 B 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItemEx("DeadImp_Slumped", 10);
	stop;		
		
	Death.Nailgun:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 {self.bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,random(22,30),0,1);
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(30);
		ID11 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		ID11 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		ID11 B 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		ID11 B 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		ID11 C 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		ID11 C 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		ID11 D 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		ID11 D 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadImp1");
	stop;	PinToWall:
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AA 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_PlaySound("Weapons/NailHitBleed", 6);
		PIN6 A 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItemEx("DeadImp_Pinned", 10, 0, 10);
	stop;		
		
	Death.Melee:
		//TNT1 A 0 A_JumpIfInventory("SKImp", 1, "StealthKill");
	Death.Kick: 
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(8);
		ID30 ABCD 8;
		TNT1 A 1 A_SpawnItem("DeadImp1MeleeDeath", 5);
	stop;		
		

	HeadExploder:
		TNT1 A 0;
		TNT1 A 0 A_Jump(72, "Death.HeadExplode");
	Goto Death.HeadMinor;
		
	Death.head:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		//TNT1 A 0 A_JumpIfIntargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		//TNT1 A 0 A_JumpIfIntargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
		//TNT1 A 0 A_JumpIfIntargetInventory("HasCutingWeapon", 1, "Death.Decaptate");
		TNT1 A 0 A_JumpIfHealthLower(-50, "Death.HeadExplode");
		//TNT1 A 0 A_JumpIfIntargetInventory("RandomHeadExploder", 1, "HeadExploder");
	Death.HeadMinor:
		TNT1 A 0;
		TNT1 A 0 A_Playsound("MinorHeadshot", 0);
		TNT1 AA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160))
		TNT1 AA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_Jump(150, "MinorHead1", "MinorHead2");
		TROH K 9 A_NoBlocking();
		TROH L 9 A_Scream();
		TROH M 8;
		TROH N 8;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadImp_MinorHeadDeadFront");
	stop;		
	MinorHead1:
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		T6SW A 8 A_NoBlocking();
		T6SW B 8 A_XScream();
		T6SW C 8;
		T6SW DDD 2 a_spawnprojectile("Brutal_LiquidBlood2", 25, 0, random(0, 360), 2, random(60, 120));
		T6SW E 2 A_Scream();
		T6SW EEEDDD 2 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(60, 120));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		T6SW F 6;
		TNT1 A 0 A_SpawnItem("DeadImpT6SWG");
	stop;		
	MinorHead2:
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		T6SW H 8 A_NoBlocking();
		T6SW I 8 A_XScream();
		T6SW J 8;
		T6SW KKK 2 a_spawnprojectile("Brutal_LiquidBlood2", 25, 0, random(0, 360), 2, random(60, 120));
		T6SW L 2 A_Scream();
		T6SW LLLKKK 2 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(60, 120));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		T6SW M 6;
		TNT1 A 0 A_SpawnItem("DeadImpT6SWn");
	stop;


	
		
		
	DeathMirror:
		TROO V 9;
		TROO W 9 A_Scream();
		TROO X 8 A_NoBlocking();
		TROO Y 8;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadImpTROOY");
	stop;

	Death.decaptate:
		TNT1 AAAAAAAAA 0 a_spawnprojectile("Blood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 a_spawnprojectile("XDeathImpHeadBeheaded", 50, 0, random(0, 360), 2, random(40, 90));
		TROH A 9;
		TROH B 9 A_XScream();
		TROH C 8 A_NoBlocking();
		TROH DE 8;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadImp_NoHead");
	stop;

	Death.cut:
	Death.HKFT:
	Death.Saw:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Jump(48, "Death.Arm", "Death");
		TNT1 A 0 A_Jump(32,"DeathNoGuts");
	Goto Death.Tear;
		
		
		
		
		
	Death.cutless:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Death.Down");
		TNT1 A 0 A_Jump(42,"DeathNoGuts");
		TNT1 A 0 A_Jump(16, "Death");
		TNT1 A 0 A_Jump(16, "Death.LegMassacre");
	Goto Death.Minigun;
		
	Death.Minigun:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Scream();
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 A_Jump(128, "DeathMinigun2");
		//TNT1 A 0 A_SpawnItem("BrutalizedImp1", 1);
	stop;
	
	DeathMinigun2:
		TNT1 A 0;
		//TNT1 A 0 A_SpawnItem("BrutalizedImp4", 1);
	stop;
	
	Death.LegMassacre:
		TNT1 A 0 a_spawnprojectile("XDeathImpLeg", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TR09 A 8 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TR09 B 8 A_Scream();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("ImpBrutalizedWithNoLeg");
	stop;		

	Death.Tear:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Jump(128, "Tear2", "Tear3", "Tear4");
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TROG A 2 a_spawnprojectile("RipImp", 0, 0, random(0, 360), 2, random(0, 160));
		TROG AAA 4 {pb_blood_and_gore_event.big_blood(self);}
		TROG BCDEFGH 8;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 1 A_SpawnItem("DeadImp_Half", 5);
	stop;		
	Tear2:
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		T5SW A 3;
		T5SW A 1 A_PlaySound("misc/xdeath4f", 9);
		T5SW BBB 2 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		T5SW CCC 2 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AA 0 a_spawnprojectile("XDeath2", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath5", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("xdeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("xdeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("LivingHeart", 32, 0, random(170, 190), 2, random(0, 40));
		T5SW DDD 2 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		T5SW EEE 2 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		T5SW FFF 2 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		T5SW GGG 2 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadImpT5SWG");
	stop;

	Tear3:
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		IXD1 ABC 4  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AA 0 a_spawnprojectile("xdeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("xdeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("LivingHeart", 32, 0, random(170, 190), 2, random(0, 40));
		IXD1 DDDDDDDDDD 1 a_spawnprojectile("Brutal_LiquidBlood2", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("RipImp", 0, 0, random(0, 360), 2, random(0, 160));
		IXD1 EEEEEEEEEE 1 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(0, 160));
		IXD1 FFFFFFFFFF 1 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 8, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 8, 0, random(150, 210), 2, random(0, 40));
		IXD1 GGGGGGGG 1 a_spawnprojectile("Brutal_LiquidBlood2", 9, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		IXD1 HHHHHHHHHHHHH 1 a_spawnprojectile("Brutal_LiquidBlood2", 6, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadImpIXD1H");
	stop;

	Tear4:
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		TNT1 AA 0 a_spawnprojectile("xdeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("LivingHeart", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("RipImp", 0, 0, random(0, 360), 2, random(0, 160));
		IXD4 AAAABBBBCCCCDDDD 1 a_spawnprojectile("Brutal_LiquidBlood2", 35, 0, random(0, 360), 2, random(0, 160));
		
		IXD4 DEFEDEFGFGEFGEFG 2
		{
			a_spawnprojectile("Brutal_LiquidBlood2", 32, 0, random(0, 360), 2, random(0, 160));
			a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
			a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		}
		IXD4 HHHH 1 a_spawnprojectile("Brutal_LiquidBlood2", 32, 0, random(0, 360), 2, random(0, 160));
		IXD4 IIIII 1 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(0, 160));
		IXD4 JJJJJ 1 a_spawnprojectile("Brutal_LiquidBlood2", 22, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		IXD4 KKKKKKKKKK 1 a_spawnprojectile("Brutal_LiquidBlood2", 19, 0, random(0, 360), 2, random(0, 160));
		IXD4 LLLLLL 1 a_spawnprojectile("Brutal_LiquidBlood2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadImpIXD4L");
	stop;

	DeathNoGuts:
		TNT1 AAAAA 0;
		TNT1 A 0 A_Jump(120, "DeathNoGuts2");
		TNT1 AA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AA 0 a_spawnprojectile("XDeath1", 30, 0, random(0, 360), 2, random(0, 160));
		IMPC A 8 A_Scream();
		IMPC B 8 A_NoBlocking();
		IMPC C 8;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem("DyingImp", 2);
	stop;	DeathNoGuts2:
		TNT1 AAA 0 a_spawnprojectile("Instestin", 28, 0, random(150, 210), 2, random(0, 40));
		I9PC C 8;
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AA 0 a_spawnprojectile("XDeath1", 30, 0, random(0, 360), 2, random(0, 160));
		I9PC D 8 A_Scream();
		I9PC E 8 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem("DyingImp2", 2);
	stop;


	
	
	Death.Blast:
	Death.Railgun:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Jump(12, "Death.Arm");
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Jump(128, "Death.Blast2", "DeathBlast3");
		TNT1 A 0 A_XScream();
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathImpArm", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathImpHead", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		TR03 A 6 A_Stop();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TR03 BBBBBBBBBB 3 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(30, 60));
		TR03 CCC 3 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(10, 40));
		TR03 DD 3 a_spawnprojectile("Brutal_LiquidBlood2", 6, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_SpawnItem("DeadImpTR03E");
	Stop;
	
	Death.Blast2:
		TNT1 A 0 A_XScream();
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathImpArm", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathImpHead", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		TR04 A 6 A_Stop();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TR04 BBBBBBBBBB 3 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(30, 60));
		TR04 CCC 3 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(10, 40));
		TR04 DD 3 a_spawnprojectile("Brutal_LiquidBlood2", 6, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_SpawnItem("DeadImpTR04E");
	Stop;
	
	DeathBlast3:
		TNT1 A 0 A_xScream();
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TR04 F 6 A_Stop();
		TR04 G 2 A_Scream();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TR04 GGGG 2 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(30, 60));
		TR04 H 3 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(10, 40));
		TR04 I 3 a_spawnprojectile("Brutal_LiquidBlood2", 6, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_SpawnItem("DeadImpTR04J");
	Stop;
	
	Death.SSG:
	Death.SuperPunch:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		IZD1 E 1 A_Pain();
		IZD1 E 1 A_FaceTarget();
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AAA 0 bright a_spawnprojectile("SuperGoreSpawner", 35, 0, random(170, 190), 2, random(0, 40));
		//TNT1 A 0 a_spawnprojectile("MeatDeath", 0, 0, random(0, 360), 2, random(0, 160))
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 AA 0 a_spawnprojectile("XDeathImpArm", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathImpHead", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		IZD1 EEFFGH 6;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadImpJustLegsAreLeft");
	Stop;
	
	Death.Explosive:
		TNT1 A 1 A_FaceTarget();
		//TNT1 A 1 A_JumpIfInTargetInventory("RocketLauncherSelected", 1, "RocketMan");
		XDeath:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		//TNT1 A 0 A_JumpIfIntargetInventory("SSGSelected", 1, "Death.SSG");
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_FaceTarget();
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 A 0 a_spawnprojectile("XDeath2", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 A 0 a_spawnprojectile("XDeath4", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 A 1 a_spawnprojectile("ImpXDeath", 0, 0, random(0, 360), 2, random(0, 160));
	Stop;
	
	RocketMan:
//		TNT1 A 0 A_JumpIfCloser(800, "RocketImp");
	Goto XDeath;
	
	RocketImp:
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 1 a_spawnprojectile("RocketImpVictim", 15, 0, 180, 2, 0);
	stop;
	
	Death.ExplosiveImpact:
	Death.ExtremePunches:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_XScream();
		TNT1 A 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 A_Jump(96,"Death.LandMine");
		
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(20, 90));
		TNT1 A 0 a_spawnprojectile("XDeathImpArm", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathImpLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		ID17 AB 5;
		ID17 CDEF 5 A_CheckFloor("Dead.ExplosiveImpact");
		ID17 EEEEEEEEEE 5 A_CheckFloor("Dead.ExplosiveImpact");
		TNT1 A 0 A_SpawnItem("DeadImpID17G");
	Stop;
	
	Dead.ExplosiveImpact:
		TNT1 A 0 A_Jump(128, "Dead.ExplosiveImpact2");
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem("ThisImpGotFuckedHard");
		//TNT1 A 0 A_SpawnItem("Ploft");
		TNT1 AAAA 0 A_SpawnItem("Blood");
	Stop;
	
	Dead.ExplosiveImpact2:
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem("ThisImpGotFuckedHard2");
		//TNT1 A 0 A_SpawnItem("Ploft");
		TNT1 AAAA 0 A_SpawnItem("Blood");
	Stop;
	
	
	Death.Landmine:
	Death.LandMine2:
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 ThrustThingZ(0,15,0,1);
		Death.LegInTheAir:
		TNT1 A 0 ThrustThingZ(0,35,0,1);
		TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathImpLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		
		ID13 A 1 A_Scream();
		ID17 HI 4;
		ID17 JKLMN 4 A_CheckFloor("Dead.Landmine");
		ID17 NNNNNNNN 4 A_CheckFloor("Dead.Landmine");
		TNT1 A 0 A_SpawnItem("DeadImp_NoLeg");
	Stop;
	
	Dead.Landmine:
		TNT1 O 0 A_NoBlocking();
		TR09 E 1;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem("Ploft");
		TNT1 AAAA 0 A_SpawnItem("Blood");
		TNT1 A 0 A_SpawnItem("DeadImp_NoLeg");
	Stop;
	
	Raise:
		TROO MLKJI 8;
	Goto See;
	
	Crush:
	Death.Stomp:
		TNT1 A 0;
		TNT1 A 0;//A_DamageSelf(1, "Stomp", DMSS_KILL)
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail8", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AAAAAA 0 bright a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright a_spawnprojectile("XDeath2", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright a_spawnprojectile("XDeath3", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("CrushedRemains");
		TNT1 A 1 A_XScream();
		TNT1 A 1 A_NoBlocking();
	Stop;
	
	FatalityMarine:
		TNT1 A 0 A_SetInvulnerable();
		IPFP ABCD 4;
		TNT1 A 0 A_SpawnItemEx("FootStep5", 0, 0, 40, 0, 0);
		IPFP EE 6;
		IPFP F 8;
		TNT1 A 0 A_PlaySound("DSFDTHE");
		IPFP G 8;
		TNT1 AA 0 a_spawnprojectile("XDeath1", 1, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("PlayerFlyingBlood", 25, 0, random(0, 360), 2, random(0, 160));
		IPFP H 8;
		IPFP I 8;
		TNT1 AA 0 a_spawnprojectile("XDeath1", 1, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("PlayerFlyingBlood", 25, 0, random(0, 360), 2, random(0, 160));
		IPFP J 8;
		IPFP K 8;
		TNT1 AA 0 a_spawnprojectile("XDeath1", 1, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("PlayerFlyingBlood", 25, 0, random(0, 360), 2, random(0, 160));
		IPFP H 8;
		IPFP I 8;
		TNT1 AA 0 a_spawnprojectile("XDeath1", 1, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("PlayerFlyingBlood", 25, 0, random(0, 360), 2, random(0, 160));
		IPFP J 8;
		IPFP K 8;
		TNT1 AA 0 a_spawnprojectile("XDeath1", 1, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("PlayerFlyingBlood", 25, 0, random(0, 360), 2, random(0, 160));
		IPFP H 8;
		IPFP I 8;
		TNT1 AA 0 a_spawnprojectile("XDeath1", 1, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("PlayerFlyingBlood", 25, 0, random(0, 360), 2, random(0, 160));
		IPFP J 8;
		IPFP L 8;
		TNT1 AA 0 a_spawnprojectile("XDeath1", 1, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("PlayerFlyingBlood", 25, 0, random(0, 360), 2, random(0, 160));
		IPFP M 8;
		TNT1 A 0 a_spawnprojectile("Instestin", 12, 0, random(0, 360), 2, random(0, 40));
		IPFP N 8;
		TNT1 AA 0 a_spawnprojectile("XDeath1", 1, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("PlayerFlyingBlood", 25, 0, random(0, 360), 2, random(0, 160));
		IPFP O 8;
		TNT1 A 0 a_spawnprojectile("Instestin", 12, 0, random(0, 360), 2, random(0, 40));
		IPFP L 8;
		TNT1 AA 0 a_spawnprojectile("XDeath1", 1, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("PlayerFlyingBlood", 25, 0, random(0, 360), 2, random(0, 160));
		IPFP M 8;
		TNT1 A 0 a_spawnprojectile("Instestin", 12, 0, random(0, 360), 2, random(0, 40));
		IPFP N 8;
		TNT1 AA 0 a_spawnprojectile("XDeath1", 1, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("PlayerFlyingBlood", 25, 0, random(0, 360), 2, random(0, 160));
		IPFP O 8;
		TNT1 A 0 a_spawnprojectile("Instestin", 12, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_UnSetInvulnerable();
		//TNT1 A 0 A_SpawnItem("MarineGotOwnedByImp", 1);
	Goto See;
	
	StealthKill:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfIntargetInventory("FistsSelected", 1, 1);
	Goto Death;
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("SKImp", 1);
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Fall();
		TNT1 A 1;
		TNT1 A 0 A_Die("Stealthy");
		TNT1 A 1;
	Stop;
	Death.Stealthy:
		TNT1 A 0;
	Stop;
	
	Swim:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Fall();
		//TNT1 A 0 A_SpawnItem("ImpFish");
	Stop;
	
}

}
