CLASS pb_Arachnophyte : proto_spider// replaces Arachnotron
{ 
Default
{		
	Health 625;
	Radius 52;
	Height 56;
	Speed 6;
	PainChance 15;
	Mass 5000;
	MONSTER;
	//SpawnID 1630;
	+NOGRAVITY;
	-FLOATBOB;
	-FLOAT;
	+NORADIUSDMG;
	+DONTHARMSPECIES;
	+DONTHARMCLASS;
	Species "Arachnotron";
	SeeSound "arachnophyte/sight";
	PainSound "arachnophyte/pain";
	DeathSound "arachnophyte/death";
	AttackSound "spider/attack";
	Obituary "%o was perforated by an Arachnophyte.";
	DamageFactor "Crush", 10.0;
	DamageFactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	DamageFactor "Saw", 0.6;
	BloodType "Brutal_Blood", "BloodSPlatterReplacer", "Brutal_Blood";
	MaxStepHeight 24;
	MaxDropOffHeight 24;
	PainChance "Kick", 255;
	Damage 25;
	Scale 1.15;
	Explosiondamage 128;
	Explosionradius 255;

/*	//DropItem "Berserker", 5;
	//DropItem "DemonStrengthRune", 1;
	//DropItem "Demonpickup2", 255;
	//DropItem "Demonpickup", 95;
	//DropItem "Demonpickup", 85;*/
	
	PainChance "Stun", 255;
}

States
{
	Spawn:
		MARP Z 7 A_Look;
	loop;

	See:
		TNT1 A 0 A_Playsound("cbaron/metal");
		MARP Z 2 A_PlaySound("arachnophyte/engine",6, 1, 1);
		TNT1 A 0 {self.bFLOAT = true;}
		MARP BAB 2
		{
			ThrustThingZ(0,3,0,0);
			A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		}
	SeeContinue:
		MARP AB 2 Bright
		{
			A_Chase();
			A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		}
	Loop;



	Missile:
	PrepareToFirePlasma:
		TNT1 A 0 A_PlaySound("BMCHARG");
		MARP ABABAB 2 Bright
		{
			A_FaceTarget();
			A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		}
	FirePlasma:
		MARP CDCD 2 BRIGHT
		{
			if(frame == 2) {a_spawnprojectile("RedPlasmaBall",25,0,0,0); A_FaceTarget();}
			A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		}
		TNT1 A 0 A_JumpIfInTargetLOS("FirePlasma", 0, JLOSF_DEADNOJUMP);
	Goto SeeContinue;
		
	Missile2:
		TNT1 A 0 A_PlaySound("DTHDLRST");
		MARP ABABAB 2 Bright
		{
			A_FaceTarget();
			A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		}
	FireMachineGun:
		MARP KLKLKLKL 3 BRIGHT
		{
			A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
			A_FaceTarget();
			a_spawnprojectile("YellowFlareSmall",12,-5,0,0);
			a_spawnprojectile("YellowFlareSmall",12, 5,0,0);
			a_spawnprojectile("ArachnophyteTracer",12, 5,random(-3,3),0);
			a_spawnprojectile("ArachnophyteTracer",12,-5,random(-3,3),0);
			a_spawnprojectile("ArachnophyteTracer",12, 5,random(-3,3),0);
			a_spawnprojectile("BigEmptyCaseSpawn",12, 5,random(-3,3),0);
		}
		TNT1 A 0 A_Jump(4, "SeeContinue", "PrepareToFirePlasma");
		TNT1 A 0 A_JumpIfInTargetLOS("FireMachineGun", 0, JLOSF_DEADNOJUMP);
	Goto SeeContinue;



























	Death.Blackhole:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));		
		ID67 AAABCDEFGHIJK 4;
		TNT1 A 0 A_StopSound(2);
	Stop;


		
		//Brutal Counters are used so the chaingun attack isn't too OP

		
		
	Pain:
		MARP E 1 A_Pain;
		MARP EEE 2 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
	Goto SeeContinue;
		
	Pain.Avoid: 
		MARP C 1 A_FaceTarget;
		TNT1 A 0 ThrustThing(angle*256/360 + randompick(192, 64), 8, 0, 0);
		MARP C 5 A_FaceTarget;
	Goto Missile;

	Possession:
		TNT1 A 0 A_SetInvulnerable;
		MARP E 3;
		MARP E 3 A_Pain;
 		TNT1 A 0 A_UnSetInvulnerable;
	Goto See;
		
	Death.Fatality:
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_BossDeath;
		//TNT1 A 0 A_GiveToTarget("ArachnophyteFatality", 1);
	Stop;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 {self.bFLOATBOB = false;}
		TNT1 A 0 A_Jump(148, "GenericDeath");
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_StopSound(6);
		TNT1 A 0 A_Fall;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0
		{
			for(int i = 0; i < 4; i++)
			{
				A_PlaySound("FAREXPL");
				A_PlaySound("Explosion", 1);
				a_spawnprojectile("CasingSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
			}
		}
		TNT1 A 0 A_Playsound("Explosion");
		TNT1 AAAAAAAAA 0 a_spawnprojectile("MetalShard1", 5, 0, random(0, 360), 2, random(30, 160));
		TNT1 AA 0 a_spawnprojectile("SpiderPart1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSpiderPart5", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSpiderPart6", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSpiderPart4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece", random(-35, 35), random(-35, 35));
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece", random(-45, 45), random(-45, 35));
		TNT1 A 0 a_spawnprojectile("CoolandNewFlameTrails", 40, 0, random(0, 360), 2, random(50, 130));
		MARP S 12;
		MARP T 11;
		MARP U 10 A_BossDeath;
		MARP VVVVVVVVVVVVVVVVVVVVVVVVVV 7 a_spawnprojectile("ExplosionSmoke", 15, 0, random(0, 360), 2, random(70, 110));
		MARP V -1;
	Stop;
		
		
	Death.Cut:
	Death.Saw:
	Death.Tear:
		TNT1 AAAAA 0 a_spawnprojectile("Instestin2", 14, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("CeilBloodSpot", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 AAAAA 0 a_spawnprojectile("XDeath1", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("XDeath2", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathArachnotronHead3", 50, 0, random(0, 360), 2, random(40, 130));
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 {self.bFLOATBOB = false;}
		ARF7 L 2 A_BossDeath;
		TNT1 A 0 A_Fall;
		TNT1 A 0 A_SpawnItemEx("ArachnophyteFrame",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	Stop;
		
	Death.Plasma:
	Death.SuperPlasma:
	Death.Desintegrate:
	GenericDeath:
	XDeath:
	Death.ExplosiveImpact:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 {self.bFLOATBOB = false;}
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0
		{
			for(int i = 0; i < 2; i++)
			{
				A_PlaySound("FAREXPL");
				A_PlaySound("Explosion", 1);
				a_spawnprojectile("CasingSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
			}
		}
		TNT1 A 0 a_spawnprojectile("NewRocketExploFX", 0, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 ThrustThing(angle*random(0, 360), 12, 0, 0);
		TNT1 A 0 ThrustThingZ(0,random(-10, 10),0,1);
		TNT1 A 0 a_spawnprojectile("CoolandNewFlameTrails", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 
		{
			pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");
		}
		TNT1 A 0 A_Playsound("Explosion");
		TNT1 A 0 a_spawnprojectile("XDeathSpiderPart1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SpiderPart1", 32, 0, random(0, 360), 2, random(0, 160));
		tnt1 a 0 A_StopSound(6);
		MARP EFGHIJQR 3
		{
			ThrustThing(angle*random(0, 360), 12, 0, 0);
			ThrustThingZ(0,random(-10, 10),0,1);
			a_spawnprojectile("CoolandNewFlameTrails", 40, 0, random(0, 360), 2, random(50, 130));
			pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");
		}
		TNT1 A 0 A_PlaySound("excavator/explode");
		TNT1 A 0 a_spawnprojectile("BigRicoChet");
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -30);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		//TNT1 AAA 0 a_spawnprojectile("FireworkSFXType1", 32, 0, random(0, 360), 2, random(30, 60));
		//TNT1 A 0 A_SpawnItemEx("NewRocketExploFX", 15, 0, 20);
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece", random(-35, 35), random(-35, 35));
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece", random(-45, 45), random(-45, 35));
		TNT1 A 0 A_Jump(180, 2);
		TNT1 A 0 a_spawnprojectile("XDeathArachnotronHead3", 50, 0, random(0, 360), 2, random(40, 130));
		TNT1 A 0;
		MARP R 1 A_BossDeath;
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAA 0 {pb_blood_and_gore_event.gore_spawner_2(self);}
		TNT1 AAAA 0 a_spawnprojectile("PEPart2SuperFast", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("SpiderPart1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSpiderPart2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSpiderPart3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathSpiderPart5", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSpiderPart6", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSpiderPart4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_Jump(127, 47);
		MARP Y 1 A_Fall;
		MARP YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY 8 a_spawnprojectile("ExplosionSmoke", 15, 0, random(0, 360), 2, random(70, 110));
		MARP Y -1;
	Stop;
		TNT1 AAAAAAA 0;
		MARP X 1 A_Fall;
		MARP XXXXXXXXXXXXXXXXXXXXXXX 8 a_spawnprojectile("ExplosionSmoke", 15, 0, random(0, 360), 2, random(70, 110));
		MARP X -1;
	Stop;
		
	Death.Blast:
	Death.Nailgun:
		TNT1 A 0;
		TNT1 A 0 A_Jump(32, "Death.SSG", "DeathStrong");
	Goto GenericDeath;

	Death.Shotgun:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfCloser(250, 1);
	Goto Death;

	DeathStrong:
		TNT1 AA 0;
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("PEPart2SuperFast", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSpiderPart2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("XDeathSpiderPart3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 {self.bFLOATBOB = false;}
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Fall;
		TNT1 A 0 A_StopSound(6);
		MARP M 10 A_XScream;
		MARP N 10 A_Fall;
		MARP O 9;
		MARP P 1 A_BossDeath;
		MARP PPPPPPPPPPPPPPPPPPPPPPP 2 a_spawnprojectile("Brutal_LiquidBlood3", 13, 0, random(0, 360), 2, random(0, 160));
		MARP P -1;
		Stop;
	Death.SSG:
		TNT1 AAAAA 0 a_spawnprojectile("Instestin2", 14, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("CeilBloodSpot", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 AAAAA 0 a_spawnprojectile("XDeath1", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("XDeath2", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathArachnotronHead3", 50, 0, random(0, 360), 2, random(40, 130));
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 {self.bFLOATBOB = false;}
		ARF7 L 2 A_BossDeath;
		TNT1 A 0 A_Fall;
		TNT1 A 0 A_SpawnItemEx("ArachnophyteFrame",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		Stop;
		
}
}

