


CLASS CrawlingDyingSpider3 : ACTOR { 
Default {

	Radius 12;
	Height 24;
	Speed 9;
	Health 100;
	PainSound "SP_CRAWL";
	damagefactor "Kick", 0.1;
	damagefactor "Melee", 0.1;
	damagefactor "SuperPunch", 0.1;
	damagefactor "SuperKick", 0.1;
	damagefactor "Extremepunches", 0.1;
	PainChance "Kick", 255;
	PainChance "SuperKick", 255;
	PainChance "SuperPunch", 255;
	PainChance "Extremepunches", 255;
	PainChance 255;
	damagefactor "trample", 2.0;
	+SHOOTABLE;
	+FLOORCLIP;
	//+NOBLOCKMAP
	+LOOKALLAROUND;
	+FRIGHTENED;
	+SOLID;
}
States
{
	Spawn:
		AAHD B 1 A_Look;
	Goto See;
	See:
		AAHD ABCD 10 A_Chase;
		AAHD A 0 A_Pain;
		TNT1 A 0 A_SpawnItemEx("Brutal_FlyingBlood", 0, 0, 10, 0, 0);
		tnt1 a 0 a_jump(25, "gotodeath", "death");
		//TNT1 A 0 A_GiveInventory("DeathTimer1", 1);
		//TNT1 A 0 A_JumpIfInventory("DeathTimer1", 12, "GotoDeath");
	Loop;
	
	GotoDeath:
		TNT1 A 0;
		TNT1 A 0 {self.bNOPAIN = true;}
		AAHD EFGH 5;
		AAHD H -1;
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("SmallBrainPiece", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 10, 0, random(0, 360), 2, random(0, 160));
		AAHD IJKLMN 5;
		AAHD N -5;
	Stop;

	Pain.SuperPunch:
	Pain.SuperKick:
	Pain.Kick:
	Pain.Extremepunches:
		TNT1 A 0 A_FaceTarget;
		AAHD A 1 A_Pain;
		TNT1 A 0 ThrustThing(angle*256/360+128, 5, 0, 0);
	Pain.ExplosiveImpact:
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		AAHD A 2 A_FaceTarget;	
	Fly:
		AAHD ABCDEFGH 3 A_CheckFloor("See");
		tnt1 a 0 A_JumpIf(vel.z == 0, "See");
		TNT1 A 0;
	Loop;
	
}
}

CLASS ArachnophyteFrame : ACTOR { 
Default {
+NOTELEPORT;
+MOVEWITHSECTOR;
+CORPSE;
Scale 1.15;
}

States
{
	Spawn:
		ARF7 LLLLLLLLLLLLLLLLL 6 a_spawnprojectile("ExplosionSmoke", 22, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0 a_spawnprojectile("ShoqueAzul", 20, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0
		{
			A_PlaySound("Sparks/Spawn");
			for(int i = 0; i < 30; i++)
			{a_spawnprojectile("pb_Spark", 0.0, 0, random(0, 360), 2, random(67, 113));}
		}
		ARF7 LLLLLL 6 a_spawnprojectile("ExplosionSmoke", 22, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0 a_spawnprojectile("ShoqueAzul", 20, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0
		{
			A_PlaySound("Sparks/Spawn");
			for(int i = 0; i < 30; i++)
			{a_spawnprojectile("pb_Spark", 0.0, 0, random(0, 360), 2, random(67, 113));}
		}
		ARF7 LLLLLLLLLLLLLLLLLLL 6 a_spawnprojectile("ExplosionSmoke", 22, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0 a_spawnprojectile("ShoqueAzul", 20, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0
		{
			A_PlaySound("Sparks/Spawn");
			for(int i = 0; i < 30; i++)
			{a_spawnprojectile("pb_Spark", 0.0, 0, random(0, 360), 2, random(67, 113));}
		}
		ARF7 LLLLLLLLLLLLLLLL 6 a_spawnprojectile("ExplosionSmoke", 22, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0 a_spawnprojectile("ShoqueAzul", 20, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0
		{
			A_PlaySound("Sparks/Spawn");
			for(int i = 0; i < 30; i++)
			{a_spawnprojectile("pb_Spark", 0.0, 0, random(0, 360), 2, random(67, 113));}
		}
		ARF7 LLLLLLLLLLLLLLLLLLLLLLL 6 a_spawnprojectile("ExplosionSmoke", 22, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0 a_spawnprojectile("ShoqueAzul", 20, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0
		{
			A_PlaySound("Sparks/Spawn");
			for(int i = 0; i < 30; i++)
			{a_spawnprojectile("pb_Spark", 0.0, 0, random(0, 360), 2, random(67, 113));}
		}
		ARF7 L -1;
	stop;
}
}

