CLASS Tall_Torch_Red : pb_torch_base//RedTorch replaces RedTorch
{ 
Default {
	height 85;
	radius 2;
	-SHOOTABLE;
	+INVULNERABLE;
	+NOBLOOD;
	+GHOST;
	+RANDOMIZE;
	Mass 0;
	scale .5;
}

states
{
	Spawn:
		TTRB A 0;
		TNT1 A 0 A_Playsound("BDFireplace2", 1, 0.25, 1);
		TNT1 A 1;
		TNT1 A 0 A_SPawnItem("TallTOrch_RedFlames");
		TNT1 A 1 A_SPawnItem("TallTOrch_RedCore");
	Stay:
		TTRB AAA 10 a_spawnprojectile ("torch_fire", 59, 0, random (0, 140), 2, random (0, 160));
		TTRB A 0 a_spawnprojectile ("RealisticFireSparks1", 70, 0, random (0, 140), 2, random (0, 160));
		Loop;
		
		
	Performance:
		TNT1 A 0 A_SetScale(1.0);
	PerformanceLoop:
		TRED ABCD 4 BRIGHT;
		Loop;
		
	}
}



CLASS TallTorch_RedFlames : pb_torch_base { 
	Default {
	
	XScale 1.0;
	YScale 1.2;
	Renderstyle "Add";
	Alpha 0.9;
	+CLIENTSIDEONLY;
	+THRUACTORS;
	}
	states
	{
	Spawn:
		TRKR ABCDEFGHIJKL 1 BRIGHT;
		Loop;
		
	}
}

CLASS TallTorch_RedCOre : pb_torch_base { 
	Default {
	
	XScale 0.5;
	YScale 0.3;
	}
	states
	{
	Spawn:
		TRKR MN 1 BRIGHT;
		Loop;
		
	}
}

CLASS TallTorch_Blue : pb_torch_base replaces BlueTorch { 
	Default {
	
	}
	states
	{
	
	Spawn:
		TTRB A 0;
		TNT1 A 0 A_Playsound("BDFireplace2", 1, 0.25, 1);
		//TNT1 A 0 ACS_NamedExecuteAlways("PerformanceMode", 0, 0, 0, 0);//Check Effects
		TNT1 A 1;
		TNT1 A 0 A_SPawnItem("TallTOrch_BlueFlames");
		TNT1 A 1 A_SPawnItem("TallTOrch_BlueCore");
		
	Stay:
		TTRB AAA 10 a_spawnprojectile ("torch_fire", 59, 0, random (0, 140), 2, random (0, 160));
		TTRB A 0 a_spawnprojectile ("RealisticFireSparks1Blue", 70, 0, random (0, 140), 2, random (0, 160));
		Loop;
		
	Performance:
		TNT1 A 0 A_SetScale(1.0);
	PerformanceLoop:
		TBLU ABCD 4 BRIGHT;
		Loop;
		
	}
}



CLASS TallTorch_BlueFlames : pb_torch_base { 
	Default {
	
	XScale 1.0;
	YScale 1.2;
	Renderstyle "Add";
	Alpha 0.9;
	+CLIENTSIDEONLY;
	+THRUACTORS;
	}
	states
	{
	Spawn:
		TRKB ABCDEFGHIJKL 1 BRIGHT;
		Loop;
		
	}
}

CLASS TallTorch_BlueCOre : pb_torch_base{ 
	Default {
	
	XScale 0.5;
	YScale 0.3;
	}
	states
	{
	Spawn:
		TRKB MN 1 BRIGHT;
		Loop;
		
	}
}

CLASS TallTorch_Green : pb_torch_base replaces GreenTorch { 
	Default {
	
	}
	states
	{
	
	Spawn:
		TTRB A 0;
		TNT1 A 0 A_Playsound("BDFireplace2", 1, 0.25, 1);
		//TNT1 A 0 A_SpawnItemEx("EvidenceCheckerGreenTorch", 0, 0, 0, 0, 0, 0, 0, SXF_NOCHECKPOSITION);
		//TNT1 A 0 ACS_NamedExecuteAlways("PerformanceMode", 0, 0, 0, 0);//Check Effects
		TNT1 A 1;
		TNT1 A 0 A_SPawnItem("TallTOrch_GreenFlames");
		TNT1 A 1 A_SPawnItem("TallTOrch_GreenCore");
		
	Stay:
		TTRB AAA 10 a_spawnprojectile ("torch_fire", 59, 0, random (0, 140), 2, random (0, 160));
		TTRB A 0 a_spawnprojectile ("RealisticFireSparks1Green", 70, 0, random (0, 140), 2, random (0, 160));
		Loop;
		
	Performance:
		TNT1 A 0 A_SetScale(1.0);
	PerformanceLoop:
		TGRN ABCD 4 BRIGHT;
		Loop;
		
	}
}



CLASS TallTorch_GreenFlames : pb_torch_base { 
	Default {
	
	XScale 1.0;
	YScale 1.2;
	Renderstyle "Add";
	Alpha 0.9;
	+CLIENTSIDEONLY;
	+THRUACTORS;
	}
	states
	{
	Spawn:
		TRKG ABCDEFGHIJKL 1 BRIGHT;
		Loop;
		
	}
}

CLASS TallTorch_GreenCore : pb_torch_base{ 
	Default {
	
	XScale 0.5;
	YScale 0.3;
	}
	states
	{
	Spawn:
		TRKG MN 1 BRIGHT;
		Loop;
		
	}
}

CLASS ShortTorch_Blue : ShortBlueTorch replaces ShortBlueTorch { 
	Default {
	
	+LOOKALLAROUND;
	-SHOOTABLE;
	+INVULNERABLE;
	+NOBLOOD;
	+GHOST;
	+RANDOMIZE;
	Mass 900000;
	height 80;
	radius 8;
	scale .4;
	}
	states
	{
	Spawn:
		TTRB A 0;
		TNT1 A 0 A_Playsound("BDFireplace2", 1, 0.25, 1);
		//TNT1 A 0 ACS_NamedExecuteAlways("PerformanceMode", 0, 0, 0, 0);//Check Effects
		TNT1 A 1;
		TNT1 A 0 A_SPawnItem("ShortTOrch_BlueFlames");
		TNT1 A 1 A_SPawnItem("ShortTOrch_BlueCore");
		
	Stay:
		STRB AAA 10 a_spawnprojectile ("torch_fire", 25, 0, random (0, 140), 2, random (0, 160));
		STRB A 0 a_spawnprojectile ("RealisticFireSparks1Blue", 40, 0, random (0, 140), 2, random (0, 160));
		Loop;
		
	Performance:
		TNT1 A 0 A_SetScale(1.0);
	PerformanceLoop:
		SMBT ABCD 4 BRIGHT;
		Loop;
	}
}



CLASS ShortTorch_BlueFlames : ShortTorch_Blue { 
	Default {
	
	XScale 1.0;
	YScale 1.2;
	Renderstyle "Add";
	Alpha 0.9;
	+CLIENTSIDEONLY;
	+THRUACTORS;
	}
	states
	{
	Spawn:
		SRKB ABCDEFGHIJKL 1 BRIGHT;
		Loop;
		
	}
}

CLASS ShortTorch_BlueCOre : ShortTorch_BlueFlames { 
	Default {
	
	XScale 0.5;
	YScale 0.3;
	}
	states
	{
	Spawn:
		SRKB MN 1 BRIGHT;
		Loop;
		
	}
}

CLASS ShortTorch_Red : ShortTorch_Blue replaces ShortRedTorch { 
	Default {
	
	}
	states
	{
	
	Spawn:
		TTRB A 0;
		TNT1 A 0 A_Playsound("BDFireplace2", 1, 0.25, 1);
		//TNT1 A 0 A_SpawnItemEx("EvidenceCheckerGreenTorch", 0, 0, 0, 0, 0, 0, 0, SXF_NOCHECKPOSITION);
		//TNT1 A 0 ACS_NamedExecuteAlways("PerformanceMode", 0, 0, 0, 0);//Check Effects
		TNT1 A 1;
		TNT1 A 0 A_SPawnItem("ShortTOrch_RedFlames");
		TNT1 A 1 A_SPawnItem("ShortTOrch_RedCore");
		
	Stay:
		STRB AAA 10 a_spawnprojectile ("torch_fire", 25, 0, random (0, 140), 2, random (0, 160));
		STRB A 0 a_spawnprojectile ("RealisticFireSparks1", 40, 0, random (0, 140), 2, random (0, 160));
		Loop;
		
	Performance:
		TNT1 A 0 A_SetScale(1.0);
	PerformanceLoop:
		SMRT ABCD 4 BRIGHT;
		Loop;
		
	}
}


CLASS ShortTorch_RedFlames : ShortTorch_Red { 
	Default {
	
	XScale 1.0;
	YScale 1.2;
	Renderstyle "Add";
	Alpha 0.9;
	+CLIENTSIDEONLY;
	+THRUACTORS;
	}
	states
	{
	Spawn:
		SRKR ABCDEFGHIJKL 1 BRIGHT;
		Loop;
		
	}
}

CLASS ShortTorch_RedCOre : ShortTorch_RedFlames { 
	Default {
	
	XScale 0.5;
	YScale 0.3;
	}
	states
	{
	Spawn:
		SRKR MN 1 BRIGHT;
		Loop;
		
	}
}

CLASS ShortTorch_Green : ShortTorch_Blue replaces ShortGreenTorch { 
	Default {
	
	}
	states
	{
	Spawn:
		TTRB A 0;
		TNT1 A 0 A_Playsound("BDFireplace2", 1, 0.25, 1);
		//TNT1 A 0 A_SpawnItemEx("EvidenceCheckerGreenTorch", 0, 0, 0, 0, 0, 0, 0, SXF_NOCHECKPOSITION);
		//TNT1 A 0 ACS_NamedExecuteAlways("PerformanceMode", 0, 0, 0, 0);//Check Effects
		TNT1 A 1;
		TNT1 A 0 A_SPawnItem("ShortTOrch_GreenFlames");
		TNT1 A 1 A_SPawnItem("ShortTOrch_GreenCore");
		
	Stay:
		STRB AAA 10 a_spawnprojectile ("torch_fire", 25, 0, random (0, 140), 2, random (0, 160));
		STRB A 0 a_spawnprojectile ("RealisticFireSparks1Green", 40, 0, random (0, 140), 2, random (0, 160));
		Loop;
		
	Performance:
		TNT1 A 0 A_SetScale(1.0);
	PerformanceLoop:
		SMGT ABCD 4 BRIGHT;
		Loop;
		
	}
}



CLASS ShortTorch_GreenFlames : ShortTorch_Red { 
	Default {
	
	XScale 1.0;
	YScale 1.2;
	Renderstyle "Add";
	Alpha 0.9;
	+CLIENTSIDEONLY;
	+THRUACTORS;
	}
	states
	{
	Spawn:
		SRKG ABCDEFGHIJKL 1 BRIGHT;
		Loop;
		
	}
}

CLASS ShortTorch_GreenCOre : ShortTorch_RedFlames { 
	Default {
	
	XScale 0.5;
	YScale 0.3;
	}
	states
	{
	Spawn:
		SRKG MN 1 BRIGHT;
		Loop;
		
	}
}

CLASS Candelabra1 : Candelabra replaces Candelabra { 
	Default {
	
	+LOOKALLAROUND;
	+INVULNERABLE;
	+NOBLOOD;
	+FORCEYBILLBOARD;
	+GHOST;
	Mass 900000;
	scale 0.7;
	}
	states
	{
	Spawn:
		TNT1 A 0;
	Stay:
		CBRA BCDE 1;
		Loop;
	Spawn2:
		CBRA A 7 bright;
		Goto Spawn;
		
		
	}
}

CLASS Performance_Candelabra : Candelabra { 
	Default {
	
	Mass 900000;
	scale 0.7;
	}
	States
	{
	Spawn:
		CBRA AABABABB 1 bright;
		Loop;
	}
}

CLASS Candlestick1 : Candlestick replaces Candlestick { 
	Default {
	
	+RANDOMIZE;
	scale .7;
	}
	states
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 ACS_NamedExecuteAlways("PerformanceMode", 0, 0, 0, 0);//Check Effects
	Stay:
		CAND A 25 bright A_SpawnItemEx ("CandleStick1Flare",0,0,5,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_Jump(128, "Stay2");
		
	Stay1:
		CAND BABABA 2 BRIGHT;
		CAND B 8 BRIGHT;
		CAND ABAB 2 BRIGHT;
		Loop;
		
	Stay2:
		CAND ABABAB 2 BRIGHT;
		CAND A 10 BRIGHT;
		CAND BABA 2 BRIGHT;
		Loop;
		
	Performance:
		TNT1 A 0 bright A_SpawnItem("Performance_Candlestick",0,0);
		Stop;
		
	}
}

CLASS Performance_Candlestick : Candlestick { 
	Default {
	
	scale .7;
	}
	States
	{
	Spawn:
		CAND AABABABB 1 bright;
		Loop;
	}
}

CLASS Candlestick1Flare : Candlestick { 
	Default {
	
	XScale 0.2;
	YScale 0.1;
	Renderstyle "Add";
	Alpha 0.8;
	+CLIENTSIDEONLY;
	+THRUACTORS;
	+Movewithsector;
	}
	states
	{
	Spawn:
		FSO1 AB 1;
		Loop;
		
	}
}

CLASS BurningBarrelTopFIre : pb_torch_base{ 
	Default {
	
	XScale -0.75;
	YScale 0.5;
	Alpha 1.0;
	Radius 0;
	Height 0;
	+NOGRAVITY;
	}
	states
	{
	Spawn:
		FLME ABCDEFGHIJKLMNABC 1 BRIGHT;
		Stop;
		
	}
}
/*
CLASS BurningBarrel1 : SwitchableDecoration replaces BurningBarrel { 
	Default {
	
	+LOOKALLAROUND;
	+SHOOTABLE;
	+NOBLOOD;
	+GHOST;
	+NOTARGET;
	+SOLID;
	height 25;
	Radius 16;
	ProjectilePassHeight -16;
	Health 30;
	DamageFactor "kick", 5.0;
	DamageFactor "SuperPunches", 5.0;
	Damagefactor "SuperKick", 5.0;
	DamageFactor "Fatality", 9.0;
	PainSound "barrel/pain";
	Scale 1.1;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	}
	states
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Playsound("BDFirePlace2", 1, 1, 1);
		TNT1 A 0 ACS_NamedExecuteAlways("PerformanceMode", 0, 0, 0, 0);//Check Effects
	Stay:
		TNT1 A 0 bright a_spawnprojectile ("BigBlackSmokePillar", 72, 0, random (40, 180), 2, random (60, 120));
		
		
		TTRB A 0 a_spawnprojectile ("RealisticFireSparks1", 44, 0, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("BurningBarrelTopFIre", 28, 0, random (40, 180), 2, random (50, 130));
		BURB ABCBA 2;//A_SpawnItem("Red_Flare",0,32)
		
		TTRB A 0 a_spawnprojectile ("RealisticFireSparks1", 44, 0, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("BurningBarrelTopFIre", 28, 0, random (40, 180), 2, random (50, 130));
		BURB ABCBA 2;//A_SpawnItem("Red_Flare",0,32)
		
		TTRB A 0 a_spawnprojectile ("RealisticFireSparks1", 44, 0, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("BurningBarrelTopFIre", 28, 0, random (40, 180), 2, random (50, 130));
		BURB ABCBA 2;//A_SpawnItem("Red_Flare",0,32)
		Loop;
		
	Spawn2:
		//TNT1 A 0 A_Playsound("BDFireplace2", 1, 0.25, 1)
		BURB A 1;
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 35, 0, random (0, 140), 2, random (0, 160));
		Goto Spawn;
		
	Performance:
		FCAN ABC 4 Bright;
		Loop;
		
	Death.Kick:
	Death.SuperKick:
	Death.ExtremePunches:
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_Changeflag("USESPECIAL", 0);
		BURB A 1 A_FaceTarget;
		BURB D 1 A_Recoil(3);
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_PlaySound("Afrit/Hellfire");
		TNT1 AAA 0 a_spawnprojectile ("FlyingBurningFuel", 24, 0, random (150, 210), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("FlyingBurningFuel", 24, 0, random (150, 210), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("FlyingBurningFuel", 24, 0, random (150, 210), 2, random (0, 40));
		BURB D -1;
		Stop;
		
	Death.Explosive:
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 a_spawnprojectile ("FlyingBurningFuel", 24, 0, random (0, 360), 2, random (30, 80));
		TNT1 AA 0 a_spawnprojectile ("FlyingBurningFuel", 24, 0, random (0, 360), 2, random (30, 80));
		TNT1 AA 0 a_spawnprojectile ("FlyingBurningFuel", 24, 0, random (0, 360), 2, random (30, 80));
		TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -15);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("BarrelExplosion",0,0,30,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("BarrelKaboom",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAAAAA 0 a_spawnprojectile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAA 0 a_spawnprojectile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAA 0 a_spawnprojectile ("BarrelShrapnel1", 25, 0, random (0, 360), 2, random (30, 160));
		TNT1 AAA 0 a_spawnprojectile ("BarrelShrapnel1", 15, 0, random (0, 360), 2, random (30, 160));
		TNT1 AAA 0 a_spawnprojectile ("BarrelShrapnel1", 5, 0, random (0, 360), 2, random (30, 160));
		TNT1 AAA 0 a_spawnprojectile ("BarrelShrapnel1", 5, 0, random (0, 360), 2, random (30, 160));
		Stop;
		
		
		
	Death.Fatality:
		TNT1 A 0 A_NoBlocking;
		//TNT1 A 0 A_GiveToTarget("GoSpecial", 1);
		//TNT1 A 0 A_GiveToTarget("HasBurningBarrel", 1);
		Stop;
		
	Active:
		BURB A 1 A_FaceTarget;
		//TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("CheckTraditional")==1,"Stay");
		//TNT1 A 0 A_JumpIfInTargetInventory("HasBarrel",1, "See");
		////TNT1 A 0 A_JumpIfInTargetInventory("HasBurningBarrel",1, "See");
		//TNT1 A 0 A_JumpIfInTargetInventory("PowerStrength",1, "GiveBarrel");
		Goto Stay;
	GiveBarrel:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_ChangeFlag("SHOOTABLE", 1);
		BURB A 1 A_FaceTarget;
		TTRB A 0 a_spawnprojectile ("RealisticFireSparks1", 44, 0, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("BurningBarrelTopFIre", 28, 0, random (40, 180), 2, random (50, 130));
		BURB ABCBA 2;
		TNT1 A 0 A_PlaySound("barrel/pain");
		Stop;
	}
}


CLASS BurningBarrelDamage : ACTOR { 
	Default {
	
	+NOTARGET;
	Radius 0;
	Height 0;
	DamageType "Fire";
	+NOGRAVITY;
	+NOTELEPORT;
	+NODAMAGETHRUST;
	+THRUGHOST;
	+NORADIUSDMG;
	+NOEXTREMEDEATH;
	+FORCERADIUSDMG;
	-BLOODSPLATTER;
	+BLOODLESSIMPACT;
	PROJECTILE;
	+DEHEXPLOSION;
	+ACTIVATEMCROSS;
	+NOTARGET;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 AA 5 A_Explode(5,25);
		Stop;
	}
}






*/

CLASS TorchFlare : ACTOR { 
	Default {
	
	+NOINTERACTION;
	+NOGRAVITY;
	+CLIENTSIDEONLY;
	+FORCEXYBILLBOARD;
	renderstyle "Add";
	radius 1;
	height 1;
	alpha 0.4;
	}
}

CLASS RedTF : TorchFlare { 
	states
	{
	Spawn:
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128,2);
		FLAR A 2 bright;
		stop;
		TNT1 A 0;
		FLAR B 2 bright;
		stop;
		Stop;
	}
}
CLASS NewHeadCandles : HeadCandles replaces Headcandles { 
	Default {
	
	+FLOORCLIP;
	}
	states
	{
	Spawn:
		POL3 ABCDCB 2;
		loop;
	}
}

CLASS SmoothEye : Evileye replaces Evileye { 
	Default {
	
	+FLOORCLIP;
	}
	states
	{
	Spawn:
		SEYE abcdef 3 bright;
		loop;
	}
}

CLASS SmoothFloatingSkull : FloatingSkull replaces FloatingSKull { 
	states
	{
	spawn:
		FSKX abcdef 4;
		loop;
	}
}



CLASS RedTorchVanilla : ACTOR { 
	Default {
	Radius 16;
	Height 68;
	ProjectilePassHeight -16;
	+SOLID;
	}
	States
	{
	Spawn:
		TRED ABCD 2 BRIGHT;
		Loop;
	}
}


CLASS BlueTorchVanilla : ACTOR { 
	Default {
	Radius 16;
	Height 68;
	ProjectilePassHeight -16;
	+SOLID;
	}
	States
	{
	Spawn:
		TBLU ABCD 2 BRIGHT;
		Loop;
	}
}


CLASS GreenTorchVanilla : ACTOR { 
	Default {
	Radius 16;
	Height 68;
	ProjectilePassHeight -16;
	+SOLID;
	}
	States
	{
	Spawn:
		TGRN ABCD 2 BRIGHT;
		Loop;
	}
}



CLASS ShortBlueTorchVanilla : ACTOR { 
	Default {
	Radius 16;
	Height 37;
	ProjectilePassHeight -16;
	+SOLID;
	}
	States
	{
	Spawn:
		SMBT ABCD 2 BRIGHT;
		Loop;
	}
}

CLASS ShortRedTorchVanilla : ACTOR { 
	Default {
	Radius 16;
	Height 37;
	ProjectilePassHeight -16;
	+SOLID;
	}
	States
	{
	Spawn:
		SMRT ABCD 2 BRIGHT;
		Loop;
	}
}


CLASS ShortGreenTorchVanilla : ACTOR { 
	Default {
	Radius 16;
	Height 37;
	ProjectilePassHeight -16;
	+SOLID;
	}
	States
	{
	Spawn:
		SMGT ABCD 2 BRIGHT;
		Loop;
	}
}

CLASS CandelabraVanilla : ACTOR { 
	Default {
	Radius 16;
	Height 60;
	ProjectilePassHeight -16;
	+SOLID;
	}
	States
	{
	Spawn:
		CBRA A -1 BRIGHT;
		Stop;
	}
}

CLASS CandleVanilla : ACTOR { 
	Default {
	Radius 20;
	Height 14;
	ProjectilePassHeight -16;
	}
	States
	{
	Spawn:
		CAND A -1 BRIGHT;
		Stop;
	}
}


CLASS BurningBarrelVanilla : ACTOR { 
	Default {
	Radius 16;
	Height 32;
	ProjectilePassHeight -16;
	+SOLID;
	}
	States
	{
	Spawn:
		FCAN ABC 2 BRIGHT;
		Loop;
	}
}



CLASS HumanBBQ : ACTOR { 
	Default {
	
	+NOTARGET;
	Radius 10;
	Height 10;
	//DamageType HumanBBQ;
	+NOGRAVITY +NOTELEPORT +NODAMAGETHRUST;
	+THRUGHOST +NORADIUSDMG +NOEXTREMEDEATH;
	-BLOODSPLATTER +BLOODLESSIMPACT;
	PROJECTILE+DEHEXPLOSION+ACTIVATEMCROSS;
	+NOPAIN;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Explode(3,5);
		TNT1 A 0 A_NoBLocking;
		Stop;
	}
}
