//===========================================================================
//
// Arch Vile
//
//===========================================================================
CLASS pb_Arch_vile: proto_arch_vile// Replaces Archvile
{ 
Default
{
	//SpawnID 2300;
	Mass 500;
	Speed 15;
	MaxTargetRange 896;
	Monster;
	+QUICKTORETALIATE;
	+FLOORCLIP;
	+NOTARGET;

	PainChance 10;
	PainChance "Kick", 90;
	PainChance "ExtremePunches", 90;
	PainChance "Stun", 255;

	damagefactor "Crush", 10.0;
	damagefactor "Head", 0.45;
	damagefactor "Avoid", 0.0; damagefactor "killme", 0.0;
	damagefactor "GibRemoving", 0.0; DamageFactor "CauseObjectsToSplash", 0.0;
	damagefactor "TeleportRemover", 0.0; damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0; damagefactor "GreenBlood", 0.0;

	DamageType "Rape";
	SeeSound "vile/sight";
	PainSound "vile/pain";
	DeathSound "vile/death";
	ActiveSound "vile/active";
	MeleeSound "vile/stop";
	Obituary "%o was exploded by an Arch-Vile.";
	BloodType "Brutal_Blood", "BloodSPlatterReplacer", "AxeBlood";

/*	//DropItem "DemonStrengthRune", 5;
	//DropItem "DemonMorphRune", 5;
	//DropItem "RageSphere", 5;
	//DropItem "DoubleSphere", 5;
	//DropItem "TimeSphere", 2;
	//DropItem "Demonpickup2", 255;
	//DropItem "Demonpickup2", 25;*/
}

States
{	
	Death.Shrink:
		TNT1 A 1 A_PlaySound("Shrink", 3);
/*		TNT1 A 0 A_SpawnItemEx("VileShrinkFX1", 0, 0,  5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("VileShrinkFX2", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("VileShrinkFX3", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("VileShrinkFX4", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("VileShrinkFX5", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("VileShrinkFX6", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("VileShrinkFX7", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("LilVile", 1);*/
	Stop;
		
	Spawn:
 	Stand:
		DIAB B 10 A_Look;
	Loop;

	See:
		DIAB AABBCCDD 2 A_VileChase;
	Loop;
		
	Heal:
		TNT1 A 0
		{
			if(bd_NoArchvileHeal && random(0, 100) <= 24 )
			{
				setstatelabel("bigheal");
			}
		}
		VILE "[\]" 10 Bright;
		TNT1 A 0 A_SpawnItem("PentagramSpawner");
	Goto See;

	BigHeal:
		TNT1 A 0 A_PlaySound("VRESURR", 0);
		V1LH ABCABCABCABC 4 BRIGHT
		{
			a_spawnprojectile("SmallFleshTrails", 25, 0, random(0, 40), 2, random(0, 160));
			A_RadiusGive("Health", 500, RGF_MONSTERS, 80);
			A_SpawnItem("PentagramSpawner", 1);
		}
	Goto See;
		
	Missile:
		TNT1 A 0;
		/*{
			if(monster_handle_event(spawning_event).Archvile_Summon.getint() == 0 && random(0, 100) <= 17 )
			{
				setstatelabel("SummonAfrit");
			}
		}*/

		DIAB E 10 {A_FaceTarget(); A_VileStart();}
		DIAB EEE 3 A_VileTarget("ArchvileFire2");

		DIAB EF 3 BRIGHT
		{
			A_FaceTarget();
			a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
			a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));
		}
		DIAB E 1 A_VileTarget("ArchvileFire2");

		DIAB EF 3 
		{
			A_FaceTarget();
			a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
			a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));
		}
		DIAB E 1 A_VileTarget("ArchvileFire2");

		DIAB EF 3 BRIGHT
		{
			A_FaceTarget();
			a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
			a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));
		}
		DIAB E 1 A_VileTarget("ArchvileFire2");

		DIAB EF 3 BRIGHT
		{
			A_FaceTarget();
			a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
			a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));
		}

		DIAB JKLMN 3 BRIGHT A_FaceTarget;
		DIAB O 3 BRIGHT A_VileAttack;
		DIAB P 3 BRIGHT;
	Goto See;

	SummonAfrit:
		TNT1 A 0 A_Playsound("vile/fire",4);

		TNT1 A 0 A_SpawnItemEx("WalkFire",0,0,0,1,0,0,0,128);
		DIAB E 10 A_FaceTarget;
		DIAB EE 4;
		DIAB EEFFEEFE 3 BRIGHT
		{
			A_FaceTarget();
			a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
			A_SpawnItemEx("WalkFire",0,0,0,1,0,0,0,128);
			a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));
		}

		DIAB JKLMN 3 BRIGHT A_FaceTarget;
		TNT1 A 0  A_Jump(106, "SummonImps");
		DIAB O 3 BRIGHT a_spawnprojectile("ArchComet",10,0,0,0);
		DIAB P 3 BRIGHT;
	goto see;
		
	SummonImps:
		DIAB O 3 BRIGHT a_spawnprojectile("ArchImp1Comet",10,0,0,0);
		TNT1 A 0 a_spawnprojectile("ArchImp2Comet", 85, 35, 40, 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ArchImp3Comet", 85, -35, -40, 2, random(0, 160));
		DIAB P 3 BRIGHT;
	goto see;
		
	Pain:
		DIAB Q 5;
		DIAB Q 5 A_Pain;
	Goto See;
		
	Possession:
		DIAB Q 3 {self.binvulnerable = true;}
		DIAB Q 3 A_Pain;
 		TNT1 A 0 {self.binvulnerable = false;}
	Goto See;

	Pain.Stun:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx("StunElectrocute", random(-4, 4), random(-4, 4),  random(16, 32), 0, 0);
		DIAB Q 1 A_Pain;
		DIAB QQQQQQQQQQ 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		DIAB Q 1 A_Pain;
		DIAB QQQQQQQQQQ 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		DIAB Q 1 A_Pain;
		DIAB QQQQQQQQQQ 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		DIAB Q 1 A_Pain;
		DIAB QQQQQQQQQQ 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		DIAB Q 1 A_Pain;
		DIAB QQQQQQQQQQ 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		DIAB Q 1 A_Pain;
	Goto See;

	Pain.Kick:
	Pain.ExtremePunches:
		DIAB Q 10 {A_Recoil(8); A_FaceTarget();}
		DIAB Q 10 A_Pain();
	Goto See;

	Death.Head:
	Death.MinorHead:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("Brains2", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPiece", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Teeth", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(50, 90));
		TNT1 A 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(50, 90));
		TNT1 A 0 A_Jump(130, "Head2");
		VID2 A 3;
		VID2 BC 7 a_spawnprojectile("Bloodmist", 58, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("Bloodmist", 50, 0, random(0, 360), 2, random(0, 160));
		VID2 D 6 a_spawnprojectile("Bloodmist", 45, 0, random(0, 360), 2, random(0, 160));
		VID2 E 6 a_spawnprojectile("Bloodmist", 36, 0, random(0, 360), 2, random(0, 160));
		VID2 F 6 a_spawnprojectile("Bloodmist", 20, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadArchvileVID2F");
	Stop;

	Death.Decapitate:
		TNT1 A 0 a_spawnprojectile("Archvile_severed_Head", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 40, 0, random(0, 360), 2, random(30, 90));
	Head2:
		D1AX G 7;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("HeadlessArchvile");
	Stop;
		
	Death:
		TNT1 A 0 A_Jump(132, "Death2");
		TNT1 A 0 A_Jump(64, "DeathArm");
		TNT1 A 0 A_Jump(32, "Death.Arm");
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		DIAB RSTUVWX 5 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadArchvile");
	Stop;
		
	Death2:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		D1AX ABCDE 6;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadArchvile_D1AXF");
	Stop;
		
	DeathArm:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 a_spawnprojectile("Bloodmist", 44, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 42, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeath2", 38, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("archvile_severed_arm", 45, 0, random(150, 210), 2, random(0, 40));
		D2AX IJKL 6;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadArchvile_D2AXM");
	Stop;
		
	Death.Shotgun:
		TNT1 A 0 A_JumpIfCloser(250, "ShotgunBlast");
	Goto Death;

	Death.Blast:
		TNT1 A 0 a_jUMP(48, "Death.SSG", "BrutalDeath");
	Death.Railgun:
	ShotgunBlast:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_XScream;
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("archvile_severed_arm", 42, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("Archvile_severed_Head", 52, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 26, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 38, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 38, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 38, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 44, 0, random(0, 360), 2, random(30, 90));
		D2AX N 8 A_Stop;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		D2AX OOOOOOOO 3 a_spawnprojectile("Brutal_LiquidBlood2", 38, 0, random(0, 360), 2, random(30, 60));
		D2AX PPP 3 a_spawnprojectile("Brutal_LiquidBlood2", 32, 0, random(0, 360), 2, random(10, 40));
		TNT1 A 0 A_PlaySound("BODYF",6);
		D2AX QQ 3 a_spawnprojectile("Brutal_LiquidBlood2", 6, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_SpawnItem("DeadArchvile_D2AXQ");
	Stop;
		
	Death.ExtremePunches:
	Death.SSG:
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_XScream;
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("archvile_severed_arm", 38, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("archvile_severed_torso", 45, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("Archvile_severed_Head", 52, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 26, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 44, 0, random(0, 360), 2, random(30, 90));
		D2AX EEEEEEEE 2 a_spawnprojectile("Brutal_LiquidBlood2", 38, 0, random(0, 360), 2, random(0, 160));
		D2AX FG 8;
		TNT1 A 0 A_PlaySound("BODYF",6);
		D2AX H 1;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadArchvile_D2AXH");
	Stop;
		
	Death.Saw:
	Death.Cut:
		TNT1 A 0;
		TNT1 A 0 a_fACETARGET;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("XDeathStomach", 32, 0, random(0, 360), 2, random(60, 120));
		TNT1 AAAAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(60, 120));
		D2AX EEEEEEEE 2 a_spawnprojectile("Brutal_LiquidBlood2", 38, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("archvile_torso_two_arms", 30, 0, random(190, 240), 2, random(0, 30));
		D2AX FG 8;
		TNT1 A 0 A_PlaySound("BODYF",6);
		D2AX H 1;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadArchvile_D2AXH");
	Stop;
		
	Death.cutless:
		TNT1 A 0;
		TNT1 A 0 A_Jump(16, "Death");
		TNT1 A 0 A_Jump(96, "Death.Arm");
	Goto Death.Minigun;

	Death.Minigun:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Scream;
		TNT1 O 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("BrutalizedArchvile", 1);
	Stop;
		
	Death.Arm:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 a_spawnprojectile("XDeath1", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("archvile_severed_arm", 52, 0, random(0, 360), 2, random(40, 120));
		TNT1 AAA 0 {pb_blood_and_gore_event.much_blood(self);}
		VID2 HHIJ 5;
		TNT1 A 0 A_SpawnItem("DyingArchvileNoArm");
		TNT1 A -1;
	Stop;
		
	Death.Tear:
	Death.QuadBlast:
	BrutalDeath:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(60, 120));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 52, 0, random(0, 360), 2, random(60, 120));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 52, 0, random(0, 360), 2, random(60, 120));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(60, 120));
		XVIL ABCDEFGHIJKLMNOPQ 2;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadArchvileXVILQ");
	Stop;

	XDeath:
	Death.Explosive:
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_XScream;
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 A 0 a_spawnprojectile("XDeath2", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 A 0 a_spawnprojectile("XDeath4", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 A 1 a_spawnprojectile("archvile_guro_spawner", 0, 0, random(0, 360), 2, random(0, 160));
	Stop;

	Death.Desintegrate:
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("Bloodmist", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 a_spawnprojectile("Bloodmist", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		VIGI C 3 A_Scream;
		VIGI D 3;
		VIGI E 3 A_NoBlocking;
		VIGI FGHIJ 3;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadArchvileVIGIJ");
	Stop;

	Death.SuperPlasma:
	Death.GreenFire:
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("Barrel_explosion_Column");
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 AAA 0 A_SpawnItemEx("TinyBurningPiece", random(-35, 35), random(-35, 35));
		TNT1 AAAA 0 a_spawnprojectile("BluePlasmaFire", 42, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_Stop;
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece", random(-45, 45), random(-45, 35));
		TNT1 A 0;
		TNT1 A 0 A_Scream;
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 52, 0, random(0, 360), 2, random(60, 120));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 52, 0, random(0, 360), 2, random(60, 120));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(60, 120));
		TNT1 A 0 A_NoBlocking;
		XVIP ABCDEFGHIJKLMNOPQ 2;
		XVIP Q -1;
	Stop;
	
	Death.Fire:
		TNT1 A 0;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Playsound("props/redfire");
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		XVIP ABCDEFGHIJKLMNOPQ 2;
		XVIP QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ 2 a_spawnprojectile("FlameTrails", 15, 0, random(0, 360), 2, random(70, 130));
		XVIP QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ 10 a_spawnprojectile("Explosion_Smoke", 15, 0, random(0, 360), 2, random(70, 130));
		XVIP Q -1;
	Stop;

	Death.Fatality:
		TNT1 A 0 A_Pain;
		//TNT1 A 0 A_JumpIfIntargetInventory("FistsSelected", 1, 1);
	Goto Death;
		TNT1 A 0 A_Jump(128, "Fatality2");
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_NoBlocking;
		//TNT1 A 0 A_GiveToTarget("ArchvileFatality", 1);
	Stop;
	
	Fatality2:
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_NoBlocking;
		//TNT1 A 0 A_GiveToTarget("ArchvileFatality2", 1);
	Stop;
	
	Crush:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS2 A 5;
		CRS2 A -1;
	Stop;
	
	Pain.KillMe:
	Pain.Taunt:
		TNT1 A 0;
	Goto Missile;

	Death.KillMe:
	Death.Taunt:
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 A_SpawnItem("pb_Arch_Vile");
	Stop;
	
	Death.Ice:
	Death.Freeze:
	Death.Frost:
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		//TNT1 A 0 A_SpawnItem("FrozenArchvile");
	Stop;
}

}


CLASS ArchvileFire2 : ACTOR //Replaces ArchvileFire
{ 
Default
{
	Scale 0.7;
	+NOBLOCKMAP +NOGRAVITY;
	RenderStyle "Add";
	Alpha 0.6;
}

States
{
	Spawn:
		TNT1 A 1 bright A_StartFire;
		INFE ABCDEF 1 bright A_Fire;
		INFE G 1 bright A_FireCrackle;
		INFE HIJKLM 1 bright A_Fire;
		INFE N 1 bright A_FireCrackle;
		INFE OPQRS 1 bright A_Fire;
		INFE T 1 bright A_FireCrackle;
	Stop;
}

}

CLASS ArchComet : ACTOR
{ 
Default
{
	Radius 6;
	Height 8;
	Speed 15;
	Damage 25;
	DamageType "Fire";
	//SpawnID 250;
	Scale 1.5;
	Projectile;
	+DoomBounce;
	BounceFactor 0.6;
	Gravity 0.5;
	SeeSound "Afrit/CometFire";
	DeathSound "Afrit/CometHit";
	Decal "Scorch";
}
States
{
	Spawn:
		COMT AAAAAAAAAAAAABBBBBBBBBBBBBBBCCCCCCCCCCCCCC  1 Bright A_SpawnItemEx("ArchCometTail", 0, 0, 0, 0, 0, 0, 0, 128);
	Goto Death;
	Death:
		COMT D 3 Bright A_SpawnItemEx("CometDeathGlow", 0, 0, 0, 0, 0, 0, 0, 128);
		COMT E 3;
		TNT1 A 0 Bright A_SpawnItem("pb_afrit");
		TNT1 A 0 A_SpawnItemEx("ArchCometDeath", 0, 0, 0, 0, 0, 0, 0, 128);
	Stop;
}

}

CLASS ArchImp1Comet : ACTOR
{ 
Default
{
	Radius 6;
	Height 8;
	Speed 15;
	Damage 10;
	DamageType "Fire";
	//SpawnID 250;
	Scale 1.25;
	Projectile;
	+DoomBounce;
	BounceFactor 0.6;
	Gravity 0.5;
	SeeSound "Afrit/CometFire";
	DeathSound "Afrit/CometHit";
	Decal "Scorch";
}
States
{
	Spawn:
		COMT AAAAAAAAAAAAABBBBBBBBBBBBBBBCCCCCCCCCCCCCC  1 Bright A_SpawnItemEx("ArchCometTail", 0, 0, 0, 0, 0, 0, 0, 128);
	Goto Death;

	Death:
		COMT D 3 Bright A_SpawnItemEx("CometDeathGlow", 0, 0, 0, 0, 0, 0, 0, 128);
		COMT E 3;
		//TNT1 A 0 Bright A_SpawnItem("DNImpVariant1");
		TNT1 A 0 A_SpawnItemEx("ArchCometDeath", 0, 0, 0, 0, 0, 0, 0, 128);
	Stop;
}

}

CLASS ArchImp2Comet : ACTOR
{ 
Default
{
	Radius 6;
	Height 8;
	Speed 15;
	Damage 10;
	DamageType "Fire";
	//SpawnID 250;
	Scale 1.25;
	Projectile;
	+DoomBounce;
	BounceFactor 0.6;
	Gravity 0.5;
	SeeSound "Afrit/CometFire";
	DeathSound "Afrit/CometHit";
	Decal "Scorch";
}
States
{
	Spawn:
		COMT AAAAAAAAAAAAABBBBBBBBBBBBBBBCCCCCCCCCCCCCC  1 Bright A_SpawnItemEx("ArchCometTail", 0, 0, 0, 0, 0, 0, 0, 128);
	Goto Death;
	Death:
		COMT D 3 Bright A_SpawnItemEx("CometDeathGlow", 0, 0, 0, 0, 0, 0, 0, 128);
		COMT E 3;
		//TNT1 A 0 Bright A_SpawnItem("DNImpVariant2");
		TNT1 A 0 A_SpawnItemEx("ArchCometDeath", 0, 0, 0, 0, 0, 0, 0, 128);
	Stop;
}

}

CLASS ArchImp3Comet : ACTOR
{
Default
{	
	Radius 6;
	Height 8;
	Speed 15;
	Damage 10;
	DamageType "Fire";
	//SpawnID 250;
	Scale 1.25;
	Projectile;
	+DoomBounce;
	BounceFactor 0.6;
	Gravity 0.5;
	SeeSound "Afrit/CometFire";
	DeathSound "Afrit/CometHit";
	Decal "Scorch";
}
States
{
	Spawn:
		COMT AAAAAAAAAAAAABBBBBBBBBBBBBBBCCCCCCCCCCCCCC  1 Bright A_SpawnItemEx("ArchCometTail", 0, 0, 0, 0, 0, 0, 0, 128);
	Goto Death;

	Death:
		COMT D 3 Bright A_SpawnItemEx("CometDeathGlow", 0, 0, 0, 0, 0, 0, 0, 128);
		COMT E 3;
		////TNT1 A 0 Bright A_SpawnItem("DNImpVariant3");
		TNT1 A 0 A_SpawnItemEx("ArchCometDeath", 0, 0, 0, 0, 0, 0, 0, 128);
	Stop;
}

}

CLASS ArchCometTail : ACTOR
{
Default
{
	Projectile;
	+NoClip;
	RenderStyle "Add";
	Alpha 0.4;
}
States
{
	Spawn:
		FRTB ABCDEFGHI 1 Bright;
	Stop;
}
}

CLASS ArchCometDeath : ACTOR { 
	Default {
	
	Projectile;
	RenderStyle "Add";
	+NoClip;
	Alpha 0.7;
	}
  States
  {
	Spawn:
		COMT FGHI 3 Bright;
	Stop;
}
}

