CLASS pb_mancy_bus : proto_fat //Replaces Fatso
{

Default
{
	//SpawnID 1700;
	Scale 1.2;
	MaxStepHeight 16;
	MaxDropOffHeight 24;
	damagefactor "Crush", 10.0;
	damagefactor "Head", 0.65;
	damagefactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	PainChance "Kick", 255;
	PainChance "ExtremePunches", 255;
	PainChance "Taunt", 255;
	PainChance "Explosive", 255;
	damagefactor "TeleportRemover", 0.0;
	damagefactor "GibRemoving", 0.0;
	DamageFactor "CauseObjectsToSplash", 0.0;
	PainChance "SSG", 255;
	PainChance "Stun", 255;
	Radius 48;
	GibHealth 30;
	Health 650;
	Mass 500;
	BloodType "pb_blood", "BloodSPlatterReplacer", "AxeBlood";
	Obituary "%o was incinerated by a Mancubus.";
	damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0; damagefactor "GreenBlood", 0.0;
	+THRUGHOST;
	+BOSSDEATH;
	Species "BigFatAss";
	+DONTHARMSPECIES;
	+DONTHARMCLASS;
	
	//DropItem "DemonStrengthRune", 5;
	//DropItem "Demonpickup2", 60;
	//DropItem "Demonpickup2", 250;
}
States
{

	Spawn:
		TNT1 A 0;
 	Stand:
		FATT B 10 A_Look();
	Loop;
		
	See:
	LookingForPlayer:
		TNT1 A 0 A_PlaySound("knight/step",5);
		tnt1 a 0 {pb_monster_memory(); cooldown --;}
		FATT AA 4 A_Chase();
		TNT1 A 0 A_PlaySound("knight/step",5);
		FATT BBCC 4 A_Chase();
		TNT1 A 0 A_PlaySound("knight/step",5);
		FATT DDEEFF 4 A_Chase();
	Goto See;

	Missile:
		TNT1 A 0 A_JumpIfCloser(900, 2);
		TNT1 A 0 A_JumpIfCloser(300, "Flamethrower");
		TNT1 A 0 A_JumpIfInventory("Enraged", 1, 1);
		FATT G 2 A_FaceTarget();
		FATT GG 10 A_FatRaise();
		TNT1 A 0 a_spawnprojectile("BigFireBall",30,-25,10,0);
		TNT1 A 0 a_spawnprojectile("BigFireBall",30,25,0,0);
		FATT H 10 BRIGHT;
		FATT IG 5 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("BigFireBall",30,-25,0,0);
		TNT1 A 0 a_spawnprojectile("BigFireBall",30,25,-10,0);
		FATT H 10 BRIGHT;
		FATT IG 5 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("BigFireBall",30,-25,4,0);
		TNT1 A 0 a_spawnprojectile("BigFireBall",30,25,-4,0);
		FATT H 10 BRIGHT;
		FATT IG 5;
	Goto See;
		
	Flamethrower:
		TNT1 A 0 A_JumpIfInventory("Enraged", 1, 1);
		FATT G 1 A_FatRaise();
		TNT1 A 0 A_PlaySound("FLMDRAW",3);	
		FATT GGGGGGGGGGGG 2
		{
			A_FaceTarget();
			pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");
			pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");
		}
	Torch:
		FATT GHIGH 1
		{
			A_FaceTarget();
			A_PlaySound("flamersh",2);
			if( (frame % 2) == 0) cooldown ++;
			a_spawnprojectile("EnemyFlamethrowerMissile",30,-25,10,0);
			a_spawnprojectile("EnemyFlamethrowerMissile",30,25,0,0);
			pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");
			pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");
		}
		TNT1 A 0 A_JumpIf(cooldown > 8, "See");
		TNT1 A 0 A_JumpIfCloser(320, "Torch");
		FATT IG 5;
	Goto See;
		
	Pain:
		FATT J 3;
		FATT J 3 A_Pain();
	Goto See;
		
	Possession:
		TNT1 A 0 A_SetInvulnerable();
		FATT J 3;
		FATT J 3 A_Pain();
 		TNT1 A 0 A_UnSetInvulnerable();
	Goto See;
		
	Pain.Kick:
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(0.50);
		FATT J 9 A_Pain();
		FATT J 8;
	Goto See;
		
	Pain.Explosive:
	Pain.ExtremePunches:
	Pain.SSG:
	Pain.Blackhole:
	Pain.QuadShot:
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 {self.bNOPAIN = true;}
		FAT4 A 4 ThrustThingZ(0,30,0,1);
		FAT4 B 4 A_Pain();
		FAT4 CDDDD 4;
		FAT4 C 4 A_Stop();
		FAT4 BA 4;
		TNT1 A 0 {self.bNOPAIN = false;}
	Goto See;
		
	Death.Fatality:
		TNT1 A 0 A_Jump(256, "Fatality1", "Fatality2");
		TNT1 A 0;
	Stop;
		
	Fatality1:
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("FatsoFatality", 1);
		TNT1 A 1 A_BossDeath();
		TNT1 A 0;
	Stop;
		
	Fatality2:
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("FatsoFatality2", 1);
		TNT1 A 1 A_BossDeath();
		TNT1 A 0;
	Stop;

	Death.minorhead:
	Death.head:
		//TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 A 0 A_SpawnItem("MancubusHeadExplode", 0, 50);
		TNT1 A 0 A_Jump(32, "DeathHead2");
		FATT KKKLLL 2 a_spawnprojectile("Brutal_LiquidBlood2", 50, 0, random(0, 360), 2, random(30, 50));
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_BossDeath();
		FATT MMMNNOOPPQQRRSSTTTTTTTTTTTTTTTTTTTTTTT 2 a_spawnprojectile("Brutal_LiquidBlood2", 30, 0, random(0, 360), 2, random(20, 50));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadFatNoHead", 1);
	Stop;
		
	DeathHead2:
		FATR K 6 A_Scream();
		FATR L 6;
		FATR M 6;
		FATR NOPQR 6;
		FATR S 6 A_NoBlocking();
		FATR T 6 A_BossDeath();
		TNT1 A 0 A_SpawnItem("Deadfat3", 1);
	Stop;
		
		
	Death.decaptate:
		TNT1 AAAAAA 0 a_spawnprojectile("Xdeath1", 62, 0, random(50, 130), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XdeathMancubusHead", 62, 0, random(50, 130), 2, random(50, 130));
		FATT O 6 A_Scream();
		FATT P 6 A_NoBlocking();
		FATT QRS 6;
		FATT T 1 A_BossDeath();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadFatNoHead", 1);
	Stop;
		
	Death:
		TNT1 A 0 A_Jump(32, "Death.Arm");
		TNT1 A 0 A_Jump(112, "Death2");
		TNT1 A 0 A_Jump(128, "Death3");
		FATK A 6;
		FATK B 6 A_Scream();
		FATK C 6 A_NoBlocking();
		FATK DEF 6  {pb_blood_and_gore_event.much_blood(self);}
		FATK F 1 A_BossDeath  ();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadFat", 1);
	Stop;
		
	Death2:
		FAT3 K 6;
		FAT3 L 6 A_Scream();
		FAT3 M 6 A_NoBlocking();
		FAT3 NOP 6  {pb_blood_and_gore_event.much_blood(self);}
		FAT3 Q 6;
		FAT3 R 6 A_BossDeath();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadFat2", 1);
	Stop;
		
	Death3:
		FAT3 A 1;
		FAT3 B 6 A_Scream();
		FAT3 C 6 A_NoBlocking();
		FAT3 DEF 6;
		FAT3  F 1 A_BossDeath();
		FAT3 F 1 A_SpawnItem("DeadFattyHoles", 1);
	Stop;
		
		////////////////////////////////
		
		
		
	Death.Tear:
		TNT1 O 0 A_Jump(128, "DeathGutted");
		TNT1 AAA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 A_Scream();
		TNT1 O 0 A_NoBlocking();
		FAT2 KL 5  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAAA 0 a_spawnprojectile("RipGuts", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_BossDeath();
		FAT2 MNOP 5  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("NoGutsFatso", 1);
	Stop;
		
	Death.Cut:
	Death.Saw:
		TNT1 O 0 A_Jump(24, "DeathGutted");
		TNT1 A 0;
		TNT1 A 0 A_Stop();
		XFAT AB 4;
		TNT1 A 0 A_Scream();
		TNT1 O 0 A_NoBlocking();
		TNT1 AA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAAA 0 a_spawnprojectile("RipGuts", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_BossDeath();
		XFAT CDEF 5;
		XFAT GH 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 AAAAAAAAAAAAAAAAAA 4 a_spawnprojectile("Brutal_LiquidBlood2", 40, 0, random(0, 360), 2, random(30, 50));
		XFAT I -1;
	Stop;
		
	Death.cutless:
		TNT1 A 0 A_Jump(32, "Death3");
		TNT1 A 0 A_Jump(20, "DeathGutted");
	Death.Arm:
		TNT1 A 0;
		TNT1 A 0 A_BossDeath();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 AA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		XFT1 AAAAAAAA 1 a_spawnprojectile("Brutal_LiquidBlood2", 50, 0, random(0, 360), 2, random(30, 50));
		TNT1 A 0 A_SpawnItem("DyingFatso01");
		TNT1 A -1;
	Stop;

	DeathGutted:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_BossDeath();
		TNT1 AAA 0  {pb_blood_and_gore_event.much_blood(self);}
		MXD1 AABBBBBBCCCCCCCDDDDDDDEEEEEEEFFFFFFGGGGGGGHHHHHHHIIIIIIIIIIIIIIIIIIIIIIIIIIIIII 1
		{
			a_spawnprojectile("Brutal_LiquidBlood2", 40, 0, random(0, 360), 2, random(30, 60));
			if(frame < 3)
			{
					a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
					a_spawnprojectile("xdeath2", 0, 0, random(0, 360), 2, random(0, 160));
			}
			if(frame == 1) a_spawnprojectile("RipGuts", 25, 0, random(0, 360), 2, random(0, 160));
		}
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadFatSlump", 1);
	Stop;
		
	Death.Shotgun:
		TNT1 A 0 A_JumpIfCloser(250, 1);
	Goto Death;
		//TNT1 A 0 A_JumpIfInTargetInventory("SSGSelected", 1, "Death.SSG");
	Goto Death;
		
	Death.SSG:
		TNT1 A 0;
		TNT1 A 0 A_Jump(96, "Death.Blast");
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_noBlocking();
		TNT1 A 0 A_BossDeath();
		TNT1 A 0 A_Jump(255, "DeathSSG1", "DEathSSG2");
	DeathSSG1:
		TNT1 A 0;
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AA 0 a_spawnprojectile("XDeathMancubusArm", 30, 0, random(0, 360), 2, random(50, 130));
		XFT2 AAAAAAAAAAAA 2 a_spawnprojectile("Brutal_LiquidBlood2", 50, 0, random(0, 360), 2, random(30, 50));
		XFT2 BC 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		XFT2 D -1;
	Stop;
		
	DeathSSG2:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("MancubusHeadExplode", 0, 50);
		TNT1 AA 0 a_spawnprojectile("XDeathMancubusArm", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 AAA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		XFT3 AAAAAAAAAAAAAAAAAAAAAAAA 2 a_spawnprojectile("Brutal_LiquidBlood2", 50, 0, random(0, 360), 2, random(30, 50));
		XFT3 BC 6;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		XFT3 D -1;
	Stop;
		
	XDeath:
	Death.QuadBlast:
	Death.Explosives:
	Death.ExplosiveImpact:
	Death.Landmine:
		TNT1 A 0 a_spawnprojectile("MeatDeath", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(60, 90));
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathMancubusTorso", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathMancubusLeg", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathMancubusHead", 20, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("XDeath2", 20, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("XDeath3", 20, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0  {pb_blood_and_gore_event.much_blood(self);}
		XFBT A 6 A_Scream();
		XFBT B 6 A_NoBlocking();
		XFBT CDEF 6 A_BossDeath();
		XFBT F 1;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("XDeadFat", 1);
	Stop;
	
	Crush:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS3 A 5 A_BossDeath();
		CRS3 A -1;
	Stop;
	
	Pain.Taunt:
		tnt1 B 0
		{
			A_Pain();
		} 
		TNT1 A 0 {self.bNOPAIN = true;}
		TNT1 A 0 {self.bMISSILEMORE = true;}
		TNT1 A 0 {self.bMISSILEEVENMORE = true;}
		TNT1 A 0 A_PlaySound("demon/pain");
		FATR A 1 A_FaceTarget();
		FATR A 10  A_Pain();
		FATR BAC 8;
		TNT1 A 0 A_Pain();
		FATR ABAC 8;
		TNT1 A 0 A_Pain();
		FATR ABAC 8;
		TNT1 A 0 {rage = true;}
	Goto Missile;
	
	Pain.KillMe:
		TNT1 A 0;
	Goto Missile;

	Death.KillMe:
	Death.Taunt:
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 A_SpawnItem("Fatso");
	Stop;
} 
} 

CLASS BigFireBall  : pb_projectile_base //Replaces Fatshot
{ 
Default
{	
	//SpawnID 153;
	Radius 6;
	Height 8;
	Speed 20;
	Fastspeed 25;
	DamageFunction (random(25,40));
	Projectile;
	Scale 0.71;
	+FORCEXYBILLBOARD;
	+THRUGHOST;
	RenderStyle "Translucent";
	DamageType "Fire";
	ExplosionRadius 150;
	ExplosionDamage 8;
	Alpha 1;
	Decal "Scorch";
	SeeSound "BREATHOF";
	DeathSound "fatso/shotx";
}

States
{
	Spawn:
		TNT1 A 0 nodelay A_Playsound("BGFLMBL", 6, 1, 1);
	Spawn1:
		BLHD CD 1 BRIGHT
		{
			 A_SpawnItem("CoolandNewFlameTrails");
			a_spawnprojectile("ExplosionSmoke", 2, 0, random(70, 110), 2, random(0, 360));
		}
	Loop;
	
	death:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 A_Explode(10, 50, 0);
		TNT1 A 0;
		TNT1 A 0 A_StopSound(6);
		TNT1 AAAA 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0
		{
			for (int i = 0; i < 10; i++)
			{
				a_spawnprojectile("pb_particle", 0, 0, random(0, 360), 2, random(0, 180));
			}
		}
		TNT1 AAA 0 
		{
			pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");
		}
		EXPL AAA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(0, 90));
		//TNT1 AA 0 a_spawnprojectile("FireworkSFXType1", 0, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-35, 35), random(-35, 35));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-45, 45), random(-45, 35));
		TNT1 A 1 Light("BIGREDTORCH");
		TNT1 AAAAAA 20 a_spawnprojectile("BigBlackSmoke", 0, 0, random(0, 360), 2, random(40, 160));
	Stop;
}

}


CLASS NoGutsFatso : pb_blood_and_gore_base { 
Default {
	Radius 24;
	Mass 10000;
	Health 500;
	Scale 1.1;
}
States
{
	Spawn:
		FAT2 PPPPPPPPPPPPPPPPPPPPPPP 9;
		FAT2 PPP 1 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
		FAT2 P -1;
	Stop;
	Death:
		TNT1 A 0 a_spawnprojectile("MuchMeatDeath", 2, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("NoGutsFatso_RemovedWeapon", 1);
	Stop;

	Death.flames:
	Death.burn:
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL AAAAAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		CARB LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 10 a_spawnprojectile("Explosion_Smoke", 1, 0, random(0, 360), 2, random(0, 160));
		CARB L -1;
	Death.Cut:
	Death.Saw:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("xdeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("xdeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("NoGutsFatso_RemovedWeapon", 1);
		TNT1 A -1;
	Stop;
}
}

CLASS NoGutsFatso_RemovedWeapon: NoGutsFatso { 
Default {
	Health 500;
}
States
{
	Spawn:
		FAT2 Q 1;
	Loop;

    Death.flames:
    Death.burn:
    Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL AAAAAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		CARB OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 10 a_spawnprojectile("Explosion_Smoke", 1, 0, random(0, 360), 2, random(0, 160));
		CARB O -1;
	stop;

	Death.Cutless: 
	Death.Cut:
	Death.Saw:
	Death:
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		FAT2 Z -1;
	Stop;
}

}

CLASS DeadFat : pb_blood_and_gore_base { 
Default {
    Radius 39;
	Height 23;
    Scale 1.2;
    +SHOOTABLE
    -SOLID
    +NOTELEPORT
    +MOVEWITHSECTOR
    -CORPSE
	-DONTGIB
	-TELESTOMP
    Mass 1000;
    Health 500;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	Species "Marine";
	damagefactor "Cut", 4.0;
	damagefactor "Saw", 4.0;
	damagefactor "Tear", 4.0;
}
States
{
	Spawn:
		FATK F -1;
	Stop;
	Death:
		TNT1 AA 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("DeadFatNoArm", 1);
	Stop;
	Death.flames:
	Death.burn:
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL AAAAAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		CARB LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 10 a_spawnprojectile("Explosion_Smoke", 1, 0, random(0, 360), 2, random(0, 160));
		CARB L -1;
	Stop;

	Death.Cutless: 
	Death.Cut:
	Death.Saw:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("DeadFatNoArm", 1);
	Stop;
}

}
	
CLASS Deadfat2: Deadfat
{ 
States
{
	Spawn:
		FAT3 RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR 10;
		FAT3 RRRRR 1 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
		FAT3 R -1;
	stop;
	Death.flames:
	Death.burn:
	Death.Plasma: Death.Plasma2:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL AAAAAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		CARB OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 10 a_spawnprojectile("Explosion_Smoke", 1, 0, random(0, 360), 2, random(0, 160));
		CARB O -1;
	Stop;

	Death.Cutless: 
	Death.Cut:
	Death.Saw:
	Death:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		FAT2 U 1 A_SpawnItem("Deadfat2NoArm", 1);
	Stop;
}

}

CLASS DeadFat2NoArm : pb_blood_and_gore_base { 
Default {
    Radius 39;
	Height 28;
    Scale 1.2;
    +SHOOTABLE
    -SOLID
    +NOTELEPORT
    +MOVEWITHSECTOR
    -CORPSE
	-DONTGIB
	-TELESTOMP
    Mass 1000;
    Health 500;
	Damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	Species "Marine";
	damagefactor "Cut", 4.0;
	damagefactor "Saw", 4.0;
	damagefactor "Tear", 4.0;
}
States
{
	Spawn:
		FAT2 UUUUUUUUUUUUUU 12;
		FAT2 UU 1 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
		FAT2 U -1;
	Stop;
	Death.flames:
	Death.burn:
	Death.Plasma: Death.Plasma2:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL AAAAAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		CARB OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 10 a_spawnprojectile("Explosion_Smoke", 1, 0, random(0, 360), 2, random(0, 160));
		CARB O -1;
	Stop;

	Death.Cutless: 
	Death.Cut:
	Death.Saw:
	Death:
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		FAT2 T -1;
	Stop;
}
}

CLASS Deadfat3: DeadFat
{ 
States
{
	Spawn:
		FATR TTTTTTTTTTTTTTTTTTTTTTTTTTTT 10;
		FATR TTTT 1 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
		FATR T -1;
	Stop;

	Death.Cutless: 
	Death.Cut:
	Death.Saw:
	Death:
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		FAT2 W 1 A_SpawnItem("Deadfat3_RemovedWeapon", 1);
	Stop;
}
}

CLASS Deadfat3_RemovedWeapon: DeadFat
{ 
States
{
	Spawn:
		FAT2 W -1;
	Stop;

	Death.Cutless: 
	Death.Cut:
	Death.Saw:
	Death:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		FAT2 V -1;
	Stop;
}
}

CLASS Deadfat4: DeadFat
{ 
States
{
	Spawn:
		FAT5 EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 10;
		FAT5 EEEE 1 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
		FAT5 E -1;
	Stop;
	Death.Cutless: 
	Death.Cut:
	Death.Saw:
	Death:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		FAT2 W 1 A_SpawnItem("Deadfat4_RemovedWeapon", 1);
	Stop;
}
}

CLASS Deadfat4_RemovedWeapon: DeadFat
{ 
States
{
	Spawn:
		FAT5 F -1;
	Stop;

	Death.Cutless: 
	Death.Cut:
	Death.Saw:
	Death:
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		FAT5 G -1;
	Stop;
}
}

CLASS DeadFatNoArm : ACTOR { 
Default {
	Radius 39;
	Height 25;
	Scale 1.2;
	+SHOOTABLE;
	-SOLID;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	-CORPSE;
	-DONTGIB;
	-TELESTOMP;
	Mass 1000;
	Health 500;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	Species "Marine";
	damagefactor "Cut", 4.0;
	damagefactor "Saw", 4.0;
	damagefactor "Tear", 4.0;
}
States
{
	Spawn:
		FATK GGGGGGGGGGGGGGGGGGG 12;
		FATK GGGG 1 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
		FATK G -1;
	Stop;
	Death.flames:
	Death.burn:
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL AAAAAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		CARB OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 10 a_spawnprojectile("Explosion_Smoke", 1, 0, random(0, 360), 2, random(0, 160));
		CARB O -1;
	Stop;
	Death.Cutless: 
	Death.Cut:
	Death.Saw:
	Death:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		FAT2 Y -1;
	Stop;
}
}

CLASS DeadFatNoHead: DeadFat { 
Default {
	Health 500; 
}
States
{
	Spawn:
		FATT TTTTTTTTTTTTTTTTTT 10;
		FATT TT 1 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
		FATT T -1;
	Stop;
	Death:
		TNT1 AA 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A -1;
	Stop;

	Death.Cutless: 
	Death.Cut:
	Death.Saw:
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("DeadFatNoHead_RemovedWeapon", 1);
		TNT1 A -1;
	Stop;
	}}

CLASS DeadFatNoHead_RemovedWeapon: DeadFat { 
Default {
	Health 500;
}
States
{
	Spawn:
		FAT2 RRRRRRRRRRRRRRRRRRRRRRRRRRRRR 16;
		FAT2 RRR 1 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
		FAT2 R -1;
	Stop;

    Death.flames:
    Death.burn:
    Death.Plasma: Death.Plasma2:
        TNT1 A 0;
        TNT1 A 0 A_Scream;
        TNT1 A 0 A_NoBlocking;
        TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
	    TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	    TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL AAAAAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
        CARB OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 10 a_spawnprojectile("Explosion_Smoke", 1, 0, random(0, 360), 2, random(0, 160));
        CARB O -1;
	stop;
	
	Death.Cutless:
	Death.Cut:
	Death.Saw:
	Death:
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		FAT2 X -1;
	Stop;
}

}




CLASS XDeadFat: DeadFat { 
Default {
	Health 500 ;
}
States
{
	Spawn:
		XFBT FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 10;
		XFBT FFFFF 1 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
		XFBT F -1;
	Stop;

    Death.flames:
    Death.burn:
    Death.Plasma: Death.Plasma2:
        TNT1 A 0;
        TNT1 A 0 A_Scream;
        TNT1 A 0 A_NoBlocking;
        TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
	    TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	    TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL AAAAAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
        CARB OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 10 a_spawnprojectile("Explosion_Smoke", 1, 0, random(0, 360), 2, random(0, 160));
        CARB O -1;
	Stop;

	Death.Cutless: 
	Death.Cut:
	Death.Saw:
	Death:
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A -1;
	Stop;
}
}

CLASS FatalizedFatso: DeadFat { 
Default {
	Scale 1.0 ;
	Health 500 ;
}
States
{
	Spawn:
		FATF F 1 A_PlaySound("fatso/pain");
		FATF FFEE 10 a_spawnprojectile("Blood", 35, 0, random(0, 360), 2, random(0, 160));
		tnt1 a 0 a_jumpif(random(0, 10) < 7, "spawn");
		FATF E 1 A_PlaySound("fatso/death");
		FATF EEEEEEEEE 4 a_spawnprojectile("Blood", 35, 0, random(0, 360), 2, random(0, 160));
		FATF E -1;
	Stop;
 
    Death.flames:
    Death.burn:
    Death.Plasma: Death.Plasma2:
        TNT1 A 0;
        TNT1 A 0 A_Scream;
        TNT1 A 0 A_NoBlocking;
        TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
	    TNT1 AAAA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL AAAAAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
        CARB LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 10 a_spawnprojectile("Explosion_Smoke", 1, 0, random(0, 360), 2, random(0, 160));
        CARB L -1;
	stop;

    Death:
		TNT1 AA 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("NoGutsFatso_RemovedWeapon", 1);
		TNT1 A -1;
	Stop;
	Death.Cutless: 
	Death.Cut:
	Death.Saw:
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("NoGutsFatso_RemovedWeapon", 1);
		TNT1 A -1;
	Stop;}}
	


CLASS FatalizedFatso2: DeadFat { 
Default 
{Health 500;}
States
{
	Spawn:
		FAFT R -1;
	Stop; 
	Death.Cutless:
	Death:
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
	Stop;}}
	
CLASS DeadFattyHoles: Deadfat { 
States
{
	Spawn:
		FAT3 FFFFFFFFFFFFFFFFF 10;
		FAT3 FFFFF 1 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
		FAT3 F -1;
	Stop;
 
    Death.flames:
    Death.burn:
    Death.Plasma: Death.Plasma2:
        TNT1 A 0;
        TNT1 A 0 A_Scream;
        TNT1 A 0 A_NoBlocking;
        TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
	    TNT1 AAAA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL AAAAAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
        CARB OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 10 a_spawnprojectile("Explosion_Smoke", 1, 0, random(0, 360), 2, random(0, 160));
        CARB O -1;
	Stop;
	Death.Cutless: 
	Death.Cut:
	Death.Saw:
	Death:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		FAT3 G 1 A_SpawnItem("DeadFattyHolesNoArm", 1);
	Stop;
	}
}

CLASS DeadFattyHolesNoArm: Deadfat { 
States
{
	Spawn:
		FAT3 G -1;
	Stop;
    Death.flames:
    Death.burn:
    Death.Plasma: Death.Plasma2:
        TNT1 A 0;
        TNT1 A 0 A_Scream;
        TNT1 A 0 A_NoBlocking;
        TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
	    TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	    TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	EXPL AAAAAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
        CARB OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 10 a_spawnprojectile("Explosion_Smoke", 1, 0, random(0, 360), 2, random(0, 160));
        CARB O -1;
	Stop;
       Death.Cutless: 
	   Death.Cut:
	   Death.Saw:
	   Death:
	TNT1 A 0;
	TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
	FAT3 X -1;
	Stop;
	}
}

CLASS DeadFatsoNoArm: DeadFat { 
Default 
{Health 500;} States{Spawn:
	XFT1 D -1;
        Stop   ;
	
       Death:
        TNT1 A 0 A_SpawnItem("GutsPile");
	 TNT1 A 0 A_NoBlocking;
	 TNT1 AAA 0 {pb_blood_and_gore_event.ultra_gore_spawner(self);}
	 TNT1 AAAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAAA 0 a_spawnprojectile("XDeath2", 25, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAAA 0 a_spawnprojectile("XDeath3", 25, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 30, 0, random(0, 360), 2, random(40, 90));
	 TNT1 AAAAAAA 0 a_spawnprojectile("XDeathSkinPiece2", 25, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAAA 0 a_spawnprojectile("XDeathSkinPiece1", 25, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AAAAAAAA 0 a_spawnprojectile("SmallSuperGore", 30, 0, random(0, 360), 2, random(10, 170));
	 TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 20, 0, random(0, 360), 2, random(0, 40));
	TNT1 AA 0 a_spawnprojectile("XDeathMancubusLeg", 20, 0, random(0, 360), 2, random(40, 160));
	Stop;}}	

CLASS DeadFatSlump: Deadfat
{ 
States
{
	Spawn:
		MXD1 IIIIIIIIIIIIIIII 10;
		MXD1 IIII 1 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
		MXD1 I -1;
	Stop;
    Death.flames:
    Death.burn:
    Death.Plasma: Death.Plasma2:
        TNT1 A 0;
        TNT1 A 0 A_Scream;
        TNT1 A 0 A_NoBlocking;
        TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
	    TNT1 AAAA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	EXPL AAAAAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
        CARB OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 10 a_spawnprojectile("Explosion_Smoke", 1, 0, random(0, 360), 2, random(0, 160));
        CARB O -1;
	Stop;
	Death.Cutless: 
	Death.Cut:
	Death.Saw:
	Death:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		FAT3 Z 1 A_SpawnItem("DeadFatSlumpNoArm", 1);
	Stop;
	}
}

CLASS DeadFatSlumpNoArm: Deadfat { 
States
{
	Spawn:
		FAT3 Z -1;
    stop;
	
	Death.flames:
    Death.burn:
    Death.Plasma:
	Death.Plasma2:
        TNT1 A 0;
        TNT1 A 0 A_Scream;
        TNT1 A 0 A_NoBlocking;
        TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
	    TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	    TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL AAAAAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
        CARB OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 10 a_spawnprojectile("Explosion_Smoke", 1, 0, random(0, 360), 2, random(0, 160));
        CARB O -1;
	Stop;
	Death.Cutless: 
	Death.Cut:
	Death.Saw:
	Death:
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		FAT3 Y -1 ;
	Stop;
	}
}



	
	
	

	
	
CLASS DyingFatso01: NoGutsFatso { 
	Default {
 Scale 1.0 ;
Health 130 ;
Radius 28;
Height 56;
-CLIENTSIDEONLY;
	}
States
	{Spawn:
		XFT1 A 1 A_PlaySound("fatso/pain");
        XFT1 EEEEEEEEEEEEEEEE 3 a_spawnprojectile("Brutal_LiquidBlood2", 40, 0, random(0, 360), 2, random(30, 50));
		TNT1 A 0 a_jumpif(random(0, 10) < 7, "spawn");

		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		XFT1 BC 4;
		TNT1 A 0 A_SpawnItem("DeadFatsoNoArm");
	Stop;
	
	Death:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_PlaySound("fatso/pain");
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 30, 0, random(0, 360), 2, random(50, 130));
		XFT2 AAAAAAA 2 a_spawnprojectile("Brutal_LiquidBlood2", 50, 0, random(0, 360), 2, random(30, 50));
		TNT1 A 0 A_SpawnItem("DyingFatso02");
	Stop;
		}}	
		
		
		
CLASS DyingFatso02: DyingFatso01
{ 
	Default {
 Scale 1.0 ;
Health 130;
	}
 States
	{Spawn:
		XFT2 AAAAAAAAAAAAAAAAAAAAAAAAAAAA 2 a_spawnprojectile("Brutal_LiquidBlood2", 50, 0, random(0, 360), 2, random(30, 50));
		XFT2 BC 4;
		XFT2 D -1;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
	Stop;
	
	Death:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("MancubusHeadExplode", 0, 50);
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		XFT3 AAA 2 a_spawnprojectile("Brutal_LiquidBlood2", 50, 0, random(0, 360), 2, random(30, 50));
		TNT1 A 0 A_SpawnItem("DyingFatso03");
	Stop;
}}		



CLASS DyingFatso03: DyingFatso02 { 
Default {
	Scale 1.0;
	Health 130;
}
 States
{
	Spawn:
		XFT3 AAAAAAAAAAAAAAAAAAAAAAAAAAAA 2 a_spawnprojectile("Brutal_LiquidBlood2", 50, 0, random(0, 360), 2, random(30, 50));
		XFT3 B 4;
		XFT3 D -1;
		
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
	Stop;
	
	Death:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("RipGuts", 0, 40);
		TNT1 AAA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAAA 0 a_spawnprojectile("XDeath2", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath4", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathMancubusTorso", 30, 0, random(0, 360), 2, random(40, 160));
		XFT4 AAAAAABBBC 2 a_spawnprojectile("Brutal_LiquidBlood2", 40, 0, random(0, 360), 2, random(30, 50));
		XFT4 C -1;
	Stop;
}

}