CLASS pb_Plasma_Zombie : commando_base// Replaces ChaingunGuy
{ 
Default {
	Scale 1.05;
	Health 75;
	//SpawnID 1180;
	////DropItem "Cell";
	proto_zombieman_class.max_magazine_size 20;
}

States
{
	Death.Shrink:
		TNT1 A 1 A_PlaySound("Shrink", 3);
/*		TNT1 A 0 A_SpawnItemEx ("PlasmaZombieShrinkFX1", 0, 0,  5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("PlasmaZombieShrinkFX2", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("PlasmaZombieShrinkFX3", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("PlasmaZombieShrinkFX4", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("PlasmaZombieShrinkFX5", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("PlasmaZombieShrinkFX6", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("PlasmaZombieShrinkFX7", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("LilPlasmaZombie", 1);*/
	stop;

	Spawn:
		TNT1 A 0;
 		TNT1 A 0 {self.ammo_amount = random(0, max_magazine_size);} //A_GiveInventory("ZombieManAmmo", random(1,10));
	STAND:
		ZMAY BB 10 A_Look();
	Loop;
		
	SearchForPlayer:
	Idle:
		TNT1 A 0 A_ClearTarget();
		TNT1 A 0 A_TakeInventory("EnemyMemory", 30);
		////TNT1 A 0 A_giveInventory("SKZombieman", 1);
		ZMAY AA 10 A_Look();		
		ZMAY A 4 A_Look();
		TNT1 A 0 A_PlaySound("humans/step",3);
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		ZMAY B 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		ZMAY C 4 A_Look();
		TNT1 A 0 A_PlaySound("humans/step",3);
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		ZMAY D 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		
		TNT1 A 0 A_Jump(128, "Idle");
		ZMAY A 4 A_Look();
		TNT1 A 0 A_PlaySound("humans/step",3);
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		ZMAY B 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		ZMAY C 4 A_Look();
		TNT1 A 0 A_PlaySound("humans/step",3);
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		ZMAY D 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
	Loop;
		
		
	FallBack:
		TNT1 A 0 A_CheckSight("Advance");
		TNT1 A 0 {self.bNODROPOFF = true;}
		ZMAY D 2 A_FaceTarget();
		ZMAY D 2 A_Recoil(2);
		TNT1 A 0 A_jump(64, "Missile");
		TNT1 A 0 A_PlaySound("humans/step",3);
		ZMAY C 2 A_FaceTarget();
		ZMAY C 2 A_Recoil(2);
		ZMAY B 2 A_FaceTarget();
		ZMAY B 2 A_Recoil(2);
		TNT1 A 0 A_PlaySound("humans/step",3);
		ZMAY A 2 A_FaceTarget();
		ZMAY A 2 A_Recoil(2);
		TNT1 A 0 A_PlaySound("humans/step",3);
		ZMAY D 2 A_FaceTarget();
		ZMAY D 2 A_Recoil(2);
		TNT1 A 0 A_jump(64, "Missile");
		ZMAY C 2 A_FaceTarget();
		ZMAY C 2 A_Recoil(2);
		TNT1 A 0 A_PlaySound("humans/step",3);
		ZMAY B 2 A_FaceTarget();
		ZMAY B 2 A_Recoil(2);
		ZMAY A 2 A_FaceTarget();
		ZMAY A 2 A_Recoil(2);
		TNT1 A 0 A_PlaySound("humans/step",3);
	GOto Missile;
		
	See:
		TNT1 A 0 A_JumpIfHealthLower(1, "Death");
		TNT1 A 0 {self.bNODROPOFF = false;}
		//TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 A_TakeInventory("EnemyMemory", 15);
		TNT1 A 0 A_CheckSight("SeeNeverSeen");
		Goto SeeContinue;
		
	SeeContinue:
		TNT1 A 0 A_JumpIfHealthLower(1, "Death");
		TNT1 A 0 {self.bSOLID = true;}
		TNT1 A 0 {self.bSHOOTABLE = true;}
		TNT1 A 0 {self.bGHOST = false;}
		TNT1 A 0 {self.bINVULNERABLE = false;}
		TNT1 A 0 A_JumpIfCloser(200, "FallBack");
	Advance:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		TNT1 A 0 A_JumpIfInventory("EnemyMemory", 15, "SearchForPlayer");
		TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
		ZMAY AABB 2 A_Chase();
		//TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 A_PlaySound("humans/step",3);
		ZMAY CCDD 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
	Loop;
		
	SeeNeverSeen:
		TNT1 A 0 A_JumpIfCloser(200, "FallBack");
	Advance:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		ZMAY AA 2 A_Chase();
		//TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		ZMAY BB 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
		ZMAY CCDD 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
	Loop;
		
	Missile:
		//TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 {self.ammo_amount --;}//A_GiveInventory("ZombieManAmmo", 2);
		
		ZMAY E 8 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		TNT1 A 0 A_PlaySound("PLSM9",3);
		TNT1 A 0 a_spawnprojectile("Blue_FlareSpawn",0,0,0,0);
		ZMAY F 3 BRIGHT a_spawnprojectile("ZombiePlasma", 32, 0, random(-1, 1), 1, random(-3, 3));
		
		ZMAY E 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		TNT1 A 0 A_PlaySound("PLSM9",3);
		TNT1 A 0 a_spawnprojectile("Blue_FlareSpawn",0,0,0,0);
		ZMAY F 3 BRIGHT a_spawnprojectile("ZombiePlasma", 32, 0, random(-2, 2), 1, random(-3, 3));
		
		ZMAY E 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		TNT1 A 0 A_PlaySound("PLSM9",3);
		TNT1 A 0 a_spawnprojectile("Blue_FlareSpawn",0,0,0,0);
		ZMAY F 3 BRIGHT a_spawnprojectile("ZombiePlasma", 32, 0, random(-2, 2), 1, random(-3, 3));
		ZMAY E 6 A_FaceTarget();
		TNT1 A 0 pb_check_reloading("reload");//A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
	Goto SeeContinue;
		
	Reload:
		TNT1 A 0 {self.ammo_amount = max_magazine_size;}//A_TakeInventory("ZombieManAmmo", 20);
		ZMAY E 3;
		ZMAY E 1 a_spawnprojectile("PlasmaCaseSpawn", 38, 0, random(-11, 11), 0);
		TNT1 A 0 A_PlaySound("PLSOFF");
		ZMAY Z 8;
		ZMAY W 8;
		ZMAY X 8;
		ZMAY Y 8 A_PlaySound("PLSCLICK");
		ZMAY Z 8;
		ZMAY A 8;
		Goto SeeContinue;
		
	Pain.Avoid:
		TNT1 A 0;
		TNT1 A 0 A_Jump(255, "AvoidLeft", "AvoidRight");
		Goto AvoidGeneral;
		
	AvoidLeft:
		ZMAY D 1 A_FaceTarget();
		TNT1 A 0 ThrustThing(angle*256/360+192, 15, 0, 0);
		YRO2 ABCDEFGH 2 A_FaceTarget();
		Goto Missile;
	AvoidRight:
		ZMAY D 1 A_FaceTarget();
		TNT1 A 0 ThrustThing(angle*256/360+64, 15, 0, 0);
		YRO1 ABCDEFGH 2 A_FaceTarget();
		Goto Missile;
	AvoidGeneral:
		ZMAY AABBCC 3 A_FastChase();
		Goto Missile;
		
		
	Pain.BlackHole:
		TNT1 A 0;
		ID19 A 1 A_Pain();
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
		//TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,8,0,1);
		ID19 A 1 A_facetarget();
		ID19 A 6 ThrustThing(angle*256/360+128, 20, 0, 0);
		ID19 A 8;
	Goto FallingAfterImpact;

	Pain.Kick:
	Pain.SuperKick:
	Pain.ExtremePunches:
		TNT1 A 0;
		ID19 Z 1 A_Pain();
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
		//TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		ID19 Z 1 A_facetarget();
		ID19 Z 6 ThrustThing(angle*256/360+128, 5, 0, 0);
		Goto FallingAfterImpact;
		
	Pain.ExplosiveImpact:
	Pain.Explosive:
		TNT1 A 0;
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
		//TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		ID19 ZZZZ 6;
		Goto FallingAfterImpact;
		
	FallingAfterImpact:
		ID19 B 1 A_GiveInventory ("FallingHeight", 1);
		ID19 B 1 A_CheckFloor("GetUp");
		TNT1 A 0 A_JumpIf (vel.z == 0, "GetUp");
		Loop;
		
	GetUp:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 5, "FallingDie");
		TNT1 A 0 A_TakeInventory("FallingHeight", 100);
		ID19 BBBBBBB 5 A_JumpIf(vel.z < 0, "FallingAfterImpact");
		TNT1 A 0 A_TakeInventory("IsDown", 1);
	Goto See;

	FallingDie:
		TNT1 A 0;
		TNT1 A 0  A_ChangeCountFlags(false);
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 A_SpawnItem("SplatteredSmall");
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 15, "Death.Stomp");
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 10, "FallingSuperDeath");
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 5, "FallingDeath");
	FallingDeath:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBLocking();
		//TNT1 A 0 A_SpawnItem ("Ploft");
		TNT1 AAAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (0, 360), 2, random (50, 130));
		ID19 AA 2;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DeadZombieman1");
		Stop;
		
	FallingDeath:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBLocking();
		//TNT1 A 0 A_SpawnItem ("Ploft");
		TNT1 AAAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (0, 360), 2, random (50, 130));
		ID19 AA 2;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		ID19 A -1;
		Stop;
		
	FallingSuperDeath:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBLocking();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 AAA 0 A_SpawnItem ("Ploft");
	Goto Death.ExplosiveImpact+1;
		
	Pain.KillMe:
	Pain.Taunt:
		TNT1 A 0;
	Goto Missile;
		
		
	Death.Fatality:
	Death.Fatality:
		TNT1 A 0 A_Jump(256, "Fatality1", "Fatality2");
	stop;
		
	Fatality1:
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("PlasmaZombieFatality",1);
		stop;
		
	Fatality2:
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("PlasmaZombieFatality2",1);
		stop;
		
	Death.KillMe:
	Death.Taunt:
	Death.Avoid:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("PlasmaZombie");
		TNT1 A 0;
	Stop;
		
	Death.Rare:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		13DG A 5 A_Scream();
		TNT1 A 0 a_spawnprojectile ("Brutal_LiquidBlood2", 28, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_PlaySound("PLSM9");
		TNT1 A 0 a_spawnprojectile ("ZombiePlasma", 24, 5, -20, 2, -20);
		13DG B 5 BRIGHT;
		13DG CD 5;
		TNT1 A 0 A_PlaySound("PLSM9");
		TNT1 A 0 a_spawnprojectile ("ZombiePlasma", 24, -5, 20, 2, 30);
		13DG E 5 BRIGHT;
		TNT1 A 0 A_NoBlocking();
		13DG FGHI 5;
		TNT1 A 0 A_PlaySound("BODYF",6);
		13DG I -1;
		Stop;
		
		
	DeathMirror:
		TNT1 A 0 A_Jump(64, "Death.Rare");
		ZMAY H 6 A_Scream();
		ZMAY J 6 A_NoBlocking();
		ZMAY K 6;
		ZMAY l 6;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		ZMAY l -1;
		Stop;
		
	Death:
		TNT1 A 0 A_Jump(128, "Death1", "Death2");
		TNT1 A 0 A_Jump(96, "Death.Arm");
		TNT1 A 0 A_Jump(64, "Death.Rare");
		//Death.Melee:
		ZMAY H 6 A_Scream();
		ZMAY J 6 A_NoBlocking();
		ZMAY K 6;
		ZMAY L 6;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DeadPlasmaZombie1");
		Stop;
		
	Death1:
		ZMS1 A 8 A_NoBlocking();
		ZMS1 B 5;
		ZMS1 C 5 A_Scream();
		ZMS1 D 5;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DeadPlasmaZombie2");
		Stop;
		
	Death2:
		ZMS2 A 8 A_NoBlocking();
		ZMS2 B 5;
		ZMS2 C 5 A_Scream();
		ZMS2 D 5;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DeadPlasmaZombie3");
		Stop;
		
		
	XDeath:
		//TNT1 A 0 A_JumpIfInTargetInventory("SSGSelected", 1, "Death.SSG");
		TNT1 A 0 A_Recoil(2);
		TNT1 A 1 A_ClearTarget();
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0;//A_FaceTarget
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 42, 0, random (0, 290), 2, random (10, 60));
		TNT1 AAA 0 a_spawnprojectile ("XDeath3", 42, 0, random (0, 290), 2, random (10, 60));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 42, 0, random (0, 190), 2, random (10, 60));
		TNT1 A 0 a_spawnprojectile ("XDeath4", 42, 0, random (0, 190), 2, random (10, 60));
		TNT1 A 0 a_spawnprojectile ("PlasmaZombieXDeath", 2, 0, random (0, 360), 2, random (0, 160));
		Stop;
		
	Death.Kick:
	Death.ExtremePunches:
	Death.Melee:
		ZMS5 A 1;// A_Chase("", "")
		ZMS5 A 1 A_Pain();
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(6);
		TNT1 A 0 ThrustThingZ(0,25,0,1);
		ZMS5 B 0 A_Scream();
		ZMS5 C 0 A_NoBlocking();
		ZMS5 BCDEF 6;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem ("DeadPlasmaZombieZMS5F");
	Stop;
		
	Death.Blast:
	Death.Railgun:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Jump(128, "Death.Blast2");
		TNT1 A 0 A_Scream();
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		Z3Z7 A 6 A_Stop();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		Z3Z7 BBBBBBBBBB 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (30, 60));
		Z3Z7 CCC 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (10, 40));
		Z3Z7 DD 3 a_spawnprojectile ("Brutal_LiquidBlood2", 6, 0, random (0, 360), 2, random (30, 60));
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem ("DeadPlasmaZombieZ3Z7E");
	Stop;
		
	Death.Blast2:
		TNT1 A 0 A_XScream();
		TNT1 A 0 a_spawnprojectile ("XDeathArm1", 42, 0, random (0, 360), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("Xdeath2", 16, 0, random (130, 210), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		Z3Z8 A 6 A_Stop();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		Z3Z8 BBBBBBBBBBBBBBBBBBB 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (30, 60));
		Z3Z8 CCC 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (10, 40));
		Z3Z8 DD 3 a_spawnprojectile ("Brutal_LiquidBlood2", 6, 0, random (0, 360), 2, random (30, 60));
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem ("DeadPlasmaZombieZ3Z8E");
		Stop;
		
	Death.Shotgun:
		TNT1 A 0 A_JumpIfCloser(140, "Death.Blast");
		TNT1 A 0 A_JumpIfCloser(300, "Death.Shotgunontheface");
		TNT1 A 0 A_Jump(96, "Death.Arm");
		Goto Death;
		
	Death.Shotgunontheface:
		TNT1 A 0;
		TNT1 A 0 A_Jump(160, "DeathShotgunFly");
		TNT1 A 0 A_Jump(34, "Death.Arm");
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_Pain();
		ZMAY H 1 A_FaceTarget();
		TNT1 A 0 A_Recoil(13);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		TNT1 A 0 A_JumpIf(vel.y == 0, "DeathShotgunFly");
		TNT1 A 0 A_Scream();
		TNT1 A 0 a_spawnprojectile ("MuchBlood2", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 35, 0, random (0, 360), 2, random (0, 160));
		ZM4Y ABCD 4;
		ZM4Y EFGHIJ 4 A_JumpIf((vel.Y == 0), "DSFStop");
		Goto DSFStop+1;
		
	DSFStop:
		//TNT1 A 0 A_SpawnItem("Ploft3");
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 a_spawnprojectile ("SuperWallRedBlood", 2, 0, random (170, 190), 2, random (0, 0));
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadPlasmaZombieZM4YJ");
		Stop;
		
	DeathShotgunFly:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 {self.bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil (6);
		ZMS5 A 5 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		ZMS5 A 5 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		ZMS5 B 5 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		ZMS5 C 5 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		ZMS5 D 5 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		ZMS5 E 5 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadPlasmaZombieZMS5F");
	Stop;
	
	TakeASit:
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		POS4 U 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItemEx("DeadPlasmaZombieman_Slumped", 10);
	Stop;
		
	Death.Arm:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile ("XDeathArm2", 35, 0, random (0, 360), 2, random (0, 160));
		ZM5Y B 9 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DyingPlasmaZombie", 2);
		Stop;
		
		
	HeadExploder:
		TNT1 A 0 A_Jump(72, "Death.HeadExplode");
		Goto death.MinorHead;
		
	Death.Head:
		//TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
		//TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		//TNT1 A 0 A_JumpIfInTargetInventory("HasCutingWeapon", 1, "Death.Decaptate");
		TNT1 A 0 A_JumpIfHealthLower(-200, "HeavyHead");
		TNT1 A 0 A_JumpIfHealthLower(-70, "Death.HeadExplode");
		//TNT1 A 0 A_JumpIfInTargetInventory("RandomHeadExploder", 1, "HeadExploder");
	death.MinorHead:
		TNT1 A 0;
		TNT1 A 0 A_Playsound("MinorHeadshot", 0);
		TNT1 A 0 A_Jump(96, "death.MinorHead3");
		TNT1 A 0 A_Jump(64, "death.MinorHead2");
		TNT1 A 0;
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile ("Brains4Blue", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AA 0 a_spawnprojectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 A 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		ZMS3 A 6 a_spawnprojectile ("MuchBlood2", 40, 0, random (0, 360), 2, random (0, 160));
		ZMS3 BC 8;
		TNT1 A 0 A_Scream();
		ZMS3 D 6 A_NoBlocking();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DeadPlasmaZombieZMS3E");
	Stop;
		
	DeathMinorHead2:
		MAYH G 8 a_spawnprojectile ("MuchBlood2", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_PlaySound("CHOKIN");
		TNT1 A 0 a_spawnprojectile ("Brains7", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("Teeth", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("TeethNoBounce", 50, 0, random (0, 360), 2, random (0, 160));
		MAYH H 8 A_NoBlocking();
		MAYH I 8;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_SpawnItem ("DeadPlasmaZombieMAYHJ");
	Stop;
		
	DeathMinorHead3:
		MAYH A 7 A_Scream();
		MAYH B 7 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile ("Brains2", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 A 0 a_spawnprojectile ("Brains4", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 A 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("Teeth", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		MAYH C 7 A_NoBlocking();
		MAYH D 7;
		MAYH E 7;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DeadPlasmaZombieMAYHF");
	Stop;
		
	Death.decaptate:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile ("XDeathPlasmaZombieHead", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("MuchBlood2", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 A 0 A_NoBlocking();
		ZMS8 AAAAABBBBBBBBBBCCCCC 2 a_spawnprojectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		ZMS8 DDDDEEEEEEEEEEEEEEEE 2 a_spawnprojectile ("Brutal_LiquidBlood2", 10, 0, random (0, 360), 2, random (10, 40));
		TNT1 A 0 A_SpawnItem ("DeadPlasmaZombieZMS8E");
	Stop;
		
	Death.HeadExplode:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_SpawnItem("PlasmaZombieHeadExplode", 0, 40);
		ZMS8 B 0 A_XScream();
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		ZMS8 C 0 A_NoBlocking();
		ZMS8 AAAAABBBBBBBBBBCCCCC 2 a_spawnprojectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		ZMS8 DDDDEEEEEEEEEEEEEEEE 2 a_spawnprojectile ("Brutal_LiquidBlood2", 10, 0, random (0, 360), 2, random (10, 40));
		TNT1 A 0 A_SpawnItem ("DeadPlasmaZombieZMS8E");
	Stop;
		
	HeavyHead:
		TNT1 A 0;//A_ClearTarget
		TNT1 A 0 A_SpawnItem("PlasmaZombieHeadExplode", 0, 40);
		TNT1 A 0 a_spawnprojectile ("MuchBlood2", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains2", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains3", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains4", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains5", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAAA 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		ZMS6 A 1;// A_Chase("", "")
		ZMS6 A 1 A_Pain();
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(10);
		TNT1 A 0 ThrustThingZ(0,35,0,1);
		TNT1 A 0 A_SpawnItem("PlasmaZombieHeadExplode", 0, 40);
		ZMS6 B 0 A_XScream();
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		ZMS6 C 0 A_NoBlocking();
		ZMS6 BCDEF 6;
		TNT1 A 0 A_PlaySound("BODYF",6);
		ZMS6 FFFFFFFFFFFFFFFFFFFF 4 a_spawnprojectile ("Brutal_LiquidBlood2", 10, 0, random (0, 360), 2, random (10, 40));
		TNT1 A 0 A_SpawnItem ("DeadPlasmaZombieZMS6F");
	Stop;
		
	Death.Leg:
		TNT1 A 0 a_spawnprojectile ("MuchBlood2", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathPlasmaZombieLeg", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Scream();
		//TNT1 A 0 A_SpawnItemEx ("PlasmaZombiemanGotHisLegBlowed",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	Stop;
		
		
	Death.SuperPunch:
	Death.SSG:
		MAYH O 1 A_Pain();
		MAYH O  1 A_FaceTarget();
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("LivingHeart", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 AA 0 a_spawnprojectile ("XDeathArm1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathPlasmaZombieHead", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		MAYH OOPPQR 6;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DeadPlasmaZombieMAYHR");
	Stop;
		
		
	Death.cutless:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
		TNT1 A 0 A_Jump(8, "Death.Arm");
		TNT1 A 0 A_Jump(54, "Death.Rare");
		TNT1 A 0 A_Jump(96, "Death.Massacre");
		TNT1 A 0 A_Jump(16, "Death.Tear");
		Goto Death.Massacre;
		
	Death.Massacre:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Scream();
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem ("BrutalizedPlasmaZombie", 1);
		Stop;
		
	Death.ExplosiveImpact:
		//TNT1 A 0 A_JumpIfInTargetInventory("SSGSelected", 1, "Death.SSG");
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 a_spawnprojectile ("Brains2", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains3", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains4Green", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains5", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile ("BrainBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathPlasmaZombieLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile ("BloodMistLarge", 40, 0, random (0, 360), 2, random (20, 90));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		ZMS9 AB 5;
		ZMS9 CDEF 5 A_CheckFloor ("Dead.ExplosiveImpact");
		ZMS9 FFFFFFFFFF 5 A_CheckFloor ("Dead.ExplosiveImpact");
		TNT1 A 0 A_SpawnItem ("DeadPlasmaZombieZMS9G");
	Stop;
		
	Dead.ExplosiveImpact:
		TNT1 AAAA 0 A_SpawnItem ("Blood");
		//TNT1 A 0 A_SpawnItem ("Ploft");
		TNT1 A 0 A_SpawnItem ("DeadPlasmaZombieZMS9G");
	Stop;
		
		
	Death.Saw:
	Death.Cut:
	Death.HKFT:
		TNT1 A 0 A_Jump(192, "Saw2");
		TNT1 AA 0 a_spawnprojectile ("MuchBlood2", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile ("RipPlasmaZombie", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		MAYH OOPPQR 6;
		TNT1 A 0 A_SpawnItem ("DeadPlasmaZombieMAYHR");
		Stop;
		
		
	Saw2:
		TNT1 AAA 0 a_spawnprojectile ("MuchBlood", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath1", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("BloodMist", random (30, 40), 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Scream();
		TNT1 O 0 A_NoBlocking();
		ZMS0 JJJJKKKK 2  a_spawnprojectile ("Brutal_LiquidBlood2", random(28, 34), 0, random (0, 360), 2, random (30, 60));
		TNT1 A 0 a_spawnprojectile ("XDeathHalfPlasmaZombie2", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		ZMS0 A 7 A_XScream();
		ZMS0 BCD 7;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		ZMS0 DDDDDDDDD 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (30, 60));
		TNT1 A 0 A_SpawnItem("DeadPlasmaZombieZMS0D");
		Stop;
		
	Death.Tear:
		TNT1 A 0 A_Jump(32, "Saw2");
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAAA 0 a_spawnprojectile ("Instestin", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 42, 0, random (0, 360), 2, random (0, 160));
		ZMS7 ABCDE 5;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem ("DeadPlasmaZombieZMS7F");
		Stop;
		
		
	Death.Ice:
	Death.Freeze:
	Death.Frost:
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		//TNT1 A 0 A_SpawnItem("FrozenPlasmaZombie");
	Stop;
		// TNT1 A 0 A_SpawnItem ("DeadZombieManFacingFront")
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
	Stop;
		
	Pain:
		//TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, 6);
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBlood", 35, 0, random (0, 360), 2, random (0, 160));
		ZMAY G 3;
		ZMAY G 3 A_Pain();
		Goto See;
		TNT1 AAAA 0;
		TNT1 A 0 A_Pain();
		ID19 AAAABB 10;
		TNT1 A 0 A_TakeInventory("IsDown", 1);
		Goto See;
		
	Possession:
		TNT1 A 0 A_SetInvulnerable();
		ZMAY G 3;
		ZMAY G 3 A_Pain();
 		TNT1 A 0 A_UnSetInvulnerable();
		Goto See;
		
	Pain.Stun:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx ("StunElectrocute", random (-4, 4), random (-4, 4),  random (16, 32), 0, 0);
		ZMAY G 1 A_Pain();
		ZMAY GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		ZMAY G 1 A_Pain();
		ZMAY GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		ZMAY G 1 A_Pain();
		ZMAY GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		ZMAY G 1 A_Pain();
		ZMAY GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		ZMAY G 1 A_Pain();
		ZMAY GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		ZMAY G 1 A_Pain();
		Goto See;
		
	Pain.Melee:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInventory ("SKZombieMan", 1, "StealthKill");
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, 6);
		ZMAY G 3;
		ZMAY G 3 A_Pain();
		Goto See;
		TNT1 AAAA 0;
		TNT1 A 0 A_Pain();
		ID19 AAAABB 10;
		//TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 A_TakeInventory("IsDown", 1);
	Goto See;
		
	StealthKill:
		TNT1 A 1;
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("SKPlasmaZombie", 1);
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Die("Stealthy");
		TNT1 A 0 A_Fall();
		TNT1 A 1;
	Stop;
}

}

CLASS ZombiePlasma : pb_projectile_base
{ 
Default {
	DamageFunction (random(7,9));
	Speed 20;
}

}


CLASS DeadPlasmaZombie_Half: ZombieManTorso { 
Default
{Mass 300; Health 200;}
States
{
	Spawn:
		TNT1 A 0;
		PMAH Z -1;
	Stop;
	Death:
		TNT1 A 0 A_SpawnItem("GibsZ");
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;
	Death.Saw:
	Death.Saw:
	Death.Cutless:
	Goto Death;
}
}
	
CLASS RipPlasmaZombie : ACTOR { 
Default {	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFACTOR 0.5;
	BounceType "Doom";
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}

States
{
	Spawn:
		TNT1 AAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("DeadPlasmaZombie_Half", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAA 0 a_spawnprojectile ("Instestin2", 32, 0, random (0, 360), 2, random (0, 160));
	Death:
		TNT1 A 0;
	Stop;
}

}

CLASS DyingPlasmaZombie : SwitchableDecoration { 
Default {
	Radius 16;
	Height 28;
	Health 60;
	PainSound "grunt/pain";
	PainChance 255;
	PainChance "Fatality", 256;
	DamageFactor "Blood", 0.0; DamageFactor "BlueBlood", 0.0; DamageFactor "GreenBlood", 0.0;
	DamageFactor "Avoid", 0.0;
	DamageFactor "Leg", 0.0;
	DamageFactor "Kick", 6.0;
	DamageFactor "SuperKick", 6.0;
	DamageFactor "Fatality", 6.0;
	DamageFactor "bloodsplasher", 0.0;    DamageFactor "tinybloodsplasher", 0.0;
    DamageFactor "superbloodsplasher", 0.0;    DamageFactor "smallbloodsplasher", 0.0;
	DamageFactor "BlueBloodSplasher", 0.0;
	DamageFactor "BlueSuperBloodSplasher", 0.0;
	Mass 50;
	-SOLID;
	+SHOOTABLE;
	+FLOORCLIP;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
}

States
{
	Death.Fatality:
	Death.SuperPunch:
	Active:
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_GiveToTarget("HasPlasmaZombieShield", 1);
		//TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
		ZM5Y B 8;
	Stop;
	
	Death.fire:
	Death.Flames:
		//TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("DyingZombiemanInFlames");
	Stop;
	
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_PlaySound ("BURNZOM");
		ZM5Y B 10;
		TNT1 A 0 A_Jump(120, "Death");
	Suffer:
		ZM5Y CCCCCC 2 a_spawnprojectile ("Brutal_LiquidBlood", 18, 1, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("BloodDying", 0, 20);
		ZM5Y BBBBBB 2 a_spawnprojectile ("Brutal_LiquidBlood", 18, 1, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("BloodDying", 0, 20);
		TNT1 A 0 A_Jump(12, "LastStand");
		//TNT1 A 0 A_GiveInventory("DeathTimer1", 1);
		//TNT1 A 0 A_JumpIfInventory("DeathTimer1", 10, "GotoDeath");
	Loop;

	GotoDeath:
		TNT1 A 0 A_PlaySound("BLANKSND");
		TNT1 A 0;
	Goto Death;
	
	Death.Saw:
	Death.Cutless:
	Death:
	LastStand:
	TNT1 A 0 A_PlaySound ("grunt/death");
	TNT1 A 0 A_SpawnItem ("BrutalizedPlasmaZombieStop2");
	Stop;
	
	Death.Head:
	Death.Decaptate:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("headex", 0);
		TNT1 AAAA 0 a_spawnprojectile ("Brains1", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains3", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains4", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains5", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_XScream();
		//TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile ("BrainBlood", 37, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem ("BrutalizedPlasmaZombieStop4", 1);
	Stop;
	
	Death.Shotgun:
	TNT1 A 0 A_PlaySound("BLANKSND");
	TNT1 A 0 a_spawnprojectile ("MuchBlood2", 35, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_Scream();
	TNT1 A 0 ThrustThingZ(0,30,0,1);
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_SpawnItem ("BrutalizedPlasmaZombieStop2");
	Stop;
	
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("BLANKSND");
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		XBRN AA 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
		TNT1 AAAA 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		//TNT1 A 0 A_SpawnItem ("CrueltyBonus5Armor");
		XBRN BB 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
		TNT1 A 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
		XBRN CC 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
		TNT1 AAAAA 0 a_spawnprojectile ("PlasmaParticleX", 48, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAA 0 a_spawnprojectile ("PlasmaParticleX", 42, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 0;
	Stop;
	
	Xdeath:
	Death.SuperPunch:
	Death.SSG:
		TNT1 A 0 A_PlaySound("BLANKSND");
		//TNT1 A 0 A_SpawnItem ("CrueltyBonus10Armor");
		TNT1 AAAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeath5", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("xdeath1", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAA 0 a_spawnprojectile ("xdeath3", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathArm1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathPlasmaZombieHead", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem ("BrutalizedPlasmaZombieStop2");
	Stop;
	
	//LastStand:
	/*
	        TNT1 A 0 A_PlaySound("BLANKSND")
		TNT1 A 0 A_NoBlocking
		TNT1 A 0 A_Pain
		TNT1 A 0 A_SpawnItem ("SergeantLastStand2")
		Stop*/
	
}
}

CLASS FatalizedPlasmaZombie : ACTOR { 
States{Spawn:
	    FPMA PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP 5 a_spawnprojectile ("ExplosionSmoke", 1, 0, random (0, 360), 2, random (0, 160));
	FPMA P -1;
        Stop; }}
	
CLASS FatalizedPlasmaZombie2 : ACTOR { 
States{Spawn:
	    FPMA SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 5 a_spawnprojectile ("ExplosionSmoke", 1, 0, random (0, 360), 2, random (0, 160));
	FPMA S -1;
        Stop; }}	
	
CLASS BrutalizedPlasmaZombie : SwitchableDecoration
{ 
Default
{
	Radius 16;
	Height 40;
	Health 35;
	PainSound "grunt/pain";
	PainChance 255;
	Mass 0x7FFFFFFF;
	-SOLID;
	+SHOOTABLE
	+FLOORCLIP;

	DamageFactor "bloodsplasher", 0.0;  
	DamageFactor "tinybloodsplasher", 0.0;
    DamageFactor "superbloodsplasher", 0.0;    
	DamageFactor "smallbloodsplasher", 0.0;
	DamageFactor "BlueBloodSplasher", 0.0;
	DamageFactor "BlueSuperBloodSplasher", 0.0;

	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	Scale 1.0;
}

States
{
	Death.Fatality:
	Death.SuperPunch:
	Active:
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_GiveToTarget("HasPlasmaZombieShield", 1);
		//TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
		ZM5Y A 8;
	Stop;
		
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Recoil(2);
		TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
	Pain:
		ZM5Y A 35;
	Goto DieNow;
		
	DieNow:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem ("BrutalizedPlasmaZombieStop");
	Stop;
		
	Death:
		TNT1 A 0;
		TNT1 AAAA 0 a_spawnprojectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains2", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains3", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains4", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains5", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile ("BrainBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Recoil(2);
		TNT1 A 0 a_spawnprojectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
		ZM5Y B 16;
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem ("BrutalizedPlasmaZombie2");
	Stop;
		
	Death.SSG:
	XDeath:
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("LivingHeart", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("XDeathArm1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathPlasmaZombieHead", 32, 0, random (170, 190), 2, random (0, 40));
	Stop;
		
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		XBRN AA 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
		TNT1 AAAA 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		//TNT1 A 0 A_SpawnItem ("CrueltyBonus5Armor");
		XBRN BB 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
		TNT1 A 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
		XBRN CC 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
		TNT1 AAAAA 0 a_spawnprojectile ("PlasmaParticleX", 48, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAA 0 a_spawnprojectile ("PlasmaParticleX", 42, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 0;
	Stop;
}}

CLASS DeadPlasmaZombie1: pb_blood_and_gore_base
{
States
{
	Spawn:
		ZMAY L -1;
	Stop;
	
	Raise:
		TNT1 A 2 a_spawnprojectile ("RealFlameTrailsSmall", 6, 0, random (0, 360), 2, random (70, 110));
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 2 a_spawnprojectile ("RealFlameTrailsSmall", 6, 0, random (0, 360), 2, random (70, 110));
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 0 A_SpawnItem("TeleportFog");
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem ("PlasmaZombie");
	Stop;
	
	
	Death:
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 a_spawnprojectile ("XDeathArm1", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 a_spawnprojectile ("XDeathPlasmaZombieLeg", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAA 0 a_spawnprojectile ("BloodMist", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 A_SpawnItem ("DeadPlasmaZombieZMS9G");
	Stop;
}

}
	   
CLASS DeadPlasmaZombieZM4YJ: DeadPlasmaZombie1 { 
    States
    {
	Spawn:
	ZM4Y J -1;
Stop;}}

CLASS DeadPlasmaZombieZMS6F: DeadPlasmaZombie1 { 
    States
    {
	Spawn:
	ZMS6 F -1;
	Stop;
	
	Death:
	TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AAAA 0 a_spawnprojectile ("BloodMist", 15, 0, random (0, 360), 2, random (0, 180));
	TNT1 A 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;
}}
   
CLASS DeadPlasmaZombieZ3Z8E: DeadPlasmaZombie1 { 
    States
    {
	Spawn:
	Z3Z8 E -1;
	Stop;
	
	Death:
	TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AAAA 0 a_spawnprojectile ("BloodMist", 15, 0, random (0, 360), 2, random (0, 180));
	TNT1 A 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;
}}
	
CLASS DeadPlasmaZombieMAYHR: DeadPlasmaZombie1 { 
    States
    {
	Spawn:
	MAYH R -1;
	Stop;
	
	Death:
	TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AAAA 0 a_spawnprojectile ("BloodMist", 15, 0, random (0, 360), 2, random (0, 180));
	TNT1 A 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;
}}


CLASS DeadPlasmaZombieZ3Z7E: DeadPlasmaZombie1 { 
    States
    {
	Spawn:
	Z3Z7 E -1;
	Stop;
	
	Death:
	TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AAAA 0 a_spawnprojectile ("BloodMist", 15, 0, random (0, 360), 2, random (0, 180));
	TNT1 A 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;
}}

CLASS DeadPlasmaZombieZMS7F: DeadPlasmaZombie1 { 
    States
    {
	Spawn:
	ZMS7 F -1;
Stop;}}

CLASS DeadPlasmaZombieZMS5F: DeadPlasmaZombie1 { 
    States
    {
	Spawn:
	ZMS5 F -1;
Stop;}}

CLASS DeadPlasmaZombieZMS3E: DeadPlasmaZombie1 { 
    States
    {
	Spawn:
	ZMS3 E -1;
Stop;}}


CLASS DeadPlasmaZombieMAYHJ: DeadPlasmaZombie1 { 
    States
    {
	Spawn:
	MAYH J -1;
Stop;}}



CLASS DeadPlasmaZombieMAYHF: DeadPlasmaZombie1 { 
    States
    {
	Spawn:
	MAYH F -1;
Stop;}}
	
//PMAH F -1
CLASS DeadPlasmaZombiePMAHF: DeadPlasmaZombie1 { 
    States
    {
	Spawn:
	PMAH F -1;
Stop;}}

CLASS DeadPlasmaZombieZMS9G: DeadPlasmaZombie1 { 
    States
    {
	Spawn:
	ZMS9 G -1;
	Stop;
	
	Death:
	TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AAAA 0 a_spawnprojectile ("BloodMist", 15, 0, random (0, 360), 2, random (0, 180));
	TNT1 A 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;
}}

CLASS DeadPlasmaZombieZMS8E: DeadPlasmaZombie1 { 
    States
    {
	Spawn:
	ZMS8 E -1;
	Stop;
	
	Death:
	TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AAAA 0 a_spawnprojectile ("BloodMist", 15, 0, random (0, 360), 2, random (0, 180));
	TNT1 A 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;
}}


CLASS DeadPlasmaZombie2: DeadPlasmaZombie1 { 
    States
    {
	Spawn:
	ZMS1 D -1;
Stop;}}

CLASS DeadPlasmaZombie3: DeadPlasmaZombie1 { 
    States
    {
	Spawn:
	ZMS2 D -1;
Stop;}}

CLASS BrutalizedPlasmaZombieStop: pb_blood_and_gore_base { 
    States
    {
	Spawn:
	ZMAY JKL 5 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
	ZMAY L -1;
Stop;}}
	   
CLASS BrutalizedPlasmaZombie2: BrutalizedPlasmaZombie { 
	States
	{
	Spawn:
	TNT1 A 0 A_PlaySound ("BURNZOM");
	Pain:
	ZM5Y BCBCBCB 5 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
	Goto DieNow;
	
	DieNow:
	TNT1 A 0;
	TNT1 A 0 A_SpawnItem ("BrutalizedPlasmaZombieStop2");
	Stop;
	
	Death:
	TNT1 A 0;
	TNT1 A 0 A_Recoil(2);
	TNT1 A 0 a_spawnprojectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
	ZM5Y D 12;
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0;
	TNT1 A 0 A_SpawnItem ("BrutalizedPlasmaZombie3");
	Stop;
}}

CLASS BrutalizedPlasmaZombieStop2: pb_blood_and_gore_base { 
    States
    {
	Spawn:
	ZM5Y GH 5 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
	ZM5Y H -1;
Stop;}}
	   
CLASS BrutalizedPlasmaZombie3: BrutalizedPlasmaZombie { 
	States
	{
	Spawn:
	Pain:
	ZM5Y D 30 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
	Goto DieNow;
	
	DieNow:
	TNT1 A 0;
	TNT1 A 0 A_SpawnItem ("BrutalizedPlasmaZombieStop3");
	Stop;
	
	Death:
	TNT1 A 0;
	TNT1 A 0 A_Recoil(2);
	TNT1 A 0 a_spawnprojectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
	ZM5Y E 12;
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0;
	TNT1 A 0 A_SpawnItem ("BrutalizedPlasmaZombie4");
	Stop;
}}

CLASS BrutalizedPlasmaZombieStop3: pb_blood_and_gore_base { 
    States
    {
	Spawn:
	ZM5Y IJ 5 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
	ZM5Y J -1;
Stop;}}
	   
CLASS BrutalizedPlasmaZombie4: BrutalizedPlasmaZombie { 
	States
	{
	Spawn:
	Pain:
	ZM5Y EEEEEE 5 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
	Goto DieNow;
	
	DieNow:
	TNT1 A 0;
	TNT1 A 0 A_SpawnItem ("BrutalizedPlasmaZombieStop4");
	Stop;
	
	Death:
	TNT1 A 0;
	TNT1 A 0 A_Recoil(2);
	ZM5Y F 12;
	//TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
	TNT1 A 0 a_spawnprojectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0;
	TNT1 A 0 A_SpawnItem ("BrutalizedPlasmaZombieStop5");
	Stop;
}}

CLASS BrutalizedPlasmaZombieStop4: pb_blood_and_gore_base { 
    States
    {
	Spawn:
	ZM5Y KL 5 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
	ZM5Y L -1;
Stop;}}
	   
CLASS BrutalizedPlasmaZombieStop5: pb_blood_and_gore_base { 
    States
    {
	Spawn:
	ZM5Y F -1;
Stop;}}
	   
//
CLASS DeadPlasmaZombieZMS0D: pb_blood_and_gore_base { 
    States
    {
	Spawn:
	ZMS0 D -1;
Stop;}}
	   
CLASS DeadPlasmaZombieman_Slumped: ZombiemanTorso
{ 
Default
{
	+NOPAIN;
	Health 200;
	DamageFactor "Head", 15.0;
	Height 22;
	Radius 6;
	}
	
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Recoil(6);
		BR88 A 6;
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		BR88 A 16;
	Loop ;

	LayDown:
		TNT1 A 0 A_NoBlocking();
		ZMS1 D -1;
	Stop;

	XDeath:
	Death.Explosives:
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ZombieXDeath");
	Stop;
	
	Death.Head:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItemEx("PlasmaZombieHeadExplode", 0, 0, 22);
		TNT1 A 0 A_SpawnItem("DeadPlasmaZombieman_Slumped_NoHead");
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 AA 0 a_spawnprojectile ("XDeathArm1", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnItemEx("PlasmaZombieHeadExplode", 0, 0, 22);
		TNT1 A 0 A_SpawnItem("DeadZombiemanJustLegsAreLeft");
	Stop;
}}
	
	
CLASS DeadPlasmaZombieman_Slumped_NoHead: ZombiemanTorso { 
Default {
	+NOPAIN;
	Height 22;
}
States
{
	Spawn:
		TNT1 A 0;
		BR88 B 100;
	Loop ;
	
	XDeath:
	Death.Explosives:
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ZombieXDeath");
	Stop;
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 AA 0 a_spawnprojectile ("XDeathArm1", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnItem("DeadZombiemanJustLegsAreLeft");
	Stop;
}}
	
CLASS VeryFuckedUpBrutalizedPlasmaZombie: pb_blood_and_gore_base { 
	Default {
	Health 200;
	DamageFactor "ExplosiveImpact", 10.0;
	}
States{Spawn:
	TNT1 A 0;
	ZMS9 G -1;
	Stop;
	Death.ExplosiveImpact:
	TNT1 A 0 ThrustThingZ(0,30,0,1);
	ZMS9 ABCDEF 5;
	TNT1 A 0 A_SpawnItem ("VeryFuckedUpBrutalizedPlasmaZombie");
Stop;}}
/* 
CLASS ZombieRailgunner : PlasmaZombie
{}  

CLASS ZombieRailgunner70 : PlasmaZombie
{}
	
class ZombieRailgunner50 : PlasmaZombie
{}
	
class ZombieRailgunner30 : PlasmaZombie
{}
	
class SpreadFireZombie : PlasmaZombie
{}
*/