// --------------------------------------------------------------------------
// Plasma Gun
// --------------------------------------------------------------------------
class Psalm_Gun : weapon_slot_6_proto_class //Replaces PlasmaRifle
{
default
{
	Weapon.SlotNumber 6;
	Weapon.SelectionOrder 2;
	Weapon.slotpriority 0.1;

	Weapon.BobRangeX 0.3;
	Weapon.BobRangeY 0.5;
	Weapon.BobStyle "InverseSmooth";
	Weapon.BobSpeed 2.4;
	Inventory.MaxAmount 3;
	Inventory.Amount 2;//for dual wielding

	Weapon.AmmoUse1 0;
	Weapon.AmmoGive1 50;
	Weapon.AmmoUse2 0;
	Weapon.AmmoGive2 0;
	
	Inventory.PickupSound "PLSPICK";
	Weapon.AmmoType1 "pb_cell";
	Weapon.AmmoType2 "Psalm";
	+WEAPON.NOAUTOAIM;
	+WEAPON.NOALERT;
	+FLOORCLIP;
	+DONTGIB;
	Inventory.PickupMessage "You got the UAC-M1 Plasma Rifle! (Slot 6)";
	Tag "Pray to the great god Carmack";
}

override void doeffect()
{
	if(owner.player.readyweapon == self)
	{
		if(owner.player.findPsprite(psp_weapon) != null )
		{
			let ttt = Owner.player.FindPSprite(PSP_Weapon);
			if(self.instatesequence(ttt.curstate, self.findstate("althold") ) && (owner.player.cmd.buttons & BT_RELOAD) )
			{owner.Player.SetPSprite(PSP_WEAPON, self.findstate("DeCharge" ) ); }
		}
	}
	PB_Weapon_base.doeffect();
}

States
{
	Spawn:
		PLAS A -1;
	Stop;

	Select:
		TNT1 A 0 A_Overlay(-10, "FirstPersonLegsStand");
		TNT1 A 1 A_Raise(60);
	Wait;

	Ready:
		TNT1 A 0 A_PlaySound("PLSDRAW");
	Ready_loop:
		TNT1 A 0 A_PlaySound("PLSIDLE", 6,1,1);
		PLSG A 1 a_weaponready(WRF_ALLOWRELOAD);
		4LSG BCDEDCB 1 a_weaponready(WRF_ALLOWRELOAD);
		PLSG A 1 a_weaponready(WRF_ALLOWRELOAD);
	Loop;

	Fire:
		TNT1 A 0 A_WeaponOffset(0,32);
		TNT1 A 0 A_JumpIfInventory("Psalm",1,1);
	Goto Reload;
		TNT1 A 0 A_PlaySound("PLSM9",3);
		TNT1 A 0 A_AlertMonsters;
		TNT1 A 0 A_ZoomFactor(.985);
		PLSF A 1 BRIGHT a_fireprojectile("Plasma_Ball", 0, 1, 0, 0);
		tnt1 a 0 A_QuakeEx(1, 1, 1, 4, 0, 64, "", 0);
		TNT1 A 0 a_fireprojectile("GunFireSmoke", 0, 0, 0, 0, 0, 0);
		PLSF B 1 A_ZoomFactor(.970);
		PLSF C 1 A_ZoomFactor(.965);
		PLSF B 0 A_ZoomFactor(.985);
		TNT1 A 0 A_Takeinventory("Psalm",1);


		TNT1 A 0 A_ReFire;
		TNT1 A 0 A_ZoomFactor(1.0);
		TNT1 A 0 A_PlaySound("PLSCOOL",1);
		TNT1 A 0 A_Playsound("PLSCO0L",2);
		PLSG BCD 1;
		PLSG EEEEEE 3 a_fireprojectile("GunFireSmoke",0,0,0,5);
		PLSG DCB 1;
		TNT1 A 0 A_PlaySound("BEPBEP");
	Goto Ready_loop;

	AltFire:
		TNT1 A 0 A_WeaponOffset(0,32);
		TNT1 A 0 A_JumpIfInventory("Psalm",18,1);
	Goto Reload;
		TNT1 A 0
		{
			A_StopSound(6);
			A_AlertMonsters();
			A_PlaySound("ULTCHAR", 0);
		}
		PLSG A 11 A_ZoomFactor(0.995);
		PLHE A 4 BRIGHT A_PlaySound("PLSC_1", 1);
		PLHE B 4 BRIGHT A_PlaySound("PLSC_2", 2);
		PLHE C 4 BRIGHT A_PlaySound("PLSC_3", 3);
		PLHE D 4 BRIGHT A_PlaySound("PLSC_4", 4);	
		PLHE EFGHI 1 BRIGHT;
		PLSA ABCDCB 1 BRIGHT a_fireprojectile("Blue_FlareSpawn",0,0,0,0);
	AltHold:
		TNT1 A 0
		{
			A_PlaySound("PLSFULL", 7,1,1);
			A_SpawnItem("PlasmaGauntlet", 0, 1, 0, 0);
			A_QuakeEx(1, 1, 1, 4, 0, 64, "", 0);
			a_fireprojectile("Blue_FlareSpawn",0,0,0,0);
			A_SpawnItem("PlasmaGauntlet", 0, 1, 0, 0);
		}
		PLSA ABCDCB 1 BRIGHT
		{
			A_SpawnItem("PlasmaGauntlet", 0, 1, 0, 0);
			a_fireprojectile("Blue_FlareSpawn",0,0,0,0);
			A_SpawnItem("PlasmaGauntlet", 0, 1, 0, 0);
		}
		TNT1 A 0 A_ReFire;
		
		TNT1 A 0 A_StopSound(7);
		PLSG I 2 BRIGHT A_Recoil(1);
		TNT1 A 0 a_fireprojectile("Blue_FlareSpawn",-5,0,0,0);
		TNT1 AAAAAAAAAAAAAAAA 0 ;//a_fireprojectile("RailGunTrailSpark_Fast", 0, 0, random(-25,25), random(-13,13), 0, 0);
		TNT1 A 0 A_PlaySound("PLSULT", 7);
		TNT1 A 0 A_ZoomFactor(0.85);
		
		TNT1 A 0
		{
			for(int x = -7; x < 7; x += 2)
			{
				for(int y = -1; x < 2; x ++)
				{
					for(int z = -10; z < 10; z += 10)
					{
						a_fireprojectile("UltPlasma_Ball", x, 0, y, z );
						A_Takeinventory("Psalm",1);
					}
				}
			}
		}
		TNT1 A 0 A_SetPitch(Pitch - 1.15);


		PLSG J 1 A_ZoomFactor(0.90);
		PLSG K 1 A_ZoomFactor(0.95);		
		PLSG L 1 A_ZoomFactor(0.975);
		PLSG K 1 A_ZoomFactor(0.99);
		PLSG J 1 A_ZoomFactor(1.0);
		PLSU BCDE 1;
		PLSU FFFFFFFFFFFF 2 a_fireprojectile("GunFireSmoke",0,0,0,5);
		PLSG DCB 1;
		TNT1 A 0 A_JumpIfInventory("Psalm",1,1);
	Goto Reload;
		TNT1 A 0 A_PlaySound("BEPBEP");
	Goto Ready_loop;

	DeCharge:
		TNT1 A 0 A_StopSound(7);
		TNT1 A 0 A_PlaySound("PLSDEARG");
		TNT1 A 0 A_ZoomFactor(1.0);
		PLSA A 1 BRIGHT a_fireprojectile("Blue_FlareSpawn",0,0,0,0);
		PLSA B 1 BRIGHT a_fireprojectile("Blue_FlareSpawn",0,0,0,0);
		PLSA C 1 BRIGHT a_fireprojectile("Blue_FlareSpawn",0,0,0,0);
		PLSA D 1 BRIGHT a_fireprojectile("Blue_FlareSpawn",0,0,0,0);
		PLSA C 1 BRIGHT a_fireprojectile("Blue_FlareSpawn",0,0,0,0);
		PLHE I 2 BRIGHT;
		PLHE H 1 BRIGHT;
		PLHE G 2 BRIGHT;
		PLHE F 1 BRIGHT;
		PLHE E 2 BRIGHT;
		PLHE D 1 BRIGHT;
		PLHE C 2 BRIGHT;
		PLHE B 1 BRIGHT;
		PLHE A 2 BRIGHT;
		TNT1 A 0 A_PlaySound("BEPBEP", 5, 1.2);
		TNT1 A 0 A_ClearReFire;
	Goto Ready_loop;

	Reload:
		PLSR A 1 A_WeaponReady;
		TNT1 A 0 A_JumpIfInventory("Psalm",50,"ready_loop");
		TNT1 A 0 A_PlaySound("BEEEP");
		TNT1 A 0 A_JumpIfInventory("pb_cell",1,1);
	Goto Ready_loop;
		PLSR A 1;
		PLSR B 2 A_PlaySound("CELLPKUP", 20);
		PLSR C 1;
		PLSR D 2;
		PLSR E 1;
		PLSR F 2 A_StopSound(6);
		PLSR G 1 A_PlaySound("PLSOFF", 1);
		TNT1 A 0 a_fireprojectile("PlasmaCaseSpawn",-5,0,8,-4);
		PLSR HHHHHHHHIJK 2;
		PLSR L 1 A_PlaySound("PLREADY", 20);
		PLSR L 1 A_PlaySound("PLSRD", 21);
		PLSR LLMNO 2;
		PLSR C 1;
		PLSR B 2;
		TNT1 A 0 A_PlaySound("PLSCLICK");
		PLSR A 2
		{

			giveinventory("Psalm", 0);

			giveinventory("pb_cell", 0);


			inventory left_arm_ammo = findinventory("Psalm");

			
			inventory main_ammo = findinventory("pb_cell");
			
			do
			{

				left_arm_ammo.amount ++;

				main_ammo.amount --;
			}
			while( (left_arm_ammo).amount < (left_arm_ammo).maxamount && (main_ammo).amount > 0)
		}
	Goto Ready_loop;














	Deselect:
		TNT1 A 0 A_Zoomfactor(1.0);
		TNT1 A 0 A_StopSound(6);
		TNT1 A 0 A_PlaySound("PLSOFF", 1);
		PLS9 CBA 1;
		TNT1 A 0 A_Lower(80);
	Wait;	
	
	
	
	
	
	Steady:
	TNT1 A 1;
	Goto Ready;
	
	
	DualWieldBaby:
		TNT1 AAAAA 0;
		//TNT1 A 0 A_JumpIfInventory("Plasma_Gun", 3,"SwitchToDualWield");


		TNT1 AA 0;
		TNT1 A 0 A_Print("You need two plasma rifles to dual wield!");
	

	Goto Ready+9;
	
	SwitchToDualWield:
		TNT1 A 0 A_StopSound(6);
		//TNT1 A 0 A_SelectWeapon("DualPlasmaRifles");
	Goto Select;
	
	GunEmpty:
		PLSR A 1 A_WeaponReady;
		TNT1 AA 0;
		PLSR A 1 A_weaponready;
	Goto GunEmpty+3;
	
	Draw:
		TNT1 A 0 A_StopSound(6);
		TNT1 A 0 A_PlaySound("PLSOFF", 1);

		//TNT1 A 0 A_SpawnItem("Plasma_Gun", 1);
	Stop;
	
	DontNeedToReload:
	Goto Ready_loop;


	
	
	
	

	

	Flash:
	TNT1 A 4;
	Goto LightDone;

	
	////////////////////////////////////////Unloading	
	
	AlreadyUnloaded:

	Goto Ready+6;
	
	Unload:
		PLSR A 1 A_WeaponReady;
		//TNT1 A 0 A_JumpIfInventory("PlasmaRifleHasUnloaded", 1, "AlreadyUnloaded");
		TNT1 A 0 A_StopSound(6);
		TNT1 A 0 A_ZoomFactor(1.0);



		TNT1 A 0 A_JumpIfInventory("Psalm",1,3);
	Goto GunEmpty;
		TNT1 AAA 0;

		
		
		PLSR A 1;
		PLSR B 2 A_PlaySound("CELLPKUP");
		PLSR MMLKJIH 2;
		
		PLSR G 1;
		PLSR F 2;
		PLSR E 1;
		PLSR D 2;
		PLSR C 1;
		PLSR B 2;
		PLSR A 1;
		


		
	RemoveBullets:
		TNT1 AAAA 0;
		TNT1 A 0 A_JumpIfInventory("Psalm",1,3);
	Goto FinishUnload;
	TNT1 AAAAAA 0;
		TNT1 A 0 A_Takeinventory("Psalm",1);


		TNT1 A 0 A_Giveinventory("pb_cell",1);
	Goto RemoveBullets;
	
	FInishUnload:


	Goto GunEmpty+6;
	
	//////////////////////////////////////////Unloading
	
	FlashKicking:
	PLSG W 1;
	PLSG X 1;
	PLSG Y 1;
	PLSG Y 3;
	PLSG Z 3;
	PLSG Y 3;
	PLSG X 1;
	PLSG W 1;
	PLSG A 1;
	PLSG AAA 1;
	Stop;
	
	FlashAirKicking:
	PLSG W 1;
	PLSG X 1;
	PLSG Y 1;
	PLSG Y 3;
	PLSG Z 3;
	PLSG Y 3;
	PLSG X 1;
	PLSG W 1;
	PLSG A 1;
	PLSG AAAA 1;
	Stop;
	
	FlashSlideKicking:
	PLSU BC 2;
	PLSU DDDDDDEEEFF 2 ;
	Stop;
	
	FlashSlideKickingStop:
	//TNT1 A 0
	PLSU FEDCB 1;
	PLSG A 1;
	Stop;
	
	FlashPunching:
	PLSG W 1;
	PLSG X 1;
	PLSG Y 1;
	PLSG Y 3;
	PLSG Z 3;
	PLSG Y 3;
	PLSG X 1;
	PLSG W 1;
	PLSG A 1;
	PLSG AAA 1;
	Stop;
}
}

CLASS PlasmaGauntlet : ACTOR { 
	Default {
	
	Projectile;
	Height 12;
	Radius 40;
	Speed 6;
	Damagefunction (random(1,2));
	DamageType "Plasma";
	+NOEXTREMEDEATH;
	-EXTREMEDEATH;
	Obituary "%o became an electrical conductor for %k";
	}
	States
	{
	Spawn:
	TNT1 A 1;
	Stop;
}
}

CLASS Plasma_Ball: pb_projectile_base
{ 
Default
{
	Radius 10;
	Height 2;
	Speed 60;
	Damage 8;
	DamageType "Plasma";
	Decal "SmallerScorch";
	Projectile;
	+RANDOMIZE;
	
	//+SHOOTABLE
	-NOBLOCKMAP;
	+NOBLOOD;
	+NORADIUSDMG;
	+THRUSPECIES;
	+MTHRUSPECIES;
	Species "Marines";
	Health 5;
	
	renderstyle "Add";
	Scale 0.18;
	DeathSound "weapons/plasmax";
	//SeeSound "PLSM9"
	SeeSound "None";
	Obituary "$OB_MPPLASMARIFLE";
	}
	States
	{
	DM:
	TNT1 A 0;
	TNT1 A 0 {self.bTHRUSPECIES = 0;}
	TNT1 A 0 {self.bMTHRUSPECIES = 0;}
	Goto Spawn1;
	
	Spawn:
	TNT1 A 0;
	TNT1 A 0 ACS_ExecuteAlways(719, 0, 0, 0, 0);//Check if Coop
	
	Spawn1:
	DB19 ABCDEFGHIJKLMNOPQRSTUVWXYZ 2 BRIGHT;
	//	{	
	//	A_SpawnItem("PlasmaFlareSpawner",0,0);
	//A_SpawnItemEx("RailGunTrailSpark", random(1,-1), random(1,-1), random(1,-1), 0, 0, 0, 0, 128, 0);
	//}
	Loop;
	
	Xdeath:
	TNT1 A 0 A_SpawnItem ("Plasma_Puff", 0);
	//TNT1 A 0 A_SpawnItem ("RailPuff", 0)
	TNT1 A 0 a_spawnprojectile ("BluePlasmaFire", 0, 0, random (0, 360), 2, random (0, 360));
	//TNT1 A 0 A_SpawnItem("BluePlasmaRife")
	TNT1 AAAA 0; //a_spawnprojectile ("RailGunTrailSpark", 0, 0, random (0, 360), 2, random (0, 360));
	TNT1 B 1 A_Explode(6,50,0);
	TNT1 B 4;
	TNT2 AAA 9 a_spawnprojectile ("ExplosionSmoke", 1, 0, random (0, 360), 2, random (0, 160));
	
	Stop;
	
	Death:
	TNT1 A 0 A_SpawnItem ("Plasma_Puff", 0);
	//TNT1 A 0 A_SpawnItem ("RailPuff", 0)
	TNT1 B 1 A_Explode(6,50,1);
	TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 a_spawnprojectile ("BluePlasmaFire", 0, 0, random (0, 360), 2, random (0, 360));
	TNT1 AAAAA 0 a_spawnprojectile ("BluePlasmaParticle", 0, 0, random (0, 360), 2, random (0, 360));
	TNT1 B 4;
	TNT2 AAAAAAAAA 9 a_spawnprojectile ("ExplosionSmoke", 1, 0, random (0, 360), 2, random (0, 160));
	Stop;
}
}

/*
Spawn:
	TRAC A 1 BRIGHT
	TNT1 A 0 A_ChangeFlag("THRUACTORS", 0)
	Goto Fly
*/

CLASS MeatshieldPlasmaBall: Plasma_Ball { 
	Default {
	
	+THRUACTORS;
	}
	States
	{
	
	Spawn:
	DB19 A 1 BRIGHT;
	TNT1 A 0 {self.bTHRUACTORS = 0;}
	Spawn1:
	DB19 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 BRIGHT A_SpawnItem("PlasmaFlareSpawner",0,0);
	Loop;
}
}

CLASS UltPlasma_Ball: Plasma_Ball { 
	Default {
	
	Radius 10;
	Height 2;
	Speed 60;
	Damage 8;
	DamageType "Plasma";
	Decal "SmallerScorch";
	Projectile;
	+RANDOMIZE;
	
	//+SHOOTABLE
	-NOBLOCKMAP;
	+NOBLOOD;
	+NORADIUSDMG;
	+THRUSPECIES;
	+MTHRUSPECIES;
	Species "Marines";
	Health 5;
	
	renderstyle "Add";
	Scale 0.18;
	DeathSound "weapons/plasmax";
	//SeeSound "PLSM9"
	SeeSound "None";
	Obituary "$OB_MPPLASMARIFLE";
	}
	States
	{
	DM:
	TNT1 A 0;
	TNT1 A 0 {self.bTHRUSPECIES = 0;}
	TNT1 A 0 {self.bMTHRUSPECIES = 0;}
	Goto Spawn1;
	
	Spawn:
	TNT1 A 0;
	TNT1 A 0 ACS_ExecuteAlways(719, 0, 0, 0, 0);//Check if Coop
	
	Spawn1:
	DB19 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 BRIGHT A_SpawnItem("PlasmaFlareSpawner",0,0);
	Loop;
	
	Xdeath:
	TNT1 A 0 A_SpawnItem ("Plasma_Puff", 0);
	//TNT1 A 0 A_SpawnItem ("RailPuff", 0)
	TNT1 A 0 a_spawnprojectile ("BluePlasmaFire", 0, 0, random (0, 360), 2, random (0, 360));
	//TNT1 A 0 A_SpawnItem("BluePlasmaRife")
	TNT1 AAAAA 0 a_spawnprojectile ("BluePlasmaParticle", 0, 0, random (0, 360), 2, random (0, 360));
	TNT1 B 1 A_Explode(6,50,0);
	TNT1 B 4;
	TNT2 AAA 9 a_spawnprojectile ("ExplosionSmoke", 1, 0, random (0, 360), 2, random (0, 160));
	
	Stop;
	
	Death:
	TNT1 A 0 A_SpawnItem ("Plasma_Puff", 0);
	//TNT1 A 0 A_SpawnItem ("RailPuff", 0)
	TNT1 B 1 A_Explode(6,50,1);
	TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 a_spawnprojectile ("BluePlasmaFire", 0, 0, random (0, 360), 2, random (0, 360));
	TNT1 AAAAA 0 a_spawnprojectile ("BluePlasmaParticle", 0, 0, random (0, 360), 2, random (0, 360));
	TNT1 B 4;
	TNT2 AAAAAAAAA 9 a_spawnprojectile ("ExplosionSmoke", 1, 0, random (0, 360), 2, random (0, 160));
	Stop;
}
}

CLASS PlasmaBall75: Plasma_Ball { 
	Default {
	
	
	SeeSound "PLSM9";
	}
}

CLASS PlasmaBall76: Plasma_Ball { 
	Default {
	
	SeeSound "PLSULT";
	SeeSound "PLSULT";
	}
}
CLASS PlasmaBall65: Plasma_Ball { 
	Default {
	
	
	SeeSound "PLSM4";
	}
}

CLASS Psalm : Ammo
{ 
Default
{
	Inventory.Amount 0;
	Inventory.MaxAmount 50;
	Ammo.BackpackAmount 0;
	Ammo.BackpackMaxAmount 50;
	Inventory.Icon "PLASA0";
}

}