//PhasicKnightX from X-Weapon Hellsturm, BRUTALIZED!//Translation "16:47=112:127", "192:207=80:111", "168:191=64:79"
CLASS pb_cyber_Knight_X: knight_base// Replaces HellKnight
{
Default
{	
	Health 740;
	//SpawnID 2220;
	//Radius 24;
	//Height 64;
	Mass 1000;
	Speed 8;
	FastSpeed 10;
	Scale 1.1;
	MeleeDamage 15;

	PainChance "Kick", 255;
	PainChance "Stun", 255;
	PainChance "Extremepunches", 255;
	PainChance "Explosive", 255;
	PainChance 25;
	PainChance "Saw", 100;
	PainChance "Cut", 100;

	damagefactor "Crush", 10.0;
	damagefactor "GibRemoving", 0.0;
	DamageFactor "CauseObjectsToSplash", 0.0;
	damagefactor "SSG", 0.75;
	damagefactor "Head", 0.9;
	damagefactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	damagefactor "TeleportRemover", 0.0;
	PainSound "PSXDPN";
	
	Height 56;
	GibHealth 30;
	-BOSSDEATH;
	MaxStepHeight 24;
	MaxDropOffHeight 32;
	damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0; damagefactor "GreenBlood", 0.0;
	BloodType "Brutal_Blood", "BloodSPlatterReplacer", "AxeBlood";
	Obituary "%o was slain by a Cyber Hell Knight.";
	
	MeleeDamage 5;
	Species "Noble";
	+DONTHARMSPECIES;
	+MissileEvenMore;	

/*	//DropItem "DemonStrengthRune", 3;
	//DropItem "DemonStrengthRune", 7;
	//DropItem "RageSphere", 6;
	//DropItem "DoubleSphere", 5;
	//DropItem "ShieldSphere", 4;
	//DropItem "Demonpickup2", 90;
	//DropItem "Demonpickup", 196;*/

	SeeSound "monster/bruSit";
	PainSound "baron/pain";
	DeathSound "monster/brudth";
	MeleeSound "baron/melee";
}

States 
{ 		
	Spawn:
 		TNT1 A 0;
		CYUS AB 10 A_Look;
	Stand:
		TNT1 A 0;
		CYUS B 5 A_Look;
	loop;

	See:
		TNT1 A 0 A_StopSound(5);
		CYUS A 1 A_Playsound("monster/bruwlk",7);
		CYUS AABB 2 A_Chase;
		CYUS C 1 A_Playsound("monster/bruwlk",7);
		CYUS CCDD 2 A_Chase;
	loop;

	Missile:
		TNT1 A 0 {A_StopSound(5); A_FaceTarget();}
		CYUS E 2 A_Playsound("REILAIM");
		CYUS E 1 A_Jump(120, "ChaingunStart");
		CYUS E 0 A_Jump(24, "Freezer");
		CYUS E 1 A_JumpIfCloser(290, "Freezer");
		CYUS E 4 A_FaceTarget;
		TNT1 A 0 A_Jump(42, "MissileSomeMore");
		TNT1 A 0 A_PlaySound("DSRFIRE");
		TNT1 A 0 a_spawnprojectile("Red_FlareSpawn", 38, 15, random(-2,2), CMF_OFFSETPITCH);
		CYUS F 4 Bright a_spawnprojectile("CyberKnightMissile", 38, 15, random(-2,2), CMF_OFFSETPITCH);
		CYUS E 8 ;
	goto See;
		
	MissileSomeMore:
	MissileInRage:
		CYUS E 6 A_FaceTarget;
		TNT1 A 0 A_PlaySound("DSRFIRE");
		CYUS F 3 Bright a_spawnprojectile("CyberKnightMissile", 38, 15, random(-3,3), CMF_OFFSETPITCH);
		tnt1 a 0 a_jumpif(random(0, 10) > 6, "MissileInRage");
		CYUS E 8;
	goto See;
		
	Freezer:
		CYUS E 6 {A_FaceTarget(); A_StopSound(5);}
		TNT1 A 0
		{
			A_PlaySound("Weapons/FreezerFire"); 
			a_spawnprojectile("Blue_FlareSpawn", 38, 15, random(-1,1), CMF_OFFSETPITCH);
		}
		BRUR A 5 Bright a_spawnprojectile("CyberKnightFreezer", 38, 15, random(-3,3), CMF_OFFSETPITCH);
		tnt1 a 0 a_jumpif(random(0, 10) > 6, "Freezer");
		CYUS E 8;
	goto See;
		
	ChaingunStart:
		TNT1 A 0 A_StopSound(5);
		TNT1 A 0 A_PlaySound("weapons/chagan/start", 4);
		CYUS EE 8 A_FaceTarget;

	Chaingun:
		CYUS E 2 A_FaceTarget;
		TNT1 A 0 A_Playsound("Weapons/NailMGFire");
		CYUS F 2 Bright a_spawnprojectile("EnemyNail", 38, 15, random(-3,3), CMF_OFFSETPITCH, random(-1,1));
		tnt1 a 0 a_jumpif(random(0, 10) > 4, "Chaingun");
		CYUS E 8 A_FaceTarget;
	goto See;
		
		
	Melee:
		TNT1 A 0 {A_StopSound(5);  A_PlaySound("weapons/gswing");}
		CYUS GH 8 A_FaceTarget;
		CYUS I 8 a_spawnprojectile("CyberFistAttack",10,0,0,0);
	goto See;
		
	CurbstompMarine:
		TNT1 A 0 A_StopSound(5);
		TNT1 A 0 {self.binvulnerable = true;}
		CYFA A 6;
		CYFA BCCCDI 3;
		TNT1 A 0 {self.binvulnerable = false;}
		TNT1 A 0 A_PlaySound("weapons/gswing");
		TNT1 A 0 a_spawnprojectile("ThrowedMarine",10,0,0,0);
	goto See;


	Pain: 
		CYUS J 6 {A_StopSound(5); A_Pain();}
		CYUS J 0;
	goto See;
		
	Possession:
		TNT1 A 0 A_SetInvulnerable;
		CYUS J 3;
		CYUS J 3 A_Pain;
 		TNT1 A 0 A_UnSetInvulnerable;
	goto See;
		
		
	Pain.ExtremePunches:
	Pain.Kick:
		TNT1 A 0;
		TNT1 A 0 {self.bMISSILEMORE = true; self.bMISSILEEVENMORE = true;}
		//TNT1 A 0 A_JumpIfInventory("StopKickingMyBallsMotherFucker", 1, "MissileInRage");
		//TNT1 A 0 A_GiveInventory("StopKickingMyBallsMotherFucker", 1);
		TNT1 A 0 ThrustThingZ(0,25,0,1);
		TNT1 A 0 {self.bNOPAIN = true;}
		CNRJ ABCD 4 ;
		TNT1 A 0 A_Pain;
		CNRJ ABCD 5 ;
		TNT1 A 0 A_Pain;
		CNRJ ABCD 4 ;
		TNT1 A 0 A_Pain;
		CNRJ ABCD 4 ;
		TNT1 A 0 {self.bNOPAIN = false;}
	goto Missile;

	Death.Saw:
	Death.Cut:
	Death.Tear:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeathCyberKnightRipped", 48, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 57, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAA 0 a_spawnprojectile("Instestin", 35, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathStomach", 39, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("Xdeath3", 52, 0, random(0, 360), 2, random(0, 160));
		CP5L EEEE 2 a_spawnprojectile("Brutal_LiquidBlood2", 45, 2, random(0, 360), 2, random(60, 120));
		CP5L FGH 6;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		CP5L H -1;
	stop;
		
		
	Death.Arm:
		TNT1 A 0 A_StopSound(5);
		TNT1 A 0 A_Jump(32, "Death.Alt2");
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 a_spawnprojectile("XDeathCyberKnightArm", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("MuchMeatDeath", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("DyingCyberKnight3", 1);
	stop;
		
	Death.Alt2:
		TNT1 A 0 A_StopSound(5);
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 42, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("xdeath3", 32, 0, random(0, 360), 2, random(0, 160));
		C95D A 6 A_Scream;
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_PlaySound("master/walk", 9);
		C95D BBB 3  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 22, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 22, 0, random(150, 210), 2, random(0, 40));
		C95D CDE 6;
		TNT1 A 0 A_PlaySound("master/walk", 9);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		C95D F -1;
	stop;
		
	Death.Shotgun:
		TNT1 A 0 A_StopSound(5);
		TNT1 A 0 A_JumpIfCloser(200, "Death.Blast");
	goto Death;
		
	Death.Blast:
		TNT1 A 0 A_Jump(96, "Death.Arm");
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeathCyberKnightTorso", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathCyberKnightArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAAA 0 a_spawnprojectile("Xdeath3", 52, 0, random(0, 360), 2, random(0, 160));
		CP5L EEEE 2 a_spawnprojectile("Brutal_LiquidBlood2", 45, 2, random(0, 360), 2, random(60, 120));
		CP5L FGH 6;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		CP5L H -1;
	stop;
		
		
	Death.Landmine:
	Death.SuperKick:
	Death.ExplosiveImpact:
	Death.ExtremePunches:
		TNT1 A 0 A_StopSound(5);
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 ThrustThingZ(0,35,0,1);
		TNT1 A 0 a_spawnprojectile("XDeathCyberKnightArm", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathCyberKnightLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("xdeath3", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 A_StopSound(5);
		C97D A  8 A_Scream;
		C97D B  8 A_NoBlocking;
		C97D CCCCCC  8 A_CheckFloor("Land1");
	goto Land1;
		
	Land1:
		TNT1 A 0 A_StopSound(5);
		TNT1 A 0 A_PlaySound("master/walk", 9);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		C97D D -1;
	stop;
		
	Death:
		TNT1 A 0 A_StopSound(5);
		TNT1 A 0 A_Jump(128, "Death.Alt2");
		TNT1 A 0 A_Jump(96, "Death.Alt3");
		TNT1 A 0 A_Jump(128, "Death.Alt");
		TNT1 A 0 A_JumpIfCloser(150, "Death.Alt2");
	Death.Explosive:
	XDeath:
		//TNT1 A 0 A_JumpIfInTargetInventory("SSGSelected", 1, "Death.SSG");
		TNT1 A 0 A_StopSound(5);
		CYUS K 3 Bright A_Scream;
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_PlaySound("caco/shotx");
		EXPL A 0 Radius_Quake(3, 60, 0, 11, 0);
		TNT1 A 0
		{
			for(int i = 0; i < 2; i++)
			{
				A_PlaySound("FAREXPL");
				A_PlaySound("Explosion", 1);
				a_spawnprojectile("CasingSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
			}
		}
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		CYUS L 3 Bright
		{
			for(int i = 0; i < 2; i++)
			{
				A_PlaySound("FAREXPL");
				A_PlaySound("Explosion", 1);
				a_spawnprojectile("CasingSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
			}
		}
		TNT1 AA 0 a_spawnprojectile("MuchMeatDeath", 0, 0, random(0, 360), 2, random(0, 160));
		CYUS M 3 a_spawnprojectile("XDeathCyberKnightArm", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathCyberKnightTorso", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathCyberKnightLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 {pb_blood_and_gore_event.much_blood(self);}
		CYUS NO 3
		{
			for(int i = 0; i < 2; i++)
			{
				A_PlaySound("FAREXPL");
				A_PlaySound("Explosion", 1);
				a_spawnprojectile("CasingSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
			}
			a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
			{pb_blood_and_gore_event.much_blood(self);}
		}
		TNT1 AAAAAAAAAAAAA 3 a_spawnprojectile("ExplosionSmoke", 2, 0, random(0, 360), 2, random(0, 360));
		CYUS QR 2 Bright;
		CYUS S 2;
		CYUS TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT 4 a_spawnprojectile("ExplosionSmoke", 24, 0, random(0, 180), 2, random(0, 180));//A_BossDeath
		CYUS T -1;
	stop;
		
		
	Death.SSG:
	Death.QuadBlast:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Jump(12, "Death.Blast");
		TNT1 A 0 a_spawnprojectile("XDeathCyberKnightTorso", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathCyberKnightArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAAA 0 a_spawnprojectile("Xdeath3", 52, 0, random(0, 360), 2, random(0, 160));
		C92D AAAA 2 a_spawnprojectile("Brutal_LiquidBlood2", 45, 2, random(0, 360), 2, random(60, 120));
		C92D BCD 6;
		C92D D -1;
	stop;
		
	Death.Head:
	Death.Decapitate:
		//TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		TNT1 A 0 A_PlaySound("misc/gibbed", 3);
		TNT1 AAAA 0 a_spawnprojectile("Xdeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("Brains2", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Brains2", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Brains4", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("Brains4", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Teeth", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 62, 0, random(0, 360), 2, random(50, 80));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPieceFast", random(55, 59), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPiece", 58, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 58, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 A_Jump(162, 3);
		TNT1 A 0 A_SpawnItem("DyingCyberKnight1", 1);
	stop;
		TNT1 A 0;
		CP8L A 6;
		CP8L BC 6;
		CP8L D 6;
		TNT1 A 0 A_PlaySound("master/walk", 9);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_NoBlocking;
		CP8L D -1;
	stop;
		
	Death.Alt:
		TNT1 A 0 A_StopSound(5);
		C91D A 6 A_Scream;
		TNT1 AAA 0 {pb_blood_and_gore_event.much_blood(self);}
		C91D B 6 A_BossDeath;
		C91D C 6;
		C91D D 6 A_NoBlocking;
		EXPL A 0 Radius_Quake(3, 60, 0, 11, 0);
		TNT1 A 0 A_PlaySound("master/walk", 9);
		C91D DDDDDDzDDDDDzDDDD 11
		{
			if(frame > 20)
			{
				A_PlaySound("caco/shotx");
				A_SpawnItem("ShoqueAzul");
				A_PlaySound("Sparks/Spawn");
				for(int i = 0; i < 30; i++)
				{a_spawnprojectile("pb_Spark", 0.0, 0, random(0, 360), 2, random(67, 113));}
			}
		}
		C91D DDDD 11;
		EXPL A 0 Radius_Quake(3, 60, 0, 11, 0);
		C91D E 4;
		TNT1 A 0
		{
			for(int i = 0; i < 2; i++)
			{
				A_PlaySound("FAREXPL");
				A_PlaySound("Explosion", 1);
				a_spawnprojectile("CasingSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
			}
		}
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 AAAAA 0 a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AA 0 a_spawnprojectile("MuchMeatDeath", 0, 0, random(0, 360), 2, random(0, 160));
		C91D FG 5;
		TNT1 A 0
		{
			for(int i = 0; i < 2; i++)
			{
				A_PlaySound("FAREXPL");
				A_PlaySound("Explosion", 1);
				a_spawnprojectile("CasingSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
			}
		}
		TNT1 AAAAAAAAAAAAA 3 a_spawnprojectile("ExplosionSmoke", 2, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("xdeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("xdeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("XDeath3", 62, 0, random(0, 360), 2, random(0, 160));
		C91D HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 8 a_spawnprojectile("ExplosionSmoke", 24, 0, random(0, 180), 2, random(0, 180));
		C91D H -1;
	stop;
		
	Death.Alt3:
		TNT1 A 0 A_StopSound(5);
		TNT1 A 0 {pb_blood_and_gore_event.much_blood(self);}
		C96D A 6 A_Scream;
		C96D BC 6;
		C96D D 6 A_BossDeath;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_NoBlocking;
		C96D D -1;
	stop;
		
	Death.Fatality:
		TNT1 A 0 A_Jump(256, "Fatality1", "Fatality2");
	Fatality1:
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("CyberKnightFatality1", 1);
		TNT1 A 1 A_BossDeath;
	stop;
	Fatality2:
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("CyberKnightFatality2", 1);
		TNT1 A 1 A_BossDeath;
	stop;
		
} 

}

CLASS CyberFistAttack: BaronBall
{ 
Default
{	
	Radius 24;
	Height 16;
	DamageType "CYFT";
	Projectile;
	+RANDOMIZE;
	+FORCEXYBILLBOARD;
	+THRUGHOST;
	RenderStyle "Add";
	Alpha 0.6;
	DamageFunction(random(50,60));
	Speed 28;
	SeeSound "none";
	DeathSound "none";
	Decal "none";
}
States
{
	Spawn:
		TNT1 A 2 BRIGHT;
		TNT1 A 2;
	goto Death;
	Death:
		TNT1 A 0 BRIGHT;
	stop;
	}
}


CLASS FriendlyCyberKnight: pb_cyber_Knight_X
{ 
Default {
	Translation "16:47=112:127", "192:207=80:111", "168:191=64:79";
	+Friendly;
}

States 
{ 
	Spawn: 
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 A_PlaySound("PLSC_1", 1);
		CYUS J 8;
		TNT1 A 0 A_PlaySound("PLSC_2", 2);
		CYUS J 6 ;
		TNT1 A 0 A_PlaySound("PLSC_3", 3);
		CYUS J 4 ;
		TNT1 A 0 A_PlaySound("PLSC_4", 4);
		CYUS J 2 A_Look;
		TNT1 A 0 {self.bSOLID = true;}
	Goto See;

	Death.Fatality:
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("CyberKnightFatality1", 1);
		TNT1 A 1 A_BossDeath;
	stop;
}

}

CLASS CyberKnightMissile : pb_projectile_base { 
	Default {
 
	Radius 4;
	Height 4;
	Speed 32;
	FastSpeed 32;
	Damage 0;
	PROJECTILE;
	Scale 0.75;
    damagetype "ExplosiveImpact";
	SeeSound "RLSHOT2";
	DeathSound "Explosion";
	}
	States
	{
	Spawn:
	TNT1 A 0 A_PlaySound("weapons/rocketloop",6,1,1);
	Fly:
	C1MS A 1 BRIGHT A_SpawnItem("YellowFlareSmall",0,0);
	C1MS B 1 BRIGHT A_SpawnItem("RocketFlare",0,0);
	//TNT1 A 0 A_SpawnItemEx("RevenantProjectileTrails", 0, 0, 0, 0, 0, 0, 0, 128) 
	TNT1 A 0 A_SpawnItem("ExplosionSmoke");
	TNT1 A 0 a_spawnprojectile("ExplosionSmoke", 2, 0, random(160, 210), 2, random(-30, 30));
	Loop;
	Death:
	TNT1 A 0 A_StopSound(6);
	    EXPL AAA 0 a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	    EXPL A 0 Radius_Quake(2, 54, 0, 15, 0);
	BFE1 A 0 Bright A_Explode(40, 120, 1);
		TNT1 A 0
		{
			pb_effect_event(effects).show_some_effect(self, "NewRocketExploFX");
		}
		TNT1 A 0
		{
			for (int i = 0; i < 10; i++)
			{
				a_spawnprojectile("pb_particle", 0, 0, random(0, 360), 2, random(0, 180));
			}
		}
	TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
        TNT1 AAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 A 0 A_PlaySound("FAREXPL", 3);
	TNT1 A 10;
	Stop;
	}
}

CLASS CyberKnightFreezer: pb_projectile_base
{ 
	Default {
 
	Radius 10;
	Height 10;
	Speed 32;
	Damage 5;
    DamageType "Freeze";
	Decal "IceScorch";
	Projectile;
	//+RANDOMIZE
	renderstyle "Add";
	alpha 0.90;
	Scale 0.25;
	DeathSound "weapons/cryobowhit";
    SeeSound "None";
	Obituary "$OB_MPPLASMARIFLE";
	}
	States
	{
	Spawn:
	FRPJ ABC 1 Bright;
	TNT1 A 0 a_spawnprojectile("Blue_FlareSpawn",0,0,0,0);
	TNT1 A 0 a_spawnprojectile("Icetracer", 0, 0, random(0, 360), 2, random(0, 360));
	Loop;

	Xdeath:
	Death:
	BXPL A 0 Bright A_Explode(15, 16, 0);
	TNT1 A 0 a_spawnprojectile("Blue_FlareSpawn",0,0,0,0);
	BXPL AAA 0 Bright A_SpawnItemEx("MiniCryoSmoke1", 0, 0, 0, random(10, 30)*0.1, 0, random(0, 10)*0.1, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION);
	BXPL A 0 Bright A_SpawnItemEx("MiniCryoSmoke1", 0, 0, 0, random(10, 30)*0.04, 0, random(0, 10)*0.04, random(1,360), SXF_CLIENTSIDE|SXF_NOCHECKPOSITION,64);
	BXPL ABC 1 Bright;
	BXPL DEFGHIJKLM 1 Bright A_FadeOut(0.1);
	Stop;
	
}
}

