CLASS pb_Hell_Trooper : proto_zombieman_class// Replaces ShotgunGuy
{ 
Default
{
	Health 220;
	Radius 16;
	Height 46;
	Speed 9;
	FastSpeed 14;
	Monster;
	+FLOORCLIP;
	+MISSILEMORE;
	Scale 1.1;
	MaxStepHeight 24;
	MaxDropOffHeight 32;
	//SpawnID 1290;

	PainChance 150;
	PainChance "Avoid", 100;
	PainChance "Kick", 200;
	PainChance "ExtremePunches", 256;
	PainChance "Melee", 256;
	PainChance "Taunt", 0;
	PainChance "ExplosiveImpact", 200;
	PainChance "Stun", 255;

	damagefactor "Fatality", 0.5;
	damagefactor "Taunt", 0.0;
	damagefactor "SSG", 50.0;
	damagefactor "HelperMarineFatallity", 3.0;
	DamageFactor "Blood", 0.0; DamageFactor "BlueBlood", 0.0; DamageFactor "GreenBlood", 0.0;
	damagefactor "SuperPunch", 3.0;
	damagefactor "Melee", 3.0;
	damagefactor "Freeze", 2.0;
	damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0; damagefactor "GreenBlood", 0.0;
	damagefactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	damagefactor "Kick", 0.3;
	damagefactor "MinorHead", 2.0;
	damagefactor "Head", 2.0;
	damagefactor "Shrapnel", 0.4;
	damagefactor "Taunt", 1.0;
	damagefactor "ExplosiveImpact", 2.0;

	BloodType "pb_blood";
	SeeSound "grunt/sight";
	PainSound "grunt/pain";
	DeathSound "grunt/death";
	ActiveSound "grunt/active";
	Obituary "%o was silenced by a demon tech trooper.";
	////DropItem "DemonMorphRune", 3;

	proto_zombieman_class.max_magazine_size 20;
}

States
{
	Death.Shrink:
		TNT1 A 1 A_PlaySound("Shrink", 3);
/*		TNT1 A 0 A_SpawnItemEx("HellTrooperShrinkFX1", 0, 0,  5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("HellTrooperShrinkFX2", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("HellTrooperShrinkFX3", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("HellTrooperShrinkFX4", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("HellTrooperShrinkFX5", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("HellTrooperShrinkFX6", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("HellTrooperShrinkFX7", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("LilHellTrooper", 1);*/
	stop;
		
	Spawn:
		TNT1 A 0;
		//TNT1 A 0 A_GiveInventory("SKHellTrooper", 1);
 		//TNT1 A 0 {ammo_amount -= 2;}//A_GiveInventory("ZombieManAmmo", random(1,10));
		HTWA B 1 {self.ammo_amount = random(0, max_magazine_size); }
	Stand:
		TNT1 A 0 ;
		HTWA B 10 A_Look();
	Loop;
		
	See:
		//TNT1 A 0 A_takeInventory("SKHellTrooper", 1);
		
		TNT1 A 0 ;
		HTWA AA 2 A_Chase();
		TNT1 A 0 A_Recoil(-1);
		
		TNT1 A 0 ;
		HTWA AA 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",0);
		TNT1 A 0 ;
		HTWA BB 2 A_Chase();
		TNT1 A 0 ;
		HTWA BB 2 A_Chase();
		TNT1 A 0 ;
		HTWA CC 2 A_Chase();
		TNT1 A 0 ;
		HTWA CC 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",0);
		TNT1 A 0 ;
		HTWA DD 2 A_Chase();
		TNT1 A 0 ;
		HTWA DD 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",0);
		
		
		Loop;
		
	Pain.Taunt:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("Enraged", 1, "SpecialAttack");
		HTWA B 0 A_Pain();
		TNT1 A 0 {self.bMISSILEMORE = true;}
		TNT1 A 0 {self.bMISSILEEVENMORE = true;}
		TNT1 A 0 A_PlaySound("grunt/sight");
		HTWA A 1 A_FaceTarget();
		HTWA A 1;
		TNT1 A 0 A_GiveInventory("Enraged", 1);
		TNT1 A 0 A_PlaySound("grunt/sight", 1);
	Goto SpecialAttack;
		
	Missile: 
		TNT1 A 0 {ammo_amount -= 2;}//{ammo_amount -= 2;}//A_GiveInventory("ZombieManAmmo", 2);
		TNT1 A 0 A_Jump(96,"CrouchFire");
		//TNT1 A 0 A_JumpIfInventory("Enraged", 1, "SpecialAttack");
		TNT1 A 0 A_Jump(132,"SpecialAttack");
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTF1 A 4 A_FaceTarget();
		TNT1 A 0 A_PlaySound("HRFire");
		TNT1 A 0 a_spawnprojectile("Red_FlareSmall", 34, 6);
		TNT1 A 0 a_spawnprojectile("Trooperbullet", 35, 0, random(-8, 8), 0);
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTF1 B 4 BRIGHT A_FaceTarget();
		TNT1 A 0 pb_check_reloading("reload");//A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
		Goto See;
		
	SpecialAttack:
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTF1 A 3 A_FaceTarget();
		TNT1 A 0 A_PlaySound("HRFire");
		TNT1 A 0 a_spawnprojectile("Red_FlareSmall", 34, 6);
		TNT1 A 0 a_spawnprojectile("Trooperbullet", 35, 0, random(-8, 8), 0);
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTF1 B 3 BRIGHT A_FaceTarget();
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTF1 A 3 A_FaceTarget();
		TNT1 A 0 A_PlaySound("HRFire");
		TNT1 A 0 a_spawnprojectile("Red_FlareSmall", 34, 6);
		TNT1 A 0 a_spawnprojectile("Trooperbullet", 35, 0, random(-8, 8), 0);
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTF1 B 3 BRIGHT A_FaceTarget();
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTF1 A 3 A_FaceTarget();
		TNT1 A 0 A_PlaySound("HRFire");
		TNT1 A 0 a_spawnprojectile("Red_FlareSmall", 34, 6);
		TNT1 A 0 a_spawnprojectile("Trooperbullet", 35, 0, random(-8, 8), 0);
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTF1 B 3 BRIGHT A_FaceTarget();
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTF1 A 3 A_FaceTarget();
		TNT1 A 0 A_PlaySound("HRFire");
		TNT1 A 0 a_spawnprojectile("Red_FlareSmall", 34, 6);
		TNT1 A 0 a_spawnprojectile("Trooperbullet", 35, 0, random(-8, 8), 0);
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTF1 B 3 BRIGHT A_FaceTarget();
		TNT1 A 0 pb_check_reloading("reload");//A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
	Goto See;
		
	CrouchFire:
		HTF1 A 3 A_FaceTarget();
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTWA E 3 A_FaceTarget();
		TNT1 A 0 A_PlaySound("HRFire");
		TNT1 A 0 a_spawnprojectile("Red_FlareSmall", 34, 6);
		TNT1 A 0 a_spawnprojectile("Trooperbullet", 35, 0, random(-8, 8), 0);
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTWA F 3 BRIGHT A_FaceTarget();
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTWA E 3 A_FaceTarget();
		TNT1 A 0 A_PlaySound("HRFire");
		TNT1 A 0 a_spawnprojectile("Red_FlareSmall", 34, 6);
		TNT1 A 0 a_spawnprojectile("Trooperbullet", 35, 0, random(-8, 8), 0);
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTWA F 3 BRIGHT A_FaceTarget();
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTWA E 3 A_FaceTarget();
		TNT1 A 0 A_PlaySound("HRFire");
		TNT1 A 0 a_spawnprojectile("Red_FlareSmall", 34, 6);
		TNT1 A 0 a_spawnprojectile("Trooperbullet", 35, 0, random(-8, 8), 0);
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTWA F 3 BRIGHT A_FaceTarget();
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTWA E 3 A_FaceTarget();
		TNT1 A 0 A_PlaySound("HRFire");
		TNT1 A 0 a_spawnprojectile("Red_FlareSmall", 34, 6);
		TNT1 A 0 a_spawnprojectile("Trooperbullet", 35, 0, random(-8, 8), 0);
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTWA F 3 BRIGHT A_FaceTarget();
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTWA E 3 A_FaceTarget();
		TNT1 A 0 A_PlaySound("HRFire");
		TNT1 A 0 a_spawnprojectile("Red_FlareSmall", 34, 6);
		TNT1 A 0 a_spawnprojectile("Trooperbullet", 35, 0, random(-8, 8), 0);
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTWA F 3 BRIGHT A_FaceTarget();
		HTF1 A 3 A_FaceTarget();
		TNT1 A 0 pb_check_reloading("reload");//A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
		Goto See;
		
	Reload:
		TNT1 A 0 {ammo_amount = max_magazine_size;}//A_TakeInventory("ZombieManAmmo", 20);
		TNT1 A 0 ;
		TNT1 A 0 ;
		TNT1 A 0 A_PlaySound("HRSteam");
		TNT1 A 0 A_SpawnItem("HellRifle_Puff2", 15,38);
		HTWA G 1;
		HTWA H 1 BRIGHT a_spawnprojectile("bfg_4_laser_train", 38, 0, random(-11, 11), 0);
		HTWA G 1;
		HTWA H 1 BRIGHT a_spawnprojectile("bfg_4_laser_train", 38, 0, random(-11, 11), 0);
		HTWA G 1;
		HTWA H 1 BRIGHT a_spawnprojectile("bfg_4_laser_train", 38, 0, random(-11, 11), 0);
		HTWA G 1;
		HTWA H 1 BRIGHT a_spawnprojectile("bfg_4_laser_train", 38, 0, random(-11, 11), 0);
		TNT1 A 0 ;
		TNT1 A 0 ;
		
		HTWA I 1;
		HTWA J 1 BRIGHT;
		HTWA I 1;
		HTWA J 1 BRIGHT;
		HTWA I 1;
		HTWA J 1 BRIGHT;
		HTWA I 1;
		HTWA J 1 BRIGHT;
		
		TNT1 A 0 A_PlaySound("CLIPIN");
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTWA K 9;
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTWA L 9;
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTWA G 9;
		TNT1 A 0 ;
		TNT1 A 0 ;
		HTWA A 6;
		Goto See;
		
		
		
	Pain.KillMe:
		TNT1 A 0;
		Goto See;
		
	Death.KillMe:
	Death.Taunt:
	Death.Avoid:
		TNT1 A 0;
		TNT1 A 0 {self.bSOLID = false;}
		//TNT1 A 0 A_SpawnItem("HellTrooper");
		TNT1 A 0;
	Stop;
		
	Pain:
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, 7);
		TNT1 A 0 ;
		TNT1 A 0 a_spawnprojectile("brutal_FlyingBlood", 35, 0, random(0, 360), 2, random(0, 160));
		HTPA A 3;
		TNT1 A 0 ;
		HTPA A 3 A_Pain();
		Goto See;
		TNT1 AAAA 0;
		HTD1 G 4;
		TNT1 A 0 A_Pain();
		HT11 SSST 10;
		TNT1 A 0 A_TakeInventory("IsDown", 1);
		Goto See;
		
	Possession:
		TNT1 A 0 A_SetInvulnerable();
		HTD1 G 3;
		HTD1 G 3 A_Pain();
 		TNT1 A 0 A_UnSetInvulnerable();
		Goto See;
		
	Pain.Stun:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx("StunElectrocute", random(-4, 4), random(-4, 4),  random(16, 32), 0, 0);
		TNT1 A 0 ;
		HTD1 G 1 A_Pain();
		HTD1 GGGGGGGGGG 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		TNT1 A 0 ;
		HTD1 G 1 A_Pain();
		HTD1 GGGGGGGGGG 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		TNT1 A 0 ;
		HTD1 G 1 A_Pain();
		HTD1 GGGGGGGGGG 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		TNT1 A 0 ;
		HTD1 G 1 A_Pain();
		HTD1 GGGGGGGGGG 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		TNT1 A 0 ;
		HTD1 G 1 A_Pain();
		HTD1 GGGGGGGGGG 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		TNT1 A 0 ;
		HTD1 G 1 A_Pain();
		Goto See;
		
	Pain.Melee:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInventory("SKHellTrooper", 1, "GotoStealthKill");
		HTPA A 3;
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, 7);
		TNT1 A 0 ;
		TNT1 A 0 a_spawnprojectile("brutal_FlyingBlood", 35, 0, random(0, 360), 2, random(0, 160));
		HTPA A 3;
		TNT1 A 0 ;
		HTPA A 3 A_Pain();
		Goto See;
		TNT1 AAAA 0;
		HTD1 G 4;
		TNT1 A 0 A_Pain();
		HT11 SSST 10;
		TNT1 A 0 A_TakeInventory("IsDown", 1);
	Goto See;

	Pain.ExplosiveImpact:
	Pain.Explosive:
		TNT1 A 0;
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain");
		//TNT1 A 0 A_takeInventory("SKHellTrooper", 1);
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		HT11 GH 8;
	Goto FallingAfterImpact;
		// Falling back animation
	Pain.Kick:
	Pain.BlackHole:
	Pain.ExtremePunches:
		TNT1 A 0;
		HT11 G 1 A_Pain();
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain");
		//TNT1 A 0 A_takeInventory("SKHellTrooper", 1);
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		//ID11 E 1 A_Chase("","")
		HT11 G 1 A_facetarget();
		HT11 G 6 ThrustThing(angle*256/360+128, 10, 0, 0);
		HT11 H 8;
		Goto FallingAfterImpact;
		
	FallingAfterImpact:
		HT11 H 1 A_GiveInventory("Fallingheight", 1);
		HT11 H 1 A_CheckFloor("GetUp");
		tnt1 a 0 A_JumpIf(vel.z == 0, "GetUp");
		Loop;
		
	GetUp:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("Fallingheight", 5, "FallingDie");
		HT11 SSSSSSS 5 A_JumpIf(vel.z < 0, "FallingAfterImpact");
		TNT1 A 0 A_TakeInventory("Fallingheight", 100);
		TNT1 A 0 A_TakeInventory("IsDown", 1);
		HT11 T 10;
		Goto See;
		
	FallingDie:
		TNT1 A 0;
		TNT1 A 0 A_ChangeCountFlags(false);
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 A_SpawnItem("SplatteredSmall");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 15, "Death.Stomp");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 10, "FallingSuperDeath");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 5, "FallingDeath");
	FallingDeath:
		TNT1 A 0;
		TNT1 A 0 A_Explode(200, 2, 1);
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBLocking();
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(50, 130));
		HT11 GH 2;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		HTMS L -1;
	Stop;
		
	FallingSuperDeath:
		TNT1 A 0;
		TNT1 A 0 A_Explode(200, 2, 1);
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBLocking();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		Goto Death.ExplosiveImpact+1;
		
	Death.Nailgun:
		TNT1 A 0 A_Jump(128, "Naildeath2");
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 {self.bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,random(20,30),0,1);
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(30);
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		HT11 G 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		HT11 G 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		HT11 H 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		HT11 H 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		HT11 H 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		HT11 H 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		HTMS Q -1;
		Stop;
	PinToWall:
		TNT1 A 0 a_spawnprojectile("MuchBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_PlaySound("Weapons/NailHitBleed");
		PIN9 A 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItemEx("DeadHellTrooper_Pinned", 10);
		Stop;
		
	Death.Melee:
		//TNT1 A 0 A_JumpIfInventory("SKHellTrooper", 1, "StealthKill");
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Death.Down");
	Death.Kick:
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(8);
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		HT11 GH 8;
		TNT1 A 0 A_PlaySound("BODYF",6);
		HTMS L -1;
		Stop;
		
		
		
	Death.Down:
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		POSS I 0 A_Scream();
		POSS J 0 A_NoBlocking();
		HTMS L 1;
		HTMS L -1;
		Stop;
		
		
	Death.Shotgun:
		TNT1 A 0 A_JumpIfCloser(200, "Death.Shotgunontheface");
	Goto Death;
		
	Death.Shotgunontheface:
		
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "Death.Arm", "Death.Leg");
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		TNT1 A 0 a_spawnprojectile("MuchBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		HT11 GH 8;
		TNT1 A 0 A_PlaySound("BODYF",6);
		HTMS L -1;
		Stop;
		
	StealthKill:
	GotoStealthKill:
		TNT1 A 1;
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("SKHelltrooper", 1);
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Die("Stealthy");
		TNT1 A 0 A_Fall();
		TNT1 A 1;
		Stop;
		
	Death.Stealthy:
		TNT1 A 0;
		Stop;
		
	Death:
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Death.Down");
		TNT1 A 0;
		TNT1 AA 0 a_spawnprojectile("brutal_FlyingBlood", 7, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_Jump(96, "Death.Arm", "Death.Leg");
		TNT1 A 0 A_Jump(128, "DeathMirror","Death.Vanish");
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		HTMS H 5;
		HTMS I 5 A_Scream();
		HTMS J 5 A_NoBlocking();
		HTMS K 5;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		HTMS L -1;
		Stop;
		
	DeathMirror:
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		HTMS M 5;
		HTMS N 5 A_Scream();
		HTMS O 5 A_NoBlocking();
		HTMS P 5;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		HTMS Q -1;
		Stop;
		
		// own addition
	Death.Vanish:
	Death.BlackHole:
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		HTD6 A 5;
		HTD6 B 5 A_Scream();
		HTD6 C 5 A_NoBlocking();
		HTD6 DEFG 5;
		Stop;
		//	
	Death.Arm:
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("MuchBlood", 35, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		HTD2 A 10 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("DyingHellTrooperNoArm");
		Stop;
		
		
		
	Death.Leg:
		TNT1 A 0;
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("MuchBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 A 0 a_spawnprojectile("XDeathSargeLeg1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("DyingHellTrooperNoLeg");
		Stop;
		
	Death.Ice:
	Death.Freeze:
	Death.Frost:
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		//TNT1 A 0 A_SpawnItem("FrozenHellTrooper");
	Stop;
		
		
	Death.cutless:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Death.Down");
		TNT1 A 0 A_Jump(32, "Death");
		TNT1 A 0 A_Jump(32, "Death.Arm");
		TNT1 A 0 A_Jump(32, "Death.Leg");
		Goto Death.Massacre;
		
	Death.Massacre:
		TNT1 A 0;
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Scream();
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("BrutalizedHellTrooper1", 1);
		Stop;
		
	Death.LegMassacre:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("MuchBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSargeLeg1", 35, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		HTS7 B 1 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("BrutalizedHellTrooperLeg");
		Stop;
		
	Death.Cut:
		TNT1 A 0 A_Jump(32, "Death.Arm", "Death.Tear");
	Death.Saw:
		TNT1 AA 0 a_spawnprojectile("MuchBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile("RipHellTrooper", 0, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		HTD1 FG 9;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadHellTrooper_Half");
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		HTD1 H -1;
		Stop;
		
	Death.Tear:
		TNT1 AAA 0 a_spawnprojectile("MuchBlood", 1, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		TNT1 AAAA 0 a_spawnprojectile("BloodMist", random(30, 40), 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("RipHellTrooper", 0, 0, random(0, 360), 2, random(0, 160));
		SP2X BBBB 2 a_spawnprojectile("Brutal_LiquidBlood3", 32, 0, random(0, 360), 2, random(30, 60));
		SP2X CCCC 2 a_spawnprojectile("Brutal_LiquidBlood3", 20, 0, random(0, 360), 2, random(30, 60));
		SP2X DDDD 2 a_spawnprojectile("Brutal_LiquidBlood3", 12, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		SP2X EEEEEEEEEEEEEEEE 2 a_spawnprojectile("Brutal_LiquidBlood3", 12, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_SpawnItem("DeadShotgunguySP2XE");
		Stop;
		
		
	Death.Fatality:
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_Jump(256, "Death.Fatality2", "Death.Fatality3");//"Death.Fatality1",
		Goto Death.Fatality2;
		
		//	Death.Fatality1:
		//	TNT1 A 0 A_Scream
		//        //TNT1 A 0 A_GiveToTarget("HellTrooperFatality1", 1)
		//   Stop
	Death.Fatality2:
		TNT1 A 0 A_Scream();
		//TNT1 A 0 A_GiveToTarget("HellTrooperFatality2", 1);
		Stop;
	Death.Fatality3:
		TNT1 A 0 A_Scream();
		//TNT1 A 0 A_GiveToTarget("HellTrooperFatality3", 1);
		Stop;
		
		
		//Death.HelperMarineFatallity:
		//	TNT1 A 0 A_Scream
		//	TNT1 A 0 A_NoBlocking
		//  //TNT1 A 0 A_GiveToTarget("HellTrooperFatality3", 1)
		// Stop
		
		
		
		
	Death.Head:
		//TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
		//TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		//TNT1 A 0 A_JumpIfInTargetInventory("HasCutingWeapon", 1, "Death.Decaptate");
		TNT1 A 0 A_JumpIfHealthLower(-60, "Death.HeadExplode");
		//TNT1 A 0 A_JumpIfInTargetInventory("RandomHeadExploder", 1, "Death.HeadExplode");
	Death.MinorHead:
	Death.HeadMinor:
		TNT1 A 0;
		TNT1 A 0 A_Playsound("MinorHeadshot", 0);
		TNT1 A 0 A_Jump(128, "DeathMinorhead2");
		TNT1 A 0 A_Scream();
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		HTSH U 5 a_spawnprojectile("MuchBlood", 40, 0, random(0, 360), 2, random(0, 160));
		HTSH V 5 a_spawnprojectile("Brutal_LiquidBlood", 40, 0, 120, 2, random(0, 60));
		TNT1 AA 0 a_spawnprojectile("SmallBrainPiece", random(45, 55), random(5, -5), random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		HTSH W 5 A_NoBlocking();
		HTSH XY 5 a_spawnprojectile("Brutal_LiquidBlood", 30, 0, 120, 2, random(0, 60));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		HTSH Z -1;
		Stop;
		
	DeathMinorHead2:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "DeathMinorhead3");
		TNT1 A 0 A_Pain();
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("Teeth", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("TeethNoBounce", 50, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		HTD5 A 6 a_spawnprojectile("MuchBlood", 40, 0, random(0, 360), 2, random(0, 160));
		HTD5 CB 8 a_spawnprojectile("Brutal_LiquidBlood", 40, 0, 120, 2, random(0, 60));
		
		TNT1 A 0 A_Scream();
		HTD5 D 6 A_NoBlocking();
		
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		HTZA L -1;
		Stop;
		
		
	DeathMinorHead3:
		TNT1 A 0;
		TNT1 A 0 A_Pain();
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("Teeth", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("TeethNoBounce", 50, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		HTD5 A 6 a_spawnprojectile("MuchBlood", 40, 0, random(0, 360), 2, random(0, 160));
		HTD5 CB 8 a_spawnprojectile("Brutal_LiquidBlood", 40, 0, 120, 2, random(0, 60));
		HTD5 CBCBCB 12 a_spawnprojectile("Brutal_LiquidBlood", 40, 0, 120, 2, random(0, 60));
		TNT1 A 0 A_Scream();
		HTD5 D 6 A_NoBlocking();
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		HTZA L -1;
	Stop;
		
	Death.Headexplode:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode", 0, 50);
		ZMAD B 0 A_XScream();
		ZMAD C 0 A_NoBlocking();
		TNT1 A 0 A_Jump(32, "Deathchickenhead");
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		HTDH ABBC 10 a_spawnprojectile("MuchBlood", 30, 0, random(0, 360), 2, random(0, 160));
		HTDH DE 6 a_spawnprojectile("Brutal_LiquidBlood", 30, 0, 120, 2, random(0, 60));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		HTDH EEEEEEEEE 2 a_spawnprojectile("Brutal_LiquidBlood", 5, 0, 120, 2, random(0, 60));
		HTDH E -1;
		Stop;
		
	DeathChickenHead:
		
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		HTAD FGH 4 a_spawnprojectile("Bloodmist", 55, 0, 120, 2, random(0, 60));
		
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		HTAD FGH 4 a_spawnprojectile("Bloodmist", 55, 0, 120, 2, random(0, 60));
		
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		HTAD FGH 4 a_spawnprojectile("Bloodmist", 55, 0, 120, 2, random(0, 60));
		
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		HTAD FGH 4 a_spawnprojectile("Bloodmist", 55, 0, 120, 2, random(0, 60));
		
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		HTAD FGH 4 a_spawnprojectile("Bloodmist", 55, 0, 120, 2, random(0, 60));
		
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		HTAD FGH 4 a_spawnprojectile("Bloodmist", 55, 0, 120, 2, random(0, 60));
		
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		HTAD FGH 4 a_spawnprojectile("Bloodmist", 55, 0, 120, 2, random(0, 60));
		
		
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		HTDH ABBC 10 a_spawnprojectile("MuchBlood", 30, 0, random(0, 360), 2, random(0, 160));
		HTDH DE 6 a_spawnprojectile("Brutal_LiquidBlood", 20, 0, 120, 2, random(0, 60));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		HTDH E -1;
		Stop;
		
	Death.decaptate:
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", random(45, 55), random(5, -5), random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("MuchBlood", 40, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		HTDH A 15 a_spawnprojectile("MuchBlood", 40, 0, random(0, 360), 2, random(0, 160));
		HTDH B 9 A_XScream();
		HTDH C 9 A_NoBlocking();
		HTDH DE 5 a_spawnprojectile("Brutal_LiquidBlood", 25, 0, 120, 2, random(0, 60));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		HTDH E -1;
		Stop;
		
	Death.Incinerate:
		TNT1 A 0;
		TNT1 A 0 A_Stop();
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Playsound("MELT");
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAAA 0 a_spawnprojectile("ExplosionParticle", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAA 0 a_spawnprojectile("ExplosionParticle", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,32,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-35, 35), random(-35, 35));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-45, 45), random(-45, 35));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("Ashes1", 28, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("Ashes2", 40, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),32,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		Z8RN AAAAA 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile("ExplosionParticle", 36, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),28,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		Z8RN BBBBB 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile("ExplosionParticle", 28, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),24,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		Z8RN CCCCC 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile("ExplosionParticle", 36, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_Playsound("SZZLL", 3);
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),20,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		Z8RN DDDDD 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile("ExplosionParticle", 20, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),16,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		Z8RN EEEEE 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile("ExplosionParticle", 12, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),12,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		Z8RN FFFFF 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		TNT1 A 0 A_SpawnItem("Barrel_explosion_Column");
		Z8RN GGGG 2 Light("IncinerationGlow");
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		Z8RN HHHH 2 Light("IncinerationGlow") a_spawnprojectile("ExplosionSmoke", 14, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		Z8RN HHHHHH 12 a_spawnprojectile("ExplosionSmoke", 14, 0, random(0, 360), 2, random(0, 160));
		Z8RN H -1;
		Stop;
		
	Death.fire:
	Death.Flames:
	Death.Burn:
		//TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("BurningZombie");
		Stop;
		
	Death.Desintegrate:
		TNT1 A 0;//A_Jump(112, "AcidGuy")
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("DesintegratedHuman");
		Stop;
		
	AcidGuy:
		//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("GenericAcidGuy");
		TNT1 A 1;
		TNT1 A 0;
		Stop;
		
	Death.Plasma: Death.Plasma2:
	TNT1 A 0;
	TNT1 A 0 A_Stop();
	TNT1 A 0 A_PlaySound("plasmaflesh");
	TNT1 AAAAAAAAA 0 a_spawnprojectile("Ashes1", 32, 0, random(0, 360), 2, random(0, 180));
	TNT1 AAAAAAAAA 0 a_spawnprojectile("Ashes2", 32, 0, random(0, 360), 2, random(0, 180));
	TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1Blue",random(-2,2),random(-2,2),18,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
	TNT1 AAAA 0 a_spawnprojectile("BluePlasmaFire", 42, 0, random(0, 360), 2, random(0, 180));
	TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 32, 0, random(0, 360), 2, random(0, 180));
	TNT1 AAAAAA 0 a_spawnprojectile("SuperGoreMistSmall", 32, 0, random(0, 360), 2, random(10, 90));
	TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(0, 360), 2, random(0, 180));
	PBR1 B 6 A_NoBlocking();
	TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1Blue",random(-2,2),random(-2,2),10,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
	TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 A_SpawnItem("Barrel_explosion_Column");
	TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
	TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-35, 35), random(-35, 35));
	TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-45, 45), random(-45, 35));
	PBR1 CCDD 3 a_spawnprojectile("BluePlasmaFire", 32, 0, random(0, 360), 2, random(0, 180));
	PBR1 EEFF 3;
	PBR1 GG 3;
	PBR1 H -1;
	Stop;
	
	Death.SuperPlasma:
	TNT1 A 0;
	//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	XBRN AA 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
	TNT1 AAAA 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
	
	TNT1 A 0 a_spawnprojectile("XDeathBurnedArm", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	
	XBRN BB 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
	TNT1 A 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
	XBRN CC 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
	TNT1 AAAAA 0 a_spawnprojectile("PlasmaParticleX", 48, 0, random(0, 360), 2, random(0, 360));
	TNT1 AAA 0 a_spawnprojectile("PlasmaParticleX", 42, 0, random(0, 360), 2, random(0, 360));
	TNT1 A 0;
	Stop;
	
	
	Death.GreenFire:
	TNT1 A 0;
	//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	TNT1 AAAA 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
	
	TNT1 A 0 a_spawnprojectile("XDeathBurnedArm", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	
	EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("GreenFlameTrails", 50, 0, random(0, 360), 2, random(0, 360));
	XBRN AAAA 2 BRIGHT A_SpawnItem("Green_Flare",0,43);
	Stop;
	
	Death.SuperPunch:
	Death.Blast:
	Death.SSG:
	Death.Railgun:
	//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
	HTD1 D 1 A_Pain();
	HTD1 D 1 A_FaceTarget();
	//TNT1 A 0 a_spawnprojectile("MeatDeath", 0, 0, random(0, 360), 2, random(0, 160))
	TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 A_SpawnItem("BloodSplasher2");
	TNT1 AAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
	TNT1 AAA 0 bright a_spawnprojectile("SuperGoreSpawner", 35, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
	TNT1 AA 0 a_spawnprojectile("XDeathArm1", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	HTD1 DEEFFGH 6;
	TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	TNT1 A 0 A_PlaySound("BODYF",6);
	HTD1 H -1;
	Stop;
	
	XDeath:
	//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 a_spawnprojectile("SargeXDeath", 2, 0, random(0, 360), 2, random(0, 160));
	Stop;
	
	Death.Stomp:
	TNT1 A 0 A_Explode(200, 2, 1);
	//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
	TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
	TNT1 AAAAAA 0 bright a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(30, 180));
	TNT1 A 0 bright a_spawnprojectile("XDeath2", 55, 0, random(0, 360), 2, random(30, 180));
	TNT1 AAAA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 bright a_spawnprojectile("XDeath3", 55, 0, random(0, 360), 2, random(30, 180));
	TNT1 A 0 A_SpawnItem("CrushedRemains");
	TNT1 A 1;
	TNT1 A 1 A_XScream();
	TNT1 A 1 A_NoBlocking();
	Stop;
	
	Death.ExplosiveImpact:
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 {self.bNOBLOCKMONST = true;}
	TNT1 A 0 A_Jump(130,"Death.LandMine");
	TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", random(45, 55), random(5, -5), random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathSargeLeg1", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 ThrustThingZ(0,30,0,1);
	//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
	HT14 AB 5;
	HT14 CDEF 5 A_CheckFloor("Dead.ExplosiveImpact");
	HT14 FFFFFFFFFF 5 A_CheckFloor("Dead.ExplosiveImpact");
	TNT1 A 0 A_PlaySound("BODYF",6);
	HT14 G -1;
	Stop;
	
	
	Death.LandMine:
	TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathSargeLeg1", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GibHand", 42, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	//TNT1 A 0 a_spawnprojectile("TossedHellRifle", 25, 0, random(0, 360), 2, random(50, 130));
	HT16 A 1 A_Scream();
	HT16 A 9;
	HT16 BCD 9 A_CheckFloor("Dead.Landmine");
	HT16 DDDDD 9 A_CheckFloor("Dead.Landmine");
	TNT1 A 0 A_PlaySound("BODYF",6);
	HT14 G -1;
	Stop;
	
	Dead.ExplosiveImpact:
	TNT1 AAAA 0 A_SpawnItem("Blood");
	TNT1 A 0 A_PlaySound("BODYF",6);
	HT14 G -1;
	Stop;
	
	Dead.Landmine:
	TNT1 AAAA 0 A_SpawnItem("Blood");
	TNT1 A 0 A_PlaySound("BODYF",6);
	HT14 G -1;
	Stop;
	
	
	
	Raise:
	POSS K 5;
	POSS JIH 5;
	Goto See;
	Crush:
	TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail8", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 A 0 A_PlaySound("misc/xdeath4");
	TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	POSC A 5;
	POSC A -1;
	Stop;
}
}







/////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////







CLASS DeadHellTrooper : pb_blood_and_gore_base { 
	Default {
	
	}
States
    {
	Spawn:
	HTMS L -1;
	Stop;
	Raise:
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_SpawnItem("TeleportFog");
	//TNT1 A 0 A_SpawnItem("HellTrooper");
	Stop;
	Death:
	XDeath:
	Crush:
	TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 A 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
	Stop;
}
}

CLASS DeadHelltrooper_Half: DeadHelltrooper { 
	Default
{Health 200;} States{Spawn:
	HTD1 H -1;
	Stop;
	Death:
	Death.Cut:
	Death.Cutless:
	TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AAA 0 a_spawnprojectile("XDeath1", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath2", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAAA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath3", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath4", 50, 0, random(0, 360), 2, random(0, 160));
Stop;}}

CLASS DyingHellTrooperNoArm: DeadHellTrooper { 
	Default {
	
	Radius 12;
	Height 32;
	Health 50;
	damagefactor "Head", 10.0;
	}
States
    {
	Spawn:
	TNT1 A 0;
	
	TNT1 A 0 A_PlaySound("BURNZOM");
	
	HTD2 BEBEBEBEBEBE 10;
	HTD2 C 6;
	TNT1 A 0 {self.bSHOOTABLE = false;}
	TNT1 A 0 A_NoBlocking();
	HTD3 D -1;
	Stop;
	Death:
	HTD2 C 6 {self.bSHOOTABLE = false;}
	TNT1 A 0 A_PlaySound("grunt/death");
	TNT1 A 0 A_NoBlocking();
	HTD3 D -1;
	Stop;
	
	Death.Head:
	Death.MinorHead:
	TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
	TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode", 0, 50);
	HTD2 B 2;
	TNT1 A 0 A_PlaySound("misc/gibbed");
	HTD3 G 7;
	TNT1 A 0 {self.bSHOOTABLE = false;}
	TNT1 A 0 A_NoBlocking();
	HTD3 H -1;
	Stop;
	XDeath:
	Crush:
	TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 A 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
	Stop;
}
}


CLASS DyingHellTrooperNoLeg: DeadHellTrooper { 
	Default {
	
	Radius 12;
	Height 32;
	Health 50;
	damagefactor "Head", 10.0;
	}
States
    {
	Spawn:
	TNT1 A 0;
	
	TNT1 A 0 A_PlaySound("BURNZOM");

	HTS7 ABC 5;
	HTS7 DEDEDEDEDEDE 10;
	HTS7 GH 5;
	TNT1 A 0 {self.bSHOOTABLE = false;}
	TNT1 A 0 A_NoBlocking();
	HTS7 F -1;
	Stop;
	Death:
	TNT1 A 0 A_PlaySound("grunt/death");
	HTS7 GH 5;
	TNT1 A 0 {self.bSHOOTABLE = false;}
	TNT1 A 0 A_NoBlocking();
	HTS7 F -1;
	Stop;
	
	Death.Head:
	Death.MinorHead:
	TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
	TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode", 0, 50);
	HTS7 IJ 5;
	TNT1 A 0 {self.bSHOOTABLE = false;}
	TNT1 A 0 A_NoBlocking();
	HTS7 F -1;
	Stop;
	Stop;
	
	Stop;
	XDeath:
	Crush:
	TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 A 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
	Stop;
}
}


CLASS BrutalizedHellTrooper1 : ACTOR { 
	Default {
	Radius 16;
	Height 50;
	Health 70;
	bloodtype "DeadBlood";
	PainSound "grunt/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	+NORADIUSDMG;
	+FLOORCLIP;
	Scale 1.0;
	}
	States
	{
	Death.Fatality:
	Death.SuperPunch:
	TNT1 A 0 A_NoBlocking();
	//TNT1 A 0 A_GiveToTarget("HasZManShield", 1);
	//TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
	Stop;
	
	Spawn:
	TNT1 A 0;
	TNT1 A 0 A_Recoil(2);
	TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
	Pain:
	HTD1 A 15;
	Goto DieNow;
	
	DieNow:
	TNT1 A 0;
	TNT1 A 0 A_SpawnItem("BrutalizedHellTrooperStop");
	Stop;
	
	Death:
	TNT1 A 0;
	TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", random(45, 55), random(5, -5), random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 A_Recoil(2);
	TNT1 A 0;
	TNT1 A 0 A_SpawnItem("BrutalizedHellTrooper2");
	Stop;
	
	Death.SSG:
	XDeath:
	Death.QuadBlast:
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 a_spawnprojectile("SargeXDeath", 0, 0, random(0, 360), 2, random(0, 160));
	Stop;
}}

CLASS BrutalizedHellTrooperStop: DeadHellTrooper { 
    States
    {
	Spawn:
	HTD2 ABCD 5 A_SpawnItem("brutal_FlyingBlood",0,5,0,1);
	HTD3 D -1;
Stop;}}

CLASS BrutalizedHellTrooper2: BrutalizedHellTrooper1 { 
	States
	{
	Spawn:
	Pain:
	HTD1 B 15;
	Goto DieNow;
	
	DieNow:
	TNT1 A 0;
	TNT1 A 0 A_SpawnItem("BrutalizedHellTrooperStop2");
	Stop;
	
	Death:
	TNT1 A 0;
	TNT1 A 0 A_Recoil(2);
	TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0;
	TNT1 A 0 A_SpawnItem("BrutalizedHellTrooper3");
	Stop;
}}

CLASS BrutalizedHellTrooperStop2: DeadHellTrooper { 
    States
    {
	Spawn:
	HTD4 AB 6 A_SpawnItem("brutal_FlyingBlood",0,5,0,1);
	HTD4 B -1;
Stop;    }}

CLASS BrutalizedHellTrooper3: BrutalizedHellTrooper1 { 
	States
	{
	Spawn:
	Pain:
	HTD1 C 15;
	Goto DieNow;
	
	DieNow:
	TNT1 A 0;
	TNT1 A 0 A_SpawnItem("BrutalizedHellTrooperStop3");
	Stop;
	
	Death:
	TNT1 A 0;
	TNT1 A 0 A_Recoil(2);
	TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath2", 40, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
	HTD1 EFGH 6;
	HTD1 H -1;
	Stop;
}}


CLASS BrutalizedHellTrooperStop3: DeadHellTrooper { 
    States
    {
	Spawn:
	HTD3 ABC 6 A_SpawnItem("brutal_FlyingBlood",0,5,0,1);
	HTD3 C -1;
Stop;    }}
	
CLASS BrutalizedHellTrooperLeg: BrutalizedHellTrooper1 { 
	States
	{
	Spawn:
	Pain:
	POS7 A 15;
	Goto DieNow;
	
	DieNow:
	POS7 BCD 5;
	TNT1 A 0 A_SpawnItem("DeadHellTrooper_NoLeg");
	Stop;
	
	Death:
	TNT1 A 0;
	TNT1 A 0 A_Recoil(4);
	
	TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", random(45, 55), random(5, -5), random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
	//TNT1 AAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160))
	TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 ThrustThingZ(0,30,0,1);
	ID13 ABCDEF 5;
	TNT1 A 0 A_SpawnItem("VeryFuckedUpBrutalizedHellTrooperLeg");
	Stop;
}}

CLASS DeadHelltrooper_Noleg: DeadShotgunGuy_NoLeg
{ 
	Default 
{Alpha 1.0;}
}

CLASS VeryFuckedUpBrutalizedHellTrooperLeg: DeadHellTrooper { 
	Default {
	Health 200;
	DamageFactor "ExplosiveImpact", 10.0;
	}
	States{Spawn:
	ID13 G -1;
	Stop;
	Death.ExplosiveImpact:
	TNT1 A 0 ThrustThingZ(0,30,0,1);
	ID13 ABCDEF 5;
	TNT1 A 0 A_SpawnItem("VeryFuckedUpBrutalizedHellTrooperLeg");
	Stop;
}}
	  
CLASS VeryFuckedUpBrutalizedHellTrooperLeg2: VeryFuckedUpBrutalizedHellTrooperLeg { 
	Default 
{Health 200;} States{Spawn:
	ID15 E -1;
Stop;}}
//Fatality 3 corpse	
CLASS HeartlessHT: DeadHellTrooper { 
  States
    {
	Spawn:
	HTZA L 6 A_SpawnItem("brutal_FlyingBlood",0,5,0,1);
	HTZA L -1;
Stop;}}
	   
//Fatal 2 corpse
CLASS HelmbangedHT: DeadHellTrooper { 
  States
    {
	Spawn:
	HTMS L 6 A_SpawnItem("brutal_FlyingBlood",0,5,0,1);
	HTMS L -1;
Stop;    }}
	   
CLASS RipHelltrooper : ACTOR { 
	Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
	}
    States
    {
	Spawn:
	TNT1 AAA 0 a_spawnprojectile("brutal_FlyingBlood", 40, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("Instestin2", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathHalfHelltrooper", 32, 0, random(0, 360), 2, random(0, 160));
	Death:
	TNT1 A 0;
	Stop;
}
}

CLASS XDeathHalfHelltrooper : ACTOR { 
Default
{
	Radius 8;
	Height 8;
	Speed 7;
	Mass 8;
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSplat";
}
 
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("pb_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		HTMX F 12 a_spawnprojectile("Brutal_FlyingBloodTrails",0,0,180,2);
	Loop;
	Death:
		TNT1 A 0 A_SpawnItem("pb_Blood_Spot",0,0,0,1);
		HTMX F 0 A_SpawnItem("GibHalfHelltrooper",0,0,0,1);
	Stop;
}
}

CLASS GibHalfHelltrooper: pb_blood_and_gore_base { 
    States
    {
	Spawn:
		HTMX F 1900 A_SpawnItem("pb_Blood_Spot",0,0,0,1);
	Loop;
}}


CLASS DeadHellTrooper_Pinned: ZombiemanTorso { 
	Default {
	+NOPAIN;
	+NOGRAVITY;
	Health 200;
	DamageFactor "Head", 15.0;
	Height 40;
	Radius 6;
	}
States{Spawn:
	TNT1 A 0;
	TNT1 A 0 A_PlaySound("Weapons/NailHitBleed");
	TNT1 A 0 A_Recoil(15);
	PIN9 AA 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_Recoil(10);
	PIN9 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	PIN9 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_Recoil(10);
	PIN9 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	PIN9 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_Recoil(10);
	PIN9 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	PIN9 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_Recoil(10);
	PIN9 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	PIN9 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_Recoil(10);
	PIN9 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	JustHangThere:
	TNT1 A 0 A_Recoil(6);
	PIN9 A 6;
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	PIN9 A 16;
	Loop;
	
	LayDown:
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_SpawnItem("DeadFormerScientist");
	Stop;
	
	XDeath:
	Death.Explosives:
	Death.ExplosiveImpact:
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_SpawnItem("SargeXDeath");
	Stop;
	
	Death:
	TNT1 AAA 0 bright a_spawnprojectile("SuperGoreSpawner", 35, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
	TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
	TNT1 AA 0 a_spawnprojectile("XDeathArm1", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeathSergeantHead", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0;
	TNT1 A 0 A_NoBlocking();
	SZD1 EFGH 3;
	TNT1 A 0 A_SpawnItem("DeadShotgunguyJustLegsAreLeft");
	Stop;
}}
CLASS Trooperbullet: pb_projectile_base { 
	Default {
	
	Projectile;
	+RANDOMIZE;
	+FORCEXYBILLBOARD;
	+BLOODSPLATTER;
	+NOEXTREMEDEATH;
	-TELESTOMP;
	+NOTELEFRAG;
	damagefunction(random(8,11));
	damagetype "fire";
	DamageFactor "Blood", 0.0; DamageFactor "BlueBlood", 0.0; DamageFactor "GreenBlood", 0.0;
	radius 2;
	height 2;
	renderstyle "Add";
	//alpha 0.65
	speed 110;
	scale .20;
	Decal "Scorch";
	Deathsound "Weapons/Demontech/Crash";
	}
	states
	{
	Spawn:
		PBAL HI 2 BRIGHT A_SpawnItem("Red_Flare",0,0);
		TNT1 A 0 a_spawnprojectile("RedTracerSmall", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_SpawnItemEx("bfg_4_laser_train", random(5,-5), random(5,-5), random(5,-5), 0, 0, 0, 0, 128, 0);
		Loop;
	Xdeath:
		
		TNT1 A 0;//a_spawnprojectile("Flametrails", 0, 0, random(0, 180), 2, random(0, 360))
		TNT1 A 0 A_SpawnItem("HellRifle_Puff",0);
		TNT1 A 0 BRIGHT A_SpawnItem("Red_Flare",0);
		TNT1 AA 0 A_SpawnItemEx("ExplosionParticle", random(-8, 8), random(-8, 8), random(-2,2), 0, 0, 0, 0, 128, 0);
		TNT1 A 0 A_SpawnItemEx("bfg_4_laser_train", random(-8, 8), random(-8, 8), random(-2,2), 0, 0, 0, 0, 128, 0);
		TNT1 A 4;
		Stop;
		
	Death:
		TNT1 A 0 A_SpawnItem("HellRifle_Puff2",0);
		TNT1 A 0 BRIGHT A_SpawnItem("Red_Flare",0);
		TNT1 AA 0 A_SpawnItemEx("ExplosionParticle", random(-8, 8), random(-8, 8), random(-2,2), 0, 0, 0, 0, 128, 0);
		TNT1 AA 0 A_SpawnItemEx("bfg_4_laser_train", random(-8, 8), random(-8, 8), random(-2,2), 0, 0, 0, 0, 128, 0);
		TNT1 A 4;
		TNT2 AAAAA 4 a_spawnprojectile("ExplosionSmoke", 1, 0, random(0, 360), 2, random(0, 160));
		Stop;
	}
}
