CLASS pb_suicide_Bomber : proto_zombieman_class
{ //22099
Default
{		
	obituary "%o was killed by a crazy suicide bomber.";
	health 70;
	radius 20;
	height 56;
	mass 100;
	Scale .98;
	speed 18;
	//SpawnID 1280;
	PainChance 32;
	PainChance "Kick", 255;
	PainChance "Melee", 255;
	PainChance "MonsterKnocked", 255;
	PainChance "ExplosiveImpact", 255;
	PainChance "Taunt", 255;
	PainChance "Stun", 255;
	DamageFactor "Saw", 0.15;
	DamageFactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	DamageFactor "bloodsplasher", 0.0;    DamageFactor "tinybloodsplasher", 0.0;
	DamageFactor "superbloodsplasher", 0.0;    DamageFactor "smallbloodsplasher", 0.0;
	DamageFactor "BlueBloodSplasher", 0.0;
	DamageFactor "BlueSuperBloodSplasher", 0.0;
	Monster;
	Damagetype "ExplosiveImpact";
	+forceradiusdmg
	+FLOORCLIP;
	//-TELESTOMP
	//-NOTELEFRAG
	//+NOTELESTOMP
	//+TELESTOMP
	//+THRUACTORS
	BloodType "brutal_Blood", "BloodSPlatterReplacer", "brutal_Blood";
	DamageFactor "Blood", 0.0; DamageFactor "BlueBlood", 0.0; DamageFactor "GreenBlood", 0.0;
	DamageFactor "Shrapnel", 0.3;
	DamageFactor "Kick", 0.4;
	DamageFactor "MinorHead", 2.0;
	DamageFactor "Head", 2.0;
	DamageFactor "taunt", 0.0;
	seesound "suicide/sit";
	PainSound "grunt/pain";
	DeathSound "null";
	//ActiveSound "grunt/active"
}

states
{
	Pain.Stun:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx("StunElectrocute", random(-4, 4), random(-4, 4),  random(16, 32), 0, 0);
		BMBE A 1 A_Pain();
		BMBE AAAAAAAAAA 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		BMBE A 1 A_Pain();
		BMBE AAAAAAAAAA 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		BMBE A 1 A_Pain();
		BMBE AAAAAAAAAA 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		BMBE A 1 A_Pain();
		BMBE AAAAAAAAAA 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		BMBE A 1 A_Pain();
		BMBE AAAAAAAAAA 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		BMBE A 1 A_Pain();
	Goto See;

	Spawn:
		BMRZ A 4 A_Look();
	loop;
			
	See:
		BMRZ A 0 A_PlaySound("OPNGRN", 3);
		BMRZ E 4;
		TNT1 A 0 A_PlaySound("suicide/scream", 2);
		BMRZ FGFGFGFGFGFGFGFGFG 1;
	AlahAkbar:
		BMBE AAABBBCCCDDD 2 A_Chase();
		BMBE A 0 A_PlaySound("suicide/scream", 1);
	loop;

	Melee:
		BMBE A 0 A_Die();
	stop;

	Pain:
		BMBE A 3;
		BMBE A 3 A_Pain();
	goto See;

	Death:
		BMBE M 0 bright A_Explode(6, 128);
		EXPL A 0 Radius_Quake(2, 40, 0, 8, 0);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0
		{
			for(int i = 0; i < 4; i++)
			{
				A_PlaySound("FAREXPL");
				A_PlaySound("Explosion", 1);
				a_spawnprojectile("CasingSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
			}
		}
		TNT1 A 0 a_spawnprojectile("MetalShard1", 5, 0, random(0, 360), 2, random(30, 160));
		TNT1 A 0 a_spawnprojectile("SargeXDeath", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("MetalShard1", 5, 0, random(0, 360), 2, random(30, 160));
		TNT1 A 0 a_spawnprojectile("MetalShard1", 5, 0, random(0, 360), 2, random(30, 160));
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_Explode(65, 170, damagetype:"ExplosiveImpact");
		TNT1 AAAAAAAAAAAAAAAAAAAAA 0
		{
			pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");
		}
		TNT1 A 0 A_QuakeEx(1, 1, 1, 12, 0, 420, "", 0);
		TNT1 AAAAAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		EXPL AAA 0 a_spawnprojectile("CasingSmoke", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAA 1 a_spawnprojectile("ExplosionSmoke", 2, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 AAAAAAAAA 2 a_spawnprojectile("CasingSmoke", 2, 0, random(0, 360), 2, random(0, 360));
		BMBE M 0 bright A_PlaySound("weapons/rocklx");
		BMBE O 0 A_NoBlocking();
	stop;
}

}