class proto_zombieman_class : pb_monster_base
{
//exactly what it says
int ammo_amount, max_magazine_size;

property ammo_amount : ammo_amount;
property max_magazine_size : max_magazine_size;

int awareness;

default
{
	Height 54; //44+18
	pb_monster_base.headshot_multiplier 3;
	pb_monster_base.head_starting_position 48;
	pb_monster_base.legs_height_max 10;
	
	proto_zombieman_class.ammo_amount 0;
	proto_zombieman_class.max_magazine_size 0;
}

void pb_check_reloading(statelabel state_name = null)
{
	if(self.ammo_amount <= 0) {self.setstatelabel(state_name);}
}

states
{
	Death.Blackhole:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 27, 0, 0, 0, 0, 128);
		ID52 ABCDEFGHIJ 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 0, 6, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
	stop;
}


}




















class monsters_hand_grenade : pb_projectile_base
{
states
{
	spawn:
		tnt1 a 1 {console.printf("enemy grenade dont work for now");}
	stop;
}

}

class MonsterRiotTracer : pb_projectile_base
{
states
{
	spawn:
		tnt1 a 10 {console.printf("plug for MonsterRiotTracer spawned");}
	stop;
}

}

class FallingHeight : inventory {}
class IsDown : inventory {}
class Enraged : inventory {}
class NoZombieGrenade : inventory {}
class SKZombieman : inventory {}
class TypeZombieMan : inventory {}
class ZombiemanAmmo : inventory {default{inventory.maxamount 100;} }
class SKHelmetZombie1 : inventory {}
class EnemyMemory : inventory {default{inventory.maxamount 100;} }
class ZombieManGrenadeCount : inventory {default{inventory.maxamount 100;} }





































CLASS XDeathZombieLeg: XDeathArm1 { 
	Default {
	
	Scale 1.1;
	Speed 8;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		LEG1 ABCDEFGH 5 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		LEG1 E 1;
		LEG1 E 0 A_SpawnItem("Gib_ZombieLeg1");
		Stop;
	}
}


CLASS Gib_ZombieLeg1: LimbBase { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG1 E 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		LEG1 E -1;
		Stop;
	Death.plasma:    TNT1 A 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:    
		TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("GibZombieLegPart", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GibZombieBoot", 0, 0, random(0, 180), 2, random(0, 180));
		Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		LEG1 EE 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathZombieLeg", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		LEG1 ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		LEG1 A 5;
		LEG1 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
		Goto Landz;
	Landz:
		XDT5 I 0 A_SpawnItem("Gib_ZombieLeg2");
		Stop;
}}


CLASS XDeathPlasmaZombieLeg: XDeathArm1 { 
	Default {
	
	Scale 1.1;
	Speed 8;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		ZM42 ABCDEFGH 5 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		ZM42 I 1;
		ZM42 E 0 A_SpawnItem("Gib_PlasmaZombieLeg");
		Stop;
	}
}


CLASS Gib_PlasmaZombieLeg: LimbBase { 
	Default {
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		ZM42 I 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		ZM42 I -1;
		Stop;
	Death.plasma: 
	TNT1 A 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:    
		TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("GibZombieLegPart", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GibZombieBoot", 0, 0, random(0, 180), 2, random(0, 180));
		Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		ZM42 I 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathPlasmaZombieLeg", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		ZM42 ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		ZM42 I 5;
		ZM42 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
		Goto Landz;
	Landz:
		XDT5 I 0 A_SpawnItem("Gib_PlasmaZombieLeg");
		Stop;
		
}}

CLASS GibZombieLegPart: TinyGib { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG1 Z -1;
		Stop;
	Death:
		LEG1 Z 1;
		Loop;
}}

CLASS GibZombieBoot: TinyGib { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG1 Y -1;
		Stop;
	Death:
		LEG1 Y 1;
		Loop;
}}


CLASS XDeathZombieLeg2: XDeathZombieLeg { 
	Default {
	
	Speed 8;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		LEG1 ABCDEFGH 5 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		LEG1 A 1;
		TNT1 A 0 A_SpawnItem("Gib_ZombieLeg2");
		Stop;
	}
}


CLASS Gib_ZombieLeg2: LimbBase { 
	Default {
	
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG1 A 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		LEG1 A -1;
		Stop;
	Death.plasma: 
	TNT1 A 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));  
	Stop;
	Death:    
		TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("GibZombieLegPart", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GibZombieBoot", 0, 0, random(0, 180), 2, random(0, 180));
		Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		LEG1 AA 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathZombieLegKicked", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		LEG1 ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		LEG1 A 5;
		LEG1 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
		Goto Landz;
	Landz:
		XDT5 I 0 A_SpawnItem("Gib_ZombieLeg1");
		Stop;
}}

CLASS XDeathZombieLegKicked: XDeathZombieLeg { 
	Default {
	
	+ACTIVATEMCROSS;
	+ACTIVATEIMPACT;
	}
}