class proto_zombieman_class : pb_monster_base
{
//exactly what it says
int ammo_amount, max_magazine_size;

property ammo_amount : ammo_amount;
property max_magazine_size : max_magazine_size;

int awareness;

default
{
	Height 54; //44+18
	pb_monster_base.headshot_multiplier 3;
	pb_monster_base.head_starting_position 48;
	pb_monster_base.legs_height_max 10;
	
	proto_zombieman_class.ammo_amount 0;
	proto_zombieman_class.max_magazine_size 0;
}

void pb_check_reloading(statelabel state_name = null)
{
	if(self.ammo_amount <= 0) {self.setstatelabel(state_name);}
}

states
{
	Death.Blackhole:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 27, 0, 0, 0, 0, 128);
		ID52 ABCDEFGHIJ 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 0, 6, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
	stop;
}


}




















class monsters_hand_grenade : pb_projectile_base
{
states
{
	spawn:
		tnt1 a 1 {console.printf("enemy grenade dont work for now");}
	stop;
}

}

class MonsterRiotTracer : pb_projectile_base
{
states
{
	spawn:
		tnt1 a 10 {console.printf("plug for MonsterRiotTracer spawned");}
	stop;
}

}

class FallingHeight : inventory {}
class IsDown : inventory {}
class Enraged : inventory {}
class NoZombieGrenade : inventory {}
class SKZombieman : inventory {}
class TypeZombieMan : inventory {}
class ZombiemanAmmo : inventory {default{inventory.maxamount 100;} }
class SKHelmetZombie1 : inventory {}
class EnemyMemory : inventory {default{inventory.maxamount 100;} }
class ZombieManGrenadeCount : inventory {default{inventory.maxamount 100;} }





































CLASS XDeathZombieLeg: XDeathArm1 { 
	Default {
	
	Scale 1.1;
	Speed 8;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		LEG1 ABCDEFGH 5 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		LEG1 E 1;
		LEG1 E 0 A_SpawnItem("Gib_ZombieLeg1");
		Stop;
	}
}


CLASS Gib_ZombieLeg1: LimbBase { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG1 E 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		LEG1 E -1;
		Stop;
	Death.plasma:    TNT1 A 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:    
		TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("GibZombieLegPart", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GibZombieBoot", 0, 0, random(0, 180), 2, random(0, 180));
		Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		LEG1 EE 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathZombieLeg", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		LEG1 ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		LEG1 A 5;
		LEG1 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
		Goto Landz;
	Landz:
		XDT5 I 0 A_SpawnItem("Gib_ZombieLeg2");
		Stop;
}}


CLASS XDeathPlasmaZombieLeg: XDeathArm1 { 
	Default {
	
	Scale 1.1;
	Speed 8;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		ZM42 ABCDEFGH 5 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		ZM42 I 1;
		ZM42 E 0 A_SpawnItem("Gib_PlasmaZombieLeg");
		Stop;
	}
}


CLASS Gib_PlasmaZombieLeg: LimbBase { 
	Default {
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		ZM42 I 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		ZM42 I -1;
		Stop;
	Death.plasma: 
	TNT1 A 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:    
		TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("GibZombieLegPart", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GibZombieBoot", 0, 0, random(0, 180), 2, random(0, 180));
		Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		ZM42 I 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathPlasmaZombieLeg", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		ZM42 ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		ZM42 I 5;
		ZM42 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
		Goto Landz;
	Landz:
		XDT5 I 0 A_SpawnItem("Gib_PlasmaZombieLeg");
		Stop;
		
}}

CLASS GibZombieLegPart: TinyGib { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG1 Z -1;
		Stop;
	Death:
		LEG1 Z 1;
		Loop;
}}

CLASS GibZombieBoot: TinyGib { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG1 Y -1;
		Stop;
	Death:
		LEG1 Y 1;
		Loop;
}}


CLASS XDeathZombieLeg2: XDeathZombieLeg { 
	Default {
	
	Speed 8;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		LEG1 ABCDEFGH 5 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		LEG1 A 1;
		TNT1 A 0 A_SpawnItem("Gib_ZombieLeg2");
		Stop;
	}
}


CLASS Gib_ZombieLeg2: LimbBase { 
	Default {
	
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG1 A 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		LEG1 A -1;
		Stop;
	Death.plasma: 
	TNT1 A 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));  
	Stop;
	Death:    
		TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("GibZombieLegPart", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GibZombieBoot", 0, 0, random(0, 180), 2, random(0, 180));
		Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		LEG1 AA 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathZombieLegKicked", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		LEG1 ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		LEG1 A 5;
		LEG1 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
		Goto Landz;
	Landz:
		XDT5 I 0 A_SpawnItem("Gib_ZombieLeg1");
		Stop;
}}

CLASS XDeathZombieLegKicked: XDeathZombieLeg { 
	Default {
	
	+ACTIVATEMCROSS;
	+ACTIVATEIMPACT;
	}
}


CLASS XDeathSargeLeg1: XDeathArm1 { 
	Default {
	
	Scale 1.1;
	Speed 8;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		LEG2 ABCDEFGH 5 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		LEG2 A 1;
		LEG2 A 0 A_SpawnItem("Gib_SargeLeg");
		Stop;
	}
}

CLASS Gib_SargeLeg: LimbBase { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG2 A 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		LEG2 A -1;
		Stop;
	Death.plasma:    TNT1 A 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160)); 
	Stop;
	Death:    
		TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("GibSargeLegPart", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GibSargeBoot", 0, 0, random(0, 180), 2, random(0, 180));
		Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		LEG2 A 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathSargeLeg1", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		LEG2 ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		LEG2 ABCDEFGH 5;
		XDT5 I 0 A_SpawnItem("Gib_SargeLeg");
		Stop;
		
}}

CLASS GibSargeLegPart: TinyGib { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG2 Z -1;
		Stop;
	Death:
		LEG2 Z 1;
		Loop;
}}

CLASS GibSargeBoot: TinyGib { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG2 Y -1;
		Stop;
	Death:
		LEG2 Y 1;
		Loop;
}}



CLASS XDeathSargeLeg2: XDeathArm1 { 
	Default {
	
	Scale 1.1;
	Speed 8;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		LEG2 ABCDEFGH 5 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		LEG2 E 1;
		LEG2 E 1 A_SpawnItem("Gib_SargeLeg2");
		Stop;
	}
}

CLASS Gib_SargeLeg2: Gib_SargeLeg { 
	Default {
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG2 E 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		LEG2 E -1;
		Stop;
	Death.plasma:    TNT1 A 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:    
		TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("GibSargeLegPart", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GibSargeBoot", 0, 0, random(0, 180), 2, random(0, 180));
		Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		LEG2 A 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathSargeLeg1", 5, 0, random(170, 190), 2, random(20, 40));
Stop;}}


CLASS XDeathHalfZombieman : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Scale 1.0;
	Speed 6;
	Mass 4;
	Decal "BrutalBloodSplat";
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		POSX F 12;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		POSX F 1 A_SpawnItem("Gib_HalfZombieman",0,0,0,1);
		TNT1 A 0;
		Stop;
	}
}

CLASS XDeathHalfZSpecOPs : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Scale 1.0;
	Speed 6;
	Mass 4;
	Decal "BrutalBloodSplat";
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		ZP3X B 12;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		ZP3X B 1 A_SpawnItem("Gib_HalfZSpecOPs",0,0,0,1);
		TNT1 A 0;
		Stop;
	}
}

CLASS XDeathHalfHelmetZombieman : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Scale 1.0;
	Speed 6;
	Mass 4;
	Decal "BrutalBloodSplat";
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		4OSX F 12;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		4OSX F 1 A_SpawnItem("Gib_HalfHelmetZombieman",0,0,0,1);
		TNT1 A 0;
		Stop;
	}
}

CLASS XDeathHalfHFQSZ : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Scale 1.0;
	Speed 6;
	Mass 4;
	Decal "BrutalBloodSplat";
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		QP3X F 12;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		QP3X F 1 A_SpawnItem("Gib_HalfHFQSZ",0,0,0,1);
		TNT1 A 0;
		Stop;
	}
}

CLASS Gib_HalfZombieMan: BigGibBase { 
	Default {
	
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		POSX F 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		POSX F -1;
Stop;    }}
	   
CLASS Gib_HalfHelmetZombieMan: BigGibBase { 
	Default {
	
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		4OSX F 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		4OSX F -1;
Stop;    }}
	   
CLASS Gib_HalfHFQSZ: BigGibBase { 
	Default {
	
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		QP3X G 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		QP3X G -1;
Stop;    }}
	   
CLASS Gib_HalfZSpecOPs: BigGibBase { 
	Default {
	
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		ZP3X C 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		ZP3X C -1;
Stop;    }}
	   

CLASS XDeathHalfZombiemanNoArmNoHead : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	
	Speed 10;
	Gravity 0.7;
	Mass 4;
	Decal "BrutalBloodSplat";
	BounceFactor 0.01;
	+DOOMBOUNCE;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	Scale 1.3;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		POSX GHIJKLMN 4;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
		TNT1 A 0 A_SpawnItem("Gib_HalfZombiemanNoArmNoHead",0,0,0,1);
		Stop;
	}
}

CLASS Gib_HalfZombieManNoArmNoHead: BigGibBase { 
	Default {
	
	Scale 1.3;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		POSX O -1;
Stop;    }}
	   
	   
CLASS XDeathHalfPlasmaZombiemanNoArmNoHead : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	
	Speed 10;
	Gravity 0.7;
	Mass 4;
	Decal "BrutalBloodSplat";
	BounceFactor 0.01;
	+DOOMBOUNCE;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	Scale 1.3;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		ZM40 ABCDEFGH 4;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
		TNT1 A 0 A_SpawnItem("Gib_HalfPlasmaZombieManNoArmNoHead",0,0,0,1);
		Stop;
	}
}

CLASS Gib_HalfPlasmaZombieManNoArmNoHead: BigGibBase { 
	Default {
	
	Scale 1.3;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		ZM40 I -1;
Stop;    }}	
	   
CLASS XDeathHalfLabGuyNoArmNoHead : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	
	Speed 10;
	Gravity 0.7;
	Mass 4;
	Decal "BrutalBloodSplat";
	BounceFactor 0.01;
	+DOOMBOUNCE;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	Scale 1.3;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		PLSX GHIJKLMN 4;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
		TNT1 A 0 A_SpawnItem("Gib_HalfLabguyNoArmNoHead",0,0,0,1);
		Stop;
	}
}

CLASS Gib_HalfLabguyNoArmNoHead: BigGibBase { 
	Default {
	
	Scale 1.3;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		PLSX O -1;
Stop;    }}



CLASS XDeathHalfShotgunguyNoArmNoHead : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	
	Speed 10;
	Gravity 0.7;
	Mass 4;
	Decal "BrutalBloodSplat";
	BounceFactor 0.01;
	+DOOMBOUNCE;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	Scale 1.3;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		SPSX GHIJKLMN 4;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
		TNT1 A 0 A_SpawnItem("Gib_HalfShotgunguyNoArmNoHead",0,0,0,1);
		Stop;
	}
}

CLASS XDeathHalfChaingunMajorNoArmNoHead : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	
	Speed 10;
	Gravity 0.7;
	Mass 4;
	Decal "BrutalBloodSplat";
	BounceFactor 0.01;
	+DOOMBOUNCE;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	Scale 1.55;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		4CH7 ABCDEFGH 4;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
		TNT1 A 0 A_SpawnItem("Gib_HalfChaingunMajorNoArmNoHead",0,0,0,1);
		Stop;
	}
}

CLASS Gib_HalfShotgunguyNoArmNoHead: BigGibBase { 
	Default {
	
	Scale 1.3;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		SPSX O -1;
Stop;    }}	
	   
CLASS Gib_HalfChaingunMajorNoArmNoHead: BigGibBase { 
	Default {
	
	Scale 1.55;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		4CH7 I -1;
Stop;    }}	


CLASS XDeathHalfZombiemanDown : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Scale 1.1;
	Speed 6;
	Mass 4;
	Decal "BrutalBloodSplat";
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	Stay:
		POSX D 2000;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		POSX E 0 A_SpawnItem("GibHalfZombiemanDown",0,0,0,1);
		Stop;
	}
}

CLASS GibHalfZombiemanDown: BigGibBase { 
	Default {
	
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		POSX E 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		POSX E -1;
Stop;    }}



CLASS XDeathHalfSergeant : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Speed 7;
	Mass 8;
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		SP2X F 12 a_spawnprojectile("Brutal_FlyingBloodTrails",0,0,180,2);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		SP2X G 0 A_SpawnItem("GibHalfSergeant",0,0,0,1);
		Stop;
	}
}


CLASS XDeathHalfPlasmaZombie2 : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Speed 1;
	Mass 8;
	BounceFactor 0.1;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		ZMS0 FG 7;
	Fly:
		ZMS0 H 12 a_spawnprojectile("Brutal_FlyingBloodTrails",0,0,180,2);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		ZMS0 I 6;
		TNT1 A 0 A_SpawnItem("GibHalfPlasmaZombie2",0,0,0,1);
		Stop;
	}
}

CLASS GibHalfPlasmaZombie2: BigGibBase { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		ZMS0 I 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		ZMS0 I -1;
Stop;    }}


CLASS XDeathHalfSergeant2 : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Speed 1;
	Mass 8;
	BounceFactor 0.1;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		SXD1 JK 7;
	Fly:
		SXD1 L 12 a_spawnprojectile("Brutal_FlyingBloodTrails",0,0,180,2);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		SXD1 M 6;
		SXD1 N 0 A_SpawnItem("GibHalfSergeant2",0,0,0,1);
		Stop;
	}
}

CLASS GibHalfSergeant2: BigGibBase { 
	Default {
	
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		SXD1 N 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		SXD1 N -1;
Stop;    }}

CLASS XDeathHalfHelmetSergeant : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Speed 7;
	Mass 8;
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		SP4X F 12 a_spawnprojectile("Brutal_FlyingBloodTrails",0,0,180,2);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		SP4X G 0 A_SpawnItem("GibHalfHelmetSergeant",0,0,0,1);
		Stop;
	}
}

CLASS GibHalfHelmetSergeant: BigGibBase { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		SP4X G 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		SP4X G -1;
Stop;    }}


CLASS XDeathHalfChaingunGuy1 : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Speed 7;
	Mass 8;
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		CP04 W 12 a_spawnprojectile("Brutal_FlyingBloodTrails",0,0,180,2);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 G 0 A_SpawnItem("GibHalfChaingunGuy1",0,0,0,1);
		Stop;
	}
}

CLASS GibHalfChaingunGuy1: CurbstompedMarine { 
	Default {
	
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		CP04 X 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		CP04 X -1;
Stop;    }}
	   
CLASS XDeathHalfChaingunGuy2 : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Speed 7;
	Mass 8;
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		CP06 K 12 a_spawnprojectile("Brutal_FlyingBloodTrails",0,0,180,2);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 G 0 A_SpawnItem("GibHalfChaingunGuy2",0,0,0,1);
		Stop;
	}
}

CLASS GibHalfChaingunGuy2: CurbstompedMarine { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		CP06 L 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		CP06 L -1;
		Stop;
}}
////////////////////////////////
CLASS GibHalfHelmetChaingunGuy1: BigGibBase { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		C404 X 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		C404 X -1;
Stop;    }}

CLASS XDeathHalfHelmetChaingunGuy1 : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Speed 7;
	Mass 8;
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		C404 W 12 a_spawnprojectile("Brutal_FlyingBloodTrails",0,0,180,2);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 G 0 A_SpawnItem("GibHalfHelmetChaingunGuy1",0,0,0,1);
		Stop;
	}
}

	   
CLASS XDeathHalfHelmetChaingunGuy2 : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Speed 7;
	Mass 8;
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		C404 K 12 a_spawnprojectile("Brutal_FlyingBloodTrails",0,0,180,2);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 G 0 A_SpawnItem("GibHalfHelmetChaingunGuy2",0,0,0,1);
		Stop;
	}
}

CLASS GibHalfHelmetChaingunGuy2: BigGibBase { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		C404 L 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		C404 L -1;
Stop;    }}

////////////////////////////////
CLASS XDeathHalfZombieman2 : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Speed 7;
	Mass 8;
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		PP2X F 12 a_spawnprojectile("Brutal_FlyingBloodTrails",0,0,180,2);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 G 0 A_SpawnItem("GibHalfZombieman2",0,0,0,1);
		Stop;
	}
}

CLASS GibHalfZombieman2: BigGibBase { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		PP2X G 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		PP2X G -1;
Stop;    }}

CLASS XDeathHalfHelmetZombieman2 : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Speed 7;
	Mass 8;
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		4P2X F 12 a_spawnprojectile("Brutal_FlyingBloodTrails",0,0,180,2);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_SpawnItem("GibHalfHelmetZombieman2",0,0,0,1);
		Stop;
	}
}

CLASS GibHalfHelmetZombieman2: BigGibBase { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		4P2X G 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		4P2X G -1;
Stop;    }}

CLASS GibHalfSergeant: BigGibBase { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		SP2X G 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		SP2X G -1;
Stop;    }}


CLASS XDeathZombieManHead: XDeathBullArm1 { 
	Default {
	
	-CLIENTSIDEONLY;
	Radius 10;
	Scale 1.0;
	}
	States
	{
	Spawn:
	Spawn1:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		XHE2 AB 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		XHE2 CDEFGH 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		Loop;
	Death:
		XHE2 E 1;
		XHE2 E 1 A_SpawnItem("ZombieManHead",0,0,0,1);
		Stop;
	}
}


CLASS XDeathZombiemanHeadBeheaded: XDeathZombieManHead { 
	Default {
	
	Speed 5;
	Gravity 0.5;
	}
}


CLASS XDeathZombiemanHeadOnXDeath: XDeathZombieManHead { 
	Default {
	
	}
	States
	{
	Spawn:
		TNT1 A 1;
		TNT1 A 0 A_jump(96, "ExplodeOnAir");
		Goto Spawn1;
	ExplodeOnAir:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("ZombiemanHeadExplode");
		Stop;
}}

CLASS ZombiemanHead: LimbBase { 
	Default {
	
	damagefactor "Kick", 99.0;
	damagefactor "Melee", 99.0;
	damagefactor "SuperPunch", 99.0;
	-CLIENTSIDEONLY;
	+SHOOTABLE;
	+THRUACTORS;
	damagefactor "Crush", 50.0;
	Radius 10;
	
	Mass 12;
	Health 40;
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
	Spawn1:
		XHE2 C 1;
		XHE2 C -1;
		Stop;
	Spawn2:
		XHE2 G 1;
		XHE2 G -1;
		Stop;
	Spawn3:
		XHE2 H 1;
		XHE2 H -1;
		Stop;
		
	Death.Trample:
	Death.Stomp:
		//TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
		Goto Death;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("ZombiemanHeadExplode");
		Stop;
	Crush:
		TNT1 AAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS1 B 5;
		CRS1 B 9009;
		Stop;
	Death.plasma:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL A 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0;
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		XHE2 EE 1 A_FaceTarget;
		TNT1 AAAA 0 A_SpawnItemEx("Blood", 0, 0, 10);
		TNT1 A 0 a_spawnprojectile("XDeathZombieManHeadKicked", 5, 0, random(170, 190), 2, random(20, 30));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		XHE2 ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		XHE2 ABCD 6;
		XDT5 I 0 A_SpawnItem("ZombiemanHead");
		Stop;
		
}}


CLASS XDeathZombieManHeadKicked: XDeathZombieManHead { 
	Default {
	
	-BOUNCEONACTORS;
	Damage 4;
	Speed 13;
	}
}



CLASS XDeathSergeantHead: XDeathZombieManHead { 
	States
	{
	Spawn:
	Spawn1:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		XHE1 AB 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		XHE1 CDEFGH 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		Loop;
	Death:
		XHE1 E 1;
		XHE1 E 1 A_SpawnItem("SergeantHead",0,0,0,1);
		Stop;
		
	}
}

CLASS XDeathLabguyHead: XDeathZombieManHead { 
	States
	{
	Spawn:
	Spawn1:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		FSHD AB 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		FSHD CDEFGH 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		Loop;
	Death:
		FSHD A 1;
		FSHD A 1 A_SpawnItem("LabguyHead",0,0,0,1);
		Stop;
		
	}
}

CLASS LabguyHead: ZombieManHead { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot");
		TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
	Spawn1:
		FSHD A 1;
		FSHD A -1;
		Stop;
	Spawn2:
		FSHD G 1;
		FSHD G -1;
		Stop;
	Spawn3:
		FSHD H 1;
		FSHD H -1;
		Stop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode");
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		FSHD EE 1 A_FaceTarget;
		TNT1 AAAA 0 A_SpawnItemEx("Blood", 0, 0, 10);
		TNT1 A 0 a_spawnprojectile("XDeathLabguyHead", 5, 0, random(170, 190), 2, random(20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		XHE1 ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		FSHD ABCDEFGH 3;
		XDT5 I 0 A_SpawnItem("LabguyHead");
		Stop;
		
}}

CLASS XDeathPlasmaZombieHead: XDeathZombieManHead { 
	Default {
	
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 {self.bTHRUSPECIES = false;}
	Spawn1:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		ZM41 ABCDEFGH 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		Loop;
	Death:
		ZM41 A 0;
		ZM41 A 0 A_SpawnItem("PlasmaZombieHead",0,0,0,1);
		Stop;
		
	}
}

CLASS PlasmaZombieHead: ZombieManHead { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot");
		TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
	Spawn1:
		ZM41 A 1;
		ZM41 A -1;
		Stop;
	Spawn2:
		ZM41 G 1;
		ZM41 G -1;
		Stop;
	Spawn3:
		ZM41 H 1;
		ZM41 H -1;
		Stop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("PlasmaZombieHeadExplode");
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		ZM41 A 1 A_FaceTarget;
		TNT1 AAAA 0 A_SpawnItemEx("Blood", 0, 0, 10);
		TNT1 A 0 a_spawnprojectile("XDeathPlasmaZombieHead", 5, 0, random(170, 190), 2, random(20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		ZM41 ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		ZM41 ABCDEFGH 3;
		XDT5 I 0 A_SpawnItem("PlasmaZombieHead");
		Stop;
}}



CLASS XDeathZSpecOpsHead: XDeathZombieManHead { 
	States
	{
	Spawn:
	Spawn1:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		ZHE2 ABCD 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		Loop;
	Death:
		ZHE2 E 1;
		ZHE2 E 1 A_SpawnItem("ZSpecOpsHead",0,0,0,1);
		Stop;
		
	}
}

CLASS ZSpecOpsHead: ZombieManHead { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot");
	Spawn1:
		ZHE2 E 1;
		ZHE2 E -1;
		Stop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode");
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		ZHE2 EE 1 A_FaceTarget;
		TNT1 AAAA 0 A_SpawnItemEx("Blood", 0, 0, 10);
		TNT1 A 0 a_spawnprojectile("XDeathZSpecOpsHead", 5, 0, random(170, 190), 2, random(20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		ZHE2 ABCD 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		ZHE2 ABCDEFGH 3;
		TNT1 A 0 A_SpawnItem("ZSpecOpsHead");
		Stop;
		
}}


CLASS XDeathSergeantHeadBeheaded: XDeathSergeantHead { 
	Default {
	
	Speed 5;
	Gravity 0.5;
	}
}

CLASS XDeathSergeantHeadOnXDeath: XDeathSergeantHead { 
	States
	{
	Spawn:
		TNT1 A 1;
		TNT1 A 0 A_jump(96, "ExplodeOnAir");
		Goto Spawn1;
	ExplodeOnAir:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode");
		Stop;
}}

CLASS SergeantHead: ZombieManHead { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot");
		TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
	Spawn1:
		XHE1 C 1;
		XHE1 C -1;
		Stop;
	Spawn2:
		XHE1 G 1;
		XHE1 G -1;
		Stop;
	Spawn3:
		XHE1 H 1;
		XHE1 H -1;
		Stop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode");
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		XHE1 EE 1 A_FaceTarget;
		TNT1 AAAA 0 A_SpawnItemEx("Blood", 0, 0, 10);
		TNT1 A 0 a_spawnprojectile("XDeathSergeantHead", 5, 0, random(170, 190), 2, random(20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		XHE1 ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		XHE1 ABCDEFGH 3;
		XDT5 I 0 A_SpawnItem("SergeantHead");
		Stop;
		
}}


CLASS SergeantHeadThrown: XDeathSergeantHead { 
	Default {
	
	+BOUNCEONACTORS;
	Damagefunction(random(30, 40));
	DamageType "Kick";
	-CLIENTSIDEONLY;
	Speed 20;
	Gravity 0.4;
	}
}


CLASS XDeathChaingunguyHead: XDeathBullArm1 { 
	Default {
	
	-CLIENTSIDEONLY;
	BounceCount 3;
	Scale 1.0;
	}
	States
	{
	Spawn:
	Spawn1:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		CHHE AB 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		CHHE CDEFGH 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		Loop;
	Death:
		XHE2 E 0;
		XHE2 E 0 A_SpawnItem("ChaingunguyHead",0,0,0,1);
		Stop;
	}
}

CLASS XDeathHelmetChaingunguyHead: XDeathBullArm1 { 
	Default {
	
	-CLIENTSIDEONLY;
	BounceCount 3;
	Scale 1.0;
	}
	States
	{
	Spawn:
	Spawn1:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		C1HE AB 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		C1HE CDEFGH 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		Loop;
	Death:
		XHE2 E 0;
		XHE2 E 0 A_SpawnItem("HelmetChaingunguyHead",0,0,0,1);
		Stop;
	}
}

CLASS XDeathChaingunguyHeadBeheaded: XDeathChaingunguyHead { 
	Default {
	
	Speed 5;
	Gravity 0.5;
	}
}


CLASS XDeathChaingunguyHeadOnXDeath: XDeathChaingunguyHead { 
	States
	{
	Spawn:
		TNT1 A 1;
		TNT1 A 0 A_jump(96, "ExplodeOnAir");
		Goto Spawn1;
	ExplodeOnAir:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("ChaingunguyHeadExplode");
		Stop;
}}

CLASS ChaingunguyHead: LimbBase { 
	Default {
	
	damagefactor "Kick", 9.0;
	damagefactor "Melee", 9.0;
	damagefactor "SuperPunch", 9.0;
	-CLIENTSIDEONLY;
	+SHOOTABLE;
	+SOLID;
	+THRUACTORS;
	damagefactor "Crush", 50.0;
	Radius 10;
	
	Mass 12;
	Health 40;
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		TNT1 A 0 A_Jump(256, "Spawn1", "SPawn2");
	Spawn1:
		CHHE A -1;
		Stop;
	Spawn2:  
		CHHE E -1;
		Stop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("ChaingunguyHeadExplode");
		Stop;
	Death.Trample:
	Crush:
		//TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
		TNT1 AAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS1 B 5;
		CRS1 B 9009;
		Stop;
	Death.plasma:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL A 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0;
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		CHHE EE 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathChaingunguyHeadKicked", 5, 0, random(170, 190), 2, random(20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		CHHE ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		CHHE ABCDEFGH 3;
		XDT5 I 0 A_SpawnItem("ChaingunguyHead");
		Stop;
		
}}

CLASS HelmetChaingunguyHead: LimbBase { 
	Default {
	
	damagefactor "Kick", 9.0;
	damagefactor "Melee", 9.0;
	damagefactor "SuperPunch", 9.0;
	-CLIENTSIDEONLY;
	+SHOOTABLE;
	+SOLID;
	+THRUACTORS;
	damagefactor "Crush", 50.0;
	Radius 10;
	
	Mass 12;
	Health 40;
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		TNT1 A 0 A_Jump(256, "Spawn1", "SPawn2");
	Spawn1:
		C1HE A -1;
		Stop;
	Spawn2:  
		C1HE E -1;
		Stop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("ChaingunguyHeadExplode");
		Stop;
	Death.Trample:
	Crush:
		//TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
		TNT1 AAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS1 B 5;
		CRS1 B 9009;
		Stop;
	Death.plasma:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL A 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0;
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		C1HE EE 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathHelmetChaingunguyHeadKicked", 5, 0, random(170, 190), 2, random(20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		C1HE ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		CHHE ABCDEFGH 3;
		XDT5 I 0 A_SpawnItem("ChaingunguyHead");
		Stop;
		
}}


CLASS XDeathChaingunguyHeadKicked: XDeathChaingunguyHead { 
	Default {
	
	-BOUNCEONACTORS;
	Damage 4;
	Speed 13;
	}
}

CLASS XDeathHelmetChaingunguyHeadKicked: XDeathHelmetChaingunguyHead { 
	Default {
	
	-BOUNCEONACTORS;
	Damage 4;
	Speed 13;
	}
}


CLASS XDeathHFQSZArm1 : pb_blood_and_gore_base { 
	Default {
 
    Radius 8;
    Height 8;
    Scale 0.8;
	Speed 8;
	Mass 1;
    gravity 0.5;
	Decal "BrutalBloodSplat";
bounceFactor 0.4;
	BounceCount 3;
	+DOOMBOUNCE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MISSILE;
	seesound "bloood";
	deathsound "bloood";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		QARM ABCDEFGH 5 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		QARM X 1;
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		QARM X 0 A_SpawnItem("Gib_HFQSZ_Arm");
		Stop;
	}
}

CLASS Gib_HFQSZ_Arm: LimbBase { 
	Default {
	
	Scale 0.8;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		QARM X 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		QARM X -1;
		Stop;
Death.plasma: Death.Burn: Death.Flames:
	    TNT1 A 0 a_spawnprojectile("XDeathBurnedArm", 32, 0, random(0, 360), 2, random(0, 160));
        Stop;
Death:    
	TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 A 0 a_spawnprojectile("GibHFQSZHand", 0, 0, random(0, 180), 2, random(0, 180));
	TNT1 A 0 a_spawnprojectile("GibHFQSZArmPart", 0, 0, random(0, 180), 2, random(0, 180));
	Stop;
Death.Kick:
Death.Melee:
Death.SuperPunch:
	QARM XX 1 A_FaceTarget;
	TNT1 A 0 a_spawnprojectile("XDeathHFQSZArm1Kicked", 5, 0, random(170, 190), 2, random(20, 40));
	Stop;
Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	QARM ABCDEFGH 3;
	Goto Spawn;
	
Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	QARM GH 3;
	QARM ABCDEFGHABDCEFGHABCDEFGH 3 A_CheckFloor("Landz");
	Goto Landz;
Landz:
	QARM X 0 A_SpawnItem("Gib_HFQSZ_Arm");
	Stop;
}}

CLASS XDeathHFQSZArm1Kicked: XDeathArm1 { 
	Default {
 
+ACTIVATEMCROSS
+ACTIVATEIMPACT
+CANUSEWALLS
	}
    States
    {
    Spawn:
	    TNT1 A 0 {self.bNOCLIP = true;}
	    QARM A 2;
	TNT1 A 0 {self.bNOCLIP = false;}
	TNT1 A 0;
        TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
	QARM ABCDEFGH 3 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
	Goto Spawn+3;
	}
}

CLASS GibHFQSZArmPart: TinyGib { 
	Default {
 
    Scale 0.8;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	QARM Z -1;
        Stop;
    Death:
QARM Z 1;
       Loop;
}}

CLASS GibHFQSZHand: TinyGib { 
	Default {
 
    Scale 0.8;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	QARM Y -1;
        Stop;
    Death:
QARM Y 1;
       Loop;
}}


CLASS XDeathHFQSZArm2: XDeathArm1 { 
	Default {
 
	Speed 10;
	}
}

// QSZ LEG

CLASS XDeathHFQSZLeg1: XDeathHFQSZArm1 { 
	Default {
 
    Scale 1.1;
    Speed 8;
	Gravity 0.4;
bounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		LEGQ ABCDEFGH 5 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		LEGQ A 1;
		LEGQ A 0 A_SpawnItem("Gib_HFQSZLeg",0,0,0,1);
		Stop;
	}
}

CLASS Gib_HFQSZLeg: LimbBase { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEGQ A 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		LEGQ A -1;
		Stop;
	Death.plasma:
    TNT1 A 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:    
		TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("GibHFQSZLegPart", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GibHFQSZBoot", 0, 0, random(0, 180), 2, random(0, 180));
		Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		LEGQ A 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZLeg1", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		LEGQ ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		LEGQ ABCDEFGH 5;
		XDT5 I 0 A_SpawnItem("Gib_HFQSZLeg");
		Stop;
		
}}

CLASS GibHFQSZLegPart: TinyGib { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEGQ Z -1;
		Stop;
	Death:
		LEGQ Z 1;
		Loop;
}}

CLASS GibHFQSZBoot: TinyGib { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEGQ Y -1;
		Stop;
	Death:
		LEGQ Y 1;
		Loop;
}}



CLASS XDeathHFQSZLeg2: XDeathHFQSZArm1 { 
	Default {
	
	Scale 1.1;
	Speed 8;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		LEGQ ABCDEFGH 5 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		LEGQ E 1;
		LEGQ A 0 A_SpawnItem("Gib_HFQSZLeg2",0,0,0,1);
		Stop;
	}
}

CLASS Gib_HFQSZLeg2: Gib_HFQSZLeg { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEGQ E 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		LEGQ E -1;
		Stop;
	Death.plasma:
    TNT1 A 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:    
		TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("GibHFQSZLegPart", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GibHFQSZBoot", 0, 0, random(0, 180), 2, random(0, 180));
		Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		LEGQ A 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZLeg1", 5, 0, random(170, 190), 2, random(20, 40));
Stop;}}
	
CLASS XDeathHalfHFQSZDown : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Scale 1.1;
	Speed 6;
	Mass 4;
	Decal "BrutalBloodSplat";
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		QZD1 G 12;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		QZD1 H 0 A_SpawnItem("GibHalfHFQSZDown",0,0,0,1);
		Stop;
	}
}

CLASS GibHalfHFQSZDown: BigGibBase { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		QZD1 H 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		QZD1 H -1;
Stop;    }}
	   
CLASS HFQSZFatality1Aftermath: BigGibBase { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		QZFT A 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		QZFT A -1;
Stop;    }}
	   

CLASS GibHalfHFQSZ: BigGibBase { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		QP3X G 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		QP3X G -1;
Stop;    }}
	   
CLASS XDeathHFQSZHead: XDeathZombieManHead { 
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		XHEQ ABCD 6;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		QHED A 1;
		QHED A 1 A_SpawnItem("HFQSZHead",0,0,0,1);
		Stop;
		
	}
}

CLASS HFQSZHead: ZombieManHead { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		QHED A 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		QHED A -1;
		Stop;
	Death:
		TNT1 AAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains2", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains2", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains4", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains4", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 AAAAAA 0 a_spawnprojectile("SmallBrainPiece", 5, 0, random(0, 360), 2, random(60, 140));
		HEDQ A -1;
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		HEDQ AA 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZHead", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		XHEQ ABCD 3;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		XHEQ ABCD 6;
		XDT5 I 0 A_SpawnItem("HFQSZHead");
		Stop;
		
}}


CLASS ZombieXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 40, 0, random(0, 360), 2, random(-15, 15));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfZombiemanNoArmNoHead", 48, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath5", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath2", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath3", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathSkinPiece2", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathSkinPiece1", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathZombieLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("GibZombieBoot", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathZombiemanHeadOnXDeath", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
		
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("SuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
}
}

CLASS ZombieHelmetXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 40, 0, random(0, 360), 2, random(-15, 15));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfZombiemanNoArmNoHead", 48, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath5", 32, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathZombieLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("GibZombieBoot", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZHead", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
		
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("SuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
}
}

CLASS PlasmaZombieXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 40, 0, random(0, 360), 2, random(-15, 15));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfPlasmaZombiemanNoArmNoHead", 48, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath5", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath2", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath3", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathSkinPiece2", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathSkinPiece1", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathPlasmaZombieLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("GibZombieBoot", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathPlasmaZombieHead", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
		
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("SuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
}
}

CLASS LabGuyXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 40, 0, random(0, 360), 2, random(-15, 15));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathLabGuyArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfLabguyNoArmNoHead", 48, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath5", 32, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSargeLeg2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("GibSargeLegPart", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("GibSargeBoot", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathLabguyHead", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
		
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("SuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
}
}


CLASS ChainMajorXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 40, 0, random(0, 360), 2, random(-15, 15));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath5", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Gib_HalfChaingunMajorNoArmNoHead", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSargeLeg2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("GibSargeBoot", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSergeantHeadOnXDeath", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
		
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("SuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
}
}


CLASS ZSpecOpsXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 40, 0, random(0, 360), 2, random(-15, 15));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 AA 0 a_spawnprojectile("XDeathHFQSZArm1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath5", 32, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathHFQSZLeg2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathZSpecOpsHead", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
		
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("SuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
}
}

CLASS SargeHelmetXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 NoDelay A_Jump(110, "Spawn2");
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 40, 0, random(0, 360), 2, random(-15, 15));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath5", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfShotgunguyNoArmNoHead", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSargeLeg2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("GibSargeBoot", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZHead", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
		
	Spawn2:
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 40, 0, random(0, 360), 2, random(-15, 15));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathNewSergeantArm1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathNewSergeantLeg1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZHead", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("GibSargeBoot", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathNewSergeantLowerTorso", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathNewSergeantUpperTorso", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
		
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("SuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
}
}



CLASS ChainXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 AA 0 a_spawnprojectile("XDeathChainArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathChaingunguyHeadOnXDeath", 42, 0, random(0, 360), 2, random(0, 160));
		
		//TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath5", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
		
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("SuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
}
}


CLASS RipZombieMan : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfZombieMan", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAA 0 a_spawnprojectile("Instestin2", 32, 0, random(0, 360), 2, random(0, 160));
	Death:
		TNT1 A 0;
		Stop;
}
}

CLASS RipHelmetZombieMan : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfHelmetZombieMan", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAA 0 a_spawnprojectile("Instestin2", 32, 0, random(0, 360), 2, random(0, 160));
	Death:
		TNT1 A 0;
		Stop;
}
}

CLASS RipHFQSZ : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfHFQSZ", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAA 0 a_spawnprojectile("Instestin2", 32, 0, random(0, 360), 2, random(0, 160));
	Death:
		TNT1 A 0;
		Stop;
}
}


CLASS FatalityZombieMan : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 a_spawnprojectile("Instestin2", 32, 0, random(0, 360), 2, random(0, 160));
		
	Death:
		TNT1 A 0;
		Stop;
}
}

CLASS RipSergeant : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("Instestin2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfSergeant", 32, 0, random(0, 360), 2, random(0, 160));
	Death:
		TNT1 A 0;
		Stop;
}
}

CLASS RipHelmetSergeant : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("Instestin2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfHelmetSergeant", 32, 0, random(0, 360), 2, random(0, 160));
	Death:
		TNT1 A 0;
		Stop;
}
}


CLASS RipZombieman2 : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("Instestin2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfZombieman2", 32, 0, random(0, 360), 2, random(0, 160));
	Death:
		TNT1 A 0;
		Stop;
}
}

CLASS RipChaingunGuy1 : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("Instestin2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfChaingunGuy1", 32, 0, random(0, 360), 2, random(0, 160));
	Death:
		TNT1 A 0;
		Stop;
}
}

CLASS RipChaingunGuy2 : RipChaingunGuy1 { 
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("Instestin2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfChaingunGuy2", 32, 0, random(0, 360), 2, random(0, 160));
	Death:
		TNT1 A 0;
		Stop;
}
}

CLASS RipHelmetChaingunGuy1 : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("Instestin2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfHelmetChaingunGuy1", 32, 0, random(0, 360), 2, random(0, 160));
	Death:
		TNT1 A 0;
		Stop;
}
}

CLASS RipHelmetChaingunGuy2 : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("Instestin2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfHelmetChaingunGuy2", 32, 0, random(0, 360), 2, random(0, 160));
	Death:
		TNT1 A 0;
		Stop;
}
}

CLASS RipHelmetZombieman2 : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("Instestin2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfHelmetZombieman2", 32, 0, random(0, 360), 2, random(0, 160));
	Death:
		TNT1 A 0;
		Stop;
}
}


CLASS BeheadZombieMan : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 1;
		TNT1 A 0 A_SpawnItemEx("XDeathZombieManHead", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0;
		Goto Death;
	Death:
		TNT1 A 0;
		Stop;
}
}





CLASS ZombiemanHeadExplode: ZombieXDeath { 
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("Brains2", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4Green", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4GreenBig", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPiece", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Teeth", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 90));
		TNT1 A 10;
		Stop;
}
}

CLASS PlasmaZombieHeadExplode: ZombieXDeath { 
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("Brains2", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4Blue", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4BlueBig", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPiece", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Teeth", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 90));
		TNT1 A 10;
		Stop;
}
}


CLASS LabguyHeadExplode: ZombieXDeath { 
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("Brains2", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4Orange", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4OrangeBig", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPiece", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Teeth", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 90));
		TNT1 A 10;
		Stop;
}
}



CLASS ShotgunguyHeadExplode: ZombieXDeath { 
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPiece", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Teeth", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 90));
		TNT1 A 10;
		Stop;
}
}

CLASS NaziHeadExplode: ZombieXDeath { 
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("Brains2", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4Blonde", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4Blonde", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPiece", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Teeth", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 90));
		TNT1 A 10;
		Stop;
}
}

CLASS ChaingunguyHeadExplode: ZombieXDeath { 
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("Brains2", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("BrainsImpHeadPiece", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPiece", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Teeth", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 90));
		TNT1 A 10;
		Stop;
}
}


CLASS HFQSZXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 40, 0, random(0, 360), 2, random(-5, 5));
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZArm1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath5", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZLeg2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZHead", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
	Death:
		TNT1 A 0;
		Stop;
}
}


//Sergeant Arm
CLASS XDeathNewSergeantArm1: XDeathArm1 { 
Default {
	Scale 1.0;
	Speed 10;
	Gravity 0.4;
	BounceFactor 0.4;
	+SKYEXPLODE;
	Species "Marines";
	+THRUSPECIES;
	BounceCount 5;
	Radius 10;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		4N09 ABCDEFGH 3 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
	Loop;

	Death.plasma: Death.Burn: Death.Flames:
		TNT1 A 0 a_spawnprojectile("XDeathBurnedArm", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;

	Death:
		4N09 I 1;
		4N09 I -1;
		HND8 A 0 A_SpawnItem("Gib_NewSergeantArm1",0,0,0,1);
	Stop;
}
}

CLASS Gib_NewSergeantArm1: LimbBase { 
	Default {
 
    Scale 1.2;
	}
    States
    {
    Spawn:
	4N09 I 1900 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
       Loop;
    Death.plasma: Death.Burn: Death.Flames:
		TNT1 A 0 a_spawnprojectile("XDeathBurnedArm", 32, 0, random(0, 360), 2, random(0, 160));
		Stop;
    Death:    
    TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
    TNT1 A 0 a_spawnprojectile("GibHand", 0, 0, random(0, 180), 2, random(0, 180));
    TNT1 A 0 a_spawnprojectile("GibArmPart", 0, 0, random(0, 180), 2, random(0, 180));
Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
	    4N09 II 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathNewSergeantArm1Kicked", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;
	Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	4N09 ABCD 3;
	Goto Spawn;
	
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	4N09 A 6;
	4N09 ABCDABCDABCD 6 A_CheckFloor("Landz");
	Goto Landz;
	Landz:
	4N09 I 0 A_SpawnItem("Gib_NewSergeantArm1");
	Stop;
}}

CLASS XDeathNewSergeantArm1Kicked: XDeathNewSergeantArm1 { 
	Default {
 
+ACTIVATEMCROSS
+ACTIVATEIMPACT
+CANUSEWALLS
	}
    States
    {
    Spawn:
	    TNT1 A 0 {self.bNOCLIP = true;}
	    4N09 A 2;
		TNT1 A 0 {self.bNOCLIP = false;}
		TNT1 A 0;
        TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		4N09 ABCD 6 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Goto Spawn+3;
	}
}

//Sergeant Upper Torso
CLASS XDeathNewSergeantUpperTorso : pb_blood_and_gore_base { 
	Default {
 
    Radius 8;
    Height 8;
    
	Speed 10;
	Gravity 0.7;
	Mass 4;
	Decal "BrutalBloodSplat";
bounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			4N06 ABCDEFGHI 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_NewSergeantUpperTorso",0,0,0,1);
			Stop;
	}
}

CLASS Gib_NewSergeantUpperTorso: BigGibBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			4N06 J 1;
			4N06 J -1;
Stop;    }}
	   
//Sergeant Lower Torso
CLASS XDeathNewSergeantLowerTorso : pb_blood_and_gore_base { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			4N05 ABCDEFGHI 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_NewSergeantLowerTorso",0,0,0,1);
			Stop;
	}
}

CLASS Gib_NewSergeantLowerTorso: BigGibBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			4N05 J 1;
			4N05 J -1;
Stop;    }}

//Sergeant Leg
CLASS XDeathNewSergeantLeg1: XDeathArm1 { 
	Default {
		
		Scale 1.35;
		Speed 10;
		Gravity 0.4;
		BounceFactor 0.4;
		+SKYEXPLODE;
		Species "Marines";
		+THRUSPECIES;
		BounceCount 5;
		Radius 10;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			4N07 ABCDEFGH 3 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
			Loop;
Death.plasma: Death.Burn: Death.Flames:
	    TNT1 A 0 a_spawnprojectile("XDeathBurnedArm", 32, 0, random(0, 360), 2, random(0, 160));
        Stop;
Death:
	4N07 I 1;
	4N07 I -1;
	HND8 A 0 A_SpawnItem("Gib_NewSergeantLeg1",0,0,0,1);
	Stop;
}
}

CLASS Gib_NewSergeantLeg1: LimbBase { 
	Default {
 
    Scale 1.35;
	}
    States
    {
    Spawn:
	4N07 I 1900 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
       Loop;
    Death.plasma: Death.Burn: Death.Flames:
	TNT1 A 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
    Death:    
    TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
    TNT1 A 0 a_spawnprojectile("GibHand", 0, 0, random(0, 180), 2, random(0, 180));
    TNT1 A 0 a_spawnprojectile("GibArmPart", 0, 0, random(0, 180), 2, random(0, 180));
Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
	    4N07 II 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathNewSergeantLeg1Kicked", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;
	Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	4N07 ABCD 3;
	Goto Spawn;
	
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	4N07 A 6;
	4N07 ABCDABCDABCD 6 A_CheckFloor("Landz");
	Goto Landz;
	Landz:
	4N07 I 0 A_SpawnItem("Gib_NewSergeantLeg1");
	Stop;
}}

CLASS XDeathNewSergeantLeg1Kicked: XDeathNewSergeantLeg1 { 
	Default {
 
+ACTIVATEMCROSS
+ACTIVATEIMPACT
+CANUSEWALLS
	}
    States
    {
    Spawn:
	    TNT1 A 0 {self.bNOCLIP = true;}
	    4N07 A 2;
		TNT1 A 0 {self.bNOCLIP = false;}
		TNT1 A 0;
        TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		4N07 ABCD 6 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Goto Spawn+3;
	}
}

