// --------------------------------------------------------------------------
// BFG9000 (Big Fucking Gun) PB
// --------------------------------------------------------------------------

CLASS BIG_FUCKING_GUN : weapon_slot_8_proto_class
{
Default
{	
	Height 20;
	SpawnID 31;
	Weapon.AmmoUse 40;
	Weapon.AmmoGive 40;
	Weapon.AmmoType "Cell";
	Inventory.PickupSound "BFGPICK";
	DamageType Desintegrate;
	+WEAPON.NOAUTOAIM;
	+WEAPON.BFG;
	+WEAPON.NOALERT;
	+FLOORCLIP;
	+DONTGIB;
	Tag "BFG9000";
	Inventory.PickupMessage "You got the BFG9000! FUCK YEAH! (Slot 7)";
}
States
{
	Steady:
		TNT1 A 1;
	Goto Ready;

	Spawn:
		BFUG A -1;
	Stop;
		
	Ready:
	Ready3:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("BFGRA1S");
		BFGG EDCB 1;
	Ready_loop:
		BFGG A 1
		{
			A_WeaponReady;
			A_WeaponOffset(CallACS("Script_GetGunOffsetX"), CallACS("Script_GetGunOffsetY"),WOF_KEEPY);
		}
	loop;
	
	WeaponSpecialPurist:
	WeaponSpecial:
		TNT1 A 0 A_Print("");
		TNT1 A 0 A_Takeinventory("GoWeaponSpecialAbility",1);
		Goto Ready+5;
		
	AltFirePurist:
		TNT1 A 0;
		//TNT1 A 0 A_Print("Secondary Fire Not Available in Classic Mode!")
		Goto Ready+5;
		
	Deselect:
		TNT1 A 0 A_JumpIfInventory("GotMeatShield", 1, "GrabEnemy");
		BFGG A 1 A_Lower;
		TNT1 AAAAAAAAAAAAAAAAAAA 0 A_Lower;
	wait;
		
	Select:
		TNT1 A 0 A_Overlay(-10, "FirstPersonLegsStand");
		TNT1 AA 1 A_Raise(60);
	wait;
		
		
	Fire:
		TNT1 A 0 A_WeaponOffset(0,32);
		TNT1 A 0 A_AlertMonsters;
		TNT1 A 0 A_PlaySound("BFGCHARGE");
		BFGC A 2 BRIGHT A_FireProjectile("GreenFlareSpawnEvenSmaller",0,0,0,0);
		BFGC B 2 BRIGHT A_FireProjectile("GreenFlareSpawnJustSmaller",0,0,0,0);
		BFGC C 2 BRIGHT A_FireProjectile("GreenFlareSpawnSmallClose",0,0,0,0);
		BFGC DEFEFEFEFEFEF 2 BRIGHT A_FireProjectile("GreenFlareSpawn",0,0,0,0);
		BFGF A 2 BRIGHT A_FireProjectile("GreenFlareSpawn",0,0,0,0);
		TNT1 A 0 A_Zoomfactor(0.85);
		TNT1 A 0 A_PlaySound("BFG_FIRE", 1);
		TNT1 AAA 0 A_FireProjectile("GreenFlareSpawn",0,0,0,0);
		TNT1 A 0 A_Recoil(8);
		TNT1 A 0 BRIGHT A_FireProjectile("Alerter", 0, 0, -1, 0);
		TNT1 A 0 BRIGHT A_FireProjectile("BFGBall");
		BFGF B 2 BRIGHT;
		TNT1 A 0 A_FireProjectile("ShakeYourAssDouble", 0, 0, 0, 0);
		BFGF CDEF 2 BRIGHT A_FireProjectile("GreenFlareSpawn",0,0,0,0);
		TNT1 A 0 A_Zoomfactor(1.0);
		BFGF GHGFE 1;
		BFGG A 1;
		TNT1 A 0 A_ReFire;
		Goto Ready+11;
		
	AltFire:
		TNT1 A 0 A_WeaponOffset(0,32);
		TNT1 A 0 A_JumpIfInventory("IsPlayingAsPurist", 1, "AltFirePurist");
		TNT1 A 0 A_JumpIfInventory("Cell", 5, 3);
		BFGG A 0 A_PlaySound("Seeker", 1);
		Goto Ready+5;
		BFGG A 1;
		TNT1 A 0 A_PlaySound("mbfgsh", 3, 1.0);
		BFGF B 1 BRIGHT A_PlaySound("BFGFIRE", CHAN_WEAPON, 1.2);
		TNT1 A 0 A_Takeinventory("Cell",5);
		TNT1 A 0 A_FireProjectile("GreenFlareSpawn",0,0,0,0);
		BFGF C 1 BRIGHT A_FireProjectile("BFGSmallSphere", 0, 1, 0, 0);
		TNT1 A 0 A_FireProjectile("GreenFlareSpawn",0,0,0,0);
		TNT1 A 0 A_Recoil(1);
		BFGF B 1 BRIGHT;
		TNT1 A 0 A_FireProjectile("ShakeYourAssDouble", 0, 0, 0, 0);
		TNT1 A 0 A_FireProjectile("GreenFlareSpawn",0,0,0,0);
		BFGC F 1 BRIGHT;
		BFGF F 1 Offset(0,34);
		BFGF F 1 Offset(0,42);
		BFGF F 2 Offset(0,32);
		TNT1 A 0 A_ReFire;
		Goto Ready+11;
		
	FlashKicking:
		BFGG A 1;
		BFGG B 1;
		BFGG B 1;
		BFGG C 3;
		BFGG D 3;
		BFGG C 3;
		BFGG B 1;
		BFGG B 1;
		BFGG A 1;
		BFGG AAA 1;
		Stop;
		
	FlashAirKicking:
		BFGG A 1;
		BFGG B 1;
		BFGG B 1;
		BFGG C 3;
		BFGG D 3;
		BFGG C 3;
		BFGG B 1;
		BFGG B 1;
		BFGG A 1;
		BFGG AAAA 1;
		Stop;
		
	FlashSlideKicking:
		BFGG AB 2;
		BFGG CCDDDEEDDCC 2 ;
		Stop;
		
	FlashSlideKickingStop:
		//TNT1 A 0
		BFGG CCBBA 1;
		BFGG A 1;
		Stop;
		
	FlashPunching:
		BFGG A 1;
		BFGG B 1;
		BFGG B 1;
		BFGG C 3;
		BFGG D 3;
		BFGG C 3;
		BFGG B 1;
		BFGG B 1;
		BFGG A 1;
		BFGG AAA 1;
		Stop;
	}
}

CLASS BFGDeathParticle : ACTOR { 
	Default {
	
	Height 0;
	Radius 0;
	Mass 0;
	+Missile;
	+NoBlockMap;
	-NoGravity;
	+LowGravity;
	+DontSplash;
	+DoomBounce;
	BounceFactor 0.5;
	RenderStyle "Add";
	Scale 0.04;
	}
	States
	{
	Spawn:
	Death:
		SPKG A 2 Bright A_FadeOut(0.02);
		Loop;
	}
}



CLASS BFGDeathParticleFast: BFGDeathParticle { 
	Default {
	
	Speed 10;
	Scale 0.1;
	}
	States
	{
	Spawn:
	Death:
		SPKG A 11 BRIGHT;
		SPKG AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 2 Bright A_FadeOut(0.06);
		Stop;
	}
}

CLASS BFGDeathParticleSuperFast: BFGDeathParticleFast { 
	Default {
	
	Speed 20;
	}
}


CLASS BFGLightningTrial : ACTOR { 
	Default {
	
	renderstyle "Add";
	Damage 0;
	Scale 0.80;
	+NOGRAVITY;
	+THRUACTORS;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Jump (256, "Spawn2", "Spawn3", "Spawn4", "Spawn5", "Spawn6", "Spawn7", "Spawn8", "Spawn9", "Spawn10");
		DLI1 ABCDEFGHIJK 1 bright;
		Stop;
	Spawn2:
		TNT1 A 0;
		DLI2 ABCDEFGHIJK 1 bright;
		Stop;
	Spawn2:
		TNT1 A 0;
		DLI3 ABCDEFGHIJK 1 bright;
		Stop;
	Spawn3:
		TNT1 A 0;
		DLI3 ABCDEFGHIJK 1 bright;
		Stop;
	Spawn4:
		TNT1 A 0;
		DLI4 ABCDEFGHIJK 1 bright;
		Stop;
	Spawn5:
		TNT1 A 0;
		DLI5 ABCDEFGHIJK 1 bright;
		Stop;
	Spawn6:
		TNT1 A 0;
		DLI2 LMNOPQRSTUV 1 bright;
		Stop;
	Spawn7:
		TNT1 A 0;
		DLI3 LMNOPQRSTUV 1 bright;
		Stop;
	Spawn8:
		TNT1 A 0;
		DLI3 LMNOPQRSTUV 1 bright;
		Stop;
	Spawn9:
		TNT1 A 0;
		DLI4 LMNOPQRSTUV 1 bright;
		Stop;
	Spawn10:
		TNT1 A 0;
		DLI5 LMNOPQRSTUV 1 bright;
		Stop;
	}
}

CLASS BFGLightningTrial_Small : BFGLightningTrial { 
	Default {
	
	Scale 0.17;
	Speed 4;
	}
}
CLASS BFGLightningTrial_Small_Faster : BFGLightningTrial { 
	Default {
	
	Scale 0.2;
	Speed 14;
	}
}


CLASS SuperBFGBall : BFGBall replaces BFGBall { 
	Default {
	
	+EXTREMEDEATH;
	//+DEHEXPLOSION
	Damage 500;
	Decal "BFGLightning";
	DeathSound "BFGEXPLO";
	DamageType "Desintegrate";
	Scale 0.65;
	Species "Marines";
	+THRUSPECIES;
	+MTHRUSPECIES;
	+DONTHARMCLASS;
	}
	States
	{
	DM:
		TNT1 A 0;
		TNT1 A 0 A_ChangeFLag("THRUSPECIES", 0);
		TNT1 A 0 A_ChangeFLag("MTHRUSPECIES", 0);
		Goto Spawn1;
		
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Playsound("Bfgfly1",6 ,1,1);
		TNT1 A 0 ACS_ExecuteAlways(719, 0, 0, 0, 0);//Check if Coop
	Spawn1:
		TNT1 A 0 A_SpawnItemEx("BFGFOG", 15, 0);
		BFS1 A 1 BRIGHT A_SpawnItem("GreenFlareMedium",0,0);
		TNT1 A 0 A_SpawnItemEx("BFGFOG", 15, 0);
		BFS1 B 1 BRIGHT A_SpawnItemEx("BFGTrailParticle", Random(-13, 13), Random(-13, 13), Random(0, 18), Random(1, 3), 0, (0.1)*Random(-10, 10), Random(-20, 20), 128);
		TNT1 A 0 A_SpawnItemEx("BFGLightningTrial", 15, random(-1,1), random(4,6));
		TNT1 A 0 A_SpawnItemEx("NewBFGTrailGreen", 15, random(8,-8), random(8,-8), 0, 0, 0, 0, 128, 0);
		TNT1 A 0 A_SpawnItemEx("BFGFOG", 15, 0);
		BFS1 C 1 BRIGHT A_SpawnItem("GreenFlareMedium",0,0);
		TNT1 A 0 A_SpawnItemEx("BFGFOG", 15, 0);
		BFS1 D 1 BRIGHT A_SpawnItemEx("BFGTrailParticle", Random(-13, 13), Random(-13, 13), Random(0, 18), Random(1, 3), 0, (0.1)*Random(-10, 10), Random(-20, 20), 128);
		TNT1 A 0 A_SpawnItemEx("BFGLightningTrial", 15, random(-1,1), random(4,6));
		TNT1 A 0 A_SpawnItemEx("NewBFGTrailGreen", 15, random(8,-8), random(8,-8), 0, 0, 0, 0, 128, 0);
		Loop;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 A_StopSound(6);
		TNT1 A 0 Bright A_SpawnItem("GreenShockWave",0,0,0);
		EXPL A 0 Radius_Quake (5, 16, 0, 20, 0);//(intensity, duration, damrad, tremrad, tid)
		EXPL AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("BFGBIGFOG", 0, 0, random (0, 360), 2, random (0, 360));
		EXPL AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("BFGDeathParticleFast", 0, 0, random (0, 360), 2, random (0, 360));
		EXPL AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("BFGDeathParticleSuperFast", 0, 0, random (0, 360), 2, random (0, 360));
		EXPL AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("BFGDeathParticleFast", 0, 0, random (0, 360), 2, random (0, 360));
		EXPL AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("BFGDeathParticleFast", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 0 A_SpawnItem("MegaGibRemoving");
		TNT1 A 0 A_Playsound("BFGAR", 3);
		TNT1 A 0 A_Explode(400,500,0,0,true);
		BFGB ABCDE 1 Bright A_SpawnItem("GreenFlare",0,0);
		BFE1 F 1 Bright A_BFGSpray("SuperBFGExtra", 40, 35);
		TNT1 A 0 A_SPawnItem("SuperBFGExtraGiant");
		BFE1 GGHHIIJJKK 1 Bright A_SpawnItem("GreenFlare",0,0);
		Stop;
	}
}

CLASS BFGTrailParticle : ACTOR { 
	Default {
	
	Height 0;
	Radius 0;
	Mass 0;
	Speed 3;
	+Missile;
	+NoBlockMap;
	+NoGravity;
	+DontSplash;
	RenderStyle "Add";
	Scale 0.05;
	}
	States
	{
	Spawn:
		SPKG A 2 Bright A_FadeOut(0.02);
		Loop;
	}
}

CLASS SuperBFGExtra : BFGExtra Replaces BFGExtra { 
	Default {
	
	+NoBlockMap;
	+NoGravity;
	RenderStyle "Add";
	+FORCERADIUSDMG;
	+THRUGHOST;
	Damage 0;
	Scale 0.5;
	Radius 1;
	Height 1;
	DamageType "Desintegrate";
	Species "Marines";
	+THRUSPECIES;
	+MTHRUSPECIES;
	+DONTHARMCLASS;
	}
	States
	{
	Spawn:
		BFE2 A 0;
		TNT1 A 0 A_Playsound("BFGEXTRA");
		TNT1 A 0 A_Explode(80, 3);
		TNT1 AAAAAA 0 A_SpawnItemEx("BFGExtraParticle", 0, 0, 14, (0.1)*Random(10, 40), 0, (0.1)*Random(-40, 40), Random(0, 360), 128);
		TNT1 AAAAAA 0 A_SpawnItemEx("BFGAltTrail", random(8,-8), random(8,-8), random(8,-8), 0, 0, 0, 0, 128, 0);
		TNT1 AAAAAA 0 A_SpawnItemEx("BFGExtraParticle", 0, 0, 14, (0.1)*Random(10, 40), 0, (0.1)*Random(-40, 40), Random(0, 360), 128);
		DB45 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 Bright A_SpawnItem("GreenFlareMedium",0,0);
		stop;
	}
}


CLASS SuperBFGExtraGiant : SuperBFGExtra { 
	Default {
	
	Scale 0.85;
	}
	States
	{
	Spawn:
		BFE2 A 0;
		TNT1 A 0 A_Playsound("BFGEXTRA");
		DB45 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 Bright A_SpawnItem("GreenFlareMedium",0,0);
		Stop;
}}

CLASS BFGExtraParticle : ACTOR { 
	Default {
	
	Height 0;
	Radius 0;
	Mass 0;
	+Missile;
	+NoBlockMap;
	+DontSplash;
	+NoInteraction;
	RenderStyle "Add";
	Scale 0.035;
	}
	States
	{
	Spawn:
	Death:
		SPKG A 2 Bright A_FadeOut(0.1);
		Loop;
	}
}

CLASS GreenShockWave  : ACTOR { 
	Default {
	
	Speed 0;
	Height 64;
	Radius 32;
	Scale 2.25;
	RenderStyle "Add";
	Alpha 0.9;
	+DROPOFF;
	+NOBLOCKMAP;
	+NOGRAVITY;
	}
	States 
	{ 
	Spawn: 
		SHOK A 1 BRIGHT;
		Goto Death;
	Death: 
		SHOK BCDEFGHIJJKKLLMMNNOPQR 1 BRIGHT A_FadeOut(0.03);
		Stop;
	} 
} 

CLASS BFGFOG : ACTOR { 
	Default {
	
	Radius 1;
	Height 1;
	Alpha 0.2;
	RenderStyle "Add";
	Scale 0.75;
	Speed 8;
	Gravity 0;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+DONTSPLASH;
	+MISSILE;
	+FORCEXYBILLBOARD;
	+CLIENTSIDEONLY;
	}
	States
	{
	Spawn:
		DB48 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 BRIGHT;
		{
			A_SpawnItem("GreenFlareMedium",0,0);
			A_SetScale(Scalex-0.04, Scaley-0.05);
			A_Fadeout(.02);
	}
	Goto Death;
	Death:
		DB48 ABCDEFGHIJKLM 1 BRIGHT A_Fadeout(.1);
		Stop;
	}
}

CLASS BFGBIGFOG: BFGFOG { 
	Default {
	
	Scale 0.8;
	}
}

CLASS SmallGreenFog: BFGFOG { 
	Default {
	
	Speed 3;
	Scale 1.0;
	}
}

CLASS BFGDeathParticleSpawner : ACTOR { 
	Default {
	
	+NoClip;
	+NoBlockMap;
	+NoGravity;
	+Missile;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 AAAAA 0 A_SpawnItemEx("BFGDeathParticle", 0, 0, 0, (0.1)*Random(20, 45), 0, (0.1)*Random(-40, 40), Random(0, 360), 128);
		TNT1 AAAAA 0 A_SpawnItemEx("BFGDeathParticle", 0, 0, 0, (0.1)*Random(20, 45), 0, (0.1)*Random(-40, 40), Random(0, 360), 128);
		TNT1 AAAAA 0 A_SpawnItemEx("BFGDeathParticle", 0, 0, 0, (0.1)*Random(20, 45), 0, (0.1)*Random(-40, 40), Random(0, 360), 128);
		TNT1 AAAAA 0 A_SpawnItemEx("BFGDeathParticle", 0, 0, 0, (0.1)*Random(20, 45), 0, (0.1)*Random(-40, 40), Random(0, 360), 128);
		TNT1 A 1;
		Stop;
	}
}

CLASS BFGSuperParticleSpawner : ACTOR { 
	Default {
	
	+NoClip;
	+NoBlockMap;
	+NoGravity;
	+Missile;
	+FORCEXYBILLBOARD;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("BFGSuperParticle", 0, 0, 0, (0.1)*Random(10, 35), 0, (0.1)*Random(-20, 20), Random(0, 360), 128);
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("BFGSuperParticle", 0, 0, 0, (0.1)*Random(10, 35), 0, (0.1)*Random(-20, 20), Random(0, 360), 128);
		TNT1 AAAAAAAAAAAAAAA 0 A_SpawnItemEx("BFGSuperParticle", 0, 0, 0, (0.1)*Random(10, 35), 0, (0.1)*Random(-20, 20), Random(0, 360), 128);
		TNT1 A 1;
		Stop;
	}
}


CLASS BFGSuperParticle : ACTOR { 
	Default {
	
	Height 0;
	Radius 0;
	Mass 0;
	+Missile;
	+NoBlockMap;
	+NOGRAVITY;
	+DontSplash;
	+FORCEXYBILLBOARD;
	RenderStyle "Add";
	Scale 0.04;
	Speed 24;
	}
	States
	{
	Spawn:
	Death:
		SPKG A 2 Bright A_FadeOut(0.02);
		Loop;
	}
}

CLASS BFGSmallSphere : BaronBall { 
	Default {
	
	Radius 10;
	Height 8;
	Speed 45;
	FastSpeed 50;
	DamageType GreenFire;
	Projectile;
	//+RANDOMIZE
	+FORCEXYBILLBOARD;
	-THRUGHOST;
	Damage 30;
	RenderStyle "Add";
	Alpha 1;
	Scale 0.45;
	DeathSound "BFGALPP";
	SeeSound "None";
	Decal "Scorch";
	Species "Marines";
	+THRUSPECIES;
	+MTHRUSPECIES;
	+DONTHARMCLASS;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Playsound("BGFLMBL", 6, 1, 1);
	Fly:
		DB57 AB 1 BRIGHT A_SpawnItem("GreenFlareSmall",0,0);
		TNT1 A 0 A_SpawnItemEx("BFGLightningTrial_Small", 20, 0, 0, 0, 0, 0, 0, 128);
		TNT1 A 0 A_SpawnItemEx("SmallGreenFlameTrails", 0, 0, 0, 0, 0, 0, 0, 128);
		TNT1 A 0 A_SpawnItemEx("BFGAltTrail", Random(-13, 13), Random(-13, 13), Random(0, 18), Random(1, 3), 0, (0.1)*Random(-10, 10), Random(-20, 20), 128);
		DB57 C 1 BRIGHT A_SpawnItem("GreenFlareSmall",0,0);
		Loop;
	Death:
		TNT1 A 0 A_StopSound(6);
		TNT1 AAA 0 A_SpawnItemEx("PlasmaParticleSpawner", 0, 0, 0, 6, 6, 6, 0, 128);
		TNT1 A 0 A_SpawnItemEx ("BFGAltExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItem("BFGAltShockWave",0,0);
		EXPG ABCDEFG 2 BRIGHT A_SpawnItem("GreenFlare",0,0);
		TNT1 AAAAA 19 A_CustomMissile("PlasmaSmoke", 1, 0, random (0, 360), 2, random (0, 160));
		Stop;
	XDeath:
		TNT1 A 0 A_StopSound(6);
		TNT1 AAA 0 A_SpawnItemEx("PlasmaParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
		TNT1 A 0 A_SpawnItemEx ("BFGAltExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItem("BFGAltShockWave",0,0);
		TNT1 A 0 A_SpawnItemEx ("DetectFloorCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("DetectCeilCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		EXPG ABCDEFG 2 A_SpawnItem("GreenFlare",0,0);
		Stop;
	Crash:
		TNT1 A 0 A_StopSound(6);
		TNT1 AAA 0 A_SpawnItemEx("PlasmaParticleSpawner", 0, 0, 0, 6, 6, 6, 0, 128);
		TNT1 A 0 A_SpawnItemEx ("BFGAltExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItem("BFGAltShockWave",0,0);
		TNT1 A 0 A_SpawnItemEx ("DetectFloorCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("DetectCeilCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		FRPG ABCDEFGH 2 BRIGHT A_SpawnItem("GreenFlare",0,0);
		TNT1 AAAAA 19 A_CustomMissile ("PlasmaSmoke", 1, 0, random (0, 360), 2, random (0, 160));
		Stop;
	}
}

CLASS BFGAltShockWave : GreenShockWave { 
	Default {
	
	Height 1;
	Radius 1;
	+FORCEXYBILLBOARD;
	Scale 1.0;
	Species "Marines";
	+THRUSPECIES;
	+MTHRUSPECIES;
	+DONTHARMCLASS;
	Damagetype "Desintegrate";
	}
	States
	{ 
	Spawn: 
		SHOK A 1 BRIGHT;
		Goto Death;
	Death: 
		SHOK CEGIKMOQS 1 BRIGHT A_FadeOut(0.11);
		Stop;
	} 
}

CLASS BFGAltTrail : BFGTrailParticle { 
	Default {
	
	Height 0;
	Radius 0;
	Mass 0;
	Speed 3;
	+MISSILE;
	+NOBLOCKMAP;
	+NOGRAVITY;
	+DONTSPLASH;
	RenderStyle "Add";
	Scale 0.025;
	}
	States
	{
	Spawn:
		SPKG A 1 BRIGHT A_FadeOut(0.04);
		Loop;
	}
}

CLASS BFGAltExplosion : ACTOR { 
	Default {
	
	+NOBLOCKMAP;
	+MISSILE;
	Species "Marines";
	+THRUSPECIES;
	+MTHRUSPECIES;
	+DONTHARMCLASS;
	Damagetype ExplosiveImpact;
	}
	States    
	{
	Spawn:
		TNT1 A 1;
		TNT1 A 0 A_Explode(76,115);
		Stop;
	}
}

CLASS GreenExplosionFire : ACTOR { 
	Default {
	
	Radius 1;
	Height 1;
	Speed 3;
	Damage 0;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+DONTSPLASH;
	+MISSILE;
	+FORCEXYBILLBOARD;
	+CLIENTSIDEONLY;
	+NOINTERACTION;
	+NOCLIP;
	RenderStyle "Add";
	DamageType Flames;
	SeeSound "9KEXPL";
	Scale 2.0;
	Alpha 1;
	Gravity 0;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		EXPG ABCDEFG 3 BRIGHT;
		Stop;
	}
}

CLASS WhiteShockWave: GreenShockwave { 
	Default {
	
	Scale 2.0;
	Alpha 0.12;
	}
	States 
	{ 
	Spawn: 
		SHWK A 1;
		SHWK CEGIKMOQ 1 A_FadeOut(0.01);
		Stop;
	} 
} 

CLASS WhiteShockWaveBig: WhiteShockWave { 
	Default {
	
	Scale 3.0;
	}
} 

CLASS WhiteShockWaveSmall: WhiteShockWave { 
	Default {
	
	Scale 1.0;
	}
} 
