// --------------------------------------------------------------------------
// BFG9000 Mark IV (see what I did there)
// --------------------------------------------------------------------------

CLASS little_pleasant_toy : weapon_slot_8_proto_class
{
enum bfg_fire_mode
{
	bfg = 0,
	laser = 1,
	guard = 2
};

bfg_fire_mode actual_bfg_fire_mode;
 
Default
{
	Weapon.SlotNumber 8;
	Weapon.SelectionOrder 5;
	Weapon.slotpriority 0.1;

	Height 20;
	Weapon.AmmoUse 0;
	Weapon.AmmoGive 50;
	Weapon.AmmoType "Cell";
	Inventory.PickupSound "BFGPICK";
	DamageType "Desintegrate";
	+WEAPON.NOAUTOAIM;
	+FLOORCLIP;
	+DONTGIB;
	Tag "Wanna be bfg";
	Inventory.PickupMessage "You got the BFG 9000 Mark IV! (Slot 8)";
}

override bool, bool weapon_dual_and_special()
{return false, true; }

override void activate_special()
{
	owner.player.SetPSprite(PSP_WEAPON, self.FindState("change_bfg_mode") );
}


States
{
	Spawn:
		RDAB X -1;
	Stop;

	Select:
		TNT1 A 0 A_Overlay(-10, "FirstPersonLegsStand");
		TNT1 A 0 A_Gunflash("FlashOff");
		TNT1 AA 1 A_Raise(90);
	wait;

	Steady:
		TNT1 A 1;
	Goto Ready;
		
	Ready:
		4DCX ABCD 1;
		TNT1 A 0 A_PlaySound("BFGRA1S");
	ready_loop:
		TNT1 A 0 A_PlaySound("BFGHUM", 6,1,1);
		TNT1 A 0
		{
			switch(invoker.actual_bfg_fire_mode)
			{
				case bfg : self.player.SetPsprite(PSP_FLASH, invoker.findstate("FlashReadyGreen") ); break; 
				case guard : self.player.SetPsprite(PSP_FLASH, invoker.findstate("FlashReadyOrange") ); break; 
				case laser : self.player.SetPsprite(PSP_FLASH, invoker.findstate("FlashReadyRed") ); break; 
				default: console.printf("BFG overlay fuckup, tell user_name"); break;
			}
		}
		4DBX ZZZZ 1
		{
			switch(invoker.actual_bfg_fire_mode)
			{
				case bfg : self.Player.GetPSprite(PSP_WEAPON).sprite = getspriteindex("4dbx"); break; 
				case laser : self.Player.GetPSprite(PSP_WEAPON).sprite = getspriteindex("5D5X"); break; 
				case guard : self.Player.GetPSprite(PSP_WEAPON).sprite = getspriteindex("6DBX"); break; 
				default: console.printf("BFG sprite fuckup, tell user_name"); break;
			}
			a_weaponready();
		}
	Loop;

	change_bfg_mode:
		tnt1 a 0
		{
			A_StopSound(6);
			A_GunFlash("FlashNothing");
			switch(invoker.actual_bfg_fire_mode)
			{
				case bfg : A_Print("Weapon Mode: Contact Laser"); break;
				case laser : A_Print("Weapon Mode: Guard");break;
				case guard : A_Print("Weapon Mode: BFG");break;
			}
		}
		4DCX DCB 1;
		TNT1 A 0 A_PlaySound("BFGRA1S");
		4DCX BCD 1;
		tnt1 a 0
		{
			switch(invoker.actual_bfg_fire_mode)
			{
				case bfg : invoker.actual_bfg_fire_mode = laser; break;
				case laser : invoker.actual_bfg_fire_mode = guard; break; 
				case guard : invoker.actual_bfg_fire_mode = bfg; break; 
				default: console.printf("BFG mode change fuckup, tell user_name"); break;
			}
		}
	Goto ready_loop;

	Fire:
		TNT1 A 0 A_WeaponOffset(0,32);
		TNT1 A 0
		{
			switch(invoker.actual_bfg_fire_mode)
			{
				case bfg : self.player.SetPsprite(PSP_WEAPON, invoker.resolvestate("Fire_BFG") ); break; 
				case guard : self.player.SetPsprite(PSP_WEAPON, invoker.resolvestate("fire_guard") ); break;
				case laser : self.player.SetPsprite(PSP_WEAPON, invoker.resolvestate("fire_laser") ); break;
				default: console.printf("BFG fire fuckup, tell user_name"); break;
			}
		}
	Fire_BFG:
		TNT1 A 0 A_StopSound(6);
		TNT1 A 0 A_JumpIfInventory("Cell",40,2);
		BFGG A 0 A_PlaySound("Seeker", 1);
	Goto ready_loop;
		TNT1 A 0 A_GunFlash("FlashFireGreen");
		TNT1 A 0 A_PlaySound("BFGCHARGE", 7);
		TNT1 A 0 A_SetBlend("Green",0.10,5);
		4DAX K 1 BRIGHT Offset(-2,34) a_fireprojectile("Green_FlareSpawnEvenSmaller",0,0,0,0);//2
		4DAX L 1 BRIGHT Offset(0, 32);// ; //a_fireprojectile("BFGLightningTrial_Small_Faster",0,0);//; //a_fireprojectile("BFGLightningTrial_Small_Faster",0,0)
		4DAX L 1 BRIGHT Offset(2, 34);// ; //a_fireprojectile("BFGLightningTrial_Small_Faster",0,0);
		TNT1 A 0 A_QuakeEx(2, 2, 2, 6, 0, 64, "", 0);
		TNT1 A 0 A_ZoomFactor(.950);
		4DAX M 1 BRIGHT Offset(1, 33) a_fireprojectile("Green_FlareSpawnSmallClose",0,0,0,0);//2
		4DAX N 1 BRIGHT Offset(-2,34);// ; //a_fireprojectile("BFGLightningTrial_Small_Faster",0,0);//2
		TNT1 A 0 A_QuakeEx(2, 2, 2, 6, 0, 64, "", 0);
		TNT1 A 0 A_ZoomFactor(.925);
		TNT1 A 0 A_SetBlend("Green",0.15,6);
		4DAX M 1 BRIGHT Offset(0, 32) a_fireprojectile("Green_FlareSpawn",0,0,0,0);//13
		4DAX N 1 BRIGHT Offset(2, 34);// ; //a_fireprojectile("BFGLightningTrial_Small_Faster",0,0);//13
		4DAX O 1 BRIGHT Offset(1, 33) a_fireprojectile("Green_FlareSpawn",0,0,0,0);//13
		4DAX P 1 BRIGHT Offset(-2,34);// ; //a_fireprojectile("BFGLightningTrial_Small_Faster",0,0);//13
		4DAX O 1 BRIGHT;// ; //a_fireprojectile("BFGLightningTrial_Small_Faster",0,0);//13
		4DAX P 1 BRIGHT;// ; //a_fireprojectile("BFGLightningTrial_Small_Faster",0,0);//13
		TNT1 A 0 A_QuakeEx(2, 2, 2, 6, 0, 64, "", 0);
		TNT1 A 0 A_PlaySound("BFGCHAFF", 8);
		TNT1 A 0 A_SetBlend("Green",0.20,8);
		4DAX Q 1 BRIGHT Offset(0, 32) a_fireprojectile("Green_FlareSpawn",0,0,0,0);//13
		4DAX R 1 BRIGHT Offset(2, 34);// ; //a_fireprojectile("BFGLightningTrial_Small_Faster",0,0);//13
		4DAX Q 1 BRIGHT Offset(1, 33) a_fireprojectile("Green_FlareSpawn",0,0,0,0);//13
		4DAX R 1 BRIGHT Offset(-2,34);// ; //a_fireprojectile("BFGLightningTrial_Small_Faster",0,0);//13
		4DAX S 1 BRIGHT Offset(0, 32) a_fireprojectile("Green_FlareSpawn",0,0,0,0);//13
		4DAX T 1 BRIGHT Offset(2, 34);// ; //a_fireprojectile("BFGLightningTrial_Small_Faster",0,0);//13
		4DAX S 1 BRIGHT Offset(1, 33) a_fireprojectile("Green_FlareSpawn",0,0,0,0);//13
		4DAX T 1 BRIGHT Offset(-2,34) ; //a_fireprojectile("BFGLightningTrial_Small_Faster",0,0);//13
		TNT1 A 0 A_QuakeEx(2, 2, 2, 6, 0, 64, "", 0);
		TNT1 A 0 A_SetBlend("Green",0.25,5);
		4DAX U 1 BRIGHT Offset(0, 32) a_fireprojectile("Green_FlareSpawn",0,0,0,0);//13
		4DAX T 1 BRIGHT Offset(2, 34) ; //a_fireprojectile("BFGLightningTrial_Small_Faster",0,0);//13
		4DAX S 1 BRIGHT Offset(1, 33) a_fireprojectile("Green_FlareSpawn",0,0,0,0);//13
		4DAX T 1 BRIGHT Offset(-2,34) ; //a_fireprojectile("BFGLightningTrial_Small_Faster",0,0);//13
		4DAX U 1 BRIGHT Offset(0, 32) ; //a_fireprojectile("BFGLightningTrial_Small_Faster",0,0);//13
		TNT1 A 0 A_QuakeEx(2, 2, 2, 6, 0, 64, "", 0);
		TNT1 A 0 A_SetBlend("Green",0.27,4);
		TNT1 A 0 a_fireprojectile("Green_FlareSpawn",0,0,0,0);
		4DAX S 1 BRIGHT Offset(0,36);//
		4DAX T 1 BRIGHT Offset(0,37);//
		4DAX U 1 BRIGHT Offset(0,38);
		4DAX T 1 BRIGHT Offset(0,39);
		TNT1 A 0 A_ZoomFactor(.9);
		TNT1 A 0 A_PlaySound("BFG_FIRE", 1);
		TNT1 A 0 a_fireprojectile("Green_FlareSpawn",0,0,0,0);
		TNT1 AAA 0 ; //a_fireprojectile("BFGLightningTrial_Small_Faster",0,0,0,0);
		TNT1 A 0 A_Recoil(6);
		TNT1 A 0 BRIGHT a_fireprojectile("Alerter", 0, 0, -1, 0);
		TNT1 A 0 BRIGHT a_fireprojectile("BFGBall");
		TNT1 A 0 A_Takeinventory("Cell",40);
		TNT1 A 0 A_SetBlend("Green",0.30,5);
		4DAX V 1  BRIGHT;//Offset(1,38)
		4DAX W 1  BRIGHT;//Offset(1,37)
		4DAX X 1  BRIGHT;//Offset(1,36)
		
			TNT1 A 0 A_QuakeEx(4, 4, 4, 6, 0, 64, "", 0);
		TNT1 A 0 A_ZoomFactor(.925);
		4DAX Y 1 a_fireprojectile("Green_FlareSpawn",0,0,0,0);
		TNT1 A 0 A_ZoomFactor(.95);
		4DAX Z 1 Offset(0,34) a_fireprojectile("Green_FlareSpawn",0,0,0,0);
		TNT1 A 0 A_ZoomFactor(.975);
		4DBX Z 2 Offset(0,33)a_fireprojectile("Green_FlareSpawn",0,0,0,0);
		TNT1 A 0 A_ZoomFactor(1.0);
		4DBX Z 2 Offset(0,32)a_fireprojectile("Green_FlareSpawn",0,0,0,0);
		
		4DBX Z 2;
		TNT1 A 0 A_ReFire("fire_bfg");
	Goto ready_loop;
		
	Fire_Guard:
		TNT1 A 0 A_StopSound(6);
		TNT1 A 0 A_JUMPIFINVENTORY("CELL",1, 2);
		BFGG A 0 A_PlaySound("Seeker", 1);
	Goto ready_loop;
		TNT1 A 0 A_PlaySound("SHLDSTT",2);
	FireGuardHold:
		TNT1 A 0 A_PlaySound("SHLDLP", 3,1,1);
		TNT1 A 0 A_GunFlash("FlashFireOrange");
		
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner", 0, 68, 0, 0, 0, 0, -270, 32);
		6DBX E 1 BRIGHT Offset(-2,34) A_SpawnItemEx ("Shield_Spawner", 0,68, 0, 0, 0, 0, -270, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner", 0, 68, 0, 0, 0, 0, -270, 32);
		6DBX F 1 BRIGHT Offset(0, 32) A_SpawnItemEx ("Shield_Spawner", 0, 68, 0, 0, 0, 0, -270, 32);
		//TNT1 A 0 A_SpawnItemEx ("Shield_Spawner", 0, 68, 0, 0, 0, 0, -270, 32);
		//TNT1 A 0 a_fireprojectile("HellionTrailSpark_Fast", random(-30,30), 0, random(-3,3), 0);
		6DBX G 1 BRIGHT Offset(2, 34) A_SpawnItemEx ("Shield_Spawner", 0, 68, 0, 0, 0, 0, -270, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner", 0, 68, 0, 0, 0, 0, -270, 32);
		6DBX H 1 BRIGHT Offset(1, 33) A_SpawnItemEx ("Shield_Spawner", 0, 68, 0, 0, 0, 0, -270, 32);
		//TNT1 A 0 A_SpawnItemEx ("Shield_Spawner", 0, 68, 0, 0, 0, 0, -270, 32);
		//TNT1 A 0 a_fireprojectile("HellionTrailSpark_Fast", random(-30,30), 0, random(-3,3), 0);
		TNT1 A 0 A_Takeinventory("Cell",2);
		TNT1 A 0 A_ReFire("FireGuardHold");
		TNT1 A 0 A_StopSound(3);
	Goto ready_loop;

	// too lazy to revrite lazer primary section now IT JUST WORK
	Fire_Laser:
		TNT1 A 0 A_StopSound(6);
		TNT1 A 0 A_JumpIfInventory("Cell", 5, 2);
		BFGG A 0 A_PlaySound("Seeker", 1);
	Goto ready_loop;
		TNT1 A 0 A_GunFlash("FlashFireRed");
		5D5X A 1 BRIGHT Offset(-2,34);
		5D5X B 1 BRIGHT Offset(0, 32);
		5D5X C 1 BRIGHT Offset(2, 34);
		5D5X D 1 BRIGHT Offset(1, 33);
		5D5X E 1 BRIGHT Offset(0, 34);
		TNT1 A 0 A_ReFire("Charge1A");
		TNT1 A 0 a_fireprojectile("bfg_4_laser_projectile",0,0,0,-1,0,0);
		TNT1 A 0 A_Takeinventory("Cell",5);
		TNT1 A 0 a_fireprojectile("Red_FlareSpawn",0,0,0,0);
		TNT1 AAAAAA 0;
		TNT1 A 0 A_SetBlend("Red",0.25,15);
		TNT1 A 0 A_StopSound(5);
		TNT1 A 0;//A_GunFlash
		TNT1 A 0 A_AlertMonsters;
		TNT1 A 0 A_PlaySound("Weapons/StachanovFire",1);
		TNT1 A 0 A_PlaySound("Weapons/StachanovAddFire",0);
		5D5X K 1 BRIGHT A_ZoomFactor(0.95);
		5D5X L 1 BRIGHT A_ZoomFactor(0.96);
		5D5X M 1 BRIGHT A_ZoomFactor(0.97);
		5D5X N 1 BRIGHT A_ZoomFactor(0.98);
		5D5X O 1 BRIGHT A_ZoomFactor(0.99);
		5D5X P 1 ;//Offset(4, 44) A_ZoomFactor(0.95)
		5D5X Q 1 ;//Offset(3, 42) A_ZoomFactor(0.96)
		
		TNT1 A 0 A_GunFlash("FlashReadyRed");
		5D5X Z 4 A_ZoomFactor(1);
		TNT1 A 0 A_GunFlash("FlashReadyRed");
		5D5X Z 4;
	goto ready_loop;
		
	Charge1A: //Stage 1, aka "looks like he's gonna rack up some more power."
		TNT1 A 0 A_JumpIfInventory("Cell", 15, 2);
		BFGG A 0 A_PlaySound("Seeker", 1);
	Goto Fire_Laser+10;
		BFGG A 0 A_PlaySound("CNTCTBM", 6);
		OBLG A 0 A_PlaySound("Weapons/StachanovCharge",5,1.0,1);
		TNT1 A 0 A_PlaySound("BEPBEP", 9);
		OBLG D 0 A_Quake (1, 9, 0, 3);
		TNT1 A 0 A_GunFlash("FlashFireRedCharge1");
		5D5X B 1 BRIGHT Offset(-2, 34) A_SetBlend("Red",0.1,6);
		5D5X C 1 BRIGHT Offset(0, 32) A_SetBlend("Red",0.1,6);
		5D5X D 1 BRIGHT Offset(2, 34) A_SetBlend("Red",0.1,6);
		5D5X E 1 BRIGHT Offset(1, 33) A_SetBlend("Red",0.1,6);
		5D5X F 1 BRIGHT Offset(0, 34) A_SetBlend("Red",0.1,6);
		TNT1 A 0 A_ReFire("Charge1B");
	Goto Fire_Laser+3;
	Charge1B:
		OBLG D 0 A_Quake (1, 9, 0, 3);
		TNT1 A 0 A_GunFlash("FlashFireRedCharge1");
		5D5X G 1 BRIGHT Offset(-2, 34) A_SetBlend("Red",0.1,6);
		5D5X H 1 BRIGHT Offset(0, 32) A_SetBlend("Red",0.1,6);
		5D5X I 1 BRIGHT Offset(2, 34) A_SetBlend("Red",0.1,6);
		5D5X J 1 BRIGHT Offset(1, 33) A_SetBlend("Red",0.1,6);
		5D5X A 1 BRIGHT Offset(0, 34) A_SetBlend("Red",0.1,6);
		TNT1 A 0 A_ReFire("Charge1C");
	Goto Charged_Fire1;
	Charge1C:
		OBLG D 0 A_Quake (1, 9, 0, 3);
		TNT1 A 0 A_GunFlash("FlashFireRedCharge1");
		5D5X B 1 BRIGHT Offset(-2, 34) A_SetBlend("Red",0.1,6);
		5D5X C 1 BRIGHT Offset(0, 32) A_SetBlend("Red",0.1,6);
		5D5X D 1 BRIGHT Offset(2, 34) A_SetBlend("Red",0.1,6);
		5D5X E 1 BRIGHT Offset(1, 33) A_SetBlend("Red",0.1,6);
		5D5X F 1 BRIGHT Offset(0, 34) A_SetBlend("Red",0.1,6);
		TNT1 A 0 A_ReFire("Charge2A");
	Goto Charged_Fire1;
		
	Charge2A: //Stage 2, aka "Should we stay in his line of fire? I don't think so."FlashFireRedCharge2
		TNT1 A 0 A_JumpIfInventory("Cell", 25, 2);
		BFGG A 0 A_PlaySound("Seeker", 1);
	Goto Charged_Fire1;
		OBLG D 0 A_Quake (2, 6, 0, 3);
		TNT1 A 0 A_GunFlash("FlashFireRedCharge2");
		TNT1 A 0 A_PlaySound("BEPBEP", 8);
		5D5X G 1 BRIGHT Offset(-2, 34) A_SetBlend("Red",0.15,6);
		5D5X H 1 BRIGHT Offset(0, 32) A_SetBlend("Red",0.15,6);
		5D5X I 1 BRIGHT Offset(2, 34) A_SetBlend("Red",0.15,6);
		5D5X J 1 BRIGHT Offset(1, 33) A_SetBlend("Red",0.15,6);
		5D5X A 1 BRIGHT Offset(0, 34) A_SetBlend("Red",0.15,6);
		5D5X B 1 BRIGHT Offset(-2, 34) A_SetBlend("Red",0.15,6);
		5D5X C 1 BRIGHT Offset(0, 32) A_SetBlend("Red",0.15,6);
		5D5X D 1 BRIGHT Offset(2, 34) A_SetBlend("Red",0.15,6);
		5D5X E 1 BRIGHT Offset(1, 33) A_SetBlend("Red",0.15,6);
		5D5X F 1 BRIGHT Offset(0, 34) A_SetBlend("Red",0.15,6);
		TNT1 A 0 A_ReFire("Charge2B");
	Goto Charged_Fire2;
	Charge2B:
		OBLG D 0 A_Quake (2, 6, 0, 3);
		TNT1 A 0 A_GunFlash("FlashFireRedCharge2");
		5D5X G 1 BRIGHT Offset(-2, 34) A_SetBlend("Red",0.15,6);
		5D5X H 1 BRIGHT Offset(0, 32) A_SetBlend("Red",0.15,6);
		5D5X I 1 BRIGHT Offset(2, 34) A_SetBlend("Red",0.15,6);
		5D5X J 1 BRIGHT Offset(1, 33) A_SetBlend("Red",0.15,6);
		5D5X A 1 BRIGHT Offset(0, 34) A_SetBlend("Red",0.15,6);
		5D5X B 1 BRIGHT Offset(-2, 34) A_SetBlend("Red",0.15,6);
		5D5X C 1 BRIGHT Offset(0, 32) A_SetBlend("Red",0.15,6);
		5D5X D 1 BRIGHT Offset(2, 34) A_SetBlend("Red",0.15,6);
		5D5X E 1 BRIGHT Offset(1, 33) A_SetBlend("Red",0.15,6);
		5D5X F 1 BRIGHT Offset(0, 34) A_SetBlend("Red",0.15,6);
		TNT1 A 0 A_ReFire("Charge2C");
	Goto Charged_Fire2;
	Charge2C:
		OBLG D 0 A_Quake (1, 6, 0, 3);
		TNT1 A 0 A_GunFlash("FlashFireRedCharge2");
		5D5X G 1 BRIGHT Offset(-2, 34) A_SetBlend("Red",0.15,6);
		5D5X H 1 BRIGHT Offset(0, 32) A_SetBlend("Red",0.15,6);
		5D5X I 1 BRIGHT Offset(2, 34) A_SetBlend("Red",0.15,6);
		5D5X J 1 BRIGHT Offset(1, 33) A_SetBlend("Red",0.15,6);
		5D5X A 1 BRIGHT Offset(0, 34) A_SetBlend("Red",0.15,6);
		5D5X B 1 BRIGHT Offset(-2, 34) A_SetBlend("Red",0.15,6);
		5D5X C 1 BRIGHT Offset(0, 32) A_SetBlend("Red",0.15,6);
		5D5X D 1 BRIGHT Offset(2, 34) A_SetBlend("Red",0.15,6);
		5D5X E 1 BRIGHT Offset(1, 33) A_SetBlend("Red",0.15,6);
		5D5X F 1 BRIGHT Offset(0, 34) A_SetBlend("Red",0.15,6);
		TNT1 A 0 A_ReFire("Charge2D");
	Goto Charged_Fire2;
	Charge2D:
		OBLG D 0 A_Quake (1, 6, 0, 3);
		TNT1 A 0 A_GunFlash("FlashFireRedCharge2");
		5D5X G 1 BRIGHT Offset(-2, 34) A_SetBlend("Red",0.15,6);
		5D5X H 1 BRIGHT Offset(0, 32) A_SetBlend("Red",0.15,6);
		5D5X I 1 BRIGHT Offset(2, 34) A_SetBlend("Red",0.15,6);
		5D5X J 1 BRIGHT Offset(1, 33) A_SetBlend("Red",0.15,6);
		5D5X A 1 BRIGHT Offset(0, 34) A_SetBlend("Red",0.15,6);
		5D5X B 1 BRIGHT Offset(-2, 34) A_SetBlend("Red",0.15,6);
		5D5X C 1 BRIGHT Offset(0, 32) A_SetBlend("Red",0.15,6);
		5D5X D 1 BRIGHT Offset(2, 34) A_SetBlend("Red",0.15,6);
		5D5X E 1 BRIGHT Offset(1, 33) A_SetBlend("Red",0.15,6);
		5D5X F 1 BRIGHT Offset(0, 34) A_SetBlend("Red",0.15,6);
		TNT1 A 0 A_ReFire("Charge3A");
	Goto Charged_Fire2;
		
	Charge3A://Stage 3, aka "HOLYSHITHESGONNABLOWMYASSOFF!!"
		TNT1 A 0 A_JumpIfInventory("Cell", 40, 2);
		BFGG A 0 A_PlaySound("Seeker", 1);
		Goto Charged_Fire2;
		OBLG D 0 A_Quake (1, 6, 0, 3);
		TNT1 A 0 A_GunFlash("FlashFireRedCharge1");
		TNT1 A 0 A_PlaySound("BEPBEP", 7);
		5D5X G 1 BRIGHT Offset(-2, 34) A_SetBlend("Red",0.2,1);
		5D5X H 1 BRIGHT Offset(0, 32) A_SetBlend("Red",0.2,1);
		5D5X I 1 BRIGHT Offset(2, 34) A_SetBlend("Red",0.18,1);
		5D5X J 1 BRIGHT Offset(1, 33) A_SetBlend("Red",0.2,1);
		5D5X A 1 BRIGHT Offset(0, 34) A_SetBlend("Red",0.18,1);
		TNT1 A 0 A_ReFire("Charge3B");
	Goto Charged_Fire3;
	Charge3B:
		OBLG D 0 A_Quake (1, 6, 0, 3);
		TNT1 A 0 A_GunFlash("FlashFireRedCharge1");
		5D5X A 1 BRIGHT Offset(-2, 34) A_SetBlend("Red",0.2,1);
		5D5X B 1 BRIGHT Offset(0, 32) A_SetBlend("Red",0.2,1);
		5D5X C 1 BRIGHT Offset(2, 34) A_SetBlend("Red",0.18,1);
		5D5X D 1 BRIGHT Offset(1, 33) A_SetBlend("Red",0.2,1);
		5D5X E 1 BRIGHT Offset(0, 34) A_SetBlend("Red",0.18,1);
		TNT1 A 0 A_ReFire("Charge3C");
	Goto Charged_Fire3;
	Charge3C:
		OBLG D 0 A_Quake (1, 6, 0, 3);
		TNT1 A 0 A_GunFlash("FlashFireRedCharge1");
		5D5X F 1 BRIGHT Offset(-2, 34) A_SetBlend("Red",0.2,1);
		5D5X G 1 BRIGHT Offset(0, 32) A_SetBlend("Red",0.2,1);
		5D5X H 1 BRIGHT Offset(2, 34) A_SetBlend("Red",0.18,1);
		5D5X I 1 BRIGHT Offset(1, 33) A_SetBlend("Red",0.2,1);
		5D5X J 1 BRIGHT Offset(0, 34) A_SetBlend("Red",0.18,1);
		TNT1 A 0 A_ReFire("Charge3D");
	Goto Charged_Fire3;
	Charge3D:
		OBLG D 0 A_Quake (1, 6, 0, 3);
		TNT1 A 0 A_GunFlash("FlashFireRedCharge1");
		5D5X A 1 BRIGHT Offset(-2, 34) A_SetBlend("Red",0.2,1);
		5D5X B 1 BRIGHT Offset(0, 32) A_SetBlend("Red",0.2,1);
		5D5X C 1 BRIGHT Offset(2, 34) A_SetBlend("Red",0.18,1);
		5D5X D 1 BRIGHT Offset(1, 33) A_SetBlend("Red",0.2,1);
		5D5X E 1 BRIGHT Offset(0, 34) A_SetBlend("Red",0.18,1);
	Goto Charged_Fire3;
		
	Charged_Fire1:
		TNT1 A 0 A_PlaySound("Weapons/StachanovCharged1",6);
		TNT1 A 0 A_SetBlend("Red",0.3,20);
		TNT1 A 0 a_fireprojectile("bfg_4_laser_projectile1",0,0,0,-1,0,0.0);

		TNT1 A 0 A_Takeinventory("Cell", 15);
		TNT1 A 0 a_fireprojectile("Red_FlareSpawn",0,0,0,0);
	Goto Fire_Laser+12;
	Charged_Fire2:
		TNT1 A 0 A_PlaySound("Weapons/StachanovCharged2",6);
		TNT1 A 0 A_SetBlend("Red",0.35,25);
		TNT1 A 0 a_fireprojectile("bfg_4_laser_projectile2",0,0,0,-1,0,0.0);

		TNT1 A 0 A_Takeinventory("Cell",25);
		TNT1 A 0 a_fireprojectile("Red_FlareSpawn",0,0,0,0);
	Goto Fire_Laser+12;
	Charged_Fire3:
		TNT1 A 0 A_PlaySound("Weapons/StachanovCharged3",6);
		TNT1 A 0 A_SetBlend("Red",0.4,30);
		TNT1 A 0 a_fireprojectile("bfg_4_laser_projectile3",0,0,0,-1,0,0.0);
		TNT1 A 0 A_Takeinventory("Cell",40);
		TNT1 A 0 a_fireprojectile("Red_FlareSpawn",0,0,0,0);
	Goto Fire_Laser+12;
		




		////////////////////////////////////////////////////////////////////////////
		
	AltFire:
		TNT1 A 0 A_WeaponOffset(0,32);
		TNT1 A 0
		{
			switch(invoker.actual_bfg_fire_mode)
			{
				case bfg : self.player.SetPsprite(PSP_WEAPON, invoker.resolvestate("alt_BFG") ); break; 
				case guard : self.player.SetPsprite(PSP_WEAPON, invoker.resolvestate("alt_guard") ); break; 
				case laser : self.player.SetPsprite(PSP_WEAPON, invoker.resolvestate("alt_laser") ); break; 
				default: console.printf("BFG fire fuckup, tell user_name"); break;
			}
		}
	alt_BFG:
		TNT1 A 0 A_StopSound(6);
		TNT1 A 0 A_JumpIfInventory("Cell", 5, 2);
		BFGG A 0 A_PlaySound("Seeker", 1);
	Goto ready_loop;
		TNT1 A 0 A_GunFlash("FlashNothing");
		TNT1 A 0 A_PlaySound("mbfgsh", 3, 1.0);
		4DAX V 1 BRIGHT A_PlaySound("BFGFIRE", CHAN_WEAPON, 1.2);
		TNT1 A 0 A_Takeinventory("Cell",5);
		TNT1 A 0 a_fireprojectile("Green_FlareSpawn",0,0,0,0);
		4DAX W 1 BRIGHT;// a_fireprojectile("BFGSmallSphere", 0, 1, 0, 0);
		TNT1 A 0 a_fireprojectile("Green_FlareSpawn",0,0,0,0);

		TNT1 A 0 A_Recoil(1);
		4DAX X 1 BRIGHT;
			TNT1 A 0 A_QuakeEx(4, 4, 4, 6, 0, 64, "", 0);
		TNT1 A 0 a_fireprojectile("Green_FlareSpawn",0,0,0,0);
		4DAX Y 1;
		4DAX Z 1 A_GunFlash("FlashAltFireGreen");
		4DBX Z 5;
		TNT1 A 0 A_ReFire;
	Goto ready_loop;
		
	alt_guard:
		TNT1 A 0 A_StopSound(6);
		TNT1 A 0 A_JumpIfInventory("Cell", 40, 2);
		BFGG A 0 A_PlaySound("Seeker", 1);
	Goto ready_loop;
		TNT1 A 0 A_PlaySound("SHLDSTT", 2);
	alt_guard_Hold:
		TNT1 A 0 A_PlaySound("SHLDLP", 3,1,1);
		TNT1 A 0 A_GunFlash("FlashFireOrange");
		TNT1 A 0;
		
		6DBX E 1 BRIGHT Offset(-2,34);
		6DBX F 1 BRIGHT Offset(0, 32);
		6DBX G 1 BRIGHT Offset(2, 34);
		6DBX H 1 BRIGHT Offset(1, 33);
		
		TNT1 A 0;
		TNT1 A 0 A_Takeinventory("Cell",1);
		//TNT1 AAAA 0 a_fireprojectile("HellionTrailSpark_Fast", random(-30,30), 0, random(-3,3), 0);
		TNT1 A 0 BRIGHT A_SpawnItemEx ("Shield_Spawner_Placed_Cover", 0, 68, 0, 0, 0, 0, -270, 32);
		TNT1 A 0 A_Takeinventory("Cell", 40);
		TNT1 A 0 A_GunFlash("FlashReadyOrange");
		6DBX Z 4;
		TNT1 A 0 A_GunFlash("FlashReadyOrange");
		6DBX Z 4;
		TNT1 A 0;
		TNT1 A 0 A_StopSound(3);
	Goto ready_loop;
		
	alt_laser:
		TNT1 A 0 A_StopSound(6);
		TNT1 A 0 A_JumpIfInventory("Cell", 20, 3);
		BFGG A 0 A_PlaySound("Seeker", 1);
	Goto ready_loop;
		TNT1 A 0 A_GunFlash("FlashFireRed");
		TNT1 A 0 a_fireprojectile("bfg_4_laser_seek_er",0,0,0,-1,0,0);
		TNT1 A 0 A_Takeinventory("Cell",20);
		TNT1 A 0 a_fireprojectile("Red_FlareSpawn",0,0,0,0);
		TNT1 A 0 A_SetBlend("Red",0.25,15);
		TNT1 A 0 A_StopSound(5);
		TNT1 A 0 A_AlertMonsters;
		TNT1 A 0 A_PlaySound("Weapons/StachanovFire",1);
		TNT1 A 0 A_PlaySound("Weapons/StachanovAddFire",0);
		5D5X K 1 BRIGHT A_ZoomFactor(0.95);
		5D5X L 1 BRIGHT A_ZoomFactor(0.96);
		5D5X M 1 BRIGHT A_ZoomFactor(0.97);
		5D5X N 1 BRIGHT A_ZoomFactor(0.98);
		5D5X O 1 BRIGHT A_ZoomFactor(0.99);
		5D5X P 1 ;//Offset(4, 44) A_ZoomFactor(0.95)
		5D5X Q 1 ;//Offset(3, 42) A_ZoomFactor(0.96)
		
		TNT1 A 0 A_GunFlash("FlashReadyRed");
		5D5X Z 4 A_ZoomFactor(1);
		TNT1 A 0 A_GunFlash("FlashReadyRed");
		5D5X Z 4;
		TNT1 A 0 A_ClearReFire;
	goto ready_loop;

	Deselect:
		TNT1 A 0 A_Gunflash("FlashOff");
		TNT1 A 0 A_StopSound(6);
		4DCX DCBA 1;
		TNT1 A 0 A_Lower(60);
	Wait;





/////////////////////////////////	
//		technical stuff
/////////////////////////////////	

	FlashNothing:
		TNT1 A 2;
		Stop;
		
	FlashFireGreen:
		4DBX A 2 BRIGHT;//AB
		4DBX B 2 BRIGHT;//CD
		4DBX C 2 BRIGHT;//EF
		4DBX D 2 BRIGHT;//AB
		
		4DBX A 2 BRIGHT;//CD
		4DBX B 2 BRIGHT;//EF
		4DBX C 2 BRIGHT;//AB
		4DBX D 2 BRIGHT;//CD
		
		4DBX A 1 BRIGHT;//AB
		4DBX B 1 BRIGHT;//CD
		4DBX C 1 BRIGHT;//EF
		4DBX D 1 BRIGHT;//EF
		
		4DBX A 1 BRIGHT;//AB
		4DBX B 1 BRIGHT;//CD
		4DBX C 1 BRIGHT;//EF
		4DBX D 1 BRIGHT;//EF
		
		
		4DBX A 1 BRIGHT;//AB
		4DBX B 1 BRIGHT;//CD
		4DBX C 1 BRIGHT;//EF
		4DBX D 1 BRIGHT;//EF
		
		Stop;
		
	FlashAltFireGreen:
		4DBX A 1 BRIGHT;
		4DBX B 1 BRIGHT;
		4DBX C 1 BRIGHT;
		4DBX D 1 BRIGHT;
		4DAX E 1 BRIGHT;
		Stop;
		
	FlashReadyGreen:
		4DAX A 1 BRIGHT;
		4DAX B 1 BRIGHT;
		4DAX C 1 BRIGHT;
		4DAX D 1 BRIGHT;
		Stop;
		
		
		////////////////////////////
	FlashFireOrange:
		6DBX A 1 BRIGHT;//AB
		6DBX B 1 BRIGHT;//CD
		6DBX C 1 BRIGHT;//EF
		6DBX D 1 BRIGHT;//EF
		Stop;
		
	FlashAltFireOrange:
		6DBX A 1 BRIGHT;//AB
		6DBX B 1 BRIGHT;//CD
		6DBX C 1 BRIGHT;//EF
		6DBX D 1 BRIGHT;//EF
		Stop;
		
	FlashReadyOrange:
		RD6X A 1 BRIGHT;
		RD6X B 1 BRIGHT;
		RD6X C 1 BRIGHT;
		RD6X D 1 BRIGHT;
		Stop;
		
		///////////////////////////
		
	FlashReadyRed:
		5DAX ABCD 1 BRIGHT;
		Stop;
		
		
	FlashFireRed:
		5DAX EFGHIJ 1 BRIGHT;//AB
		Stop;
		
	FlashFireRedCharge1:
		5DAX EFGHIJ 1 BRIGHT;//AB
		Stop;
		
	FlashFireRedCharge2:
		5DAX EFGHIJEFGHIJ 1 BRIGHT;//AB
		Stop;
		
		
		///////////////////////////
		
		///////////////////////////
		
	FlashReadyBlue:
		RDAS P 1 BRIGHT;
		RDAS O 1 BRIGHT;
		RDAS P 1 BRIGHT;
		RDAS N 1 BRIGHT;
		Stop;
		
	FlashFireBlue:
		RDAS L 1 BRIGHT;//AB
		RDAS M 1 BRIGHT;//CD
		RDAS N 1 BRIGHT;//EF
		RDAS O 1 BRIGHT;//EF
		Stop;
		
		
		///////////////////////////
		
	FlashKicking:
		4DCX D 1;
		4DCX C 1;
		4DCX C 1;
		4DCX B 3;
		4DCX A 3;
		4DCX B 3;
		4DCX C 1;
		4DCX C 1;
		4DCX D 1;
		//TNT1 A 0 A_GunFlash("FlashReadyGreen")
		4DBX ZZZZ 1;
		Stop;
		
	FlashAirKicking:
		4DCX D 1;
		4DCX C 1;
		4DCX C 1;
		4DCX B 3;
		4DCX A 3;
		4DCX B 3;
		4DCX C 1;
		4DCX C 1;
		4DCX D 1;
		//TNT1 A 0 A_GunFlash("FlashReadyGreen")
		4DBX ZZZZ 1;
		Stop;
		
	FlashSlideKicking:
		4DCX DC 2;
		4DCX CBBAAAABBCD 2 ;
		Stop;
		
	FlashSlideKickingStop:
		//TNT1 A 0
		4DCX BBCCD 1;
		4DBX Z 1;
		Stop;
		
	FlashPunching:
		4DCX D 1;
		4DCX C 1;
		4DCX C 1;
		4DCX B 3;
		4DCX A 3;
		4DCX B 3;
		4DCX C 1;
		4DCX C 1;
		4DCX D 1;
		//TNT1 A 0 A_GunFlash("FlashReadyGreen")
		4DBX ZZZZ 1;
		Stop;
	}
}



//SHIELD. SHIELD!. SHIEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEELD?!!!?!?!
//Libra Shield, courtesy of Capt'n Toenail's Shield! And russian overkill

CLASS Shield_Part : ACTOR { 
	Default {
	
	Radius 24;
	Height 24;
	Scale 0.5;
	RenderStyle "None";
	Alpha 0.25;
	BloodType "Shield_Hit";
	+SHOOTABLE;
	+NOGRAVITY;
	+NOTELEPORT;
	+NODAMAGE;
	+DONTRIP;
	+NOBLOODDECALS;
	+FLOORCLIP;
	+FRIENDLY;
	+REFLECTIVE;
	Damagetype "BFGShield";
	//  +GHOST
	// THRUREFLECT
	}
	States
	{
	Spawn:
		SHIE A 2 bright;
		stop;
	Death:
		TNT1 A 2;
		stop;
	}
}

CLASS Shield_Part_Visual : ACTOR { 
	Default {
	
	Radius 24;
	Height 24;
	Scale 0.5;
	RenderStyle "Add";
	Obituary "%o was evaporated by %k's shield, mwahahaha!";
	Alpha 0.25;
	+NOINTERACTION;
	+CLIENTSIDEONLY;
	+FLOORCLIP;
	+FRIENDLY;
	}
	States
	{
	Spawn:
		SHIE A 2 bright;
		stop;
	Death:
		TNT1 A 2;
		stop;
	}
}

CLASS Shield_Spawner : ACTOR
{
Default
{
	Radius 60;
	Height 60;
	+NOGRAVITY;
	+NOINTERACTION;
	+SHOOTABLE;
	+NOGRAVITY;
	+NOTELEPORT;
	+NODAMAGE;
	+DONTRIP;
	+NOBLOODDECALS;
	+FLOORCLIP;
	+FRIENDLY;
	BloodType "Shield_Hit";
	Damagetype "BFGShield";
	+REFLECTIVE;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 1;
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner4up", 0, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner5up", 24, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner5up", -24, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner4up", 48, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner4up", -48, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner3up", 72, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner3up", -72, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner2up", 96, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner2up", -96, 0, 0, 0, 0, 0, 0, 32);
		stop;
	}
}

CLASS ShieldDeathTimer1 : Inventory { 
	Default {
	
	Inventory.MaxAmount 1001;
	}
}

CLASS Shield_Spawner_Placed_Cover : ACTOR { 
	Default {
	
	Radius 60;
	Height 60;
	+NOGRAVITY;
	+NOINTERACTION;
	+SHOOTABLE;
	+NOGRAVITY;
	+NOTELEPORT;
	+NODAMAGE;
	+DONTRIP;
	+NOBLOODDECALS;
	+FLOORCLIP;
	+Solid;
	+FRIENDLY;
	Damagetype "BFGShield";
	BloodType "Shield_Hit";
	SeeSound "SHLDLP";
	DeathSound "SHLDSTT";
	+REFLECTIVE;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 1;
		TNT1 A 0 A_PlaySound("SHLDLP", 6,1,1);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner4up", 0, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner5up", 24, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner5up", -24, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner4up", 48, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner4up", -48, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner3up", 72, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner3up", -72, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner2up", 96, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner2up", -96, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_GiveInventory("ShieldDeathTimer1", 1);
		TNT1 A 0 A_JumpIfInventory("ShieldDeathTimer1", 1000, "Death");
		Loop;
	Death:
		TNT1 AAAAAAAAA 1 A_SpawnItemEx ("Shield_Spawner4up", 0, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 2;
		TNT1 AAAAAAA 1 A_SpawnItemEx ("Shield_Spawner4up", 0, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 4;
		TNT1 AAAAA 1 A_SpawnItemEx ("Shield_Spawner4up", 0, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 6;
		TNT1 AAA 1 A_SpawnItemEx ("Shield_Spawner4up", 0, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 8;
		TNT1 A 1 A_SpawnItemEx ("Shield_Spawner4up", 0, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_StopSound(6);
		TNT1 A 0 A_PlaySound("SHLDSTT");
		TNT1 AAA 0;
		Stop;
	}
}

CLASS Shield_Spawner2 : ACTOR { 
	Default {
	
	Radius 70;
	Height 70;
	+NOGRAVITY;
	+NOINTERACTION;
	+SHOOTABLE;
	+NOGRAVITY;
	+NOTELEPORT;
	+NODAMAGE;
	+DONTRIP;
	+NOBLOODDECALS;
	+FLOORCLIP;
	+REFLECTIVE;
	+FRIENDLY;
	BloodType "Shield_Hit";
	Damagetype "BFGShield";
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 1;
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner4up", 0, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner5up", 24, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner5up", -24, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner4up", 48, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner4up", -48, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner3up", 72, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner3up", -72, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner2up", 96, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Spawner2up", -96, 0, 0, 0, 0, 0, 0, 32);
		stop;
	}
}

CLASS Shield_Spawner5up : ACTOR { 
	Default {
	
	Radius 24;
	Height 24;
	+NOGRAVITY;
	+NOINTERACTION;
	+FRIENDLY;
	Damagetype "BFGShield";
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 1;
		TNT1 A 0 A_SpawnItemEx ("Shield_Part", 0, 0, 0, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Part", 0, 0, 16, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Part", 0, 0, 32, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Part", 0, 0, 48, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Part", 0, 0, 64, 0, 0, 0, 0, 32);
		//TNT1 A 0 A_SpawnItemEx ("Shield_Part_Visual", 0, 0, 0, 0, 0, 0, 0, 32)
		TNT1 A 0 A_SpawnItemEx ("Shield_Part_Visual", 0, 0, 16, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Part_Visual", 0, 0, 32, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Part_Visual", 0, 0, 48, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Part_Visual", 0, 0, 64, 0, 0, 0, 0, 32);
		stop;
	}
}

CLASS Shield_Spawner4up : ACTOR { 
	Default {
	
	Radius 24;
	Height 24;
	+NOGRAVITY;
	+NOINTERACTION;
	+FRIENDLY;
	Damagetype "BFGShield";
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 1;
		TNT1 A 0 A_SpawnItemEx ("Shield_Part", 0, 0, 8, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Part", 0, 0, 24, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Part", 0, 0, 40, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Part", 0, 0, 56, 0, 0, 0, 0, 32);
		//TNT1 A 0 A_SpawnItemEx ("Shield_Part_Visual", 0, 0, 8, 0, 0, 0, 0, 32)
		TNT1 A 0 A_SpawnItemEx ("Shield_Part_Visual", 0, 0, 24, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Part_Visual", 0, 0, 40, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Part_Visual", 0, 0, 56, 0, 0, 0, 0, 32);
		stop;
	}
}

CLASS Shield_Spawner3up : ACTOR { 
	Default {
	
	Radius 24;
	Height 24;
	+NOGRAVITY;
	+NOINTERACTION;
	+FRIENDLY;
	Damagetype "BFGShield";
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 1;
		TNT1 A 0 A_SpawnItemEx ("Shield_Part", 0, 0, 16, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Part", 0, 0, 32, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Part", 0, 0, 48, 0, 0, 0, 0, 32);
		//TNT1 A 0 A_SpawnItemEx ("Shield_Part_Visual", 0, 0, 16, 0, 0, 0, 0, 32)
		TNT1 A 0 A_SpawnItemEx ("Shield_Part_Visual", 0, 0, 32, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Part_Visual", 0, 0, 48, 0, 0, 0, 0, 32);
		stop;
	}
}


CLASS Shield_Spawner2up : ACTOR { 
	Default {
	
	Radius 24;
	Height 24;
	+NOGRAVITY;
	+NOINTERACTION;
	+FRIENDLY;
	Damagetype "BFGShield";
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 1;
		TNT1 A 0 A_SpawnItemEx ("Shield_Part", 0, 0, 24, 0, 0, 0, 0, 32);
		TNT1 A 0 A_SpawnItemEx ("Shield_Part", 0, 0, 40, 0, 0, 0, 0, 32);
		//TNT1 A 0 A_SpawnItemEx ("Shield_Part_Visual", 0, 0, 24, 0, 0, 0, 0, 32)
		TNT1 A 0 A_SpawnItemEx ("Shield_Part_Visual", 0, 0, 40, 0, 0, 0, 0, 32);
		stop;
	}
}

CLASS Shield_Hit : ACTOR { 
	Default {
	
	Scale 0.15;
	Alpha 1;
	RenderStyle "Add";
	+NOINTERACTION;
	+NOGRAVITY;
	+FRIENDLY;
	Damagetype "BFGShield";
	}
	States
	{
	Spawn:
		VINR A 0;
		VINR A 0 bright A_PlaySound("Weapons/ShieldImpact",0,1);
	Looplet:
		VINR A 0 A_FadeOut(0.1);
		VINR A 1 A_SetScale(scale.x+0.15, scale.y+0.15);
		Loop;
	}
}
///////////////////////////////////////////////////////////////////////////////////////////////////
//Laser Beamz (Originally from Russian Overkill)
//Projectile

CLASS bfg_4_laser_projectile : pb_projectile_base
{ 
Default
{	
	Speed 200;
	Radius 12;
	Height 8;
	Damage 40;
	Renderstyle "Add";
	// +RIPPER
	-CANNOTPUSH;
	+NODAMAGETHRUST;
	+EXTREMEDEATH;
	+FORCERADIUSDMG;
	DamageType "ExplosiveImpact";
	DeathSound "weapons/StachanovHit";
	MissileType "bfg_4_laser_train";
	MissileHeight 10;
	Decal "BFGLightning";
	Decal "BigScorch";
}
states
{
	Spawn:
		TNT1 A 0;
		TNT1 A 1 A_PlaySound("Weapons/StachanovFly",5,1.0,1);
		Loop;
	Death:
		TNT1 A 0 A_PlaySound("Weapons/YamatoExp",5);
		TNT1 AAAAAAAAAA 0 A_SpawnItemEx("bfg_4_laser_train_Spark", random(19,-19), random(19,-19), random(19,-19), 0, 0, 0, 0, 128, 0);
		TNT1 A 0 A_SpawnItemEx("bfg_4_laser_explode",0,0,0,0,0,0,0,128,0);
		TNT1 A 0 A_Explode(60,80,0,1);
		TNT1 BCD 4;
		stop;
	}
}

CLASS bfg_4_laser_seek_er : FastProjectile { 
	Default {
	
	Speed 100;
	Radius 12;
	Height 8;
	Damage 45;
	Renderstyle "Add";
	// +RIPPER
	-CANNOTPUSH;
	+NODAMAGETHRUST;
	+EXTREMEDEATH;
	+Friendly;
	+FORCERADIUSDMG;
	+SeekerMissile;
	DamageType "ExplosiveImpact";
	DeathSound "weapons/StachanovHit";
	MissileType "bfg_4_laser_train";
	MissileHeight 10;
	Decal "BFGLightning";
	Decal "BigScorch";
	Scale 0.55;
	}
	states
	{
	Spawn:
		TNT1 A 0 A_SeekerMissile(0, 90, SMF_LOOK || SMF_PRECISE);
		TNT1 A 1 A_PlaySound("Weapons/StachanovFly",5,1.0,1);
		Loop;
	Death:
		TNT1 A 0 A_PlaySound("Weapons/YamatoExp",5);
		TNT1 AAAAAAAAAA 0 A_SpawnItemEx("bfg_4_laser_train_Spark", random(19,-19), random(19,-19), random(19,-19), 0, 0, 0, 0, 128, 0);
		TNT1 A 0 A_SpawnItemEx("bfg_4_laser_explode",0,0,0,0,0,0,0,128,0);
		TNT1 A 0 A_Explode(50,40,0,1);
		TNT1 BCD 4;
		stop;
	}
}

CLASS bfg_4_laser_explode : ACTOR { 
	Default {
	
	Radius 12;
	Height 8;
	Renderstyle "Add";
	Scale 0.5;
	+NOINTERACTION;
	+NOGRAVITY;
	+CLIENTSIDEONLY;
	}
	states
	{
	Spawn:
		YAE3 ABCDEFGHIJKLMNOPQRS 1 bright A_FadeOut(0.05);
		stop;
	}
}

CLASS bfg_4_laser_train : pb_special_effect_base { 
	Default {
	
	RenderStyle "Add";
	Scale 0.175;
	Alpha 1;
	+NOINTERACTION;
	+NOGRAVITY;
	+CLIENTSIDEONLY;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SetScale(scale.x, scale.y -0.0875);
		YAE4 A 2 bright A_SpawnItemEx("bfg_4_laser_train_Spark", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, 128, 0);
		YAE4 A 2 bright;
	Trolololo:
		YAE4 A 0 A_JumpIf(scale.y <= 0, "NULL");
		YAE4 A 0 A_SetScale(scale.x -0.01, scale.y -0.01);
		YAE4 A 1 bright A_FadeOut(0.295);
		Loop;
	}
}

CLASS bfg_4_bfg_train_green: bfg_4_laser_train { 
	Default {
	
	Scale 0.45;
	Translation "0:255=%[0,0,0]:[0,1,0]";
	}
	States
	{
	Spawn:
	TNT1 A 0;
	TNT1 A 0;
	YAE4 A 2 bright A_SpawnItemEx("bfg_4_bfg_train_spark_green", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, 128, 0);
	YAE4 A 2 bright;
	Trolololo:
	YAE4 A 0 A_JumpIf(scale.y <= 0, "NULL");
	YAE4 A 0;
	YAE4 A 1 bright A_FadeOut(0.295);
	Loop;
}
}

CLASS bfg_4_bfg_train_bean_green: bfg_4_laser_train { 
	Default {
	
	Scale 0.085;
	Alpha 0.65;
Translation "0:255=%[0,0,0]:[0,1,0]";
	}
  States
  {
Spawn:
	TNT1 A 0;
	TNT1 A 0;
	YAE4 A 2 bright;//A_SpawnItemEx("bfg_4_bfg_train_spark_green", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, 128, 0)
	YAE4 A 2 bright;
Trolololo:
	YAE4 A 0 A_JumpIf(scale.y <= 0, "NULL");
	YAE4 A 0;
	YAE4 A 1 bright A_FadeOut(0.295);
	Loop;
}
}

CLASS bfg_4_laser_train_Spark : pb_special_effect_base { 
	Default {
  
    RenderStyle "Add";
    Scale 0.0125;
    Alpha 0.95;
    +NOINTERACTION
    +NOGRAVITY
    +CLIENTSIDEONLY
	}
    States
    {
    Spawn:
	YAE4 A 0 NoDelay A_JumpIf(scale.x <= 0, "NULL");
	YAE4 A 0 A_SetScale(scale.x-0.00075);
    YAE4 A 3 bright A_ChangeVelocity (frandom(-0.8, 0.8), frandom(-0.8, 0.8), frandom(-0.8, 0.8), 0);
    YAE4 A 1 bright A_FadeOut(0.05);
    Loop;
    }
}

CLASS bfg_4_bfg_train_spark_green : pb_special_effect_base { 
	Default {
  
    RenderStyle "Add";
    Scale 0.0125;
    Alpha 0.95;
    +NOINTERACTION
    +NOGRAVITY
    +CLIENTSIDEONLY
	}
    States
    {
    Spawn:
	YAE6 A 0 NoDelay A_JumpIf(scale.x <= 0, "NULL");
	YAE6 A 0 A_SetScale(scale.x-0.00075);
    YAE6 A 3 bright A_ChangeVelocity (frandom(-0.8, 0.8), frandom(-0.8, 0.8), frandom(-0.8, 0.8), 0);
    YAE6 A 1 bright A_FadeOut(0.05);
    Loop;
    }
}

CLASS bfg_4_purpy_train_spark : pb_special_effect_base { 
	Default {
  
    RenderStyle "Add";
    Scale 0.022;
    Alpha 0.95;
    +NOINTERACTION;
    +NOGRAVITY
    +CLIENTSIDEONLY
	}
    States
    {
    Spawn:
	YA36 A 0 NoDelay A_JumpIf(scale.x <= 0, "NULL");
	YA36 A 0 A_SetScale(scale.x-0.00075);
    YA36 A 3 bright A_ChangeVelocity (frandom(-0.8, 0.8), frandom(-0.8, 0.8), frandom(-0.8, 0.8), 0);
    YA36 A 1 bright A_FadeOut(0.05);
    Loop;
    }
}

CLASS bfg_4_purpy_train_spark_Small : pb_special_effect_base { 
	Default {
  
    RenderStyle "Add";
    Scale 0.01;
    Alpha 0.95;
    +NOINTERACTION
    +NOGRAVITY
    +CLIENTSIDEONLY
	}
    States
    {
    Spawn:
	YA36 A 0 NoDelay A_JumpIf(scale.x <= 0, "NULL");
	YA36 A 0 A_SetScale(scale.x-0.00075);
    YA36 A 3 bright A_ChangeVelocity (frandom(-0.8, 0.8), frandom(-0.8, 0.8), frandom(-0.8, 0.8), 0);
    YA36 A 1 bright A_FadeOut(0.05);
    Loop;
    }
}

CLASS Freezer_Train_Sparks_tiny : pb_special_effect_base { 
	Default {
  
    RenderStyle "Add";
    Scale 0.008;
    Alpha 0.95;
    +NOINTERACTION
    +NOGRAVITY
    +CLIENTSIDEONLY
	}
    States
    {
    Spawn:
	YA36 B 0 NoDelay A_JumpIf(scale.x <= 0, "NULL");
	YA36 B 0 A_SetScale(scale.x-0.00075);
    YA36 B 3 bright A_ChangeVelocity (frandom(-0.8, 0.8), frandom(-0.8, 0.8), frandom(-0.8, 0.8), 0);
    YA36 B 1 bright A_FadeOut(0.05);
    Loop;
    }
}

//Charge-up stuff
CLASS bfg_4_laser_projectile1 : bfg_4_laser_projectile { 
	Default {
 
  Damage 100;
  Scale 1.1;
  DamageType "Blast";
  -RIPPER;
  MissileType "bfg_4_laser_train";
	}
}

CLASS bfg_4_laser_projectile2 : bfg_4_laser_projectile { 
	Default {
 
  Scale 1.2;
  Damage 250;
  DamageType "Cut";
  -RIPPER
  MissileType "bfg_4_laser_train2";
	}
}

CLASS bfg_4_laser_projectile3 : bfg_4_laser_projectile { 
	Default {
 
  Scale 1.3;
  Damage 500;
  DamageType "Incinerate";
  +RIPPER
  +NOBOSSRIP
  MissileType "bfg_4_laser_train3";
	}
}

CLASS bfg_4_laser_train2 : bfg_4_laser_train { 
  States
  {
  Spawn:
    TNT1 A 0;
    TNT1 A 0 A_SetScale(scale.x, scale.y -0.0875);
    YAE4 AA 2 bright A_SpawnItemEx("bfg_4_laser_train_Spark", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, SXF_CLIENTSIDE, 0);
  Trolololo:
    YAE4 A 0 A_JumpIf(scale.y <= 0, "NULL");
    YAE4 A 0 A_SetScale(scale.x -0.01, scale.y -0.01);
    YAE4 A 1 bright A_FadeOut(0.095);
    Loop;
  }
}

CLASS bfg_4_laser_train3 : bfg_4_laser_train { 
  States
  {
  Spawn:
    TNT1 A 0;
    TNT1 A 0 A_SetScale(scale.x, scale.y -0.0875);
	YAE4 A 1;
    YAE4 AAA 1 bright A_SpawnItemEx("bfg_4_laser_train_Spark", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, SXF_CLIENTSIDE, 0);
  Trolololo:
    YAE4 A 0 A_JumpIf(scale.y <= 0, "NULL");
    YAE4 A 0 A_SetScale(scale.x -0.01, scale.y -0.01);
    YAE4 A 1 bright A_FadeOut(0.04);
    Loop;
  }
}

////////////////////////////////////////////////////////////////////////////////

CLASS Lights_Train_Spark : pb_special_effect_base { 
	Default {
  
    RenderStyle "Add";
    Scale 0.0135;
    Alpha 0.95;
    +NOINTERACTION
    +NOGRAVITY
    +CLIENTSIDEONLY
	}
    States
    {
    Spawn:
	YAE5 A 0 NoDelay A_JumpIf(scale.x <= 0, "NULL");
	YAE5 A 0 A_SetScale(scale.x-0.00075);
    YAE5 A 3 bright A_ChangeVelocity (frandom(-0.8, 0.8), frandom(-0.8, 0.8), frandom(-0.8, 0.8), 0);
    YAE5 A 1 bright A_FadeOut(0.05);
    Loop;
    }
}

CLASS Lightning_Ball : pb_projectile_base
{ 
	Default {
 
   Speed 80;
   Height 8;
   Radius 8;
   Damagefunction (random(0,1));
   Scale 0.55;
   RenderStyle "Add";
   Alpha 0.95;
   DeathSound "LightningHit";
   PROJECTILE;
   Decal "Scorch";
   +NOBLOCKMAP
   +DROPOFF
   +NOGRAVITY
   +NOEXTREMEDEATH
   +MTHRUSPECIES
   +FRIENDLY
   +SeekerMissile
   DamageType "Plasma";
	}
   States
   {
   Spawn:
	  TNT1 A 0 A_SpawnItem("PlasmaFlare",0,0);
      DPLS A 1 BRIGHT A_SpawnItemEx("Lights_Train_Spark", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, SXF_CLIENTSIDE, 0);
	  TNT1 A 0 BRIGHT A_SpawnItem("PlasmaFlare",0,0);
	  DPLS B 1 BRIGHT A_SpawnItemEx("Lights_Train_Spark", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, SXF_CLIENTSIDE, 0);
	  TNT1 A 0 A_SpawnItem("PlasmaFlare",0,0);
	  DPLS C 1 BRIGHT A_SpawnItemEx("Lights_Train_Spark", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, SXF_CLIENTSIDE, 0);
	  TNT1 A 0 BRIGHT A_SpawnItem("PlasmaFlare",0,0);
	  DPLS D 1 BRIGHT A_SpawnItemEx("Lights_Train_Spark", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, SXF_CLIENTSIDE, 0);
	  TNT1 A 0 BRIGHT A_SpawnItem("PlasmaFlare",0,0);
	  DPLS E 1 BRIGHT A_SpawnItemEx("Lights_Train_Spark", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, SXF_CLIENTSIDE, 0);
	  TNT1 A 0 BRIGHT A_SpawnItem("PlasmaFlare",0,0);
	  DPLS F 1 BRIGHT A_SpawnItemEx("Lights_Train_Spark", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, SXF_CLIENTSIDE, 0);
	  TNT1 A 0 A_SpawnItem("PlasmaFlare",0,0);
	  TNT1 A 0 BRIGHT A_SpawnItem("PlasmaFlare",0,0);
	  DPLS G 1 BRIGHT A_SpawnItemEx("Lights_Train_Spark", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, SXF_CLIENTSIDE, 0);
      Goto Death;
	  
   Death:
	  TNT1 A 0 a_spawnprojectile ("BluePlasmaFire", 0, 0, random (0, 360), 2, random (0, 360));
	TNT1 AAAAA 0 a_spawnprojectile ("BluePlasmaParticle", 0, 0, random (0, 360), 2, random (0, 360));
	TNT2 AAA 0 a_spawnprojectile ("ExplosionSmoke", 1, 0, random (0, 360), 2, random (0, 160));
      Stop;
   }
}
