
CLASS RapedArachnotron_X : pb_blood_and_gore_base { 
Default {
	Health 200;
	Scale 1.0;//sprite already scaled
}
States{
	Spawn:
		ARF3 O -1;
	Stop;
}

}
	
CLASS CrawlingDyingSpider2 : pb_blood_and_gore_base { 
Default {
	Radius 12;
	Height 24;
	Speed 9;
	Health 100;
	PainSound "SP_CRAWL";
	damagefactor "Kick", 0.1;
	damagefactor "Melee", 0.1;
	damagefactor "SuperPunch", 0.1;
	damagefactor "SuperKick", 0.1;
	damagefactor "Extremepunches", 0.1;
	PainChance "Kick", 255;
	PainChance "SuperKick", 255;
	PainChance "SuperPunch", 255;
	PainChance "Extremepunches", 255;
	PainChance 255;
	damagefactor "trample", 2.0;
	+SHOOTABLE;
	+FLOORCLIP;
	//+NOBLOCKMAP
	+LOOKALLAROUND;
	+FRIGHTENED;
	+SOLID;
}
States
{

	Spawn:
		NAHD B 1 A_Look();
	Goto See;
	See:
		NAHD ABCD 10 A_Chase();
		NAHD A 0 A_Pain();
		TNT1 A 0 A_SpawnItemEx("Brutal_FlyingBlood", 0, 0, 10, 0, 0);
		//TNT1 A 0 A_GiveInventory("DeathTimer1", 1);
		//TNT1 A 0 A_JumpIfInventory("DeathTimer1", 12, "GotoDeath");
	Loop;
	
	GotoDeath:
		TNT1 A 0;
		TNT1 A 0 {self.bNOPAIN = true;}
		NAHD EFGH 5;
		NAHD H -1;
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("SmallBrainPiece", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 10, 0, random(0, 360), 2, random(0, 160));
		NAHD IJKLMN 5;
		NAHD N -5;
	Stop;

	Pain.SuperPunch:
	Pain.SuperKick:
	Pain.Kick:
	Pain.Extremepunches:
		TNT1 A 0 A_FaceTarget();
		NAHB A 1 A_Pain();
		TNT1 A 0 ThrustThing(angle*256/360+128, 5, 0, 0);
	Pain.ExplosiveImpact:
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		NAHB A 2 A_FaceTarget();
	Goto Fly;
	
	Fly:
		NAHB ABCDEFGH 3 A_CheckFloor("See");
		tnt1 a 0 A_JumpIf(vel.z == 0, "See");
		TNT1 A 0;
	Loop;
	
}

}