class proto_rev_class : pb_monster_base
{
bool jetpack;
default
{
	Radius 20;
	Height 60;
}
states
{
	Death.Blackhole:
		TNT1 A 0 {A_Scream(); A_NoBlocking();  A_PlaySound("redburn",6,1,1);}
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));		
		//TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);

		TNT1 A 0 {if(jetpack == true) {self.setstatelabel("Death.BlackHole.Jetpack");} }
		ID57 AABCDEFGHI 4;// A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
	Stop;
	
	Death.Blackhole.jetpack:
		ID68 AABCDEFGHI 4;// A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
	Stop;

}


}



































CLASS XDeathRevenantHead: XDeathBullArm1 { 
	Default {
	
	-CLIENTSIDEONLY;
	Scale 1.0;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		XHE6 ABCD 6;
		Loop;
	Death:
		XHE6 A 1;
		XHE6 A 1 A_SpawnItem("RevenantHead",0,0,0,1);
		Stop;
	}
}




CLASS RevenantHead: LimbBase { 
	Default {
	
	damagefactor "Kick", 9.0;
	damagefactor "Melee", 9.0;
	damagefactor "SuperPunch", 9.0;
	BloodType "RevenantBlood";
	-CLIENTSIDEONLY;
	Radius 10;
	
	Mass 12;
	Health 60;
	Scale 1.0;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		XHE6 B -1;
		Stop;
		
	Death.Trample:
	Crush:
		TNT1 AAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS1 B 5;
		CRS1 B 9009;
		Stop;
	Death.plasma:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL A 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0;
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		XHE6 A 1 A_Pain;
		XHE6 A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeathRevenantHeadKicked", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 a_spawnprojectile("LSpart1", 2, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("LSpart3", 2, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("LSpart2", 2, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 AAAAAA 0 a_spawnprojectile("SmallBrainPiece", 5, 0, random(0, 360), 2, random(60, 140));
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		XHE6 ABCD 3;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		Goto Fly293;
	Fly293:
		XHE6 ABCD 6;
		TNT1 A 0 A_JumpIf(vel.z == 0, "Land293");
		
	Land293:
		XHE6 I 0 A_SpawnItem("XDeathRevenantHead");
		Stop;
		
}}


CLASS XDeathRevenantHeadKicked: XDeathRevenantHead { 
	Default {
	
	-BOUNCEONACTORS;
	Damage 4;
	Speed 13;
	BounceFactor 0.4;
	}
}

CLASS XDeathRevenantHeadKicked2: XDeathRevenantHead { 
	Default {
	
	+BOUNCEONACTORS;
	+NOEXTREMEDEATH;
	Damage 15;
	Speed 24;
	BounceFactor 0.2;
	}
}


CLASS XDeathHalfSkeleton : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Speed 9;
	Mass 8;
	BounceFactor 0.4;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		SKEX F 12 a_spawnprojectile("pb_FlyingBloodTrail",0,0,180,2);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		SKEX F 0 A_SpawnItem("GibHalfSkeleton",0,0,0,1);
		Stop;
	}
}

CLASS XDeathHalfDraugr : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Speed 9;
	Mass 8;
	BounceFactor 0.4;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		BNP4 E 12 a_spawnprojectile("pb_FlyingBloodTrail",0,0,180,2);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		BNP4 E 0 A_SpawnItem("GibHalfDraugr",0,0,0,1);
		Stop;
	}
}

CLASS GibHalfDraugr: BigGibBase { 
	Default {
	
	Radius 8;
	damagefactor "Kick", 12.0;
	damagefactor "ExtremePunches", 12.0;
	damagefactor "Melee", 12.0;
	damagefactor "Fatality", 12.0;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		BNP4 E 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		BNP4 E -1;
		Stop   ;
	Death.Trample:
	Death:
		TNT1 A 0 A_SpawnItem("HellishMissileLauncher");
		TNT1 AA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		Stop;
}}

CLASS GibHalfSkeleton: BigGibBase { 
	Default {
	
	Radius 8;
	damagefactor "Kick", 12.0;
	damagefactor "ExtremePunches", 12.0;
	damagefactor "Melee", 12.0;
	damagefactor "Fatality", 12.0;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		SKEX F 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		SKEX F -1;
		Stop   ;
	Death.Trample:
	Death:
		TNT1 A 0 A_SpawnItem("HellishMissileLauncher");
		TNT1 AA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		Stop;
}}
	
CLASS GibHalfSkeletonJustLegs: BigGibBase { 
	Default {
	
	Radius 8;
	damagefactor "Kick", 12.0;
	damagefactor "ExtremePunches", 12.0;
	damagefactor "Melee", 12.0;
	damagefactor "Fatality", 12.0;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		SKEX E 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		SKEX E -1;
		Stop   ;
	Death.Trample:
	Death:
		TNT1 AA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		Stop;
}}




CLASS SkeletonXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 AAAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfSkeleton", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
	Death:
		TNT1 A 0;
		Stop;
}
}

CLASS SkeletonXDeathRare : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 a_spawnprojectile("XDeathHalfSkeleton", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("RoamingLegs", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
	Death:
		TNT1 A 0;
		Stop;
}
}

