CLASS pb_Quad_Shotgun_Zombie: sergeant_base// Replaces ShotgunGuy
{
int shoot_counter;

Default
{	
	Health 46;
	Radius 16;
	Mass 100;
	Speed 9;
	Scale .98;
	//SpawnID 12;
	Monster;

	SeeSound "grunt/sight";
	PainSound "grunt/pain";
	DeathSound "grunt/death";
	ActiveSound "grunt/active";
	Obituary "%o was splattered by a Quad-Shotgun Zombie";

	DamageFactor "Blood", 0.0; DamageFactor "BlueBlood", 0.0; DamageFactor "GreenBlood", 0.0;
//	//DropItem "NewShell";
//	//DropItem "DropedSSG";
//	//DropItem "DropedGrenade", 5;
}

States
{
	Spawn:
		TNT1 A 0;
 		QSZM B 1 {ammo_amount = random(0, max_magazine_size);}
	Stand:
		QSZM A 12 A_Look();
	Loop;

	See:
		TNT1 A 0 {self.bNODROPOFF = false;}
		//TNT1 A 0 A_TakeInventory("SKQuadShotgunZombie", 1);
		TNT1 A 0 A_TakeInventory("EnemyMemory", 15);
		TNT1 A 0 A_CheckSight("SeeNeverSeen");
	SeeContinue:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_JumpIfCloser(200, "FallBack");
		//Advance:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_JumpIfInventory("EnemyMemory", 15, "SearchForPlayer");
		TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 20, 0, 0);
		//TNT1 A 0 A_TakeInventory("SKShotgunGuy", 1);
		QSZM AAAA 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
		QSZM BBBB 2 A_Chase();
		
		QSZM CCCC 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
		QSZM DDDD 2 A_Chase();
	Loop;
























	Death.Shrink:
		TNT1 A 1 A_PlaySound("Shrink", 3);
/*		TNT1 A 0 A_SpawnItemEx("QuadShotgunZombieShrinkFX1", 0, 0,  5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("QuadShotgunZombieShrinkFX2", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("QuadShotgunZombieShrinkFX3", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("QuadShotgunZombieShrinkFX4", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("QuadShotgunZombieShrinkFX5", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("QuadShotgunZombieShrinkFX6", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("QuadShotgunZombieShrinkFX7", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("LilQuadShotgunZombie", 1);*/
	stop;
	
	Pain.Avoid: 
		TNT1 A 0;
		TNT1 A 0 A_Jump(255, "AvoidLeft", "AvoidRight");
	Goto AvoidLeft;
		
	AvoidLeft:
		ZRO6 A 1 A_FaceTarget();
		TNT1 A 0 ThrustThing(angle*256/360+192, 15, 0, 0);
		ZRO6 ABCDEFGH 2 A_FaceTarget();
		Goto Missile;
	AvoidRight:
		ZRO5 A 1 A_FaceTarget();
		TNT1 A 0 ThrustThing(angle*256/360+64, 15, 0, 0);
		ZRO5 ABCDEFGH 2 A_FaceTarget();
		Goto Missile;
		
		
	FallBack:
		TNT1 A 0 A_CheckSight("Advance");
		TNT1 A 0 {self.bNODROPOFF = true;}
		QSZM D 2 A_FaceTarget();
		QSZM D 2 A_Recoil(2);
		TNT1 A 0 A_jump(64, "Missile");
		QSZM C 2 A_FaceTarget();
		QSZM C 2 A_Recoil(2);
		QSZM B 2 A_FaceTarget();
		QSZM B 2 A_Recoil(2);
		QSZM A 2 A_FaceTarget();
		QSZM A 2 A_Recoil(2);
		QSZM D 2 A_FaceTarget();
		QSZM D 2 A_Recoil(2);
		TNT1 A 0 A_jump(64, "Missile");
		QSZM C 2 A_FaceTarget();
		QSZM C 2 A_Recoil(2);
		QSZM B 2 A_FaceTarget();
		QSZM B 2 A_Recoil(2);
		QSZM A 2 A_FaceTarget();
		QSZM A 2 A_Recoil(2);
		TNT1 A 0 {self.bNODROPOFF = false;}
	GOto Missile;
		
		
		
		
	SearchForPlayer:
	Idle:
		TNT1 A 0 A_ClearTarget();
		TNT1 A 0 A_TakeInventory("EnemyMemory", 30);
		QSZM ACADA 10 A_Look();
		
		QSZM A 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		QSZM B 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		QSZM C 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		QSZM D 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		
		TNT1 A 0 A_Jump(128, "Idle");
		QSZM A 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		QSZM B 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		QSZM C 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		QSZM D 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
	Loop;
		

		
	SeeNeverSeen:
		TNT1 A 0 A_JumpIfCloser(200, "FallBack");
	Advance:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		QSZM AA 2 A_Chase();
		TNT1 A 0 A_Recoil(-1);
		QSZM BB 2 A_Chase();
		QSZM CC 2 A_Chase();
		QSZM DD 2 A_Chase();
	Loop;
		
	Missile:
		TNT1 A 0 A_Jump(132, "SingleShot");
		QSZM E 0 {if(shoot_counter > 4) { setstatelabel("SingleShot"); } }
	QuadShot:
		QSZM EEEE 5 A_FaceTarget();
		QSZM F 0 Bright A_PlaySound("QSGFIRE1", 12);
		QSZM F 0 Bright {shoot_counter = 4;}
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		QSZM F 4;
		TNT1 A 0 A_Playsound("SuperShotgunDistantGunshot", 3);
		TNT1 AAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("QuadTracer", random(16, 64), random(-25, 25), random(-20, 20), 0, random(-22, 22));
		QSZM EE 6 A_FaceTarget();
	Goto Reload;
		
	SingleShot:
		QSZM EE 5 A_FaceTarget();
		QSZM F 0 Bright A_PlaySound("weapons/shh2", 8);
		QSZM F 0 Bright {shoot_counter ++;}
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 AA 0 a_spawnprojectile("QuadSingeTracer", random(28, 50), 0, random(-14, 14), 0, random(-17, 17));
		QSZM F 4 Bright A_PlaySound("weapons/shh2", 8);
		TNT1 AA 0 a_spawnprojectile("QuadSingeTracer", random(28, 50), 0, random(-14, 14), 0, random(-17, 17));
		QSZM E 6 A_FaceTarget();
		TNT1 A 0 A_Playsound("SuperShotgunDistantGunshot", 3);
		QSZM E 0 {if(shoot_counter > 4) {setstatelabel("Reload");} }//A_JumpIfInventory("QuadShotgunZombieCounter", 4, "Reload");
		QSZM E 0 A_Jump(96, "SingleShot");
		QSZM EE 6 A_FaceTarget();
	Goto SeeContinue;
		
	Reload:
		QSZM A 4 A_FaceTarget();
		QSZX FABCDE 3;
		TNT1 A 0 A_PlaySound("QuadShotgunZombie/Reload2", 6);
		QSZM E 0 {shoot_counter = 0;}
		QSZM A 4 A_FaceTarget();
		QSZX FABCDE 3;
		TNT1 A 0 A_PlaySound("QuadShotgunZombie/Reload2", 6);
	Goto SeeContinue;
		
	Pain.Melee:
		//TNT1 A 0 A_JumpIfInventory("SKQuadShotgunZombie", 1, "GotoStealthKill");
	Pain:
		QSZM G 3;
		QSZM G 3 A_Pain();
		Goto SeeContinue;
		
	Possession:
		TNT1 A 0 A_SetInvulnerable();
		QSZM G 3;
		QSZM G 3 A_Pain();
 		TNT1 A 0 A_UnSetInvulnerable();
	Goto See;
		
	Pain.Stun:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx("StunElectrocute", random(-4, 4), random(-4, 4),  random(16, 32), 0, 0);
		QSZM G 1 A_Pain();
		QSZM GGGGGGGGGG 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		QSZM G 1 A_Pain();
		QSZM GGGGGGGGGG 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		QSZM G 1 A_Pain();
		QSZM GGGGGGGGGG 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		QSZM G 1 A_Pain();
		QSZM GGGGGGGGGG 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		QSZM G 1 A_Pain();
		QSZM GGGGGGGGGG 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		QSZM G 1 A_Pain();
		Goto See;
		
	Pain.ExplosiveImpact:
	Pain.Kick:
	Pain.ExtremePunches:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain");
		QXXZ A 0 A_Pain();
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 {self.bNOPAIN = true;}
		//QXXZ E 1 A_Chase("","")
		QXXZ A 1 A_facetarget();
		QXXZ A 6 ThrustThing(angle*256/360+128, 10, 0, 0);
		QXXZ B 8;
		TNT1 A 0 {self.bNOPAIN = false;}
		
		Goto FallingAfterImpact;
		
	FallingAfterImpact:
		QXXZ B 1 A_GiveInventory("FallingHeight", 1);
		QXXZ B 1 A_CheckFloor("GetUp");
		tnt1 a 0 A_JumpIf(vel.z == 0, "GetUp");
		Loop;
		
	GetUp:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 5, "FallingDie");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_TakeInventory("FallingHeight", 100);
		QXXZ CCCCCCC 5 A_JumpIf(vel.z < 0, "FallingAfterImpact");
		
		TNT1 A 0 A_TakeInventory("IsDown", 1);
		QXXZ D 10;
		Goto See;
		
	FallingDie:
		TNT1 A 0;
		TNT1 A 0 A_ChangeCountFlags(false);
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 A_SpawnItem("SplatteredSmall");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 15, "Death.Stomp");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 10, "FallingSuperDeath");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 5, "FallingDeath");
	FallingDeath:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(50, 130));
		QXXZ AB 2;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("PB_pot");
		TNT1 A 0 A_SpawnItem("DeadHFQSZ1");
		Stop;
		
	FallingSuperDeath:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBLocking();
		TNT1 A 0 A_SpawnItem("PB_pot");
		Goto Death.ExplosiveImpact+1;
		
	Death.Shotgun:
		TNT1 A 0 A_JumpIfCloser(100, "Death.bLAST");
		TNT1 A 0 A_JumpIfCloser(300, "Death.Shotgunontheface");
		
		Goto Death;
		
	Death.ShotgunontheFace:
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_Stop();
		QSZM H 1 A_FaceTarget();
		TNT1 A 0 A_Recoil(12);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		TNT1 A 0 a_spawnprojectile("MuchBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		Goto Death;
		
	Death.Eat:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Scream();
		//TNT1 A 0 A_GiveToTarget("HFQSZFatality",1);
	Stop;
		
	Death.ShotgunonthefaceArm:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "Death.Arm");
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("MuchBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_Scream();
		QXXZ EF 15;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("DeadHFQSZ_NoArm");
		Stop;
		
		
	Death.Melee:
		//TNT1 A 0 A_JumpIfInventory("SKQuadShotgunZombie", 1, "StealthKill");
	Death.Kick:
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Death.Down");
		TNT1 A 0 A_Scream();
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(8);
		QXXZ A 8;
		QXXZ B 8;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("DeadHFQSZ1", 5);
		Stop;
		
	Death.Down:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("DeadHFQSZ1", 1);
		Stop;
		
	Death:
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Death.Down");
		
		TNT1 A 0 A_Jump(96, "Death.Arm");
	Death.MinorLeg:
		QSZM H 5 A_Scream();
		QSZM I 5;
		QSZM J 5 A_NoBlocking();
		QSZM K 5;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadHFQSZ1", 1);
		Stop;
		
	Death.Leg:
		TNT1 A 0 A_Jump(32, "LeaveCrawling");
	Death.Crush:
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZLeg1", 35, 0, random(0, 360), 2, random(0, 160));
		QPO3 A 9 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_Playsound("grunt/death");
		QPO3 B 3;
		QPO3 C 3 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("HFQSZGotHisLegBlowed");
	Stop;
		
	LeaveCrawling:
		TNT1 A 0;
		//TNT1 A 0 A_SpawnItem("DyingHFQSZNoLeg", 2);
		TNT1 A 0;
		Stop;
		
	Death.Arm:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZArm2", 35, 0, random(0, 360), 2, random(0, 160));
		QPO6 A 9 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem("DyingHFQSZ", 2);
		Stop;
		
	HeadExploder:
		TNT1 A 0 A_Jump(128, "Death.HeadExplode");
		Goto Death.MinorHead;
		
	Death.Head:
		//TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
		//TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		//TNT1 A 0 A_JumpIfInTargetInventory("HasCutingWeapon", 1, "Death.Decaptate");
		TNT1 A 0 A_JumpIfHealthLower(-60, "Death.HeadExplode");
		//TNT1 A 0 A_JumpIfInTargetInventory("RandomHeadExploder", 1, "HeadExploder");
	Death.MinorHead:
	Death.HeadMinor:
		TNT1 A 0;
		TNT1 A 0 A_Playsound("MinorHeadshot", 0);
		TNT1 A 0 A_Jump(32, "Death.MinorHeadLong");
		TNT1 AAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail8", 50, 0, random(0, 360), 2, random(0, 360));
		TNT1 AA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		QZHS A 6 A_Scream();
		QZHS B 6 A_NoBlocking();
		QZHS CD 6;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadHFQSZ_NoBrain", 1);
		//	QSZM Z -1
		Stop;
		
	Death.MinorHeadLong:
		TNT1 AAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail8", 50, 0, random(0, 360), 2, random(0, 360));
		TNT1 AA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		QZHS A 6 A_Scream();
		QZHS B 6 A_NoBlocking();
		QZHS BCBCBC 18 A_Pain();
		QZHS DE 6;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadHFQSZ_NoBrain", 1);
		Stop;
		
	Death.HeadExplode:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_XScream();
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_NoBlocking();
		QPDH ABBC 10 a_spawnprojectile("MuchBlood", 30, 0, random(0, 360), 2, random(0, 160));
		QPDH CDE 8;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadHFQSZ_NoHead", 1);
		//        SPDH E -1
		Stop;
		
	Death.decaptate:
		TNT1 AAAAAAA 0 a_spawnprojectile("Blood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZHead", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("MuchBlood", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		QPDH AABBBC 8 a_spawnprojectile("MuchBlood", 30, 0, random(0, 360), 2, random(0, 160));
		QPDH CDE 8;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadHFQSZ_NoHead", 1);
		//        SPDH E -1
		Stop;
		
	Death.Saw:
	Death.cut:
	Death.HKFT:
		TNT1 A 0;
		TNT1 A 0 A_Jump(32, "Death.Arm", "Death");
		Goto Death.Tear;
		
	Death.cutless:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Death.Down");
		TNT1 A 0 A_Jump(16, "Death");
		TNT1 A 0 A_Jump(32, "Death.Cut");
		TNT1 A 0 A_Jump(16, "Death.LegMassacre");
		Goto Death.Massacre;
		
	Death.Tear:
		TNT1 AAA 0 a_spawnprojectile("MuchBlood", 1, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		QP3X AA 8;
		TNT1 A 0 a_spawnprojectile("XDeath4", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("RipHFQSZ", 0, 0, random(0, 360), 2, random(0, 160));
		QP3X BBCD 8;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadHFQSZ_Half", 1);
		Stop;
		
	Death.Massacre:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Scream();
		TNT1 O 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("BrutalizedHFQSZ1", 1);
	Stop;
		
	Death.Ice:
	Death.Freeze:
	Death.Frost:
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		//TNT1 A 0 A_SpawnItem("FrozenQuadShotgunguy");
	Stop;
		
	Death.LegMassacre:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Scream();
		TNT1 O 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("BrutalizedHFQSZLeg", 1);
	Stop;
		
	Death.SuperPunch:
	Death.SSG:
		QZD1 E 1 A_Pain();
		QZD1 E 1 A_FaceTarget();
		//TNT1 A 0 a_spawnprojectile("MeatDeath", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("XDeathHFQSZArm1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZHead", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		QZD1 EEFFGH 6;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadHFQSZ_QZD1H");
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		Stop;
		
	Death.Blast:
	Death.Railgun:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Jump(12, "Death.Arm");
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Jump(128, "Death.Blast2");
		TNT1 A 0 A_Scream();
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		QPO4 A 6 A_Stop();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		QPO4 BBBBBBBBBB 3 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(30, 60));
		QPO4 CCC 3 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(10, 40));
		TNT1 A 0 A_PlaySound("BODYF",6);
		QPO4 DD 3 a_spawnprojectile("Brutal_LiquidBlood2", 6, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_SpawnItem("DeadHFQSZ_QPO4E");
		Stop;
		
	Death.Blast2:
		TNT1 A 0 A_XScream();
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 42, 0, random(0, 360), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("Xdeath2", 16, 0, random(130, 210), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		QPO4 F 6 A_Stop();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		QPO4 GGGGGGGGGGGGGGGGGGG 3 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(30, 60));
		QPO4 HHH 1 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(10, 40));
		TNT1 A 0 A_PlaySound("BODYF",6);
		QPO4 II 3 a_spawnprojectile("Brutal_LiquidBlood2", 6, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_SpawnItem("DeadHFQSZ_QPO4J");//
		Stop;
		
	Death.GreenFire:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAA 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 A 0 a_spawnprojectile("XDeathBurnedArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		
		EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("GreenFlameTrails", 50, 0, random(0, 360), 2, random(0, 360));
		XBRN AAAA 2 BRIGHT A_SpawnItem("Green_Flare",0,43);
		Stop;
		
	Death.Plasma: Death.Plasma2:
	TNT1 A 0;
	TNT1 A 0 A_Stop();
	TNT1 A 0 A_PlaySound("plasmaflesh");
	TNT1 AAAAAAAAA 0 a_spawnprojectile("Ashes1", 32, 0, random(0, 360), 2, random(0, 180));
	TNT1 AAAAAAAAA 0 a_spawnprojectile("Ashes2", 32, 0, random(0, 360), 2, random(0, 180));
	TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1Blue",random(-2,2),random(-2,2),18,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
	TNT1 AAAA 0 a_spawnprojectile("BluePlasmaFire", 42, 0, random(0, 360), 2, random(0, 180));
	TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 32, 0, random(0, 360), 2, random(0, 180));
	TNT1 AAAAAA 0 a_spawnprojectile("SuperGoreMistSmall", 32, 0, random(0, 360), 2, random(10, 90));
	TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(0, 360), 2, random(0, 180));
	PBR1 B 6 A_NoBlocking();
	TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1Blue",random(-2,2),random(-2,2),10,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
	TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 A_SpawnItem("Barrel_explosion_Column");
	TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
	TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-35, 35), random(-35, 35));
	TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-45, 45), random(-45, 35));
	PBR1 CCDD 3 a_spawnprojectile("BluePlasmaFire", 32, 0, random(0, 360), 2, random(0, 180));
	PBR1 EEFF 3;
	PBR1 GG 3;
	PBR1 H -1;
	Stop;
	
	Death.SuperPlasma:
	TNT1 A 0;
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	XBRN AA 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
	TNT1 AAAA 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
	
	TNT1 A 0 a_spawnprojectile("XDeathBurnedArm", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	
	XBRN BB 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
	TNT1 A 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
	XBRN CC 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
	TNT1 AAAAA 0 a_spawnprojectile("PlasmaParticleX", 48, 0, random(0, 360), 2, random(0, 360));
	TNT1 AAA 0 a_spawnprojectile("PlasmaParticleX", 42, 0, random(0, 360), 2, random(0, 360));
	TNT1 A 0;
	Stop;
	
	Death.Fatality:
		TNT1 A 0;
		TNT1 A 0 A_Pain();
		//TNT1 A 0 A_JumpIfIntargetInventory("FistsSelected", 1, 1);
	Goto Death.ExplosiveImpact;
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_Jump(255, "Death.Fatality1", "Death.Fatality2", "Death.Fatality3");
	Death.Fatality1:
		//TNT1 A 0 A_GiveToTarget("HFQSZFatality", 1);
	Stop;
	Death.Fatality2:    
		//TNT1 A 0 A_GiveToTarget("HFQSZFatality2", 1);
	Stop;
	Death.Fatality3:    
		//TNT1 A 0 A_GiveToTarget("HFQSZFatality3", 1);
	Stop;
	
	Death.HelperMarineFatallity:
	Death.BHFT:
	Death.RVFT:
		TNT1 A 0;
		TNT1 A 1 A_Pain();
		//TNT1 A 0 A_GiveToTarget("HFQSZFatality", 1);
		TNT1 A 0 A_NoBlocking();
		TNT1 A 1;
	Stop;
	
	Death.Incinerate:
		TNT1 A 0;
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_Playsound("MELT");
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAAA 0 a_spawnprojectile("ExplosionParticle", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAA 0 a_spawnprojectile("ExplosionParticle", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,32,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-35, 35), random(-35, 35));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-45, 45), random(-45, 35));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("Ashes1", 28, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("Ashes2", 40, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),32,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		Z8RN KKKKK 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile("ExplosionParticle", 36, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),28,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		Z8RN LLLLL 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile("ExplosionParticle", 28, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),24,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		Z8RN CCCCC 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile("ExplosionParticle", 36, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_Playsound("SZZLL", 3);
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),20,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		Z8RN DDDDD 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile("ExplosionParticle", 20, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),16,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		Z8RN EEEEE 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile("ExplosionParticle", 12, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),12,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		Z8RN FFFFF 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		TNT1 A 0 A_SpawnItem("Barrel_explosion_Column");
		Z8RN GGGG 2 Light("IncinerationGlow");
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		Z8RN HHHH 2 Light("IncinerationGlow") a_spawnprojectile("ExplosionSmoke", 14, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		Z8RN HHHHHH 12 a_spawnprojectile("ExplosionSmoke", 14, 0, random(0, 360), 2, random(0, 160));
		Z8RN H -1;
	Stop;
	
	Death.fire:
	Death.Flames:
	Death.Burn:
		TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItemEx("BurningShotgunguy",0,0,0,0,0,0,0,288);
	Stop;
	
	XDeath:
	Death.QuadBlast:
		//TNT1 A 0 A_JumpIfInTargetInventory("SSGSelected", 1, "Death.SSG");
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AA 0 a_spawnprojectile("XDeathHFQSZArm1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZHead", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZLeg2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 bright a_spawnprojectile("XDeath2", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	
	
	Death.Desintegrate:
		TNT1 A 0 A_Jump(84, "AcidGuy");
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("DesintegratedHuman");
	Stop;
	
	AcidGuy:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("GenericAcidGuy");
		TNT1 A 1;
		TNT1 A -1;
	Stop;
	
	
	Death.Stomp:
	TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
	TNT1 AAAAAA 0 bright a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(30, 180));
	TNT1 AA 0 bright a_spawnprojectile("XDeath2", 55, 0, random(0, 360), 2, random(30, 180));
	TNT1 AA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAAA 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0 bright a_spawnprojectile("XDeath3", 55, 0, random(0, 360), 2, random(30, 180));
	TNT1 A 0 A_SpawnItem("CrushedRemains");
	TNT1 A 1;
	TNT1 A 1 A_XScream();
	TNT1 A 1 A_NoBlocking();
	Stop;
	
	Death.ExtremePunches:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Jump(96,"Death.LandMine");
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZLeg2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		IQ14 AB 5;
		IQ14 CDEF 5 A_CheckFloor("Dead.ExplosiveImpact");
		IQ14 FFFFFF 5 A_CheckFloor("Dead.ExplosiveImpact");
		//TNT1 A 0 A_SpawnItem("VeryFuckedUpBrutalizedHFQSZLeg");
		TNT1 A 0 A_PlaySound("BODYF",6);
	Stop;
	
	Dead.ExplosiveImpact:
		//TNT1 A 0 A_SpawnItem("VeryFuckedUpBrutalizedHFQSZLeg");
		//TNT1 A 0 A_SpawnItem("Ploft");
		TNT1 A 0 A_SpawnItem("MuchBlood");
		TNT1 A 0 A_PlaySound("BODYF",6);
	Stop;
	
	Death.ExplosiveImpact:
	TNT1 A 0 {self.bNODROPOFF = false;}
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,30,0,1);
	TNT1 A 0 A_FaceTarget();
	TNT1 A 1;
	TNT1 A 0 A_JumpIf(angle < 180, "IsFacingNorth");
	TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayRight");
	TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayLeft");
	Goto XDeath;
	IsFacingNorth:
	TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayRight");
	TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayLeft");
	Goto XDeath;
	
	BlownAwayLeft:
		TNT1 A 0;
		TNT1 A 0 A_Jump(96, "Death.LandMine");
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSargeLeg2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(20, 90));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Xscream();
		QPO5 ABCDEFG 3 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, 0, 2, 90);
		TNT1 A 0 A_CheckFloor("Land8473");
		QPO5 ABCDEFGABCDEFG 5 A_CheckFloor("Land8473");
	Land8473:
		QPO5 N 0;
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadHFQSZ_QPO5I");
	Stop;
	
	BlownAwayRight:
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_Jump(96, "Death.ExtremePunches");
	TNT1 A 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 {self.bNOBLOCKMONST = true;}
	TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
	TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathSargeLeg2", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(20, 90));
	TNT1 A 0 ThrustThingZ(0,30,0,1);
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_SpawnItemEx("BloodMist", 0, 0, 50, vel.x, vel.y, vel.z, 0, SXF_ABSOLUTEVELOCITY);
	QPO5 GFEDCBA 3 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, 0, 2, 90);
	TNT1 A 0 A_CheckFloor("Land8472");
	QPO5 GFEDCBAGFEDCBA 5 A_CheckFloor("Land8472");
	Land8472:
	SXS2 N 0;
	TNT1 A 0 A_Stop();
	TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	TNT1 A 0 A_SpawnItem("DeadHFQSZ_QPO5H");
	Stop;
	
	Death.LandMine:
	TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathHFQSZLeg1", 32, 0, random(0, 360), 2, random(0, 160));
	//TNT1 A 0 a_spawnprojectile("GibHand", 42, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	IQ16 A 1 A_Scream();
	IQ16 A 9;
	IQ16 BCD 9 A_CheckFloor("Dead.Landmine");
	IQ16 DDDD 9 A_CheckFloor("Dead.Landmine");
	TNT1 A 0 A_PlaySound("BODYF",6);
	TNT1 A 0 A_SpawnItem("DeadHFQSZ_NoLeg", 1);
	Stop;
	
	Dead.Landmine:
		TNT1 A 0 A_SpawnItem("DeadHFQSZ_NoLeg", 1);
		//TNT1 A 0 A_SpawnItem("Ploft");
		TNT1 A 0 A_SpawnItem("MuchBlood");
		TNT1 A 0 A_PlaySound("BODYF",6);
	Stop;
	
	Raise:
	QSZM L 5;
	QSZM KJIH 5;
	Goto SeeContinue;
	Crush:
	TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail8", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 A 0 A_PlaySound("misc/xdeath4");
	POSC B 5;
	TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	POSC B -1;
	Stop;
	
	StealthKill:
	TNT1 A 0;
	//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
	//TNT1 A 0 A_GiveToTarget("SKQuadShotgunZombie", 1);
	TNT1 A 0 A_Fall();
	//TNT1 A 0 A_NoBlocking
	TNT1 A 0 A_Die("Stealthy");
	TNT1 A 1;
	TNT1 A 1;
	Stop;
	Death.Stealthy:
	TNT1 A 0;
	Stop;
}
}
/*
CLASS QuadShotgunZombieCounter : Inventory { 
	Default {
	
	Inventory.MaxAmount 4;
	}
}
*/
CLASS DeadHFQSZ1 : pb_blood_and_gore_base { 
States
    {
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,15,0,1);
	TNT1 A 0 A_FaceTarget();
	TNT1 A 0 A_Recoil(2);
	QXXZ IJ 8;
	TNT1 A 1 A_SpawnItem("DeadHFQSZ1", 5);
	Stop;
	Spawn:
	QSZM L -1;
	Stop;
	Raise:
	QSZM K 1;
	QSZM JIH 1;
	TNT1 A 0 A_SpawnItem("pb_Quad_Shotgun_Zombie", 3);
	Stop;
	Death:
	TNT1 A 0 a_spawnprojectile("XDeathHFQSZLeg1", 5, 0, random(0, 360), 2, random(0, 160));
	QSZM A 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 1 A_SpawnItem("DeadHFQSZ_NoLeg", 5);
	Stop;
	
Death.Plasma: Death.Plasma2:
	TNT1 A 0;
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	TNT1 AAA 0 a_spawnprojectile("brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	EXPL AAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
	TNT1 A 0;
	Stop;
	
}
}

CLASS DeadHFQSZ_NoArm: DeadHFQSZ1 { 
	Default
{Health 200;} States{Spawn:
        QPO6 E -1;
        Stop;
    Death.CutLess:
    Death.Cut:    
	Death:
        TNT1 A 0 A_PlaySound("misc/xdeath4");
	TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 6, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains2", 6, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains2", 6, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains4", 6, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains4", 6, 0, random(0, 360), 2, random(0, 160));
        TNT1 A 0 A_SpawnItem("DeadHFQSZ_NoHeadNoArm", 1);
	Stop;
    Death.Fatality:
    Death.Melee:
    Death.Kick:
	Death.ExplosiveImpact:
         TNT1 A 0;
         TNT1 A 0;
        TNT1 A 0 ThrustThingZ(0,15,0,1);
        TNT1 A 0 A_FaceTarget;
        TNT1 A 0 A_Recoil(2);
         QXXZ KL 8;
         TNT1 A 1 A_SpawnItem("DeadHFQSZ_NoArm", 5);
         stop;}}


CLASS DeadHFQSZ_NoLeg: DeadHFQSZ_NoArm { 
	Default
{Health 200;} States{Spawn:
        QPO3 F -1;
        Stop;
	Death:
   Death.CutLess:
    Death.Cut:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
	 TNT1 AAA 0 a_spawnprojectile("XDeath1", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath2", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 AA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath3", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath4", 50, 0, random(0, 360), 2, random(0, 160));
	Stop;
    Death.Fatality:
    Death.Melee:
    Death.Kick:
         TNT1 A 0;
         TNT1 A 0;
        TNT1 A 0 ThrustThingZ(0,15,0,1);
        TNT1 A 0 A_FaceTarget;
        TNT1 A 0 A_Recoil(2);
         QXXZ MN 8;
         TNT1 A 1 A_SpawnItem("DeadHFQSZ_NoLeg", 5);
         stop;}}

CLASS DeadHFQSZ_NoBrain: DeadHFQSZ1 { 
	Default
{Health 200;} States{Spawn:
        QZHS F -1;
        Stop;
	
	Death:
        TNT1 A 0 A_PlaySound("misc/xdeath4");
	TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 6, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains2", 6, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains2", 6, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains4", 6, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains4", 6, 0, random(0, 360), 2, random(0, 160));
        TNT1 A 0 A_SpawnItem("DeadHFQSZ_NoHead", 1);
	Stop;
    Death.Fatality:
    Death.Melee:
    Death.Kick:
	Death.ExplosiveImpact:
         TNT1 A 0;
         TNT1 A 0;
        TNT1 A 0 ThrustThingZ(0,15,0,1);
        TNT1 A 0 A_FaceTarget;
        TNT1 A 0 A_Recoil(2);
         QXXZ IJ 8;
         TNT1 A 1 A_SpawnItem("DeadHFQSZ_NoBrain", 5);
         stop;}}


CLASS DeadHFQSZ_NoHead: DeadHFQSZ1 { 
	Default
{Health 200;} States{Spawn:
        QPDH E -1;
        Stop;
	Death:
    Death.CutLess:
    Death.Cut:
	TNT1 A 0 a_spawnprojectile("XDeathHFQSZArm1", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
         TNT1 A 1 A_SpawnItem("DeadHFQSZ_NoHeadNoArm", 5);
        Stop;
    Death.Fatality:
    Death.Melee:
    Death.Kick:
	Death.ExplosiveImpact:
         TNT1 A 0;
         TNT1 A 0;
        TNT1 A 0 ThrustThingZ(0,15,0,1);
        TNT1 A 0 A_FaceTarget;
        TNT1 A 0 A_Recoil(2);
         QXXZ IJ 8;
         TNT1 A 1 A_SpawnItem("DeadHFQSZ_NoHead", 5);
         stop;}}

CLASS DeadHFQSZ_NoHeadNoArm: DeadHFQSZ1 { 
	Default
{Health 200;} States{Spawn:
        QPXS B -1;
        Stop;
	Death:
    Death.CutLess:
    Death.Cut:
	TNT1 A 0 A_SpawnItem("GibsZ");
  	    TNT1 AAA 0 a_spawnprojectile("XDeath1", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath2", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath3", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath4", 50, 0, random(0, 360), 2, random(0, 160));
	Stop;
    Death.Fatality:
    Death.Melee:
    Death.Kick:
	Death.ExplosiveImpact:
         TNT1 A 0;
         TNT1 A 0;
        TNT1 A 0 ThrustThingZ(0,15,0,1);
        TNT1 A 0 A_FaceTarget;
        TNT1 A 0 A_Recoil(2);
         QXXZ KL 8;
         TNT1 A 1 A_SpawnItem("DeadHFQSZ_NoHeadNoArm", 5);
         stop;}}

CLASS DeadHFQSZ_Half: DeadHFQSZ1 { 
	Default
{Health 200;} States{Spawn:
        QP3X E -1;
        Stop	;
	
        Death:
	Death.Cut:
        Death.Cutless:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
	 TNT1 AAA 0 a_spawnprojectile("XDeath1", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath2", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath3", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath4", 50, 0, random(0, 360), 2, random(0, 160));
         Stop;}}


CLASS DeadHFQSZ_QZD1H: DeadHFQSZ1 { 
	Default
{Health 200;} States{Spawn:
        QZD1 H -1;
        Stop;	
        Death:
	Death.Cut:
        Death.Cutless:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
	 TNT1 AAA 0 a_spawnprojectile("XDeath1", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath2", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath3", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath4", 50, 0, random(0, 360), 2, random(0, 160));
         Stop;}}
	 

CLASS DeadHFQSZ_QPO4E: DeadHFQSZ1 { 
	Default
{Health 200;} States{Spawn:
        QPO4 E -1;
        Stop;
        Death:
	Death.Cut:
        Death.Cutless:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
	 TNT1 AAA 0 a_spawnprojectile("XDeath1", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath2", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath3", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath4", 50, 0, random(0, 360), 2, random(0, 160));
         Stop;}}


CLASS DeadHFQSZ_QPO4J: DeadHFQSZ1 { 
	Default
{Health 200;} States{Spawn:
        QPO4 J -1;
        Stop;
        Death:
	Death.Cut:
        Death.Cutless:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
	 TNT1 AAA 0 a_spawnprojectile("XDeath1", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath2", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath3", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath4", 50, 0, random(0, 360), 2, random(0, 160));
         stop;}}

CLASS DeadHFQSZ_QPO5I: DeadHFQSZ1 { 
	Default
{Health 200;} States{Spawn:
        QPO5 I -1;
        Stop;	
        Death:
	Death.Cut:
        Death.Cutless:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
	 TNT1 AAA 0 a_spawnprojectile("XDeath1", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath2", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath3", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath4", 50, 0, random(0, 360), 2, random(0, 160));
         stop;}}


CLASS DeadHFQSZ_QPO5H: DeadHFQSZ1 { 
	Default
{Health 200;} States{Spawn:
        QPO5 H -1;
        Stop;	
        Death:
	Death.Cut:
        Death.Cutless:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
	 TNT1 AAA 0 a_spawnprojectile("XDeath1", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath2", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath3", 50, 0, random(0, 360), 2, random(0, 160));
	 TNT1 A 0 a_spawnprojectile("XDeath4", 50, 0, random(0, 360), 2, random(0, 160));
         stop;}}


CLASS BeheadedHFQSZZombie: DeadHFQSZ_NoHead { 
	Default {
 
	Mass 6;
	}
}
