CLASS pb_Rocket_Zombie: pb_Shotgun_Guy// Replaces ShotgunGuy
{ 
Default
{
	//DropItem "RocketAmmo";
	//SpawnID 1260;
	+NOTARGET;
	Painchance "Avoid", 0;
}

States
{
	Pain.Stun:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx ("StunElectrocute", random (-4, 4), random (-4, 4),  random (16, 32), 0, 0);
		MP0S G 1 A_Pain();
		MP0S GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		MP0S G 1 A_Pain();
		MP0S GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		MP0S G 1 A_Pain();
		MP0S GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		MP0S G 1 A_Pain();
		MP0S GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		MP0S G 1 A_Pain();
		MP0S GGGGGGGGGG 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		MP0S G 1 A_Pain();
	Goto See;
		
	Death.Shrink:
		TNT1 A 1 A_PlaySound("Shrink", 3);
/*		TNT1 A 0 A_SpawnItemEx ("RocketZombieShrinkFX1", 0, 0,  5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("RocketZombieShrinkFX2", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("RocketZombieShrinkFX3", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("RocketZombieShrinkFX4", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("RocketZombieShrinkFX5", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("RocketZombieShrinkFX6", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("RocketZombieShrinkFX7", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("LilRocketZombie", 1);*/
	stop;
	Spawn:
		TNT1 A 0;
		TNT1 A 0;
		MP0S B 1;
	Stand:
		//TNT1 A 0 A_SpawnItem ("LegTarget100", 10)
				MP0S AB 10 A_Look();
		Loop;
		
	See:
		//TNT1 A 0 A_JumpIfCloser(255, "Jihad")
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 20, 0, 0);
		//TNT1 A 0 A_TakeInventory("SKShotgunGuy", 1);
		MP0S AAAA 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
		MP0S BBBBCCCC 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
		MP0S DDDD 2 A_Chase();
	Loop;
		
	Missile:
		//TNT1 A 0 A_TakeInventory("SKShotgunGuy", 1);
		MP0S E 11 A_FaceTarget();
		MP0S E 11 A_FaceTarget();
		MP0S E 5 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 44, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("ZombieRocket", 44, 0, 0, 0);
		MP0S F 4 A_FaceTarget();
		MP0S E 20;
	Goto See;
		
	Possession:
		TNT1 A 0 A_SetInvulnerable();
		MP0S G 3;
		MP0S G 3 A_Pain();
 		TNT1 A 0 A_UnSetInvulnerable();
	Goto See;
		
		
	Pain:
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, 6);
		//TNT1 A 0 A_TakeInventory("SKShotgunGuy", 1);
		MP0S G 3;
		MP0S G 3 A_Pain();
	Goto See;
		TNT1 AAAAA 0;
		TNT1 A 0 A_Pain();
		ID11 H 8;
		ID11 S 35;
		TNT1 A 0 A_TakeInventory("IsDown", 1);
		ID11 T 10;
	Goto See;
		
		
	Death:
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
		TNT1 A 0 A_Jump(210, "Death.Kamikaze");
		TNT1 A 0 A_Jump(48, "Death.Arm");
	Death.MinorLeg:
		SPOS H 5 A_Scream();
		SPOS I 5;
		SPOS J 5 A_NoBlocking();
		SPOS K 5;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem ("DeadShotgunguy1", 1);
	Stop;
		
	Death.Down:
		SPOS J 5 A_NoBlocking();
		SPOS K 5;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem ("DeadShotgunguy1", 1);
	Stop;
		
	Death.Kamikaze:
		TNT1 A 0 A_SpawnItemEx("pb_suicide_Bomber", 0, 0, 3, 0, 0, 0, 0, SXF_NOCHECKPOSITION);
	stop;
		
	Death.Arm:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile ("XDeathArm2", 35, 0, random (0, 360), 2, random (0, 160));
		SPO5 A 9 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem ("DyingSergeant", 2);
	Stop;
}

}




CLASS ZombieRocket : pb_projectile_base
{
Default
{
	Speed 20;
	Damage 10;
	seesound "0SRFIRE";
	deathsound "explosion";
	+THRUGHOST;
}

States
{
	Spawn:
		TNT1 A 0;
		MISL A 0 A_PlaySound("RocketLauncherDistantFire",3);
		MISL A 1 A_PlaySound("weapons/rocketloop",4,1,1);
	Fly:
		MISL A 1 Bright;
		TNT1 A 0 A_SpawnItem("RocketFlare",-20,0);
		TNT1 A 0 a_spawnprojectile ("Explosion_Smoke", 2, 0, random (160, 210), 2, random (-30, 30));
		TNT1 A 0 A_SpawnItem ("ExplosionSmoke");
	Loop;
		
	Death:
		TNT1 A 0 A_StopSound(4);
		EXPL A 0 Radius_Quake (2, 54, 0, 15, 0);
		TNT1 A 0 A_SpawnItemEx ("NewRocketExploFX", 0, 0, 0);
		TNT1 A 0 a_spawnprojectile ("MetalShard1", 5, 0, random (0, 360), 2, random (30, 160));
		TNT1 A 0 a_spawnprojectile ("MetalShard1", 5, 0, random (0, 360), 2, random (30, 160));
		TNT1 A 0 a_spawnprojectile ("MetalShard1", 5, 0, random (0, 360), 2, random (30, 160));
		TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("ZombieRocketExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AA 0 a_spawnprojectile ("ExplosionParticle", 0, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAA 0 a_spawnprojectile ("ExplosionParticle", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAA 0 a_spawnprojectile ("ExplosionParticle", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 0 A_QuakeEx(1, 1, 1, 12, 0, 420, "", 0);
		
		TNT1 AAAAAAA 0 a_spawnprojectile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
		EXPL AAA 0 a_spawnprojectile ("CasingSmoke", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAA 1 a_spawnprojectile ("ExplosionSmoke", 2, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 3;
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 AAAAAAAAA 2 a_spawnprojectile ("CasingSmoke", 2, 0, random (0, 360), 2, random (0, 360));
	Stop;
}

}

CLASS ZombieRocketExplosion : ACTOR { 
	Default {
	+NOBLOCKMAP;
	+MISSILE;
	Damagetype "ExplosiveImpact";
	}
	States    {
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Explode(25,100, 0);
Stop;}}