CLASS pb_Cyber_Paladin : knight_base// replaces Hellknight
{ 
Default
{
	Tag "Paladin";
	Health 825;
	//SpawnID 2230;
	Radius 24;
	Height 56;
	Mass 800;
	Speed 8;
	PainChance 80;
	ProjectileKickBack 9001;
	Monster;
	+FloorClip;
	+DontHarmClass;
	+DontHarmSpecies;

	+AvoidMelee;
	damagefactor "Crush", 10.0;
	damagefactor "GibRemoving", 0.0;
	PainChance "Kick", 255;
	PainChance "Taunt", 0;
	PainChance "Extremepunches", 255;
	PainChance "Stun", 255;
	PainChance "Explosive", 255;
	PainChance 25;
	PainChance "Saw", 100;
	PainChance "Cut", 100;
	DamageFactor "CauseObjectsToSplash", 0.0;
	damagefactor "SSG", 0.75;
	damagefactor "Head", 0.9;
	damagefactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	damagefactor "TeleportRemover", 0.0;
	damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0; damagefactor "GreenBlood", 0.0;
	BloodType "Brutal_Blood", "BloodSPlatterReplacer", "AxeBlood";
	
	Obituary "%o played dodgeball with a paladin and lost.";
	HitObituary "A Paladin blew %o away.";
	
	SeeSound "Paladin/Sight";
	PainSound "Paladin/Pain";
	DeathSound "Paladin/Death";
	ActiveSound "Paladin/Active";
	Species "Noble";
	
	////DropItem "DemonStrengthRune", 7;
	////DropItem "RageSphere", 6;
	////DropItem "DoubleSphere", 5;
	////DropItem "ShieldSphere", 4;
	////DropItem "Demonpickup2", 90;
	////DropItem "Demonpickup", 196;
}
States
{ 
	Spawn:
 		TNT1 A 0;
		HPAL AB 10 A_Look;
	Stand:
		TNT1 A 0;
		HPAL B 5 A_Look;
	Loop;














	See:
		TNT1 A 0 {self.binvulnerable = false; self.bFRIGHTENED = false;}
		TNT1 A 0 A_JumpIfCloser(128, "SeePanic");
		HPAL AABB 3 A_Chase;
		TNT1 A 0 A_PlaySound("Paladin/Step");
		HPAL CCDD 3 A_Chase;
		TNT1 A 0 A_PlaySound("Paladin/Step");
	Goto See+1;

	SeeShield:
		HPAL EEFF 4 A_Chase;
		TNT1 A 0 A_PlaySound("Paladin/Step");
		HPAL GGHH 4 A_Chase;
		TNT1 A 0 A_PlaySound("Paladin/Step");
		TNT1 A 0 A_Jump(96, "See");
	Goto SeeShield;

	SeePanic: //Try to get some distance if the target is too close
		TNT1 A 0 {self.bFRIGHTENED = true;}
		HPAL AABB 3 A_Chase;
		TNT1 A 0 A_PlaySound("Paladin/Step");
		HPAL CCDD 3 A_Chase;
		TNT1 A 0 A_PlaySound("Paladin/Step");
		TNT1 A 0 A_JumpIfCloser(128, "SeePanic");
		TNT1 A 0 {self.bFRIGHTENED = false;}
	Goto See;

	Melee:
		TNT1 A 0 {self.binvulnerable = false; self.bFRIGHTENED = false;}
		HPAL MN 6 A_FaceTarget;
		HPAL O 6 A_CustomMeleeAttack(random(5, 10)*4, "Paladin/Melee", "Paladin/Swing", "ExplosiveImpact");
	Goto See;

	Missile:
		TNT1 A 0 {self.binvulnerable = false; self.bFRIGHTENED = false;}
		TNT1 A 0 A_JumpIfCloser(832, "Missile1");
	Goto Missile2;
	Missile1: //Grenade used if target is within 832 map units
		TNT1 A 0 A_Jump(32, "Missile2");//Use shield attack anyway
		HPAL I 5 A_FaceTarget;
		TNT1 A 0 A_JumpIfCloser(384, "MissileLow");//Don't lob the grenade if closer
		TNT1 A 0 A_Jump(128, "MissileRare");
		HPAL I 5 A_FaceTarget;//than 384 map units
		HPAL J 4 Bright a_spawnprojectile("PaladinGrenade", 24, 16, 0, CMF_OFFSETPITCH, 8);
		HPAL J 4 Bright A_FaceTarget;
		HPAL II 5 A_FaceTarget;
	Goto See;

	MissileRare:
		HPAL I 5 A_FaceTarget;//than 384 map units
		HPAL J 4 Bright a_spawnprojectile("PaladinGrenade", 24, 16, random(-1, 1), CMF_OFFSETPITCH, 8);
		HPAL J 4 Bright A_FaceTarget;
		HPAL II 3 A_FaceTarget;
		HPAL J 4 Bright a_spawnprojectile("PaladinGrenade", 24, 16, random(-3, 3), CMF_OFFSETPITCH, 8);
		HPAL J 4 Bright A_FaceTarget;
		HPAL II 3 A_FaceTarget;
		HPAL J 4 Bright a_spawnprojectile("PaladinGrenade", 24, 16, random(-5, 5), CMF_OFFSETPITCH, 8);
		HPAL J 4 Bright A_FaceTarget;
		HPAL II 3 A_FaceTarget;
	Goto See;

	MissileLow: //Low lob grenade for close targets
		HPAL I 5 A_FaceTarget;
		HPAL J 4 Bright a_spawnprojectile("PaladinGrenade", 24, 16, 0);
		HPAL J 4 Bright A_FaceTarget;
		HPAL II 5 A_FaceTarget;
	Goto See;

	Missile2: //Shield attack
	Pain.Taunt:
		HPAL K 4 A_FaceTarget;
		HPAL L 5 Bright a_spawnprojectile("PaladinBall",28,0,0,0);
		HPAL K 4 A_FaceTarget;
		HPAL L 5 Bright a_spawnprojectile("PaladinBall",28,0,0,0);
		HPAL K 4 A_FaceTarget;
		HPAL L 5 Bright a_spawnprojectile("PaladinBall",28,0,0,0);
		HPAL K 4 A_FaceTarget;
		HPAL L 5 Bright a_spawnprojectile("PaladinBall",28,0,0,0);
		HPAL K 4 A_FaceTarget;
		HPAL L 5 Bright a_spawnprojectile("PaladinBall",28,0,0,0);
		HPAL K 4 A_FaceTarget;
	Goto See;

	Pain:
		HPAL P 3 {self.bFRIGHTENED = false;}
		TNT1 A 0 A_JumpIfCloser(512, "ClosePain");
		HPAL P 3 A_Pain;
		TNT1 A 0 A_Jump(96, "See");
	shielded_pain:
		HPAL K 4 A_FaceTarget;
		tnt1 a 0 a_jumpif(random(0, 10) < 9, "shielded_pain");
		TNT1 A 0 A_Jump(180, "SeeShield");
		TNT1 A 0 {self.binvulnerable = false;}
	Goto See;
		
	Possession:
		TNT1 A 0 A_SetInvulnerable;
		HPAL P 3;
		HPAL P 3 A_Pain;
 		TNT1 A 0 A_UnSetInvulnerable;
	Goto See;
		
	ClosePain: //Less likely to raise shield when in grenading-range
		HPAL P 3 A_Pain;
		TNT1 A 0 A_Jump(184, "See");
		TNT1 A 0;
	shielded_close:
		HPAL K 4 A_FaceTarget;
		tnt1 a 0 a_jumpif(random(0, 10) < 9, "shielded_close");
		TNT1 A 0 A_Jump(24, "SeeShield");
		TNT1 A 0 A_UnSetInvulnerable;
	Goto See;
		
	Death.Decapitate:
		TNT1 A 0 a_spawnprojectile("XDeathCyberPaladinHead", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("Xdeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_Jump(162, 3);
		TNT1 A 0 A_SpawnItem("DyingCyberKnight1", 1);
	Stop;
		TNT1 A 0;
		CP8L A 6;
		CP8L BC 6;
		CP8L D 6;
		TNT1 A 0 A_PlaySound("master/walk", 9);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_NoBlocking;
		CP8L D -1;
	Stop;
		
	Death.Head:
		//TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		//TNT1 A 0 A_JumpIfInTargetInventory("HasCutingWeapon", 1, "Death.decaptate");
		TNT1 A 0 A_SpawnItemEx("PaladinShield", 0, 0, 25, 6, 0, 0, 60, SXF_SETMASTER|SXF_CLIENTSIDE);
		TNT1 A 0 A_PlaySound("misc/gibbed", 3);
		TNT1 AAAA 0 a_spawnprojectile("Xdeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("Brains2", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Brains4", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("Brains4", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Teeth", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 62, 0, random(0, 360), 2, random(50, 80));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPieceFast", random(55, 59), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPiece", 58, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 58, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 A_Jump(162, 3);
		TNT1 A 0 A_SpawnItem("DyingCyberKnight1", 1);
	Stop;
		TNT1 A 0;
		CP8L ABCD 6;
		TNT1 A 0 A_PlaySound("master/walk", 9);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_NoBlocking;
		CP8L D -1;
	Stop;
		
	XDeath:
		//TNT1 A 0 A_JumpIfInTargetInventory("SSGSelected", 1, "Death.SSG");
		TNT1 A 0
		{
			for(int i = 0; i < 2; i++)
			{
				A_PlaySound("FAREXPL");
				A_PlaySound("Explosion", 1);
				a_spawnprojectile("CasingSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
				A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
			}
		}
		HPLX A 0 A_PlaySound("Paladin/XDeath",1);
		HPLX B 0 Bright A_SpawnItemEx("PaladinShield", 0, 0, 25, 6, 0, 0, 60, SXF_SETMASTER|SXF_CLIENTSIDE);
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		EXPL A 0 Radius_Quake(3, 60, 0, 11, 0);
		TNT1 A 0 A_PlaySound("caco/shotx",2);
		TNT1 AAAA 0 a_spawnprojectile("XDeathBurnedMeat", 42, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("CyberNobleXDeath", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathCyberPaladinHead", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0;//A_Scream
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0;
	Stop;
		
	Death.Landmine:
	Death.SuperKick:
	Death.ExplosiveImpact:
	Death.ExtremePunches:
		TNT1 A 0 A_SpawnItemEx("PaladinShield", 0, 0, 25, 6, 0, 0, 60, SXF_SETMASTER|SXF_CLIENTSIDE);
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 ThrustThingZ(0,35,0,1);
		TNT1 A 0 a_spawnprojectile("XDeathCyberKnightArm", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathCyberKnightLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("xdeath3", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 A_Jump(255, "Death.ExplosiveImpact1");
		
	Death.ExplosiveImpact1:
		TNT1 A 0 A_StopSound(5);
		CP9L A  8 A_Scream;
		CP9L B  8 A_NoBlocking;
		CP9L CCCCCC  8 A_CheckFloor("Land1");
	Land1:
		TNT1 A 0 A_StopSound(5);
		TNT1 A 0 A_PlaySound("master/walk", 9);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		CP9L D -1;
	Stop;
		
	Death.SSG:
	Death.QuadBlast:
		TNT1 A 0 A_SpawnItemEx("PaladinShield", 0, 0, 25, 6, 0, 0, 60, SXF_SETMASTER|SXF_CLIENTSIDE);
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Jump(12, "Death.Blast");
		TNT1 A 0 a_spawnprojectile("XDeathCyberKnightTorso", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathCyberKnightArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathCyberPaladinHead", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAAA 0 a_spawnprojectile("Xdeath3", 52, 0, random(0, 360), 2, random(0, 160));
		C92D AAAA 2 a_spawnprojectile("Brutal_LiquidBlood2", 45, 2, random(0, 360), 2, random(60, 120));
		C92D BCD 6;
		C92D D -1;
	Stop;
		
	Death.Blast:
		TNT1 A 0 A_Jump(96, "Blast2");
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx("PaladinShield", 0, 0, 25, 6, 0, 0, 60, SXF_SETMASTER|SXF_CLIENTSIDE);
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeathCyberKnightTorso", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathCyberKnightArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathCyberPaladinHead", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAAA 0 a_spawnprojectile("Xdeath3", 52, 0, random(0, 360), 2, random(0, 160));
		CP5L EEEE 2 a_spawnprojectile("Brutal_LiquidBlood2", 45, 2, random(0, 360), 2, random(60, 120));
		CP5L FGH 6;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		CP5L H -1;
	Stop;
		
	Blast2:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx("PaladinShield", 0, 0, 25, 6, 0, 0, 60, SXF_SETMASTER|SXF_CLIENTSIDE);
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 39, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AA 0 a_spawnprojectile("Xdeath3", 40, 0, random(0, 360), 2, random(0, 160));
		CP9L EEE 2 a_spawnprojectile("Brutal_LiquidBlood2", 45, 2, random(0, 360), 2, random(60, 120));
		CP9L FGH 6;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		CP9L H -1;
	Stop;
		
	Death.Saw:
	Death.Cut:
	Death.Tear:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx("PaladinShield", 0, 0, 25, 6, 0, 0, 60, SXF_SETMASTER|SXF_CLIENTSIDE);
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeathCyberPaladinRipped", 48, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 57, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAA 0 a_spawnprojectile("Instestin", 35, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathStomach", 39, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("Xdeath3", 52, 0, random(0, 360), 2, random(0, 160));
		CP5L EEEE 2 a_spawnprojectile("Brutal_LiquidBlood2", 45, 2, random(0, 360), 2, random(60, 120));
		CP5L FGH 6;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		CP5L H -1;
	Stop;
		
	Death.Shotgun:
		TNT1 A 0 A_StopSound(5);
		TNT1 A 0 A_JumpIfCloser(200, "Death.Blast");
	Goto Death;


	Death:
		TNT1 A 0 A_Jump(158, "Death1", "Death2");
		HPAL Q 7 A_Scream;
		HPAL R 7 A_SpawnItemEx("PaladinShield", 0, 0, 25, 6, 0, 0, 60, SXF_SETMASTER|SXF_CLIENTSIDE);
		HPAL S 7;
		HPAL T 7 A_NoBlocking;
		TNT1 A 0 A_PlaySound("master/walk", 9);
		HPAL UV 7;
		HPAL W -1;
	Stop;

	Death1:
		TNT1 A 0 {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 A_SpawnItemEx("PaladinShield", 0, 0, 25, 6, 0, 0, 60, SXF_SETMASTER|SXF_CLIENTSIDE);
		CP5L A 7 A_Scream;
		CP5L BC 7;
		CP5L D 7 A_BossDeath;
		TNT1 A 0 A_PlaySound("master/walk", 9);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_NoBlocking;
		CP5L D -1;
	Stop;

	Death2:
		TNT1 A 0 {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 A_SpawnItemEx("PaladinShield", 0, 0, 25, 6, 0, 0, 60, SXF_SETMASTER|SXF_CLIENTSIDE);
		CP6L A 7 A_Scream;
		CP6L BC 7;
		CP6L D 7 A_BossDeath;
		TNT1 A 0 A_PlaySound("master/walk", 9);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_NoBlocking;
		CP6L E -1;
	Stop;
		
	Death.Fatality:
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("CyberPaladinFatality1", 1);
		TNT1 A 1 A_BossDeath;
	Stop;
		
	Raise: 
		HPAL W 7 A_KillChildren;
		HPAL VUTSRQ 7;
	Goto See;
	} 
}
