// --------------------------------------------------------------------------
// Rocket Launcher
// --------------------------------------------------------------------------
CLASS pb_Rocket_Launcher : weapon_slot_5_proto_class
{
protected bool laser_guiding;
protected int hold_rocket_amount;

Default
{
	Weapon.SlotNumber 5;
	Weapon.SelectionOrder 2500;
	Weapon.slotpriority 155;

	Damage 20;
	Weapon.AmmoUse1 0;
	Weapon.AmmoUse2 0;
	Weapon.AmmoGive2 0;
	Weapon.AmmoGive1 6;
	Weapon.AmmoType1 "pb_rocket_ammo";
	Weapon.AmmoType2 "RocketRounds";
	Inventory.PickupSound "misc/rockboxa";
	+WEAPON.NOAUTOAIM;
	+WEAPON.EXPLOSIVE;
	+WEAPON.NOALERT;
	Inventory.PickupMessage "You got the UAC Guided Rocket Launcher!(Slot 5)";
	Tag "Rocket Launcher";
}

States
{
	Spawn:
		LAUN A -1;
	Stop;
	
	Select:
		TNT1 A 0 A_Overlay(-10, "FirstPersonLegsStand");
		TNT1 A 1 A_Raise(90);
	Wait;

	Ready:
		TNT1 A 0 A_PlaySound("RLANDRAW");
		MISG EDCB 1;
		MISG A 1;
	ready_loop:
		MISG A 1 a_weaponready(WRF_allowreload);
	loop;
		
	LaserReady:
		TNT1 A 0 A_PlaySound("RLANDRAW");
		M2SG ABCD 1;
		TNT1 A 0 A_FireBullets(0,0,1,0,"GreenLaserDot",FBF_NOFLASH|FBF_NORANDOMPUFFZ);
		M2SG A 1;
	SeriouslyLaserReady:
		TNT1 A 0 A_FireBullets(0,0,1,0,"GreenLaserDot",FBF_NOFLASH|FBF_NORANDOMPUFFZ);
		M2SG A 1 a_weaponready(WRF_allowreload);
		TNT1 A 0 A_FireBullets(0,0,1,0,"GreenLaserDot",FBF_NOFLASH|FBF_NORANDOMPUFFZ);
	loop;

	Fire:
		TNT1 A 0 A_WeaponOffset(0,32);
		TNT1 A 0 A_JumpIfInventory("RocketRounds",1,1);
	Goto Reload;
		TNT1 A 0
		{
			A_AlertMonsters();
			a_fireprojectile("Red_FlareSpawn",-5,0,0,0);
			A_PlaySound("0SRFIRE", 7);
			a_fireprojectile("Alerter");
			A_ZoomFactor(0.985);
		}
		MISF A 1 BRIGHT
		{
			a_fireprojectile("RocketGlassBreaker", 0, 1, 0, -6);
			a_fireprojectile("pb_rocket", 0, 1, 0, -5);
			A_SetPitch(-3.0 + pitch);
			A_ZoomFactor(0.980);
			A_Takeinventory("RocketRounds",1);
			A_QuakeEx(4, 4, 4, 6, 0, 64, "", 0);
		}
		MISF BCD 1 BRIGHT A_SetPitch(1.0 + pitch);
		TNT1 A 0 A_ZoomFactor(0.99);
		MISF E 3 A_ZoomFactor(1.0);
		MISF F 6 A_PlaySound("RLCYC", 5);
		MISG A 3;
		TNT1 A 0 A_ReFire("fire");
	Goto ready_loop;












































	Deselect:
		MISG BCDE 1;
		TNT1 A 0 A_Lower(90);
	Wait;
		
	DeselectLaserGuided:
		M2SG BCDE 1;
		TNT1 A 0 A_Lower(90);
	Wait;






























	Steady:
		TNT1 A 1;
		Goto Ready;
		

		
		
	WeaponSpecial:
		////TNT1 A 0 A_JumpIfInventory("LaserGuidedSystemActivated",1,"DeactivateLaserGuided");
		TNT1 A 0 A_Print("Laser Guided System Activated");
		TNT1 A 0 A_PlaySound("RLSPCL2", 1);
		MISS ABCDEFGHIJ 1;
		TNT1 A 0 A_PlaySound("RLSPCL1");
		MISS JKLMN 2;
	Goto LaserReady+8;
		
	DeactivateLaserGuided:
		TNT1 A 0 A_Print("Laser Guided System Deactivated");
		TNT1 A 0 A_PlaySound("RLSPCL1");
		MISS NMLKJ 2;
		TNT1 A 0 A_PlaySound("RLSPCL3", 1);
		MISS IHGFEDCBA 1;
	Goto ready_loop+8;
		
		

		

		

		
	AmmoChecker:
		TNT1 A 0 A_JumpIfInventory("RocketRounds",1,"AltHold");
		//TNT1 A 0 A_JumpIfInventory("AltFireRocketCounter",5,"Fire3Rocket");
		//TNT1 A 0 A_JumpIfInventory("AltFireRocketCounter",3,"Fire2Rocket");
		//TNT1 A 0 A_JumpIfInventory("AltFireRocketCounter",1,"Fire1Rocket");
		Goto FireMultipleRockets;
	AltFire:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("RocketRounds",1,2);
		TNT1 A 0 A_JumpIfInventory("pb_rocket_ammo",1,2);
		Goto Reload;
		TNT1 AAA 0;
		//TNT1 A 0 A_JumpIfInventory("LaserGuidedSystemActivated", 1, "GuidedAltFire");
		TNT1 A 0 A_JumpIfInventory("RocketRounds",1,2);
		Goto Reload;
	AltHold:
		TNT1 AAA 0;
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("RocketRounds",1,2);
		Goto Reload;
		TNT1 AAAA 0;
		//TNT1 A 0 A_JumpIfInventory("LaserGuidedSystemActivated", 1, "GuidedAltHold");
		TNT1 A 0 A_Takeinventory("RocketRounds",1);
		MISG A 1;
		//TNT1 A 0 A_JumpIfInventory("AltFireRocketCounter",5,"Fire3Rocket");
		TNT1 A 0 A_JumpIfInventory("RocketRounds",1, 2);
	Goto FireMultipleRockets;
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 A_AlertMonsters;
		MISG A 2;
		MISF F 6 A_PlaySound("RLCYC", 4);
		MISG A 2;
		TNT1 A 0 A_ReFire("AmmoChecker");
	FireMultipleRockets:
		//TNT1 A 0 A_JumpIfInventory("AltFireRocketCounter",5,"Fire3Rocket");
		//TNT1 A 0 A_JumpIfInventory("AltFireRocketCounter",3,"Fire2Rocket");
		//TNT1 A 0 A_JumpIfInventory("AltFireRocketCounter",1,"Fire1Rocket");
		//TNT1 A 0;
	Goto ready_loop;
		
	Fire1Rocket:
		//TNT1 A 0 A_TakeInventory("AltFireRocketCounter", 6);
		TNT1 A 0 a_fireprojectile("Red_FlareSpawn",-5,0,0,0);
		TNT1 A 0 A_PlaySound("0SRFIRE", 3);
		TNT1 A 0 BRIGHT a_fireprojectile("Alerter");
		TNT1 A 0 A_ZoomFactor(0.98);
		MISF A 1 BRIGHT a_fireprojectile("RocketGlassBreaker", 0, 1, 0, -6);
		MISF A 0 BRIGHT a_fireprojectile("Rocket", random(1,1), 1, 0, -5);
		TNT1 A 0 A_QuakeEx(4, 4, 4, 6, 0, 64, "", 0);
 		MISF BCD 1 BRIGHT;
		TNT1 A 0 A_ZoomFactor(0.99);
		MISF E 3;
		TNT1 A 0 A_ZoomFactor(1.00);
		MISF F 6 A_PlaySound("RLCYC", 5);
		MISG A 3;
		Goto ready_loop;
		
	Fire2Rocket:
		//TNT1 A 0 A_TakeInventory("AltFireRocketCounter", 6);
		TNT1 A 0 a_fireprojectile("Red_FlareSpawn",-5,0,0,0);
		TNT1 A 0 A_PlaySound("RLSHOT2", 3);
		TNT1 A 0 BRIGHT a_fireprojectile("Alerter");
		TNT1 A 0 A_ZoomFactor(0.98);
		MISF A 1 BRIGHT a_fireprojectile("RocketGlassBreaker", 0, 1, 0, -6);
		MISF A 0 BRIGHT a_fireprojectile("Rocket", random(3,4), 1, 0, -5);
		MISF A 0 BRIGHT a_fireprojectile("Rocket", random(-4,-3), 1, 0, -5);
		TNT1 A 0 A_QuakeEx(4, 4, 4, 6, 0, 64, "", 0);
 		MISF BCD 1 BRIGHT;
		TNT1 A 0 A_ZoomFactor(0.99);
		MISF E 3;
		TNT1 A 0 A_ZoomFactor(1.00);
		MISF F 6 A_PlaySound("RLCYC", 5);
		MISG A 3;
		Goto ready_loop;
		
	Fire3Rocket:
		//TNT1 A 0 A_TakeInventory("AltFireRocketCounter", 6);
		TNT1 A 0 a_fireprojectile("Red_FlareSpawn",-5,0,0,0);
		TNT1 A 0 A_PlaySound("RLSHOT2", 3);
		TNT1 A 0 a_fireprojectile("Alerter");
		TNT1 A 0 A_ZoomFactor(0.98);
		MISF A 1 BRIGHT a_fireprojectile("RocketGlassBreaker", 0, 1, 0, -6);
		MISF A 0 a_fireprojectile("Rocket", 0, 1, 0, -5);
		MISF A 0 a_fireprojectile("Rocket", random(5,6), 1, 0, -5);
		MISF A 0 a_fireprojectile("Rocket", random(-5,-6), 1, 0, -5);
			TNT1 A 0 A_QuakeEx(4, 4, 4, 6, 0, 64, "", 0);
 		MISF BCD 1 BRIGHT;
		TNT1 A 0 A_ZoomFactor(0.99);
		MISF E 3;
		TNT1 A 0 A_ZoomFactor(1.00);
		MISF F 6 A_PlaySound("RLCYC", 5);
		MISG A 3;
		Goto ready_loop;
		
	GuidedAmmoChecker:
		TNT1 A 0 A_JumpIfInventory("RocketRounds",1,"GuidedAltHold");
		//TNT1 A 0 A_JumpIfInventory("AltFireRocketCounter",5,"GuidedFire3Rocket");
	//	TNT1 A 0 A_JumpIfInventory("AltFireRocketCounter",3,"GuidedFire2Rocket");
		//TNT1 A 0 A_JumpIfInventory("AltFireRocketCounter",1,"GuidedFire1Rocket");
		Goto FireMultipleGuidedRockets;
	GuidedAltFire:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("RocketRounds",1,3);
		Goto Reload;
	GuidedAltHold:
		TNT1 AAA 0;
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("RocketRounds",1,2);
		Goto Reload;
		TNT1 AAA 0;
		TNT1 A 0 A_Takeinventory("RocketRounds",1);
		//M2SG A 1 A_GiveInventory("GuidedAltFireRocketCounter", 2);
		//TNT1 A 0 A_JumpIfInventory("GuidedAltFireRocketCounter",5,"GuidedFire3Rocket");
		TNT1 A 0 A_JumpIfInventory("RocketRounds",1, 2);
		Goto FireMultipleGuidedRockets;
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 A_AlertMonsters;
		M2SG A 2;
		M2SF J 6 A_PlaySound("RLCYC", 4);
		MISG A 2;
		TNT1 A 0 A_ReFire("GuidedAmmoChecker");
	FireMultipleGuidedRockets:
		//TNT1 A 0 A_JumpIfInventory("GuidedAltFireRocketCounter",5,"GuidedFire3Rocket");
		//TNT1 A 0 A_JumpIfInventory("GuidedAltFireRocketCounter",3,"GuidedFire2Rocket");
		//TNT1 A 0 A_JumpIfInventory("GuidedAltFireRocketCounter",1,"GuidedFire1Rocket");
		TNT1 A 0;
		Goto ready_loop;
		

		
	Reload:
		//TNT1 A 0 A_JumpIfInventory("LaserGuidedSystemActivated", 1, "LaserGuidedReload");
		MISG A 1 A_WeaponReady;
		TNT1 A 0 A_JumpIfInventory("RocketRounds",6,55);
		TNT1 A 0 A_JumpIfInventory("pb_rocket_ammo",1,3);
		TNT1 A 0;//A_JumpIfInventory("LaserGuidedSystemActivated", 1, "SeriouslyLaserReady")
		Goto Ready+15;
		TNT1 AAAA 0;
		TNT1 A 0 A_PlaySound("ReloadRL");
		MISR ABCDE 2;
		TNT1 A 0 a_fireprojectile("RocketCaseSpawn",-30,0,-4,-4);
		MISR EFGHIJKLM 2;
		TNT1 A 0 A_PlaySound("RKTSLAP");
		MISR NNN 2;
		TNT1 AAAAA 0;
		MISR OPQ 1;
		MISG A 1 A_PlaySound("RLCYC");
		MISF F 5;
		MISG A 1;
		
		TNT1 AAAAAA 0;
		TNT1 A 0 A_JumpIfInventory("RocketRounds",6,15);
		TNT1 A 0 A_JumpIfInventory("pb_rocket_ammo",1,3);
		Goto Ready+6;
		TNT1 AAAAAA 0;
		TNT1 A 0 A_Giveinventory("RocketRounds",1);
		TNT1 A 0 A_Takeinventory("pb_rocket_ammo",1);
		Goto Reload+44;
		
		TNT1 AAAAAAAAAA 0;
		
		MISG A 1 A_Refire;
		Goto ready_loop;

	LaserGuidedReload:
		M2SG A 1 A_WeaponReady;
		TNT1 A 0 A_JumpIfInventory("RocketRounds",6,55);
		TNT1 A 0 A_JumpIfInventory("pb_rocket_ammo",1,3);
		TNT1 A 0;//A_JumpIfInventory("LaserGuidedSystemActivated", 1, "SeriouslyLaserReady")
		Goto SeriouslyLaserReady+15;
		TNT1 AAAA 0;
		TNT1 A 0 A_PlaySound("ReloadRL");
		M2SR ABCDE 2;
		TNT1 A 0 a_fireprojectile("RocketCaseSpawn",-30,0,-4,-4);
		M2SR EFGHIJKLM 2;
		TNT1 A 0 A_PlaySound("RKTSLAP");
		M2SR NNN 2;
		TNT1 AAAAA 0;
		M2SR OPQ 2;
		M2SG A 1;
		M2SF J 5 A_PlaySound("RLCYC");
		M2SG A 1;
		
		TNT1 AAAAAA 0;
		TNT1 A 0 A_JumpIfInventory("RocketRounds",6,15);
		TNT1 A 0 A_JumpIfInventory("pb_rocket_ammo",1,3);
		Goto SeriouslyLaserReady+6;
		TNT1 AAAAAA 0;
		TNT1 A 0 A_Giveinventory("RocketRounds",1);
		TNT1 A 0 A_Takeinventory("pb_rocket_ammo",1);
		Goto LaserGuidedReload+44;
		
		TNT1 AAAAAAAAAA 0;
		M2SG A 1 A_Refire;
		Goto SeriouslyLaserReady;
		
		
	FlashKicking:
		//TNT1 A 0 A_JumpIfInventory("LaserGuidedSystemActivated", 1, "LaserGuidedFlashKicking");
		MISG W 1;
		MISG X 1;
		MISG Y 1;
		MISG Y 3;
		MISG Z 3;
		MISG Y 3;
		MISG X 1;
		MISG W 1;
		MISG A 1;
		MISG AAA 1;
		Stop;
		
	LaserGuidedFlashKicking:
		M2SG W 1;
		M2SG X 1;
		M2SG Y 1;
		M2SG Y 3;
		M2SG Z 3;
		M2SG Y 3;
		M2SG X 1;
		M2SG W 1;
		M2SG A 1;
		M2SG AAA 1;
		Stop;
		
	FlashAirKicking:
		//TNT1 A 0 A_JumpIfInventory("LaserGuidedSystemActivated", 1, "LaserGuidedFlashAirKicking");
		MISG W 1;
		MISG X 1;
		MISG Y 1;
		MISG Y 3;
		MISG Z 3;
		MISG Y 3;
		MISG X 1;
		MISG W 1;
		MISG A 1;
		MISG AAAA 1;
		Stop;
		
	LaserGuidedFlashAirKicking:
		M2SG W 1;
		M2SG X 1;
		M2SG Y 1;
		M2SG Y 3;
		M2SG Z 3;
		M2SG Y 3;
		M2SG X 1;
		M2SG W 1;
		M2SG A 1;
		M2SG AAAA 1;
		Stop;
		
	FlashSlideKicking:
		//TNT1 A 0 A_JumpIfInventory("LaserGuidedSystemActivated", 1, "LaserGuidedFlashSlideKicking");
		MISG WX 2;
		MISG YYYYZZZZZYY 2 ;
		Stop;
		
	LaserGuidedFlashSlideKicking:
		M2SG WX 2;
		M2SG YYYYZZZZZYY 2 ;
		Stop;
		
	FlashSlideKickingStop:
		//TNT1 A 0 A_JumpIfInventory("LaserGuidedSystemActivated", 1, "LaserGuidedFlashSlideKickingStop");
		MISG YXWWA 1;
		MISG A 1;
		Stop;
		
	LaserGuidedFlashSlideKickingStop:
		M2SG YXWWA 1;
		M2SG A 1;
		Stop;
		
	FlashPunching:
		//TNT1 A 0 A_JumpIfInventory("LaserGuidedSystemActivated", 1, "LaserGuidedFlashPunching");
		MISG W 1;
		MISG X 1;
		MISG Y 1;
		MISG Y 3;
		MISG Z 3;
		MISG Y 3;
		MISG X 1;
		MISG W 1;
		MISG A 1;
		MISG AAA 1;
		Stop;
		
	LaserGuidedFlashPunching:
		M2SG W 1;
		M2SG X 1;
		M2SG Y 1;
		M2SG Y 3;
		M2SG Z 3;
		M2SG Y 3;
		M2SG X 1;
		M2SG W 1;
		M2SG A 1;
		M2SG AAA 1;
		Stop;
	}
}

CLASS RocketRounds : Ammo { 
	Default {
	
	Inventory.Amount 0;
	Inventory.MaxAmount 6;
	Ammo.BackpackAmount 0;
	Ammo.BackpackMaxAmount 6;
	Inventory.Icon "LAUNA0";
	}
}


CLASS GreenLaserDot: pb_projectile_base
{ 
Default
{
	Decal "None";
	Mass 0;
	Scale 0.3;
	Radius 1;
	Height 2;
	+NOBLOCKMAP;
	+NOGRAVITY;
	+BLOODLESSIMPACT;
	+ALWAYSPUFF;
	+PUFFONACTORS;
	+DONTSPLASH;
	+FORCEXYBILLBOARD;
	Renderstyle "Add";
	Alpha 0.75;
}

States
{
	Spawn:
		LEYS G 1 BRIGHT;
	Death:
		LEYS G 1 A_AlertMonsters(500);
		LEYS G 1 BRIGHT;
	Stop;
}

}

CLASS RocketPuff : ACTOR { 
	Default {
	
	radius 1;
	height 1;
	Scale 0.3;
	+SKYEXPLODE;
	+GHOST;
	+NOBLOOD;
	-FRIENDLY;
	+ALWAYSPUFF;
	+PUFFONACTORS;
	+NOCLIP;
	+NOGRAVITY;
	-NOBLOCKMAP;
	+SHOOTABLE;
	+BLOODLESSIMPACT;
	+CLIENTSIDEONLY;
	RenderStyle "Add";
	}
	States
	{
	Spawn:
		TNT1 A 0;
		LEYS G 1 BRIGHT;
 		TNT1 A 0;
		TNT1 A 1 A_Die;
		Goto Death;
	Death:
		TNT1 A 1;
		Stop;
	}
}



CLASS pb_rocket : pb_projectile_base { 
Default {
	Radius 6;
	Height 6;
	Speed 75;
	Damage 45;
	DamageType "Explosive";
	Projectile;
	+SKYEXPLODE;
	+THRUSPECIES;
	+THRUGHOST;
	+ROCKETTRAIL;
	+SEEKERMISSILE;
	+ALLOWPARTICLES;
	+EXTREMEDEATH;
	+BLOODSPLATTER;
	+FLOORCLIP;
	+DONTGIB;
	Species "Marine";
	+THRUSPECIES;
	+MTHRUSPECIES;
	SeeSound "weapons/RLL";
	DeathSound "Explosion";
	Obituary "$OB_MPROCKET";
	Decal "Scorch";
	Species "Rocket";
	Obituary "%o was hunted down by %k's Laser-Guided Rocket.";
}
States
{
	Spawn:
		MISL A 1 A_SeekerMissile(0,24,SMF_PRECISE);
		TNT1 A 0 A_PlaySound("weapons/rocketloop",6,1,1);
		TNT1 A 0 A_SpawnItem("RocketFlare",-20,0);
		TNT1 A 0 a_spawnprojectile("Explosion_Smoke", 2, 0, random(160, 210), 2, random(-30, 30));
		TNT1 A 0 A_SpawnItem("ExplosionSmoke");
 	Loop;

	Death:
 		TNT1 A 0 A_Stopsound(6);
		EXPL A 0 Radius_Quake(3, 16, 0, 15, 0);
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -30);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		tnt1 a 0 A_Explode(120,150, damagetype:"ExplosiveImpact");
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 
		{
			pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");
		}
		TNT1 AAAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		EXPL AAAAA 0 a_spawnprojectile("explosionsmoke", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 1;
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 A 20;
	Stop;
	}
}
