
CLASS VolcabusBall : ACTOR { 
Default
{
	Radius 6;
	Height 6;
	Speed 27;
	Fastspeed 32;
	DamageFunction(random(30,40));
	Projectile;
	Scale 0.85;
	+FORCEXYBILLBOARD;
	+THRUGHOST;
	RenderStyle "Translucent";
	DamageType "ExplosiveImpact";
	ExplosionRadius 150;
	ExplosionDamage 8;
	Alpha 1;
	Decal "Scorch";
	DeathSound "unmbal";
	SeeSound "unmalt";
}
States
{
	Spawn:
	TNT1 A 0;
 	
	Spawn1:
	TNT1 A 0 A_Playsound("UNMFLY1", 1, 1, 1);
	Fly:
		S4BA A 2 BRIGHT A_Weave(5,5,0.2,0.2);
		TNT1 A 0 A_SpawnItem("Red_Flare22", 15);
		tnt1 a 0 A_SpawnItem("RedLightningTrial_Small", 25);
		S4BA B 2 BRIGHT A_Weave(5,5,0.2,0.2);
		TNT1 A 0 A_SpawnItem("Red_Flare22", 15);
		tnt1 a 0 A_SpawnItem("RedLightningTrial_Small", 25);
	Loop;
	
	SpawnCheap:
	S4BA AB 2 BRIGHT A_SpawnItem("Red_Flare22");
	Loop;
	
	Death:
	TNT1 A 0 {self.bNOGRAVITY = false;}
	TNT1 A 0 A_Explode(14, 55, 0);
	Goto ExplosionEffect;
	
	ExplosionEffect:
		TNT1 A 0 A_StopSound(1);
		TNT1 A 0 A_SpawnItem("HellRifle_Puff2",0);
		TNT1 AAAA 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 BRIGHT A_SpawnItem("Red_Flare22");
		TNT1 AAA 0 A_SpawnItemEx("bfg_4_laser_train", random(19,-19), random(19,-19), random(19,-19), 0, 0, 0, 0, 128, 0);
		TNT1 A 0 A_SpawnItemEx("bfg_4_laser_explode",0,0,0,0,0,0,0,128,0);
		HEFX CDEEFGH 1 bright;
	Stop;
}
}
