//===========================================================================
//
// Demon
//
//===========================================================================

CLASS pb_Mech_Demon: proto_pinky// Replaces Demon
{ 
Default
{
	GibHealth 35;
	//Radius 30
	Health 350;
	Scale 1.1;
	Height 56;
	Radius 22;
	Mass 400;
	Speed 12;
	FastSpeed 13;//yes, his fast speed is slower because it would make him sanic fast if it was default. NO IT'S NOT.
	//SpawnID 1530;
	PainChance "Saw", 200;
	PainChance "Cut", 200;
	PainChance "Kick", 255;
	PainChance "Stun", 255;
	damagefactor "Crush", 10.0;
	damagefactor "SSG", 7.00;
	damagefactor "Kick", 0.7;
	damagefactor "Fatality", 0.7;
	damagefactor "SuperPunch", 0.7;
	//damagefactor "Melee", 0.7
	damagefactor "Avoid", 0.0;
	damagefactor "GibRemoving", 0.0;
	damagefactor "killme", 0.0;
	damagefactor "TeleportRemover", 0.0;
	DamageFactor "CauseObjectsToSplash", 0.0;
	+CANPASS;
	Monster;
	damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0; damagefactor "GreenBlood", 0.0;
	damagefactor "Shrapnel", 0.3;
	+FLOORCLIP;
	
	SeeSound "demon/sight";
	AttackSound "demon/melee";
	PainSound "demon/pain";
	DeathSound "demon/death";
	ActiveSound "demon/active";
	BloodType "pb_blood", "BloodSPlatterReplacer", "AxeBlood";
	DamageType "Eat";
	MaxStepHeight 32;
	MaxDropOffHeight 32;
	
	////DropItem "DemonStrengthRune", 4;
	////DropItem "Demonpickup", 150;
	////DropItem "Demonpickup", 100;
}

States
{
	Death.Shrink:
		TNT1 A 1 A_PlaySound("Shrink", 3);
/*		TNT1 A 0 A_SpawnItemEx("MechPinkyShrinkFX1", 0, 0,  5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("MechPinkyShrinkFX2", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("MechPinkyShrinkFX3", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("MechPinkyShrinkFX4", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("MechPinkyShrinkFX5", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("MechPinkyShrinkFX6", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("MechPinkyShrinkFX7", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("LilMechPinky", 1);*/
	stop;
		
	Spawn:
 		TNT1 A 0;
	watch:	
		SRG2 A 10 A_Look;
	loop;
		
	Forget:
		TNT1 A 0 A_ClearTarget;
		TNT1 A 0 A_TakeInventory("EnemyMemory", 15);
	SearchPlayer:
	Idle:
		SRG2 A 10 A_Look;
		TNT1 A 0 A_SetAngle(angle + randompick(40, -40) );
		SRG2 AA 10 A_Look;
		SRG2 AA 0 A_Wander;
		SRG2 AABBCCDD 2
		{
			A_Look();
			A_Wander();
		}
	loop;
		
	See:
		//TNT1 A 0 A_JumpIfInventory("ZombieManFatality", 1, "FatalityZombieman");
		//TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
		//TNT1 A 0 A_JumpIfInventory("ImpFatality", 1, "FatalityImp");
		//TNT1 A 0 A_JumpIfInventory("ComandoFatality", 1, "FatalityComando");
		
		//  TNT1 A 0 A_JumpIfInventory("EatMe", 1, "Eat")
		tnt1 a 0 pb_monster_memory();
		SRG2 AA 2 A_Chase;
		TNT1 A 0 A_Playsound("pinky/step", 4);
		SRG2 BB 2 A_Chase;
		TNT1 A 0 A_SpawnItemEx("FootStep6", 0, 0, 30, 0, 0);
		SRG2 CC 2 A_Chase;
		TNT1 A 0 A_Playsound("pinky/step", 5);
		SRG2 DD 2 A_Chase;
	Loop;
		
		
		
	Melee:
		//TNT1 A 0 A_JumpIfInTargetInventory("ComeEatMeDemon", 1, "MeleeDown");
		SRG2 EF 6 A_FaceTarget;
		TNT1 AAA 0 a_spawnprojectile("DemonAttack",40,0,0,0);
		SRG2 G 12 a_spawnprojectile("DemonAttack",5,0,0,0);
		//TNT1 A 0 A_JumpIfInventory("ZombieManFatality", 1, "FatalityZombieman");
		//TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
		//TNT1 A 0 A_JumpIfInventory("ImpFatality", 1, "FatalityImp");
		//TNT1 A 0 A_JumpIfInventory("ComandoFatality", 1, "FatalityComando");
		//TNT1 A 0 A_JumpIfInventory("EatMe", 1, "Eat")
	Goto See;
		
	MeleeDown:
		PDEV AB 6 A_FaceTarget;
		PDEV C 12 a_spawnprojectile("DemonAttack",5,0,0,0);
		//TNT1 A 0 A_JumpIfInventory("ZombieManFatality", 1, "FatalityZombieman");
		//TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
		//TNT1 A 0 A_JumpIfInventory("ImpFatality", 1, "FatalityImp");
		//TNT1 A 0 A_JumpIfInventory("ComandoFatality", 1, "FatalityComando");
		TNT1 A 0 A_Jump(32, "EatFast");
	Goto See;
		
	Pain:
		SRG2 H 2;
		SRG2 H 2 A_Pain;
	Goto See;
		
	Possession:
		TNT1 A 0 A_SetInvulnerable;
		SRG2 H 3;
		SRG2 H 3 A_Pain;
 		TNT1 A 0 A_UnSetInvulnerable;
	Goto See;
		
	Pain.Stun:
		SRG2 H 1 A_Pain;
		SRG2 HHHHHHHHHH 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		tnt1 a 0 a_jumpif(random(0, 10) < 7, "Pain.Stun");
	Goto See;
		
	Pain.Shotgun:
		TNT1 A 0 A_Pain;
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil(2);
		SRG2 H 4;
	Goto See;
		
	Pain.Kick:
	Pain.ExtremePunches:
		TNT1 A 0 A_Pain;
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil(18);
		SRG2 H 12;
	Goto See;

	Death:
		TNT1 A 0;
		TNT1 A 0 A_Jump(96, "LeftDeath");
		TNT1 A 0 A_Jump(96, "some_death");
		SRG3 A 8;
		SRG3 B 8 A_Scream;
		SRG3 C 4;
		SRG3 D 4 A_NoBlocking;
		SRG3 E 4;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		SRG3 F -1;
	Stop;
	some_death:
		TNT1 AAAAAAAAA 0;
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 a_spawnprojectile("XDeathDemonArm", 35, 0, random(0, 360), 2, random(0, 160));
		SRG2 I 8 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		SRG2 J 8 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItemEx("PoorMechPinkyLostHisArm",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	Stop;
		
	LeftDeath:
		SRG8 A 8;
		SRG8 B 8 A_Scream;
		SRG8 C 4;
		SRG8 D 4 A_NoBlocking;
		SRG8 E 4;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		SRG8 F -1;
		Stop;
		
	CleanDeath:
		TNT1 A 0;
		TNT1 A 0 A_Jump(96, "LeftDeath");
		SRG3 A 8;
		SRG3 B 8 A_Scream;
		SRG3 C 4;
		SRG3 D 4 A_NoBlocking;
		SRG3 E 4;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		SRG3 F -1;
		Stop;
		
	Death.Kick:
	Death.Melee:
	Death.SuperKick:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil(5);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		Goto CleanDeath;
		
	Death.Shotgun:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfCloser(200, "Death.Strong");
		Goto Death+4;
		
	Death.Strong:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "DeathRemoveArm");
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AA 0 a_spawnprojectile("XDeathBrain1", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBrain2", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", random(45, 55), random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AA 0 a_spawnprojectile("XDeath2", random(45, 55), random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 50, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("PinkyHeadPiece", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("PinkyJaw", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		SRG5 AAAAAAA 2 a_spawnprojectile("Brutal_LiquidBlood", 40, 0, random(0, 360), 2, random(30, 110));
		SRG5 BBBBBB 2 a_spawnprojectile("Brutal_LiquidBlood", 40, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		SRG5 CCCCCC 2 a_spawnprojectile("Brutal_LiquidBlood", 30, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		SRG5 DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 a_spawnprojectile("Brutal_LiquidBlood", 20, 0, random(0, 360), 2, random(30, 110));
		SRG5 D -1;
	Stop;
		
		
	Death.Saw:
	Death.Cut:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeathHalfDemon", 75, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathStomach", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDEATH5", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("xdeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("xdeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 60, 0, random(0, 360), 2, random(0, 160));
		SRG7 ABCD 9;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		SRG7 D -1;
	Stop;
		
	Death.Tear:
		TNT1 A 0 a_spawnprojectile("XDeathStomach", 30, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath4", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 60, 0, random(0, 360), 2, random(0, 160));
		SRG4 AAAAAAAAA 1 a_spawnprojectile("Brutal_LiquidBlood2", 46, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_Scream;
		SRG4 BBBBBBBBB 1 a_spawnprojectile("Brutal_LiquidBlood2", 25, 0, random(0, 360), 2, random(30, 60));
		SRG4 C 4 A_NoBlocking;
		SRG4 DEF 4;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		SRG4 F -1;
	Stop;
		
	Death.SuperPunch:
	Death.ExtremePunches:
	Death.Blast:
	Death.SSG:
		SRG9 A 1 A_Pain;
		SRG9 A 1 A_FaceTarget;
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AAA 0 bright a_spawnprojectile("SuperGoreSpawner", 35, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("MeatDeath", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("XDeath2", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("XDeathDemonArm", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		SRG9 AAAAABBBCCCCC 3 a_spawnprojectile("Brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		SRG9 CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 2 a_spawnprojectile("Brutal_LiquidBlood", 15, 0, random(0, 360), 2, random(30, 110));
		SRG9 C -1;
	Stop;


	Death.CutLEss:
		TNT1 A 0;
		TNT1 A 0 A_Jump(32, "Death.Cut");
		TNT1 A 0 A_Jump(132, "DeathRemoveArm");
	Goto Death;
		
		
	Crush:
	Death.Stomp:
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail8", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AAAAAA 0 bright a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright a_spawnprojectile("XDeath2", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright a_spawnprojectile("XDeath3", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("CrushedRemains");
		TNT1 A 1;
		TNT1 A 1 A_XScream;
		TNT1 A 1 A_NoBlocking;
	Stop;
		
	DeathRemoveArm:
		Goto Death+14;
		
	Death.GreenFire:
		TNT1 A 0;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAA 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
		
		
		TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		
		EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("GreenFlameTrails", 50, 0, random(0, 360), 2, random(0, 360));
		XBRN AAAA 2 BRIGHT A_SpawnItem("Green_Flare",0,43);
		Stop;
	Death.SuperPlasma:
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		
		TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("Ashes1", 32, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("Ashes2", 32, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		SPRG ABCDEF 6;
		CARB JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 10 a_spawnprojectile("Explosion_Smoke", 25, 0, random(0, 360), 2, random(70, 110));
		CARB J -1;
	Stop;
	
	Death.Incinerate:
		TNT1 A 0 A_Playsound("MELT");
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 {pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");}
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,32,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAA 0 A_SpawnItemEx("TinyBurningPiece", random(-45, 45), random(-45, 35));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("Ashes1", 28, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("Ashes2", 40, 0, random(0, 360), 2, random(0, 180));

		S6RN AAAABBBBCCCCCzDDDDDEEEEEFFFFFGGGGHHIIHHIIHHIIHHIIHHIIHHIIHHIIHHII 1 BRIGHT Light("IncinerationGlow")
		{
			pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");
			A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),28,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			if(frame > 22)A_Playsound("SZZLL", 3);
		}
		S6RN HHIIHHIIHHIIHHII 2;
		S6RN JJJJJJJ 12 a_spawnprojectile("ExplosionSmoke", 14, 0, random(0, 360), 2, random(0, 160));
		S6RN J -1;
	Stop;
	
	
	Death.fire:
	Death.Flames:
	Death.Burn:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItemEx("BurningDemon",0,0,8,0,0,0,0,288);
	Stop;
	
	Death.Fatality:
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_NoBlocking;
		//TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, 1);
	Goto Death.ExplosiveImpact;
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_Jump(256, "MechDemonFatality1");
	MechDemonFatality1:
		//TNT1 A 0 A_GiveToTarget("MechDemonFatality", 1);
	Stop;
	
	
	Death.BHFT:
		TNT1 A 1 A_Pain;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		//TNT1 A 0 A_GiveToTarget("DemonFatality", 1);
		TNT1 A 0;
	Stop;
	
	Death.ExplosiveImpact:
	Death.RVFT:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,25,0,1);
		TNT1 A 0 A_FaceTarget;
		TNT1 A 1;
		TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayRight");
		TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayLeft");
	Goto XDeath;
	
	BlownAwayLeft:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathStomach", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBullLeg12", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathPinkyDemonHead", 42, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(20, 90));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Xscream;
		S6RH ABCD 5 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, 0, 2, 90);
		S6RH DDDDDDDDDD 3 A_CheckFloor("LandBlownAwayLeft");
	LandBlownAwayLeft:
		TNT1 A 0 A_Stop;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadDemonS6RHE");
	Stop;
	
	BlownAwayRight:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathStomach", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBullLeg12", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathPinkyDemonHead", 42, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(20, 90));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Xscream;
		S6RH FGHI 5 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, 0, 2, 90);
		S6RH GGGGGGGGGG 3 A_CheckFloor("LandBlownAwayRight");
	LandBlownAwayRight:
	TNT1 A 0 A_Stop;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadDemonS6RHJ");
	Stop;
	
	XDeath:
	DEath.Explosive:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 AAAA 0 a_spawnprojectile("XDeath3", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 A 0 a_spawnprojectile("XDeath4", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 A 0 a_spawnprojectile("BullXDeath", 0, 0, random(0, 360), 2, random(0, 160));
	Stop;

	Raise:
		SARG N 5;
		SARG MLKJI 5;
	Goto See;
	
	Pain.KillMe:
	Pain.Taunt:
		TNT1 A 0;
	Goto See;

	
	
	FatalityZombieman:
	S4RK DEDEDEDEDE 10  {pb_blood_and_gore_event.much_blood(self);}
	TNT1 A 0 a_spawnprojectile("XDeathHalfZombieManDown", 20, 0, random(0, 360), 2, random(0, 160));
	//TNT1 A 0 A_TakeInventory("ZombiemanFatality",1);
	Goto See;
	
	
	FatalitySergeant:
	S4RK FGFGFGFGFG 10  {pb_blood_and_gore_event.much_blood(self);}
	TNT1 A 0 a_spawnprojectile("XDeathHalfZombieManDown", 20, 0, random(0, 360), 2, random(0, 160));
	//TNT1 A 0 A_TakeInventory("SergeantFatality",1);
	Goto See;
	
	FatalityComando:
	S4RK JKJKJKJKJK 10  {pb_blood_and_gore_event.much_blood(self);}
	//TNT1 A 0 A_TakeInventory("ComandoFatality",1);
	Goto See;
	
	FatalityImp:
	S4RK HIHIHIHIHI 10  {pb_blood_and_gore_event.much_blood(self);}
	//TNT1 A 0 A_TakeInventory("ImpFatality",1);
	Goto See;
	
	
	Eat:
	//TNT1 A 0 A_TakeInventory("EatMe", 1);
	SRG2 HGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHG 20
	{
		A_Look();
		a_spawnprojectile("named_BloodTr", 35, 0, random(0, 360), 2, random(0, 180));
		a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 160));
	}
	Goto Spawn;

	Death.Eat:
		//TNT1 A 0 A_GiveToTarget("EatMe",1);
	Goto Death+3;
	Stop;
	
	EatFast:
	SRG2 HGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHGHG 20
	{
		A_Look();
		a_spawnprojectile("named_BloodTr", 35, 0, random(0, 360), 2, random(0, 180));
		a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 160));
	}
	Goto MeleeDown;
	
	
	Death.Ice:
	Death.Freeze:
	Death.Frost:
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		//TNT1 A 0 A_SpawnItem("FrozenMechDemon");
	Stop;
	
	Death.Massacre:
	Goto Death;
}
}
