//Everything that can explode and hurt people goes here.
CLASS STGrenadeTimer : Inventory { 
Default {
		
	inventory.maxamount 20;
}
}


CLASS NewRocketExploFX : ACTOR { 
Default {
		
	Radius 0;
	Height 0;
	RenderStyle "Add";
	Alpha 1;
	Scale 1.35;
	+NOGRAVITY;
	+NOINTERACTION;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+ForceXYBillboard;
	+CLIENTSIDEONLY;
}
States
{
	Spawn:
		tnt1 A 0 nodelay
		{
			double scal = frandom(0.45, 5);
			scale =(scal, scal);
		}
		TNT1 A 0 A_PlaySound("FAREXPL");
		TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3", "Spawn4", "Spawn5");

	Spawn1:
		X006 ABCDEFGHIJKLMNOP 1 bright;
	stop;

	Spawn2:
		X003 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 bright;
	stop;

	Spawn3:
		X004 ABCDEFGHIJKLMNOPQ 1 bright;
	stop;

	Spawn4:
		X001 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 bright;//excavator
	stop;

	Spawn5:
		X005 ABCDEFGHIJKLMNOPQRSTUVWX 1 bright;
	stop;

}
}











CLASS StunGrenadeExplosion : ACTOR { 
Default {
		
	+NOBLOCKMAP;
	+MISSILE;
	Radius 2;
	Height 2;
	Damagetype "Stun";
}
States    {
	Spawn:
		Goto Death;
	Death:
		TNT1 A 0 A_PlaySound("LGBOMB", 3);
		TNT1 A 0 A_SetScale(0.1,0.01);
		STFL ABCDEFGHIJKL 1 BRIGHT Light("LightningImpactLight") A_SetScale(scale.x+0.12,scale.y+0.12);
		TNT1 A 0 BRIGHT A_SpawnItem("LightningGunPuff_Bigger",0);
		TNT1 A 0 BRIGHT A_SpawnItem("Blue_Flare",0);
		TNT1 A 0 A_explode(2, 300,0,0,300);
		TNT1 A 0 A_PlaySound("STNBOEX", 3);
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("ElectroBlastTrail3",6,0,random(0,359),CMF_AIMDIRECTION|CMF_TRACKOWNER,random(30,270));
		XELC AABBCCDDEEFF 1 Bright Light("LightningImpactLight") a_spawnprojectile("ElectroBlastTrail3",6,0,random(0,359),CMF_AIMDIRECTION|CMF_TRACKOWNER,random(30,270));
	Stop;
}}

		
		
		
		
		
		


CLASS GrenadeMissile : ACTOR { 
Default {
		
	Radius 4;
	Height 4;
	Speed 50;
	Damage 6;
	+MISSILE;
	+BLOODSPLATTER;
	//Damagetype "ExplosiveImpact"
	Gravity 0.7;
	
	+forceradiusdmg
	+SKYEXPLODE;
	+DOOMBOUNCE;
	+EXPLODEONWATER;
	DamageType "Kick";
	BounceFactor 0.5;
	SeeSound "Weapons/GrenadeBounce";
	DeathSound "none";
	Obituary "$OB_MPROCKET";
}
States
{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
		TNT1 A 0 A_GiveInventory("STGrenadeTimer", 1);
		TNT1 A 0 A_JumpIfInventory("STGrenadeTimer", 9, "Explode");
		TNT1 A 0 A_CheckFloor("Death");
		GBPJ ABCD 3 a_spawnprojectile("ExplosionSmoke", 2, 0, random(70, 110), 2, random(0, 360));
		TNT1 A 0 A_JumpIfInventory("STGrenadeTimer", 9, "Explode");
		TNT1 A 0 A_GiveInventory("STGrenadeTimer", 1);
		GBPJ EFGH 3a_spawnprojectile("ExplosionSmoke", 2, 0, random(70, 110), 2, random(0, 360));
		TNT1 A 0 A_JumpIfInventory("STGrenadeTimer", 9, "Explode");
	Loop;
			
	SpawnUnderwater:
		TNT1 A 0 A_GiveInventory("STGrenadeTimer", 1);
		GBPJ ABCD 3;
		TNT1 A 0 A_JumpIfInventory("STGrenadeTimer", 9, "Explode");
		TNT1 A 0 A_GiveInventory("STGrenadeTimer", 1);
		GBPJ EFGH 3;
		TNT1 A 0 A_JumpIfInventory("STGrenadeTimer", 9, "Explode");
	Goto Spawn;
			
	Death:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("STGrenadeTimer", 9, "Explode");
		GBPJ AAAA 3 a_spawnprojectile("ExplosionSmoke", 2, 0, random(70, 110), 2, random(0, 360));
		TNT1 A 0 A_GiveInventory("STGrenadeTimer", 1);
		Loop;
			
	XDeath:
		TNT1 A 0 A_Recoil(1);
		TNT1 A 0 A_SetAngle(random(90,-90) + angle);
		GBPJ C 1 ThrustThingZ(0,20,0,1);
		Goto Spawn;
			
	Explode:
	Death.Slime:
	Death.Fire:
	Death.Bullet:
	Death.Shotgun:
	Death.SSG:
	Death.Cutless:
	Death.Shrapnel:
		TNT1 A 0;
		TNT1 A 0 {self.bSHOOTABLE = false;}
		EXPL A 0 Radius_Quake(3, 16, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -30);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_Explode(200, 200, damagetype:"ExplosiveImpact");
		TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		EXPL AAAAA 0 a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_PlaySound("Explosion", 1);
		TNT1 A 1;
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 A 20;
		//TNT1 AAAAAAAAAAAAA 3 a_spawnprojectile("ExplosionSmoke", 2, 0, random(0, 360), 2, random(0, 360))
	Stop;
}
}




CLASS ShortGrenade: GrenadeMissile { 
Default {
		
	-DOOMBOUNCE;
	+SLIDESONWALLS;
}
States
{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
		GBPJ ABCDEFGH 3 a_spawnprojectile("ExplosionSmoke", 2, 0, random(70, 110), 2, random(0, 360));
		Loop;
			
	SpawnUnderwater:
		TNT1 A 0 A_GiveInventory("STGrenadeTimer", 1);
		GBPJ ABCD 3;
		TNT1 A 0 A_JumpIfInventory("STGrenadeTimer", 1, "Explode");
		TNT1 A 0 A_GiveInventory("STGrenadeTimer", 1);
		GBPJ EFGH 3;
		TNT1 A 0 A_JumpIfInventory("STGrenadeTimer", 1, "Explode");
		Goto Spawn;
			
	Death:
	XDeath:
		TNT1 A 0;
		Goto Explode;
}
}

///////////////////////////////////////////////////////////////////////////////PB


		






CLASS GrenadeMissileFrag : ACTOR { 
Default {
		
	Radius 4;
	Height 4;
	Speed 60;
	Damage 25;
	+MISSILE;
	+BLOODSPLATTER;
	+EXTREMEDEATH;
	+FORCEXYBILLBOARD;
	+CANBOUNCEWATER;
	+FORCERADIUSDMG;
	Gravity 1.2;
	Decal "Scorch";
	SeeSound "none";
	DeathSound "Explosion";
	Obituary "$OB_MPROCKET";
}
States
{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
		TNT1 A 0 a_spawnprojectile("Explosion_Smoke", 2, 0, random(70, 110), 2, random(0, 360));
		TNT1 A 0 A_SpawnItem("ExplosionSmoke");
		GRNP A 2 Bright A_SpawnItem("Red_FlareSmall",0,0);
		Loop;
			
	SpawnUnderwater:
		GRNP A 2 Bright A_SpawnItem("Red_FlareSmall",0,0);
		TNT1 A 0 a_spawnprojectile("underwater_bubles", 0, 0, random(0, 360), 2, random(0, 180));
		Goto Spawn;
			
	Death:
		TNT1 A 0;
		TNT1 A 1 A_SpawnItem("BigRicoChet", 0, -30);
		EXPL AAA 0 a_spawnprojectile("CasingSmoke", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("ExplosionSmoke", 22, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_Explode(100,130, damagetype:"Explosionimpact");
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 1;
		TNT1 AAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("SubFlakShell", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("FlackTracer", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ShrapnelParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_QuakeEx(1, 1, 1, 12, 0, 420, "", 0);
		TNT1 AAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_PlaySound("FAREXPL");
		EXPL AAA 0 a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360))      ;
		Stop;
			
	DeathLiquid:
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -30);
		EXPL AAA 0 a_spawnprojectile("CasingSmoke", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("ExplosionSmoke", 22, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_Explode(100,130, damagetype:"Explosionimpact");
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 1;
		//TNT1 AA 0 a_spawnprojectile("SubFlakShell", 0, 0, random(0, 360), 2, random(0, 360))
		//TNT1 AA 0 a_spawnprojectile("FlackTracer", 0, 0, random(0, 360), 2, random(0, 360))
		TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_QuakeEx(1, 1, 1, 12, 0, 420, "", 0);
		TNT1 AAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_PlaySound("FAREXPL");
		EXPL AAA 0 a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360))      ;
		Stop;
			
	XDeath:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -30);
		EXPL AAA 0 a_spawnprojectile("CasingSmoke", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("ExplosionSmoke", 22, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_Explode(100,130, damagetype:"Explosionimpact");
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 1;
		TNT1 AAAAAAAA 0 a_spawnprojectile("SubFlakShell", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAAAA 0 a_spawnprojectile("FlackTracer", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ShrapnelParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_QuakeEx(1, 1, 1, 12, 0, 420, "", 0);
		TNT1 AAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_PlaySound("FAREXPL");
		EXPL AAA 0 a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360))      ;
		Stop;
}
}



/////////////////////////////////////////////////////////////////////////////////





CLASS JuggernautRocket: pb_rocket { 
Default {
		
	speed 20;
	DamageFunction(random(100, 110));
	Species "None";
	-THRUSPECIES;
	-MTHRUSPECIES;
}
States
{
	Spawn:
		TNT1 A 0;
 			
	Spawn1:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
		WYVB A 1 Bright A_SpawnItem("Red_FlareSmall22",0,0);
		TNT1 A 0 a_spawnprojectile("ExplosionSmoke", 2, 0, random(160, 210), 2, random(-30, 30));
	Loop;
			
	SpawnCheap:
		TNT1 A 0;
		WYVB A 1 Bright A_SpawnItem("Red_FlareSmall22",0,0);
		Loop;
			
			
	SpawnUnderwater:
		WYVB A 1 Bright A_SpawnItem("YellowFlareSmall",0,0);
		TNT1 A 0 a_spawnprojectile("underwater_bubles", 0, 0, random(0, 360), 2, random(0, 180));
		Goto Spawn1;
			
			
	Death:
		EXPL A 0 Radius_Quake(2, 16, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
		//TNT1 A 0 A_SpawnItem("SuperExpensiveParticleSpawner")
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -30);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0  A_Explode(120, 150, damagetype:"ExplosiveImpact");
		TNT1 A 0 A_SpawnItemEx("NewRocketExploFX", 0, 0, 0);
		TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		EXPL AAAAA 0 a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 1;
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		Stop;
			
	DeathCheap:
		EXPL A 0 Radius_Quake(2, 16, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -30);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0  A_Explode(120, 150, damagetype:"ExplosiveImpact");
		TNT1 A 0 A_SpawnItemEx("NewRocketExploFX", 0, 0, 0);
		TNT1 AAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
	Stop;
}
}







CLASS CyberBalls : ACTOR { 
Default {
		
	Radius 10;
	Height 8;
	Projectile;
	Speed 28;
	Damage 8;
	DamageType "Explosive";
	Gravity 0.00;
	Decal "Scorch";
	Renderstyle "Add";
	-NOGRAVITY;
	+EXTREMEDEATH;
	+THRUGHOST;
	Scale 0.65;
	SeeSound "DSCANFIR";
	//SeeSound "RLANSHOT"
	DeathSound "Explosion";
	Obituary "$OB_MPROCKET";
}
States
{
	Spawn:
		TNT1 A 0;
 			
	Spawn1:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
		WYVB A 1 Bright A_SpawnItem("Red_FlareSmall22",0,0);
		TNT1 A 0 a_spawnprojectile("ExplosionSmoke", 2, 0, random(160, 210), 2, random(-30, 30));
	Loop;
			
	SpawnCheap:
		TNT1 A 0;
		WYVB A 1 Bright A_SpawnItem("Red_FlareSmall22",0,0);
		Loop;
			
			
	SpawnUnderwater:
		WYVB A 1 Bright A_SpawnItem("YellowFlareSmall",0,0);
		TNT1 A 0 a_spawnprojectile("underwater_bubles", 0, 0, random(0, 360), 2, random(0, 180));
		Goto Spawn1;
			
			
	Death:
		EXPL A 0 Radius_Quake(2, 16, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
		//TNT1 A 0 A_SpawnItem("SuperExpensiveParticleSpawner")
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -30);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0  A_Explode(120, 150, damagetype:"ExplosiveImpact");
		TNT1 A 0 A_SpawnItemEx("NewRocketExploFX", 0, 0, 0);
		TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		EXPL AAAAA 0 a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 1;
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		Stop;
			
	DeathCheap:
		EXPL A 0 Radius_Quake(2, 16, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -30);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0  A_Explode(120, 150, damagetype:"ExplosiveImpact");
		TNT1 A 0 A_SpawnItemEx("NewRocketExploFX", 0, 0, 0);
		TNT1 AAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 1;
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		Stop;
}
}

CLASS FastCyberballs: Cyberballs { 
Default {
		
	Speed 40;
	Damage 30;
}
}

CLASS CyberballTrail : ACTOR { 
Default {
		
	Radius 0;
	Height 0;
	Alpha 1.0;
	RenderStyle "Add";
	Scale 0.9;
	Speed 2;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+DONTSPLASH;
	+MISSILE;
	+FORCEXYBILLBOARD;
	+CLIENTSIDEONLY;
	Damage 0;
	+NOINTERACTION;
}
States
{
	Spawn:
		TNT1 A 2;
		WYVB CDE 1;
			
		Stop;
}
}







CLASS MarineGrenade : ACTOR { 
Default {
		
	Radius 4;
	Height 4;
	Speed 20;
	Damage 20;
	+MISSILE;
	+BLOODSPLATTER;
	+EXTREMEDEATH;
	+DOOMBOUNCE;
	BounceFactor 0.5;
	Damagetype "FriendBullet";
	Gravity 1.0;
	Decal "Scorch";
	SeeSound "none";
	DeathSound "Explosion";
	Obituary "$OB_MPROCKET";
	+EXTREMEDEATH;
}
States
{
	Spawn:
		TNT1 A 0 a_spawnprojectile("ExplosionSmoke", 2, 0, random(70, 110), 2, random(0, 360));
		TNT1 A 0 A_SpawnItem("ExplosionSmoke");
		GRNP A 2 Bright A_SpawnItem("Red_FlareSmall",0,0);
		Loop;
			
			
	Death:
		EXPL A 0 Radius_Quake(2, 16, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -30);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0  A_Explode(120, 150, damagetype:"ExplosiveImpact");
		TNT1 AAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		EXPL AAAAAA 0 a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 1;
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 AAAAAAAAAAAAA 3 a_spawnprojectile("ExplosionSmoke", 2, 0, random(0, 360), 2, random(0, 360));
		Stop;
}
}



CLASS NuclearRocket: pb_rocket { 
Default {
		
	+FORCERADIUSDMG;
	Damagetype "ExplosiveImpact";
}
States
{
	Spawn:
			
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("DSRLAUN");
		TNT1 A 0 BRIGHT a_spawnprojectile("RocketBackblast", 0, 0, 180, 2, 0+pitch);
	Live:
		MISL A 1 Bright;
		TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
		TNT1 A 0 A_SpawnItem("RocketFlare",-20,0);
		TNT1 A 0 A_SpawnItem("ExplosionSmoke");
		TNT1 A 0 a_spawnprojectile("ExplosionSmoke", 2, 0, random(160, 210), 2, random(-30, 30));
	Loop;
			
	SpawnUnderwater:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 A_SpawnItem("RocketFlare",-20,0);
		TNT1 A 0 a_spawnprojectile("underwater_bubles", 0, 0, random(0, 360), 2, random(0, 180));
		Goto Live;
			
	Death:
		TNT1 A 0;
		TNT1 A 0 {self.bFORCERADIUSDMG = true;}
		TNT1 A 1;
		TNT1 A 0 a_spawnprojectile("SpawnedExplosion", 30, 0, random(0, 360), 2, random(80, 90));
		TNT1 AAA 0 a_spawnprojectile("SpawnedExplosion", 30, 0, random(0, 360), 2, 90);
		TNT1 AAA 0  A_SpawnItemEx("SpawnedExplosion", random(-400, 400), random(-400, 400), random(0, 100));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0  A_SpawnItemEx("SpawnedExplosion", random(-600, 600), random(-600, 600), random(0, 50));
		EXPL A 0 Radius_Quake(6, 6, 0, 900, 0);
		TNT1 A 0 A_Explode(2000,400, 1, 1, 1);
		BEXP B 0 BRIGHT A_Scream;
		TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnItemEx("NukeFlare", random(-800, 800), random(-800, 800), random(0, 100));
		TNT1 AAAA 2 A_SpawnItemEx("NukeFlare", random(-800, 800), random(-800, 800), random(0, 100));
		TNT1 AAAA 0 a_spawnprojectile("SpawnedExplosion", random(0, 500), 0, random(0, 360), 2, random(80, 90));
		TNT1 A 0 A_Explode(4000,800, 1, 1, 1);
		TNT1 A 2 A_SpawnItemEx("NukeFlare", 0, 0, 300);
		TNT1 A 2 A_SpawnItemEx("NukeFlare", 0, 0, 600);
		TNT1 A 2 A_SpawnItemEx("NukeFlare", 0, 0, 900);
		TNT1 A 2 A_SpawnItemEx("NukeFlare", 0, 0, 1200);
		TNT1 A 0 A_Explode(500,1400, 1, 1, 1);
		TNT1 AAA 0  A_SpawnItemEx("SpawnedExplosion", random(-200, 200), random(-200, 200), 1000);
		TNT1 AAA 0  A_SpawnItemEx("SpawnedExplosion", random(-200, 200), random(-200, 200), 1500);
		TNT1 AAAAA 2 A_SpawnItemEx("NukeFlare", 0, 0, 1200);
		TNT1 A 60;
		EXPL A 0 Radius_Quake(6, 6, 0, 900, 0);
		TNT1 A 1000;
		sTOP;
}
}




CLASS TankShell : ACTOR { 
Default {
		
	Radius 6;
	Height 6;
	Speed 110;
	DamageFunction(random(1500, 1600));
	Projectile;
	+RANDOMIZE;
	+DEHEXPLOSION;
	+ROCKETTRAIL;
	+MISSILE;
	-NOGRAVITY;
	damagetype "TankShell";
	Gravity 0.4;
	SeeSound "weapons/rocklf";
	DeathSound "weapons/rocklx";
	Obituary "$OB_MPROCKET";
}
States
{
	Spawn:
		MISL A 1 Bright;
		Loop;
	Death:
		MISL B 0 Bright A_Explode;
		TNT1 A 0  A_Explode(200, 400, damagetype:"ExplosiveImpact");
		TNT1 A 0 A_PlaySound("Explosion", 1);
		TNT1 A 0 A_SpawnItemEx("ExplosionSplashSpawner", 0, 0, -20);
		TNT1 A 0 A_SpawnItemEx("SpawnedExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			
		TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		//EXPL AAAAA 0 a_spawnprojectile("ExplosionSmoke22", 0, 0, random(0, 360), 2, random(0, 360))
		TNT1 A 6;
		TNT1 A 0 A_PlaySound("FAREXPL", 1);
		TNT1 A 12;
		Stop;
}
}


CLASS EnemYTankShell: TankShell { 
Default {
		
	Speed 40;
	DamageFunction(random(190, 200));
	+NOGRAVITY;
}
}


CLASS TankFireEffect : ACTOR { 
Default {
		
	Radius 1;
	Height 1;
	Speed 70;
	Damage 1;
	Projectile;
	+RANDOMIZE;
	+MISSILE;
}
States
{
	Spawn:
		TNT1 A 2;
		Goto Death;
	Death:
		TNT1 A 0;
		TNT1 A 0 Radius_Quake(6, 12, 0, 4, 0);
		TNT1 AAAAA 0 A_SpawnItem("Red_Flare");
		TNT1 AAAAA 0 a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 1 BRIGHT;
		TNT1 AAAAA 0 A_SpawnItem("Red_Flare");
		TNT1 A 0 A_Stop;
		TNT1 A 0 A_Recoil(-5);
		TKFL A 5 BRIGHT;
		Stop;
}
}