//Everything that can explode and hurt people goes here.

CLASS STGrenadeTimer : Inventory { 
Default {
		
	inventory.maxamount 20;
}
}


CLASS NewRocketExploFX : ACTOR { 
Default {
		
	Radius 0;
	Height 0;
	RenderStyle "Add";
	Alpha 1;
	Scale 1.35;
	+NOGRAVITY;
	+NOINTERACTION;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+ForceXYBillboard;
	+CLIENTSIDEONLY;
}
States
{
	Spawn:
		tnt1 A 0 nodelay
		{
			double scal = frandom(0.45, 5);
			scale =(scal, scal);
		}
		TNT1 A 0 A_PlaySound("FAREXPL");
		TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3", "Spawn4", "Spawn5");

	Spawn1:
		X006 ABCDEFGHIJKLMNOP 1 bright;
	stop;

	Spawn2:
		X003 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 bright;
	stop;

	Spawn3:
		X004 ABCDEFGHIJKLMNOPQ 1 bright;
	stop;

	Spawn4:
		X001 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 bright;//excavator
	stop;

	Spawn5:
		X005 ABCDEFGHIJKLMNOPQRSTUVWX 1 bright;
	stop;

}
}
