

CLASS pb_Spark : ACTOR { 
Default {

height 1;
radius 2;
mass 0;
speed 1;
+CLIENTSIDEONLY
+MISSILE +NOBLOCKMAP +DOOMBOUNCE
bouncefactor 0.3;
renderstyle "Add";
scale 0.025;
Gravity 0.3;
}
states
{
	Spawn:
		tnt1 a 0 nodelay
		{
			vel *= frandom(0.5, 4);
		}
		SPRK A 1 bright A_JumpIf(waterlevel > 1, "Underwater");
	loop;
	Death:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Underwater");
		SPRK A 1 bright A_FadeOut(0.1);
	loop;

	Underwater:
		TNT1 A 0;
	Stop;
}
}
