//Tracing projectiles goes here

CLASS Tracer: FastProjectile { 
Default {
	
	Projectile;
	+RANDOMIZE;
	+FORCEXYBILLBOARD;
	+DONTSPLASH;
	//+BLOODSPLATTER 
	+NOEXTREMEDEATH;
	damage 0;
	radius 2;
	height 2;
	speed 140;
	renderstyle "Add";
	alpha 0.9;
	scale .15;
}
states
{
	Spawn:
		TRAC A 1 BRIGHT;
		Loop;
	Death:
		TNT1 A 0;
		Stop;
	XDeath:
		TNT1 A 0;
		Stop;
}
}

CLASS MinigunTracer: Tracer {
Default {
	
	-DONTSPLASH;
	seesound "weapons/chainwiz";
	damagetype "Cutless";
}
}

CLASS MonsterNewMinigunTracer: Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUGHOST;
	-DONTSPLASH;
	speed 80;
	damagefunction(random(4,6));
	seesound "weapons/chainwiz";
	damagetype "Cutless";
	Decal "BulletChip";
}
States
{
	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
		Stop;
}
}

CLASS MonsterNewClassicChaingunTracer: Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUGHOST;
	-DONTSPLASH;
	speed 80;
	damagefunction(random(4,5));
	seesound "weapons/chainwiz";
	damagetype "Cutless";
	Decal "BulletChip";
}
States
{
	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
		Stop;
}
}

///////////////////////////////////////////////////////////////////////////////PB

CLASS ExplosiveChaingunTracer : Tracer { 
Default {
	
	+BLOODSPLATTER;
	-NOEXTREMEDEATH;
	+EXTREMEDEATH;
	speed 75;
	damage 12;
	scale .35;
	radius 3;
	height 3;
	seesound "None";
	damagetype "ExplosiveImpact";
	Decal "Scorch";
}
States
{
	
	Spawn:
		TRAC A 1 BRIGHT;
		Loop;
		
	Death:
	Xdeath:
		EXPL A 0 A_Explode(3, random(32,42), 1);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 1 A_SpawnItem("HitPuff");
		TNT1 A 0 a_spawnprojectile("SmallExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		
		TNT1 A 0 a_spawnprojectile("ExplosionParticleHeavy", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("ExplosionParticleVeryFast", 0, 0, random(0, 360), 2, random(0, 40));
		
		TNT1 A 0 A_PlaySound("FAREXPL");
		TNT1 AAA 4 a_spawnprojectile("PlasmaSmoke", 2, 0, random(0, 360), 2, random(0, 360));
		Stop;
}
}

CLASS ExplosiveChaingunTracer1 : Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUGHOST;
	-DONTSPLASH;
	speed 75;
	damage 12;
	scale .3;
	seesound "None";
	damagetype "SSG";
	Decal "Scorch";
}
States
{
	Death:
	Xdeath:
		EXPL A 0 A_Explode(3, random(32,42), 1);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 1 A_SpawnItem("HitPuff");
		TNT1 A 0 a_spawnprojectile("SmallExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		
		TNT1 A 0 a_spawnprojectile("ExplosionParticleHeavy", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("ExplosionParticleVeryFast", 0, 0, random(0, 360), 2, random(0, 40));
		
		TNT1 A 0 A_PlaySound("FAREXPL");
		TNT1 AAA 4 a_spawnprojectile("PlasmaSmoke", 2, 0, random(0, 360), 2, random(0, 360));
		Stop;
}
}

CLASS ExplosiveChaingunTracer2 : Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUGHOST;
	-DONTSPLASH;
	speed 75;
	damage 12;
	scale .3;
	seesound "None";
	damagetype "Blast";
	Decal "Scorch";
}
States
{
	Death:
	Xdeath:
		EXPL A 0 A_Explode(3, random(32,42), 1);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 1 A_SpawnItem("HitPuff");
		TNT1 A 0 a_spawnprojectile("SmallExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		
		TNT1 A 0 a_spawnprojectile("ExplosionParticleHeavy", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("ExplosionParticleVeryFast", 0, 0, random(0, 360), 2, random(0, 40));
		
		TNT1 A 0 A_PlaySound("FAREXPL");
		TNT1 AAA 4 a_spawnprojectile("PlasmaSmoke", 2, 0, random(0, 360), 2, random(0, 360));
		Stop;
}
}

CLASS FlackTracer: Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUGHOST;
	+Friendly;
	+DONTSPLASH;
	speed 80;
	damage 12;
	Decal "BulletChip";
	DamageType "FriendBullet";
}
States
{
	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
		Stop;
}
}

//////////////////////////////////////////////////////////////////////////////////


CLASS MonsterTracer: Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUGHOST;
	-DONTSPLASH;
	+MISSILE;
	speed 60;
	damagefunction(random(3,4));
	Decal "BulletDecalNew1";
	DamageType "Bullet";
}
States
{
	Spawn:
		TRAC A 1 BRIGHT;
		TNT1 A 0 ThrustThingZ(0,random(-8, 8),0,1);
		TRAC A 1 BRIGHT;
		Goto Spawn2;
		
	Spawn2:
		TRAC A 1 BRIGHT;
		Loop;
		
	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
		Stop;
}
}

CLASS ZombieManTracer: MonsterTracer { 
Default {
	
	damagefunction(random(5,6));
	Seesound "LightDistantGunshot";
}
}

CLASS MonsterHandgunTracer: MonsterTracer { 
Default {
	
	damagefunction(random(5,6));
	Seesound "SmallerDistantGunshot";
}
}

CLASS EvilNaziTracer: MonsterTracer { 
Default {
	
	damagefunction(random(1,2));
}
}

CLASS MonsterMinigunTracer: MonsterTracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUGHOST;
	-DONTSPLASH;
	speed 60;
	damagefunction(random(4,5));
	seesound "NONE";
	damagetype "Cutless";
	Decal "BulletDecalNew1";
}
States
{
	
	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
		Stop;
}
}

CLASS MonsterNewchaingunTracer: Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUGHOST;
	-DONTSPLASH;
	speed 80;
	damagefunction(random(5,7));
	Seesound "HeavyDistantGunshot";
	damagetype "Cutless";
	Decal "BulletChip";
}
States
{
	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
		Stop;
}
}


CLASS MonsterLMGTracer: Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUGHOST;
	-DONTSPLASH;
	speed 80;
	damagefunction(random(6,7));
	Seesound "HeavyDistantGunshot";
	damagetype "Cutless";
	Decal "BulletChip";
}
States
{
	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
		Stop;
}
}

CLASS MeatShieldTracer: Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUACTORS;
	-DONTSPLASH;
	speed 100;
	damagefunction(random(20,25));
	Decal "BulletDecalNew1";
	//DamageType "FriendBullet"
	DamageType "Bullet";
}
States
{
	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
		Stop;
		
	Spawn:
		TRAC A 1 BRIGHT;
		TNT1 A 0 {self.bTHRUACTORS = false;}
		Goto Fly;
	Fly:
		TRAC A 1 BRIGHT;
		Loop;
}
}

CLASS MeatShieldShotgunTracer1: Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUACTORS;
	-DONTSPLASH;
	speed 100;
	damagefunction(random(20,25));
	Decal "BulletDecalNew1";
	damagetype "Cutless";
}
States
{
	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
		Stop;
		
	Spawn:
		TRAC A 1 BRIGHT;
		TNT1 A 0 {self.bTHRUACTORS = false;}
		Goto Fly;
	Fly:
		TRAC A 1 BRIGHT;
		Loop;
}
}

CLASS MeatShieldShotgunTracer2: Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUACTORS;
	-DONTSPLASH;
	speed 100;
	damagefunction(random(20,25));
	Decal "BulletDecalNew1";
	damagetype "Shotgun";
}
States
{
	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
		Stop;
		
	Spawn:
		TRAC A 1 BRIGHT;
		TNT1 A 0 {self.bTHRUACTORS = false;}
		Goto Fly;
	Fly:
		TRAC A 1 BRIGHT;
		Loop;
}
}
CLASS MarineMinigunTracer: Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUGHOST;
	-DONTSPLASH;
	speed 100;
	damage 1;
	seesound "weapons/minigunfire2";
	DamageType "FriendBullet";
	Decal "BulletDecalNew1";
}
States
{
	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
		Stop;
}
}

CLASS MarineTracer: Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUGHOST;
	-DONTSPLASH;
	-GHOST;
	-THRUGHOST;
	+THRUSPECIES;
	+MTHRUSPECIES;
	Species "Marine";
	speed 100;
	damagefunction(random(8,10));
	Decal "BulletDecalNew1";
	DamageType "FriendBullet";
}
States
{
	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
		Stop;
	XDEath:
		TNT1 A 0;
		//TNT1 A 0 A_Explode(2, 5)
		TNT1 A 1;
		Stop;
}
}

CLASS MarineStrongTracer: MarineTracer { 
Default {
	
	damagefunction(random(12,13));
}
States
{
	Spawn:
		TRAC A 1 BRIGHT;
		TNT1 A 0 ThrustThingZ(0,random(-9, 9),0,1);
		TRAC A 1 BRIGHT;
		Goto Spawn2;
		
	Spawn2:
		TRAC A 1 BRIGHT;
		Loop;
}
}

CLASS SentryTracer1: MarineTracer { 
Default {
	
	Scale .26;
	damage 9;
	//damagetype "Cutless"
}
States
{
	Spawn:
		TRAC A 1 BRIGHT;
		TNT1 A 0 ThrustThingZ(0,random(-9, 9),0,1);
		TRAC A 1 BRIGHT;
		Goto Spawn2;
		
	Spawn2:
		TRAC A 1 BRIGHT;
		Loop;
}
}

CLASS SentryTracer2: SentryTracer1 { 
Default {
	
	damage 10;
	//	damagetype saw
}
}

CLASS SentryTracer3: SentryTracer1 { 
Default {
	
	damage 9;
	//	damagetype "Blast"
}
}

CLASS MarineShotgunTracer: MarineTracer { 
Default {
	
	damagefunction(random(10,12));
	damagetype "Shotgun";
}
States
{
	Spawn:
		TRAC A 1 BRIGHT;
		TNT1 A 0 ThrustThingZ(0,random(-9, 9),0,1);
		TRAC A 1 BRIGHT;
		Goto Spawn2;
		
	Spawn2:
		TRAC A 1 BRIGHT;
		Loop;
}
}

CLASS Alerter: MonsterTracer { 
Default {
	
	-BLOODSPLATTER;
	+THRUGHOST;
	+DONTSPLASH;
	speed 200;
	radius 12;
	height 12;
	damagefunction(random(1,1));
	DamageType "Avoid";
	Decal "None";
}
States
{
	Spawn:
		TNT1 A 1 BRIGHT;
		Loop;
	Death:
		TNT1 A 0;
		Stop;
}
}

CLASS RareAlerter: Alerter { 
Default {
	
	Speed 70;
	+THRUACTORS;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Jump(246, "Death");
		TNT1 A 0 {self.bTHRUACTORS = false;}
		TNT1 A 100;
		Loop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_Stop;
		TNT1 A 0;
		Stop;
		
}
}


CLASS Taunter: MonsterTracer { 
Default {
	
	-BLOODSPLATTER;
	+THRUGHOST;
	+DONTSPLASH;
	radius 16;
	height 16;
	speed 100;
	damagefunction(random(1,2));
	DamageType "Taunt";
	Decal "None";
}
States
{
	Spawn:
		PUZZ Z 1 BRIGHT;
		Loop;
	XDeath:
	Melee:
	Death:
		TNT1 A 1;
		TNT1 A 100;
		
		Stop;
}
}




CLASS MastermindTracer: Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUGHOST;
	-DONTSPLASH;
	speed 90;
	damagefunction(random(5,7));
	scale .45;
	Seesound "HeavyDistantGunshot";
	damagetype "ExplosiveImpact";
	Decal "Scorch";
	Obituary "$OB_SPIDER";
}
States
{
	
	
	Death:
	Xdeath:
		EXPL A 0 A_Explode(2, 120, 0);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AA 0 a_spawnprojectile("ExplosionParticleHeavy", 0, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAA 0 a_spawnprojectile("ExplosionParticleHeavy", 0, 0, random(0, 180), 2, random(0, 180));
		XXXX A 0 a_spawnprojectile("ShakeShakeShake", 1, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		
		TNT1 AAA 0 a_spawnprojectile("ExplosionParticleHeavy", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("ExplosionParticleVeryFast", 0, 0, random(0, 360), 2, random(0, 40));
		
		TNT1 A 0 A_PlaySound("FAREXPL");
		TNT1 AAAAAAAA 4 a_spawnprojectile("PlasmaSmoke", 2, 0, random(0, 360), 2, random(0, 360));
		Stop;
}
}

CLASS SuperMastermindTracer: MastermindTracer { 
Default {
	
	Speed 120;
	damagefunction(random(7,10));
	Height 24;
}
}

CLASS ArachnophyteTracer: MastermindTracer { 
Default {
	
	Speed 50;
	damage 0;
	Height 16;
	scale .36;
Translation "0:255=%[0,0,0]:[1,1,0]";
}
States
{
	
	
Death:
Xdeath:
	EXPL A 0 A_Explode(4, 24, 0);
	TNT1 A 0 a_spawnprojectile("YellowFlare", 0, 0, random(0, 360));
	TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 AA 0 a_spawnprojectile("ExplosionParticleHeavy", 0, 0, random(0, 360), 2, random(0, 180));
	TNT1 AA 0 a_spawnprojectile("SmallExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 AAA 0 a_spawnprojectile("ExplosionParticleVeryFast", 0, 0, random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_PlaySound("FAREXPL", 1, 0.3);
	TNT1 AAA 4 a_spawnprojectile("PlasmaSmoke", 2, 0, random(0, 360), 2, random(0, 360));
	Stop;
}
}


CLASS NaziAlerter: Tracer { 
Default {

-BLOODSPLATTER;
+THRUGHOST;
speed 150;
Decal "None";
Radius 16;
Height 16;
DamageType "KillMe";
Damage 2;
}
States
{
Spawn:
	POSS A 25;
	Loop;
Death:
	TNT1 A 1;
	Stop;
}
}

CLASS QuadTracer: MonsterTracer { 
Default {

speed 60;
damagefunction(random(1,2));
+FORCEXYBILLBOARD;
+THRUGHOST;
damagetype "SSG";
}
States
{
Death:
	TNT1 A 1 A_SpawnItem("HitPuff");
	Stop;
}
}

CLASS QuadSingeTracer: MonsterTracer { 
Default {

speed 65;
damage 2;
+FORCEXYBILLBOARD;
+THRUGHOST;
Decal "BulletChip";
DamageType "Arm";
}
States
{
Death:
	TNT1 A 1 A_SpawnItem("HitPuff");
	Stop;
}
}

CLASS WallPenetrationHitscan: FastProjectile { 
Default {

Projectile;
+RANDOMIZE;
+FORCEXYBILLBOARD;
+DONTSPLASH;
damage 0;
radius 2;
height 2;
speed 900;
renderstyle "Add";
alpha 0.9;
scale .3;
}
states
{
Spawn:
	TRAC A 1 BRIGHT;
	Loop;
Death:
	TNT1 A 0;
	TNT1 A 0 A_CheckFloor("Nothing");
	TNT1 A 0 A_CheckCeiling("Nothing");
	TNT1 A 0 A_SpawnItemEx("Penetrator",cos(-pitch)*24,0,0+(sin(pitch)*24),cos(-pitch)*100,0,sin(pitch)*100,0,SXF_TRANSFERPITCH);
	tnt1 A 2;
	Stop;
	
Nothing:
	TNT1 A 0;
	Stop;
	
XDeath:
	TNT1 A 0;
	TNT1 A 0 A_SpawnItemEx("Penetrator",cos(-pitch)*24,0,0+(sin(pitch)*24),cos(-pitch)*100,0,sin(pitch)*100,0,SXF_TRANSFERPITCH);
	Stop;
}
}

CLASS RailgunWallPenetrationHitscan: FastProjectile { 
Default {

Projectile;
+RANDOMIZE;
+FORCEXYBILLBOARD;
+DONTSPLASH;
damage 0;
radius 2;
height 2;
speed 900;
renderstyle "Add";
alpha 0.9;
scale .3;
}
states
{
Spawn:
	TRAC A 1 BRIGHT;
	Loop;
Death:
	TNT1 A 0;
	TNT1 A 0 A_CheckFloor("Nothing");
	TNT1 A 0 A_CheckCeiling("Nothing");
	TNT1 A 0 A_SpawnItemEx("RailgunPenetrator",cos(-pitch)*24,0,0+(sin(pitch)*24),cos(-pitch)*100,0,sin(pitch)*100,0,SXF_TRANSFERPITCH);
	tnt1 A 2;
	Stop;
	
Nothing:
	TNT1 A 0;
	Stop;
	
XDeath:
	TNT1 A 0;
	TNT1 A 0 A_SpawnItemEx("RailgunPenetrator",cos(-pitch)*24,0,0+(sin(pitch)*24),cos(-pitch)*100,0,sin(pitch)*100,0,SXF_TRANSFERPITCH);
	Stop;
}
}


CLASS SpawnBulletDecalBackwards: FastProjectile { 
Default {

Projectile;
+RANDOMIZE;
+FORCEXYBILLBOARD;
+DONTSPLASH;
+THRUACTORS;
damage 0;
radius 2;
height 2;
speed 50;
renderstyle "Add";
Decal "BulletDecalNew1";
alpha 0.9;
scale .3;
}
states
{
Spawn:
	TNT1 A 1 BRIGHT;
	Loop;
Death:
	TNT1 A 0 A_SpawnItem("HitPuff");
	TNT1 A 10;
	Stop;
XDeath:
	TNT1 A 0;
	Stop;
}
}



CLASS SpawnRocketDecalBackwards: FastProjectile { 
Default {

Projectile;
+RANDOMIZE;
+FORCEXYBILLBOARD;
+DONTSPLASH;
+THRUACTORS;
damage 0;
radius 6;
height 2;
speed 50;
renderstyle "Add";
Decal "Scorch";
alpha 0.9;
scale .8;
}
states
{
Spawn:
	TNT1 A 1 BRIGHT;
	Loop;
Death:
	TNT1 AAAAAAA 4 a_spawnprojectile("PLasmaSmoke", 2, 0, random(0, 360), 2, random(10, 60));
	Stop;
XDeath:
	TNT1 A 0;
	Stop;
}
}


CLASS Penetrator: MarineTracer { 
Default {

damagefunction(random(8,10));
Decal "none";
DamageType "FriendBullet";
-SKYEXPLODE;
//+Ripper
}
States
{
Spawn:
	TNT1 A 0;
	TNT1 A 0 a_spawnprojectile("SpawnBulletDecalBackwards", 0, 0, 0);
	TRAC A 10 BRIGHT;
	sTOP;
	
Death:
	TNT1 A 0;
	TNT1 A 0 A_CheckFloor("XDeath");
	TNT1 A 0 A_CheckCeiling("XDeath");
	TNT1 A 1 A_SpawnItem("HitPuff");
	Stop;
	
DeathSpecial:
	
	Stop;
XDEath:
	TNT1 A 0;
	TNT1 A 0 A_Playsound("bulletfleshimpact", 1);
	TNT1 A 0 A_SpawnItemEx("Penetrator2",cos(-pitch)*24,0,0+(sin(pitch)*24),cos(-pitch)*100,0,sin(pitch)*100,0,SXF_TRANSFERPITCH);
	TNT1 A 1;
	Stop;
}
}

CLASS Penetrator2: MarineTracer { 
Default {

damagefunction(random(8,10));
Decal "none";
DamageType "FriendBullet";
-SKYEXPLODE;
//+Ripper
}
States
{
Spawn:
	TNT1 A 0;
	TNT1 A 0 a_spawnprojectile("SpawnBulletDecalBackwards", 0, 0, 0);
	TRAC A 10 BRIGHT;
	sTOP;
	
Death:
	TNT1 A 0;
	TNT1 A 0 A_CheckFloor("XDeath");
	TNT1 A 0 A_CheckCeiling("XDeath");
	TNT1 A 1 A_SpawnItem("HitPuff");
	Stop;
	
DeathSpecial:
	
	Stop;
XDEath:
	TNT1 A 0;
	TNT1 A 0 A_Playsound("bulletfleshimpact", 1);
	TNT1 A 0 A_SpawnItemEx("Penetrator3",cos(-pitch)*24,0,0+(sin(pitch)*24),cos(-pitch)*100,0,sin(pitch)*100,0,SXF_TRANSFERPITCH);
	TNT1 A 1;
	Stop;
}
}

CLASS Penetrator3: MarineTracer { 
Default {

damagefunction(random(8,10));
Decal "none";
DamageType "FriendBullet";
-SKYEXPLODE;
//+Ripper
}
States
{
Spawn:
	TNT1 A 0;
	TNT1 A 0 a_spawnprojectile("SpawnBulletDecalBackwards", 0, 0, 0);
	TRAC A 10 BRIGHT;
	sTOP;
	
Death:
	TNT1 A 0;
	TNT1 A 0 A_CheckFloor("XDeath");
	TNT1 A 0 A_CheckCeiling("XDeath");
	TNT1 A 1 A_SpawnItem("HitPuff");
	Stop;
	
DeathSpecial:
	
	Stop;
XDEath:
	TNT1 A 0;
	TNT1 A 1;
	Stop;
}
}

CLASS MonsterPenetrator: MarineTracer { 
Default {

damagefunction(random(2,3));
Decal "BulletDecalNew1";
DamageType "Bullet";
-SKYEXPLODE;
}
States
{
Spawn:
	TNT1 A 0;
	TNT1 A 0 a_spawnprojectile("SpawnBulletDecalBackwards", 0, 0, 0);
	TRAC A 10 BRIGHT;
	sTOP;
	
Death:
	TNT1 A 0;
	TNT1 A 0 A_CheckFloor("XDeath");
	TNT1 A 0 A_CheckCeiling("XDeath");
	
	TNT1 A 1 A_SpawnItem("HitPuff");
	Stop;
XDEath:
	TNT1 A 0;
	TNT1 A 1;
	Stop;
}
}

CLASS RailgunPenetrator: MarineTracer { 
Default {

damage 50;
Decal "none";
damagetype "Blast";
-SKYEXPLODE;
//+Ripper
Scale 5.0;
Translation "0:255=%[0,0,0]:[0,1,1]";
}
States
{
Spawn:
TNT1 A 0;
TNT1 A 0 a_spawnprojectile("SpawnRocketDecalBackwards", 0, 0, 0);
TRAC A 10 BRIGHT;
sTOP;

Death:
TNT1 A 0;
TNT1 A 0 A_CheckFloor("XDeath");
TNT1 A 0 A_CheckCeiling("XDeath");

TNT1 A 1;
TNT1 AAAA 0 A_SpawnItemEx("BluePlasmaParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
TNT1 AA 0 A_SpawnItem("WhiteShockwave");

TNT1 A 0 A_Explode(120,5, 1);
TNT1 A 0 A_Playsound("explosion/deepimpact", 3);
EXPL A 0 Radius_Quake(4, 10, 0, 15, 0);
TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticleHeavy", 0, 0, random(0, 360), 2, random(0, 180));
TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ExplosionParticleHeavy", 0, 0, random(0, 360), 2, random(0, 360));
TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticleVeryFast", 0, 0, random(0, 360), 2, random(0, 360));
EXPL AAAAA 0 a_spawnprojectile("ExplosionSmokeFast22", 0, 0, random(0, 360), 2, random(0, 360));
TNT1 AAAA 0 a_spawnprojectile("FireworkSFXType2", 2, 0, random(0, 360), 2, random(10, 80));
TNT1 A 0 A_SpawnItemEx("DetectFloorCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
TNT1 A 0 A_SpawnItemEx("DetectCeilCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
TNT1 A 0 a_spawnprojectile("BluePlasmaFire", 0, 0, random(0, 360), 2, random(0, 360));
TNT1 AAAAA 0 a_spawnprojectile("BluePlasmaParticle", 0, 0, random(0, 360), 2, random(0, 360));
TNT1 ABCDE 2 BRIGHT A_SpawnItem("BlueFlare" ,0);
TNT2 AAAAAAAAA 9 a_spawnprojectile("PlasmaSmoke", 1, 0, random(0, 360), 2, random(0, 160));
stop;

DeathSpecial:	

Stop;
XDEath:
TNT1 A 0;
TNT1 A 0 A_Playsound("bulletfleshimpact", 1);
TNT1 A 0 A_SpawnItemEx("RailgunPenetrator2",cos(-pitch)*24,0,0+(sin(pitch)*24),cos(-pitch)*100,0,sin(pitch)*100,0,SXF_TRANSFERPITCH);
TNT1 A 1;
Stop;
}
}

CLASS RailgunPenetrator2: MarineTracer { 
Default {

damage 45;
Decal "none";
damagetype "Blast";
-SKYEXPLODE
//+Ripper
Scale 5.0;
Translation "0:255=%[0,0,0]:[0,1,1]";
}
States
{
Spawn:
	TNT1 A 0;
	TNT1 A 0 a_spawnprojectile("SpawnRocketDecalBackwards", 0, 0, 0);
	TRAC A 10 BRIGHT;
	sTOP;
	
Death:
TNT1 A 0;
TNT1 A 0 A_CheckFloor("XDeath");
TNT1 A 0 A_CheckCeiling("XDeath");

	TNT1 A 1;
	TNT1 AAAA 0 A_SpawnItemEx("BluePlasmaParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
	TNT1 AA 0 A_SpawnItem("WhiteShockwave");
	
	TNT1 A 0 A_Explode(120,5, 1);
	TNT1 A 0 A_Playsound("explosion/deepimpact", 3);
	EXPL A 0 Radius_Quake(4, 10, 0, 15, 0);
	TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticleHeavy", 0, 0, random(0, 360), 2, random(0, 180));
	TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ExplosionParticleHeavy", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticleVeryFast", 0, 0, random(0, 360), 2, random(0, 360));
	EXPL AAAAA 0 a_spawnprojectile("ExplosionSmokeFast22", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 AAAA 0 a_spawnprojectile("FireworkSFXType2", 2, 0, random(0, 360), 2, random(10, 80));
	TNT1 A 0 A_SpawnItemEx("DetectFloorCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 A_SpawnItemEx("DetectCeilCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 a_spawnprojectile("BluePlasmaFire", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 AAAAA 0 a_spawnprojectile("BluePlasmaParticle", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 ABCDE 2 BRIGHT A_SpawnItem("BlueFlare" ,0);
	TNT2 AAAAAAAAA 9 a_spawnprojectile("PlasmaSmoke", 1, 0, random(0, 360), 2, random(0, 160));
	stop;

DeathSpecial:	

Stop;
XDEath:
TNT1 A 0;
TNT1 A 0 A_Playsound("bulletfleshimpact", 1);
TNT1 A 0 A_SpawnItemEx("RailgunPenetrator3",cos(-pitch)*24,0,0+(sin(pitch)*24),cos(-pitch)*100,0,sin(pitch)*100,0,SXF_TRANSFERPITCH);
TNT1 A 1;
Stop	;
}
}

CLASS RailgunPenetrator3: MarineTracer { 
Default {

damage 45;
Decal "none";
damagetype "Blast";
-SKYEXPLODE
//+Ripper
Scale 5.0;
Translation "0:255=%[0,0,0]:[0,1,1]";
}
States
{
Spawn:
	TNT1 A 0;
	TNT1 A 0 a_spawnprojectile("SpawnRocketDecalBackwards", 0, 0, 0);
	TRAC A 10 BRIGHT;
	sTOP;
	
Death:
TNT1 A 0;
TNT1 A 0 A_CheckFloor("XDeath");
TNT1 A 0 A_CheckCeiling("XDeath");

	TNT1 A 1;
	TNT1 AAAA 0 A_SpawnItemEx("BluePlasmaParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
	TNT1 AA 0 A_SpawnItem("WhiteShockwave");
	
	TNT1 A 0 A_Explode(120,5, 1);
	TNT1 A 0 A_Playsound("explosion/deepimpact", 3);
	EXPL A 0 Radius_Quake(4, 10, 0, 15, 0);
	TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticleHeavy", 0, 0, random(0, 360), 2, random(0, 180));
	TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ExplosionParticleHeavy", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticleVeryFast", 0, 0, random(0, 360), 2, random(0, 360));
	EXPL AAAAA 0 a_spawnprojectile("ExplosionSmokeFast22", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 AAAA 0 a_spawnprojectile("FireworkSFXType2", 2, 0, random(0, 360), 2, random(10, 80));
	TNT1 A 0 A_SpawnItemEx("DetectFloorCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 A_SpawnItemEx("DetectCeilCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 a_spawnprojectile("BluePlasmaFire", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 AAAAA 0 a_spawnprojectile("BluePlasmaParticle", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 ABCDE 2 BRIGHT A_SpawnItem("BlueFlare" ,0);
	TNT2 AAAAAAAAA 9 a_spawnprojectile("PlasmaSmoke", 1, 0, random(0, 360), 2, random(0, 160));
	stop;

DeathSpecial:	

Stop;
XDEath:
TNT1 A 0;
TNT1 A 0 A_Playsound("bulletfleshimpact", 1);
TNT1 A 0 A_SpawnItemEx("RailgunPenetrator4",cos(-pitch)*24,0,0+(sin(pitch)*24),cos(-pitch)*100,0,sin(pitch)*100,0,SXF_TRANSFERPITCH);
TNT1 A 1;
Stop	;
}
}


CLASS RailgunPenetrator4: MarineTracer { 
Default {

damage 35;
Decal "none";
damagetype "Blast";
-SKYEXPLODE
//+Ripper
Scale 5.0;
Translation "0:255=%[0,0,0]:[0,1,1]";
}
States
{
Spawn:
	TNT1 A 0;
	TNT1 A 0 a_spawnprojectile("SpawnRocketDecalBackwards", 0, 0, 0);
	TRAC A 10 BRIGHT;
	sTOP;
	
	Death:
		TNT1 A 0;
		TNT1 A 0 A_CheckFloor("XDeath");
		TNT1 A 0 A_CheckCeiling("XDeath");

		TNT1 A 1;
		TNT1 AAAA 0 A_SpawnItemEx("BluePlasmaParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
		TNT1 AA 0 A_SpawnItem("WhiteShockwave");
		
		TNT1 A 0 A_Explode(120,5, 1);
		TNT1 A 0 A_Playsound("explosion/deepimpact", 3);
		EXPL A 0 Radius_Quake(4, 10, 0, 15, 0);
		TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticleHeavy", 0, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ExplosionParticleHeavy", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("ExplosionParticleVeryFast", 0, 0, random(0, 360), 2, random(0, 360));
		EXPL AAAAA 0 a_spawnprojectile("ExplosionSmokeFast22", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAA 0 a_spawnprojectile("FireworkSFXType2", 2, 0, random(0, 360), 2, random(10, 80));
		TNT1 A 0 A_SpawnItemEx("DetectFloorCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("DetectCeilCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 a_spawnprojectile("BluePlasmaFire", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAA 0 a_spawnprojectile("BluePlasmaParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 ABCDE 2 BRIGHT A_SpawnItem("BlueFlare" ,0);
		TNT2 AAAAAAAAA 9 a_spawnprojectile("PlasmaSmoke", 1, 0, random(0, 360), 2, random(0, 160));
	stop;

DeathSpecial:
Stop;

XDEath:
TNT1 A 0;
TNT1 A 1;
Stop;
}
}


CLASS RocketBackblast: Tracer { 
Default {

speed 80;
damagefunction(random(5,10));
Decal "Scorch";
Radius 12;
Height 24;
Alpha 0.9;
Scale 1.0;
Renderstyle "Add";
+RIPPER;
DamageType "sHOTGUN";
}
States
{
Spawn:
	TNT1 A 2;
	EXPL GHI 1 a_spawnprojectile("smALLExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
	Stop;
	
Death:
TNT1 A 1;
Stop;
}
}

CLASS RocketGlassBreaker: Alerter { 
Default {

speed 40;
Radius 4;
Height 2;
damagefunction(random(1,1));
DamageType "Normal";
Decal "None";
}
}
