CLASS pb_Daedabus : proto_fat //replaces Fatso
{ 
Default
{
	Health 850;
	Radius 48;
	Height 64;
	Scale 1.2;
	Mass 1000;
	
	Speed 8;
	damagefactor "Crush", 10.0;
	damagefactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	PainChance "Stun", 255;
	PainChance "Kick", 255;
	PainChance "ExtremePunches", 225;
	PainChance "Taunt", 255;
	PainChance "Explosive", 255;
	PainChance 40;
	BloodType "pb_blood";
	SeeSound "Daedabus/Sight";
	PainSound "Daedabus/Pain";
	DeathSound "Daedabus/Death";
	ActiveSound "Daedabus/Active";
	damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0; damagefactor "GreenBlood", 0.0;
	damagefactor "HEAD", 3;
	
	Species "BigFatAss";
	
	+DONTHARMSPECIES;
	+DONTHARMCLASS;
	MONSTER;
	+FLOORCLIP;
	+BossDeath;
	+DONTHARMCLASS;
	Obituary "%o was acidified by a Daedabus.";
	
/*	//DropItem "TimeSphere", 3;
	//DropItem "DemonStrengthRune", 5;
	//DropItem "DemonMorphRune", 3;
	//DropItem "RageSphere", 4;
	//DropItem "DoubleSphere", 4;
	//DropItem "ShieldSphere", 3;
	//DropItem "Demonpickup2", 80;
	//DropItem "Demonpickup2", 30;
	//DropItem "Demonpickup2", 250;*/
}

States
{
	Spawn:
 	Stand:
		DAED BBBBBBBBBB 10 A_Look;
	Loop;
		
	See:
	LookingForPlayer:
		TNT1 A 0 pb_monster_memory();
		DAED AA 4 A_Chase;
		TNT1 A 0 A_PlaySound("knight/step",5);
		DAED BBCCDD 4 A_Chase;
		TNT1 A 0 A_PlaySound("knight/step",8);
		DAED EEFF 4 A_Chase;
	Loop;
		

	Pain:
		DAED J 3;
		DAED J 3 A_Pain;
	Goto See;

	Pain.Kick:
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil(0.50);
		DAED J 9 A_Pain ;
		DAED J 8;
	Goto See;
		
	Pain.Explosive:
	Pain.ExtremePunches:
	Pain.SSG:
	Pain.Blackhole:
	Pain.QuadShot:
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 {self.bNOPAIN = true;}
		DA5D A 4 ThrustThingZ(0,30,0,1);
		DA5D B 4 A_Pain;
		DA5D CDDDD 4;
		DA5D C 4 A_Stop;
		DA5D BA 4;
		TNT1 A 0 {self.bNOPAIN = false;}
	Goto See;
		
	Pain.Taunt:
		TNT1 A 0;
		TNT1 A 0 A_Pain;
		TNT1 A 0 {self.bNOPAIN = true;}
		TNT1 A 0 {self.bMISSILEMORE = true;}
		TNT1 A 0 {self.bMISSILEEVENMORE = true;}
		TNT1 A 0 A_PlaySound("demon/pain");
		DA6D A 1 A_FaceTarget;
		DA6D A 10  A_Pain;
		DA6D BAC 8;
		TNT1 A 0 A_Pain;
		DA6D ABAC 8;
		TNT1 A 0 A_Pain;
		DA6D ABAC 8;
		TNT1 A 0 {self.rage = true;}
	Goto Missile;
		
	Possession:
		TNT1 A 0 A_SetInvulnerable;
		DAED J 3;
		DAED J 3 A_Pain;
 		TNT1 A 0 A_UnSetInvulnerable;
	Goto See;
		
	Pain.Stun:
		DAED J 1 A_Pain;
		DAED JJJJJJJJJJ 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		tnt1 a 0 a_jumpif(random(0, 10) < 7, "Pain.Stun");
	Goto See;
		
	Missile:
		TNT1 A 0 A_JumpIfCloser(280, "AssThrower");
		DAED F 0 A_Jump(128, "Missile2");
	AssThrower:
		TNT1 A 0 a_jumpif(rage, 1);
		DAED G 1 A_FatRaise;
		TNT1 A 0 A_PlaySound("FLMDRAW",3);
		DAED GGGGGGGGGGGG 2
		{
			A_FaceTarget();
		}
	Torch:
		TNT1 A 0 A_PlaySound("acid/spew");
		TNT1 A 0 a_spawnprojectile("GreenCloudMissile_Enemy",30,-25,10,0);
		TNT1 A 0 a_spawnprojectile("GreenCloudMissile_Enemy",30,25,0,0);
	shot:
		TNT1 A 0 {cooldown ++;}
		DAED HIG 1 BRIGHT
		{
			A_FaceTarget();
			A_SpawnItemEx("Green_Flare", 0, 0, 0, 0, 0, 0, 0, 128);
			a_spawnprojectile("GreenCloudMissile_Enemy",30,-25,10,0);
			a_spawnprojectile("GreenCloudMissile_Enemy",30,25,0,0);
		}
		TNT1 A 0 {if(cooldown > 8) setstatelabel("See");}
		TNT1 A 0 A_JumpIfCloser(280, "shot");
		DAED IG 5;
	Goto See;
		
	Missile2:
		DAED G 0 A_PlaySound("Daedabus/Attack");
		DAED GHIG 8 BRIGHT
		{
			A_FaceTarget();
			if(frame == 7 && tics > 7)
			{
				tics = 5;
				A_PlaySound("Daedabus/gun");
				int shoot_mode = random (0, 2);
				
				switch (shoot_mode)
				{
					case 0: 
						a_spawnprojectile("DaedFire",30,-25,10,0);
					break;

					case 1:
						a_spawnprojectile("DaedFire",30,25,0,0);
					break;

					case 2:
						a_spawnprojectile("DaedFire",30,-25,10,0);
						a_spawnprojectile("DaedFire",30,25,0,0);
					break;

					default : console.printf("stop using memory editor to cheat, jeez..."); break;
				}
			}
		}
		tnt1 a 0 a_jumpif(random(0, 10) < 4, "missile2");
	Goto See;
		
		
	Death.Ice:
	Death.Freeze:
	Death.Frost:
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 {self.bSHOOTABLE = false; self.bSOLID = false;}
		//TNT1 A 0 A_SpawnItem("FrozenDaedabus");
	stop;
		
	Death:
		TNT1 A 0 A_Jump(127, "Death2", "Death3");
		DA8D A 6;
		DA8D B 6 A_Scream;
		DA8D C 6 A_NoBlocking;
		DA8D DEF 5 a_spawnprojectile("MuchBlood", 15, 0, random(0, 360), 2, random(0, 160));
		DA8D F 1 A_BossDeath   ;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		DA8D F -1 simple_death_handler();
	stop;
		
	Death2:
		DA4D K 6;
		DA4D L 5 A_Scream;
		DA4D M 5 A_NoBlocking;
		DA4D NOP 5 a_spawnprojectile("MuchBlood", 15, 0, random(0, 360), 2, random(0, 160));
		DA4D Q 5;
		DA4D R 5 A_BossDeath;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		DA4D R -1;
	stop;
		
	Death3:
		DA4D A 1;
		DA4D B 6 A_Scream;
		DA4D C 6 A_NoBlocking;
		DA4D DEF 6;
		DA4D  F 1 A_BossDeath;
		DA4D F -1;
	stop;
		
	Death.cutless:
		TNT1 A 0 A_Jump(32, "Death3");
		TNT1 A 0 A_Jump(16, "DeathGutted");
	Death.Arm:
		TNT1 A 0;
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 AA 0 a_spawnprojectile("MuchBlood", 55, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		D4T1 AAAAAAAA 1 a_spawnprojectile("Brutal_LiquidBlood2", 50, 0, random(0, 360), 2, random(30, 50));
		TNT1 A 0 A_SpawnItem("DyingDaedabus01");
		TNT1 A -1;
	stop;
		
	Death.cut:
	Death.Saw:
		TNT1 A 0;
		TNT1 A 0 A_Stop;
		D4AT AB 4;
		TNT1 A 0 A_Scream;
		TNT1 O 0 A_NoBlocking;
		TNT1 AA 0 a_spawnprojectile("MuchBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("RipGuts", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_BossDeath;
		D4AT CDEF 5;
		D4AT GH 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 AAAAAAAAAAAAAAAAAA 4 a_spawnprojectile("Brutal_LiquidBlood2", 40, 0, random(0, 360), 2, random(30, 50));
		D4AT I -1;
	stop;

	Death.Tear:
	DeathGutted:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_BossDeath;
		TNT1 AAA 0 a_spawnprojectile("MuchBlood", 35, 0, random(0, 360), 2, random(0, 160));
		DA7D AA 1 a_spawnprojectile("Brutal_LiquidBlood2", 40, 0, random(0, 360), 2, random(30, 60));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("xdeath2", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("RipGuts", 25, 0, random(0, 360), 2, random(0, 160));
		DA7D BBBBBBCCCCCCCDDDDDDDEEEEEEEFFFFFFGGGGGGGHHHHHHH 1
		{
			a_spawnprojectile("Brutal_LiquidBlood2", 30, 0, random(0, 360), 2, random(30, 60));
			a_spawnprojectile("MuchBlood", 25, 0, random(0, 360), 2, random(0, 160));
		}
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		DA7D IIIIIIIIIIIIIIIIIIIIIIIIIIIIII 1 a_spawnprojectile("Brutal_LiquidBlood2", 12, 0, random(0, 360), 2, random(30, 60));
		DA7D I -1;
	stop;
		
	Death.Head:
		//TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 A 0 A_SpawnItem("DaedabusHeadExplode", 0, 50);
		TNT1 A 0 A_Jump(200, "DeathHead2");
		DA3D K 5 A_Scream;
		DA3D LLLLLMMMMMNOPQRST 2
		{
			a_spawnprojectile("Brutal_LiquidBlood2", 50, 0, random(0, 360), 2, random(30, 50));
			a_spawnprojectile("brutal_FlyingBlood", 75, 0, random(0, 360), 2, random(0, 160));
		}
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		DA3D T -1;
	stop;
		
	DeathHead2:
		D4T5 AAABBBCCC 2 a_spawnprojectile("Brutal_LiquidBlood3", 50, 0, random(0, 360), 2, random(30, 50));
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_BossDeath;
		D4T5 DDEEFFGGHHIIJJJJJJJJJJJJJJJJJJJJJ 2 a_spawnprojectile("Brutal_LiquidBlood3", 32, 0, random(0, 360), 2, random(20, 50));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		D4T5 J -1;
	stop;
		
	Death.Shotgun:
		TNT1 A 0 A_JumpIfCloser(250, 1);
		Goto Death;
		//TNT1 A 0 A_JumpIfInTargetInventory("SSGSelected", 1, "Death.Blast");
	Goto Death;

	Death.Blast:
		TNT1 AA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("xdeath2", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("RipGuts", 25, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		DA9D AAAA 2 a_spawnprojectile("Brutal_LiquidBlood2", 40, 0, random(0, 360), 2, random(30, 60));
		DA9D B 6 A_Scream;
		TNT1 A 0 a_spawnprojectile("MuchBlood", 25, 0, random(0, 360), 2, random(0, 160));
		DA9D C 6 A_NoBlocking;
		DA9D D 6 a_spawnprojectile("MuchBlood", 15, 0, random(0, 360), 2, random(0, 160));
		DA9D E 6 A_BossDeath;
		DA9D EEEEEEEEE 2 a_spawnprojectile("Brutal_LiquidBlood2", 8, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		DA9D EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 13;
		DA9D EEEEE 1 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
		DA9D E -1;
	stop;
		
	Death.SSG:
		TNT1 A 0;
		TNT1 A 0 A_Jump(96, "Death.Blast");
		TNT1 A 0 A_Stop;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_noBlocking;
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_Jump(255, "DeathSSG1", "DEathSSG2");
	DeathSSG1:
		TNT1 A 0;
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("MuchBlood", 55, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathMancubusArm", 30, 0, random(0, 360), 2, random(50, 130));
		D4T2 AAAAAAAAAAAA 2 a_spawnprojectile("Brutal_LiquidBlood2", 50, 0, random(0, 360), 2, random(30, 50));
		D4T2 BC 6;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		D4T2 D -1 simple_death_handler();
	stop;


	Death.Shrink:
		TNT1 A 1 A_PlaySound("Shrink", 3);
/*		TNT1 A 0 A_SpawnItemEx("DaedabusShrinkFX1", 0, 0,  5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("DaedabusShrinkFX2", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("DaedabusShrinkFX3", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("DaedabusShrinkFX4", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("DaedabusShrinkFX5", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("DaedabusShrinkFX6", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("DaedabusShrinkFX7", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("LilDaedabus", 1);*/
	stop;
		


	XDeath:
	Death.QuadBlast:
	Death.Explosives:
	Death.ExplosiveImpact:
	Death.Landmine:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathDaedabusEyeball", 58, 0, random(0, 360), 2, random(10, 90));
		TNT1 A 0 a_spawnprojectile("MeatDeath", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(60, 90));
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathDaedabusTorso", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathDaedabusLeg", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathDaedabusHead", 20, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("XDeath2", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("XDeath3", 20, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("XDeath1", 36, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("MuchBlood", 50, 0, random(0, 360), 2, random(0, 160));
		DA3D A 6 A_xScream;
		DA3D B 6 A_NoBlocking;
		DA3D CDE 6;
		DA3D E 1 A_BossDeath;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		DA3D EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 13;
		DA3D EEEEE 1 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
		DA3D E -1;
	stop;
		
	Death.Fire:
		TNT1 A 0 A_Jump(162, "DeathFireLong");
		FATK A 4;
		FATK B 4 A_Scream;
		FATK C 4 A_NoBlocking;
		FATK D 4;
		BF4T EF 4;
		BF4T F 1 A_BossDeath;
		TNT1 A 0 A_Playsound("props/redfire");
		CARB OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 2 a_spawnprojectile("FlameTrails", 32, 0, random(0, 360), 2, random(70, 130));
		CARB OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 10 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(70, 130));
		CARB O -1;
	stop;
		
	DeathFireLong:
		TNT1 A 0;
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("BurningFatso2", 0, 10);
	stop;
		
	Death.Desintegrate:
	Death.Plasma: Death.Plasma2:
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		CRB7 G 5 BRIGHT;
		TNT1 AAA 0 a_spawnprojectile("brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		CRB7 H 5 BRIGHT;
		EXPL AAAAAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		CRB7 IJ 5 BRIGHT;
		CARB OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 10 a_spawnprojectile("Explosion_Smoke", 1, 0, random(0, 360), 2, random(0, 160));
		CARB O -1;
	Stop;
	
	Death.SuperPlasma:
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAAAAAA 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
		XBRN BB 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
		TNT1 A 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
		XBRN CC 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
		TNT1 AAAAAAAA 0 a_spawnprojectile("PlasmaParticleX", random(42, 48), 0, random(0, 360), 2, random(0, 360));
	Stop;
	
	Death.GreenFire:
		TNT1 A 0;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAA 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("GreenFlameTrails", 50, 0, random(0, 360), 2, random(0, 360));
		XBRN AAAA 2 BRIGHT A_SpawnItem("Green_Flare",0,43);
	Stop;
	
	Death.Fatality:
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("OtherFatsoFatality2", 1);
		TNT1 A 1 A_BossDeath;
		TNT1 A 0;
	Stop;
	
	Raise:
		DAED RQPONMLK 5;
	Goto See;
}

}