



CLASS FatalizedOtherFatso: DeadFat { 
	Default {
	
	Scale 1.2;
	Health 200;
	Species "Marine";
	damagefactor "Cut", 4.0;
	damagefactor "Saw", 4.0;
	damagefactor "Tear", 4.0;
	}
States
{
	Spawn:
	tnt1 a 0 A_PlaySound("Daedabus/Sight");
    DA3D MMMNNNOOOPPPQQQRRRSSSTTT 2
    {
        a_spawnprojectile("Blood", 35, 0, random(0, 360), 2, random(0, 160));
	    a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
    }
	TNT1 AAAAAAA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
	
	DA3D TTT 2 a_spawnprojectile("Blood", 35, 0, random(0, 360), 2, random(0, 160));
	
	DA3D T -1;
	Stop;
	
	Death:
	TNT1 AA 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 A -1;
	Stop;
}
}
	
	

CLASS OtherFatsoXDeath : ACTOR { 
	Default {
	
	Radius 1;
	Height 1;
	Scale 1.2;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFACTOR 0.5;
	BounceType "Doom";
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
	Species "Marine";
	damagefactor "Cut", 4.0;
	damagefactor "Saw", 4.0;
	damagefactor "Tear", 4.0;
	}
    States
    {
	Spawn:
	TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("brutal_FlyingBlood", 35, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
	TNT1 A 0 a_spawnprojectile("brutal_FlyingBlood", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 A_SpawnItem("PB_pot");
	Death:
	TNT1 A 0;
	Stop;
}
}


CLASS FatalizedOtherFatso2: DeadFat { 
	Default {
	
	}
	States{
	Spawn:
	TNT1 A 0 A_PlaySound("Daedabus/Active",2);
	FDA1 HHHH 3  {pb_blood_and_gore_event.much_blood(self);}
	
	TNT1 A 0 A_PlaySound("flamersh",1);
	TNT1 A 0 A_SpawnItem("Green_Flare",0,10);
		TNT1 a 0 
		{
			for(int i = 0; i < 14; i++)
			{
				A_SpawnItemEx("PlasmaParticle", 0, 0, 14,(0.1)*Random(10, 40), 0,(0.1)*Random(-40, 40), Random(0, 360), 128);
				a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
			}
		}
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudLarge", 22, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudLarge", 44, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 H 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 H 2;
	
	TNT1 A 0 A_PlaySound("flamersh",1);
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 H 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 H 2;
	
	TNT1 A 0 A_PlaySound("flamersh",1);
	TNT1 A 0 A_SpawnItem("Green_Flare",0,10);
		TNT1 a 0 
		{
			for(int i = 0; i < 14; i++)
			{
				A_SpawnItemEx("PlasmaParticle", 0, 0, 14,(0.1)*Random(10, 40), 0,(0.1)*Random(-40, 40), Random(0, 360), 128);
				a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
			}
		}
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 H 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 H 2;
	
	TNT1 A 0 A_PlaySound("flamersh",1);
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 H 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 H 2;
	
	TNT1 A 0 A_PlaySound("flamersh",1);
	TNT1 A 0 A_SpawnItem("Green_Flare",0,10);
		TNT1 a 0 
		{
			for(int i = 0; i < 14; i++)
			{
				A_SpawnItemEx("PlasmaParticle", 0, 0, 14,(0.1)*Random(10, 40), 0,(0.1)*Random(-40, 40), Random(0, 360), 128);
				a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
			}
		}
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 H 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 H 2;
	TNT1 A 0 A_PlaySound("Daedabus/Pain",3);
	TNT1 A 0 A_PlaySound("flamersh",1);
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudLarge", 12, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudLarge", 22, 0, random(0, 360), 2, random(0, 160));
	FDA1 H 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 H 2;
	TNT1 A 0 A_PlaySound("Daedabus/Pain",3);
	TNT1 A 0 A_PlaySound("flamersh",1);
	TNT1 A 0 A_SpawnItem("Green_Flare",0,10);
		TNT1 a 0 
		{
			for(int i = 0; i < 14; i++)
			{
				A_SpawnItemEx("PlasmaParticle", 0, 0, 14,(0.1)*Random(10, 40), 0,(0.1)*Random(-40, 40), Random(0, 360), 128);
				a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
			}
		}
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 H 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 H 2;
	EXPL A 0 Radius_Quake(3, 60, 0, 11, 0);
	TNT1 A 0 A_PlaySound("Daedabus/Pain",3);
	TNT1 A 0 A_PlaySound("flamersh",1);
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudLarge", 12, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudLarge", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 H 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 H 2;
	TNT1 A 0 A_PlaySound("Daedabus/Pain",3);
	TNT1 A 0 A_PlaySound("flamersh",1);
	TNT1 A 0 A_SpawnItem("Green_Flare",0,10);
		TNT1 a 0 
		{
			for(int i = 0; i < 14; i++)
			{
				A_SpawnItemEx("PlasmaParticle", 0, 0, 14,(0.1)*Random(10, 40), 0,(0.1)*Random(-40, 40), Random(0, 360), 128);
				a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
			}
		}
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 H 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudSmall", 42, 0, random(0, 360), 2, random(0, 160));
	FDA1 H 2;
	goto Death;
	
	Death:
	EXPL A 0 Radius_Quake(3, 60, 0, 11, 0);
	TNT1 A 0 A_PlaySound("misc/gibbed",4,4);
	TNT1 A 0 a_spawnprojectile("MeatDeath", 0, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudLarge", 12, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("GreenCloudLarge", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0 a_spawnprojectile("GreenCloudMedium", 62, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 20, 0, random(0, 360), 2, random(50, 130));
	TNT1 AAAA 0 a_spawnprojectile("brutal_FlyingBlood", 75, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAAAA 0 a_spawnprojectile("CeilBloodSpot", 50, 0, random(0, 360), 2, random(50, 130));
	TNT1 AA 0 a_spawnprojectile("brutal_FlyingBlood", 65, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAA 0  {pb_blood_and_gore_event.much_blood(self);}
	TNT1 AAAA 0 a_spawnprojectile("XDeath4", 0, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAA 0 a_spawnprojectile("XDeath2", 0, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0  {pb_blood_and_gore_event.much_blood(self);}
	TNT1 AAAAAA 0  {pb_blood_and_gore_event.much_blood(self);}
	XDAT D 6 A_Scream;
	XDAT E 6 A_NoBlocking;
	XDAT F 6 A_BossDeath;
	TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	DA3D EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 13;
	DA3D EEEEE 1 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
	DA3D E -1;
	stop;
}
}



CLASS DaedabusFatalityHelper : ACTOR { 
	Default {
 
	Height 0;
	+NOBLOOD
	}
	States
	{
	Spawn:
	FDXE R 6;
	FDXE RR 6;
	FDXE RR 6;
	FDXE R 6 ;
	FDXE RRR 6;
	FDXE R 12 ;
	FDXE SSS 7;
	FDXE TTT 5;
	Stop;
	}
}

CLASS DaedabusFatalityHelper2 : ACTOR { 
	Default {
 
	Height 0;
	+NOBLOOD
	}
	States
	{
	Spawn:
	FDX1 A 5 ;
	FDX1 B 5 ;
	FDX1 A 5 ;
	FDX1 B 5 ;
	FDX1 AB 3;
	FDX1 C 4 ;
	FDX1 C 2 ;
	FDX1 C 2 ;
	FDX1 C 2 ;
	FDX1 C 5 ;
	FDX1 F 11;
	FDX1 F 11;
	Stop;
	}
}


CLASS DyingDaedabus01:  pb_blood_and_gore_base { 
Default {
 Scale 1.0 ;
Health 130 ;
Radius 28;
Height 56;
-CLIENTSIDEONLY
}
States
{
    Spawn:
            D4T1 AEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEE 3
            {   
                if(frame == 0) A_PlaySound("Daedabus/pain");
                a_spawnprojectile("Brutal_LiquidBlood2", 40, 0, random(0, 360), 2, random(30, 50));
            }
        TNT1 A 0 A_NoBlocking;
        TNT1 A 0 A_Scream;
        D4T1 BC 4;
        DA5D z RANDOM(300, 500);
        DA5D ZZ 1 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
        DA5D Z -1;
	Stop;
	
	Death:
	Death.Cutless:
    Death.Cut:
    Death.Saw:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_PlaySound("Daedabus/pain");
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 30, 0, random(0, 360), 2, random(50, 130));
		D4T2 AAAAAAA 2 a_spawnprojectile("Brutal_LiquidBlood2", 50, 0, random(0, 360), 2, random(30, 50));
		TNT1 A 0 A_SpawnItem("DyingDaedabus02");
	stop;
}

}	
		

		
CLASS DyingDaedabus02: DyingDaedabus01 { 
Default
{
    Scale 1.0;
    Health 130;
}
States
{
    Spawn:
        D4T2 AAAAAAAAAAAAAAAAAAAAAAAAAAAA 2 a_spawnprojectile("Brutal_LiquidBlood2", 50, 0, random(0, 360), 2, random(30, 50));
        TNT1 A 0 A_NoBlocking;
        TNT1 A 0 A_Scream;
        D4T2 BC 4;
        D4T2 D -1;
	Stop;
	
	Death:
	Death.Cutless:
    Death.Cut:
    Death.Saw:
		TNT1 A 0;
        TNT1 AAAAAA 0 a_spawnprojectile("Xdeath1", 62, 0, random(0, 360), 2, random(0, 160));
        TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 62, 0, random(0, 360), 2, random(0, 160));
        TNT1 AA 0 a_spawnprojectile("Brains2", 62, 0, random(0, 360), 2, random(0, 160));
        TNT1 AAA 0 a_spawnprojectile("Brains4", 62, 0, random(0, 360), 2, random(0, 160));
        TNT1 AA 0 a_spawnprojectile("Brains4", 62, 0, random(0, 360), 2, random(0, 160));
        TNT1 AA 0 a_spawnprojectile("MancubusEyeballs", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		D4T3 AAA 2 a_spawnprojectile("Brutal_LiquidBlood2", 50, 0, random(0, 360), 2, random(30, 50));
		TNT1 A 0 A_SpawnItem("DyingDaedabus03");
	stop;
}}		

CLASS DyingDaedabus03: DyingDaedabus02 { 
Default {
    Scale 1.0; 
    Health 130;
}
States
{
    Spawn:
        D4T3 AAAAAAAAAAAAAAAAAAAAAAAAAAAA 2 a_spawnprojectile("Brutal_LiquidBlood2", 50, 0, random(0, 360), 2, random(30, 50));
        TNT1 A 0 A_NoBlocking;
        TNT1 A 0 A_Scream;
        D4T3 B 4;
        D4T2 D -1;
	Stop;
	
	Death:
	Death.Cutless:
    Death.Cut:
    Death.Saw:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("RipGuts", 0, 40);
		TNT1 AAA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAAA 0 a_spawnprojectile("XDeath2", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath4", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathDaedabusTorso", 30, 0, random(0, 360), 2, random(40, 160));
		D4T4 AAAAAABBBC 2 a_spawnprojectile("Brutal_LiquidBlood2", 40, 0, random(0, 360), 2, random(30, 50));
        D4T4 C -1;
	stop;
}

}	





CLASS XDeathDaedabusEyeball : pb_blood_and_gore_base { 
	Default {
	
	Radius 2;
	Height 2;
	Speed 6;
	Mass 1;
	Decal "GreenBloodSpot";
	+CLIENTSIDEONLY;
	BounceFactor 0.4;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	+FLOORCLIP;
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		M4NA UVWX 4 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		M4NA Y 1;
		TNT1 A 0 A_QueueCorpse;
 	Rest:
		M4NA Y 2000;
		M4NA Y -1;
		Stop;
		
	DoNothing:
		TNT1 A 0;
		Stop;
	}
}


CLASS XDeathDaedabusHead: XDeathBullArm1 { 
	Default {
	
	-CLIENTSIDEONLY;
	Scale 0.9;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		XH37 ABCD 6;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		XH37 A 1;
		XH37 A 1 A_SpawnItem("DaedabusHead",0,0,0,1);
		Stop;
	}
}



CLASS DaedabusHead: Limbs_Base { 
	Default {
	
	damagefactor "Kick", 9.0;
	damagefactor "Melee", 9.0;
	damagefactor "SuperPunch", 9.0;
	-CLIENTSIDEONLY;
	Radius 10;
	
	Mass 12;
	Health 60;
	Scale 0.9;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		XH37 B 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		XH37 B -1;
		Stop;
		
	Death:
		TNT1 AAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains2", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains2", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains4", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains4", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 AAAAAA 0 a_spawnprojectile("SmallBrainPiece", 5, 0, random(0, 360), 2, random(60, 140));
		Stop;
	Death.Trample:
	Crush:
		//TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
		TNT1 AAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS1 B 5;
		CRS1 B 9009;
		Stop;
	Death.plasma:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL A 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0;
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		XH37 A 1 A_Pain;
		XH37 A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeathDaedabusHead", 5, 0, random(170, 190), 2, random(20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		XH37 ABCD 3;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		XH37 ABCD 6;
		XH37 I 0 A_SpawnItem("DaedabusHead");
		Stop;
		
}}


CLASS XDeathDaedabusTorso: XDeathArm1 { 
	Default {
	
	+SKYEXPLODE;
	-CLIENTSIDEONLY;
	Scale 1.2;
	Speed 9;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		M4NA IJKLMNOP 3;
		Loop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	Rest:
		M4NA QRSTTT 4;
		Loop;
	}
}

CLASS XDeathDaedabusLeg: XDeathArm1 { 
	Default {
	
	+SKYEXPLODE;
	-CLIENTSIDEONLY;
	Scale 1.2;
	Speed 9;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		M4N4 ABCDEFGH 3;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		M4N4 I -1;
		Stop;
	}
}





CLASS DaedabusHeadExplode: ZombieXDeath { 
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAAAA 0 a_spawnprojectile("Bloodmist", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("XDeathDaedabusEyeball", 0, 0, random(0, 360), 2, random(10, 90));
		//TNT1 AA 0 a_spawnprojectile("Brains4", 0, 0, random(0, 360), 2, random(10, 90));
		TNT1 AA 0 a_spawnprojectile("Brains4", 0, 0, random(0, 360), 2, random(10, 90));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPieceFast", 0, 0, random(0, 360), 2, random(10, 20));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPiece", 0, 0, random(0, 360), 2, random(10, 90));
		
		TNT1 AAA 0 a_spawnprojectile("Teeth", 0, 0, random(0, 360), 2, random(10, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(10, 90));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 90));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 10, 0, random(0, 360), 2, random(50, 90));
		TNT1 A 10;
		Stop;
}
}

















CLASS DeadDaedabus2NoArm : ACTOR { 
	Default {
	
	Radius 39;
	Height 32;
	Scale 1.2;
	+SHOOTABLE;
	-SOLID;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	-CORPSE;
	-DONTGIB;
	-TELESTOMP;
	Mass 1000;
	health 500;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	Species "Marine";
	damagefactor "Cut", 4.0;
	damagefactor "Saw", 4.0;
	damagefactor "Tear", 4.0;
	}
	States
    {
	Spawn:
	DA4D GGGGGGGGGGGGGGGGGGGGGG 12;
	DA4D GG 1 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
	DA4D G -1;
	Stop;
	Death:
	TNT1 A 0;
	TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
	DA5D X -1;
	Stop;
}
}

CLASS DeadDaedabus4NoArm : ACTOR { 
	Default {
	
	Radius 39;
	Height 32;
	Scale 1.2;
	+SHOOTABLE;
	-SOLID;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	-CORPSE;
	-DONTGIB;
	-TELESTOMP;
	Mass 1000;
	health 500;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	Species "Marine";
	damagefactor "Cut", 4.0;
	damagefactor "Saw", 4.0;
	damagefactor "Tear", 4.0;
	}
	States
    {
	Spawn:
	DA4D WWWWWWWWWWWWWWWWWWWWWWWWWWW 12;
	DA4D WW 1 A_SpawnItemEx("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
	DA4D W -1;
	Stop;
	Death:
	TNT1 A 0;
	TNT1 A 0 a_spawnprojectile("XDeathMancubusArm", 0, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
	DA4D V -1;
	Stop;
}
}