
CLASS BluePlasmaParticleSpawner : pb_particle { 
Default {
	RenderStyle "Add";
	Alpha 0.95;
	Scale 1.1;
}
States
{
	Spawn:
		TNT1 AA 0 a_spawnprojectile("BluePlasmaParticle", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 AA 0 a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
		PBEX A 4 BRIGHT;
		TNT1 A 1;
	Stop;
}
}

CLASS PlasmaParticleSpawner: BluePlasmaParticleSpawner { 
States
{
	Spawn:
		TNT1 AAAA 0 A_SpawnItemEx("PlasmaParticle", 0, 0, 14,(0.1)*Random(10, 40), 0,(0.1)*Random(-40, 40), Random(0, 360), 128);
		TNT1 AAAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 1;
		Stop;
}
}

CLASS BluePlasmaParticle : pb_particle { 
Default {
	Gravity 0.8;
	RenderStyle "Add";
	Scale 0.035;
}
States
{
	Spawn:
	Death:
		SPKB A 2 Bright A_FadeOut(0.04);
		Loop;
}
}

CLASS BluePlasmaFire: pb_particle { 
Default {
	
	+NoGravity;
	-DOOMBOUNCE;
	RenderStyle "Add";
	Scale 0.7;
	Alpha 0.9;
	Speed 0;
}
States
{
	Spawn:
	tnt1 a 0 nodelay a_jump(126, "spawn2");
		FIR5 ABCDEFGHIJKLMNOP 1 Bright A_FadeOut(0.04);
		Stop;
	spawn2:
		FIR6 ABCDEFGHIJKLMNOP 1 Bright A_FadeOut(0.04);
		Stop;
}
}




CLASS HotPlasmaGas: BluePlasmaParticle { 
Default {
	
	+NoGravity;
	-DOOMBOUNCE;
	-NOCLIP;
	-NOBLOCKMAP;
	Damage 1;
	Damagetype "Plasma";
	RenderStyle "Add";
	Scale 0.77;
	Alpha 0.8;
	Speed 20;
	Decal "Scorch";
	SeeSound "PLSTHRW";
	DeathSound "imp/shotx";
	Radius 12;
	Height 12;
}
States
{
	Spawn:
		TNT1 A 0 A_SetScale(1.20);
		TNT1 A 0 A_SpawnItemEx("FreezerTrailSparksSmall", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, 128, 0);
		FIR6 AAABB 1 BRIGHT Light("M2PlasmaLight1");
		TNT1 A 0 A_SpawnItemEx("FreezerTrailSparksSmall", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, 128, 0);
		TNT1 A 0 A_SetScale(1.35);
		FIR6 CDEFGH 1 BRIGHT Light("M2PlasmaLight1") a_spawnprojectile("BluePlasmaFire", 0, 0, 0, 2, random(-30, 30));
		TNT1 A 0 A_SpawnItemEx("FreezerTrailSparksSmall", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, 128, 0);
		TNT1 A 0 A_SetScale(1.50);
		FIR6 IJKL 1 BRIGHT a_spawnprojectile("BluePlasmaFire", 0, 0, 0, 2, random(-60, 60));
		TNT1 A 0 A_SpawnItemEx("FreezerTrailSparksSmall", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, 128, 0);
		TNT1 A 0 A_SetScale(1.75);
		FIR6 MNOP 1 Bright a_spawnprojectile("BluePlasmaFire", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAA 0 A_SpawnItemEx("FreezerTrailSparksSmall", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, 128, 0);
		Stop;
	Death:
		TNT1 A 0 A_Explode(47, 200, 0);
		TNT1 AAAA 0 A_SpawnItemEx("FreezerTrailSparksSmall", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, 128, 0);
		FIR6 BCDEFGHIJKLMNOP 1 Bright;//a_spawnprojectile("BluePlasmaFire", 0, 0, random(0, 360), 2, random(0, 360))
		Stop;
}
}


CLASS PlasmaParticleX : pb_particle { 
Default {
	Height 0;
	Radius 0;
	Mass 0;
	+Missile;
	+NoBlockMap;
	-NoGravity;
	+DontSplash;
	+DoomBounce;
	+FORCEXYBILLBOARD;
	BounceFactor 0.1;
	Gravity 0.4;
	RenderStyle "Add";
	Scale 1.0;
	//Speed 2
	Speed 2;
}
States
{
	Spawn:
		SPKB A 1 Bright;
		//TNT1 A 0 A_ChangeFlag(DOOMBOUNCE, 0);
		Goto Stand;
	Stand:
		SPKB B 2 Bright A_FadeOut(0.06);
		Loop;
	Death:
		TNT1 A 1;
		Stop;
	}
}


CLASS PlasmaParticle: BluePlasmaParticle { 
States
{
	Spawn:
	Death:
		SPKG A 2 Bright A_FadeOut(0.02);
		Loop;
}
}


CLASS PlasmaPuff: pb_puff { 
Default {
	RenderStyle "Add";
	Alpha 0.95;
	+NOBLOCKMAP;
	+NOGRAVITY;
	+CLIENTSIDEONLY;
	Scale 1.1;
}
states
{
	Spawn:
		PBEX A 0 BRIGHT;// A_SpawnItem("Blue_Flare",0,0)
		TNT1 AA 0 a_spawnprojectile("PlasmaParticleX", 12, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_SpawnItemEx("BluePlasmaParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
		//EXPL AAAA 0 a_spawnprojectile("Explosion_Smoke", 0, 0, random(0, 360), 2, random(0, 360))
		PLSE ABCDE 2 BRIGHT A_SpawnItem("Blue_Flare" ,0);
		stop;
}
}


CLASS RailgunPuff: pb_puff { 
Default {
	RenderStyle "Add";
	Alpha 0.95;
	+NOBLOCKMAP;
	+NOGRAVITY;
	+CLIENTSIDEONLY;
	Scale 1.1;
}
states
{
	Spawn:
		PBEX A 0 BRIGHT;// A_SpawnItem("Blue_Flare",0,0)
		TNT1 AA 0 a_spawnprojectile("PlasmaParticleX", 12, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_SpawnItemEx("BluePlasmaParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
		PLSE ABCDE 2 BRIGHT A_SpawnItem("Blue_Flare" ,0);
		stop;
}
}

CLASS PlasmaFog : pb_particle { 
Default {
	Radius 1;
	Height 1;
	Alpha 0.7;
	RenderStyle "Add";
	Speed 3;
	Scale 0.5;
	Gravity 0;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+DONTSPLASH;
	+MISSILE;
	+FORCEXYBILLBOARD;
	+CLIENTSIDEONLY;
}
States
{
	Spawn:
		BFOG ABCDEF 2 BRIGHT A_SpawnItem("Green_FlareMedium",0,0);
		BFOG G 2 BRIGHT;// A_SpawnItem("Blue_FlareMedium",0,0)
	Stop;
}
}


CLASS RailPuff: pb_puff { 
Default {
	renderstyle "Translucent";
	alpha 0.9;
	Scale 1.3;
	+NOBLOCKMAP;
	+NOGRAVITY;
	+NOEXTREMEDEATH;
}
states
{
	Spawn:
	Death:
	Xdeath:
	Melee:
		TNT1 A 0;
		TNT1 AAAA 0 A_SpawnItemEx("BluePlasmaParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
		//EXPL AAAA 0 a_spawnprojectile("Explosion_Smoke", 0, 0, random(0, 360), 2, random(0, 360))
		TNT1 ABCDE 2 BRIGHT A_SpawnItem("Blue_Flare" ,0);
		Stop;
}
}

CLASS ShortRailPuff: pb_puff { 
Default {
	renderstyle "Translucent";
	alpha 0.9;
	Scale 1.6;
	+NOBLOCKMAP;
	+NOGRAVITY;
	+NOEXTREMEDEATH;
	+PUFFONACTORS;
	Damagetype "SSG";
}
states
{
	Spawn:
		TNT1 A 0;
		TNT1 AAA 0 A_SpawnItemEx("BluePlasmaParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
		PLSE ABCDE 5 BRIGHT A_SpawnItem("Blue_FlareMedium",0,0);
		Stop;
}
}
