
//Original Decorate code by TheShooter7, Mechadon from realm667 Nail Gun
CLASS MGNail : ACTOR { 
	Default {
		
		Projectile;
		Radius 3;
		Height 3;
		Speed 50;
		Damage 11;
		Damagetype "Nailgun";
		Scale 0.5;
		+BloodSplatter;
		+MISSILE;
		SeeSound "";
		DeathSound "Weapons/NailHit";
		Decal BulletChip;
	}
	States
	{
		Spawn:
			NLPJ A 1 A_SpawnItemEx("NailBlur", 0, 0, 0, 1, 0, 0, 180, 128);
			NLPJ A 0();//A_PlaySound("Weapons/NailFlight")
			Loop;
		Crash:
		Death:
			TNT1 A 0();//A_PlaySound("Weapons/NailHit")
			TNT1 A 0 A_SpawnItem("HitPuff");
			NLPJ A 200;
			NLPJ AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1 A_FadeOut(0.02);
			Stop;
			
		XDeath:
			NLPJ B 0 A_PlaySound("Weapons/NailHitBleed");
			Stop;
	}
}

CLASS HotMGNail : MGNail { 
	Default {
		
		Speed 60;
		Decal Scorch;
		Damage 14;
		Scale 0.5;
		SeeSound "";
		DeathSound "Weapons/NailHit";
	}
	States
	{
		Spawn:
			NLPJ B 1 BRIGHT A_SpawnItemEx("HotNailBlur", 0, 0, 0, 1, 0, 0, 180, 128);
			NLPJ A 0();//A_PlaySound("Weapons/NailFlight")
			Loop;
		Crash:
		Death:
			TNT1 A 0();//A_PlaySound("Weapons/NailHit")
			TNT1 A 0 A_SpawnItem("HitPuff");
			TNT1 A 0 A_SpawnItemEx ("Red_Flare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			EXPL A 0 A_SpawnItem("ExplosionParticleSpawner");
			TNT1 AAAA 0 a_spawnprojectile ("HitSpark", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
			TNT1 AAAA 0 a_spawnprojectile ("HitSpark", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
			TNT1 AAAA 0 a_spawnprojectile ("HitSpark", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 360));
			NLPJ B 1 BRIGHT A_Jump(224, 2);
			TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-45, 45), random (-45, 45));
			NLPJ BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 2 BRIGHT A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
			NLPJ BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 2 A_SpawnItemEx("CasingSmoke",frandom(0.3,0.2),random(0,-1.0),0,0,0,frandom(0.5,0.1),0,SXF_CLIENTSIDE,0);
			NLPJ A 70;
			NLPJ AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1 A_FadeOut(0.02);
			Stop;
			
		XDeath:
			NLPJ B 0 A_PlaySound("Weapons/NailHitBleed");
			Stop;
	}
}

CLASS EnemyNail : ACTOR { 
	Default {
		
		Projectile;
		Radius 3;
		Height 3;
		Speed 38;
		Damage 4;
		Damagetype "Blast";
		Scale 0.7;
		+BloodSplatter;
		+MISSILE;
		SeeSound "";
		DeathSound "Weapons/NailHit";
		Decal BulletChip;
	}
	States
	{
		Spawn:
			NLPJ A 1 A_SpawnItemEx("NailBlur", 0, 0, 0, 1, 0, 0, 180, 128);
			NLPJ A 0();//A_PlaySound("Weapons/NailFlight")
			Loop;
			
		Crash:
		Death:
			TNT1 A 0();//A_PlaySound("Weapons/NailHit")
			TNT1 A 0 A_SpawnItem("HitPuff");
			NLPJ A 200;
			NLPJ AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1 A_FadeOut(0.02);
			Stop;
			
		XDeath:
			NLPJ B 0 A_PlaySound("Weapons/NailHitBleed");
			Stop;
	}
}


CLASS NailBlur        : ACTOR { 
	Default {
		
		Height 8;
		Radius 1;
		Damage 0;
		Scale 0.65;
		Speed 0.2;
		RenderStyle "Translucent";
		Alpha 0.5;
		+NoGravity;
		+DropOff;
		+NoTeleport;
	}
	States
	{
		Spawn:
			NLPJ A 1 A_FadeOut(0.4);
			Loop;
	}
}

CLASS HotNailBlur : NailBlur      { 
	Default {
		
	}
	States
	{
		Spawn:
			NLPJ B 1 BRIGHT A_FadeOut(0.4);
			Loop;
	}
}
