//Everything that can explode and hurt people goes here.
CLASS STGrenadeTimer : Inventory { 
	Default {
		
		inventory.maxamount 20;
	}
}


CLASS NewRocketExploFX : ACTOR { 
	Default {
		
		Radius 0;
		Height 0;
		RenderStyle "Add";
		Alpha 1;
		Scale 1.35;
		+NOGRAVITY;
		+NOINTERACTION;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+ForceXYBillboard;
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
		Spawn1:
			X006 ABCDEFGHIJKLMNOP 1 bright;
			stop;
		Spawn2:
			X003 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 bright;
			stop;
		Spawn3:
			X004 ABCDEFGHIJKLMNOPQ 1 bright;
			stop;
			
	}
}


CLASS RailgunImpactExplosionSFX : ACTOR { 
	Default {
		
		Radius 0;
		Height 0;
		RenderStyle "Add";
		Alpha 1;
		Scale 1.1;
		+NOGRAVITY;
		+NOINTERACTION;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+ForceXYBillboard;
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			X006 ABCDEFGHI 2 bright;
			X006 JKLMNOP 1 bright;
			stop;
			
	}
}

CLASS NewRocketExploFX_Small : NewRocketExploFX { 
	Default {
		
		Scale 0.45;
	}
}

CLASS ExcavatorExploFX : ACTOR { 
	Default {
		
		Radius 0;
		Height 0;
		RenderStyle "Add";
		Alpha 1;
		Scale 2.25;
		+NOGRAVITY;
		+NOINTERACTION;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+ForceXYBillboard;
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			X001 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 bright;
			stop;
			
	}
}

CLASS Rocket2 Replaces Rocket : ACTOR { 
	Default {
		
		Radius 6;
		Height 6;
		Projectile;
		Speed 45;
		Damage 35;
		DamageType Explosive;
		MeleeDamage 0;
		Gravity 0.00;
		Scale 0.7;
		Decal "Scorch";
		-NOGRAVITY;
		+EXTREMEDEATH;
		+BLOODSPLATTER;
		+THRUSPECIES;
		+MTHRUSPECIES;
		SeeSound "weapons/RLL";
		DeathSound "Explosion";
		Species "Marine";
		Obituary "$OB_MPROCKET";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_PlaySound("weapons/rocketloop",3,1,1);
		Fly:
			MISL A 1 Bright;
			TNT1 A 0();//A_PlaySound("DSRLAUN")
			TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
			TNT1 A 0 A_SpawnItem("RocketFlare",-20,0);
			//TNT1 A 0 A_CustomMissile ("ExplosionSmoke", 2, 0, random (70, 110), 2, random (0, 360))
			//TNT1 A 0 A_SpawnItem ("ExplosionSmoke")
			
			//TNT1 A 0 A_CustomMissile ("Explosion_Smoke", 2, 0, random (160, 210), 2, random (-30, 30))
			//TNT1 A 0 A_SpawnItem ("ExplosionSmoke")
			TNT1 A 0 A_SpawnItem ("ExplosionSmoke");
			TNT1 A 0 A_CustomMissile ("ExplosionSmoke", 2, 0, random (160, 210), 2, random (-30, 30));
			Loop;
			
		SpawnUnderwater:
			TNT1 A 0 A_ChangeFlag("NOGRAVITY", 0);
			TNT1 A 0 A_SpawnItem("RocketFlare",-20,0);
			TNT1 A 0 A_CustomMissile ("underwater_bubles", 0, 0, random (0, 360), 2, random (0, 180));
			Goto Spawn;
			
		Death:
			TNT1 A 0 A_StopSound(3);
			EXPL A 0 Radius_Quake (3, 8, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
			TNT1 A 0 A_CustomMissile("BigRicoChet");
			TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -30);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 AAA 0 A_CustomMissile ("BDExplosionparticles", 0, 0, random (0, 360), 2, random (40, 90));
			TNT1 AA 0 A_CustomMissile ("BDExplosionparticles", 0, 0, random (0, 360), 2, random (40, 90));
			TNT1 AA 0 A_CustomMissile ("BDExplosionparticles", 10, 0, random (0, 360), 2, random (40, 90));
			TNT1 AAA 0 A_CustomMissile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
			EXPL AAA 0 A_CustomMissile ("ExplosionSmokeFast22", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnItemEx ("RocketExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			//TNT1 AA 0 A_SpawnItem("SuperExpensiveParticleSpawner")
			TNT1 A 1();
			TNT1 A 0 A_SpawnItemEx ("NewRocketExploFX", 0, 0, 0);
			TNT1 A 0 A_SpawnItemEx ("LiquidExplosionEffectSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_PlaySound("FAREXPL", 3);
			TNT1 A 20;
			//TNT1 AAAAAAAAAAAAA 3 A_CustomMissile ("HeavyExplosionSmoke", 2, 0, random (0, 360), 2, random (0, 360))
			Stop;
			
	}
}

CLASS WeakRocket: Rocket2 { 
	Default {
		
		speed 20;
		damage 25;
	}
}

CLASS StunGrenadeExplosion : ACTOR { 
	Default {
		
		+NOBLOCKMAP;
		+MISSILE;
		Radius 2;
		Height 2;
		Damagetype Stun;
	}
	States    {
		Spawn:
			Goto Death;
		Death:
			TNT1 A 0 A_PlaySound("LGBOMB", 3);
			TNT1 A 0 A_SetScale(0.1,0.01);
			STFL ABCDEFGHIJKL 1 BRIGHT Light("LightningImpactLight") A_SetScale(ScaleX+0.12,ScaleY+0.12);
			TNT1 A 0 BRIGHT A_SpawnItem("LightningGunPuff_Bigger",0);
			TNT1 A 0 BRIGHT A_SpawnItem("Blue_Flare",0);
			TNT1 A 0 A_explode(2, 300,0,0,300);
			TNT1 A 0 A_PlaySound("STNBOEX", 3);
			TNT1 AAAAAAAAAAA 0 A_CustomMissile("ElectroBlastTrail3",6,0,random(0,359),CMF_AIMDIRECTION|CMF_TRACKOWNER,random(30,270));
			XELC AABBCCDDEEFF 1 Bright Light("LightningImpactLight") A_CustomMissile("ElectroBlastTrail3",6,0,random(0,359),CMF_AIMDIRECTION|CMF_TRACKOWNER,random(30,270));
Stop}}

CLASS RocketExplosion : ACTOR { 
	Default {
		
		+NOBLOCKMAP;
		+MISSILE;
		Radius 2;
		Height 2;
		Damagetype ExplosiveImpact;
	}
	States    {
		Spawn:
			Goto Death;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("WhiteShockwave");
			TNT1 A 2;
			TNT1 A 0 A_Explode(120,150);
Stop}}
		
CLASS LiquidExplosionEffectSpawner : ACTOR { 
	Default {
		
		+NOBLOCKMAP;
		+MISSILE;
		Radius 2;
		Height 2;
		Damagetype CauseWaterSplash;
	}
	States    {
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_Explode(3,9);
Stop}}
		
CLASS BarrelExplosion: RocketExplosion { 
	Default {
		
		+FORCERADIUSDMG;
	}
	States    {
		Spawn:
			Goto Death;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("WhiteShockwaveBig");
			TNT1 A 2;
			TNT1 A 0 A_Explode(160,200);
Stop}}
		
CLASS KamikazeeExplosion: RocketExplosion { 
	Default {
		
		+FORCERADIUSDMG;
	}
	States    {
		Spawn:
			Goto Death;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("WhiteShockwave");
			TNT1 A 2;
			TNT1 A 0 A_Explode(65,170);
Stop}}
		
CLASS GrenadeExplosion: RocketExplosion { 
	Default {
		
		+FORCERADIUSDMG;
	}
	States    {
		Spawn:
			Goto Death;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("WhiteShockwave");
			TNT1 A 2;
			TNT1 A 0 A_Explode(200,200);
Stop}}
		
CLASS HandGrenadeExplosion: RocketExplosion { 
	Default {
		
		+FORCERADIUSDMG;
	}
	States    {
		Spawn:
			Goto Death;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("WhiteShockwave");
			TNT1 A 2;
			TNT1 A 0 A_Explode(200,320);
Stop}}
		
CLASS MineExplosion: RocketExplosion { 
	Default {
		
		+FORCERADIUSDMG;
	}
	States    {
		Spawn:
			Goto Death;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("WhiteShockwaveBig");
			TNT1 A 2;
			TNT1 A 0 A_Explode(180,180, 0, 0, 90);
Stop}}

CLASS CyberRocket: Rocket2 { 
	Default {
		
		Speed 30;
	}
}

CLASS GrenadeMissile : ACTOR { 
	Default {
		
		Radius 4;
		Height 4;
		Speed 50;
		Damage 6;
		+MISSILE;
		+BLOODSPLATTER;
		//Damagetype "ExplosiveImpact"
		Gravity 0.7;
		
		+SKYEXPLODE;
		+DOOMBOUNCE;
		+EXPLODEONWATER;
		DamageType Kick;
		BounceFactor 0.5;
		SeeSound "Weapons/GrenadeBounce";
		DeathSound "none";
		Obituary "$OB_MPROCKET";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
			TNT1 A 0 A_GiveInventory("STGrenadeTimer", 1);
			TNT1 A 0 A_JumpIfInventory("STGrenadeTimer", 9, "Explode");
			TNT1 A 0 A_CheckFloor("Death");
			GBPJ ABCD 3 A_CustomMissile ("ExplosionSmoke", 2, 0, random (70, 110), 2, random (0, 360));
			TNT1 A 0 A_JumpIfInventory("STGrenadeTimer", 9, "Explode");
			TNT1 A 0 A_GiveInventory("STGrenadeTimer", 1);
			GBPJ EFGH 3A_CustomMissile ("ExplosionSmoke", 2, 0, random (70, 110), 2, random (0, 360));
			TNT1 A 0 A_JumpIfInventory("STGrenadeTimer", 9, "Explode");
			
			Loop;
			
		SpawnUnderwater:
			TNT1 A 0 A_GiveInventory("STGrenadeTimer", 1);
			GBPJ ABCD 3;
			TNT1 A 0 A_JumpIfInventory("STGrenadeTimer", 9, "Explode");
			TNT1 A 0 A_GiveInventory("STGrenadeTimer", 1);
			GBPJ EFGH 3;
			TNT1 A 0 A_JumpIfInventory("STGrenadeTimer", 9, "Explode");
			Goto Spawn;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory("STGrenadeTimer", 9, "Explode");
			GBPJ AAAA 3 A_CustomMissile ("ExplosionSmoke", 2, 0, random (70, 110), 2, random (0, 360));
			TNT1 A 0 A_GiveInventory("STGrenadeTimer", 1);
			Loop;
			
		XDeath:
			TNT1 A 0 A_Recoil(1);
			TNT1 A 0 A_SetAngle(random (90,-90) + angle);
			GBPJ C 1 ThrustThingZ(0,20,0,1);
			Goto Spawn;
			
		Explode:
		Death.Slime:
		Death.Fire:
		Death.Bullet:
		Death.Shotgun:
		Death.SSG:
		Death.Cutless:
		Death.Shrapnel:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("SHOOTABLE", 0);
			EXPL A 0 Radius_Quake (3, 16, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
			TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -30);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("GrenadeExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleVeryFast", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAA 0 A_CustomMissile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
			EXPL AAAAA 0 A_CustomMissile ("ExplosionSmokeFast22", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_PlaySound("Explosion", 1);
			TNT1 A 1;
			TNT1 A 0 A_PlaySound("FAREXPL", 3);
			TNT1 A 20;
			//TNT1 AAAAAAAAAAAAA 3 A_CustomMissile ("HeavyExplosionSmoke", 2, 0, random (0, 360), 2, random (0, 360))
			Stop;
	}
}




CLASS ShortGrenade: GrenadeMissile { 
	Default {
		
		-DOOMBOUNCE;
		+SLIDESONWALLS;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
			GBPJ ABCDEFGH 3 A_CustomMissile ("ExplosionSmoke", 2, 0, random (70, 110), 2, random (0, 360));
			Loop;
			
		SpawnUnderwater:
			TNT1 A 0 A_GiveInventory("STGrenadeTimer", 1);
			GBPJ ABCD 3;
			TNT1 A 0 A_JumpIfInventory("STGrenadeTimer", 1, "Explode");
			TNT1 A 0 A_GiveInventory("STGrenadeTimer", 1);
			GBPJ EFGH 3;
			TNT1 A 0 A_JumpIfInventory("STGrenadeTimer", 1, "Explode");
			Goto Spawn;
			
		Death:
		XDeath:
			TNT1 A 0;
			Goto Explode;
	}
}

///////////////////////////////////////////////////////////////////////////////PB
CLASS ExcavatorExplosion: RocketExplosion { 
	Default {
		
		+FORCERADIUSDMG;
	}
	States    {
		Spawn:
			Goto Death;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("WhiteShockwaveBig");
			TNT1 A 2;
			TNT1 A 0 A_Explode(325, 100, 0,0, 90,0,0,"None","Explosive");
			TNT1 A 0 A_Explode(200,240, 0, 0, 100);
Stop}}


CLASS StickyExplosion: RocketExplosion { 
	Default {
		
		+FORCERADIUSDMG;
	}
	States    {
		Spawn:
			Goto Death;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("WhiteShockwaveBig");
			TNT1 A 2;
			TNT1 A 0 A_Explode(175, 24, 0, 0,0,0,0,"BulletPuff","Explosive");
			TNT1 A 1 A_Explode(130,150);
Stop}}
		
CLASS ImpactGrenadeExplosion: RocketExplosion { 
	Default {
		
		+FORCERADIUSDMG;
	}
	States    {
		Spawn:
			Goto Death;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("WhiteShockwave");
			TNT1 A 2;
			TNT1 A 0 A_Explode(150,180);
Stop}}

CLASS CustomBarrelExplosion: RocketExplosion { 
	Default {
		
		+FORCERADIUSDMG;
	}
	States    {
		Spawn:
			Goto Death;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("WhiteShockwave");
			TNT1 A 2;
			TNT1 A 0 A_Explode(125,150);
Stop;}}




CLASS BouncingGrenadeHE: GrenadeMissileHE { 
	Default {
		
		+DOOMBOUNCE;
		-EXPLODEONWATER;
		+CANBOUNCEWATER;
		+FORCERADIUSDMG;
		Scale 0.25;
		Speed 60;
		BounceFactor 0.5;
		Damage 35;
		
		SeeSound "weapon/grenade";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
			//TNT1 A 0 A_CustomMissile ("Explosion_Smoke", 2, 0, random (70, 110), 2, random (0, 360))
			TNT1 A 0 A_SpawnItem ("ExplosionSmoke");
			GRNP A 1 Bright A_SpawnItem("Red_FlareVerySmall",0,0);
			Loop;
			
		SpawnUnderwater:
			GRNP A 2 Bright A_SpawnItem("Red_FlareSmall",0,0)();
			TNT1 A 0 A_CustomMissile ("underwater_bubles", 0, 0, random (0, 360), 2, random (0, 180))();
			Goto Spawn;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItemEx ("HandGrenadeExplosion",0,0,30,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -15);
			TNT1 A 0 A_CustomMissile("BigRicoChet");
			TNT1 A 0 A_SpawnItem("WhiteShockwave");
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			//TNT1 A 0 A_SpawnItemEx ("BarrelKaboom",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0)
			TNT1 A 0 A_SpawnItemEx ("NewRocketExploFX", 0, 0, 0);
			TNT1 A 0 A_SpawnItemEx ("NewGroundExplosionSmoke",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			//	TNT1 AAAAAAA 0 A_CustomMissile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360))
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
			EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
			BEXP B 0 BRIGHT A_Scream();
			TNT1 A 0 A_ALertMonsters();
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ShrapnelParticle2", 0, 0, random (0, 360), 2, random (5, 90));
			TNT1 A 0 A_Playsound("excavator/explode");
			TNT1 A 0 A_PlaySound("FAREXPL", 3);
			TNT1 A 0 A_SpawnItem("Barrel_explosion_Column");
			TNT1 A 0 A_SpawnItem("FragGrenadeExplosionSmoke");
			Stop;
			
		XDeath:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItemEx ("HandGrenadeExplosion",0,0,30,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -15);
			TNT1 A 0 A_CustomMissile("BigRicoChet");
			TNT1 A 0 A_SpawnItem("WhiteShockwave");
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("BarrelKaboom",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("NewRocketExploFX", 0, 0, 0);
			//TNT1 A 0 A_SpawnItemEx ("NewGroundExplosionSmoke",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0)
			//	TNT1 AAAAAAA 0 A_CustomMissile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360))
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
			EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
			BEXP B 0 BRIGHT A_Scream();
			TNT1 A 0 A_ALertMonsters();
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ShrapnelParticle2", 0, 0, random (0, 360), 2, random (5, 90));
			TNT1 A 0 A_Playsound("excavator/explode");
			TNT1 A 0 A_PlaySound("FAREXPL", 3);
			TNT1 A 0 A_SpawnItem("Barrel_explosion_Column");
			TNT1 A 0 A_SpawnItem("FragGrenadeExplosionSmoke");
			Stop;
	}
}

CLASS GrenadeFragExplosion: RocketExplosion { 
	Default {
		
	}
	States    {
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Explode(100,130);
Stop}}

CLASS GrenadeMissileFrag : ACTOR { 
	Default {
		
		Radius 4;
		Height 4;
		Speed 60;
		Damage 25;
		+MISSILE;
		+BLOODSPLATTER;
		+EXTREMEDEATH;
		+FORCEXYBILLBOARD;
		+CANBOUNCEWATER;
		+FORCERADIUSDMG;
		Gravity 1.2;
		Decal "Scorch";
		SeeSound "none";
		DeathSound "Explosion";
		Obituary "$OB_MPROCKET";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
			TNT1 A 0 A_CustomMissile ("Explosion_Smoke", 2, 0, random (70, 110), 2, random (0, 360));
			TNT1 A 0 A_SpawnItem ("ExplosionSmoke");
			GRNP A 2 Bright A_SpawnItem("Red_FlareSmall",0,0);
			Loop;
			
		SpawnUnderwater:
			GRNP A 2 Bright A_SpawnItem("Red_FlareSmall",0,0)();
			TNT1 A 0 A_CustomMissile ("underwater_bubles", 0, 0, random (0, 360), 2, random (0, 180))();
			Goto Spawn;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory("crutch", 1, "DeathLiquid");
			TNT1 A 0 A_JumpIfInventory("crutch", 1, "DeathLiquid");
			TNT1 A 0 A_JumpIfInventory("crutch", 1, "DeathLiquid");
			TNT1 A 0 A_JumpIfInventory("crutch", 1, "DeathLiquid");
			TNT1 A 1 A_SpawnItem ("BigRicoChet", 0, -30);
			EXPL AAA 0 A_CustomMissile ("CasingSmoke", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAA 0 A_CustomMissile ("ExplosionSmoke", 22, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("GrenadeFragExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 1;
			TNT1 AAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("SubFlakShell", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("FlackTracer", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleVeryFast", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ShrapnelParticle", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_QuakeEx(1, 1, 1, 12, 0, 420, "", 0);
			TNT1 AAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_PlaySound("FAREXPL");
			EXPL AAA 0 A_CustomMissile ("ExplosionSmoke", 0, 0, random (0, 360), 2, random (0, 360))      ();
			Stop;
			
		DeathLiquid:
			TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -30);
			EXPL AAA 0 A_CustomMissile ("CasingSmoke", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAA 0 A_CustomMissile ("ExplosionSmoke", 22, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("GrenadeFragExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 1;
			//TNT1 AA 0 A_CustomMissile ("SubFlakShell", 0, 0, random (0, 360), 2, random (0, 360))
			//TNT1 AA 0 A_CustomMissile ("FlackTracer", 0, 0, random (0, 360), 2, random (0, 360))
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleVeryFast", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_QuakeEx(1, 1, 1, 12, 0, 420, "", 0);
			TNT1 AAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_PlaySound("FAREXPL");
			EXPL AAA 0 A_CustomMissile ("ExplosionSmoke", 0, 0, random (0, 360), 2, random (0, 360))      ();
			Stop;
			
		XDeath:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -30);
			EXPL AAA 0 A_CustomMissile ("CasingSmoke", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAA 0 A_CustomMissile ("ExplosionSmoke", 22, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("GrenadeFragExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 1;
			TNT1 AAAAAAAA 0 A_CustomMissile ("SubFlakShell", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAA 0 A_CustomMissile ("FlackTracer", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleVeryFast", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ShrapnelParticle", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_QuakeEx(1, 1, 1, 12, 0, 420, "", 0);
			TNT1 AAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_PlaySound("FAREXPL");
			EXPL AAA 0 A_CustomMissile ("ExplosionSmoke", 0, 0, random (0, 360), 2, random (0, 360))      ();
			Stop;
	}
}

CLASS BouncingGrenadeFrag: GrenadeMissileHE { 
	Default {
		
		+DOOMBOUNCE;
		-EXPLODEONWATER;
		+CANBOUNCEWATER;
		+FORCERADIUSDMG;
		Speed 45;
		BounceFactor 0.5;
		SeeSound "weapon/grenade";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
			TNT1 A 0 A_CustomMissile ("Explosion_Smoke", 2, 0, random (70, 110), 2, random (0, 360));
			TNT1 A 0 A_SpawnItem ("ExplosionSmoke");
			GRNP A 2 Bright A_SpawnItem("Red_FlareSmall",0,0);
			Loop;
			
		SpawnUnderwater:
			GRNP A 2 Bright A_SpawnItem("Red_FlareSmall",0,0)();
			TNT1 A 0 A_CustomMissile ("underwater_bubles", 0, 0, random (0, 360), 2, random (0, 180))();
			Goto Spawn;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory("crutch", 1, "DeathLiquid");
			TNT1 A 0 A_JumpIfInventory("crutch", 1, "DeathLiquid");
			TNT1 A 0 A_JumpIfInventory("crutch", 1, "DeathLiquid");
			TNT1 A 0 A_JumpIfInventory("crutch", 1, "DeathLiquid");
			TNT1 A 1 A_SpawnItem ("BigRicoChet", 0, -30);
			EXPL AAA 0 A_CustomMissile ("CasingSmoke", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAA 0 A_CustomMissile ("ExplosionSmoke", 22, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("GrenadeFragExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 1;
			TNT1 AAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("SubFlakShell", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("FlackTracer", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleVeryFast", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ShrapnelParticle", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_QuakeEx(1, 1, 1, 12, 0, 420, "", 0);
			TNT1 AAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_PlaySound("FAREXPL");
			EXPL AAA 0 A_CustomMissile ("ExplosionSmoke", 0, 0, random (0, 360), 2, random (0, 360))      ();
			Stop;
			
		DeathLiquid:
			TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -30);
			EXPL AAA 0 A_CustomMissile ("CasingSmoke", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAA 0 A_CustomMissile ("ExplosionSmoke", 22, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("GrenadeFragExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 1;
			//	TNT1 AA 0 A_CustomMissile ("SubFlakShell", 0, 0, random (0, 360), 2, random (0, 360))
			//	TNT1 A 0 A_CustomMissile ("FlackTracer", 0, 0, random (0, 360), 2, random (0, 360))
			TNT1 AAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAA 0 A_CustomMissile ("ExplosionParticleVeryFast", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_QuakeEx(1, 1, 1, 12, 0, 420, "", 0);
			TNT1 AAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_PlaySound("FAREXPL");
			EXPL AAA 0 A_CustomMissile ("ExplosionSmoke", 0, 0, random (0, 360), 2, random (0, 360))      ();
			Stop;
		XDeath:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -30);
			EXPL AAA 0 A_CustomMissile ("CasingSmoke", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAA 0 A_CustomMissile ("ExplosionSmoke", 22, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("GrenadeFragExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 1;
			TNT1 AAAAAAAA 0 A_CustomMissile ("SubFlakShell", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAA 0 A_CustomMissile ("FlackTracer", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleVeryFast", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ShrapnelParticle", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_QuakeEx(1, 1, 1, 12, 0, 420, "", 0);
			TNT1 AAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_PlaySound("FAREXPL");
			EXPL AAA 0 A_CustomMissile ("ExplosionSmoke", 0, 0, random (0, 360), 2, random (0, 360))      ();
			Stop;
	}
}


/////////////////////////////////////////////////////////////////////////////////

CLASS BouncingGrenade: GrenadeMissile { 
	Default {
		
		+DOOMBOUNCE;
		+EXPLODEONWATER;
		BounceFactor 0.5;
		SeeSound "Weapons/GrenadeBounce";
	}
}

CLASS CyberDemonGrenade: BouncingGrenade { 
	Default {
		
		Speed 28;
		Damage 30;
		DamageType Explosive;
		BounceFactor 0.9;
	}
	States
	{
		Death:
			EXPL A 1 A_Explode(200,200);
			EXPL A 0 Radius_Quake (2, 16, 0, 15, 0);
			TNT1 A 0();//A_AlertMonsters
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("RocketExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 AAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleVeryFast", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAA 0 A_CustomMissile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
			EXPL AAAAAA 0 A_CustomMissile ("ExplosionSmokeFast22", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 1;
			TNT1 A 0 A_PlaySound("FAREXPL", 3);
			TNT1 AAAAAAAAAAAAA 3 A_CustomMissile ("HeavyExplosionSmoke", 2, 0, random (0, 360), 2, random (0, 360));
			Stop;
	}
}


CLASS MarinesRocket: Rocket2 { 
	Default {
		
		DamageType FriendBullet;
	}
}

CLASS JuggernautRocket: Rocket2 { 
	Default {
		
		speed 20;
		Damage (random (100, 110));
		Species "None";
		-THRUSPECIES;
		-MTHRUSPECIES;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
			
		Spawn1:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
			WYVB A 1 Bright A_SpawnItem("Red_FlareSmall22",0,0);
			TNT1 A 0 A_CustomMissile ("ExplosionSmoke", 2, 0, random (160, 210), 2, random (-30, 30));
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "SpawnCheap");
			Loop;
			
		SpawnCheap:
			TNT1 A 0;
			WYVB A 1 Bright A_SpawnItem("Red_FlareSmall22",0,0);
			Loop;
			
			
		SpawnUnderwater:
			WYVB A 1 Bright A_SpawnItem("YellowFlareSmall",0,0);
			TNT1 A 0 A_CustomMissile ("underwater_bubles", 0, 0, random (0, 360), 2, random (0, 180));
			Goto Spawn1;
			
			
		Death:
			EXPL A 0 Radius_Quake (2, 16, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "DeathCheap");
			//TNT1 A 0 A_SpawnItem("SuperExpensiveParticleSpawner")
			TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -30);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("RocketExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("NewRocketExploFX", 0, 0, 0);
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleVeryFast", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAA 0 A_CustomMissile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
			EXPL AAAAA 0 A_CustomMissile ("ExplosionSmokeFast22", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 1;
			TNT1 A 0 A_PlaySound("FAREXPL", 3);
			Stop;
			
		DeathCheap:
			EXPL A 0 Radius_Quake (2, 16, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
			TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -30);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("RocketExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("NewRocketExploFX", 0, 0, 0);
			TNT1 AAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAA 0 A_CustomMissile ("ExplosionParticleVeryFast", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAA 0 A_CustomMissile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 1;
			TNT1 A 0 A_PlaySound("FAREXPL", 3);
			Stop;
	}
}







CLASS CyberBalls : ACTOR { 
	Default {
		
		Radius 10;
		Height 8;
		Projectile;
		Speed 28;
		Damage 8;
		DamageType Explosive;
		Gravity 0.00;
		Decal "Scorch";
		Renderstyle "Add";
		-NOGRAVITY;
		+EXTREMEDEATH;
		+THRUGHOST;
		Scale 0.65;
		SeeSound "DSCANFIR";
		//SeeSound "RLANSHOT"
		DeathSound "Explosion";
		Obituary "$OB_MPROCKET";
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
			
		Spawn1:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
			WYVB A 1 Bright A_SpawnItem("Red_FlareSmall22",0,0);
			TNT1 A 0 A_CustomMissile ("ExplosionSmoke", 2, 0, random (160, 210), 2, random (-30, 30));
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "SpawnCheap");
			Loop;
			
		SpawnCheap:
			TNT1 A 0;
			WYVB A 1 Bright A_SpawnItem("Red_FlareSmall22",0,0);
			Loop;
			
			
		SpawnUnderwater:
			WYVB A 1 Bright A_SpawnItem("YellowFlareSmall",0,0);
			TNT1 A 0 A_CustomMissile ("underwater_bubles", 0, 0, random (0, 360), 2, random (0, 180));
			Goto Spawn1;
			
			
		Death:
			EXPL A 0 Radius_Quake (2, 16, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "DeathCheap");
			//TNT1 A 0 A_SpawnItem("SuperExpensiveParticleSpawner")
			TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -30);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("RocketExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("NewRocketExploFX", 0, 0, 0);
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleVeryFast", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAA 0 A_CustomMissile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
			EXPL AAAAA 0 A_CustomMissile ("ExplosionSmokeFast22", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 1;
			TNT1 A 0 A_PlaySound("FAREXPL", 3);
			Stop;
			
		DeathCheap:
			EXPL A 0 Radius_Quake (2, 16, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
			TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -30);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("RocketExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("NewRocketExploFX", 0, 0, 0);
			TNT1 AAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAA 0 A_CustomMissile ("ExplosionParticleVeryFast", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAA 0 A_CustomMissile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 1;
			TNT1 A 0 A_PlaySound("FAREXPL", 3);
			Stop;
	}
}

CLASS FastCyberballs: Cyberballs { 
	Default {
		
		Speed 40;
		Damage 30;
	}
}

CLASS CyberballTrail : ACTOR { 
	Default {
		
		Radius 0;
		Height 0;
		Alpha 1.0;
		RenderStyle "Add";
		Scale 0.9;
		Speed 2;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+DONTSPLASH;
		+MISSILE;
		+FORCEXYBILLBOARD;
		+CLIENTSIDEONLY;
		Damage 0;
		+NOINTERACTION;
	}
	States
	{
		Spawn:
			TNT1 A 2;
			WYVB CDE 1;
			
			Stop;
	}
}







CLASS MarineGrenade : ACTOR { 
	Default {
		
		Radius 4;
		Height 4;
		Speed 20;
		Damage 20;
		+MISSILE;
		+BLOODSPLATTER;
		+EXTREMEDEATH;
		+DOOMBOUNCE;
		BounceFactor 0.5;
		Damagetype "FriendBullet";
		Gravity 1.0;
		Decal "Scorch";
		SeeSound "none";
		DeathSound "Explosion";
		Obituary "$OB_MPROCKET";
		+EXTREMEDEATH;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_CustomMissile ("ExplosionSmoke", 2, 0, random (70, 110), 2, random (0, 360));
			TNT1 A 0 A_SpawnItem ("ExplosionSmoke");
			GRNP A 2 Bright A_SpawnItem("Red_FlareSmall",0,0);
			Loop;
			
			
		Death:
			EXPL A 0 Radius_Quake (2, 16, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
			TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -30);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("RocketExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 AAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleVeryFast", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAA 0 A_CustomMissile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
			EXPL AAAAAA 0 A_CustomMissile ("ExplosionSmokeFast22", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 1;
			TNT1 A 0 A_PlaySound("FAREXPL", 3);
			TNT1 AAAAAAAAAAAAA 3 A_CustomMissile ("HeavyExplosionSmoke", 2, 0, random (0, 360), 2, random (0, 360));
			Stop;
	}
}



CLASS NuclearRocket: Rocket2 { 
	Default {
		
		+FORCERADIUSDMG;
		Damagetype "ExplosiveImpact";
	}
	States
	{
		Spawn:
			
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("DSRLAUN");
			TNT1 A 0 BRIGHT A_CustomMissile("RocketBackblast", 0, 0, 180, 2, 0+pitch);
		Live:
			MISL A 1 Bright;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
			TNT1 A 0 A_SpawnItem("RocketFlare",-20,0);
			TNT1 A 0 A_SpawnItem ("ExplosionSmoke");
			TNT1 A 0 A_CustomMissile ("ExplosionSmoke", 2, 0, random (160, 210), 2, random (-30, 30));
			MISL A 1 Bright;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
			TNT1 A 0 A_SpawnItem("RocketFlare",-20,0);
			TNT1 A 0 A_SpawnItem ("ExplosionSmoke");
			TNT1 A 0 A_CustomMissile ("ExplosionSmoke", 2, 0, random (160, 210), 2, random (-30, 30));
			MISL A 1 Bright;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
			TNT1 A 0 A_SpawnItem("RocketFlare",-20,0);
			TNT1 A 0 A_SpawnItem ("ExplosionSmoke");
			TNT1 A 0 A_CustomMissile ("ExplosionSmoke", 2, 0, random (160, 210), 2, random (-30, 30));
			MISL A 1 Bright;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
			TNT1 A 0 A_SpawnItem("RocketFlare",-20,0);
			TNT1 A 0 A_SpawnItem ("ExplosionSmoke");
			TNT1 A 0 A_CustomMissile ("ExplosionSmoke", 2, 0, random (160, 210), 2, random (-30, 30));
			MISL A 1 Bright;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
			TNT1 A 0 A_SpawnItem("RocketFlare",-20,0);
			TNT1 A 0 A_SpawnItem ("ExplosionSmoke");
			TNT1 A 0 A_CustomMissile ("ExplosionSmoke", 2, 0, random (160, 210), 2, random (-30, 30));
			MISL A 1 Bright;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
			TNT1 A 0 A_SpawnItem("RocketFlare",-20,0);
			TNT1 A 0 A_SpawnItem ("ExplosionSmoke");
			TNT1 A 0 A_CustomMissile ("ExplosionSmoke", 2, 0, random (160, 210), 2, random (-30, 30));
			
			TNT1 A 0 A_ChangeFlag("NOGRAVITY", 0);
			Loop;
			
		SpawnUnderwater:
			TNT1 A 0 A_ChangeFlag("NOGRAVITY", 0);
			TNT1 A 0 A_SpawnItem("RocketFlare",-20,0);
			TNT1 A 0 A_CustomMissile ("underwater_bubles", 0, 0, random (0, 360), 2, random (0, 180));
			Goto Live;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_ChangeFlag("FORCERADIUSDMG", 1);
			TNT1 A 1;
			TNT1 A 0 A_CustomMissile ("SpawnedExplosion", 30, 0, random (0, 360), 2, random(80, 90));
			TNT1 AAA 0 A_CustomMissile ("ExplosionSpawner", 30, 0, random (0, 360), 2, 90);
			TNT1 AAA 0  A_SpawnItemEx("SpawnedExplosion", random (-400, 400), random (-400, 400), random (0, 100));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0  A_SpawnItemEx("SpawnedExplosion", random (-600, 600), random (-600, 600), random (0, 50));
			EXPL A 0 Radius_Quake (6, 6, 0, 900, 0);
			TNT1 A 0 A_Explode(2000,400, 1, 1, 1);
			BEXP B 0 BRIGHT A_Scream();
			TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnItemEx("NukeFlare", random (-800, 800), random (-800, 800), random (0, 100));
			TNT1 AAAA 2 A_SpawnItemEx("NukeFlare", random (-800, 800), random (-800, 800), random (0, 100));
			TNT1 AAAA 0 A_CustomMissile ("SpawnedExplosion", random (0, 500), 0, random (0, 360), 2, random(80, 90));
			TNT1 A 0 A_Explode(4000,800, 1, 1, 1);
			TNT1 A 2 A_SpawnItemEx("NukeFlare", 0, 0, 300);
			TNT1 A 2 A_SpawnItemEx("NukeFlare", 0, 0, 600);
			TNT1 A 2 A_SpawnItemEx("NukeFlare", 0, 0, 900);
			TNT1 A 2 A_SpawnItemEx("NukeFlare", 0, 0, 1200);
			TNT1 A 0 A_Explode(500,1400, 1, 1, 1);
			TNT1 AAA 0  A_SpawnItemEx("SpawnedExplosion", random (-200, 200), random (-200, 200), 1000);
			TNT1 AAA 0  A_SpawnItemEx("SpawnedExplosion", random (-200, 200), random (-200, 200), 1500);
			TNT1 AAAAA 2 A_SpawnItemEx("NukeFlare", 0, 0, 1200);
			TNT1 A 60;
			EXPL A 0 Radius_Quake (6, 6, 0, 900, 0);
			TNT1 A 1000;
			sTOP;
	}
}




CLASS TankShell : ACTOR { 
	Default {
		
		Radius 6;
		Height 6;
		Speed 110;
		Damage (random (1500, 1600));
		Projectile;
		+RANDOMIZE;
		+DEHEXPLOSION;
		+ROCKETTRAIL;
		+MISSILE;
		-NOGRAVITY;
		damagetype "TankShell";
		Gravity 0.4;
		SeeSound "weapons/rocklf";
		DeathSound "weapons/rocklx";
		Obituary "$OB_MPROCKET";
	}
	States
	{
		Spawn:
			MISL A 1 Bright;
			Loop;
		Death:
			MISL B 0 Bright A_Explode();
			TNT1 A 0 A_SpawnItem("TankShotExplosionImpact");
			TNT1 A 0 A_PlaySound("Explosion", 1);
			TNT1 A 0 A_SpawnItemEx ("ExplosionSplashSpawner", 0, 0, -20);
			TNT1 A 0 A_SpawnItemEx ("BarrelKaboom",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAA 0 A_CustomMissile ("ExplosionParticleVeryFast", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAA 0 A_CustomMissile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
			//EXPL AAAAA 0 A_CustomMissile ("ExplosionSmoke22", 0, 0, random (0, 360), 2, random (0, 360))
			TNT1 A 6;
			TNT1 A 0 A_PlaySound("FAREXPL", 1);
			TNT1 A 12;
			Stop;
	}
}


CLASS EnemYTankShell: TankShell { 
	Default {
		
		Speed 40;
		Damage (random (190, 200));
		+NOGRAVITY;
	}
}


CLASS TankFireEffect : ACTOR { 
	Default {
		
		Radius 1;
		Height 1;
		Speed 70;
		Damage 1;
		Projectile;
		+RANDOMIZE;
		+MISSILE;
	}
	States
	{
		Spawn:
			TNT1 A 2;
			Goto Death;
		Death:
			TNT1 A 0;
			TNT1 A 0 Radius_Quake(6, 12, 0, 4, 0);
			TNT1 AAAAA 0 A_SpawnItem("Red_Flare");
			TNT1 AAAAA 0 A_CustomMissile ("ExplosionSmoke", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 1 BRIGHT;
			TNT1 AAAAA 0 A_SpawnItem("Red_Flare");
			TNT1 A 0 A_Stop();
			TNT1 A 0 A_Recoil(-5);
			TKFL A 5 BRIGHT;
			Stop;
	}
}


CLASS TankShotExplosionImpact : ACTOR { 
	Default {
		
		damagetype "ExplosiveImpact";
		+MISSILE;
		+NOCLIP;
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_Explode(200, 400);
			Stop;
	}
}
