CLASS HasLeech : Inventory {inventory.maxamount 1} { 
	Default {
	
	ACTOR LeechGrenade: CustomInventory 
		
		Game Doom;
		Scale 0.45;
		+DONTGIB;
		+FLOORCLIP;
		Inventory.PickupMessage "What the fuck is this thing..?"();
		Inventory.PickupSound "SiphonGrowl";
	}
	States
	{
	Spawn:
		FLSP BAFEFA 6();
		Loop;
		
	Pickup:
		TNT1 A 0 A_GiveInventory("HasLeech",1);
		TNT1 A 20;
		Stop;
		
}
}

CLASS HandGrenadeAmmo : Ammo { 
	Default {
	
	Inventory.Amount 1;
	Inventory.MaxAmount 6;
	Ammo.BackPackAmount 1;
	Ammo.BackPackMaxAmount 12;
	Inventory.PickUpMessage "";
	Inventory.Icon PGRND0;
	Scale 0.45;
	}
   States
   {
	Spawn:
		PGRN D -1;
		Stop;
}
}

CLASS MineAmmo : Ammo { 
	Default {
	
	Radius 10;
	Inventory.Amount 1;
	Inventory.MaxAmount 6;
	Ammo.BackpackAmount 3;
	Ammo.BackpackMaxAmount 12;
	Inventory.PickupMessage "Picked up a proximity mine";
	Inventory.Icon "";
	Inventory.PickupSound "GRNPIN";
	Scale 0.35;
	}
States
{
	Spawn:
		XPFP A -1;
		Loop;
}
}

CLASS StunGrenadeAmmo : Ammo { 
	Default {
	
	Inventory.Amount 1;
	Inventory.MaxAmount 6;
	Ammo.BackPackAmount 1;
	Ammo.BackPackMaxAmount 12;
	Inventory.PickUpMessage "Picked up a stun grenade";
	Inventory.Icon STNGA0;
	Scale 0.3;
	}
   States
   {
	Spawn:
		STNG A -1;
		Stop;
}
}

CLASS HandGrenade: CustomInventory { //23167
	Default {
	
	Game Doom;
	Scale 0.45;
	+DONTGIB;
	+FLOORCLIP;
	Inventory.PickupMessage "You got a UAC-M26 Frag Grenade";
	Inventory.PickupSound "GRNPIN";
	}
	States
	{
	Spawn:
		PGRN D 2();
		Loop;
		
	Pickup:
		TNT1 A 0 A_GiveInventory("HandGrenadeAmmo",1);
		TNT1 A 20;
		Stop;
		
}
}


CLASS DropedGrenade : ACTOR { 
	Default {
	
	Radius 8;
	Height 10;
	Scale 0.45;
	Speed 1;
	Mass 1;
	gravity 1;
	Decal none;
	+MOVEWITHSECTOR;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MISSILE;
	}
    States
    {
	Spawn:
		TNT1 A 1 NoDelay A_JumpIf(ACS_NamedExecuteWithResult("CheckTraditional")==1,"ReplaceTraditional");
		TNT1 AA 1;
		TNT1 AA 1;
		Goto Death;
		
	Death:
		TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("CheckTraditional")==1,"ReplaceTraditional");
		TNT1 A 1 ACS_ExecuteAlways(796, 0, 0, 0, 0);//Check if Vanilla Mode is activated
		TNT1 A 1();
		TNT1 AA 1;
		TNT1 AA 1;
		TNT1 A 0 A_SpawnItemEx("HandGrenade",0,0,0,0,0,0,0,288);
		Stop;
		
	ReplaceVanilla:
		TNT1 A 0 A_JumpIf(ACS_NamedExecuteWithResult("CheckTraditional")==1,"ReplaceTraditional");
		TNT1 A 0 A_SpawnItemEx("HandGrenade",0,0,0,0,0,0,0,288);
		Stop;
		
	ReplaceTraditional:
		TNT1 A 2();
		Stop;
		
}
}

//Revamped Proximity mines, courtesy from Brutal Hellfest!!
CLASS ThrownProxMine : ACTOR { 
	Default {
	
	Radius 10;
	Height 10;
	Speed 15;
	Damage 0;
	PROJECTILE;
	BounceType "Doom";
	BounceFactor 0.3;
	BounceCount 3;
	Gravity 0.95;
	SeeSound "MINE001";
	DeathSound "MINE002";
	-NOGRAVITY;
	+TELESTOMP;
	+THRUGHOST;
	+THRUACTORS;
	-NOTELEPORT;
	-BLOODSPLATTER;
	+CANNOTPUSH;
	+FORCERADIUSDMG;
	+EXPLODEONWATER;
	+FIXMAPTHINGPOS;
	Species "Marine";
	+DontHurtSpecies;
	+ThruSpecies;
	Scale 0.35;
	}
    States
    {
	Spawn:
		TNT1 A 0();
		TNT1 A 0 ThrustThingZ(0,random(12,14),0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0();//A_SpawnItem ("Red_FlareSpawn",0,5)
		XPFP A 1;
		TNT1 A 0 A_ChangeFlag ("THRUACTORS",0);
		Goto Spawn+2;
	Death:
	XDeath:
		TNT1 A 0 A_SpawnItemEx("GroundProxMine", 0, 0, 0, 0, 0, 0, 0,SXF_NOCHECKPOSITION,0);
		Stop;
}
}

CLASS GroundProxMine : SwitchableDecoration { 
	Default {
	
	Radius 10;
	Height 6;
	Damage 0;
	-SHOOTABLE;
	-SOLID;
	+NORADIUSDMG;
	+FLOORCLIP;
	+FRIENDLY;
	+FIXMAPTHINGPOS;
	-EXPLODEONWATER;
	+MOVEWITHSECTOR;
	+NOBLOOD;
	+NOICEDEATH;
	+DONTRIP;
	+THRUACTORS;
	+LOOKALLAROUND;
	+QUICKTORETALIATE;
	
	+USESPECIAL;
	Activation THINGSPEC_Activate;
	Species "Marine";
	+MTHRUSPECIES;
	+THRUSPECIES;
	+DontHurtSpecies;
	+DontHarmSpecies;
	//+ThruSpecies
	Mass 1000000;
	Health 10;
	Scale 0.35;
	PainChance "Kick", 255;
	PainChance "ExtremePunches", 255;
	damagefactor "Normal", 1.35;
	damagefactor "Melee", 99;
	damagefactor "Kick", 99;
	damagefactor "Avoid", 0.0;
	damagefactor "ExplosiveImpact", 0.0;
	damagefactor "Explosive", 0.0;
	damagefactor "Landmine", 0.0;
	damagefactor "Trample", 0.0;
	damagefactor "Blood", 0.0    damagefactor "GreenBlood", 0.0    damagefactor "BlueBlood", 0.0    damagefactor "Taunt", 0.0    damagefactor "KillMe", 0.0  damagefactor "Avoid", 0.0  damagefactor "Taunt", 0.0;
	Damagetype ExplosiveImpact;
	}
States    {
	
	Death.Kick:
	Death.ExtremePunches:
	Death.ExplosiveImpact:
	Pain.Kick:
	Pain.ExtremePunches:
		TNT1 A 0();//A_Pain
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile ("ThrownProxMine", 5, 0, random (170, 190), 2, random (20, 40));
		Stop;
		
	Active:
		TNT1 A 0 A_PlaySound ("Weapons/StickyBombTick");
		TNT1 A 0 A_SpawnItem ("Green_FlareSpawn",0,6);
		XPFP A 6 Bright;
		TNT1 A 0 A_SpawnItem ("Green_FlareSpawn",0,6);
		TNT1 A 0 A_PlaySound ("Weapons/StickyBombTick");
		XPFP A 6 Bright;
		TNT1 A 0 A_PlaySound ("Weapons/StickyBombTick");
		TNT1 A 0 A_SpawnItem ("Green_FlareSpawn",0,6);
		XPFP A 6 Bright;
		XPFP A 4();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_ChangeFLag ("SHOOTABLE", 0);
		TNT1 A 0 A_SpawnItemEx ("MineAmmo",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0;
		Stop;
		
	DontTriggerOnFriendly:
		TNT1 A 0;
		TNT1 A 0 A_ClearTarget();
	Spawn:
		TNT1 A 0;
		XPFP A 10;
		TNT1 A 0 A_ChangeFlag ("SHOOTABLE",1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		XPFP AAAA 8 A_LookEx(LOF_NOSOUNDCHECK,0,160,0,0,"Death");
		TNT1 A 0 A_PlaySound ("Weapons/StickyBombTick");
		TNT1 A 0 A_SpawnItem ("Red_FlareSpawn",0,6);
		XPFP A 1 A_LookEx(LOF_NOSOUNDCHECK,0,160,0,0,"Death");
		TNT1 A 0 A_SpawnItem ("Red_FlareSpawn",0,6);
		XPFP A 1 A_LookEx(LOF_NOSOUNDCHECK,0,160,0,0,"Death");
		TNT1 A 0 A_SpawnItem ("Red_FlareSpawn",0,6);
		XPFP A 1 A_LookEx(LOF_NOSOUNDCHECK,0,160,0,0,"Death");
		TNT1 A 0 A_SpawnItem ("Red_FlareSpawn",0,6);
		XPFP A 1 A_LookEx(LOF_NOSOUNDCHECK,0,160,0,0,"Death");
		TNT1 A 0 A_SpawnItem ("Red_FlareSpawn",0,6);
		XPFP A 1 A_LookEx(LOF_NOSOUNDCHECK,0,160,0,0,"Death");
		TNT1 A 0 A_SpawnItem ("Red_FlareSpawn",0,6);
		XPFP A 1 A_LookEx(LOF_NOSOUNDCHECK,0,160,0,0,"Death");
		TNT1 A 0 A_SpawnItem ("Red_FlareSpawn",0,6);
		XPFP A 1 A_LookEx(LOF_NOSOUNDCHECK,0,160,0,0,"Death");
		TNT1 A 0 A_SpawnItem ("Red_FlareSpawn",0,6);
		XPFP A 1 A_LookEx(LOF_NOSOUNDCHECK,0,160,0,0,"Death");
		Goto Spawn+3;
		
		
	Death:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "DontTriggerOnFriendly");
		TNT1 A 0 A_PlaySound ("Weapons/StickyBombTick");
		TNT1 A 0 A_SpawnItem ("Red_FlareSpawn",0,9);
		XPFP A 4 Bright;
		TNT1 A 0 A_SpawnItem ("Red_FlareSpawn",0,9);
		TNT1 A 0 A_PlaySound ("Weapons/StickyBombTick");
		XPFP A 4 Bright;
		TNT1 A 0 A_PlaySound ("Weapons/StickyBombTick");
		TNT1 A 0 A_SpawnItem ("Red_FlareSpawn",0,9);
		XPFP A 4 Bright;
		TNT1 A 0 A_PlaySound ("Weapons/StickyBombTick");
		TNT1 A 0 A_SpawnItem ("Red_FlareSpawn",0,9);
		XPFP A 4 Bright;
		
		EXPL A 0 Radius_Quake (2, 54, 0, 15, 0);
		TNT1 A 0 A_ChangeFlag ("FLOORCLIP", 0);
		TNT1 A 0 A_AlertMonsters();
		
		TNT1 A 0 A_PlaySound("Explosion",3);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("MineExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("NewGroundExplosionSmoke",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAA 0 a_spawnprojectile ("FireworkSFXType1", 0, 0, random (0, 360), 2, random (30, 60));
		TNT1 AAA 0 a_spawnprojectile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAAAAA 0 a_spawnprojectile ("ExplosionParticleVeryFast", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAAA 0 a_spawnprojectile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
		EXPL AAAAAA 0 a_spawnprojectile ("ExplosionSmokeFast22", 0, 0, random (0, 360), 2, random (0, 360));
		//TNT1 A 0 A_SpawnItem("FragGrenadeExplosion")
		
		TNT1 A 0;
		
		TNT1 A 0 A_Explode(210,310, XF_HURTSOURCE);
		
		TNT1 A 0 A_Explode(190,170, XF_HURTSOURCE);
		
		TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -15);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("BarrelExplosion",0,0,30,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("BarrelKaboom",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAAAAA 0 a_spawnprojectile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAA 0 a_spawnprojectile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
		EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
		BEXP B 0 BRIGHT A_Scream();
		TNT1 A 0 A_ALertMonsters();
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("ShrapnelParticle2", 0, 0, random (0, 360), 2, random (5, 90));
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 A 0 A_Playsound("excavator/explode", 1);
		TNT1 A 0 A_SpawnItem("Barrel_explosion_Column");
		TNT1 AAAAA 1 a_spawnprojectile ("ExplosionSmoke", 1, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0;
		TNT1 A 1 A_Stop();
		Stop;
		
}
}

CLASS GrenadeTime : Inventory { 
	Default {
	
	inventory.maxamount 6;
	}
}
CLASS SparkSpawner : ACTOR { 
	Default {
	
	Speed 10;
	}
	States
	{
	Spawn:
		TNT1 AAAA 1;
		{
			a_spawnprojectile("HitSpark",0,0,frandom(0,359),2,frandom(-1,50));
			a_spawnprojectile("HitSpark",0,0,frandom(0,359),2,frandom(-1,50));
			a_spawnprojectile("HitSpark",0,0,frandom(0,359),2,frandom(-1,50));
			a_spawnprojectile("HitSpark",0,0,frandom(0,359),2,frandom(-1,50));
	}
	Stop;
}
}

CLASS ThrownGrenade1 : ACTOR { 
	Default {
	
	Radius 2;
	Height 3;
	Projectile;
	Speed 30;
	Damage 0;
	Gravity 0.7;
	Scale 0.2;
	Projectile;
	+MISSILE;
	-NOGRAVITY;
	-BLOODSPLATTER;
	-EXTREMEDEATH;
	+EXPLODEONWATER;
	+SKYEXPLODE;
	+DOOMBOUNCE;
	+FLOORCLIP;
	+DONTGIB;
	Species "Marine";
	+MTHRUSPECIES;
	+THRUSPECIES;
	+DontHurtSpecies;
	+DontHarmSpecies;
	+NoExtremeDeath;
	DamageType "ExplosiveImpact";
	BounceFactor 0.5;
	WallBounceFactor 0.25;
	Health 5;
	SeeSound "GBOUNCE";
	DeathSound "none";
	Obituary "%o ate %k grenade.";
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("TIMGRN", 5,1,1);
		GRND ABCDEFGA 2;
		TNT1 A 0 A_StopSound(5);
		TNT1 A 0 A_PlaySound("ALRTGRN", 6,1,1);
		TNT1 A 0 A_GiveInventory("GrenadeTime", 1);
		TNT1 A 0 A_JumpIfInventory("GrenadeTime", 3, "Explode");
		Loop;
		
	Death:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("TIMGRN", 5,1,1);
		GRND G 17;
		TNT1 A 0 A_StopSound(5);
		TNT1 A 0 A_PlaySound("ALRTGRN", 6,1,1);
		TNT1 A 0 A_GiveInventory("GrenadeTime", 1);
		TNT1 A 0 A_JumpIfInventory("GrenadeTime", 3, "Explode");
		Loop;
		
	Explode:
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_StopSound(6);
		//TNT1 A 0 A_SpawnItem("FragGrenadeExplosion")
		
		TNT1 A 0;
		TNT1 A 0();
		TNT1 A 0 A_Explode(180,180, XF_HURTSOURCE);
		TNT1 A 0 A_SpawnItemEx ("HandGrenadeExplosion",0,0,30,0,0,0,0,SXF_NOCHECKPOSITION,0);
		
		TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -15);
		TNT1 A 0 a_spawnprojectile("BigRicoChet");
		TNT1 A 0 A_SpawnItem("WhiteShockwave");
		TNT1 A 0 a_spawnprojectile("SparkSpawner",0,0,frandom(0,359),2,-15);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("BarrelKaboom",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("NewGroundExplosionSmoke",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAAAAA 0 a_spawnprojectile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile ("HitSpark", 0, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAA 0 a_spawnprojectile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
		EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
		TNT1 AAAA 0 a_spawnprojectile ("HitSpark", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 160));
		TNT1 AAAA 0 a_spawnprojectile ("HitSpark", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 160));
		TNT1 AAAA 0 a_spawnprojectile ("HitSpark", 2, 0, frandom(0,1)*frandom (0, 360), 2, frandom(0,1)*frandom (30, 160));
		BEXP B 0 BRIGHT A_Scream();
		TNT1 A 0 A_ALertMonsters();
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("ShrapnelParticle2", 0, 0, random (0, 360), 2, random (5, 90));
		TNT1 A 0 A_Playsound("excavator/explode");
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 A 0 A_SpawnItem("Barrel_explosion_Column");
		TNT1 A 0 A_SpawnItem("FragGrenadeExplosionSmoke");
		Stop;
}
}

CLASS FragGrenadeExplosion : ACTOR { 
	Default {
	
	+NOBLOCKMAP;
	+MISSILE;
	Damagetype ExplosiveImpact;
	DeathSound "Explosion";
	}
States    {
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -15);
		TNT1 A 0 A_SpawnItem("WhiteShockwave");
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("BarrelExplosion",0,0,30,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("BarrelKaboom",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAAAAA 0 a_spawnprojectile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAA 0 a_spawnprojectile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
		EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
		BEXP B 0 BRIGHT A_Scream();
		TNT1 A 0 A_ALertMonsters();
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("ShrapnelParticle2", 0, 0, random (0, 360), 2, random (5, 90));
		TNT1 A 0 A_Playsound("excavator/explode", 1);
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 A 0 A_SpawnItem("Barrel_explosion_Column");
		TNT1 AAAAAAAAAAAAAAA 8 a_spawnprojectile ("ExplosionSmoke", 1, 0, random (0, 360), 2, random (50, 130));
Stop}}
		
CLASS FragGrenadeExplosionSmoke : ACTOR { 
	Default {
	
	+NOBLOCKMAP;
	+MISSILE;
	}
States    {
	Spawn:
		TNT1 AAAAAAAAAAAAAAA 8 a_spawnprojectile ("ExplosionSmoke", 1, 0, random (0, 360), 2, random (50, 130));
Stop}}

CLASS HandGrenadeAnother: ThrownGrenade1 { 
	Default {
	
	+BOUNCEONFLOORS;
	+BOUNCEONWALLS;
	+BOUNCEONCEILINGS;
	-BOUNCEONACTORS;
	-ALLOWBOUNCEONACTORS;
	BounceFactor 0.600;
	BounceSound "grenade/bounce";
	}
}

CLASS EnemyThrownGrenade : HandGrenadeAnother { 
	Default {
	
	+ALLOWBOUNCEONACTORS;
	+BOUNCEONACTORS;
	+NOEXTREMEDEATH;
	+DONTHURTSPECIES;
	Species "Zombieman";
	+MTHRUSPECIES;
	+THRUSPECIES;
	Damage 0;
	// -ALLOWBOUNCEONACTORS
	Speed 16;
	}
   States
   {
	Explode:
		TNT1 A 0 A_SpawnItemEx("FootStep6", 0, 0, 40, 0, 0);
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_Fall();
		//	TNT1 A 0 A_ChangeFlag("NOEXTREMEDEATH", 0)
		TNT1 A 0 A_ChangeFlag("ALLOWBOUNCEONACTORS", 0);
		TNT1 A 0 A_ChangeFlag("NOGRAVITY", 0);
		TNT1 A 0 A_ChangeFlag("THRUACTORS", 1);
		GRND G 25;
		TNT1 A 0 A_StopSound(6);
		EXPL A 0 Radius_Quake (2, 16, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
		TNT1 A 0 A_SpawnItem("WhiteShockwave");
		TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -30);
		TNT1 A 0 A_SpawnItemEx ("NewGroundExplosionSmoke",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("BarrelKaboom",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAA 0 a_spawnprojectile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAAAAA 0 a_spawnprojectile ("ExplosionParticleVeryFast", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAAA 0 a_spawnprojectile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
		EXPL AAAAAA 0 a_spawnprojectile ("ExplosionSmokeFast22", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 0 A_Explode(25, 180, 0);
		TNT1 A 0 A_Explode(18, 75, 1);
		TNT1 A 1;
		TNT1 A 0 A_Playsound("excavator/explode", 1);
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 AAAAAAAAAAAAA 3 a_spawnprojectile ("HeavyExplosionSmoke", 2, 0, random (0, 360), 2, random (0, 360));
		Stop;
}
}

CLASS BigBrutalExplode : ACTOR { 
	Default {
	
	}
States
{
	Spawn:
		NULL A 0 A_PlaySound("Explosion");
		TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -30);
		NULL A 0 a_spawnprojectile("FootStep6", 0, 0, 150);
		NULL A 0 a_spawnprojectile("FootStep6", 0, 0, -150);
		NULL A 0 a_spawnprojectile("FootStep6", 0, 0, -30);
		NULL A 0 a_spawnprojectile("FootStep6", 0, 0, 30);
		NULL A 0 a_spawnprojectile("FootStep6", 0, 0, -60);
		NULL A 0 a_spawnprojectile("FootStep6", 0, 0, 60);
		NULL A 0 a_spawnprojectile("FootStep6", 0, 0, -90);
		NULL A 0 a_spawnprojectile("FootStep6", 0, 0, 90);
		NULL A 0 a_spawnprojectile("FootStep6", 0, 0, -120);
		NULL A 0 a_spawnprojectile("FootStep6", 0, 0, 120);
		EXPL AAA 0 a_spawnprojectile ("CasingSmoke", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAAAA 0 a_spawnprojectile ("ExplosionSmoke", 22, 0, random (0, 360), 2, random (0, 360));
		EXPL A 0 A_Explode();
		TNT1 AAAAAA 0 a_spawnprojectile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile ("ExplosionParticleHeavy", 0, 0, random (0, 180), 2, random (0, 180));
		TNT1 A 0 A_QuakeEx(1, 1, 1, 12, 0, 420, "", 0);
		TNT1 AAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
		EXPL AAA 0 a_spawnprojectile ("CasingSmoke", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAAA 1 a_spawnprojectile ("CasingSmoke", 2, 0, random (0, 360), 2, random (0, 360));
		
		TNT1 AAAAAAAAAAAAAA 1 a_spawnprojectile ("CasingSmoke", 2, 0, random (0, 360), 2, random (0, 360));
		Stop;
}
}

CLASS ThrownGrenade2 : HandGrenadeAnother { 
	Default {
	
	Speed 2;
	}
}

CLASS ThrownGrenade3 : HandGrenadeAnother { 
	Default {
	
	Speed 3;
	}
}

CLASS ThrownGrenade4 : HandGrenadeAnother { 
	Default {
	
	Speed 4;
	}
}

CLASS ThrownGrenade5 : HandGrenadeAnother { 
	Default {
	
	Speed 5;
	}
}

CLASS ThrownGrenade6 : HandGrenadeAnother { 
	Default {
	
	Speed 6;
	}
}

CLASS ThrownGrenade7 : HandGrenadeAnother { 
	Default {
	
	Speed 7;
	}
}

CLASS ThrownGrenade8 : HandGrenadeAnother { 
	Default {
	
	Speed 8;
	}
}

CLASS ThrownGrenade9 : HandGrenadeAnother { 
	Default {
	
	Speed 9;
	}
}

CLASS ThrownGrenade10 : HandGrenadeAnother { 
	Default {
	
	Speed 10;
	}
}

CLASS ThrownGrenade11 : HandGrenadeAnother { 
	Default {
	
	Speed 11;
	}
}

CLASS ThrownGrenade12 : HandGrenadeAnother { 
	Default {
	
	Speed 12;
	}
}

CLASS ThrownGrenade13 : HandGrenadeAnother { 
	Default {
	
	Speed 13;
	}
}

CLASS ThrownGrenade14 : HandGrenadeAnother { 
	Default {
	
	Speed 14;
	}
}

CLASS ThrownGrenade15 : HandGrenadeAnother { 
	Default {
	
	Speed 15;
	}
}

CLASS ThrownGrenade16 : HandGrenadeAnother { 
	Default {
	
	Speed 16;
	}
}

CLASS ThrownGrenade17 : HandGrenadeAnother { 
	Default {
	
	Speed 17;
	}
}

CLASS ThrownGrenade18 : HandGrenadeAnother { 
	Default {
	
	Speed 18;
	}
}

CLASS ThrownGrenade19 : HandGrenadeAnother { 
	Default {
	
	Speed 19;
	}
}

CLASS ThrownGrenade20 : HandGrenadeAnother { 
	Default {
	
	Speed 20;
	}
}

CLASS ThrownGrenade21 : HandGrenadeAnother { 
	Default {
	
	Speed 21;
	}
}

CLASS ThrownGrenade22 : HandGrenadeAnother { 
	Default {
	
	Speed 22;
	}
}

CLASS ThrownGrenade23 : HandGrenadeAnother { 
	Default {
	
	Speed 23;
	}
}

CLASS ThrownGrenade24 : HandGrenadeAnother { 
	Default {
	
	Speed 24;
	}
}

CLASS ThrownGrenade25 : HandGrenadeAnother { 
	Default {
	
	Speed 25;
	}
}

CLASS ThrownGrenade26 : HandGrenadeAnother { 
	Default {
	
	Speed 26;
	}
}

CLASS ThrownGrenade27 : HandGrenadeAnother { 
	Default {
	
	Speed 27;
	}
}

CLASS ThrownGrenade28 : HandGrenadeAnother { 
	Default {
	
	Speed 28;
	}
}

CLASS ThrownGrenade29 : HandGrenadeAnother { 
	Default {
	
	Speed 29;
	}
}

CLASS ThrownGrenade30 : HandGrenadeAnother { 
	Default {
	
	Speed 30;
	}
}

CLASS ThrownStunGrenade : ThrownGrenade1 { 
	Default {
	
	Speed 25;
	Damage 0;
	Gravity 0.9;
	Scale 0.6;
	DamageType Stun;
	BounceFactor 0.3;
	WallBounceFactor 0.2;
	Health 5;
	SeeSound "StunGrenadeBounce";
	DeathSound "none";
	Obituary "%o ate %k grenade.";
	+ROLLSPRITE;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("StunGrenadeLoop", 5,0.4,1);
		STNG AAAAAAAAAAAA 1 A_SetRoll(roll+20);
		TNT1 A 0 A_GiveInventory("GrenadeTime", 1);
		TNT1 A 0 A_JumpIfInventory("GrenadeTime", 3, "Death");
		Loop;
		/*
				Death:
					TNT1 A 0
					STNG Z 12 //A_SetRoll(roll)/
					TNT1 A 0 A_GiveInventory("GrenadeTime", 1)
					TNT1 A 0 A_JumpIfInventory("GrenadeTime", 3, 1)
					Loop
					TNT1 A 0 A_StopSound(5)
					TNT1 A 0 A_PlaySound("StunGrenadeDetonate", 6,1,1)
					STNG Z 12 //A_SetRoll(roll)/
					Goto ExplodeZ
					*/
		
	ExplodeZ:
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_SpawnItemEx ("StunGrenadeExplosion",0,0,1,0,0,0,0,SXF_NOCHECKPOSITION,0);
		STNG Z 15 A_SetRoll(roll);
	Fade:
		STNG ZZZZZZZZZZ 1 A_FadeOut(0.1);
		Loop;
		
	Death:
		TNT1 A 0 A_StopSound(5);
		TNT1 A 0 A_PlaySound("StunGrenadeDetonate", 6,1,1);
		STNG Z 12();//A_SetRoll(roll)
		TNT1 A 0 A_SpawnItemEx ("StunGrenadeExplosion",0,0,1,0,0,0,0,SXF_NOCHECKPOSITION,0);
		Stop;
}
}

