CLASS SuperGoreSpawner : ACTOR { 
	Default {
		
		Projectile;
		+RANDOMIZE;
		+MISSILE;
		+FORCEXYBILLBOARD;
		// +BLOODSPLATTER 
		+THRUACTORS;
		Decal "BloodSuper";
		damage 0;
		radius 2;
		height 0;
		speed 10;
		renderstyle "Add";
		alpha 0.9;
		scale .15;
		gravity 0.7;
		-NOGRAVITY;
	}
	states
	{
		Spawn:
			//TNT1 AAAAAAAA 3 A_SpawnItem("SuperGore")
			Stop;
		Death:
			Stop;
		XDeath:
			TNT1 A 0;
			Stop;
	}
}

CLASS SuperGore : ACTOR { 
	Default {
		
		Decal "BloodSplat";
		Alpha 0.45;
		+FORCEXYBILLBOARD;
		+GHOST;
		+NOBLOCKMAP;
		Gravity 0.05;
		+DontSplash;
		-EXPLODEONWATER;
		-ALLOWPARTICLES;
		+CLIENTSIDEONLY;
		-NOGRAVITY;
		+THRUACTORS;
		Scale 0.57;
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
			BLER FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG 1 A_FadeOut(0.01);
			stop;
		SpawnUnderwater:
			TNT1 A 0;
			TNT1 AA 0 a_spawnprojectile("Underblood3", 32, 0, random(0, 360), 2, random(0, 160));
			
			Stop;
	}
}


CLASS SuperGoreMist: SuperGore { 
	Default {
		
		Scale 1.0;
		Speed 8;
		Gravity 0.3;
	}
}

CLASS SuperGoreMistSmall: SuperGore { 
	Default {
		
		Scale 0.35;
		Speed 2;
		Gravity 0.1;
	}
}

CLASS SuperGoreMistTiny: SuperGore { 
	Default {
		
		Scale 0.15;
		Speed 1;
		Gravity 0.1;
	}
}

CLASS BlueSuperGore: SuperGore { 
	Default {
		
		Alpha 0.4;
		translation "168:191=192:207","16:47=240:247";
	}
States
{
SpawnUnderwater:
	TNT1 A 0;
	TNT1 AA 0 a_spawnprojectile("UnderbloodBlue3", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
}
}


CLASS BlueSuperGoreSpawner: SuperGoreSpawner { 
	Default {
 
speed 20;
	}
states
	{
	Spawn:
		TNT1 AAAAAAAA 1 A_SpawnItem("BlueSuperGore");
		Stop;
	}
}



CLASS GreenSuperGore: SuperGore { 
	Default {
 
translation "168:191=112:127","16:47=120:127";
Decal "GreenBloodSplat";
	}
States
{
	SpawnUnderwater:
		TNT1 A 0;
		TNT1 AA 0 a_spawnprojectile("UnderbloodGreen3", 32, 0, random(0, 360), 2, random(0, 160));
		Stop;
}
}


CLASS GreenSuperGoreSpawner: SuperGoreSpawner { 

states
	{
	Spawn:
		TNT1 AAAA 1 A_SpawnItem("GreenSuperGore");
		Stop;
	}
}



CLASS StealthBloodLol : ACTOR { 
	Default {
 
 scale 1.1;
 speed 6;
 health 1;
 radius 8;
 height 1;
 Gravity 0.8;
 damage 0;
 Renderstyle "Translucent";
 Alpha 0.7;
	DamageType "Blood";
	Decal "BloodSuper";
   +MISSILE
   +CLIENTSIDEONLY
   +NOTELEPORT
   +NOBLOCKMAP
	+THRUACTORS
		+BLOODLESSIMPACT;
		+FORCEXYBILLBOARD;
		+NODAMAGETHRUST;
		+MOVEWITHSECTOR;
		+CORPSE;
		-DONTSPLASH;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			TNT1 A 1;
			loop;
		Splash:
			stop;
		Death:
			//TNT1 A 0 a_spawnprojectile("SmallBloodSplasher", 0, 0, random(0, 360), 2, random(0, 160))
			TNT1 A 0 A_PlaySound("blooddrop");
			TNT1 A 0 A_SpawnItem("pb_blood_spot", 5);
			XDT1 EFGHIJK 0;
			Stop;
	}
}


CLASS BloodCloud : ACTOR { 
	Default {
		
		scale 1.4;
		mass 1;
		renderstyle "Translucent";
		alpha 0.9;
		Decal "BloodSplat";
		+LOWGRAVITY;
		+NOTELEPORT;
		+NOBLOCKMAP;
		+NOCLIP;
		+FORCEXYBILLBOARD;
		+CLIENTSIDEONLY;
		+DontSplash;
		+MISSILE;
		-NOGRAVITY;
		Speed 2;
	}
	states
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			//BTRL ABCD 4
			BLOD ABCDDEEFFF 4;
			stop;
		Death:
			TNT1 A 0;
			Stop;
			
		Splash:
			stop;
			
	}
}



CLASS BloodSplasher2 : ACTOR { 
	Default {
		
		damagefactor "Trample", 0.0;
		DamageType "Blood";
		Health 1;
		Radius 1;
		Height 1;
		Mass 1;
		+NOCLIP;
		+NOGRAVITY;
		+ACTIVATEMCROSS;
		+WINDTHRUST;
		+NODAMAGETHRUST;
		+PIERCEARMOR;
		+BLOODLESSIMPACT;
		DeathSound "None";
	}
	States
	{
		Spawn:
			BTRL A 1;
			Stop;
	}
}


CLASS BloodSplasher3: BloodSplasher2 { 
	States
	{
		Spawn:
			BTRL A 1;
			//TNT1 A 0 A_Explode(3,600)
			Stop;
	}
}



CLASS SmallSuperGore : ACTOR { 
	Default {
		
		Decal "BloodSplat";
		Alpha 0.5;
		+FORCEXYBILLBOARD;
		+GHOST;
		+NOBLOCKMAP;
		+DontSplash;
		-EXPLODEONWATER;
		-ALLOWPARTICLES;
		+CLIENTSIDEONLY;
		+THRUACTORS;
		+MISSILE;
		+NOGRAVITY;
		Speed 16;
		Scale 2;
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
			BLOD EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 1 A_FadeOut(0.03);
			stop;
		SpawnUnderwater:
			TNT1 A 0;
			TNT1 AA 0 a_spawnprojectile("Underblood3", 32, 0, random(0, 360), 2, random(0, 160));
		Stop;
	}
}


CLASS SmallSuperGore2: SmallSuperGore { 
	Default {
		
		Alpha 0.3;
		Scale 0.6;
		Speed 1;
	}
}


CLASS MediumSuperGore: SmallSuperGore { 
	Default {
		
		Scale 2.0;
		Speed 4;
	}
}



CLASS GiantSuperGore: SmallSuperGore { 
	Default {
		
		Scale 4.0;
		Speed 8;
	}
}

CLASS GreenSuperGoreMist: GreenSuperGore { 
	Default {
		
		Scale 1.0;
		Speed 8;
		Gravity 0.3;
	}
}

CLASS GreenSuperGoreMistSmall: GreenSuperGore { 
	Default {
		
		Scale 0.35;
		Speed 2;
		Gravity 0.1;
	}
}

CLASS GreenSuperGoreMistTiny: GreenSuperGore { 
	Default {
		
		Scale 0.15;
		Speed 1;
		Gravity 0.1;
	}
}
CLASS GreenSmallSuperGore : SmallSuperGore { 
	Default {
		
		Decal "GreenBloodSplat";
Translation"168:191=112:127", "16:47=123:127";
	}
States
{
SpawnUnderwater:
	TNT1 A 0;
	TNT1 AA 0 a_spawnprojectile("UnderbloodGreen3", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
}
}
CLASS GreenSmallSuperGore2: GreenSmallSuperGore { 
	Default {
 
Alpha 0.3;
Scale 0.6;
Speed 1;
Decal "GreenBloodSplat";
	}
}


CLASS GreenMediumSuperGore: GreenSmallSuperGore { 
	Default {
 
Scale 2.0;
Speed 4;
Decal "GreenBloodSplat";
	}
}



CLASS GiantGreenSuperGore: GreenSmallSuperGore { 
	Default {
 
Scale 4.0;
Speed 8;

Decal "GreenBloodSplat";
	}
}
