CLASS GenericBurningGuy : ACTOR { 
Default {
	Radius 1;
	Height 1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOICEDEATH;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 BRIGHT;
		TNT1 A 0 A_Jump(128, "Spawn2");
		TNT1 A 0 A_PlaySound("DSFDTHE");
		BUR2 A 1 BRIGHT;
		BUR2 AABBCCDDEE 3 BRIGHT a_spawnprojectile("BurnParticles", 36, 0, random(0, 180), 2, random(0, 180));
		BURN FFGGHH 3 BRIGHT a_spawnprojectile("BurnParticles", 36, 0, random(0, 180), 2, random(0, 180));
		BURN IIJJKKLL 3 BRIGHT a_spawnprojectile("BurnParticles", 28, 0, random(0, 180), 2, random(0, 180));
		BURN MMN 3 BRIGHT a_spawnprojectile("BurnParticles", 32, 0, random(0, 180), 2, random(0, 180));
		BURN NOOPP 3 BRIGHT a_spawnprojectile("BurnParticles", 22, 0, random(0, 180), 2, random(0, 180));
		BURN QQ 3 BRIGHT a_spawnprojectile("BurnParticles", 18, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 A_PlaySound("DSFDTHE");
		BURN RRSSTTSSRRSSTTSSRRSSTTRRSSTTSSRRSSTTSSRRSSTTSSTT 3 BRIGHT a_spawnprojectile("SmallBurnParticles", 12, 0, random(0, 180), 2, random(0, 180));
		BURN UU 3 BRIGHT a_spawnprojectile("BurnParticles", 12, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 A_SpawnItem("SmallFireFocusSpawnerz1");
		BURN VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 9 a_spawnprojectile("ExplosionSmoke", 8, 0, random(0, 360), 2, random(90, 110));
		BURN V -1;

	Spawn2:
		TNT1 A 0 BRIGHT;
		TNT1 A 0 A_PlaySound("DSFDTHG");
		TNT1 A 0 BRIGHT;
		BUR2 A 1 BRIGHT;
		BUR2 AABBCCDDEE 3 BRIGHT a_spawnprojectile("BurnParticles", 36, 0, random(0, 180), 2, random(0, 180));
		BURN FFGGHH 3 BRIGHT a_spawnprojectile("BurnParticles", 36, 0, random(0, 180), 2, random(0, 180));
		BURN IIJJKKLL 3 BRIGHT a_spawnprojectile("BurnParticles", 28, 0, random(0, 180), 2, random(0, 180));
		BURN MMN 3 BRIGHT a_spawnprojectile("BurnParticles", 32, 0, random(0, 180), 2, random(0, 180));
		BURN NOOPP 3 BRIGHT a_spawnprojectile("BurnParticles", 22, 0, random(0, 180), 2, random(0, 180));
		BURN QQ 3 BRIGHT a_spawnprojectile("BurnParticles", 18, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 A_PlaySound("DSFDTHG");
		BURN RRSSTTSSRRSSTTSSRRSSTTRRSSTTSSRRSSTTSSRRSSTTSSTT 3 BRIGHT a_spawnprojectile("SmallBurnParticles", 12, 0, random(0, 180), 2, random(0, 180));
		BURN UU 3 BRIGHT a_spawnprojectile("BurnParticles", 12, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 A_SpawnItem("SmallFireFocusSpawnerz1");
		BURN VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 9 a_spawnprojectile("ExplosionSmoke", 8, 0, random(0, 360), 2, random(90, 110));
		BURN V -1;
Stop;}}
   

   




CLASS BlackHoledArachnotron : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 1.3;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	//DamageFactor "bloodsplasher", 0.0    DamageFactor "tinybloodsplasher", 0.0    DamageFactor "superbloodsplasher", 0.0    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		ID63 AAABCDEFGHI 4;
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}  

CLASS BlackHoledArachnotron3 : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 1.1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	//DamageFactor "bloodsplasher", 0.0    DamageFactor "tinybloodsplasher", 0.0    DamageFactor "superbloodsplasher", 0.0    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		ID64 AABCDEFGHIJKLM 4;
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}

CLASS BlackHoledAracnorbQueen : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.85;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	//DamageFactor "bloodsplasher", 0.0    DamageFactor "tinybloodsplasher", 0.0    DamageFactor "superbloodsplasher", 0.0    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		ID66 AAABCDEFGHIJK 4;
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}  

CLASS BlackHoledArachnophyte : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.74;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	//DamageFactor "bloodsplasher", 0.0    DamageFactor "tinybloodsplasher", 0.0    DamageFactor "superbloodsplasher", 0.0    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		ID67 AAABCDEFGHIJK 4;
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}  


CLASS BurnParticles : ACTOR { 
Default {
	
	Radius 8;
	Height 8;
	Speed 5;
	Mass 6;
	BounceFactor 0.5;
	+DOOMBOUNCE;
	Speed 0;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	+NODAMAGETHRUST;
	+NOCLIP;
	DamageType "Fire";
	+NOBLOOD;
	+NOBLOODDECALS;
	+BLOODLESSIMPACT;
	-BLOODSPLATTER;
}
States
{
	Spawn:
		TNT1 A 0;
		XDT3 A 0 A_Explode(3,30);
		TNT1 A 0 A_SpawnItem("Red_Flare", 0, 5);
		TTRB A 0 bright a_spawnprojectile("ExplosionSmoke", 20, 0, random(0, 360), 2, random(60, 130));
		TTRB A 0 bright a_spawnprojectile("CoolandNewFlameTrails", 0, 0, random(0, 360), 2, random(0, 130));
		TNT1 A 3;
		stop;
}
}

CLASS BurnParticlesNoPain : BurnParticles { 
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("Red_Flare", 0, 5);
		TTRB A 0 bright a_spawnprojectile("ExplosionSmoke", 20, 0, random(0, 360), 2, random(60, 130));
		TTRB A 0 bright a_spawnprojectile("CoolandNewFlameTrails", 0, 0, random(0, 360), 2, random(0, 130));
		TNT1 A 3;
		stop;
}
}

CLASS SmallBurnParticles: BurnParticles { 
Default {
	
	DamageType "Burn";
}
States
{
	Spawn:
		TNT1 A 0;
		XDT3 A 0 A_Explode(2,30);
		TNT1 A 0 A_SpawnItem("Red_Flare", 0, 5);
		TTRB A 0 bright a_spawnprojectile("ExplosionSmoke", 20, 0, random(0, 360), 2, random(60, 130));
		TTRB A 0 bright a_spawnprojectile("FlameTrails", 0, 0, random(0, 360), 2, random(60, 130));
		stop;
}
}


CLASS BurnParticlesNoDamage: BurnParticles { 
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("Red_Flare", 0, 5);
		TTRB A 0 bright a_spawnprojectile("ExplosionSmoke", 20, 0, random(0, 360), 2, random(60, 130));
		TTRB A 0 bright a_spawnprojectile("FlameTrails", 0, 0, random(0, 360), 2, random(60, 130));
		stop;
}
}




   
   
   
   
   
   









  

 

  

  
  
  
  

  










CLASS DyingZombiemanInFlames : ACTOR { 
Default {
	
	Radius 12;
	Height 30;
	Speed 5;
	Health 20;
	PainSound "grunt/pain";
	DeathSound "grunt/death";
	+SHOOTABLE;
	+FLOORCLIP;
	//+NOBLOCKMAP
	+NOICEDEATH;
	+LOOKALLAROUND;
	+FRIGHTENED;
	-SOLID;
	damagefactor "Burn", 0.0;
	damagefactor "Fire", 0.0;
	damagefactor "Flames", 0.0;
}
States
{
	
	Spawn:
		TNT1 A 0;
		ZMAB A 1 A_Look;
		Loop;
	See:
		TNT1 A 0;
		TNT1 A 0 A_Playsound("BurnZom");
	See2:
		ZMAB AABB 5
		{
			A_Chase();
			a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
			a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		}
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_SpawnItem("pb_blood_spot");
		//TNT1 A 0 A_GiveInventory("DeathTimer1", 1);
		//TNT1 A 0 A_JumpIfInventory("DeathTimer1", 15, "GotoDeath");
		Loop;

	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		TNT1 A 0 {self.bSHOOTABLE = false;}
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 3 a_spawnprojectile("BurnParticles", 5, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_SpawnItem("SmallFireFocusSpawnerz1");
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHH 10 a_spawnprojectile("ExplosionSmoke", 15, 0, random(0, 360), 2, random(50, 130));
		BRZ3 H -1;
	Crush:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS2 A 5;
		CRS2 A -1;
		Stop;
		
	Death.Stomp:
	Death.SSG:
	XDeath:
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AAAAAA 0 bright a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright a_spawnprojectile("XDeath2", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright a_spawnprojectile("XDeath3", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 A 0 A_SpawnItem("CrushedRemains");
		TNT1 A 1;
 		TNT1 A 1 A_XScream;
		TNT1 A 1 A_NoBlocking;
		TNT1 A -1;
		Stop;
}
}



CLASS DyingSergeantNoLegInFlames : ACTOR { 
Default {
	
	Radius 12;
	Height 30;
	Speed 5;
	Health 20;
	PainSound "grunt/pain";
	DeathSound "grunt/death";
	+SHOOTABLE;
	+FLOORCLIP;
	//+NOBLOCKMAP
	+LOOKALLAROUND;
	+NOICEDEATH;
	+FRIGHTENED;
	-SOLID;
	
	damagefactor "Burn", 0.0;
	damagefactor "Fire", 0.0;
	damagefactor "Flames", 0.0;
}
States
{
	
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Playsound("BurnZom");
		ZMAB A 1 A_Look;
		Loop;
	See:
		SMBM A 5 A_Chase;
		TNT1 A 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		SMBM A 5 A_Chase;
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		
		SMBM B 5 A_Chase;
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		SMBM B 5 A_Chase;
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		
		//TNT1 A 0 A_GiveInventory("DeathTimer1", 1);
		//TNT1 A 0 A_JumpIfInventory("DeathTimer1", 15, "GotoDeath");
		Loop;
		
	GotoDeath:
		TNT1 A 0;
		Goto Death;
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 3 a_spawnprojectile("BurnParticles", 5, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_SpawnItem("SmallFireFocusSpawnerz1");
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHH 10 a_spawnprojectile("ExplosionSmoke", 15, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 {self.bSHOOTABLE = false;}
		BRZ3 H -1;
	Crush:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS2 A 5;
		CRS2 A -1;
		Stop;
		
	Death.Stomp:
	Death.SSG:
	XDeath:
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AAAAAA 0 bright a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright a_spawnprojectile("XDeath2", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright a_spawnprojectile("XDeath3", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 A 0 A_SpawnItem("CrushedRemains");
		TNT1 A 1;
 		TNT1 A 1 A_XScream;
		TNT1 A 1 A_NoBlocking;
		TNT1 A -1;
		Stop;
}
}







CLASS PoorGuyBurningLife : Inventory { 
Default {
	
	inventory.maxamount 20;
}
}








CLASS BurningCacodemon : ACTOR { 
Default {
	
	Radius 12;
	Height 56;
	Speed 3;
	Scale 0.85;
	Health 100;
	GibHealth 25;
	+NOICEDEATH;
	damagefactor "Burn", 0.5;
	damagefactor "Fire", 0.5;
	damagefactor "Flames", 0.5;
	damagefactor "Flame", 0.5;
	damagefactor "ExplosiveImpact", 10.0;
	bloodtype "Blue_Blood";
	bloodcolor "DarkBlue";
	MONSTER;
	-COUNTKILL;
	+FLOAT;
	+NOGRAVITY;
	+FRIENDLY;
	+FLOORCLIP;
	+SHOOTABLE;
	+NOBLOCKMONST;
	+DONTSPLASH;
	Gravity 1.0;
	bloodtype "DeadBlood";
	Obituary "%o was near someone in flames.";
	Mass 100;
}
States
{
	Spawn:
		TNT1 A 0 a_spawnprojectile("BurnParticles", 40, 0, random(0, 360), 2, random(50, 130));
		HEAD NN 1 Bright A_Chase(null, null);
		Goto Suffer;
	Suffer:
		HEAD OONN 1 Bright
		{
			A_Wander();
			A_Recoil(-1);
		
			a_spawnprojectile("BurnParticles", 40, 0, random(0, 360), 2, random(50, 130));
			a_spawnprojectile("CoolandNewFlameTrails", 40, 0, random(0, 360), 2, random(50, 130));
			a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		}
		
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 15, "Death");
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		Loop;
		
	Death:
		TNT1 A 0 A_Fall;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 {self.bNOTARGET = true;}
		TNT1 A 0 {self.bNOGRAVITY = false;}
		HEAD P 1 A_SpawnItem("SmallFireFocusSpawnerz1");
		TNT1 A 0 A_Playsound("props/redfire");
		HEAD PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP 8 a_spawnprojectile("CoolandNewFlameTrails", 15, 0, random(0, 360), 2, random(50, 130));
		HEAD P 1 A_SpawnItem("SmallFireFocusSpawnerz1");
		HEAD PPPPPPPPPPPPPPPPPPPPPPPP 6 a_spawnprojectile("ExplosionSmoke", 15, 0, random(0, 360), 2, random(50, 130));
		HEAD P -1;
		Stop;
}
}


















































CLASS BurningImpRunning: BurningZombieMan { 
Default {
	Scale 1.05;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("BURNZOM");
	Suffer:
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, "Death");
		TNT1 A 0 ThrustThingZ(0,60,0,1);
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0;
	Looping:
		TRBR AAAA 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TRBR BBBB 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TRBR CCCC 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TRBR DDDD 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		Loop;
		
	FallDeath:
		TNT1 AAAAAAAAAA 0 a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(20, 150));
		TNT1 AAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(20, 150));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 10, 0, random(0, 360), 2, random(20, 150));
		TNT1 A 0 A_PlaySound("misc/xdeath");
		TNT1 A 0 A_Explode(100, 128);
		Goto Death;
		
	Death:
		TNT1 A 0 A_Fall;
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 {self.bNOTARGET = true;}
		Stop;
}
}

CLASS BurningDarkImpNami : BurningImpRunning { 
States
{
	
	Spawn:
		TNT1 A 0 A_PlaySound("BURNZOM");
		Goto Suffer;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, "Death");
		TNT1 A 0 ThrustThingZ(0,60,0,1);
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0;
		Goto Looping;
		
	Looping:
		T1BR AAAA 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		T1BR BBBB 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		T1BR CCCC 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		T1BR DDDD 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		Loop;
		
	Suffer:
		T1BR AAABBBCCCDDD 1
		{
			A_Wander();
			A_Recoil(-1);
			a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
			a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		}
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 8, "Death");
		Loop;
		
}
}

CLASS BurningImpST : BurningImpRunning { 
States
{
	
	Spawn:
		TNT1 A 0 A_PlaySound("BURNZOM");
	Suffer:
		T2BR AAABBBCCCDDD 1
		{
			A_Wander();
			A_Recoil(-1);
			a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
			a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		}
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 8, "Death");
		Loop;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, "Death");
		TNT1 A 0 ThrustThingZ(0,60,0,1);
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0;
		Goto Looping;
		
	Looping:
		T2BR AAAA 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T2BR BBBB 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T2BR CCCC 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T2BR DDDD 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		Loop;
}
}

CLASS BurningImpBig : BurningImpRunning { 
States
{
	
	Spawn:
		TNT1 A 0 A_PlaySound("BURNZOM");
		Goto Suffer;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, "Death");
		TNT1 A 0 ThrustThingZ(0,60,0,1);
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0;
		Goto Looping;
		
	Looping:
		T3BR AAAA 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T3BR BBBB 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T3BR CCCC 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T3BR DDDD 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		Loop;
		
	Suffer:
		T3BR AAABBBCCCDDD 1
		{
			A_Wander();
			A_Recoil(-1);
			a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
			a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		}
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 8, "Death");
		Loop;
}
}


CLASS BurningImpUgly : BurningImpRunning { 
States
{
	
	Spawn:
		TNT1 A 0 A_PlaySound("BURNZOM");
		Goto Suffer;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, "Death");
		TNT1 A 0 ThrustThingZ(0,60,0,1);
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0;
		Goto Looping;
		
	Looping:
		T4BR AAAA 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T4BR BBBB 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T4BR CCCC 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T4BR DDDD 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		Loop;
		
	Suffer:
		T4BR AAABBBCCCDDD 1
		{
			A_Wander();
			A_Recoil(-1);
			a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
			a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		}
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 8, "Death");
		Loop;
}
}

CLASS BurningImpSavage: BurningImpRunning { 
States
{
	
	Spawn:
		TNT1 A 0 A_PlaySound("BURNZOM");
		Goto Suffer;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, "Death");
		TNT1 A 0 ThrustThingZ(0,60,0,1);
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0;
		Goto Looping;
		
	Looping:
		T5BR AAAA 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 AA 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T5BR BBBB 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 AA 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T5BR CCCC 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 AA 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T5BR DDDD 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 AA 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		Loop;
		
	Suffer:
		T5BR AAA 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 A 0 A_PlaySound("SavageImp/pain");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("FlameTrails", 40, 0, random(0, 360), 2, random(50, 130));
		T5BR BBB 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("FlameTrails", 40, 0, random(0, 360), 2, random(50, 130));
		T5BR CCC 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("FlameTrails", 40, 0, random(0, 360), 2, random(50, 130));
		T5BR DDD 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("FlameTrails", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 8, "Death");
		Loop;
		
	Death:
		TNT1 A 0 A_Fall;
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 {self.bNOTARGET = true;}
		Stop;
}
}
























