CLASS GenericBurningGuy : ACTOR { 
Default {
	Radius 1;
	Height 1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOICEDEATH;
	Mass 1000;
	Health 100;
}
States    {
	Spawn:
		TNT1 A 0 BRIGHT;
		TNT1 A 0 A_Jump(128, "Spawn2");
		TNT1 A 0 A_PlaySound("DSFDTHE");
		BUR2 A 1 BRIGHT;
		BUR2 AABBCCDDEE 3 BRIGHT a_spawnprojectile("BurnParticles", 36, 0, random(0, 180), 2, random(0, 180));
		BURN FFGGHH 3 BRIGHT a_spawnprojectile("BurnParticles", 36, 0, random(0, 180), 2, random(0, 180));
		BURN IIJJKKLL 3 BRIGHT a_spawnprojectile("BurnParticles", 28, 0, random(0, 180), 2, random(0, 180));
		BURN MMN 3 BRIGHT a_spawnprojectile("BurnParticles", 32, 0, random(0, 180), 2, random(0, 180));
		BURN NOOPP 3 BRIGHT a_spawnprojectile("BurnParticles", 22, 0, random(0, 180), 2, random(0, 180));
		BURN QQ 3 BRIGHT a_spawnprojectile("BurnParticles", 18, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 A_PlaySound("DSFDTHE");
		BURN RRSSTTSSRRSSTTSSRRSSTTRRSSTTSSRRSSTTSSRRSSTTSSTT 3 BRIGHT a_spawnprojectile("SmallBurnParticles", 12, 0, random(0, 180), 2, random(0, 180));
		BURN UU 3 BRIGHT a_spawnprojectile("BurnParticles", 12, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 A_SpawnItem("SmallFireFocusSpawnerz1");
		BURN VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 9 a_spawnprojectile("PlasmaSmoke", 8, 0, random(0, 360), 2, random(90, 110));
		BURN V -1;
		
		
	Spawn2:
		TNT1 A 0 BRIGHT;
		TNT1 A 0 A_PlaySound("DSFDTHG");
		TNT1 A 0 BRIGHT;
		BUR2 A 1 BRIGHT;
		BUR2 AABBCCDDEE 3 BRIGHT a_spawnprojectile("BurnParticles", 36, 0, random(0, 180), 2, random(0, 180));
		BURN FFGGHH 3 BRIGHT a_spawnprojectile("BurnParticles", 36, 0, random(0, 180), 2, random(0, 180));
		BURN IIJJKKLL 3 BRIGHT a_spawnprojectile("BurnParticles", 28, 0, random(0, 180), 2, random(0, 180));
		BURN MMN 3 BRIGHT a_spawnprojectile("BurnParticles", 32, 0, random(0, 180), 2, random(0, 180));
		BURN NOOPP 3 BRIGHT a_spawnprojectile("BurnParticles", 22, 0, random(0, 180), 2, random(0, 180));
		BURN QQ 3 BRIGHT a_spawnprojectile("BurnParticles", 18, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 A_PlaySound("DSFDTHG");
		BURN RRSSTTSSRRSSTTSSRRSSTTRRSSTTSSRRSSTTSSRRSSTTSSTT 3 BRIGHT a_spawnprojectile("SmallBurnParticles", 12, 0, random(0, 180), 2, random(0, 180));
		BURN UU 3 BRIGHT a_spawnprojectile("BurnParticles", 12, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 A_SpawnItem("SmallFireFocusSpawnerz1");
		BURN VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 9 a_spawnprojectile("PlasmaSmoke", 8, 0, random(0, 360), 2, random(90, 110));
		BURN V -1;
Stop;}}
   
//Generic Acid Guy
CLASS GenericAcidGuy : ACTOR { 
Default {
	Radius 1;
	Height 1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOICEDEATH;
	DamageFactor "bloodsplasher", 0.0;
    DamageFactor "tinybloodsplasher", 0.0;
    DamageFactor "superbloodsplasher", 0.0;
    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States    {
	Spawn:
		TNT1 A 0 BRIGHT;
		TNT1 A 0 A_Jump(128, "Spawn2");
		TNT1 A 0 A_Playsound("redburn");
		TNT1 A 0 A_PlaySound("BURNZOM", 3);
		ACID B 1 BRIGHT;
		TNT1 A 0 a_spawnprojectile("GreenFlare", 36, 0, random(0, 180), 2, random(0, 180));
		ACID BBCCDDEE 2 BRIGHT a_spawnprojectile("GreenTrailSparks", 36, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GreenFlare", 36, 0, random(0, 180), 2, random(0, 180));
		TNT1 AAAAA 0 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		ACID FFGGHH 3 BRIGHT a_spawnprojectile("PlasmaParticleSpawner", 36, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GreenFlare", 36, 0, random(0, 180), 2, random(0, 180));
		TNT1 AAAAA 0 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		ACID IIJJKKLL 2 BRIGHT a_spawnprojectile("GreenTrailSparks", 28, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile( "GreenCloudSmall", 12, 0, random( 0, 359 ), 2 );
		TNT1 AAAAA 0 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("GreenFlare", 36, 0, random(0, 180), 2, random(0, 180));
		ACID MMN 3 BRIGHT a_spawnprojectile("PlasmaParticleSpawner", 32, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile( "GreenCloudSmall", 12, 0, random( 0, 359 ), 2 );
		TNT1 A 0 a_spawnprojectile("GreenFlare", 36, 0, random(0, 180), 2, random(0, 180));
		TNT1 AAAAA 0 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		ACID NOOPP 2 BRIGHT a_spawnprojectile("GreenTrailSparks", 22, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GreenFlare", 36, 0, random(0, 180), 2, random(0, 180));
		TNT1 AAAAA 0 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		ACID QQ 3 BRIGHT a_spawnprojectile("PlasmaParticleSpawner", 18, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile( "GreenCloudSmall", 12, 0, random( 0, 359 ), 2 );
		TNT1 A 0 a_spawnprojectile("GreenFlare", 36, 0, random(0, 180), 2, random(0, 180));
		TNT1 AAAAA 0 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		ACID RRSSTTSSRRSSTTSSRRSSTTRRSSTTSSRRSSTTSSRRSSTTSSTT 3 BRIGHT a_spawnprojectile("GreenTrailSparks", 12, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GreenFlare", 36, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 A_Playsound("redburn");
		TNT1 AAAAA 0 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		ACID UU 3 BRIGHT a_spawnprojectile("BFGAltShockWave", 12, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GreenFlare", 36, 0, random(0, 180), 2, random(0, 180));
		TNT1 AAAAA 0 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("BFGAltShockWave");
		ACID VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 9 a_spawnprojectile("PlasmaSmoke", 8, 0, random(0, 360), 2, random(90, 110));
		ACID V -1;
		TNT1 A 0 A_SpawnItem("BFGAltShockWave",0,0);
		
	Spawn2:
		TNT1 A 0 BRIGHT;
		TNT1 A 0 BRIGHT;
		ACID B 1 BRIGHT;
		TNT1 A 0 A_Playsound("redburn");
		TNT1 A 0 A_PlaySound("BURNZOM", 3);
		ACID BBCCDDEE 2 BRIGHT a_spawnprojectile("PlasmaParticleSpawner", 36, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GreenFlare", 36, 0, random(0, 180), 2, random(0, 180));
		TNT1 AAAAA 0 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		ACID FFGGHH 2 BRIGHT a_spawnprojectile("GreenTrailSparks", 36, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GreenFlare", 36, 0, random(0, 180), 2, random(0, 180));
		TNT1 AAAAA 0 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		ACID IIJJKKLL 2 BRIGHT a_spawnprojectile("PlasmaParticleSpawner", 28, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile( "GreenCloudSmall", 12, 0, random( 0, 359 ), 2 );
		TNT1 AAAAA 0 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("GreenFlare", 36, 0, random(0, 180), 2, random(0, 180));
		ACID MMN 3 BRIGHT a_spawnprojectile("GreenTrailSparks", 32, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GreenFlare", 36, 0, random(0, 180), 2, random(0, 180));
		TNT1 AAAAA 0 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		ACID NOOPP 3 BRIGHT a_spawnprojectile("PlasmaParticleSpawner", 22, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile( "GreenCloudSmall", 12, 0, random( 0, 359 ), 2 );
		TNT1 A 0 a_spawnprojectile("GreenFlare", 36, 0, random(0, 180), 2, random(0, 180));
		ACID QQ 3 BRIGHT a_spawnprojectile("GreenTrailSparks", 18, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile( "GreenCloudSmall", 12, 0, random( 0, 359 ), 2 );
		TNT1 AAAAA 0 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("GreenFlare", 36, 0, random(0, 180), 2, random(0, 180));
		ACID RRSSTTSSRRSSTTSSRRSSTTRRSSTTSSRRSSTTSSRRSSTTSSTT 3 BRIGHT a_spawnprojectile("GreenTrailSparks", 12, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GreenFlare", 36, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 A_Playsound("redburn");
		TNT1 A 0 a_spawnprojectile( "GreenCloudSmall", 12, 0, random( 0, 359 ), 2 );
		TNT1 AAAAA 0 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		ACID UU 3 BRIGHT a_spawnprojectile("PlasmaParticleSpawner", 12, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GreenFlare", 36, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 A_SpawnItem("PlasmaParticleSpawner");
		TNT1 AAAAA 0 a_spawnprojectile("Blood", 10, 0, random(0, 360), 2, random(0, 160));
		BURN VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 9 a_spawnprojectile("PlasmaSmoke", 8, 0, random(0, 360), 2, random(90, 110));
		TNT1 A 0 a_spawnprojectile("GreenFlare", 36, 0, random(0, 180), 2, random(0, 180));
		ACID V -1;
Stop;}}
   
CLASS DesintegratedHuman2 : ACTOR { 
Default {
	Radius 1;
	Height 1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	DamageFactor "bloodsplasher", 0.0;
    DamageFactor "tinybloodsplasher", 0.0;
    DamageFactor "superbloodsplasher", 0.0;
    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
	Scale 1.0;
}
States    {
	Spawn:
		TNT1 A 0 A_PlaySound("MELT",6,1,1);
		TNT1 AAAAA 0 a_spawnprojectile("BloodMistExtraBig", 22, 0, random(0, 360), 2, random(0, 90));
		TNT1 AAAAA 0 a_spawnprojectile("BloodmistBig", 37, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("BloodmistSmall", 30, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBloodLevel3", 37, 0, random(0, 360), 2, random(10, 50));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 30, 0, random(0, 360), 2, random(0, 90));
		TNT1 A 0 a_spawnprojectile("SuperGoreSpawner2", 30, 0, random(0, 360), 2, random(10, 90));
		TNT1 A 0 A_SpawnItem("BigBloodSpot");
		ID51 ABCDEFGHIJ 5 A_SpawnItemEx("PlasmaParticleSpawner", 0, 0, 28, 6, 6, 6, 0, 128);
		TNT1 A 20;//A_StopSound(2)
		
		Stop;
}}
  
CLASS BlackHoledHuman : ACTOR { 
Default {
	Radius 1;
	Height 1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	DamageFactor "bloodsplasher", 0.0;
    DamageFactor "tinybloodsplasher", 0.0;
    DamageFactor "superbloodsplasher", 0.0;
    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
	Scale 1.0;
}
States    {
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 27, 0, 0, 0, 0, 128);
		ID52 ABCDEFGHIJ 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 0, 6, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
	Stop;
}}
  

CLASS BlackHoledDemon : ACTOR { 
Default {
	Radius 1;
	Height 1;
	Scale 1.1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	DamageFactor "bloodsplasher", 0.0;
    DamageFactor "tinybloodsplasher", 0.0;
    DamageFactor "superbloodsplasher", 0.0;
    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 32, 0, 0, 0, 0, 128);
		ID53 AAABCDEFGHI 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 32, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}  

CLASS BlackHoledCacoDemon : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.9;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	DamageFactor "bloodsplasher", 0.0;
    DamageFactor "tinybloodsplasher", 0.0;
	DamageFactor "superbloodsplasher", 0.0;
    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAAA 0 ;//a_spawnprojectile("Blue_FlyingBlood", 47, 0, random(0, 360), 2, random(30, 150));
		TNT1 AAAAAAAAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 36, 0, 0, 0, 0, 128);
		ID54 AAABCDEFGH 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 36, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}  

CLASS BlackHoledFatso : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 1.2;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	DamageFactor "bloodsplasher", 0.0;
    DamageFactor "tinybloodsplasher", 0.0;
    DamageFactor "superbloodsplasher", 0.0;
    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		ID55 AABCDEFGHIJK 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}  

CLASS BlackHoledKnight : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 1.0;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	DamageFactor "bloodsplasher", 0.0;
    DamageFactor "tinybloodsplasher", 0.0;
    DamageFactor "superbloodsplasher", 0.0;
    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		ID56 AABCDEFGHI 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
} 

CLASS BlackHoledBaron : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 1.13;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	DamageFactor "bloodsplasher", 0.0;
    DamageFactor "tinybloodsplasher", 0.0;
	DamageFactor "superbloodsplasher", 0.0;
    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		ID56 AABCDEFGHI 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}  

CLASS BlackHoledSkeleton : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 1.1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	DamageFactor "bloodsplasher", 0.0;
    DamageFactor "tinybloodsplasher", 0.0 ;
	DamageFactor "superbloodsplasher", 0.0;
    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		ID57 AABCDEFGHI 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}  

CLASS BlackHoledSkeletonJ : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 1.1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	//DamageFactor "bloodsplasher", 0.0    DamageFactor "tinybloodsplasher", 0.0    DamageFactor "superbloodsplasher", 0.0    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		ID68 AABCDEFGHI 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}

CLASS BlackHoledSoul : ACTOR { 
Default {
	Radius 1;
	Height 1;
	Scale 1.0;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	//DamageFactor "bloodsplasher", 0.0    DamageFactor "tinybloodsplasher", 0.0    DamageFactor "superbloodsplasher", 0.0    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 20, 0, 0, 0, 0, 128);
		ID58 AAAABCDEF 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 20, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}  

CLASS BlackHoledPainElemental : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 1.2;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	//DamageFactor "bloodsplasher", 0.0    DamageFactor "tinybloodsplasher", 0.0    DamageFactor "superbloodsplasher", 0.0    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		ID59 AAABCDEFGHI 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}  

CLASS BlackHoledMagcaco : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.9;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	//DamageFactor "bloodsplasher", 0.0    DamageFactor "tinybloodsplasher", 0.0    DamageFactor "superbloodsplasher", 0.0    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 30, 0, 0, 0, 0, 128);
		ID60 AAABCDEFGHI 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 30, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}  


CLASS BlackHoledArchvile : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 1.0;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	//DamageFactor "bloodsplasher", 0.0    DamageFactor "tinybloodsplasher", 0.0    DamageFactor "superbloodsplasher", 0.0    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 35, 0, 0, 0, 0, 128);
		ID61 AAABCDEFGHI 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 35, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}  

CLASS BlackHoledAfrit : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 1.0;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	//DamageFactor "bloodsplasher", 0.0    DamageFactor "tinybloodsplasher", 0.0    DamageFactor "superbloodsplasher", 0.0    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		ID62 AAABCDEFGHI 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}  

CLASS BlackHoledArachnotron : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 1.3;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	//DamageFactor "bloodsplasher", 0.0    DamageFactor "tinybloodsplasher", 0.0    DamageFactor "superbloodsplasher", 0.0    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		ID63 AAABCDEFGHI 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}  

CLASS BlackHoledArachnotron3 : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 1.1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	//DamageFactor "bloodsplasher", 0.0    DamageFactor "tinybloodsplasher", 0.0    DamageFactor "superbloodsplasher", 0.0    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		ID64 AABCDEFGHIJKLM 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}

CLASS BlackHoledAracnorb : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 1.0;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	//DamageFactor "bloodsplasher", 0.0    DamageFactor "tinybloodsplasher", 0.0    DamageFactor "superbloodsplasher", 0.0    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 25, 0, 0, 0, 0, 128);
		ID65 AAABCDEFGH 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 25, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}  

CLASS BlackHoledAracnorbQueen : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.85;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	//DamageFactor "bloodsplasher", 0.0    DamageFactor "tinybloodsplasher", 0.0    DamageFactor "superbloodsplasher", 0.0    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		ID66 AAABCDEFGHIJK 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}  

CLASS BlackHoledArachnophyte : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.74;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	//DamageFactor "bloodsplasher", 0.0    DamageFactor "tinybloodsplasher", 0.0    DamageFactor "superbloodsplasher", 0.0    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 50, 0, 0, 0, 0, 128);
		ID67 AAABCDEFGHIJK 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 50, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
}  

CLASS BlackHoledBruiser : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 1.1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	//DamageFactor "bloodsplasher", 0.0    DamageFactor "tinybloodsplasher", 0.0    DamageFactor "superbloodsplasher", 0.0    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 50, 0, 0, 0, 0, 128);
		ID69 AAABCDEFGHIJ 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 50, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
} 

CLASS BlackHoledPaladin : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 1.1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	//DamageFactor "bloodsplasher", 0.0    DamageFactor "tinybloodsplasher", 0.0    DamageFactor "superbloodsplasher", 0.0    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 50, 0, 0, 0, 0, 128);
		ID70 AAABCDEFGH 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 50, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
} 

CLASS BlackHoledCyberKnight : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	Scale 1.1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	//DamageFactor "bloodsplasher", 0.0    DamageFactor "tinybloodsplasher", 0.0    DamageFactor "superbloodsplasher", 0.0    DamageFactor "smallbloodsplasher", 0.0;
	Mass 1000;
	Health 100;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 50, 0, 0, 0, 0, 128);
		ID71 AAABCDEFGHI 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 50, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
		Stop;
}
} 



CLASS BurnParticles : ACTOR { 
Default {
	
	Radius 8;
	Height 8;
	Speed 5;
	Mass 6;
	BounceFactor 0.5;
	+DOOMBOUNCE;
	Speed 0;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	+NODAMAGETHRUST;
	+NOCLIP;
	DamageType "Fire";
	+NOBLOOD;
	+NOBLOODDECALS;
	+BLOODLESSIMPACT;
	-BLOODSPLATTER;
}
States
{
	Spawn:
		TNT1 A 0;
		XDT3 A 0 A_Explode(3,30);
		TNT1 A 0 A_SpawnItem("RedFlare", 0, 5);
		TTRB A 0 bright a_spawnprojectile("PlasmaSmoke", 20, 0, random(0, 360), 2, random(60, 130));
		TTRB A 0 bright a_spawnprojectile("SmallFireTrail324", 0, 0, random(0, 360), 2, random(0, 130));
		TNT1 A 3;
		stop;
}
}

CLASS BurnParticlesNoPain : ACTOR { 
Default {
	
	Radius 8;
	Height 8;
	Speed 5;
	Mass 6;
	BounceFactor 0.5;
	+DOOMBOUNCE;
	Speed 0;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	+NODAMAGETHRUST;
	+NOCLIP;
	DamageType "Fire";
	+NOBLOOD;
	+NOBLOODDECALS;
	+BLOODLESSIMPACT;
	-BLOODSPLATTER;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("RedFlare", 0, 5);
		TTRB A 0 bright a_spawnprojectile("PlasmaSmoke", 20, 0, random(0, 360), 2, random(60, 130));
		TTRB A 0 bright a_spawnprojectile("SmallFireTrail324", 0, 0, random(0, 360), 2, random(0, 130));
		TNT1 A 3;
		stop;
}
}

CLASS SmallBurnParticles: BurnParticles { 
Default {
	
	DamageType "Burn";
}
States
{
	Spawn:
		TNT1 A 0;
		XDT3 A 0 A_Explode(2,30);
		TNT1 A 0 A_SpawnItem("RedFlare", 0, 5);
		TTRB A 0 bright a_spawnprojectile("PlasmaSmoke", 20, 0, random(0, 360), 2, random(60, 130));
		TTRB A 0 bright a_spawnprojectile("SmallFlameTrails", 0, 0, random(0, 360), 2, random(60, 130));
		stop;
}
}


CLASS BurnParticlesNoDamage: BurnParticles { 
Default {
	
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("RedFlare", 0, 5);
		TTRB A 0 bright a_spawnprojectile("PlasmaSmoke", 20, 0, random(0, 360), 2, random(60, 130));
		TTRB A 0 bright a_spawnprojectile("FlameTrails", 0, 0, random(0, 360), 2, random(60, 130));
		stop;
}
}




CLASS BurningZombieOld : ACTOR { 
Default {
	Radius 1;
	Height 1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	Mass 1000;
	Health 100;
}
States    {
	Spawn:
		TNT1 A 0 BRIGHT;
		TNT1 A 0 A_PlaySound("BURNZOM");
		BUR2 A 1 BRIGHT;
		BUR2 AABBCCDDEE 3 BRIGHT a_spawnprojectile("BurnParticles", 36, 0, random(0, 180), 2, random(0, 180));
		BURN FFGGHH 3 BRIGHT a_spawnprojectile("BurnParticles", 36, 0, random(0, 180), 2, random(0, 180));
		BURN IIJJKKLL 3 BRIGHT a_spawnprojectile("BurnParticles", 28, 0, random(0, 180), 2, random(0, 180));
		BURN MMN 3 BRIGHT a_spawnprojectile("BurnParticles", 32, 0, random(0, 180), 2, random(0, 180));
		BURN NOOPP 3 BRIGHT a_spawnprojectile("BurnParticles", 22, 0, random(0, 180), 2, random(0, 180));
		BURN QQ 3 BRIGHT a_spawnprojectile("BurnParticles", 18, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 A_PlaySound("BURNZOM");
		BURN RRSSTTSSRRSSTTSSRRSSTTRRSSTTSSRRSSTTSSRRSSTTSSTT 3 BRIGHT a_spawnprojectile("SmallBurnParticles", 12, 0, random(0, 180), 2, random(0, 180));
		BURN UU 3 BRIGHT a_spawnprojectile("BurnParticles", 12, 0, random(0, 180), 2, random(0, 180));
		BURN VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 9 a_spawnprojectile("PlasmaSmoke", 8, 0, random(0, 360), 2, random(90, 110));
		BURN V -1;
Stop;}}
   
   
   
   
   
   









CLASS DesintegratedHuman : ACTOR { 
Default {
	Radius 1;
	Height 1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	Mass 1000;
	Health 100;
	Scale 0.7;
	//Seesound "desintegratedflesh"
}
States    {
	Spawn:
		// TNT1 A 0 A_Jump(118, "Spawn2")
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "Spawn2");
		TNT1 A 0 A_PlaySound("desintegratedflesh", 3);
		TNT1 A 0 A_PlaySound("MELT",6);
		TNT1 AAAAA 0 a_spawnprojectile("BloodMistExtraBig", 22, 0, random(0, 360), 2, random(0, 90));
		TNT1 AAAAA 0 a_spawnprojectile("BloodmistBig", 37, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("BloodmistSmall", 30, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBloodLevel3", 37, 0, random(0, 360), 2, random(10, 50));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 30, 0, random(0, 360), 2, random(0, 90));
		TNT1 A 0 a_spawnprojectile("SuperGoreSpawner2", 30, 0, random(0, 360), 2, random(10, 90));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("BarrelExplosionSmokeColumn");
		ID50 AAABBBCCCDDDEEEFFFGGGGGGGGGGGGGGGGGGG 2 a_spawnprojectile("Brutal_LiquidBlood3", 18, 0, random(0, 360), 2, random(0, 40));
		ID50 G -1;
		Stop;
		
	Spawn2:
		TNT1 A 0 A_SpawnItemEx("DesintegratedHuman3",0,0,0,0,0,0,0,288);
		TNT1 A 1;
		Stop;
}}
  
CLASS DesintegratedHuman3 : ACTOR { 
Default {
	Radius 1;
	Height 1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	Mass 1000;
	Health 100;
	Scale 0.255;
}
States    {
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("desintegratedflesh", 3);
		TNT1 A 0 A_PlaySound("MELT",6,1);
		TNT1 AAAAA 0 a_spawnprojectile("BloodMistExtraBig", 22, 0, random(0, 360), 2, random(0, 90));
		TNT1 AAAAA 0 a_spawnprojectile("BloodmistBig", 37, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("BloodmistSmall", 30, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBloodLevel3", 37, 0, random(0, 360), 2, random(10, 50));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 30, 0, random(0, 360), 2, random(0, 90));
		TNT1 A 0 a_spawnprojectile("SuperGoreSpawner2", 30, 0, random(0, 360), 2, random(10, 90));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("BarrelExplosionSmokeColumn");
		M31T CCCCCDDDDDEEEEEFFFFGGGGHHHHIIIIJJJJKKKKKKKKKKKKK 2 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		M31T K -1;
		Stop;
}}
  

 
CLASS BurningFatso : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	Mass 1000;
	Health 100;
}
States   
{
	Spawn:
		TNT1 A 0 A_PlaySound("fatso/pain");
		TNT1 A 0 a_spawnprojectile("IncendiaryGrenadeExplosion", 10, 0, random(0, 360), 2, random(50, 130));
		
		BF4T AAAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T CCCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T AAAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T CCCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T AAAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T CCCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("fatso/pain");
		
		BF4T AAAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T CCCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T AAAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T CCCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("fatso/pain");
		
		BF4T AAAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T CCCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T AAAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T CCCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T AAAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T CCCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("fatso/death");
		
		
		BF4T DEF 4;
		BF4T F 1;
		TNT1 A 0 A_Playsound("props/redfire");
		BF4T FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 a_spawnprojectile("FlameTrails", 32, 0, random(0, 360), 2, random(70, 130));
		BF4T FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 10 a_spawnprojectile("PLasmaSmoke", 32, 0, random(0, 360), 2, random(70, 130));
		BF4T F -1;
		Stop;
}
}

CLASS BurningFatso2 : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	Mass 1000;
	Health 100;
}
States    
{
	Spawn:
		TNT1 A 0 A_PlaySound("fatso/pain");
		TNT1 A 0 a_spawnprojectile("IncendiaryGrenadeExplosion", 10, 0, random(0, 360), 2, random(50, 130));
		
		BF4T AAAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T CCCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T AAAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T CCCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T AAAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T CCCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("fatso/pain");
		
		BF4T AAAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T CCCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T AAAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T CCCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("fatso/pain");
		
		BF4T AAAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T CCCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T AAAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T CCCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T AAAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T CCCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BF4T BBBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("fatso/death");
		
		
		BF4T DEF 4;
		BF4T F 1;
		TNT1 A 0 A_Playsound("props/redfire");
		CARB OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 2 a_spawnprojectile("FlameTrails", 32, 0, random(0, 360), 2, random(70, 130));
		CARB OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 10 a_spawnprojectile("PLasmaSmoke", 32, 0, random(0, 360), 2, random(70, 130));
		CARB O -1;
		Stop;
}
}

CLASS BurningVolcabus : ACTOR { 
Default {
	
	Scale 1.25;
	Radius 1;
	Height 1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	Mass 1000;
	Health 100;
}
States    
{
	Spawn:
		
		TNT1 A 0 A_Playsound("VOLCBRN", 4);
		
		//TNT1 A 0 a_spawnprojectile("IncendiaryGrenadeExplosion", 10, 0, random(0, 360), 2, random(50, 130))
		EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90));
		
		F7T2 FFFF 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 GGGG 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 HHHH 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 GGGG 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 FFFF 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 GGGG 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 HHHH 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 GGGG 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 FFFF 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 GGGG 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		TNT1 A 0 A_Playsound("Volcabus/Pain");
		
		F7T2 HHHH 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 GGGG 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 FFFF 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 GGGG 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 HHHH 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		TNT1 A 0 A_Playsound("Volcabus/Pain");
		
		F7T2 GGGG 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 FFFF 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 GGGG 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 HHHH 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		TNT1 A 0 A_Playsound("Volcabus/Pain");
		
		F7T2 GGGG 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 FFFF 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 GGGG 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 HHHH 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		TNT1 A 0 A_Playsound("Volcabus/Pain");
		
		F7T2 GGGG 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 FFFF 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 GGGG 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		//EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90))
		
		F7T2 HHHH 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90));
		TNT1 A 0 A_Playsound("Volcabus/Pain");
		
		F7T2 GGGG 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90));
		
		F7T2 FFFF 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90));
		
		F7T2 GGGG 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90));
		
		F7T2 HHHH 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90));
		TNT1 A 0 A_Playsound("Volcabus/Death");
		
		F7T2 GGGG 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		EXPL AA 0 a_spawnprojectile("FlamethrowerFireParticles", 6, 0, random(0, 360), 2, random(10, 90));
		
		TNT1 A 0 a_spawnprojectile("IncendiaryGrenadeExplosion", 35, 0, random(0, 360), 2, random(50, 130));
		F7T2 B 4;
		EXPL AAAAAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		F7T2 CD 4;
		TNT1 A 0 A_Playsound("props/redfire");
		F7T2 EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 10 a_spawnprojectile("BigBlackSmoke", 1, 0, random(0, 360), 2, random(0, 160));
		F7T2 E -1;
		Stop;
}
}
  
  
CLASS BurningKnight : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	Mass 1000;
	Health 100;
}
States    
{
	Spawn:
		TNT1 A 0 A_PlaySound("PSXDPN");
		TNT1 A 0 a_spawnprojectile("IncendiaryGrenadeExplosion", 10, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 AAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 BBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 CCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 DDD 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("PSXDPN");
		BAF4 EEE 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 FFF 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 EEE 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 DDD 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("PSXDPN");
		BAF4 BBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 AAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 BBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 CCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("PSXDPN");
		
		BAF4 AAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 DDD 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 EEE 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 FFF 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("PSXDPN");
		BAF4 CCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 DDD 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 CCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 DDD 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("PSXDPN");
		BAF4 BBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 AAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 CCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 DDD 2 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("PSXDPN");
		
		BAF4 AAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 BBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 CCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 DDD 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("PSXDPN");
		BAF4 EEE 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 FFF 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 EEE 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 DDD 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("PSXDPN");
		BAF4 BBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 AAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 BBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 CCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("PSXDPN");
		
		BAF4 AAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 DDD 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 EEE 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 FFF 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("PSXDPN");
		BAF4 CCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 DDD 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 CCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 DDD 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("PSXDPN");
		BAF4 BBB 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 AAA 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 CCC 1 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		
		BAF4 DDD 2 a_spawnprojectile("BurnParticles", 45, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("PSXDPN");
		
		
		
		TNT1 A 0;//A_Scream
		TNT1 A 0 A_NoBlocking;
		BOSB AAAA 2 a_spawnprojectile("FlameTrails", 45, 0, random(0, 360), 2, random(50, 130));
		BOSB BBBB 2 a_spawnprojectile("FlameTrails", 30, 0, random(0, 360), 2, random(50, 130));
		BOSB CCCC 2 a_spawnprojectile("FlameTrails", 25, 0, random(0, 360), 2, random(50, 130));
		BOSB DDDD 2 a_spawnprojectile("FlameTrails", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Playsound("props/redfire");
		BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 2 a_spawnprojectile("FlameTrails", 25, 0, random(0, 360), 2, random(50, 130));
		BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 10 a_spawnprojectile("SmallSmoke", 25, 0, random(0, 360), 2, random(70, 110));
		BOSB E -1;
		Stop;
}
}
  
CLASS BurningBaron : BurningKnight { 
Default {
	
	Scale 1.2;
}
}	
  
  
  
CLASS BurningImp : ACTOR { 
Default {
	Radius 1;
	Height 1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	Mass 1000;
	Health 100;
}
States    {
	Spawn:
		IZD4 CCC 2 a_spawnprojectile("BurnParticles", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("imp/pain");
		IZD4 DDD 2 a_spawnprojectile("BurnParticles", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("imp/pain");
		IZD4 CCC 3 a_spawnprojectile("BurnParticles", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("imp/pain");
		IZD4 DDD 2 a_spawnprojectile("BurnParticles", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("imp/pain");
		IZD4 CCC 3 a_spawnprojectile("BurnParticles", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("imp/pain");
		IZD4 DDD 2 a_spawnprojectile("BurnParticles", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("imp/pain");
		IZD4 CCC 3 a_spawnprojectile("BurnParticles", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("imp/pain");
		IZD4 DDD 3 a_spawnprojectile("BurnParticles", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("imp/pain");
		IZD4 CCC 3 a_spawnprojectile("BurnParticles", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("imp/pain");
		IZD4 DDD 3 a_spawnprojectile("BurnParticles", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("imp/pain");
		IZD4 CCC 3 a_spawnprojectile("BurnParticles", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("imp/pain");
		IZD4 DDD 3 a_spawnprojectile("BurnParticles", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("imp/pain");
		
		
		DRKS LLLL 1 a_spawnprojectile("FlameTrails", 25, 0, random(0, 360), 2, random(50, 130));
		
		
		TNT1 A 0 A_Playsound("props/redfire");
		BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 a_spawnprojectile("FlameTrails", 15, 0, random(0, 360), 2, random(50, 130));
		BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 20 a_spawnprojectile("SmallSmoke", 25, 0, random(0, 360), 2, random(70, 110));
		BOSB F -1;
		
		Stop;
}
}

  
CLASS BurningImpDieFast : ACTOR { 
Default {
	Radius 1;
	Height 1;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	Mass 1000;
	Health 100;
}
States    {
	Spawn:
		DRKS IIIJJJJJ 1 a_spawnprojectile("BurnParticles", 32, 0, random(0, 360), 2, random(50, 130));
		DRKS KKKKKK 1 a_spawnprojectile("BurnParticles", 29, 0, random(0, 360), 2, random(50, 130));
		DRKS LLLLLL 1 a_spawnprojectile("BurnParticles", 25, 0, random(0, 360), 2, random(50, 130));
		
		
		TNT1 A 0 A_Playsound("props/redfire");
		BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 a_spawnprojectile("FlameTrails", 15, 0, random(0, 360), 2, random(50, 130));
		BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 20 a_spawnprojectile("SmallSmoke", 25, 0, random(0, 360), 2, random(70, 110));
		BOSB F -1;
		
		Stop;
}
}




CLASS BurningDemon2 : ACTOR { 
Default {
	Radius 22;
	Height 52;
	+NOTELEPORT;
	+SHOOTABLE;
	+MOVEWITHSECTOR;
	+SOLID;
	+NOBLOCKMONST;
	PainChance 0;
	Speed 15;
	//damagefactor "Blood", 0.0 damagefactor "BlueBlood", 0.0 damagefactor "GreenBlood", 0.0;
	damagefactor "Shrapnel", 0.3;
	damagefactor "Fire", 0.0;
	damagefactor "Flames", 0.0;
	damagefactor "Burn", 0.0;
	damagefactor "SSG", 5.0;
	damagefactor "Explosive", 5.0;
	damagefactor "ExplosiveImpact", 2.0;
	Mass 1000;
	Health 100;
}
States    {
	Spawn:
		CRB7 M 3 A_Wander;
		TNT1 A 0 a_spawnprojectile("BurnParticles", 25, 0, random(0, 360), 2, random(50, 130));
		CRB7 N 3 A_Wander;
		TNT1 A 0 a_spawnprojectile("BurnParticles", 25, 0, random(0, 360), 2, random(50, 130));
		CRB7 O 3 A_Wander;
		TNT1 A 0 a_spawnprojectile("BurnParticles", 25, 0, random(0, 360), 2, random(50, 130));
		CRB7 P 3 A_Wander;
		TNT1 A 0 a_spawnprojectile("BurnParticles", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_playsound("demon/pain");
		TNT1 A 0 A_GiveInventory("DeathTimer1", 1);
		TNT1 A 0 A_JumpIfInventory("DeathTimer1", 20, "GotoDeath");
	Loop;
		
	GotoDeath:
	Death:
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 A_Jump(96, "Death2");
		CRB7 Q  2;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_playsound("demon/death");
		CRB7 QQQQ 2 a_spawnprojectile("BurnParticles", 35, 0, random(0, 360), 2, random(50, 130));
		CRB7 RRRR 2 a_spawnprojectile("BurnParticles", 26, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_SpawnItem("BurnedDemon");
		Stop;
		
	Death2:
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_playsound("demon/pain");
		P1N7 AAA 3 a_spawnprojectile("FlamethrowerFireParticles", 20, 0, random(0, 360), 2, random(50, 130));
		P1N7 BBB 3 a_spawnprojectile("FlamethrowerFireParticles", 20, 0, random(0, 360), 2, random(50, 130));
		P1N7 CCC 3 a_spawnprojectile("FlamethrowerFireParticles", 20, 0, random(0, 360), 2, random(50, 130));
		P1N7 DDD 3 a_spawnprojectile("FlamethrowerFireParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_playsound("demon/pain");
		P1N7 CCC 3 a_spawnprojectile("FlamethrowerFireParticles", 20, 0, random(0, 360), 2, random(50, 130));
		P1N7 DDD 3 a_spawnprojectile("FlamethrowerFireParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_playsound("demon/pain",2);
		P1N7 CCC 3 a_spawnprojectile("FlamethrowerFireParticles", 20, 0, random(0, 360), 2, random(50, 130));
		P1N7 DDD 3 a_spawnprojectile("FlamethrowerFireParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_playsound("demon/pain",3);
		P1N7 CCC 3 a_spawnprojectile("FlameTrails", 23, 0, random(0, 360), 2, random(50, 130));
		P1N7 DDD 3 a_spawnprojectile("FlameTrails", 23, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_playsound("demon/pain",4);
		P1N7 CCC 3 a_spawnprojectile("FlameTrails", 23, 0, random(0, 360), 2, random(50, 130));
		P1N7 DDD 3 a_spawnprojectile("FlameTrails", 23, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_playsound("demon/death",5);
		TNT1 A 0 A_SpawnItem("BurnedDemon2");
		stop;
		
	XDeath:
	Death.SSG:
	Death.Explosive:
		TNT1 A 0 A_NOBlocking;
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedDemonLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("MuchMeatDeath", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("BurningFlyingMeatPiece", 64, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		Stop;
}
}

CLASS BurningMeanDemon : ACTOR { 
Default {
	Radius 22;
	Height 52;
	+NOTELEPORT;
	+SHOOTABLE;
	+MOVEWITHSECTOR;
	+SOLID;
	+NOBLOCKMONST;
	PainChance 0;
	Speed 15;
	//damagefactor "Blood", 0.0 damagefactor "BlueBlood", 0.0 damagefactor "GreenBlood", 0.0;
	damagefactor "Shrapnel", 0.3;
	damagefactor "Fire", 0.0;
	damagefactor "Flames", 0.0;
	damagefactor "Burn", 0.0;
	damagefactor "SSG", 5.0;
	damagefactor "Explosive", 5.0;
	damagefactor "ExplosiveImpact", 2.0;
	Mass 1000;
	Health 100;
}
States    {
	Spawn:
		CRB9 M 3 A_Wander;
		TNT1 AA 0 a_spawnprojectile("BurnParticles", random(24,26), random(-4,4), random(0, 360), 2, random(50, 130));
		CRB9 N 3 A_Wander;
		TNT1 AA 0 a_spawnprojectile("BurnParticles", random(24,26), random(-4,4), random(0, 360), 2, random(50, 130));
		CRB9 O 3 A_Wander;
		TNT1 AA 0 a_spawnprojectile("BurnParticles", random(24,26), random(-4,4), random(0, 360), 2, random(50, 130));
		CRB9 P 3 A_Wander;
		TNT1 AA 0 a_spawnprojectile("BurnParticles", random(24,26), random(-4,4), random(0, 360), 2, random(50, 130));
		
		TNT1 A 0 A_playsound("demon/pain");
		
		TNT1 A 0 A_GiveInventory("DeathTimer1", 1);
		TNT1 A 0 A_JumpIfInventory("DeathTimer1", 20, "GotoDeath");
		Loop;
		
	GotoDeath:
		TNT1 A 0;
		Goto Death;
		
	Death:
		TNT1 A 0 {self.bSHOOTABLE = false;}
		CRB9 Q  2;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_playsound("demon/death");
		CRB9 QQQQ 2 a_spawnprojectile("BurnParticles", 35, 0, random(0, 360), 2, random(50, 130));
		CRB9 RRRR 2 a_spawnprojectile("BurnParticles", 26, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_SpawnItem("BurnedDemon");
		Stop;
		
	XDeath:
	Death.SSG:
	Death.Explosive:
		TNT1 A 0 A_NOBlocking;
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedDemonLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("MuchMeatDeath", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("BurningFlyingMeatPiece", 64, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		Stop;
}
}

CLASS BurningVoidDemon : ACTOR { 
Default {
	Radius 22;
	Height 52;
	+NOTELEPORT;
	+SHOOTABLE;
	+MOVEWITHSECTOR;
	+SOLID;
	+NOBLOCKMONST;
	PainChance 0;
	Speed 15;
	//damagefactor "Blood", 0.0 damagefactor "BlueBlood", 0.0 damagefactor "GreenBlood", 0.0;
	damagefactor "Shrapnel", 0.3;
	damagefactor "Fire", 0.0;
	damagefactor "Flames", 0.0;
	damagefactor "Burn", 0.0;
	damagefactor "SSG", 5.0;
	damagefactor "Explosive", 5.0;
	damagefactor "ExplosiveImpact", 2.0;
	Mass 1000;
	Health 100;
}
States    {
	Spawn:
		CRB8 M 3 A_Wander;
		TNT1 AA 0 a_spawnprojectile("BurnParticles", random(24,26), random(-4,4), random(0, 360), 2, random(50, 130));
		CRB8 N 3 A_Wander;
		TNT1 AA 0 a_spawnprojectile("BurnParticles", random(24,26), random(-4,4), random(0, 360), 2, random(50, 130));
		CRB8 O 3 A_Wander;
		TNT1 AA 0 a_spawnprojectile("BurnParticles", random(24,26), random(-4,4), random(0, 360), 2, random(50, 130));
		CRB8 P 3 A_Wander;
		TNT1 AA 0 a_spawnprojectile("BurnParticles", random(24,26), random(-4,4), random(0, 360), 2, random(50, 130));
		
		TNT1 A 0 A_playsound("demon/pain");
		
		TNT1 A 0 A_GiveInventory("DeathTimer1", 1);
		TNT1 A 0 A_JumpIfInventory("DeathTimer1", 20, "GotoDeath");
		Loop;
		
	GotoDeath:
		TNT1 A 0;
		Goto Death;
		
	Death:
		TNT1 A 0 {self.bSHOOTABLE = false;}
		CRB8 Q  2;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_playsound("demon/death");
		CRB8 QQQQ 2 a_spawnprojectile("BurnParticles", 35, 0, random(0, 360), 2, random(50, 130));
		CRB8 RRRR 2 a_spawnprojectile("BurnParticles", 26, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_SpawnItem("BurnedDemon");
		Stop;
		
	XDeath:
	Death.SSG:
	Death.Explosive:
		TNT1 A 0 A_NOBlocking;
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedDemonLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("MuchMeatDeath", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("BurningFlyingMeatPiece", 64, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		Stop;
}
}


CLASS BurnedDemon : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
}
States
{
	Spawn:
		TNT1 A 0 A_Playsound("props/redfire");
		CARB JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 2 a_spawnprojectile("FlameTrails", 25, 0, random(0, 360), 2, random(50, 130));
		CARB JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 20 a_spawnprojectile("SmallSmoke", 35, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0 {self.bSHOOTABLE = false;}
		CARB J -1;
		Stop;
}
}



CLASS BurnedDemon2 : ACTOR { 
Default {
	
	Radius 1;
	Height 1;
}
States
{
	Spawn:
		TNT1 A 0 A_Playsound("props/redfire");
		TNT1 A 0 {self.bSHOOTABLE = false;}
		P1N7 EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 2 a_spawnprojectile("BurnParticles", 32, 0, random(0, 360), 2, random(50, 130));
		P1N7 EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 15 a_spawnprojectile("SmallSmoke", 30, 0, random(0, 360), 2, random(50, 130));
		P1N7 E -1;
		stop;
}
}








CLASS DyingZombiemanInFlames : ACTOR { 
Default {
	
	Radius 12;
	Height 30;
	Speed 5;
	Health 20;
	PainSound "grunt/pain";
	DeathSound "grunt/death";
	+SHOOTABLE;
	+FLOORCLIP;
	//+NOBLOCKMAP
	+NOICEDEATH;
	+LOOKALLAROUND;
	+FRIGHTENED;
	-SOLID;
	damagefactor "Burn", 0.0;
	damagefactor "Fire", 0.0;
	damagefactor "Flames", 0.0;
}
States
{
	
	Spawn:
		TNT1 A 0;
		ZMAB A 1 A_Look;
		Loop;
	See:
		TNT1 A 0;
		TNT1 A 0 A_Playsound("BurnZom");
	See2:
		ZMAB A 5 A_Chase;
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		ZMAB A 5 A_Chase;
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		
		ZMAB B 5 A_Chase;
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		ZMAB B 5 A_Chase;
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_SpawnItem("pb_blood_spot");
		TNT1 A 0 A_GiveInventory("DeathTimer1", 1);
		TNT1 A 0 A_JumpIfInventory("DeathTimer1", 15, "GotoDeath");
		Loop;
		
	GotoDeath:
		TNT1 A 0;
		Goto Death;
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		TNT1 A 0 {self.bSHOOTABLE = false;}
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 3 a_spawnprojectile("BurnParticles", 5, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_SpawnItem("SmallFireFocusSpawnerz1");
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHH 10 a_spawnprojectile("PlasmaSmoke", 15, 0, random(0, 360), 2, random(50, 130));
		BRZ3 H -1;
	Crush:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS2 A 5;
		CRS2 A -1;
		Stop;
		
	Death.Stomp:
	Death.SSG:
	XDeath:
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AAAAAA 0 bright a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright a_spawnprojectile("XDeath2", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright a_spawnprojectile("XDeath3", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 A 0 A_SpawnItem("CrushedRemains");
		TNT1 A 1;
		TNT1 A 0 ACS_Execute(477, 0, 0, 0, 0);
		TNT1 A 1 A_XScream;
		TNT1 A 1 A_NoBlocking;
		TNT1 A -1;
		Stop;
}
}



CLASS DyingSergeantNoLegInFlames : ACTOR { 
Default {
	
	Radius 12;
	Height 30;
	Speed 5;
	Health 20;
	PainSound "grunt/pain";
	DeathSound "grunt/death";
	+SHOOTABLE;
	+FLOORCLIP;
	//+NOBLOCKMAP
	+LOOKALLAROUND;
	+NOICEDEATH;
	+FRIGHTENED;
	-SOLID;
	
	damagefactor "Burn", 0.0;
	damagefactor "Fire", 0.0;
	damagefactor "Flames", 0.0;
}
States
{
	
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Playsound("BurnZom");
		ZMAB A 1 A_Look;
		Loop;
	See:
		SMBM A 5 A_Chase;
		TNT1 A 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		SMBM A 5 A_Chase;
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		
		SMBM B 5 A_Chase;
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		SMBM B 5 A_Chase;
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		
		TNT1 A 0 A_GiveInventory("DeathTimer1", 1);
		TNT1 A 0 A_JumpIfInventory("DeathTimer1", 15, "GotoDeath");
		Loop;
		
	GotoDeath:
		TNT1 A 0;
		Goto Death;
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 3 a_spawnprojectile("BurnParticles", 5, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_SpawnItem("SmallFireFocusSpawnerz1");
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHH 10 a_spawnprojectile("PlasmaSmoke", 15, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 {self.bSHOOTABLE = false;}
		BRZ3 H -1;
	Crush:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS2 A 5;
		CRS2 A -1;
		Stop;
		
	Death.Stomp:
	Death.SSG:
	XDeath:
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AAAAAA 0 bright a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright a_spawnprojectile("XDeath2", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright a_spawnprojectile("XDeath3", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 A 0 A_SpawnItem("CrushedRemains");
		TNT1 A 1;
		TNT1 A 0 ACS_Execute(477, 0, 0, 0, 0);
		TNT1 A 1 A_XScream;
		TNT1 A 1 A_NoBlocking;
		TNT1 A -1;
		Stop;
}
}






CLASS BurningZombie : ACTOR { 
Default {
	
	Radius 12;
	Height 56;
	Speed 5;
	Scale 0.85;
	Health 100;
	GibHealth 25;
	damagefactor "Burn", 0.0;
	damagefactor "Fire", 0.0;
	damagefactor "Flames", 0.0;
	damagefactor "Flame", 0.0;
	damagefactor "Head", 0.0;
	damagefactor "ExplosiveImpact", 10.0;
	MONSTER;
	-COUNTKILL;
	+NOICEDEATH;
	+FRIENDLY;
	+FLOORCLIP;
	+SHOOTABLE;
	+NOBLOCKMONST;
	+DONTSPLASH;
	
	Gravity 0.7;
	bloodtype "DeadBlood";
	Obituary "%o was near someone in flames.";
	MaxDropOffHeight 6000;
	
	Mass 999999;
}
States
{
	Spawn:
		BDT1 B 0 a_spawnprojectile("BurnParticles", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("BURNZOM");
	Suffer:
		BDT1 AAA 1 Bright A_Wander;
		TNT1 A 0 A_Recoil(-2);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 40, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		BDT1 BBB 1 Bright A_Wander;
		TNT1 A 0 A_Recoil(-2);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 40, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		BDT1 CCC 1 Bright A_Wander;
		TNT1 A 0 A_Recoil(-2);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 40, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		BDT1 DDD 1 Bright A_Wander;
		TNT1 A 0 A_Recoil(-2);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 40, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 12, "Death");
		//TNT1 A 0 A_JumpIf(vel.z < 5, "Falling")
		Loop;
	Falling:
		BDT2 AA 1 Bright;
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		BDT2 BB 1 Bright;
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		BDT2 CC 1 Bright;
		TNT1 A 0 A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		BDT2 DD 1 Bright;
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_JumpIf(vel.z == 0, "fallDeath");
		Loop;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, "Death");
		TNT1 A 0 ThrustThingZ(0,60,0,1);
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0;
		Goto Looping;
		
	Looping:
		BDT3 AAAA 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT3 BBBB 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT3 CCCC 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT3 DDDD 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		Loop;
		
	FallDeath:
		TNT1 AAAAAAAAAA 0 a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(20, 150));
		TNT1 AAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(20, 150));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 10, 0, random(0, 360), 2, random(20, 150));
		TNT1 A 0 A_PlaySound("misc/xdeath");
		TNT1 A 0 A_Explode(100, 128);
		Goto Death;
	Death:
		TNT1 A 0 A_Fall;
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 {self.bNOTARGET = true;}
		
		TNT1 A 0 A_Jump(128, "Death2");
		BDT1 EEFFGGHHiijjkkLLmm 3 Bright a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		NJEX AAAAAAAAAAAAAAAAAA 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_SpawnItem("SmallFireFocusSpawnerz1");
		NJEX AAAAAAAAAAAAAAAAAA 10 Bright a_spawnprojectile("PlasmaSmoke", 15, 0, random(0, 360), 2, random(50, 130));
		NJEX A -1;
		Stop;
	Death2:
		BDT1 EEFFGGHHiijjkkLLmm 3 Bright a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		NJEX BBBBBBBBBBBBBBBBBB 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_SpawnItem("SmallFireFocusSpawnerz1");
		NJEX BBBBBBBBBBBBBBBBBB 10 Bright a_spawnprojectile("PlasmaSmoke", 15, 0, random(0, 360), 2, random(50, 130));
		NJEX B -1;
		Stop;
	XDEATH:
	DEATH.SSG:
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 {self.bNOTARGET = true;}
		TNT1 A 0 A_PlaySound("misc/xdeath");
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("MuchMeatDeath", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("BurningFlyingMeatPiece", 64, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		Stop;
}
}


CLASS PoorGuyBurningLife : Inventory { 
Default {
	
	inventory.maxamount 20;
}
}








CLASS BurningCacodemon : ACTOR { 
Default {
	
	Radius 12;
	Height 56;
	Speed 3;
	Scale 0.85;
	Health 100;
	GibHealth 25;
	+NOICEDEATH;
	damagefactor "Burn", 0.5;
	damagefactor "Fire", 0.5;
	damagefactor "Flames", 0.5;
	damagefactor "Flame", 0.5;
	damagefactor "ExplosiveImpact", 10.0;
	bloodtype "Blue_Blood";
	bloodcolor "DarkBlue";
	MONSTER;
	-COUNTKILL;
	+FLOAT;
	+NOGRAVITY;
	+FRIENDLY;
	+FLOORCLIP;
	+SHOOTABLE;
	+NOBLOCKMONST;
	+DONTSPLASH;
	Gravity 1.0;
	bloodtype "DeadBlood";
	Obituary "%o was near someone in flames.";
	Mass 100;
}
States
{
	Spawn:
		TNT1 A 0 a_spawnprojectile("BurnParticles", 40, 0, random(0, 360), 2, random(50, 130));
		HEAD NN 1 Bright A_Chase(null, null);
		Goto Suffer;
	Suffer:
		HEAD OO 1 Bright A_Wander;
		TNT1 A 0 A_Recoil(-1);
		
		BDT1 B 0 a_spawnprojectile("BurnParticles", 40, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("FireballExplosionFlamesBig", 40, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		
		
		HEAD NN 1 Bright A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 40, 0, random(0, 360), 2, random(50, 130));
		HEAD B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 15, "Death");
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		Loop;
		
	Death:
		TNT1 A 0 A_Fall;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 {self.bNOTARGET = true;}
		TNT1 A 0 {self.bNOGRAVITY = false;}
		HEAD P 1 A_SpawnItem("SmallFireFocusSpawnerz1");
		TNT1 A 0 A_Playsound("props/redfire");
		HEAD PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP 8 a_spawnprojectile("FireballExplosionFlamesBig", 15, 0, random(0, 360), 2, random(50, 130));
		HEAD P 1 A_SpawnItem("SmallFireFocusSpawnerz1");
		HEAD PPPPPPPPPPPPPPPPPPPPPPPP 6 a_spawnprojectile("PlasmaSmoke", 15, 0, random(0, 360), 2, random(50, 130));
		HEAD P -1;
		Stop;
}
}





































CLASS BurningZombieMan : ACTOR { 
Default {
	
	Radius 12;
	Height 56;
	Speed 3;
	Health 30;
	GibHealth 25;
	damagefactor "Burn", 0.0;
	damagefactor "Fire", 0.0;
	damagefactor "Flames", 0.0;
	damagefactor "Flame", 0.0;
	damagefactor "Head", 0.0;
	damagefactor "Ice", 0.0;
	damagefactor "ExplosiveImpact", 10.0;
	MONSTER;
	-COUNTKILL;
	+FRIENDLY;
	+FLOORCLIP;
	+SHOOTABLE;
	+NOBLOCKMONST;
	
	Gravity 0.7;
	bloodtype "DeadBlood";
	Obituary "%o was near someone in flames.";
	MaxDropOffHeight 6000;
	
	Mass 999999;
}
States
{
	Spawn:
		BRZ1 B 0 a_spawnprojectile("BurnParticles", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("BURNZOM");
		Goto Suffer;
	Suffer:
		BRZ3 AAA 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		BRZ3 BBB 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		BRZ3 CCC 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		BRZ3 BBB 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 9, "Death");
		Loop;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, "Death");
		TNT1 A 0 ThrustThingZ(0,60,0,1);
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0;
		Goto Looping;
		
	Looping:
		BDT3 AAAA 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT3 BBBB 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT3 CCCC 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT3 DDDD 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		Loop;
		
	FallDeath:
		TNT1 AAAAAAAAAA 0 a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(20, 150));
		TNT1 AAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(20, 150));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 10, 0, random(0, 360), 2, random(20, 150));
		TNT1 A 0 A_PlaySound("misc/xdeath");
		TNT1 A 0 A_Explode(100, 128);
		Goto Death;
	Death:
		TNT1 A 0 A_Fall;
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 {self.bNOTARGET = true;}
		
		TNT1 A 0 A_Jump(256, "Death1", "Death2", "Death3");
		Goto Death1;
		
	Death1:
		TNT1 A 0 A_PlaySound("BURNZOM");
		BRZ3 DD 3 a_spawnprojectile("BurnParticles", 30, 0, random(0, 360), 2, random(50, 130));
		BRZ3 EE 3 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 3 a_spawnprojectile("BurnParticles", 5, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_SpawnItem("SmallFireFocusSpawnerz1");
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHH 10 a_spawnprojectile("PlasmaSmoke", 15, 0, random(0, 360), 2, random(50, 130));
		BRZ3 H -1;
		Stop;
	Death2:
		TNT1 A 0 A_PlaySound("BURNZOM");
		BRZ3 DD 3 a_spawnprojectile("BurnParticles", 30, 0, random(0, 360), 2, random(50, 130));
		BRZ3 EE 3 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		
		BRZ3 IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII 3 a_spawnprojectile("BurnParticles", 5, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_SpawnItem("SmallFireFocusSpawnerz1");
		BRZ3 IIIIIIIIIIIIIIIII 10 a_spawnprojectile("PlasmaSmoke", 15, 0, random(0, 360), 2, random(50, 130));
		BRZ3 I -1;
		Stop;
		
	Death3:
		TNT1 A 0 A_PlaySound("BURNZOM");
		BRZ3 DD 3 a_spawnprojectile("BurnParticles", 30, 0, random(0, 360), 2, random(50, 130));
		BRZ3 EE 3 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_SpawnItem("DyingZombiemanInFlames");
		Stop;
		
	XDEATH:
	DEATH.SSG:
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 {self.bNOTARGET = true;}
		TNT1 A 0 A_PlaySound("misc/xdeath");
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("MuchMeatDeath", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("BurningFlyingMeatPiece", 64, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		Stop;
}
}


CLASS BurningShotgunguy: BurningZombieMan { 
States
{
	Spawn:
		BRZ1 B 0 a_spawnprojectile("BurnParticles", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("BURNZOM");
		Goto Suffer;
	Suffer:
		BRZ3 AAA 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		BRZ3 BBB 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		BRZ3 CCC 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		BRZ3 BBB 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 12, "Death");
		Loop;
		
		
	Death:
		TNT1 A 0 A_Fall;
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 {self.bNOTARGET = true;}
		
		TNT1 A 0 A_Jump(256, "Death1", "Death2", "Death3");
		Goto Death1;
		
	Death1:
		TNT1 A 0 A_PlaySound("BURNZOM");
		BRZ3 DD 3 a_spawnprojectile("BurnParticles", 30, 0, random(0, 360), 2, random(50, 130));
		BRZ3 EE 3 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 3 a_spawnprojectile("BurnParticles", 5, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_SpawnItem("SmallFireFocusSpawnerz1");
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHH 10 a_spawnprojectile("PlasmaSmoke", 15, 0, random(0, 360), 2, random(50, 130));
		BRZ3 H -1;
		Stop;
	Death2:
		TNT1 A 0 A_PlaySound("BURNZOM");
		BRZ3 DD 3 a_spawnprojectile("BurnParticles", 30, 0, random(0, 360), 2, random(50, 130));
		BRZ3 EE 3 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		
		BRZ3 IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII 3 a_spawnprojectile("BurnParticles", 5, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_SpawnItem("SmallFireFocusSpawnerz1");
		BRZ3 IIIIIIIIIIIIIIIII 10 a_spawnprojectile("PlasmaSmoke", 15, 0, random(0, 360), 2, random(50, 130));
		BRZ3 I -1;
		Stop;
		
	Death3:
		TNT1 A 0 A_PlaySound("BURNZOM");
		BRZ3 DD 3 a_spawnprojectile("BurnParticles", 30, 0, random(0, 360), 2, random(50, 130));
		BRZ3 EE 3 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 FF 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Wander;
		BRZ3 GG 3 Bright a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_SpawnItem("DyingSergeantNoLegInFlames");
		Stop;
		Stop;
}
}









CLASS BurningcHAINGUNGUY: BurningZombieMan { 
States
{
	Spawn:
		BRZ1 B 0 a_spawnprojectile("BurnParticles", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("BURNZOM");
		Goto Suffer;
	Suffer:
		CPBR AAA 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		CPBR BBB 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		CPBR CCC 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		CPBR BBB 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 12, "Death");
		Loop;
		
	Death:
		TNT1 A 0 {self.bShootable = false;}
		TNT1 A 0 A_NoBlocking;
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 3 a_spawnprojectile("BurnParticles", 5, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_SpawnItem("SmallFireFocusSpawnerz1");
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHH 10 a_spawnprojectile("PlasmaSmoke", 15, 0, random(0, 360), 2, random(50, 130));
		BRZ3 H -1;
		Stop;
}
}




CLASS BurningImpRunning: BurningZombieMan { 
Default {
	Scale 1.05;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("BURNZOM");
		Goto Suffer;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, "Death");
		TNT1 A 0 ThrustThingZ(0,60,0,1);
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0;
		Goto Looping;
		
	Looping:
		TRBR AAAA 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TRBR BBBB 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TRBR CCCC 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TRBR DDDD 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		Loop;
		
	FallDeath:
		TNT1 AAAAAAAAAA 0 a_spawnprojectile("BurnParticles", 10, 0, random(0, 360), 2, random(20, 150));
		TNT1 AAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 10, 0, random(0, 360), 2, random(20, 150));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 10, 0, random(0, 360), 2, random(20, 150));
		TNT1 A 0 A_PlaySound("misc/xdeath");
		TNT1 A 0 A_Explode(100, 128);
		Goto Death;
		
	Suffer:
		TRBR AAA 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 A 0 A_PlaySound("imp/pain");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		TRBR BBB 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		TRBR CCC 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		TRBR DDD 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 8, "Death");
		Loop;
	Death:
		TNT1 A 0 A_Fall;
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 {self.bNOTARGET = true;}
		TNT1 A 0 A_SpawnItem("BurningImp");
		Stop;
}
}

CLASS BurningDarkImpNami : BurningImpRunning { 
States
{
	
	Spawn:
		TNT1 A 0 A_PlaySound("BURNZOM");
		Goto Suffer;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, "Death");
		TNT1 A 0 ThrustThingZ(0,60,0,1);
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0;
		Goto Looping;
		
	Looping:
		T1BR AAAA 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		T1BR BBBB 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		T1BR CCCC 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		T1BR DDDD 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		Loop;
		
	Suffer:
		T1BR AAA 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 A 0 A_PlaySound("imp/pain");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		T1BR BBB 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		T1BR CCC 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		T1BR DDD 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 8, "Death");
		Loop;
		
}
}

CLASS BurningImpST : BurningImpRunning { 
States
{
	
	Spawn:
		TNT1 A 0 A_PlaySound("BURNZOM");
		Goto Suffer;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, "Death");
		TNT1 A 0 ThrustThingZ(0,60,0,1);
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0;
		Goto Looping;
		
	Looping:
		T2BR AAAA 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T2BR BBBB 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T2BR CCCC 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T2BR DDDD 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		Loop;
		
	Suffer:
		T2BR AAA 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 A 0 A_PlaySound("imp/pain");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		T2BR BBB 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		T2BR CCC 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		T2BR DDD 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 8, "Death");
		Loop;
}
}

CLASS BurningImpBig : BurningImpRunning { 
States
{
	
	Spawn:
		TNT1 A 0 A_PlaySound("BURNZOM");
		Goto Suffer;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, "Death");
		TNT1 A 0 ThrustThingZ(0,60,0,1);
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0;
		Goto Looping;
		
	Looping:
		T3BR AAAA 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T3BR BBBB 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T3BR CCCC 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T3BR DDDD 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		Loop;
		
	Suffer:
		T3BR AAA 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 A 0 A_PlaySound("imp/pain");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		T3BR BBB 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		T3BR CCC 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		T3BR DDD 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 8, "Death");
		Loop;
}
}


CLASS BurningImpUgly : BurningImpRunning { 
States
{
	
	Spawn:
		TNT1 A 0 A_PlaySound("BURNZOM");
		Goto Suffer;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, "Death");
		TNT1 A 0 ThrustThingZ(0,60,0,1);
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0;
		Goto Looping;
		
	Looping:
		T4BR AAAA 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T4BR BBBB 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T4BR CCCC 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T4BR DDDD 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		TNT1 B 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		Loop;
		
	Suffer:
		T4BR AAA 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 A 0 A_PlaySound("imp/pain");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		T4BR BBB 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		T4BR CCC 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		T4BR DDD 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 8, "Death");
		Loop;
}
}

CLASS BurningImpSavage: BurningImpRunning { 
States
{
	
	Spawn:
		TNT1 A 0 A_PlaySound("BURNZOM");
		Goto Suffer;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, "Death");
		TNT1 A 0 ThrustThingZ(0,60,0,1);
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0;
		Goto Looping;
		
	Looping:
		T5BR AAAA 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 AA 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T5BR BBBB 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 AA 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T5BR CCCC 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 AA 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		T5BR DDDD 1 Bright A_JumpIf(vel.z == 0, "fallDeath");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 AA 0 a_spawnprojectile("FlameTrails", 20, 0, random(0, 360), 2, random(50, 130));
		Loop;
		
	Suffer:
		T5BR AAA 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 A 0 A_PlaySound("SavageImp/pain");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("FlameTrails", 40, 0, random(0, 360), 2, random(50, 130));
		T5BR BBB 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("FlameTrails", 40, 0, random(0, 360), 2, random(50, 130));
		T5BR CCC 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("FlameTrails", 40, 0, random(0, 360), 2, random(50, 130));
		T5BR DDD 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 B 0 a_spawnprojectile("FlameTrails", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 8, "Death");
		Loop;
		
	Death:
		TNT1 A 0 A_Fall;
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 {self.bNOTARGET = true;}
		TNT1 A 0 A_SpawnItem("BurningImpDieFast");
		Stop;
}
}








CLASS BurningDemon: BurningZombieMan { 
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("BURNZOM");
		Goto Suffer;
	Suffer:
		SBRG AAA 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 A 0 A_playsound("demon/pain");
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		SBRG BBB 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		SBRG CCC 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		SBRG DDD 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 15, "Death");
		Loop;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 A_Jump(96, "Death2");
		TNT1 A 0 A_SpawnItem("BurnedDemon");
		Stop;
		
	Death2:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_playsound("demon/pain");
		P1N7 AAA 3 a_spawnprojectile("FlameTrails", 30, 0, random(0, 360), 2, random(50, 130));
		P1N7 BBB 3 a_spawnprojectile("FlameTrails", 30, 0, random(0, 360), 2, random(50, 130));
		P1N7 CCC 3 a_spawnprojectile("FlameTrails", 30, 0, random(0, 360), 2, random(50, 130));
		P1N7 DDD 3 a_spawnprojectile("FlameTrails", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_playsound("demon/pain");
		P1N7 CCC 3 a_spawnprojectile("FlameTrails", 30, 0, random(0, 360), 2, random(50, 130));
		P1N7 DDD 3 a_spawnprojectile("FlameTrails", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_playsound("demon/pain",2);
		P1N7 CCC 3 a_spawnprojectile("FlameTrails", 30, 0, random(0, 360), 2, random(50, 130));
		P1N7 DDD 3 a_spawnprojectile("FlameTrails", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_playsound("demon/pain",3);
		P1N7 CCC 3 a_spawnprojectile("FlameTrails", 30, 0, random(0, 360), 2, random(50, 130));
		P1N7 DDD 3 a_spawnprojectile("FlameTrails", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_playsound("demon/pain",4);
		P1N7 CCC 3 a_spawnprojectile("FlameTrails", 30, 0, random(0, 360), 2, random(50, 130));
		P1N7 DDD 3 a_spawnprojectile("FlameTrails", 30, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_playsound("demon/death",5);
		TNT1 A 0 A_SpawnItem("BurnedDemon2");
		stop;
		
	XDeath:
	Death.SSG:
	Death.Explosive:
		TNT1 A 0 A_NOBlocking;
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedDemonLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("MuchMeatDeath", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("BurningFlyingMeatPiece", 64, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		Stop;
}
}
















CLASS BurningZombieManSimple: BurningZombieMan { 
Default {
	Speed 1;
}
States
{
	Spawn:
		BRZ5 B 0 a_spawnprojectile("BurnParticles", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_PlaySound("BURNZOM");
		Goto Suffer;
	Suffer:
		BRZ5 AAA 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		BRZ5 BBB 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		BRZ5 CCC 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		BRZ5 DDD 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		BRZ5 EEE 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		BRZ5 FFF 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		BDT1 B 0 a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
		BDT1 B 0 a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 4, "Death");
		Loop;
}
}