//this would be a veeeeeeeery big file
CLASS gibs_base : pb_blood_and_gore_base
{ 
Default {
	Radius 10;
	Height 10;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+DONTSPLASH;
	+NOBLOCKMONST;
	-NOBLOCKMAP;
	+THRUACTORS;
	+FLOORCLIP;
	+SLIDESONWALLS;
	+FORCEXYBILLBOARD;
	+NOTAUTOAIMED;

	DamageFactor "CauseObjectsToSplash", 0.0;
	DamageFactor "GibRemoving", 0.5;
	//+SOLID
	-SOLID;
	+SHOOTABLE;
	damagefactor "Crush", 50.0;
	damagefactor "Shrapnel", 100.0;
	damagefactor "Plasma", 20.0;
	damagefactor "Fire", 0.0;
	damagefactor "TeleportRemover", 1000.0;
	Mass 1000;
	Health 100;
	damagefactor "Blood", 0.0;    damagefactor "GreenBlood", 0.0;    damagefactor "BlueBlood", 0.0;
    damagefactor "Taunt", 0.0;    damagefactor "KillMe", 0.0;  damagefactor "Avoid", 0.0;
	damagefactor "Taunt", 0.0;
	damagefactor "Trample", 5000.0;
	painchance 255;
}

States
{
	Spawn:
		TNT1 A 1900 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	Loop;

	Death:
		TNT1 AAAAAAA 0 a_spawnprojectile("XDeathSkinPiece2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeathSkinPiece1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallSuperGore", 10, 0, random(0, 360), 2, random(10, 170));
		TNT1 AA 0 a_spawnprojectile("Bloodmist", 10, 0, random(0, 360), 2, random(30, 90));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 90));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 10, 0, random(0, 360), 2, random(50, 90));
	Stop;

	Death.plasma:
		TNT1 A 0;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL AAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0;
	Stop;

	Death.Trample:
	Death.Crush:
	Death.Stomp:
	Death.SuperPunch:
	Death.ExtremePunches:
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 30));
		TNT1 AAAA 0 a_spawnprojectile("BloodMist", 5, 0, random(0, 360), 2, random(0, 30));
		TNT1 AAAAAAA 0 a_spawnprojectile("XDeathSkinPiece2", 5, 0, random(0, 360), 2, random(10, 30));
		TNT1 AAAA 0 a_spawnprojectile("XDeathSkinPiece1", 5, 0, random(0, 360), 2, random(10, 130));
		TNT1 AAAA 0 a_spawnprojectile("SmallSuperGore", 10, 0, random(0, 360), 2, random(10, 30));
		TNT1 A 0 A_SpawnItem("SplatteredSmall");
		XME2 L 1;
		XME2 L -1;
	Stop;

	Death.TeleportRemover:
	Death.GibRemoving:
		TNT1 A 1 {self.destroy(); return;}
	Stop;

	Death.Desintegrate:
		TNT1 A 0;
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFake", 0, 0, random(0, 360), 2, random(0, 90));
		TNT1 A 0 a_spawnprojectile("Brutal_FlyingBlood", 7, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 a_spawnprojectile("Bloodmist", 7, 0, random(0, 360), 2, random(30, 60));
	Stop;
}

}


CLASS Limbs_Base: gibs_base { 
	Default {
	Radius 6;
	Height 10;
	Mass 1000;
	Painchance 256;
	Health 35;
	+FORCEXYBILLBOARD;
	+DONTSPLASH;
	+SHOOTABLE;
	-CLIENTSIDEONLY;
	+NOBLOCKMONST;
	//+SOLID
	+THRUACTORS;
	+FLOORCLIP;
	damagefactor "Crush", 50.0;
	DeathSound "misc/xdeath4";
	damagefactor "Blood", 0.0;    damagefactor "GreenBlood", 0.0;
    damagefactor "BlueBlood", 0.0;    damagefactor "Taunt", 0.0;
    damagefactor "KillMe", 0.0;  damagefactor "Avoid", 0.0;  damagefactor "Taunt", 0.0;
	//damagefactor "Plasma", 99000.0
	damagefactor "Trample", 2.0;
	damagefactor "Kick", 9.0;
	damagefactor "Explosive", 0.1;
	damagefactor "ExplosiveImpact", 9.1;
	damagefactor "Shrapnel", 100.0;
	damagefactor "Melee", 9.0;
	damagefactor "SuperPunch", 9.0;
	damagefactor "Plasma", 20.0;
	painchance 0;
}

States
{
	Spawn:
		TNT1 A 1900 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	Loop;

	Death:
		TNT1 AAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		XDT3 BCDEFGH 3;
	Death.Crush:
		TNT1 A 1 a_spawnprojectile("XDeath1", 5, 5, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 5, -5, random(0, 360), 2, random(0, 160));
		CRSB A 9009;
	Stop;
}

}
	

// Blood trails spawned by FlyingBlood
CLASS pb_FlyingBloodTrail8 : pb_blood_and_gore_base { 
Default {
	scale 0.70;
	mass 1;
	Decal "BrutalBloodSplat";
	+LOWGRAVITY;
	+NOTELEPORT;
	+NOBLOCKMAP;
	+NOCLIP;
	+FORCEXYBILLBOARD;
	+CLIENTSIDEONLY;
	-DONTSPLASH;
	+MISSILE;
	-NOGRAVITY;
	Speed 3;
}
	states
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "null");
		BTRL ABCD 8;
	stop;
}

}

CLASS Greenpb_FlyingBloodTrail : pb_blood_and_gore_base { 
	Default {
	-NOGRAVITY;
	+NOCLIP;
	radius 16;
	height 16;
	gravity 0.5;
	Scale 1.5;
	translation "168:191=112:127","16:47=120:127";
	+FORCEXYBILLBOARD;
	+NOBLOCKMAP;
}

states
{
Spawn:
	TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
	TNT1 A 0 Thing_ChangeTid(0,386);
	BLOD ABCD 2;
	stop;
Splash:
	TNT1 A 0;
	Stop;
}
}


CLASS Bluepb_FlyingBloodTrail : pb_blood_and_gore_base
{ 
Default {
	-NOGRAVITY
	+NOCLIP;
	radius 16;
	height 16;
	gravity 0.5;
	Scale 1.5;
	translation "168:191=192:207","16:47=240:247";
	decal "CacoBloodSplat";
	+FORCEXYBILLBOARD;
}
states
	{
	Spawn:
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
		TNT1 A 0;
		BLOD ABCD 2;
	stop;
    Splash:
        TNT1 A 0;
        Stop;
	}
}



CLASS XDeath1 : pb_blood_and_gore_base { 
Default {
    Radius 8;
    Height 8;
    Speed 10;
    Scale 1.2;
	Mass 1;
    +NOBLOCKMAP
	+MISSILE
    +NOTELEPORT
    +MOVEWITHSECTOR
    +CLIENTSIDEONLY
    +RIPPER
    +BLOODLESSIMPACT 
	-DONTSPLASH
	+THRUGHOST
	+thrUACTORS
	+FLOORCLIP;
	damagetype "Blood";
	SeeSound "misc/xdeath4";
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSuper";
	Mass 1;
}

States
{
	Spawn:
		TNT1 A 0 nodelay
		{
			gravity = frandom(0.4, 1);
		}
		BLOD A 4 a_spawnprojectile("XDeath1Trail", 0, 0, random(0, 360), 2, random(0, 360));
	Loop;

	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot", 0, 1);
		XDT1 EFGHIJKL 3;
	Stop;
	
	Underwater:
	Splash:
		BLUD C 0 ThrustThingZ(0,35,1,0);
		XDT1 AB 3 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		BLUD C 0 ThrustThingZ(0,35,1,0);
		XDT1 CD 3 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
	stop;
		
	IsOverLiquid:
		TNT1 A 1;
		TNT1 A 0 A_SpawnItem("WaterBloodSpot", 5);
		Stop;
	}
}

CLASS XDeath2 : XDeath1
{
Default
{
	DeathSound "misc/xdeath2";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
		XME1 ABCD 3 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		TNT1 AAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 A_CheckFloor("SpawnFloor");
		TNT1 A 0 A_SpawnItemEx("CeilBloodSpot",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("DetectCeilXDeath2",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		Stop;
		
	SpawnFloor:
		XME1 E 1;
		TNT1 A 0 A_QueueCorpse;
		XME1 E -1;
		TNT1 A 0;
		XME1 E 3;
		TNT1 A 0 A_SpawnItemEx("PB_Blood_Spot", 0, 0, 1);
	Living:
		XME1 E -1;
	stop;
	}
}


CLASS XDeath3: XDeath2 { 
	Default {
	SeeSound "misc/xdeath4";
	DeathSound "misc/xdeath3";
	Decal "BrutalBloodSuper";
	Scale 1.1;
	Speed 10;
	Gravity 1.2;
}

States
{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
		XME2 ABCD 3 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		TNT1 AAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 A_CheckFloor("SpawnFloor");
		TNT1 A 0 A_SpawnItemEx("CeilBloodSpot",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("DetectCeilXDeath3",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		Stop;
		
	SpawnFloor:
		XME2 E 1;
		TNT1 A 0 A_QueueCorpse;
		XME2 E -1;
		TNT1 A 0;
		XME2 E 3;
		TNT1 A 0 A_SpawnItemEx("PB_Blood_Spot", 0, 0, 1);
	Living:
		XME2 E -1;
	stop;
}
}


CLASS XDeath4: XDeath2 { 
Default {
	SeeSound "misc/xdeath4";
	DeathSound "misc/xdeath3";
	Scale 1.1;
	+DOOMBOUNCE;
	BounceFactor 0.3;
}
States
{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
		XME3 ABCDEFGH 3 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_Jump(255, "Death1", "Death2");
	Death1:
		TNT1 A 0;
		XME3 GH 3;
		XME3 A 1;
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	Living1:
		TNT1 A 0 A_QueueCorpse;
		XME3 A -1;
	stop;
	Death2:
		XME3 I 1;
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		XME3 I 1;
	Living2:
		XME3 I -1;
	stop;
}

}

CLASS XDeath4b: XDeath2 { 
Default
{
	SeeSound "misc/xdeath4";
	DeathSound "misc/xdeath3";
	Scale 1.0;
	+DOOMBOUNCE;
	BounceFactor 0.01;
	Gravity 1.0;
	wallbouncefactor 0.2;
	Speed 4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
		GIB4 AAAAAA 3 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		GIB4 B 1;
		TNT1 A 0 A_QueueCorpse;
		GIB4 B -1;
		TNT1 A 0;
		GIB4 B 1;
		TNT1 A 0 A_SpawnItemEx("PB_Blood_Spot", 0, 0, 1);
	Living1:
		GIB4 B 600;//duration
		Loop;
	Vanish:
		TNT1 A 1;
		Stop;
	}
}

CLASS XDeath5: XDeath2 { 
Default {
	SeeSound "misc/xdeath4";
	DeathSound "misc/xdeath3";
	Scale 1.1;
}
States
{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
		XME5 ABCD 3 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		TNT1 AAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 A_SpawnItemEx("PB_Blood_Spot", 0, 0, 1);
		XME5 E 1;
		TNT1 A 0 A_QueueCorpse;
		XME5 E -1;
		XME5 E 3;
	Living:
		XME5 E 800;//duration
		Loop;
	Vanish:
		TNT1 A 1;
		Stop;
		
	}
}


CLASS XDeathOrgan1: XDeath2 { 
Default {
	SeeSound "misc/xdeath4";
	DeathSound "misc/xdeath3";
	Scale 0.9;
	Speed 4;
}
States
{
	Spawn:
		tnt1 a 0 nodelay
		{
			self.scale.x = frandompick(1, 0.7, -0.7, 1.1);
			self.scale.y = frandompick(1, 0.5, -0.5, 1.1);
		}
		tnt2 a 0 a_jump(126, "spawn_2", "spawn_3");
		XME8 A 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		XME8 A 1 A_QueueCorpse;
		XME8 A -1;
	Stop;

	Spawn_2:
		XME8 B 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		XME8 B 1 A_QueueCorpse;
		XME8 B -1;
	Stop;

	spawn_3:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
		XME4 AAAABBBBCCCCDDDD 2;
		TNT1 AAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 A_QueueCorpse;
		XME4 E -1;
	Stop;
}

}










	
	
	
	
	
	
	
	
	
	
	
	
/////////////////
//ARMS
/////////////////

class XDeathArm1 : pb_blood_and_gore_base
{
default {
	Radius 8;
	Height 8;
	Scale 1.2;
	Speed 8;
	Mass 1;
	gravity 0.5;
	Decal "BrutalBloodSplat";
	BounceFactor 0.4;
	BounceCount 3;
	+DOOMBOUNCE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MISSILE;
	+EXPLODEONWATER;
	+SKYEXPLODE;
	-DONTSPLASH;
	seesound "bloood";
	deathsound "bloood";
}

States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		XARM AEBCFDG 5 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
	Loop;

	Death:
		XDT5 I 1;
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		XDT5 I 0 A_SpawnItem("Gib_Arm");
	Stop;
}

}

	
class Gib_Arm: Limbs_Base
{
default{
	Scale 1.2;
}

States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		XDT5 I 1 A_SpawnItem("PB_Blood_Spot", 0, 1);
		XDT5 I -1;
	Stop;

	Death.plasma:
	Death.Burn:
	Death.Flames:    
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedArm", 2, 0, random(0, 360), 2, 270)    ;
	Stop;
	Death:    
		TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("GibHand", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GibArmPart", 0, 0, random(0, 180), 2, random(0, 180));
	Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		XDT5 II 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathArm1Kicked", 5, 0, random(170, 190), 2, random(20, 40));
	Stop;
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		XARM ABCD 3;
	Goto Spawn;
	
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		XARM A 6;
		XARM ABCDABCDABCD 6 A_CheckFloor("Landz");
	Goto Landz;
	Landz:
		XDT5 I 0 A_SpawnItem("Gib_Arm");
	Stop;
}

}


CLASS XDeathArm1Kicked: XDeathArm1 { 
	Default {
+ACTIVATEMCROSS
+ACTIVATEIMPACT
+CANUSEWALLS
	}
    States
    {
    Spawn:
	    TNT1 A 0 {self.bNOCLIP = true;}
	    XARM A 2;
		TNT1 A 0 {self.bNOCLIP = false;}
		TNT1 A 0;
        TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		XARM ABCD 6 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
	Goto Spawn+3;
	}
}

CLASS GibArmPart: gibs_base { 
	Default {
 
    Scale 1.0;
	}
    States
    {
	Spawn:
	XDT5 Z 1;
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	XDT5 Z -1;
	Stop;
    Death:
XDT5 Z 1;
       Loop;
}}

CLASS GibHand: gibs_base { 
	Default {
 
    Scale 1.0;
	}
    States
    {
	Spawn:
	XDT5 Y 1;
	TNT1 A 0 A_QueueCorpse;
	XDT5 Y -1;
       Stop;
    Death:
XDT5 Y 1;
       Loop;
}}


CLASS XDeathArm2: XDeathArm1 { 
	Default {
	Speed 10;
	}
}













/////////////////////
//LEGS
/////////////////////

























//////////////
//GUTS
//////////////


CLASS XDeathStomach: XDeathArm1 { 
	Default {
	
	BounceType "none";
	BounceFactor 0.0;
	Speed 2;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		XSTO A 24 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		XSTO EEEEEEEEE 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 180), 2, random(0, 180));
		XSTO E -1;
		Stop;
	}
}

CLASS XDeathStomachGreen: XDeathArm1 { 
	Default {
	
translation "168:191=112:127","16:47=120:127";
	BounceType "none";
	BounceFactor 0.0;
	Speed 2;
	}
    States
    {
Spawn:
	TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	XSTO A 24 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
	Loop;
Death:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	XSTO EEEEEEEEE 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 180), 2, random(0, 180));
	XSTO E -1;
	Stop;
}
}




CLASS XDeathHalfMarine : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Speed 4;
	Mass 8;
	BounceFactor 0.2;
	BounceCount 3;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		HPLA A 12 a_spawnprojectile("pb_FlyingBloodTrail",0,0,180,2);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		HPLA A 0 A_SpawnItem("HalfMarineGib",0,0,0,1);
		Stop;
	}
}

CLASS HalfMarineGib: gibs_base { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		HPLA A 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		HPLA A -1;
Stop;    }}







CLASS XDeathMeat2 : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Scale 0.8;
	Speed 11;
	Mass 1;
	BounceFactor 0.4;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		XDT5 D 2;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		XDT5 D -1;
		Stop;
	}
}

CLASS XDeathBrain1 : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Scale 0.8;
	Speed 13;
	Mass 1;
	BounceFactor 0.3;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+MISSILE;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		XDB5 ABCD 6;
		Loop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "Death2");
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		XDT5 B -1;
		Stop;
	Death2:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		XDT5 O -1;
		Stop;
	}
}

CLASS XDeathBrain2 : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Scale 0.8;
	Speed 12;
	Mass 1;
	BounceFactor 0.3;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+MISSILE;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		XDB5 EFGH 6;
		Loop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		XDT5 C -1;
		Stop;
	}
}

CLASS XDeathSmashedBrain : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Scale 0.8;
	Speed 10;
	Mass 1;
	BounceFactor 0.4;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		BRS1 A 4;
		Goto Death;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		BRS1 A -1;
		Stop;
	}
}

CLASS XDeathStomachHeavy : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Scale 0.8;
	Speed 2;
	Mass 4;
	Decal "BrutalBloodSplat";
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	}
	States
	{
	Spawn:
		XDT5 F 1;
		Loop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		XDT5 F -1;
		Stop;
	}
}

CLASS XDeathTripe : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Scale 0.8;
	Speed 13;
	Mass 4;
	Decal "BrutalBloodSplat";
	BounceFactor 0.4;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	}
	States
	{
	Spawn:
		XDT5 H 1;
		Loop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		XDT5 H -1;
		Stop;
	}
}

CLASS XDeathTripeHeavy : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Scale 0.8;
	Speed 2;
	Mass 4;
	Decal "BrutalBloodSplat";
	BounceFactor 0.4;
	+DOOMBOUNCE;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	}
	States
	{
	Spawn:
		XDT5 H 1;
		Loop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		XDT5 H -1;
		Stop;
	}
}




CLASS XDeathGreen : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Speed 18;
	Mass 1;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+DOOMBOUNCE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	SeeSound "misc/xdeath4";
	DeathSound "misc/xdeath3";
	Decal "GreenBloodSuper";
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 4 a_spawnprojectile("Greenpb_FlyingBloodTrail",0,0,180,2);
		Loop;
	Death:
		TNT1 A 1;
		Stop;
	}
}

CLASS XDeathBlue1 : pb_blood_and_gore_base { 
Default {
	Radius 8;
	Height 8;
	Speed 12;
	Mass 1;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+DOOMBOUNCE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	SeeSound "misc/xdeath4";
	DeathSound "misc/xdeath3";
	Decal "BlueBloodSplat";
	BounceFactor 0.4;
}
protected int frame_num;
States
{
	Spawn:
		TNT1 A 0 nodelay A_JumpIf(waterlevel > 1, "Death");
		tnt1 a 0 {frame_num = random(0,4);}
		XDT6 A 6 {
			a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 160));
			frame = frame_num;
			}
		Loop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		XDT6 A -1 {frame = frame_num;}
		Stop;
	}
}


CLASS Instestin : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 12;
	Speed 6;
	Mass 1;
	BounceFactor 0.4;
	Renderstyle "Translucent";
	Alpha 0.9;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+FORCEXYBILLBOARD;
	-EXPLODEONWATER;
	DeathSound "misc/xdeath2";
	Decal "BrutalBloodSplat";
	Scale 0.8;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3", "Spawn4");
		
	Spawn1:
		GUTS A 4;
		Loop;
		
	Spawn2:
		GUTS B 4;
		Loop;
		
	Spawn3:
		GUTS C 4;
		Loop;
		
	Spawn4:
		GUTS D 4;
		Loop;
		
	Death:
		GUTS E 0;
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Water");
	Goto Rest;
		
		
	Rest:
		TNT1 A 0;
		TNT1 A 0 A_SetAngle(random(0,360));
		TNT1 A 0 {self.bFLATSPRITE = true;}
		TNT1 A 0 A_QueueCorpse;
		TNT1 A 0 A_Jump(255, "Rest1", "Rest2");
	Rest1:
		GUTS Y -1;
		Stop;
		
	Rest2:
		GUTS Z -1;
		Stop;
	DoNothing:
		TNT1 A 0;
		Stop;
		
	Water:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "Water2");
		Goto Water1;
		
	Water1:
		GUTS GH 10;
		//TNT1 A 0 A_JumpIf(waterlevel == 0, "Death")
		Loop;
		
	Water2:
		GUTS IJ 10;
		//TNT1 A 0 A_JumpIf(waterlevel == 0, "Death")
		Loop;
	}
}

CLASS Instestin2: Instestin { 
	Default {
	
	Speed 3;
	}
}
























CLASS BurningFlyingMeatPiece : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Speed 16;
	Scale 0.8;
	Mass 1;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+RIPPER;
	+BLOODLESSIMPACT;
	BounceFactor 0.4;
	damagetype "Blood";
	SeeSound "misc/xdeath4";
	DeathSound "misc/xdeath1";
	Decal "BloodSuper";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
		XME1 ABCD 2 a_spawnprojectile("FlameTrails", 2, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0 {pb_blood_and_gore_event.big_blood(self);}
		Loop;
	Death:
		XME1 E 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 AAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 180), 2, random(0, 180));
		XME1 EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 7 a_spawnprojectile("FlameTrails", 10, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		XME1 E -1;
		Stop;
	Splash:
		TNT1 A 0;
		Stop;
	}
}





CLASS Teeth : pb_blood_and_gore_base { 
	Default {
	
	Height 2;
	Radius 2;
	Speed 6;
	Scale 0.15;
	+DOOMBOUNCE;
	- NOGRAVITY;
	+WINDTHRUST;
	+CLIENTSIDEONLY;
	+MOVEWITHSECTOR;
	+MISSILE;
	+NOBLOCKMAP;
	-DROPOFF;
	+NOTELEPORT;
	+FORCEXYBILLBOARD;
	+NOTDMATCH;
	+THRUACTORS;
	+GHOST;
	}
	States
	{
	Spawn:
		XTET ABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGHABCDEFGH 3;
		Stop;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LCPJ A 0 A_Jump(256,"Rest1","Rest2");
		Goto Rest1;
	Rest1:
		XTET C 250;
		TNT1 A 0 A_CheckSight("Vanish");
	Rest2:
		XTET G 250;
		TNT1 A 0 A_CheckSight("Vanish");
		Loop;
		
	Vanish:
		TNT1 A 0;
		Stop;
	}
}


CLASS TeethNoBounce: Teeth { 
Default {
	BounceType "none";
	}
}































CLASS Ashes1: XDeath1 { 
	Default {
	
	Speed 5;
	Gravity 0.2;
	DeathSound "none";
	SeeSound "none";
	+DOOMBOUNCE;
	+DONTSPLASH;
	BounceFactor 0.01;
	Decal "";
	Scale 1.0;
	}
	States
	{
	Spawn:
		ASHZ ABCB 3;
		Loop;
	Death:
		ASHZ B 2000;
		Stop;
	Splash:
		TNT1 A 0;
		TNT1 A 0;
		Stop;
	}
}


CLASS Ashes2: XDeath1 { 
	Default {
	
	Speed 5;
	Gravity 0.2;
	+DONTSPLASH;
	DeathSound "none";
	SeeSound "none";
	Decal "";
	Scale 1.0;
	}
	States
	{
	Spawn:
		ASHY ABCB 3;
		Loop;
	Death:
		ASHY B 2000;
		Stop;
	Splash:
		TNT1 A 0;
		TNT1 A 0;
		Stop;
	}
}










CLASS BasicGib : pb_blood_and_gore_base { 
	Default {
	
	Radius 6;
	Height 6;
	+NOBLOCKMAP;
	+CLIENTSIDEONLY;
	Mass 50;
	}
	States
	{
	Spawn:
		TNT1 A 1;
		Stop;
	}
}




CLASS BasicMarineGib1: BasicGib { 
	States
	{
	Spawn:
		TNT1 A 1;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		TNT1 A 0 A_SetAngle(random(0, 359));
		TNT1 A 0 A_Recoil(3);
		XDMG A -1;
		Stop;
	}
}


CLASS BasicMarineGib2: BasicGib { 
	States
	{
	Spawn:
		TNT1 A 1;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		TNT1 A 0 A_SetAngle(random(0, 359));
		TNT1 A 0 A_Recoil(3);
		XDMG B -1;
		Stop;
	}
}


CLASS BasicMarineGib3: BasicGib { 
	States
	{
	Spawn:
		TNT1 A 1;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		TNT1 A 0 A_SetAngle(random(0, 359));
		TNT1 A 0 A_Recoil(3);
		XDMG C -1;
		Stop;
	}
}


CLASS BasicMarineGib4: BasicGib { 
	States
	{
	Spawn:
		TNT1 A 1;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		TNT1 A 0 A_SetAngle(random(0, 359));
		TNT1 A 0 A_Recoil(3);
		XDMG D -1;
		Stop;
	}
}






// QSZ ARM






CLASS XDeathSkinPiece1: Xdeath1 { 
	Default {
	
	Radius 2;
	Height 2;
	Speed 10;
	Scale 1.0;
	Mass 1;
	SeeSound "none";
	DeathSound "none";
	Mass 1;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Underwater");
		XSKI A 4;
		Loop;
	Death:
		XSKI B 1;
		TNT1 A 0 A_QueueCorpse;
		XSKI B -1;
		Stop;
		TNT1 A 1;
	Underwater:
	Splash:
		Goto Death;
	}
}	


CLASS XDeathSkinPiece2: Xdeath1 { 
	Default {
	
	Radius 2;
	Height 2;
	Speed 10;
	Scale 1.0;
	Mass 1;
	SeeSound "none";
	DeathSound "none";
	Mass 1;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Underwater");
		XSKI C 4;
		Loop;
	Death:
		XSKI D 1;
		TNT1 A 0 A_QueueCorpse;
		XSKI D -1;
		Stop;
		TNT1 A 1;
	Underwater:
	Splash:
		Goto Death;
	}
}



//////gore2.dec


CLASS SargeXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 NoDelay A_Jump(110, "Spawn2");
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 40, 0, random(0, 360), 2, random(-15, 15));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath5", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfShotgunguyNoArmNoHead", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSargeLeg2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSergeantHead", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 A 0 A_QueueCorpse;
		LEG2 Y -1;
		Stop;
		Stop;
		
	Spawn2:
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 40, 0, random(0, 360), 2, random(-15, 15));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathNewSergeantArm1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathNewSergeantLeg1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathNewSergeantLowerTorso", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathNewSergeantUpperTorso", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSergeantHead", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 A 0 A_QueueCorpse;
		LEG2 Y -1;
		Stop;
		Stop;
		
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAA 0 {pb_blood_and_gore_event.gore_spawner_2(self);}
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("SuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 {pb_blood_and_gore_event.gore_spawner_2(self);}
		Stop;
}
}






CLASS MarineXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathArm2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
		
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAA 0 {pb_blood_and_gore_event.gore_spawner_2(self);}
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("SuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 {pb_blood_and_gore_event.gore_spawner_2(self);}
		Stop;
}
}



CLASS MeatDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
	Death:
		TNT1 A 0;
		Stop;
}
}


CLASS SmalllMeatDeath: MeatDeath { 
States
{
	Spawn:
		TNT1 AAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 AAAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 160));
	Death:
		TNT1 A 0;
		Stop;
}
}

CLASS MuchMeatDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
	Death:
		TNT1 A 0;
		Stop;
}
}




CLASS RipGuts : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("Instestin2", 32, 0, random(0, 360), 2, random(0, 160));
	Death:
		TNT1 A 0;
		Stop;
}
}










CLASS MeatDeathSmall: ImpXDeath { 
States
{
	Spawn:
		TNT1 AA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 10, 0, random(0, 360), 2, random(40, 90));
		TNT1 A 0 a_spawnprojectile("XDeathSkinPiece2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSkinPiece1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SmallSuperGore", 10, 0, random(0, 360), 2, random(10, 170));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 35, 0, random(0, 360), 2, random(40, 90));
		Stop;
}
}


////gore3.dec

CLASS XDeathBurnedLeg : pb_blood_and_gore_base { 
Default {
	
	Radius 8;
	Height 8;
	Speed 5;
	Mass 6;
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
}
States
{
	Spawn:
		CARB E 10 a_spawnprojectile("ExplosionSmoke",0,0,180,2);
		Loop;
	Death:
		CARB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 14 a_spawnprojectile("ExplosionSmoke", 1, 0, random(0, 360), 2, random(0, 160));
		CARB E -1;
		Stop;
}
}


CLASS XDeathBurnedSkull : XDeathBurnedLeg { 
States
{
	Spawn:
		BURN B 10 a_spawnprojectile("ExplosionSmoke",0,0,180,2);
		Loop;
	Death:
		BURN BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 14 a_spawnprojectile("ExplosionSmoke", 1, 0, random(0, 360), 2, random(0, 160));
		BURN B -1;
		Stop;
}
}

CLASS XDeathBurnedArm : XDeathBurnedLeg { 
States
{
	Spawn:
		CARB D 10 a_spawnprojectile("ExplosionSmoke",0,0,180,2);
		Loop;
	Death:
		CARB DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 14 a_spawnprojectile("ExplosionSmoke", 1, 0, random(0, 360), 2, random(0, 160));
		CARB D -1;
		Stop;
}
}




CLASS XDeathBurnedMeat : XDeathBurnedLeg { 
protected int frame_num;
States
{
	Spawn:
		tnt1 a 0 nodelay {frame_num = random(0,2);}
		CARB A 10 { frame = frame_num; a_spawnprojectile("ExplosionSmoke",0,0,180,2);}
		CARB AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 14 {a_spawnprojectile("ExplosionSmoke", 1, 0, random(0, 360), 2, random(0, 160)); frame = frame_num; }
		CARB A -1;
	Stop;
}

}


CLASS XDeathBurnedBlueMeat1 : XDeathBurnedLeg { 
States
{
	Spawn:
		tnt1 a 0 nodelay {a_jump(126, "Spawn2");}
		CACB P 10 a_spawnprojectile("ExplosionSmoke",0,0,180,2);
		CACB PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP 15 a_spawnprojectile("ExplosionSmoke", 1, 0, random(0, 360), 2, random(0, 160));
		BURN D -1;
	Stop;

	Spawn2:
		CACB Q 10 a_spawnprojectile("ExplosionSmoke",0,0,180,2);
		CACB QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ 15 a_spawnprojectile("ExplosionSmoke", 1, 0, random(0, 360), 2, random(0, 160));
		BURN D -1;
	Stop;
}
}