//Tracing projectiles goes here
CLASS Tracer: FastProjectile { 
Default {
	
	Projectile;
	+RANDOMIZE;
	+FORCEXYBILLBOARD;
	+DONTSPLASH;
	//+BLOODSPLATTER 
	+NOEXTREMEDEATH;
	damage 0;
	radius 2;
	height 2;
	speed 140;
	renderstyle "Add";
	alpha 0.9;
	scale .15;
}
states
{
	Spawn:
		TRAC A 1 BRIGHT;
		Loop;
	Death:
		TNT1 A 0;
	Stop;
}
}

CLASS MinigunTracer: Tracer {
Default {
	-DONTSPLASH;
	seesound "weapons/chainwiz";
	damagetype "Cutless";
}
}

///////////////////////////////////////////////////////////////////////////////PB

CLASS ExplosiveChaingunTracer : Tracer { 
Default {
	+BLOODSPLATTER;
	-NOEXTREMEDEATH;
	+EXTREMEDEATH;
	speed 75;
	damage 12;
	scale .35;
	radius 3;
	height 3;
	seesound "None";
	damagetype "ExplosiveImpact";
	Decal "Scorch";
}
States
{
	
	Spawn:
		TRAC A 1 BRIGHT;
		Loop;
		
	Death:
	Xdeath:
		EXPL A 0 A_Explode(3, random(32,42), 1);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 1 A_SpawnItem("HitPuff");
		TNT1 A 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 40));
		
		TNT1 A 0 A_PlaySound("FAREXPL");
		TNT1 AAA 4 a_spawnprojectile("ExplosionSmoke", 2, 0, random(0, 360), 2, random(0, 360));
		Stop;
}
}


CLASS FlackTracer: Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUGHOST;
	+Friendly;
	+DONTSPLASH;
	speed 80;
	damage 12;
	Decal "BulletChip";
	DamageType "FriendBullet";
}
States
{
	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
		Stop;
}
}

//////////////////////////////////////////////////////////////////////////////////


CLASS MonsterTracer: Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUGHOST;
	-DONTSPLASH;
	+MISSILE;
	speed 60;
	damagefunction(random(3,4));
	Decal "BulletDecalNew1";
	DamageType "Bullet";
}
States
{
	Spawn:
		TRAC A 1 BRIGHT;
	Loop;
		
	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
	Stop;
}
}

CLASS ZombieManTracer: MonsterTracer { 
Default {
	
	damagefunction(random(5,6));
	Seesound "LightDistantGunshot";
}
}

CLASS MonsterHandgunTracer: MonsterTracer { 
Default {
	
	damagefunction(random(5,6));
	Seesound "SmallerDistantGunshot";
}
}


CLASS MonsterMinigunTracer: MonsterTracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUGHOST;
	-DONTSPLASH;
	speed 60;
	damagefunction(random(4,5));
	seesound "NONE";
	damagetype "Cutless";
	Decal "BulletDecalNew1";
}
States
{
	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
		Stop;
}
}

CLASS MonsterNewchaingunTracer: Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUGHOST;
	-DONTSPLASH;
	speed 80;
	damagefunction(random(5,7));
	Seesound "HeavyDistantGunshot";
	damagetype "Cutless";
	Decal "BulletChip";
}
States
{
	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
		Stop;
}
}


CLASS MonsterLMGTracer: Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUGHOST;
	-DONTSPLASH;
	speed 80;
	damagefunction(random(6,7));
	Seesound "HeavyDistantGunshot";
	damagetype "Cutless";
	Decal "BulletChip";
}
States
{
	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
		Stop;
}
}

CLASS MeatShieldTracer: Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUACTORS;
	-DONTSPLASH;
	speed 100;
	damagefunction(random(20,25));
	Decal "BulletDecalNew1";
	//DamageType "FriendBullet"
	DamageType "Bullet";
}
States
{
	Spawn:
		TRAC A 1 BRIGHT;
		TNT1 A 0 {self.bTHRUACTORS = false;}
	Fly:
		TRAC A 1 BRIGHT;
	Loop;

	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
	Stop;
}
}

CLASS MeatShieldShotgunTracer1: Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUACTORS;
	-DONTSPLASH;
	speed 100;
	damagefunction(random(20,25));
	Decal "BulletDecalNew1";
	damagetype "Cutless";
}
States
{
	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
		Stop;
		
	Spawn:
		TRAC A 1 BRIGHT;
		TNT1 A 0 {self.bTHRUACTORS = false;}
		Goto Fly;
	Fly:
		TRAC A 1 BRIGHT;
		Loop;
}
}

CLASS MeatShieldShotgunTracer2: Tracer { 
Default {
	
	+BLOODSPLATTER;
	+THRUACTORS;
	-DONTSPLASH;
	speed 100;
	damagefunction(random(20,25));
	Decal "BulletDecalNew1";
	damagetype "Shotgun";
}
States
{
	Death:
		TNT1 A 1 A_SpawnItem("HitPuff");
		Stop;
		
	Spawn:
		TRAC A 1 BRIGHT;
		TNT1 A 0 {self.bTHRUACTORS = false;}
		Goto Fly;
	Fly:
		TRAC A 1 BRIGHT;
		Loop;
}
}

CLASS Alerter: MonsterTracer { 
Default {
	
	-BLOODSPLATTER;
	+THRUGHOST;
	+DONTSPLASH;
	speed 200;
	radius 12;
	height 12;
	damagefunction(random(1,1));
	DamageType "Avoid";
	Decal "None";
}
States
{
	Spawn:
		TNT1 A 1 BRIGHT;
		Loop;
	Death:
		TNT1 A 0;
		Stop;
}
}

CLASS RareAlerter: Alerter { 
Default {
	
	Speed 70;
	+THRUACTORS;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Jump(246, "Death");
		TNT1 A 0 {self.bTHRUACTORS = false;}
		TNT1 A 100;
		Loop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_Stop;
		TNT1 A 0;
		Stop;
		
}
}


CLASS Taunter: MonsterTracer { 
Default {
	
	-BLOODSPLATTER;
	+THRUGHOST;
	+DONTSPLASH;
	radius 16;
	height 16;
	speed 100;
	damagefunction(random(1,2));
	DamageType "Taunt";
	Decal "None";
}
States
{
	Spawn:
		PUZZ Z 1 BRIGHT;
		Loop;
	XDeath:
	Melee:
	Death:
		TNT1 A 1;
		TNT1 A 100;
		
		Stop;
}
}






CLASS NaziAlerter: Tracer { 
Default {

-BLOODSPLATTER;
+THRUGHOST;
speed 150;
Decal "None";
Radius 16;
Height 16;
DamageType "KillMe";
Damage 2;
}
States
{
Spawn:
	POSS A 25;
	Loop;
Death:
	TNT1 A 1;
	Stop;
}
}

CLASS QuadTracer: MonsterTracer { 
Default {

speed 60;
damagefunction(random(1,2));
+FORCEXYBILLBOARD;
+THRUGHOST;
damagetype "SSG";
}
States
{
Death:
	TNT1 A 1 A_SpawnItem("HitPuff");
	Stop;
}
}

CLASS QuadSingeTracer: MonsterTracer { 
Default {

speed 65;
damage 2;
+FORCEXYBILLBOARD;
+THRUGHOST;
Decal "BulletChip";
DamageType "Arm";
}
States
{
Death:
	TNT1 A 1 A_SpawnItem("HitPuff");
	Stop;
}
}

CLASS WallPenetrationHitscan: FastProjectile { 
Default {

Projectile;
+RANDOMIZE;
+FORCEXYBILLBOARD;
+DONTSPLASH;
damage 0;
radius 2;
height 2;
speed 900;
renderstyle "Add";
alpha 0.9;
scale .3;
}
states
{
Spawn:
	TRAC A 1 BRIGHT;
	Loop;
Death:
	TNT1 A 0;
	TNT1 A 0 A_CheckFloor("Nothing");
	TNT1 A 0 A_CheckCeiling("Nothing");
	TNT1 A 0 A_SpawnItemEx("Penetrator",cos(-pitch)*24,0,0+(sin(pitch)*24),cos(-pitch)*100,0,sin(pitch)*100,0,SXF_TRANSFERPITCH);
	tnt1 A 2;
	Stop;
	
Nothing:
	TNT1 A 0;
	Stop;
	
XDeath:
	TNT1 A 0;
	TNT1 A 0 A_SpawnItemEx("Penetrator",cos(-pitch)*24,0,0+(sin(pitch)*24),cos(-pitch)*100,0,sin(pitch)*100,0,SXF_TRANSFERPITCH);
	Stop;
}
}

CLASS RailgunWallPenetrationHitscan: FastProjectile { 
Default {

Projectile;
+RANDOMIZE;
+FORCEXYBILLBOARD;
+DONTSPLASH;
damage 0;
radius 2;
height 2;
speed 900;
renderstyle "Add";
alpha 0.9;
scale .3;
}
states
{
Spawn:
	TRAC A 1 BRIGHT;
	Loop;
Death:
	TNT1 A 0;
	TNT1 A 0 A_CheckFloor("Nothing");
	TNT1 A 0 A_CheckCeiling("Nothing");
	TNT1 A 0 A_SpawnItemEx("RailgunPenetrator",cos(-pitch)*24,0,0+(sin(pitch)*24),cos(-pitch)*100,0,sin(pitch)*100,0,SXF_TRANSFERPITCH);
	tnt1 A 2;
	Stop;
	
Nothing:
	TNT1 A 0;
	Stop;
	
XDeath:
	TNT1 A 0;
	TNT1 A 0 A_SpawnItemEx("RailgunPenetrator",cos(-pitch)*24,0,0+(sin(pitch)*24),cos(-pitch)*100,0,sin(pitch)*100,0,SXF_TRANSFERPITCH);
	Stop;
}
}


CLASS SpawnBulletDecalBackwards: FastProjectile { 
Default {

Projectile;
+RANDOMIZE;
+FORCEXYBILLBOARD;
+DONTSPLASH;
+THRUACTORS;
damage 0;
radius 2;
height 2;
speed 50;
renderstyle "Add";
Decal "BulletDecalNew1";
alpha 0.9;
scale .3;
}
states
{
Spawn:
	TNT1 A 1 BRIGHT;
	Loop;
Death:
	TNT1 A 0 A_SpawnItem("HitPuff");
	TNT1 A 10;
	Stop;
XDeath:
	TNT1 A 0;
	Stop;
}
}



CLASS SpawnRocketDecalBackwards: FastProjectile { 
Default {

Projectile;
+RANDOMIZE;
+FORCEXYBILLBOARD;
+DONTSPLASH;
+THRUACTORS;
damage 0;
radius 6;
height 2;
speed 50;
renderstyle "Add";
Decal "Scorch";
alpha 0.9;
scale .8;
}
states
{
Spawn:
	TNT1 A 1 BRIGHT;
	Loop;
Death:
	TNT1 AAAAAAA 4 a_spawnprojectile("ExplosionSmoke", 2, 0, random(0, 360), 2, random(10, 60));
	Stop;
XDeath:
	TNT1 A 0;
	Stop;
}
}




CLASS RocketBackblast: Tracer { 
Default {

speed 80;
damagefunction(random(5,10));
Decal "Scorch";
Radius 12;
Height 24;
Alpha 0.9;
Scale 1.0;
Renderstyle "Add";
+RIPPER;
DamageType "sHOTGUN";
}
States
{
Spawn:
	TNT1 A 2;
	EXPL GHI 1 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
	Stop;
	
Death:
TNT1 A 1;
Stop;
}
}

CLASS RocketGlassBreaker: Alerter { 
Default {

speed 40;
Radius 4;
Height 2;
damagefunction(random(1,1));
DamageType "Normal";
Decal "None";
}
}
