
CLASS DyingImpNoArm2 : SwitchableDecoration { 
	Default {
	Radius 16;
	Height 32;
	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 0x7FFFFFFF;
	-SOLID;
	+SHOOTABLE;
	DamageFactor "bloodsplasher", 0.0;
	DamageFactor "tinybloodsplasher", 0.0;
	DamageFactor "superbloodsplasher", 0.0;
	DamageFactor "smallbloodsplasher", 0.0;
	DamageFactor "BlueBloodSplasher", 0.0;
	DamageFactor "BlueSuperBloodSplasher", 0.0;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	Scale 1.0;
	}
	States
	{
	
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
		TNT1 A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ;//A_GiveToTarget("HasImpShield = true;}
		TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
		T408 B 8;
		stop;
		
	Spawn:
		IMPC E 1;
		TNT1 A 0 A_Jump(160, "Death");
		Goto Suffer;
	Suffer:
		T408 BB 4 a_spawnprojectile("Brutal_FlyingBlood", 15, 2, random(0, 360), 2, random(0, 45));
		T408 B 5 A_Pain;

		T408 CC 4 a_spawnprojectile("Brutal_FlyingBlood", 15, 2, random(0, 360), 2, random(0, 45));
		T408 C 5 A_Pain;

	Death:
		T408 D 8;
		TNT1 A 0 A_SpawnItem("DeadImp_NoArm2", 5);
		stop;
		
	Death.Head:
	Death.Decaptate:
	Death.MINORHead:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("headex");
		TNT1 AAAA 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 36, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		T408 F 8;
		TNT1 A 0 A_SpawnItem("healthbonus");
		TNT1 A 0 A_SpawnItem("DeadImp_NoArmNoHead2");
		stop;
}
}

CLASS DyingImp2 : SwitchableDecoration { 
	Default {
	Radius 16;
	Height 32;
	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 0x7FFFFFFF;
	+SHOOTABLE;
	+SOLID;
	DamageFactor "Crush", 50.0;
	DamageFactor "Fatality", 50.0;
	DamageFactor "bloodsplasher", 0.0;
	DamageFactor "tinybloodsplasher", 0.0;
	DamageFactor "superbloodsplasher", 0.0;
	DamageFactor "smallbloodsplasher", 0.0;
	DamageFactor "BlueBloodSplasher", 0.0;
	DamageFactor "BlueSuperBloodSplasher", 0.0;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	Scale 1.0;
	}
	States
	{
	
	
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
		TNT1 A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ;//A_GiveToTarget("HasImpShield = true;}
		TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
		I9PC E 8;
		stop;
		
	Spawn:
		I9PC E 1;
		Goto Suffer;
	Suffer:
		I9PC EE 4 a_spawnprojectile("Brutal_FlyingBlood", 13, 2, random(0, 360), 2, random(0, 45));
		I9PC E 5 A_Pain;
		
		I9PC FF 4 a_spawnprojectile("Brutal_FlyingBlood", 13, 2, random(0, 360), 2, random(0, 45));
		I9PC F 5 A_Pain;

	Death:
		I9PC HI 8;
		TNT1 A 1 A_SpawnItem("DeadImp_NoStomach2", 5);
		stop;
		
	Death.Head:
	Death.Decaptate:
	Death.MINORHead:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("headex");
		TNT1 AAAA 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 36, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		I9PC JKL 8;
		TNT1 A 0 A_SpawnItem("healthbonus");
		TNT1 A 0 A_SpawnItem("DeadImp_NoStomachNoHead2");
		stop;
		
Death.Plasma: Death.Plasma2:
	TNT1 A 0;
	TNT1 A 0 A_XScream;
	TNT1 A 0 A_NoBlocking;
	XBRN AA 2 BRIGHT A_SpawnItem("PB_Flare",0,43);
	TNT1 AAAA 0 a_spawnprojectile("PB_blood", 30, 0, random(0, 360), 2, random(0, 160));
	
	TNT1 A 0 a_spawnprojectile("XDeathBurnedImpArm", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedImpLeg", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	
	XBRN BB 2 BRIGHT A_SpawnItem("PB_Flare",0,43);
	TNT1 A 0 a_spawnprojectile("PB_blood", 30, 0, random(0, 360), 2, random(0, 160));
	XBRN CC 2 BRIGHT A_SpawnItem("PB_Flare",0,43);
	XBRN DEF 4 BRIGHT;
	TNT1 A 0;
	stop;
	
Death.Fire:
	TNT1 A 0;
	TNT1 A 0 A_Scream;
	TNT1 A 0 A_NoBlocking;
	TNT1 A 0 A_SpawnItem("healthbonus");
	TROO JJJJ 2 a_spawnprojectile("FlameTrails", 45, 0, random(0, 360), 2, random(50, 130));
	TROO KKKK 2 a_spawnprojectile("FlameTrails", 30, 0, random(0, 360), 2, random(50, 130));
	TROO LLLL 2 a_spawnprojectile("FlameTrails", 25, 0, random(0, 360), 2, random(50, 130));
	TNT1 A 0 A_Playsound("props/redfire");
	BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 a_spawnprojectile("FlameTrails", 15, 0, random(0, 360), 2, random(50, 130));
	BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 10 a_spawnprojectile("CasingSmoke", 15, 0, random(0, 360), 2, random(70, 110));
	BOSB E -1;
	stop;
	
Death.Saw:
Death.cutless:
	TNT1 O 0 A_Jump(230, 2);
	Goto Death;
	TNT1 A 0 A_XScream;
	TNT1 O 0 A_NoBlocking;
	TNT1 A 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
	TROG A 2 a_spawnprojectile("RipImp", 0, 0, random(0, 360), 2, random(0, 160));
	TROG AAAAAAAAAAAAAAAAAAAAAAAAAA 4 A_SpawnItem("Big_Blood", 0, 30);
	TROG BCDEFGH 8;
	TNT1 A 1 A_SpawnItem("DeadImp_Half", 5);
	stop;
	
Death.Blast:
Death.SSG:
	TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
	TNT1 AA 0 a_spawnprojectile("XDeathImpArm", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeathImpHead", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperGoreSpawner", 22, 0, random(170, 190), 2, random(0, 15));
	TNT1 A 0 A_XScream;
	TNT1 A 0 A_NoBlocking;
	IZD1 EFGH 6;
	IZD1 H -1;
	TNT1 A 0 A_SpawnItem("PB_blood_Spot");
	stop;
	
	
Death.ExtremePunches:
	//TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, "Death.Fatality");
	Goto Death;
}
}


CLASS ImpVar1SaciLol: DyingImpNoLeg { 
	Default {
		
		//MONSTER
		-COUNTKILL;
		Speed 4;
		Height 48;
	}
	States
	{
		
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("imp/pain");
			Goto Suffer;
			
		Suffer:
			T5DC ABC 3;
			TNT1 A 0 A_SpawnItem("BloodDying", 0, 30);
			T5DC DDDD 1 A_Chase(null, null);
			TNT1 A 0 A_PlaySound("imp/pain");

			T5DC ABC 3;
			TNT1 A 0 A_SpawnItem("BloodDying", 0, 30);
			T5DC DDDD 1 A_Wander;
			TNT1 A 0 A_PlaySound("imp/pain");

		Death.Head:
			TNT1 A 0 A_PlaySound("misc/xdeath");
			TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 50);
		FallHead:
			T5DC EFG 7;
			TNT1 A 0 A_SpawnItem("DeadImp_NoLeg");
			stop;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("imp/death");
			T5DC HIJ 7;
			TNT1 A 0 A_SpawnItem("DeadImp_NoLeg");
			stop;
	}
}

CLASS ImpVar2SaciLol: DyingImpNoLeg { 
	Default {
		
		//MONSTER
		-COUNTKILL;
		Speed 4;
		Height 48;
	}
	States
	{
		
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("imp/pain");
			Goto Suffer;
			
		Suffer:
			T3DC ABC 3;
			TNT1 A 0 A_SpawnItem("BloodDying", 0, 30);
			T3DC DDDD 1 A_Chase(null, null);
			TNT1 A 0 A_PlaySound("imp/pain");
			

		Death.Head:
			TNT1 A 0 A_PlaySound("misc/xdeath");
			TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 50);
			Goto FallHead;
		FallHead:
			T3DC EFG 7;
			TNT1 A 0 A_SpawnItem("DeadImp_NoLeg");
			stop;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("imp/death");
			T3DC HIJ 7;
			TNT1 A 0 A_SpawnItem("DeadImp_NoLeg");
			stop;
	}
}


CLASS DyingImp : SwitchableDecoration { 
	Default {
	
	Radius 16;
	Height 28;
	Health 60;
	PainSound "imp/pain";
	PainChance 255;
	Mass 999999;
	+SHOOTABLE;
	+SOLID;
	-THRUACTORS;
	
	+FLOORCLIP;
	damagefactor "Crush", 50.0;
	Scale 1.0;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	}
	States
	{
	Spawn:
		TRO2 D 1;
		//TNT1 A 0 A_Jump(160, "Death")
	Suffer:
		TRO2 DDDDD 2 a_spawnprojectile("Brutal_FlyingBlood", 16, 0, random(0, 360), 2, random(0, 45));
		TRO2 D 2;
		
		TRO2 EEEEE 2 a_spawnprojectile("Brutal_FlyingBlood", 16, 0, random(0, 360), 2, random(0, 45));
		TRO2 E 2 A_Pain;

	Death:
		TRO2 FG 8;
		TNT1 A 0 A_SpawnItem("DeadImp_NoStomach", 5);
		stop;
		
	Death.Head:
	Death.Decaptate:
	Death.MINORHead:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 30);
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		IMPC JJJJJJJJJJJJJJJJJJJ 2 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(0, 360), 2, random(0, 45));
		IMPC KKKK 2 a_spawnprojectile("Brutal_FlyingBlood", 16, 0, random(0, 360), 2, random(0, 45));
		TNT1 A 0 A_SpawnItem("healthbonus");
		IMPC LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 2 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
		TNT1 A 0 A_SpawnItem("DeadImp_NoStomachNoHead", 5);
		stop;
		
Death.Plasma: Death.Plasma2:
	TNT1 A 0;
	TNT1 A 0 A_XScream;
	TNT1 A 0 A_NoBlocking;
	XBRN AA 2 BRIGHT A_SpawnItem("PB_Flare",0,43);
	TNT1 AAAA 0 a_spawnprojectile("PB_blood", 30, 0, random(0, 360), 2, random(0, 160));
	
	TNT1 A 0 a_spawnprojectile("XDeathBurnedImpArm", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedImpLeg", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	
	XBRN BB 2 BRIGHT A_SpawnItem("PB_Flare",0,43);
	TNT1 A 0 a_spawnprojectile("PB_blood", 30, 0, random(0, 360), 2, random(0, 160));
	XBRN CC 2 BRIGHT A_SpawnItem("PB_Flare",0,43);
	XBRN DEF 4 BRIGHT;
	TNT1 A 0;
	stop;
	
Death.Fire:
	TNT1 A 0;
	TNT1 A 0 A_Scream;
	TNT1 A 0 A_NoBlocking;
	TNT1 A 0 A_SpawnItem("healthbonus");
	TROO JJJJ 2 a_spawnprojectile("FlameTrails", 45, 0, random(0, 360), 2, random(50, 130));
	TROO KKKK 2 a_spawnprojectile("FlameTrails", 30, 0, random(0, 360), 2, random(50, 130));
	TROO LLLL 2 a_spawnprojectile("FlameTrails", 25, 0, random(0, 360), 2, random(50, 130));
	TNT1 A 0 A_Playsound("props/redfire");
	BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 a_spawnprojectile("FlameTrails", 15, 0, random(0, 360), 2, random(50, 130));
	BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 10 a_spawnprojectile("CasingSmoke", 15, 0, random(0, 360), 2, random(70, 110));
	BOSB E -1;
	stop;
	
Death.cut:
Death.cutless:
	TNT1 O 0 A_Jump(230, 2);
	Goto Death;
	TNT1 A 0 A_XScream;
	TNT1 O 0 A_NoBlocking;
	TNT1 A 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
	TROG A 2 a_spawnprojectile("RipImp", 0, 0, random(0, 360), 2, random(0, 160));
	TROG AAA 4 A_SpawnItem("Big_Blood", 0, 30);
	TNT1 A 0 A_SpawnItem("healthbonus");
	TROG BCDEFGH 8;
	TNT1 A 1 A_SpawnItem("DeadImp_Half", 5);
	//TROG H -1
	stop;
	
	
Death.SSG:
	//TNT1 A 0 a_spawnprojectile("MeatDeath", 0, 0, random(0, 360), 2, random(0, 160))
	TNT1 A 0 A_SpawnItem("healthbonus");
	TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
	TNT1 AA 0 a_spawnprojectile("XDeathImpArm", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeathImpHead", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperGoreSpawner", 22, 0, random(170, 190), 2, random(0, 15));
	TNT1 A 0 A_XScream;
	TNT1 A 0 A_NoBlocking;
	IZD1 EFGH 6;
	TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	IZD1 H -1;
	stop;
	
Death.Fatality:
Death.SuperPunch:
Death.ExtremePunches:
Pain.Fatality:
Active:
	TNT1 A 1 A_FaceTarget;
	TNT1 A 0 A_NoBlocking;
	TNT1 A 0 ;//A_GiveToTarget("HasImpShield = true;}
	TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
	TRO2 E 8;
	stop;
	
Death.Shotgun:
Death.Blast:
Death.Railgun:
	TNT1 A 0 A_XScream;
	TNT1 A 0 A_SpawnItem("healthbonus");
	TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
	TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeathImpArm", 32, 0, random(150, 210), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeathImpHead", 32, 0, random(150, 210), 2, random(0, 40));
	TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAA 0 a_spawnprojectile("BloodMist", 40, 0, random(0, 360), 2, random(30, 90));
	TR03 A 6 A_stop;
	TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	TR03 BBBBBBBBBB 3 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(30, 60));
	TR03 CCC 3 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(10, 40));
	TR03 DD 3 a_spawnprojectile("Brutal_FlyingBlood", 6, 0, random(0, 360), 2, random(30, 60));
	TR03 E -1;
	stop;
}
}


CLASS BrutalizedImp4 : SwitchableDecoration { 
	Default {
		Radius 16;
		Height 50;
		Health 115;
		PainSound "imp/pain";
		PainChance 256;
		Mass 999999;
		-SOLID;
		+SHOOTABLE;
		+NORADIUSDMG;
		+NODAMAGETHRUST;
		Scale 1.02;
		+usespecial;
		Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	}
	States
	{
		Death.Fatality:
		Death.SuperPunch:
		Active:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ;//A_GiveToTarget("HasImpShield = true;}
			TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
			I9PC O 6;
			stop;
			
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Recoil(1);
			TNT1 A 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
			I9PC OOOOOOO 5 a_spawnprojectile("Brutal_FlyingBlood", 25, 0, random(0, 360), 2, random(10, 40));
			Goto DieNow;
			
		Pain:
			TNT1 A 0 {self.bNopain = true;}
			TNT1 A 0 A_Jump(128, "Pain2");
			TNT1 A 0 A_Pain;
			I9PC MNO 3 a_spawnprojectile("Brutal_FlyingBlood", 25, 0, random(0, 360), 2, random(10, 40));
			TNT1 A 0 {self.bNopain = false;}
			Goto Spawn;
			
		Pain2:
			TNT1 A 0 A_Pain;
			I9PC ONM 3 a_spawnprojectile("Brutal_FlyingBlood", 29, 0, random(0, 360), 2, random(10, 40));
			TNT1 A 0 {self.bNopain = false;}
			Goto Spawn;
			
		DieNow:
			TNT1 A 0;
			TNT1 A 0 A_NoBlocking;
			I9PC PQR 5;
			TNT1 A 0 A_SpawnItem("GrowingBloodPool");
			TNT1 A 0 A_SpawnItem("BrutalizedImp4stop", 2);
			stop;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("healthbonus");
			TNT1 A 0 A_Jump(43, "Death2");
			TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
			TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
			TNT1 A 0 a_spawnprojectile("XDeathHalfImpUpperPart32", 27, 0, random(150, 210), 2, random(0, 40));
			TNT1 A 0 a_spawnprojectile("XDeathImpHead", 32, 0, random(150, 210), 2, random(0, 40));
			TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAA 0 a_spawnprojectile("BloodMist", 40, 0, random(0, 360), 2, random(30, 90));
			TR04 A 0 A_stop;
			TNT1 A 0 A_SpawnItem("GrowingBloodPool");
			TR04 BBBBBBBBBB 2 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(30, 60));
			TR04 CCC 2 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(10, 40));
			TR04 DD 2 a_spawnprojectile("Brutal_FlyingBlood", 6, 0, random(0, 360), 2, random(30, 60));
			TNT1 A 0 A_SpawnItem("DeadImpTR04E");
			stop;
			
		Death2:
			TNT1 A 0 a_spawnprojectile("XDeathImpArm", 26, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("MuchBlood", 30, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 A_SpawnItem("DyingImpNoArm", 2);
			stop;
			
		Death.SSG:
		Death.Shotgun:
		Death.Blast:
		Death.Railgun:
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_SpawnItem("healthbonus");
			TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
			TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
			TNT1 A 0 a_spawnprojectile("XDeathImpHead", 32, 0, random(150, 210), 2, random(0, 40));
			TNT1 A 0 a_spawnprojectile("XDeathImpArm", 32, 0, random(150, 210), 2, random(0, 40));
			TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAA 0 a_spawnprojectile("BloodMist", 40, 0, random(0, 360), 2, random(30, 90));
			TROG A 6 A_stop;
			TNT1 A 0 A_SpawnItem("GrowingBloodPool");
			TROG BBBBBBBBBB 3 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(30, 60));
			TROG CCC 3 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(10, 40));
			TROG DD 3 a_spawnprojectile("Brutal_FlyingBlood", 6, 0, random(0, 360), 2, random(30, 60));
			TROG E -1;
			stop;
}}


CLASS BrutalizedImp1 : SwitchableDecoration { 
	Default {
		Radius 16;
		Height 50;
		Health 20;
		PainSound "grunt/pain";
		PainChance 255;
		Mass 999999;
		-SOLID;
		+SHOOTABLE;
		+NORADIUSDMG;
		+usespecial;
		Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
		Scale 1.0;
	}
	States
	{
		Death.Fatality:
		Death.SuperPunch:
		Active:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ;//A_GiveToTarget("HasImpShield = true;}
			TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
			IZD1 A 8;
			stop;
			
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Recoil(2);
			TNT1 A 0 a_spawnprojectile("XDeathImpArm", 35, 0, random(0, 360), 2, random(0, 160));
			TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		Pain:
			IZD1 A 30;
			Goto DieNow;
			
		DieNow:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("BrutalizedImpstop");
			stop;
			
		Death:
			TNT1 A 0;
			TNT1 AAAA 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
			TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 A_Recoil(2);
			IZD1 B 16;
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("BrutalizedImp2");
			stop;
			
		Death.SSG:
		XDeath:
			TNT1 A 0 A_XScream;
			
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 a_spawnprojectile("ImpXDeath", 0, 0, random(0, 360), 2, random(0, 160));
			stop;
}}

CLASS BrutalizedImpstop: CurbstompedMarine { 
	Default {
		
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
		damagefactor "Melee", 10.0;
		damagefactor "Fatality", 10.0;
		damagefactor "Kick", 10.0;
	}
	States
	{
		Spawn:
			IZD2 ABC 5 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
			IZD3 D -1;
			stop;
			
		Death.Fatality:
		Death.Melee:
		Death.Kick:
		Death.Extremepunches:
			TNT1 A 0;
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			//IZD2 B 7
			TNT1 A 1 A_SpawnItem("BrutalizedImpstop", 5);
			stop;
			
}}
	   
CLASS BrutalizedImp4stop: BrutalizedImpstop { 
	Default {
		
	}
	States
	{
		Spawn:
			I9PC R -1;
			stop;
}}

CLASS BrutalizedImp2: BrutalizedSergeant1 { 
	Default {
		
		+usespecial;
		Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	}
	States
	{
		Spawn:
		Pain:
			IZD1 B 30;
			Goto DieNow;
			
		DieNow:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("BrutalizedImpstop2");
			stop;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_Recoil(2);
			TNT1 A 0 a_spawnprojectile("XDeathImpArm", 35, 0, random(0, 360), 2, random(0, 160));
			TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0;
			IZD1 C 16;
			TNT1 A 0 A_SpawnItem("BrutalizedImp3");
			stop;
			
		Death.Fatality:
		Death.SuperPunch:
		Active:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ;//A_GiveToTarget("HasImpShield = true;}
			TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
			IZD1 B 30;
			stop;
}

}

CLASS BrutalizedImpstop2: BrutalizedImpstop

{ 
	States
	{
		Spawn:
			IZD4 AB 6 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
			IZD4 B -1;
			stop;
			
		Death.Fatality:
		Death.Melee:
		Death.Kick:
		Death.Extremepunches:
			TNT1 A 0;
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			IZD4 A 7;
			TNT1 A 1 A_SpawnItem("BrutalizedImpstop2", 5);
			stop;
}}

CLASS BrutalizedImp3: BrutalizedImp1 { 
	Default {
		
	}
	States
	{
		Spawn:
		Pain:
			IZD1 C 25;
			Goto DieNow;
			
		DieNow:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("BrutalizedImpstop3");
			stop;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_Recoil(2);
			TNT1 A 0 A_SpawnItem("BloodSplasher2");
			TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 AA 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("XDeath4", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("XDeath2", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 AAAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 44, 0, random(0, 360), 2, random(0, 50));
			IZD1 EFGH 6;
			TNT1 A 0 A_SpawnItem("healthbonus");
			IZD1 H -1;
			stop;
}}


CLASS BrutalizedImpstop3: BrutalizedImpstop { 
	States
	{
		Spawn:
			IZD3 ABC 6 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
			IZD3 C -1;
			stop;
			
		Death.Fatality:
		Death.Melee:
		Death.Kick:
		Death.Extremepunches:
			TNT1 A 0;
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,15,0,1);
			TNT1 A 0 A_FaceTarget;
			IZD3 B 7;
			TNT1 A 1 A_SpawnItem("BrutalizedImpstop3", 5);
stop;}}
	   
		
CLASS ThisImpGotFuckedHard: CurbstompedMarine { 
	Default {
		Health 200;
		DamageFactor "ExplosiveImpact", 10.0;
	}
	States{Spawn:
		TNT1 A 0 A_Jump(128, "Spawn2");
		ID17 G -1;
		stop;
		
	Death.ExplosiveImpact:
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		ID17 ABCDEF 5;
		TNT1 A 0 A_SpawnItem("ThisImpGotFuckedHard");
		stop;
}}

CLASS ThisImpGotFuckedHard2: CurbstompedMarine { 
	Default {
	Health 200;
	DamageFactor "ExplosiveImpact", 10.0;
	}
States{Spawn:
	ID17 O -1;
	stop;
	
	Death.ExplosiveImpact:
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		ID17 ABCDEF 5;
		TNT1 A 0 A_SpawnItem("ThisImpGotFuckedHard2");
		stop;
}}
	
	
CLASS ImpBrutalizedWithNoLeg : ACTOR { 
	Default {
	Radius 16;
	Height 50;
	Health 20;
	PainSound "grunt/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	Scale 1.0;
	}
	States
	{
	
	Spawn:
		TR09 A 30;
		Goto DieNow;
		
	DieNow:
		TR09 BC 8;
		TR09 DE 8;
		TNT1 A 0 A_SpawnItem("DeadImp_NoLeg");
		stop;
		
		
		
	Death:
		TNT1 A 0;
		TNT1 AAAA 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathImpArm", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathImpLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		ID17 ABCDEF 5;
		TNT1 A 0 A_SpawnItem("armorbonus");
		TNT1 A 0 A_SpawnItem("ThisImpGotFuckedHard");
		stop;
}}









CLASS DyingImpNoArm : SwitchableDecoration { 
	Default {
	Radius 16;
	Height 32;
	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	Scale 1.0;
	}
	States
	{
	
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
		TNT1 A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ;//A_GiveToTarget("HasImpShield = true;}
		TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
		TR08 B 8;
		stop;
		
	Spawn:
		TR08 B 1;
		//TNT1 A 0 A_Jump(128, "Death")
		Goto Suffer;
	Suffer:
		TR08 BB 4 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(0, 45));
		TR08 B 5;
		TR08 CC 4 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(0, 45));
		TR08 C 5 A_Pain;

	Death:
		TR08 D 8;
		TNT1 A 0 A_SpawnItem("DeadImp_NoArm", 5);
		stop;
		
	Death.Head:
	Death.Decaptate:
	Death.MINORHead:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 30);
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TR08 F 8;
		TNT1 A 0 A_SpawnItem("healthbonus");
		TNT1 A 0 A_SpawnItem("DeadImp_NoArmNoHead");
		stop;
		
	XDeath:
	Death.Explosives:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_SpawnItem("healthbonus");
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 42, 0, random(170, 190), 2, random(10, 60));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 42, 0, random(170, 190), 2, random(10, 60));
		TNT1 A 0 a_spawnprojectile("XDeath2", 42, 0, random(170, 190), 2, random(10, 60));
		TNT1 A 0 a_spawnprojectile("XDeath4", 42, 0, random(170, 190), 2, random(10, 60));
		TNT1 A 1 a_spawnprojectile("ImpXDeath", 0, 0, random(0, 360), 2, random(0, 160));
		stop;
		
	Death.SSG:
	Death.Shotgun:
	Death.Blast:
	Death.Railgun:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_SpawnItem("healthbonus");
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathImpHead", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathImpArm", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("BloodMist", 40, 0, random(0, 360), 2, random(30, 90));
		TROG A 6 A_stop;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TROG BBBBBBBBBB 3 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(30, 60));
		TROG CCC 3 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(10, 40));
		TROG DD 3 a_spawnprojectile("Brutal_FlyingBlood", 6, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_SpawnItem("DeadImpTROGE");
		stop;
}
}



CLASS DyingImpNoLeg : SwitchableDecoration { 
	Default {
	
	
	Radius 16;
	Height 32;
	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	Scale 1.0;
	}
	States
	{
	
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
		TNT1 A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ;//A_GiveToTarget("HasImpShield = true;}
		TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
		TR09 F 8;
		stop;
		
	Spawn:
		IMPC E 1;
		TNT1 A 0;
		TNT1 A 0 A_Jump(32, "Colapse");
		Goto Suffer;
	Suffer:
		TR09 DD 4 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
		TR09 D 5 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
		TR09 FF 4 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
		TR09 F 5 A_Pain;

		Goto Colapse;
	Death:
		TNT1 A 0 A_PlaySound("imp/death");
		TR09 G 8;
		TNT1 A 0 A_SpawnItem("DeadImp_NoLeg", 5);
		stop;
		
	Colapse:
		TR09 H 8;
		TNT1 A 0 A_SpawnItem("DeadImp_NoLeg", 5);
		stop;
		
	Death.Head:
	Death.Decaptate:
	Death.MINORHead:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 30);
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TR09 I 8;
		TNT1 A 0 A_SpawnItem("DeadImp_Noleg");
		TNT1 A 0 A_SpawnItem("healthbonus");
		stop;
}
}





CLASS ImpDyingOfBloodLoss: switchabledecoration { 
	Default {
	
	Radius 16;
	Height 28;
	Health 10;
	+NOPAIN;
	-COUNTKILL;
	+SHOOTABLE;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	}
	States
	{
	
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
		TNT1 A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ;//A_GiveToTarget("HasImpShield = true;}
		TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
		TROD F 8;
		stop;
		
	Spawn:
		TROD E 1;
		TROD EFEFEFEFEFEFEFEFEFEFEFEF 10;
		Goto Colapse;
	Death:
		TNT1 A 0;
		stop;//Goto DeathNoGuts;
		
	Death.Shotgun:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfCloser(150, "Death.Shotgunontheface");
		stop;//Goto DeathNoGuts;
		
	Colapse:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking;
		TROD GHIJ 5;
		TNT1 A 0 A_SpawnItem("DeadImpBloodLoss", 5);
		stop;
}
}


CLASS ImpSaciLol: DyingImpNoLeg { 
	Default {
	
	//MONSTER
	-COUNTKILL;
	Speed 4;
	Height 48;
	}
	States
	{
	
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("imp/pain");
		Goto Suffer;
		
	Suffer:
		ZL3E ABC 3;
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 30);
		ZL3E DDDD 1 A_Chase(null, null);
		TNT1 A 0 A_PlaySound("imp/pain");
		

		TNT1 A 0 A_SpawnItem("DyingImpNoLeg");
		stop;
	Death.Head:
		TNT1 A 0 A_PlaySound("misc/xdeath");
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 50);
		Goto FallHead;
	FallHead:
		ZL3E EFG 7;
		TNT1 A 0 A_SpawnItem("DeadImp_NoLeg");
		stop;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("imp/death");
		ZL3E HIJ 7;
		TNT1 A 0 A_SpawnItem("DeadImp_NoLeg");
		stop;
}
}

