
CLASS SavageImpBrutalizedWithNoLeg : ACTOR { 
	Default {
		
		
		Radius 16;
		Height 50;
		Health 20;
		PainSound "savageimp/pain";
		PainChance 255;
		Mass 999999;
		-SOLID;
		+SHOOTABLE;
		Scale 1.0;
	}
	States
	{
		
		Spawn:
			2R09 A 30;
			Goto DieNow;
			
		DieNow:
			2R09 BC 8;
			2R09 DE 8;
			TNT1 A 0 A_SpawnItem("DeadSavageImp_NoLeg");
			stop;

		Death:
			TNT1 A 0;
			TNT1 AAAA 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
			TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("XDeathSavageImpArm", 35, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("XDeathImpLeg", 32, 0, random(0, 360), 2, random(0, 160));
			TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			5D17 ABCDEF 5;
			TNT1 A 0 A_SpawnItem("armorbonus");
			TNT1 A 0 A_SpawnItem("ThisSavageImpGotFuckedHard");
			stop;
}}

CLASS BrutalizedSavageImp1 : SwitchableDecoration { 
	Default {
		
		
		Radius 16;
		Height 50;
		Health 20;
		PainSound "grunt/pain";
		PainChance 255;
		Mass 999999;
		-SOLID;
		+SHOOTABLE;
		+NORADIUSDMG;
		Scale 1.0;
		+usespecial;
		Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	}
	States
	{
		Death.Fatality:
		Death.SuperPunch:
		Active:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ;//A_GiveToTarget("HasSavageImpShield = true;}
			TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
			1ZD1 A 8;
			stop;
			
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Recoil(2);
			TNT1 A 0 a_spawnprojectile("XDeathSavageImpArm", 35, 0, random(0, 360), 2, random(0, 160));
			TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		Pain:
			1ZD1 A 30;
			Goto DieNow;
			
		DieNow:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("BrutalizedSavageImpstop");
			stop;
			
		Death:
			TNT1 A 0;
			TNT1 AAAA 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
			TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 A_Recoil(2);
			1ZD1 B 16;
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("BrutalizedSavageImp2");
			stop;
			
		Death.SSG:
		XDeath:
			TNT1 A 0 A_XScream;
			
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 a_spawnprojectile("SavageImpXDeath", 0, 0, random(0, 360), 2, random(0, 160));
			stop;
}}

CLASS BrutalizedSavageImpstop: CurbstompedMarine { 
	Default {
		
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
		damagefactor "Melee", 10.0;
		damagefactor "Fatality", 10.0;
		damagefactor "Kick", 10.0;
	}
	States
	{
		Spawn:
			1ZD2 ABC 5 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
			1ZD2 C -1;
			stop;
			
		Death.Fatality:
		Death.Melee:
		Death.Kick:
		Death.Extremepunches:
			TNT1 A 0;
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			//IZD2 B 7
			TNT1 A 1 A_SpawnItem("BrutalizedSavageImpstop", 5);
			stop;
			
}}
	   
CLASS BrutalizedSavageImp2: BrutalizedSergeant1 { 
	Default {
		
		+usespecial;
		Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	}
	States
	{
		Spawn:
		Pain:
			1ZD1 B 30;
			Goto DieNow;
			
		DieNow:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("BrutalizedSavageImpstop2");
			stop;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_Recoil(2);
			TNT1 A 0 a_spawnprojectile("XDeathSavageImpArm", 35, 0, random(0, 360), 2, random(0, 160));
			TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0;
			1ZD1 C 16;
			TNT1 A 0 A_SpawnItem("BrutalizedSavageImp3");
			stop;
			
		Death.Fatality:
		Death.SuperPunch:
		Active:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ;//A_GiveToTarget("HasSavageImpShield = true;}
			TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
			stop;
			
			
}}

CLASS BrutalizedSavageImpstop2: BrutalizedSavageImpstop { 
	Default {
		
	}
	States
	{
		Spawn:
			1ZD4 AB 6 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
			1ZD4 B -1;
			stop;
			
		Death.Fatality:
		Death.Melee:
		Death.Kick:
		Death.Extremepunches:
			TNT1 A 0;
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			1ZD4 A 7;
			TNT1 A 1 A_SpawnItem("BrutalizedSavageImpstop2", 5);
			stop;
}}

CLASS BrutalizedSavageImp3: BrutalizedSavageImp1 { 
	Default {
		
	}
	States
	{
		Spawn:
		Pain:
			1ZD1 C 25;
			Goto DieNow;
			
		DieNow:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("BrutalizedSavageImpstop3");
			stop;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_Recoil(2);
			TNT1 A 0 A_SpawnItem("BloodSplasher2");
			TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 AA 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("XDeath4", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("XDeath2", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 AAAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 44, 0, random(0, 360), 2, random(0, 50));
			1ZD1 EFGH 6;
			TNT1 A 0 A_SpawnItem("healthbonus");
			1ZD1 H -1;
			stop;
}}


CLASS BrutalizedSavageImpstop3: BrutalizedImpstop { 
	Default {
		
	}
	States
	{
		Spawn:
			1ZD3 ABC 6 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
			1ZD3 C -1;
			stop;
			
		Death.Fatality:
		Death.Melee:
		Death.Kick:
		Death.Extremepunches:
			TNT1 A 0;
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,15,0,1);
			TNT1 A 0 A_FaceTarget;
			1ZD3 B 7;
			TNT1 A 1 A_SpawnItem("BrutalizedSavageImpstop3", 5);
stop;}}

CLASS DyingSavageImpNoArm : SwitchableDecoration { 
	Default {
		
		
		Radius 16;
		Height 32;
		Health 50;
		PainSound "SavageImp/pain";
		PainChance 255;
		Mass 999999;
		-SOLID;
		+SHOOTABLE;
		+usespecial;
		Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
		Scale 1.0;
	}
	States
	{
		
		
		Death.Fatality:
		Death.SuperPunch:
		Active:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ;//A_GiveToTarget("HasSavageImpShield = true;}
			TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
			2R08 B 8;
			stop;
			
		Spawn:
			2R08 B 1;
			//TNT1 A 0 A_Jump(128, "Death")
			Goto Suffer;
		Suffer:
			2R08 BB 4 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(0, 45));
			2R08 B 5;
			2R08 CC 4 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(0, 45));
			2R08 C 5 A_Pain;
			
			2R08 BB 4 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(0, 45));
			2R08 B 5;
			2R08 CC 4 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(0, 45));
			2R08 C 5 A_Pain;
			
			2R08 BB 4 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(0, 45));
			2R08 B 5;
			2R08 CC 4 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(0, 45));
			2R08 C 5 A_Pain;
			
			2R08 BB 4 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(0, 45));
			2R08 B 5;
			2R08 CC 4 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(0, 45));
			2R08 C 5 A_Pain;
			
			2R08 BB 4 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(0, 45));
			2R08 B 5;
			2R08 CC 4 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(0, 45));
			2R08 C 5 A_Pain;
			
			
			
			Goto Death;
		Death:
			2R08 D 8;
			TNT1 A 0 A_SpawnItem("DeadSavageImp_NoArm", 5);
			stop;
			
		Death.Head:
		Death.Decaptate:
		Death.MINORHead:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 A_SpawnItem("SavageImpHeadExplode", 0, 30);
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			2R08 F 8;
			TNT1 A 0 A_SpawnItem("healthbonus");
			TNT1 A 0 A_SpawnItem("DeadSavageImp_NoArmNoHead");
			stop;
			
		XDeath:
		Death.Explosives:
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_SpawnItem("healthbonus");
			TNT1 AAA 0 a_spawnprojectile("XDeath1", 42, 0, random(170, 190), 2, random(10, 60));
			TNT1 AAA 0 a_spawnprojectile("XDeath3", 42, 0, random(170, 190), 2, random(10, 60));
			TNT1 A 0 a_spawnprojectile("XDeath2", 42, 0, random(170, 190), 2, random(10, 60));
			TNT1 A 0 a_spawnprojectile("XDeath4", 42, 0, random(170, 190), 2, random(10, 60));
			TNT1 A 1 a_spawnprojectile("SavageImpXDeath", 0, 0, random(0, 360), 2, random(0, 160));
			stop;
			
		Death.SSG:
		Death.Shotgun:
		Death.Blast:
		Death.Railgun:
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_SpawnItem("healthbonus");
			TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
			TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
			TNT1 A 0 a_spawnprojectile("XDeathSavageImpHead", 32, 0, random(150, 210), 2, random(0, 40));
			TNT1 A 0 a_spawnprojectile("XDeathSavageImpArm", 32, 0, random(150, 210), 2, random(0, 40));
			TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAA 0 a_spawnprojectile("BloodMist", 40, 0, random(0, 360), 2, random(30, 90));
			2ROG A 6 A_stop;
			TNT1 A 0 A_SpawnItem("GrowingBloodPool");
			2ROG BBBBBBBBBB 3 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(30, 60));
			2ROG CCC 3 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(10, 40));
			2ROG DD 3 a_spawnprojectile("Brutal_FlyingBlood", 6, 0, random(0, 360), 2, random(30, 60));
			2ROG E -1;
			stop;
	}
}



CLASS DyingSavageImpNoLeg : SwitchableDecoration { 
	Default {
		
		
		Radius 16;
		Height 32;
		Health 50;
		PainSound "Savageimp/pain";
		PainChance 255;
		Mass 999999;
		-SOLID;
		+SHOOTABLE;
		+usespecial;
		Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
		Scale 1.0;
	}
	States
	{
		
		
		Death.Fatality:
		Death.SuperPunch:
		Active:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ;//A_GiveToTarget("HasSavageImpShield = true;}
			TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
			2R09 D 8;
			stop;
			
		Spawn:
			2R09 D 1;
			TNT1 A 0;
			TNT1 A 0 A_Jump(32, "Colapse");
			Goto Suffer;
		Suffer:
			
			2R09 DD 4 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
			2R09 D 5 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
			2R09 FF 4 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
			2R09 F 5 A_Pain;
			
			2R09 DD 4 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
			2R09 D 5 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
			2R09 FF 4 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
			2R09 F 5 A_Pain;
			
			2R09 DD 4 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
			2R09 D 5 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
			2R09 FF 4 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
			2R09 F 5 A_Pain;
			
			
			2R09 DD 4 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
			2R09 D 5 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
			2R09 FF 4 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
			2R09 F 5 A_Pain;
			
			Goto Colapse;
		Death:
			TNT1 A 0 A_PlaySound("imp/death");
			2R09 G 8;
			TNT1 A 0 A_SpawnItem("DeadSavageImp_NoLeg", 5);
			stop;
			
		Colapse:
			2R09 H 8;
			TNT1 A 0 A_SpawnItem("DeadSavageImp_NoLeg", 5);
			stop;
			
		Death.Head:
		Death.Decaptate:
		Death.MINORHead:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 30);
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			2R09 I 8;
			TNT1 A 0 A_SpawnItem("DeadSavageImp_Noleg");
			TNT1 A 0 A_SpawnItem("healthbonus");
			stop;
	}
}

CLASS SavageImpSaciLol: DyingSavageImpNoLeg { 
	Default {
		
		//MONSTER
		-COUNTKILL;
		Speed 4;
		Height 48;
	}
	States
	{
		
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("imp/pain");
			Goto Suffer;
			
		Suffer:
			TNT1 A 0;
			
			3L3E ABC 3;
			TNT1 A 0 A_SpawnItem("BloodDying", 0, 30);
			3L3E DDDD 1 A_Chase(null, null);
			TNT1 A 0 A_PlaySound("SavageImp/pain");
			
			3L3E ABC 3;
			TNT1 A 0 A_SpawnItem("BloodDying", 0, 30);
			3L3E DDDD 1 A_Wander;
			TNT1 A 0 A_PlaySound("SavageImp/pain");
			
			3L3E ABC 3;
			TNT1 A 0 A_SpawnItem("BloodDying", 0, 30);
			3L3E DDDD 1 A_Wander;
			TNT1 A 0 A_PlaySound("SavageImp/pain");
			
			3L3E ABC 3;
			TNT1 A 0 A_SpawnItem("BloodDying", 0, 30);
			3L3E DDDD 1 A_Wander;
			TNT1 A 0 A_PlaySound("SavageImp/pain");
			
			3L3E ABC 3;
			TNT1 A 0 A_SpawnItem("BloodDying", 0, 30);
			3L3E DDDD 1 A_Wander;
			TNT1 A 0 A_PlaySound("SavageImp/pain");
			
			3L3E ABC 3;
			TNT1 A 0 A_SpawnItem("BloodDying", 0, 30);
			3L3E D 1 A_Wander;
			TNT1 A 0 A_PlaySound("SavageImp/pain");
			
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("none");
			2R09 A 6;
			2R09 A 3;
			2R09 B 3;
			2R09 C 3 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("DyingSavageImpNoLeg");
			stop;
		Death.Head:
			TNT1 A 0 A_PlaySound("misc/xdeath");
			TNT1 A 0 A_SpawnItem("SavageImpHeadExplode", 0, 50);
			Goto FallHead;
		FallHead:
			3L3E EFG 7;
			TNT1 A 0 A_SpawnItem("DeadSavageImp_NoLeg");
			stop;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("savageimp/death");
			3L3E HIJ 7;
			TNT1 A 0 A_SpawnItem("DeadSavageImp_NoLeg");
			stop;
	}
}


CLASS SavageImpDyingOfBloodLoss: switchabledecoration { 
	Default {
		
		Radius 16;
		Height 28;
		Health 10;
		+NOPAIN;
		-COUNTKILL;
		+SHOOTABLE;
	}
	States
	{
		Spawn:
			2ROD E 1;
			2ROD EFEFEFEFEFEFEFEFEFEFEFEF 10;
			Goto Colapse;
		Death:
			TNT1 A 0;
			stop;//Goto DeathNoGuts;
			
		Death.Shotgun:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfCloser(150, "Death.Shotgunontheface");
			stop;//Goto DeathNoGuts;
			
		Colapse:
			TNT1 A 0;
			TNT1 A 0 A_NoBlocking;
			2ROD GHIJ 5;
			TNT1 A 0 A_SpawnItem("DeadSavageImpBloodLoss", 5);
			stop;
	}
}

CLASS DyingSavageImp : SwitchableDecoration { 
	Default {
		
		
		Radius 16;
		Height 28;
		Health 60;
		PainSound "SavageImp/Pain";
		PainChance 255;
		Mass 999999;
		+SHOOTABLE;
		+SOLID;
		-THRUACTORS;
		+usespecial;
		Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
		+FLOORCLIP;
		damagefactor "Crush", 50.0;
		Scale 1.0;
	}
	States
	{
		Spawn:
			TRO2 D 1;
			//TNT1 A 0 A_Jump(160, "Death")
			Goto Suffer;
		Suffer:
			2RO2 DDDDD 2 a_spawnprojectile("Brutal_FlyingBlood", 16, 0, random(0, 360), 2, random(0, 45));
			2RO2 D 2;
			
			2RO2 EEEEE 2 a_spawnprojectile("Brutal_FlyingBlood", 16, 0, random(0, 360), 2, random(0, 45));
			2RO2 E 2 A_Pain;
			
			2RO2 DDDDD 2 a_spawnprojectile("Brutal_FlyingBlood", 16, 0, random(0, 360), 2, random(0, 45));
			2RO2 D 2;
			
			2RO2 EEEEE 2 a_spawnprojectile("Brutal_FlyingBlood", 16, 0, random(0, 360), 2, random(0, 45));
			2RO2 E 2 A_Pain;
			
			2RO2 DDDDD 2 a_spawnprojectile("Brutal_FlyingBlood", 16, 0, random(0, 360), 2, random(0, 45));
			2RO2 D 2;
			
			2RO2 EEEEE 2 a_spawnprojectile("Brutal_FlyingBlood", 16, 0, random(0, 360), 2, random(0, 45));
			2RO2 E 2 A_Pain;
			
			2RO2 DDDDD 2 a_spawnprojectile("Brutal_FlyingBlood", 16, 0, random(0, 360), 2, random(0, 45));
			2RO2 D 2;
			
			2RO2 EEEEE 2 a_spawnprojectile("Brutal_FlyingBlood", 16, 0, random(0, 360), 2, random(0, 45));
			2RO2 E 2 A_Pain;
			Goto Death;
		Death:
			2RO2 FG 8;
			TNT1 A 1 A_SpawnItem("DeadSavageImp_NoStomach", 5);
			stop;
			
		Death.Head:
		Death.Decaptate:
		Death.MINORHead:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 A_SpawnItem("SavageImpHeadExplode", 0, 30);
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			1MPC JJJJJJJJJJJJJJJJJJJ 2 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(0, 360), 2, random(0, 45));
			1MPC KKKK 2 a_spawnprojectile("Brutal_FlyingBlood", 16, 0, random(0, 360), 2, random(0, 45));
			TNT1 A 0 A_SpawnItem("healthbonus");
			1MPC LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 2 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
			1MPC L -1;
			stop;
			
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		XBRN AA 2 BRIGHT A_SpawnItem("PB_Flare",0,43);
		TNT1 AAAA 0 a_spawnprojectile("PB_blood", 30, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 A 0 a_spawnprojectile("XDeathBurnedImpArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedImpLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		
		XBRN BB 2 BRIGHT A_SpawnItem("PB_Flare",0,43);
		TNT1 A 0 a_spawnprojectile("PB_blood", 30, 0, random(0, 360), 2, random(0, 160));
		XBRN CC 2 BRIGHT A_SpawnItem("PB_Flare",0,43);
		XBRN DEF 4 BRIGHT;
		TNT1 A 0;
		stop;
		
	Death.Fire:
		TNT1 A 0;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("healthbonus");
		TROO JJJJ 2 a_spawnprojectile("FlameTrails", 45, 0, random(0, 360), 2, random(50, 130));
		TROO KKKK 2 a_spawnprojectile("FlameTrails", 30, 0, random(0, 360), 2, random(50, 130));
		TROO LLLL 2 a_spawnprojectile("FlameTrails", 25, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_Playsound("props/redfire");
		BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 a_spawnprojectile("FlameTrails", 15, 0, random(0, 360), 2, random(50, 130));
		BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 10 a_spawnprojectile("CasingSmoke", 15, 0, random(0, 360), 2, random(70, 110));
		BOSB E -1;
		stop;
		
	Death.cut:
	Death.cutless:
		TNT1 O 0 A_Jump(230, 2);
		Goto Death;
		TNT1 A 0 A_XScream;
		TNT1 O 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		2ROG A 2 a_spawnprojectile("SavageImpTorso", 0, 0, random(0, 360), 2, random(0, 160));
		2ROG AAA 4 A_SpawnItem("Big_Blood", 0, 30);
		TNT1 A 0 A_SpawnItem("healthbonus");
		2ROG BCDEFGH 8;
		TNT1 A 1 A_SpawnItem("DeadSavageImp_Half", 5);
		//TROG H -1
		stop;
		
		
	Death.SSG:
		//TNT1 A 0 a_spawnprojectile("MeatDeath", 0, 0, random(0, 360), 2, random(0, 160))
		TNT1 A 0 A_SpawnItem("healthbonus");
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("XDeathSavageImpArm", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathSavageImpHead", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperGoreSpawner", 22, 0, random(170, 190), 2, random(0, 15));
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		1ZD1 EFGH 6;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		1ZD1 H -1;
		stop;
		
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
		TNT1 A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ;//A_GiveToTarget("HasSavageImpShield = true;}
		TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
		2RO2 E 8;
		stop;
		
	Death.Shotgun:
	Death.Blast:
	Death.Railgun:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_SpawnItem("healthbonus");
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathSavageImpArm", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathSavageImpHead", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("BloodMist", 40, 0, random(0, 360), 2, random(30, 90));
		2RO3 A 6 A_stop;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		2RO3 BBBBBBBBBB 3 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(30, 60));
		2RO3 CCC 3 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(10, 40));
		2RO3 DD 3 a_spawnprojectile("Brutal_FlyingBlood", 6, 0, random(0, 360), 2, random(30, 60));
		2RO3 E -1;
		stop;
}
}