
CLASS BruiserBall : ACTOR { 
	Default {
	Radius 12;
	Height 18;
	Speed 22;
	FastSpeed 23;
	DamageType "Fire";
	Projectile;
	+RANDOMIZE;
	+FORCEXYBILLBOARD;
	+THRUGHOST;
	DamageFunction(random(25,35));
	//RenderStyle "Add"
	//Alpha 0.1
	Scale 0.95;
	SeeSound "BaronFire";
	DeathSound "belphegor/missile";
	Decal "Scorch";
}
States
{
	Spawn:
		TNT1 A 0 A_Playsound("ImpFireLoop", 1, 1);
	Fly:
		COMT ABCB 1 BRIGHT
		{
			A_SpawnItem("Red_FlareSmall",0,0);
			A_SpawnItem("ExplosionSmoke");
			A_SpawnItem("CoolandNewFlameTrails");
			A_SpawnItemEx("CoolandNewFlameTrails", 0, 0, 0, 0, 0, 0, 0, 128);
		}
	Loop;
		
	Death:
		TNT1 A 0 A_StopSound(1);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		EXPL AAAAAA 0 a_spawnprojectile("CoolandNewFlameTrails", 1, 0, random(0, 360), 2, random(0, 360));
		
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-5, 5), random(-5, 5));
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 AAAA 19 a_spawnprojectile("ExplosionSmoke", 1, 0, random(0, 360), 2, random(0, 160));
	Stop;
		
	XDeath:
		TNT1 A 0 A_StopSound(1);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		EXPL AAAAAA 0 a_spawnprojectile("CoolandNewFlameTrails", 1, 0, random(0, 360), 2, random(0, 360));
		
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-5, 5), random(-5, 5));
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 180), 2, random(0, 180));
	Stop;
	}
}

CLASS BruiserBallBig:BruiserBall { 
	Default {
	Radius 15;
	Height 18;
	Speed 24;
	FastSpeed 25;
	DamageFunction(random(40,45));
	Scale 1.35;
	DeathSound "belphegor/missile";
}
	States
	{
	Spawn:
		TNT1 A 0 A_Playsound("ImpFireLoop", 1, 1);
	Fly:
		COMT ABCB 1 BRIGHT
		{
			A_SpawnItem("Red_FlareSmall",0,0);
			A_SpawnItem("ExplosionSmoke");
			A_SpawnItem("CoolandNewFlameTrails");
			A_SpawnItemEx("CoolandNewFlameTrails");
		}
	Loop;
		
	XDeath:
		TNT1 A 0 A_StopSound(1);
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		EXPL AAAAAA 0 a_spawnprojectile("CoolandNewFlameTrails", 1, 0, random(0, 360), 2, random(0, 360));
		EXPL A 0 Radius_Quake(3, 8, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
		BFE1 A 0 Bright A_Explode(10, 110, 1);
		TNT1 A 0 a_spawnprojectile("BigRicoChet");
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -30);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		EXPL AAA 0 a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
	Stop;

	Death:
		TNT1 A 0 A_StopSound(1);
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		EXPL AAAAAA 0 a_spawnprojectile("CoolandNewFlameTrails", 1, 0, random(0, 360), 2, random(0, 360));
		EXPL A 0 Radius_Quake(3, 8, 0, 15, 0);
		BFE1 A 0 Bright A_Explode(10, 110, 1);
		TNT1 A 0 a_spawnprojectile("BigRicoChet");
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -30);
		TNT1 A 0 A_SpawnItemEx("Underwater_Explosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		tnt1 AAA 0 a_spawnprojectile("ExplosionSmoke", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAA 19 a_spawnprojectile("ExplosionSmoke", 1, 0, random(0, 360), 2, random(0, 160));
	Stop;
	}
}

CLASS BruiserSpikeSpawner : ACTOR { 
Default {
	Radius 8;
	Height 8;
	Speed 12;
	Damage 0;
	+Ripper;
	+FloorHugger;
	+BloodlessImpact;
	Projectile;
	MissileType "BruiserSpike";
	Missileheight 0;
}

States
{
	Spawn:
		TNT1 A 1 spawn("BruiserSpike", pos:self.pos);
		TNT1 A 5;
		TNT1 A 5 A_SpawnItemEx("WalkFire",0,0,0,1,0,0,0,128);
	Loop;
	Death:  
		TNT1 A 6;
	Stop;
}
}

CLASS BruiserBallTrail : ACTOR { 
	Default {
	Radius 1;
	Height 1;
	Speed 0;
	Projectile;
	RenderStyle "Add";
	Alpha 0.70;
	+NoClip;
}

States
{
	Spawn:
		BRBA CDEFGHIJ 4 Bright;
	Stop;
}

}

CLASS BruiserFire : ACTOR { 
	Default {
	
	Radius 1;
	Height 1;
	Speed 0;
	Damage 20;
	Projectile;
	RenderStyle "Add";
	Alpha 0.9;
	+NoClip;
	+FloorHugger;
	SeeSound "weapons/rocklx";
}

States
{
	Spawn:
		XXBF AB 3 Bright;
		XXBF C 3 Bright A_Explode(48,128,0);
		XXBF DEFGHIJKLMNOPQRST 3 Bright;
	Stop;
	}
}

CLASS BruiserSpike : ACTOR { 
	Default {
	Scale 0.8;
	Radius 6;
	Height 8;
	Projectile;
	Renderstyle "Translucent";
	DamageType "ExplosiveImpact";
	+FLOORHUGGER;
	+NOCLIP;
}
	States
	{
	Spawn:
		SPIK A 0;
		TNT1 A 0 a_spawnprojectile("BigRicoChet");
		TNT1 A 0 A_SpawnItem("BigRicoChet", 0, -30);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		SPIK A 1 A_PlaySound("superbaron/spike");
		EXPL A 0 Radius_Quake(2, 24, 0, 15, 0);
		TNT1 AA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("ExplosionParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("ExplosionFlames", 0, 0, random(0, 360), 2, random(0, 360));
		SPIK BC 1;
		SPIK D 1 Radius_Quake(2,5,0,2,0);
		SPIK EF 1;
		SPIK G 0 A_Explode(45,150,0);
		SPIK G 1;
		SPIK GFEDCB 2;
		SPIK A 50;
		SPIK AAAAAAAAAAAAAAAAAAAA 1 A_FadeOut(0.05);
	Stop;

	Death:
		TNT1 A 1;
	Stop;
}
}