CLASS pb_Nether_Dark_Imp : proto_imp_class// Replaces DoomImp
{ 
Default
{
	Scale 1.04;
	//SpawnID 1470;
	Health 140;
	Radius 18;
	Speed 10;
	Mass 100;
	GibHealth 35;

	PainChance 200;
	PainChance "Avoid", 35;
	PainChance "Head", 255;
	PainChance "Taunt", 255;
	PainChance "Kick", 255;
	PainChance "ExtremePunches", 255;
	PainChance "Melee", 255;
	PainChance "Fatality", 255;
	PainChance "Stun", 255;
	PainChance "ExplosiveImpact", 255;

	damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0; damagefactor "GreenBlood", 0.0;
	damagefactor "TeleportRemover", 0.0;
	damagefactor "GibRemoving", 0.0;
	//PainChance "Avoid", 100
	damagefactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	damagefactor "Trample", 1.5;
	damagefactor "SSG", 5.0;
	damagefactor "Crush", 10.0;
	DamageFactor "CauseObjectsToSplash", 0.0;

	Monster;
	BloodType "pb_blood", "BloodSPlatterReplacer", "SawBlood";
	damagefactor "Shrapnel", 0.3;
	+FLOORCLIP;
	SeeSound "dimp/see";
	PainSound "dimp/pain";
	DeathSound "dimp/death";
	ActiveSound "dimp/active";
	damagefactor "Kick", 0.5;
	damagefactor "SSG", 5.0;
	damagefactor "explosiveimpact", 2.0;
	MaxStepHeight 24;
	MaxDropOffHeight 32;
	//+MISSILEMORE
	+DONTHARMCLASS;
	+SLIDESONWALLS;
	PainChance "Trample", 255;
	Species "Imp";
	Obituary "%o was cursed by a dark imp.";
	HitObituary "%o was touched by a dark imp.";
	MissileType "InfernoBall";
	MeleeRange 64;
	MeleeDamage 3;

	////DropItem "DemonStrengthRune", 1;
	////DropItem "Demonpickup", 225;
}

States
{
	Death.Shrink:
		TNT1 A 1 A_PlaySound("Shrink", 3);
/*		TNT1 A 0 A_SpawnItemEx ("NetherDarkImpShrinkFX1", 0, 0,  5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("NetherDarkImpShrinkFX2", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("NetherDarkImpShrinkFX3", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("NetherDarkImpShrinkFX4", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("NetherDarkImpShrinkFX5", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("NetherDarkImpShrinkFX6", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("NetherDarkImpShrinkFX7", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("LilNetherDarkImp", 1);*/
	stop;
		
	Spawn:
		TNT1 A 0;
 	Stand:
		TNT1 A 0;
		DRKF B 10 A_Look();
	Loop;
		
	Idle:
	LookingForPlayer:
		//TNT1 A 0 A_GiveInventory("SKImp", 1);
		DRKF B 10 A_Look();
		DRKF B 10 A_Look();
		DRKF B 10 A_Look();
		TNT1 A 0 {self.angle -= 40;}
		DRKF B 10 A_Look();
		DRKF B 10 A_Look();
		DRKF B 10 A_Look();
		TNT1 A 0 {self.angle += 40;}
		DRKF B 10 A_Look();
		DRKF B 10 A_Look();
		DRKF B 10 A_Look();
		
		DRKF A 0 A_Wander();
		TNT1 A 0 A_PlaySound("flesh/step",4);
		DRKF AA 2 A_Look();
		TNT1 A 0 A_Recoil(-2);
		
		DRKF B 0 A_Wander();
		DRKF BB 2 A_Look();
		TNT1 A 0 A_Recoil(-2);
		
		DRKF C 0 A_Wander();
		TNT1 A 0 A_PlaySound("flesh/step",4);
		DRKF CC 2 A_Look();
		TNT1 A 0 A_Recoil(-2);
		
		DRKF D 0 A_Wander();
		DRKF DD 2 A_Look();
		TNT1 A 0 A_Recoil(-2);
		
		
		TNT1 A 0 A_jump(128, "LookingForPlayer");
		
		
		DRKF A 0 A_Wander();
		TNT1 A 0 A_PlaySound("flesh/step",4);
		DRKF AA 2 A_Look();
		TNT1 A 0 A_Recoil(-2);
		
		DRKF B 0 A_Wander();
		DRKF BB 2 A_Look();
		TNT1 A 0 A_Recoil(-2);
		
		DRKF C 0 A_Wander();
		TNT1 A 0 A_PlaySound("flesh/step",4);
		DRKF CC 2 A_Look();
		TNT1 A 0 A_Recoil(-2);
		
		DRKF D 0 A_Wander();
		DRKF DD 2 A_Look();
		TNT1 A 0 A_Recoil(-2);
	Goto LookingForPlayer;


	ForgetTarget:
		TNT1 A 0 A_ClearTarget();
		TNT1 A 0 A_TakeInventory("EnemyMemory", 25);
	Goto Stand;
		
	See:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIf(vel.Z < 0, "FallingAfterImpact")// funny thing I tried, better not implement
		TNT1 A 0 A_TakeInventory("EnemyMemory", 15);
		DRKF A 4 A_faceTarget();
		DRKF B 4;
		DRKF C 10;
	Goto SeeContinue;
		

	SeeContinue:
		//TNT1 A 0 A_JumpIf(vel.Z < 0, "FallingAfterImpact")// funny thing I tried, better not implement
		
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		//TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim")
		//TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim")
		TNT1 A 0 A_JumpIfInventory("EnemyMemory", 25, "ForgetTarget");
		TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
		DRKF AA 2 A_Chase();
		TNT1 A 0 A_Recoil(-1);
		DRKF AA 2 A_Chase();
		TNT1 A 0 A_PlaySound("flesh/step",4);
		//TNT1 A 0 A_TakeInventory("SKImp", 1);
		DRKF BBBBCCCC 2 A_Chase();
		TNT1 A 0 A_PlaySound("flesh/step",4);
		DRKF DDDD 2 A_Chase();
	Loop;

	Melee:
		TNT1 A 0 A_JumpIfCloser(40, "Melee2");
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_PlaySound("dimp/see",6);
		D8S4 ABCD 4 A_Recoil (-1);
		D8S4 A 5 A_FaceTarget();
		TNT1 A 0 A_JumpIfCloser(60, "Melee2");
		//TNT1 A 0 A_TakeInventory("SKImp", 1);
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil (-10);
		D8S4 E 6;
		//TNT1 A 0 A_GiveInventory ("IsJumping");
		TNT1 A 0 A_PlaySound("weapons/fistwhoosh");
		TNT1 A 0 A_FaceTarget();
		D8S4 E 4 a_spawnprojectile("ImpAttack2",10,0,0,0);
		//TNT1 A 0 A_TakeInventory ("IsJumping");
		D8S4 A 4 a_spawnprojectile("ImpAttack2",10,0,0,0);
	Goto SeeContinue;
		
	Melee2:
		DRKF I 6 A_FaceTarget();
		DRKF J 6 A_FaceTarget();
		DRKF K 6 a_spawnprojectile("ImpAttack",10,0,0,0);
	Goto SeeContinue;
		
	Advancing:
		//TNT1 A 0 A_TAkeInventory("CantFire", 1);
		TNT1 A 0 A_JumpIfInventory("EnemyMemory", 20, "ForgetTarget");
		TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
		DRKF AA 2 A_Chase();
		DRKF AA 2 A_Chase();
		TNT1 A 0 A_PlaySound("flesh/step",4);
		//TNT1 A 0 A_TakeInventory("SKImp", 1);
		DRKF BBBBCCCC 2 A_Chase();
		TNT1 A 0 A_PlaySound("flesh/step",4);
		DRKF DDDD 2 A_Chase();
	Loop;
		
	Missile:
		TNT1 A 0 A_JumpIfCloser(1200, 3);
		//TNT1 A 0 a_spawnprojectile("MonsterTargetCheck", 34, 0, 0, 0);
		//TNT1 A 0 a_spawnprojectile("MonsterTargetCheckFaster", 34, 0, 0, 0);
		DRKF E 1 A_FaceTarget();
		//TNT1 A 0 A_JumpIfInventory("CantFire",1, "Advancing");
		DRKF E 1 A_Jump (255, "Attack1", "Attack2");
	Goto SeeContinue;

	Attack1:
		DRKF E 6 A_FaceTarget();
		TNT1 A 0 A_Playsound("weapons/shock");
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 20, 0, random (0, 360), 2, random (70, 110));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 20, 0, random (0, 360), 2, random (70, 110));
		DRKF F 2 A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF F 2 BRIGHT A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF F 2 A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF F 2 BRIGHT A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF F 2 A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF F 2 BRIGHT A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF F 2 A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF F 2 BRIGHT A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF F 2 A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, -22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF F 2 BRIGHT A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, -22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF F 2 A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, -22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF F 2 BRIGHT A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsBlue", 28, -22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("NetherLightningTrail", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF F 2 A_FaceTarget();
		DRKF F 3 A_FaceTarget();
		DRKF F 3 A_FaceTarget();
		DRKF G 6 a_spawnprojectile ("NetherLightning", 32, 0, 0);
	Goto SeeContinue;
		
	Attack2:
		DRKF I 6 A_FaceTarget();
		DRKF J 6 A_FaceTarget();
		TNT1 A 0 A_Playsound("redburn");
		DRKF J 2 BRIGHT A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("GreenPlasma_Puff_Small", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("GreenPlasma_Puff_Small", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF J 2 A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF J 2 BRIGHT A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF J 2 A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF J 2 BRIGHT A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF J 2 A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF J 2 BRIGHT A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF J 2 A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF J 2 BRIGHT A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF J 2 BRIGHT A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF J 2 BRIGHT A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF J 2 A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, -20, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF J 1 A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, -22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF J 1 BRIGHT A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, -22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF J 1 A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, -22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF J 1 BRIGHT A_FaceTarget();
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, 22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, 20, random (0, 140), 2, random (0, 160));
		TNT1 A 0 bright a_spawnprojectile ("RealFlameTrailsGreen", 28, -22, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("BallGettingReadyGreen", 27, -20, random (0, 140), 2, random (0, 160));
		DRKF J 1 A_FaceTarget();
		DRKF K 6 a_spawnprojectile ("InfernoBall", 32, 0, 0);
	Goto SeeContinue;
	
	Pain:
		DRKF H 2;
		DRKF H 2 A_Pain();
	Goto SeeContinue;
		
	Pain.Melee:
		TNT1 A 0{self.bNOGRAVITY = false;}
		TNT1 A 0{self.bTHRUSPECIES = false;}
		TNT1 A 0{self.bCEILINGHUGGER = false;}
		TNT1 D 0;
		DRKF H 2;
		//TNT1 A 0 A_JumpIfInventory ("SKImp", 1, "GotoStealthKill");
		DRKF H 2 A_Pain();
	Goto SeeContinue;
		
	GotoStealthKill:
		TNT1 A 1;
		//TNT1 A 0 A_GiveToTarget("SKDarkImpNether");
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 1 A_Die("Stealthy");
	Stop;

	Death.Stealthy:
		TNT1 A 0 A_NoBlocking();
	Stop;
		
	Possession:
		TNT1 A 0 A_SetInvulnerable();
		DRKF H 3;
		DRKF H 3 A_Pain();
 		TNT1 A 0 A_UnSetInvulnerable();
		Goto See;
		
	Pain.Stun:
		TNT1 A 0;
		TNT1 A 0{self.bNOGRAVITY = false;}
		TNT1 A 0{self.bTHRUSPECIES = false;}
		TNT1 A 0{self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_SpawnItemEx ("StunElectrocute", random (-4, 4), random (-4, 4),  random (16, 32), 0, 0);
		DRKF H 1 A_Pain();
		DRKF HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		DRKF H 1 A_Pain();
		DRKF HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		DRKF H 1 A_Pain();
		DRKF HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		DRKF H 1 A_Pain();
		DRKF HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		DRKF H 1 A_Pain();
		DRKF HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		DRKF H 1 A_Pain();
	Goto See;
		
	Pain.Kick:
	Pain.ExtremePunches:
	Pain.SuperKick:
		TNT1 A 0;
		D2S1 A 1 A_Pain();
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,16,0,1);
		D2S1 A 1 A_facetarget();
		D2S1 A 6 ThrustThing(angle*256/360+128, 5, 0, 0);
		D2S1 B 8;
	Goto FallingAfterImpact;
		
	FallingAfterImpact:
		D2S1 B 1 A_GiveInventory ("FallingHeight", 1);
		D2S1 B 1 A_CheckFloor ("GetUp");
		TNT1 A 0 A_JumpIf (vel.z == 0, "GetUp");
	Loop;
		
	FallingDie:
		TNT1 A 0;
		TNT1 A 0{self.bCOUNTKILL = false;}
		TNT1 A 0{self.bSHOOTABLE = false;}
		//TNT1 A 0 A_SpawnItem("SplatteredSmall");
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 10, "FallingSuperDeath");
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 7, "FallingDeath");
	GetUp:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("Underwater_Explosion");
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 5, "FallingDie");
		D2S1 CCC 5 A_JumpIf(vel.z < 0, "FallingAfterImpact");
		TNT1 A 0 A_TakeInventory("FallingHeight", 100);
		TNT1 A 0 A_TakeInventory("IsDown", 1);
		D2S1 DE 7;
	Goto SeeContinue;

	Death.Incinerate:
		TNT1 A 0;
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_Playsound("MELT");
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAAA 0 a_spawnprojectile ("ExplosionParticle", 32, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAA 0 a_spawnprojectile ("ExplosionParticle", 32, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,32,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-15, 15), random (-15, 15));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-35, 35), random (-35, 35));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-45, 45), random (-45, 35));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile ("Ashes1", 28, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile ("Ashes2", 40, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),32,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB AAAAA 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionParticle", 36, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),28,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB BBBBB 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionParticle", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),24,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB CCCCC 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionParticle", 28, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Playsound("SZZLL", 3);
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),20,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB DDDDD 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionParticle", 20, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),16,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB EEEEE 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionParticle", 12, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),12,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB FFFFF 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionParticle", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		TNT1 A 0 A_SpawnItem("Barrel_explosion_Column");
		T6SB GGGG 2 BRIGHT Light("IncinerationGlow");
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB HHIIHHIIHHIIHHII 2 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionSmoke", 14, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB HHIIHHIIHHIIHHII 2 Light("IncinerationGlow") a_spawnprojectile ("ExplosionSmoke", 14, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB HHIIHHIIHHIIHHII 2;
		T6SB JJJJJJJ 12 a_spawnprojectile ("ExplosionSmoke", 14, 0, random (0, 360), 2, random (0, 160));
		T6SB J -1;
	Stop;
		
	Death.fire:
	Death.Flames:
	Death.Burn:
		//TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		TNT1 A 0 A_Jump(32, "Fire2");//Doesn't run around
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("BurningImpRunning", 0, 10);
	Stop;

	Fire2:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("BurningImp");
	Stop;
		
	Death.GreenFire:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAA 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("GreenFlameTrails", 50, 0, random (0, 360), 2, random (0, 360));
		XBRN AAAA 2 BRIGHT A_SpawnItem("Green_Flare",0,43);
	Stop;
		
	Death.Ice:
	Death.Freeze:
	Death.Frost:
		TNT1 A 0{self.bSHOOTABLE = false;}
		TNT1 A 0{self.bSOLID = false;}
		//TNT1 A 0 A_SpawnItem("FrozenDarkImpNami");
	Stop;
		
	FallingDeath:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBLocking();
		TNT1 AAAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem ("DeadDarkImp1");
	Stop;

	FallingSuperDeath:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBLocking();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
	Goto Death.ExplosiveImpact+1;
		
	Death.Plasma: Death.Plasma2:
		TNT1 A 0{self.bNOGRAVITY = false;}
		TNT1 A 0{self.bTHRUSPECIES = false;}
		TNT1 A 0{self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Jump(96, "OtherPlasmaDeath");
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_PlaySound("plasmaflesh");
		TNT1 AAAAAAAAA 0 a_spawnprojectile ("Ashes1", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAA 0 a_spawnprojectile ("Ashes2", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1Blue",random(-2,2),random(-2,2),18,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		TNT1 AAAA 0 a_spawnprojectile ("BluePlasmaFire", 42, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAA 0 a_spawnprojectile ("BloodMistBig", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAA 0 a_spawnprojectile ("SuperGoreMistSmall", 32, 0, random (0, 360), 2, random (10, 90));
		TNT1 AAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (0, 360), 2, random (0, 180));
		PBR1 B 6 A_NoBlocking();
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1Blue",random(-2,2),random(-2,2),10,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItem("Barrel_explosion_Column");
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-15, 15), random (-15, 15));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-35, 35), random (-35, 35));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-45, 45), random (-45, 35));
		PBR1 CCDD 3 a_spawnprojectile ("BluePlasmaFire", 32, 0, random (0, 360), 2, random (0, 180));
		PBR1 EEFF 3;
		PBR1 GG 3;
		PBR1 H -1;
	Stop;
	
	OtherPlasmaDeath:
		IMPP A 1 A_PlaySound("plasmaflesh");
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("Ashes1", 33, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAA 0 a_spawnprojectile ("BluePlasmaFire", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("Ashes2", 31, 0, random (0, 360), 2, random (0, 180));
		IMPP B 6 A_NoBlocking();
		TNT1 AAAAAAA 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 a_spawnprojectile ("Brains1", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAA 0 a_spawnprojectile ("Brains7", 52, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile ("BrainBlood", 50, 0, random (0, 360), 2, random (0, 160));
		IMPP CDE 6;
		IMPP FFFFFFFFFFFFFFFFFFFFFFFFFFFFF 8 a_spawnprojectile ("ExplosionSmoke", 10, 0, random (0, 360), 2, random (0, 160));
		IMPP F -1;
	stop;
	
	Death.SuperPlasma:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		XBRN AA 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
		TNT1 AAAA 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		XBRN BB 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
		TNT1 A 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
		XBRN CC 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
		TNT1 AAAAA 0 a_spawnprojectile ("PlasmaParticleX", 48, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAA 0 a_spawnprojectile ("PlasmaParticleX", 42, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 0;
	Stop;
	
	Death:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInventory("IsJumping", 1, "DeathJump");
		TNT1 A 0 A_Jump(62, "Death.Arm");
		TNT1 A 0 A_Jump(54,"DeathNoGuts");
		TNT1 A 0 A_Jump(62,"Death20alt");
		DRKV L 7;
		DRKV M 6 A_Scream();
		DRKV N 5 a_spawnprojectile ("XDeath1", 30, 0, random (0, 360), 2, random (0, 160));
		DRKV O 5 A_Fall();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem ("DeadDarkImpDRKVP");
	Stop;
	
	FatalityMarine:
		TNT1 A 0 A_SetInvulnerable();
		F1D1 BCDE 4;
		TNT1 A 0 A_SpawnItemEx("FootStep5", 0, 0, 40, 0, 0);
		F1D1 E 6;
		TNT1 A 0 A_PlaySound("dimp/active",2);
		F1D1 F 6;
		
		TNT1 A 0 A_PlaySound("DSFDTHE", 3);
		F1D1 G 6;
		TNT1 AAAA 0 a_spawnprojectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("xdeath4", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("PlayerFlyingBlood", 25, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 1, 0, random (0, 360), 2, random (0, 160));
		F1D1 H 12;
		TNT1 A 0 A_PlaySound("EYEPULL", 4);
		TNT1 AAAAA 0 a_spawnprojectile ("PlayerFlyingBlood", 25, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("MuchBlood", 1, 0, random (0, 360), 2, random (0, 160));
		F1D1 I 8;
		
		F1D1 J 6 A_PlaySound("monster/ovlbit",8);
		TNT1 A 0 a_spawnprojectile ("XDeath1", 26, 0, random (0, 360), 2, random (0, 160));
		F1D1 KL 6;
		TNT1 A 0 A_PlaySound("monster/ovlbit",7);
		TNT1 A 0 a_spawnprojectile ("XDeath1", 26, 0, random (0, 360), 2, random (0, 160));
		F1D1 LLLLJJJJLLLLJJJJ 2 a_spawnprojectile ("Brutal_LiquidBlood3", 35, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_PlaySound("monster/ovlbit",7);
		TNT1 A 0 a_spawnprojectile ("XDeath1", 26, 0, random (0, 360), 2, random (0, 160));
		F1D1 LLLLJJJJLLLLJJJJ 2 a_spawnprojectile ("Brutal_LiquidBlood3", 35, 0, random (0, 360), 2, random (0, 40));
		
		//TNT1 A 0 A_TakeInventory("Fatality_Marine",1);
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_UnSetInvulnerable();
		//TNT1 A 0 A_SpawnItem ("MarineGotOwnedByImp", 1);
	Goto SeeContinue;
	
	DeathJump:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Stop();
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil (20);
		DRKI KLM 6;
		TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
		//TNT1 A 0 A_SpawnItem ("DeadDarkImp1");
	Stop;
	
	Death.cutless:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
		TNT1 A 0 A_Jump(16, "Death");
		TNT1 A 0 A_Jump(16, "Death.LegMassacre");
	Goto Death.Massacre;
	
	Death.Massacre:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Scream();
		TNT1 O 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem ("BrutalizedDarkImp1", 1);
	Stop;
	
	Death.LegMassacre:
		//TNT1 A 0 a_spawnprojectile ("XDeathDarkImpLeg", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		D1S4 A 8 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		D1S4 B 8 A_Scream();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem ("DarkImpBrutalizedWithNoLeg");
	Stop;
	
	Death20alt:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		D1S8 ABCD 6;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItemEx ("DarkImpDyingOfBloodLoss", 0,0,7,0,0,0,0,SXF_NOCHECKPOSITION,0);
	Stop;
	
	Death.Arm:
		//TNT1 A 0 a_spawnprojectile ("XDeathDarkImpArm1", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		D1S5 A 8 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		//TNT1 A 0 A_SpawnItem ("DyingDarkImpNoArm", 2);
	Stop;
	
	Death.Leg:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInventory("IsJumping", 1, "Death.LegInTheAir");
		//TNT1 A 0 a_spawnprojectile ("XDeathDarkImpLeg", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		D1S4 A 9;
		D1S4 A 3 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		D1S4 B 3 A_Scream();
		D1S4 C 3 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem ("DyingDarkImpNoLeg", 5);
	Stop;
	
	DeathNoGuts:
		TNT1 AAAAA 0;
		TNT1 AA 0 a_spawnprojectile ("Instestin", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 30, 0, random (0, 360), 2, random (0, 160));
		D1S6 A 8 A_Scream();
		D1S6 B 8 A_NoBlocking();
		D1S6 C 8;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem ("DyingDarkImp", 2);
	Stop;
	
	Death.Tear:
	Death.Saw:
	Death.Cut:
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile ("xdeath4", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("Instestin", 24, 0, random (0, 360), 2, random (0, 160));
		D1S7 A 2;// a_spawnprojectile ("XDeathHalfDarkImp", 0, 0, random (0, 360), 2, random (0, 160));
		D1S7 AAA 4 A_SpawnItem ("Big_Blood", 0, 30);
		D1S7 BCDE 8;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 1 A_SpawnItem ("DeadDarkImp_Half", 5);
	Stop;
	
	Death.Decaptate:
		TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		//TNT1 A 0 a_spawnprojectile ("XDeathDarkImpHead1", 0, 0, random (0, 360), 2, random (0, 160));
		D1S9 A 9 A_NoBlocking();
		D1S9 B 9 A_XScream();
		TNT1 A 0 A_Jump(32, "Deathchickenhead");
		D1S9 C 8;
		D1S9 DE 8;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 1 A_SpawnItem ("DeadDarkImp_NoHead1", 5);
	Stop;
	
	Death.HeadExplode:
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAA 0 a_spawnprojectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("Brains3", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("Brains6", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("Brains7", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Jump(64, "DeathHead2");
		D1S9 A 9 A_NoBlocking();
		D1S9 B 9 A_XScream();
		TNT1 A 0 A_Jump(32, "Deathchickenhead");
		D1S9 C 8;
		D1S9 DE 8;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 1 A_SpawnItem ("DeadDarkImp_NoHead1", 5);
	Stop;
	
	HeadExploder:
		TNT1 A 0;
		TNT1 A 0 A_Jump(72, "Death.HeadExplode");
	Goto Death.MinorHead;
		
	Death.head:
		TNT1 A 0{self.bNOGRAVITY = false;}
		TNT1 A 0{self.bCEILINGHUGGER = false;}
		//TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		//TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
		//TNT1 A 0 A_JumpIfInTargetInventory("HasCutingWeapon", 1, "Death.Decaptate");
		TNT1 A 0 A_JumpIfHealthLower(-75, "Death.HeadExplode");
		//TNT1 A 0 A_JumpIfInTargetInventory("RandomHeadExploder", 1, "HeadExploder");
	Death.MinorHead:
		TNT1 A 0;
		TNT1 A 0 A_Playsound("MinorHeadshot", 0);
		TNT1 AA 0 a_spawnprojectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains3", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains6", 50, 0, random (0, 360), 2, random (0, 160));
		//TNT1 A 0 a_spawnprojectile ("Brains7", 50, 0, random (0, 360), 2, random (0, 160))
		TNT1 AA 0 a_spawnprojectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AA 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Jump(179, "MinorHead1");
		D1S9 K 9 A_NoBlocking();
		D1S9 L 9 A_Scream();
		D1S9 M 8;
		D1S9 N 8;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem ("DeadDarkImpD1S9O");
	Stop;
	
	MinorHead1:
		D1S9 P 8 A_NoBlocking();
		D1S9 Q 8 A_XScream();
		D1S9 R 8;
		D1S9 SSS 2 a_spawnprojectile ("Brutal_LiquidBlood2", 25, 0, random (0, 360), 2, random (60, 120));
		D1S9 T 2 A_Scream();
		D1S9 TTTSSS 2 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		D1S9 U 6;
		//TNT1 A 0 A_SpawnItem ("DeadDarkImpD1S9V");
	Stop;
	
	Deathchickenhead:
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		D1S9 FGHI 5 A_SpawnItem ("Blood", 0, 40);
		
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		D1S9 FGHI 5 A_SpawnItem ("Blood", 0, 40);
		
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		D1S9 FGHI 5 A_SpawnItem ("Blood", 0, 40);

		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		D1S9 FGHI 5 A_SpawnItem ("Blood", 0, 40);
		TNT1 A 0 A_PlaySound("misc/xdeath2c");

		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		D1S9 FGHI 5 A_SpawnItem ("Blood", 0, 40);
		TNT1 A 0 A_PlaySound("misc/xdeath2c");

		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		D1S9 FGHI 5 A_SpawnItem ("Blood", 0, 40);
		TNT1 A 0 A_PlaySound("misc/xdeath2c");

		D1S9 DE 8;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 1 A_SpawnItem ("DeadDarkImp_NoHead1", 5);
	Stop;
	
	DeathHead2:
		TNT1 A 0 A_XScream();
		DRKD A 9 A_NoBlocking();
		DRKD C 8;
		DRKD DE 8;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 1 A_SpawnItem ("DeadDarkImp_NoHead2", 5);
	Stop;
	
	Death.ExplosiveImpact:
	Death.ExtremePunches:
	Death.SuperKick:
	Death.LandMine:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("xdeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile ("xdeath4", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0{self.bNOBLOCKMONST = true;}
		
		TNT1 AAAA 0 a_spawnprojectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains3", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains6", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains7", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAA 0 a_spawnprojectile ("BrainBlood", 50, 0, random (0, 360), 2, random (0, 160));
		//TNT1 A 0 a_spawnprojectile ("XDeathDarkImpArm1", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		//TNT1 A 0 a_spawnprojectile ("XDeathDarkImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		D3S1 AB 5;
		D3S1 CDEF 5 A_CheckFloor ("Dead.ExplosiveImpact");
		D3S1 EEEEEEEEEE 5 A_CheckFloor ("Dead.ExplosiveImpact");
		//TNT1 A 0 A_SpawnItem ("ThisDarkImpGotFuckedHard");
	Stop;
	
	Dead.ExplosiveImpact:
		TNT1 A 0 A_Jump(128, "Dead.ExplosiveImpact2");
		//TNT1 A 0 A_SpawnItem ("ThisDarkImpGotFuckedHard");
		//TNT1 A 0 A_SpawnItem ("Ploft");
		TNT1 AAAA 0 A_SpawnItem ("Blood");
	Stop;
	
	Dead.ExplosiveImpact2:
		//TNT1 A 0 A_SpawnItem ("ThisDarkImpGotFuckedHard2");
		//TNT1 A 0 A_SpawnItem ("Ploft");
		TNT1 AAAA 0 A_SpawnItem ("Blood");
	Stop;
	
	Death.SSG:
	Death.SuperPunch:
		IZD1 E 1 A_Pain();
		IZD1 E 1 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("xdeath2", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("xdeath4", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("xdeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("LivingHeart", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		//TNT1 A 0 a_spawnprojectile ("XDeathDarkImpArm1", 32, 0, random (170, 190), 2, random (0, 40));
		//TNT1 A 0 a_spawnprojectile ("XDeathDarkImpArm2", 32, 0, random (170, 190), 2, random (0, 40));
		//TNT1 A 0 a_spawnprojectile ("XDeathDarkImpHead1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		D2S2 EEFFGH 6;
		//TNT1 A 0 A_SpawnItem ("DeadDarkImpD2S2H");
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
	Stop;
	
	Death.Blast:
	Death.Railgun:
	Death.Eat:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Jump(12, "Death.Arm");
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_Jump(128, "Death.Blast2")
		TNT1 A 0 A_XScream();
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathImpArm", 32, 0, random (150, 210), 2, random (0, 40));
		//TNT1 A 0 a_spawnprojectile ("XDeathDarkImpHead1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		D3S3 A 6 A_Stop();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		D3S3 BBBBBBBBBB 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (30, 60));
		D3S3 CCC 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (10, 40));
		D3S3 DD 3 a_spawnprojectile ("Brutal_LiquidBlood2", 6, 0, random (0, 360), 2, random (30, 60));
		//TNT1 A 0 A_SpawnItem ("AbsolutelyRapedDarkImp2");
	Stop;
	
	/*Death.Shotgun:
			TNT1 A 0 A_JumpIfCloser(300, "Death.Shotgunontheface")
			Goto Death*/
	Death.Shotgun:
	Death.Shotgunontheface:
		TNT1 A 0 A_JumpIfCloser(120, "Death.Blast");
		TNT1 A 0 A_Jump(128, "DeathJump");
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_Jump(92, "DeathJump")
		TNT1 A 0{self.bNOBLOCKMONST = true;}
		TNT1 A 0 A_Jump(32, "Death.ARm");
		TNT1 A 0 A_Jump(20,"DeathNoGuts");
		TNT1 A 0 A_Jump(42, "Death.Arm");
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_Pain();
		DRKI H 1 A_FaceTarget();
		TNT1 A 0 A_Recoil(13);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		TNT1 A 0 A_Scream();
		TNT1 A 0 a_spawnprojectile ("MuchBlood2", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 35, 0, random (0, 360), 2, random (0, 160));
		D3S2 ABCDE 4;
		D3S2 FGHIJK 4 A_JumpIf((vel.Y == 0), "DSFStop");
	Goto DSFStop+1;
	
	DSFStop:
		//TNT1 A 0 A_SpawnItem("Ploft3");
		TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
		TNT1 A 0 a_spawnprojectile ("SuperWallRedBlood", 2, 0, random (170, 190), 2, random (0, 0));
		//TNT1 A 0 A_SpawnItem ("DeadDarkImpD3S2K");
	Stop;
	
	DeathJump:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Stop();
		TNT1 A 0{self.bNODROPOFF = false;}
		TNT1 A 0{self.bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil (10);
		DRKI K 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		DRKI K 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		DRKI K 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		DRKI K 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		DRKI L 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		DRKI L 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		DRKI L 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		DRKI M 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem ("DeadDarkImp1");
	Stop;

	TakeASit:
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		DRKI K 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItemEx("DeadDarkImp_Slumped", 10);
	Stop;
	
	Death.Nailgun:
		TNT1 A 0{self.bNODROPOFF = false;}
		TNT1 A 0{self.bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,random(22,30),0,1);
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil (30);
		DRKI K 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		DRKI K 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		DRKI K 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		DRKI K 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		DRKI L 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		DRKI L 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		DRKI L 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		DRKI M 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem ("DeadDarkImp1");
	Stop;

	PinToWall:
		TNT1 A 0 a_spawnprojectile ("MuchBlood2", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_PlaySound("Weapons/NailHitBleed", 6);
		PIN5 A 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItemEx("DeadDarkImp_Pinned", 10, 0, 10);
	Stop;
	
	Death.Fatality:
		TNT1 A 0 A_Pain();
		TNT1 A 0;//A_NoBlocking
		//TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, 1);
		Goto Death.ExplosiveImpact;
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_Jump(255, "Death.Fatality1", "Death.Fatality2");
	Death.Fatality1:
		TNT1 A 1;
		//TNT1 A 0 A_GiveToTarget("DarkImpFatality1", 1);
	Stop;
	
	Death.Fatality2:
		TNT1 A 1;
		//TNT1 A 0 A_GiveToTarget("DarkImpFatality2", 1);
	Stop;
	
	XDeath:
	Death.Quadblast:
		//TNT1 A 0 A_JumpIfInTargetInventory("SSGSelected", 1, "Death.SSG");
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_FaceTarget();
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 42, 0, random (170, 190), 2, random (10, 60));
		TNT1 AAA 0 a_spawnprojectile ("XDeath3", 42, 0, random (170, 190), 2, random (10, 60));
		TNT1 A 0 a_spawnprojectile ("xdeath4", 42, 0, random (170, 190), 2, random (10, 60));
		TNT1 A 0 a_spawnprojectile ("XDeath4", 42, 0, random (170, 190), 2, random (10, 60));
		//TNT1 A 1 a_spawnprojectile ("DarkImpXDeath", 0, 0, random (0, 360), 2, random (0, 160));
	Stop;
	
	Raise:
		DRKV PO 8;
		DRKV NML 6;
	Goto SeeContinue;
}
}

CLASS InfernoBall : pb_projectile_base
{
Default
{
	Radius 8;
	Height 6;
	Speed 14;
	Damage 6;
	DamageType "Desintegrate";
	PROJECTILE;
	RENDERSTYLE "Add";
	ALPHA 0.67;
	Scale 0.28;
	SeeSound "dimp/missile";
	DeathSound "imp/shotx";
	Decal "DoomImpScorch";
}

States
{
	Spawn:
		TNT1 A 0 nodelay A_Playsound("DarkImpFireLoop", 1, 1);
	Fly:
		TNT1 A 0 A_SpawnItem("Green_FlareSmall",0,0);
		DB57 AAABBBCCC 1 Bright A_SpawnItemEx ("GreenPlasma_Puff_Small", 0, 0, 0, random(0, -4), random(-2, 2), random(-2, 2), 0, 0, 0);
		Loop;
		Death:
		TNT1 A 0 Bright A_SpawnItemEx ("GreenPlasma_Puff_Small", 0, 0, 0, random(0, -4), random(-2, 2), random(-2, 2), 0, 0, 0);
	Stop;
}
}

CLASS InfernoBallTrail : ACTOR { 
Default
{
	Radius 1;
	Height 1;
	Speed 0;
	Damage 0;
	DamageType "Flames";
	+NOGRAVITY;
	Scale 0.2;
}

States
{
	Spawn:
	ITRL ABCDEFGHIJKLMN 1 Bright A_SpawnItemEx("GreenFlameTrails", 0, 0, 0, 0, 0, 0, 0, 128);
	stop;
}
}

CLASS NetherLightning : ACTOR { 
Default {
	Radius 8;
	Height 6;
	Speed 19;
	Damage 4;
	DamageType "Plasma";
	PROJECTILE;
	+RIPPER;
	RENDERSTYLE "Add";
	ALPHA 0.75;
	Scale 0.85;
	SeeSound "caco/attack";
	DeathSound "weapons/devzap";
	Decal "DoomImpScorch";
}

States
{
	Spawn:
	NLIT AA 1 Bright A_SpawnItemEx ("NetherLightningTrail", 0, 0, 0, 0, 0, 0, 0, 0, 0);
	TNT1 A 0 A_SpawnItem("Blue_Flare",0,0);
	TNT1 A 0 a_spawnprojectile ("BluePlasmaFireSmall", 0, 0, random (0, 360), 2, random (0, 360));
	NLIT A 0 Bright A_SpawnItemEx ("NetherLightningSpark", 0, 0, 0, random(0, -4), random(-2, 2), random(-2, 2), 0, 0, 0);
	NLIT AA 1 Bright A_SpawnItemEx ("NetherLightningTrail", 0, 0, 0, 0, 0, 0, 0, 0, 0);
	TNT1 A 0 A_SpawnItem("Blue_Flare",0,0);
	TNT1 A 0 a_spawnprojectile ("BluePlasmaFireSmall", 0, 0, random (0, 360), 2, random (0, 360));
	NLIT A 0 Bright A_SpawnItemEx ("NetherLightningSpark", 0, 0, 0, random(0, -4), random(-2, 2), random(-2, 2), 0, 0, 0);
	loop;
	Death:
	NLIT ABCDEFG 1 Bright;
	Stop;
}
}

CLASS NetherLightningTrail : ACTOR { 
Default {
	Radius 8;
	Height 6;
	Speed 1;
	Damage 0;
	DamageType "blood";
	PROJECTILE;
	// +RIPPER
	RENDERSTYLE "Add";
	ALPHA 0.75;
	Scale 0.75;
	}
    States
    {
	Spawn:
	NLIT A 1 A_FadeOut (0.025);
	NLIT A 0 A_Jump (32, "Spark");
	loop;
	Spark:
	NLIT A 0 A_SpawnItemEx ("NetherLightningSpark", 0, 0, 0, random(0, -4), random(-2, 2), random(-2, 2), 0, 0, 0);
	TNT1 A 0 a_spawnprojectile ("BluePlasmaFireSmall", 0, 0, random (0, 360), 2, random (0, 360));
	goto Spawn;
}
}

CLASS NetherLightningSpark : ACTOR { 
Default {
	Radius 1;
	Height 1;
	Speed 0;
	Damage 0;
	DamageType "Plasma";
	+NOGRAVITY;
	Scale 0.3;
	}
    States
    {
	Spawn:
	NLIT BCDEFG 1 Bright;
	stop;
}
}
