//===========================================================================
//
// Imp aka pimp my imp
//
//===========================================================================

CLASS pb_imp: proto_imp_class// Replaces DoomImp
{ 
Default
{	
	Scale 1.04;
	//SpawnID 1400;
	Health 75;

	Mass 100;
	GibHealth 35;
	Monster;
	MaxStepHeight 24;
	MaxDropOffHeight 32;
	Speed 8;

	+SLIDESONWALLS;
	+FLOORCLIP;

	PainChance 200;
	PainChance "Stun", 255;
	PainChance "Avoid", 35;
	PainChance "Head", 255;
	PainChance "Taunt", 255;
	PainChance "Kick", 255;
	PainChance "ExtremePunches", 255;
	PainChance "Melee", 255;
	PainChance "Fatality", 255;
	PainChance "ExplosiveImpact", 255;
	PainChance "Trample", 255;

	damagefactor "TeleportRemover", 0.0;
	damagefactor "GibRemoving", 0.0;
	damagefactor "Avoid", 1.0;
	damagefactor "Trample", 1.5;
	damagefactor "Crush", 10.0;
	DamageFactor "CauseObjectsToSplash", 0.0;
	damagefactor "killme", 0.0;
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0;
	damagefactor "Shrapnel", 0.3;
	damagefactor "explosiveimpact", 2.0;
	damagefactor "Kick", 0.5;
	damagefactor "SSG", 5.0;

	
	BloodType "pb_blood", "BloodSPlatterReplacer", "SawBlood";
	Species "Imp";
	SeeSound "imp/sight";
	PainSound "imp/pain";
	DeathSound "imp/death";
	ActiveSound "imp/active";
	
//	DropItem "DemonStrengthRune", 1;
//	DropItem "Demonpickup", 60;
}

States
{	
	Spawn:
		TROO A 0;
		//TNT1 A 0 ACS_ExecuteAlways(796, 0, 0, 0, 0);//Check if Vanilla Mode is activated
		//TNT1 A 1 ACS_NamedExecuteAlways("CeilingClimbingImps", 0);//Check for CVARs
		//TNT1 A 0 A_GiveInventory("SKImp", 1);
		TNT1 A 0 A_JumpIf(waterlevel >= 2, "Swim");
		TNT1 A 0 {self.on_floor = true;}
	Stand:
		TROS AB 11 A_Look();
	Loop;
		
	See:
		TNT1 A 0 A_TakeInventory("EnemyMemory", 15);
		tnt1 a 0 a_jumpif(first_seeing == true , 4);
		TROT A 4 A_faceTarget();
		TROT B 4 {first_seeing = true;}
		TROT C 10;//waving his arms here
		tnt1 a 0 a_spawnitemEx("FootStep", 0, 0, 10, 0, 0);
		TNT1 A 0 A_JumpIf(waterlevel >= 2, "Swim");
		TNT1 A 0 A_JumpIfInventory("EnemyMemory", 25, "ForgetTarget");
		TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
		TROO AAA 2 A_Chase();		
		TROO A 2 {A_Chase(); A_PlaySound("flesh/step",4); }
		TROO BBBBCCC 2 A_Chase();
		TROO C 2 {A_Chase(); A_PlaySound("flesh/step",4);}
		TROO DDDD 2 A_Chase();
		TNT1 A 0 A_Jump(236, 3);
		TNT1 A 0 A_JumpIfCloser(800, "jump_to_ceiling");
		TNT1 AAAAA 0;
	Loop;

	Idle:
	LookingForPlayer:
		//TNT1 A 0 A_GiveInventory("SKImp", 1);
		TNT1 A 0 {self.angle -= 40;}
		TROO BBB 10 A_Look();
		TNT1 A 0 {self.angle += 40;}
		TROO BBB 10 A_Look();
		TROO AA 2 {A_Wander(); A_Look(); A_PlaySound("flesh/step",4); A_Recoil(-2);}
		TROO BB 2 {A_Wander(); A_Look(); A_Recoil(-2);}
		TROO CC 2 {A_Wander(); A_Look(); A_PlaySound("flesh/step",4); A_Recoil(-2);}
		TROO DD 2 {A_Wander(); A_Look(); A_Recoil(-2);}
	Loop;

	Advancing:
		//TNT1 A 0 A_TAkeInventory("CantFire", 1);
		//TNT1 A 0 A_takeInventory("SKImp", 1);
		tnt1 a 0 a_spawnitemEx("FootStep", 0, 0, 10, 0, 0);
		TNT1 A 0 A_JumpIfInventory("EnemyMemory", 20, "ForgetTarget");
		TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
		TROO AAAA 2 A_Chase();
		TROO BBBB 2 A_Chase();
		TROO CCCC 2 A_Chase();
		TROO DDDD 2 A_Chase();
	Loop;
		
	jump_to_ceiling:
		TNT1 A 0
		{
			if(pb_imp_ceiling_jump() == false)
			{setstatelabel("see");}//ceiling too high or there ara sky
		}
		1M40 A 6
		{
			A_PlaySound("imp/sight",6);
			//self.vel.z += 110;
		}

		2M40 AAABBBBCCCCDDDD 1
		{
			if( (pos.z + height) >= ceilingz)
			{
				pb_change_flags_for_jump();
				self.ceiling_jump = false; 
				self.on_ceiling = true;
				setstatelabel("CeilingLatch");
			}
		}
		
	jump_up:
		2M40 D 1
		{
			if( (self.pos.z + self.height) >= self.ceilingz)
			{
				self.ceiling_jump = false; self.on_ceiling = true; self.on_floor = false;
				setstatelabel("CeilingLatch");
			}
		}
		tnt1 a 0 a_jumpif( self.vel.z <= 0, 1);
	loop;
		//jumps fail, make a good appearance
		2M40 EEEEFFFFGGGG 1
		{
			if( self.pos.z <= self.floorz)
			{
				self.ceiling_jump = false; self.on_ceiling = false;
				self.on_floor = true;
				setstatelabel("See");
			}
		}

	falling_down:
		1M40 A 1
		{
			if( self.pos.z <= self.floorz)
			{
				pb_change_flags_for_jump();
				self.ceiling_jump = false; self.on_ceiling = false;
				self.on_floor = true; setstatelabel("CeilingLatch");
			}
		}
	loop;
		
	CeilingCrawl:
		tnt1 a 0 a_spawnitemEx("FootStep", 0, 0, 10, 0, 0);
		TNT1 A 0 A_JumpIf(waterlevel >= 2, "Swim");

		//TNT1 A 0 A_JumpIf(CallACS("IsThisSky") == 1, "jump_from_ceiling");
		//TNT1 A 0 A_JumpIf(vel.z != 0, "jump_from_ceiling")
		//TNT1 A 0 ThrustThingZ(0,500,0,1);
		2M40 II 2 A_Chase("jump_from_ceiling", "CeilingMissile");

		2M40 HH 2 A_Chase("jump_from_ceiling", "Maybe_jump_from_ceiling");
		TNT1 A 0 A_PlaySound("flesh/step",4);
		//TNT1 A 0 A_JumpIf(CallACS("IsThisSky") == 1, "jump_from_ceiling");
		TNT1 A 0 A_JumpIf(vel.z != 0, "jump_from_ceiling");
		TNT1 A 0 A_JumpIfTargetInLOS(1);//this is too costly function, must be replaced by line tracer
	Goto CeilingDrop;
		TNT1 A 0;
		TNT1 A 0 A_Jump(224, 3);
		TNT1 A 0 A_JumpIfCloser(1200, "CeilingDrop");
		TNT1 AAAAA 0;
	Loop;
		
	CeilingDrop:
		TNT1 AAA 0;
		TNT1 A 0 {self.on_ceiling = false; self.bNOGRAVITY = false; self.bCEILINGHUGGER = false;}
		2M40 DCBA 1 A_FaceTarget();
	CeilingDropping:
		TROT F 1 A_JumpIf (vel.z == 0, "CeilingLanding");
	Loop;

	CeilingLanding:
		TNT1 A 0 A_PlaySound("flesh/step",4);
		TROT GHCD 5 A_FaceTarget();
	Goto see;

	CeilingMissile:
		2M40 L 4 A_FaceTarget();
		//TNT1 A 0 A_JumpIfCloser(150, "jump_from_ceiling");
		TNT1 A 0 A_Playsound ("IMPCHARG");
		TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 25, -30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 25, -30, random (0, 140), 2, random (0, 160));
		2M40 L 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 25, -30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 25, -30, random (0, 140), 2, random (0, 160));
		//TNT1 A 0 ThrustThingZ(0,500,0,1);
		2M40 L 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 25, -30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 25, -30, random (0, 140), 2, random (0, 160));
		//TNT1 A 0 ThrustThingZ(0,500,0,1);
		2M40 L 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 25, -30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 25, -30, random (0, 140), 2, random (0, 160));
		//TNT1 A 0 ThrustThingZ(0,500,0,1);
		2M40 L 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 25, -30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 25, -30, random (0, 140), 2, random (0, 160));
		//TNT1 A 0 ThrustThingZ(0,500,0,1);
		2M40 L 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 25, -30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 25, -30, random (0, 140), 2, random (0, 160));
		//TNT1 A 0 ThrustThingZ(0,500,0,1);
		2M40 M 2 A_FaceTarget();
		//TNT1 A 0 ThrustThingZ(0,500,0,1);
		2M40 N 6 a_spawnprojectile("pb_imp_fireball", 22, 0, 0, 0);
		//TNT1 A 0 ThrustThingZ(0,500,0,1);
		2M40 M 4;
	Goto CeilingCrawl;
		
	Maybe_jump_from_ceiling:
		TNT1 A 0 A_Jump(28, 3);
	Goto CeilingCrawl;
	
	jump_from_ceiling:
		TNT1 AAA 0;
		TNT1 A 0 
		{
			self.on_ceiling = false; self.bNOGRAVITY = false;
			self.bCEILINGHUGGER = false; self.bTHRUSPECIES = false;
		}
		TNT1 A 0 A_Recoil (-18);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_PlaySound("weapons/fistwhoosh");
		TNT1 A 0 a_spawnprojectile("ImpAttack2",10,0,0,0);
		2M40 CDEFG 4 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("ImpAttack2",10,0,0,0);
		1M40 EEE 1 a_spawnprojectile("ImpAttack2",10,0,0,0);
		TNT1 A 0 {self.ceiling_jump = false;}
		
		TNT1 A 0 A_Jump(24, 3);
		1M40 A 6;
	Goto see;
		TNT1 AAA 0;
	Goto Melee+1;

	ForgetTarget:
		TNT1 A 0 A_ClearTarget();
		TNT1 A 0 A_TakeInventory("EnemyMemory", 25);
	Goto Stand;

	Melee:
		TNT1 A 0 A_Jump(132, "Melee3");
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_PlaySound("imp/sight",6);
		1M40 ABCD 4 A_Recoil (-1);
		1M40 A 5 A_FaceTarget();
		TNT1 A 0 A_JumpIfCloser(60, "Melee2");
		//TNT1 A 0 A_takeInventory("SKImp", 1);
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil (-10);
		1M40 E 6;
		TNT1 A 0 {self.ceiling_jump = true;}
		TNT1 A 0 A_PlaySound("weapons/fistwhoosh");
		TNT1 A 0 A_FaceTarget();
		1M40 E 4 a_spawnprojectile("ImpAttack2",10,0,0,0);
		TNT1 A 0 {self.ceiling_jump = false;}
		1M40 A 4 a_spawnprojectile("ImpAttack2",10,0,0,0);
	Goto see;
		
	Melee2:
		TROO EF 4 A_FaceTarget();
		//TNT1 A 0 A_takeInventory("SKImp", 1);
		TROO G 4 a_spawnprojectile("ImpAttack",10,0,0,0);
		TROO FE 4;
	Goto see;
		
		
	Melee3:
		TROO E 1 A_FaceTarget();
		TNT1 A 0 A_JumpIfCloser(50, "Melee2");
		
		TROT CD 4;
		//TNT1 A 0 A_takeInventory("SKImp", 1);
		TNT1 A 0 ThrustThingZ(0,25,0,1);
		TNT1 A 0 A_FaceTarget();
		
		TNT1 A 0 A_Recoil (-10);
		TROT E 2;
		TROT F 2;
		TNT1 A 0 {self.ceiling_jump = true;}
		TNT1 A 0 A_PlaySound("weapons/fistwhoosh");
		TNT1 A 0 A_FaceTarget();
		TROT F 6;
		TNT1 A 0 a_spawnprojectile("ImpAttack2",10,0,0,0);
		TNT1 A 0 {self.ceiling_jump = false;}
		//TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
		TROT G 1;
		TROT GG 2 a_spawnprojectile("ImpAttack2",10,0,0,0);
		TROT G 1;
		//TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
		//TROT HHH 2 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
	Goto see;
		
	Missile:
		TNT1 A 0 {if (self.on_ceiling == true) { setstatelabel("CeilingMissile");} }
		TNT1 A 0 A_JumpIfCloser(150, "Melee");
		
		//TNT1 A 0 A_takeInventory("SKImp", 1);
		TNT1 A 0 A_JumpIfCloser(1200, 3);
		//TNT1 A 0 a_spawnprojectile("MonsterTargetCheck", 34, 0, 0, 0);
		//TNT1 A 0 a_spawnprojectile("MonsterTargetCheckFaster", 34, 0, 0, 0);
		TROO E 4 A_FaceTarget();
		//TNT1 A 0 A_JumpIfInventory("CantFire",1, "Advancing");
		TNT1 A 0 A_JumpIfCloser(170, "Melee");
		TNT1 A 0 A_Playsound ("IMPCHARG");
		TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
		TROO E 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
		TROO E 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
		TROO E 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
		TROO E 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
		TROO E 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
		TNT1 A 0 A_Jump(100, "specialattack");
		TROO F 2 A_FaceTarget();
		TROO G 6 a_spawnprojectile("pb_imp_fireball", 34, 0, 0, 0);
		TROO F 4;
	Goto see;
		
	SpecialAttack:
		TROO F 2 A_FaceTarget();
		TROO G 6 a_spawnprojectile("pb_imp_fireball", 34, 0, 0, 0);
		TROO F 4;
		TROO I 2 A_FaceTarget();
		TROA H 6 a_spawnprojectile("pb_imp_fireball", 34, 0, 0, 0);
		TROO I 4;
	Goto see;
		
	Death.Eat:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Scream();
		//TNT1 A 0 A_GiveToTarget("ImpFatality",1);
		TNT1 A 0;
	stop;		
	Death.HelperMarineFatallity:
	Death.RVFT:
		TNT1 A 0;
		TNT1 A 1 A_Pain();
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_GiveToTarget("ImpFatality3", 1);
		//TNT1 A 0 A_GiveToTarget("ImpFatality", 1);
	stop;		
	Death.Fatality:
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_JumpIfIntargetInventory("FistsSelected", 1, 1);
	Goto Death.ExplosiveImpact;
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_Jump(255, "Death.Fatality", "Death.Fatality1", "Death.Fatality2", "Death.Fatality2", "Death.Fatality3", "Death.Fatality3", "Death.Fatality4", "Death.Fatality5");
	Death.Fatality1:
		//TNT1 A 0 A_GiveToTarget("ImpFatality", 1);
	stop;
	Death.Fatality2:
		//TNT1 A 0 A_GiveToTarget("ImpFatality2", 1);
	stop;	Death.Fatality3:
	Death.BHFT:
		//TNT1 A 0 A_GiveToTarget("ImpFatality3", 1);
	stop;	Death.Fatality4:
		//TNT1 A 0 A_GiveToTarget("ImpFatality4", 1);
	stop;	Death.Fatality5:
		//TNT1 A 0 A_GiveToTarget("ImpFatality5", 1);
	stop;		
		
	Pain.Melee:
		TNT1 A 0 {self.bNOGRAVITY = false; self.bTHRUSPECIES = false; self.bCEILINGHUGGER = false;}
		TNT1 D 0;
		TROO A 2;
		//TNT1 A 0 A_JumpIfInventory ("SKImp", 1, "GotoStealthKill");
		TROO A 2 A_Pain();
	Goto see;
		
	GotoStealthKill:
		TNT1 A 1;
		//TNT1 A 0 A_GiveToTarget("SKImp");
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 1 A_Die("Stealthy");
	stop;
	
	Death.Stealthy:
		TNT1 A 0 A_NoBlocking();
	stop;
	
	Pain:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false; self.bTHRUSPECIES = false; self.bCEILINGHUGGER = false;}
		TNT1 A 0 { if( self.on_ceiling == true) { setstatelabel("PainCanFallFromCeiling");} }
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain.IsDown");
		//TNT1 A 0 A_takeInventory("SKImp", 1);
		TROO H 3;
		TROO H 3 A_Pain();
	Goto see;
		
	Possession:
		TNT1 A 0 A_SetInvulnerable();
		TROO H 3;
		TROO H 3 A_Pain();
		"####" "#" 35;// ACS_NamedExecuteAlways("Pos - Flicker effect");
		TNT1 A 0 A_UnSetInvulnerable();
	Goto See;
		
	Pain.Stun:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_SpawnItemEx ("StunElectrocute", random (-4, 4), random (-4, 4),  random (16, 32), 0, 0);
		TROO H 1 A_Pain();
		TROO HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		TROO H 1 A_Pain();
		TROO HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		TROO H 1 A_Pain();
		TROO HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		TROO H 1 A_Pain();
		TROO HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		TROO H 1 A_Pain();
		TROO HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		TROO H 1 A_Pain();
	Goto See;
		
	Pain.IsDown:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		ID11 B 1;
		ID11 B 5 A_Pain();
	Goto GetUp;
		
		
	Pain.KillMe:
	Pain.Taunt:
		TNT1 A 0;
	Goto Missile;

	Death.KillMe:
	Death.Taunt:
	Death.Avoid:
		TNT1 A 0 {self.bSOLID = false;}
	stop;
	
	Pain.head:
	Pain.minorhead:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 { if( self.on_ceiling == true) { setstatelabel("PainCanFallFromCeiling");} }
		//TNT1 A 0 A_takeInventory("SKImp", 1);
		TROO H 6;
		TROO H 6 A_Pain();
	Goto see;
		
	Pain.ExplosiveImpact:
	Pain.Explosive:
	Pain.ExtremePunches:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
		//TNT1 A 0 A_takeInventory("SKImp", 1);
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		IZD4 KL 8;
	Goto FallingAfterImpact;
		
		
	Pain.Kick:
	Pain.ExtremePunches:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		IZD4 K 1 A_Pain();
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		ID11 E 1;// A_Chase (null,null)
		IZD4 K 1 A_facetarget();
		IZD4 K 6 ThrustThing(angle*256/360+128, 5, 0, 0);
		IZD4 L 8;
	Goto FallingAfterImpact;
		
		
	PainCanFallFromCeiling:
		TNT1 A 0 {self.bNOGRAVITY = false; self.bTHRUSPECIES = false; self.bCEILINGHUGGER = false;}
		TNT1 A 0 { self.on_ceiling = false;}

	FallingAfterImpact:
		IZD4 L 1 A_GiveInventory ("FallingHeight", 1);
		TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim");
		TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim");
		IZD4 L 1 A_CheckFloor ("GetUp");
		TNT1 A 0 A_JumpIf(vel.z == 0, "GetUp");
	Loop;
		
	GetUp:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("LargeMassWaterImpact");
		TNT1 A 0 A_SpawnItem("SmallUnderwaterExplosion");
		TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim");
		TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim");
		TNT1 A 0 {self.bGHOST = true;}
		TNT1 A 0 {self.bNOPAIN = false;}
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 {self.bFORCEXYBILLBOARD = true;}
		TNT1 A 0 A_GiveInventory("ISDOWN", 1);
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 8, "FallingDie");
		IZD4 MMMMMMMM 5 A_JumpIf(vel.z < 0, "FallingAfterImpact");
		TNT1 A 0 {self.bSOLID = true;}
		TNT1 A 0 A_TakeInventory("ISDOWN", 1);
		TNT1 A 0 {self.bFORCEXYBILLBOARD = false;}
		TNT1 A 0 A_TakeInventory("FallingHeight", 100);
		TNT1 A 0 A_TakeInventory("ISDOWN", 1);
		IZD4 NO 7;
	Goto see;
		
		
	FallingDie:
		TNT1 A 0;
		TNT1 A 0 {self.bSHOOTABLE = false;}//
		TNT1 A 0 {self.bCOUNTKILL = false;}
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 30, "Death.Stomp");
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 20, "FallingSuperDeath");
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 6, "FallingDeath");
	FallingDeath:
	Death.FellFromALongFall:
		TNT1 A 0;
		TROO M 1;
		TNT1 A 1;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("DeadImp1");
		//TROO M -1
	stop;

	FallingSuperDeath:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
	Goto Death.ExplosiveImpact+1;
		
	PainHurt:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TROO H 1;
		TROO H 1 A_Pain();
	Goto see;

	Pain.Avoid:
		TNT1 A 0
		{
			int direct = randompick(90, -90);//choose left or right
			self.vel.x = cos(self.angle + direct) * 10;
			self.vel.y = sin(self.angle + direct) * 10;
			self.vel.z = 5;
		}
		TROO NNNOOO 2 A_FaceTarget();
	Goto Missile+26;

		
	Pain.BlackHole:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		IZD4 K 1 A_Pain();
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,6,0,1);
		IZD4 K 1 A_facetarget();
		IZD4 K 6 ThrustThing(angle*256/360+128, 5, 0, 0);
		IZD4 L 8;
	Goto FallingAfterImpact;
		
	Death.Shotgun:
		TNT1 A 0 {self.bSLIDESONWALLS = false;}
		TNT1 A 0 A_Jump(42, "Death.Shotgunontheface");
		TNT1 A 0 A_JumpIfCloser(80, "Death.Blast");
		TNT1 A 0 A_JumpIfCloser(320, "Death.Shotgunontheface");
	Goto Death;
		
	Death.Shotgunontheface:
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Jump(128, "DeathJump");
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 A_Jump(32, "Death.ARm");
		TNT1 A 0 A_Jump(96, "DeathNoGuts");
		TNT1 A 0 A_Jump(128, "DeathShotgunontheface2");
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_Pain();
		TROO H 1 A_FaceTarget();
		TNT1 A 0 A_Recoil(13);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		TNT1 A 0 A_Scream();
		TNT1 A 0 a_spawnprojectile ("MuchBlood2", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 35, 0, random (0, 360), 2, random (0, 160));
		TR06 ABCDE 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TR06 FGHIJK 4 A_JumpIf((vel.Y == 0), "DSFStop");
	Goto DSFStop+1;
		
	DSFStop:
		//TNT1 A 0 A_SpawnItem("Ploft3");
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 a_spawnprojectile ("SuperWallRedBlood", 2, 0, random (170, 190), 2, random (0, 0));
		TNT1 A 0 A_SpawnItem ("DeadImpTR06K");
	stop;

	DeathShotgunontheface2:
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_Pain();
		TROO H 1 A_FaceTarget();
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_Recoil(13);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		TNT1 A 0 a_spawnprojectile ("MuchBlood2", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 35, 0, random (0, 360), 2, random (0, 160));
		TR06 LMNO 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TR06 QRSTU 4 A_JumpIf((vel.Y == 0), "DSFStop2");
	Goto DSFStop2+1;
		
	DSFStop2:
		//TNT1 A 0 A_SpawnItem("Ploft3");
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 a_spawnprojectile ("SuperWallRedBlood", 2, 0, random (170, 190), 2, random (0, 0));
		TNT1 A 0 A_SpawnItem ("DeadImpTR06V");
	stop;	Death.MinorLeg:
		TNT1 A 0;
		TNT1 A 0 A_Jump(48, "Death.Leg");
	Goto Death+5;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false; self.bTHRUSPECIES = false; self.bCEILINGHUGGER = false;}
		TNT1 A 0 {if(self.ceiling_jump == true ) { setstatelabel("DeathJump");} }
		TNT1 A 0 A_Jump(32, "Death.Arm");
		TNT1 A 0 A_Jump(24,"DeathNoGuts");
		TNT1 A 0 A_Jump(32,"Death20alt");
		TNT1 A 0 A_Jump(128, "DeathMirror");
		TR97 A 8;
		TR97 B 8 A_Scream();
		TR97 C 6;
		TR97 D 6 A_NoBlocking();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadImp1");
	stop;

	Death.Down:
	Death.Trample:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Stop();
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 2, 0, random (0, 360), 2, random (0, 40));
		ID11 DC 6;
		TNT1 A 0 A_SpawnItem("DeadImp1");
	stop;		
	Death.Incinerate:
		TNT1 A 0;
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_Playsound("MELT");
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAAA 0 a_spawnprojectile ("ExplosionParticle", 32, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAA 0 a_spawnprojectile ("ExplosionParticle", 32, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,32,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-15, 15), random (-15, 15));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece2", random (-35, 35), random (-35, 35));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random (-45, 45), random (-45, 35));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile ("Ashes1", 28, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile ("Ashes2", 40, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),32,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB AAAAA 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionParticle", 36, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),28,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB BBBBB 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionParticle", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),24,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB CCCCC 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionParticle", 28, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Playsound("SZZLL", 3);
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),20,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB DDDDD 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionParticle", 20, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),16,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB EEEEE 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionParticle", 12, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),12,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB FFFFF 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionParticle", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		TNT1 A 0 A_SpawnItem("BarrelExplosionSmokeColumn");
		T6SB GGGG 2 BRIGHT Light("IncinerationGlow");
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB HHIIHHIIHHIIHHII 2 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("PlasmaSmoke", 14, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB HHIIHHIIHHIIHHII 2 Light("IncinerationGlow") a_spawnprojectile ("PlasmaSmoke", 14, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB HHIIHHIIHHIIHHII 2;
		T6SB JJJJJJJ 12 a_spawnprojectile ("PlasmaSmoke", 14, 0, random (0, 360), 2, random (0, 160));
		T6SB J -1;
	stop;		
	Death.fire:
	Death.Flames:
	Death.Burn:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		//TNT1 A 0 A_JumpIfIntargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItemEx("BurningImpRunning",0,0,0,0,0,0,0,288);
	stop;		
		
	Death20alt:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TROD ABCD 6;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItemEx ("ImpDyingOfBloodLoss", 0,0,7,0,0,0,0,SXF_NOCHECKPOSITION,0);
	stop;		
		
		
	Death.Arm:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 a_spawnprojectile ("XDeathImpArm", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Jump(110, "Arm2");
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TR08 A 8 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		//TNT1 A 0 A_SpawnItem ("DyingImpNoArm", 2);
	stop;		
	Arm2:
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		T408 A 8 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		//TNT1 A 0 A_SpawnItem ("DyingImpNoArm2", 2);
	stop;		
	Death.Leg:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false; self.bTHRUSPECIES = false; self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Jump(64, "DeathLeg2");
		TNT1 A 0 {if( self.ceiling_jump == true ) { setstatelabel("Death.LegInTheAir");} }
		TNT1 A 0 a_spawnprojectile ("XDeathImpLeg", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TR09 A 9;
		TR09 A 3 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TR09 B 3 A_Scream();
		TR09 C 3 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem ("DyingImpNoLeg", 5);
	stop;		
	DeathLeg2:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Fall();
		TNT1 A 0 a_spawnprojectile ("XDeathImpLeg", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		//TNT1 A 0 A_SpawnItem("ImpSaciLol");
	stop;		
		
		
	DeathJump:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Stop();
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 {self.bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil (10);
		ID11 A 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		ID11 A 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		ID11 B 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		ID11 B 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		ID11 C 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		ID11 C 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		ID11 D 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		ID11 D 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadImp1");
	stop;		
	stop;	TakeASit:
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		ID11 B 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItemEx("DeadImp_Slumped", 10);
	stop;		
		
	Death.Nailgun:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 {self.bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,random(22,30),0,1);
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil (30);
		ID11 A 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		ID11 A 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		ID11 B 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		ID11 B 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		ID11 C 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		ID11 C 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		ID11 D 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		ID11 D 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadImp1");
	stop;	PinToWall:
		TNT1 A 0 a_spawnprojectile ("MuchBlood2", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_PlaySound("Weapons/NailHitBleed", 6);
		PIN6 A 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItemEx("DeadImp_Pinned", 10, 0, 10);
	stop;		
		
	Death.Melee:
		//TNT1 A 0 A_JumpIfInventory ("SKImp", 1, "StealthKill");
	Death.Kick: 
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil (8);
		ID30 ABCD 8;
		TNT1 A 1 A_SpawnItem ("DeadImp1MeleeDeath", 5);
	stop;		
		

	HeadExploder:
		TNT1 A 0;
		TNT1 A 0 A_Jump(72, "Death.HeadExplode");
	Goto Death.HeadMinor;
		
	Death.head:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		//TNT1 A 0 A_JumpIfIntargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		//TNT1 A 0 A_JumpIfIntargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
		//TNT1 A 0 A_JumpIfIntargetInventory("HasCutingWeapon", 1, "Death.Decaptate");
		TNT1 A 0 A_JumpIfHealthLower(-50, "Death.HeadExplode");
		//TNT1 A 0 A_JumpIfIntargetInventory("RandomHeadExploder", 1, "HeadExploder");
	Goto Death.HeadMinor;
		
	Death.HeadMinor:
		TNT1 A 0;
		TNT1 A 0 A_Playsound("MinorHeadshot", 0);
		TNT1 AA 0 a_spawnprojectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains3", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains6", 50, 0, random (0, 360), 2, random (0, 160));
		//TNT1 A 0 a_spawnprojectile ("Brains7", 50, 0, random (0, 360), 2, random (0, 160))
		TNT1 AA 0 a_spawnprojectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AA 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("BrainBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Jump(150, "MinorHead1", "MinorHead2");
		TROH K 9 A_NoBlocking();
		TROH L 9 A_Scream();
		TROH M 8;
		TROH N 8;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DeadImp_MinorHeadDeadFront");
	stop;		
	MinorHead1:
		TNT1 A 0 a_spawnprojectile ("Brains2", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains5", 50, 0, random (0, 360), 2, random (0, 160));
		T6SW A 8 A_NoBlocking();
		T6SW B 8 A_XScream();
		T6SW C 8;
		T6SW DDD 2 a_spawnprojectile ("Brutal_LiquidBlood2", 25, 0, random (0, 360), 2, random (60, 120));
		T6SW E 2 A_Scream();
		T6SW EEEDDD 2 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		T6SW F 6;
		TNT1 A 0 A_SpawnItem ("DeadImpT6SWG");
	stop;		
	MinorHead2:
		TNT1 A 0 a_spawnprojectile ("Brains2", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains5", 50, 0, random (0, 360), 2, random (0, 160));
		T6SW H 8 A_NoBlocking();
		T6SW I 8 A_XScream();
		T6SW J 8;
		T6SW KKK 2 a_spawnprojectile ("Brutal_LiquidBlood2", 25, 0, random (0, 360), 2, random (60, 120));
		T6SW L 2 A_Scream();
		T6SW LLLKKK 2 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		T6SW M 6;
		TNT1 A 0 A_SpawnItem ("DeadImpT6SWn");
	stop;		
	Death.headExplode:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 50);
		TNT1 A 0 A_Jump(120, "HeadExplode2");
		TROH AAAA 2 a_spawnprojectile ("Brutal_LiquidBlood2", 50, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_NoBlocking();
		TROH BBBB 2 a_spawnprojectile ("Brutal_LiquidBlood2", 40, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_Jump(32, "Deathchickenhead");
		TROH CCCCCCCC 2 a_spawnprojectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (60, 120));
		TROH DDD 2 a_spawnprojectile ("Brutal_LiquidBlood2", 20, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TROH EEEEEEEEEEEEEEEEEEEEEEEEEEEEE 2 a_spawnprojectile ("Brutal_LiquidBlood2", 15, 0, random (0, 360), 2, random (15, 40));
		TNT1 A 0 A_SpawnItem ("DeadImp_NoHead");
	stop;		
	HeadExplode2:
		TR0H AAAA 2 a_spawnprojectile ("Brutal_LiquidBlood2", 50, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_NoBlocking();
		TR0H BBBB 2 a_spawnprojectile ("Brutal_LiquidBlood2", 40, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_Jump(32, "Deathchickenhead");
		TR0H CCCCCCCC 2 a_spawnprojectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (60, 120));
		TR0H DDD 2 a_spawnprojectile ("Brutal_LiquidBlood2", 20, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TR0H EEEEEEEEEEEEEEEEEEEEEEEEEEEEE 2 a_spawnprojectile ("Brutal_LiquidBlood2", 15, 0, random (0, 360), 2, random (15, 40));
		TNT1 A 0 A_SpawnItem ("DeadImpTR0HE");
	stop;		
	Deathchickenhead:
		
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TROH FFFGGGHHHIII 2 a_spawnprojectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (10, 90));
		
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TROH FFFGGGHHHIII 2 a_spawnprojectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (10, 90));
		
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TROH FFFGGGHHHIII 2 a_spawnprojectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (10, 90));
		
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TROH FFFGGGHHHIII 2 a_spawnprojectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (10, 90));
		
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TROH FFFGGGHHHIII 2 a_spawnprojectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (10, 90));
		
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TROH FFFGGGHHHIII 2 a_spawnprojectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (10, 90));

		TROH CCCCCCCC 2 a_spawnprojectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (60, 120));
		TROH DDD 2 a_spawnprojectile ("Brutal_LiquidBlood2", 20, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TROH EEEEEEEEEEEEEEEEEEEEEEEEEEEEE 2 a_spawnprojectile ("Brutal_LiquidBlood2", 15, 0, random (0, 360), 2, random (15, 40));
		TNT1 A 0 A_SpawnItem ("DeadImp_NoHead");
	stop;		
		
		
	DeathMirror:
		TROO V 9;
		TROO W 9 A_Scream();
		TROO X 8 A_NoBlocking();
		TROO Y 8;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DeadImpTROOY");
	stop;		
	Death.decaptate:
		TNT1 AAAAAAAAA 0 a_spawnprojectile ("Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 a_spawnprojectile ("XDeathImpHeadBeheaded", 50, 0, random (0, 360), 2, random (40, 90));
		TROH A 9;
		TROH B 9 A_XScream();
		TROH C 8 A_NoBlocking();
		TROH DE 8;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DeadImp_NoHead");
	stop;		
	Death.cut:
	Death.HKFT:
	Death.Saw:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Jump(48, "Death.Arm", "Death");
		TNT1 A 0 A_Jump(32,"DeathNoGuts");
	Goto Death.Tear;
		
		
		
		
		
	Death.cutless:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
		TNT1 A 0 A_Jump(42,"DeathNoGuts");
		TNT1 A 0 A_Jump(16, "Death");
		TNT1 A 0 A_Jump(16, "Death.LegMassacre");
	Goto Death.Minigun;
		
	Death.Minigun:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Scream();
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 A_Jump(128, "DeathMinigun2");
		//TNT1 A 0 A_SpawnItem ("BrutalizedImp1", 1);
	stop;
	
	DeathMinigun2:
		TNT1 A 0;
		//TNT1 A 0 A_SpawnItem ("BrutalizedImp4", 1);
	stop;
	
	Death.LegMassacre:
		TNT1 A 0 a_spawnprojectile ("XDeathImpLeg", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TR09 A 8 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TR09 B 8 A_Scream();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem ("ImpBrutalizedWithNoLeg");
	stop;		

	Death.Tear:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Jump(128, "Tear2", "Tear3", "Tear4");
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TROG A 2 a_spawnprojectile ("RipImp", 0, 0, random (0, 360), 2, random (0, 160));
		TROG AAA 4 A_SpawnItem ("Big_Blood", 0, 30);
		TROG BCDEFGH 8;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 1 A_SpawnItem ("DeadImp_Half", 5);
	stop;		
	Tear2:
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		T5SW A 3;
		T5SW A 1 A_PlaySound("misc/xdeath4f", 9);
		T5SW BBB 2 a_spawnprojectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		T5SW CCC 2 a_spawnprojectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath2", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath5", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("xdeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("xdeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("LivingHeart", 32, 0, random (170, 190), 2, random (0, 40));
		T5SW DDD 2 a_spawnprojectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		T5SW EEE 2 a_spawnprojectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		T5SW FFF 2 a_spawnprojectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		T5SW GGG 2 a_spawnprojectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DeadImpT5SWG");
	stop;

	Tear3:
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		IXD1 ABC 4 a_spawnprojectile ("MuchBlood", 45, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("xdeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("xdeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("LivingHeart", 32, 0, random (170, 190), 2, random (0, 40));
		IXD1 DDDDDDDDDD 1 a_spawnprojectile ("Brutal_LiquidBlood2", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("RipImp", 0, 0, random (0, 360), 2, random (0, 160));
		IXD1 EEEEEEEEEE 1 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (0, 160));
		IXD1 FFFFFFFFFF 1 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 8, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 8, 0, random (150, 210), 2, random (0, 40));
		IXD1 GGGGGGGG 1 a_spawnprojectile ("Brutal_LiquidBlood2", 9, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		IXD1 HHHHHHHHHHHHH 1 a_spawnprojectile ("Brutal_LiquidBlood2", 6, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DeadImpIXD1H");
	stop;

	Tear4:
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		TNT1 AA 0 a_spawnprojectile ("xdeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("LivingHeart", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("MuchBlood", 45, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 a_spawnprojectile ("RipImp", 0, 0, random (0, 360), 2, random (0, 160));
		IXD4 AAAABBBBCCCCDDDD 1 a_spawnprojectile ("Brutal_LiquidBlood2", 35, 0, random (0, 360), 2, random (0, 160));
		
		IXD4 D 2 a_spawnprojectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 E 2 a_spawnprojectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 F 2 a_spawnprojectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 E 2 a_spawnprojectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 D 2 a_spawnprojectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 E 2 a_spawnprojectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 F 2 a_spawnprojectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 G 2 a_spawnprojectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 F 2 a_spawnprojectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 36, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 G 2 a_spawnprojectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 E 2 a_spawnprojectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 F 2 a_spawnprojectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 G 2 a_spawnprojectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 E 2 a_spawnprojectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 F 2 a_spawnprojectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 G 2 a_spawnprojectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		IXD4 HHHH 1 a_spawnprojectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		IXD4 IIIII 1 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (0, 160));
		IXD4 JJJJJ 1 a_spawnprojectile ("Brutal_LiquidBlood2", 22, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		IXD4 KKKKKKKKKK 1 a_spawnprojectile ("Brutal_LiquidBlood2", 19, 0, random (0, 360), 2, random (0, 160));
		IXD4 LLLLLL 1 a_spawnprojectile ("Brutal_LiquidBlood2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DeadImpIXD4L");
	stop;

	DeathNoGuts:
		TNT1 AAAAA 0;
		TNT1 A 0 A_Jump(120, "DeathNoGuts2");
		TNT1 AA 0 a_spawnprojectile ("Instestin", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 30, 0, random (0, 360), 2, random (0, 160));
		IMPC A 8 A_Scream();
		IMPC B 8 A_NoBlocking();
		IMPC C 8;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem ("DyingImp", 2);
	stop;	DeathNoGuts2:
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 28, 0, random (150, 210), 2, random (0, 40));
		I9PC C 8;
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 30, 0, random (0, 360), 2, random (0, 160));
		I9PC D 8 A_Scream();
		I9PC E 8 A_NoBlocking();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem ("DyingImp2", 2);
	stop;

	Death.Plasma: Death.Plasma2:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Jump(96, "OtherPlasmaDeath");
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_PlaySound("plasmaflesh");
		TNT1 AAAAAAAAA 0 a_spawnprojectile ("Ashes1", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAA 0 a_spawnprojectile ("Ashes2", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1Blue",random(-2,2),random(-2,2),18,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		TNT1 AAAA 0 a_spawnprojectile ("BluePlasmaFireNonStatic", 42, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAA 0 a_spawnprojectile ("BloodMistBig", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAA 0 a_spawnprojectile ("SuperGoreMistSmall", 32, 0, random (0, 360), 2, random (10, 90));
		TNT1 AAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (0, 360), 2, random (0, 180));
		PBR1 B 6 A_NoBlocking();
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1Blue",random(-2,2),random(-2,2),10,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		TNT1 A 0 A_SpawnItemEx ("DetectFloorCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItem("BarrelExplosionSmokeColumn");
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-15, 15), random (-15, 15));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece2", random (-35, 35), random (-35, 35));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random (-45, 45), random (-45, 35));
		PBR1 CCDD 3 a_spawnprojectile ("BluePlasmaFireNonStatic", 32, 0, random (0, 360), 2, random (0, 180));
		PBR1 EEFF 3;
		PBR1 GG 3;
		PBR1 H -1;
	Stop;
	
	OtherPlasmaDeath:
		IMPP A 6 A_PlaySound("plasmaflesh");
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("Ashes1", 33, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAA 0 a_spawnprojectile ("BluePlasmaFire", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("Ashes2", 31, 0, random (0, 360), 2, random (0, 180));
		IMPP B 6 A_NoBlocking();
		TNT1 AAAAAAA 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 a_spawnprojectile ("Brains1", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAA 0 a_spawnprojectile ("Brains7", 52, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile ("BrainBlood", 50, 0, random (0, 360), 2, random (0, 160));
		IMPP CDE 6;
		IMPP FFFFFFFFFFFFFFFFFFFFFFFFFFFFF 8 a_spawnprojectile ("PlasmaSmoke", 10, 0, random (0, 360), 2, random (0, 160));
		IMPP F -1;
	stop;
	
	Death.SuperPlasma:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		XBRN AA 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 AAAA 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
		
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedImpArm", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
		
		XBRN BB 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 A 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
		XBRN CC 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 AAAAA 0 a_spawnprojectile ("PlasmaParticleX", 48, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAA 0 a_spawnprojectile ("BigPlasmaParticleX", 42, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 0;
	Stop;
	
	Death.GreenFire:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAA 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
		EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("GreenFlameTrails", 50, 0, random (0, 360), 2, random (0, 360));
		XBRN AAAA 2 BRIGHT A_SpawnItem("GreenFlare",0,43);
	Stop;
	
	Death.Blast:
	Death.Railgun:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Jump(12, "Death.Arm");
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Jump(128, "Death.Blast2", "DeathBlast3");
		TNT1 A 0 A_XScream();
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathImpArm", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathImpHead", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		TR03 A 6 A_Stop();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TR03 BBBBBBBBBB 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (30, 60));
		TR03 CCC 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (10, 40));
		TR03 DD 3 a_spawnprojectile ("Brutal_LiquidBlood2", 6, 0, random (0, 360), 2, random (30, 60));
		TNT1 A 0 A_SpawnItem ("DeadImpTR03E");
	Stop;
	
	Death.Blast2:
		TNT1 A 0 A_XScream();
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathImpArm", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathImpHead", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		TR04 A 6 A_Stop();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TR04 BBBBBBBBBB 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (30, 60));
		TR04 CCC 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (10, 40));
		TR04 DD 3 a_spawnprojectile ("Brutal_LiquidBlood2", 6, 0, random (0, 360), 2, random (30, 60));
		TNT1 A 0 A_SpawnItem ("DeadImpTR04E");
	Stop;
	
	DeathBlast3:
		TNT1 A 0 A_xScream();
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("XDeath2", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TR04 F 6 A_Stop();
		TR04 G 2 A_Scream();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TR04 GGGG 2 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (30, 60));
		TR04 H 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (10, 40));
		TR04 I 3 a_spawnprojectile ("Brutal_LiquidBlood2", 6, 0, random (0, 360), 2, random (30, 60));
		TNT1 A 0 A_SpawnItem ("DeadImpTR04J");
	Stop;
	
	Death.SSG:
	Death.SuperPunch:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		IZD1 E 1 A_Pain();
		IZD1 E 1 A_FaceTarget();
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AAA 0 bright a_spawnprojectile ("SuperGoreSpawner", 35, 0, random (170, 190), 2, random (0, 40));
		//TNT1 A 0 a_spawnprojectile ("MeatDeath", 0, 0, random (0, 360), 2, random (0, 160))
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 AA 0 a_spawnprojectile ("XDeathImpArm", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathImpHead", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		IZD1 EEFFGH 6;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DeadImpJustLegsAreLeft");
	Stop;
	
	Death.Explosive:
		TNT1 A 1 A_FaceTarget();
		//TNT1 A 1 A_JumpIfInTargetInventory("RocketLauncherSelected", 1, "RocketMan");
		XDeath:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		//TNT1 A 0 A_JumpIfIntargetInventory("SSGSelected", 1, "Death.SSG");
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_FaceTarget();
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 42, 0, random (0, 190), 2, random (10, 60));
		TNT1 AAA 0 a_spawnprojectile ("XDeath3", 42, 0, random (0, 190), 2, random (10, 60));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 42, 0, random (0, 190), 2, random (10, 60));
		TNT1 A 0 a_spawnprojectile ("XDeath4", 42, 0, random (0, 190), 2, random (10, 60));
		TNT1 A 1 a_spawnprojectile ("ImpXDeath", 0, 0, random (0, 360), 2, random (0, 160));
	Stop;
	
	RocketMan:
//		TNT1 A 0 A_JumpIfCloser(800, "RocketImp");
	Goto XDeath;
	
	RocketImp:
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 1 a_spawnprojectile ("RocketImpVictim", 15, 0, 180, 2, 0);
	stop;
	
	Death.ExplosiveImpact:
	Death.ExtremePunches:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_XScream();
		TNT1 A 0 a_spawnprojectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 A_Jump(96,"Death.LandMine");
		
		TNT1 AAAA 0 a_spawnprojectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains3", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains6", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains7", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAA 0 a_spawnprojectile ("BrainBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile ("BloodMistLarge", 40, 0, random (0, 360), 2, random (20, 90));
		TNT1 A 0 a_spawnprojectile ("XDeathImpArm", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		ID17 AB 5;
		ID17 CDEF 5 A_CheckFloor ("Dead.ExplosiveImpact");
		ID17 EEEEEEEEEE 5 A_CheckFloor ("Dead.ExplosiveImpact");
		TNT1 A 0 A_SpawnItem ("DeadImpID17G");
	Stop;
	
	Dead.ExplosiveImpact:
		TNT1 A 0 A_Jump(128, "Dead.ExplosiveImpact2");
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem ("ThisImpGotFuckedHard");
		//TNT1 A 0 A_SpawnItem ("Ploft");
		TNT1 AAAA 0 A_SpawnItem ("Blood");
	Stop;
	
	Dead.ExplosiveImpact2:
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem ("ThisImpGotFuckedHard2");
		//TNT1 A 0 A_SpawnItem ("Ploft");
		TNT1 AAAA 0 A_SpawnItem ("Blood");
	Stop;
	
	
	Death.Landmine:
	Death.LandMine2:
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 ThrustThingZ(0,15,0,1);
		Death.LegInTheAir:
		TNT1 A 0 ThrustThingZ(0,35,0,1);
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAA 0 a_spawnprojectile ("BloodMistLarge", 40, 0, random (0, 360), 2, random (20, 90));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile ("BrainBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		
		ID13 A 1 A_Scream();
		ID17 HI 4;
		ID17 JKLMN 4 A_CheckFloor ("Dead.Landmine");
		ID17 NNNNNNNN 4 A_CheckFloor ("Dead.Landmine");
		TNT1 A 0 A_SpawnItem ("DeadImp_NoLeg");
	Stop;
	
	Dead.Landmine:
		TNT1 O 0 A_NoBlocking();
		TR09 E 1;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem ("Ploft");
		TNT1 AAAA 0 A_SpawnItem ("Blood");
		TNT1 A 0 A_SpawnItem ("DeadImp_NoLeg");
	Stop;
	
	Raise:
		TROO MLKJI 8;
	Goto See;
	
	Crush:
	Death.Stomp:
		TNT1 A 0;
		TNT1 A 0;//A_DamageSelf(1, "Stomp", DMSS_KILL)
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("Brutal_FlyingBloodTrail8", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAA 0 bright a_spawnprojectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AAAAAA 0 bright a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright a_spawnprojectile ("XDeath2", 55, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright a_spawnprojectile ("XDeath3", 55, 0, random (0, 360), 2, random (30, 180));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("CrushedRemains");
		TNT1 A 1 A_XScream();
		TNT1 A 1 A_NoBlocking();
	Stop;
	
	FatalityMarine:
		TNT1 A 0 A_SetInvulnerable();
		IPFP ABCD 4;
		TNT1 A 0 A_SpawnItemEx("FootStep5", 0, 0, 40, 0, 0);
		IPFP EE 6;
		IPFP F 8;
		TNT1 A 0 A_PlaySound("DSFDTHE");
		IPFP G 8;
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("PlayerFlyingBlood", 25, 0, random (0, 360), 2, random (0, 160));
		IPFP H 8;
		IPFP I 8;
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("PlayerFlyingBlood", 25, 0, random (0, 360), 2, random (0, 160));
		IPFP J 8;
		IPFP K 8;
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("PlayerFlyingBlood", 25, 0, random (0, 360), 2, random (0, 160));
		IPFP H 8;
		IPFP I 8;
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("PlayerFlyingBlood", 25, 0, random (0, 360), 2, random (0, 160));
		IPFP J 8;
		IPFP K 8;
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("PlayerFlyingBlood", 25, 0, random (0, 360), 2, random (0, 160));
		IPFP H 8;
		IPFP I 8;
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("PlayerFlyingBlood", 25, 0, random (0, 360), 2, random (0, 160));
		IPFP J 8;
		IPFP L 8;
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("PlayerFlyingBlood", 25, 0, random (0, 360), 2, random (0, 160));
		IPFP M 8;
		TNT1 A 0 a_spawnprojectile ("Instestin", 12, 0, random (0, 360), 2, random (0, 40));
		IPFP N 8;
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("PlayerFlyingBlood", 25, 0, random (0, 360), 2, random (0, 160));
		IPFP O 8;
		TNT1 A 0 a_spawnprojectile ("Instestin", 12, 0, random (0, 360), 2, random (0, 40));
		IPFP L 8;
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("PlayerFlyingBlood", 25, 0, random (0, 360), 2, random (0, 160));
		IPFP M 8;
		TNT1 A 0 a_spawnprojectile ("Instestin", 12, 0, random (0, 360), 2, random (0, 40));
		IPFP N 8;
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("PlayerFlyingBlood", 25, 0, random (0, 360), 2, random (0, 160));
		IPFP O 8;
		TNT1 A 0 a_spawnprojectile ("Instestin", 12, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_UnSetInvulnerable();
		//TNT1 A 0 A_SpawnItem ("MarineGotOwnedByImp", 1);
	Goto See;
	
	StealthKill:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfIntargetInventory("FistsSelected", 1, 1);
	Goto Death;
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("SKImp", 1);
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Fall();
		TNT1 A 1;
		TNT1 A 0 A_Die("Stealthy");
		TNT1 A 1;
	Stop;
	Death.Stealthy:
		TNT1 A 0;
	Stop;
	
	Swim:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Fall();
		//TNT1 A 0 A_SpawnItem("ImpFish");
	Stop;
	
	Death.Ice:
	Death.Freeze:
	Death.Frost:
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		//TNT1 A 0 A_SpawnItem("FrozenImp");
	Stop;
	
	Death.Massacre:
	Goto Death;

	Death.Shrink:
		TNT1 A 1 A_PlaySound("Shrink", 3);
/*		TNT1 A 0 A_SpawnItemEx ("ImpShrinkFX1", 0, 0,  5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("ImpShrinkFX2", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("ImpShrinkFX3", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("ImpShrinkFX4", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("ImpShrinkFX5", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("ImpShrinkFX6", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("ImpShrinkFX7", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("LilImp", 1);*/
	stop;
}

}

CLASS ImpAttack: actor
{ 
Default 
{
	Radius 10;
	Height 18;
	DamageType "Rip";
	Projectile;
	+RANDOMIZE;
	Damage 2;
	+FORCEXYBILLBOARD;
	+THRUGHOST;
	+BLOODSPLATTER;
	RenderStyle "Add";
	Alpha 0.6;
	HitObituary "$OB_IMPHIT";
	Obituary "$OB_IMPHIT";
	
	
	SeeSound "None";
	DeathSound "none";
	Decal "none";
	Speed 20;
	}
	States
	{
	Spawn:
	TNT1 A 4 BRIGHT;
	Stop;
	Death:
	TNT1 A 0 A_PlaySound("imp/melee");
	TNT1 A 0 BRIGHT;
	Stop;
}
}

CLASS ImpAttack2: ImpAttack { 
Default 
{
	+THRUGHOST;
	DamageType "ImpFatalityMarine";
	Damage 2;
	}
}

CLASS pb_imp_fireball : pb_projectile_base//DoomImpBall// Replaces DoomImpBall : ACTOR
{ 
Default
{
	DamageType "Burn";
	Radius 8;
	Height 4;
	Speed 16;
	FastSpeed 20;
	DamageFunction (random(15,20));
	PROJECTILE;
	+THRUGHOST;
	RenderStyle "Add";
	Alpha 1;
	SeeSound "ImpFire";
	DeathSound "ImpFireImpact";
	Decal "Scorch";
	Scale 0.25;
}
States
{
	Spawn:
	TNT1 A 0;
	TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
	TNT1 A 0;//A_JumpIf(ACS_NamedExecuteWithResult("PerformanceMode")==1,"SpawnCheap")
	//TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
	Spawn1:
	TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "SpawnCheap");
	TNT1 A 0 A_Playsound("SMLFRBL", 1, 1, 1);
	Fly:
	TNT1 A 0 A_SpawnItem ("CoolAndNewFlameTrails", 0, random( -2, 2));
	BLHD C 1 BRIGHT A_SpawnItem("FireballFlare",2,0);
	TNT1 A 0 a_spawnprojectile ("OldschoolRocketSmokeTrail2", 2, 0, random (160, 210), 2, random (-30, 30));
	TNT1 A 0 A_SpawnItem ("CoolAndNewFlameTrails");
	BLHD D 1 BRIGHT A_SpawnItem("FireballFlare",0,0);
	Loop;

	SpawnCheap:
	TNT1 A 0;//A_SpawnItem ("CoolAndNewFlameTrails")
	BLHD A 1 BRIGHT A_SpawnItem("FireballFlare",0,0);
	TNT1 A 0;//A_SpawnItem ("CoolAndNewFlameTrails")
	BLHD B 1 BRIGHT A_SpawnItem("FireballFlare",0,0);
	Loop;
	
	SpawnUnderwater:
	BLHD A 1 BRIGHT A_SpawnItem("FireballFlare",0,0);
	TNT1 A 0 a_spawnprojectile ("BUBULZ", 0, 0, random (0, 360), 2, random (0, 180));
	BLHD B 1 BRIGHT A_SpawnItem("FireballFlare",0,0);
	TNT1 A 0 a_spawnprojectile ("BUBULZ", 0, 0, random (0, 360), 2, random (0, 180));
	Goto Spawn1;
	
	Death:
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 A_StopSound(1);
		tnt1 a 0 a_spawnitem("ShrapnelParticle");
		TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "DeathCheap");
		TNT1 A 0 A_SpawnItemEx ("SmallUnderwaterExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		EXPL AAAAAA 0 a_spawnprojectile ("FireBallExplosionFlames", 1, 0, random (0, 360), 2, random (0, 360));
		//FRFX CDEFGHIJKLMNOP 1 BRIGHT A_SpawnItem("RedFlare",0,0)
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random (-5, 5), random (-5, 5));
		TNT1 A 0 A_SpawnItemEx ("DetectFloorCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("DetectCeilCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAAAAAAAA 0 a_spawnprojectile ("ExplosionParticle", 0, 0, random (0, 180), 2, random (0, 180));
		TNT1 AAAA 19 a_spawnprojectile ("PlasmaSmoke", 1, 0, random (0, 360), 2, random (0, 160));
		Stop;
		XDeath:
		TNT1 A 0 A_StopSound(1);
		TNT1 A 0 {self.bSHOOTABLE = false;}
		tnt1 a 0 a_spawnitem("ShrapnelParticle");
		TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "DeathCheap");
		TNT1 AAAAAAAAAA 0 a_spawnprojectile ("ExplosionParticle", 0, 0, random (0, 180), 2, random (0, 180));
		TNT1 A 0 A_SpawnItemEx ("SmallUnderwaterExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		EXPL AAAAAA 0 a_spawnprojectile ("FireBallExplosionFlames", 1, 0, random (0, 360), 2, random (0, 360));
		EXPL AAA 0 a_spawnprojectile ("PlasmaSmoke", 1, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random (-15, 15), random (-15, 15));
		//FRFX CDEFGHIJKLMNOP 1 BRIGHT A_SpawnItem("RedFlare",0,0)
	Stop;

	DeathCheap:
		TNT1 A 0 A_StopSound(1);
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 AAA 0 a_spawnprojectile ("ExplosionParticle", 0, 0, random (0, 180), 2, random (0, 180));
		TNT1 A 0 A_SpawnItemEx ("SmallUnderwaterExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		EXPL AAAA 0 a_spawnprojectile ("FireBallExplosionFlames", 1, 0, random (0, 360), 2, random (0, 360));
	Stop;
}
}

CLASS FireBallWeapon: pb_imp_fireball { 
Default 
{
	-THRUGHOST;
	}
}


CLASS ImpTorso : ACTOR { 
Default 
{
	Radius 0;
	Height 16;
	Scale 1.1;
	Mass 20;
	Health 50;
	+SHOOTABLE;
	-SOLID;
	+NOTELEPORT;
	+FLOORCLIP;
	+MOVEWITHSECTOR;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	}
    States
    {
	Spawn:
	BLUD C 0 A_Recoil (3);
	BLUD C 0 ThrustThing (random(0,255),random(1,5));
	BLUD C 0 ThrustThingZ (0,random(0,50),random(0,1),0);
	TNT1 A 0 A_SetInvulnerable();
	GORX B 10;
	TNT1 A 0 A_UnSetInvulnerable();
	Goto Dead;
	
	Dead:
	GORX B 10;
	Loop;
	Death:
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 0, 0, random (0, 180), 2, random (0, 180));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 0, 0, random (0, 180), 2, random (0, 180));
	TNT1 A 0;
	Stop;
Death.Plasma: Death.Plasma2:
	TNT1 A 0;
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	TNT1 AAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
	EXPL AAA 0 a_spawnprojectile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
	TNT1 A 0;
	Stop;
	
}
}










CLASS DeadImp1: pb_blood_and_gore_base// Replaces DeadDoomImp
{ 
Default
{
    Radius 12;
    Height 12;
    +SHOOTABLE;
    +NOTELEPORT;
    +MOVEWITHSECTOR;
    +CORPSE;
	-SOLID;
	+FLOORCLIP;
	+thrUACTORS;
	+SHOOTABLE;
	damagefactor "Crush", 50.0;
	Mass 1000;
	Health 100;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	damagefactor "Melee", 10.0;
	damagefactor "Fatality", 10.0;
	damagefactor "Kick", 10.0;
	damagefactor "ExplosiveImpact", 10.0;
	}
	States
	{
	Spawn:
		TROO MMM 100;
		TROO MMM 2 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
		TROO M -1;
	stop;	Raise:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("TeleportFog");
		//TNT1 A 0 A_SpawnItem ("Imp");
	stop;	Death:
		TNT1 A 0 A_Jump (128, "Death2");
		TNT1 A 0 a_spawnprojectile ("XDeathImpArm", 5, 0, random (0, 360), 2, random (0, 160));
		POS3 A 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 1 A_SpawnItem ("DeadImp_NoArm", 5);
	stop;	Death2:
		TNT1 A 0 a_spawnprojectile ("XDeathImpLeg", 5, 0, random (0, 360), 2, random (0, 160));
		SPOS A 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 1 A_SpawnItem ("DeadImp_NoLeg", 5);
	stop;	Death.CutLess:
	Death.Cut:
		TNT1 A 1 A_SpawnItem ("DeadImp_Half", 5);
		TNT1 A 0 a_spawnprojectile ("RipImp", 0, 0, random (0, 360), 2, random (0, 160));
	stop;
	
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
		EXPL AAA 0 a_spawnprojectile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 0;
	Stop;

	XDeath:
		TNT1 A 0 A_SpawnItem("GibsZ");
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	Death.ExplosiveImpact:
	Death.ExtremePunches:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,15,0,1);
		TNT1 A 0 A_FaceTarget();
		ID11 ABC 6;
		TNT1 A 1 A_SpawnItem ("DeadImp1", 5);
	Stop;}}

CLASS DeadImp_NoArm: DeadImp1 { 
Default {Health 200;}
States
{
	Spawn:
		TR08 EEE 100;
		TRO8 E 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
		TR08 E -1;
	Stop   ;

	Death.Cut:        Death.Cutless:	        Death:
		TNT1 A 0 A_SpawnItem("GibsZ");
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	Death.ExplosiveImpact:
	Death.ExtremePunches:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,15,0,1);
		TNT1 A 0 A_FaceTarget();
		IZD2 B 7;
		//TNT1 A 1 A_SpawnItem ("BrutalizedImpStop", 5);
	stop;
}}

CLASS DeadImp_NoArmNoHead: DeadImp_NoArm { 
Default {Health 200;} States{Spawn:
	TR08 GGG 125 ;
	TR08 GGGG 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
        TR08 G -1;
        Stop   ; 
       Death.Cut:        Death.Cutless:	        Death:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
	 TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;}}
	
CLASS DeadImp_NoArm2: DeadImp1 { 
Default {Health 200;} States{Spawn:
	T408 EEE 110;
	T408 EEEE 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
        T408 E -1;
        Stop;
       Death.Cut:        Death.Cutless:	        Death:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
		 TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;
    Death.Fatality:
    Death.Melee:
    Death.Kick:
	Death.ExplosiveImpact:
	Death.ExtremePunches:
         TNT1 A 0;
         TNT1 A 0;
        TNT1 A 0 ThrustThingZ(0,15,0,1);
        TNT1 A 0 A_FaceTarget();
         IZD2 B 7;
         //TNT1 A 1 A_SpawnItem ("BrutalizedImpStop", 5);
	stop; }}

CLASS DeadImp_NoArmNoHead2: DeadImp_NoArm { 
Default {Health 200;} States{Spawn:
	T408 GGG 105;
	T408 GGGG 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
        T408 G -1;
        Stop   ; 
       Death.Cut:        Death.Cutless:	        Death:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
	 TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;}}

CLASS DeadImp_NoLeg: DeadImp1 { 
Default {Health 200;}
States
{
Spawn:
	TR09 E 145;
	TR09 EEEE 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
        TR09 E -1;
        Stop;
       Death.Cut:        Death.Cutless:	        Death:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 Stop;
    Death.Fatality:
    Death.Melee:
    Death.Kick:
	Death.ExplosiveImpact:
	Death.ExtremePunches:
         TNT1 A 0;
         TNT1 A 0;
        TNT1 A 0 ThrustThingZ(0,15,0,1);
        TNT1 A 0 A_FaceTarget();
         ID11 ABC 6;
         TNT1 A 1 A_SpawnItem ("DeadImp_NoLeg", 5);
	Stop;
	}}


CLASS DeadImp_NoHead: DeadImp1 { 
Default {Health 200;} States{Spawn:
	TROH EEE 109;
	TROH E 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
        TROH E -1;
        Stop	;     	
        Death:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
         Stop;}}

CLASS DeadImp_MinorHeadDeadFront: DeadImp1 { 
Default 

{Health 200;} States{Spawn:
	TROH OOO 120;
	TROH OO 1;
        TROH O -1;
        Stop;}}
	 
CLASS DeadImpMinorHeadShot: DeadImp1 { 
Default 
{Health 200;} States{Spawn:
	TROO YYYY 145;
	TROO YYY 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
        TROO Y -1;
        Stop	;     	
        Death:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
         Stop;}}

CLASS DeadImp_Half: DeadImp1 { 
Default {Health 200;} States{Spawn:
        TROG H -1;
        Stop;
        Death.Cut:
        Death.Cutless:	
        Death:
    Death.Fatality:
    Death.Melee:
    Death.Kick:
	Death.ExplosiveImpact:
	Death.ExtremePunches:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
          Stop;}}
	  
CLASS impfacesorapedomgthisiscruel: DeadImp_Half { 
Default 
{Health 200;} States{Spawn:
	FTCI KKK 105;
	FTCI KKKK 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
        FTCI K -1;
        Stop;
  }}	  


CLASS StompedImp: DeadImp_NoHead { 
Default 
{Health 200;} States{Spawn:
        FTYI Z -1;
        Stop;
		Death:
TNT1 A 0 A_SpawnItem("GibsZ");
TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
          Stop;}}



CLASS DeadImp_NoStomach: DeadImp1 { 
Default 
{Health 200;} States{Spawn:
	IMPC III 133;
	IMPC IIII 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
	    IMPC I -1;
        Stop;
       Death.Cut:        Death.Cutless:	        Death:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;}}
	
CLASS DeadImp_NoStomach2: DeadImp1 { 
Default 
{Health 200;} States{Spawn:
	I9PC III 135;
	I9PC II 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
	    I9PC I -1;
        Stop   ; 
       Death.Cut:        Death.Cutless:	        Death:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;}}



CLASS DeadImp_NoStomachNoHead: DeadImp1 { 
Default 
{Health 200;} States{Spawn:
	IMPC LLL 160;
	IMPC L 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
	    IMPC L -1;
        Stop;
       Death.Cut:        Death.Cutless:	        Death:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
			 TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;}}
	
CLASS DeadImp_NoStomachNoHead2: DeadImp1 { 
Default 
{Health 200;} States{Spawn:
	I9PC LLLL 109;
	I9PC LL 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
	    I9PC L -1;
        Stop ;
		
       Death.Cut:        Death.Cutless:	        Death:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
			 TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;}}
	
	
CLASS DeadImp_BaronFatality: DeadImp1 { 
Default 
{Health 200;} States{Spawn:
	3HF2 KKK 100;
	3HF2 KKKK 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
	    3HF2 K -1;
        Stop;
}

}	


CLASS ImpMessyCorpse: DeadMarine { 
Default 

{Health 200;} States{Spawn:
	FTBI HHH 100;
	FTBI HH 2 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
	    FTBI H -1;
        Stop   ; 
       Death.Cut:        Death.Cutless:	        Death:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
	 TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;}}
	
	
CLASS DeadImpBloodLoss: DeadMarine { 
Default 

{Health 200;} States{Spawn:
	TROD JJJ 45;
	TROD JJ 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
	    TROD J -1;
        Stop;
       Death.Cut:        Death.Cutless:	        Death:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
	 TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;}}	

CLASS DeadImpJustLegsAreLeft: DeadImp_Half { 
Default 
{Health 300;} States{Spawn:
        IZD1 H -1;
        Stop;}}

CLASS DeadImp_Slumped: pb_dismembered_monster_base { 
Default 
{
	+NOPAIN
	Health 200;
	DamageFactor "Head", 15.0;
	Height 22;
	Radius 8;
}

States
{	
	Spawn:
	TNT1 A 0;
	TNT1 A 0 A_Recoil(6);
	BR94 A 6;
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	BR94 A 16;
	Loop ;
	LayDown:
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_SpawnItem("DeadImp1");
	Stop;
	XDeath:
	Death.Explosives:
	Death.ExplosiveImpact:
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_SpawnItem("ZombieXDeath");
	Stop;
	
	Death.Head:
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_SpawnItemEx("ImpHeadExplode", 0, 0, 22);
	TNT1 A 0 A_SpawnItem("DeadImp_Slumped_NoHead");
	Stop;
	
	Death:
	TNT1 A 0 A_NoBlocking();
	TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
	TNT1 AAA 0 a_spawnprojectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
	TNT1 AA 0 a_spawnprojectile ("XDeathImpArm", 40, 0, random (0, 360), 2, random (30, 90));
	TNT1 A 0 A_SpawnItemEx("ImpHeadExplode", 0, 0, 22);
	TNT1 A 0 A_SpawnItem("DeadImpJustLegsAreLeft");
	Stop;
}}
	
	
CLASS DeadImp_Slumped_NoHead: pb_dismembered_monster_base { 
Default 
	{
	+NOPAIN;
	Height 22;
	}
States{Spawn:
	TNT1 A 0;
	BR94 B 100;
	Loop ;
	XDeath:
	Death.Explosives:
	Death.ExplosiveImpact:
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_SpawnItem("ZombieXDeath");
	Stop;
	Death:
	TNT1 A 0 A_NoBlocking();
	TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
	TNT1 AAA 0 a_spawnprojectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
	TNT1 AA 0 a_spawnprojectile ("XDeathImpArm", 40, 0, random (0, 360), 2, random (30, 90));
	TNT1 A 0 A_SpawnItem("DeadImpJustLegsAreLeft");
	Stop;
}}
	
CLASS RocketImpVictim : ACTOR
{ 
Default 
{
	Radius 10;
	Height 8;
	Projectile;
	Speed 20;
	Damage 35;
	DamageType "ExplosiveImpact";
	MeleeDamage 0;
	Gravity 0.00;
	-NOGRAVITY;
	+EXTREMEDEATH;
	+BLOODSPLATTER;
	+FORCEXYBILLBOARD;
	+ALLOWPARTICLES;
	SeeSound "weapons/RLL";
	DeathSound "Explosion";
	Obituary "$OB_MPROCKET";
	Decal "Scorch";
}

States
	{
	Spawn:
		T0KT AB 4 Bright A_FaceTarget();
		TNT1 A 0 A_PlaySound("weapons/rocketloop",6,1,1);
		TNT1 A 0 A_PlaySound("imp/pain",7,2,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
		TNT1 A 0 A_SpawnItem("RocketFlare",-20,0);
		TNT1 A 0 a_spawnprojectile ("brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("RocketSmokeTrail52Moving", 2, 0, random (160, 210), 2, random (-30, 30));
		TNT1 A 0 A_SpawnItem ("RocketSmokeTrail52");
	Loop;
	
	SpawnUnderwater:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 A_SpawnItem("RocketFlare",-20,0);
		TNT1 A 0 a_spawnprojectile ("BUBULZ", 0, 0, random (0, 360), 2, random (0, 180));
	Goto Spawn;
	
	Death:
		EXPL A 0 Radius_Quake (2, 16, 0, 15, 0);
		TNT1 A 0 A_StopSound(6);
		TNT1 A 0 A_AlertMonsters();
		TNT1 A 0 A_SpawnItemEx ("DetectFloorCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("DetectCeilCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("UnderwaterExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		//TNT1 A 0 A_SpawnItemEx ("RocketExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 a_spawnprojectile ("ImpXDeath", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("xdeath2", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("xdeath2", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("ExplosionParticle", 0, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("ExplosionParticle", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAAAAA 0 a_spawnprojectile ("ExplosionParticle", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAAA 0 a_spawnprojectile ("MediumExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
		EXPL AAAAAA 0 a_spawnprojectile ("ExplosionSmoke", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 1;
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 AAAAAAAAAAAAA 3 a_spawnprojectile ("ExplosionSmoke", 2, 0, random (0, 360), 2, random (0, 360));
	Stop;
}
}

CLASS DeadImp1MeleeDeath : pb_blood_and_gore_base
{ 

States
    {
	Spawn:
	FID3 EEEEEEEEEEEEEEEEEEEEEE 18;
	FID3 EEE 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
	FID3 E -1;
	Stop;
	Raise:
	FID3 E 5;
	FID3 DCB 5;
	//TNT1 A 0 A_SpawnItem ("Imp", 3);
	Stop;
	Death:
	TNT1 A 0 A_Jump (128, "Death2");
	TNT1 A 0 a_spawnprojectile ("XDeathImpArm", 5, 0, random (0, 360), 2, random (0, 160));
	POS3 A 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 1 A_SpawnItem ("DeadImp_NoArm", 5);
	Stop;
	Death2:
	TNT1 A 0 a_spawnprojectile ("XDeathImpLeg", 5, 0, random (0, 360), 2, random (0, 160));
	SPOS A 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 1 A_SpawnItem ("DeadImp_NoLeg", 5);
	Stop;
	Death.CutLess:
	Death.Saw:
	TNT1 A 1 A_SpawnItem ("DeadImp_Half", 5);
	TNT1 A 0 a_spawnprojectile ("RipImp", 0, 0, random (0, 360), 2, random (0, 160));
	Stop;
Death.Plasma: Death.Plasma2:
	TNT1 A 0;
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	TNT1 AAA 0 a_spawnprojectile ("brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
	EXPL AAA 0 a_spawnprojectile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
	TNT1 A 0;
	Stop;
XDeath:
	TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("xdeath3", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAA 0 a_spawnprojectile ("xdeath2", 22, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("xdeath2", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAAAA 0 a_spawnprojectile ("xdeath4", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;
Death.Fatality:
Death.Melee:
Death.Kick:
Death.ExplosiveImpact:
Death.ExtremePunches:
	TNT1 A 0;
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,15,0,1);
	TNT1 A 0 A_FaceTarget();
	ID30 ABC 6;
	TNT1 A 1 A_SpawnItem ("DeadImp1MeleeDeath", 5);
Stop;}}

CLASS DeadImp_NoHead_Fatalized: DeadImp1 { 
Default 
{Health 200;} States{Spawn:

	TROH PPP 45;
	TROH PPP 3 A_SpawnItemEx ("SwarmFly", frandom(-16,16), frandom(-16,16), frandom(-16,16) );
        TROH P -1;
        Stop;
        Death:
  	    TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 AA 0 a_spawnprojectile ("xdeath1", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("xdeath4", 32, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	 TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
         Stop;}}


	


CLASS DeadImpTR06K: DeadImp1 { 

States{Spawn:
	TR06 K -1;
	Stop ;
	
	Death:
	TNT1 A 0 A_SpawnItem("RipImp", 0, 10);
	TNT1 A 0 A_SpawnItem("MeatDeathSmall", 0, 10);
	TNT1 A 0 A_SpawnItem("DeadImp_Half");
	TNT1 A 0 A_NoBlocking();
	Stop;
	}}
	
	

CLASS DeadImpTR06V: DeadImp1 { 
States{Spawn:
	TR06 V -1;
	Stop;
	
	Death:
	TNT1 A 0 A_SpawnItem("RipImp", 0, 10);
	TNT1 A 0 A_SpawnItem("MeatDeathSmall", 0, 10);
	TNT1 A 0 A_SpawnItem("DeadImp_Half");
	TNT1 A 0 A_NoBlocking();
	Stop;}}


CLASS DeadImpTRO3E: DeadImp1 { 
States{Spawn:
	TRO3 E -1;
	Stop ;
	
	Death:
	TNT1 A 0 a_spawnprojectile ("XDeathHalfImpUpperPart32", 32, 0, random (0, 360), 2, random (10, 60));
	TNT1 A 0 A_SpawnItem("MeatDeathSmall", 0, 10);
	TNT1 A 0 A_SpawnItem("DeadImp_Half");
	TNT1 A 0 A_NoBlocking();
	Stop;
	}}	


CLASS DeadImpTRO4E: DeadImp1 { 
States{Spawn:
	TRO4 E -1;
	Stop;
	
	Death:
	TNT1 A 0 a_spawnprojectile ("XDeathHalfImpUpperPart32", 32, 0, random (0, 360), 2, random (10, 60));
	TNT1 A 0 A_SpawnItem("MeatDeathSmall", 0, 10);
	TNT1 A 0 A_SpawnItem("DeadImp_Half");
	TNT1 A 0 A_NoBlocking();
	Stop;}}	


CLASS DeadImpIZD1H: DeadImp_Half { 
States{Spawn:
	IZD1 H -1;
	Stop; }}	


CLASS DeadImpID17G: DeadImp1 { 
States{Spawn:
	ID17 G -1;
	Stop;
	
	Death:
	TNT1 A 0 a_spawnprojectile ("XDeathHalfImpUpperPart32", 32, 0, random (0, 360), 2, random (10, 60));
	TNT1 A 0 A_SpawnItem("MeatDeathSmall", 0, 10);
	TNT1 A 0 a_spawnprojectile ("XDeathImpLeg", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnItem("RipGuts", 0, 10);
	TNT1 A 0 A_NoBlocking();
	Stop;}}	
	
	

CLASS DeadImpIZD3D: DeadImp1 { 
States{Spawn:
	IZD3 D -1;
	Stop;
	
	Death:
	TNT1 A 0 a_spawnprojectile ("XDeathHalfImpUpperPart32", 32, 0, random (0, 360), 2, random (10, 60));
	TNT1 A 0 A_SpawnItem("MeatDeathSmall", 0, 10);
	TNT1 AA 0 a_spawnprojectile ("XDeathImpLeg", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnItem("RipGuts", 0, 10);
	TNT1 A 0 A_NoBlocking();
	Stop;}}		

CLASS DeadImpTROOY: DeadImp1 { 
States{Spawn:
	TROO Y -1;
	Stop;		
	}}
	
CLASS DeadImpTRO4M: DeadImp1 { 
States{Spawn:
	TRO4 M -1;
	Stop;		
	}}

CLASS DeadImpT6SWG: DeadImp1 { 
Default 
{Health 200;} States{Spawn:
	T6SW G -1;
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 10);
		TNT1 A 0 A_SpawnItem("DeadImp_NoHead");
		Stop;
	}}

CLASS DeadImpT6SWN: DeadImp1 { 
Default 
{Health 200;} States{Spawn:
	T6SW N -1;
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 10);
		TNT1 A 0 A_SpawnItem("DeadImp_NoHead");
		Stop;
	}}

CLASS DeadImpT5SWG: DeadImp1 { 
Default 
{Health 200;} States{Spawn:
	T5SW G -1;
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 10);
		TNT1 A 0 A_SpawnItem("DeadImp_NoHead");
		Stop;
	}}
	
CLASS DeadImpT55WG: DeadImp1 { 
Default 
{Health 200;} States{Spawn:
	T55W G -1;
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 10);
		TNT1 A 0 A_SpawnItem("DeadImp_NoHead");
		Stop;
	}}
	
CLASS DeadImpT55WN: DeadImp1 { 
Default 
{Health 200;} States{Spawn:
	T55W N -1;
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 10);
		TNT1 A 0 A_SpawnItem("DeadImp_NoHead");
		Stop;
	}}

CLASS DeadImpT5SWN: DeadImp1 { 
Default 
{Health 200;} States{Spawn:
	T5SW N -1;
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 10);
		TNT1 A 0 A_SpawnItem("DeadImp_NoHead");
		Stop;
	}}

CLASS DeadImpTR0HE: DeadImp1 { 
Default 
{Health 200;} States{Spawn:
	TR0H E -1;
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 10);
		TNT1 A 0 A_SpawnItem("DeadImp_NoHead");
		Stop;
	}}

CLASS DeadImpIXD1H : DeadImp1 { 
Default 
{Health 200;} States{Spawn:
	IXD1 H -1;
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("MeatDeathSmall", 0, 10);
		TNT1 A 0 A_SpawnItem("DeadImpIZD1H");
		Stop;
	}}
	
CLASS DeadImpIXD4L : DeadImp1 { 
Default 
{Health 200;} States{Spawn:
	IXD4 L -1;
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("MeatDeathSmall", 0, 10);
		TNT1 A 0 A_SpawnItem("DeadImpIZD1H");
		Stop;
	}}
	
CLASS DeadImpTR03E : DeadImp1 { 
Default 
{Health 200;} States{Spawn:
	TR03 E -1;
	Stop;
	
	Death:
	TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;
	}}

CLASS DeadImpTR04E : DeadImp1 { 
Default 
{Health 200;} States{Spawn:
	TR04 E -1;
	Stop;
	
	Death:
	TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;
	}}

CLASS DeadImpTR04J : DeadImp1 { 
Default 
{Health 200;} States{Spawn:
	TR04 J -1;
	Stop;
	
	Death:
	TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;
	}}

CLASS DeadImpTROGE  : DeadImp1 { 
Default 
{Health 200;} States{Spawn:
	TROG E  -1;
	Stop;
	
	Death:
	TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;
	}}

CLASS DeadImp_Pinned: pb_dismembered_monster_base
{
Default 
{
+NOPAIN
+NOGRAVITY
Health 200;
DamageFactor "Head", 15.0;
	Height 40;
	Radius 6;
	}
	States{Spawn:
	TNT1 A 0;
	TNT1 A 0 A_PlaySound("Weapons/NailHitBleed");
	TNT1 A 0 A_Recoil(15);
	PIN6 AA 4 a_spawnprojectile ("Brutal_LiquidBlood3", 25, random(-2,2), random (0, 360), 2, random (0, 40));
	TNT1 A 0 A_Recoil(10);
	PIN6 A 4 a_spawnprojectile ("Brutal_LiquidBlood3", 25, random(-2,2), random (0, 360), 2, random (0, 40));
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	PIN6 A 4 a_spawnprojectile ("Brutal_LiquidBlood3", 25, random(-2,2), random (0, 360), 2, random (0, 40));
	TNT1 A 0 A_Recoil(10);
	PIN6 A 4 a_spawnprojectile ("Brutal_LiquidBlood3", 25, random(-2,2), random (0, 360), 2, random (0, 40));
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	PIN6 A 4 a_spawnprojectile ("Brutal_LiquidBlood3", 25, random(-2,2), random (0, 360), 2, random (0, 40));
	TNT1 A 0 A_Recoil(10);
	PIN6 A 4 a_spawnprojectile ("Brutal_LiquidBlood3", 25, random(-2,2), random (0, 360), 2, random (0, 40));
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	PIN6 A 4 a_spawnprojectile ("Brutal_LiquidBlood3", 25, random(-2,2), random (0, 360), 2, random (0, 40));
	TNT1 A 0 A_Recoil(10);
	PIN6 A 4 a_spawnprojectile ("Brutal_LiquidBlood3", 25, random(-2,2), random (0, 360), 2, random (0, 40));
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	PIN6 A 4 a_spawnprojectile ("Brutal_LiquidBlood3", 25, random(-2,2), random (0, 360), 2, random (0, 40));
	TNT1 A 0 A_Recoil(10);
	PIN6 A 4 a_spawnprojectile ("Brutal_LiquidBlood3", 25, random(-2,2), random (0, 360), 2, random (0, 40));
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	TNT1 A 0 A_Jump(36, "SlideDown");
	JustHangThere:
	TNT1 A 0 A_Recoil(6);
	PIN6 A 6;
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	PIN6 A 16;
	Loop;
	
	SlideDown:
	TNT1 A 0 A_Recoil(6);
	TNT1 A 0 ThrustThingZ(0, 6, 1, 0);
	PIN6 A 6;
	TNT1 A 0 A_JumpIf(vel.z < 2, "SlumpSittingDown");
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	PIN6 A 12;
	Loop;
	
	SlumpSittingDown:
	TNT1 A 0 A_SpawnItemEx("DeadImp_Slumped", 10);
	Stop;
	
	LayDown:
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_SpawnItem("DeadImp1");
	Stop;
	
	XDeath:
	Death.Explosives:
	Death.ExplosiveImpact:
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_SpawnItem("ImpXDeath");
	Stop;
	
	Death:
	TNT1 A 0 A_NoBlocking();
	TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
	TNT1 AAA 0 a_spawnprojectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
	TNT1 AA 0 a_spawnprojectile ("XDeathImpArm", 35, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnItemEx("ImpHeadExplode", 0, 0, 22);
	TNT1 A 0 A_SpawnItem("DeadImpJustLegsAreLeft");
	Stop;
}

}