
//Dickhead imp
CLASS DNImpVariant3 : zscript_Imp// Replaces DoomImp
{ 
		//SpawnID 1410;
Default {
		
		Health 65;
		Radius 20;
		Height 46;
		Species "Imp";
		Speed 6;
		PainChance 200;
		MONSTER;
		+FLOORCLIP;
		Obituary "%o got imped.";
	}
	States
	{
		Death.Shrink:
			TNT1 A 1 A_PlaySound("Shrink", 3);
			TNT1 A 0 A_SpawnItemEx ("DNImpVariant3ShrinkFX1", 0, 0,  5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("DNImpVariant3ShrinkFX2", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("DNImpVariant3ShrinkFX3", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("DNImpVariant3ShrinkFX4", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("DNImpVariant3ShrinkFX5", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("DNImpVariant3ShrinkFX6", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("DNImpVariant3ShrinkFX7", 0, 0, 5, 0, 0);
			TNT1 A 1 A_SpawnItemEx ("LilDNImpVariant3", 1);
			stop;
			
		ReplaceVanilla:
			TNT1 A 0 {self.bTHRUACTORS = true;}
			TNT1 A 0 A_ChangeCountFlags(false);
			TNT1 A 0 A_SpawnItemEx ("Vanilla_DNImpVariant3",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION |SXF_TRANSFERSPECIAL| SXF_TRANSFERAMBUSHFLAG ,0);
			Stop;
			
		Spawn:
			TROO A 0;
			TNT1 A 0 ACS_ExecuteAlways(796, 0, 0, 0, 0);//Check if Vanilla Mode is activated
			TNT1 A 1 ACS_NamedExecuteAlways("CeilingClimbingImps", 0);//Check for CVARs
			TNT1 A 0 A_GiveInventory("SKImp", 1);
			
			TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim");
			TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim");
			TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
			Goto Stand;
			
		Stand:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("HeadshotTarget20", 12, 48,0);
			TNT1 A 0 A_CheckSight("Stand2");
			TRO4 BB 10 A_Look();
			Loop;
			
		Stand2:
			TRO4 BB 11 A_Look();
			Goto Stand;
			
		Idle:
		LookingForPlayer:
			TNT1 A 0 A_GiveInventory("SKImp", 1);
			TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 42,0);
			TRO4 B 10 A_Look();
			TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 42,0);
			TRO4 B 10 A_Look();
			TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 42,0);
			TRO4 B 10 A_Look();
			TNT1 A 0 {self.angle -= 40;}
			TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 42,0);
			TRO4 B 10 A_Look();
			TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 42,0);
			TRO4 B 10 A_Look();
			TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 42,0);
			TRO4 B 10 A_Look();
			TNT1 A 0 {self.angle -= 40;}
			TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 42,0);
			TRO4 B 10 A_Look();
			TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 42,0);
			TRO4 B 10 A_Look();
			TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 42,0);
			TRO4 B 10 A_Look();
			
			TROO A 0 A_Wander();
			TRO4 AA 2 A_Look();
			TNT1 A 0 A_Recoil(-2);
			TNT1 A 0 A_SpawnItem("HeadshotTarget6", 12, 48,0);
			TNT1 A 0 A_PlaySound("flesh/step",4);
			TROO B 0 A_Wander();
			TRO4 BB 2 A_Look();
			TNT1 A 0 A_Recoil(-2);
			TNT1 A 0 A_SpawnItem("HeadshotTarget6", 12, 48,0);
			TNT1 A 0 A_PlaySound("flesh/step",4);
			TROO C 0 A_Wander();
			TRO4 CC 2 A_Look();
			TNT1 A 0 A_Recoil(-2);
			TNT1 A 0 A_SpawnItem("HeadshotTarget6", 12, 48,0);
			TNT1 A 0 A_PlaySound("flesh/step",4);
			TROO D 0 A_Wander();
			TRO4 DD 2 A_Look();
			TNT1 A 0 A_Recoil(-2);
			TNT1 A 0 A_SpawnItem("HeadshotTarget6", 12, 48,0);
			
			
			TNT1 A 0 A_jump(128, "LookingForPlayer");
			
			
			TROO A 0 A_Wander();
			TRO4 AA 2 A_Look();
			TNT1 A 0 A_Recoil(-2);
			TNT1 A 0 A_SpawnItem("HeadshotTarget6", 12, 48,0);
			TNT1 A 0 A_PlaySound("flesh/step",4);
			TROO B 0 A_Wander();
			TRO4 BB 2 A_Look();
			TNT1 A 0 A_Recoil(-2);
			TNT1 A 0 A_SpawnItem("HeadshotTarget6", 12, 48,0);
			TNT1 A 0 A_PlaySound("flesh/step",4);
			TROO C 0 A_Wander();
			TRO4 CC 2 A_Look();
			TNT1 A 0 A_Recoil(-2);
			TNT1 A 0 A_SpawnItem("HeadshotTarget6", 12, 48,0);
			TNT1 A 0 A_PlaySound("flesh/step",4);
			TROO D 0 A_Wander();
			TRO4 DD 2 A_Look();
			TNT1 A 0 A_Recoil(-2);
			TNT1 A 0 A_SpawnItem("HeadshotTarget6", 12, 48,0);
			Goto LookingForPlayer;
			
			
			
		ForgetTarget:
			TNT1 A 0 A_ClearTarget();
			TNT1 A 0 A_TakeInventory("EnemyMemory", 25);
			TNT1 A 0 A_GiveInventory("LookingForPlayer", 1);
			Goto Stand;
			
		See:
			//TNT1 A 0 A_JumpIf(vel.Z < 0, "FallingAfterImpact")// funny thing I tried, better not implement
			TNT1 A 0 A_TakeInventory("EnemyMemory", 15);
			TNT1 A 0 A_SpawnItem("HeadshotTarget10", 12, 48,0);
			TRO4 A 4 A_faceTarget();
			TNT1 A 0 A_SpawnItem("HeadshotTarget10", 12, 48,0);
			TRO4 B 4;
			TNT1 A 0 A_SpawnItem("HeadshotTarget10", 12, 48,0);
			TRO4 C 10;
			TNT1 A 0 A_SpawnItem("HeadshotTarget10", 12, 48,0);
			Goto SeeContinue;
			
		CeilingJump:
			TNT1 A 0 A_JumpIf(CallACS("GetActorZDist") <= 120, 2);
			TNT1 AAA 0;
			TNT1 A 0 A_JumpIf(CallACS("IsThisSky") == 1, "SeeContinue");
			TNT1 A 0 A_PlaySound("imp/sight",6);
			1M42 A 6;
			TNT1 A 0 A_GiveInventory ("IsJumping");
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			4M40 AAAA 1 A_CheckCeiling("CeilingLatch");
			TNT1 A 0 ThrustThingZ(0,45,0,1);
			4M40 BBBBCCCC 1 A_CheckCeiling("CeilingLatch");
			TNT1 A 0 ThrustThingZ(0,45,0,1);
			4M40 DDDDEEEE 1 A_CheckCeiling("CeilingLatch");
			TNT1 A 0 ThrustThingZ(0,45,0,1);
			4M40 FFFFGGGG 1 A_CheckCeiling("CeilingLatch");
			1M42 EEEEEEEEEEEEEEE 1 A_CheckFloor("SeeContinue");
			TNT1 A 0 A_TakeInventory ("IsJumping");
			Goto SeeContinue;
			
		CeilingLatch:
			TNT1 A 0 {self.bNOGRAVITY = true;}
			TNT1 A 0 {self.bTHRUSPECIES = true;}
			//	TNT1 A 0 {self.bCEILINGHUGGER", 1)
			TNT1 A 0 {self.bNOVERTICALMELEERANGE = true;}
			TNT1 A 0 A_GiveInventory ("IsOnCeiling", 1);
			4M40 HHHHHHHH 1 ThrustThingZ(0,500,0,1);
			Goto CeilingCrawl;
			
		CeilingCrawl:
			TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
			//TNT1 A 0 A_JumpIf(vel.Z < 0, "FallingAfterImpact")// funny thing I tried, better not implement
			
			TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
			TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim");
			TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim");
			TNT1 A 0 A_SpawnItem("HeadshotTarget4", 12, 48,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TNT1 A 0 A_JumpIf(CallACS("IsThisSky") == 1, "CeilingPounce");
			//TNT1 A 0 A_JumpIf(vel.z != 0, "CeilingPounce")
			TNT1 A 0 ThrustThingZ(0,500,0,1);
			4M40 II 2 A_Chase("CeilingPounce", "CeilingMissile");
			//ContinueCeilingCrawl1:
			TNT1 A 0 A_Recoil(-1);
			TNT1 A 0 A_SpawnItem("HeadshotTarget4", 12, 48,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TNT1 A 0 ThrustThingZ(0,500,0,1);
			4M40 II 2 A_Chase("CeilingPounce", "CeilingMissile");
			TNT1 A 0 A_JumpIf(vel.z != 0, "CeilingPounce");
			TNT1 A 0 A_PlaySound("flesh/step",4);
			TNT1 A 0 A_TakeInventory("SKImp", 1);
			//ContinueCeilingCrawl2:
			TNT1 A 0 A_SpawnItem("HeadshotTarget4", 12, 48,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TNT1 A 0 ThrustThingZ(0,500,0,1);
			4M40 JJ 2 A_Chase("CeilingPounce", "CeilingMissile");
			//ContinueCeilingCrawl3:
			TNT1 A 0 A_SpawnItem("HeadshotTarget4", 12, 48,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TNT1 A 0 ThrustThingZ(0,500,0,1);
			4M40 JJ 2 A_Chase("CeilingPounce", "CeilingMissile");
			TNT1 A 0 A_PlaySound("flesh/step",4);
			TNT1 A 0;
			TNT1 A 0 A_JumpIf(CallACS("IsThisSky") == 1, "CeilingPounce");
			TNT1 A 0 A_JumpIf(vel.z != 0, "CeilingPounce");
			//ContinueCeilingCrawl4:
			TNT1 A 0 A_SpawnItem("HeadshotTarget4", 12, 48,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TNT1 A 0 ThrustThingZ(0,500,0,1);
			4M40 KK 2 A_Chase("CeilingPounce", "CeilingMissile");
			//ContinueCeilingCrawl5:
			TNT1 A 0 A_SpawnItem("HeadshotTarget4", 12, 48,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TNT1 A 0 ThrustThingZ(0,500,0,1);
			4M40 KK 2 A_Chase("CeilingPounce", "CeilingMissile");
			TNT1 A 0 A_PlaySound("flesh/step",4);
			TNT1 A 0 A_JumpIf(CallACS("IsThisSky") == 1, "CeilingPounce");
			TNT1 A 0 A_JumpIf(vel.z != 0, "CeilingPounce");
			//ContinueCeilingCrawl6:
			TNT1 A 0 A_SpawnItem("HeadshotTarget4", 12, 48,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TNT1 A 0 ThrustThingZ(0,500,0,1);
			4M40 HH 2 A_Chase("CeilingPounce", "CeilingMissile");
			//ContinueCeilingCrawl7:
			TNT1 A 0 A_SpawnItem("HeadshotTarget4", 12, 48,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TNT1 A 0 ThrustThingZ(0,500,0,1);
			4M40 HH 2 A_Chase("CeilingPounce", "MaybeCeilingPounce");
			TNT1 A 0 A_PlaySound("flesh/step",4);
			TNT1 A 0 A_JumpIf(CallACS("IsThisSky") == 1, "CeilingPounce");
			TNT1 A 0 A_JumpIf(vel.z != 0, "CeilingPounce");
			TNT1 A 0 A_JumpIfTargetInLOS(1);
			Goto CeilingDrop;
			TNT1 A 0;
			TNT1 A 0 A_Jump(224, 3);
			TNT1 A 0 A_JumpIfCloser(1100, "CeilingDrop");
			TNT1 AAAAA 0;
			Loop;
			
		CeilingDrop:
			TNT1 AAA 0;
			TNT1 A 0 A_TakeInventory ("IsOnCeiling");
			TNT1 A 0 {self.bNOGRAVITY = false;}//CEILINGHUGGER
			TNT1 A 0 {self.bCEILINGHUGGER = false;}
			4M40 DCBA 1 A_FaceTarget();
		CeilingDropping:
			T41R C 1 A_JumpIf (vel.z == 0, "CeilingLanding");
			loop;
		CeilingLanding:
			TNT1 A 0 A_PlaySound("flesh/step",4);
			T41R DEBA 5 A_FaceTarget();
			Goto SeeContinue;
			
		CeilingMissile:
			TNT1 D 0 A_SpawnItem("HeadshotTarget23", 0, 48,0);
			TNT1 A 0 A_SpawnItem ("LegTarget30", 10);
			TNT1 A 0 ThrustThingZ(0,500,0,1);
			4M40 L 4 A_FaceTarget();
			TNT1 A 0 A_JumpIfCloser(150, "CeilingPounce");
			TNT1 A 0 A_Playsound ("IMPCHARG");
			TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 25, -30, random (0, 40), 2, random (0, 160));
			TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 25, -30, random (0, 140), 2, random (0, 160));
			4M40 L 2 A_FaceTarget();
			
			TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 25, -30, random (0, 40), 2, random (0, 160));
			TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 25, -30, random (0, 140), 2, random (0, 160));
			TNT1 A 0 ThrustThingZ(0,500,0,1);
			4M40 L 2 A_FaceTarget();
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 25, -30, random (0, 40), 2, random (0, 160));
			TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 25, -30, random (0, 140), 2, random (0, 160));
			TNT1 A 0 ThrustThingZ(0,500,0,1);
			4M40 L 2 A_FaceTarget();
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TNT1 D 0 A_SpawnItem("HeadshotTarget23", 0, 48,0);
			TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 25, -30, random (0, 40), 2, random (0, 160));
			TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 25, -30, random (0, 140), 2, random (0, 160));
			TNT1 A 0 ThrustThingZ(0,500,0,1);
			4M40 L 2 A_FaceTarget();
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TNT1 D 0 A_SpawnItem("HeadshotTarget23", 0, 48,0);
			TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 25, -30, random (0, 40), 2, random (0, 160));
			TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 25, -30, random (0, 140), 2, random (0, 160));
			TNT1 A 0 ThrustThingZ(0,500,0,1);
			4M40 L 2 A_FaceTarget();
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TNT1 D 0 A_SpawnItem("HeadshotTarget23", 0, 48,0);
			TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 25, -30, random (0, 40), 2, random (0, 160));
			TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 25, -30, random (0, 140), 2, random (0, 160));
			TNT1 A 0 ThrustThingZ(0,500,0,1);
			4M40 M 2 A_FaceTarget();
			TNT1 D 0 A_SpawnItem("HeadshotTarget10", 12, 48,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TNT1 A 0 ThrustThingZ(0,500,0,1);
			4M40 N 6 a_spawnprojectile("FireBall_", 22, 0, 0, 0);
			TNT1 A 0 ThrustThingZ(0,500,0,1);
			4M40 M 4;
			Goto CeilingCrawl;
			
		MaybeCeilingPounce:
			TNT1 A 0 A_Jump(28, 3);
			Goto CeilingCrawl;
		CeilingPounce:
			TNT1 AAA 0;
			TNT1 A 0 A_TakeInventory ("IsOnCeiling");
			TNT1 A 0 {self.bNOGRAVITY = false;}//CEILINGHUGGER
			TNT1 A 0 {self.bCEILINGHUGGER = false;}
			TNT1 A 0 {self.bTHRUSPECIES = false;}
			TNT1 A 0 A_Recoil (-18);
			TNT1 A 0 A_FaceTarget();
			TNT1 A 0 A_PlaySound("weapons/fistwhoosh");
			TNT1 A 0 a_spawnprojectile("ImpAttack2",10,0,0,0);
			4M40 CDEFG 4 A_FaceTarget();
			TNT1 A 0 a_spawnprojectile("ImpAttack2",10,0,0,0);
			1M42 EEE 1 a_spawnprojectile("ImpAttack2",10,0,0,0);
			TNT1 A 0 A_TakeInventory ("IsJumping");
			
			TNT1 A 0 A_Jump(24, 3);
			1M42 A 6;
			Goto SeeContinue;
			TNT1 AAA 0;
			Goto Melee+1;
			
		SeeContinue:
			TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
			//TNT1 A 0 A_JumpIf(vel.Z < 0, "FallingAfterImpact")// funny thing I tried, better not implement
			
			TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
			TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim");
			TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim");
			TNT1 A 0 A_SpawnItem("HeadshotTarget4", 12, 48,0);
			TNT1 A 0 A_JumpIfInventory("EnemyMemory", 25, "ForgetTarget");
			TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TRO4 AA 2 A_Chase();
			TNT1 A 0 A_Recoil(-1);
			TNT1 A 0 A_SpawnItem("HeadshotTarget4", 12, 48,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TRO4 AA 2 A_Chase();
			TNT1 A 0 A_TakeInventory("SKImp", 1);
			TNT1 A 0 A_PlaySound("flesh/step",4);
			
			TNT1 A 0 A_SpawnItem("HeadshotTarget4", 12, 48,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TRO4 BB 2 A_Chase();
			TNT1 A 0 A_SpawnItem("HeadshotTarget4", 12, 48,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TRO4 BB 2 A_Chase();
			
			TNT1 A 0 A_SpawnItem("HeadshotTarget4", 12, 48,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TRO4 CC 2 A_Chase();
			TNT1 A 0 A_SpawnItem("HeadshotTarget4", 12, 48,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TRO4 CC 2 A_Chase();
			TNT1 A 0 A_PlaySound("flesh/step",4);
			TNT1 A 0 A_SpawnItem("HeadshotTarget4", 12, 48,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TRO4 DD 2 A_Chase();
			TNT1 A 0 A_SpawnItem("HeadshotTarget4", 12, 48,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TRO4 DD 2 A_Chase();
			TNT1 A 0 A_JumpIfInventory("NoCeilingClimb", 1, 4);
			TNT1 A 0 A_Jump(236, 3);
			TNT1 A 0 A_JumpIfCloser(800, "CeilingJump");
			TNT1 AAAAA 0;
			Loop;
			
		Melee:
			TNT1 A 0 A_FaceTarget();
			TNT1 A 0 A_PlaySound("imp/sight",6);
			1M42 ABCD 4 A_Recoil (-1);
			1M42 A 5 A_FaceTarget();
			TNT1 A 0 A_JumpIfCloser(60, "Melee2");
			TNT1 A 0 A_TakeInventory("SKImp", 1);
			TNT1 A 0 ThrustThingZ(0,39,0,1);
			TNT1 A 0 A_FaceTarget();
			TNT1 A 0 A_Recoil (-12);
			1M42 E 6;
			TNT1 A 0 A_GiveInventory ("IsJumping");
			TNT1 A 0 A_PlaySound("weapons/fistwhoosh");
			TNT1 A 0 A_FaceTarget();
			1M42 E 4 a_spawnprojectile("ImpAttack2",10,0,0,0);
			TNT1 A 0 A_TakeInventory ("IsJumping");
			TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
			1M42 A 4 a_spawnprojectile("ImpAttack2",10,0,0,0);
			TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
			Goto SeeContinue;
			
		Melee2:
			TNT1 D 0 A_SpawnItem("HeadshotTarget4", 12, 39,0);
			TRO4 EF 4 A_FaceTarget();
			TNT1 A 0 A_TakeInventory("SKImp", 1);
			TNT1 D 0 A_SpawnItem("HeadshotTarget4", 12, 39,0);
			TRO4 G 4 a_spawnprojectile("ImpAttack",10,0,0,0);
			TNT1 D 0 A_SpawnItem("HeadshotTarget4", 12, 39,0);
			TRO4 GE 4;
			Goto SeeContinue;
			
			
		Missile:
			TNT1 A 0 A_JumpIfCloser(1200, 3);
			TNT1 A 0 a_spawnprojectile("MonsterTargetCheck", 34, 0, 0, 0);
			TNT1 A 0 a_spawnprojectile("MonsterTargetCheckFaster", 34, 0, 0, 0);
			TRO4 E 1 A_FaceTarget();
			TNT1 A 0 A_JumpIfInventory("CantFire",1, "Advancing");
			TNT1 A 0 A_JumpIfCloser(150, "Melee");
			TNT1 A 0 A_TakeInventory("SKImp", 1);
			TNT1 D 0 A_SpawnItem("HeadshotTarget23", 0, 39,0);
			TNT1 A 0 A_SpawnItem ("LegTarget30", 10);
			TRO4 E 4 A_FaceTarget();
			TNT1 D 0 A_SpawnItem("HeadshotTarget23", 0, 39,0);
			TNT1 A 0 A_SpawnItem ("LegTarget30", 10);
			TNT1 A 0 A_Playsound ("IMPCHARG");
			TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
			TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
			TRO4 E 2 A_FaceTarget();
			
			TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
			TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
			TRO4 E 2 A_FaceTarget();
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
			TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
			TRO4 E 2 A_FaceTarget();
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TNT1 D 0 A_SpawnItem("HeadshotTarget23", 0, 48,0);
			TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
			TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
			TRO4 E 2 A_FaceTarget();
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
			TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
			TRO4 E 2 A_FaceTarget();
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TNT1 A 0 a_spawnprojectile ("SmallFlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
			TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
			
			TNT1 A 0 A_Jump(100, "specialattack");
			
			TROO F 2 A_FaceTarget();
			TNT1 D 0 A_SpawnItem("HeadshotTarget10", 12, 48,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TRO4 G 6 A_CustomComboAttack("LargeImpBall",32,2,"gauntimp/meleehit");
			TNT1 D 0 A_SpawnItem("HeadshotTarget23", 0, 39,0);
			TNT1 A 0 A_SpawnItem ("LegTarget30", 10);
			Goto SeeContinue;
			
		SpecialAttack:
			TRO4 F 2 A_FaceTarget();
			TNT1 D 0 A_SpawnItem("HeadshotTarget10", 12, 39,0);
			TNT1 A 0 A_SpawnItem ("LegTarget30", 10);
			TRO4 G 6 a_spawnprojectile("LargeImpBall", 34, 0, 0, 0);
			TRO4 F 4;
			TNT1 D 0 A_SpawnItem("HeadshotTarget10", 12, 39,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TRO4 F 2 A_FaceTarget();
			TNT1 D 0 A_SpawnItem("HeadshotTarget10", 12, 39,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TRO4 G 6 a_spawnprojectile("LargeImpBall", 34, 0, 0, 0);
			TNT1 D 0 A_SpawnItem("HeadshotTarget10", 12, 39,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			Goto SeeContinue;
			
		Pain:
			TNT1 A 0 {self.bNOGRAVITY = false;}
			TNT1 A 0 {self.bTHRUSPECIES = false;}
			TNT1 A 0 {self.bCEILINGHUGGER = false;}
			TNT1 A 0 A_JumpIfInventory("IsOnCeiling", 1, "PainCanFallFromCeiling");
			TNT1 D 0 A_SpawnItem("HeadshotTarget4", 12, 48,0);
			TNT1 A 0 A_SpawnItem ("LegTargetBase", 10);
			TNT1 A 0 A_TakeInventory("SKImp", 1);
			TRO4 H 2;
			TRO4 H 2 A_Pain();
			Goto SeeContinue;
			
		Pain.Melee:
			TNT1 A 0 {self.bNOGRAVITY = false;}
			TNT1 A 0 {self.bTHRUSPECIES = false;}
			TNT1 A 0 {self.bCEILINGHUGGER = false;}
			TNT1 A 0;
			TRO4 H 2;
			TNT1 A 0 A_JumpIfInventory ("SKImp", 1, "GotoStealthKill");
			TRO4 H 2 A_Pain();
			Goto SeeContinue;
			
		Pain.head:
		Pain.minorhead:
			TNT1 A 0 {self.bNOGRAVITY = false;}
			TNT1 A 0 {self.bCEILINGHUGGER = false;}
			TNT1 A 0 A_JumpIfInventory("IsOnCeiling", 1, "PainCanFallFromCeiling");
			TNT1 D 0 A_SpawnItem("HeadshotTarget10", 12, 48,0);
			TNT1 A 0 A_TakeInventory("SKImp", 1);
			TRO4 H 6;
			TRO4 H 6 A_Pain();
			Goto SeeContinue;
			
		GotoStealthKill:
			TNT1 A 1;
			TNT1 A 0 A_GiveToTarget("SKImp3");
			TNT1 A 0 A_GiveToTarget("GoFatality", 1);
			TNT1 A 1 A_Die("Stealthy");
			Stop;
		Death.Stealthy:
			TNT1 A 0 A_NoBlocking();
			Stop;
			
		Pain.ExplosiveImpact:
		Pain.Explosive:
		Pain.ExtremePunches:
			TNT1 A 0;
			TNT1 A 0 {self.bNOGRAVITY = false;}
			TNT1 A 0 {self.bCEILINGHUGGER = false;}
			TNT1 A 0 A_Pain();
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
			TNT1 A 0 A_TakeInventory("SKImp", 1);
			TNT1 A 0 A_GiveInventory("IsDown", 1);
			TNT1 A 0 ThrustThingZ(0,40,0,1);
			T4DI AB 8;
			Goto FallingAfterImpact;
			
		Pain.Kick:
			TNT1 A 0;
			TNT1 A 0 {self.bNOGRAVITY = false;}
			TNT1 A 0 {self.bCEILINGHUGGER = false;}
			T4DI A 1 A_Pain();
			TNT1 A 0 A_GiveInventory("IsDown", 1);
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			T4DI A 1 A_facetarget();
			T4DI A 6 ThrustThing(angle*256/360+128, 5, 0, 0);
			T4DI B 8;
			Goto FallingAfterImpact;
			
		PainCanFallFromCeiling:
			TNT1 A 0 {self.bNOGRAVITY = false;}
			TNT1 A 0 {self.bCEILINGHUGGER = false;}
			TNT1 A 0 A_TakeInventory ("IsOnCeiling");
		FallingAfterImpact:
			T4DI B 1 A_GiveInventory ("FallingHeight", 1);
			TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim");
			TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim");
			T4DI B 1 A_CheckFloor ("GetUp");
			TNT1 A 0 A_JumpIf (vel.z == 0, "GetUp");
			Loop;
			
		GetUp:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("LargeMassWaterImpact");
			TNT1 A 0 A_SpawnItem("SmallUnderwaterExplosion");
			TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim");
			TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim");
			TNT1 A 0 {self.bGHOST = true;}
			TNT1 A 0 {self.bNOPAIN = false;}
			TNT1 A 0 {self.bSOLID = false;}
			TNT1 A 0 {self.bFORCEXYBILLBOARD = true;}
			TNT1 A 0 A_GiveInventory("ISDOWN", 1);
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 6, "FallingDie");
			T4DI CCCCCCCC 5 A_JumpIf(vel.z < 0, "FallingAfterImpact");
			TNT1 A 0 {self.bSOLID = true;}
			TNT1 A 0 A_TakeInventory("ISDOWN", 1);
			TNT1 A 0 {self.bFORCEXYBILLBOARD = false;}
			TNT1 A 0 A_TakeInventory("FallingHeight", 100);
			TNT1 A 0 A_TakeInventory("IsDown", 1);
			T4DI DE 7;
			Goto SeeContinue;
			
		PainHurt:
			TNT1 A 0 {self.bNOGRAVITY = false;}
			TNT1 A 0 {self.bCEILINGHUGGER = false;}
			TNT1 A 0 A_TakeInventory("SKImp", 1);
			TNT1 D 0 A_SpawnItem("HeadshotTarget4", 12, 48,0);
			TRO4 H 1;
			TRO4 H 1 A_Pain();
			Goto SeeContinue;
			
		Pain.BlackHole:
			TNT1 A 0 {self.bNOGRAVITY = false;}
			TNT1 A 0 {self.bCEILINGHUGGER = false;}
			T4DI A 1 A_Pain();
			TNT1 A 0 A_GiveInventory("IsDown", 1);
			TNT1 A 0 ThrustThingZ(0,6,0,1);
			T4DI A 1 A_facetarget();
			T4DI A 6 ThrustThing(angle*256/360+128, 5, 0, 0);
			T4DI B 8;
			Goto FallingAfterImpact;
			
		Possession:
			TNT1 A 0 A_SetInvulnerable();
			TRO4 H 3;
			TRO4 H 3 A_Pain();
			"####" "#" 35 ACS_NamedExecuteAlways("Pos - Flicker effect");
			TNT1 A 0 A_UnSetInvulnerable();
			Goto See;
			
		Pain.Stun:
			TNT1 A 0;
			TNT1 A 0 {self.bNOGRAVITY = false;}
			TNT1 A 0 {self.bTHRUSPECIES = false;}
			TNT1 A 0 {self.bCEILINGHUGGER = false;}
			TNT1 A 0 A_SpawnItemEx ("StunElectrocute", random (-4, 4), random (-4, 4),  random (16, 32), 0, 0);
			TRO4 H 1 A_Pain();
			TRO4 HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			TRO4 H 1 A_Pain();
			TRO4 HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			TRO4 H 1 A_Pain();
			TRO4 HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			TRO4 H 1 A_Pain();
			TRO4 HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			TRO4 H 1 A_Pain();
			TRO4 HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
			TRO4 H 1 A_Pain();
			Goto See;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 {self.bNOGRAVITY = false;}
			TNT1 A 0 {self.bCEILINGHUGGER = false;}
			TNT1 A 0 A_JumpIfInventory("IsJumping", 1, "DeathJump");
			TNT1 A 0 A_Jump(32, "Death.Arm");
			TNT1 A 0 A_Jump(24,"DeathNoGuts");
			TNT1 A 0 A_Jump(32,"Death20alt");
			TNT1 A 0 A_Jump(128, "DeathMirror");
			TRO4 I 8;
			TRO4 J 8 A_Scream();
			TRO4 K 6;
			TRO4 L 6 A_NoBlocking();
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_SpawnItem ("DeadImpTRO4M");
			Stop;
			
		DeathNoGuts:
			TNT1 AAAAA 0;
			TNT1 A 0 A_Jump(120, "DeathNoGuts2");
			TNT1 AA 0 a_spawnprojectile ("Instestin", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 a_spawnprojectile ("MuchBlood", 30, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 a_spawnprojectile ("XDeath1", 30, 0, random (0, 360), 2, random (0, 160));
			T4DE A 8 A_Scream();
			T4DE B 8 A_NoBlocking();
			T4DE C 8;
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_SpawnItem ("DyingImpVar31", 2);
			Stop;
			
		DeathNoGuts2:
			TNT1 AAA 0 a_spawnprojectile ("Instestin", 28, 0, random (150, 210), 2, random (0, 40));
			T4D2 ABC 6;
			TNT1 A 0 a_spawnprojectile ("MuchBlood", 30, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 a_spawnprojectile ("XDeath1", 30, 0, random (0, 360), 2, random (0, 160));
			T4D2 D 1 A_Scream();
			T4D2 E 8 A_NoBlocking();
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_SpawnItem ("DyingImpVar32", 2);
			Stop;
			
	Death.Plasma: Death.Plasma2:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Jump(96, "OtherPlasmaDeath");
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_PlaySound("plasmaflesh");
		TNT1 AAAAAAAAA 0 a_spawnprojectile ("Ashes1", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAA 0 a_spawnprojectile ("Ashes2", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1Blue",random(-2,2),random(-2,2),18,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		TNT1 AAAA 0 a_spawnprojectile ("BluePlasmaFireNonStatic", 42, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAA 0 a_spawnprojectile ("BloodMistBig", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAA 0 a_spawnprojectile ("SuperGoreMistSmall", 32, 0, random (0, 360), 2, random (10, 90));
		TNT1 AAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (0, 360), 2, random (0, 180));
		PBR1 B 6 A_NoBlocking();
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1Blue",random(-2,2),random(-2,2),10,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		TNT1 A 0 A_SpawnItemEx ("DetectFloorCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItem("BarrelExplosionSmokeColumn");
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-15, 15), random (-15, 15));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece2", random (-35, 35), random (-35, 35));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random (-45, 45), random (-45, 35));
		PBR1 CCDD 3 a_spawnprojectile ("BluePlasmaFireNonStatic", 32, 0, random (0, 360), 2, random (0, 180));
		PBR1 EEFF 3;
		PBR1 GG 3;
		PBR1 H -1;
		Stop;
		
	OtherPlasmaDeath:
		T4D4 A 6 A_Scream();
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("Ashes1", 33, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAA 0 a_spawnprojectile ("BluePlasmaFire", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("Ashes2", 31, 0, random (0, 360), 2, random (0, 180));
		T4D4 B 6 A_NoBlocking();
		TNT1 AAAAAAA 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 a_spawnprojectile ("Brains1", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAA 0 a_spawnprojectile ("Brains7", 52, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile ("BrainBlood", 50, 0, random (0, 360), 2, random (0, 160));
		T4D4 CDE 6;
		T4D4 FFFFFFFFFFFFFFFFFFFFFFFFFFFFF 8 a_spawnprojectile ("PlasmaSmoke", 10, 0, random (0, 360), 2, random (0, 160));
		T4D4 F -1;
		stop;
		
	Death.Leg:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_JumpIfInventory("IsJumping", 1, "Death.LegInTheAir");
		TNT1 A 0 a_spawnprojectile ("XDeathImpLeg", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		T4DA A 9;
		T4DA A 3 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		T4DA B 3 A_Scream();
		T4DA C 3 A_NoBlocking();
		TNT1 A 0 A_SpawnItem ("DyingImpVar3NoLeg", 5);
		Stop;
		
	Death.LegMassacre:
		TNT1 A 0 a_spawnprojectile ("XDeathImpLeg", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		T4DA A 8 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		T4DA B 8 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem ("ImpVar3BrutalizedWithNoLeg");
		Stop;
		
}
}

CLASS NewImpBall: FireBall_ { 
	Default {
	
	Radius 8;
	Height 6;
	Speed 18;
	FastSpeed 20;
	Damage 3;
	Scale 0.24;
	}
	States
	{
	
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
		TNT1 A 0;//A_JumpIf(ACS_NamedExecuteWithResult("PerformanceMode")==1,"SpawnCheap")
		TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
	Spawn1:
		TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "SpawnCheap");
		TNT1 A 0 A_Playsound("SMLFRBL", 1, 1, 1);
	Fly:
		TNT1 A 0 A_SpawnItem ("CoolAndNewFlameTrails", 0, random( -2, 2));
		BLHD E 1 BRIGHT A_SpawnItem("FireballFlare2",2,0);
		TNT1 A 0 a_spawnprojectile ("OldschoolRocketSmokeTrail2", 2, 0, random (160, 210), 2, random (-30, 30));
		TNT1 A 0 A_SpawnItem ("CoolAndNewFlameTrails");
		BLHD F 1 BRIGHT A_SpawnItem("FireballFlare",0,0);
		TNT1 A 0 a_spawnprojectile ("OldschoolRocketSmokeTrail2", 2, 0, random (160, 210), 2, random (-30, 30));
		TNT1 A 0 A_SpawnItem ("CoolAndNewFlameTrails");
		BLHD G 1 BRIGHT A_SpawnItem("FireballFlare2",2,0);
		TNT1 A 0 a_spawnprojectile ("OldschoolRocketSmokeTrail2", 2, 0, random (160, 210), 2, random (-30, 30));
		TNT1 A 0 A_SpawnItem ("CoolAndNewFlameTrails");
		BLHD H 1 BRIGHT A_SpawnItem("FireballFlare",0,0);
		TNT1 A 0 a_spawnprojectile ("OldschoolRocketSmokeTrail2", 2, 0, random (160, 210), 2, random (-30, 30));
		TNT1 A 0 A_SpawnItem ("CoolAndNewFlameTrails");
		BLHD I 1 BRIGHT A_SpawnItem("FireballFlare2",2,0);
		TNT1 A 0 a_spawnprojectile ("OldschoolRocketSmokeTrail2", 2, 0, random (160, 210), 2, random (-30, 30));
		TNT1 A 0 A_SpawnItem ("CoolAndNewFlameTrails");
		BLHD J 1 BRIGHT A_SpawnItem("FireballFlare",0,0);
		TNT1 A 0 a_spawnprojectile ("OldschoolRocketSmokeTrail2", 2, 0, random (160, 210), 2, random (-30, 30));
		TNT1 A 0 A_SpawnItem ("CoolAndNewFlameTrails");
		BLHD K 1 BRIGHT A_SpawnItem("FireballFlare2",2,0);
		TNT1 A 0 a_spawnprojectile ("OldschoolRocketSmokeTrail2", 2, 0, random (160, 210), 2, random (-30, 30));
		TNT1 A 0 A_SpawnItem ("CoolAndNewFlameTrails");
		BLHD L 1 BRIGHT A_SpawnItem("FireballFlare",0,0);
		Loop;
		
	Death:
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 A_StopSound(1);
		//TNT1 A 0 A_SpawnItem("SuperExpensiveParticleSpawner")
		TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "DeathCheap");
		TNT1 A 0 A_SpawnItemEx ("SmallUnderwaterExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		EXPL AAAAAA 0 a_spawnprojectile ("FireBallExplosionFlames", 1, 0, random (0, 360), 2, random (0, 360));
		
		EXPL A 0 a_spawnprojectile ("FlamethrowerFireParticles", 6, 0, random (0, 360), 2, random (0, 90));
		//FRFX CDEFGHIJKLMNOP 1 BRIGHT A_SpawnItem("RedFlare",0,0)
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-15, 15), random (-15, 15));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece2", random (-35, 35), random (-35, 35));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random (-45, 45), random (-45, 35));
		TNT1 A 0 A_SpawnItemEx ("DetectFloorCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("DetectCeilCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAAAAAAAA 0 a_spawnprojectile ("ExplosionParticleHeavy", 0, 0, random (0, 180), 2, random (0, 180));
		TNT1 AAAA 19 a_spawnprojectile ("PlasmaSmoke", 1, 0, random (0, 360), 2, random (0, 160));
		Stop;
		
	XDeath:
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 A_StopSound(1);
		//TNT1 A 0 A_SpawnItem("SuperExpensiveParticleSpawner")
		TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "DeathCheap");
		EXPL A 0 a_spawnprojectile ("FlamethrowerFireParticles", 6, 0, random (0, 360), 2, random (0, 90));
		TNT1 AAAAAAAAAA 0 a_spawnprojectile ("ExplosionParticleHeavy", 0, 0, random (0, 180), 2, random (0, 180));
		TNT1 A 0 A_SpawnItemEx ("SmallUnderwaterExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		EXPL AAAAAA 0 a_spawnprojectile ("FireBallExplosionFlames", 1, 0, random (0, 360), 2, random (0, 360));
		EXPL AAA 0 a_spawnprojectile ("PlasmaSmoke", 1, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-15, 15), random (-15, 15));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece2", random (-35, 35), random (-35, 35));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece3", random (-45, 45), random (-45, 35));
		//FRFX CDEFGHIJKLMNOP 1 BRIGHT A_SpawnItem("RedFlare",0,0)
		Stop;
}
}


CLASS SmallImpBall : FireBall_ { 
	Default {
	
	Radius 6;
	Height 6;
	Speed 22;
	FastSpeed 24;
	Damage 3;
	Scale .16;
	}
}

CLASS LargeImpBall : FireBall_ { 
	Default {
	
	Radius 8;
	Scale 0.26;
	Height 8;
	Speed 12;
	FastSpeed 16;
	Damage 4;
	Alpha 1;
	}
}

CLASS ImpBallEffect : ACTOR { 
	Default {
	
	RenderStyle "Add";
	Scale 0.4;
	+NOGRAVITY;
	+NOINTERACTION;
	}
	States
	{
	Spawn:
		BAL1 CDE 2;
		Stop;
}
}


CLASS DyingImpVar31 : SwitchableDecoration { 
	Default {
	

	Radius 16;
	Height 32;
	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 0x7FFFFFFF;
	+SHOOTABLE;
	+SOLID;
	DamageFactor "Crush", 50.0;
	DamageFactor "Fatality", 50.0;
	DamageFactor "bloodsplasher", 0.0;    DamageFactor "tinybloodsplasher", 0.0;
    DamageFactor "superbloodsplasher", 0.0;    DamageFactor "smallbloodsplasher", 0.0;
	DamageFactor "BlueBloodSplasher", 0.0;
	DamageFactor "BlueSuperBloodSplasher", 0.0;
	Scale 1.0;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	}
	States
	{
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_GiveToTarget("HasImpShield", 1);
		TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
		T4DE E 8;
		Stop;
		
	Spawn:
		T5DE D 1;
		Goto Suffer;
	Suffer:
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 28,0);
		T4DE EEEEE 2 a_spawnprojectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 28,0);
		T4DE E 2;
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 28,0);
		T4DE FFFFF 2 a_spawnprojectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 28,0);
		T4DE F 2 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 28,0);
		T4DE EEEEE 2 a_spawnprojectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 28,0);
		T4DE E 2;
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 28,0);
		T4DE FFFFF 2 a_spawnprojectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 28,0);
		T4DE F 2 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 28,0);
		T4DE EEEEE 2 a_spawnprojectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 28,0);
		T4DE E 2;
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 28,0);
		T4DE FFFFF 2 a_spawnprojectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 28,0);
		T4DE F 2 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 28,0);
		T4DE EEEEE 2 a_spawnprojectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 28,0);
		T4DE E 2;
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 28,0);
		T4DE FFFFF 2 a_spawnprojectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 28,0);
		T4DE F 2 A_Pain();
		Goto Death;
	Death:
		T4DE GH 8;
		TNT1 A 1 A_SpawnItem ("DeadImp_NoStomach", 5);
		Stop;
		
		
	Death.Head:
	Death.Decaptate:
	Death.MINORHead:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 30);
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		T3D3 JJJJJJJJJJJJJJJJJJJ 2 a_spawnprojectile ("Brutal_LiquidBlood", 32, 0, random (0, 360), 2, random (0, 45));
		T3D3 KKKK 2 a_spawnprojectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		T3D3 LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 2 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
		T3D3 L -1;
		Stop;
		
	Death.Plasma: 
	Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		XBRN AA 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedImpArm", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
		
		XBRN BB 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 A 0 a_spawnprojectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		XBRN CC 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		XBRN DEF 4 BRIGHT;
		TNT1 A 0;
		Stop;
		
	Death.fire:
	Death.Flames:
	Death.Burn:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TRO3 JJJJ 2 a_spawnprojectile ("FlameTrails", 45, 0, random (0, 360), 2, random (50, 130));
		TRO3 KKKK 2 a_spawnprojectile ("FlameTrails", 30, 0, random (0, 360), 2, random (50, 130));
		TRO3 LLLL 2 a_spawnprojectile ("FlameTrails", 25, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0 A_Playsound("props/redfire");
		BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 a_spawnprojectile ("FlameTrails", 15, 0, random (0, 360), 2, random (50, 130));
		BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 10 a_spawnprojectile ("SmallSmoke", 15, 0, random (0, 360), 2, random (70, 110));
		BOSB E -1;
		Stop;
		
	Death.cut:
	Death.cutless:
		TNT1 O 0 A_Jump(230, 2);
		Goto Death;
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TROG A 2 a_spawnprojectile ("RipImp", 0, 0, random (0, 360), 2, random (0, 160));
		TROG AAA 4 A_SpawnItem ("Big_Blood", 0, 30);
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TROG BCDEFGH 8;
		TNT1 A 1 A_SpawnItem ("DeadImp_Half", 5);
		//TROG H -1
		Stop;
		
		
	Death.SSG:
		//TNT1 A 0 a_spawnprojectile ("MeatDeath", 0, 0, random (0, 360), 2, random (0, 160))
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("XDeathImpArm", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathImpHead", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperGoreSpawner", 22, 0, random (170, 190), 2, random (0, 15));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		T3DD EFGH 6;
		T3DD H -1;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		Stop;
		
	Death.Shotgun:
	Death.Blast:
	Death.Railgun:
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathImpArm", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathImpHead", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		T3DK A 6 A_Stop();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		T3DK BBBBBBBBBB 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (30, 60));
		T3DK CCC 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (10, 40));
		T3DK DD 3 a_spawnprojectile ("Brutal_LiquidBlood2", 6, 0, random (0, 360), 2, random (30, 60));
		T3DK E -1;
		Stop;
}
}

CLASS DyingImpVar32 : SwitchableDecoration { 
	Default {
	

	Radius 16;
	Height 22;
	Health 60;
	PainSound "imp/pain";
	PainChance 255;
	Mass 999999;
	+SHOOTABLE;
	+SOLID;
	-THRUACTORS;
	
	+FLOORCLIP;
	damagefactor "Crush", 50.0;
	Scale 1.0;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	}
	States
	{
	
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_GiveToTarget("HasImpShield", 1);
		TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
		T4DE D 8;
		Stop;
		
	Spawn:
		T4D2 E 1;
		Goto Suffer;
	Suffer:
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 EE 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 E 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 F 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 GG 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 G 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 F 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 EE 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 E 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 F 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 GG 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 G 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 F 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 EE 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 E 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 F 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 GG 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 G 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 EE 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 E 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 F 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 GG 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 G 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 F 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 EE 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 E 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 F 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 GG 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 G 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 F 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 EE 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 E 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 F 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 GG 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D2 G 5 A_Pain();
		
		Goto Death;
		
	Death:
		T4D2 HI 8;
		TNT1 A 1 A_SpawnItem ("DeadImp_NoStomach2", 5);
		Stop;
		
	Death.Head:
	Death.Decaptate:
	Death.MINORHead:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("headex", 0);
		TNT1 AAAA 0 a_spawnprojectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains3", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains6", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains7", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile ("BrainBlood", 36, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		T4D2 JKL 8;
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 A 0 A_SpawnItem ("DeadImp_NoStomachNoHead2", 1);
		Stop;
		
	Death.Arm:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 a_spawnprojectile ("XDeathImpArm", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		T4D9 A 8 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("DyingImpVar3NoArm", 2);
		Stop;
	Death.Plasma: 
	Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		XBRN AA 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedImpArm", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
		
		XBRN BB 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 A 0 a_spawnprojectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		XBRN CC 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		XBRN DEF 4 BRIGHT;
		TNT1 A 0;
		Stop;
		
	Death.Fire:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TRO3 JJJJ 2 a_spawnprojectile ("FlameTrails", 45, 0, random (0, 360), 2, random (50, 130));
		TRO3 KKKK 2 a_spawnprojectile ("FlameTrails", 30, 0, random (0, 360), 2, random (50, 130));
		TRO3 LLLL 2 a_spawnprojectile ("FlameTrails", 25, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0 A_Playsound("props/redfire");
		BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 a_spawnprojectile ("FlameTrails", 15, 0, random (0, 360), 2, random (50, 130));
		BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 10 a_spawnprojectile ("SmallSmoke", 15, 0, random (0, 360), 2, random (70, 110));
		BOSB E -1;
		Stop;
		
	Death.cut:
	Death.cutless:
		TNT1 O 0 A_Jump(230, 2);
		Goto Death;
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TROG A 2 a_spawnprojectile ("RipImp", 0, 0, random (0, 360), 2, random (0, 160));
		TROG AAA 4 A_SpawnItem ("Big_Blood", 0, 30);
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TROG BCDEFGH 8;
		TNT1 A 1 A_SpawnItem ("DeadImp_Half", 5);
		//TROG H -1
		Stop;
		
		
	Death.SSG:
		//TNT1 A 0 a_spawnprojectile ("MeatDeath", 0, 0, random (0, 360), 2, random (0, 160))
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("XDeathImpArm", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathImpHead", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperGoreSpawner", 22, 0, random (170, 190), 2, random (0, 15));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		T3DD EFGH 6;
		T3DD H -1;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		Stop;
		
	Death.Shotgun:
	Death.Blast:
	Death.Railgun:
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathImpArm", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathImpHead", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		T3DK A 6 A_Stop();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		T3DK BBBBBBBBBB 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (30, 60));
		T3DK CCC 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (10, 40));
		T3DK DD 3 a_spawnprojectile ("Brutal_LiquidBlood2", 6, 0, random (0, 360), 2, random (30, 60));
		T3DK E -1;
		Stop;
		
}
}

CLASS DyingImpVar3NoLeg : SwitchableDecoration { 
	Default {
	

	Radius 16;
	Height 25;
	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	Scale 1.0;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	}
	States
	{
	
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_GiveToTarget("HasImpShield", 1);
		TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
		T4DA D 8;
		Stop;
		
	Spawn:
		T4DA D 1;
		TNT1 A 0;
		TNT1 A 0 A_Jump(32, "Colapse");
		Goto Suffer;
	Suffer:
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 22,0);
		T4DA DD 4 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 22,0);
		T4DA D 5 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 22,0);
		T4DA FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 22,0);
		T4DA F 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 22,0);
		T4DA DD 4 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 22,0);
		T4DA D 5 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 22,0);
		T4DA FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 22,0);
		T4DA F 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 22,0);
		T4DA DD 4 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 22,0);
		T4DA D 5 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 22,0);
		T4DA FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 22,0);
		T4DA F 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 22,0);
		T4DA DD 4 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 22,0);
		T4DA D 5 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 22,0);
		T4DA FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 22,0);
		T4DA F 5 A_Pain();
		Goto Colapse;
		
	Death:
		TNT1 A 0 A_PlaySound("imp/death");
		T4DA G 8;
		TNT1 A 0 A_SpawnItem ("DeadImp_NoLeg", 5);
		Stop;
		
	Colapse:
		T4DA H 8;
		TNT1 A 0 A_SpawnItem ("DeadImp_NoLeg", 5);
		Stop;
}
}


CLASS DyingImpVar3NoArm : SwitchableDecoration { 
	Default 
	{
	Radius 16;
	Height 25;
	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 0x7FFFFFFF;
	-SOLID;
	+SHOOTABLE;
	DamageFactor "bloodsplasher", 0.0;    DamageFactor "tinybloodsplasher", 0.0;
    DamageFactor "superbloodsplasher", 0.0;    DamageFactor "smallbloodsplasher", 0.0;
	DamageFactor "BlueBloodSplasher", 0.0;
	DamageFactor "BlueSuperBloodSplasher", 0.0;
	Scale 1.0;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	}
	States
	{
	
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_GiveToTarget("HasImpShield", 1);
		TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
		T4DA D 8;
		Stop;
		
	Spawn:
		T4D9 B 1;
		Goto Suffer;
		
	Suffer:
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 BB 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 B 5;
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 CC 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 C 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 BB 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 B 5;
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 CC 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 C 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 BB 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 B 5;
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 CC 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 C 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 BB 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 B 5;
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 CC 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 C 5 A_Pain();
		
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 BB 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 B 5;
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 CC 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 32,0);
		T4D9 C 5 A_Pain();
		Goto Death;
		
	Death:
		T4D9 D 8;
		TNT1 A 0 A_SpawnItem ("DeadImp_NoArm", 5);
		Stop;
		
	Death.Head:
	Death.Decaptate:
	Death.MINORHead:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 30);
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		T4D9 F 8;
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 A 0 A_SpawnItem ("DeadImp_NoArmNoHead", 1);
		Stop;
		
	Death.Blast:
	Death.SSG:
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathImpArm", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathImpHead", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperGoreSpawner", 22, 0, random (170, 190), 2, random (0, 15));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		IZD1 EFGH 6;
		IZD1 H -1;
		TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
		Stop;
}
}

CLASS ImpVar3BrutalizedWithNoLeg : ACTOR { 
	Default {
	
	Radius 16;
	Height 50;
	Health 20;
	PainSound "grunt/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	Scale 1.0;
	}
	States
	{
	
	Spawn:
		T4DA A 30;
		Goto DieNow;
		
	DieNow:
		T4DA BC 8;
		T4DA DE 8;
		TNT1 A 0 A_SpawnItem ("DeadImp_NoLeg");
		Stop;
		
		
		
	Death:
		TNT1 A 0;
		TNT1 AAAA 0 a_spawnprojectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains3", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains6", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains7", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAA 0 a_spawnprojectile ("BrainBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathImpArm", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		ID17 ABCDEF 5;
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Armor");
		TNT1 A 0 A_SpawnItem ("ThisImpGotFuckedHard");
		Stop;
}}

///////////////////////////======VANILLA======//////////////////////////////////


CLASS Vanilla_DNImpVariant3 : DNImpVariant3 { 
	Default {
	
	DropItem "DemonStrengthRune", 1;
	}
	States
	{
	Spawn:
		TNT1 A 0 ACS_NamedExecuteAlways("CeilingClimbingImps", 0);//Check for CVARs
		TNT1 A 0 A_GiveInventory("SKImp", 1);
		TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim");
		TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim");
		TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
	Stand:
		TROO A 0 A_CheckSight("Spawn2");
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 42,0);
		TRO4 B 10 A_Look();
		TROO A 0 A_CheckSight("Spawn2");
		TNT1 A 0 A_SpawnItem ("HeadshotTarget10", 12, 42,0);
		TRO4 B 10 A_Look();
		Loop;
}
}
