// Impbomination by Gez, Dreadopp, and Damien Daurio
CLASS DNImpVariant2 : pb_imp// Replaces DoomImp
{
Default {
	Health 55;
	Radius 20;
	Speed 11;
	//SpawnID 1420;
	PainChance 200;
	MONSTER;
	+FLOORCLIP;
	Obituary "%o got imped.";
	Tag "Mean Imp";
}

States
{
	////////////////////////////////////////////////////////////////////////////
	Death.Shrink:
		TNT1 A 1 A_PlaySound("Shrink", 3);
/*		TNT1 A 0 A_SpawnItemEx ("DNImpVariant2ShrinkFX1", 0, 0,  5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("DNImpVariant2ShrinkFX2", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("DNImpVariant2ShrinkFX3", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("DNImpVariant2ShrinkFX4", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("DNImpVariant2ShrinkFX5", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("DNImpVariant2ShrinkFX6", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("DNImpVariant2ShrinkFX7", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("LilDNImpVariant2", 1);*/
	stop;
		
	Spawn:
		TNT1 A 0;
		//TNT1 A 0 ACS_ExecuteAlways(796, 0, 0, 0, 0);//Check if Vanilla Mode is activated
		//TNT1 A 1 ACS_NamedExecuteAlways("CeilingClimbingImps", 0);//Check for CVARs
		//TNT1 A 0 A_GiveInventory("SKImp", 1);
		TNT1 A 0 A_JumpIf(waterlevel >= 2, "Swim");
	Stand:
		TRO3 BB 10 A_Look();
	Loop;
		
	Idle:
	LookingForPlayer:
		//TNT1 A 0 A_GiveInventory("SKImp", 1);

		TRO3 B 10 A_Look();

		TRO3 B 10 A_Look();

		TRO3 B 10 A_Look();
		TNT1 A 0 {self.angle -= 40;}

		TRO3 B 10 A_Look();

		TRO3 B 10 A_Look();

		TRO3 B 10 A_Look();
		TNT1 A 0 {self.angle += 40;}

		TRO3 B 10 A_Look();

		TRO3 B 10 A_Look();

		TRO3 B 10 A_Look();
		
		TROO A 0 A_Wander();
		TRO3 AA 2 A_Look();
		TNT1 A 0 A_PlaySound("flesh/step",4);
		TNT1 A 0 A_Recoil(-2);

		
		TROO B 0 A_Wander();
		TRO3 BB 2 A_Look();
		TNT1 A 0 A_Recoil(-2);

		
		TROO C 0 A_Wander();
		TRO3 CC 2 A_Look();
		TNT1 A 0 A_PlaySound("flesh/step",4);
		TNT1 A 0 A_Recoil(-2);

		
		TROO D 0 A_Wander();
		TRO3 DD 2 A_Look();
		TNT1 A 0 A_Recoil(-2);

		
		
		TNT1 A 0 A_jump(128, "LookingForPlayer");
		
		
		TROO A 0 A_Wander();
		TRO3 AA 2 A_Look();
		TNT1 A 0 A_PlaySound("flesh/step",4);
		TNT1 A 0 A_Recoil(-2);

		
		TROO B 0 A_Wander();
		TRO3 BB 2 A_Look();
		TNT1 A 0 A_Recoil(-2);

		
		TROO C 0 A_Wander();
		TRO3 CC 2 A_Look();
		TNT1 A 0 A_PlaySound("flesh/step",4);
		TNT1 A 0 A_Recoil(-2);

		
		TROO D 0 A_Wander();
		TRO3 DD 2 A_Look();
		TNT1 A 0 A_Recoil(-2);

		Goto LookingForPlayer;
		
		
	ForgetTarget:
		TNT1 A 0 A_ClearTarget();
		TNT1 A 0 A_TakeInventory("EnemyMemory", 25);

	Goto Stand;
		
	See:
		//TNT1 A 0 A_JumpIf(vel.Z < 0, "FallingAfterImpact")// funny thing I tried, better not implement
		TNT1 A 0 A_TakeInventory("EnemyMemory", 15);

		TRO3 A 4 A_faceTarget();

		TRO3 B 4;

		TRO3 C 10;

		Goto SeeContinue;
		
		
	CeilingLatch:
		TNT1 A 0 {self.bNOGRAVITY = true;}
		TNT1 A 0 {self.bCEILINGHUGGER = true;}
		TNT1 A 0 {self.bNOVERTICALMELEERANGE = true;}
		//TNT1 A 0 A_GiveInventory ("IsOnCeiling", 1);
		3M40 H 8;
	Goto CeilingCrawl;
		
	CeilingJump:
		TNT1 A 0;
		////TNT1 A 0 A_JumpIf(CallACS("GetActorZDist") <= 120, 2);
		TNT1 AAA 0;
		////TNT1 A 0 A_JumpIf(CallACS("IsThisSky") == 1, "SeeContinue");
		TNT1 A 0 A_PlaySound("imp/sight",6);
		1M43 A 6;
		//TNT1 A 0 A_giveInventory ("IsJumping");
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		5M40 AAAA 1 A_CheckCeiling("CeilingLatch");
		TNT1 A 0 ThrustThingZ(0,45,0,1);
		5M40 BBBBCCCC 1 A_CheckCeiling("CeilingLatch");
		TNT1 A 0 ThrustThingZ(0,45,0,1);
		5M40 DDDDEEEE 1 A_CheckCeiling("CeilingLatch");
		TNT1 A 0 ThrustThingZ(0,45,0,1);
		5M40 FFFFGGGG 1 A_CheckCeiling("CeilingLatch");
		1M43 EEEEEEEEEEEEEEE 1 A_CheckFloor("SeeContinue");
		//TNT1 A 0 A_TakeInventory ("IsJumping");
		Goto SeeContinue;
		
	CeilingLatch:
		TNT1 A 0 {self.bNOGRAVITY = true;}
		TNT1 A 0 {self.bCEILINGHUGGER = true;}
		TNT1 A 0 {self.bNOVERTICALMELEERANGE = true;}
		//TNT1 A 0 A_GiveInventory ("IsOnCeiling", 1);
		5M40 H 8;
		Goto CeilingCrawl;
		
	CeilingCrawl:

		//TNT1 A 0 A_JumpIf(vel.Z < 0, "FallingAfterImpact")// funny thing I tried, better not implement
		
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		TNT1 A 0 A_JumpIf(waterlevel >= 2, "Swim");


		//TNT1 A 0 A_JumpIf(CallACS("IsThisSky") == 1, "CeilingPounce");
		//TNT1 A 0 A_JumpIf(vel.z > 0 || vel.z < 0, "CeilingPounce")
		5M40 II 2 A_Chase("CeilingPounce", "CeilingMissile");
		//ContinueCeilingCrawl1:
		TNT1 A 0 A_Recoil(-1);


		5M40 II 2 A_Chase("CeilingPounce", "CeilingMissile");
		TNT1 A 0 A_PlaySound("flesh/step",4);
		//TNT1 A 0 A_TakeInventory("SKImp", 1);
		//ContinueCeilingCrawl2:


		5M40 JJ 2 A_Chase("CeilingPounce", "CeilingMissile");
		TNT1 A 0 A_PlaySound("flesh/step",4);
		//ContinueCeilingCrawl3:


		5M40 JJ 2 A_Chase("CeilingPounce", "CeilingMissile");
		//TNT1 A 0 A_JumpIf(CallACS("IsThisSky") == 1, "CeilingPounce");
		//TNT1 A 0 A_JumpIf(vel.z > 0 || vel.z < 0, "CeilingPounce")
		TNT1 A 0 A_PlaySound("flesh/step",4);
		//ContinueCeilingCrawl4:


		5M40 KK 2 A_Chase("CeilingPounce", "CeilingMissile");
		TNT1 A 0 A_PlaySound("flesh/step",4);
		//ContinueCeilingCrawl5:


		5M40 KK 2 A_Chase("CeilingPounce", "CeilingMissile");
		//TNT1 A 0 A_JumpIf(CallACS("IsThisSky") == 1, "CeilingPounce");
		//TNT1 A 0 A_JumpIf(vel.z > 0 || vel.z < 0, "CeilingPounce")
		//ContinueCeilingCrawl6:


		5M40 HH 2 A_Chase("CeilingPounce", "CeilingMissile");
		TNT1 A 0 A_PlaySound("flesh/step",4);
		//ContinueCeilingCrawl7:


		5M40 HH 2 A_Chase("CeilingPounce", "MaybeCeilingPounce");
		//TNT1 A 0 A_JumpIf(CallACS("IsThisSky") == 1, "CeilingPounce");
		//TNT1 A 0 A_JumpIf(vel.z > 0 || vel.z < 0, "CeilingPounce")
		Loop;
		
	CeilingMissile:


		5M40 L 4 A_FaceTarget();
		TNT1 A 0 A_JumpIfCloser(150, "CeilingPounce");
		TNT1 A 0 A_Playsound ("IMPCHARG");
		TNT1 A 0 a_spawnprojectile ("FlameTrails", 25, -30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 25, -30, random (0, 140), 2, random (0, 160));
		5M40 L 2 A_FaceTarget();
		
		TNT1 A 0 a_spawnprojectile ("FlameTrails", 25, -30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 25, -30, random (0, 140), 2, random (0, 160));
		5M40 L 2 A_FaceTarget();

		TNT1 A 0 a_spawnprojectile ("FlameTrails", 25, -30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 25, -30, random (0, 140), 2, random (0, 160));
		5M40 L 2 A_FaceTarget();


		TNT1 A 0 a_spawnprojectile ("FlameTrails", 25, -30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 25, -30, random (0, 140), 2, random (0, 160));
		5M40 L 2 A_FaceTarget();


		TNT1 A 0 a_spawnprojectile ("FlameTrails", 25, -30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 25, -30, random (0, 140), 2, random (0, 160));
		5M40 L 2 A_FaceTarget();


		TNT1 A 0 a_spawnprojectile ("FlameTrails", 25, -30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 25, -30, random (0, 140), 2, random (0, 160));
		5M40 M 2 A_FaceTarget();


		5M40 N 6 a_spawnprojectile("pb_imp_fireball", 22, 0, 0, 0);
		5M40 M 4;
	Goto CeilingCrawl;

	MaybeCeilingPounce:
		TNT1 A 0 A_Jump(28, 3);
		Goto CeilingCrawl;
	CeilingPounce:
		TNT1 AAA 0;
		//TNT1 A 0 A_TakeInventory ("IsOnCeiling");
		TNT1 A 0 {self.bNOGRAVITY = false;}//CEILINGHUGGER
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Recoil (-18);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_PlaySound("weapons/fistwhoosh");
		TNT1 A 0 a_spawnprojectile("ImpAttack2",10,0,0,0);
		5M40 CDEFG 4 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("ImpAttack2",10,0,0,0);
		1M43 EEE 1 a_spawnprojectile("ImpAttack2",10,0,0,0);
		//TNT1 A 0 A_TakeInventory ("IsJumping");
		TNT1 A 0 A_Jump(24, 3);
		1M43 A 6;
	Goto SeeContinue;
		TNT1 AAA 0;
	Goto Melee+1;
		
	SeeContinue:
		//TNT1 A 0 A_JumpIf(vel.Z < 0, "FallingAfterImpact")// funny thing I tried, better not implement
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim");
		TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim");
		TNT1 A 0 A_JumpIfInventory("EnemyMemory", 25, "ForgetTarget");
		TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
		TRO3 AA 2 A_Chase();
		TNT1 A 0 A_Recoil(-1);
		TRO3 AA 2 A_Chase();
		TNT1 A 0 A_PlaySound("flesh/step",4);
		//TNT1 A 0 A_TakeInventory("SKImp", 1);
		TRO3 BBBBCCCC 2 A_Chase();
		TNT1 A 0 A_PlaySound("flesh/step",4);
		TRO3 DDDD 2 A_Chase();

		TNT1 A 0 A_Jump(224, 3);
		//TNT1 A 0 A_JumpIfCloser(800, "CeilingJump");
		TNT1 AAAAA 0;
	Loop;
		////////////////////////////////////////////////////////////////////////////
		
	Melee:
		TNT1 A 0 A_Jump(128, "Melee3");
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_PlaySound("imp/sight",6);
		TNT1 A 0 A_Recoil (-2);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_JumpIfCloser(60, "Melee2");
		//TNT1 A 0 A_TakeInventory("SKImp", 1);
		TNT1 A 0 ThrustThingZ(0,35,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil (-11);
		TRO3 EF 4 A_FaceTarget();
		//TNT1 A 0 A_giveInventory ("IsJumping");
		TNT1 A 0 A_PlaySound("weapons/fistwhoosh");
		TNT1 A 0 A_FaceTarget();
		TRO3 G 4 a_spawnprojectile("ImpAttack2",10,0,0,0);
		//TNT1 A 0 A_TakeInventory ("IsJumping");
		TRO3 GE 4;

		TRO3 G 4 a_spawnprojectile("ImpAttack2",10,0,0,0);
	Goto SeeContinue;
		
		
		
	Melee2:

		TRO3 EF 4 A_FaceTarget();
		//TNT1 A 0 A_TakeInventory("SKImp", 1);

		TRO3 G 4 a_spawnprojectile("ImpAttack",10,0,0,0);

		TRO3 GE 4;
		Goto SeeContinue;
		
	Melee3:
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_PlaySound("imp/sight",6);
		1M43 ABCD 4 A_Recoil (-3);
		1M43 A 5 A_FaceTarget();
		TNT1 A 0 A_JumpIfCloser(60, "Melee2");
		//TNT1 A 0 A_TakeInventory("SKImp", 1);
		TNT1 A 0 ThrustThingZ(0,26,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil (-9);
		1M43 E 6;
		//TNT1 A 0 A_giveInventory ("IsJumping");
		TNT1 A 0 A_PlaySound("weapons/fistwhoosh");
		TNT1 A 0 A_FaceTarget();
		1M43 E 4 a_spawnprojectile("ImpAttack2",10,0,0,0);
		//TNT1 A 0 A_TakeInventory ("IsJumping");

		1M43 A 4 a_spawnprojectile("ImpAttack2",10,0,0,0);
	Goto SeeContinue;
		
		
	Missile:
		TNT1 A 0 A_JumpIfCloser(150, "Melee");
		//TNT1 A 0 A_TakeInventory("SKImp", 1);


		TRO3 E 2 A_FaceTarget();

		TNT1 A 0 A_Playsound ("IMPCHARG");
		TNT1 A 0 a_spawnprojectile ("FlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
		TRO3 E 2 A_FaceTarget();
		
		TNT1 A 0 a_spawnprojectile ("FlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
		TRO3 E 2 A_FaceTarget();

		TNT1 A 0 a_spawnprojectile ("FlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
		TRO3 E 2 A_FaceTarget();


		TNT1 A 0 a_spawnprojectile ("FlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
		TRO3 E 2 A_FaceTarget();

		TNT1 A 0 a_spawnprojectile ("FlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
		TRO3 E 2 A_FaceTarget();

		TNT1 A 0 a_spawnprojectile ("FlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("ImBallGettingReady", 35, 30, random (0, 140), 2, random (0, 160));
		
		TNT1 A 0 A_Jump(100, "specialattack");
		
		TRO3 F 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile ("FlameTrails", 35, 30, random (0, 40), 2, random (0, 160));
		TRO3 G 6 A_CustomComboAttack("SmallImpBall",32,2,"gauntimp/meleehit");
	Goto SeeContinue;
		
	SpecialAttack:
		TRO3 F 2 A_FaceTarget();
		TRO3 G 6 a_spawnprojectile("SmallImpBall", 34, 0, 0, 0);
		TRO3 F 4;
		TRO3 F 2 A_FaceTarget();
		TRO3 G 6 a_spawnprojectile("SmallImpBall", 34, 0, 0, 0);
	Goto SeeContinue;
		
	Pain:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		////TNT1 A 0 A_JumpIfInventory("IsOnCeiling", 1, "PainCanFallFromCeiling");
		//TNT1 A 0 A_TakeInventory("SKImp", 1);
		TRO3 H 2;
		TRO3 H 2 A_Pain();
	Goto SeeContinue;
		
	Pain.Melee:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		//TNT1 A 0 A_JumpIfInventory ("SKImp", 1, "GotoStealthKill");

		TRO3 H 2;
		TRO3 H 2 A_Pain();
		Goto SeeContinue;
		
	GotoStealthKill:
		TNT1 A 1;
		//TNT1 A 0 A_GiveToTarget("SKImp2");
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 1 A_Die("Stealthy");
	Stop;

	Death.Stealthy:
		TNT1 A 0 A_NoBlocking();
		Stop;
		
	Pain.head:
	Pain.minorhead:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		//TNT1 A 0 A_JumpIfInventory("IsOnCeiling", 1, "PainCanFallFromCeiling");

		//TNT1 A 0 A_TakeInventory("SKImp", 1);
		TRO3 H 6;
		TRO3 H 6 A_Pain();
	Goto SeeContinue;
		
	Pain.Stun:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_SpawnItemEx ("StunElectrocute", random (-4, 4), random (-4, 4),  random (16, 32), 0, 0);
		TRO3 H 1 A_Pain();
		TRO3 HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		TRO3 H 1 A_Pain();
		TRO3 HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		TRO3 H 1 A_Pain();
		TRO3 HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		TRO3 H 1 A_Pain();
		TRO3 HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		TRO3 H 1 A_Pain();
		TRO3 HHHHHHHHHH 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		TRO3 H 1 A_Pain();
		Goto See;
		
	Death.Ice:
	Death.Freeze:
	Death.Frost:
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		//TNT1 A 0 A_SpawnItem("FrozenImpVar2");
	Stop;
		
	Raise:
		TROO M 8;
		T3DF D 8;
		T3DF CBA 6;
	Goto SeeContinue;
		
	Pain.ExplosiveImpact:
	Pain.Explosive:
	Pain.ExtremePunches:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
		//TNT1 A 0 A_TakeInventory("SKImp", 1);
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		T3D6 KL 8;
		Goto FallingAfterImpact;
		
	Pain.Kick:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		T3D6 K 1 A_Pain();
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		T3D6 K 1 A_facetarget();
		T3D6 K 6 ThrustThing(angle*256/360+128, 5, 0, 0);
		T3D6 L 8;
		Goto FallingAfterImpact;
		
	FallingAfterImpact:
		T3D6 L 1 A_GiveInventory ("FallingHeight", 1);
		TNT1 A 0 A_JumpIf(waterlevel >= 2, "Swim");
		T3D6 L 1 A_CheckFloor ("GetUp");
		TNT1 A 0 {self.bNOPAIN = false;}
		NULL A 0 A_JumpIf (vel.z == 0, "GetUp");
		Loop;
		
	PainCanFallFromCeiling:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		//TNT1 A 0 A_TakeInventory ("IsOnCeiling");
	FallingAfterImpact:
		T3D6 L 1 A_GiveInventory ("FallingHeight", 1);
		TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim");
		TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim");
		T3D6 L 1 A_CheckFloor ("GetUp");
		TNT1 A 0 A_JumpIf (vel.z == 0, "GetUp");
		Loop;
		
	GetUp:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("LargeMassWaterImpact");
		TNT1 A 0 A_SpawnItem("Underwater_Explosion");
		TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim");
		TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim");
		TNT1 A 0 {self.bGHOST = true;}
		TNT1 A 0 {self.bNOPAIN = false;}
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 {self.bFORCEXYBILLBOARD = true;}
		TNT1 A 0 A_GiveInventory("ISDOWN", 1);
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 6, "FallingDie");
		T3D6 MMMMMMMM 5 A_JumpIf(vel.z < 0, "FallingAfterImpact");
		TNT1 A 0 {self.bSOLID = true;}
		TNT1 A 0 A_TakeInventory("ISDOWN", 1);
		TNT1 A 0 {self.bFORCEXYBILLBOARD = false;}
		TNT1 A 0 A_TakeInventory("FallingHeight", 100);
		TNT1 A 0 A_TakeInventory("IsDown", 1);
		T3D6 NO 7;
	Goto SeeContinue;
		
	PainHurt:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		//TNT1 A 0 A_TakeInventory("SKImp", 1);
		TRO3 H 1;
		TRO3 H 1 A_Pain();
	Goto SeeContinue;
		
	Pain.BlackHole:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		T3D6 K 1 A_Pain();
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,6,0,1);
		T3D6 K 1 A_facetarget();
		T3D6 K 6 ThrustThing(angle*256/360+128, 5, 0, 0);
		T3D6 L 8;
	Goto FallingAfterImpact;
		
	Death.MinorLeg:
		TNT1 A 0;
		TNT1 A 0 A_Jump(48, "Death.Leg");
		Goto Death+5;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		//TNT1 A 0 A_JumpIfInventory("IsJumping", 1, "DeathJump");
		TNT1 A 0 A_Jump(32, "Death.Arm");
		TNT1 A 0 A_Jump(24,"DeathNoGuts");
		TNT1 A 0 A_Jump(32,"Death20alt");
		TNT1 A 0 A_Jump(128, "DeathMirror");
		T3DF A 8;
		T3DF B 8 A_Scream();
		T3DF C 6;
		T3DF D 6 A_NoBlocking();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadImp1");
	Stop;
		
	Death.Down:
	Death.Trample:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Stop();
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 2, 0, random (0, 360), 2, random (0, 40));
		T3DH DC 6;
		TNT1 A 0 A_SpawnItem("DeadImp1");
	Stop;

	Death.Incinerate:
		TNT1 A 0;
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_Playsound("MELT");
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAAA 0 a_spawnprojectile ("ExplosionParticle", 32, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAA 0 a_spawnprojectile ("ExplosionParticle", 32, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,32,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-15, 15), random (-15, 15));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-35, 35), random (-35, 35));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-45, 45), random (-45, 35));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile ("Ashes1", 28, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile ("Ashes2", 40, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),32,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB AAAAA 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionParticle", 36, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),28,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB BBBBB 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionParticle", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),24,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB CCCCC 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionParticle", 28, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Playsound("SZZLL", 3);
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),20,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB DDDDD 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionParticle", 20, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),16,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB EEEEE 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionParticle", 12, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),12,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB FFFFF 1 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionParticle", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		TNT1 A 0 A_SpawnItem("Barrel_explosion_Column");
		T6SB GGGG 2 BRIGHT Light("IncinerationGlow");
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB HHIIHHIIHHIIHHII 2 BRIGHT Light("IncinerationGlow") a_spawnprojectile ("ExplosionSmoke", 14, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB HHIIHHIIHHIIHHII 2 Light("IncinerationGlow") a_spawnprojectile ("ExplosionSmoke", 14, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		T6SB HHIIHHIIHHIIHHII 2;
		T6SB JJJJJJJ 12 a_spawnprojectile ("ExplosionSmoke", 14, 0, random (0, 360), 2, random (0, 160));
		T6SB J -1;
	Stop;
		
	Death.fire:
	Death.Flames:
	Death.Burn:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		//TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("BurningImpRunning", 0, 10);
	Stop;
		
	Death20alt:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		T3DB ABCD 6;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItemEx ("ImpVar2DyingOfBloodLoss", 0,0,7,0,0,0,0,SXF_NOCHECKPOSITION,0);
	Stop;
		
	Death.Arm:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 a_spawnprojectile ("XDeathImpArm", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Jump(110, "Arm2");
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		T3D9 A 8 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("DyingImpVar2NoArm", 2);
		Stop;
		
	Arm2:
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		T3D8 A 8 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("DyingImpVar2NoArm2", 2);
		Stop;
		
	Death.Leg:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Jump(64, "DeathLeg2");
		//TNT1 A 0 A_JumpIfInventory("IsJumping", 1, "Death.LegInTheAir");
		TNT1 A 0 a_spawnprojectile ("XDeathImpLeg", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		T3DA A 9;
		T3DA A 3 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		T3DA B 3 A_Scream();
		T3DA C 3 A_NoBlocking();
		TNT1 A 0 A_SpawnItem ("DyingImpVar2NoLeg", 5);
		Stop;
		
	DeathLeg2:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Fall();
		TNT1 A 0 a_spawnprojectile ("XDeathImpLeg", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		//TNT1 A 0 A_SpawnItem("ImpVar2SaciLol");
	Stop;
		
	DeathJump:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Stop();
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 {self.bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil (10);
		T3DH A 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		T3DH A 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		T3DH B 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		T3DH B 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		T3DH C 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		T3DH C 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		T3DH D 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		T3DH D 4 a_spawnprojectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadImp1");
	Stop;
		
	TakeASit:
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		T3DH B 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItemEx("DeadImpVar2_Slumped", 10);
		Stop;
		
	Death.Melee:
	Death.Kick: 
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil (8);
		T3DI ABCD 8;
		TNT1 A 1 A_SpawnItem ("DeadImp1MeleeDeath", 5);
		Stop;
		
	Death.cut:
	Death.HKFT:
	Death.Saw:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Jump(48, "Death.Arm", "Death");
		TNT1 A 0 A_Jump(32,"DeathNoGuts");
	Goto Death.Tear;
		
	Death.cutless:
		TNT1 A 0;
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
		TNT1 A 0 A_Jump(42,"DeathNoGuts");
		TNT1 A 0 A_Jump(16, "Death");
		TNT1 A 0 A_Jump(16, "Death.LegMassacre");
		Goto Death.Minigun;
		
	Death.Minigun:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Scream();
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem ("BrutalizedImpVar2", 1);
		Stop;
		
	Death.LegMassacre:
		TNT1 A 0 a_spawnprojectile ("XDeathImpLeg", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		T3DA A 8 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		T3DA B 8 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem ("ImpVar2BrutalizedWithNoLeg");
		Stop;
		
	Death.Tear:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Jump(128, "Tear2", "Tear3", "Tear4");
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TROG A 2 a_spawnprojectile ("RipImp", 0, 0, random (0, 360), 2, random (0, 160));
		TROG AAA 4 A_SpawnItem ("Big_Blood", 0, 30);
		TROG BCDEFGH 8;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 1 A_SpawnItem ("DeadImp_Half", 5);
		Stop;
		
	Tear2:
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		T3D7 A 3;
		T3D7 A 1 A_PlaySound("misc/xdeath4f", 9);
		T3D7 BBB 2 a_spawnprojectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		T3D7 CCC 2 a_spawnprojectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath2", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath5", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("xdeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("xdeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("LivingHeart", 32, 0, random (170, 190), 2, random (0, 40));
		T3D7 DDD 2 a_spawnprojectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		T3D7 EEE 2 a_spawnprojectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		T3D7 FFF 2 a_spawnprojectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		T3D7 GGG 2 a_spawnprojectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("DeadImpT5SWG");
		Stop;
		
	Tear3:
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		T3D5 ABC 4 a_spawnprojectile ("MuchBlood", 45, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("xdeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("xdeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("LivingHeart", 32, 0, random (170, 190), 2, random (0, 40));
		T3D5 DDDDDDDDDD 1 a_spawnprojectile ("Brutal_LiquidBlood2", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("RipImp", 0, 0, random (0, 360), 2, random (0, 160));
		T3D5 EEEEEEEEEE 1 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (0, 160));
		T3D5 FFFFFFFFFF 1 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 8, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 8, 0, random (150, 210), 2, random (0, 40));
		T3D5 GGGGGGGG 1 a_spawnprojectile ("Brutal_LiquidBlood2", 9, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		T3D5 HHHHHHHHHHHHH 1 a_spawnprojectile ("Brutal_LiquidBlood2", 6, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("DeadImpIXD1H");
		Stop;
		
	DeathNoGuts:
		TNT1 AAAAA 0;
		TNT1 A 0 A_Jump(120, "DeathNoGuts2");
		TNT1 AA 0 a_spawnprojectile ("Instestin", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 30, 0, random (0, 360), 2, random (0, 160));
		T3D3 A 8 A_Scream();
		T3D3 B 8 A_NoBlocking();
		T3D3 C 8;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DyingImpVar2", 2);
		Stop;
		
	DeathNoGuts2:
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 28, 0, random (150, 210), 2, random (0, 40));
		T3D2 C 8;
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 30, 0, random (0, 360), 2, random (0, 160));
		T3D2 D 8 A_Scream();
		T3D2 E 8 A_NoBlocking();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DyingImpVar22", 2);
		Stop;
	}
}

CLASS DeadImpVar2_Slumped: pb_blood_and_gore_base { 
Default {
	+NOPAIN;
	Health 200;
	DamageFactor "Head", 15.0;
	Height 22;
	Radius 8;
}

States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Recoil(6);
		T3D1 A 6;
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");

		T3D1 A 16;
		Loop ;
	LayDown:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("DeadImp1");
		Stop;
		
	XDeath:
	Death.Explosives:
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ZombieXDeath");
		Stop;
		
	Death.Head:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItemEx("ImpHeadExplode", 0, 0, 22);
		TNT1 A 0 A_SpawnItem("DeadImpVar2_Slumped_NoHead");
		Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 AA 0 a_spawnprojectile ("XDeathImpArm", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnItemEx("ImpHeadExplode", 0, 0, 22);
		TNT1 A 0 A_SpawnItem("DeadImpJustLegsAreLeft");
	Stop;
}}
	
	
CLASS DeadImpVar2_Slumped_NoHead: pb_blood_and_gore_base { 
Default
{
	+NOPAIN;
	Height 22;
}

States
{
	Spawn:
		TNT1 A 0;
		T3D1 B 100;
	Loop ;

	XDeath:
	Death.Explosives:
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ZombieXDeath");
	Stop;

	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 AA 0 a_spawnprojectile ("XDeathImpArm", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnItem("DeadImpJustLegsAreLeft");
	Stop;
}

}

CLASS ImpVar2DyingOfBloodLoss: DNImpVariant2 { 
Default
{
	Radius 16;
	Height 28;
	Health 10;
	+NOPAIN;
	-COUNTKILL;
	+SHOOTABLE;
	//DropItem "None";
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
}

States
{
	
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
	Use:
		TNT1 A 1 A_FaceTarget();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_GiveToTarget("HasImpShield", 1);
		//TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
		Stop;
		
	Spawn:
		T3DB E 1;
		T3DB EFEFEFEFEFEFEFEFEFEFEFEF 10;
		Goto Colapse;
	Death:
		TNT1 A 0;
		Goto DeathNoGuts;
		
	Death.Shotgun:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfCloser(150, "Death.Shotgunontheface");
		Goto DeathNoGuts;
		
	Colapse:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		T3D1 GHIJ 5;
		TNT1 A 0 A_SpawnItem ("DeadImpBloodLoss", 5);
	Stop;
}
}



CLASS DyingImpVar2 : SwitchableDecoration { 
Default
{
	Radius 16;
	Height 22;
	Health 60;
	PainSound "imp/pain";
	PainChance 255;
	Mass 999999;
	+SHOOTABLE;
	+SOLID;
	-THRUACTORS;
	
	+FLOORCLIP;
	damagefactor "Crush", 50.0;
	Scale 1.0;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
}

States
{
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_GiveToTarget("HasImpShield", 1);
		//TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
		T3DE D 8;
		Stop;
		
	Spawn:
		T3DE D 1;
		Goto Suffer;
	Suffer:

		T3DE DDDDD 2 a_spawnprojectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));

		T3DE D 2;
		T3DE EEEEE 2 a_spawnprojectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));

		T3DE E 2 A_Pain();
		T3DE DDDDD 2 a_spawnprojectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));

		T3DE D 2;
		T3DE EEEEE 2 a_spawnprojectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));
		T3DE E 2 A_Pain();
		T3DE DDDDD 2 a_spawnprojectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));
		T3DE D 2;
		T3DE EEEEE 2 a_spawnprojectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));
		T3DE E 2 A_Pain();
		T3DE DDDDD 2 a_spawnprojectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));
		T3DE D 2;
		T3DE EEEEE 2 a_spawnprojectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));
		T3DE E 2 A_Pain();
	Death:
		T3DE FG 8;
		TNT1 A 1 A_SpawnItem ("DeadImp_NoStomach", 5);
	Stop;
		
	Death.Head:
	Death.Decaptate:
	Death.MINORHead:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 30);
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		T3D3 JJJJJJJJJJJJJJJJJJJ 2 a_spawnprojectile ("Brutal_LiquidBlood", 32, 0, random (0, 360), 2, random (0, 45));
		T3D3 KKKK 2 a_spawnprojectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));
		//TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		T3D3 LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 2 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
		T3D3 L -1;
		Stop;
		
	Death.Plasma: Death.Plasma2:
		TNT1 A 0 {self.bNOGRAVITY = false;}
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		TNT1 A 0 {self.bCEILINGHUGGER = false;}
		TNT1 A 0 A_Jump(96, "OtherPlasmaDeath");
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_PlaySound("plasmaflesh");
		TNT1 AAAAAAAAA 0 a_spawnprojectile ("Ashes1", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAA 0 a_spawnprojectile ("Ashes2", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1Blue",random(-2,2),random(-2,2),18,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		TNT1 AAAA 0 a_spawnprojectile ("BluePlasmaFire", 42, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAA 0 a_spawnprojectile ("BloodMistBig", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAA 0 a_spawnprojectile ("SuperGoreMistSmall", 32, 0, random (0, 360), 2, random (10, 90));
		TNT1 AAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (0, 360), 2, random (0, 180));
		PBR1 B 6 A_NoBlocking();
		TNT1 A 0 A_SpawnItemEx ("RealisticFireSparks1Blue",random(-2,2),random(-2,2),10,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		TNT1 A 0 A_SpawnItemEx ("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItem("Barrel_explosion_Column");
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-15, 15), random (-15, 15));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-35, 35), random (-35, 35));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-45, 45), random (-45, 35));
		PBR1 CCDD 3 a_spawnprojectile ("BluePlasmaFire", 32, 0, random (0, 360), 2, random (0, 180));
		PBR1 EEFF 3;
		PBR1 GG 3;
		PBR1 H -1;
	Stop;
	
	OtherPlasmaDeath:
		IMPP A 6 A_PlaySound("plasmaflesh");
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("Ashes1", 33, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAA 0 a_spawnprojectile ("BluePlasmaFire", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("Ashes2", 31, 0, random (0, 360), 2, random (0, 180));
		IMPP B 6 A_NoBlocking();
		TNT1 AAAAAAA 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 a_spawnprojectile ("Brains1", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAA 0 a_spawnprojectile ("Brains7", 52, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile ("BrainBlood", 50, 0, random (0, 360), 2, random (0, 160));
		IMPP CDE 6;
		IMPP FFFFFFFFFFFFFFFFFFFFFFFFFFFFF 8 a_spawnprojectile ("ExplosionSmoke", 10, 0, random (0, 360), 2, random (0, 160));
		IMPP F -1;
	stop;
	
	Death.Fire:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TRO3 JJJJ 2 a_spawnprojectile ("FlameTrails", 45, 0, random (0, 360), 2, random (50, 130));
		TRO3 KKKK 2 a_spawnprojectile ("FlameTrails", 30, 0, random (0, 360), 2, random (50, 130));
		TRO3 LLLL 2 a_spawnprojectile ("FlameTrails", 25, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0 A_Playsound("props/redfire");
		BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 a_spawnprojectile ("FlameTrails", 15, 0, random (0, 360), 2, random (50, 130));
		BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 10 a_spawnprojectile ("Explosion_Smoke", 15, 0, random (0, 360), 2, random (70, 110));
		BOSB E -1;
	Stop;
	
	Death.cut:
	Death.cutless:
		TNT1 O 0 A_Jump(230, 2);
	Goto Death;
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TROG A 2 a_spawnprojectile ("RipImp", 0, 0, random (0, 360), 2, random (0, 160));
		TROG AAA 4 A_SpawnItem ("Big_Blood", 0, 30);
		////TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TROG BCDEFGH 8;
		TNT1 A 1 A_SpawnItem ("DeadImp_Half", 5);
		//TROG H -1
	Stop;
	
	
	Death.SSG:
		//TNT1 A 0 a_spawnprojectile ("MeatDeath", 0, 0, random (0, 360), 2, random (0, 160))
		//TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 a_spawnprojectile ("XDeathImpArm", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathImpHead", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperGoreSpawner", 22, 0, random (170, 190), 2, random (0, 15));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		T3DD EFGH 6;
		T3DD H -1;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
	Stop;
	
	Death.Shotgun:
	Death.Blast:
	Death.Railgun:
		TNT1 A 0 A_XScream();
		//TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathImpArm", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 a_spawnprojectile ("XDeathImpHead", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		T3DK A 6 A_Stop();
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		T3DK BBBBBBBBBB 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (30, 60));
		T3DK CCC 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (10, 40));
		T3DK DD 3 a_spawnprojectile ("Brutal_LiquidBlood2", 6, 0, random (0, 360), 2, random (30, 60));
		T3DK E -1;
	Stop;
}
}


CLASS BrutalizedImpVar2 : SwitchableDecoration
{ 
Default
{
	Radius 16;
	Height 50;
	Health 20;
	PainSound "grunt/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	+NORADIUSDMG;
	Scale 1.0;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
}

States
{
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_GiveToTarget("HasImpShield", 1);
		//TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
		T3DE D 8;
	Stop;
	
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Recoil(2);
		TNT1 A 0 a_spawnprojectile ("XDeathImpArm", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		Pain:
		T3DD A 30;
	Goto DieNow;
	
	DieNow:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem ("BrutalizedImpVar2Stop");
	Stop;
	
	Death:
		TNT1 A 0;
		TNT1 AAAA 0 a_spawnprojectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains2", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains3", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains6", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains7", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile ("BrainBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Recoil(2);
		T3DD B 16;
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem ("BrutalizedImpVar22");
	Stop;
	
	Death.SSG:
	XDeath:
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile ("ImpXDeath", 0, 0, random (0, 360), 2, random (0, 160));
	Stop;
}}

CLASS BrutalizedImpVar2Stop: pb_blood_and_gore_base { 
Default
{
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	damagefactor "Melee", 10.0;
	damagefactor "Fatality", 10.0;
	damagefactor "Kick", 10.0;
}

States
   {
	Spawn:
		IZD2 ABC 5 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
		IZD3 D -1;
	Stop;
	
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	Death.Extremepunches:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		//IZD2 B 7
		TNT1 A 1 A_SpawnItem ("BrutalizedImpVar2Stop", 5);
	Stop;
}}

CLASS BrutalizedImpVar22: BrutalizedSergeant1
{ 
States
{
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_GiveToTarget("HasImpShield", 1);
		//TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
		T3DD B 8;
	Stop;
	
	Spawn:
	Pain:
	T3DD B 30;
	Goto DieNow;
	
	DieNow:
	TNT1 A 0;
	TNT1 A 0 A_SpawnItem ("BrutalizedImpVar2Stop2");
	Stop;
	
	Death:
	TNT1 A 0;
	TNT1 A 0 A_Recoil(2);
	TNT1 A 0 a_spawnprojectile ("XDeathImpArm", 35, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0;
	T3DD C 16;
	TNT1 A 0 A_SpawnItem ("BrutalizedImpVar23");
	Stop;
	
}}

CLASS BrutalizedImpVar2Stop2: BrutalizedImpVar2Stop { 
    States
    {
	Spawn:
	IZD4 AB 6 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
	IZD4 B -1;
	Stop;
	
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	Death.Extremepunches:
	TNT1 A 0;
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,30,0,1);
	IZD4 A 7;
	TNT1 A 1 A_SpawnItem ("BrutalizedImpVar2Stop2", 5);
	Stop;
}}

CLASS BrutalizedImpVar23: BrutalizedImpVar2 { 
	States
	{
	Spawn:
	Pain:
	T3DD C 25;
	Goto DieNow;
	
	DieNow:
	TNT1 A 0;
	TNT1 A 0 A_SpawnItem ("BrutalizedImpVar2Stop3");
	Stop;
	
	Death:
	TNT1 A 0;
	TNT1 A 0 A_Recoil(2);
	TNT1 A 0 A_SpawnItem("BloodSplasher2");
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("XDeath3b", 40, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath4", 40, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath2b", 40, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAAAA 0 a_spawnprojectile ("Brutal_LiquidBlood", 44, 0, random (0, 360), 2, random (0, 50));
	T3DD EFGH 6;
	//TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
	T3DD H -1;
	Stop;
}}


CLASS BrutalizedImpVar2Stop3: BrutalizedImpVar2Stop { 
	Default {
	
	}
	States
	{
	Spawn:
	IZD3 ABC 6 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
	IZD3 C -1;
	Stop;
	
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	Death.Extremepunches:
	TNT1 A 0;
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,15,0,1);
	TNT1 A 0 A_FaceTarget();
	IZD3 B 7;
	TNT1 A 1 A_SpawnItem ("BrutalizedImpVar2Stop3", 5);
	Stop;
	
}}

	
CLASS ImpVar2BrutalizedWithNoLeg : pb_blood_and_gore_base { 
	Default {
	Radius 16;
	Height 50;
	Health 20;
	PainSound "grunt/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	Scale 1.0;
}

States
{
	Spawn:
		T3DA A 30;
	DieNow:
		T3DA BC 8;
		T3DA DE 8;
		TNT1 A 0 A_SpawnItem ("DeadImp_NoLeg");
	Stop;
	
	Death:
		TNT1 A 0;
		TNT1 AAAA 0 a_spawnprojectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains3", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains6", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("Brains7", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAA 0 a_spawnprojectile ("BrainBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathImpArm", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		ID17 ABCDEF 5;
		//TNT1 A 0 A_SpawnItem ("CrueltyBonus5Armor");
		//TNT1 A 0 A_SpawnItem ("ThisImpGotFuckedHard");
	Stop;
}

}


CLASS DyingImpVar2NoArm : SwitchableDecoration
{
Default {
	Radius 16;
	Height 32;
	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	Scale 1.0;
}

States
{
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
	TNT1 A 0 A_FaceTarget();
	TNT1 A 0 A_NoBlocking();
	//TNT1 A 0 A_GiveToTarget("HasImpShield", 1);
	//TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
	T3D9 B 8;
	Stop;
	
	Spawn:
	T3D9 B 1;
	Goto Suffer;
	
	Suffer:

	T3D9 BB 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));

	T3D9 B 5;

	T3D9 CC 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));

	T3D9 C 5 A_Pain();
	

	T3D9 BB 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));

	T3D9 B 5;

	T3D9 CC 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));

	T3D9 C 5 A_Pain();
	

	T3D9 BB 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));

	T3D9 B 5;

	T3D9 CC 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));

	T3D9 C 5 A_Pain();
	

	T3D9 BB 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));

	T3D9 B 5;

	T3D9 CC 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));

	T3D9 C 5 A_Pain();
	

	T3D9 BB 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));

	T3D9 B 5;

	T3D9 CC 4 a_spawnprojectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (0, 45));

	T3D9 C 5 A_Pain();
	Goto Death;
	
	Death:
	T3D9 D 8;
	TNT1 A 0 A_SpawnItem ("DeadImp_NoArm", 5);
	Stop;
	
	Death.Head:
	Death.Decaptate:
	Death.MINORHead:
	TNT1 A 0 A_PlaySound("misc/xdeath4");
	TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 30);
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	T3D9 F 8;
	////TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
	TNT1 A 0 A_SpawnItem ("DeadImp_NoArmNoHead", 1);
	Stop;
	
	XDeath:
	Death.Explosives:
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_FaceTarget();
	//TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 42, 0, random (170, 190), 2, random (10, 60));
	TNT1 AAA 0 a_spawnprojectile ("XDeath3", 42, 0, random (170, 190), 2, random (10, 60));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 42, 0, random (170, 190), 2, random (10, 60));
	TNT1 A 0 a_spawnprojectile ("XDeath4", 42, 0, random (170, 190), 2, random (10, 60));
	TNT1 A 1 a_spawnprojectile ("ImpXDeath", 0, 0, random (0, 360), 2, random (0, 160));
	Stop;
	
	Death.SSG:
	Death.Shotgun:
	Death.Blast:
	Death.Railgun:
	TNT1 A 0 A_XScream();
	//TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
	TNT1 AAA 0 a_spawnprojectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
	TNT1 A 0 a_spawnprojectile ("XDeathImpHead", 32, 0, random (150, 210), 2, random (0, 40));
	TNT1 A 0 a_spawnprojectile ("XDeathImpArm", 32, 0, random (150, 210), 2, random (0, 40));
	TNT1 AAA 0 a_spawnprojectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
	TROG A 6 A_Stop();
	TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
	TROG BBBBBBBBBB 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (30, 60));
	TROG CCC 3 a_spawnprojectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (10, 40));
	TROG DD 3 a_spawnprojectile ("Brutal_LiquidBlood2", 6, 0, random (0, 360), 2, random (30, 60));
	TROG E -1;
	Stop;
}
}



CLASS DyingImpVar2NoLeg : SwitchableDecoration { 
Default {
	Radius 16;
	Height 25;
	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	Scale 1.0;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	}
	States
	{	
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
	TNT1 A 0 A_FaceTarget();
	TNT1 A 0 A_NoBlocking();
	//TNT1 A 0 A_GiveToTarget("HasImpShield", 1);
	//TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
	T3DA D 8;
	Stop;
	
	Spawn:
	T3D3 E 1;
	TNT1 A 0;
	TNT1 A 0 A_Jump(32, "Colapse");
	Goto Suffer;
	Suffer:
	

	T3DA DD 4 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));

	T3DA D 5 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));

	T3DA FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));

	T3DA F 5 A_Pain();
	

	T3DA DD 4 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));

	T3DA D 5 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));

	T3DA FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));

	T3DA F 5 A_Pain();
	

	T3DA DD 4 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));

	T3DA D 5 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));

	T3DA FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));

	T3DA F 5 A_Pain();
	

	T3DA DD 4 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));

	T3DA D 5 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));

	T3DA FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));

	T3DA F 5 A_Pain();
	Goto Colapse;
	
	Death:
	TNT1 A 0 A_PlaySound("imp/death");
	T3DA G 8;
	TNT1 A 0 A_SpawnItem ("DeadImp_NoLeg", 5);
	Stop;
	
	Colapse:
	T3DA H 8;
	TNT1 A 0 A_SpawnItem ("DeadImp_NoLeg", 5);
	Stop;
	
	Death.Head:
	Death.Decaptate:
	Death.MINORHead:
	TNT1 A 0 A_PlaySound("misc/xdeath4");
	TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 30);
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	T3DA I 8;
	TNT1 A 0 A_SpawnItem ("DeadImp_Noleg", 1);
	//TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
	Stop;
}
}


CLASS DyingImpVar2NoArm2 : SwitchableDecoration { 
default {
	Radius 16;
	Height 25;
	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 0x7FFFFFFF;
	-SOLID;
	+SHOOTABLE;
	DamageFactor "bloodsplasher", 0.0;    DamageFactor "tinybloodsplasher", 0.0;
    DamageFactor "superbloodsplasher", 0.0;    DamageFactor "smallbloodsplasher", 0.0;
	DamageFactor "BlueBloodSplasher", 0.0;
	DamageFactor "BlueSuperBloodSplasher", 0.0;
	Scale 1.0;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	}
	States
	{
	
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
	TNT1 A 0 A_FaceTarget();
	TNT1 A 0 A_NoBlocking();
	//TNT1 A 0 A_GiveToTarget("HasImpShield", 1);
	//TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
	T3DA D 8;
	Stop;
	
	Spawn:
	T3D3 E 1;
	TNT1 A 0 A_Jump(128, "Death");
	Goto Suffer;
	Suffer:

	T3D8 BB 4 a_spawnprojectile ("Brutal_LiquidBlood", 15, 2, random(0, 360), 2, random (0, 45));

	T3D8 B 5 A_Pain();
	

	T3D8 CC 4 a_spawnprojectile ("Brutal_LiquidBlood", 15, 2, random(0, 360), 2, random (0, 45));

	T3D8 C 5 A_Pain();
	

	T3D8 BB 4 a_spawnprojectile ("Brutal_LiquidBlood", 15, 2, random(0, 360), 2, random (0, 45));

	T3D8 B 5 A_Pain();
	

	T3D8 CC 4 a_spawnprojectile ("Brutal_LiquidBlood", 15, 2, random(0, 360), 2, random (0, 45));

	T3D8 C 5 A_Pain();
	

	T3D8 BB 4 a_spawnprojectile ("Brutal_LiquidBlood", 15, 2, random(0, 360), 2, random (0, 45));

	T3D8 B 5 A_Pain();
	

	T3D8 CC 4 a_spawnprojectile ("Brutal_LiquidBlood", 15, 2, random(0, 360), 2, random (0, 45));

	T3D8 C 5 A_Pain();
	

	T3D8 BB 4 a_spawnprojectile ("Brutal_LiquidBlood", 15, 2, random(0, 360), 2, random (0, 45));

	T3D8 B 5 A_Pain();
	

	T3D8 CC 4 a_spawnprojectile ("Brutal_LiquidBlood", 15, 2, random(0, 360), 2, random (0, 45));

	T3D8 C 5 A_Pain();
	

	T3D8 BB 4 a_spawnprojectile ("Brutal_LiquidBlood", 15, 2, random(0, 360), 2, random (0, 45));

	T3D8 B 5 A_Pain();
	

	T3D8 CC 4 a_spawnprojectile ("Brutal_LiquidBlood", 15, 2, random(0, 360), 2, random (0, 45));

	T3D8 C 5 A_Pain();
	

	T3D8 BB 4 a_spawnprojectile ("Brutal_LiquidBlood", 15, 2, random(0, 360), 2, random (0, 45));

	T3D8 B 5 A_Pain();
	

	T3D8 CC 4 a_spawnprojectile ("Brutal_LiquidBlood", 15, 2, random(0, 360), 2, random (0, 45));

	T3D8 C 5 A_Pain();
	

	T3D8 BB 4 a_spawnprojectile ("Brutal_LiquidBlood", 15, 2, random(0, 360), 2, random (0, 45));

	T3D8 B 5 A_Pain();
	

	T3D8 CC 4 a_spawnprojectile ("Brutal_LiquidBlood", 15, 2, random(0, 360), 2, random (0, 45));

	T3D8 C 5 A_Pain();
	

	T3D8 BB 4 a_spawnprojectile ("Brutal_LiquidBlood", 15, 2, random(0, 360), 2, random (0, 45));

	T3D8 B 5 A_Pain();
	

	T3D8 CC 4 a_spawnprojectile ("Brutal_LiquidBlood", 15, 2, random(0, 360), 2, random (0, 45));

	T3D8 C 5 A_Pain();
	

	T3D8 BB 4 a_spawnprojectile ("Brutal_LiquidBlood", 15, 2, random(0, 360), 2, random (0, 45));

	T3D8 B 5 A_Pain();
	

	T3D8 CC 4 a_spawnprojectile ("Brutal_LiquidBlood", 15, 2, random(0, 360), 2, random (0, 45));

	T3D8 C 5 A_Pain();
	Goto Death;
	Death:
	T3D8 D 8;
	TNT1 A 0 A_SpawnItem ("DeadImp_NoArm2", 5);
	Stop;
	
	Death.Blast:
	Death.SSG:
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 A 0 a_spawnprojectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
	TNT1 A 0 a_spawnprojectile ("XDeathImpArm", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 A 0 a_spawnprojectile ("XDeathImpHead", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("SuperGoreSpawner", 22, 0, random (170, 190), 2, random (0, 15));
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	IZD1 EFGH 6;
	IZD1 H -1;
	TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
	Stop;
	
	Death.Head:
	Death.Decaptate:
	Death.MINORHead:
	TNT1 A 0 A_PlaySound("misc/xdeath4");
	TNT1 A 0 A_PlaySound("headex", 0);
	TNT1 AAAA 0 a_spawnprojectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("Brains3", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("Brains6", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("Brains7", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
	TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAAAAAAAAA 0 a_spawnprojectile ("BrainBlood", 36, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	T3D8 F 8;
	//TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
	TNT1 A 0 A_SpawnItem ("DeadImp_NoArmNoHead2", 1);
	Stop;
}
}

CLASS DyingImpVar22 : SwitchableDecoration { 
Default {
	Radius 16;
	Height 32;
	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 0x7FFFFFFF;
	+SHOOTABLE;
	+SOLID;
	DamageFactor "Crush", 50.0;
	DamageFactor "Fatality", 50.0;
	DamageFactor "bloodsplasher", 0.0;    DamageFactor "tinybloodsplasher", 0.0;
    DamageFactor "superbloodsplasher", 0.0;    DamageFactor "smallbloodsplasher", 0.0;
	DamageFactor "BlueBloodSplasher", 0.0;
	DamageFactor "BlueSuperBloodSplasher", 0.0;
	Scale 1.0;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	}
	States
	{
	Spawn:
	T3D2 E 1;
	Goto Suffer;
	Suffer:

	T3D2 EE 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 E 5 A_Pain();
	

	T3D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 F 5 A_Pain();
	

	T3D2 GG 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 G 5 A_Pain();
	

	T3D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 F 5 A_Pain();
	

	T3D2 EE 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 E 5 A_Pain();
	

	T3D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 F 5 A_Pain();
	

	T3D2 GG 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 G 5 A_Pain();
	

	T3D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 F 5 A_Pain();
	

	T3D2 EE 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 E 5 A_Pain();
	

	T3D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 F 5 A_Pain();
	

	T3D2 GG 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 G 5 A_Pain();
	

	T3D2 EE 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 E 5 A_Pain();
	

	T3D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 F 5 A_Pain();
	

	T3D2 GG 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 G 5 A_Pain();
	

	T3D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 F 5 A_Pain();
	

	T3D2 EE 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 E 5 A_Pain();
	

	T3D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 F 5 A_Pain();
	

	T3D2 GG 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 G 5 A_Pain();
	

	T3D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 F 5 A_Pain();
	

	T3D2 EE 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 E 5 A_Pain();
	

	T3D2 FF 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 F 5 A_Pain();
	

	T3D2 GG 4 a_spawnprojectile ("Brutal_LiquidBlood", 13, 2, random(0, 360), 2, random (0, 45));

	T3D2 G 5 A_Pain();
	
	Goto Death;
	
	Death:
	T3D2 HI 8;
	TNT1 A 1 A_SpawnItem ("DeadImp_NoStomach2", 5);
	Stop;
	
	Death.Head:
	Death.Decaptate:
	Death.MINORHead:
	TNT1 A 0 A_PlaySound("misc/xdeath4");
	TNT1 A 0 A_PlaySound("headex", 0);
	TNT1 AAAA 0 a_spawnprojectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("Brains3", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("Brains6", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("Brains7", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPieceFast", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
	TNT1 AAAA 0 a_spawnprojectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAAAAAAAAA 0 a_spawnprojectile ("BrainBlood", 36, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	T3D2 JKL 8;
	//TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
	TNT1 A 0 A_SpawnItem ("DeadImp_NoStomachNoHead2", 1);
	Stop;
	
Death.Plasma: Death.Plasma2:
	TNT1 A 0;
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	XBRN AA 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
	TNT1 AAAA 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
	
	TNT1 A 0 a_spawnprojectile ("XDeathBurnedImpArm", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeathBurnedImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
	
	XBRN BB 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
	TNT1 A 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
	XBRN CC 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
	XBRN DEF 4 BRIGHT;
	TNT1 A 0;
	Stop;
	
Death.Fire:
	TNT1 A 0;
	TNT1 A 0 A_Scream();
	TNT1 A 0 A_NoBlocking();
	//TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
	TRO3 JJJJ 2 a_spawnprojectile ("FlameTrails", 45, 0, random (0, 360), 2, random (50, 130));
	TRO3 KKKK 2 a_spawnprojectile ("FlameTrails", 30, 0, random (0, 360), 2, random (50, 130));
	TRO3 LLLL 2 a_spawnprojectile ("FlameTrails", 25, 0, random (0, 360), 2, random (50, 130));
	TNT1 A 0 A_Playsound("props/redfire");
	BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 a_spawnprojectile ("FlameTrails", 15, 0, random (0, 360), 2, random (50, 130));
	BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 10 a_spawnprojectile ("Explosion_Smoke", 15, 0, random (0, 360), 2, random (70, 110));
	BOSB E -1;
	Stop;
	
Death.Saw:
Death.cutless:
	TNT1 O 0 A_Jump(230, 2);
	Goto Death;
	TNT1 A 0 A_XScream();
	TNT1 O 0 A_NoBlocking();
	TNT1 A 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
	TROG A 2 a_spawnprojectile ("RipImp", 0, 0, random (0, 360), 2, random (0, 160));
	TROG AAAAAAAAAAAAAAAAAAAAAAAAAA 4 A_SpawnItem ("Big_Blood", 0, 30);
	TROG BCDEFGH 8;
	TNT1 A 1 A_SpawnItem ("DeadImp_Half", 5);
	Stop;
	
Death.Blast:
Death.SSG:
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 A 0 a_spawnprojectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 A 0 a_spawnprojectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
	TNT1 AA 0 a_spawnprojectile ("XDeathImpArm", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 A 0 a_spawnprojectile ("XDeathImpHead", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 a_spawnprojectile ("SuperGoreSpawner", 22, 0, random (170, 190), 2, random (0, 15));
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	IZD1 EFGH 6;
	IZD1 H -1;
	TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
	Stop;
	
Death.Fatality:
Death.SuperPunch:
Death.ExtremePunches:
	TNT1 A 0 A_NoBlocking();
	//TNT1 A 0 A_GiveToTarget("HasImpShield", 1);
	//TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
	Stop;
}

}
