class proto_imp_class : pb_monster_base
{
bool on_floor, ceiling_jump, on_ceiling, attack_jump, first_seeing;

default
{
	height 54;
	radius 18;

	pb_monster_base.headshot_multiplier 2;
	pb_monster_base.head_starting_position 48;
	pb_monster_base.legs_height_max 10;
}

sector prev_sector;
//to check current and previous actor sectors for ceiling imps

protected bool pb_check_for_ceiling()
{
	if(curSector.GetTexture(curSector.ceiling) == skyflatnum)//there are sky at the ceiling
	{return false;}
	
	return true;
}
	
protected void pb_change_flags_for_jump()
{
	if(self is "proto_imp_class")
	{
		if(proto_imp_class(self).on_ceiling == true && proto_imp_class(self).on_floor == false)
		{
			bNOGRAVITY = true;
			bTHRUSPECIES = true;
			bNOVERTICALMELEERANGE = true;
		}
		
		if(proto_imp_class(self).on_ceiling == false && proto_imp_class(self).on_floor == true)
		{
			bNOGRAVITY = false;
			bTHRUSPECIES = false;
			bNOVERTICALMELEERANGE = false;
		}
	}
}

protected bool pb_imp_ceiling_jump()
{
	if(ceiling_jump == true) {return false;}
	if(pb_check_for_ceiling() == false) {return false;}
	if(self.ceilingz - self.floorz > 300) {return false;}

	double jump_vel = sqrt(self.getgravity() * 2 * self.ceilingz);

	if(jump_vel > 0) {self.vel.z = jump_vel; ceiling_jump = true;}
	return true;
}

override void tick()
{
	super.tick();
	
	if(ceiling_jump == true)
	{
		if((self.pos.z + self.height >= self.ceilingz) )
		{ceiling_jump = false; return;}

		if(self.pos.z == self.floorz) {ceiling_jump = false; return;}
	}
	
}

states
{
	Death.Blackhole:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		ID52 ABCDEFGHIJ 4;
		TNT1 A 0 A_StopSound(2);
	stop;
	
	Death.Desintegrate:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_PlaySound("desintegratedflesh", 3);
		TNT1 A 0 A_PlaySound("MELT",6);
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 22, 0, random(0, 360), 2, random(0, 90));
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 37, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 37, 0, random(0, 360), 2, random(10, 50));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 30, 0, random(0, 360), 2, random(0, 90));
		TNT1 A 0 a_spawnprojectile("SuperGoreSpawner2", 30, 0, random(0, 360), 2, random(10, 90));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("Barrel_explosion_Column");
		
		TNT1 A 0 A_Jump(128, "desintegrate_2");
		ID50 AAABBBCCCDDDEEEFFFGGGGGGGGGGGGGGGGGGG 2 a_spawnprojectile("Brutal_LiquidBlood3", 18, 0, random(0, 360), 2, random(0, 40));
		ID50 G -1;
	stop;
		
	desintegrate_2:
       M31T CCCCCDDDDDEEEEEFFFFGGGGHHHHIIIIJJJJKKKKKKKKKKKKK 2 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
       M31T K -1;
	Stop;
}

}



































CLASS BrainsImpHeadPiece: Brains4 { //White skinned piece 1
	Default {
	Speed 2;
	-DOOMBOUNCE;
	Scale 1.0;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		BR7N E 4 a_spawnprojectile("named_BloodTr", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		BR7N E 1;
		TNT1 A 0 A_QueueCorpse;
 	Rest:
		BR7N E 800;
		BR7N E -1;
		Stop;
	DoNothing:
		TNT1 A 0;
		Stop;
	}
}


CLASS BrainsSavageImpHeadPiece: Brains4 { //White skinned piece 1
	Default {
	Speed 2;
	-DOOMBOUNCE;
	Scale 1.0;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		1HED A 4 a_spawnprojectile("named_BloodTr", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		1HED A 1;
		TNT1 A 0 A_QueueCorpse;
 	Rest:
		1HED A 800;
		1HED A -1;
		Stop;
	DoNothing:
		TNT1 A 0;
		Stop;
	}
}


CLASS XDeathImpArm: XDeathArm1 { 
	Default {
    Scale 1.1;
    Speed 8;
	Gravity 0.4;
	bounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		HND4 ABCDEFGH 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death.plasma:    TNT1 A 0 a_spawnprojectile("XDeathBurnedImpArm", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:
		HND4 X 1;
		//HND4 X -1
		HND4 X 0 A_SpawnItem("Gib_ImpArm",0,0,0,1);
		Stop;
	}
}

CLASS XDeathSavageImpArm: XDeathImpArm { 
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		9ND4 ABCDEFGH 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
		
	Death.plasma:
	TNT1 A 0 a_spawnprojectile("XDeathBurnedImpArm", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:
		9ND4 X 1;
		9ND4 X 0 A_SpawnItem("Gib_SavageImpArm",0,0,0,1);
		Stop;
	}
}


CLASS Gib_ImpArm: Limbs_Base { 
	Default {
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		HND4 X 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		HND4 X -1;
		Stop;
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 a_spawnprojectile("XDeathBurnedImpArm", 32, 0, random(0, 360), 2, random(0, 160));
        Stop;
Death:    
	TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 A 0 a_spawnprojectile("GibImpHand", 0, 0, random(0, 180), 2, random(0, 180));
	TNT1 A 0 a_spawnprojectile("GibImpArmPart", 0, 0, random(0, 180), 2, random(0, 180));
	Stop;
	Stop;
Death.Kick:
Death.Melee:
Death.SuperPunch:
	HND4 AA 1 A_FaceTarget;
	TNT1 A 0 a_spawnprojectile("XDeathImpArm", 5, 0, random(170, 190), 2, random(20, 40));
	Stop;
	
Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	HND4 ABCDEFGH 3;
	Goto Spawn;
	
Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	HND4 X 5;
	HND4 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
Landz:
	XDT5 I 0 A_SpawnItem("Gib_ImpArm");
	Stop;
}}

CLASS Gib_SavageImpArm: Gib_ImpArm {
    States
    {
    Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
        9ND4 X 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
        9ND4 X -1;
        Stop;
	Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 a_spawnprojectile("XDeathBurnedImpArm", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
    Death:    
    TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
    TNT1 A 0 a_spawnprojectile("GibSavageImpHand", 0, 0, random(0, 180), 2, random(0, 180));
    TNT1 A 0 a_spawnprojectile("GibSavageImpArmPart", 0, 0, random(0, 180), 2, random(0, 180));
Stop;

	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
	    9ND4 AA 1 A_FaceTarget;
	TNT1 A 0 a_spawnprojectile("XDeathSavageImpArm", 5, 0, random(170, 190), 2, random(20, 40));
	Stop;
	
	Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	9ND4 ABCDEFGH 3;
	Goto Spawn;
	
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	9ND4 X 5;
	9ND4 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
	Landz:
	XDT5 I 0 A_SpawnItem("Gib_SavageImpArm");
	Stop;
}}

CLASS GibImpArmPart: gibs_base { 
	Default {
 
    Scale 1.1;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
        HND4 Z -1;
        Stop;
    Death:
        HND4 Z 1;
       Loop;
}}

CLASS GibImpHand: gibs_base { 
	Default {
 
    Scale 0.8;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
        HND4 Y -1;
        Stop;
    Death:
        HND4 Y 1;
       Loop;
}}


CLASS GibSavageImpArmPart: gibs_base { 
	Default {
 
    Scale 1.1;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
        9ND4 Z -1;
        Stop;
    Death:
        9ND4 Z 1;
       Loop;
}}



CLASS GibSavageImpHand: gibs_base { 
	Default {
 
    Scale 0.8;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
        9ND4 Y -1;
        Stop;
    Death:
        9ND4 Y 1;
       Loop;
}}


CLASS XDeathHalfImpUpperPart32 : pb_blood_and_gore_base { 
	Default {
 
    Radius 2;
    Height 2;
    Scale 1.1;
	Speed 12;
	Gravity 0.3;
	Mass 4;
	Decal "BrutalBloodSplat";
	bounceFactor 0.2;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	}
	States
	{
	Spawn:
		//TNT1 A 0 A_SpawnItem("Brutal_LiquidBlood",0,0,0,1)
		HND4 IJKLMNOPQ 3 a_spawnprojectile("Brutal_LiquidBlood",0,0,0,1);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 AAA 0 A_spawnItem("Blood", 0, 10);
		HND4 Q 1 A_SpawnItem("Gib_HalfImpUpperPart32",0,0,0,1);
		TNT1 A 0;
		Stop;
	}
}

CLASS XDeathHalfSavageImpUpperPart32 : pb_blood_and_gore_base { 
	Default {
	
	Radius 2;
	Height 2;
	Scale 1.1;
	Speed 12;
	Gravity 0.3;
	Mass 4;
	Decal "BrutalBloodSplat";
	BounceFactor 0.2;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	}
	States
	{
	Spawn:
		//TNT1 A 0 A_SpawnItem("Brutal_LiquidBlood",0,0,0,1)
		9ND4 IJKLMNOPQ 3 a_spawnprojectile("Brutal_LiquidBlood",0,0,0,1);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 AAA 0 A_spawnItem("Blood", 0, 10);
		9ND4 Q 1 A_SpawnItem("Gib_HalfSavageImpUpperPart32",0,0,0,1);
		TNT1 A 0;
		Stop;
	}
}

CLASS Gib_HalfImpUpperPart32: gibs_base { 
	Default {
	
	damagefactor "ExplosiveImpact", 5.0;
	Mass 10;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		HND4 Q -1;
		Stop   ;
	Death.ExplosiveImpact:
	Death.Explosive:
	Death.Kick:
	Death.SuperPunches:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		Goto Fly;
	Fly:
		HND4 IJKLMNOPQ 3 A_CheckFloor("Land");
		Loop;
	Land:
		HND4 Q 1 A_SpawnItem("Gib_HalfImpUpperPart32",0,0,0,1);
Stop; }}	 

CLASS Gib_HalfSavageImpUpperPart32: gibs_base { 
	Default {
	
	damagefactor "ExplosiveImpact", 5.0;
	Mass 10;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		9ND4 Q -1;
		Stop   ;
	Death.ExplosiveImpact:
	Death.Explosive:
	Death.Kick:
	Death.SuperPunches:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		Goto Fly;
	Fly:
		9ND4 IJKLMNOPQ 3 A_CheckFloor("Land");
		Loop;
	Land:
		9ND4 Q 1 A_SpawnItem("Gib_HalfSavageImpUpperPart32",0,0,0,1);
Stop; }}



CLASS XDeathImpLeg: XDeathArm1 { 
	Default {
	
	Scale 1.1;
	Speed 8;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		LEG4 ABCDEFGH 5 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		LEG4 I 1;
		LEG4 I 1 A_SpawnItem("Gib_ImpLeg");
		Stop;
		
	}
}

CLASS XDeathSavageImpLeg: XDeathImpLeg { 
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		1EG4 ABCDEFGH 5 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		1EG4 I 1;
		1EG4 I 1 A_SpawnItem("Gib_SavageImpLeg");
		Stop;
		
	}
}

CLASS Gib_ImpLeg: Limbs_Base { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG4 I 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		LEG4 I -1;
		Stop;
Death.plasma: Death.Burn: Death.Flames:
    TNT1 A 0 a_spawnprojectile("XDeathBurnedImpLeg", 32, 0, random(0, 360), 2, random(0, 160));        
Stop;
Death:    
	TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 A 0 a_spawnprojectile("GibImpLegPart", 0, 0, random(0, 180), 2, random(0, 180));
	TNT1 A 0 a_spawnprojectile("GibImpPaw", 0, 0, random(0, 180), 2, random(0, 180));
	Stop;
Death.Kick:
Death.Melee:
Death.SuperPunch:
	LEG4 A 1 A_FaceTarget;
	TNT1 A 0 a_spawnprojectile("XDeathImpLeg", 5, 0, random(170, 190), 2, random(20, 40));
	Stop;
	
Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	LEG4 ABCDEFGH 2;
	Goto Spawn;
	
Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	LEG4 A 5;
	LEG4 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
Landz:
	XDT5 I 0 A_SpawnItem("Gib_ImpLeg");
	Stop;
}}

CLASS Gib_SavageImpLeg: Limbs_Base { 
	Default {
 
    Scale 1.1;
	}
    States
    {
    Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	1EG4 I 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	1EG4 I -1;
        Stop;
Death.plasma: Death.Burn: Death.Flames:
	    TNT1 A 0 a_spawnprojectile("XDeathBurnedImpLeg", 32, 0, random(0, 360), 2, random(0, 160));
Stop;
    Death:    
    TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
    TNT1 A 0 a_spawnprojectile("GibSavageImpLegPart", 0, 0, random(0, 180), 2, random(0, 180));
    TNT1 A 0 a_spawnprojectile("GibSavageImpPaw", 0, 0, random(0, 180), 2, random(0, 180));
Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
	    1EG4 A 1 A_FaceTarget;
	TNT1 A 0 a_spawnprojectile("XDeathImpLeg", 5, 0, random(170, 190), 2, random(20, 40));
	Stop;
	
	Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	1EG4 ABCDEFGH 2;
	Goto Spawn;
	
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	1EG4 A 5;
	1EG4 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
	Landz:
	1EG4 I 0 A_SpawnItem("Gib_SavageImpLeg");
	Stop;
}}

CLASS GibImpLegPart: gibs_base { 
	Default {
 
    Scale 1.1;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	LEG4 Z -1;
        Stop;
    Death:
LEG4 Z 1;
       Loop;
}}

CLASS GibImpPaw: gibs_base { 
	Default {
 
    Scale 1.1;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	LEG4 Y -1;
        Stop;
    Death:
LEG4 Y 1;
       Loop;
}}

CLASS GibSavageImpLegPart: gibs_base { 
	Default {
 
    Scale 1.1;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	1EG4 Z -1;
        Stop;
    Death:
1EG4 Z 1;
       Loop;
}}

CLASS GibSavageImpPaw: gibs_base { 
	Default {
 
    Scale 1.1;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	1EG4 Y -1;
        Stop;
    Death:
1EG4 Y 1;
       Loop;
}}



CLASS XDeathHalfImp : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Speed 7;
	Mass 8;
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TROG I 12 a_spawnprojectile("pb_FlyingBloodTrail",0,0,180,2);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TROG I 0 A_SpawnItem("HalfImpGib",0,0,0,1);
		Stop;
	}
}


CLASS HalfImpGib: gibs_base { 
	Default {
	
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		TROG J 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TROG J -1;
Stop;    }}


CLASS XDeathImpHead: XDeathChaingunguyHead { 
	States
	{
	Spawn:
	Spawn1:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		XHE4 AB 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		XHE4 CDEFGH 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		XHE4 E 1;
		XHE4 E 1 A_SpawnItem("ImpHead",0,0,0,1);
		Stop;
	}
}

CLASS XDeathSavageImpHead: XDeathChaingunguyHead { 
	States
	{
	Spawn:
	Spawn1:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		7HE4 AB 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		7HE4 CDEFGH 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		7HE4 E 1;
		7HE4 E 1 A_SpawnItem("SavageImpHead",0,0,0,1);
		Stop;
	}
}


CLASS XDeathImpHeadBeheaded: XDeathImpHead { 
	Default {
	
	Speed 5;
	Gravity 0.5;
	}
}

CLASS XDeathImpHeadOnXDeath: XDeathImpHead { 
	States
	{
	Spawn:
		TNT1 A 1;
		TNT1 A 0 A_jump(96, "ExplodeOnAir");
		Goto Spawn1;
	ExplodeOnAir:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("ImpHeadExplode");
		Stop;
}}

CLASS XDeathSavageImpHeadOnXDeath: XDeathSavageImpHead { 
	States
	{
	Spawn:
		TNT1 A 1;
		TNT1 A 0 A_jump(96, "ExplodeOnAir");
		Goto Spawn1;
	ExplodeOnAir:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("SavageImpHeadExplode");
		Stop;
}}

CLASS ImpHead: ZombieManHead { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot");
		TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
	Spawn1:
		XHE4 C 1;
		XHE4 C -1;
		Stop;
	Spawn2:
		XHE4 G 1;
		XHE4 G -1;
		Stop;
	Spawn3:
		XHE4 H 1;
		XHE4 H -1;
		Stop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("ImpHeadExplode");
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		XHE4 EE 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathImpHead", 5, 0, random(170, 190), 2, random(20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		XHE4 ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		XHE4 ABCDEFGH 3;
		XDT5 I 0 A_SpawnItem("ImpHead");
		Stop;
		
}}

CLASS SavageImpHead: ZombieManHead { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot");
		TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
	Spawn1:
		7HE4 C 1;
		7HE4 C -1;
		Stop;
	Spawn2:
		7HE4 G 1;
		7HE4 G -1;
		Stop;
	Spawn3:
		7HE4 H 1;
		7HE4 H -1;
		Stop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("SavageImpHeadExplode");
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		7HE4 EE 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathSavageImpHead", 5, 0, random(170, 190), 2, random(20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		7HE4 ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		7HE4 ABCDEFGH 3;
		XDT5 I 0 A_SpawnItem("SavageImpHead");
		Stop;
		
}}


CLASS ImpXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 NoDelay A_Jump(110, "Spawn2");
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 40, 0, random(0, 360), 2, random(-15, 15));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathImpArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfImpUpperPart32", 32, 0, random(0, 360), 2, random(10, 60));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath5", 32, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 AAAAAAA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathImpLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathImpHeadOnXDeath", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
		
	Spawn2:
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 40, 0, random(0, 360), 2, random(-15, 15));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathImpArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath5", 32, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 A 0 a_spawnprojectile("XDeathNewImpLowerTorso", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathNewImpUpperTorso", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathImpLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathImpHeadOnXDeath", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
		
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("SuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
}
}

CLASS SavageImpXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 40, 0, random(0, 360), 2, random(-15, 15));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathSavageImpArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfSavageImpUpperPart32", 32, 0, random(0, 360), 2, random(10, 60));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath5", 32, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 AAAAAAA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSavageImpLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSavageImpHeadOnXDeath", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
		
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("SuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
}
}


CLASS RipImp : pb_blood_and_gore_base { 
Default {
	
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("Instestin2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfImp", 40, 0, random(0, 360), 2, random(0, 160));
	Death:
		TNT1 A 0;
		Stop;
}
}


CLASS ImpHeadExplode: ZombieXDeath { 
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("Brains2", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("BrainsImpHeadPiece", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPiece", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Teeth", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 90));
		TNT1 A 10;
		Stop;
}
}

CLASS SavageImpHeadExplode: ImpHeadExplode { 
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("Brains2", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("BrainsSavageImpHeadPiece", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPiece", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Teeth", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 90));
		TNT1 A 10;
		Stop;
}
}


CLASS XDeathBurnedImpLeg : XDeathBurnedLeg { 
States
{
	Spawn:
		CARB F 10 a_spawnprojectile("ExplosionSmoke",0,0,180,2);
		Loop;
	Death:
		CARB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 14 a_spawnprojectile("ExplosionSmoke", 1, 0, random(0, 360), 2, random(0, 160));
		CARB F -1;
		Stop;
}
}


CLASS XDeathBurnedImpArm : XDeathBurnedLeg { 
States
{
	Spawn:
		CARB G 10 a_spawnprojectile("ExplosionSmoke",0,0,180,2);
		Loop;
	Death:
		CARB GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG 14 a_spawnprojectile("ExplosionSmoke", 1, 0, random(0, 360), 2, random(0, 160));
		CARB G -1;
		Stop;
}
}


CLASS XDeathNewImpUpperTorso : pb_blood_and_gore_base { 
	Default {
 
    Radius 8;
    Height 8;
    
	Speed 10;
	Gravity 0.7;
	Mass 4;
	Decal "BrutalBloodSplat";
bounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			4N04 ABCDEFGHI 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_NewImpUpperTorso",0,0,0,1);
			Stop;
	}
}

CLASS Gib_NewImpUpperTorso: gibs_base { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			4N04 J 1;
			4N04 J -1;
Stop;    }}
	   
//Imp Lower Torso
CLASS XDeathNewImpLowerTorso : pb_blood_and_gore_base { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			4N03 ABCDEFGHI 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_NewImpLowerTorso",0,0,0,1);
			Stop;
	}
}

CLASS Gib_NewImpLowerTorso: gibs_base { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			4N03 J 1;
			4N03 J -1;
Stop;    }}
	   


CLASS DyingImpNoArm2 : SwitchableDecoration { 
	Default {
	Radius 16;
	Height 32;
	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 0x7FFFFFFF;
	-SOLID;
	+SHOOTABLE;
	DamageFactor "bloodsplasher", 0.0;
	DamageFactor "tinybloodsplasher", 0.0;
	DamageFactor "superbloodsplasher", 0.0;
	DamageFactor "smallbloodsplasher", 0.0;
	DamageFactor "BlueBloodSplasher", 0.0;
	DamageFactor "BlueSuperBloodSplasher", 0.0;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	Scale 1.0;
	}
	States
	{
	
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
		TNT1 A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ;//A_GiveToTarget("HasImpShield = true;}
		TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
		T408 B 8;
		stop;
		
	Spawn:
		IMPC E 1;
		TNT1 A 0 A_Jump(160, "Death");
		Goto Suffer;
	Suffer:
		T408 BB 4 a_spawnprojectile("Brutal_FlyingBlood", 15, 2, random(0, 360), 2, random(0, 45));
		T408 B 5 A_Pain;

		T408 CC 4 a_spawnprojectile("Brutal_FlyingBlood", 15, 2, random(0, 360), 2, random(0, 45));
		T408 C 5 A_Pain;

	Death:
		T408 D 8;
		TNT1 A 0 A_SpawnItem("DeadImp_NoArm2", 5);
		stop;
		
	Death.Head:
	Death.Decaptate:
	Death.MINORHead:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("headex");
		TNT1 AAAA 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 36, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		T408 F 8;
		TNT1 A 0 A_SpawnItem("healthbonus");
		TNT1 A 0 A_SpawnItem("DeadImp_NoArmNoHead2");
		stop;
}
}

CLASS DyingImp2 : SwitchableDecoration { 
	Default {
	Radius 16;
	Height 32;
	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 0x7FFFFFFF;
	+SHOOTABLE;
	+SOLID;
	DamageFactor "Crush", 50.0;
	DamageFactor "Fatality", 50.0;
	DamageFactor "bloodsplasher", 0.0;
	DamageFactor "tinybloodsplasher", 0.0;
	DamageFactor "superbloodsplasher", 0.0;
	DamageFactor "smallbloodsplasher", 0.0;
	DamageFactor "BlueBloodSplasher", 0.0;
	DamageFactor "BlueSuperBloodSplasher", 0.0;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	Scale 1.0;
	}
	States
	{
	
	
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
		TNT1 A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ;//A_GiveToTarget("HasImpShield = true;}
		TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
		I9PC E 8;
		stop;
		
	Spawn:
		I9PC E 1;
		Goto Suffer;
	Suffer:
		I9PC EE 4 a_spawnprojectile("Brutal_FlyingBlood", 13, 2, random(0, 360), 2, random(0, 45));
		I9PC E 5 A_Pain;
		
		I9PC FF 4 a_spawnprojectile("Brutal_FlyingBlood", 13, 2, random(0, 360), 2, random(0, 45));
		I9PC F 5 A_Pain;

	Death:
		I9PC HI 8;
		TNT1 A 1 A_SpawnItem("DeadImp_NoStomach2", 5);
		stop;
		
	Death.Head:
	Death.Decaptate:
	Death.MINORHead:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("headex");
		TNT1 AAAA 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 36, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		I9PC JKL 8;
		TNT1 A 0 A_SpawnItem("healthbonus");
		TNT1 A 0 A_SpawnItem("DeadImp_NoStomachNoHead2");
		stop;
		
Death.Plasma: Death.Plasma2:
	TNT1 A 0;
	TNT1 A 0 A_XScream;
	TNT1 A 0 A_NoBlocking;
	XBRN AA 2 BRIGHT A_SpawnItem("PB_Flare",0,43);
	TNT1 AAAA 0 a_spawnprojectile("PB_blood", 30, 0, random(0, 360), 2, random(0, 160));
	
	TNT1 A 0 a_spawnprojectile("XDeathBurnedImpArm", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedImpLeg", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	
	XBRN BB 2 BRIGHT A_SpawnItem("PB_Flare",0,43);
	TNT1 A 0 a_spawnprojectile("PB_blood", 30, 0, random(0, 360), 2, random(0, 160));
	XBRN CC 2 BRIGHT A_SpawnItem("PB_Flare",0,43);
	XBRN DEF 4 BRIGHT;
	TNT1 A 0;
	stop;
	
Death.Fire:
	TNT1 A 0;
	TNT1 A 0 A_Scream;
	TNT1 A 0 A_NoBlocking;
	TNT1 A 0 A_SpawnItem("healthbonus");
	TROO JJJJ 2 a_spawnprojectile("FlameTrails", 45, 0, random(0, 360), 2, random(50, 130));
	TROO KKKK 2 a_spawnprojectile("FlameTrails", 30, 0, random(0, 360), 2, random(50, 130));
	TROO LLLL 2 a_spawnprojectile("FlameTrails", 25, 0, random(0, 360), 2, random(50, 130));
	TNT1 A 0 A_Playsound("props/redfire");
	BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 a_spawnprojectile("FlameTrails", 15, 0, random(0, 360), 2, random(50, 130));
	BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 10 a_spawnprojectile("CasingSmoke", 15, 0, random(0, 360), 2, random(70, 110));
	BOSB E -1;
	stop;
	
Death.Saw:
Death.cutless:
	TNT1 O 0 A_Jump(230, 2);
	Goto Death;
	TNT1 A 0 A_XScream;
	TNT1 O 0 A_NoBlocking;
	TNT1 A 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
	TROG A 2 a_spawnprojectile("RipImp", 0, 0, random(0, 360), 2, random(0, 160));
	TROG AAAAAAAAAAAAAAAAAAAAAAAAAA 4 A_SpawnItem("Big_Blood", 0, 30);
	TROG BCDEFGH 8;
	TNT1 A 1 A_SpawnItem("DeadImp_Half", 5);
	stop;
	
Death.Blast:
Death.SSG:
	TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
	TNT1 AA 0 a_spawnprojectile("XDeathImpArm", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeathImpHead", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperGoreSpawner", 22, 0, random(170, 190), 2, random(0, 15));
	TNT1 A 0 A_XScream;
	TNT1 A 0 A_NoBlocking;
	IZD1 EFGH 6;
	IZD1 H -1;
	TNT1 A 0 A_SpawnItem("PB_blood_Spot");
	stop;
	
	
Death.ExtremePunches:
	//TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, "Death.Fatality");
	Goto Death;
}
}


CLASS ImpVar1SaciLol: DyingImpNoLeg { 
	Default {
		
		//MONSTER
		-COUNTKILL;
		Speed 4;
		Height 48;
	}
	States
	{
		
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("imp/pain");
			Goto Suffer;
			
		Suffer:
			T5DC ABC 3;
			TNT1 A 0 A_SpawnItem("BloodDying", 0, 30);
			T5DC DDDD 1 A_Chase(null, null);
			TNT1 A 0 A_PlaySound("imp/pain");

			T5DC ABC 3;
			TNT1 A 0 A_SpawnItem("BloodDying", 0, 30);
			T5DC DDDD 1 A_Wander;
			TNT1 A 0 A_PlaySound("imp/pain");

		Death.Head:
			TNT1 A 0 A_PlaySound("misc/xdeath");
			TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 50);
		FallHead:
			T5DC EFG 7;
			TNT1 A 0 A_SpawnItem("DeadImp_NoLeg");
			stop;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("imp/death");
			T5DC HIJ 7;
			TNT1 A 0 A_SpawnItem("DeadImp_NoLeg");
			stop;
	}
}

CLASS ImpVar2SaciLol: DyingImpNoLeg { 
	Default {
		
		//MONSTER
		-COUNTKILL;
		Speed 4;
		Height 48;
	}
	States
	{
		
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("imp/pain");
			Goto Suffer;
			
		Suffer:
			T3DC ABC 3;
			TNT1 A 0 A_SpawnItem("BloodDying", 0, 30);
			T3DC DDDD 1 A_Chase(null, null);
			TNT1 A 0 A_PlaySound("imp/pain");
			

		Death.Head:
			TNT1 A 0 A_PlaySound("misc/xdeath");
			TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 50);
			Goto FallHead;
		FallHead:
			T3DC EFG 7;
			TNT1 A 0 A_SpawnItem("DeadImp_NoLeg");
			stop;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("imp/death");
			T3DC HIJ 7;
			TNT1 A 0 A_SpawnItem("DeadImp_NoLeg");
			stop;
	}
}


CLASS DyingImp : SwitchableDecoration { 
	Default {
	
	Radius 16;
	Height 28;
	Health 60;
	PainSound "imp/pain";
	PainChance 255;
	Mass 999999;
	+SHOOTABLE;
	+SOLID;
	-THRUACTORS;
	
	+FLOORCLIP;
	damagefactor "Crush", 50.0;
	Scale 1.0;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	}
	States
	{
	Spawn:
		TRO2 D 1;
		//TNT1 A 0 A_Jump(160, "Death")
	Suffer:
		TRO2 DDDDD 2 a_spawnprojectile("Brutal_FlyingBlood", 16, 0, random(0, 360), 2, random(0, 45));
		TRO2 D 2;
		
		TRO2 EEEEE 2 a_spawnprojectile("Brutal_FlyingBlood", 16, 0, random(0, 360), 2, random(0, 45));
		TRO2 E 2 A_Pain;

	Death:
		TRO2 FG 8;
		TNT1 A 0 A_SpawnItem("DeadImp_NoStomach", 5);
		stop;
		
	Death.Head:
	Death.Decaptate:
	Death.MINORHead:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 30);
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		IMPC JJJJJJJJJJJJJJJJJJJ 2 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(0, 360), 2, random(0, 45));
		IMPC KKKK 2 a_spawnprojectile("Brutal_FlyingBlood", 16, 0, random(0, 360), 2, random(0, 45));
		TNT1 A 0 A_SpawnItem("healthbonus");
		IMPC LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 2 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
		TNT1 A 0 A_SpawnItem("DeadImp_NoStomachNoHead", 5);
		stop;
		
Death.Plasma: Death.Plasma2:
	TNT1 A 0;
	TNT1 A 0 A_XScream;
	TNT1 A 0 A_NoBlocking;
	XBRN AA 2 BRIGHT A_SpawnItem("PB_Flare",0,43);
	TNT1 AAAA 0 a_spawnprojectile("PB_blood", 30, 0, random(0, 360), 2, random(0, 160));
	
	TNT1 A 0 a_spawnprojectile("XDeathBurnedImpArm", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedImpLeg", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	
	XBRN BB 2 BRIGHT A_SpawnItem("PB_Flare",0,43);
	TNT1 A 0 a_spawnprojectile("PB_blood", 30, 0, random(0, 360), 2, random(0, 160));
	XBRN CC 2 BRIGHT A_SpawnItem("PB_Flare",0,43);
	XBRN DEF 4 BRIGHT;
	TNT1 A 0;
	stop;
	
Death.Fire:
	TNT1 A 0;
	TNT1 A 0 A_Scream;
	TNT1 A 0 A_NoBlocking;
	TNT1 A 0 A_SpawnItem("healthbonus");
	TROO JJJJ 2 a_spawnprojectile("FlameTrails", 45, 0, random(0, 360), 2, random(50, 130));
	TROO KKKK 2 a_spawnprojectile("FlameTrails", 30, 0, random(0, 360), 2, random(50, 130));
	TROO LLLL 2 a_spawnprojectile("FlameTrails", 25, 0, random(0, 360), 2, random(50, 130));
	TNT1 A 0 A_Playsound("props/redfire");
	BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 a_spawnprojectile("FlameTrails", 15, 0, random(0, 360), 2, random(50, 130));
	BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 10 a_spawnprojectile("CasingSmoke", 15, 0, random(0, 360), 2, random(70, 110));
	BOSB E -1;
	stop;
	
Death.cut:
Death.cutless:
	TNT1 O 0 A_Jump(230, 2);
	Goto Death;
	TNT1 A 0 A_XScream;
	TNT1 O 0 A_NoBlocking;
	TNT1 A 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
	TROG A 2 a_spawnprojectile("RipImp", 0, 0, random(0, 360), 2, random(0, 160));
	TROG AAA 4 A_SpawnItem("Big_Blood", 0, 30);
	TNT1 A 0 A_SpawnItem("healthbonus");
	TROG BCDEFGH 8;
	TNT1 A 1 A_SpawnItem("DeadImp_Half", 5);
	//TROG H -1
	stop;
	
	
Death.SSG:
	//TNT1 A 0 a_spawnprojectile("MeatDeath", 0, 0, random(0, 360), 2, random(0, 160))
	TNT1 A 0 A_SpawnItem("healthbonus");
	TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
	TNT1 AA 0 a_spawnprojectile("XDeathImpArm", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeathImpHead", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperGoreSpawner", 22, 0, random(170, 190), 2, random(0, 15));
	TNT1 A 0 A_XScream;
	TNT1 A 0 A_NoBlocking;
	IZD1 EFGH 6;
	TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	IZD1 H -1;
	stop;
	
Death.Fatality:
Death.SuperPunch:
Death.ExtremePunches:
Pain.Fatality:
Active:
	TNT1 A 1 A_FaceTarget;
	TNT1 A 0 A_NoBlocking;
	TNT1 A 0 ;//A_GiveToTarget("HasImpShield = true;}
	TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
	TRO2 E 8;
	stop;
	
Death.Shotgun:
Death.Blast:
Death.Railgun:
	TNT1 A 0 A_XScream;
	TNT1 A 0 A_SpawnItem("healthbonus");
	TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
	TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeathImpArm", 32, 0, random(150, 210), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeathImpHead", 32, 0, random(150, 210), 2, random(0, 40));
	TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAA 0 a_spawnprojectile("BloodMist", 40, 0, random(0, 360), 2, random(30, 90));
	TR03 A 6 A_stop;
	TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	TR03 BBBBBBBBBB 3 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(30, 60));
	TR03 CCC 3 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(10, 40));
	TR03 DD 3 a_spawnprojectile("Brutal_FlyingBlood", 6, 0, random(0, 360), 2, random(30, 60));
	TR03 E -1;
	stop;
}
}


CLASS BrutalizedImp4 : SwitchableDecoration { 
	Default {
		Radius 16;
		Height 50;
		Health 115;
		PainSound "imp/pain";
		PainChance 256;
		Mass 999999;
		-SOLID;
		+SHOOTABLE;
		+NORADIUSDMG;
		+NODAMAGETHRUST;
		Scale 1.02;
		+usespecial;
		Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	}
	States
	{
		Death.Fatality:
		Death.SuperPunch:
		Active:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ;//A_GiveToTarget("HasImpShield = true;}
			TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
			I9PC O 6;
			stop;
			
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Recoil(1);
			TNT1 A 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
			I9PC OOOOOOO 5 a_spawnprojectile("Brutal_FlyingBlood", 25, 0, random(0, 360), 2, random(10, 40));
			Goto DieNow;
			
		Pain:
			TNT1 A 0 {self.bNopain = true;}
			TNT1 A 0 A_Jump(128, "Pain2");
			TNT1 A 0 A_Pain;
			I9PC MNO 3 a_spawnprojectile("Brutal_FlyingBlood", 25, 0, random(0, 360), 2, random(10, 40));
			TNT1 A 0 {self.bNopain = false;}
			Goto Spawn;
			
		Pain2:
			TNT1 A 0 A_Pain;
			I9PC ONM 3 a_spawnprojectile("Brutal_FlyingBlood", 29, 0, random(0, 360), 2, random(10, 40));
			TNT1 A 0 {self.bNopain = false;}
			Goto Spawn;
			
		DieNow:
			TNT1 A 0;
			TNT1 A 0 A_NoBlocking;
			I9PC PQR 5;
			TNT1 A 0 A_SpawnItem("GrowingBloodPool");
			TNT1 A 0 A_SpawnItem("BrutalizedImp4stop", 2);
			stop;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("healthbonus");
			TNT1 A 0 A_Jump(43, "Death2");
			TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
			TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
			TNT1 A 0 a_spawnprojectile("XDeathHalfImpUpperPart32", 27, 0, random(150, 210), 2, random(0, 40));
			TNT1 A 0 a_spawnprojectile("XDeathImpHead", 32, 0, random(150, 210), 2, random(0, 40));
			TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAA 0 a_spawnprojectile("BloodMist", 40, 0, random(0, 360), 2, random(30, 90));
			TR04 A 0 A_stop;
			TNT1 A 0 A_SpawnItem("GrowingBloodPool");
			TR04 BBBBBBBBBB 2 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(30, 60));
			TR04 CCC 2 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(10, 40));
			TR04 DD 2 a_spawnprojectile("Brutal_FlyingBlood", 6, 0, random(0, 360), 2, random(30, 60));
			TNT1 A 0 A_SpawnItem("DeadImpTR04E");
			stop;
			
		Death2:
			TNT1 A 0 a_spawnprojectile("XDeathImpArm", 26, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("MuchBlood", 30, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 A_SpawnItem("DyingImpNoArm", 2);
			stop;
			
		Death.SSG:
		Death.Shotgun:
		Death.Blast:
		Death.Railgun:
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_SpawnItem("healthbonus");
			TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
			TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
			TNT1 A 0 a_spawnprojectile("XDeathImpHead", 32, 0, random(150, 210), 2, random(0, 40));
			TNT1 A 0 a_spawnprojectile("XDeathImpArm", 32, 0, random(150, 210), 2, random(0, 40));
			TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAA 0 a_spawnprojectile("BloodMist", 40, 0, random(0, 360), 2, random(30, 90));
			TROG A 6 A_stop;
			TNT1 A 0 A_SpawnItem("GrowingBloodPool");
			TROG BBBBBBBBBB 3 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(30, 60));
			TROG CCC 3 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(10, 40));
			TROG DD 3 a_spawnprojectile("Brutal_FlyingBlood", 6, 0, random(0, 360), 2, random(30, 60));
			TROG E -1;
			stop;
}}


CLASS BrutalizedImp1 : SwitchableDecoration { 
	Default {
		Radius 16;
		Height 50;
		Health 20;
		PainSound "grunt/pain";
		PainChance 255;
		Mass 999999;
		-SOLID;
		+SHOOTABLE;
		+NORADIUSDMG;
		+usespecial;
		Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
		Scale 1.0;
	}
	States
	{
		Death.Fatality:
		Death.SuperPunch:
		Active:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ;//A_GiveToTarget("HasImpShield = true;}
			TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
			IZD1 A 8;
			stop;
			
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Recoil(2);
			TNT1 A 0 a_spawnprojectile("XDeathImpArm", 35, 0, random(0, 360), 2, random(0, 160));
			TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		Pain:
			IZD1 A 30;
			Goto DieNow;
			
		DieNow:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("BrutalizedImpstop");
			stop;
			
		Death:
			TNT1 A 0;
			TNT1 AAAA 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
			TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
			TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
			TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 A_Recoil(2);
			IZD1 B 16;
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("BrutalizedImp2");
			stop;
			
		Death.SSG:
		XDeath:
			TNT1 A 0 A_XScream;
			
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 a_spawnprojectile("ImpXDeath", 0, 0, random(0, 360), 2, random(0, 160));
			stop;
}}

CLASS BrutalizedImpstop: CurbstompedMarine { 
	Default {
		
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
		damagefactor "Melee", 10.0;
		damagefactor "Fatality", 10.0;
		damagefactor "Kick", 10.0;
	}
	States
	{
		Spawn:
			IZD2 ABC 5 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
			IZD3 D -1;
			stop;
			
		Death.Fatality:
		Death.Melee:
		Death.Kick:
		Death.Extremepunches:
			TNT1 A 0;
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			//IZD2 B 7
			TNT1 A 1 A_SpawnItem("BrutalizedImpstop", 5);
			stop;
			
}}
	   
CLASS BrutalizedImp4stop: BrutalizedImpstop { 
	Default {
		
	}
	States
	{
		Spawn:
			I9PC R -1;
			stop;
}}

CLASS BrutalizedImp2: BrutalizedSergeant1 { 
	Default {
		
		+usespecial;
		Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	}
	States
	{
		Spawn:
		Pain:
			IZD1 B 30;
			Goto DieNow;
			
		DieNow:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("BrutalizedImpstop2");
			stop;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_Recoil(2);
			TNT1 A 0 a_spawnprojectile("XDeathImpArm", 35, 0, random(0, 360), 2, random(0, 160));
			TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0;
			IZD1 C 16;
			TNT1 A 0 A_SpawnItem("BrutalizedImp3");
			stop;
			
		Death.Fatality:
		Death.SuperPunch:
		Active:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ;//A_GiveToTarget("HasImpShield = true;}
			TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
			IZD1 B 30;
			stop;
}

}

CLASS BrutalizedImpstop2: BrutalizedImpstop

{ 
	States
	{
		Spawn:
			IZD4 AB 6 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
			IZD4 B -1;
			stop;
			
		Death.Fatality:
		Death.Melee:
		Death.Kick:
		Death.Extremepunches:
			TNT1 A 0;
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			IZD4 A 7;
			TNT1 A 1 A_SpawnItem("BrutalizedImpstop2", 5);
			stop;
}}

CLASS BrutalizedImp3: BrutalizedImp1 { 
	Default {
		
	}
	States
	{
		Spawn:
		Pain:
			IZD1 C 25;
			Goto DieNow;
			
		DieNow:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("BrutalizedImpstop3");
			stop;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_Recoil(2);
			TNT1 A 0 A_SpawnItem("BloodSplasher2");
			TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 AA 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("XDeath4", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 a_spawnprojectile("XDeath2", 40, 0, random(0, 360), 2, random(0, 160));
			TNT1 AAAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 44, 0, random(0, 360), 2, random(0, 50));
			IZD1 EFGH 6;
			TNT1 A 0 A_SpawnItem("healthbonus");
			IZD1 H -1;
			stop;
}}


CLASS BrutalizedImpstop3: BrutalizedImpstop { 
	States
	{
		Spawn:
			IZD3 ABC 6 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
			IZD3 C -1;
			stop;
			
		Death.Fatality:
		Death.Melee:
		Death.Kick:
		Death.Extremepunches:
			TNT1 A 0;
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,15,0,1);
			TNT1 A 0 A_FaceTarget;
			IZD3 B 7;
			TNT1 A 1 A_SpawnItem("BrutalizedImpstop3", 5);
stop;}}
	   
		
CLASS ThisImpGotFuckedHard: CurbstompedMarine { 
	Default {
		Health 200;
		DamageFactor "ExplosiveImpact", 10.0;
	}
	States{Spawn:
		TNT1 A 0 A_Jump(128, "Spawn2");
		ID17 G -1;
		stop;
		
	Death.ExplosiveImpact:
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		ID17 ABCDEF 5;
		TNT1 A 0 A_SpawnItem("ThisImpGotFuckedHard");
		stop;
}}

CLASS ThisImpGotFuckedHard2: CurbstompedMarine { 
	Default {
	Health 200;
	DamageFactor "ExplosiveImpact", 10.0;
	}
States{Spawn:
	ID17 O -1;
	stop;
	
	Death.ExplosiveImpact:
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		ID17 ABCDEF 5;
		TNT1 A 0 A_SpawnItem("ThisImpGotFuckedHard2");
		stop;
}}
	
	
CLASS ImpBrutalizedWithNoLeg : ACTOR { 
	Default {
	Radius 16;
	Height 50;
	Health 20;
	PainSound "grunt/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	Scale 1.0;
	}
	States
	{
	
	Spawn:
		TR09 A 30;
		TR09 BCde 8;
		TNT1 A 0 A_SpawnItem("DeadImp_NoLeg");
	stop;
		
		
		
	Death:
		TNT1 A 0;
		TNT1 AAAA 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathImpArm", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathImpLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		ID17 ABCDEF 5;
		TNT1 A 0 A_SpawnItem("armorbonus");
		TNT1 A 0 A_SpawnItem("ThisImpGotFuckedHard");
		stop;
}}









CLASS DyingImpNoArm : SwitchableDecoration { 
	Default {
	Radius 16;
	Height 32;
	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	Scale 1.0;
	}
	States
	{
	
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
		TNT1 A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ;//A_GiveToTarget("HasImpShield = true;}
		TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
		TR08 B 8;
		stop;
		
	Spawn:
		TR08 B 1;
		//TNT1 A 0 A_Jump(128, "Death")
		Goto Suffer;
	Suffer:
		TR08 BB 4 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(0, 45));
		TR08 B 5;
		TR08 CC 4 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(0, 45));
		TR08 C 5 A_Pain;

	Death:
		TR08 D 8;
		TNT1 A 0 A_SpawnItem("DeadImp_NoArm", 5);
		stop;
		
	Death.Head:
	Death.Decaptate:
	Death.MINORHead:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 30);
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TR08 F 8;
		TNT1 A 0 A_SpawnItem("healthbonus");
		TNT1 A 0 A_SpawnItem("DeadImp_NoArmNoHead");
		stop;
		
	XDeath:
	Death.Explosives:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_SpawnItem("healthbonus");
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 42, 0, random(170, 190), 2, random(10, 60));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 42, 0, random(170, 190), 2, random(10, 60));
		TNT1 A 0 a_spawnprojectile("XDeath2", 42, 0, random(170, 190), 2, random(10, 60));
		TNT1 A 0 a_spawnprojectile("XDeath4", 42, 0, random(170, 190), 2, random(10, 60));
		TNT1 A 1 a_spawnprojectile("ImpXDeath", 0, 0, random(0, 360), 2, random(0, 160));
		stop;
		
	Death.SSG:
	Death.Shotgun:
	Death.Blast:
	Death.Railgun:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_SpawnItem("healthbonus");
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathImpHead", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathImpArm", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("BloodMist", 40, 0, random(0, 360), 2, random(30, 90));
		TROG A 6 A_stop;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TROG BBBBBBBBBB 3 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(30, 60));
		TROG CCC 3 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(10, 40));
		TROG DD 3 a_spawnprojectile("Brutal_FlyingBlood", 6, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_SpawnItem("DeadImpTROGE");
		stop;
}
}



CLASS DyingImpNoLeg : SwitchableDecoration { 
	Default {
	
	
	Radius 16;
	Height 32;
	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	Scale 1.0;
	}
	States
	{
	
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
		TNT1 A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ;//A_GiveToTarget("HasImpShield = true;}
		TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
		TR09 F 8;
		stop;
		
	Spawn:
		IMPC E 1;
		TNT1 A 0;
		TNT1 A 0 A_Jump(32, "Colapse");
		Goto Suffer;
	Suffer:
		TR09 DD 4 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
		TR09 D 5 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
		TR09 FF 4 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 45));
		TR09 F 5 A_Pain;

		Goto Colapse;
	Death:
		TNT1 A 0 A_PlaySound("imp/death");
		TR09 G 8;
		TNT1 A 0 A_SpawnItem("DeadImp_NoLeg", 5);
		stop;
		
	Colapse:
		TR09 H 8;
		TNT1 A 0 A_SpawnItem("DeadImp_NoLeg", 5);
		stop;
		
	Death.Head:
	Death.Decaptate:
	Death.MINORHead:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 30);
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TR09 I 8;
		TNT1 A 0 A_SpawnItem("DeadImp_Noleg");
		TNT1 A 0 A_SpawnItem("healthbonus");
		stop;
}
}





CLASS ImpDyingOfBloodLoss: switchabledecoration { 
	Default {
	
	Radius 16;
	Height 28;
	Health 10;
	+NOPAIN;
	-COUNTKILL;
	+SHOOTABLE;
	+usespecial;
	Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
	}
	States
	{
	
	Death.Fatality:
	Death.SuperPunch:
	Death.ExtremePunches:
	Pain.Fatality:
	Active:
		TNT1 A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ;//A_GiveToTarget("HasImpShield = true;}
		TNT1 A 0 ;//A_GiveToTarget("GotMeatShield = true;}
		TROD F 8;
		stop;
		
	Spawn:
		TROD E 1;
		TROD EFEFEFEFEFEFEFEFEFEFEFEF 10;
		Goto Colapse;
	Death:
		TNT1 A 0;
		stop;//Goto DeathNoGuts;
		
	Death.Shotgun:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfCloser(150, "Death.Shotgunontheface");
		stop;//Goto DeathNoGuts;
		
	Colapse:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking;
		TROD GHIJ 5;
		TNT1 A 0 A_SpawnItem("DeadImpBloodLoss", 5);
		stop;
}
}


CLASS ImpSaciLol: DyingImpNoLeg { 
	Default {
	
	//MONSTER
	-COUNTKILL;
	Speed 4;
	Height 48;
	}
	States
	{
	
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("imp/pain");
		Goto Suffer;
		
	Suffer:
		ZL3E ABC 3;
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 30);
		ZL3E DDDD 1 A_Chase(null, null);
		TNT1 A 0 A_PlaySound("imp/pain");
		

		TNT1 A 0 A_SpawnItem("DyingImpNoLeg");
		stop;
	Death.Head:
		TNT1 A 0 A_PlaySound("misc/xdeath");
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 50);
		Goto FallHead;
	FallHead:
		ZL3E EFG 7;
		TNT1 A 0 A_SpawnItem("DeadImp_NoLeg");
		stop;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("imp/death");
		ZL3E HIJ 7;
		TNT1 A 0 A_SpawnItem("DeadImp_NoLeg");
		stop;
}
}

