class proto_imp_class : pb_monster_base
{
bool on_floor, ceiling_jump, on_ceiling, attack_jump, first_seeing;

default
{
	height 54;
	radius 18;

	pb_monster_base.headshot_multiplier 2;
	pb_monster_base.head_starting_position 48;
	pb_monster_base.legs_height_max 10;
}

sector prev_sector;
//to check current and previous actor sectors for ceiling imps

protected bool pb_check_for_ceiling()
{
	if(curSector.GetTexture(curSector.ceiling) == skyflatnum)//there are sky at the ceiling
	{return false;}
	
	return true;
}
	
protected void pb_change_flags_for_jump()
{
	if(self is "proto_imp_class")
	{
		if(proto_imp_class(self).on_ceiling == true && proto_imp_class(self).on_floor == false)
		{
			bNOGRAVITY = true;
			bTHRUSPECIES = true;
			bNOVERTICALMELEERANGE = true;
		}
		
		if(proto_imp_class(self).on_ceiling == false && proto_imp_class(self).on_floor == true)
		{
			bNOGRAVITY = false;
			bTHRUSPECIES = false;
			bNOVERTICALMELEERANGE = false;
		}
	}
}

protected bool pb_imp_ceiling_jump()
{
	if(ceiling_jump == true) {return false;}
	if(pb_check_for_ceiling() == false) {return false;}
	if(self.ceilingz - self.floorz > 300) {return false;}

	double jump_vel = sqrt(self.getgravity() * 2 * self.ceilingz);

	if(jump_vel > 0) {self.vel.z = jump_vel; ceiling_jump = true;}
	return true;
}

override void tick()
{
	super.tick();
	
	if(ceiling_jump == true)
	{
		if( (self.pos.z + self.height >= self.ceilingz) )
		{ceiling_jump = false; return;}

		if(self.pos.z == self.floorz) {ceiling_jump = false; return;}
	}
	
}

states
{
	Death.Blackhole:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 27, 0, 0, 0, 0, 128);
		ID52 ABCDEFGHIJ 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 0, 6, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
	stop;
	
	Death.Desintegrate:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("DesintegratedHuman");
		TNT1 A 0 A_PlaySound("desintegratedflesh", 3);
		TNT1 A 0 A_PlaySound("MELT",6);
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 22, 0, random (0, 360), 2, random (0, 90));
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 37, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 37, 0, random (0, 360), 2, random (10, 50));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 30, 0, random (0, 360), 2, random (0, 90));
		TNT1 A 0 a_spawnprojectile("SuperGoreSpawner2", 30, 0, random (0, 360), 2, random (10, 90));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("Barrel_explosion_Column");
		
		TNT1 A 0 A_Jump(128, "desintegrate_2");
		ID50 AAABBBCCCDDDEEEFFFGGGGGGGGGGGGGGGGGGG 2 a_spawnprojectile("Brutal_LiquidBlood3", 18, 0, random (0, 360), 2, random (0, 40));
		ID50 G -1;
	stop;
		
	desintegrate_2:
       M31T CCCCCDDDDDEEEEEFFFFGGGGHHHHIIIIJJJJKKKKKKKKKKKKK 2 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
       M31T K -1;
	Stop;
}

}
















CLASS BrainsImpHeadPiece: Brains4 { //White skinned piece 1
	Default {
	Speed 2;
	-DOOMBOUNCE;
	Scale 1.0;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		BR7N E 4 a_spawnprojectile("named_BloodTr", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		BR7N E 1;
		TNT1 A 0 A_QueueCorpse;
 	Rest:
		BR7N E 800;
		BR7N E -1;
		Stop;
	DoNothing:
		TNT1 A 0;
		Stop;
	}
}


CLASS BrainsSavageImpHeadPiece: Brains4 { //White skinned piece 1
	Default {
	Speed 2;
	-DOOMBOUNCE;
	Scale 1.0;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		1HED A 4 a_spawnprojectile("named_BloodTr", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		1HED A 1;
		TNT1 A 0 A_QueueCorpse;
 	Rest:
		1HED A 800;
		1HED A -1;
		Stop;
	DoNothing:
		TNT1 A 0;
		Stop;
	}
}


CLASS XDeathImpArm: XDeathArm1 { 
	Default {
    Scale 1.1;
    Speed 8;
	Gravity 0.4;
	bounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		HND4 ABCDEFGH 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death.plasma:    TNT1 A 0 a_spawnprojectile("XDeathBurnedImpArm", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:
		HND4 X 1;
		//HND4 X -1
		HND4 X 0 A_SpawnItem("Gib_ImpArm",0,0,0,1);
		Stop;
	}
}

CLASS XDeathSavageImpArm: XDeathImpArm { 
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		9ND4 ABCDEFGH 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
		
	Death.plasma:
	TNT1 A 0 a_spawnprojectile("XDeathBurnedImpArm", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:
		9ND4 X 1;
		//9ND4 X -1
		9ND4 X 0 A_SpawnItem("Gib_SavageImpArm",0,0,0,1);
		Stop;
	}
}


CLASS Gib_ImpArm: LimbBase { 
	Default {
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		HND4 X 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		HND4 X -1;
		Stop;
Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 a_spawnprojectile("XDeathBurnedImpArm", 32, 0, random(0, 360), 2, random(0, 160));
        Stop;
Death:    
	TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 A 0 a_spawnprojectile("GibImpHand", 0, 0, random(0, 180), 2, random(0, 180));
	TNT1 A 0 a_spawnprojectile("GibImpArmPart", 0, 0, random(0, 180), 2, random(0, 180));
	Stop;
	Stop;
Death.Kick:
Death.Melee:
Death.SuperPunch:
	HND4 AA 1 A_FaceTarget;
	TNT1 A 0 a_spawnprojectile("XDeathImpArm", 5, 0, random(170, 190), 2, random(20, 40));
	Stop;
	
Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	HND4 ABCDEFGH 3;
	Goto Spawn;
	
Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	HND4 X 5;
	HND4 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
Landz:
	XDT5 I 0 A_SpawnItem("Gib_ImpArm");
	Stop;
}}

CLASS Gib_SavageImpArm: Gib_ImpArm {
    States
    {
    Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
        9ND4 X 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
        9ND4 X -1;
        Stop;
	Death.plasma: Death.Burn: Death.Flames:	    TNT1 A 0 a_spawnprojectile("XDeathBurnedImpArm", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
    Death:    
    TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
    TNT1 A 0 a_spawnprojectile("GibSavageImpHand", 0, 0, random(0, 180), 2, random(0, 180));
    TNT1 A 0 a_spawnprojectile("GibSavageImpArmPart", 0, 0, random(0, 180), 2, random(0, 180));
Stop;

	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
	    9ND4 AA 1 A_FaceTarget;
	TNT1 A 0 a_spawnprojectile("XDeathSavageImpArm", 5, 0, random(170, 190), 2, random(20, 40));
	Stop;
	
	Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	9ND4 ABCDEFGH 3;
	Goto Spawn;
	
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	9ND4 X 5;
	9ND4 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
	Landz:
	XDT5 I 0 A_SpawnItem("Gib_SavageImpArm");
	Stop;
}}

CLASS GibImpArmPart: TinyGib { 
	Default {
 
    Scale 1.1;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
        HND4 Z -1;
        Stop;
    Death:
        HND4 Z 1;
       Loop;
}}

CLASS GibImpHand: TinyGib { 
	Default {
 
    Scale 0.8;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
        HND4 Y -1;
        Stop;
    Death:
        HND4 Y 1;
       Loop;
}}


CLASS GibSavageImpArmPart: TinyGib { 
	Default {
 
    Scale 1.1;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
        9ND4 Z -1;
        Stop;
    Death:
        9ND4 Z 1;
       Loop;
}}



CLASS GibSavageImpHand: TinyGib { 
	Default {
 
    Scale 0.8;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
        9ND4 Y -1;
        Stop;
    Death:
        9ND4 Y 1;
       Loop;
}}


CLASS XDeathHalfImpUpperPart32 : pb_blood_and_gore_base { 
	Default {
 
    Radius 2;
    Height 2;
    Scale 1.1;
	Speed 12;
	Gravity 0.3;
	Mass 4;
	Decal "BrutalBloodSplat";
	bounceFactor 0.2;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	}
	States
	{
	Spawn:
		//TNT1 A 0 A_SpawnItem("Brutal_LiquidBlood",0,0,0,1)
		HND4 IJKLMNOPQ 3 a_spawnprojectile("Brutal_LiquidBlood",0,0,0,1);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 AAA 0 A_spawnItem("Blood", 0, 10);
		HND4 Q 1 A_SpawnItem("Gib_HalfImpUpperPart32",0,0,0,1);
		TNT1 A 0;
		Stop;
	}
}

CLASS XDeathHalfSavageImpUpperPart32 : pb_blood_and_gore_base { 
	Default {
	
	Radius 2;
	Height 2;
	Scale 1.1;
	Speed 12;
	Gravity 0.3;
	Mass 4;
	Decal "BrutalBloodSplat";
	BounceFactor 0.2;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	}
	States
	{
	Spawn:
		//TNT1 A 0 A_SpawnItem("Brutal_LiquidBlood",0,0,0,1)
		9ND4 IJKLMNOPQ 3 a_spawnprojectile("Brutal_LiquidBlood",0,0,0,1);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 AAA 0 A_spawnItem("Blood", 0, 10);
		9ND4 Q 1 A_SpawnItem("Gib_HalfSavageImpUpperPart32",0,0,0,1);
		TNT1 A 0;
		Stop;
	}
}

CLASS Gib_HalfImpUpperPart32: BigGibBase { 
	Default {
	
	damagefactor "ExplosiveImpact", 5.0;
	Mass 10;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		HND4 Q -1;
		Stop   ;
	Death.ExplosiveImpact:
	Death.Explosive:
	Death.Kick:
	Death.SuperPunches:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		Goto Fly;
	Fly:
		HND4 IJKLMNOPQ 3 A_CheckFloor("Land");
		Loop;
	Land:
		HND4 Q 1 A_SpawnItem("Gib_HalfImpUpperPart32",0,0,0,1);
Stop; }}	 

CLASS Gib_HalfSavageImpUpperPart32: BigGibBase { 
	Default {
	
	damagefactor "ExplosiveImpact", 5.0;
	Mass 10;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		9ND4 Q -1;
		Stop   ;
	Death.ExplosiveImpact:
	Death.Explosive:
	Death.Kick:
	Death.SuperPunches:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		Goto Fly;
	Fly:
		9ND4 IJKLMNOPQ 3 A_CheckFloor("Land");
		Loop;
	Land:
		9ND4 Q 1 A_SpawnItem("Gib_HalfSavageImpUpperPart32",0,0,0,1);
Stop; }}



CLASS XDeathImpLeg: XDeathArm1 { 
	Default {
	
	Scale 1.1;
	Speed 8;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		LEG4 ABCDEFGH 5 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		LEG4 I 1;
		LEG4 I 1 A_SpawnItem("Gib_ImpLeg");
		Stop;
		
	}
}

CLASS XDeathSavageImpLeg: XDeathImpLeg { 
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		1EG4 ABCDEFGH 5 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		1EG4 I 1;
		1EG4 I 1 A_SpawnItem("Gib_SavageImpLeg");
		Stop;
		
	}
}

CLASS Gib_ImpLeg: LimbBase { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG4 I 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		LEG4 I -1;
		Stop;
Death.plasma: Death.Burn: Death.Flames:
    TNT1 A 0 a_spawnprojectile("XDeathBurnedImpLeg", 32, 0, random(0, 360), 2, random(0, 160));        
Stop;
Death:    
	TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 A 0 a_spawnprojectile("GibImpLegPart", 0, 0, random(0, 180), 2, random(0, 180));
	TNT1 A 0 a_spawnprojectile("GibImpPaw", 0, 0, random(0, 180), 2, random(0, 180));
	Stop;
Death.Kick:
Death.Melee:
Death.SuperPunch:
	LEG4 A 1 A_FaceTarget;
	TNT1 A 0 a_spawnprojectile("XDeathImpLeg", 5, 0, random(170, 190), 2, random(20, 40));
	Stop;
	
Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	LEG4 ABCDEFGH 2;
	Goto Spawn;
	
Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	LEG4 A 5;
	LEG4 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
Landz:
	XDT5 I 0 A_SpawnItem("Gib_ImpLeg");
	Stop;
}}

CLASS Gib_SavageImpLeg: LimbBase { 
	Default {
 
    Scale 1.1;
	}
    States
    {
    Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	1EG4 I 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	1EG4 I -1;
        Stop;
Death.plasma: Death.Burn: Death.Flames:
	    TNT1 A 0 a_spawnprojectile("XDeathBurnedImpLeg", 32, 0, random(0, 360), 2, random(0, 160));
Stop;
    Death:    
    TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
    TNT1 A 0 a_spawnprojectile("GibSavageImpLegPart", 0, 0, random(0, 180), 2, random(0, 180));
    TNT1 A 0 a_spawnprojectile("GibSavageImpPaw", 0, 0, random(0, 180), 2, random(0, 180));
Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
	    1EG4 A 1 A_FaceTarget;
	TNT1 A 0 a_spawnprojectile("XDeathImpLeg", 5, 0, random(170, 190), 2, random(20, 40));
	Stop;
	
	Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	1EG4 ABCDEFGH 2;
	Goto Spawn;
	
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	1EG4 A 5;
	1EG4 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
	Landz:
	1EG4 I 0 A_SpawnItem("Gib_SavageImpLeg");
	Stop;
}}

CLASS GibImpLegPart: TinyGib { 
	Default {
 
    Scale 1.1;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	LEG4 Z -1;
        Stop;
    Death:
LEG4 Z 1;
       Loop;
}}

CLASS GibImpPaw: TinyGib { 
	Default {
 
    Scale 1.1;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	LEG4 Y -1;
        Stop;
    Death:
LEG4 Y 1;
       Loop;
}}

CLASS GibSavageImpLegPart: TinyGib { 
	Default {
 
    Scale 1.1;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	1EG4 Z -1;
        Stop;
    Death:
1EG4 Z 1;
       Loop;
}}

CLASS GibSavageImpPaw: TinyGib { 
	Default {
 
    Scale 1.1;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	1EG4 Y -1;
        Stop;
    Death:
1EG4 Y 1;
       Loop;
}}



CLASS XDeathHalfImp : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Speed 7;
	Mass 8;
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TROG I 12 a_spawnprojectile("pb_FlyingBloodTrail",0,0,180,2);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TROG I 0 A_SpawnItem("HalfImpGib",0,0,0,1);
		Stop;
	}
}


CLASS HalfImpGib: BigGibBase { 
	Default {
	
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		TROG J 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TROG J -1;
Stop;    }}


CLASS XDeathImpHead: XDeathChaingunguyHead { 
	States
	{
	Spawn:
	Spawn1:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		XHE4 AB 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		XHE4 CDEFGH 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		XHE4 E 1;
		XHE4 E 1 A_SpawnItem("ImpHead",0,0,0,1);
		Stop;
	}
}

CLASS XDeathSavageImpHead: XDeathChaingunguyHead { 
	States
	{
	Spawn:
	Spawn1:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		7HE4 AB 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		7HE4 CDEFGH 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		7HE4 E 1;
		7HE4 E 1 A_SpawnItem("SavageImpHead",0,0,0,1);
		Stop;
	}
}


CLASS XDeathImpHeadBeheaded: XDeathImpHead { 
	Default {
	
	Speed 5;
	Gravity 0.5;
	}
}

CLASS XDeathImpHeadOnXDeath: XDeathImpHead { 
	States
	{
	Spawn:
		TNT1 A 1;
		TNT1 A 0 A_jump(96, "ExplodeOnAir");
		Goto Spawn1;
	ExplodeOnAir:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("ImpHeadExplode");
		Stop;
}}

CLASS XDeathSavageImpHeadOnXDeath: XDeathSavageImpHead { 
	States
	{
	Spawn:
		TNT1 A 1;
		TNT1 A 0 A_jump(96, "ExplodeOnAir");
		Goto Spawn1;
	ExplodeOnAir:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("SavageImpHeadExplode");
		Stop;
}}

CLASS ImpHead: ZombieManHead { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot");
		TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
	Spawn1:
		XHE4 C 1;
		XHE4 C -1;
		Stop;
	Spawn2:
		XHE4 G 1;
		XHE4 G -1;
		Stop;
	Spawn3:
		XHE4 H 1;
		XHE4 H -1;
		Stop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("ImpHeadExplode");
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		XHE4 EE 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathImpHead", 5, 0, random(170, 190), 2, random(20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		XHE4 ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		XHE4 ABCDEFGH 3;
		XDT5 I 0 A_SpawnItem("ImpHead");
		Stop;
		
}}

CLASS SavageImpHead: ZombieManHead { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot");
		TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
	Spawn1:
		7HE4 C 1;
		7HE4 C -1;
		Stop;
	Spawn2:
		7HE4 G 1;
		7HE4 G -1;
		Stop;
	Spawn3:
		7HE4 H 1;
		7HE4 H -1;
		Stop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("SavageImpHeadExplode");
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		7HE4 EE 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathSavageImpHead", 5, 0, random(170, 190), 2, random(20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		7HE4 ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		7HE4 ABCDEFGH 3;
		XDT5 I 0 A_SpawnItem("SavageImpHead");
		Stop;
		
}}


CLASS ImpXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 NoDelay A_Jump(110, "Spawn2");
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 40, 0, random(0, 360), 2, random(-15, 15));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathImpArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfImpUpperPart32", 32, 0, random(0, 360), 2, random(10, 60));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath5", 32, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 AAAAAAA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathImpLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathImpHeadOnXDeath", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
		
	Spawn2:
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 40, 0, random(0, 360), 2, random(-15, 15));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathImpArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath5", 32, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 A 0 a_spawnprojectile("XDeathNewImpLowerTorso", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathNewImpUpperTorso", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathImpLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathImpHeadOnXDeath", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
		
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("SuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
}
}

CLASS SavageImpXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		TNT1 AAAAAAAAAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 40, 0, random(0, 360), 2, random(-15, 15));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 a_spawnprojectile("XDeathSavageImpArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfSavageImpUpperPart32", 32, 0, random(0, 360), 2, random(10, 60));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath5", 32, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 AAAAAAA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSavageImpLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathSavageImpHeadOnXDeath", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
		
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("SuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SuperGoreSpawner2", 64, 0, random(0, 360), 2, random(20, 40));
		Stop;
}
}


CLASS RipImp : pb_blood_and_gore_base { 
Default {
	
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("Instestin2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfImp", 40, 0, random(0, 360), 2, random(0, 160));
	Death:
		TNT1 A 0;
		Stop;
}
}


CLASS ImpHeadExplode: ZombieXDeath { 
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("Brains2", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("BrainsImpHeadPiece", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPiece", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Teeth", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 90));
		TNT1 A 10;
		Stop;
}
}

CLASS SavageImpHeadExplode: ImpHeadExplode { 
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("Brains2", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("BrainsSavageImpHeadPiece", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPiece", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Teeth", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 90));
		TNT1 A 10;
		Stop;
}
}


CLASS XDeathBurnedImpLeg : XDeathBurnedLeg { 
States
{
	Spawn:
		CARB F 10 a_spawnprojectile("ExplosionSmoke",0,0,180,2);
		Loop;
	Death:
		CARB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 14 a_spawnprojectile("ExplosionSmoke", 1, 0, random(0, 360), 2, random(0, 160));
		CARB F -1;
		Stop;
}
}


CLASS XDeathBurnedImpArm : XDeathBurnedLeg { 
States
{
	Spawn:
		CARB G 10 a_spawnprojectile("ExplosionSmoke",0,0,180,2);
		Loop;
	Death:
		CARB GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG 14 a_spawnprojectile("ExplosionSmoke", 1, 0, random(0, 360), 2, random(0, 160));
		CARB G -1;
		Stop;
}
}


CLASS XDeathNewImpUpperTorso : pb_blood_and_gore_base { 
	Default {
 
    Radius 8;
    Height 8;
    
	Speed 10;
	Gravity 0.7;
	Mass 4;
	Decal "BrutalBloodSplat";
bounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			4N04 ABCDEFGHI 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_NewImpUpperTorso",0,0,0,1);
			Stop;
	}
}

CLASS Gib_NewImpUpperTorso: BigGibBase { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			4N04 J 1;
			4N04 J -1;
Stop;    }}
	   
//Imp Lower Torso
CLASS XDeathNewImpLowerTorso : pb_blood_and_gore_base { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			4N03 ABCDEFGHI 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
			TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_NewImpLowerTorso",0,0,0,1);
			Stop;
	}
}

CLASS Gib_NewImpLowerTorso: BigGibBase { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			4N03 J 1;
			4N03 J -1;
Stop;    }}
	   

