//===========================================================================
//
// Carbine Rifle Zombie
//
//===========================================================================
CLASS pb_carbine_Zombie_Man : pb_zombie_man// Replaces ZombieMan
{ 
Default
{
	+FLOORCLIP;

	Health 70;
	GibHealth 70;
	Speed 9;
	FastSpeed 20;
	PainChance 160;

	SeeSound "grunt/sight";
	AttackSound "weapons/rifle/fire";
	PainSound "grunt/pain";
	DeathSound "grunt/death";
	ActiveSound "grunt/active";
	Obituary "%o was perforated by an Assault Gunner.";

//	//DropItem "DropedCarbine";
//	//DropItem "DropedGrenade", 15;

	Damagefactor "ExtremePunches", 1.25;
	Damagefactor "Fatality", 1.25;
}

States
{
	Spawn:
		tnt1 a 0;
 		TNT1 A 0 {ammo_amount = random(0, max_magazine_size);}//A_GiveInventory("ZombieManAmmo", random(1,10));
	Goto Stand;
		
	Stand:
		RFTR AB 10 A_Look();
	Loop;

	See:
		TNT1 A 0 A_JumpIfHealthLower(1, "Death");
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 A_TakeInventory("EnemyMemory", 15);
		TNT1 A 0 A_CheckSight("SeeNeverSeen");
	SeeContinue:
		TNT1 A 0 A_JumpIfHealthLower(1, "Death");
		TNT1 A 0 {
			self.bSOLID = true;
			self.bSHOOTABLE = true;
			self.bGHOST = false;
			self.bINVULNERABLE = false;
		}
		TNT1 A 0 A_JumpIfCloser(200, "FallBack");
	Advance:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		TNT1 A 0 A_JumpIfInventory("EnemyMemory", 15, "SearchForPlayer");
		TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
		
		RFTR AA 2 A_Chase();
		TNT1 A 0 A_Recoil(-1);
		TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		RFTR BB 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
		RFTR CCDD 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
	Loop;


	Missile:
		//TNT1 A 0 A_TakeInventory("SKARZombie", 1);
		TNT1 A 0 A_JumpIfInventory("Enraged", 1, "SpecialAttack");
		TNT1 A 0 A_Jump(80,"SpecialAttack");//80 out of 255 chance to do a special attack
		TNT1 A 0 A_JumpIfInventory("NoZombieGrenade", 1, "JustShootTheFuckingRifle1");
		TNT1 A 0 A_Jump(18, "ThrowGrenade");//18 out of 255 chance to do a grenade attack
	JustShootTheFuckingRifle1:
		TNT1 A 0 {ammo_amount -= 2;}//A_GiveInventory("ZombieManAmmo", 2);
		TNT1 A 0 A_Jump(108, "JustShootTheFuckingRifle2", "JustShootTheFuckingRifle3");
		RFTR E 4 A_FaceTarget();
		RFTR E 2 A_FaceTarget();
		RFTR E 3 A_FaceTarget();
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		RFTR F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 0, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		RFTR E 1 A_facetarget();
		RFTR E 2 A_facetarget();
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		RFTR F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 0, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		RFTR E 1 A_facetarget();
		RFTR E 2 A_facetarget();
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		RFTR F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 0, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		RFTR E 1 A_facetarget();
		RFTR E 2 A_facetarget();
		RFTR E 5 A_FaceTarget();
		TNT1 A 0 pb_check_reloading();//A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
		TNT1 A 0 A_JumpIfInventory("Enraged", 1, "Missile");
		TNT1 A 0 A_jump(96, "Missile");
	Goto SeeContinue;




































	pain.Siphon:
		//TNT1 AAA 0 A_SpawnItemEx("RedLightning_Small", random(-12, 12), random(-12, 12), random(16, 52), 0, 0);
		RFTR G 1
		{
			A_FaceTarget();
			A_GiveToTarget("HealthBonus",4);
		}
		RFTR G 5 A_FaceTarget;
		TNT1 A 0 A_Pain;
	Goto See;

	Possession:
		TNT1 A 0 A_SetInvulnerable();
		RFTR G 3;
		RFTR G 3 A_Pain();
 		TNT1 A 0 A_UnSetInvulnerable();
	Goto See;
		
	Pain.Stun:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx("StunElectrocute", random(-4, 4), random(-4, 4),  random(16, 32), 0, 0);
		RFTR G 1 A_Pain();
		RFTR GGGGGGGGGG 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		RFTR G 1 A_Pain();
		RFTR GGGGGGGGGG 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		RFTR G 1 A_Pain();
		RFTR GGGGGGGGGG 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		RFTR G 1 A_Pain();
		RFTR GGGGGGGGGG 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		RFTR G 1 A_Pain();
		RFTR GGGGGGGGGG 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		RFTR G 1 A_Pain();
	Goto See;
		
	Death.Shrink:
		TNT1 A 1 A_PlaySound("Shrink", 3);
/*		TNT1 A 0 A_SpawnItemEx("ARZombieManShrinkFX1", 0, 0,  5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("ARZombieManShrinkFX2", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("ARZombieManShrinkFX3", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("ARZombieManShrinkFX4", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("ARZombieManShrinkFX5", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("ARZombieManShrinkFX6", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("ARZombieManShrinkFX7", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("LilARZombieMan", 1);*/
	stop;
		
	WalkAround:
		TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		RFTR A 2 A_Look();
		RFTR A 2 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		
		RFTR B 2 A_Look();
		RFTR B 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",3);
		RFTR D 2 A_Look();
		RFTR D 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",4);
		RFTR C 2 A_Look();
		RFTR C 2 A_Wander();
		RFTR D 2 A_Look();
		RFTR D 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",4);
		RFTR B 2 A_Look();
		RFTR B 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",4);
		TNT1 A 0 A_Jump(32, "Stand");
	Loop;
		
		
	SearchForPlayer:
	Idle:
		TNT1 A 0 A_ClearTarget();
		TNT1 A 0 A_TakeInventory("EnemyMemory", 30);
		TNT1 A 0 A_GiveInventory("SKZombieMan", 1);
		RFTR A 10 A_Look();
		RFTR B 10 A_Look();
		TNT1 A 0 A_SetAngle(angle - 40);
		RFTR A 10 A_Look();
		RFTR C 10 A_Look();
		TNT1 A 0 A_SetAngle(angle + 40);
		RFTR A 10 A_Look();
		RFTR D 10 A_Look();
		TNT1 A 0 A_SetAngle(angle + 40);
		RFTR A 10 A_Look();
		
		RFTR A 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		RFTR B 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		RFTR C 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		RFTR D 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		
		TNT1 A 0 A_Jump(128, "Idle");
		RFTR A 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		RFTR B 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		RFTR C 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		RFTR D 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		Loop;
		
	FallBack:
		TNT1 A 0 A_CheckSight("Advance");
		TNT1 A 0 {self.bNODROPOFF = true;}
		RFTR D 2 A_FaceTarget();
		RFTR D 2 A_Recoil(2);
		TNT1 A 0 A_jump(64, "Missile");
		RFTR C 2 A_FaceTarget();
		RFTR C 2 A_Recoil(2);
		RFTR B 2 A_FaceTarget();
		RFTR B 2 A_Recoil(2);
		RFTR A 2 A_FaceTarget();
		RFTR A 2 A_Recoil(2);
		RFTR D 2 A_FaceTarget();
		RFTR D 2 A_Recoil(2);
		TNT1 A 0 A_jump(64, "Missile");
		RFTR C 2 A_FaceTarget();
		RFTR C 2 A_Recoil(2);
		RFTR B 2 A_FaceTarget();
		RFTR B 2 A_Recoil(2);
		RFTR A 2 A_FaceTarget();
		RFTR A 2 A_Recoil(2);
	Goto Missile;
		

		
	SeeNeverSeen:
		TNT1 A 0 A_JumpIfCloser(200, "FallBack");
	Advance:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		RFTR AA 2 A_Chase();
		TNT1 A 0 A_Recoil(-1);
		TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		RFTR BB 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
		RFTR CC 2 A_Chase();
		RFTR DD 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
	Loop;
		

		
	SpecialAttack:
	JustShootTheFuckingRifle2:
		P066 E 6 A_FaceTarget();
		TNT1 A 0 {ammo_amount -= 2;}//A_GiveInventory("ZombieManAmmo", 2);
		
		P066 E 1 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 42, 18, 15, 0);
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		P066 E 1 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-6, 6), 1, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 36,0);
		P066 E 2 A_FaceTarget();
		
		P066 E 1 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 42, 18, 15, 0);
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		P066 E 1 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-6, 6), 1, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 36,0);
		P066 E 2 A_FaceTarget();
		
		P066 E 1 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 42, 18, 15, 0);
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		P066 E 1 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-6, 6), 1, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 36,0);
		P066 E 2 A_FaceTarget();
		
		P066 E 6 A_FaceTarget();
		TNT1 A 0 pb_check_reloading();//A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
		TNT1 A 0 A_JumpIfInventory("Enraged", 1, "Missile");
		TNT1 A 0 A_jump(96, "Missile");
	Goto SeeContinue;
		
	Pain.Taunt:
		//TNT1 A 0 A_TakeInventory("SKARZombie", 3);
		TNT1 A 0 A_JumpIfInventory("NoZombieGrenade", 1, "JustShootTheFuckingRifle2");
		TNT1 A 0 A_Jump(32, "ThrowGrenade");//32 out of 255 chance to do a grenade attack
	JustShootTheFuckingRifle3:
		TNT1 A 0 {ammo_amount --;}//A_GiveInventory("ZombieManAmmo", 1);
		RFTR E 3 A_FaceTarget();
		RFTR E 1 A_FaceTarget();
		RFTR E 2 A_FaceTarget();
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		RFTR F 1 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 0, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		RFTR E 2 A_facetarget();
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		RFTR F 1 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 0, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		RFTR E 2 A_facetarget();
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		RFTR F 1 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 0, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		RFTR E 2 A_facetarget();
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		RFTR F 1 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 0, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		RFTR E 2 A_facetarget();
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		RFTR F 1 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 0, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		RFTR E 2 A_facetarget();
		RFTR E 5 A_FaceTarget();
		TNT1 A 0 pb_check_reloading();//A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
	Goto Missile+1;
		
	ThrowGrenade:
		TNT1 A 0 A_Stop();
		TNT1 A 0 {self.bGHOST = false;}
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 A_TakeInventory("EnemyMemory", 10);
		TNT1 A 0 A_JumpIfInventory("ZombieManGrenadeCount", 3, "JustShootTheFuckingRifle1");
		TNT1 A 0 A_JumpIfCloser(500, 1);
	Goto Missile+6;
		TNT1 A 0 A_JumpIfCloser(80, "SpecialAttack");
		TNT1 A 0 A_JumpIfInventory("ZombieManGrenadeCount", 3, "JustShootTheFuckingRifle");
		RFG1 A 6 A_FaceTarget();
		TNT1 A 0 A_PLaySound("GRNPIN");
		RFG1 A 6 A_FaceTarget();
		TNT1 A 0 A_PlaySound("THRGRN", 1);
		TNT1 A 0 A_GiveInventory("ZombieManGrenadeCount", 1);
		RFG1 B 6 a_spawnprojectile("monsters_hand_grenade", 42);
	Goto SeeContinue;
		
	Reload:
		TNT1 A 0 {ammo_amount = max_magazine_size;}//A_TakeInventory("ZombieManAmmo", 20);
		RFTR E 3;
		RFTR E 1 a_spawnprojectile("EmptyClipSpawn", 38, 0, random(-11, 11), 0);
		TNT1 A 0 A_PlaySound("Reload");
		RFR2 A 6;
		RFR2 A 5;
		RFR2 B 5;
		RFR2 C 5;
		TNT1 A 0 A_PlaySound("CLIPIN");
		RFR2 D 6;
		RFTR A 10;
	Goto SeeContinue;
		
	Pain:
		//TNT1 A 0 A_TakeInventory("SKARZombie", 1);
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, 6);
		TNT1 A 0 a_spawnprojectile("brutal_FlyingBlood", 35, 0, random(0, 360), 2, random(0, 160));
		RFTR G 3;
		RFTR G 3 A_Pain();
	Goto SeeContinue;
		TNT1 AAAA 0;
		TNT1 A 0 A_Pain();
		RFT9 EGGG 8;
		TNT1 A 0 A_TakeInventory("IsDown", 1);
	Goto SeeContinue;
		
	Pain.Melee:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInventory("SKARZombie", 1, "StealthKill");
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, 6);
		RFTR G 3;
		RFTR G 3 A_Pain();
	Goto SeeContinue;
		TNT1 AAAA 0;
		TNT1 A 0 A_Pain();
		RFT9 DEGGG 8;
		//TNT1 A 0 A_TakeInventory("SKARZombie", 1);
		TNT1 A 0 A_TakeInventory("IsDown", 1);
	Goto SeeContinue;
		
	StealthKill:
		TNT1 A 1;
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		////TNT1 A 0 A_GiveToTarget("SKARZombie", 1);
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Die("Stealthy");
		TNT1 A 0 A_Fall();
		TNT1 A 1;
	stop;
	Death.Stealthy:
		TNT1 A 0;
	stop;
		
	Pain.Avoid:
		TNT1 A 0;
		TNT1 A 0 A_Jump(72, "AvoidLeft", "AvoidRight");
	Goto AvoidLeft;
		
	AvoidLeft:
		RFTR A 1 A_FaceTarget();
		TNT1 A 0 ThrustThing(angle*256/360+192, 15, 0, 0);
		RFR1 ABCDEFGH 2 A_FaceTarget();
	Goto Missile;
	AvoidRight:
		RFTR A 1 A_FaceTarget();
		TNT1 A 0 ThrustThing(angle*256/360+64, 15, 0, 0);
		RFR0 ABCDEFGH 2 A_FaceTarget();
	Goto Missile;
		
	Pain.Kick:
	Pain.Fatality:
	Pain.ExtremePunches:
	Pain.ExplosiveImpact:
	Pain.Explosive:
		TNT1 A 0;
		RFT9 A 1 A_Pain();
		TNT1 A 0 {self.bNOPAIN = true;}
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain");
		//TNT1 A 0 A_TakeInventory("SKARZombie", 1);
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		RFT9 B 1 A_facetarget();
		RFT9 C 3 ThrustThing(angle*256/360+128, 10, 0, 0);
		RFT9 DEGGG 5;
		TNT1 A 0 {self.bNOPAIN = false;}
	Goto FallingAfterImpact;
		
	FallingAfterImpact:
		RFT9 G 1 A_GiveInventory("FallingHeight", 1);
		TNT1 A 0 A_PlaySound("BODYF",6);
		RFT9 G 1 A_CheckFloor("GetUp");
		tnt1 a 0 A_JumpIf(vel.z == 0, "GetUp");
		Loop;
		
	GetUp:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 5, "FallingDie");
		TNT1 A 0 A_TakeInventory("FallingHeight", 100);
		RFT9 HHHHH 5 A_JumpIf(vel.z < 0, "FallingAfterImpact");
		TNT1 A 0 A_TakeInventory("IsDown", 1);
	Goto SeeContinue;
		
	FallingDie:
		TNT1 A 0;
		TNT1 A 0 A_ChangeCountFlags(false);
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 A_SpawnItem("SplatteredSmall");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 15, "Death.Stomp");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 10, "FallingSuperDeath");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 5, "FallingDeath");
	FallingDeath:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBLocking();
		//TNT1 A 0 A_SpawnItem("Ploft");
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(50, 130));
		RFT9 EF 2;
		TNT1 A 0 A_SpawnItem("Dead_AR_ZombieMan1");
	stop;
		
	FallingSuperDeath:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBLocking();
		//TNT1 AAA 0 A_SpawnItem("Ploft");
	Goto Death.ExplosiveImpact+1;
		
	Death.Nailgun:
		TNT1 A 0 A_Jump(128, "Naildeath2");
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 {self.bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,random(20,30),0,1);
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(30);
		RFT9 A 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		RFT9 A 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		RFT9 B 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		RFT9 C 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		RFT9 D 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		RFT9 D 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("Dead_AR_ZombieMan1");
	stop;
	PinToWall:
		TNT1 A 0 a_spawnprojectile("MuchBlood2", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_PlaySound("Weapons/NailHitBleed");
		PIN2 A 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItemEx("Dead_AR_Zombieman_Pinned", 10);
	stop;
		
	Death.Fatality:
		TNT1 A 0;
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("RapidFireTrooperFatality", 1);
	stop;
		
	Death.Kick:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 {self.bSLIDESONWALLS = true;}
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(10);
		RFT9 BBCDE 5;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("Dead_AR_ZombieMan1");
	stop;
		
	Death:
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Death.Down");
		TNT1 A 0 A_Jump(48, "Death.ARm");
		TNT1 A 0 A_Jump(100, "Death2");
		RFTR H 5;
		TNT1 AAA 0 a_spawnprojectile("MuchBlood2", 35, 0, random(0, 360), 2, random(0, 160));
		RFTR I 5 A_Scream();
		RFTR J 5 A_NoBlocking();
		RFTR K 5;
		TNT1 A 0 A_PlaySound("BODYF",6);
		RFTR L -1;
	stop;
		
	Death.Down:
		POSS I 0 A_Scream();
		TNT1 A 0 A_Stop();
		POSS J 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 2, 0, random(0, 360), 2, random(0, 40));
		RFT2 E 3;
		TNT1 A 0 A_SpawnItem("Dead_AR_ZombieMan1");
	stop;
		
	Death.cutless:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Death.Down");
		TNT1 A 0 A_Jump(16, "Death.Saw");
	Goto Death.Minigun;
		
	Death.Minigun:
	Death.Massacre:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Scream();
		TNT1 O 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("BrutalizedARZombieMan1", 1);
	stop;
		
	Death2:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_Pain();
		RFT2 A 1 A_FaceTarget();
		TNT1 A 0 A_Scream();
		TNT1 AAAA 0 a_spawnprojectile("MuchBlood2", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		RFT2 ABCDE 3;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("Dead_AR_ZombieMan1");
	stop;
		
	Death.Arm:
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("MuchBlood2", 35, 0, random(0, 360), 2, random(0, 160));
		RFT6 A 10 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_PlaySound("BODYF",6);
		//TNT1 A 0 A_SpawnItem("DyingARZombiemanZombiemanNoArm");
	stop;
		
	Death.Shotgun:
		TNT1 A 0 A_JumpIfCloser(80, "Death.Blast");
		TNT1 A 0 A_JumpIfCloser(320, "Death.Shotgunontheface");
	Goto Death;
		
	Death.Shotgunontheface:
		TNT1 A 0;
		TNT1 A 0 {self.bSLIDESONWALLS = false;}
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 A_JumpIfCloser(80, "Death.Blast");
		TNT1 A 0 A_Jump(160, "DeathShotgunFly");
		TNT1 A 0 A_Jump(48, "Death.ARm");
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_Pain();
		RFTR H 1 A_FaceTarget();
		TNT1 A 0 A_Recoil(13);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		TNT1 A 0 A_JumpIf(vel.y == 0, "DeathShotgunFly");
		TNT1 A 0 A_Scream();
		TNT1 A 0 a_spawnprojectile("MuchBlood2", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_NoBlocking();
		RFS4 ABCD 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		RFS4 EFGHIJ 4 A_JumpIf((vel.Y == 0), "DSFStop");
	Goto DSFStop+1;
		
	DeathShotgunFly:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 {self.bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(6);
		RFT9 A 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		RFT2 B 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		RFT2 C 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		RFT2 D 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		RFT9 B 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		RFT9 C 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("Dead_AR_ZombieMan1");
	stop;
		
	TakeASit:
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		RFT9 A 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItemEx("DeadARZombieman_Slumped", 10);
	stop;
		
	DSFStop:
		//TNT1 A 0 A_SpawnItem("Ploft3");
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 a_spawnprojectile("SuperWallRedBlood", 2, 0, random(170, 190), 2, random(0, 0));
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadARZombiemanShotguntotheFace1");
	stop;
		
	Death.Leg:
	Death.Crush:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("MuchBlood2", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathZombieLeg", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("MediumBloodSpot");
		RFT8 AB 6;
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("DyingARZombiemanLegBlewedOff");
	stop;
		
	Death.Saw:
	Death.Cut:
	Death.Tear:
	Death.Blast:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Pain();
		TNT1 A 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 37));
		TNT1 A 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 37));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains3", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains5", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 37));
		TNT1 A 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 37));
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 32, 0, random(170, 190), 2, random(0, 37));
		TNT1 AAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 37));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 37));
		TNT1 AA 0 a_spawnprojectile("brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 37));
		TNT1 AAAA 0 a_spawnprojectile("brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 37));
		TNT1 AAA 0 a_spawnprojectile("brutal_FlyingBloodMuchFaster", 32, 0, random(170, 190), 2, random(0, 37));
		RFT4 A 6 A_FaceTarget();
		TNT1 A 0 A_Recoil(1);
		TNT1 A 0 A_XScream();
		TNT1 AAAA 0 a_spawnprojectile("MuchBlood2", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		RFT4 BBBBC 7 a_spawnprojectile("MuchBlood2", 35, 0, random(0, 360), 2, random(0, 160));
		RFT4 CDE 6;
		TNT1 A 0 A_SpawnItem("Dead_AR_ZombieMan_Fucked");
	stop;

	Death.Head:
		TNT1 A 0; //A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
		TNT1 A 0; //A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		TNT1 A 0; //A_JumpIfInTargetInventory("HasCutingWeapon", 1, "Death.Decaptate");
		TNT1 A 0 A_JumpIfHealthLower(-40, "Death.HeadExplode");
		//TNT1 A 0 //A_JumpIfInTargetInventory("RandomHeadExploder", 1, "HeadExploder");
	Death.HeadMinor:
	Death.MinorHead:
	MinorHead:
		TNT1 A 0;
		TNT1 A 0 A_Playsound("MinorHeadshot", 0);
		TNT1 A 0 A_Jump(32, "Death.MinorHeadLong");
		TNT1 AAAAA 0 a_spawnprojectile("brutal_FlyingBloodTrail8", 50, 0, random(0, 360), 2, random(0, 360));
		TNT1 AA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains3", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains5", 50, 0, random(0, 360), 2, random(0, 160));
		RFT7 A 6 A_Scream();
		RFT7 B 6 A_NoBlocking();
		RFT7 CDE 6;
		TNT1 A 0 A_SpawnItem("MediumBloodSpot");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("Dead_AR_ZombieMan_NoBrain", 1);
	stop;
		
	Death.MinorHeadLong:
		TNT1 AAAAA 0 a_spawnprojectile("brutal_FlyingBloodTrail8", 50, 0, random(0, 360), 2, random(0, 360));
		TNT1 AA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains3", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains5", 50, 0, random(0, 360), 2, random(0, 160));
		RFT7 A 6 A_Scream();
		RFT7 B 6 A_NoBlocking();
		RFT7 CBCBCB 18 A_Pain();
		RFT7 DE 6;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("MediumBloodSpot");
		TNT1 A 0 A_SpawnItem("Dead_AR_ZombieMan_NoBrain", 1);
	stop;
		
	Death.HeadExplode:
	HeadExploder:
		TNT1 A 0 A_Jump(128, "Head2");
	Death.decaptate:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_SpawnItem("NaziHeadExplode", 0, 40);
		TNT1 AAAA 0 a_spawnprojectile("Brains1", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains3", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains5", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 37));
		RFT3 B 0 A_XScream();
		RFT3 C 0 A_NoBlocking();
		TNT1 A 0 A_Jump(32, "Deathchickenhead");
		RFT3 AABC 6 a_spawnprojectile("MuchBlood", 30, 0, random(0, 360), 2, random(0, 160));
		RFT3 DE 6;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("Dead_AR_ZombieMan_NoHeadFront");
		TNT1 A 0 A_SpawnItem("BigBloodSpot");
	stop;

	Head2:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_SpawnItem("NaziHeadExplode", 0, 40);
		TNT1 A 0 a_spawnprojectile("MuchBlood2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Brains1", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains3", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains5", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		RFT3 B 0 A_XScream();
		RFT3 C 0 A_NoBlocking();
		TNT1 A 0 A_Jump(32, "Deathchickenhead");
		RFT3 FGGH 10 a_spawnprojectile("MuchBlood", 30, 0, random(0, 360), 2, random(0, 160));
		RFT3 IJ 6;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("Dead_AR_ZombieMan_NoHeadFront2");
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	stop;

	DeathChickenHead:
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		RFT3 AAA 4
		{
			A_SpawnItem("Blood", 0, 56);
			A_PlaySound("misc/xdeath2c");
		}
		RFT3 AABC 6 a_spawnprojectile("MuchBlood", 30, 0, random(0, 360), 2, random(0, 160));
		RFT3 DE 6;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("Dead_AR_ZombieMan_NoHeadFront");
		TNT1 A 0 A_SpawnItem("BigBloodSpot");
	stop;
		
	Death.ExplosiveImpact:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0;
		TNT1 A 0 A_Jump(96,"Death.LandMine");
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains3", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4Green", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains5", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("BrainBlood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathZombieLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("BloodMistLarge", 40, 0, random(0, 360), 2, random(20, 90));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		RFR3 AB 5;
		RFR3 CDEF 5 A_CheckFloor("Dead.ExplosiveImpact");
		RFR3 FFFFFFFFFF 5 A_CheckFloor("Dead.ExplosiveImpact");
		TNT1 A 0 A_PlaySound("BODYF",6);
		RFR3 G -1;
	stop;
		
	Death.LandMine:
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("BrainBlood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathZombieLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("GibHand", 42, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("BloodMistLarge", 40, 0, random(0, 360), 2, random(20, 90));
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		RFR4 A 1 A_Scream();
		RFR4 A 9;
		RFR4 BCD 9 A_CheckFloor("Dead.Landmine");
		RFR4 DDDDD 9 A_CheckFloor("Dead.Landmine");
		TNT1 A 0 A_PlaySound("BODYF",6);
		RFR4 E -1;
	stop;
		
	Dead.ExplosiveImpact:
		TNT1 AAAA 0 A_SpawnItem("Blood");
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem("Ploft");
		TNT1 A 0 A_PlaySound("BODYF",6);
		RFR3 G -1;
	stop;
		
	Dead.Landmine:
		TNT1 AAAA 0 A_SpawnItem("Blood");
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem("Ploft");
		TNT1 A 0 A_PlaySound("BODYF",6);
		RFR4 E -1;
	stop;
		
	Raise:
		RFTR K 5;
		RFTR JIH 5;
	Goto SeeContinue;
}

}
