class private_base : proto_zombieman_class
{
private name self_type;

default
{
	proto_zombieman_class.max_magazine_size 20;
}

//templates for all general private states
states
{
	//freeze templates
	Death.Ice:
	Death.Freeze:
	Death.Frost:
		TNT1 A 0 
		{
			if(self.bkilled == true) console.printf("ded");
			self.frozen = true;
			health += 150;
			//self.bsolid = false;
			self.bshootable = true;
			self.bNOPAIN = true;
			a_setsize(default.radius, default.height);//A_NoBlocking();
			self_type = getclassname();

			switch(self_type)
			{
				case 'pb_Zombie_Man' :
				case 'pb_Minigun_Guy' :
				case 'pb_pistol_Zombieman':
				default:
					setstatelabel("zomb_ded");
				break;
				
				case 'pb_pistol_Zombieman_2':
					setstatelabel("zomb_p_ded");
				break;
				
				case 'pb_carbine_Zombie_Man':
					setstatelabel("zomb_carb_ded");
				break;

				case 'pb_ZSpecOps_Machinegun':
					setstatelabel("zomb_zpec_ded");
				break;

				case 'pb_Lab_guy': case 'pb_Chainsaw_guy':
					setstatelabel("zomb_scin_ded");
				break;
			}
		}
		//TNT1 A 0 A_SpawnItem("FrozenZombieman");
		//TNT1 A 0 A_SpawnItem("FrozenPistolZombieman");
		//TNT1 A 0 A_SpawnItem("FrozenPistolZombieman2");
		//TNT1 A 0 A_SpawnItem("FrozenHelmetRifleZombieman");
		//TNT1 A 0 A_SpawnItem("FrozenMinigunZombie");
		//TNT1 A 0 A_SpawnItem("FrozenLabguy");
		//TNT1 A 0 A_SpawnItem("FrozenChainsawZombie");
		//TNT1 A 0 A_SpawnItem("FrozenZSpecOp");
	Stop;



























	Death.Melee:
	Death.Kick:
		TNT1 A 0
		{
			self.bNODROPOFF = false;
			self.bSLIDESONWALLS = true;
			self.bsolid = false;
			self.bshootable = true;
			a_setsize(-1, height / 10);//A_NoBlocking();
			ThrustThingZ(0,30,0,1);
			A_Scream();
			A_FaceTarget();
			A_Recoil(10);
		}
		tnt1 a 0 
		{
			self_type = self.getclassname();
			
			switch(self_type)
			{
				case 'pb_Zombie_Man' :
				case 'pb_Minigun_Guy' :
				case 'pb_pistol_Zombieman':
				default:
					setstatelabel("zomb_ded");
				break;
				
				case 'pb_pistol_Zombieman_2':
					setstatelabel("zomb_p_ded");
				break;
				
				case 'pb_carbine_Zombie_Man':
					setstatelabel("zomb_carb_ded");
				break;

				case 'pb_ZSpecOps_Machinegun':
					setstatelabel("zomb_zpec_ded");
				break;

				case 'pb_Lab_guy': case 'pb_Chainsaw_guy':
					setstatelabel("zomb_scin_ded");
				break;
			}
		}
	
	zomb_p_ded://pistol zombie 2
		9OS2 HIZ 4;
		TNT1 A 0 A_PlaySound("BODYF",6);
		POSS KL 4;
	goto st_zomb_ded;//they use same 'actual dead' actor type
	zomb_ded://zombie, pistol zombie and minigun zombie
		TNT1 A 0 A_PlaySound("BODYF",6);
		POS4 UUVWXY 5;
	st_zomb_ded://DeadZombieman1
		
		
		tnt1 a 1 {console.printf("zombie kick/melee state template");}
	stop;
	
	zomb_carb_ded:
		TNT1 A 0 A_PlaySound("BODYF",6);
		RFT9 BBCDE 5;
	stop;//Dead_AR_ZombieMan1
		
	zomb_zpec_ded://zpesops
		ZID9 ABC 6;
		TNT1 A 0 A_PlaySound("BODYF",6);
		ZSP2 KL 6;
	stop;//DeadZSPEC

	zomb_scin_ded://scientist and chainsawed
		TNT1 A 0 A_PlaySound("BODYF",6);
		FS11 GH 8;
	stop;//DeadFormerScientist
		
		
}

}



CLASS DeadZombieman1: pb_blood_and_gore_base Replaces DeadZombieman
{ 
Default{Scale 0.98;}
States
{
	Spawn:
		POSS L -1;
	Stop;
	
	Raise:
	Stop;
	
	Pain.Kick:
	Pain.Fatality:
	Pain.ExtremePunches:
	Pain.ExplosiveImpact:
	Pain.Shotgun:
		TNT1 A 0;
		TNT1 A 0 {self.bNOPAIN = true;}
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		ID11 E 6;
		ID11 F 4;
		TNT1 A 0 {self.bNOPAIN = false;}
	Goto Spawn;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 A_Jump(256, "Death1", "Death2");
	Death1:
		TNT1 A 0 A_NoBlocking();
		TNT1 AA 0 A_SpawnProjectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnProjectile("XDeathArm1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAA 0 A_SpawnProjectile("BloodMist", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 ;//A_SpawnItem("DeadZombieman_NoArm");
	Stop;
	
	Death2:
		TNT1 A 0 A_NoBlocking();
		TNT1 AA 0 A_SpawnProjectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnProjectile("XDeathZombieLeg", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAA 0 A_SpawnProjectile("BloodMist", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 ;//A_SpawnItem("DeadZombieman_NoLeg");
	Stop;

	Crush:
		TNT1 AA 0 A_SpawnItem("MeatDeathSmall");
		TNT1 AAA 0 bright A_SpawnProjectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AAAA 0 bright A_SpawnProjectile("XDeath1", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright A_SpawnProjectile("XDeath2b", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright A_SpawnProjectile("XDeath3b", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("CrushedRemains");
		TNT1 A 1;
		TNT1 A 1 A_XScream();
		POSC A -1;
	Stop;
}

}

































CLASS GuttedUndeadMarineDude: DeadZombieman1 { 
States
{
	Spawn:
		TNT1 A 0;
		U4M3 EE 8;
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TNT1 AAA 0 A_SpawnItem("Blood", 5);
		U4M3 FF 8;
		
		U4M3 EE 8;
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TNT1 AAA 0 A_SpawnItem("Blood", 5);
		U4M3 FF 8;
		
		U4M3 EE 8;
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TNT1 AAA 0 A_SpawnItem("Blood", 5);
		U4M3 FF 8;
		
		U4M3 EE 8;
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TNT1 AAA 0 A_SpawnItem("Blood", 5);
		U4M3 FF 8;
		
		U4M3 G -1;
	stop;
}
}

CLASS DeadHelmetZombieman_Slumped: ZombiemanTorso { 
Default {
	+NOPAIN;
	Health 200;
	DamageFactor "Head", 15.0;
	Height 22;
	Radius 6;
}

States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Recoil(6);
		BR99 A 6;
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		BR99 A 16;
	Loop ;

	LayDown:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("DeadZombieman1");
	Stop;
	XDeath:
	Death.Explosives:
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ZombieXDeath");
		Stop;
		
	Death.Head:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItemEx("ZombiemanHeadExplode", 0, 0, 22);
		TNT1 A 0 A_SpawnItem("DeadZombieman_Slumped_NoHead");
		Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodMuchFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("BloodMistBig", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 AA 0 a_spawnprojectile("XDeathArm1", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 A_SpawnItemEx("ZombiemanHeadExplode", 0, 0, 22);
		TNT1 A 0 A_SpawnItem("DeadZombiemanJustLegsAreLeft");
	Stop;
}}

CLASS DeadHelmetZombiemanShotguntotheFace1: DeadZombieman1 { 
Default {
	damagefactor "shotgun", 0.7;
	}
States{
	Spawn:
		Z6Z7 J -1;
	Stop;
	
	Pain.Kick:
	Pain.Fatality:
	Pain.ExtremePunches:
	Pain.Shotgun:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(3);
		TNT1 A 0 {self.bNOPAIN = true;}
		Z6Z7 FGHI 5;
		TNT1 A 0 {self.bNOPAIN = false;}
		Goto Spawn;
}}


CLASS DeadHelmetZombiemanShotguntotheFace2: DeadZombieman1 { 
	Default {
	damagefactor "shotgun", 0.7;
	}
States{
	Spawn:
		Z6Z7 T -1;
	Stop;
	
	Pain.Kick:
	Pain.Fatality:
	Pain.ExtremePunches:
	Pain.Shotgun:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(3);
		TNT1 A 0 {self.bNOPAIN = true;}
		Z6Z7 PQRS 5;
		TNT1 A 0 {self.bNOPAIN = false;}
		Goto Spawn;		
}}

CLASS DeadHelmetZombiemanLikeInActionMovie: DeadZombieman1 { 
States{Spawn:
	Z6Z8 I -1;
Stop;   }}


CLASS DeadHelmetZombieman_Pinned: ZombiemanTorso { 
	Default {
	+NOPAIN;
	+NOGRAVITY;
	Health 200;
	DamageFactor "Head", 15.0;
	Height 40;
	Radius 6;
	}
States{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Recoil(15);
		PIN3 AA 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_Recoil(10);
		PIN3 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		PIN3 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_Recoil(10);
		PIN3 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		PIN3 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_Recoil(10);
		PIN3 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		PIN3 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_Recoil(10);
		PIN3 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		PIN3 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_Recoil(10);
		PIN3 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		TNT1 A 0 A_Jump(36, "SlideDown");
	JustHangThere:
		TNT1 A 0 A_Recoil(6);
		PIN3 A 6;
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		PIN3 A 16;
		Loop;
		
	SlideDown:
		TNT1 A 0 A_Recoil(6);
		TNT1 A 0 ThrustThingZ(0, 6, 1, 0);
		PIN3 A 6;
		TNT1 A 0 A_JumpIf(vel.z < 2, "SlumpSittingDown");
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		PIN3 A 12;
		Loop;
		
	SlumpSittingDown:
		TNT1 A 0 A_SpawnItemEx("DeadHelmetZombieman_Slumped", 10);
		Stop;
		
	LayDown:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("DeadZombieman1");
		Stop;
		
	XDeath:
	Death.Explosives:
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ZombieXDeath");
		Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodMuchFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("BloodMistBig", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 AA 0 a_spawnprojectile("XDeathArm1", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 A_SpawnItemEx("ZombiemanHeadExplode", 0, 0, 22);
		TNT1 A 0 A_SpawnItem("DeadZombiemanJustLegsAreLeft");
	Stop;
}

}


CLASS DeadHelmetZombieMan_NoArmFront: DeadZombieMan_NoArm
{ 
States
{
	Spawn:
		TNT1 A 0;
		U4M6 D -1;
	Stop;
}

}

	
CLASS DeadHelmetZombieMan_NoLeg : DeadZombieMan_NoArm
{ 
Default 
{Health 200;}

States
{
	Spawn:
		TNT1 A 0;
		U4M5 D -1;
	Stop;
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,15,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(1);
		ID11 KL 8;
		TNT1 A 1 A_SpawnItem("DeadHelmetZombieMan_NoLeg", 5);
	Stop;
}}

CLASS DeadZombieMan_Z4Z7: DeadZombieMan_NoHeadFront
{
States
{	
	Spawn:
		Z4Z7 E -1;
	Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AA 0 a_spawnprojectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAA 0 a_spawnprojectile("BloodMist", 15, 0, random(0, 360), 2, random(0, 180));
		//TNT1 A 0 A_SpawnItem("DeadZombieman_NoHeadNoArm");
	Stop;
}}

CLASS DeadZombieMan_U4M8 : DeadZombieMan_NoHeadFront
{
States
{
	Spawn:
		U4M8 F -1;
	Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AA 0 a_spawnprojectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAA 0 a_spawnprojectile("BloodMist", 15, 0, random(0, 360), 2, random(0, 180));
		//TNT1 A 0 A_SpawnItem("DeadZombieman_NoHeadNoArm");
	Stop;
}}

CLASS DeadZombieman_U4M7: DeadZombieman1
{
States
{
	Spawn:
		U4M7 E -1;
	Stop;
}

}

CLASS DeadZombieman_U4M7J : DeadZombieMan_NoHeadFront
{
States
{
	Spawn:
		U4M7 J -1;
	Stop;
}
}

CLASS DeadZombieman_U4M9: DeadZombieMan_NoHeadFront { 
States
{
	Spawn:
		U4M9 F -1;
	Stop;
}
}

CLASS DeadZombieman_PXS4: DeadZombieMan_NoHeadFront { 
States
    {
	Spawn:
		PXS4 F -1;
	Stop;
}
}


CLASS DeadZombieMarine_NoArmFront: DeadZombieMan_NoArm { 
States{Spawn:
	TNT1 A 0;
	U5M6 D -1;
Stop;   }}
		
CLASS DeadZombieMarine_NoLeg: DeadZombieMan_NoArm { 
default{ Health 200;} States{Spawn:
	TNT1 A 0;
	U5M5 D -1;
	Stop   ;
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,15,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(1);
		ID11 KL 8;
		TNT1 A 1 A_SpawnItem("DeadZombieMarine_NoLeg", 5);
Stop;}}


CLASS Dead_AR_ZombieMan_NoHeadFront: DeadZombieMan_NoArm { 
Default
{Health 200;}

States
{
	Spawn:
		TNT1 A 0;
		RFT3 E -1;
	Stop;
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,15,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(1);
		ID11 EF 8;
		TNT1 A 1 A_SpawnItem("Dead_AR_ZombieMan_NoHeadFront", 5);
	Stop;}}
	 
CLASS Dead_AR_ZombieMan_NoHeadFront2: DeadZombieMan_NoArm { 
	Default
{Health 200;} States{Spawn:
	TNT1 A 0;
	RFT3 J -1;
	Stop;
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,15,0,1);
	TNT1 A 0 A_FaceTarget();
	TNT1 A 0 A_Recoil(1);
	ID11 EF 8;
	TNT1 A 1 A_SpawnItem("Dead_AR_ZombieMan_NoHeadFront", 5);
Stop;}}
	 
CLASS Dead_AR_ZombieMan1: DeadZombieMan_NoArm { 
	Default
{Health 200;} States{Spawn:
	TNT1 A 0;
	RFT2 E -1;
	Stop;
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,15,0,1);
	TNT1 A 0 A_FaceTarget();
	TNT1 A 0 A_Recoil(1);
	ID11 EF 8;
	TNT1 A 1 A_SpawnItem("Dead_AR_ZombieMan1", 5);
Stop;}}
	 
CLASS Dead_AR_ZombieMan_NoLeg: DeadZombieMan_NoArm { 
	Default
{Health 200;} States{Spawn:
	TNT1 A 0;
	RFT8 D -1;
	Stop;
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,15,0,1);
	TNT1 A 0 A_FaceTarget();
	TNT1 A 0 A_Recoil(1);
	ID11 EF 8;
	TNT1 A 1 A_SpawnItem("Dead_AR_ZombieMan_NoLeg", 5);
Stop;}}
	 
CLASS Dead_AR_ZombieMan_Fucked: DeadZombieMan_NoArm { 
	Default
{Health 200;} States{Spawn:
	TNT1 A 0;
	RFT4 E -1;
	Stop;
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,15,0,1);
	TNT1 A 0 A_FaceTarget();
	TNT1 A 0 A_Recoil(1);
	ID11 EF 8;
	TNT1 A 1 A_SpawnItem("Dead_AR_ZombieMan1", 5);
Stop;}}
	 
CLASS Dead_AR_ZombieMan_NoBrain: DeadZombieMan_NoArm { 
	Default 
{Health 200;} States{Spawn:
	TNT1 A 0;
	RFT7 F -1;
	Stop;
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,15,0,1);
	TNT1 A 0 A_FaceTarget();
	TNT1 A 0 A_Recoil(1);
	ID11 EF 8;
	TNT1 A 1 A_SpawnItem("Dead_AR_ZombieMan1", 5);
Stop;}}

//DeadARZombieman_NoArm
CLASS DeadARZombieman_NoArm: DeadZombieMan_NoArm { 
	Default
{Health 200;} States{Spawn:
	TNT1 A 0;
	RFT6 H -1;
	Stop;
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,15,0,1);
	TNT1 A 0 A_FaceTarget();
	TNT1 A 0 A_Recoil(1);
	ID11 EF 8;
	TNT1 A 1 A_SpawnItem("Dead_AR_ZombieMan1", 5);
Stop;}}
//FatalizedRapidFireTrooper
CLASS FatalizedRapidFireTrooper: DeadZombieMan_NoArm { 
	Default 
{Health 200;} States{Spawn:
	TNT1 A 0;
	FRFZ P -1;
	Stop;
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,15,0,1);
	TNT1 A 0 A_FaceTarget();
	TNT1 A 0 A_Recoil(1);
	ID11 EF 8;
	TNT1 A 1 A_SpawnItem("Dead_AR_ZombieMan1", 5);
Stop;}}
	 
CLASS DeadARZombiemanShotguntotheFace1: DeadZombieman1 { 
	Default {
	
	damagefactor "shotgun", 0.7;
	}
States{Spawn:
	RFS4 J -1;
	Stop;
	
	Pain.Kick:
	Pain.Fatality:
	Pain.ExtremePunches:
	Pain.Shotgun:
	TNT1 A 0;
	TNT1 A 0 A_FaceTarget();
	TNT1 A 0 A_Recoil(3);
	TNT1 A 0 {self.bNOPAIN = true;}
	RFS4 FGHI 5;
	TNT1 A 0 {self.bNOPAIN = false;}
	Goto Spawn;
	
}}

CLASS DeadARZombieman_Slumped: ZombiemanTorso { 
Default {
	+NOPAIN;
	Health 200;
	DamageFactor "Head", 15.0;
	Height 22;
	Radius 6;
}

States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Recoil(6);
		BR89 A 6;
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		BR89 A 16;
	Loop ;

	LayDown:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("Dead_AR_ZombieMan1");
	Stop;

	XDeath:
	Death.Explosives:
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ZombieXDeath");
	Stop;
	
	Death.Head:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItemEx("ZombiemanHeadExplode", 0, 0, 22);
		TNT1 A 0 A_SpawnItem("DeadARZombieman_Slumped_NoHead");
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodMuchFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("BloodMistBig", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 AA 0 a_spawnprojectile("XDeathArm1", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 A_SpawnItemEx("ZombiemanHeadExplode", 0, 0, 22);
		TNT1 A 0 A_SpawnItem("DeadZombiemanJustLegsAreLeft");
	Stop;
}}
	
	
CLASS DeadARZombieman_Slumped_NoHead: ZombiemanTorso {
Default {
	+NOPAIN;
	Height 22;
}

States
{
	Spawn:
		TNT1 A 0;
		BR89 B 100;
	Loop ;
	XDeath:
	Death.Explosives:
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ZombieXDeath");
	Stop;
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodMuchFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("BloodMistBig", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 AA 0 a_spawnprojectile("XDeathArm1", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 A_SpawnItem("DeadZombiemanJustLegsAreLeft");
	Stop;
}}

CLASS Dead_AR_Zombieman_Pinned: ZombiemanTorso { 
	Default {
	+NOPAIN;
	+NOGRAVITY;
	Health 200;
	DamageFactor "Head", 15.0;
	Height 40;
	Radius 6;
}

States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Recoil(15);
		PIN2 AA 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_Recoil(10);
		PIN2 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		PIN2 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_Recoil(10);
		PIN2 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		PIN2 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_Recoil(10);
		PIN2 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		PIN2 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_Recoil(10);
		PIN2 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		PIN2 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_Recoil(10);
		PIN2 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		TNT1 A 0 A_Jump(36, "SlideDown");
	JustHangThere:
		TNT1 A 0 A_Recoil(6);
		PIN2 A 6;
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		PIN2 A 16;
	Loop;
	
	SlideDown:
	TNT1 A 0 A_Recoil(6);
	TNT1 A 0 ThrustThingZ(0, 6, 1, 0);
	PIN2 A 6;
	TNT1 A 0 A_JumpIf(vel.z < 2, "SlumpSittingDown");
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	PIN2 A 12;
	Loop;
	
	SlumpSittingDown:
	TNT1 A 0 A_SpawnItemEx("DeadARZombieman_Slumped", 10);
	Stop;
	
	LayDown:
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_SpawnItem("Dead_AR_Zombieman1");
	Stop;
	
	XDeath:
	Death.Explosives:
	Death.ExplosiveImpact:
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_SpawnItem("ZombieXDeath");
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodMuchFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("BloodMistBig", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 AA 0 a_spawnprojectile("XDeathArm1", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 A_SpawnItemEx("ZombiemanHeadExplode", 0, 0, 22);
		TNT1 A 0 A_SpawnItem("DeadZombiemanJustLegsAreLeft");
	Stop;
}}


CLASS ZombiemanTorso : pb_blood_and_gore_base
{ 
Default
{	
	Radius 12;
	Height 12;
	Scale 0.98;
	Mass 800;
	damagefactor "Crush", 50.0;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	//+NORADIUSDMG
	+NOPAIN;
	+CORPSE;
}

States
{
	Spawn:
		BLUD C 0 A_Recoil(3);
		BLUD C 0 ThrustThing(random(0,255),random(1,5));
		BLUD C 0 ThrustThingZ(0,random(0,50),random(0,1),0);
		TNT1 A 0 {self.bInvulnerable = true;}
		GORX A 10;
		TNT1 A 0 {self.bInvulnerable = false;}
	Goto Dead;
		
	Dead:
		GORX A 10;
	Loop;

	Crush:
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile("Brutal_FlyingBloodTrail8", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		POSC A 5;
		POSC A -1;
	Stop;

	Raise:
		TNT1 A 2 A_SpawnProjectile("RealFlameTrailsSmall", 6, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 2 A_SpawnProjectile("RealFlameTrailsSmall", 6, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 0 A_SpawnItem("TeleportFog");
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("pb_Zombie_Man");
	Stop;		
}

}

CLASS DeadZombieMan_BottomLessActionMovie: ZombiemanTorso
{ 
Default {Health 90;}
States
{
	Spawn:
		BLUD C 0 A_Recoil(3);
		BLUD C 0 ThrustThing(random(0,255),random(1,5));
		BLUD C 0 ThrustThingZ(0,random(0,50),random(0,1),0);
		12DG TUVWX 5;
	Goto Dead;
		
	Dead:
		12DG X 10;
	Loop;
	
	Crush:
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile("Brutal_FlyingBloodTrail8", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		POSC A 5;
		POSC A -1;
	Stop;
}

}

CLASS DeadZombieman1F: DeadZombieman1
{ 
States
    {
	Spawn:
		POSS P -1;
	Stop;}
}

CLASS DeadZombieman1FG: DeadZombieman1 { 
	Default {
	
	}
States
    {
	Spawn:
		P05D L -1;
	Stop;}
}

CLASS Zombieman_DeathPNDT: DeadZombieman1
{ 
States
{
	Spawn:
		PNDT Z -1;
	Stop;

	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AA 0 A_SpawnProjectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnProjectile("XDeathArm1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAA 0 A_SpawnProjectile("BloodMist", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 ;//A_SpawnItem("DeadZombieman_NoArm3");
	Stop;
}

}

CLASS DeadZombieMan_NoArm: ZombiemanTorso
{ 
Default {Health 300;}

States
{
	Spawn:
		POS3 E -1;
	Stop;

	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("RipGuts", 0, 10);
		TNT1 A 0 A_SpawnProjectile("XDeathZombiemanHead", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnItem("MeatDeathSmall", 0, 10);
		TNT1 AA 0 A_SpawnProjectile("XDeathZombieLeg", 6, 0, random(0, 360), 2, random(0, 90));
		TNT1 A 0 A_SpawnItem("DeadZombiemanPXSXO");
	Stop;}}
		
CLASS DeadZombieMan_NoArm3: ZombiemanTorso
{ 
Default {Health 300;}

States
{
	Spawn:
		PND1 Z -1;
	Stop;		

	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("RipGuts", 0, 10);
		TNT1 A 0 A_SpawnProjectile("XDeathZombiemanHead", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnItem("MeatDeathSmall", 0, 10);
		TNT1 A 0 A_SpawnItem("DeadZombieMan_Topless");
	Stop;}}

CLASS DeadZombieMan_NoLeg: DeadZombieMan_NoArm { 
Default {Health 300;}

States{
	Spawn:
		POS7 D -1;
	Stop;

	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("DeadZombieMan_NoLegBoth", 0, 10);
		TNT1 A 0 A_SpawnItem("MuchBlood", 0, 10);
		TNT1 A 0 A_SpawnProjectile("XDeathZombieLeg", 15, 0, random(0, 360), 2, random(0, 180));
	Stop;}}
		 
		 
CLASS DeadZombieMan_NoLegBoth: DeadZombieMan_NoArm { 
	Default{Health 300;} States{
	Spawn:
		POS8 D -1;
	Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("RipZombieman", 0, 10);
		TNT1 A 0 A_SpawnItem("MeatDeathSmall", 0, 10);
	Stop;
}

}
		 



CLASS DeadZombieMan_NoHead: DeadZombieMan1f { 
	Default {Health 300;}

States
{
	Spawn:
		POSH F -1;
	Stop;
	
	Pain.Kick:
	Pain.Fatality:
	Pain.ExtremePunches:
	Pain.ExplosiveImpact:
	Pain.Shotgun:
		TNT1 A 0;
		TNT1 A 0 {self.bNOPAIN = true;}
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		ID11 E 6;
		ID11 F 4;
		TNT1 A 0 {self.bNOPAIN = false;}
Goto Spawn;}}

CLASS DeadZombieMan_NoHeadFront: DeadZombieMan_NoArm { 
	Default
{Health 300;} States{
	
	Spawn:
		ZMAD E -1;
	Stop;		
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AA 0 A_SpawnProjectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnProjectile("XDeathArm1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAA 0 A_SpawnProjectile("BloodMist", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 ;//A_SpawnItem("DeadZombieman_NoHeadNoArm");
	Stop;

	Death.Fatality:
	Death.Melee:
	Death.Kick:
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,15,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(1);
		ID11 EF 8;
		TNT1 A 1 ;//A_SpawnItem("DeadZombieman1", 5);
Stop;}}

CLASS DeadZombieMan_Half: ZombieManTorso { 
	Default
{Mass 300; Health 300;}
States
{
	Spawn:
		POSX E -1;
	Stop;
}

}
		



CLASS VeryFuckedUpBrutalizedZombiemanLeg: pb_blood_and_gore_base { 
Default {
	Health 200;
	DamageFactor "ExplosiveImpact", 10.0;
	}
States{ Spawn:
	ID13 G -1;
	Stop;
	Death.ExplosiveImpact:
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		ID13 ABCDEF 5;
		TNT1 A 0 A_SpawnItem("VeryFuckedUpBrutalizedZombiemanLeg");
	Stop;		
}}
		  
CLASS VeryFuckedUpBrutalizedZombiemanLeg2: VeryFuckedUpBrutalizedZombiemanLeg { 
	Default{Health 300;} States{Pain:
	TNT1 AAAA 0 A_SpawnProjectile("Brutal_LiquidBlood2", 15, 0, random(0, 360), 2, random(0, 180));
	Goto Spawn;
	Spawn:
		ID15 E -1;
Stop;}}
		
CLASS DeadZombieMan_NoArm4: VeryFuckedUpBrutalizedZombiemanLeg { 
	Default{Health 300;}
States
{
	Pain:
		TNT1 AAAA 0 A_SpawnProjectile("Brutal_LiquidBlood2", 15, 0, random(0, 360), 2, random(0, 180));
	Goto Spawn;

	Spawn:
		Z81D D -1;
Stop;}}

	   
CLASS StompedZombieman: DeadZombieman_NoHead
{ 
Default {Health 300;}

States
{
	Pain:
		TNT1 AAAA 0 A_SpawnProjectile("Brutal_LiquidBlood2", 15, 0, random(0, 360), 2, random(0, 180));
	Goto Spawn;
	
	Spawn:
		01CB F -1;
	Stop;
}

}
		  



CLASS DeadZombieMan_NoArmFront: DeadZombieMan_NoArm { 

States{	
	Spawn:
		ZZD3 D -1;
		Stop ;
		
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ZombiemanHeadExplode", 0, 10);
		TNT1 A 0 ;//A_SpawnItem("DeadZombieman_NoHeadNoArm");
	Stop;		
}}


CLASS DeadZombieMan_FacingFront: DeadZombieMan_NoArm { 

States{	
	Spawn:
		PSSR E -1;
		Stop ;
		
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ZombiemanHeadExplode", 0, 10);
		TNT1 A 0 ;//A_SpawnItem("DeadZombieman_NoHeadNoArm");
	Stop;		
}}	

		
		
CLASS DeadZombieMan_StomachExploded: DeadZombieman_NoHeadFront { 

States{	
	Spawn:
		ZXZ1 E -1;
		Stop ;
		
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ZombiemanHeadExplode", 0, 10);
		TNT1 A 0 ;//A_SpawnItem("DeadZombieman_NoHeadFront");
	Stop;		
}}	
		

CLASS DeadZombieMan_Blasted: DeadZombieMan_NoHeadFront { 

States{	
	Spawn:
		ZXZ2 E -1;
	Stop;		
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AA 0 A_SpawnProjectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnProjectile("XDeathArm1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAA 0 A_SpawnProjectile("BloodMist", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 ;//A_SpawnItem("DeadZombieman_NoHeadNoArm");
	Stop;		
}}
		
CLASS DeadZombieMan_BlastedMirrored: DeadZombieMan_Blasted { 

States{	
	Spawn:
		ZXZ2 J -1;
		Stop ;
}}	
		
CLASS DeadZombieManFacingFront: DeadZombieMan_NoArmFront { 

States{Spawn:
	FPZ2 J -1;
	Stop  ;
	
	Death:
		TNT1 A 0;
		TNT1 A 0 A_Jump(256, "Death1", "Death2");
	Death1:
		TNT1 A 0 A_NoBlocking();
		TNT1 AA 0 A_SpawnProjectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnProjectile("XDeathArm1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAA 0 A_SpawnProjectile("BloodMist", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 ;//A_SpawnItem("DeadZombieman_NoArmFront");
	Stop;	Death2:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ZombiemanHeadExplode", 0, 10);
		TNT1 A 0 ;//A_SpawnItem("DeadZombieman_NoHeadFront");
	Stop;}}
		
CLASS DeadZombieManFacingFrontMinorHead: DeadZombieManFacingFront { 

States{Spawn:
	12DG N -1;
	Stop ;
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ZombiemanHeadExplode", 0, 10);
		TNT1 A 0 ;//A_SpawnItem("DeadZombieman_NoHeadFront");
	Stop;}}		
		
CLASS DeadZombieManFatality3: ZombiemanTorso { 

States{Spawn:
	FPZ3 S -1;
Stop;   }}	
		
CLASS DeadZombieManFatality5: DeadZombieman1 { 

States
    {
	Spawn:
		TNT1 A 0;
		FPZ5 K -1;
	Stop;}
}

CLASS Fatality6ZMan: pb_dismembered_monster_base
{ 
Default
{
	Health 15;
	Radius 16;
	Height 44;
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("BURNZOM", 3, 3);
		FRAA EF 6 A_SpawnItem("Blood", 0, 56);
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		FRAA EF 6 A_SpawnItem("Blood", 0, 56);
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		FRAA EF 6 A_SpawnItem("Blood", 0, 56);
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		FRAA EF 6 A_SpawnItem("Blood", 0, 56);
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		FRAA EF 6 A_SpawnItem("Blood", 0, 56);
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		FRAA EF 6 A_SpawnItem("Blood", 0, 56);
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		FRAA EF 6 A_SpawnItem("Blood", 0, 56);
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		FRAA EF 6 A_SpawnItem("Blood", 0, 56);
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		FRAA GHIJ 4 A_SpawnItem("Blood", 0, 50);
		TNT1 A 0 A_NoBlocking();
		FRAA J -1;
	Stop;
}
}
		
CLASS DeadZombiemanShotguntotheFace1: DeadZombieman1
{ 
Default {damagefactor "shotgun", 0.7;}

States
{
	Spawn:
		POS4 J -1;
	Stop;
	
	Pain.Kick:
	Pain.Fatality:
	Pain.ExtremePunches:
	Pain.Shotgun:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(3);
		TNT1 A 0 {self.bNOPAIN = true;}
		POS4 FGHI 5;
		TNT1 A 0 {self.bNOPAIN = false;}
	Goto Spawn;
		
}}


CLASS DeadZombiemanShotguntotheFace2: DeadZombieman1
{ 
Default {damagefactor "shotgun", 0.7;}

States
{
	Spawn:
		POS4 T -1;
	Stop;
	
	Pain.Kick:
	Pain.Fatality:
	Pain.ExtremePunches:
	Pain.Shotgun:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(3);
		TNT1 A 0 {self.bNOPAIN = true;}
		POS4 PQRS 5;
		TNT1 A 0 {self.bNOPAIN = false;}
	Goto Spawn;
}

}


CLASS DeadZombieManMinorHead: DeadZombiemanShotguntotheFace1 { 
	Default {Health 300;}
States
{
	Spawn:
		POSH Z -1;
	Stop;
	
	Death:
		TNT1 AAAA 0 A_SpawnProjectile("Brutal_LiquidBlood", 10, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_SpawnProjectile("XDeathArm1", 11, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 A_SpawnProjectile("XDeath1", 10, 0, random(0, 360), 2, random(0, 160));
		Z81D D 1 ;//A_SpawnItem("DeadZombieman_NoArm4");
	Stop;}}

		
CLASS DeadZombiemanLikeInActionMovie: DeadZombieman1 { 
States{Spawn:
	12DG I -1;
Stop;   }}
		
CLASS DeadZombiemanLikeInActionMovie_FuckedUp: ZombiemanTorso { 
	Default {+NOPAIN;}

States
{
	Spawn:
		22DG F -1;
	Stop;  
}

}


CLASS DeadZombiemanJustLegsAreLeft: ZombiemanTorso { 
	Default {
	
	+NOPAIN;
	}
States{Spawn:
	POSX E -1;
Stop ;  }}
		
CLASS DeadZombieMan_Topless: ZombiemanTorso { 
	Default {
	
	+NOPAIN;
	}
States{Spawn:
	PND2 Z -1;
Stop;   }}
		
CLASS DeadZombieMan_ToplessActionMovie: ZombiemanTorso
{ 
Default {+NOPAIN;}
	
States{Spawn:
	12DG S -1;
Stop;
}}
		
CLASS DeadZombiemanJustLegsAreLeft2: ZombiemanTorso
{ 
Default {+NOPAIN;}

States
{
	Spawn:
		ZZD1 H -1;
	Stop;
}

}	
		
		
CLASS DeadZombieman_TearedInHalf: ZombiemanTorso 
{ 
Default
{+NOPAIN;}

States
{
	Spawn:
		PP2X E -1;
	Stop;
}
}
		
		
		
CLASS DeadZombieman_Slumped: ZombiemanTorso
{ 
Default
{	
	+NOPAIN;
	Health 200;
	DamageFactor "Head", 15.0;
	Height 22;
	Radius 6;
}

States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Recoil(6);
		BR92 A 6;
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		TNT1 A 0 ;//A_SpawnItemEx("HeadshotTarget20", 0, 0, 22);
		BR92 A 16;
	Loop ;

	LayDown:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("DeadZombieman1");
	Stop;	XDeath:
	Death.Explosives:
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ZombieXDeath");
	Stop;		
	Death.Head:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItemEx("ZombiemanHeadExplode", 0, 0, 22);
		TNT1 A 0 A_SpawnItem("DeadZombieman_Slumped_NoHead");
	Stop;		
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 A_SpawnProjectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 A_SpawnProjectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 A_SpawnProjectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 A_SpawnProjectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 A_SpawnProjectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 A_SpawnProjectile("Brutal_FlyingBloodMuchFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 A_SpawnProjectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 A_SpawnProjectile("BloodMistBig", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 AA 0 A_SpawnProjectile("XDeathArm1", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 A_SpawnItemEx("ZombiemanHeadExplode", 0, 0, 22);
		TNT1 A 0 A_SpawnItem("DeadZombiemanJustLegsAreLeft");
	Stop;}}
		
CLASS DeadZombieman_Pinned: ZombiemanTorso
{ 
Default
{	
	+NOPAIN;
	+NOGRAVITY;
	Health 200;
	DamageFactor "Head", 15.0;
	Height 40;
	Radius 6;
}

States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Recoil(15);
		PIN1 AA 4 A_SpawnProjectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_Recoil(10);
		PIN1 A 4 A_SpawnProjectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		PIN1 A 4 A_SpawnProjectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_Recoil(10);
		PIN1 A 4 A_SpawnProjectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		PIN1 A 4 A_SpawnProjectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_Recoil(10);
		PIN1 A 4 A_SpawnProjectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		PIN1 A 4 A_SpawnProjectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_Recoil(10);
		PIN1 A 4 A_SpawnProjectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		PIN1 A 4 A_SpawnProjectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_Recoil(10);
		PIN1 A 4 A_SpawnProjectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		TNT1 A 0 A_Jump(36, "SlideDown");
	JustHangThere:
		TNT1 A 0 A_Recoil(6);
		PIN1 A 6;
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		PIN1 A 16;
	Loop;
		
	SlideDown:
		TNT1 A 0 A_Recoil(6);
		TNT1 A 0 ThrustThingZ(0, 6, 1, 0);
		PIN1 A 6;
		TNT1 A 0 A_JumpIf(vel.z < 2, "SlumpSittingDown");
		TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
		TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
		PIN1 A 12;
	Loop;
		
	SlumpSittingDown:
		TNT1 A 0 A_SpawnItemEx("DeadZombieman_Slumped", 10);
	Stop;
	
	LayDown:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("DeadZombieman1");
	Stop;
	
	XDeath:
	Death.Explosives:
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ZombieXDeath");
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 A_SpawnProjectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 A_SpawnProjectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 A_SpawnProjectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 A_SpawnProjectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 A_SpawnProjectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 A_SpawnProjectile("Brutal_FlyingBloodMuchFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 A_SpawnProjectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 A_SpawnProjectile("BloodMistBig", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 AA 0 A_SpawnProjectile("XDeathArm1", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 A_SpawnItemEx("ZombiemanHeadExplode", 0, 0, 22);
		TNT1 A 0 A_SpawnItem("DeadZombiemanJustLegsAreLeft");
	Stop;
}}


CLASS DeadZombieman_Slumped_NoHead: ZombiemanTorso
{ 
Default
{	
	+NOPAIN;
	Height 22;
}

States
{
	Spawn:
		TNT1 A 0;
		BR92 B 100;
	Loop ;
	
	XDeath:
	Death.Explosives:
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ZombieXDeath");
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 A_SpawnProjectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 A_SpawnProjectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 A_SpawnProjectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 A_SpawnProjectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 A_SpawnProjectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 A_SpawnProjectile("Brutal_FlyingBloodMuchFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 A_SpawnProjectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 A_SpawnProjectile("BloodMistBig", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 AA 0 A_SpawnProjectile("XDeathArm1", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 A_SpawnItem("DeadZombiemanJustLegsAreLeft");
	Stop;}}
		

CLASS DeadZombieman1MeleeDeath : ACTOR
{ 
Default
{	
	Radius 20;
	Height 16;
	+SHOOTABLE;
	-SOLID;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	-TELESTOMP;
	-NOTELEFRAG;
	DamageFactor "Crusher", 99.0;
	Mass 200;
	Health 35;
	DamageFactor "Blood", 0.0;
	DamageFactor "Trample", 0.0;
	DamageFactor "Melee", 10.0;
	DamageFactor "Fatality", 10.0;
	DamageFactor "Kick", 10.0;
	DamageFactor "ExplosiveImpact", 10.0;
	DamageFactor "Crush", 99.0;
	DamageFactor "BFGSplash", 100.0;
	DamageFactor "BlueBloodSplasher", 0.0;
	DamageFactor "BlueSuperBloodSplasher", 0.0;
}

States
{
	Spawn:
		FID1 E -1;
	Stop;

	Raise:
		FID1 E 1;
		FID1 DCB 1;
		TNT1 A 0 A_SpawnItem("pb_Zombie_Man", 3);
	Stop;
	
	Death:
		TNT1 A 0 A_Jump(128, "Death2");
		TNT1 A 0 A_SpawnProjectile("XDeathArm1", 5, 0, random(0, 360), 2, random(0, 160));
		POS3 A 0 A_SpawnProjectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 1 ;//A_SpawnItem("DeadZombieman_NoArm", 5);
	Stop;
	
	Death2:
		TNT1 A 0 A_SpawnProjectile("XDeathZombieLeg", 5, 0, random(0, 360), 2, random(0, 160));
		POS3 A 0 A_SpawnProjectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 1 ;//A_SpawnItem("DeadZombieman_NoLeg", 5);
	Stop;
	
	Death.Saw:
		TNT1 A 1 ;//A_SpawnItem("DeadZombieman_Half", 5);
		TNT1 A 0 A_SpawnProjectile("RipZombieMan", 0, 0, random(0, 360), 2, random(0, 160));
	Stop;
	
	XDeath:
	Crush:
		TNT1 A 0 {self.bCORPSE = false;}
		TNT1 A 0 {self.bDONTCORPSE = true;}
		TNT1 A 0 A_SpawnItem("GibsZ");
		TNT1 A 0 A_SpawnProjectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnProjectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnProjectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnProjectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
	Stop;
	
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,15,0,1);
		TNT1 A 0 A_FaceTarget();
		ID31 EF 8;
		TNT1 A 1 ;//A_SpawnItem("DeadZombieman1MeleeDeath", 5);
	Stop;}
}

CLASS DeadZombiemanPXSXO: ZombiemanTorso
{ 
States
{
	Spawn:
		PXSX O -1;
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 1 A_SpawnItem("GibsZ");
		TNT1 A 0 A_SpawnItem("MeatDeathSmall");
		TNT1 A 0 A_SpawnProjectile("XDeathArm1", 15, 0, random(0, 360), 2, random(0, 180));
	Stop;		
}}


CLASS DeadZombiemanPXS2O: ZombiemanTorso
{ 
States
{
	Spawn:
		PXS2 O -1;
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 1 A_SpawnItem("GibsZ");
		TNT1 A 0 A_SpawnItem("MeatDeathSmall");
		TNT1 A 0 A_SpawnProjectile("XDeathArm1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnItem("ZombiemanHeadExplode");
	Stop;
}}


CLASS DeadZombiemanZBLDF: DeadZombiemanPXS2O
{ 
States
{
	Spawn:
		PXS2 O -1;
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 1 A_SpawnItem("GibsZ");
		TNT1 A 0 A_SpawnItem("MeatDeathSmall");
		TNT1 A 0 A_SpawnProjectile("XDeathArm1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnItem("ZombiemanHeadExplode");
	Stop;}}

CLASS DeadZombieMan_PXS3: DeadZombieMan_NoHeadFront { 
States
{	
	Spawn:
		PXS3 F -1;
	Stop;		
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AA 0 A_SpawnProjectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnProjectile("XDeathArm1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAA 0 A_SpawnProjectile("BloodMist", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 ;//A_SpawnItem("DeadZombieman_NoHeadNoArm");
	Stop;		
}}
		
CLASS DeadZombieMan_HeavyHead: DeadZombieMan_NoHeadFront
{ 
States
{	
	Spawn:
		POSL L -1;
	Stop;		
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AA 0 A_SpawnProjectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnProjectile("XDeathArm1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAA 0 A_SpawnProjectile("BloodMist", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 ;//A_SpawnItem("DeadZombieman_NoHeadNoArm");
	Stop;		
}}

		
CLASS ExecutedPistolZombie: DeadZombieMan_NoHeadFront
{ 
States
{	
	Spawn:
		FSP7 K -1;
	Stop;		

	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AA 0 A_SpawnProjectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnProjectile("XDeathArm1", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAA 0 A_SpawnProjectile("BloodMist", 15, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 ;//A_SpawnItem("DeadZombieman_NoHeadNoArm");
	Stop;		
}

}
	
CLASS PinnedZombiemanTorso : ACTOR
{ 
Default
{	
	Radius 8;
	Height 8;
	Speed 25;
	Scale 1.2;
	Mass 15;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+RIPPER;
	+BLOODLESSIMPACT;
	-DONTSPLASH;
	+THRUGHOST;
	+THRUACTORS;
	+FLOORCLIP;
	+NOGRAVITY;
	damagetype "Blood";
	SeeSound "misc/xdeath4";
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSuper";
	Mass 1;
}

States
{
	Spawn:
		P1NC A 4 A_SpawnProjectile("XDeath1Trail", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		TNT1 A 0 A_CheckFloor("HitTheFloor");
	Loop;
		
	Death:
	PinToWall:
		P1NC A 4;
		TNT1 A 0 A_CheckFloor("HitTheFloor");
		TNT1 A 0 A_JumpIf(vel.x < 0, "HitTheFloor");
		TNT1 A 0 A_JumpIf(vel.y < 0, "HitTheFloor");
		TNT1 A 0 A_JumpIf(vel.x > 0, "HitTheFloor");
		TNT1 A 0 A_JumpIf(vel.y > 0, "HitTheFloor");
	Loop;
		
	HitTheFloor:
		TNT1 A 0 A_SetFloorClip();
		TNT1 A 0 A_SpawnItem("Gib_HalfZombieManNoArmNoHead",0,0,0,1);
	Stop;
}

}


	 
CLASS DeadZSPEC: pb_blood_and_gore_base { 
	Default
{Health 200;} States{Spawn:
	ZSP2 L -1;
	Stop;
	
	Death:
	TNT1 A 0 A_SpawnItem("DeadZSPEC_Z2Z8I");
	TNT1 AAA 0 a_spawnprojectile("XDeath1", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAA 0 a_spawnprojectile("BloodMistBig", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
	TNT1 AAA 0 a_spawnprojectile("BloodMistBig", 22, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath2", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath3", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath4", 50, 0, random(0, 360), 2, random(0, 160));
	Stop;
	
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,15,0,1);
	TNT1 A 0 A_FaceTarget();
	TNT1 A 0 A_Recoil(2);
	ZID9 BC 8;
	TNT1 A 1 A_SpawnItem("DeadZSPEC", 5);
	Stop;
	Raise:
	ZSP2 LKJIH 5;
	TNT1 A 0 A_SpawnItem("pb_ZSpecOps_Machinegun", 3);
	Stop;
	
	
}}

CLASS DeadZSPEC_Z2Z8I: DeadZSPEC { 
	Default
{Health 200;} States{Spawn:
	Z2Z8 I -1;
	StopDeath:
	Death.CutLess:
	Death.Cut:
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AAA 0 a_spawnprojectile("XDeath1", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath2", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath3", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath4", 50, 0, random(0, 360), 2, random(0, 160));
Stop;}}
	
CLASS DeadZSPEC_Z2Z8H: DeadZSPEC { 
	Default
{Health 200;} States{Spawn:
	Z2Z8 H -1;
	StopDeath:
	Death.CutLess:
	Death.Cut:
	Death.Fatality:
	Death.Melee:
	Death.Kick:
	TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AAA 0 a_spawnprojectile("XDeath1", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath2", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath3", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath4", 50, 0, random(0, 360), 2, random(0, 160));
Stop;}}

CLASS DeadZSPEC_NoLeg: DeadZSPEC { 
	Default
{Health 200;} States{Spawn:
	QPO3 F -1;
Stop;}}
	 
CLASS DeadZSPEC_NoArm: DeadZSPEC { 
	Default
{Health 200;} States{Spawn:
	ZPO5 E -1;
Stop;}}


//Z2Z8 I -1

CLASS DeadZSPEC_ZSP5P: DeadZSPEC { 
	Default
{Health 200;} States{Spawn:
	ZSP5 P -1;
	Stop;
}}
	
//FatalizedZSpec
CLASS FatalizedZSpec: DeadZSPEC { 
	Default
{Health 200;} States{Spawn:
	TNT1 A 0 A_PlaySound("misc/xdeath4");
	TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode", 1, 32);
	TNT1 AAAA 0 a_spawnprojectile("BloodMistBig", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
	TNT1 AAAAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAAAAAAAAA 0 a_spawnprojectile("BrainBlood", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 A_NoBlocking;
	QPDH BBC 10 a_spawnprojectile("MuchBlood", 30, 0, random(0, 360), 2, random(0, 160));
	QPDH CDE 8;
	TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	//TNT1 A 0 A_SpawnItem("DeadHFQSZ_NoHead", 1);
	Stop;
}}
	 
CLASS DyingZSPEC : ACTOR
{ 
Default
{
	Radius 16;
	Height 28;
	Health 50;
	PainSound "grunt/pain";
	PainChance 255;
	damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0; damagefactor "GreenBlood", 0.0;
	damagefactor "Avoid", 0.0;
	damagefactor "Leg", 0.0;
	damagefactor "Kick", 6.0;
	Mass 50;
	-SOLID;
	+SHOOTABLE;
	+FLOORCLIP;
	}
	States
	{
	Death.Fatality:
	Death.SuperPunch:
	TNT1 A 0 A_NoBlocking();
	//TNT1 A 0 A_GiveToTarget("HasSguyShield", 1);
	//TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);//NOPE.AVI; FIX THIS
	Stop;
	
	Death.fire:
	Death.Flames:
		////TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("BurningZombie");
	Stop;
	
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BURNZOM");
		ZPO5 A 10;
	Suffer:
		ZPO5 BBBBBBBBBB 1 a_spawnprojectile("Brutal_LiquidBlood", 18, -5, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		ZPO5 CCCCCCCCCC 1 a_spawnprojectile("Brutal_LiquidBlood", 18, -5, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		ZPO5 BBBBBBBBBB 1 a_spawnprojectile("Brutal_LiquidBlood", 18, -5, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		ZPO5 CCCCCCCCCC 1 a_spawnprojectile("Brutal_LiquidBlood", 18, -5, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		ZPO5 BBBBBBBBBB 1 a_spawnprojectile("Brutal_LiquidBlood", 18, -5, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		ZPO5 CCCCCCCCCC 1 a_spawnprojectile("Brutal_LiquidBlood", 18, -5, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		ZPO5 BBBBBBBBBB 1 a_spawnprojectile("Brutal_LiquidBlood", 18, -5, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		ZPO5 CCCCCCCCCC 1 a_spawnprojectile("Brutal_LiquidBlood", 18, -5, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		ZPO5 BBBBBBBBBB 1 a_spawnprojectile("Brutal_LiquidBlood", 18, -5, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		ZPO5 CCCCCCCCCC 1 a_spawnprojectile("Brutal_LiquidBlood", 18, -5, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		ZPO5 BBBBBBBBBB 1 a_spawnprojectile("Brutal_LiquidBlood", 18, -5, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		ZPO5 CCCCCCCCCC 1 a_spawnprojectile("Brutal_LiquidBlood", 18, -5, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);

	Death.Cut:
	Death.Cutless:
	Death:
		ZPO5 D 8;
		TNT1 A 0 A_PlaySound("grunt/death");
		TNT1 A 0 A_SpawnItem("DeadZSPEC_NoArm");
	Stop;
	
	Death.Decaptate:
	Death.Head:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAA 0 a_spawnprojectile("Brains1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains5", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_XScream();
		//TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("BrainBlood", 37, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_NoBlocking();
		QZD4 A 10;
		////TNT1 A 0 A_SpawnItem("DeadHFQSZ_NoHeadNoArm", 1);
	Stop;
	
	Death.Shotgun:
		TNT1 A 0 a_spawnprojectile("MuchBlood2", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_Scream();
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_NoBlocking();
		QXXZ KL 15;
		////TNT1 A 0 A_SpawnItem("DeadHFQSZ_NoArm");
	Stop;

	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		XBRN AA 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
		TNT1 AAAA 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 A 0 a_spawnprojectile("XDeathBurnedArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 A_SpawnItem("CrueltyBonus5Armor");
		XBRN BB 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
		TNT1 A 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
		XBRN CC 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
		TNT1 AAAAA 0 a_spawnprojectile("PlasmaParticleX", 48, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAA 0 a_spawnprojectile("PlasmaParticleX", 42, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0;
	Stop;
	
	Xdeath:
	Death.SuperPunch:
	Death.Blast:
	Death.SSG:
		QZD1 F 1 A_Pain();
		QZD1 F 1 A_FaceTarget();
		//TNT1 A 0 a_spawnprojectile("MeatDeath", 0, 0, random(0, 360), 2, random(0, 160))
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodMuchFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("XDeathHFQSZArm1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		QZD1 FFGGGH 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		QZD1 H -1;
	Stop;
	
	
}
}

CLASS DyingZSPECLegBlewedOff: DyingZSPEC { 
	Default {
 
	Radius 16;
	Height 28;
	Health 50;
	PainSound "grunt/pain";
	PainChance 255;
Damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0; damagefactor "GreenBlood", 0.0;
	damagefactor "Avoid", 0.0;
	damagefactor "Kick", 6.0;
	Mass 50;
	-SOLID;
	+SHOOTABLE;
	}
	States
	{
	Death.Fatality:
	Death.SuperPunch:
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_GiveToTarget("HasSguyShield", 1);
		//TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);// FIX
		Stop;
		
		
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BURNZOM");
		ZPO3 C 10;
		Goto Suffer;
		
	Suffer:
		ZPO3 D 10;
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		
		ZPO3 E 10;
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		ZPO3 D 10;
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		
		ZPO3 E 10;
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		ZPO3 D 10;
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		
		ZPO3 E 10;
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		ZPO3 D 10;
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		
		ZPO3 E 10;
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		ZPO3 D 10;
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		
		ZPO3 E 10;
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		ZPO3 D 10;
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
		
		ZPO3 E 10;
		TNT1 A 0 A_SpawnItem("BloodDying", 0, 20);
	Goto Death;
		
	GotoDeath:
		TNT1 A 0;
		Goto Death;
		
	Death.Cut:
	Death.Cutless:
	Death:
		QPO3 GH 5;
		TNT1 A 0 A_PlaySound("grunt/death");
		////TNT1 A 0 A_SpawnItem("DeadHFQSZ_NoLeg");
	Stop;
		
	Death.Head:
	Death.Decaptate:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAA 0 a_spawnprojectile("Brains1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains5", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_XScream();
		//TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("BrainBlood", 37, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_NoBlocking();
		QPO3 IJ 6;
		//TNT1 A 0 A_SpawnItem("DeadHFQSZ_NoLeg", 1);
		Stop;
		
	Death.Shotgun:
		TNT1 A 0 a_spawnprojectile("MuchBlood2", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_Scream();
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_NoBlocking();
		QXXZ KL 15;
		//TNT1 A 0 A_SpawnItem("DeadHFQSZ_NoArm");
		Stop;
		
		
	Death.Plasma: Death.Plasma2:
	TNT1 A 0;
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	XBRN AA 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
	TNT1 AAAA 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
	
	TNT1 A 0 a_spawnprojectile("XDeathBurnedArm", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedLeg", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	//TNT1 A 0 A_SpawnItem("CrueltyBonus5Armor");
	XBRN BB 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
	TNT1 A 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
	XBRN CC 2 BRIGHT A_SpawnItem("Blue_Flare",0,43);
	TNT1 AAAAA 0 a_spawnprojectile("PlasmaParticleX", 48, 0, random(0, 360), 2, random(0, 360));
	TNT1 AAA 0 a_spawnprojectile("PlasmaParticleX", 42, 0, random(0, 360), 2, random(0, 360));
	TNT1 A 0;
	Stop;
	
	Xdeath:
	Death.SuperPunch:
	Death.Blast:
	Death.SSG:
	//TNT1 A 0 a_spawnprojectile("MeatDeath", 0, 0, random(0, 360), 2, random(0, 160))
	TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodMuchFaster", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeathHFQSZArm1", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	ZZD1 EFGH 6;
	TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	ZZD1 H -1;
	Stop;
	
}
}

CLASS DeadZSpec_NoBrain: DeadZSPEC { 
	Default
{Health 200;} States{Spawn:
	ZSP5 F -1;
Stop;}}


CLASS DeadZSpecZSP4J: DeadZSPEC { 
States{Spawn:
	ZSP4 J -1;
	Stop;
}}

CLASS DeadZSpecZ2Z7E: DeadZSPEC { 
States{Spawn:
	Z2Z7 E -1;
	Stop;
}}

CLASS DeadZSpecZSP5K: DeadZSPEC { 
States{Spawn:
	ZSP5 K -1;
	Stop;
}}

CLASS DeadZSpecZ2Z9E: DeadZSPEC { 
States{Spawn:
	Z2Z9 E -1;
	Stop;
}}

CLASS DeadZSPEC_Pinned: ZombiemanTorso { 
	Default {
	
	+NOPAIN;
	+NOGRAVITY;
	Health 200;
	DamageFactor "Head", 15.0;
	Height 40;
	Radius 6;
	}
States{Spawn:
	TNT1 A 0;
	TNT1 A 0 A_PlaySound("Weapons/NailHitBleed");
	TNT1 A 0 A_Recoil(15);
	P1N2 AA 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_Recoil(10);
	P1N2 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	P1N2 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_Recoil(10);
	P1N2 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	P1N2 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_Recoil(10);
	P1N2 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	P1N2 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_Recoil(10);
	P1N2 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	P1N2 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_Recoil(10);
	P1N2 A 4 a_spawnprojectile("Brutal_LiquidBlood3", 25, random(-2,2), random(0, 360), 2, random(0, 40));
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	JustHangThere:
	TNT1 A 0 A_Recoil(6);
	P1N2 A 6;
	TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
	TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
	P1N2 A 16;
	Loop;
	
	LayDown:
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_SpawnItem("DeadZSPEC");
	Stop;
	
	XDeath:
	Death.Explosives:
	Death.ExplosiveImpact:
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_SpawnItem("SargeXDeath");
	Stop;
	
	Death:
	TNT1 AAA 0 bright a_spawnprojectile("SuperGoreSpawner", 35, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAA 0 a_spawnprojectile("BloodMistBig", 40, 0, random(0, 360), 2, random(30, 90));
	TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodMuchFaster", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
	TNT1 AA 0 a_spawnprojectile("XDeathArm1", 32, 0, random(170, 190), 2, random(0, 40));
	TNT1 A 0;
	TNT1 A 0 A_NoBlocking();
	QZD1 EFFGH 5;
	TNT1 A 0 A_PlaySound("BODYF",6);
	//TNT1 A 0 A_SpawnItem("DeadHFQSZ_QZD1H");
	TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	Stop;
}}
