CLASS pb_pistol_Zombieman : pb_Zombie_Man// Replaces ZombieMan
{
Default
{
	pb_monster_base.weapon_type 'pb_pistol';
}

States
{
	Spawn:
		TNT1 A 0;
		PSPO B 1{ammo_amount = random(0, max_magazine_size);}
	Stand:
		PSPO AB 14 A_Look();
	Loop;

	See:
		TNT1 A 0 A_JumpIfHealthLower(1, "Death");
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_CheckSight("SeeNeverSeen");
		TNT1 A 0
		{
			self.bSOLID = true;
			self.bSHOOTABLE = true;
			self.bGHOST = false;
			self.bINVULNERABLE = false;
			self.bSOLID = true;
			self.bSHOOTABLE = true;
			self.bGHOST = false;
			self.bINVULNERABLE = false;
		}
		TNT1 A 0 A_JumpIfCloser(200, "FallBack");
	Advance:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		//TNT1 A 0 A_JumpIfInventory("EnemyMemory", 15, "SearchForPlayer");
		//TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
		PSPO AABB 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
		PSPO CCDD 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
	Loop;

















			
			
			
	WalkAround:
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		PSPO A 2 A_Look();
		PSPO A 2 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		PSPO B 2 A_Look();
		PSPO B 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",3);
		PSPO D 2 A_Look();
		PSPO D 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",4);
		PSPO C 2 A_Look();
		PSPO C 2 A_Wander();
		PSPO D 2 A_Look();
		PSPO D 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",4);
		PSPO B 2 A_Look();
		PSPO B 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",4);
		TNT1 A 0 A_Jump(32, "Stand");
	Loop;

	SearchForPlayer:
	Idle:
		TNT1 A 0 A_JumpIfHealthLower(1, "Death");
		TNT1 A 0 A_ClearTarget();
		//TNT1 A 0 A_TakeInventory("EnemyMemory", 30);
		//TNT1 A 0 A_GiveInventory("SKZombieMan", 1);
		PSPO AB 10 A_Look();
		TNT1 A 0 A_SetAngle(angle - 40);
		PSPO AC 10 A_Look();
		TNT1 A 0 A_SetAngle(angle + 40);
		PSPO AD 10 A_Look();
		TNT1 A 0 A_SetAngle(angle + 40);
		PSPO AA 10 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		PSPO B 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		PSPO C 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		PSPO D 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
	Loop;

	FallBack:
		TNT1 A 0 A_CheckSight("Advance");
		TNT1 A 0 {self.bNODROPOFF = true;}
		PSPO D 2 A_FaceTarget();
		PSPO D 2 A_Recoil(2);
		TNT1 A 0 A_jump(64, "Missile");
		PSPO C 2 A_FaceTarget();
		PSPO C 2 A_Recoil(2);
		PSPO B 2 A_FaceTarget();
		PSPO B 2 A_Recoil(2);
		PSPO A 2 A_FaceTarget();
		PSPO A 2 A_Recoil(2);
		PSPO D 2 A_FaceTarget();
		PSPO D 2 A_Recoil(2);
		TNT1 A 0 A_jump(64, "Missile");
		PSPO C 2 A_FaceTarget();
		PSPO C 2 A_Recoil(2);
		PSPO B 2 A_FaceTarget();
		PSPO B 2 A_Recoil(2);
		PSPO A 2 A_FaceTarget();
		PSPO A 2 A_Recoil(2);
	GOto Missile;


	SeeNeverSeen:
		TNT1 A 0 A_JumpIfCloser(200, "FallBack");
	Advance:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		PSPO AABB 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
		PSPO CCDD 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
	Loop;
			//////////////////////////////////////////
			
	Missile:
		//TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 A_Jump(122, "Attack2", "AimedAttack", "CrouchAttack");
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", 1);
		PSPO E 8 A_FaceTarget();
		TNT1 A 0 A_PlaySound("weapons/pistol");
		PSPO F 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 42, 0, random(-8, 8), 0);
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 44, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		PSPO E 4 A_FaceTarget();
		TNT1 A 0 A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
	Goto See;

	Attack2:
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", 1);
		PSPO E 8 A_FaceTarget();
		TNT1 A 0 A_PlaySound("weapons/pistol");
		PSPO F 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 42, 0, random(-8, 8), 0);
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 44, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		PSPO E 5 A_FaceTarget();
		TNT1 A 0 A_PlaySound("weapons/pistol");
		PSPO F 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 42, 0, random(-8, 8), 0);
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 44, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		PSPO E 5 A_FaceTarget();
		TNT1 A 0 A_PlaySound("weapons/pistol");
		PSPO F 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 42, 0, random(-8, 8), 0);
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 44, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		PSPO E 4 A_FaceTarget();
		TNT1 A 0 A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
	Goto See;
			
	AimedAttack:
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", 5);
		PSPO E 3 A_FaceTarget();
		PSPO J 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 52, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		PSPO K 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 48, 0, random(-8, 8), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		PSPO J 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 52, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		PSPO K 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 48, 0, random(-9, 9), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		PSPO J 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 52, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		PSPO K 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 48, 0, random(-10, 10), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		PSPO J 4 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 52, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		PSPO K 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 48, 0, random(-9, 9), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		PSPO J 4 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 52, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		PSPO K 4 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 38, 0, random(-9, 9), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		PSPO E 3;
		TNT1 A 0 A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
	Goto See;
			
			
	CrouchAttack:
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", 5);
		PSPO EJ 3 A_FaceTarget();
		PSPO H 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 40, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		PSPO I 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 48, 0, random(-8, 8), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		PSPO H 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 40, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		PSPO I 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 48, 0, random(-9, 9), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		PSPO H 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 40, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		PSPO I 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 48, 0, random(-10, 10), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		PSPO H 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 40, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		PSPO I 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 48, 0, random(-9, 9), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		PSPO H 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 40, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		PSPO I 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 38, 0, random(-9, 9), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		PSPO HJE 3;
		TNT1 A 0 A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
	Goto See;
			
	Reload:
		TNT1 A 0 A_TakeInventory("ZombieManAmmo", 20);
		PSPO E 3;
		PSPO E 1 a_spawnprojectile("EmptyClipMP40", 38, 0, random(-11, 11), 0);
		TNT1 A 0 A_PlaySound("PSRLOUT", 1);
		IDP2 A 12;
		IDP2 BC 6;
		TNT1 A 0 A_PlaySound("PSRLFIN", 3);
		IDP2 A 6;
		PSPO A 6;
	Goto see;
			
	Pain.Avoid:
		PSPO AABBCC 3 A_FastChase();
	Goto Missile;
			
	Pain.ExtremePunches:
	Pain.ExplosiveImpact:
	Pain.Explosive:
		TNT1 A 0;
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain");
		//TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		ID31 AB 12;
	Goto FallingAfterImpact;
			
	Pain.BlackHole:
		TNT1 A 0;
		ID31 A 1 A_Pain();
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain");
		//TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,9,0,1);
		ID31 A 1 A_facetarget();
		ID31 A 6 ThrustThing(angle*256/360+128, 10, 0, 0);
		ID31 A 8;
	Goto FallingAfterImpact;
			
	Pain.Kick:
	Pain.extremepunches:
		TNT1 A 0;
		ID31 A 1 A_Pain();
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain");
		//TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		ID31 A 1 A_facetarget();
		ID31 A 6 ThrustThing(angle*256/360+128, 15, 0, 0);
	Goto FallingAfterImpact;
			
	FallingAfterImpact:
		//ID31 B 1 A_GiveInventory("FallingHeight", 1);
		ID31 B 1 A_CheckFloor("GetUp");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_JumpIf(vel.z == 0, "GetUp");
	Loop;
			
	GetUp:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("LargeMassWaterImpact");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 5, "FallingDie");
		//TNT1 A 0 A_TakeInventory("FallingHeight", 100);
		2D11 RRRRRRR 5 A_JumpIf(vel.z < 0, "FallingAfterImpact");
		TNT1 A 0 A_TakeInventory("IsDown", 1);
		2D11 Q 10;
	Goto See;
			
	FallingDie:
		TNT1 A 0;
		TNT1 A 0 A_ChangeCountFlags(false);
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 A_SpawnItem("SplatteredSmall");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 15, "Death.Stomp");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 10, "FallingSuperDeath");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 5, "FallingDeath");
	FallingDeath:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0;//A_NoBLocking
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(50, 130));
		ID31 EF 2;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		POSS L -1;
	Stop;
			
	Possession:
		TNT1 A 0 A_SetInvulnerable();
		PSPO G 3;
		PSPO G 3 A_Pain();
 		TNT1 A 0 A_UnSetInvulnerable();
	Goto See;

	Death.Fatality:
		TNT1 A 0;
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_NoBlocking();
		////TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, 1);
	Goto Death.ExplosiveImpact;
		////TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_Jump(256,"Death.Fatality1", "Death.Fatality1", "Death.Fatality2", "Death.Fatality2", "Death.Fatality3", "Death.Fatality4");
	Goto Death.Fatality1;
			
	Death.Fatality1:
		TNT1 A 0 A_Scream();
		////TNT1 A 0 A_GiveToTarget("ZombieManFatality", 1);
	Stop;

	Death.Fatality2:
		TNT1 A 0 A_Scream();
		//TNT1 A 0 A_GiveToTarget("ZombieManFatality2", 1);
	Stop;
	Death.Fatality3:
		TNT1 A 0 A_Scream();
		//TNT1 A 0 A_GiveToTarget("PistolZombiemanFatality1", 1);
	Stop;
	Death.Fatality4:
		TNT1 A 0 A_Scream();
		//TNT1 A 0 A_GiveToTarget("ZombieManFatality4", 1);
	Stop;
	Death.Fatality5://Didn't like this one, but it gives me an idea...
		TNT1 A 0 A_Scream();
		//TNT1 A 0 A_GiveToTarget("ZombieManFatality5", 1);
	Stop;
	Death.Fatality6:
		TNT1 A 0 A_Scream();
		//TNT1 A 0 A_GiveToTarget("ZombieManFatality6", 1);
	Stop;
		
	FallingSuperDeath:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0;//A_NoBLocking
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 AAA 0 ;//A_SpawnItem("Ploft");
	Goto Death.ExplosiveImpact+1;
			
	Pain:
		PSPO G 0 A_JumpIfInventory("IsDown", 1, 6);
		TNT1 A 0 a_spawnprojectile("brutal_FlyingBlood", 35, 0, random(0, 360), 2, random(0, 160));
		PSPO G 3;
		PSPO G 3 A_Pain();
	Goto See;
		TNT1 AAAA 0;
		TNT1 A 0 A_Pain();
		2D11 RRRRQ 10;
		TNT1 A 0 A_TakeInventory("IsDown", 1);
	Goto See;
			
	Pain.Melee:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory("SKZombieMan", 1, "StealthKill");
			TNT1 A 0 A_JumpIfInventory("IsDown", 1, 6);
					PSPO G 3;
					PSPO G 3 A_Pain();
	Goto See;
			TNT1 AAAA 0;
			TNT1 A 0 A_Pain();
			2D11 RRRRQ 10;
				TNT1 A 0 A_TakeInventory("IsDown", 1);
	Goto See;
			
	Death:
			TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Death.Down");
			TNT1 A 0;
			TNT1 AA 0 a_spawnprojectile("Brutal_FlyingBlood", 7, 0, random(0, 360), 2, random(0, 160));
			TNT1 A 0 A_Jump(32, "Death.Arm");
	Death.MinorLeg:
			TNT1 A 0 A_Jump(129, "DeathOther", "DeathOther2");
			TNT1 A 0 A_Jump(128, "DeathMirror");
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_Scream();
			POSS J 5;// A_SpawnItem("Zombieman_DeathMinorLeg");
	Stop;
}

}

CLASS pb_pistol_Zombieman_2 : pb_Zombie_Man// Replaces ZombieMan
{
Default
{
	Health 34;
	Speed 6;
	Scale 1.0;
	Radius 16;

	PainChance "Kick", 255;
	PainChance "SuperKick", 255;
	PainChance "Melee", 255;
	PainChance "MonsterKnocked", 255;
	PainChance "ExplosiveImpact", 255;

	pb_monster_base.weapon_type 'pb_pistol';
}

States
{		
	Death.fire:
	Death.Flames:
	Death.Burn:
		//TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("BurningZombieMan");
	Stop;
		
		
	Possession:
		TNT1 A 0 {self.bINVULNERABLE = true;}
		9OS2 G 3;
		9OS2 G 3 A_Pain();
 		TNT1 A 0 {self.bINVULNERABLE = false;}
		Goto See;
		
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_TakeInventory("ZombiemanAmmo", 20);
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", random(1,10));
		9OS2 B 1;
	Goto Stand;
		
	Stand:
		9OS2 AB 10 A_Look();
	Loop;
		
	WalkAround:
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		9OS2 A 2 A_Look();
		9OS2 A 2 A_Wander();
		TNT1 A 0 A_Recoil(-1);

		9OS2 B 2 A_Look();
		9OS2 B 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",3);
		
		9OS2 D 2 A_Look();
		9OS2 D 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",4);
		
		9OS2 C 2 A_Look();
		9OS2 C 2 A_Wander();
		
		9OS2 D 2 A_Look();
		9OS2 D 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",4);
		
		9OS2 B 2 A_Look();
		9OS2 B 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",4);
		TNT1 A 0 A_Jump(32, "Stand");
		Loop;
		
		
	SearchForPlayer:
	Idle:
		TNT1 A 0 A_JumpIfHealthLower(1, "Death");
		TNT1 A 0 A_ClearTarget();
		TNT1 A 0 A_TakeInventory("EnemyMemory", 30);
		TNT1 A 0 A_GiveInventory("SKHelmetZombie1", 1);
		9OS2 A 10 A_Look();
		9OS2 B 10 A_Look();
		TNT1 A 0 {self.angle -= 40;}
		9OS2 A 10 A_Look();
		9OS2 C 10 A_Look();
		TNT1 A 0 {self.angle += 40;}
		9OS2 A 10 A_Look();
		9OS2 D 10 A_Look();
		TNT1 A 0 {self.angle += 40;}
		9OS2 A 10 A_Look();
		
		9OS2 A 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		9OS2 B 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		9OS2 C 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		9OS2 D 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
	Loop;
		
		
	FallBack:
		TNT1 A 0 A_CheckSight("Advance");
		TNT1 A 0 {self.bNODROPOFF = true;}
		9OS2 D 2 A_FaceTarget();
		9OS2 D 2 A_Recoil(2);
		TNT1 A 0 A_jump(64, "Missile");
		9OS2 C 2 A_FaceTarget();
		9OS2 C 2 A_Recoil(2);
		9OS2 B 2 A_FaceTarget();
		9OS2 B 2 A_Recoil(2);
		9OS2 A 2 A_FaceTarget();
		9OS2 A 2 A_Recoil(2);
		9OS2 D 2 A_FaceTarget();
		9OS2 D 2 A_Recoil(2);
		TNT1 A 0 A_jump(64, "Missile");
		9OS2 C 2 A_FaceTarget();
		9OS2 C 2 A_Recoil(2);
		9OS2 B 2 A_FaceTarget();
		9OS2 B 2 A_Recoil(2);
		9OS2 A 2 A_FaceTarget();
		9OS2 A 2 A_Recoil(2);
		GOto Missile;
		
	See:
		TNT1 A 0 A_JumpIfHealthLower(1, "Death");
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_TakeInventory("EnemyMemory", 15);
		TNT1 A 0 A_CheckSight("SeeNeverSeen");
		TNT1 A 0 A_JumpIfHealthLower(1, "Death");
		TNT1 A 0 {self.bSOLID = true;}
		TNT1 A 0 {self.bSHOOTABLE = true;}
		TNT1 A 0 {self.bGHOST = false;}
		TNT1 A 0 {self.bINVULNERABLE = false;}
		TNT1 A 0 A_JumpIfCloser(200, "FallBack");
	Advance:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		TNT1 A 0 A_JumpIfInventory("EnemyMemory", 15, "SearchForPlayer");
		TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
		
		9OS2 AABB 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
		
		9OS2 CCDD 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
	Loop;
		
	SeeNeverSeen:
		TNT1 A 0 A_JumpIfCloser(200, "FallBack");
	Advance:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		9OS2 AABB 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
		9OS2 CCDD 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
	Loop;

		
	Missile:
		TNT1 A 0 A_Jump(128, "Attack2", "AimedAttack", "CrouchAttack");
		
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", 1);
		
		9OS2 E 8 A_FaceTarget();
		TNT1 A 0 A_PlaySound("weapons/pistol");
		9OS2 F 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 42, 0, random(-8, 8), 0);
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 44, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		9OS2 E 4 A_FaceTarget();
		TNT1 A 0 A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
		Goto See;
		
	Attack2:
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", 1);
		9OS2 E 8 A_FaceTarget();
		TNT1 A 0 A_PlaySound("weapons/pistol");
		9OS2 F 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 42, 0, random(-8, 8), 0);
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 44, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		9OS2 E 5 A_FaceTarget();
		TNT1 A 0 A_PlaySound("weapons/pistol");
		9OS2 F 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 42, 0, random(-8, 8), 0);
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 44, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		9OS2 E 5 A_FaceTarget();
		TNT1 A 0 A_PlaySound("weapons/pistol");
		9OS2 F 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 42, 0, random(-8, 8), 0);
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 44, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		9OS2 E 5 A_FaceTarget();
		TNT1 A 0 A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
		Goto See;
		
	AimedAttack:
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", 5);
		9OS2 E 3 A_FaceTarget();
		9OS2 L 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 54, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		9OS2 M 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 48, 0, random(-8, 8), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		9OS2 L 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 54, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		9OS2 M 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 48, 0, random(-9, 9), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		9OS2 L 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 54, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		9OS2 M 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 48, 0, random(-10, 10), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		9OS2 L 4 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 54, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		9OS2 M 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 48, 0, random(-9, 9), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		9OS2 L 4 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt",54, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		9OS2 M 4 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 38, 0, random(-9, 9), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		9OS2 LE 3;
		TNT1 A 0 A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
		Goto See;
		
		
	CrouchAttack:
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", 5);
		9OS2 EL 3 A_FaceTarget();
		9OS2 K 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 40, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		9OS2 J 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 48, 0, random(-8, 8), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		9OS2 K 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 40, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		9OS2 J 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 48, 0, random(-9, 9), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		9OS2 K 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 40, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		9OS2 J 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 48, 0, random(-10, 10), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		9OS2 K 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 40, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		9OS2 J 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 48, 0, random(-9, 9), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		9OS2 K 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 40, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/pistol");
		9OS2 J 3 BRIGHT a_spawnprojectile("MonsterHandgunTracer", 38, 0, random(-9, 9), 0);
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		9OS2 KLE 3;
		TNT1 A 0 A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
		Goto See;

	Reload:
		TNT1 A 0 A_TakeInventory("ZombieManAmmo", 20);
		9OS2 E 3;
		9OS2 E 1 a_spawnprojectile("EmptyClipMP40", 38, 0, random(-11, 11), 0);
		TNT1 A 0 A_PlaySound("PSRLOUT", 1);
		IDP3 AA 6;
		TNT1 A 0 A_PlaySound("PSRLIN", 1);
		IDP3 BC 6;
		TNT1 A 0 A_PlaySound("CLIPIN");		
		IDP3 A 6;
		9OS2 A 6;
	Goto See;
		
	StealthKill:
		TNT1 A 1;
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("SKHelmetZombie1", 1);
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Die("Stealthy");
		TNT1 A 0 A_Fall();
		TNT1 A 1;
		Stop;
		
	Pain.ExtremePunches:
	Pain.ExplosiveImpact:
	Pain.Explosive:
		TNT1 A 0;
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain");
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		1D31 A 12;
		Goto FallingAfterImpact;
		
	Pain.BlackHole:
		TNT1 A 0;
		1D31 A 1 A_Pain();
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain");
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,9,0,1);
		ID31 A 1 A_facetarget();
		1D31 A 6 ThrustThing(angle*256/360+128, 10, 0, 0);
		1D31 A 8;
		Goto FallingAfterImpact;
		
	Pain.Kick:
	Pain.extremepunches:
		TNT1 A 0;
		1D31 B 1 A_Pain();
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain");
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		1D31 B 1 A_facetarget();
		1D31 B 6 ThrustThing(angle*256/360+128, 10, 0, 0);
		1D31 A 8;
		Goto FallingAfterImpact;
		
	FallingAfterImpact:
		ID31 B 1 A_GiveInventory("FallingHeight", 1);
		ID31 B 1 A_CheckFloor("GetUp");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_JumpIf(vel.z == 0, "GetUp");
		Loop;
		
	GetUp:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 5, "FallingDie");
		TNT1 A 0 A_TakeInventory("FallingHeight", 100);
		1D11 RRRRRRR 5 A_JumpIf(vel.z < 0, "FallingAfterImpact");
		TNT1 A 0 A_TakeInventory("IsDown", 1);
		1D11 Q 10;
		Goto See;
		
	FallingDie:
		TNT1 A 0;
		TNT1 A 0 {self.bCOUNTKILL = false;}
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 A_SpawnItem("SplatteredSmall");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 15, "Death.Stomp");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 10, "FallingSuperDeath");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 5, "FallingDeath");
	FallingDeath:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0;//A_NoBLocking
		//TNT1 A 0 ;//A_SpawnItem("Ploft");
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(50, 130));
		ID31 EF 2;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		POSS L -1;
	Stop;
		
	FallingSuperDeath:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0;//A_NoBLocking
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 AAA 0 ;//A_SpawnItem("Ploft");
	Goto Death.ExplosiveImpact+1;
		
	Pain:
		9OS2 G 0 A_JumpIfInventory("IsDown", 1, 6);
		TNT1 A 0 a_spawnprojectile("brutal_FlyingBlood", 35, 0, random(0, 360), 2, random(0, 160));
		9OS2 G 3;
		9OS2 G 3 A_Pain();
		Goto See;
		TNT1 AAAA 0;
		TNT1 A 0 A_Pain();
		1D11 RRRRQ 10;
		TNT1 A 0 A_TakeInventory("IsDown", 1);
		Goto See;
		
	Pain.Melee:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("SKHelmetZombie1", 1, "StealthKill");
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, 6);
		9OS2 G 3;
		9OS2 G 3 A_Pain();
		Goto See;
		TNT1 AAAA 0;
		TNT1 A 0 A_Pain();
		1D11 RRRRQ 10;
		TNT1 A 0 A_TakeInventory("IsDown", 1);
		Goto See;
		
	Death:
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Death.Down");
		TNT1 A 0;
		TNT1 AA 0 a_spawnprojectile("Brutal_FlyingBlood", 7, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_Jump(32, "Death.Arm");
	Death.MinorLeg:
		//TNT1 A 0 A_Jump(48, "Death.Leg")
		//	TNT1 A 0 A_Jump(128, "DeathMirror")
		9OS2 H 6 A_NoBlocking();
		9OS2 I 5 A_Scream();
		9OS2 Z 5;
		POSS K 5;
		POSS L 1;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		POSS L -1;
	Stop;
		
	Death.SSG:
		ZZD1 E 1 A_Pain();
		ZZD1 E 1 A_FaceTarget();
		//TNT1 A 0 a_spawnprojectile("MeatDeath", 0, 0, random(0, 360), 2, random(0, 160))
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AAA 0 bright a_spawnprojectile("SuperGoreSpawner", 35, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("XDeathArm1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZHead", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		ZZD1 EEFFGH 6;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		ZZD1 H -1;
		Stop;
		
	Death.decaptate:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZHead", 50, 0, random(0, 360), 2, random(50, 90));
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		POSH AAA 15  {pb_blood_and_gore_event.much_blood(self);}
		ZMAD AAAAABBBBBBBBBBCCCCC 2 a_spawnprojectile("Brutal_LiquidBlood2", 30, 0, random(0, 360), 2, random(60, 120));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		ZMAD DDDDEEEEEEEEEEEEEEEE 2 a_spawnprojectile("Brutal_LiquidBlood2", 10, 0, random(0, 360), 2, random(10, 40));
		ZMAD E -1;
	Stop;		
		Stop;

	Death.Blast:
	Death.Railgun:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Jump(12, "Death.Arm");
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Jump(128, "Death.Blast2");
		TNT1 A 0 A_Scream();
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		Z4Z7 A 6 A_Stop();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		Z4Z7 BBBBBBBBBB 3 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(30, 60));
		Z4Z7 CCC 3 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(10, 40));
		Z4Z7 DD 3 a_spawnprojectile("Brutal_LiquidBlood2", 6, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_PlaySound("BODYF",6);
		Z4Z7 E -1;
	Stop;
		
	Death.Blast2:
		TNT1 A 0 A_XScream();
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 42, 0, random(0, 360), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("Xdeath2", 16, 0, random(130, 210), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		ZXZ2 A 6 A_Stop();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		ZXZ2 BBBBBBBBBBBBBBBBBBB 3 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(30, 60));
		ZXZ2 CCC 3 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(10, 40));
		ZXZ2 DD 3 a_spawnprojectile("Brutal_LiquidBlood2", 6, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadZombieMan_Blasted");
		Stop;
		
	Death.Tear:
		TNT1 AAA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		4P2X AA 8 a_spawnprojectile("Brutal_LiquidBlood", 30, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeath4", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("RipHelmetZombieman2", 0, 0, random(0, 360), 2, random(0, 160));
		PP2X BBCD 8 a_spawnprojectile("Brutal_LiquidBlood2", 30, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		PP2X EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 1 a_spawnprojectile("Brutal_LiquidBlood2", 15, 0, random(0, 360), 2, random(0, 90));
		PP2X E -1;
		Stop;
		
		
	Death.Saw:
		TNT1 A 0;
		TNT1 A 0 A_Jump(24, "Death.arm");
		Goto Death.Tear;
		
	Death.cut:
	Death.HKFT:
		TNT1 A 0;
		TNT1 AA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfHelmetZombieMan", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAA 0 a_spawnprojectile("Instestin2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_LiquidBlood", 30, 0, random(0, 360), 2, random(0, 40));
		POSX AABCDE 9 a_spawnprojectile("Brutal_LiquidBlood", 30, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		POSX EEEEEEEEEEEEEEEEEEEEEE 1 a_spawnprojectile("Brutal_LiquidBlood", 12, 0, random(0, 360), 2, random(0, 90));
		TNT1 A 0 A_PlaySound("BODYF",6);
		POSX E -1;
		Stop;
		
	Death.Down:
		POSS I 0 A_Scream();
		POSS J 0 A_NoBlocking();
		POSS K 3;
		POSS L 1;
		POSS L -1;
	Stop;
		
	Death.cutless:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Death.Down");
		TNT1 A 0 A_Jump(16, "Death");
		TNT1 A 0 A_Jump(16, "Death.Cut");
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Scream();
		TNT1 O 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("BrutalizedHelmetZombieMan1", 1);
	Stop;
		
	Death.LegMassacre:
		TNT1 A 0;
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		//TNT1 A 0 A_SpawnItem("ZombieLegOnFoot");
		U4M5 A 1 A_Scream();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("BrutalizedHelmetZombieManLeg");
	Stop;
		
	Death.Arm:
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		U4M6 A 10 A_Scream();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("DyingHelmetZombiemanNoArm");
	Stop;
		
	Death.Nailgun:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 {self.bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,random(20,30),0,1);
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(30);
		1D31 B 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		1D31 B 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		1D31 A 1 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		1D31 A 1 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		POS4 X 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		POS4 Y 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		POSS L -1;
	Stop;

	PinToWall:
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AA 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_PlaySound("Weapons/NailHitBleed");
		PIN3 A 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItemEx("DeadHelmetZombieman_Pinned", 10);
	Stop;
		
	Death.Shotgun:
		TNT1 A 0 A_JumpIfCloser(95, "Death.Blast");
		TNT1 A 0 A_JumpIfCloser(350, "Death.Shotgunontheface");
		Goto Death;
		
	Death.Shotgunontheface:
		TNT1 A 0 A_ClearTarget();
		TNT1 A 0 A_Jump(160, "DeathShotgunFly");
		TNT1 A 0 A_Jump(98, "DeathShotgunFly2");
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_Pain();
		POSS H 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(13);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		TNT1 A 0 A_JumpIf(vel.y == 0, "DeathShotgunFly");
		TNT1 A 0 A_Jump(128, "DeathShotgunontheface2");
		TNT1 A 0 A_Scream();
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AA 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_NoBlocking();
		Z6Z7 ABCD 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		Z6Z7 EFGHIJ 4 A_JumpIf((vel.Y == 0), "DSFStop");
		Goto DSFStop+1;
		
	DSFStop:
		//TNT1 A 0 ;//A_Explode(20,30, 0);
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 a_spawnprojectile("SuperWallRedBlood", 2, 0, random(170, 190), 2, random(0, 0));
		TNT1 A 0 A_PlaySound("BODYF",6);
		Z6Z7 J -1;
	Stop;
		
	DeathShotgunontheface2:
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AA 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		Z6Z7 KLMN 4 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		Z6Z7 OPQRST 4 A_JumpIf((vel.Y == 0), "DSFStop2");
		Goto DSFStop2+1;
		
	DSFStop2:
		//TNT1 A 0 ;//A_Explode(20,30, 0);
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 a_spawnprojectile("SuperWallRedBlood", 2, 0, random(170, 190), 2, random(0, 0));
		TNT1 A 0 A_PlaySound("BODYF",6);
		Z6Z7 PQRS 5;
		Z6Z7 T -1;
	Stop;
		
		
	DeathShotgunFly2:
		U4M8 A 1;
		TNT1 AAAA 0 a_spawnprojectile("Brutal_LiquidBlood2", 20, 0, random(0, 360), 2, random(60, 120));
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AA 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		U4M8 A 1 A_Pain();
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(10);
		TNT1 A 0 ThrustThingZ(0,35,0,1);
		U4M8 B 0 A_Scream();
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		U4M8 C 0 A_NoBlocking();
		U4M8 BCDEF 6;
		TNT1 A 0 A_PlaySound("BODYF",6);
		U4M8 FFFFFFFFFF 4 a_spawnprojectile("Brutal_LiquidBlood2", 10, 0, random(0, 360), 2, random(10, 40));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		U4M8 F 1;
		U4M8 F -1;
	Stop;
		
	DeathShotgunFly:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 {self.bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(6);
		1D31 B 1 A_Pain();
		1D31 B 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		1D31 B 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		1D31 A 1 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		1D31 A 1 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		POS4 X 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		POS4 Y 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		POSS L -1;
	Stop;

	TakeASit:
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_PlaySound("BODYF",6);
		1D31 B 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItemEx("DeadHelmetZombieman_Slumped", 10);
	Stop;
		
	Death.Leg:
		TNT1 A 0;
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 a_spawnprojectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathZombieLeg", 35, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("HelmetZombiemanGotHisLegBlowed");
	Stop;
		
	HeadExploder:
		TNT1 A 0 A_Jump(72, "Death.HeadExplode");
		Goto Death.HeadMinor;
		
	Death.Head:
		//TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		//TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
		//TNT1 A 0 A_JumpIfInTargetInventory("HasCutingWeapon", 1, "Death.Decaptate");
		TNT1 A 0 A_JumpIfHealthLower(-200, "HeavyHead");
		TNT1 A 0 A_JumpIfHealthLower(-50, "Death.HeadExplode");
		////TNT1 A 0 A_JumpIfInTargetInventory("RandomHeadExploder", 1, "HeadExploder");
	Death.HeadMinor:
		TNT1 A 0 A_Jump(156, "DeathMinorHead5", "MinorHead2", "MinorHead3");
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("Brains4Green", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 A 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		
		U4M7 A 6  {pb_blood_and_gore_event.much_blood(self);}
		U4M7 BC 8;
		
		TNT1 A 0 A_Scream();
		U4M7 D 6 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		U4M7 E 1;
		U4M7 E -1;
	Stop;
		
	MinorHead2:
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("Brains4Green", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 A 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		
		U4M7 F 6  {pb_blood_and_gore_event.much_blood(self);}
		U4M7 GH 8;
		
		TNT1 A 0 A_Scream();
		U4M7 I 6 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		U4M7 J 1;
		U4M7 J -1;
	Stop;
		
	MinorHead3:
		TNT1 A 0 A_Scream();
		U4M9 A 5  {pb_blood_and_gore_event.much_blood(self);}
		U4M9 B 5;
		TNT1 A 0 a_spawnprojectile("Brains2", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 A 0 a_spawnprojectile("Brains4", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 A 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Teeth", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		U4M9 C 5 A_NoBlocking();
		U4M9 DE 5;
		TNT1 A 0 A_PlaySound("BODYF",6);
		U4M9 F 1;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		U4M9 F -1;
	Stop;
		
	DeathMinorHead5:
		TNT1 A 0;
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("Brains4Green", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 A 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		
		PXS4 A 6  {pb_blood_and_gore_event.much_blood(self);}
		PXS4 BC 7;
		
		TNT1 A 0 A_Scream();
		PXS4 D 6 A_NoBlocking();
		PXS4 E 6;
		PXS4 F 6;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		PXS4 F 1;
		PXS4 F -1;
	Stop;
		
	XDeath:
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile("ZombieHelmetXDeath", 2, 0, random(0, 360), 2, random(0, 160));
	Stop;
		
	Death.Fatality:
		TNT1 A 0;
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_NoBlocking();
		////TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, 1);
	Goto Death.ExplosiveImpact;
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_Jump(256,"Death.Fatality1", "Death.Fatality2", "Death.Fatality3", "Death.Fatality4");
	Death.Fatality1:
		TNT1 A 0 A_Scream();
		//TNT1 A 0 A_GiveToTarget("HelmetZombieManFatality", 1);
		Stop;
	Death.Fatality2:
		TNT1 A 0 A_Scream();
		//TNT1 A 0 A_GiveToTarget("HelmetZombieManFatality2", 1);
		Stop;
	Death.Fatality3:
		TNT1 A 0 A_Scream();
		//TNT1 A 0 A_GiveToTarget("HelmetZombieManFatality3", 1);
		Stop;
	Death.Fatality4:
		TNT1 A 0 A_Scream();
		//TNT1 A 0 A_GiveToTarget("HelmetZombieManFatality4", 1);
	Stop;
		
}

}

CLASS pb_Helmet_ZombieMan: pb_pistol_Zombieman_2// Replaces ZombieMan
{ 
Default
{
	pb_monster_base.weapon_type 'pb_pistol';
	//а тут пара пукалок спавниться...переробити треба на массиви
//	//DropItem "DropedRifle";
//	//DropItem "DropedGrenade", 5;
//	//DropItem "PistolDrop";
}

States
{
	Spawn:
		TNT1 A 0 A_TakeInventory("ZombiemanAmmo", 20);
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", random(1,10));
		ZIV1 B 1;
	Stand:
		ZIV1 AB 11 A_Look();
	Loop;

	Possession:
		TNT1 A 0 {self.bINVULNERABLE = true;}
		ZPV1 A 3;
		ZPV1 A 3 A_Pain();
 		TNT1 A 0 {self.bINVULNERABLE = false;}
	Goto See;
	
	SearchForPlayer:
	Idle:
		TNT1 A 0 A_JumpIfHealthLower(1, "Death");
		TNT1 A 0 A_ClearTarget();
		TNT1 A 0 A_TakeInventory("EnemyMemory", 30);
		TNT1 A 0 A_GiveInventory("SKHelmetZombie1", 1);
		
		ZIV1 ABABAB 10 A_Look();

		ZMV1 A 4 A_Look();
		TNT1 A 0 A_PlaySound("humans/step",3);
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		ZMV1 B 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		ZMV1 C 4 A_Look();
		TNT1 A 0 A_PlaySound("humans/step",3);
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		ZMV1 D 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		
		TNT1 A 0 A_Jump(128, "Idle");
		ZMV1 A 4 A_Look();
		TNT1 A 0 A_PlaySound("humans/step",3);
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		ZMV1 B 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		ZMV1 C 4 A_Look();
		TNT1 A 0 A_PlaySound("humans/step",3);
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		ZMV1 D 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
	Loop;
		
		
	FallBack:
		TNT1 A 0 A_CheckSight("Advance");
		TNT1 A 0 {self.bNODROPOFF = true;}
		ZMV1 D 2 A_FaceTarget();
		ZMV1 D 2 A_Recoil(2);
		TNT1 A 0 A_jump(64, "Missile");
		TNT1 A 0 A_PlaySound("humans/step",3);
		ZMV1 C 2 A_FaceTarget();
		ZMV1 C 2 A_Recoil(2);
		ZMV1 B 2 A_FaceTarget();
		ZMV1 B 2 A_Recoil(2);
		TNT1 A 0 A_PlaySound("humans/step",3);
		ZMV1 A 2 A_FaceTarget();
		ZMV1 A 2 A_Recoil(2);
		TNT1 A 0 A_PlaySound("humans/step",3);
		ZMV1 D 2 A_FaceTarget();
		ZMV1 D 2 A_Recoil(2);
		TNT1 A 0 A_jump(64, "Missile");
		ZMV1 C 2 A_FaceTarget();
		ZMV1 C 2 A_Recoil(2);
		TNT1 A 0 A_PlaySound("humans/step",3);
		ZMV1 B 2 A_FaceTarget();
		ZMV1 B 2 A_Recoil(2);
		ZMV1 A 2 A_FaceTarget();
		ZMV1 A 2 A_Recoil(2);
		TNT1 A 0 A_PlaySound("humans/step",3);
	GOto Missile;
		
	See:
		TNT1 A 0 A_JumpIfHealthLower(1, "Death");
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_TakeInventory("EnemyMemory", 15);
	SeeContinue:
		TNT1 A 0 A_JumpIfHealthLower(1, "Death");
		TNT1 A 0 {self.bSOLID = true;}
		TNT1 A 0 {self.bSHOOTABLE = true;}
		TNT1 A 0 {self.bGHOST = false;}
		TNT1 A 0 {self.bINVULNERABLE = false;}
		TNT1 A 0 A_JumpIfCloser(200, "FallBack");
	Advance:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		TNT1 A 0 A_JumpIfInventory("EnemyMemory", 15, "SearchForPlayer");
		TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
		
		ZMV1 AA 2 A_Chase();
		
		ZMV1 BB 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
		
		ZMV1 CC 2 A_Chase();
		
		ZMV1 DD 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
		Loop;
		
	SeeNeverSeen:
		TNT1 A 0 A_JumpIfCloser(200, "FallBack");
	Advance:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		ZMV1 AABB 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
		ZMV1 CCDD 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
	Loop;
		
	Pain.Taunt:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("Enraged", 1, "Missile");
		ZMV1 B 0 A_Pain();
		TNT1 A 0 {self.bMISSILEMORE = true;}
		TNT1 A 0 {self.bMISSILEEVENMORE = true;}
		TNT1 A 0 A_PlaySound("grunt/sight");
		ZMV1 B 1 A_FaceTarget();
		ZMV1 B 10;
		TNT1 A 0 A_GiveInventory("Enraged", 1);
		TNT1 A 0 A_PlaySound("grunt/sight", 1);
		Goto Missile;
		
	Missile:
		TNT1 A 0 A_Stop();
		TNT1 A 0 {self.bGHOST = false;}
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_TakeInventory("EnemyMemory", 10);
		TNT1 A 0 A_JumpIfInventory("NoZombieGrenade", 1, "JustShootTheFuckingRifle");
		TNT1 A 0 A_JumpIfCloser(900, 3);
		ZSV1 E 1 A_FaceTarget();
		TNT1 A 0 A_Jump(24, "Grenade");
	JustShootTheFuckingRifle:
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", 2);
		//TNT1 A 0 A_JumpIfInventory("NoZombieManAdvancedAttacks", 1, "JustShootTheFuckingRifle1");
		TNT1 A 0 A_Jump(110, "JustShootTheFuckingRifle2", "JustShootTheFuckingRifle3", "JustShootTheFuckingRifle4");
		TNT1 A 0 A_Jump(60, "MissileLeft", "MissileRight", "MissileBackward", "MissileForward");
	JustShootTheFuckingRifle1:
		ZSV1 E 6 A_FaceTarget();
		ZSV1 E 6 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		ZSV1 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 1, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		ZSV1 E 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		ZSV1 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 1, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		ZSV1 E 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		ZSV1 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 1, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		ZSV1 E 2 A_FaceTarget();
		TNT1 A 0 A_JumpIfInventory("Enraged", 1, "Missile");
		TNT1 A 0 A_jump(96, "Missile");
		ZSV1 E 6 A_FaceTarget();
		TNT1 A 0 A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
		Goto see;
		
		
	JustShootTheFuckingRifle2:
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", 2);
		ZSV1 E 6 A_FaceTarget();
		ZSV1 E 6 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		ZSV1 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 1, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		ZSV1 E 3 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		ZSV1 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 1, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		ZSV1 E 3 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		ZSV1 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 1, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		ZSV1 E 3 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		ZSV1 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 1, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		ZSV1 E 3 A_FaceTarget();
		TNT1 A 0 A_JumpIfInventory("Enraged", 1, "Missile");
		TNT1 A 0 A_jump(96, "Missile");
		ZSV1 E 6 A_FaceTarget();
		TNT1 A 0 A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
		Goto see;
		
	JustShootTheFuckingRifle3:
		P056 E 6 A_FaceTarget();
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", 2);
		P056 E 6 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 42, 18, 15, 0);
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 39, 4);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		P056 E 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 36,0);
		P056 E 3 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 42, 18, 15, 0);
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 39, 4);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		P056 E 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 36,0);
		P056 E 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 42, 18, 15, 0);
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 39, 4);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		P056 E 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 36,0);
		P056 E 1 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 42, 18, 15, 0);
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 39, 4);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		P056 E 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 36,0);
		P056 E 1 A_FaceTarget();
		TNT1 A 0 A_JumpIfInventory("Enraged", 1, "Missile");
		TNT1 A 0 A_jump(96, "Missile");
		P056 E 6 A_FaceTarget();
		TNT1 A 0 A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
		Goto see;
		
	JustShootTheFuckingRifle4:
		P056 F 6 A_FaceTarget();
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", 2);
		P056 F 6 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 32, 16, 15, 0);
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 32, 4);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		P056 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 36,0);
		P056 F 3 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 32, 16, 15, 0);
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 32, 4);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		P056 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 36,0);
		P056 F 3 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 32, 18, 15, 0);
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 39, 4);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		P056 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 36,0);
		P056 F 3 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("OrangeLensFlareAlt", 42, 18, 15, 0);
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 39, 4);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		P056 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-4, 4), 1, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 36,0);
		P056 F 2 A_FaceTarget();
		TNT1 A 0 A_JumpIfInventory("Enraged", 1, "Missile");
		TNT1 A 0 A_jump(96, "Missile");
		P056 FE 6 A_FaceTarget();
		TNT1 A 0 A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
		Goto see;
		
	MissileLeft:
		TNT1 A 0;
		
		P056 AA 2 A_FaceTarget();
		TNT1 A 0 ThrustThing(angle*256/360+192, 3, 0, 0);
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 34, 6);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		P056 BB 2 BRIGHT;
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		
		TNT1 A 0 ThrustThing(angle*256/360+192, 2, 0, 0);
		P056 CC 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 34, 6);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		P056 DD 2 BRIGHT;
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		
		P056 AA 2 A_FaceTarget();
		TNT1 A 0 ThrustThing(angle*256/360+192, 2, 0, 0);
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 34, 6);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		P056 BB 2 BRIGHT;
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		
		TNT1 A 0 ThrustThing(angle*256/360+192, 3, 0, 0);
		P056 CC 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 34, 6);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		P056 DD 2 BRIGHT;
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_jump(64, "Missile");
		Goto see;
		
	MissileRight:
		TNT1 A 0;
		
		P056 AA 2 A_FaceTarget();
		TNT1 A 0 ThrustThing(angle*256/360+64, 3, 0, 0);
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 34, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		P056 BB 2 BRIGHT;
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		
		TNT1 A 0 ThrustThing(angle*256/360+64, 2, 0, 0);
		P056 CC 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 34, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		P056 DD 2 BRIGHT;
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		
		P056 AA 2 A_FaceTarget();
		TNT1 A 0 ThrustThing(angle*256/360+64, 2, 0, 0);
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 34, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		P056 BB 2 BRIGHT;
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		
		TNT1 A 0 ThrustThing(angle*256/360+64, 2, 0, 0);
		P056 CC 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 34, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		P056 DD 2 BRIGHT;
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_jump(64, "Missile");
		Goto see;
		
	MissileForward:
		TNT1 A 0;
		
		TNT1 A 0 A_Recoil(-1);
		P056 AA 2 A_FaceTarget();
		TNT1 A 0 A_Recoil(-2);
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 34, 6);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_JumpIf(vel.x == 0 || vel.y == 0, "JustShootTheFuckingRifle1");
		P056 BB 2 BRIGHT;
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		
		TNT1 A 0 A_Recoil(-2);
		P056 CC 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 34, 6);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_JumpIf(vel.x == 0 || vel.y == 0, "JustShootTheFuckingRifle1");
		P056 DD 2 BRIGHT;
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		
		P056 AA 2 A_FaceTarget();
		TNT1 A 0 A_Recoil(-2);
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 34, 6);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_JumpIf(vel.x == 0 || vel.y == 0, "JustShootTheFuckingRifle1");
		P056 BB 2 BRIGHT;
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		
		TNT1 A 0 A_Recoil(-2);
		P056 CC 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 34, 6);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_JumpIf(vel.x == 0 || vel.y == 0, "JustShootTheFuckingRifle1");
		P056 DD 2 BRIGHT;
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_jump(64, "Missile");
		Goto see;
		
	MissileBackward:
		TNT1 A 0;
		
		TNT1 A 0 A_Recoil(1);
		P056 DD 2 A_FaceTarget();
		TNT1 A 0 A_Recoil(2);
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 34, 6);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_JumpIf(vel.x == 0 || vel.y == 0, "JustShootTheFuckingRifle1");
		P056 CC 2 BRIGHT;
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		
		TNT1 A 0 A_Recoil(2);
		P056 BB 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 34, 6);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_JumpIf(vel.x == 0 || vel.y == 0, "JustShootTheFuckingRifle1");
		P056 AA 2 BRIGHT;
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		
		P056 DD 2 A_FaceTarget();
		TNT1 A 0 A_Recoil(2);
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 34, 6);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_JumpIf(vel.x == 0 || vel.y == 0, "JustShootTheFuckingRifle1");
		P056 CC 2 BRIGHT;
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		
		TNT1 A 0 A_Recoil(2);
		TNT1 A 0 A_JumpIf(vel.x == 0 || vel.y == 0, "JustShootTheFuckingRifle1");
		P056 BB 2 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("MarineMuzzle1", 34, 6);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_JumpIf(vel.x == 0 || vel.y == 0, "JustShootTheFuckingRifle1");
		P056 AA 2 BRIGHT;
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_jump(64, "Missile");
		Goto see;
		
	Grenade:
		TNT1 A 0 A_CheckLOF("ActuallyThrowGrenade");//Basically checks if he doesn't have any dumbass in between him and the player
		TNT1 A 0 A_JumpIfInventory("ZombieManGrenadeCount", 3, "JustShootTheFuckingRifle");
		Goto JustShootTheFuckingRifle;
	ActuallyThrowGrenade:
		TNT1 A 0 A_Stop();
		TNT1 A 0 {self.bGHOST = false;}
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_TakeInventory("EnemyMemory", 10);
		
		TNT1 A 0 A_JumpIfInventory("ZombieManGrenadeCount", 3, "JustShootTheFuckingRifle");
		TNT1 A 0 A_JumpIfCloser(500, 1);
		Goto Missile+7;
		TNT1 A 0 A_JumpIfCloser(85, "JustShootTheFuckingRifle");
		TNT1 A 0 A_JumpIfInventory("ZombieManGrenadeCount", 3, "JustShootTheFuckingRifle");
		P05G A 6 A_FaceTarget();
		TNT1 A 0 A_PlaySound("OPNGRN", 1);
		P05G A 6 A_FaceTarget();
		TNT1 A 0 A_PlaySound("THRGRN", 1);
		TNT1 A 0 A_GiveInventory("ZombieManGrenadeCount", 1);
		//P05G B 6 a_spawnprojectile("EnemyThrownGrenade", 42);
	Goto see;
		
	Reload:
		TNT1 A 0 A_TakeInventory("ZombieManAmmo", 20);
		ZSV1 E 3;
		ZSV1 E 1 a_spawnprojectile("EmptyClipSpawn", 38, 0, random(-11, 11), 0);
		TNT1 A 0 A_PlaySound("Reload");
		
		P05R A 10;
		
		P05R A 10;
		
		P05R B 10;
		
		P05R C 10;
		TNT1 A 0 A_PlaySound("CLIPIN");
		
		P05R D 10;
		
		ZSV1 E 10;
		Goto see;
		
		
	Pain.Kick:
	Pain.extremepunches:
		TNT1 A 0;
		1D31 B 1 A_Pain();
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain");
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		1D31 B 1 A_facetarget();
		1D31 B 6 ThrustThing(angle*256/360+128, 10, 0, 0);
		1D31 A 8;
		Goto FallingAfterImpact;
		
	FallingAfterImpact:
		ID31 B 1 A_GiveInventory("FallingHeight", 1);
		ID31 B 1 A_CheckFloor("GetUp");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_JumpIf(vel.z == 0, "GetUp");
		Loop;
		
	FallingDie:
		TNT1 A 0;
		TNT1 A 0 A_ChangeCountFlags(false);
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 A_SpawnItem("SplatteredSmall");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 15, "Death.Stomp");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 10, "FallingSuperDeath");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 5, "FallingDeath");
	FallingDeath:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0;//A_NoBLocking
		TNT1 A 0 ;//A_SpawnItem("Ploft");
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(50, 130));
		ID31 EF 2;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		POSS L -1;
	Stop;
		
	FallingSuperDeath:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0;//A_NoBLocking
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 AAA 0 ;//A_SpawnItem("Ploft");
	Goto Death.ExplosiveImpact+1;
		
	GetUp:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 5, "FallingDie");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_TakeInventory("FallingHeight", 100);
		P05K AAAAAAA 5 A_JumpIf(vel.z < 0, "FallingAfterImpact");
		TNT1 A 0 A_TakeInventory("IsDown", 1);
		P05K B 10;
		Goto See;
		
	Pain.Avoid:
		TNT1 A 0;
		TNT1 A 0;//A_Jump(255, "AvoidLeft", "AvoidRight")
		Goto Fallback;
		
	AvoidLeft:
		POSS A 1 A_FaceTarget();
		TNT1 A 0 ThrustThing(angle*256/360+192, 15, 0, 0);
		5RO2 ABCDEFGH 3 A_FaceTarget();
		Goto Missile;
	AvoidRight:
		POSS A 1 A_FaceTarget();
		TNT1 A 0 ThrustThing(angle*256/360+64, 15, 0, 0);
		5RO1 ABCDEFGH 3 A_FaceTarget();
		Goto Missile;
		
		//If the monster is hit by the "Killme" damage(which is "exploded" by the captured marine), automatically start firing at the target.
	Pain.KillMe:
		TNT1 A 0;
	Goto Missile;
	//Emergency manuever in case the monster gets killed by an "alerter" actor	
	Death.KillMe:
	Death.Taunt:
	Death.Avoid:
		TNT1 A 0;
		//TNT1 A 0 {self.bSOLID", 0)
		TNT1 A 0 {self.bTHRUACTORS = true;}
		TNT1 A 0 A_ChangeCountFlags(false);
		TNT1 A 0 A_SpawnItemEx("pb_Helmet_ZombieMan",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION |SXF_TRANSFERSPECIAL| SXF_TRANSFERAMBUSHFLAG ,0);
	Stop;
		
	Pain:
		ZPV1 A 0 A_JumpIfInventory("IsDown", 1, 8);
		ZPV1 A 5;
		ZPV1 A 5 A_Pain();
		Goto see;
		TNT1 AAAA 0;
		TNT1 A 0 A_Pain();
		ID11 F 6;
		Goto GetUp;
		
	Pain.Melee:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("SKHelmetZombie1", 1, "StealthKill");
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, 8);
		ZPV1 A 3;
		ZPV1 A 3 A_Pain();
		Goto see;
		TNT1 AAAA 0;
		TNT1 A 0 A_Pain();
		ID11 FRRRQ 10;
		TNT1 A 0 A_TakeInventory("IsDown", 1);
		Goto see;
		
	StealthKill:
		TNT1 A 1;
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("SKHelmetZombie1", 1);
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Die("Stealthy");
		TNT1 A 0 A_Fall();
		TNT1 A 1;
		Stop;
		
	Death.cutless:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Death.Down");
		TNT1 A 0 A_Jump(16, "Death");
		TNT1 A 0 A_Jump(16, "Death.Cut");
		TNT1 A 0 A_Jump(24, "Death.Rare");
		
	Death.Tear:
		TNT1 AAA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		4P2X AA 8 a_spawnprojectile("Brutal_LiquidBlood", 30, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeath4", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("RipHelmetZombieman2", 0, 0, random(0, 360), 2, random(0, 160));
		PP2X BBCD 8 a_spawnprojectile("Brutal_LiquidBlood2", 30, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		PP2X EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 1 a_spawnprojectile("Brutal_LiquidBlood2", 15, 0, random(0, 360), 2, random(0, 90));
		PP2X E -1;
		Stop;
		
	Death.cut:
	Death.HKFT:
		TNT1 A 0;
		TNT1 AA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHalfHelmetZombieMan", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAA 0 a_spawnprojectile("Instestin2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_LiquidBlood", 30, 0, random(0, 360), 2, random(0, 40));
		POSX AABCDE 9 a_spawnprojectile("Brutal_LiquidBlood", 30, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		POSX EEEEEEEEEEEEEEEEEEEEEE 1 a_spawnprojectile("Brutal_LiquidBlood", 12, 0, random(0, 360), 2, random(0, 90));
		TNT1 A 0 A_PlaySound("BODYF",6);
		POSX E -1;
	Stop;
		
	Death.Rare:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		Z6Z8 A 5 A_Scream();
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 24, 5, -20, 2, -20);
		Z6Z8 B 5 BRIGHT;
		Z6Z8 CD 5;
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 24, -5, 20, 2, 30);
		Z6Z8 E 5 BRIGHT;
		TNT1 A 0 A_NoBlocking();
		Z6Z8 FGHI 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		Z6Z8 I -1;
	Stop;
}

}

CLASS ZombieMarineDude: pb_Zombie_Man// Replaces ZombieMan
{ 
Default {
	Health 44;
	Speed 7;
	Scale 1.0;
	Radius 16;
	pb_monster_base.weapon_type 'carbide';
}

States
{

	Spawn:
		UDM2 AB 10 {A_Look();}
		TNT1 A 0 A_Jump(10, "WalkAround");
	Stand:
		UDM2 AB 10 {A_Look();}
	loop;
		
	WalkAround:
		TNT1 A 0 {A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0); }
		UDM2 A 2 A_Look();
		UDM2 A 2 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		
		UDM2 B 2 A_Look();
		UDM2 B 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",3);
		
		UDM2 D 2 A_Look();
		UDM2 D 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",4);
		
		UDM2 C 2 A_Look();
		UDM2 C 2 A_Wander();
		
		UDM2 D 2 A_Look();
		UDM2 D 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",4);
		
		UDM2 B 2 A_Look();
		UDM2 B 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",4);
		TNT1 A 0 A_Jump(10, "Spawn");
		Loop;
		
	See:
		TNT1 A 0 {A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0); }
		UDM2 AA 2 A_Chase();
		TNT1 A 0 A_Recoil(-1);
		UDM2 BB 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
		UDM2 DD 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",4);
		UDM2 CCDD 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",4);
		UDM2 BB 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",4);
	Loop;
		
		//////////////////////////
		///////////////////////////////////////////

	WalkAround:
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		UDM2 A 2 A_Look();
		UDM2 A 2 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		UDM2 B 2 A_Look();
		UDM2 B 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",3);
		
		UDM2 D 2 A_Look();
		UDM2 D 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",4);
		
		UDM2 C 2 A_Look();
		UDM2 C 2 A_Wander();
		
		UDM2 D 2 A_Look();
		UDM2 D 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",4);
		
		UDM2 B 2 A_Look();
		UDM2 B 2 A_Wander();
		TNT1 A 0 A_PlaySound("humans/step",4);
		TNT1 A 0 A_Jump(32, "Stand");
		Loop;
		
		
	SearchForPlayer:
	Idle:
		TNT1 A 0 A_JumpIfHealthLower(1, "Death");
		TNT1 A 0 A_ClearTarget();
		TNT1 A 0 A_TakeInventory("EnemyMemory", 30);
		UDM2 A 10 A_Look();
		UDM2 B 10 A_Look();
		TNT1 A 0 A_SetAngle(angle - 40);
		UDM2 A 10 A_Look();
		UDM2 C 10 A_Look();
		TNT1 A 0 A_SetAngle(angle + 40);
		UDM2 A 10 A_Look();
		UDM2 D 10 A_Look();
		TNT1 A 0 A_SetAngle(angle + 40);
		UDM2 A 10 A_Look();
		
		UDM2 A 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		UDM2 B 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		UDM2 C 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		UDM2 D 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		
		TNT1 A 0 A_Jump(128, "Idle");
		UDM2 A 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		UDM2 B 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		UDM2 C 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		UDM2 D 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		Loop;
		
	Stand2:
		UDM2 B 1 A_Look();
	Goto Spawn;
		
		
	FallBack:
		TNT1 A 0 A_CheckSight("Advance");
		TNT1 A 0 {self.bNODROPOFF = true;}
		UDM2 D 2 A_FaceTarget();
		UDM2 D 2 A_Recoil(2);
		TNT1 A 0 A_jump(64, "Missile");
		UDM2 C 2 A_FaceTarget();
		UDM2 C 2 A_Recoil(2);
		UDM2 B 2 A_FaceTarget();
		UDM2 B 2 A_Recoil(2);
		UDM2 A 2 A_FaceTarget();
		UDM2 A 2 A_Recoil(2);
		UDM2 D 2 A_FaceTarget();
		UDM2 D 2 A_Recoil(2);
		TNT1 A 0 A_jump(64, "Missile");
		UDM2 C 2 A_FaceTarget();
		UDM2 C 2 A_Recoil(2);
		UDM2 B 2 A_FaceTarget();
		UDM2 B 2 A_Recoil(2);
		UDM2 A 2 A_FaceTarget();
		UDM2 A 2 A_Recoil(2);
		GOto Missile;

	SeeContinue:
		TNT1 A 0 {self.bSOLID = true;}
		TNT1 A 0 {self.bSHOOTABLE = true;}
		TNT1 A 0 {self.bGHOST = false;}
		TNT1 A 0 {self.bINVULNERABLE = false;}
		TNT1 A 0 A_JumpIfCloser(200, "FallBack");
	Advance:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		TNT1 A 0 A_JumpIfInventory("EnemyMemory", 15, "SearchForPlayer");
		TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
		UDM2 AA 2 A_Chase();
		TNT1 A 0 A_Recoil(-1);
		UDM2 BB 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
		UDM2 CCDD 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
	Loop;
		
	SeeNeverSeen:
		TNT1 A 0 A_JumpIfCloser(200, "FallBack");
	Advance:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		UDM2 AA 2 A_Chase();
		TNT1 A 0 A_Recoil(-1);
		UDM2 BB 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
		UDM2 CC 2 A_Chase();
		UDM2 DD 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
	Loop;

	Missile:
		TNT1 A 0 A_JumpIfInventory("Enraged", 1, "SpecialAttack");
		TNT1 A 0 A_Jump(48,"SpecialAttack");
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", 1);
		UDM2 E 5 A_FaceTarget();
		UDM2 E 5 A_FaceTarget();
		UDM2 E 5 A_FaceTarget();
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		UDM2 E 3 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 0, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		UDM2 E 3 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 0, random(-3, 3));
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		UDM2 E 3 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 0, random(-3, 3));
		UDM2 E 3 A_FaceTarget();
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		UDM2 E 5 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 0, random(-3, 3));
		UDM2 E 3 A_FaceTarget();
		TNT1 A 0 A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
	Goto See;
		
	SpecialAttack:
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", 5);
		UDM2 E 5 A_FaceTarget();
		UDM2 E 5 A_FaceTarget();
		UDM2 E 5 A_FaceTarget();
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		UDM2 E 3 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-8, 8), 0, random(-3, 3));
		UDM2 E 1 A_FaceTarget();
		UDM2 E 2 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		UDM2 E 3 BRIGHT a_spawnprojectile("ZombieManTracer", 38, 0, random(-8, 8), 0, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		UDM2 E 2 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		UDM2 E 3 BRIGHT a_spawnprojectile("ZombieManTracer", random(30, 42), 0, random(-9, 9), 0, random(-4, 6));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		UDM2 E 2 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		UDM2 E 2 BRIGHT a_spawnprojectile("ZombieManTracer", 38, 0, random(-10, 10), 0, random(-3, 3));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		UDM2 E 5 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		UDM2 E 3 BRIGHT a_spawnprojectile("ZombieManTracer", random(30, 42), 0, random(-9, 9), 0, random(-4, 6));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		UDM2 E 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 A_PlaySound("Weapons/Rifle/SFire");
		UDM2 E 3 BRIGHT a_spawnprojectile("ZombieManTracer", random(30, 42), 0, random(-9, 9), 0, random(-4, 6));
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		UDM2 E 2;
		UDM2 E 3 A_FaceTarget();
		TNT1 A 0 A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
	Goto See;
		
		
	Reload:
		TNT1 A 0 A_TakeInventory("ZombieManAmmo", 20);
		UDM2 E 1;
		MID1 B 2;
		MID1 A 1;
		MID1 D 1;
		MID1 C 10 A_PlaySound("RIFLC_OUT");
		MID1 B 4 a_spawnprojectile("EmptyClipSpawn", 38, 0, random(-11, 11), 0);
		MID1 A 10;
		MID1 B 4;
		MID1 C 5;
		MID1 D 10 A_PlaySound("RIFLC_IN");
		UDM2 A 10 A_PlaySound("CLIPIN", 1);
	Goto See;
		
		
	Pain:
	Pain.Melee:
		UDM2 G 5;
		UDM2 G 3 A_Pain();
	goto See;
		
	Pain.Taunt:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("Enraged", 1, "SpecialAttack");
		UDM2 B 0 A_Pain();
		TNT1 A 0 {self.bMISSILEMORE = true;}
		TNT1 A 0 {self.bMISSILEEVENMORE = true;}
		TNT1 A 0 A_PlaySound("grunt/sight");
		UDM2 B 1 A_FaceTarget();
		UDM2 B 10;
		TNT1 A 0 A_GiveInventory("Enraged", 1);
		TNT1 A 0 A_PlaySound("grunt/sight", 1);
		Goto SpecialAttack;
		
	Pain.Kick:
	Pain.extremepunches:
	Pain.ExplosiveImpact:
		TNT1 A 0;
		MID2 A 1 A_Pain();
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain");
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		MID2 A 1 A_facetarget();
		MID2 A 6 ThrustThing(angle*256/360+128, 10, 0, 0);
		MID2 A 8;
	Goto FallingAfterImpact;
		
	FallingAfterImpact:
		TNT1 A 0 A_PlaySound("BODYF",6);
		MID2 A 1 A_GiveInventory("FallingHeight", 1);
		MID2 A 1 A_CheckFloor("GetUp");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_JumpIf(vel.z == 0, "GetUp");
	Loop;
		
	GetUp:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 5, "FallingDie");
		TNT1 A 0 A_TakeInventory("FallingHeight", 100);
		MID2 BBBBBBB 5 A_JumpIf(vel.z < 0, "FallingAfterImpact");
		TNT1 A 0 A_TakeInventory("IsDown", 1);
		UDM2 A 10;
	Goto See;
		
	FallingDie:
		TNT1 A 0;
		TNT1 A 0 A_ChangeCountFlags(false);
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 A_SpawnItem("SplatteredSmall");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 15, "Death.Stomp");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 10, "FallingSuperDeath");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 5, "FallingDeath");
	FallingDeath:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBLocking();
		TNT1 A 0 ;//A_SpawnItem("Ploft");
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(50, 130));
		MID2 AA 2;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("PB_pot");
		MID2 A -1;
		Stop;
		
	FallingSuperDeath:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBLocking();
		TNT1 A 0 A_SpawnItem("PB_pot");
		TNT1 AAA 0 ;//A_SpawnItem("Ploft");
		Goto Death.ExplosiveImpact+1;
		
	Death:
		TNT1 A 0 A_Jump(96, "Death.Arm");
		UDM2 H 3  {pb_blood_and_gore_event.much_blood(self);}
		UDM2 I 3 A_Scream();
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		UDM2 J 3 A_Fall();
		TNT1 A 0 A_SpawnItem("PB_pot");
		UDM2 KLM 3;
		UDM2 N -1;
		Stop;
		
	Death.Shotgun:
		TNT1 A 0 A_JumpIfCloser(300, "Death.ShotgunBlasted");
		Goto Death;
		
	Death.ShotgunBlasted:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 {self.bSLIDESONWALLS = true;}
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(10);
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		U4M3 ABCDEFG 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		U4M3 GGGGG 2;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_Jump(64, "ItsATwitcher");
		U4M3 GGGGG -1;
		Stop;
		
		
		
	ItsATwitcher:
		U4M3 EE 8;
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TNT1 AAA 0 A_SpawnItem("Blood", 5);
		U4M3 FF 8;
		
		U4M3 EE 8;
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TNT1 AAA 0 A_SpawnItem("Blood", 5);
		U4M3 FF 8;
		
		U4M3 EE 8;
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TNT1 AAA 0 A_SpawnItem("Blood", 5);
		U4M3 FF 8;
		
		U4M3 EE 8;
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		TNT1 AAA 0 A_SpawnItem("Blood", 5);
		U4M3 FF 8;
		
		U4M3 G -1;
	stop;
		
	Death.Fatality:
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("UndeadMarineFatality1",1);
		stop;
		
	XDeath:
		UDM2 O 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		UDM2 O 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		UDM2 O 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
		UDM2 O 0 a_spawnprojectile("XDeathZombieLeg", 32, 0, random(0, 360), 2, random(0, 160));
		UDM2 O 0 a_spawnprojectile("XDeathZombieLeg", 32, 0, random(0, 360), 2, random(0, 160));
		UDM2 O 5;
		UDM2 O 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		UDM2 P 5 A_XScream();
		UDM2 P 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
		UDM2 Q 5 A_Fall();
		UDM2 Q 0 a_spawnprojectile("XDeath2", 40, 0, random(0, 360), 2, random(0, 160));
		UDM2 RSTU 5;
		UDM2 V -1;
		Stop;
	Raise:
		UDM2 NMLKJIH 5;
		Goto See;
		
	Death.Head:
		//TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		//TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
		//TNT1 A 0 A_JumpIfInTargetInventory("HasCutingWeapon", 1, "Death.Decaptate");
		TNT1 A 0 A_JumpIfHealthLower(-200, "HeavyHead");
		TNT1 A 0 A_JumpIfHealthLower(-50, "Death.HeadExplode");
		////TNT1 A 0 A_JumpIfInTargetInventory("RandomHeadExploder", 1, "HeadExploder");
	Death.HeadMinor:
		TNT1 AAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail8", 50, 0, random(0, 360), 2, random(0, 360));
		TNT1 AA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		U5M4 A 4 A_Scream();
		U5M4 B 4;
		U5M4 C 5 A_NoBlocking();
		U5M4 D 4;
		TNT1 A 0 A_PlaySound("BODYF",6);
		U5M4 E 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		U5M4 E -1;
	Stop;
		
	Death.LegMassacre:
		TNT1 A 0;
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		//TNT1 A 0 A_SpawnItem("ZombieLegOnFoot");
		U4M5 A 1 A_Scream();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("BrutalizedZombieMarineLeg");
	Stop;
		
	Death.Arm:
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		U4M6 A 10 A_Scream();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("DyingZombieMarineNoArm");
	Stop;
		
	Death.Leg:
		TNT1 A 0;
		//TNT1 A 0 A_Jump(64, "DeathLeg2")
		TNT1 A 0;
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 a_spawnprojectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathZombieLeg", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("ZombieMarineGotHisLegBlowed");
	Stop;
}

} 