CLASS pb_ZSpecOps_Machinegun : private_base// Replaces ShotgunGuy
{ 
//	SpawnID 1240;
Default
{
	Health 85;
	Radius 16;
	Speed 12;
	Mass 100;
	Scale 1.01;

	PainChance 200;
	PainChance "Avoid", 50;
	PainChance "Head", 255;
	PainChance "Kick", 255;
	PainChance "ExtremePunches", 255;
	PainChance "Melee", 255;
	PainChance "HelperMarineFatality", 255;
	PainChance "MonsterKnocked", 255;
	PainChance "ExplosiveImpact", 255;
	PainChance "Taunt", 255;
	
	DamageFactor "Fatality", 0.5;
	DamageFactor "SuperPunch", 0.5;
	damagefactor "Crush", 5.0;
	damagefactor "Avoid", 1.0;
	damagefactor "DontCallTheBaron", 0.0;
	damagefactor "TeleportRemover", 0.0;
	damagefactor "GibRemoving", 0.0;
	damagefactor "SSG", 50.0;
	damagefactor "killme", 0.0;
	DamageFactor "Blood", 0.0; DamageFactor "BlueBlood", 0.0; DamageFactor "GreenBlood", 0.0;
	DamageFactor "Shrapnel", 0.3;
	DamageFactor "Kick", 0.4;
	DamageFactor "MinorHead", 2.0;
	DamageFactor "Head", 2.0;
	DamageFactor "taunt", 0.0;

	BloodType "pb_blood";
	SeeSound "ZSpecOps/Sight";
	ActiveSound "ZSpecOps/Sight";
	PainSound "ZSpecOps/Pain";
	DeathSound "ZSpecOps/Death";
	Obituary "%o was gunned down by a ZSpecOps";
	
	pb_monster_base.weapon_type 'sof_smg';

//	Decal "BulletChip";

//	//DropItem "DropedSMG";
//	//DropItem "BulletCartridge";
}

States
{
	Spawn:
		TNT1 A 0;
 		TNT1 A 0 {ammo_amount = random(0, max_magazine_size);}//A_GiveInventory("ZombieManAmmo", random(1,12));
		ZSP2 B 1;
	Stand:
		ZSP2 BB 10 A_Look();
	Loop;

	See:
		TNT1 A 0 {self.bNODROPOFF = false;}
		//TNT1 A 0 A_TakeInventory("SKQuadShotgunZombie", 1);
		TNT1 A 0 A_TakeInventory("EnemyMemory", 15);
		TNT1 A 0 A_CheckSight("SeeNeverSeen");	
	SeeContinue:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_JumpIfCloser(200, "FallBack");
		//Advance:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_JumpIfInventory("EnemyMemory", 15, "SearchForPlayer");
		TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 20, 0, 0);
		////TNT1 A 0 A_TakeInventory("SKShotgunGuy", 1);
		ZSP2 AAAA 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
		ZSP2 BBBBCCCC 2 A_Chase();
		TNT1 A 0 A_PlaySound("humans/step",3);
		ZSP2 DDDD 2 A_Chase();
	Loop;














	FallBack:
		TNT1 A 0 A_CheckSight("Advance");
		TNT1 A 0 {self.bNODROPOFF = true;}
		ZSP2 D 2 A_FaceTarget();
		ZSP2 D 2 A_Recoil(2);
		TNT1 A 0 A_jump(64, "Missile");
		ZSP2 C 2 A_FaceTarget();
		ZSP2 C 2 A_Recoil(2);
		ZSP2 B 2 A_FaceTarget();
		ZSP2 B 2 A_Recoil(2);
		ZSP2 A 2 A_FaceTarget();
		ZSP2 A 2 A_Recoil(2);
		ZSP2 D 2 A_FaceTarget();
		ZSP2 D 2 A_Recoil(2);
		TNT1 A 0 A_jump(64, "Missile");
		ZSP2 C 2 A_FaceTarget();
		ZSP2 C 2 A_Recoil(2);
		ZSP2 B 2 A_FaceTarget();
		ZSP2 B 2 A_Recoil(2);
		ZSP2 A 2 A_FaceTarget();
		ZSP2 A 2 A_Recoil(2);
		TNT1 A 0 {self.bNODROPOFF = false;}
	GOto Missile;
		
	SearchForPlayer:
	Idle:
		TNT1 A 0 A_ClearTarget();
		TNT1 A 0 A_TakeInventory("EnemyMemory", 30);
		//TNT1 A 0 A_GiveInventory("SKShotgunGUy", 1);
		ZSP2 ACADA 10 A_Look();
		ZSP2 A 4 A_Look();
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		ZSP2 B 4 A_Look();
		
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		ZSP2 C 4 A_Look();
		
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		ZSP2 D 4 A_Look();
		
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		
		TNT1 A 0 A_Jump(128, "Idle");
		ZSP2 A 4 A_Look();
		
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		ZSP2 B 4 A_Look();
		
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		ZSP2 C 4 A_Look();
		
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
		ZSP2 D 4 A_Look();
		
		TNT1 A 0 A_Wander();
		TNT1 A 0 A_Recoil(-1);
	Loop;
		
	SeeNeverSeen:
		TNT1 A 0 A_JumpIfCloser(200, "FallBack");
	Advance:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0);
		ZSP2 AA 2 A_Chase();
		TNT1 A 0 A_Recoil(-1);
		//TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		ZSP2 BBCCDD 2 A_Chase();
	Loop;
		
	Missile:
		////TNT1 A 0 A_TakeInventory("SKZSpecOps", 1);
		TNT1 A 0 A_Jump(8,"Pain.Avoid");
		TNT1 A 0 A_Jump(256,"HipFire1", "HipFire2", "CrouchFire", "ADSFire");
	HipFire1:
		TNT1 A 0 {ammo_amount -= 2;}//A_GiveInventory("ZombieManAmmo", 2);
		ZSP2 A 5 A_FaceTarget();
		ZSP2 B 2 A_FaceTarget();
		ZSP2 E 2 A_FaceTarget();
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		ZSP2 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-15, 15), 0, random(-8, 8));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 E 2 A_FaceTarget();
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		ZSP2 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-15, 15), 0, random(-8, 8));
		ZSP2 E 2 A_FaceTarget();
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		ZSP2 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-15, 15), 0, random(-8, 8));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 E 2 A_FaceTarget();
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		ZSP2 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-15, 15), 0, random(-8, 8));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 E 1;
		ZSP2 B 2;
		ZSP2 A 5 A_FaceTarget();
		TNT1 A 0 pb_check_reloading("reload");//A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
		TNT1 A 0 A_Jump(18, "HipFire2", "CrouchFire", "ADSFire");
		TNT1 A 0 A_Jump(10,"Pain.Avoid");
	Goto See;
		
	HipFire2:
		TNT1 A 0 {ammo_amount -= 3;}//A_GiveInventory("ZombieManAmmo", 3);
		ZSP2 A 5 A_FaceTarget();
		ZSP2 B 2 A_FaceTarget();
		ZSP2 E 3 A_FaceTarget();
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 34, 10, 15, 0);
		ZSP2 F 3 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-15, 15), 0, random(-8, 8));
		ZSP2 E 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 32, 0, random(-15, 15), 0, random(-8, 8));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 E 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 34, 0, random(-9, 9), 0, random(-4, 6));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 E 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 38, 0, random(-18, 18), 0, random(-9,9));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 E 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 38, 0, random(-10, 10), 0, random(-3, 3));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 E 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 34, 0, random(-9, 9), 0, random(-4, 6));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 E 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", 38, 0, random(-10, 10), 0, random(-3, 3));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 E 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 34, 10, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 F 2 BRIGHT a_spawnprojectile("ZombieManTracer", random(30, 42), 0, random(-9, 9), 0, random(-4, 6));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 E 2;
		ZSP2 B 2;
		ZSP2 A 5 A_FaceTarget();
		TNT1 A 0 pb_check_reloading("reload");//A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
		TNT1 A 0 A_Jump(12, "CrouchFire", "ADSFire");
		TNT1 A 0 A_Jump(8,"Pain.Avoid");
		Goto See;
		
	CrouchFire:
		TNT1 A 0 {ammo_amount -= 3;}//A_GiveInventory("ZombieManAmmo", 3);
		ZSP2 M 8 A_FaceTarget();
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 30, 10, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 30, 10, 15, 0);
		ZSP2 M 2 BRIGHT a_spawnprojectile("ZombieManTracer", 30, 0, random(-15, 15), 0, random(-8, 8));
		ZSP2 M 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 30, 10, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 M 2 BRIGHT a_spawnprojectile("ZombieManTracer", 30, 0, random(-15, 15), 0, random(-8, 8));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 M 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 30, 10, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 M 2 BRIGHT a_spawnprojectile("ZombieManTracer", 30, 0, random(-9, 9), 0, random(-4, 6));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 M 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 30, 10, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 M 2 BRIGHT a_spawnprojectile("ZombieManTracer", 30, 0, random(-18, 18), 0, random(-9,9));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 M 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 30, 10, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 M 2 BRIGHT a_spawnprojectile("ZombieManTracer", 30, 0, random(-10, 10), 0, random(-3, 3));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 M 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 30, 10, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 M 2 BRIGHT a_spawnprojectile("ZombieManTracer", random(30, 42), 0, random(-9, 9), 0, random(-4, 6));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 M 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 30, 10, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 M 2 BRIGHT a_spawnprojectile("ZombieManTracer", 30, 0, random(-10, 10), 0, random(-3, 3));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 M 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 30, 10, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 M 2 BRIGHT a_spawnprojectile("ZombieManTracer", 30, 0, random(-9, 9), 0, random(-4, 6));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 M 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 30, 10, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 M 2 BRIGHT a_spawnprojectile("ZombieManTracer", 30, 0, random(-9, 9), 0, random(-4, 6));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 M 3 A_FaceTarget();
		ZSP2 E 2;
		TNT1 A 0 A_Jump(12, "Hipfire1", "Hipfire2","ADSFire");
		TNT1 A 0 A_Jump(8,"Pain.Avoid");
	Goto See;
		
	ADSFire:
		TNT1 A 0 {ammo_amount == 2;}//A_GiveInventory("ZombieManAmmo", 2);
		ZSP2 N 8 A_FaceTarget();
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 38, 11, 15, 0);
		TNT1 A 0 a_spawnprojectile("GunFireSmoke", 38, 11, 15, 0);
		ZSP2 N 2 BRIGHT a_spawnprojectile("ZombieManTracer", 37, 0, random(-15, 15), 0, random(-8, 8));
		ZSP2 N 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 38, 11, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 N 2 BRIGHT a_spawnprojectile("ZombieManTracer", 37, 0, random(-15, 15), 0, random(-8, 8));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 N 2 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 38, 11, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 N 2 BRIGHT a_spawnprojectile("ZombieManTracer", random(30, 42), 0, random(-9, 9), 0, random(-4, 6));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 N 3 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 38, 11, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 N 2 BRIGHT a_spawnprojectile("ZombieManTracer", 38, 0, random(-18, 18), 0, random(-9,9));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 N 2 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 38, 11, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 N 2 BRIGHT a_spawnprojectile("ZombieManTracer", 38, 0, random(-10, 10), 0, random(-3, 3));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 N 2 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 38, 11, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 N 2 BRIGHT a_spawnprojectile("ZombieManTracer", random(30, 42), 0, random(-9, 9), 0, random(-4, 6));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 N 2 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 38, 11, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 N 2 BRIGHT a_spawnprojectile("ZombieManTracer", 38, 0, random(-10, 10), 0, random(-3, 3));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 N 2 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 38, 11, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 N 2 BRIGHT a_spawnprojectile("ZombieManTracer", random(30, 42), 0, random(-9, 9), 0, random(-4, 6));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 N 2 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("OrangeLensFlareAlt", 38, 11, 15, 0);
		TNT1 A 0 A_PlaySound("ZSpecOps/MGun");
		ZSP2 N 2 BRIGHT a_spawnprojectile("ZombieManTracer", random(30, 42), 0, random(-9, 9), 0, random(-4, 6));
		TNT1 A 0 A_SpawnItem("Mp40CaseSpawn", 0, 30,0);
		ZSP2 N 3 A_FaceTarget();
		ZSP2 E 2;
		TNT1 A 0 pb_check_reloading("reload");//A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
		TNT1 A 0 A_Jump(12, "Hipfire1", "Hipfire2","Crouchfire");
		TNT1 A 0 A_Jump(8,"Pain.Avoid");
	Goto See;
		
	Reload:
		TNT1 A 0 {ammo_amount = max_magazine_size;}//A_TakeInventory("ZombieManAmmo", 20);
		ZSP2 E 3;
		ZSP2 E 1 a_spawnprojectile("EmptyClipSpawn", 38, 0, random(-11, 11), 0);
		TNT1 A 0 A_PlaySound("Reload");
		ZSP6 A 8;
		ZSP6 B 8;
		ZSP6 C 8;
		TNT1 A 0 A_PlaySound("CLIPIN");
		ZSP6 D 8;
		ZSP2 A 8;
	Goto SeeContinue;
		
	Pain.Avoid:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("SlideKick/Start", 1);
		TNT1 A 0 A_Jump(255, "AvoidLeft", "AvoidRight");
	Goto AvoidLeft;
		
	AvoidLeft:
		ZSP2 A 1 A_FaceTarget();
		TNT1 A 0 ThrustThing(angle*256/360+192, 12, 0, 0);
		ZP04 ABCDEFGH 2 A_FaceTarget();
	Goto Missile;
	AvoidRight:
		ZSP2 A 1 A_FaceTarget();
		TNT1 A 0 ThrustThing(angle*256/360+64, 12, 0, 0);
		ZP03 ABCDEFGH 2 A_FaceTarget();
		Goto Missile;
		
		//Misc hurting states
	Pain.Melee:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfInventory("SKZSpecOps", 1, "StealthKill");
	Pain:
		ZSP2 G 4;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		ZSP2 G 4 A_Pain();
		ZSP2 G 0 A_Jump(96, "See");
		Goto see;
		
	Possession:
		TNT1 A 0 A_SetInvulnerable();
		ZSP2 G 3;
		ZSP2 G 3 A_Pain();
 		TNT1 A 0 A_UnSetInvulnerable();
	Goto See;
		
		
	pain.ExplosiveImpact:
	Pain.Explosive:
		TNT1 A 0;
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain");
		////TNT1 A 0 A_TakeInventory("SKZSpecOps", 1);
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,44,0,1);
		ZID9 A 7;
		ZID9 B 6;
	Goto FallingAfterImpact;
		
		
	Pain.Kick:
	Pain.ExtremePunches:
		TNT1 A 0;
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain");
		ZSP2 G 1 A_Pain();
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		//TNT1 A 0 A_TakeInventory("SKShotgunGuy", 1);
		TNT1 A 0 ThrustThingZ(0,35,0,1);
		TNT1 A 0 {self.bNOPAIN = true;}
		//ID11 E 1 A_Chase("","")
		ZID9 A 1 A_facetarget();
		ZID9 A 3 ThrustThing(angle*256/360+128, 13, 0, 0);
		ZID9 ABBCC 3;
		TNT1 A 0 {self.bNOPAIN = false;}
		Goto FallingAfterImpact;
		
	FallingAfterImpact:
		ZID9 C 1 A_GiveInventory("FallingHeight", 1);
		ZID9 C 1 A_CheckFloor("GetUp");
		tnt1 a 0 A_JumpIf(vel.z == 0, "GetUp");
		Loop;
		
	GetUp:
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 A_SpawnItem("LargeMassWaterImpact");
		TNT1 A 0 {self.bFORCEXYBILLBOARD = true;}
		TNT1 A 0 {self.bNOPAIN = false;}
		TNT1 A 0 {self.bSOLID = false;}
		//TNT1 A 0 {self.bGHOST", 1)
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 4, "FallingDie");
		ZID9 DDDDDDD 5 A_JumpIf(vel.z < 0, "FallingAfterImpact");
		TNT1 A 0 A_TakeInventory("FallingHeight", 100);
		
		ZID9 E 10;
		TNT1 A 0 {self.bFORCEXYBILLBOARD = false;}
		TNT1 A 0 A_TakeInventory("IsDown", 1);
		TNT1 A 0 {self.bSOLID = true;}
		Goto See;
		
	FallingDie:
		TNT1 A 0;
		TNT1 A 0 A_ChangeCountFlags(false);
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 A_SpawnItem("SplatteredSmall");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 15, "Death.Stomp");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 10, "FallingSuperDeath");
		TNT1 A 0 A_JumpIfInventory("FallingHeight", 5, "FallingDeath");
	FallingDeath:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBLocking();
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(50, 130));
		ZID9 C 2;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		ZSP2 L -1;
		Stop;
		
	FallingSuperDeath:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBLocking();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		Goto Death.ExplosiveImpact+1;
		
	Death.Nailgun:
		TNT1 A 0 A_Jump(100, "Death.Blast");
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 {self.bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(6);
		ZSP3 I 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		ZSP3 I 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		ZSP3 G 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "PinToWall");
		ZSP3 J 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		ZSP3 J 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		ZSP3 K 5 a_spawnprojectile("Brutal_LiquidBlood3", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		ZSP2 L -1;
		Stop;
	PinToWall:
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AA 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_PlaySound("Weapons/NailHitBleed", 6);
		P1N2 A 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItemEx("DeadZSPEC_Pinned", 10, 0, 10);
		Stop;
		
	Pain.KillMe:
		TNT1 A 0;
		Goto Missile;
	Death.KillMe:
	Death.Taunt:
		TNT1 A 0 {self.bTHRUACTORS = true;}
		TNT1 A 0 A_ChangeCountFlags(false);
		TNT1 A 0 A_SpawnItemEx("pb_ZSpecOps_Machinegun",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION |SXF_TRANSFERSPECIAL| SXF_TRANSFERAMBUSHFLAG ,0);
		Stop;
		
	Death.Shotgun:
		TNT1 A 0 A_JumpIfCloser(165, "Death.Blast");
		TNT1 A 0 A_JumpIfCloser(300, "Death.Shotgunontheface");
		Goto Death;
		
	Death.Shotgunontheface:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 A_Jump(48, "Death.ARm");
		TNT1 A 0 A_Jump(92, "Death.Kick");
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_Pain();
		ZSP2 H 1 A_FaceTarget();
		TNT1 A 0 A_Recoil(13);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		TNT1 A 0 A_Scream();
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AA 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		ZSP4 ABCD 4;
		ZSP4 EFGHIJ 4 A_JumpIf((vel.Y == 0), "DSFStop");
		Goto DSFStop+1;
		
	DSFStop:
		//TNT1 A 0 A_Explode(20,30, 0);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 a_spawnprojectile("SuperWallRedBlood", 2, 0, random(170, 190), 2, random(0, 0));
		TNT1 A 0 A_PlaySound("BODYF",6);
		ZSP4 J -1;
		Stop;
		
	Death.Eat:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Scream();
		//TNT1 A 0 A_GiveToTarget("SergeantFatality",1);
	Stop;
		
	Death.ShotgunonthefaceArm:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "Death.Arm");
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		ID11 OP 15;
		//TNT1 A 0 A_SpawnItem("DeadShotgunGuy_NoArm");
	Stop;
		
	Death.Down:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		ZSP2 L -1;
		Stop;
		
	Death.MinorLeg:
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZLeg1", 35, 0, random(0, 360), 2, random(0, 160));
		ZPO3 A 5 A_Scream();
		ZPO3 B 5 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		ZPO3 C 5 A_NoBlocking();
		ZPO3 D 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		QPO3 F -1;
		Stop;
	Death.Melee:
		FID2 A 5 A_Scream();
		FID2 B 5;
		FID2 C 5 A_NoBlocking();
		FID2 D 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem("DeadShotgunguy1MeleeDeath", 1);
		Stop;
		
	Death.Leg:
	Death.Crush:
		TNT1 A 0 A_Jump(132, "LeaveCrawling");
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZLeg1", 35, 0, random(0, 360), 2, random(0, 160));
		ZPO3 A 9 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_Playsound("grunt/death");
		ZPO3 B 3;
		ZPO3 C 3 A_NoBlocking();
		TNT1 A 0 A_PlaySound("BODYF",6);
		QPO3 F -1;
		Stop;
		
	LeaveCrawling:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("DyingZSPECLegBlewedOff", 2);
		TNT1 A 0;
		Stop;
		
	Death.Arm:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile("XDeathArm2", 35, 0, random(0, 360), 2, random(0, 160));
		ZPO5 A 9 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DyingZSPEC", 2);
		Stop;
		
	Death.Head:
		TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
		TNT1 A 0 A_JumpIfInTargetInventory("HasCutingWeapon", 1, "Death.Decaptate");
		TNT1 A 0 A_JumpIfHealthLower(-80, "Death.HeadExplode");
		//TNT1 A 0 A_JumpIfInTargetInventory("RandomHeadExploder", 1, "HeadExploder");
	Death.MinorHead:
		TNT1 A 0;
		TNT1 A 0 A_Playsound("MinorHeadshot", 0);
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_Jump(32, "Death.MinorHeadLong");
		TNT1 AAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail8", 50, 0, random(0, 360), 2, random(0, 360));
		TNT1 AA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		ZSP5 A 6 A_Scream();
		ZSP5 B 6 A_NoBlocking();
		ZSP5 DE 6;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		ZSP5 F -1;
		Stop;
		
	Death.MinorHeadLong:
		TNT1 AAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail8", 50, 0, random(0, 360), 2, random(0, 360));
		TNT1 AA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		ZSP5 A 6 A_Scream();
		ZSP5 B 6 A_NoBlocking();
		ZSP5 CBCBCB 18 A_Pain();
		ZSP5 DE 6;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		ZSP5 F -1;
		Stop;
		
	Death.headexplode:
	HeadExploder:
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode", 0, 50);
		TNT1 A 0 A_NoBlocking();
		QPDH AAAABBBBBBBBBBCCCCC 2 a_spawnprojectile("Brutal_LiquidBlood2", 30, 0, random(0, 360), 2, random(60, 120));
		QPDH DDDD 2 a_spawnprojectile("Brutal_LiquidBlood2", 10, 0, random(0, 360), 2, random(60, 120));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		////TNT1 A 0 A_SpawnItem("DeadHFQSZ_NoHead", 1);
		TNT1 A 0 A_PlaySound("BODYF",6);
		Stop;
		
	Death.decaptate:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 a_spawnprojectile("XDeathZSpecOpsHead", 5, 0, random(170, 190), 2, random(70, 90));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_XScream();
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_NoBlocking();
		QPDH AAABBBBBBBBBBBBBBCCCCC 2 a_spawnprojectile("Brutal_LiquidBlood2", 30, 0, random(0, 360), 2, random(60, 120));
		QPDH DDDD 2 a_spawnprojectile("Brutal_LiquidBlood2", 10, 0, random(0, 360), 2, random(60, 120));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem("DeadHFQSZ_NoHead", 1);
		TNT1 A 0 A_PlaySound("BODYF",6);
		Stop;
		
	Death.Cut:
	Death.HKFT:
		TNT1 A 0;
		TNT1 A 0 A_Jump(32, "Death.Arm", "Death");
		Goto Death.Tear;
		
	Death.cutless:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Death.Down");
		TNT1 A 0 A_Jump(16, "Death");
		TNT1 A 0 A_Jump(32, "Death.Cut");
		TNT1 A 0 A_Jump(16, "Death.LegMassacre");
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Scream();
		TNT1 O 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("BrutalizedHFQSZ2", 1);
	Stop;
		
	Death.Tear:
	Death.Saw:
		TNT1 AAAAAAAA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		ZP3X AAAAAAAA 2 a_spawnprojectile("Brutal_LiquidBlood2", 36, 0, random(0, 360), 2, random(10, 40));
		TNT1 A 0 a_spawnprojectile("XDeathHalfZSpecOPs", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		QP3X BBCD 8;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		//TNT1 A 0 A_SpawnItem("DeadHFQSZ_Half", 1);
		Stop;
		
		
	Death.LegMassacre:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Scream();
		TNT1 O 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("BrutalizedSergeantLeg", 1);
		Stop;
		
	Death.Blast:
	Death.Railgun:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Jump(138, "Death.Blast2");
		TNT1 A 0 A_Jump(128, "Death.Blast3");
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Scream();
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		Z2Z7 A 6 A_Stop();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		Z2Z7 BBBBBBBBBB 3 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(30, 60));
		Z2Z7 CCC 3 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(10, 40));
		TNT1 A 0 A_PlaySound("BODYF",6);
		Z2Z7 DD 3 a_spawnprojectile("Brutal_LiquidBlood2", 6, 0, random(0, 360), 2, random(30, 60));
		Z2Z7 E -1;
		Stop;
		
	Death.Blast2:
		TNT1 A 0 A_XScream();
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 42, 0, random(0, 360), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("Xdeath2", 16, 0, random(130, 210), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		ZSP5 G 6 A_Stop();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		ZSP5 HHHHHHHHHHHHHHHHH 3 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(30, 60));
		ZSP5 III 1 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(10, 40));
		TNT1 A 0 A_PlaySound("BODYF",6);
		ZSP5 JJ 3 a_spawnprojectile("Brutal_LiquidBlood2", 6, 0, random(0, 360), 2, random(30, 60));
		ZSP5 K -1;
		Stop;
		
	Death.Blast3:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Scream();
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		Z2Z9 A 6 A_Stop();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		Z2Z9 BBBBBBBBBB 3 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(30, 60));
		Z2Z9 CCC 3 a_spawnprojectile("Brutal_LiquidBlood2", 26, 0, random(0, 360), 2, random(10, 40));
		TNT1 A 0 A_PlaySound("BODYF",6);
		Z2Z9 DD 3 a_spawnprojectile("Brutal_LiquidBlood2", 6, 0, random(0, 360), 2, random(30, 60));
		Z2Z9 E -1;
		Stop;
		
	Death.SSG:
		QZD1 E 1 A_Pain();
		QZD1 E 1 A_FaceTarget();
		//TNT1 A 0 a_spawnprojectile("MeatDeath", 0, 0, random(0, 360), 2, random(0, 160))
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("XDeathHFQSZArm1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathZSpecOpsHead", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		QZD1 EEFFGH 6;
		TNT1 A 0 A_PlaySound("BODYF",6);
		//TNT1 A 0 A_SpawnItem("DeadHFQSZ_QZD1H");
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		Stop;
		
	
	
	Death.Fatality:
		TNT1 A 0;
		TNT1 A 0 A_Pain();
		//TNT1 A 0 A_JumpIfIntargetInventory("FistsSelected", 1, 1);
	Goto Death.ExplosiveImpact;
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_Jump(255, "Death.Fatality1");
		
	Death.Fatality1:
		//TNT1 A 0 A_GiveToTarget("ZSpecFatality", 1);
	Stop;
	
	Death.BHFT:
	Death.RVFT:
		TNT1 A 0;
		TNT1 A 1 A_Pain();
		//TNT1 A 0 A_GiveToTarget("SergeantFatality", 1);
		TNT1 A 0 A_NoBlocking();
		TNT1 A 1;
	Stop;
	Death.HelperMarineFatallity:
		TNT1 A 0;
		TNT1 A 1 A_Pain();
		TNT1 A 0 A_SpawnItem("Blood");
		TNT1 A 0 A_PlaySound("grunt/death");
		//TNT1 A 0 A_SpawnItem("DeadShotgunGuy", 1);
		TNT1 A 0 A_NoBlocking();
		TNT1 A 1;
	Stop;
	
	XDeath:
	Death.QuadBlast:
		//TNT1 A 0 A_JumpIfInTargetInventory("SSGSelected", 1, "Death.SSG");
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile("ZSpecOpsXDeath", 0, 0, random(0, 360), 2, random(0, 160));
	Stop;
	
	Death.Stomp:
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AAAAAA 0 bright a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright a_spawnprojectile("XDeath2", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright a_spawnprojectile("XDeath3", 55, 0, random(0, 360), 2, random(30, 180));
		//TNT1 A 0 A_SpawnItem("CrushedRemains");
		TNT1 A 1;
		TNT1 A 1 A_XScream();
		TNT1 A 1 A_NoBlocking();
	Stop;
	
	
	Death.ExplosiveImpact:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 1;
		TNT1 A 0 A_JumpIf(angle < 180, "IsFacingNorth");
		TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayRight");
		TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayLeft");
	Goto XDeath;
	IsFacingNorth:
		TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayRight");
		TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayLeft");
	Goto XDeath;
	
	BlownAwayLeft:
	TNT1 A 0;
	TNT1 A 0 A_Jump(96, "Death.LandMine");
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 {self.bNOBLOCKMONST = true;}
	TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
	TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathSargeLeg2", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(20, 90));
	TNT1 A 0 ThrustThingZ(0,30,0,1);
	TNT1 A 0 A_Xscream();
	Z2Z8 ABCDEFG 3 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, 0, 2, 90);
	TNT1 A 0 A_CheckFloor("Land8473");
	Z2Z8 ABCDEFGABCDEFG 5 A_CheckFloor("Land8473");
	Land8473:
	QPO5 N 0;
	TNT1 A 0 A_Stop();
	TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	Z2Z8 I 1;
	Z2Z8 I -1;
	Stop;
	
	BlownAwayRight:
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_Jump(96, "Death.ExtremePunches");
	TNT1 A 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 {self.bNOBLOCKMONST = true;}
	TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
	TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
	TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0 a_spawnprojectile("XDeathSargeLeg2", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(20, 90));
	TNT1 A 0 ThrustThingZ(0,30,0,1);
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_SpawnItemEx("BloodMist", 0, 0, 50, vel.x, vel.y, vel.z, 0, SXF_ABSOLUTEvelOCITY);
	Z2Z8 GFEDCBA 3 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, 0, 2, 90);
	TNT1 A 0 A_CheckFloor("Land8472");
	Z2Z8 GFEDCBAGFEDCBA 5 A_CheckFloor("Land8472");
	Land8472:
	SXS2 N 0;
	TNT1 A 0 A_Stop();
	TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	Z2Z8 H 1;
	Z2Z8 H -1;
	Stop;
	
	Death.ExtremePunches:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Jump(96,"Death.LandMine");
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZLeg2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		IQ14 AB 5;
		IQ14 CDEF 5 A_CheckFloor("Dead.ExplosiveImpact");
		IQ14 FFFFFF 5 A_CheckFloor("Dead.ExplosiveImpact");
		//TNT1 A 0 A_SpawnItem("VeryFuckedUpBrutalizedHFQSZLeg");
		TNT1 A 0 A_PlaySound("BODYF",6);
	Stop;
	
	Dead.ExplosiveImpact:
		//TNT1 A 0 A_SpawnItem("VeryFuckedUpBrutalizedHFQSZLeg");
		//TNT1 A 0 A_SpawnItem("Ploft");
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 A_PlaySound("BODYF",6);
	Stop;
	
	
	Death.LandMine:
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathHFQSZLeg1", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("GibHand", 42, 0, random(0, 360), 2, random(0, 160))
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		IQ16 A 1 A_Scream();
		IQ16 A 9;
		IQ16 BCD 9 A_CheckFloor("Dead.Landmine");
		IQ16 DDDD 9 A_CheckFloor("Dead.Landmine");
		TNT1 A 0 A_PlaySound("BODYF",6);
		////TNT1 A 0 A_SpawnItem("DeadHFQSZ_NoLeg", 1);
	Stop;
	
	Dead.Landmine:
		////TNT1 A 0 A_SpawnItem("DeadHFQSZ_NoLeg", 1);
		//TNT1 A 0 A_SpawnItem("Ploft");
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 A_PlaySound("BODYF",6);
	Stop;
	
	Raise:
		SPOS L 5;
		SPOS KJIH 5;
		Goto See;
		Crush:
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail8", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		POSC B 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		POSC B -1;
	Stop;
	
	StealthKill:
		TNT1 A 1;
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("SKZSpecOps", 1);
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Die("Stealthy");
		TNT1 A 0 A_Fall();
		TNT1 A 1;
	Stop;
	Death.Stealthy:
		TNT1 A 0;
	Stop;



	Death:
		TNT1 A 0 A_Jump(127, "Death2");
		TNT1 A 0 A_Jump(32, "Death.Arm");
		ZSP2 H 5;
		ZSP2 I 5 A_Scream();
		ZSP2 J 5;
		ZSP2 KL 5;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_PlaySound("BODYF",6);
		ZSP2 L -1;
	Stop;
	
	Death2:
		ZSP5 L 5;
		ZSP5 M 5 A_Scream();
		ZSP5 N 5;
		ZSP5 OP 5;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_PlaySound("BODYF",6);
		ZSP5 P -1;
	Stop;
	
	Raise:
		ZSP2 LKJIH 5;
	Goto See;
}

}