CLASS pb_spectro: pb_Bull_Demon// Replaces Spectre
{ 
Default
{
	GibHealth 35;
	//Radius 30
	Scale 1.1;
	Height 52;
	Radius 22;
	Mass 400;
	//SpawnID 1510;
	//  -FASTER
	damagefactor "Crush", 10.0;
	damagefactor "SSG", 5.0;
	damagefactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	PainChance "Kick", 255;
	damagefactor "TeleportRemover", 0.0;
	Monster;
	damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0; damagefactor "GreenBlood", 0.0;
	damagefactor "Shrapnel", 0.3;
	damagefactor "SSG", 5.0;
	+FLOORCLIP;
	SeeSound "demon/sight";
	AttackSound "demon/melee";
	PainSound "demon/pain";
	DeathSound "demon/death";
	ActiveSound "demon/active";
	BloodType "Brutal_Blood", "BloodSPlatterReplacer", "AxeBlood";
	DamageType "Eat";
	MaxStepHeight 48;
	MaxDropOffHeight 48;
	//DropItem "NewBlurSphere", 2;
	RenderStyle "Add";
	Alpha 0.45;
	Obituary "%o has been sodomized by a Spectre.";
	
	//DropItem "Demonpickup", 100;
}
States
{
	Spawn:
		SPEC A 10 BRIGHT A_Look();
	Loop;

	See:
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 30, 0, 0);
		SPEC AAABBBAAABBB 1 BRIGHT A_Chase();
		Loop;
	Pain:
		SARG H 2;
		SARG H 2 A_Pain();
		Goto See;
		
	Possession:
		TNT1 A 0 {self.bInvulnerable = true;}
		SARG H 3;
		SARG H 3 A_Pain();
 		TNT1 A 0 {self.bInvulnerable = false;}
		Goto See;
		
	Pain.Shotgun:
		TNT1 A 0 A_Pain();
		TNT1 A 0;
		//TNT1 A 0 ThrustThingZ(0,30,0,1)
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(2);
		SARG H 2;
		//DEMP A 4
		SARG H 2;
		Goto See;
		
	Pain.Kick:
	Pain.ExtremePunches:
		TNT1 A 0 A_Pain();
		TNT1 A 0;
		//TNT1 A 0 ThrustThingZ(0,30,0,1)
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(18);
		SARG H 6;
		//DEMP B 6
		SARG H 6;
		Goto See;
		
	Melee:
		TNT1 A 0;
		TNT1 A 0 A_TakeInventory("EnemyMemory", 100);
		//TNT1 A 0 A_JumpIfInTargetInventory("ComeEatMeDemon", 1, "MeleeDown");
		SARG E 6 A_FaceTarget();
		SARG F 6 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("DemonAttack",40,0,0,0);
		SARG G 12 a_spawnprojectile("DemonAttack",5,0,0,0);
		
		//TNT1 A 0 A_JumpIfInventory("ZombieManFatality", 1, "FatalityZombieman");
		//TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
		//TNT1 A 0 A_JumpIfInventory("ImpFatality", 1, "FatalityImp");
		//TNT1 A 0 A_JumpIfInventory("ComandoFatality", 1, "FatalityComando");
		
		//TNT1 A 0 A_JumpIfInventory("EatMe", 1, "Eat");
	Goto See;
}

}
