
CLASS DyingCyberBaron1 : ACTOR
{ 
Default
{
	Radius 16;
	Height 60;
	Health 100;
	DamageFactor "Blood", 0.0; DamageFactor "BlueBlood", 0.0; DamageFactor "GreenBlood", 0.0;
	DamageFactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	DamageFactor "Shrapnel", 0.0;
	DamageFactor "KillMe", 0.0;
	DamageFactor "Cutless", 0.6;
	Mass 0;
	-SOLID;
	+SHOOTABLE;
	+FLOORCLIP;
	+NOPAIN;
	Scale 1.2;
	+NOBLOODDECALS;
	BloodType "Green_Blood", "GreenAxeBlood", "GreenAxeBlood";
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("PSXDPN");
		CB4R EF 6;//;
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		CB4R EG 6;//;
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		
		TNT1 A 0 A_PlaySound("PSXDPN");
		CB4R EF 6;//;
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		CB4R EG 6;//;
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		TNT1 A 0 A_PlaySound("PSXDPN");
		CB4R EF 6;//;
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		CB4R EG 6;//;
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		TNT1 A 0 A_PlaySound("PSXDPN");
		CB4R EF 6;//;
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		CB4R EG 6;//;
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		TNT1 A 0 A_PlaySound("PSXDPN");
		CB4R EF 6;//;
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		CB4R EG 6;//;
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		TNT1 A 0 A_PlaySound("PSXDPN");
		CB4R EF 6;//;
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		CB4R EG 6;//;
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		TNT1 A 0 A_PlaySound("PSXDPN");
		CB4R EF 6;//;
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		CB4R EG 6;//;
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		TNT1 A 0 A_PlaySound("cbaron/death");
		EXPL A 0 Radius_Quake(3, 60, 0, 11, 0);
		CB4R EE 12;
		TNT1 A 0 A_NoBlocking;
		EXPL A 0 Radius_Quake(3, 60, 0, 11, 0);
		TNT1 A 0 A_SpawnItemEx("NewFireExplosionEffect",0,0,30,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 ;//A_SpawnItemEx("SpawnedExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 AAAAA 0 ;//a_spawnprojectile("Bloodmist", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//a_spawnprojectile("XDeathBaronOfHellTorso", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 ;//a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//a_spawnprojectile("XDeath2", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 ;//a_spawnprojectile("XDeath3", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//a_spawnprojectile("XDeathOrgan1Green", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//a_spawnprojectile("XDeathOrgan1Green", 24, 0, random(0, 360), 2, random(0, 160));
		CB4R DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 8 a_spawnprojectile("ExplosionSmoke", 24, 0, random(0, 180), 2, random(0, 180));//A_BossDeath
		CB4R D -1;
	Stop;
		
	Death:
		TNT1 AA 0 ;//a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//a_spawnprojectile("Bloodmist", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_PlaySound("misc/gibbed");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("DyingCyberBaron2");
	Stop;
		
	XDeath:
	Death.Blast:
	Death.SSG:
	Death.QuadBlast:
		TNT1 A 0 A_PlaySound("misc/gibbed");
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAAA 0 ;//a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//a_spawnprojectile("XDeath2", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 ;//a_spawnprojectile("XDeath3", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 ;//a_spawnprojectile("Bloodmist", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//a_spawnprojectile("XDeathBaronOfHellTorso", 32, 0, random(0, 360), 2, random(0, 160));
		CB4R LLL 7;
		CB4R MNO 8;
		TNT1 A 0 A_PlaySound("master/walk", 5);
		CB4R O -1;
	Stop;
		
}}

CLASS DyingCyberBaron2 : ACTOR { 
	Default {
	
	Radius 16;
	Height 60;
	Health 90;
	DamageFactor "Blood", 0.0; DamageFactor "BlueBlood", 0.0; DamageFactor "GreenBlood", 0.0;
	DamageFactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	DamageFactor "Shrapnel", 0.0;
	DamageFactor "KillMe", 0.0;
	DamageFactor "Cutless", 0.6;
	DamageFactor "bloodsplasher", 0.0;    DamageFactor "tinybloodsplasher", 0.0;    DamageFactor "superbloodsplasher", 0.0;    DamageFactor "smallbloodsplasher", 0.0;
	DamageFactor "BlueBloodSplasher", 0.0;
	DamageFactor "BlueSuperBloodSplasher", 0.0;
	Mass 0x7FFFFFFF;
	-SOLID;
	+SHOOTABLE;
	+FLOORCLIP;
	+NOPAIN;
	+NOBLOODDECALS;
	BloodType "Green_Blood", "GreenAxeBlood", "GreenAxeBlood";
	Scale 1.2;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("PSXDPN");
		CB4R IIIHHH 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		CB4R IIIJJJ 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_PlaySound("PSXDPN");
		CB4R IIIHHH 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		CB4R IIIJJJ 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		TNT1 A 0 A_PlaySound("PSXDPN");
		CB4R IIIHHH 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		CB4R IIIJJJ 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		TNT1 A 0 A_PlaySound("PSXDPN");
		CB4R IIIHHH 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		CB4R IIIJJJ 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		TNT1 A 0 A_PlaySound("PSXDPN");
		CB4R IIIHHH 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		CB4R IIIJJJ 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		TNT1 A 0 A_PlaySound("PSXDPN");
		CB4R IIIHHH 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		CB4R IIIJJJ 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		TNT1 A 0 A_PlaySound("PSXDPN");
		CB4R IIIHHH 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		CB4R IIIJJJ 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		TNT1 A 0 A_PlaySound("cbaron/death");
		EXPL A 0 Radius_Quake(3, 60, 0, 11, 0);
		CB4R II 12;
		TNT1 A 0 A_NoBlocking;
		EXPL A 0 Radius_Quake(3, 60, 0, 11, 0);
		TNT1 A 0 A_SpawnItemEx("NewFireExplosionEffect",0,0,30,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 ;//A_SpawnItemEx("SpawnedExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 AAAAA 0 ;//a_spawnprojectile("Bloodmist", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//a_spawnprojectile("XDeathBaronOfHellTorso", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 ;//a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//a_spawnprojectile("XDeath2", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 ;//a_spawnprojectile("XDeath3", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//a_spawnprojectile("XDeathOrgan1Green", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//a_spawnprojectile("XDeathOrgan1Green", 24, 0, random(0, 360), 2, random(0, 160));
		CB4R DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 8 a_spawnprojectile("ExplosionSmoke", 24, 0, random(0, 180), 2, random(0, 180));//A_BossDeath
		CB4R D -1;
	Stop;
		
	Death.Head:
	Death.MinorHead:
		TNT1 A 0 A_SpawnItem("BaronOfHellHeadExplode", 0, 62);
		CB4R KKKKKKKKK 8 ;//a_spawnprojectile("brutal_LiquidBlood", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("ShoqueAzul",1,62);
		EXPL A 0 Radius_Quake(3, 60, 0, 11, 0);
		CB4R K 8 ;//a_spawnprojectile("brutal_LiquidBlood", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_NoBlocking;
		EXPL A 0 Radius_Quake(3, 60, 0, 11, 0);
		TNT1 A 0 A_SpawnItemEx("NewFireExplosionEffect",0,0,30,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 ;//A_SpawnItemEx("SpawnedExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 AAAAAA 0 ;//a_spawnprojectile("Bloodmist", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//a_spawnprojectile("XDeathBaronOfHellTorso", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 ;//a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//a_spawnprojectile("XDeath2", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 ;//a_spawnprojectile("XDeath3", 62, 0, random(0, 360), 2, random(0, 160));
		CB4R DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 8 a_spawnprojectile("ExplosionSmoke", 24, 0, random(0, 180), 2, random(0, 180));//A_BossDeath
		CB4R D -1;
	Stop;
		
	Death.SSG:
	Death.Blast:
	Death.Cut:
	Death:
	Death.Explosive:
	XDeath:
	Death.ExplosiveImpact:
		TNT1 A 0 A_PlaySound("misc/gibbed");
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 ;//a_spawnprojectile("XDeath2", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 ;//a_spawnprojectile("Bloodmist", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//a_spawnprojectile("XDeathBaronOfHellTorso", 32, 0, random(0, 360), 2, random(0, 160));
		CB4R LLL 7;
		CB4R MNO 8;
		TNT1 A 0 A_PlaySound("master/walk", 5);
		CB4R O -1;
	Stop;
		
}}

CLASS DyingCyberBaron3 : ACTOR { 
	Default {
	
	Radius 16;
	Height 60;
	Health 125;
	DamageFactor "Blood", 0.0; DamageFactor "BlueBlood", 0.0; DamageFactor "GreenBlood", 0.0;
	DamageFactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	DamageFactor "Shrapnel", 0.0;
	DamageFactor "KillMe", 0.0;
	DamageFactor "Cutless", 0.6;
	Mass 0x7FFFFFFF;
	-SOLID;
	+SHOOTABLE;
	+FLOORCLIP;
	+NOPAIN;
	+NOBLOODDECALS;
	BloodType "Green_Blood", "GreenAxeBlood", "GreenAxeBlood";
	Scale 1.2;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("PSXDPN");
		CB4R QQQRRR 2 ;//a_spawnprojectile("brutal_LiquidBlood", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 ;//a_spawnprojectile("Bloodmist", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		CB4R RRRSSS 2 ;//a_spawnprojectile("brutal_LiquidBlood", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 ;//a_spawnprojectile("Bloodmist", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_PlaySound("PSXDPN");
		CB4R QQQRRR 2 ;//a_spawnprojectile("brutal_LiquidBlood", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 ;//a_spawnprojectile("Bloodmist", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		CB4R RRRSSS 2 ;//a_spawnprojectile("brutal_LiquidBlood", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 ;//a_spawnprojectile("Bloodmist", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_PlaySound("PSXDPN");
		CB4R QQQRRR 2 ;//a_spawnprojectile("brutal_LiquidBlood", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 ;//a_spawnprojectile("Bloodmist", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		CB4R RRRSSS 2 ;//a_spawnprojectile("brutal_LiquidBlood", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 ;//a_spawnprojectile("Bloodmist", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_PlaySound("PSXDPN");
		CB4R QQQRRR 2 ;//a_spawnprojectile("brutal_LiquidBlood", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 ;//a_spawnprojectile("Bloodmist", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		CB4R RRRSSS 2 ;//a_spawnprojectile("brutal_LiquidBlood", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//A_SpawnItem("Green_Blood", 0, 30);
		TNT1 A 0 A_PlaySound("PSXDPN");
		CB4R QQQRRR 2 ;//a_spawnprojectile("brutal_LiquidBlood", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 ;//a_spawnprojectile("Bloodmist", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		CB4R RRRSSS 2 ;//a_spawnprojectile("brutal_LiquidBlood", 62, 0, random(0, 360), 2, random(0, 160));
	Death:
		TNT1 A 0 A_PlaySound("cbaron/death");
		TNT1 A 0 A_NoBlocking;
		CY8D EFGH 6;
		TNT1 A 0 A_PlaySound("master/walk", 5);
		TNT1 A 0 ;//A_SpawnItem("GrowingBloodPool");
		CY8D IIIIIIIIIIIIIIIIIIIII 2 ;//a_spawnprojectile("brutal_LiquidBlood", 10, 0, random(0, 360), 2, random(30, 60));
		CY8D I -1;
	Stop;
		
	Death.Fatality:
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("CyberBaronFatality2", 1);
		TNT1 A 1 A_NoBlocking;
	Stop;
		
		
	Death:
	Death.Blast:
	Death.Shotgun:
	Death.Nailgun:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("FatalizedCyberBaron");
	Stop;
		
	Death.SSG:
	Death.Cut:
	XDeath:
		TNT1 A 0 A_PlaySound("misc/gibbed");
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 ;//a_spawnprojectile("XDeath2", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAA 0 ;//a_spawnprojectile("Bloodmist", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 ;//a_spawnprojectile("XDeath1", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 ;//a_spawnprojectile("XDeath2", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 ;//a_spawnprojectile("XDeath3", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//a_spawnprojectile("XDeathOrgan1Green", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//a_spawnprojectile("XDeathOrgan1Green", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 ;//a_spawnprojectile("XDeathBaronOfHellTorso", 32, 0, random(0, 360), 2, random(0, 160));
		CB4R LLL 7;
		CB4R MNO 8;
		TNT1 A 0 A_PlaySound("master/walk", 5);
		CB4R O -1;
	Stop;
		
}}


CLASS FatalizedCyberBaron : ACTOR { 
	Default {
	
	Radius 16;
	Height 60;
	Health 125;
	DamageFactor "Blood", 0.0; DamageFactor "BlueBlood", 0.0; DamageFactor "GreenBlood", 0.0;
	DamageFactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	DamageFactor "Shrapnel", 0.0;
	DamageFactor "KillMe", 0.0;
	DamageFactor "Cutless", 0.6;
	DamageFactor "bloodsplasher", 0.0;    DamageFactor "tinybloodsplasher", 0.0;    DamageFactor "superbloodsplasher", 0.0;    DamageFactor "smallbloodsplasher", 0.0;
	DamageFactor "BlueBloodSplasher", 0.0;
	DamageFactor "BlueSuperBloodSplasher", 0.0;
	Mass 0x7FFFFFFF;
	-SOLID;
	+SHOOTABLE;
	+FLOORCLIP;
	+NOPAIN;
	+NOBLOODDECALS;
	BloodType "Green_Blood", "GreenAxeBlood", "GreenAxeBlood";
	Scale 1.2;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("PSXDPN");
		C8FT III 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		C8FT JJJ 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_PlaySound("PSXDPN");
		C8FT III 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		C8FT JJJ 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_PlaySound("PSXDPN");
		C8FT III 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		C8FT JJJ 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_PlaySound("PSXDPN");
		C8FT III 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		C8FT JJJ 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_PlaySound("PSXDPN");
		C8FT III 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		C8FT JJJ 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_PlaySound("PSXDPN");
		C8FT III 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		C8FT JJJ 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAA 0 ;//a_spawnprojectile("Green_Blood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_PlaySound("PSXDPN");
		C8FT III 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		C8FT JJJ 2 ;//a_spawnprojectile("brutal_LiquidBlood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAA 0 ;//a_spawnprojectile("Green_Blood", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
	Death:
		TNT1 A 0 A_PlaySound("cbaron/death");
		C8FT IJ 10;
		TNT1 A 0 A_NoBlocking;
		CY8D EFGH 6;
		TNT1 A 0 A_PlaySound("master/walk", 5);
		TNT1 A 0 ;//A_SpawnItem("GrowingBloodPool");
		CY8D IIIIIIIIIIIIIIIIIIIII 2 ;//a_spawnprojectile("brutal_LiquidBlood", 10, 0, random(0, 360), 2, random(30, 60));
		CY8D I -1;
	Stop;
		
	Death.SSG:
	Death.Blast:
	Death.Cut:
	Death.Explosive:
	XDeath:
	Death.ExplosiveImpact:
		TNT1 A 0 A_PlaySound("misc/gibbed");
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 ;//a_spawnprojectile("XDeath2", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAAA 0 ;//a_spawnprojectile("Green_Blood", 62, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 ;//a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 A 0 ;//a_spawnprojectile("XDeathBaronOfHellTorso", 32, 0, random(0, 360), 2, random(0, 160));
		CB4R LLL 7;
		CB4R MNO 8;
		TNT1 A 0 A_PlaySound("master/walk", 5);
		CB4R O -1;
	Stop;
}

}

CLASS CyberFriedMarine: pb_blood_and_gore_base { 
States
{
	Spawn:
		P19D AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 9 A_SpawnItem("ExplosionSmoke",0,0,0,1);
		P19D A -1;
	Stop;
}

}