class proto_pinky : pb_monster_base
{
states
{
	Death.Blackhole:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));		
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 32, 0, 0, 0, 0, 128);
		ID53 AAABCDEFGHI 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 32, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
	Stop;
}

}





























CLASS PinkyHeadPiece : pb_blood_and_gore_base { 
	Default {
	Radius 2;
	Height 2;
	Speed 6;
	Mass 1;
	Decal "BrutalBloodSplat";
	+CLIENTSIDEONLY;
	BounceFactor 0.4;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	+FLOORCLIP;
	Scale 1.2;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		XHE5 MNOP 4 a_spawnprojectile("named_BloodTr", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		XHE5 M 1;
		TNT1 A 0 A_QueueCorpse;
 	Rest:
		XHE5 M 2000;
		XHE5 M -1;
		Stop;
	DoNothing:
		TNT1 A 0;
		Stop;
	}
}

CLASS VoidSpectreHeadPiece : pb_blood_and_gore_base { 
	Default {
	Radius 2;
	Height 2;
	Speed 6;
	Mass 1;
	Decal "GreenBloodSpot";
	+CLIENTSIDEONLY;
	BounceFactor 0.4;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	+FLOORCLIP;
	Scale 1.2;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		E3G8 FGHI 4;//a_spawnprojectile("named_BloodTr", 0, 0, random(0, 360), 2, random(0, 360))
		Loop;
	Death:
		E3G8 J 1;
		TNT1 A 0 A_QueueCorpse;
 	Rest:
		E3G8 J 2000;
		E3G8 J -1;
		Stop;
		
	DoNothing:
		TNT1 A 0;
		Stop;
	}
}

CLASS XDeathVoidSpectreEyeball : pb_blood_and_gore_base { 
	Default {
	
	Radius 2;
	Height 2;
	Speed 6;
	Mass 1;
	Decal "GreenBloodSpot";
	+CLIENTSIDEONLY;
	BounceFactor 0.4;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	+FLOORCLIP;
	Scale 1.0;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		E3G8 KLMN 4 a_spawnprojectile("Brutal_FlyingBlood"/*Green_FlyingBlood*/, 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		E3G8 J 1;
		TNT1 A 0 A_QueueCorpse;
 	Rest:
		E3G8 O 2000;
		E3G8 O -1;
		Stop;
		
	DoNothing:
		TNT1 A 0;
		Stop;
	}
}



CLASS PinkyJaw: BaronHeadPiece { 
	Default {
	Scale 1.2;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		PDG1 ABCDEFGH 4 a_spawnprojectile("named_BloodTr", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		PDG1 I 2;
		TNT1 A 0 A_QueueCorpse;
		Goto Rest;
		
	Rest:
		PDG1 I 900;
		PDG1 I -1;
		Stop;
	DoNothing:
		TNT1 A 0;
		Stop;
	}
}



CLASS XDeathBullArm1: XDeathArm1 { 
	Default {
	
	Scale 1.0;
	Speed 10;
	Gravity 0.4;
	BounceFactor 0.4;
	+SKYEXPLODE;
	Species "Marines";
	+THRUSPECIES;
	BounceCount 5;
	Radius 10;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		HND8 ABCDEFGH 3 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
Death.plasma: Death.Burn: Death.Flames:
		TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
		Stop;
Death:
	HND8 I 1;
	HND8 A 0 A_SpawnItem("Gib_DemonArm",0,0,0,1);
	Stop;
}
}

CLASS Gib_DemonArm: LimbBase { 
	Default {
 
    Scale 1.1;
	}
    States
    {
    Spawn:
	HND8 GH 2;
	Goto Spawn1;
	
	Spawn1:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	HND8 I 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	HND8 I -1;
        Stop;
    Death:    
    TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
    TNT1 A 0 a_spawnprojectile("GibDemonHand", 0, 0, random(0, 180), 2, random(0, 180));
    TNT1 A 0 a_spawnprojectile("GibDemonArmPart", 0, 0, random(0, 180), 2, random(0, 180));
Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
	    HND8 AA 1 A_FaceTarget;
	TNT1 A 0 a_spawnprojectile("XDeathBullArm1Kicked", 5, 0, random(170, 190), 2, random(20, 40));
	Stop;
	
	Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	HND8 ABCDEFGH 2;
	Goto Spawn1;
	
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	HND8 A 5;
	HND8 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
	Landz:
	
	XDT5 I 0 A_SpawnItem("Gib_DemonArm");
	Stop;
}}


CLASS XDeathBloodDemonArm1: XDeathArm1 { 
	Default {
 
    Scale 1.0;
    Speed 10;
	Gravity 0.4;
	bounceFactor 0.4;
	+SKYEXPLODE;
	Species "Marines";
	+THRUSPECIES;
	BounceCount 5;
	Radius 10;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		M3G8 ABCDEFGH 3 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death.plasma: Death.Burn: Death.Flames:
	TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:
		M3G8 I 1;
		HND8 A 0 A_SpawnItem("Gib_BloodDemonArm",0,0,0,1);
	Stop;
}
}

CLASS Gib_BloodDemonArm: LimbBase { 
	Default {
 
    Scale 1.1;
	}
    States
    {
    Spawn:
	M3G8 GH 2;
	Goto Spawn1;
	
	Spawn1:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	M3G8 I 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	M3G8 I -1;
        Stop;
    Death:    
    TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
    TNT1 A 0 a_spawnprojectile("GibDemonHand", 0, 0, random(0, 180), 2, random(0, 180));
    TNT1 A 0 a_spawnprojectile("GibDemonArmPart", 0, 0, random(0, 180), 2, random(0, 180));
Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
	    M3G8 AA 1 A_FaceTarget;
	TNT1 A 0 a_spawnprojectile("XDeathBullArm1Kicked", 5, 0, random(170, 190), 2, random(20, 40));
	Stop;
	
	Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	M3G8 ABCDEFGH 2;
	Goto Spawn1;
	
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	M3G8 A 5;
	M3G8 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
	Landz:
	
	M3G8 I 0 A_SpawnItem("Gib_BloodDemonArm");
	Stop;
}}

CLASS XDeathVoidSpectreArm: XDeathArm1 { 
	Default {
 
    Scale 1.0;
    Speed 10;
	Gravity 0.4;
bounceFactor 0.4;
	+SKYEXPLODE;
	Species "Marines";
	+THRUSPECIES;
	BounceCount 5;
	Decal "GreenBloodSplat";
	Radius 10;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		ND6M ABCDEFGH 3 a_spawnprojectile("brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death.plasma: Death.Burn: Death.Flames:
	TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonArm", 32, 0, random(0, 360), 2, random(0, 160)); 
	Stop;
	Death:
		ND6M I 1;
		ND6M A 0 A_SpawnItem("Gib_VoidSpectreArm",0,0,0,1);
	Stop;
}
}

CLASS Gib_VoidSpectreArm: LimbBase { 
	Default {
 
    Scale 1.1;
	BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	BloodColor "DarkGreen";
	}
    States
    {
    Spawn:
	ND6M GH 2;
	Goto Spawn1;
	
	Spawn1:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	ND6M I 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	ND6M I -1;
        Stop;
    Death:    
    TNT1 AAAA 0 a_spawnprojectile("brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 360));
    TNT1 A 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 180), 2, random(0, 180));
    TNT1 A 0 a_spawnprojectile("XDeath2", 0, 0, random(0, 180), 2, random(0, 180));
	Stop;
	
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
	    ND6M AA 1 A_FaceTarget;
	TNT1 A 0 a_spawnprojectile("XDeathVoidSpectreKicked", 5, 0, random(170, 190), 2, random(20, 40));
	Stop;
	
	Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	ND6M ABCDEFGH 2;
	Goto Spawn1;
	
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	ND6M A 5;
	ND6M ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
	Landz:
	
	XDT5 I 0 A_SpawnItem("Gib_VoidSpectreArm");
	Stop;
}}

CLASS XDeathDemonArm: XDeathBullArm1 { 
	Default {
    Scale 1.1;
	}
}

CLASS XDeathVoidSpectreKicked: XDeathVoidSpectreArm { 
	Default {
+ACTIVATEMCROSS
+ACTIVATEIMPACT
+CANUSEWALLS
	}
}

CLASS XDeathBullArm1Kicked: XDeathBullArm1 { 
	Default {
+ACTIVATEMCROSS
+ACTIVATEIMPACT
+CANUSEWALLS
	}
}

CLASS GibDemonArmPart: TinyGib { 
	Default {
    Scale 1.1;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	HND8 Z -1;
        Stop;
		
    Death:
HND8 Z 1;
       Loop;
}}

CLASS GibDemonHand: TinyGib { 
	Default {
 
    Scale 0.8;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	HND8 Y -1;
       Loop;
    Death:
HND8 Y 1;
       Loop;
}}


CLASS XDeathBullLeg12: XDeathArm1 { 
	Default {
 
    Scale 1.1;
    Speed 8;
	Gravity 0.4;
bounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		LEG8 ABCDEFGH 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		LEG8 I 1;
		LEG8 I 0 A_SpawnItem("Gib_DemonLeg");
		Stop;
	}
}

CLASS Gib_DemonLeg: LimbBase { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		LEG8 GH 2;
		Goto Spawn1;
	Spawn1:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG8 I 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		LEG8 I -1;
		Stop;
		
		
	Death.plasma:
    TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonLeg", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:    
		TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("GibDemonLegPart", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GibDemonPaw", 0, 0, random(0, 180), 2, random(0, 180));
		Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		LEG8 A 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathBullLeg12", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		LEG8 ABCDEFGH 2;
		Goto Spawn1;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		LEG8 A 5;
		LEG8 ABCDEFGH 5;
		XDT5 I 0 A_SpawnItem("Gib_DemonLeg");
Stop;}}
	
CLASS XDeathBloodDemonLeg12: XDeathArm1 { 
	Default {
	
	Scale 1.1;
	Speed 8;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		M3G7 ABCDEFGH 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		M3G7 I 1;
		M3G7 I 0 A_SpawnItem("Gib_BloodDemonLeg");
		Stop;
	}
}

CLASS Gib_BloodDemonLeg: LimbBase { 
	Default {
	Scale 1.1;
	}
	States
	{
	Spawn:
		M3G7 I 0;
		M3G7 I 0 A_Jump(128, "Spawn2");
		Goto Spawn1;
		
	Spawn1:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		M3G7 I 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		M3G7 I -1;
		Stop;
		
	Spawn2:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		M3G7 J 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		M3G7 J -1;
		Stop;
		
	Death.plasma:
    TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonLeg", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:    
		TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("GibDemonLegPart", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GibDemonPaw", 0, 0, random(0, 180), 2, random(0, 180));
		Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		M3G7 A 0 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathBloodDemonLeg12", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		M3G7 ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		M3G7 A 5;
		M3G7 ABCDEFGH 5;
		XDT5 I 0 A_SpawnItem("Gib_BloodDemonLeg");
Stop;}}

CLASS XDeathVoidSpectreLeg: XDeathArm1 { 
	Default {
	
	Scale 1.1;
	Speed 8;
	Gravity 0.4;
	BounceFactor 0.4;
	Decal "GreenBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		L3G8 ABCDEFGH 4 a_spawnprojectile("brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		L3G8 H 1;
		L3G8 I 0 A_SpawnItem("Gib_VoidSpectreLeg");
		Stop;
	}
}

CLASS Gib_VoidSpectreLeg: LimbBase { 
	Default {
	
	Scale 1.1;
	BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	BloodColor "DarkGreen";
	}
	States
	{
	Spawn:
		L3G8 GH 2;
	Spawn1:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		L3G8 H 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		L3G8 H -1;
		Stop;
		
		
	Death.plasma:    TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonLeg", 32, 0, random(0, 360), 2, random(0, 160));        
	Stop;
	Death:    
		TNT1 AAAA 0 a_spawnprojectile("brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("XDeath2", 0, 0, random(0, 180), 2, random(0, 180));
		Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		L3G8 A 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathVoidSpectreLeg", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		L3G8 ABCDEFGH 2;
		Goto Spawn1;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		L3G8 A 5;
		L3G8 ABCDEFGH 5;
		XDT5 I 0 A_SpawnItem("Gib_VoidSpectreLeg");
Stop;}}

CLASS GibDemonLegPart: TinyGib { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG8 Z -1;
		Stop;
	Death:
		LEG8 Z 1;
		Loop;
}}

CLASS GibDemonPaw: TinyGib { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG8 Y 1;
		Stop;
	Death:
		LEG8 Y 1;
		Loop;
}}



CLASS XDeathPinkyDemonHead: XDeathBullArm1 { 
	Default {
	
	-CLIENTSIDEONLY;
	Speed 10;
	Scale 1.3;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		DEMH AB 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		DEMH CDEFGH 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		Loop;
	Death:
		DEMH I 1;
		DEMH I 1 A_SpawnItem("PinkyDemonHead",0,0,0,1);
		Stop;
	}
}



CLASS PinkyDemonHead: LimbBase { 
	Default {
	
	damagefactor "Kick", 9.0;
	damagefactor "Melee", 9.0;
	damagefactor "SuperPunch", 9.0;
	-CLIENTSIDEONLY;
	Radius 10;
	
	Mass 12;
	Health 60;
	Scale 1.5;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		DEMH I 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		DEMH I -1;
		Stop;
		
	Death:
		TNT1 AAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_SpawnItem("MeatDeathSmall");
		TNT1 AA 0 a_spawnprojectile("XDeathBrain1", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBrain2", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 10, random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 10, random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 10, 0, random(0, 360), 2, random(30, 90));
		TNT1 AA 0 a_spawnprojectile("PinkyHeadPiece", 12, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("PinkyJaw", 12, 0, random(0, 360), 2, random(0, 160));
		Stop;
	Death.Trample:
	Crush:
		//TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
		TNT1 AAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		DEMH I 5;
		DEMH I 9009;
		Stop;
	Death.plasma:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL A 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0;
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		DEMH A 1 A_Pain;
		DEMH A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeathPinkyDemonHeadKicked", 5, 0, random(170, 190), 2, random(20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		DEMH ACEGI 3;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		DEMH ABCDEFGH 3;
		DEMH I 0 A_SpawnItem("PinkyDemonHead");
		Stop;
		
}}



CLASS XDeathPinkyDemonHeadKicked: XDeathPinkyDemonHead { 
	Default {
	
	-BOUNCEONACTORS;
	Damage 4;
	Speed 13;
	Scale 1.3;
	BounceFactor 0.4;
	}
}

