class proto_pinky : pb_monster_base
{
states
{
	Death.Blackhole:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));		
		ID53 AAABCDEFGHI 4;
		TNT1 A 0 A_StopSound(2);
	Stop;


	Death.Incinerate:
		TNT1 A 0 A_Playsound("MELT");
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAAAA 0 
		{
			pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");
		}
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,32,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-35, 35), random(-35, 35));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-45, 45), random(-45, 35));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("Ashes1", 28, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("Ashes2", 40, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),32,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		S6RN AAAAABBBBBzCCCCCDDDDDEEEEEFFFFFzGGGGHHHH 1 BRIGHT Light("IncinerationGlow")
		{
			pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");
			A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),28,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			if(frame > 20)
			{
				A_Playsound("SZZLL", 3);
				frame = 0;
			}
		}
		S6RN HHIIHHIIHHIIHHIIHHIIHHIIHHIIHHII 2 BRIGHT Light("IncinerationGlow")
		{
			a_spawnprojectile("ExplosionSmoke", 14, 0, random(0, 360), 2, random(0, 160));
			A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		}
		S6RN HHIIHHIIHHIIHHII 2;
		S6RN JJJJJJJ 12 a_spawnprojectile("ExplosionSmoke", 14, 0, random(0, 360), 2, random(0, 160));
		S6RN J -1;
	Stop;
	

	Death.fire:
	Death.Flames:
	Death.Burn:
		//TNT1 A 0 A_JumpIfIntargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItemEx("BurningDemon",0,0,8,0,0,0,0,288);
	Stop;
	


	Death.SuperPlasma:
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("Ashes1", 32, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("Ashes2", 32, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		SPRG ABCDEF 6
		{
			if(getclassname() == 'pb_void_spectre') frame += 6;// so it would be GHIJK
		}
		CARB JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 10
		{
			a_spawnprojectile("Explosion_Smoke", 25, 0, random(0, 360), 2, random(70, 110));
			if(getclassname() == 'pb_void_spectre') frame += 8;//from J to R
		}
		CARB J -1;
	Stop;


	XDeath:
	DEath.Explosive:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 AAAA 0 a_spawnprojectile("XDeath3", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 A 0 a_spawnprojectile("XDeath4", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		TNT1 A 0 a_spawnprojectile("XDeathStomach", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBullLeg12", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathPinkyDemonHead", 42, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
	Stop;
	

}

}




CLASS BurningDemon: actor { 
States
{
	Spawn:
		//just demon
		//SBRG
		//demon 2
		//CRB7
		//Void
		//CRB8
		//mean 
		//CRB9
		
		TNT1 A 0
		{
			A_PlaySound("BURNZOM");
			switch(getclassname())
			{
				case 'pb_Bull_Demon' : sprite = getspriteindex("SBRG"); break;
				case 'pb_Mech_Demon' : sprite = getspriteindex("CRB7"); break;
				case 'pb_void_spectre' : sprite = getspriteindex("CRB8"); break;
				case 'pb_Demon_X' : sprite = getspriteindex("CRB9"); break;
				
				default: break;
			}
		}
	living_torch:
		"####" AAABBBCCCDDD 1
		{
			A_Wander();
			A_Recoil(-1);
			a_spawnprojectile("BurnParticles", 20, 0, random(0, 360), 2, random(50, 130));
			a_spawnprojectile("ExplosionParticle", 40, 0, random(0, 360), 2, random(50, 130));
		}
		tnt1 a 0 a_jumpif(random(0, 10) > 3, "living_torch");
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_playsound("demon/pain");
		P1N7 AAABBBzCCCDDDzCCCDDDzCCCDDDzCCCDDDzCCCDDD 3
		{
			a_spawnprojectile("FlameTrails", 30, 0, random(0, 360), 2, random(50, 130));
			if(frame > 20)
			{
				A_playsound("demon/pain");
				tics = 0;
			}
		}
	goto burned_demon;
		
	XDeath:
	Death.SSG:
	Death.Explosive:
		TNT1 A 0 A_NOBlocking;
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedDemonLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("MuchMeatDeath", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("BurningFlyingMeatPiece", 64, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
	Stop;

		//demon 2
		//CRB7
		
		CRB7 MNOP 3
		{
			A_Wander();
			a_spawnprojectile("BurnParticles", 25, 0, random(0, 360), 2, random(50, 130));
		}
		tnt1 a 0 a_jumpif(random(0, 10) < 3, "Death");
	Loop;
		
	Death:
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 A_Jump(96, "Death2");
		CRB7 Q 2;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_playsound("demon/death");
		CRB7 QQQQRRRR 2 a_spawnprojectile("BurnParticles", 35, 0, random(0, 360), 2, random(50, 130));
		goto burned_demon;
		
	Death2:
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_playsound("demon/pain");
	dd2_loop:
		P1N7 AAABBBCCCDDD 3 a_spawnprojectile("FlamethrowerFireParticles", 20, 0, random(0, 360), 2, random(50, 130));
		TNT1 A 0 A_playsound("demon/pain");
		tnt1 a 0 a_jumpif(random(0, 10) < 7, "dd2_loop");

		TNT1 A 0 A_playsound("demon/death",5);
		goto burned_demon;
		
	XDeath:
	Death.SSG:
	Death.Explosive:
		TNT1 A 0 A_NOBlocking;
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedDemonLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("MuchMeatDeath", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("BurningFlyingMeatPiece", 64, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		Stop;





		//mean 
		//CRB9
		CRB9 MNOP 3
		{
			A_Wander();
			a_spawnprojectile("BurnParticles", random(24,26), random(-4,4), random(0, 360), 2, random(50, 130));
		}
		TNT1 A 0 A_playsound("demon/pain");
	Death:
		CRB9 Q  2
		{
			self.bSHOOTABLE = false;
			A_NoBlocking();
			A_playsound("demon/death");
		}
		CRB9 QQQQRRRR 2 a_spawnprojectile("BurnParticles", 26, 0, random(0, 360), 2, random(50, 130));
	Stop;


	//Void
	//CRB8
		CRB8 MNOP 3
		{
			A_Wander();
			a_spawnprojectile("BurnParticles", random(24,26), random(-4,4), random(0, 360), 2, random(50, 130));
		}
		TNT1 A 0 A_playsound("demon/pain");
		tnt1 q 0 a_jump(33, 1);
	Loop;
	
		TNT1 A 0 {self.bSHOOTABLE = false;}
		CRB8 Q 2
		{
			A_NoBlocking();
			A_Scream();
			A_playsound("demon/death");
		}
		CRB8 QQQQRRRR 2 a_spawnprojectile("BurnParticles", 26, 0, random(0, 360), 2, random(50, 130));



	//burned demon
	burned_demon:
		TNT1 A 0 A_Playsound("props/redfire");
		tnt1 a 0
		{
			switch( random(0,1) )
			{
				case 0 : sprite = getspriteindex("carb"); frame = 9; break;
				case 1 : sprite = getspriteindex("P1N7"); frame = 4; break;
			}
		}
		"####" "############################################################################" 2
		{
			a_spawnprojectile("FlameTrails", 25, 0, random(0, 360), 2, random(50, 130));
			a_spawnprojectile("BurnParticles", 32, 0, random(0, 360), 2, random(50, 130));
		}
		"####" "############################################################################" 2
		{
			tics = random(15, 25);
			a_spawnprojectile("Explosion_Smoke", 35, 0, random(0, 360), 2, random(70, 110));
		}
		"####" "#" -1;
	Stop;
}
}
























CLASS PinkyHeadPiece : pb_blood_and_gore_base { 
	Default {
	Radius 2;
	Height 2;
	Speed 6;
	Mass 1;
	Decal "BrutalBloodSplat";
	+CLIENTSIDEONLY;
	BounceFactor 0.4;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	+FLOORCLIP;
	Scale 1.2;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		XHE5 MNOP 4 a_spawnprojectile("named_BloodTr", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		XHE5 M 1;
		TNT1 A 0 A_QueueCorpse;
 	Rest:
		XHE5 M 2000;
		XHE5 M -1;
		Stop;
	DoNothing:
		TNT1 A 0;
		Stop;
	}
}

CLASS VoidSpectreHeadPiece : pb_blood_and_gore_base { 
	Default {
	Radius 2;
	Height 2;
	Speed 6;
	Mass 1;
	Decal "GreenBloodSpot";
	+CLIENTSIDEONLY;
	BounceFactor 0.4;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	+FLOORCLIP;
	Scale 1.2;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		E3G8 FGHI 4;//a_spawnprojectile("named_BloodTr", 0, 0, random(0, 360), 2, random(0, 360))
		Loop;
	Death:
		E3G8 J 1;
		TNT1 A 0 A_QueueCorpse;
 	Rest:
		E3G8 J 2000;
		E3G8 J -1;
		Stop;
		
	DoNothing:
		TNT1 A 0;
		Stop;
	}
}

CLASS XDeathVoidSpectreEyeball : pb_blood_and_gore_base { 
	Default {
	
	Radius 2;
	Height 2;
	Speed 6;
	Mass 1;
	Decal "GreenBloodSpot";
	+CLIENTSIDEONLY;
	BounceFactor 0.4;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	+FLOORCLIP;
	Scale 1.0;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		E3G8 KLMN 4 a_spawnprojectile("Brutal_FlyingBlood"/*brutal_LiquidBlood*/, 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		E3G8 J 1;
		TNT1 A 0 A_QueueCorpse;
 	Rest:
		E3G8 O 2000;
		E3G8 O -1;
		Stop;
		
	DoNothing:
		TNT1 A 0;
		Stop;
	}
}



CLASS PinkyJaw: BaronHeadPiece { 
	Default {
	Scale 1.2;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		PDG1 ABCDEFGH 4 a_spawnprojectile("named_BloodTr", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		PDG1 I 2;
		TNT1 A 0 A_QueueCorpse;
		Goto Rest;
		
	Rest:
		PDG1 I 900;
		PDG1 I -1;
		Stop;
	DoNothing:
		TNT1 A 0;
		Stop;
	}
}



CLASS XDeathBullArm1: XDeathArm1 { 
	Default {
	
	Scale 1.0;
	Speed 10;
	Gravity 0.4;
	BounceFactor 0.4;
	+SKYEXPLODE;
	Species "Marines";
	+THRUSPECIES;
	BounceCount 5;
	Radius 10;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		HND8 ABCDEFGH 3 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
	Loop;

	Death.plasma: Death.Burn: Death.Flames:
		TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
		Stop;
Death:
	HND8 I 1;
	HND8 A 0 A_SpawnItem("Gib_DemonArm",0,0,0,1);
	Stop;
}
}

CLASS Gib_DemonArm: Limbs_Base { 
	Default {
 
    Scale 1.1;
	}
    States
    {
    Spawn:
	HND8 GH 2;
	Goto Spawn1;
	
	Spawn1:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	HND8 I 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	HND8 I -1;
        Stop;
    Death:    
    TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
    TNT1 A 0 a_spawnprojectile("GibDemonHand", 0, 0, random(0, 180), 2, random(0, 180));
    TNT1 A 0 a_spawnprojectile("GibDemonArmPart", 0, 0, random(0, 180), 2, random(0, 180));
Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
	    HND8 AA 1 A_FaceTarget;
	TNT1 A 0 a_spawnprojectile("XDeathBullArm1Kicked", 5, 0, random(170, 190), 2, random(20, 40));
	Stop;
	
	Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	HND8 ABCDEFGH 2;
	Goto Spawn1;
	
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	HND8 A 5;
	HND8 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
	Landz:
	
	XDT5 I 0 A_SpawnItem("Gib_DemonArm");
	Stop;
}}


CLASS XDeathBloodDemonArm1: XDeathArm1 { 
	Default {
 
    Scale 1.0;
    Speed 10;
	Gravity 0.4;
	bounceFactor 0.4;
	+SKYEXPLODE;
	Species "Marines";
	+THRUSPECIES;
	BounceCount 5;
	Radius 10;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		M3G8 ABCDEFGH 3 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death.plasma: Death.Burn: Death.Flames:
	TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:
		M3G8 I 1;
		HND8 A 0 A_SpawnItem("Gib_BloodDemonArm",0,0,0,1);
	Stop;
}
}

CLASS Gib_BloodDemonArm: Limbs_Base { 
	Default {
 
    Scale 1.1;
	}
    States
    {
    Spawn:
	M3G8 GH 2;
	Goto Spawn1;
	
	Spawn1:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	M3G8 I 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	M3G8 I -1;
        Stop;
    Death:    
    TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
    TNT1 A 0 a_spawnprojectile("GibDemonHand", 0, 0, random(0, 180), 2, random(0, 180));
    TNT1 A 0 a_spawnprojectile("GibDemonArmPart", 0, 0, random(0, 180), 2, random(0, 180));
Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
	    M3G8 AA 1 A_FaceTarget;
	TNT1 A 0 a_spawnprojectile("XDeathBullArm1Kicked", 5, 0, random(170, 190), 2, random(20, 40));
	Stop;
	
	Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	M3G8 ABCDEFGH 2;
	Goto Spawn1;
	
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	M3G8 A 5;
	M3G8 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
	Landz:
	
	M3G8 I 0 A_SpawnItem("Gib_BloodDemonArm");
	Stop;
}}

CLASS XDeathVoidSpectreArm: XDeathArm1 { 
	Default {
 
    Scale 1.0;
    Speed 10;
	Gravity 0.4;
bounceFactor 0.4;
	+SKYEXPLODE;
	Species "Marines";
	+THRUSPECIES;
	BounceCount 5;
	Decal "GreenBloodSplat";
	Radius 10;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		ND6M ABCDEFGH 3 a_spawnprojectile("brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death.plasma: Death.Burn: Death.Flames:
	TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonArm", 32, 0, random(0, 360), 2, random(0, 160)); 
	Stop;
	Death:
		ND6M I 1;
		ND6M A 0 A_SpawnItem("Gib_VoidSpectreArm",0,0,0,1);
	Stop;
}
}

CLASS Gib_VoidSpectreArm: Limbs_Base { 
	Default {
 
    Scale 1.1;
	BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	BloodColor "DarkGreen";
	}
    States
    {
    Spawn:
	ND6M GH 2;
	Goto Spawn1;
	
	Spawn1:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	ND6M I 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	ND6M I -1;
        Stop;
    Death:    
    TNT1 AAAA 0 a_spawnprojectile("brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 360));
    TNT1 A 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 180), 2, random(0, 180));
    TNT1 A 0 a_spawnprojectile("XDeath2", 0, 0, random(0, 180), 2, random(0, 180));
	Stop;
	
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
	    ND6M AA 1 A_FaceTarget;
	TNT1 A 0 a_spawnprojectile("XDeathVoidSpectreKicked", 5, 0, random(170, 190), 2, random(20, 40));
	Stop;
	
	Pain:
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,20,0,1);
	ND6M ABCDEFGH 2;
	Goto Spawn1;
	
	Death.ExplosiveImpact:
	TNT1 A 0;
	TNT1 A 0 A_ChangeLinkFlags(false);
	TNT1 A 0 ThrustThingZ(0,50,0,1);
	ND6M A 5;
	ND6M ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Goto Landz;
	Landz:
	
	XDT5 I 0 A_SpawnItem("Gib_VoidSpectreArm");
	Stop;
}}

CLASS XDeathDemonArm: XDeathBullArm1 { 
	Default {
    Scale 1.1;
	}
}

CLASS XDeathVoidSpectreKicked: XDeathVoidSpectreArm { 
	Default {
+ACTIVATEMCROSS
+ACTIVATEIMPACT
+CANUSEWALLS
	}
}

CLASS XDeathBullArm1Kicked: XDeathBullArm1 { 
	Default {
+ACTIVATEMCROSS
+ACTIVATEIMPACT
+CANUSEWALLS
	}
}

CLASS GibDemonArmPart: gibs_base { 
	Default {
    Scale 1.1;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	HND8 Z -1;
        Stop;
		
    Death:
HND8 Z 1;
       Loop;
}}

CLASS GibDemonHand: gibs_base { 
	Default {
 
    Scale 0.8;
	}
    States
    {
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_QueueCorpse;
	HND8 Y -1;
       Loop;
    Death:
HND8 Y 1;
       Loop;
}}


CLASS XDeathBullLeg12: XDeathArm1 { 
	Default {
 
    Scale 1.1;
    Speed 8;
	Gravity 0.4;
bounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		LEG8 ABCDEFGH 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		LEG8 I 1;
		LEG8 I 0 A_SpawnItem("Gib_DemonLeg");
		Stop;
	}
}

CLASS Gib_DemonLeg: Limbs_Base { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		LEG8 GH 2;
		Goto Spawn1;
	Spawn1:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG8 I 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		LEG8 I -1;
		Stop;
		
		
	Death.plasma:
    TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonLeg", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:    
		TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("GibDemonLegPart", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GibDemonPaw", 0, 0, random(0, 180), 2, random(0, 180));
		Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		LEG8 A 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathBullLeg12", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		LEG8 ABCDEFGH 2;
		Goto Spawn1;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		LEG8 A 5;
		LEG8 ABCDEFGH 5;
		XDT5 I 0 A_SpawnItem("Gib_DemonLeg");
Stop;}}
	
CLASS XDeathBloodDemonLeg12: XDeathArm1 { 
	Default {
	
	Scale 1.1;
	Speed 8;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		M3G7 ABCDEFGH 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		M3G7 I 1;
		M3G7 I 0 A_SpawnItem("Gib_BloodDemonLeg");
		Stop;
	}
}

CLASS Gib_BloodDemonLeg: Limbs_Base { 
	Default {
	Scale 1.1;
	}
	States
	{
	Spawn:
		M3G7 I 0;
		M3G7 I 0 A_Jump(128, "Spawn2");
		Goto Spawn1;
		
	Spawn1:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		M3G7 I 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		M3G7 I -1;
		Stop;
		
	Spawn2:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		M3G7 J 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		M3G7 J -1;
		Stop;
		
	Death.plasma:
    TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonLeg", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:    
		TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("GibDemonLegPart", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("GibDemonPaw", 0, 0, random(0, 180), 2, random(0, 180));
		Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		M3G7 A 0 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathBloodDemonLeg12", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		M3G7 ABCDEFGH 2;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		M3G7 A 5;
		M3G7 ABCDEFGH 5;
		XDT5 I 0 A_SpawnItem("Gib_BloodDemonLeg");
Stop;}}

CLASS XDeathVoidSpectreLeg: XDeathArm1 { 
	Default {
	
	Scale 1.1;
	Speed 8;
	Gravity 0.4;
	BounceFactor 0.4;
	Decal "GreenBloodSplat";
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		L3G8 ABCDEFGH 4 a_spawnprojectile("brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		L3G8 H 1;
		L3G8 I 0 A_SpawnItem("Gib_VoidSpectreLeg");
		Stop;
	}
}

CLASS Gib_VoidSpectreLeg: Limbs_Base { 
	Default {
	
	Scale 1.1;
	BloodType "PB_blood", "GreenAxeBlood", "GreenAxeBlood";
	BloodColor "DarkGreen";
	}
	States
	{
	Spawn:
		L3G8 GH 2;
	Spawn1:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		L3G8 H 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		L3G8 H -1;
		Stop;
		
		
	Death.plasma:    TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonLeg", 32, 0, random(0, 360), 2, random(0, 160));        
	Stop;
	Death:    
		TNT1 AAAA 0 a_spawnprojectile("brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 180), 2, random(0, 180));
		TNT1 A 0 a_spawnprojectile("XDeath2", 0, 0, random(0, 180), 2, random(0, 180));
		Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		L3G8 A 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathVoidSpectreLeg", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		L3G8 ABCDEFGH 2;
		Goto Spawn1;
		
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_ChangeLinkFlags(false);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		L3G8 A 5;
		L3G8 ABCDEFGH 5;
		XDT5 I 0 A_SpawnItem("Gib_VoidSpectreLeg");
Stop;}}

CLASS GibDemonLegPart: gibs_base { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG8 Z -1;
		Stop;
	Death:
		LEG8 Z 1;
		Loop;
}}

CLASS GibDemonPaw: gibs_base { 
	Default {
	
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		LEG8 Y 1;
		Stop;
	Death:
		LEG8 Y 1;
		Loop;
}}



CLASS XDeathPinkyDemonHead: XDeathBullArm1 { 
	Default {
	
	-CLIENTSIDEONLY;
	Speed 10;
	Scale 1.3;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		DEMH AB 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		TNT1 A 0 {self.bTHRUSPECIES = false;}
		DEMH CDEFGH 3;// a_spawnprojectile("ShortWallRedBlood", 0, 0, 0, 2)//
		Loop;
	Death:
		DEMH I 1;
		DEMH I 1 A_SpawnItem("PinkyDemonHead",0,0,0,1);
		Stop;
	}
}



CLASS PinkyDemonHead: Limbs_Base { 
	Default {
	
	damagefactor "Kick", 9.0;
	damagefactor "Melee", 9.0;
	damagefactor "SuperPunch", 9.0;
	-CLIENTSIDEONLY;
	Radius 10;
	
	Mass 12;
	Health 60;
	Scale 1.5;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		DEMH I 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		DEMH I -1;
		Stop;
		
	Death:
		TNT1 AAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_SpawnItem("MeatDeathSmall");
		TNT1 AA 0 a_spawnprojectile("XDeathBrain1", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBrain2", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 10, random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 10, random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 10, 0, random(0, 360), 2, random(30, 90));
		TNT1 AA 0 a_spawnprojectile("PinkyHeadPiece", 12, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("PinkyJaw", 12, 0, random(0, 360), 2, random(0, 160));
		Stop;
	Death.Trample:
	Crush:
		//TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
		TNT1 AAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		DEMH I 5;
		DEMH I 9009;
		Stop;
	Death.plasma:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL A 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0;
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		DEMH A 1 A_Pain;
		DEMH A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeathPinkyDemonHeadKicked", 5, 0, random(170, 190), 2, random(20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		DEMH ACEGI 3;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		DEMH ABCDEFGH 3;
		DEMH I 0 A_SpawnItem("PinkyDemonHead");
		Stop;
		
}}



CLASS XDeathPinkyDemonHeadKicked: XDeathPinkyDemonHead { 
	Default {
	
	-BOUNCEONACTORS;
	Damage 4;
	Speed 13;
	Scale 1.3;
	BounceFactor 0.4;
	}
}


CLASS XDeathDemonHead : pb_blood_and_gore_base { 
	Default {
 
    Radius 8;
    Height 8;
    Scale 0.8;
	Speed 10;
	Mass 1;
    gravity 0.5;
	Decal "BrutalBloodSplat";
bounceFactor 0.4;
	BounceCount 5;
	+DOOMBOUNCE;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		DEMH ABCDEF 7 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_SpawnItem("Gib_DemonHead");
		Stop;
	}
}

CLASS Gib_DemonHead: Limbs_Base { 
	Default {
	
	Scale 0.9;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "Spawn2");
	Stay:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		DEMH I -1;
		Stop;
		
	Spawn2:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		DEMH J -1;
		Stop;
		
	Death.plasma:
    TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:    
		TNT1 A 0 A_SpawnItem("MeatDeathSmall");
		TNT1 AA 0 a_spawnprojectile("XDeathBrain1", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBrain2", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 10, random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 10, random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 10, 0, random(0, 360), 2, random(30, 90));
		TNT1 AA 0 a_spawnprojectile("PinkyHeadPiece", 12, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("PinkyJaw", 12, 0, random(0, 360), 2, random(0, 160));
		
		Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		HND3 A 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathDemonHead", 5, 0, random(170, 190), 2, random(20, 40));
Stop;}}
	
CLASS XDeathBloodDemonHead : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Scale 0.8;
	Speed 10;
	Mass 1;
	gravity 0.5;
	Decal "BrutalBloodSplat";
	BounceFactor 0.4;
	BounceCount 5;
	+DOOMBOUNCE;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		M3G6 ABCDEFGH 7 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_SpawnItem("Gib_BloodDemonHead");
		Stop;
	}
}

CLASS Gib_BloodDemonHead: Limbs_Base { 
	Default {
	
	Scale 0.9;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "Spawn2");
	Stay:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		M3G6 I -1;
		Stop;
		
	Spawn2:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		M3G6 J -1;
		Stop;
		
	Death.plasma:
    TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:    
		TNT1 A 0 A_SpawnItem("MeatDeathSmall");
		TNT1 AA 0 a_spawnprojectile("XDeathBrain1", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBrain2", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 10, random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 10, random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 10, 0, random(0, 360), 2, random(30, 90));
		TNT1 AA 0 a_spawnprojectile("PinkyHeadPiece", 12, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("PinkyJaw", 12, 0, random(0, 360), 2, random(0, 160));
		
		Stop;
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		M3G6 A 0 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathBloodDemonHead", 5, 0, random(170, 190), 2, random(20, 40));
Stop;}}

CLASS XDeathVoidSpectreHead : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Scale 0.8;
	Speed 10;
	Mass 1;
	gravity 0.5;
	Decal "BrutalBloodSplat";
	BounceFactor 0.4;
	BounceCount 5;
	+DOOMBOUNCE;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		E3G9 ABCDEF 7 a_spawnprojectile("brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_SpawnItem("Gib_VoidSpectreHead");
		Stop;
	}
}

CLASS Gib_VoidSpectreHead: Limbs_Base { 
	Default {
	
	Scale 0.9;
	}
	States
	{
	Spawn:
		TNT1 A 0;
	Stay:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		E3G9 I -1;
		Stop;
		
		
	Death.plasma:
    TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
	Stop;
	Death:    
		TNT1 AA 0 a_spawnprojectile("XDeath1", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 10, random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 10, random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 10, 0, random(0, 360), 2, random(30, 90));
		TNT1 AA 0 a_spawnprojectile("VoidSpectreHeadPiece", 12, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathVoidSpectreEyeball", 12, 0, random(0, 360), 2, random(0, 160));
		Stop;
		
	Death.Kick:
	Death.Melee:
	Death.SuperPunch:
		HND3 A 1 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("XDeathVoidSpectreHead", 5, 0, random(170, 190), 2, random(20, 40));
Stop;}}


CLASS DyingDemon : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Speed 0;
	Mass 6;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+DONTSPLASH;
	+CLIENTSIDEONLY;
	+FORCEXYBILLBOARD;
	}
	States
	{
	Spawn:
		SARH AAABBBCCCDDDDDDDDDDDDDDD 4 {pb_blood_and_gore_event.big_blood(self);}
		//TNT1 A 0 A_SpawnItem("DeadDemonNoHead", 1);
		Stop;
	}
}


CLASS XDeathHalfDemon : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Scale 1.0;
	Speed 6;
	Mass 4;
	Decal "BrutalBloodSplat";
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		SARC E 12;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		SARC F 1 A_SpawnItem("Gib_HalfDemon",0,0,0,1);
		TNT1 A 0;
		Stop;
	}
}

CLASS Gib_HalfDemon: gibs_base { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		SARC F 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		SARC F -1;
Stop;    }}
	   
CLASS XDeathHalfVoidSpectre : pb_blood_and_gore_base { 
	Default {
	
	Radius 8;
	Height 8;
	Scale 1.0;
	Speed 6;
	Mass 4;
	Decal "GreenBloodSplat";
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		ND3M X 12;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		ND3M Y 1 A_SpawnItem("Gib_HalfVoidSpectre",0,0,0,1);
		TNT1 A 0;
		Stop;
	}
}

CLASS Gib_HalfVoidSpectre: gibs_base { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		ND3M Y 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		ND3M Y -1;
Stop;    }}



CLASS BloodDemonXDeath : pb_blood_and_gore_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAA 0 a_spawnprojectile("CeilBloodSpot", 0, 0, random(0, 360), 2, random(50, 130));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4b", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
		TNT1 A 0 a_spawnprojectile("XDeathStomach", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBloodDemonLeg12", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBloodDemonArm1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBloodDemonHead", 42, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 A 1;
		TNT1 A 2;
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		Stop;
		
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAA 0 {pb_blood_and_gore_event.gore_spawner_2(self);}
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(20, 90));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("SuperGoreMist", 24, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAAAA 0 {pb_blood_and_gore_event.gore_spawner_2(self);}
		Stop;
}
}



CLASS XDeathBurnedDemonArm : XDeathBurnedLeg { 
States
{
	Spawn:
		CARB H 10 a_spawnprojectile("ExplosionSmoke",0,0,180,2);
		Loop;
	Death:
		CARB HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 14 a_spawnprojectile("ExplosionSmoke", 1, 0, random(0, 360), 2, random(0, 160));
		CARB H -1;
		Stop;
}
}

CLASS XDeathBurnedDemonLeg : XDeathBurnedLeg { 
States
{
	Spawn:
		CARB I 10 a_spawnprojectile("ExplosionSmoke",0,0,180,2);
		Loop;
	Death:
		CARB IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII 14 a_spawnprojectile("ExplosionSmoke", 1, 0, random(0, 360), 2, random(0, 160));
		CARB I -1;
		Stop;
}
}


CLASS PoorMeanDemonLostHisArm : switchabledecoration { 
	Default {
	
	Health 110;
	+NOPAIN;
	-COUNTKILL;
	+SHOOTABLE;
	}
	States
	{
	Spawn:
		S4AR J 1;
		TNT1 A 0 A_Pain;
		S4AR JJJJJJJJ 4 a_spawnprojectile("Brutal_FlyingBlood", 42, 0, random(0, 360), 2, random(0, 45));
		TNT1 A 0 A_Pain;
		S4AR JJJJJJJJ 4 a_spawnprojectile("Brutal_FlyingBlood", 42, 0, random(0, 360), 2, random(0, 45));
		TNT1 A 0 A_Pain;
		S4AR JJJ 4 a_spawnprojectile("Brutal_FlyingBlood", 42, 0, random(0, 360), 2, random(0, 45));
		Goto Colapse;
		
	Death.Shotgun:
	Death.Cutless:
	Death:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AA 0 a_spawnprojectile("XDeathBrain1", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBrain2", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", random(45, 55), random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AA 0 a_spawnprojectile("XDeath2", random(45, 55), random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 a_spawnprojectile("BaronHeadPiece", 52, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("PinkyJaw", 52, 0, random(0, 360), 2, random(0, 160))
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		S4AR GGGGGGG 2 a_spawnprojectile("Brutal_FlyingBlood", 40, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_SpawnItem("healthbonus");
		S4AR HHHHHHHHH 2 a_spawnprojectile("Brutal_FlyingBlood", 30, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		S4AR IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII 2 a_spawnprojectile("Brutal_FlyingBlood", 20, 0, random(0, 360), 2, random(30, 110));
		S4AR I -1;
		stop;
		
		
	Colapse:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		S4AR BCDEF 5;
		TNT1 A 0 A_SpawnItem("DeadMeanDemonNoArm", 5);
		stop;
}
}



CLASS PoorPinkyLostHisArm: Demon { 
	Default {
	
	Health 50;
	+NOPAIN;
	-COUNTKILL;
	+SHOOTABLE;
	}
	States
	{
	PutAFight:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItemEx("ArmlessDemon",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0;
		stop;
	Spawn:
		SAAR J 1;
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_Jump(32, "Colapse");
		SAAR JJJJ 4 a_spawnprojectile("Brutal_FlyingBlood", 42, 0, random(0, 360), 2, random(0, 45));
		TNT1 A 0 A_Jump(96, "PutAFight");
		SAAR JJJJ 4 a_spawnprojectile("Brutal_FlyingBlood", 42, 0, random(0, 360), 2, random(0, 45));
		TNT1 A 0 A_Pain;
		SAAR JJJJJJJJ 4 a_spawnprojectile("Brutal_FlyingBlood", 42, 0, random(0, 360), 2, random(0, 45));
		TNT1 A 0 A_Pain;
		SAAR JJJ 4 a_spawnprojectile("Brutal_FlyingBlood", 42, 0, random(0, 360), 2, random(0, 45));
		Goto Colapse;
		
	Death.Shotgun:
	Death.Cutless:
	Death:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AA 0 a_spawnprojectile("XDeathBrain1", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBrain2", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", random(45, 55), random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AA 0 a_spawnprojectile("XDeath2", random(45, 55), random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 a_spawnprojectile("PinkyHeadPiece", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("PinkyJaw", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("BloodMist", 50, 0, random(0, 360), 2, random(30, 90));
		SAAR GGGGGGG 2 a_spawnprojectile("Brutal_FlyingBlood", 40, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_SpawnItem("healthbonus");
		SAAR HHHHHHHHH 2 a_spawnprojectile("Brutal_FlyingBlood", 30, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		SAAR IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII 2 a_spawnprojectile("Brutal_FlyingBlood", 20, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("DeadDemonSAARI");
		stop;
		
		
	Colapse:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		SAAR BCDEF 5;
		TNT1 A 0 A_SpawnItem("DeadDemonNoArm", 5);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		stop;
}
}

