
CLASS DeadSpider: pb_blood_and_gore_base
{ 
Default
{	
	Radius 20;
	Height 10;
	Scale 1.3;
	+SHOOTABLE;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CORPSE;
	-SOLID;
	+THRUACTORS;
	damagefactor "Crusher", 50.0;
	Mass 1000;
	Health 200;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
}

States
{
	Spawn:
		BSPI P -1;
	Stop;

	Raise:
		TNT1 A 2 A_spawnprojectile("RealFlameTrailsSmall", 6, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 2 A_spawnprojectile("RealFlameTrailsSmall", 6, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 0 A_SpawnItem("TeleportFog");
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("pb_Arrachnotron");
	Stop;

	Death.Cut:
	Death.Cutless:
	Death:
		TNT1 A 0 A_SpawnItemEx("GibsZ",-3,-3);
		TNT1 A 0 A_SpawnItemEx("GibsZ",3,3);
		TNT1 AAA 0 A_spawnprojectile("SpiderPart1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 A_spawnprojectile("SpiderPart2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 A_spawnprojectile("XDeathSpiderNew1", 32, 0, random(0, 360), 2, random(60, 90));
		TNT1 AAA 0 A_spawnprojectile("SpiderLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 A_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 A_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 A_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 A_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
	Stop;
}

}
	 
CLASS DeadSpider2: DeadSpider { 
States
    {
	Spawn:
	BSPI Y -1;
	Stop;
}}

CLASS XDeadSpider: DeadSpider { 
	Default {
	Scale 1.0;
Health 200;	}
 States{Spawn:
	XBSP D -1;
	Stop   ;
Death.Cut:        Death.Cutless:	        Death:
	TNT1 AAA 0 A_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 A_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 A_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAA 0 A_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
Stop;}}


CLASS RapedArachnotron: DeadSpider { 
Default {
	Scale 1.0;
}
States
{
	Spawn:
        ARF1 O -1;
	Stop;
}

}
	
	
CLASS NoLegsSpider: DeadSpider { 
Default
{
	Scale 1.0;
	+NOBLOOD;
	Health 300;
}

States
{
	Spawn:
        ARF2 H -1;
	Stop;
}

}	


CLASS SpiderPart1 : ACTOR { 
Default
{
    Radius 1;
    Height 8;
    Speed 12;
    Scale 1.3;
	Mass 1;
    +NOBLOCKMAP
	+MISSILE
    +NOTELEPORT
    +MOVEWITHSECTOR
    +CLIENTSIDEONLY
    +RIPPER
    +BLOODLESSIMPACT 
	damagetype "Blood";
    SeeSound "misc/xdeath4";
    DeathSound "misc/xdeath1";
	Decal "BloodSuper";
}

States
{
    Spawn:
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
        ID22 ABCD 2 {pb_blood_and_gore_event.big_blood(self);}
	Loop;

	Death:
        ID22 E 1 A_SpawnItem("pb_Blood_Spot",0,0,0,1);
        ID22 E -1;
	Stop;
        TNT1 A 1;
     Splash:
		TNT1 A 0;
	Stop;
}

}


CLASS SpiderPart2 : ACTOR { 
Default
{
    Radius 1;
    Height 8;
    Speed 12;
    Scale 2.0;
	Mass 1;
    +NOBLOCKMAP;
	+MISSILE
    +NOTELEPORT
    +MOVEWITHSECTOR
    +CLIENTSIDEONLY
    +RIPPER
    +BLOODLESSIMPACT 
    +DOOMBOUNCE
	bounceFactor 0.5;
	damagetype "Blood";
	SeeSound "misc/xdeath4";
	DeathSound "misc/xdeath1";
	Decal "BloodSuper";
}

States
{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
		ID22 ABCD 2 {pb_blood_and_gore_event.big_blood(self);}
	Loop;

	Death:
		ID22 F 1 A_SpawnItem("pb_Blood_Spot",0,0,0,1);
		ID22 F -1;
	Stop;
		TNT1 A 1;
	Splash:
		TNT1 A 0;
	Stop;
}

}


CLASS CrawlingDyingSpider : ACTOR { 
Default {
	Radius 12;
	Height 24;
	Speed 9;
	Health 100;
	PainSound "SP_CRAWL";
	damagefactor "Kick", 0.1;
	damagefactor "Melee", 0.1;
	damagefactor "SuperPunch", 0.1;
	damagefactor "SuperKick", 0.1;
	damagefactor "Extremepunches", 0.1;
	PainChance "Kick", 255;
	PainChance "SuperKick", 255;
	PainChance "SuperPunch", 255;
	PainChance "Extremepunches", 255;
	PainChance 255;
	damagefactor "trample", 2.0;
	+SHOOTABLE;
	+FLOORCLIP;
	//+NOBLOCKMAP
	+LOOKALLAROUND;
	+FRIGHTENED;
	+SOLID;
}
States
{
	Spawn:
		NAHC B 1 A_Look();
	See:
		NAHC ABCD 10 A_Chase();
		NAHC A 0 A_Pain();
		TNT1 A 0 A_SpawnItemEx("Brutal_FlyingBlood", 0, 0, 10, 0, 0);
		//TNT1 A 0 A_GiveInventory("DeathTimer1", 1);
		//TNT1 A 0 A_JumpIfInventory("DeathTimer1", 12, "GotoDeath");
	Loop;
		
	GotoDeath:
		TNT1 A 0;
		TNT1 A 0 {self.bNOPAIN = true;}
		NAHC EFGH 5;
		NAHC H -1;
	Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAAAAAAAAA 0 A_spawnprojectile("SmallBrainPiece", 10, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 A_spawnprojectile("XDeath1", 10, 0, random(0, 360), 2, random(0, 160));
		NAHC IJKLMN 5;
		NAHC N -5;
	Stop;

	Pain.SuperPunch:
	Pain.SuperKick:
	Pain.Kick:
	Pain.Extremepunches:
		TNT1 A 0 A_FaceTarget();
		NAHA A 1 A_Pain();
		TNT1 A 0 ThrustThing(angle*256/360+128, 5, 0, 0);
	Pain.ExplosiveImpact:
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		NAHA A 2 A_FaceTarget();
	Fly:
		NAHA ABCDEFGH 3 A_CheckFloor("See");
		tnt1 a 0 A_JumpIf(vel.z == 0, "See");
		TNT1 A 0;
	Loop;
}

}


CLASS ArachnoTurretFrame : ACTOR { 
Default {
	Radius 32;
	Height 24;
	Health 20;
	DamageFactor "Fatality", 2.0;
	+SHOOTABLE;
	+SOLID;
	+FLOORCLIP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CORPSE;
	
	}
	States
	{
	Spawn:
		ARF2 Y 6 A_spawnprojectile("ExplosionSmoke", 30, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0
		{
			A_PlaySound("Sparks/Spawn");
			for(int i = 0; i < 30; i++)
			{a_spawnprojectile("pb_Spark", 0.0, 0, random(0, 360), 2, random(67, 113));}
		}
		TNT1 A 0 A_SpawnItem("ShoqueAzul", 0, 17);
		ARF2 Z 6 A_spawnprojectile("ExplosionSmoke", 30, 0, random(0, 360), 2, random(70, 110));
		ARF2 YY 6 A_spawnprojectile("ExplosionSmoke", 30, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0
		{
			A_PlaySound("Sparks/Spawn");
			for(int i = 0; i < 30; i++)
			{a_spawnprojectile("pb_Spark", 0.0, 0, random(0, 360), 2, random(67, 113));}
		}
		TNT1 A 0 A_SpawnItem("ShoqueAzul", 0, 17);
		ARF2 Z 6 A_spawnprojectile("ExplosionSmoke", 30, 0, random(0, 360), 2, random(70, 110));
		ARF2 YY 2 A_spawnprojectile("ExplosionSmoke", 30, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0
		{
			A_PlaySound("Sparks/Spawn");
			for(int i = 0; i < 30; i++)
			{a_spawnprojectile("pb_Spark", 0.0, 0, random(0, 360), 2, random(67, 113));}
		}
		TNT1 A 0 A_SpawnItem("ShoqueAzul", 0, 17);
		ARF2 Z 6 A_spawnprojectile("ExplosionSmoke", 30, 0, random(0, 360), 2, random(70, 110));
		ARF2 YY 6 A_spawnprojectile("ExplosionSmoke", 30, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0
		{
			A_PlaySound("Sparks/Spawn");
			for(int i = 0; i < 30; i++)
			{a_spawnprojectile("pb_Spark", 0.0, 0, random(0, 360), 2, random(67, 113));}
		}
		TNT1 A 0 A_SpawnItem("ShoqueAzul", 0, 17);
		ARF2 Z 6 A_spawnprojectile("ExplosionSmoke", 30, 0, random(0, 360), 2, random(70, 110));
		ARF2 YY 4 A_spawnprojectile("ExplosionSmoke", 30, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0
		{
			A_PlaySound("Sparks/Spawn");
			for(int i = 0; i < 30; i++)
			{a_spawnprojectile("pb_Spark", 0.0, 0, random(0, 360), 2, random(67, 113));}
		}
		TNT1 A 0 A_SpawnItem("ShoqueAzul", 0, 17);
		ARF2 Y 6 A_spawnprojectile("ExplosionSmoke", 30, 0, random(0, 360), 2, random(70, 110));
		ARF2 ZZ 6 A_spawnprojectile("ExplosionSmoke", 30, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0
		{
			A_PlaySound("Sparks/Spawn");
			for(int i = 0; i < 30; i++)
			{a_spawnprojectile("pb_Spark", 0.0, 0, random(0, 360), 2, random(67, 113));}
		}
		TNT1 A 0 A_SpawnItem("ShoqueAzul", 0, 17);
		ARF2 Z 6 A_spawnprojectile("ExplosionSmoke", 30, 0, random(0, 360), 2, random(70, 110));
		ARF2 YY 2 A_spawnprojectile("ExplosionSmoke", 30, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0
		{
			A_PlaySound("Sparks/Spawn");
			for(int i = 0; i < 30; i++)
			{a_spawnprojectile("pb_Spark", 0.0, 0, random(0, 360), 2, random(67, 113));}
		}
		TNT1 A 0 A_SpawnItem("ShoqueAzul", 0, 17);
		ARF2 Z 1 A_spawnprojectile("ExplosionSmoke", 30, 0, random(0, 360), 2, random(70, 110));
		TNT1 A 0 A_SpawnItemEx("NoLegsSpider", 0, 1, 1, 1, 1);
	Stop;
		
	Death.Fatality:
		////TNT1 A 0 A_GiveToTarget("ArachnoGunAmmo", 50)
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("ArachnotronTurret", 1);
		//TNT1 A 0 A_GiveToTarget("ArachnoGun", 1);
	Stop;

	}
}