//Detailed Death Animations. You can still shoot them as they fall to the ground, and after.
CLASS ZombieMan_DeathMinorLeg : ACTOR { 
Default {
		
	Radius 16;
	Height 40;
	Health 50;
	BloodType "PB_blood", "BloodSPlatterReplacer", "SawBlood";
	PainSound "";
	DeathSound "grunt/death";
	PainChance 0;
	Mass 999999;

	-SOLID;
	+SHOOTABLE;
	+NORADIUSDMG;
	+FLOORCLIP;
	+DONTSPLASH;
	+FRIENDLY;//
	Scale 1.0;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Recoil(1);
		POSS QIJK 5;
	DieNow:
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadZombieman1");
	stop;
			
	Pain:
		ZZD1 A 0;
	Goto DieNow;
			
	Death:
		TNT1 A 0 A_Jump(128, "Death2");
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		POS3 C 5 A_XScream;
		POS3 D 5 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		POS3 E 5 A_SpawnItem("DeadZombieMan_NoArm");
	stop;
			
			
	Death.Shotgun:
		TNT1 A 0;
		TNT1 A 0 {self.bSLIDESONWALLS = false;}
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		//TNT1 A 0 A_Jump(160, "DeathShotgunFly");
		TNT1 A 0 A_stop;
		TNT1 A 0 A_Pain;
		POSS H 1 A_FaceTarget;
		TNT1 A 0 A_Recoil(13);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		//TNT1 A 0 A_JumpIf(vel.y == 0, "DeathShotgunFly");
		TNT1 A 0 A_Jump(128, "DeathShotgunontheface2");
		TNT1 A 0 A_Scream;
		TNT1 A 0 a_spawnprojectile("MuchBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_NoBlocking;
		POS4 ABCD 4 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 40));
		POS4 EFGHIJ 4 A_JumpIf((vel.Y == 0), "DSFstop");
	Goto DSFstop+1;
			
	DSFstop:
		TNT1 A 0 A_stop;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 a_spawnprojectile("SuperWallRedBlood", 2, 0, random(170, 190), 2, random(0, 0));
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadZombiemanShotguntotheFace1");
	stop;
			
	DeathShotgunontheface2:
		TNT1 A 0 a_spawnprojectile("MuchBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		POS4 KLMN 4 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 40));
		POS4 OPQRST 4 A_JumpIf((vel.Y == 0), "DSFstop2");
		Goto DSFstop2+1;
			
	DSFstop2:
		TNT1 A 0 A_Explode(20,30, 0);
		TNT1 A 0 A_stop;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 a_spawnprojectile("SuperWallRedBlood", 2, 0, random(170, 190), 2, random(0, 0));
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadZombiemanShotguntotheFace2");
		stop;
			
			
	DeathShotgunFly:
	Death.Kick:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 {self.bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil(6);
		POS4 U 5 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		POS4 U 5 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		POS4 V 5 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		POS4 W 5 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 40));
		POS4 X 5 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 40));
		POS4 Y 5 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadZombieman1");
		stop;
	TakeASit:
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_PlaySound("BODYF",6);
		POS4 U 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItemEx("DeadZombieman_Slumped", 10);
		stop;
			
	Death2:
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		P05D J 6 A_XScream;
		P05D K 5 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		P05D L 4 A_SpawnItem("DeadZombieman1FG");
		stop;
			
	Death.Head:
		TNT1 A 0 A_SpawnItem("ZombiemanHeadExplode", 0, 37);
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		POSH D 5 A_XScream;
		POSH E 5 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		POSH F 5 A_SpawnItem("DeadZombieMan_NoHead");
		stop;
			
	Death.ExplosiveImpact:
	Death.ExtremePunches:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_FaceTarget;
		TNT1 A 1;
		TNT1 A 0 A_JumpIf(angle < 180, "IsFacingNorth");
		TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayRight");
		TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayLeft");
		Goto XDeath;
	IsFacingNorth:
		TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayRight");
		TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayLeft");
		Goto XDeath;
			
	BlownAwayLeft:
		TNT1 A 0;
		TNT1 A 0 A_Jump(96, "Death.Landmine");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathZombieLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(20, 90));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Xscream;
		PXSX GHIJKLM 3 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, 0, 2, 90);
		TNT1 A 0 A_CheckFloor("Land8473");
		PXSX GHIJKLMGHIJKLM 5 A_CheckFloor("Land8473");
	Land8473:
		PXSX N 0;
		TNT1 A 0 A_stop;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadZombiemanPXSXO");
		stop;
			
	BlownAwayRight:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Brains4", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathZombieLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(20, 90));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_SpawnItemEx("BloodMist", 0, 0, 50, vel.x, vel.y, vel.z, 0, SXF_ABSOLUTEvelOCITY);
		PXS2 GHIJKLM 3 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, 0, 2, 90);
		TNT1 A 0 A_CheckFloor("Land8472");
		PXS2 GHIJKLMGHIJKLM 5 A_CheckFloor("Land8472");
	Land8472:
		PXS2 N 0;
		TNT1 A 0 A_stop;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadZombiemanPXS2O");
		stop;
			
	Death.LandMine:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("PB_blood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathZombieLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("GibHand", 42, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(20, 90));
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		ID13 A 1 A_Scream;
		ID15 A 9;
		ID15 BCD 9 A_CheckFloor("Dead.Landmine");
		ID15 DDDDD 9 A_CheckFloor("Dead.Landmine");
		TNT1 A 0 A_PlaySound("BODYF",6);
		ID15 E 1 A_SpawnItem("VeryFuckedUpBrutalizedZombiemanLeg2");
		stop;
			
	Dead.ExplosiveImpact:
		TNT1 AAAA 0 A_SpawnItem("Blood");
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_Explode(25,150, damagetype:"MonsterKnocked");
		ID13 G 1 A_SpawnItem("VeryFuckedUpBrutalizedZombiemanLeg");
		stop;
			
	Dead.Landmine:
		TNT1 AAAA 0 A_SpawnItem("Blood");
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_Explode(25,150, damagetype:"MonsterKnocked");
		ID15 E 1 A_SpawnItem("VeryFuckedUpBrutalizedZombiemanLeg2");
		stop;
			
	Death.SSG:
		ZZD1 E 1 A_Pain;
		ZZD1 E 1 A_FaceTarget;
		//TNT1 A 0 a_spawnprojectile("MeatDeath", 0, 0, random(0, 360), 2, random(0, 160))
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AAA 0 bright a_spawnprojectile("SuperGoreSpawner", 35, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("XDeathArm1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathZombieManHead", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		ZZD1 EEFFGH 6;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadZombiemanJustLegsAreLeft2");
		stop;
			
	XDeath:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("ZombieXDeath", 0, 0, random(0, 360), 2, random(0, 160));
		stop;
}}

CLASS ZombieMan_DeathMirror: ZombieMan_DeathMinorLeg { 
States
{
	Spawn:
		TNT1 A 0 A_Recoil(1);
		POSS MNOP 5;
	DieNow:
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadZombieman1F");
		stop;
}
}

CLASS ZombieMan_DeathOther2: ZombieMan_DeathMinorLeg { 
States
{
	Spawn:
		TNT1 A 0 A_Recoil(1);
		PSSR A 6 ;
		TNT1 A 0 a_spawnprojectile("MuchBlood", 36, 0, random(0, 360), 2, random(0, 160));
		PSSR BCD 6;
	DieNow:
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		PSSR E 1 A_SpawnItem("DeadZombieMan_FacingFront");
		stop;
			
	Death:
		TNT1 A 0 A_JumpIfHealthLower(-50, "Death.Blast");
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		ZZD2 BCD 5 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 40));
		ZZD2 D 1 A_SpawnItem("DeadZombieMan_NoArmFront");
		stop;
			
	Death.Shotgun:
		TNT1 A 0 A_Jump(42, "Death.Shotgunontheface");
		TNT1 A 0 A_JumpIfCloser(80, "Death.Blast");
		TNT1 A 0 A_JumpIfCloser(320, "Death.Shotgunontheface");
		Goto Death;
			
	Death.Shotgunontheface:
		TNT1 A 0;
		TNT1 A 0 {self.bSLIDESONWALLS = false;}
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		//TNT1 A 0 A_Jump(160, "DeathShotgunFly");
			
		TNT1 A 0 A_stop;
		TNT1 A 0 A_Pain;
		POSS H 1 A_FaceTarget;
		TNT1 A 0 A_Recoil(13);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		TNT1 A 0 A_JumpIf(vel.y == 0, "DeathShotgunFly");
		TNT1 A 0 A_Jump(128, "DeathShotgunontheface2");
		TNT1 A 0 A_Scream;
		TNT1 A 0 a_spawnprojectile("MuchBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_NoBlocking;
		POS4 ABCD 4 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 40));
		POS4 EFGHIJ 4 A_JumpIf((vel.Y == 0), "DSFstop");
		Goto DSFstop+1;
			
	DSFstop:
		TNT1 A 0 A_Explode(20,30, 0);
		TNT1 A 0 A_stop;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 a_spawnprojectile("SuperWallRedBlood", 2, 0, random(170, 190), 2, random(0, 0));
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadZombiemanShotguntotheFace1");
		stop;
			
	DeathShotgunontheface2:
		TNT1 A 0 a_spawnprojectile("MuchBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		POS4 KLMN 4 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 40));
		POS4 OPQRST 4 A_JumpIf((vel.Y == 0), "DSFstop2");
		Goto DSFstop2+1;
			
	DSFstop2:
		TNT1 A 0 A_Explode(20,30, 0);
		TNT1 A 0 A_stop;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 a_spawnprojectile("SuperWallRedBlood", 2, 0, random(170, 190), 2, random(0, 0));
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadZombiemanShotguntotheFace2");
		stop;
			
			
	DeathShotgunFly:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0 {self.bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil(6);
		POS4 U 5 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		POS4 U 5 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		POS4 V 5 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		POS4 W 5 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 40));
		POS4 X 5 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 40));
		POS4 Y 5 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadZombieman1");
		stop;
	TakeASit:
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 6, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_PlaySound("BODYF",6);
		POS4 U 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItemEx("DeadZombieman_Slumped", 10);
		stop;
			
	Death.Blast:
	Death.Railgun:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Jump(128, "Death.Blast2");
		TNT1 A 0 A_Scream;
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("BloodMist", 40, 0, random(0, 360), 2, random(30, 90));
		ZXZ1 A 0 A_stop;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		ZXZ1 CCCC 3 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(10, 40));
		ZXZ1 DD 3 a_spawnprojectile("Brutal_FlyingBlood", 6, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadZombieMan_StomachExploded");
		stop;
			
	Death.Blast2:
		TNT1 A 0 A_XScream;
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 42, 0, random(0, 360), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("Xdeath3", 16, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("Xdeath2", 16, 0, random(130, 210), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("BloodMist", 40, 0, random(0, 360), 2, random(30, 90));
		ZXZ2 A 0 A_stop;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		ZXZ2 GGGGG 3 a_spawnprojectile("Brutal_FlyingBlood", 31, 0, random(0, 360), 2, random(10, 40));
		ZXZ2 HHHH 3 a_spawnprojectile("Brutal_FlyingBlood", 26, 0, random(0, 360), 2, random(10, 40));
		ZXZ2 II 3 a_spawnprojectile("Brutal_FlyingBlood", 6, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadZombieMan_BlastedMirrored");
		stop;
}
}

CLASS ZombieMan_DeathOther: ZombieMan_DeathMinorLeg { 
States
{
	Spawn:
		PNDT V 5 a_spawnprojectile("MuchBlood", 40, 0, random(0, 360), 2, random(0, 160));
		PNDT W 5;
		TNT1 A 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		PNDT X 5;
		PNDT Y 5;
	DieNow:
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		PNDT Z 1 A_SpawnItem("Zombieman_DeathPNDT");
		stop;
			
	Death:
		TNT1 A 0 A_JumpIfHealthLower(-70, "Death.SSG");
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 30, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		PND1 X 5 A_XScream;
		PND1 Y 5 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		PND1 Z 5 A_SpawnItem("DeadZombieMan_NoArm3");
		stop;
			
	Death.SSG:
	Death.Blast:
		PND2 W 3 A_XScream;
		PND2 X 5 A_NoBlocking;
		PND2 Y 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		PND2 Z 1 A_SpawnItem("DeadZombieMan_Topless");
		stop;
}
}

CLASS ZombieMan_DeathActionMovie: ZombieMan_DeathMinorLeg { 
Default {
	Health 45;
}
States
{
	Spawn:
		TNT1 A 0 A_Recoil(1);
		12DG A 5;
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 24, 5, -20, 2, -20);
		12DG B 5 BRIGHT;
		12DG CD 5;
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 a_spawnprojectile("ZombieManTracer", 24, -5, 20, 2, 30);
		12DG E 5 BRIGHT;
		TNT1 A 0;
		12DG FG 4;
		TNT1 A 0 A_NoBlocking;
		12DG HI 4;
	DieNow:
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadZombiemanLikeInActionMovie");
		stop;
	Death:
		TNT1 A 0 a_spawnprojectile("MuchBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		22DG CDEF 5;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadZombiemanLikeInActionMovie_FuckedUp");
		stop;
			
	Death.Cutless:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 a_spawnprojectile("MuchBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(150, 210), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_SpawnItem("DeadZombieMan_BottomLessActionMovie");
		12DG OOOOO 1 a_spawnprojectile("Brutal_FlyingBlood", 17, 0, random(0, 360), 2, random(0, 40));
		12DG PPPPP 1 a_spawnprojectile("Brutal_FlyingBlood", 15, 0, random(0, 360), 2, random(0, 40));
		12DG QQQQQ 1 a_spawnprojectile("Brutal_FlyingBlood", 12, 0, random(0, 360), 2, random(0, 40));
		12DG RRRRR 1 a_spawnprojectile("Brutal_FlyingBlood", 10, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		12DG SSSSSSSSSSSSS 1 a_spawnprojectile("Brutal_FlyingBlood", 7, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_SpawnItem("DeadZombieMan_ToplessActionMovie");
		stop;
}
}

CLASS ZombieMan_DeathHeadMinor: ZombieMan_DeathMinorLeg { 
States
{
	Spawn:
		POSH U 5 a_spawnprojectile("MuchBlood", 40, 0, random(0, 360), 2, random(0, 160));
		POSH V 5;
		TNT1 AA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 A 0 a_spawnprojectile("SmallBrainPiece", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		POSH W 5;
		POSH XY 5;
	DieNow:
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadZombieManMinorHead");
		stop;
			
	Death:
		TNT1 A 0 A_JumpIfHealthLower(-60, "Death.Cutless");
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 30, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		Z81D A 5 A_XScream;
		Z81D B 5;
		Z81D C 5 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		Z81D D 5 A_SpawnItem("DeadZombieMan_NoArm4");
		stop;
			
	Death.Cutless:
		TNT1 AAAAAA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 42, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 30, 0, random(0, 360), 2, random(0, 40));
		ZBLD BCDEF 5 a_spawnprojectile("Brutal_FlyingBlood", 30, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		ZBLD F 1 A_SpawnItem("DeadZombiemanZBLDF");
		stop;
			
}
}

CLASS ZombieMan_DeathMinorHead4: ZombieMan_DeathMinorLeg { 
Default {
	Health 50;
}
States
{
	Spawn:
		12DG J 5 a_spawnprojectile("MuchBlood", 40, 0, random(0, 360), 2, random(0, 160));
		12DG KL 8;
		TNT1 A 0 A_Scream;
		12DG M 6 A_NoBlocking;
	DieNow:
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadZombieManFacingFrontMinorHead");
		stop;
			
	Death:
		TNT1 A 0 A_JumpIfHealthLower(-60, "Death.Cutless");
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 30, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		ZXZ2 H 5 A_XScream;
		ZXZ2 I 5;
		Z81D J 5 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		Z81D D 5 A_SpawnItem("DeadZombieMan_BlastedMirrored");
		stop;
			
			
	Death.Head:
		TNT1 A 0 A_SpawnItem("ZombiemanHeadExplode", 0, 36);
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		ZMAD CCCCCC 2 a_spawnprojectile("Brutal_FlyingBlood", 30, 0, random(0, 360), 2, random(60, 120));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		ZMAD DDDDEEEEEEEEEEEEEEEE 2 a_spawnprojectile("Brutal_FlyingBlood", 10, 0, random(0, 360), 2, random(10, 40));
		TNT1 A 0 A_SpawnItem("DeadZombieman_NoHeadFront");
		stop;
			
	Death.Cutless:
		TNT1 AAAAAA 0 a_spawnprojectile("Instestin", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 42, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 15, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 30, 0, random(0, 360), 2, random(0, 40));
		ZBLD BCDEF 5 a_spawnprojectile("Brutal_FlyingBlood", 30, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		ZBLD F 1 A_SpawnItem("DeadZombiemanZBLDF");
		stop;
			
}
}

CLASS ZombieMan_DeathMinorHead5: ZombieMan_DeathMinorLeg { 
Default {
	Health 50;
}
States
{
	Spawn:
		PXS3 A 5 a_spawnprojectile("MuchBlood", 40, 0, random(0, 360), 2, random(0, 160));
		PXS3 BC 7;
			
		TNT1 A 0 A_Scream;
		PXS3 D 6 A_NoBlocking;
		PXS3 E 6;
	DieNow:
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		PXS3 F 1 A_SpawnItem("DeadZombieMan_PXS3");
		stop;

	Death:
	Death.Cutless:
		TNT1 A 0 A_JumpIfHealthLower(-60, "Death.Cutless");
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 30, 0, random(0, 360), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathArm1", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		ZXZ2 C 4 A_XScream;
		ZXZ2 D 4;
		ZXZ2 E 5 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("DeadZombieMan_Blasted");
		stop;
}
}
