
CLASS DeadAfrit : ACTOR { 
Default
{
	Radius 12;
	Height 12;
	+SHOOTABLE;
	-SOLID;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CORPSE;
	+USESPECIAL;
	+FLOORCLIP;
	-DONTGIB;
	//+DROPPED
	Mass 2000;
	Health 100;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
}
States
{
	Spawn:
		FRI1 E -1;
		Stop;
	Raise:
		FRI1 D 1;
		FRI1 CBA 1;
		TNT1 A 0 A_SpawnItem("pb_Afrit", 3);
		Stop;
	Death:
	XDeath:
	Crush:
	Death:
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("GibsZ");
		Stop;
	}
}



CLASS AfritXDeath : ACTOR { 
	Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFACTOR 0.5;
	BounceType "Doom";
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
	}
	States
	{
	Spawn:
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 35, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 A 0 a_spawnprojectile("XDeathAfritTorso", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathAfritHead5", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("PB_pot");
	Death:
		TNT1 A 0;
		Stop;
	}
}

//Afrit Gibs
CLASS XDeathAfritTorso: pb_blood_and_gore_base { 
Default {
	Scale 1.3;
	Speed 12;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("pb_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		G4FD ABCD 4 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("pb_Blood_Spot",0,0,0,1);
		G4FD E 1;
		HNDC A 0 A_SpawnItem("Gib_AfritTorso",0,0,0,1);
	Stop;
}

}

CLASS Gib_AfritTorso: pb_blood_and_gore_base { 
	Default {
	Scale 1.3;
	}
	States
	{
	Spawn:
		G4FD E 0 A_SpawnItem("pb_Blood_Spot",0,0,0,1);
		G4FD E -1;
		Stop;
Death.plasma: Death.Burn: Death.Flames:
	    TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
        Stop;
Death:    
	TNT1 AAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 AAAAAAA 0 a_spawnprojectile("named_BloodTr", 0, 0, random(0, 360), 2, random(0, 360));
	TNT1 A 0 a_spawnprojectile("Xdeath1", 0, 0, random(0, 360), 2, random(0, 360));
Stop;}}

CLASS XDeathAfritHead5: pb_blood_and_gore_base { 
	Default {
 
-CLIENTSIDEONLY
    Scale 1.2;
	}
    States
    {
	Spawn:
        TNT1 A 0 A_SpawnItem("pb_Blood_Spot",0,0,0,1);
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
	TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
	XH4F ABCD 6;
	Loop;
   	Death:
        TNT1 A 0 A_SpawnItem("pb_Blood_Spot",0,0,0,1);
	    XH4F A 1;
        XH4F A 1 A_SpawnItem("AfritHead",0,0,0,1);
        Stop;
}
}

CLASS AfritHead: pb_blood_and_gore_base { 
	Default {
 
	DamageFactor "Kick", 9.0;
	DamageFactor "SuperKick", 12.0;
	DamageFactor "Melee", 9.0;
	DamageFactor "SuperPunch", 9.0;
	-CLIENTSIDEONLY;
	Radius 10;
	
	Mass 12;
	Health 60;
	Scale 1.2;
	}
	States
	{
	Spawn:
		XH4F A 0 A_SpawnItem("pb_Blood_Spot",0,0,0,1);
		XH4F A -1;
		Stop;
		
	Death:
		TNT1 AAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains2", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains2", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains4", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains4", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 AAAAAA 0 a_spawnprojectile("SmallBrainPiece", 5, 0, random(0, 360), 2, random(60, 140));
		Stop;
	Death.Trample:
	Crush:
		TNT1 AAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS1 B 5;
		CRS1 B 2002;
		Stop;
	Death.plasma:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL A 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0;
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
	Death.SuperKick:
		XH4F A 1 A_Pain;
		XH4F A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeathAfritHeadKicked", 5, 0, random(170, 190), 2, random(20, 40));
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		XH4F ABCD 3;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		XH4F ABCD 6;
		XH4F I 0 A_SpawnItem("XDeathAfritHead5");
		Stop;
}}

CLASS XDeathAfritHeadKicked: XDeathAfritHead5 { 
	Default {
	
	-BOUNCEONACTORS;
	DamageType "KickBall";
	Damage 4;
	Speed 13;
	BounceFactor 0.4;
	}
}