extend class cheap_effect_base//smoke_effect
{
states
{
    ExplosionSmoke:
		TNT1 A 0 
		{
			double scal = frandom(0.2, 1);
			self.scale =(scal, scal);
		}
		smk2 AAAAAA 2 A_FadeIn(0.04);
		smk2 A 1 {tics = random(15, 40);}
    es_loop:
		smk2 A 1
        {
            alpha -= 0.01;
			if(alpha <= 0.1) setstatelabel("reset_self_condition");
        }
    loop;


	Explosion_Smoke:
		TNT1 A 0
		{
			int scal = frandom(0.1, 1.5);
			self.scale =(scal, scal);
			self.alpha = frandom(0.1, 0.5);
		}
		
		SMK3 B 50 {self.tics = random(30, 120);}
		SMK3 CDEFGHIJKLMN 1 {A_Fadeout(0.01); self.tics = random(1, 4);}
	goto reset_self_condition;


	GunFireSmoke:
		TNT1 A 0
		{
			self.alpha = frandom(0.1, 0.3);
			a_setrenderstyle(alpha, style_add);
			double scal = frandom(-0.7, 0.7);
			self.scale =(scal, scal);
		}
		SMOK ABCDEFGHIJKLMNOPQR 1 {A_FadeOut(0.010); self.tics = random(1 , 3);}
	goto reset_self_condition;


	CasingSmoke:
		TNT1 A 0
		{
			alpha = frandom(0.05, 0.11);
			double scal = frandom(0.05, 3.3);
			scale =(scal, scal);
			a_setrenderstyle(alpha, style_add);
		}
		PUF2 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 {A_FadeOut(0.005); self.tics = random(2, 5);}
	goto reset_self_condition;


	rocket_trail_darker:
		TNT1 A 0
		{
			alpha = frandom(0.5, 0.7);
			double scal = frandom(0.1, 0.3);
			scale =(scal, scal);
		}
		SMK6 BCDEFGHIJKKLLMMNN 1 A_FadeOut(0.04);
	goto reset_self_condition;
	

	BigNeoSmoke:
		TNT1 A 0
		{
			alpha = frandom(0.12, 0.5);
			double scal = frandom(1.4, 5);
			scale =(scal, scal);
		}
		SMO2 A 45;
		SMO2 Aaaaaaa 2 A_FadeOut(0.125);
	goto reset_self_condition;


	QuickSmoke:
		TNT1 A 0
		{
			alpha = frandom(0.4, 0.6);
			double scal = frandom(1.1, 1.5);
			scale =(scal, scal);
		}
 		PUFF ABCD 4;
	goto reset_self_condition;


	Soul_Trails:
		TNT1 A 0
		{
			alpha = frandom(0.4, 0.6);
			double scal = frandom(0.4, 0.6);
			scale =(scal, scal);
		}
		FRFX KLMNOP 3 BRIGHT;
	goto reset_self_condition;


	Cyber_Step:
		TNT1 A 0
		{
			alpha = frandom(0.7, 0.8);
			double scal = frandom(0.4, 0.6);
			scale =(scal, scal);
		}
		MNSM ABCDEFGHIJKLMNOPQ 1 bright;
	goto reset_self_condition;


	Barrel_explosion_Column:
		SB17 ABCDE 3 { scale.x += 0.1; scale.y += 0.1;}
		TNT1 A 0 A_JumpIf(waterlevel > 1, "reset_self_condition");
		SB17 ABCDEFGABCDEFGABCDEFGABCDEFGABCDEFGABCDEFGABCDEFGABCDEFGABCDEFGABCDEFGABCDEFGABCDEFGABCDEFGABCDEFGABCDEFGABCDEFGABCDEFG 3;
		
		SB17 ABCDEFGABCDEFGABCDEFGABCDEFGABCDEFG 3 {scale.x += 0.1; scale.y += 0.1;}
	goto reset_self_condition;


	BigBlackSmoke:
		TNT1 A 0
		{
			a_setscale(frandom(0.3, 3.4) );
		}
		SMK1 KKKKKKKK 2 A_FadeIn(0.04);
		SMK1 K 1 {tics = random(15, 50);}
		SMK1 KKKKKKKKKK 2 A_FadeOut(0.05);
	goto reset_self_condition;


	BigBlackSmokePillar:
		TNT1 A 0
		{
			alpha = frandom(0.4, 0.6);
			double scal = frandom(1.4, 1.6);
			scale =(scal, scal);
		}
		SMK5 JIHGFEDCB 2;
		SMK5 A 50;
		SMK5 BCDEFGHIJ 4;
	goto reset_self_condition;


		DB29 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1;
		DB30 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1;
		DB31 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1;
		DB33 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1;
	NewAcidExplosionSmoke:
		TNT1 A 0
		{
			double scal = frandom(1.4, 1.6);
			scale =(scal, scal);
			//Translation = "0:255=%[0,0,0]:[0.1,0.8,0]";

			a_setrenderstyle(1, style_add);
			A_PlaySound("Daedabus/impact", 1);
			int sw = random (0, 3);

			switch(sw)
			{
				case 0 : sprite = getspriteindex("DB29"); break;
				case 1 : sprite = getspriteindex("DB30"); break;
				case 2 : sprite = getspriteindex("DB31"); break;
				case 3 : sprite = getspriteindex("DB33"); break;
				default : console.printf("fucked effect"); break;
			}
		}
		"####" ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 a_fADEOUT(0.03);
	goto reset_self_condition;


	NewGroundExplosionSmoke:
		TNT1 A 0
		{
			double scal = frandom(1.4, 1.6);
			scale =(scal, scal);
		}
		DB27 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 a_fADEOUT(0.03);
	goto reset_self_condition;


	NewFireExplosionEffect:
		TNT1 A 0
		{
			double scal = frandom(1.7, 2);
			scale =(scal, scal);
		}
		EXP1 ABCDEFGHIJKLMN 2 BRIGHT a_fADEOUT(0.05);
	goto reset_self_condition;


	Shoque:
		TNT1 A 0
		{
			double scal = frandom(0.4, 0.8);
			scale =(scal, scal);
			//Translation = "0:255=%[0,0,0]:[0.1,0.8,0]";

			a_setrenderstyle(0.5, style_add);
		}
		SHOQ ABCDEFG 1 BRIGHT;
	goto reset_self_condition;


	ShoqueAzul:
		TNT1 A 0
		{
			double scal = frandom(0.4, 0.8);
			scale =(scal, scal);
			//Translation = "0:255=%[0,0,0]:[0.1,0.8,0]";

			a_setrenderstyle(0.7, style_add);
		}
		SH1K ABCDEFG 2 BRIGHT;
	goto reset_self_condition;
	

	DirtRicochet:
		tnt1 a 0
		{
			double scal = frandom(-1.9, 1.9);
			scale =(scal, scal);
		}
		TNT1 A 0 A_PlaySound("BHITDIR");
		SDRT ABCDEF 2;
	goto reset_self_condition;



	GiantLavaRicochet:
		TNT1 A 0
		{
			double scal = frandom(2, 3);
			scale =(scal, scal);
		}
		TNT1 A 0 A_PlaySound("WTREXP");
		GSPP ABCDEFGHIJKLMNOPQRS 2 BRIGHT;
		//TNT1 A 0 A_PlaySound("mountain/splash", 15)
		GSPP TUVWXYZ 2 BRIGHT;
	goto reset_self_condition;


	GiantSlimeRicochet:
		TNT1 A 0 A_PlaySound("WTREXP");
		GSPN ABCDEFGHIJKLMNOPQRS 2;
		//TNT1 A 0 A_PlaySound("mountain/splash", 15)
		GSPN TUVWXYZ 2;
		Stop;
	goto reset_self_condition;


	GiantBloodRicochet:
		TNT1 A 0 A_PlaySound("WTREXP");
		GSPB ABCDEFGHIJKLMNOPQRS 2;
		//TNT1 A 0 A_PlaySound("mountain/splash", 15)
		GSPB TUVWXYZ 2;
	goto reset_self_condition;


	Slime2Ricochet:
		TNT1 A 0 A_PlaySound("WaterBulletImpact", 0);
		//TNT1 A 0 A_RadiusGive("SludgeSplasherz", 80, RGF_PLAYERS, 1);
		SPHN ABCDE 3;
	goto reset_self_condition;


	GiantSlime2Ricochet:
		tnt1 a 0 a_setscale (3);
		TNT1 A 0 A_PlaySound("WTREXP");
		GSPS ABCDEFGHIJKLMNOPQRS 2;
		GSPS TUVWXYZ 2;
	goto reset_self_condition;

	ATBulletPuff:
		TNT1 A 0
		{
			double scal = frandom(1, 1.7);
			scale =(scal, scal);
		}
		TNT1 A 0 A_PlaySound("smallexplode");
		TNT1 AAA 0
		{
			pb_effect_event(effect_event).show_some_effect(self, "ExplosionSmoke");
		}
		EXSH A 3 BRIGHT;
	goto reset_self_condition;


		DB21 ABCDEFGHI 1 bright;
		DB23 ABCDEFGHI 1 bright;
	Plasma_Puff:
		tnt1 a 0
		{
			int ttt = random(0, 1);
			switch(ttt)
			{
				case 0 : sprite = getspriteindex("DB23"); break;
				case 1 : sprite = getspriteindex("DB21"); break;
				default : break;
			}
		}
		DB23 ABCDEFGHI 1 bright;
	goto reset_self_condition;


	HellRifle_Puff2:
		DB26 IJKLM 1 bright Light("IncinerationGlow");
		DB26 NOPQRSTUV 1 bright;
	goto reset_self_condition;


	UnmakerPuff:
		TNT1 A 0
		{
			double scal = frandom(2, 2.7);
			scale =(scal, scal);
		}
		DB60 ABCDE 1 bright Light("IncinerationGlow");
		DB60 FGHIJKLMNOPQ 1 bright;
	goto reset_self_condition;


	GreenPlasma_Puff:
		DB59 ABCDEFGHIJKLMNOPQRS 1 bright;
	goto reset_self_condition;

//class GreenPlasma_Puff_Medium: GreenPlasma_Puff
//{default{Scale 0.45; } }


	GreenPlasma_Puff_Small:
		TNT1 A 0
		{
			double scal = frandom(0.2, 0.3);
			scale =(scal, scal);
		}
		DB59 ABCDEFGHIJKLM 1 bright Light("ARMORBONUS");
		DB59 NOPQRS 1 bright;
	goto reset_self_condition;


	PuffSmoke:
		TNT1 A 0
		{
			double scal = frandom(1.2, 1.7);
			scale =(scal, scal);
		}
		PUFY ZZZCCCCCCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 1 A_FadeOut(0.02);
	goto reset_self_condition;


	LavaStep:
		tnt1 AA 0 
		{
			pb_effect_event(effect_event).show_some_effect(self, "ExplosionParticle");
		}
		TNT1 A 0 A_SetScale(0.28, 0.22);
		INFE ABCDEFGHIJKLMNOPQR 1 BRIGHT;
		INFE ST 1 BRIGHT
		{
			pb_effect_event(effect_event).show_some_effect(self, "rocket_trail_darker");
		}
	goto reset_self_condition;



	Sparks:
		TNT1 A 0
		{
			double scal = frandom(0.2, 0.7);
			scale =(scal, scal);
		}
		TNT1 A 0 A_SpawnItem("YellowFlareSmall", 0);
		TNT1 A 0 A_Jump(132, 15);
		FX58 ABCDEFGHIJ 1 bright;
	goto reset_self_condition;
		TNT1 AAAAA 0;
		FX57 ABCDEFGHIJ 1 bright;
	goto reset_self_condition;



	SiphonPuff:
		DB26 I 1;
		DB26 JKLM 1 bright Light("IncinerationGlow");
		DB26 NOPQRSTUV 1 bright;
	goto reset_self_condition;


	WaterRicochet:
		TNT1 A 0 A_PlaySound("WaterBulletImpact", 0);
		//TNT1 A 0 A_RadiusGive("WaterSplasherz", 80, RGF_PLAYERS, 1);
		SPHW ABCDE 3;
	goto reset_self_condition;



	GiantWaterRicochet:
		GSPL ABCDEFGHIJKLMNOPQRSTUVWXYZ 2;
	goto reset_self_condition;


	SlimeRicochet:
		TNT1 A 0 A_PlaySound("WaterBulletImpact", 0);
		//TNT1 A 0 A_RadiusGive("SlimeSplasherz", 95, RGF_PLAYERS, 1);
		SPHG ABCDE 3;
	goto reset_self_condition;

	SludgeRicochet:
		TNT1 A 0 A_PlaySound("WaterBulletImpact", 0);
		SPHN ABCDE 3;
	goto reset_self_condition;


	BloodRicochet:
		TNT1 A 0 A_PlaySound("WaterBulletImpact", 0);
		//TNT1 A 0 A_RadiusGive("BloodSplasherz", 95, RGF_PLAYERS, 1);
		SPHR ABCDE 3;
	goto reset_self_condition;


	LavaRicochet:
		TNT1 A 0;
		//TNT1 A 0 A_RadiusGive("LavaSplasherz", 95, RGF_PLAYERS, 1);
		SPHO ABC 4;
		SPHO DE 3;
	goto reset_self_condition;


	MicrowavePuff:
		TNT1 A 0 A_PlaySound("Weapons/YamatoExp",5);
		TNT1 A 0 A_Explode(random(18,22),8,0,0);
		TNT1 AAAAAAAAAA 0
		{
			pb_effect_event(effect_event).show_some_effect(self, "bfg_4_laser_train");
		}
		TNT1 A 0
		{
			pb_effect_event(effect_event).show_some_effect(self, "bfg_4_laser_explode");
		}
		TNT1 BCD 4;
	goto reset_self_condition;

}

}












/*

CLASS MeleePuff : cheap_effect_base { 
Default {
	renderstyle "Translucent";
	alpha 0.5;
	Scale 1.5;
	DamageType "Melee";
	+NOBLOCKMAP;
	+NOGRAVITY;
	+NOEXTREMEDEATH;
	+PUFFONACTORS;
	+BLOODLESSIMPACT;
	+FORCEXYBILLBOARD;
	+DONTSPLASH;
}
states
{
	Spawn:
		tnt1 A 0 nodelay A_PlaySound("player/cyborg/fist");
		EXPL AAAAAA 0
		{
			pb_effect_event(effect_event).show_some_effect(self, "ExplosionSmoke");
		}
		TNT1 A 1;
	stop;
}

}

CLASS FatalityPuff: MeleePuff { 
Default {
	DamageType "Fatality";
	Decal "Crack";
}
states
{
	Spawn:
	XDeath:
	Melee:
	Death:
		TNT1 A 0 A_PlaySound("player/cyborg/fist");
		EXPL AAAAAA 0
		{
			pb_effect_event(effect_event).show_some_effect(self, "ExplosionSmoke");
		}
		stop;
}
}

CLASS KickPuff: MeleePuff { 
Default {
	DamageType "Kick";
}
states
{
	Spawn:
		tnt1 A 0 A_PlaySound("player/cyborg/fist");
		EXPL AAAAAA 0
		{
			pb_effect_event(effect_event).show_some_effect(self, "ExplosionSmoke");
		}
	stop;

	Death:
		tnt1 A 0 A_PlaySound("player/cyborg/fist");
		EXPL AAAAAA 0
		{
			pb_effect_event(effect_event).show_some_effect(self, "ExplosionSmoke");
		}
	stop;

	Melee:
		tnt1 A 0 A_PlaySound("player/cyborg/fist");
		TNT1 AAAA 0 
		{
			pb_effect_event(effects).show_some_effect(self, "ShotgunParticles");
		}

	stop;

	XDeath:
		tnt1 A 0 A_PlaySound("player/cyborg/fist");
		EXPL AAAAAA 0 
		{
			pb_effect_event(effect_event).show_some_effect(self, "ExplosionParticle");
		}
	stop;
}

}

CLASS SmashingPuff: MeleePuff { 
Default {
	DamageType "ExplosiveImpact";
	-NOEXTREMEDEATH;
	Decal "Crack";
}

states
{
	Spawn:
	XDeath:
	Melee:
	Death:
		TNT1 A 1
		{
			A_PlaySound("player/cyborg/fist");
			Radius_Quake(4, 24, 0, 15, 0);
			pb_effect_event(effect_event).show_some_effect(self, "ExplosionParticle");
		}
	stop;
}

}














//For Revenant's laser pointer
CLASS nullPuff: cheap_effect_base { 
Default {
	renderstyle "Translucent";
	alpha 1.0;
	Scale 0.1;
	Damage 0;
	DamageType "Blood";
	+NOBLOCKMAP;
	+NOGRAVITY;
	+NOEXTREMEDEATH;
	+BLOODLESSIMPACT;
	+FORCEXYBILLBOARD;
	+DONTSPLASH;
	+PAINLESS;
}
states
{
	Spawn:
	Death:
	Melee:
	XDeath:
		TNT1 A 1;
		stop;
		
}
}




CLASS SuperKickPuff: KickPuff { 
Default {
	DamageType "Kick";
	-NOEXTREMEDEATH;
	+EXTREMEDEATH;
	Decal "Crack";
}

}



CLASS UberPunchPuff: SmashingPuff { 
Default {
	DamageType "SuperPunch";
}
}

CLASS FatalitySmashingPuff: SmashingPuff { 
Default {
	DamageType "Fatality";
	+NOEXTREMEDEATH;
	-EXTREMEDEATH;
}

}

CLASS HitPuff : cheap_effect_base// Replaces BulletPuff { 
{
Default {
	renderstyle "Translucent";
	alpha 0.4;
	Scale 1.5;
	radius 0;
	height 0;
	+NOBLOCKMAP;
	+NOGRAVITY;
	Gravity 0.01;
	+NOEXTREMEDEATH;
	+FORCEXYBILLBOARD;
	+THRUACTORS;
	+NOCLIP;
	DamageType "Bullet";
	Decal "BulletDecalNew1";
	+DONTSPLASH;
	-EXPLODEONWATER;
}

states
{
	Spawn:
		TNT1 A 0;
		TNT1 AAAAAAAAAA 0 a_spawnprojectile("ShrapnelParticle", 2, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_SpawnItemEx("RicoChet",0,0,-5,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAA 0;
		TNT1 A 0 A_PlaySound("ricochet/hit");
	Melee:
		TNT1 AAA 0 
		{
			pb_effect_event(effect_event).show_some_effect(self, "ExplosionParticle");
		}
	stop;
}
}

CLASS AxePuffs: HitPuff { 
Default
{
	renderstyle "Translucent";
	scale 0.15;
	alpha 0.7;
	Radius 20;
	damagetype "Saw";
	decal "SawVertical";
	+NOBLOCKMAP;
	+NOGRAVITY;
	+NOEXTREMEDEATH;
	+FORCEXYBILLBOARD;
	+BLOODSPLATTER;
}
states
{
	Spawn:
		TNT1 A 1;
	Stop;
}
}

CLASS ExtremeBulletPuff: HitPuff { 
Default {
	DamageType "Saw";
}
}

CLASS ExtremeBulletPuff2: HitPuff { 
Default {
	DamageType "Cut";
}
}

CLASS QUADshotpuff1 : HitPuff { 
Default {
	DamageType "SSG";
	+RIPPER;
	+EXTREMEDEATH;
}
}

CLASS QUADshotpuff2 : HitPuff { 
Default {
	DamageType "SSG";
	+RIPPER;
}
}

CLASS QUADshotpuff3 : HitPuff { 
Default {
	DamageType "QuadBlast";
	+RIPPER;
	+EXTREMEDEATH;
}
}

CLASS shotpuff : HitPuff { 
Default {
	DamageType "SSG";
}
}

CLASS Shotgunpuff : HitPuff { 
Default {
	DamageType "Shotgun";
}
}







///////////////////////////////////////////////////////////////////////////////PB



CLASS RailgunPuff1 : HitPuff { 
Default {
	DamageType "Blast";
}

States
{
	Death:
		TNT1 A 0 A_StopSound(5);
		TNT1 AAAA 0 A_SpawnItemEx("BluePlasmaParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
		
		TNT1 A 0 A_Explode(120,5, 0);
		TNT1 A 0 A_Playsound("explosion/deepimpact", 3);
		TNT1 A 0 A_PlaySound("FAREXPL", 1);
		tnt1 A 0 Radius_Quake(4, 10, 0, 15, 0);
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0
		{
			effect_event.show_some_effect(self, "ExplosionParticle");
			pb_effect_event(effect_event).show_some_effect(self, "ExplosionParticle");
		}
		TNT1 AAAA 0 a_spawnprojectile("FireworkSFXType1", 2, 0, random(0, 360), 2, random(10, 80));
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 a_spawnprojectile("BluePlasmaFire", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAA 0 a_spawnprojectile("BluePlasmaParticle", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 ABCDE 2 BRIGHT A_SpawnItem("Blue_Flare" ,0);
		TNT2 AAAAAAAAA 9 
		{
			pb_effect_event(effect_event).show_some_effect(self, "ExplosionParticle");
		}
	stop;
		
	XDeath:
		TNT1 A 0 A_StopSound(5);
		TNT1 AA 0 A_SpawnItemEx("BluePlasmaParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
		TNT1 A 0 A_SpawnItemEx("Plasma_Puff", 0, 0);
		TNT1 A 0 A_PlaySound("RAILIMP");
		TNT1 ABCDE 2 BRIGHT A_SpawnItem("Blue_Flare" ,0);
		stop;
}
}


CLASS HMGPuff : HitPuff { 
Default {
	DamageType "Blast";
}
}


CLASS PulsePuff : HitPuff { 
Default {
	DamageType "Blackhole";
	+FRIENDLY;
	+DONTHARMSPECIES;
	Species "Marine";
}
}




CLASS SilentHitPuff: hitPuff { 
Default {
	DamageType "bullet";
}
}

CLASS MiniGunBulletPuff: HitPuff { 
Default {
	DamageType "CutLess";
}
}

CLASS MachineGunBulletPuff: HitPuff { 
Default {
	DamageType "CutLess";
}
}


CLASS SSawPuff: BulletPuff { 
Default {
	renderstyle "Translucent";
	scale 0.15;
	alpha 0.7;
	damagetype "tear";
	+NOBLOCKMAP;
	+NOGRAVITY;
	+NOEXTREMEDEATH;
	+FORCEXYBILLBOARD;
	Decal "SawDecalNew1";
}

states
{
	Spawn:
	Death:
	XDeath:
	Melee:
		TNT1 A 0;
		TNT1 AB 1 bright;
		TNT1 A 0 A_Jump(128,3);
		TNT1 A 0 A_SpawnItem("Sparks", 0);
		TNT1 A 0 A_SpawnItemEx("RicoChet",0,0,-5,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAAAA 0 a_spawnprojectile("ShrapnelParticle", 2, 0, random(0, 360), 2, random(30, 170));
		TNT1 AAAA 0 a_spawnprojectile("HitSpark", 2, 0, frandom(0,1)*frandom(0, 360), 2, frandom(0,1)*frandom(30, 360));
		TNT1 AA 0 a_spawnprojectile("HitSpark", 2, 0, frandom(0,1)*frandom(0, 360), 2, frandom(0,1)*frandom(30, 360));
		TNT1 A 0 a_spawnprojectile("HitSpark", 2, 0, frandom(0,1)*frandom(0, 360), 2, frandom(0,1)*frandom(30, 360));
		BPUF C 1 bright A_PlaySound("weapons/chainsaw/hitwall");
		BPUF D 1 bright;
	Stop;
}
}









CLASS RicoChet : ACTOR { 
Default {
	renderstyle "Add";
	alpha 1.0;
	-COUNTKILL;
	-SHOOTABLE;
	+CLIENTSIDEONLY;
	+BLOODLESSIMPACT;
	+FORCEXYBILLBOARD;
	+THRUACTORS;
	+NOCLIP;
	+NOGRAVITY;
	+NODAMAGETHRUST;
	+DONTTHRUST;
	//Mass 9999999
	Obituary "%o ate bullet shrapnel.";
	//damagetype "Shrapnel"
	Scale 0.09;
	Speed 0;
	Radius 1;
	Height 1;
}

states
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_CheckFloor("SpawnFloor");
		TNT1 A 0 A_SpawnItem("YellowFlareSmall", 0);
		TNT1 A 0 A_SpawnItemEx("UnderwaterHitPuff",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAAAAAAAA 0 a_spawnprojectile("ShrapnelParticle", 2, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAA 0 a_spawnprojectile("HitSpark", 2, 0, frandom(0,1)*frandom(0, 360), 2, frandom(0,1)*frandom(30, 360));
		TNT1 AA 0 a_spawnprojectile("HitSpark", 2, 0, frandom(0,1)*frandom(0, 360), 2, frandom(0,1)*frandom(30, 360));
		TNT1 A 0 a_spawnprojectile("HitSpark", 2, 0, frandom(0,1)*frandom(0, 360), 2, frandom(0,1)*frandom(30, 360));
		TNT1 A 0 A_SpawnItem("Sparks");
		tnt1 A 0 bright A_PlaySound("ricochet/hit");
		TNT1 AAA 0 
		{
			pb_effect_event(effect_event).show_some_effect(self, "ExplosionParticle");
		}
		TNT1 A 0 A_Jump(255, "Spawn1", "Spawn2", "Spawn3", "Spawn4");
	Spawn1:
		IPF2 AABB 1 bright A_SpawnItem("YellowFlareSmall", 0);
	Stop;
		
	Spawn2:
		IPF2 CCDD 1 bright A_SpawnItem("YellowFlareSmall", 0);
	Stop;
		
	Spawn3:
		IPF2 EEFF 1 bright A_SpawnItem("YellowFlareSmall", 0);
	Stop;
		
	Spawn4:
		IPF2 GGHH 1 bright A_SpawnItem("YellowFlareSmall", 0);
	Stop;
		
		
	SpawnFloor:
		TNT1 A 0;
		TNT1 A 2;
		TNT1 A 0 A_SpawnItemEx("UnderwaterHitPuff",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);

		TNT1 AAAAAAAAAA 0 a_spawnprojectile("ShrapnelParticle", 2, 0, random(0, 360), 2, random(30, 160));
		TNT1 AAAA 0 a_spawnprojectile("HitSpark", 2, 0, frandom(0,1)*frandom(0, 360), 2, frandom(0,1)*frandom(30, 160));
		TNT1 AA 0 a_spawnprojectile("HitSpark", 2, 0, frandom(0,1)*frandom(0, 360), 2, frandom(0,1)*frandom(30, 160));
		TNT1 A 0 a_spawnprojectile("HitSpark", 2, 0, frandom(0,1)*frandom(0, 360), 2, frandom(0,1)*frandom(30, 160));
		TNT1 A 0 A_SpawnItem("Sparks");
		tnt1 A 0 bright A_PlaySound("ricochet/hit");
		IPF2 GGHH 1 bright A_SpawnItem("YellowFlareSmall", 0);
		TNT1 AAA 0 
		{
			pb_effect_event(effect_event).show_some_effect(self, "ExplosionParticle");
		}
	stop;
		
	SpawnWater:
		TNT1 A 0;
		//TNT1 AAAAA 0 a_spawnprojectile("WaterParticleX", 8, 0, random(0, 360), 2, random(30, 160));
		//TNT1 AAAAA 0 a_spawnprojectile("WaterParticleX", 24, 0, random(0, 360), 2, random(30, 160));
		TNT1 A 0 A_SpawnItem("WaterSplashWaves");
		TNT1 A 0 A_SpawnItem("WaterRicochet");
		TNT1 A 0 A_PlaySound("water/bulletsplash", 1);
	Stop;
		
	SpawnSlime:
		TNT1 A 0;
		//TNT1 AAAAA 0 a_spawnprojectile("nukageParticleXFAster", 8, 0, random(0, 360), 2, random(30, 160));
		//TNT1 AAAAA 0 a_spawnprojectile("nukageParticleXFAster", 24, 0, random(0, 360), 2, random(30, 160));
		TNT1 A 0 A_SpawnItem("SlimeRicochet");
		TNT1 A 0 A_SpawnItem("NukageSplashWaves");
		TNT1 A 0 A_PlaySound("water/bulletsplash", 1);
	Stop;
		
	SpawnBlood:
		TNT1 A 0;
		TNT1 AAAAA 0 a_spawnprojectile("BloodParticleXFAster", 8, 0, random(0, 360), 2, random(30, 160));
		TNT1 AAAAA 0 a_spawnprojectile("BloodParticleXFAster", 24, 0, random(0, 360), 2, random(30, 160));
		TNT1 A 0 A_SpawnItem("BloodSplashWaves");
		TNT1 A 0 A_SpawnItem("BloodRicochet");
		TNT1 A 0 A_PlaySound("water/bulletsplash", 1);
	Stop;
		
	SpawnSludge:
		TNT1 A 0;
		TNT1 AAAAA 0 a_spawnprojectile("SludgeParticleX", 8, 0, random(0, 360), 2, random(30, 160));
		TNT1 AAAAA 0 a_spawnprojectile("SludgeParticleX", 24, 0, random(0, 360), 2, random(30, 160));
		TNT1 A 0 A_SpawnItem("SlimeSplashWaves");
		TNT1 A 0 A_SpawnItem("Slime2Ricochet");
		TNT1 A 0 A_PlaySound("water/bulletsplash", 1);
	Stop;
		
	SpawnLava:
		TNT1 A 0;
		TNT1 A 0
		{
			for (int i = 0; i < 10; i++)
			{
				a_spawnprojectile("pb_particle", 0, 0, random(0, 360), 2, random(0, 180));
			}
		}
		tnt1 aAAAa 0
		{
			pb_effect_event(effect_event).show_some_effect(self, "ExplosionParticle");
		}
		TNT1 AAA 0 ;//a_spawnprojectile("LavaMist", 0, 0, random(0, 360), 2, random(0, 90));
		TNT1 A 0 A_SpawnItem("LavaRicochet");
		TNT1 A 0 A_PlaySound("Daedabus/impact", 1);
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("rocket_trail_darker", 12, 0, random(160, 210), 2, random(10, 90));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-5, 5), random(-5, 5));
		TNT1 A 0 A_SetScale(0.5, 0.5);
		INFE ABCDEFGHIJKLMNOPQR 1 BRIGHT;
		INFE ST 1 BRIGHT a_spawnprojectile("rocket_trail_darker", 32, 0, random(160, 210), 2, random(10, 90));
		TNT1 AAA 4 a_spawnprojectile("rocket_trail_darker", 14, 0, random(160, 210), 2, random(10, 90));
	Stop;
		
	SpawnDirt:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("dirtrain", 1);
		TNT1 A 0 a_spawnprojectile("MudDust", 0, 0, random(0, 360), 2, random(10, 150));
		TNT1 AA 0 a_spawnprojectile("DirtChunk1", 0, 0, random(0, 360), 2, random(30, 150));
		TNT1 AA 0 a_spawnprojectile("DirtChunk1", 0, 0, random(0, 360), 2, random(30, 150));
		TNT1 A 0 a_spawnprojectile("MudDust", 4, 0, random(0, 360), 2, random(30, 150));
		TNT1 A 0 A_SpawnItem("DirtRicochet");
	Stop;
		
	SpawnSand:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("dirtrain", 1);
		TNT1 A 0 a_spawnprojectile("MudDust", 0, 0, random(0, 360), 2, random(10, 90));
		TNT1 A 0 a_spawnprojectile("MudDust", 0, 0, random(0, 360), 2, random(10, 90));
		TNT1 A 0 a_spawnprojectile("MudDust", 4, 0, random(0, 360), 2, random(30, 150));
	Stop;
}
}
*/