CLASS pb_Daedabus : proto_fat //replaces Fatso
{ 
Default
{
	Health 850;
	Radius 48;
	Height 64;
	Scale 1.2;
	Mass 1000;
	
	Speed 8;
	damagefactor "Crush", 10.0;
	damagefactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	PainChance "Stun", 255;
	PainChance "Kick", 255;
	PainChance "ExtremePunches", 225;
	PainChance "Taunt", 255;
	PainChance "Explosive", 255;
	PainChance 40;
	BloodType "pb_blood";
	SeeSound "Daedabus/Sight";
	PainSound "Daedabus/Pain";
	DeathSound "Daedabus/Death";
	ActiveSound "Daedabus/Active";
	damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0; damagefactor "GreenBlood", 0.0;
	damagefactor "HEAD", 3;
	
	Species "BigFatAss";
	
	+DONTHARMSPECIES;
	+DONTHARMCLASS;
	MONSTER;
	+FLOORCLIP;
	+BossDeath;
	+DONTHARMCLASS;
	Obituary "%o was acidified by a Daedabus.";
	
/*	DropItem "TimeSphere", 3;
	DropItem "DemonStrengthRune", 5;
	DropItem "DemonMorphRune", 3;
	DropItem "RageSphere", 4;
	DropItem "DoubleSphere", 4;
	DropItem "ShieldSphere", 3;
	DropItem "Demonpickup2", 80;
	DropItem "Demonpickup2", 30;
	DropItem "Demonpickup2", 250;*/
}

States
{
	Death.Shrink:
		TNT1 A 1 A_PlaySound("Shrink", 3);
/*		TNT1 A 0 A_SpawnItemEx ("DaedabusShrinkFX1", 0, 0,  5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("DaedabusShrinkFX2", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("DaedabusShrinkFX3", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("DaedabusShrinkFX4", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("DaedabusShrinkFX5", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("DaedabusShrinkFX6", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("DaedabusShrinkFX7", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("LilDaedabus", 1);*/
	stop;
		
	Spawn:
		//TNT1 A 0 ACS_ExecuteAlways(796, 0, 0, 0, 0);//Check if Vanilla Mode is activated
	Stand:
		DAED BBBBBBBBBB 10 A_Look;
	Loop;
		
	See:
		TNT1 A 0;
		TNT1 A 0 A_TakeInventory("EnemyMemory", 5);
		TNT1 A 0 A_TakeInventory("MancubusFlamethrowerCooldown", 10);
	LookingForPlayer:
		TNT1 A 0 A_JumpIfInventory("EnemyMemory", 10, "ForgetTarget");
		DAED AA 4 A_Chase;
		TNT1 A 0 A_PlaySound("knight/step",5);
		DAED BBCCDD 4 A_Chase;
		TNT1 A 0 A_PlaySound("knight/step",8);
		DAED EEFF 4 A_Chase;
	Loop;
		
	ForgetTarget:
		TNT1 A 0 A_ClearTarget;
		TNT1 A 0 A_TakeInventory("EnemyMemory", 25);
	Goto LookingForPlayer;

	Pain:
		DAED J 3;
		DAED J 3 A_Pain;
		Goto See;

	Pain.Kick:
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil(0.50);
		DAED J 9 A_Pain ;
		DAED J 8;
	Goto See;
		
	Pain.Explosive:
	Pain.ExtremePunches:
	Pain.SSG:
	Pain.Blackhole:
	Pain.QuadShot:
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 {self.bNOPAIN = true;}
		DA5D A 4 ThrustThingZ(0,30,0,1);
		DA5D B 4 A_Pain;
		DA5D CDDDD 4;
		DA5D C 4 A_Stop;
		DA5D BA 4;
		TNT1 A 0 {self.bNOPAIN = false;}
	Goto See;
		
	Pain.Taunt:
		TNT1 A 0;
		TNT1 A 0 A_Pain;
		TNT1 A 0 {self.bNOPAIN = true;}
		TNT1 A 0 {self.bMISSILEMORE = true;}
		TNT1 A 0 {self.bMISSILEEVENMORE = true;}
		TNT1 A 0 A_PlaySound("demon/pain");
		DA6D A 1 A_FaceTarget;
		DA6D A 10  A_Pain;
		DA6D BAC 8;
		TNT1 A 0 A_Pain;
		DA6D ABAC 8;
		TNT1 A 0 A_Pain;
		DA6D ABAC 8;
		TNT1 A 0 {self.rage = true;}
	Goto Missile;
		
	Possession:
		TNT1 A 0 A_SetInvulnerable;
		DAED J 3;
		DAED J 3 A_Pain;
		"####" "#" 35 ACS_NamedExecuteAlways("Pos - Flicker effect");
		TNT1 A 0 A_UnSetInvulnerable;
	Goto See;
		
	Pain.Stun:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx ("StunElectrocute", random (-4, 4), random (-4, 4),  random (16, 32), 0, 0);
		DAED J 1 A_Pain;
		DAED JJJJJJJJJJ 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		DAED J 1 A_Pain;
		DAED JJJJJJJJJJ 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		DAED J 1 A_Pain;
		DAED JJJJJJJJJJ 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		DAED J 1 A_Pain;
		DAED JJJJJJJJJJ 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		DAED J 1 A_Pain;
		DAED JJJJJJJJJJ 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		DAED J 1 A_Pain;
	Goto See;
		
	Missile:
		TNT1 A 0 A_JumpIfCloser(280, "AssThrower");
		DAED F 0 A_Jump(128, "Missile2");
		DAED F 0 A_Jump(255, "Missile3");
	Goto See;
		
	AssThrower:
		TNT1 A 0 A_JumpIfInventory("Enraged", 1, 1);
		DAED G 1 A_FatRaise;
		TNT1 A 0 A_PlaySound("FLMDRAW",3);
		DAED G 2 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, 30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, -30, 0, 2, 0);
		DAED G 2 BRIGHT A_FaceTarget;
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, 30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, -30, 0, 2, 0);
		DAED G 2 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, 30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, -30, 0, 2, 0);
		DAED G 2 BRIGHT A_FaceTarget;
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, 30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, -30, 0, 2, 0);
		DAED G 2 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, 30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, -30, 0, 2, 0);
		DAED G 2 BRIGHT A_FaceTarget;
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, 30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, -30, 0, 2, 0);
		DAED G 2 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, 30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, -30, 0, 2, 0);
		DAED G 2 BRIGHT A_FaceTarget;
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, 30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, -30, 0, 2, 0);
		DAED G 2 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, 30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, -30, 0, 2, 0);
		DAED G 2 BRIGHT A_FaceTarget;
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, 30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, -30, 0, 2, 0);
		DAED G 2 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, 30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, -30, 0, 2, 0);
		DAED G 2 BRIGHT A_FaceTarget;
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, 30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, -30, 0, 2, 0);
	goto Torch;
		
	Torch:
		TNT1 A 0 A_PlaySound("acid/spew");
		TNT1 A 0 a_spawnprojectile("GreenCloudMissile_Enemy",30,-25,10,0);
		TNT1 A 0 a_spawnprojectile("GreenCloudMissile_Enemy",30,25,0,0);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, 30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, -30, 0, 2, 0);
		TNT1 A 0 A_GiveInventory("MancubusFlamethrowerCooldown", 1);
		DAED H 1 BRIGHT A_SpawnItemEx("GreenFlare", 0, 0, 0, 0, 0, 0, 0, 128);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, 30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, -30, 0, 2, 0);
		DAED IG 2 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, 30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, -30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile("GreenCloudMissile_Enemy",30,-25,10,0);
		TNT1 A 0 a_spawnprojectile("GreenCloudMissile_Enemy",30,25,0,0);
		DAED H 1 BRIGHT A_SpawnItemEx("GreenFlare", 0, 0, 0, 0, 0, 0, 0, 128);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, 30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, -30, 0, 2, 0);
		DAED IG 2 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, 30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, -30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile("GreenCloudMissile_Enemy",30,-25,10,0);
		TNT1 A 0 a_spawnprojectile("GreenCloudMissile_Enemy",30,25,0,0);
		DAED H 1 BRIGHT A_SpawnItemEx("GreenFlare", 0, 0, 0, 0, 0, 0, 0, 128);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, 30, 0, 2, 0);
		TNT1 A 0 a_spawnprojectile ("DaedabusSwitchModeEffect", 34, -30, 0, 2, 0);
		DAED IG 2 A_FaceTarget;
		TNT1 A 0 A_JumpIfInventory("MancubusFlamethrowerCooldown", 8, "See");
		TNT1 A 0 A_MonsterRefire(16, "See");
		TNT1 A 0 A_JumpIfCloser(280, "Torch");
		TNT1 A 0 A_JumpIfCloser(300, "See");
		TNT1 A 0 A_CheckSightOrRange (320, "See");
		TNT1 A 0 A_ClearTarget;
		DAED IG 5;
	Goto See;
		
	Missile2:
		DAED G 0 A_PlaySound("Daedabus/Attack");
		DAED G 20 A_FaceTarget;
		TNT1 A 0 A_PlaySound("Daedabus/gun");
		TNT1 A 0 a_spawnprojectile("DaedFire",30,-25,10,0);
		TNT1 A 0 a_spawnprojectile("DaedFire",30,25,0,0);
		DAED H 10 Bright;
		DAED IG 5 A_FaceTarget;
		TNT1 A 0 A_PlaySound("Daedabus/gun");
		TNT1 A 0 a_spawnprojectile("DaedFire",30,-25,10,0);
		TNT1 A 0 a_spawnprojectile("DaedFire",30,25,0,0);
		DAED H 10 Bright;
		DAED IG 5 A_FaceTarget;
		TNT1 A 0 A_PlaySound("Daedabus/gun");
		TNT1 A 0 a_spawnprojectile("DaedFire",30,-25,10,0);
		TNT1 A 0 a_spawnprojectile("DaedFire",30,25,0,0);
		DAED H 10 Bright;
		DAED IG 5 A_FaceTarget;
	Goto See;
		
	Missile3:
		DAED G 0 A_PlaySound("Daedabus/Attack");
		DAED G 20 A_FaceTarget;
		TNT1 A 0 A_PlaySound("Daedabus/gun");
		TNT1 A 0 a_spawnprojectile("DaedFire",30,25,0,0);
		DAED H 5 Bright;
		DAED IG 5 A_FaceTarget;
		TNT1 A 0 A_PlaySound("Daedabus/gun");
		TNT1 A 0 a_spawnprojectile("DaedFire",30,-25,10,0);
		DAED H 5 Bright;
		DAED IG 5 A_FaceTarget;
		TNT1 A 0 A_PlaySound("Daedabus/gun");
		TNT1 A 0 a_spawnprojectile("DaedFire",30,25,0,0);
		DAED H 5 Bright;
		DAED IG 5 A_FaceTarget;
		TNT1 A 0 A_PlaySound("Daedabus/gun");
		TNT1 A 0 a_spawnprojectile("DaedFire",30,-25,10,0);
		DAED H 5 Bright;
		DAED IG 5 A_FaceTarget;
		TNT1 A 0 A_PlaySound("Daedabus/gun");
		TNT1 A 0 a_spawnprojectile("DaedFire",30,25,0,0);
		DAED H 5 Bright;
		DAED IG 5 A_FaceTarget;
		TNT1 A 0 A_PlaySound("Daedabus/gun");
		TNT1 A 0 a_spawnprojectile("DaedFire",30,-25,10,0);
		DAED H 5 Bright;
		DAED IG 5 A_FaceTarget;
	Goto See;
		
	Death.Ice:
	Death.Freeze:
	Death.Frost:
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 {self.bSHOOTABLE = false; self.bSOLID = false;}
		//TNT1 A 0 A_SpawnItem("FrozenDaedabus");
	stop;
		
	Death:
		TNT1 A 0 A_Jump(127, "Death2", "Death3");
		DA8D A 6;
		DA8D B 6 A_Scream;
		DA8D C 6 A_NoBlocking;
		DA8D DEF 5 a_spawnprojectile ("MuchBlood", 15, 0, random (0, 360), 2, random (0, 160));
		DA8D F 1 A_BossDeath   ;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DeadDaedabus1", 1);
	stop;
		
	Death2:
		DA4D K 6;
		DA4D L 5 A_Scream;
		DA4D M 5 A_NoBlocking;
		DA4D NOP 5 a_spawnprojectile ("MuchBlood", 15, 0, random (0, 360), 2, random (0, 160));
		DA4D Q 5;
		DA4D R 5 A_BossDeath;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DeadDaedabus2", 1);
	stop;
		
	Death3:
		DA4D A 1;
		DA4D B 6 A_Scream;
		DA4D C 6 A_NoBlocking;
		DA4D DEF 6;
		DA4D  F 1 A_BossDeath;
		DA4D F 1 A_SpawnItem("DeadDaedabusHoles", 1);
	stop;
		
	Death.cutless:
		TNT1 A 0 A_Jump(32, "Death3");
		TNT1 A 0 A_Jump(16, "DeathGutted");
	Death.Arm:
		TNT1 A 0;
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile ("XDeathMancubusArm", 30, 0, random (0, 360), 2, random (50, 130));
		TNT1 AA 0 a_spawnprojectile ("MuchBlood", 55, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		D4T1 AAAAAAAA 1 a_spawnprojectile ("Brutal_LiquidBlood2", 50, 0, random (0, 360), 2, random (30, 50));
		TNT1 A 0 A_SpawnItem("DyingDaedabus01");
		TNT1 A -1;
	stop;
		
	Death.cut:
	Death.Saw:
		TNT1 A 0;
		TNT1 A 0 A_Stop;
		D4AT AB 4;
		TNT1 A 0 A_Scream;
		TNT1 O 0 A_NoBlocking;
		TNT1 AA 0 a_spawnprojectile ("MuchBlood", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("RipGuts", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath2b", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath3b", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_BossDeath;
		D4AT CDEF 5;
		D4AT GH 5;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("NoGutsDaedabus2", 1);
		TNT1 AAAAAAAAAAAAAAAAAA 4 a_spawnprojectile ("Brutal_LiquidBlood2", 40, 0, random (0, 360), 2, random (30, 50));
		TNT1 A -1;
	stop;

	Death.Tear:
	DeathGutted:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_BossDeath;
		TNT1 AAA 0 a_spawnprojectile ("MuchBlood", 35, 0, random (0, 360), 2, random (0, 160));
		DA7D AA 1 a_spawnprojectile ("Brutal_LiquidBlood2", 40, 0, random (0, 360), 2, random (30, 60));
		TNT1 AAAA 0 a_spawnprojectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("xdeath2", 0, 0, random (0, 360), 2, random (0, 160));
		DA7D BBBBBB 1 a_spawnprojectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (30, 60));
		TNT1 AAAAAA 0 a_spawnprojectile ("RipGuts", 25, 0, random (0, 360), 2, random (0, 160));
		DA7D CCCCCCC 1 a_spawnprojectile ("Brutal_LiquidBlood2", 27, 0, random (0, 360), 2, random (30, 60));
		TNT1 AAA 0 a_spawnprojectile ("MuchBlood", 25, 0, random (0, 360), 2, random (0, 160));
		DA7D DDDDDDD 1 a_spawnprojectile ("Brutal_LiquidBlood2", 24, 0, random (0, 360), 2, random (30, 60));
		TNT1 AAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 20, 0, random (0, 360), 2, random (0, 160));
		DA7D EEEEEEE 1 a_spawnprojectile ("Brutal_LiquidBlood2", 21, 0, random (0, 360), 2, random (30, 60));
		DA7D FFFFFFGGGGGGG 1 a_spawnprojectile ("Brutal_LiquidBlood2", 18, 0, random (0, 360), 2, random (30, 60));
		DA7D HHHHHHH 1 a_spawnprojectile ("Brutal_LiquidBlood2", 15, 0, random (0, 360), 2, random (30, 60));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		DA7D IIIIIIIIIIIIIIIIIIIIIIIIIIIIII 1 a_spawnprojectile ("Brutal_LiquidBlood2", 12, 0, random (0, 360), 2, random (30, 60));
		TNT1 A 0 A_SpawnItem ("DeadDaedabusSlump", 1);
	stop;
		
	Death.Head:
		//TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 A 0 A_SpawnItem("DaedabusHeadExplode", 0, 50);
		TNT1 A 0 A_Jump(200, "DeathHead2");
		DA3D K 5 A_Scream;
		DA3D LLLLL 1 a_spawnprojectile ("Brutal_LiquidBlood2", 50, 0, random (0, 360), 2, random (30, 50));
		TNT1 A 0 a_spawnprojectile ("brutal_FlyingBlood", 75, 0, random (0, 360), 2, random (0, 160));
		DA3D MMMMM 1 a_spawnprojectile ("Brutal_LiquidBlood2", 47, 0, random (0, 360), 2, random (30, 50));
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_BossDeath;
		DA3D NOPQRST 4 a_spawnprojectile ("brutal_FlyingBlood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		DA3D T 0 A_SpawnItem("DeadDaedabusHead");
	stop;
		
	DeathHead2:
		D4T5 AAA 2 a_spawnprojectile ("Brutal_LiquidBlood3", 50, 0, random (0, 360), 2, random (30, 50));
		D4T5 BBB 2 a_spawnprojectile ("Brutal_LiquidBlood3", 40, 0, random (0, 360), 2, random (30, 50));
		TNT1 A 0 A_Scream;
		D4T5 CCC 2 a_spawnprojectile ("Brutal_LiquidBlood3", 38, 0, random (0, 360), 2, random (20, 50));
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_BossDeath;
		D4T5 DDEEFFGGHHII 2 a_spawnprojectile ("Brutal_LiquidBlood3", 32, 0, random (0, 360), 2, random (20, 50));
		D4T5 JJJJJJJJJJJJJJJJJJJJJ 2 a_spawnprojectile ("Brutal_LiquidBlood3", 28, 0, random (0, 360), 2, random (20, 50));
		TNT1 A 0 A_SpawnItem ("DeadDaedabusD4T5J", 1);
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
	stop;
		
	Death.Shotgun:
		TNT1 A 0 A_JumpIfCloser(250, 1);
		Goto Death;
		//TNT1 A 0 A_JumpIfInTargetInventory("SSGSelected", 1, "Death.Blast");
	Goto Death;

	Death.Blast:
		TNT1 AA 0 a_spawnprojectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("xdeath2", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("RipGuts", 25, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBloodMuchFaster", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		DA9D AAAA 2 a_spawnprojectile ("Brutal_LiquidBlood2", 40, 0, random (0, 360), 2, random (30, 60));
		DA9D B 6 A_Scream;
		TNT1 A 0 a_spawnprojectile ("MuchBlood", 25, 0, random (0, 360), 2, random (0, 160));
		DA9D C 6 A_NoBlocking;
		DA9D D 6 a_spawnprojectile ("MuchBlood", 15, 0, random (0, 360), 2, random (0, 160));
		DA9D E 6 A_BossDeath;
		DA9D EEEEEEEEE 2 a_spawnprojectile ("Brutal_LiquidBlood2", 8, 0, random (0, 360), 2, random (30, 60));
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("DeadDaedabusDA9D", 1);
	stop;
		
	Death.SSG:
		TNT1 A 0;
		TNT1 A 0 A_Jump(96, "Death.Blast");
		TNT1 A 0 A_Stop;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_noBlocking;
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_Jump(255, "DeathSSG1", "DEathSSG2");
	DeathSSG1:
		TNT1 A 0;
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("MuchBlood", 55, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeathMancubusArm", 30, 0, random (0, 360), 2, random (50, 130));
		D4T2 AAAAAAAAAAAA 2 a_spawnprojectile ("Brutal_LiquidBlood2", 50, 0, random (0, 360), 2, random (30, 50));
		D4T2 BC 6;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("FUckedDaedabus1", 1);
		TNT1 A -1;
	stop;
		
	XDeath:
	Death.QuadBlast:
	Death.Explosives:
	Death.ExplosiveImpact:
	Death.Landmine:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile ("XDeathDaedabusEyeball", 58, 0, random (0, 360), 2, random (10, 90));
		TNT1 A 0 a_spawnprojectile ("MeatDeath", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAAAAAAAA 0 a_spawnprojectile ("BloodMistExtraBig", 30, 0, random (0, 360), 2, random (60, 90));
		TNT1 A 0 a_spawnprojectile ("XDeathMancubusArm", 20, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0 a_spawnprojectile ("XDeathDaedabusTorso", 20, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0 a_spawnprojectile ("XDeathDaedabusLeg", 20, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0 a_spawnprojectile ("XDeathDaedabusHead", 20, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("XDeath2b", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("XDeath3b", 20, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile ("XDeath1", 36, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("MuchBlood2", 50, 0, random (0, 360), 2, random (0, 160));
		DA3D A 6 A_xScream;
		DA3D B 6 A_NoBlocking;
		DA3D CDE 6;
		DA3D E 1 A_BossDeath;
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem ("XDeadDaedabus", 1);
	stop;
		
	Death.Fire:
		TNT1 A 0 A_Jump(162, "DeathFireLong");
		FATK A 4;
		FATK B 4 A_Scream;
		FATK C 4 A_NoBlocking;
		FATK D 4;
		BF4T EF 4;
		BF4T F 1 A_BossDeath;
		TNT1 A 0 A_Playsound("props/redfire");
		CARB OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 2 a_spawnprojectile ("FlameTrails", 32, 0, random (0, 360), 2, random (70, 130));
		CARB OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 10 a_spawnprojectile ("PLasmaSmoke", 32, 0, random (0, 360), 2, random (70, 130));
		CARB O -1;
	stop;
		
	DeathFireLong:
		TNT1 A 0;
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("BurningFatso2", 0, 10);
	stop;
		
	Death.Desintegrate:
	Death.Plasma: Death.Plasma2:
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		CRB7 G 5 BRIGHT;
		TNT1 AAA 0 a_spawnprojectile ("brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
		CRB7 H 5 BRIGHT;
		EXPL AAAAAA 0 a_spawnprojectile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
		CRB7 IJ 5 BRIGHT;
		CARB OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO 10 a_spawnprojectile ("SmallSmoke", 1, 0, random (0, 360), 2, random (0, 160));
		CARB O -1;
	Stop;
	
	Death.SuperPlasma:
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAAAAAA 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
		XBRN BB 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 A 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
		XBRN CC 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 AAAAA 0 a_spawnprojectile ("PlasmaParticleX", 48, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAA 0 a_spawnprojectile ("BigPlasmaParticleX", 42, 0, random (0, 360), 2, random (0, 360));
	Stop;
	
	Death.GreenFire:
		TNT1 A 0;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAA 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("pb_blood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("XDeathBurnedMeat", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("XDeathBurnedMeat2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
		EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("GreenFlameTrails", 50, 0, random (0, 360), 2, random (0, 360));
		XBRN AAAA 2 BRIGHT A_SpawnItem("GreenFlare",0,43);
	Stop;
	
	Death.Fatality:
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("OtherFatsoFatality2", 1);
		TNT1 A 1 A_BossDeath;
		TNT1 A 0;
	Stop;
	
	Raise:
		DAED RQPONMLK 5;
	Goto See;
}
}

CLASS DeadDaedabus1 : ACTOR { 
Default
{
	Radius 39;
	Height 33;
	Scale 1.2;
	+SHOOTABLE;
	-SOLID;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	-CORPSE;
	-DONTGIB;
	-TELESTOMP;
	Mass 1000;
	Health 500;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	Species "Marine";
	damagefactor "Cut", 4.0;
	damagefactor "Saw", 4.0;
	damagefactor "Tear", 4.0;
}
States
{
	Spawn:
		DA8D F -1;
	Stop;
	Death:
		TNT1 AA 0 a_spawnprojectile ("XDeathMancubusArm", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;
}
}

CLASS FuckedDaedabus1: DeadDaedabus1
{ 
default{Health 500;}
States
{
	Spawn:
		D4T2 D -1;
	Stop;
	
	Death:
	TNT1 A 0 A_SpawnItem("GutsPile");
	TNT1 A 0 A_NoBlocking;
	TNT1 AAA 0 a_spawnprojectile ("UltraGoreSpawner", 5, 0, random (0, 360), 2, random (30, 60));
	TNT1 AAAA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAA 0 a_spawnprojectile ("XDeath2b", 25, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAA 0 a_spawnprojectile ("XDeath3b", 25, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeathDaedabusTorso", 20, 0, random (0, 360), 2, random (50, 130));
	TNT1 AA 0 a_spawnprojectile ("XDeathDaedabusLeg", 20, 0, random (0, 360), 2, random (50, 130));
	TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 30, 0, random (0, 360), 2, random (40, 90));
	TNT1 AAAAAAAA 0 a_spawnprojectile ("SmallSuperGore", 30, 0, random (0, 360), 2, random (10, 170));
Stop;}}	
	
	
	

CLASS FuckedDaedabus2: DeadDaedabus1 { 
default{Health 500;} States{Spawn:
	D4T2 D -1;
	Stop  ;
	
	Death:
	TNT1 A 0 A_SpawnItem("GutsPile");
	TNT1 A 0 A_NoBlocking;
	TNT1 AAA 0 a_spawnprojectile ("UltraGoreSpawner", 5, 0, random (0, 360), 2, random (30, 60));
	TNT1 AAAA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAA 0 a_spawnprojectile ("XDeath2b", 25, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAA 0 a_spawnprojectile ("XDeath3b", 25, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeathDaedabusTorso", 20, 0, random (0, 360), 2, random (50, 130));
	TNT1 AA 0 a_spawnprojectile ("XDeathDaedabusLeg", 20, 0, random (0, 360), 2, random (50, 130));
	TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 30, 0, random (0, 360), 2, random (40, 90));
	TNT1 AAAAAAAA 0 a_spawnprojectile ("SmallSuperGore", 30, 0, random (0, 360), 2, random (10, 170));
Stop;}}	

CLASS XDeadDaedabus: DeadDaedabus1 { 
	Default {
	
	Health 500;
	}
States
{
	Spawn:
	DA3D EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 13;
	DA3D EEEEE 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
	DA3D E -1;
	Stop;
	
	Death.Cutless: 
	Death.Cut:
	Death.Saw:
	Death:
	TNT1 A 0 a_spawnprojectile ("XDeathMancubusArm", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
Stop;}}


CLASS NoGutsDaedabus2: XDeadDaedabus { 
default{Health 500;} States{Spawn:
	D4AT I -1;
	Stop   ;
}}


CLASS DeadDaedabusDA9D_NoArm: DeadDaedabus1 { 
	Default {
	
	Health 500;
	}
States
{
	Spawn:
	DA9D F -1;
	Stop;
	
	Death.Cutless: 
	Death.Cut:
	Death.Saw:
	Death:
	TNT1 A 0 a_spawnprojectile ("XDeathMancubusArm", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
Stop;}}

CLASS DeadDaedabusDA9D: DeadDaedabus1 { 
	Default {
	
	Health 500;
	}
States
{
	Spawn:
	DA9D EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 13;
	DA9D EEEEE 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
	DA9D E -1;
	Stop;
	
	Death.Cutless: 
	Death.Cut:
	Death.Saw:
	Death:
	TNT1 A 0 a_spawnprojectile ("XDeathMancubusArm", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnItem ("DeadDaedabusDA9D_NoArm", 1);
Stop;}}

CLASS DeadDaedabus1NoArm : ACTOR { 
	Default {
	
	Radius 39;
	Height 32;
	Scale 1.2;
	+SHOOTABLE;
	-SOLID;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	-CORPSE;
	-DONTGIB;
	-TELESTOMP;
	Mass 1000;
	Health 500;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	Species "Marine";
	damagefactor "Cut", 4.0;
	damagefactor "Saw", 4.0;
	damagefactor "Tear", 4.0;
	}
	States
    {
	Spawn:
	DA8D GGGGGGGGGGGGGGGGGGGGGG 12;
	DA8D GG 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
	DA8D G -1;
	Stop;
	Death:
	TNT1 A 0;
	TNT1 A 0 a_spawnprojectile ("XDeathMancubusArm", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
	DA4D Y -1;
	Stop;
}
}

CLASS DeadDaedabus2 : ACTOR { 
	Default {
	
	Radius 39;
	Height 33;
	Scale 1.2;
	+SHOOTABLE;
	-SOLID;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	-CORPSE;
	-DONTGIB;
	-TELESTOMP;
	Mass 1000;
	Health 500;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	Species "Marine";
	damagefactor "Cut", 4.0;
	damagefactor "Saw", 4.0;
	damagefactor "Tear", 4.0;
	}
	States
    {
	Spawn:
	DA4D R -1;
	Stop;
	Death:
	TNT1 AA 0 a_spawnprojectile ("XDeathMancubusArm", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnItem ("DeadDaedabus1NoArm", 1);
	Stop;
}
}

CLASS DeadDaedabusHoles : ACTOR { 
	Default {
	
	Radius 39;
	Height 33;
	Scale 1.2;
	+SHOOTABLE;
	-SOLID;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	-CORPSE;
	-DONTGIB;
	-TELESTOMP;
	Mass 1000;
	Health 500;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	Species "Marine";
	damagefactor "Cut", 4.0;
	damagefactor "Saw", 4.0;
	damagefactor "Tear", 4.0;
	}
	States
    {
	Spawn:
	DA4D F -1;
	Stop;
	Death:
	TNT1 AA 0 a_spawnprojectile ("XDeathMancubusArm", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnItem ("DeadDaedabus2NoArm", 1);
	Stop;
}
}

CLASS DeadDaedabus2NoArm : ACTOR { 
	Default {
	
	Radius 39;
	Height 32;
	Scale 1.2;
	+SHOOTABLE;
	-SOLID;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	-CORPSE;
	-DONTGIB;
	-TELESTOMP;
	Mass 1000;
	health 500;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	Species "Marine";
	damagefactor "Cut", 4.0;
	damagefactor "Saw", 4.0;
	damagefactor "Tear", 4.0;
	}
	States
    {
	Spawn:
	DA4D GGGGGGGGGGGGGGGGGGGGGG 12;
	DA4D GG 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
	DA4D G -1;
	Stop;
	Death:
	TNT1 A 0;
	TNT1 A 0 a_spawnprojectile ("XDeathMancubusArm", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
	DA5D X -1;
	Stop;
}
}

CLASS DeadDaedabusSlump : ACTOR { 
	Default {
	
	Radius 39;
	Height 33;
	Scale 1.2;
	+SHOOTABLE;
	-SOLID;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	-CORPSE;
	-DONTGIB;
	-TELESTOMP;
	Mass 1000;
	health 500;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	Species "Marine";
	damagefactor "Cut", 4.0;
	damagefactor "Saw", 4.0;
	damagefactor "Tear", 4.0;
	}
	States
    {
	Spawn:
	DA7D I -1;
	Stop;
	Death:
	TNT1 AA 0 a_spawnprojectile ("XDeathMancubusArm", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnItem ("DeadDaedabus3NoArm", 1);
	Stop;
}
}

CLASS DeadDaedabus3NoArm : ACTOR { 
	Default {
	
	Radius 39;
	Height 32;
	Scale 1.2;
	+SHOOTABLE;
	-SOLID;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	-CORPSE;
	-DONTGIB;
	-TELESTOMP;
	Mass 1000;
	health 500;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	Species "Marine";
	damagefactor "Cut", 4.0;
	damagefactor "Saw", 4.0;
	damagefactor "Tear", 4.0;
	}
	States
    {
	Spawn:
	DA5D ZZZZZZZZZZZZZZZZZZZZZZZZZ 12;
	DA5D ZZ 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
	DA5D Z -1;
	Stop;
	Death:
	TNT1 A 0;
	TNT1 A 0 a_spawnprojectile ("XDeathMancubusArm", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
	DA5D Y -1;
	Stop;
}
}

CLASS DeadDaedabusHead : ACTOR { 
	Default {
	
	Radius 39;
	Height 33;
	Scale 1.2;
	+SHOOTABLE;
	-SOLID;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	-CORPSE;
	-DONTGIB;
	-TELESTOMP;
	Mass 1000;
	health 500;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	Species "Marine";
	damagefactor "Cut", 4.0;
	damagefactor "Saw", 4.0;
	damagefactor "Tear", 4.0;
	}
	States
    {
	Spawn:
	DA3D T -1;
	Stop;
	Death:
	TNT1 AA 0 a_spawnprojectile ("XDeathMancubusArm", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnItem ("DeadDaedabus4NoArm", 1);
	Stop;
}
}

CLASS DeadDaedabus4NoArm : ACTOR { 
	Default {
	
	Radius 39;
	Height 32;
	Scale 1.2;
	+SHOOTABLE;
	-SOLID;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	-CORPSE;
	-DONTGIB;
	-TELESTOMP;
	Mass 1000;
	health 500;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	Species "Marine";
	damagefactor "Cut", 4.0;
	damagefactor "Saw", 4.0;
	damagefactor "Tear", 4.0;
	}
	States
    {
	Spawn:
	DA4D WWWWWWWWWWWWWWWWWWWWWWWWWWW 12;
	DA4D WW 1 A_SpawnItemEx ("SwarmFly",frandom(-16,16),frandom(-16,16),frandom(-16,16));
	DA4D W -1;
	Stop;
	Death:
	TNT1 A 0;
	TNT1 A 0 a_spawnprojectile ("XDeathMancubusArm", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
	DA4D V -1;
	Stop;
}
}

CLASS DaedTrail : ACTOR { 
	Default {
	
	Scale 0.65;
	RenderStyle "Add";
	Alpha 0.5;
	+NoGravity;
	+NoBlockMap;
	+NoInteraction;
	}
  States
  {
	Spawn:
	DAET ABCDE 2 Bright;
	Stop;
}
}

CLASS FatalizedOtherFatso: DeadFat { 
	Default {
	
	Scale 1.2;
	Health 200;
	Species "Marine";
	damagefactor "Cut", 4.0;
	damagefactor "Saw", 4.0;
	damagefactor "Tear", 4.0;
	}
States
{
	Spawn:
	DA3D M 6 A_PlaySound("Daedabus/Sight");
	TNT1 AAAA 0 a_spawnprojectile ("Blood", 35, 0, random (0, 360), 2, random (0, 160));
	
	DA3D N 6;
	TNT1 AAAA 0 a_spawnprojectile ("Blood", 35, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
	DA3D O 6;
	
	TNT1 AAAA 0 a_spawnprojectile ("Blood", 35, 0, random (0, 360), 2, random (0, 160));
	
	DA3D P 6;
	TNT1 AAAA 0 a_spawnprojectile ("Blood", 35, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("XDeath3", 0, 0, random (0, 360), 2, random (0, 160));
	DA3D Q 6;
	TNT1 AAAA 0 a_spawnprojectile ("RipGuts", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAA 0 a_spawnprojectile ("Blood", 35, 0, random (0, 360), 2, random (0, 160));
	
	DA3D R 6;
	TNT1 AAAA 0 a_spawnprojectile ("Blood", 35, 0, random (0, 360), 2, random (0, 160));
	
	DA3D S 6;
	TNT1 AAAA 0 a_spawnprojectile ("Blood", 35, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("XDeath2", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
	
	DA3D T 6;
	TNT1 AAAA 0 a_spawnprojectile ("Blood", 35, 0, random (0, 360), 2, random (0, 160));
	
	DA3D T -1;
	Stop;
	
	Death:
	TNT1 AA 0 a_spawnprojectile ("XDeathMancubusArm", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A -1;
	Stop;
}
}
	
	

CLASS OtherFatsoXDeath : ACTOR { 
	Default {
	
	Radius 1;
	Height 1;
	Scale 1.2;
	Speed 0;
	Mass 1;
	Decal "BloodSuper";
	BounceFACTOR 0.5;
	BounceType "Doom";
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
	Species "Marine";
	damagefactor "Cut", 4.0;
	damagefactor "Saw", 4.0;
	damagefactor "Tear", 4.0;
	}
    States
    {
	Spawn:
	TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile ("brutal_FlyingBlood", 35, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAAAAAA 0 bright a_spawnprojectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
	TNT1 A 0 a_spawnprojectile ("brutal_FlyingBlood", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath4", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("XDeath3", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeath4", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnItem ("BigBloodSpot");
	Death:
	TNT1 A 0;
	Stop;
}
}

CLASS DaedFire : pb_projectile_base { 
	Default {
	
	Radius 8;
	Height 8;
	Speed 22;
	Fastspeed 23;
	DamageFunction (random(27,31));
	DamageType "Desintegrate";
	PoisonDamage 1, 10, 9;
	PoisonDamageType "Slime";
	Projectile;
	+RANDOMIZE;
	+FORCEXYBILLBOARD;
	-THRUGHOST;
	//RenderStyle "Add"
	Scale 0.5;
	DeathSound "Daedabus/impact";
	SeeSound "Daedabus/gun";
	Decal "Scorch";
	}
	States
	{
	Spawn:
	TNT1 A 0;
	TNT1 A 0 A_Playsound("BGFLMBL", 6, 1, 1);
	Spawn1:
	Fly:
	DB57 AB 1 BRIGHT A_Weave(4, 4, 0.3, 0.3);
	TNT1 A 0 A_SpawnItemEx("GreenTrailSparks", random(1,-1), random(1,-1), random(1,-1), random(-2, 2), random(-2, 2), random(-2, 2), 0, SXF_NOCHECKPOSITION, 0);
	TNT1 A 0 A_SpawnItemEx("BFGAltTrail", Random(-13, 13), Random(-13, 13), Random(0, 18), Random(1, 3), 0, (0.1)*Random(-10, 10), Random(-20, 20), 128);
	DB57 C 1 BRIGHT A_Weave(4, 4, 0.3, 0.3);
	TNT1 A 0 A_SpawnItemEx("GreenFlareSmall", 0, 0, 0, 0, 0, 0, 0, 128);
	Loop;
	
	Death:
	TNT1 A 0 A_StopSound(6);
	TNT1 A 0 A_PlaySound("misc/xdeath4f", 7);
	TNT1 A 0 A_SpawnItem("SmallNewAcidExplosionSmoke",0,0);
	TNT1 A 0 a_spawnprojectile( "GreenCloudSmall", 12, 0, random( 0, 359 ), 2 );
	TNT1 A 0 a_spawnprojectile( "GreenCloudSmall", 12, 0, random( 0, 359 ), 2 );
	TNT1 AAA 0 A_SpawnItemEx("GreenTrailSparks", random(1,-1), random(1,-1), random(1,-1), random(-2, 2), random(-2, 2), random(-2, 2), 0, SXF_NOCHECKPOSITION, 0);
	EXPG ABCDEFG 2 BRIGHT Light("BARONBALL") A_SpawnItem("GreenFlare",0,0);
	TNT1 AAAA 19 a_spawnprojectile("PlasmaSmoke", 1, 0, random (0, 360), 2, random (0, 160));
	Stop;
	
	XDeath:
	TNT1 A 0 A_StopSound(6);
	TNT1 A 0 A_SpawnItem("SmallNewAcidExplosionSmoke",0,0);
	TNT1 A 0 a_spawnprojectile( "GreenCloudSmall", 12, 0, random( 0, 359 ), 2 );
	TNT1 A 0 a_spawnprojectile( "GreenCloudSmall", 12, 0, random( 0, 359 ), 2 );
	TNT1 AAA 0 A_SpawnItemEx("GreenTrailSparks", random(1,-1), random(1,-1), random(1,-1), random(-2, 2), random(-2, 2), random(-2, 2), 0, SXF_NOCHECKPOSITION, 0);
	EXPG ABCDEFG 2 Light("BARONBALL") A_SpawnItem("GreenFlare",0,0);
	Stop;
}
}
	
CLASS DaedabusGreenCloudSmall : pb_projectile_base { 
	Default {
	
	Speed 10;
	DamageType "Desintegrate";
	}
	States
	{
	Pain.Flames:
	Pain.Fire:
	Pain.Burn:
	TNT1 A 0;
	Goto Flames;
	Flames:
	TNT1 A 0 A_Explode;
	TNT1 A 0 A_PlaySound("Afrit/Hellfire", 8);
	TNT1 A 0 {self.bNOGRAVITY = false;}
	TNT1 AAAA 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	EXPL A 0 A_SpawnItem("ExplosionParticleSpawner");
	EXPL A 0 A_SpawnItem("ExplosionParticleSpawner");
	EXPL AAAAA 0 a_spawnprojectile ("FireballExplosionFlamesBig", 6, 0, random (0, 360), 2, random (0, 360));
	FRFX ZZZ 0 BRIGHT a_spawnprojectile ("BigNeoSmoke", 2, 0, random (0, 360), 2, random (0, 360));
	EXPL AAAAA 0 a_spawnprojectile ("FireballExplosionFlamesBig", 6, 0, random (0, 360), 2, random (0, 360));
	EXPL A 0 a_spawnprojectile ("FlyingBurningFuelSmall", 12, 0, 90, 2, random (50, 130));
	EXPL AAAAA 0 a_spawnprojectile ("FireballExplosionFlamesBig", 6, 0, random (0, 360), 2, random (0, 360));
	EXPL AAA 0 a_spawnprojectile ("FlyingBurningFuelSmall", 12, 0, 270, 2, random (50, 130));
	EXPL A 0 a_spawnprojectile ("FlyingBurningFuelSmall", 12, 0, 270, 2, random (50, 130));
	EXPL AAAA 0 a_spawnprojectile ("FireballExplosionFlamesBig", 6, 0, random (0, 360), 2, random (0, 360));
	EXPL A 0 a_spawnprojectile ("FlyingBurningFuelSmall", 12, 0, 270, 2, random (50, 130));
	stop;
	Spawn:
	TNT1 A 0 A_Playsound("redburn");
	GTXS ABCDE 7;
	GTXS A 0 A_Explode ( 3, 100 );
	Loop;
}
}

CLASS DaedabusGreenCloudMedium : pb_projectile_base { 
	Default {
	
	Speed 10;
	DamageType "Desintegrate";
	}
	States
	{
	Pain.Flames:
	Pain.Fire:
	Pain.Burn:
	TNT1 A 0;
	Goto Flames;
	Flames:
	TNT1 A 0 A_Explode;
	TNT1 A 0 A_PlaySound("Afrit/Hellfire", 8);
	TNT1 A 0 {self.bNOGRAVITY = false;}
	TNT1 AAAA 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	EXPL A 0 A_SpawnItem("ExplosionParticleSpawner");
	EXPL A 0 A_SpawnItem("ExplosionParticleSpawner");
	EXPL AAAAA 0 a_spawnprojectile ("FireballExplosionFlamesBig", 6, 0, random (0, 360), 2, random (0, 360));
	FRFX ZZZ 0 BRIGHT a_spawnprojectile ("BigNeoSmoke", 2, 0, random (0, 360), 2, random (0, 360));
	EXPL AAAAA 0 a_spawnprojectile ("FireballExplosionFlamesBig", 6, 0, random (0, 360), 2, random (0, 360));
	EXPL A 0 a_spawnprojectile ("FlyingBurningFuelSmall", 12, 0, 90, 2, random (50, 130));
	EXPL AAAAA 0 a_spawnprojectile ("FireballExplosionFlamesBig", 6, 0, random (0, 360), 2, random (0, 360));
	EXPL AAA 0 a_spawnprojectile ("FlyingBurningFuelSmall", 12, 0, 270, 2, random (50, 130));
	EXPL A 0 a_spawnprojectile ("FlyingBurningFuelSmall", 12, 0, 270, 2, random (50, 130));
	EXPL AAAA 0 a_spawnprojectile ("FireballExplosionFlamesBig", 6, 0, random (0, 360), 2, random (0, 360));
	EXPL A 0 a_spawnprojectile ("FlyingBurningFuelSmall", 12, 0, 270, 2, random (50, 130));
	stop;
	Spawn:
	TNT1 A 0 A_Playsound("redburn");
	GTXM ABCDE 7;
	GTXM A 0 A_Explode ( 4, 135 );
	Loop;
}
}

CLASS FatalizedOtherFatso2: DeadFat { 
	Default {
	
	}
	States{
	Spawn:
	TNT1 A 0 A_PlaySound("Daedabus/Active",2);
	FDA1 HHHH 3 a_spawnprojectile ("MuchBlood", 32, 2, random (0, 360), 2, random (0, 160));
	
	TNT1 A 0 A_PlaySound("flamersh",1);
	TNT1 A 0 A_SpawnItem("GreenFlare",0,10);
	TNT1 A 0 A_SpawnItemEx("PlasmaParticleSpawner", 0, 0, 10, 6, 6, 6, 0, 128);
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudLarge", 22, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudLarge", 44, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 H 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 H 2;
	
	TNT1 A 0 A_PlaySound("flamersh",1);
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 H 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 H 2;
	
	TNT1 A 0 A_PlaySound("flamersh",1);
	TNT1 A 0 A_SpawnItem("GreenFlare",0,10);
	TNT1 A 0 A_SpawnItemEx("PlasmaParticleSpawner", 0, 0, 10, 6, 6, 6, 0, 128);
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 H 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 H 2;
	
	TNT1 A 0 A_PlaySound("flamersh",1);
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 H 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 H 2;
	
	TNT1 A 0 A_PlaySound("flamersh",1);
	TNT1 A 0 A_SpawnItem("GreenFlare",0,10);
	TNT1 A 0 A_SpawnItemEx("PlasmaParticleSpawner", 0, 0, 10, 6, 6, 6, 0, 128);
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 H 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 H 2;
	TNT1 A 0 A_PlaySound("Daedabus/Pain",3);
	TNT1 A 0 A_PlaySound("flamersh",1);
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudLarge", 12, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudLarge", 22, 0, random (0, 360), 2, random (0, 160));
	FDA1 H 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 H 2;
	TNT1 A 0 A_PlaySound("Daedabus/Pain",3);
	TNT1 A 0 A_PlaySound("flamersh",1);
	TNT1 A 0 A_SpawnItem("GreenFlare",0,10);
	TNT1 A 0 A_SpawnItemEx("PlasmaParticleSpawner", 0, 0, 10, 6, 6, 6, 0, 128);
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 H 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 H 2;
	EXPL A 0 Radius_Quake (3, 60, 0, 11, 0);
	TNT1 A 0 A_PlaySound("Daedabus/Pain",3);
	TNT1 A 0 A_PlaySound("flamersh",1);
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudLarge", 12, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudLarge", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 H 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 H 2;
	TNT1 A 0 A_PlaySound("Daedabus/Pain",3);
	TNT1 A 0 A_PlaySound("flamersh",1);
	TNT1 A 0 A_SpawnItem("GreenFlare",0,10);
	TNT1 A 0 A_SpawnItemEx("PlasmaParticleSpawner", 0, 0, 10, 6, 6, 6, 0, 128);
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 H 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 I 2;
	TNT1 A 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudSmall", 42, 0, random (0, 360), 2, random (0, 160));
	FDA1 H 2;
	goto Death;
	
	Death:
	EXPL A 0 Radius_Quake (3, 60, 0, 11, 0);
	TNT1 A 0 A_PlaySound("misc/gibbed",4,4);
	TNT1 A 0 A_SpawnItem("BFGAltShockWave",0,25);
	TNT1 A 0 a_spawnprojectile ("MeatDeath", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudLarge", 12, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("GreenCloudLarge", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("GreenCloudMedium", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 a_spawnprojectile ("XDeathMancubusArm", 20, 0, random (0, 360), 2, random (50, 130));
	TNT1 AAAA 0 a_spawnprojectile ("brutal_FlyingBlood", 75, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAAAA 0 a_spawnprojectile ("CeilBloodLauncher", 50, 0, random (0, 360), 2, random (50, 130));
	TNT1 AA 0 a_spawnprojectile ("brutal_FlyingBlood", 65, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAA 0 a_spawnprojectile ("MuchBlood2", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAA 0 a_spawnprojectile ("XDeath4", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAA 0 a_spawnprojectile ("XDeath2", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAAAA 0 a_spawnprojectile ("MuchBlood2", 30, 0, random (0, 360), 2, random (0, 160));
	XDAT D 6 A_Scream;
	XDAT E 6 A_NoBlocking;
	XDAT F 6 A_BossDeath;
	TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
	TNT1 A 0 A_SpawnItem ("XDeadDaedabus", 1);
	stop;
}
}

CLASS DaedabusLiquidAcid: pb_projectile_base { 
	Default {
	
	-NOCLIP;
	-NOBLOCKMAP;
	-NOGRAVITY;
	+NOEXTREMEDEATH;
	
	Damage 0;
	PoisonDamage 4, 6;
	RenderStyle "Translucent";
	Scale 0.5;
	Alpha 0.85;
	Speed 18;
	Decal "Scorch";
	SeeSound "redburn";//FLMFIRE1
	DeathSound "blooddrip";
	Radius 9;
	Height 9;
	gravity 0.2;
	Damagetype "Desintegrate";
	PoisonDamageType "Desintegrate";
	//translation "168:191=112:127","16:47=120:127"
Translation "0:255=%[0,0,0]:[0,1,0]";
	}
    States
    {
	
Spawn:
	TNT1 A 0;
	TNT1 A 0 A_Jump(128, "Spawn2", "Spawn3");
	MSBL ABCDEFGH 2 BRIGHT;//A_SpawnItem("GreenBloodTrails")
	Loop;
	
Spawn2:
	MSBU ABCDEFGH 2 BRIGHT;//A_SpawnItem("GreenBloodTrails")
	Loop;
	
Spawn3:
	MSBZ ABCDEFGH 2 BRIGHT;//A_SpawnItem("GreenBloodTrails")
	Loop;
	
	
	
Death:
Crash:
XDeath:
	TNT1 A 0 A_PlaySound("blooddrip", 6);
	TNT1 A 0 A_Explode(2, 12, 1);
	TNT1 AA 0 A_SpawnItemEx("PlasmaParticleSpawner", 0, 0, 0, 6, 6, 6, 0, 128);
	XDT1 FGHIJKL 2;
	TNT1 A 0;
	Stop;
}
}


CLASS DaedabusFatalityHelper : ACTOR { 
	Default {
 
	Height 0;
	+NOBLOOD
	}
	States
	{
	Spawn:
	FDXE R 6;
	FDXE RR 6;
	FDXE RR 6;
	FDXE R 6 ;
	FDXE RRR 6;
	FDXE R 12 ;
	FDXE SSS 7;
	FDXE TTT 5;
	Stop;
	}
}

CLASS DaedabusFatalityHelper2 : ACTOR { 
	Default {
 
	Height 0;
	+NOBLOOD
	}
	States
	{
	Spawn:
	FDX1 A 5 ;
	FDX1 B 5 ;
	FDX1 A 5 ;
	FDX1 B 5 ;
	FDX1 AB 3;
	FDX1 C 4 ;
	FDX1 C 2 ;
	FDX1 C 2 ;
	FDX1 C 2 ;
	FDX1 C 5 ;
	FDX1 F 11;
	FDX1 F 11;
	Stop;
	}
}


CLASS DyingDaedabus01: NoGutsDaedabus2 { 
	Default {
 Scale 1.0 ;
Health 130 ;
Radius 28;
Height 56;
-CLIENTSIDEONLY
	}
States
	{Spawn:
	D4T1 A 1 A_PlaySound("Daedabus/pain");
        D4T1 EEEEEEEEEEEEEEEE 3 a_spawnprojectile ("Brutal_LiquidBlood2", 40, 0, random (0, 360), 2, random (30, 50));
	
	D4T1 A 3 A_PlaySound("Daedabus/pain");
        D4T1 EEEEEEEEEEEEEEEE 3 a_spawnprojectile ("Brutal_LiquidBlood2", 40, 0, random (0, 360), 2, random (30, 50));
	
	D4T1 A 3 A_PlaySound("Daedabus/pain");
        D4T1 EEEEEEEEEEEEEEEE 3 a_spawnprojectile ("Brutal_LiquidBlood2", 40, 0, random (0, 360), 2, random (30, 50));
	
	D4T1 A 3 A_PlaySound("Daedabus/pain");
        D4T1 EEEEEEEEEEEEEEEE 3 a_spawnprojectile ("Brutal_LiquidBlood2", 40, 0, random (0, 360), 2, random (30, 50));
	TNT1 A 0;
	TNT1 A 0 A_NoBlocking;
	TNT1 A 0 A_Scream;
	D4T1 BC 4;
	TNT1 A 0 A_SpawnItem("DeadDaedabus3NoArm");
	Stop;
	
	Death:
	Death.Cutless:
	   Death.Cut:
	   Death.Saw:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_PlaySound("Daedabus/pain");
		TNT1 AAA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("MuchBlood2", 55, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathMancubusArm", 30, 0, random (0, 360), 2, random (50, 130));
		D4T2 AAAAAAA 2 a_spawnprojectile ("Brutal_LiquidBlood2", 50, 0, random (0, 360), 2, random (30, 50));
		TNT1 A 0 A_SpawnItem("DyingDaedabus02");
	stop;
		}}	
		
		
		
CLASS DyingDaedabus02: DyingDaedabus01 { 
	Default {
 Scale 1.0;
Health 130;	}
 States
	{Spawn:
	D4T2 AAAAAAAAAAAAAAAAAAAAAAAAAAAA 2 a_spawnprojectile ("Brutal_LiquidBlood2", 50, 0, random (0, 360), 2, random (30, 50));
	
	TNT1 A 0 A_NoBlocking;
	TNT1 A 0 A_Scream;
	D4T2 BC 4;
	TNT1 A 0 A_SpawnItem("FuckedDaedabus1");
	Stop;
	
	Death:
	Death.Cutless:
	   Death.Cut:
	   Death.Saw:
		TNT1 A 0;
	TNT1 AAAAAA 0 a_spawnprojectile ("Xdeath1", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAA 0 a_spawnprojectile ("Brains1", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("Brains2", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 a_spawnprojectile ("Brains6", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("Brains7", 62, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 a_spawnprojectile ("MancubusEyeballs", 62, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("MuchBlood2", 55, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		D4T3 AAA 2 a_spawnprojectile ("Brutal_LiquidBlood2", 50, 0, random (0, 360), 2, random (30, 50));
		TNT1 A 0 A_SpawnItem("DyingDaedabus03");
	stop;
}}		

CLASS DyingDaedabus03: DyingDaedabus02 { 
	Default {
 Scale 1.0; 
Health 130;	}
 States
	{Spawn:
	D4T3 AAAAAAAAAAAAAAAAAAAAAAAAAAAA 2 a_spawnprojectile ("Brutal_LiquidBlood2", 50, 0, random (0, 360), 2, random (30, 50));
	
	TNT1 A 0 A_NoBlocking;
	TNT1 A 0 A_Scream;
	D4T3 B 4;
	TNT1 A 0 A_SpawnItem("FuckedDaedabus2");
	Stop;
	
	Death:
	Death.Cutless:
	   Death.Cut:
	   Death.Saw:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("RipGuts", 0, 40);
		TNT1 AAA 0 a_spawnprojectile ("MuchBlood2", 55, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("XDeath2", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeath4", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathDaedabusTorso", 30, 0, random (0, 360), 2, random (40, 160));
		D4T4 AAAAAABBBC 2 a_spawnprojectile ("Brutal_LiquidBlood2", 40, 0, random (0, 360), 2, random (30, 50));
		TNT1 A 0 A_SpawnItem("DeaddAEDABUSLegStumps");
	stop;
		}}	

CLASS DeaddAEDABUSLegStumps: NoGutsDaedabus2 { 
default{Health 200;}States{Spawn:
	D4T4 C -1;
        Stop ; 
	
       Death:
        TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 a_spawnprojectile ("XDeathDaedabusLeg", 20, 0, random (0, 360), 2, random (50, 130));
		TNT1 AA 0 a_spawnprojectile ("MuchBlood2", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("XDeath2b", 25, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("XDeath3b", 25, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("Instestin", 30, 0, random (0, 360), 2, random (40, 90));
	Stop;
}

}
	
CLASS DeadDaedabusD4T5J: DEADDAEDABUSHEAD { 
default{Health 200;}States{Spawn:
	D4T5 J -1;
        Stop  ;
}}
