class proto_fat : pb_monster_base
{
bool rage;
states
{
	Death.Blackhole:
		TNT1 A 0 {A_Scream(); A_BossDeath(); A_NoBlocking();}
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40))	;		
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		ID55 AABCDEFGHIJK 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 40, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
	Stop;
}

}




























CLASS XDeathDaedabusEyeball : pb_blood_and_gore_base { 
	Default {
	
	Radius 2;
	Height 2;
	Speed 6;
	Mass 1;
	Decal "GreenBloodSpot";
	+CLIENTSIDEONLY;
	BounceFactor 0.4;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	+FLOORCLIP;
	Scale 1.1;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		M4NA UVWX 4 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 360));
		Loop;
	Death:
		M4NA Y 1;
		TNT1 A 0 A_QueueCorpse;
 	Rest:
		M4NA Y 2000;
		M4NA Y -1;
		Stop;
		
	DoNothing:
		TNT1 A 0;
		Stop;
	}
}


CLASS MancubusEyeballs : pb_blood_and_gore_base { //Eyeballs
	Default {
	
	Radius 2;
	Height 2;
	Speed 6;
	Mass 1;
	Decal "BrutalBloodSplat";
	+CLIENTSIDEONLY;
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	+FLOORCLIP;
	Scale 1.2;
	}
    States
    {
	Spawn:
	TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
	MANE Y 4;//a_spawnprojectile("named_BloodTr", 0, 0, random(0, 360), 2, random(0, 360))
	Loop;
	Death:
	MANE Y 1;
	TNT1 A 0 A_QueueCorpse;
 	Goto Rest;
	
	
	Rest:
	MANE Y 800;
	MANE Y -1;
	Stop;
	
	DoNothing:
	TNT1 A 0;
	Stop;
}
}

CLASS VolcabusEyeballs : pb_blood_and_gore_base { 
	Default {
	
	Radius 2;
	Height 2;
	Speed 6;
	Mass 1;
	Decal "BrutalBloodSplat";
	+CLIENTSIDEONLY;
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	+FLOORCLIP;
	Scale 1.35;
	}
    States
    {
	Spawn:
	TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
	V0LC Y 4;//a_spawnprojectile("named_BloodTr", 0, 0, random(0, 360), 2, random(0, 360))
	Loop;
	Death:
	V0LC Y 1;
	TNT1 A 0 A_QueueCorpse;
 	Goto Rest;
	
	
	Rest:
	V0LC Y 800;
	V0LC Y -1;
	Stop;
	
	DoNothing:
	TNT1 A 0;
	Stop;
}
}



CLASS XDeathMancubusHead: XDeathBullArm1 { 
	Default {
	
	-CLIENTSIDEONLY;
	Scale 0.9;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		XHE7 ABCD 6;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		XHE5 A 1;
		XHE5 A 1 A_SpawnItem("MancubusHead",0,0,0,1);
		Stop;
	}
}



CLASS MancubusHead: LimbBase { 
	Default {
	
	damagefactor "Kick", 9.0;
	damagefactor "Melee", 9.0;
	damagefactor "SuperPunch", 9.0;
	-CLIENTSIDEONLY;
	Radius 10;
	
	Mass 12;
	Health 60;
	Scale 0.9;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		XHE7 B 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		XHE7 B -1;
		Stop;
		
	Death:
		TNT1 AAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains2", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains2", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains4", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains4", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 AAAAAA 0 a_spawnprojectile("SmallBrainPiece", 5, 0, random(0, 360), 2, random(60, 140));
		Stop;
	Death.Trample:
	Crush:
		//TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
		TNT1 AAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS1 B 5;
		CRS1 B 9009;
		Stop;
	Death.plasma:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL A 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0;
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		XHE7 A 1 A_Pain;
		XHE7 A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeathMancubusHeadKicked", 5, 0, random(170, 190), 2, random(20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		XHE7 ABCD 3;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		XHE7 ABCD 6;
		XHE7 I 0 A_SpawnItem("MancubusHead");
		Stop;
		
}}

CLASS XDeathDaedabusHead: XDeathBullArm1 { 
	Default {
	
	-CLIENTSIDEONLY;
	Scale 0.9;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		XH37 ABCD 6;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		XH37 A 1;
		XH37 A 1 A_SpawnItem("DaedabusHead",0,0,0,1);
		Stop;
	}
}



CLASS DaedabusHead: LimbBase { 
	Default {
	
	damagefactor "Kick", 9.0;
	damagefactor "Melee", 9.0;
	damagefactor "SuperPunch", 9.0;
	-CLIENTSIDEONLY;
	Radius 10;
	
	Mass 12;
	Health 60;
	Scale 0.9;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		XH37 B 1 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		XH37 B -1;
		Stop;
		
	Death:
		TNT1 AAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains2", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains2", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains4", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 a_spawnprojectile("Brains4", 5, 0, random(0, 360), 2, random(60, 140));
		TNT1 AAAAAA 0 a_spawnprojectile("SmallBrainPiece", 5, 0, random(0, 360), 2, random(60, 140));
		Stop;
	Death.Trample:
	Crush:
		//TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
		TNT1 AAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail", 0, 0, random(0, 360), 2, random(60, 140));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS1 B 5;
		CRS1 B 9009;
		Stop;
	Death.plasma:
		TNT1 A 0;
		TNT1 A 0 a_spawnprojectile("XDeathBurnedSkull", 32, 0, random(0, 360), 2, random(0, 160));
		EXPL A 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0;
		Stop;
	Death.Melee:
	Death.SuperPunch:
	Death.Kick:
		XH37 A 1 A_Pain;
		XH37 A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 a_spawnprojectile("XDeathDaedabusHead", 5, 0, random(170, 190), 2, random(20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		XH37 ABCD 3;
		Goto Spawn;
		
	Death.ExplosiveImpact:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		XH37 ABCD 6;
		XH37 I 0 A_SpawnItem("DaedabusHead");
		Stop;
		
}}



CLASS XDeathMancubusHeadKicked: XDeathMancubusHead { 
	Default {
	
	-BOUNCEONACTORS;
	Damage 4;
	Speed 13;
	BounceFactor 0.4;
	}
}



CLASS XDeathVolcabusArm: XDeathArm1 { 
	Default {
 
    +SKYEXPLODE
	-CLIENTSIDEONLY
    Scale 1.2;
    Speed 9;
	Gravity 0.4;
bounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		VOLA ABCDEFGH 3;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		VOLA I -1;
		Stop;
	}
}

CLASS XDeathMancubusTorso: XDeathArm1 { 
	Default {
	
	+SKYEXPLODE;
	-CLIENTSIDEONLY;
	Scale 1.2;
	Speed 9;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		MANA IJKLMNOP 3;
		Loop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	Rest:
		MANA QRSTTT 4;
		Loop;
	}
}

CLASS XDeathMancubusLeg: XDeathArm1 { 
	Default {
	
	+SKYEXPLODE;
	-CLIENTSIDEONLY;
	Scale 1.2;
	Speed 9;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		MAN4 ABCDEFGH 3;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		MAN4 I -1;
		Stop;
	}
}

CLASS XDeathDaedabusTorso: XDeathArm1 { 
	Default {
	
	+SKYEXPLODE;
	-CLIENTSIDEONLY;
	Scale 1.2;
	Speed 9;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		M4NA IJKLMNOP 3;
		Loop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
	Rest:
		M4NA QRSTTT 4;
		Loop;
	}
}

CLASS XDeathDaedabusLeg: XDeathArm1 { 
	Default {
	
	+SKYEXPLODE;
	-CLIENTSIDEONLY;
	Scale 1.2;
	Speed 9;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		M4N4 ABCDEFGH 3;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		TNT1 A 0;
		TNT1 A 0 A_QueueCorpse;
		M4N4 I -1;
		Stop;
	}
}

CLASS XDeathMancubusArm: XDeathArm1 { 
	Default {
	
	+SKYEXPLODE;
	-CLIENTSIDEONLY;
	Scale 1.1;
	Speed 9;
	Gravity 0.4;
	BounceFactor 0.4;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		MANA ABCDEFG 3;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem("PB_Blood_Spot",0,0,0,1);
		HND8 A 0;
		//HND8 A 0 A_SpawnItem("FlameCannon",0,0,0,1);
		Stop;
		TNT1 A 0;
		MANA H -1;
		Stop;
	}
}


CLASS MancubusHeadExplode: ZombieXDeath { 
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAAA 0 a_spawnprojectile("Bloodmist", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AA 0 a_spawnprojectile("MancubusEyeballs", 0, 0, random(0, 360), 2, random(10, 90));
		TNT1 AA 0 a_spawnprojectile("Brains4", 0, 0, random(0, 360), 2, random(10, 90));
		TNT1 AA 0 a_spawnprojectile("Brains4", 0, 0, random(0, 360), 2, random(10, 90));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPieceFast", 0, 0, random(0, 360), 2, random(10, 20));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPiece", 0, 0, random(0, 360), 2, random(10, 90));
		
		TNT1 AAA 0 a_spawnprojectile("Teeth", 0, 0, random(0, 360), 2, random(10, 90));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(10, 90));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 90));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 10, 0, random(0, 360), 2, random(50, 90));
		TNT1 A 10;
		Stop;
}
}

CLASS DaedabusHeadExplode: ZombieXDeath { 
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AAAAAA 0 a_spawnprojectile("Bloodmist", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("XDeathDaedabusEyeball", 0, 0, random(0, 360), 2, random(10, 90));
		//TNT1 AA 0 a_spawnprojectile("Brains4", 0, 0, random(0, 360), 2, random(10, 90));
		TNT1 AA 0 a_spawnprojectile("Brains4", 0, 0, random(0, 360), 2, random(10, 90));
		TNT1 AAA 0 a_spawnprojectile("SmallBrainPieceFast", 0, 0, random(0, 360), 2, random(10, 20));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPiece", 0, 0, random(0, 360), 2, random(10, 90));
		
		TNT1 AAA 0 a_spawnprojectile("Teeth", 0, 0, random(0, 360), 2, random(10, 90));
		TNT1 AAAAAA 0 a_spawnprojectile("XDeath1", 0, 0, random(0, 360), 2, random(10, 90));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 10, 0, random(0, 360), 2, random(50, 90));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 10, 0, random(0, 360), 2, random(50, 90));
		TNT1 A 10;
		Stop;
}
}

