CLASS pb_Hell_lion : proto_arch_vile// Replaces Archvile
{
protected bool anger;
Default
{
	Health 900;
	//SpawnID 2330;
	Scale 1.32;
	Mass 620;
	Speed 17;
	Monster;
	+FloorClip;
	-STEALTH;

	PainChance 12;
	PainChance "Stun", 255;
	PainChance "Kick", 90;
	PainChance "ExtremePunches", 90;

	damagefactor "Head", 0.45;
	damagefactor "killme", 0.0;	damagefactor "GibRemoving", 0.0;
	DamageFactor "CauseObjectsToSplash", 0.0; damagefactor "TeleportRemover", 0.0;
	damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0; damagefactor "Avoid", 0.0;	

	BloodType "Brutal_Blood", "BloodSPlatterReplacer", "AxeBlood";
	Obituary "A Hellion burned %o to a crisp.";
	SeeSound "monster/hlnsit";
	PainSound "monster/hlnpai";
	DeathSound "monster/hlndth";
	ActiveSound "monster/hlnact";

/*	//DropItem "DemonStrengthRune", 5;
	//DropItem "DemonMorphRune", 5;
	//DropItem "RageSphere", 5;
	//DropItem "DoubleSphere", 5;
	//DropItem "TimeSphere", 2;
	//DropItem "Demonpickup2", 255;
	//DropItem "Demonpickup2", 25;*/
}
States
{
	Spawn:
		TNT1 A 0;
	Stand:
		HELN A 10 A_Look;
	Loop;

	ChillOutBro:
		HELN G 2 
		{
			self.bSTEALTH= false; self.bMISSILEMORE= false; self.bMISSILEEVENMORE= false;
			A_SetSpeed(17);
			anger = false;
			A_PlaySound("Afrit/Hellfire", 8);
			a_spawnprojectile("CoolandNewFlameTrails", 6, 0, random(0, 360), 2, random(0, 360));
			A_FadeIn(0.25, FALSE);
			A_FaceTarget();
		}
		HELN GG 2 { A_FaceTarget(); A_FadeIn(0.25, FALSE);}
	Goto See;
		
	See:
		TNT1 A 0 {if(anger == true) {setstatelabel("SPLIT_THEM_OPEN");} }
		HELN AA 2 A_Chase;
		TNT1 A 0 A_PlaySound("vile/step",5);
		HELN BBCC 2 A_Chase;
		TNT1 A 0 A_PlaySound("vile/step",5);
		HELN DDEE 2 A_Chase;
		TNT1 A 0 A_PlaySound("vile/step",5);
		HELN FF 2 A_Chase;
	Loop;
		
	SPLIT_THEM_OPEN:
		TNT1 A 0 A_SpawnItemEx("HellionTrail",0,0,30);
		TNT1 A 0 A_SpawnItemEx("WalkFire",0,0,0);
		TNT1 A 1 A_Chase;
		TNT1 A 0 A_SpawnItemEx("HellionTrail",0,0,30);
		TNT1 A 0 A_CheckSight("ChillOutBro");
		TNT1 A 0 A_CheckRange(2000, "ChillOutBro");
	Loop;
		
	Missile:
		TNT1 A 0 {if(anger == true) {setstatelabel("ApeShitFireBall"); } }
		TNT1 A 0 A_CheckSight(2);
		TNT1 A 0 A_Jump(64, "TryGoingApeShit");
		TNT1 A 0;
		TNT1 A 0;
	RegularAttack:
		TNT1 A 0 A_Jump(100, "ArchvileAttack");
		HELN G 3 A_VileStart;
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));//
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 85, -35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 85, 35, random(0, 40), 2, random(0, 160));
		HELN G 3;
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));//
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 85, -35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 85, 35, random(0, 40), 2, random(0, 160));
		HELN HIJK 6 Bright A_FaceTarget;
		HELN L 6 Bright a_spawnprojectile("HellionBall",32,0,0,0,0);
		HELN L 2;
	Goto See;
		
	ArchvileAttack:
		HELN G 0 A_VileStart;
		HELN G 10 A_FaceTarget;
		HELN GGGG 3
		{
			A_VileTarget();
			a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
			a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));//
			a_spawnprojectile("ExplosionParticle", 85, -35, random(0, 40), 2, random(0, 160));
			a_spawnprojectile("ExplosionParticle", 85, 35, random(0, 40), 2, random(0, 160));
		}
		HELN HH 3 A_FaceTarget;
		HELN G 1 A_VileTarget;
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 85, -35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 85, 35, random(0, 40), 2, random(0, 160));
		HELN G 3 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 85, -35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 85, 35, random(0, 40), 2, random(0, 160));
		HELN H 3 A_FaceTarget;
		HELN G 1 A_VileTarget;
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 85, -35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 85, 35, random(0, 40), 2, random(0, 160));
		HELN G 3 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));
		HELN H 3 A_FaceTarget;
		HELN G 1 A_VileTarget;
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 85, -35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 85, 35, random(0, 40), 2, random(0, 160));
		HELN G 3 A_FaceTarget;
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 85, -35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 85, 35, random(0, 40), 2, random(0, 160));
		HELN H 3 A_FaceTarget;
		
		HELN IJ 4 BRIGHT A_FaceTarget;
		HELN K 5 BRIGHT A_VileAttack("vile/stop", 15, 50);
		HELN L 3;
	Goto See;

	ApeShitArchvile:
		HELN GGG 2 {A_FaceTarget(); A_FadeIn(.25, FALSE);}

		HELN G 0 A_VileStart;
		HELN G 10 A_FaceTarget;
		HELN G 1 A_VileTarget;
		HELN G 7 A_VileTarget;
		HELN G 1 A_VileTarget;

		HELN GHH 3
		{
			A_FaceTarget();
			a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
			a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));
			a_spawnprojectile("ExplosionParticle", 85, -35, random(0, 40), 2, random(0, 160));
			a_spawnprojectile("ExplosionParticle", 85, 35, random(0, 40), 2, random(0, 160));
		}
		HELN GGH 3
		{
			A_FaceTarget();
			a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
			a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));
			a_spawnprojectile("ExplosionParticle", 85, -35, random(0, 40), 2, random(0, 160));
			a_spawnprojectile("ExplosionParticle", 85, 35, random(0, 40), 2, random(0, 160));
		}
		HELN G 1 A_VileTarget;
		HELN GH 3
		{
			A_FaceTarget();
			a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
			a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));
			a_spawnprojectile("ExplosionParticle", 85, -35, random(0, 40), 2, random(0, 160));
			a_spawnprojectile("ExplosionParticle", 85, 35, random(0, 40), 2, random(0, 160));
		}

		HELN G 1 A_VileTarget;
		HELN GH 3
		{
			A_FaceTarget();
			a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
			a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));
			a_spawnprojectile("ExplosionParticle", 85, -35, random(0, 40), 2, random(0, 160));
			a_spawnprojectile("ExplosionParticle", 85, 35, random(0, 40), 2, random(0, 160));
		}
		
		HELN IJ 4 BRIGHT A_FaceTarget;
		HELN K 5 BRIGHT A_VileAttack("vile/stop", 15, 50);
		HELN L 3;
	Goto SPLIT_THEM_OPEN;
		
	ApeShitFireBall:
		TNT1 A 0 A_Playsound("monster/hlnphasein", 3);
		TNT1 A 0 A_SpawnItem("PentagramSpawner");
		TNT1 A 0 A_Jump(32, "ApeShitArchvile");
		EXPL AAA 0 a_spawnprojectile("CoolandNewFlameTrails", 6, 0, random(0, 360), 2, random(0, 360));
		FRFX ZZ 0 BRIGHT a_spawnprojectile("CasingSmoke", 2, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAA 0 A_SpawnItemEx("HellionTrailSpark", random(-8, 8), random(-8, 8), random(12,40), 0, 0, 0, 0, 128, 0);
		
		TNT1 A 0 A_FadeIn(.20, FALSE);
		HELN H 5 Bright A_VileStart;

		HELN IJK 5 Bright
		{
			A_FaceTarget();
			A_FadeIn(.20, FALSE);
		}
		HELN L 5 Bright a_spawnprojectile("HellionBall",32,0,0,0,0);
		EXPL AAA 0 a_spawnprojectile("CoolandNewFlameTrails", 6, 0, random(0, 360), 2, random(0, 360));
		FRFX ZZ 0 BRIGHT a_spawnprojectile("CasingSmoke", 2, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_Playsound("monster/hlnphaseout");
		TNT1 A 0 A_SpawnItem("PentagramSpawner");
		TNT1 AAAAA 0 A_SpawnItemEx("HellionTrailSpark", random(-8, 8), random(-8, 8), random(12,40), 0, 0, 0, 0, 128, 0);
		HELN LLLLL 2 A_FadeOut(.20, FALSE);
	Goto SPLIT_THEM_OPEN;
		
	TryGoingApeShit:
		TNT1 A 0 A_JumpIfCloser(2000, 1);
	Goto RegularAttack;
	
	GoApeShit:
		//monster/hlnact
		TNT1 A 0 A_FaceTarget;
		H9LN ABC 6 ;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Playsound("monster/hlnact");
		H9LN FCFDFCFDFCFD 4;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Playsound("props/redfire");
		HELN JIH 3 A_SpawnItemEx("WalkFire",0,0,0);
		TNT1 A 0 A_FadeOut(.20, FALSE);
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, 35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("FlameTrails", 85, -35, random(0, 40), 2, random(0, 160));//
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 85, -35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 85, 35, random(0, 40), 2, random(0, 160));
		TNT1 A 0 A_Playsound("monster/hlnphaseout");
		HELN H 3 A_SpawnItemEx("WalkFire",0,0,0);
		TNT1 A 0 A_SpawnItem("PentagramSpawner");
		TNT1 AAAAAAAAAA 0 A_SpawnItemEx("HellionTrailSpark", random(-8, 8), random(-8, 8), random(12,40), 0, 0, 0, 0, 128, 0);
		TNT1 A 0 A_PlaySound("Afrit/Hellfire", 8);
		EXPL AAA 0 a_spawnprojectile("CoolandNewFlameTrails", 6, 0, random(0, 360), 2, random(0, 360));
		FRFX ZZ 0 BRIGHT a_spawnprojectile("CasingSmoke", 2, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 {anger = true;}
		TNT1 A 0 A_FadeOut(.20, FALSE);
		TNT1 A 0 {self.bSTEALTH= true; self.bMISSILEMORE= true; self.bMISSILEEVENMORE= true;}
		TNT1 A 0 A_SetSpeed(80);
	Goto SPLIT_THEM_OPEN;
		
	Pain:
		HELN M 2;
		HELN M 2 A_Pain;
	Goto See;
		
	Possession:
		HELN M 3 {self.binvulnerable = true;}
		HELN M 3 A_Pain;
 		TNT1 A 0 {self.binvulnerable = false;}
	Goto See;
		
	Pain.Stun:
		HELN MMMMMMMMMM 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		HELN M 1 A_Pain;
		tnt1 a 0 a_jumpif(random(0, 10) < 7, "pain.stun");
	Goto See;
		
		
	Death.Ice:
	Death.Freeze:
	Death.Frost:
		TNT1 A 0 {self.bSHOOTABLE= false;}
		TNT1 A 0 {self.bSOLID= false;}
		//TNT1 A 0 A_SpawnItem("FrozenHellion");
	Stop;
		
	Death:
		TNT1 A 0 A_FadeIn(1.0, FALSE);
		TNT1 A 0 A_Jump(164, "Death2", "Death3");
		HELN N 6;
		HELN O 6 A_Scream;
		HELN PQR 6;
		HELN S 6 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadHellion");
	Stop;
	
	Death2:
		H3LN A 6;
		H3LN B 6 A_Scream;
		H3LN C 6;
		H3LN DEF 6;
		H3LN G 1 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadHellion_H3LNG");
		Stop;
	Death3:
		H3LN H 9 A_Scream;
		H3LN IJK 7;
		H3LN L 1 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadHellion_H3LNL");
		Stop;
		
	Death.Fatality:
		TNT1 A 0 A_Pain;
		//TNT1 A 0 A_JumpIfIntargetInventory("FistsSelected", 1, 1);
	Goto Death;
		TNT1 A 0 A_NoBlocking;
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		//TNT1 A 0 A_GiveToTarget("HellionFatality", 1);
		Stop;
		
	XDeath:
	Death.Explosive:
	Death.ExplosiveImpact:
		TNT1 A 0;
		TNT1 A 0 A_FadeIn(1.0, FALSE);
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_XScream;
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 A 0 a_spawnprojectile("XDeath2", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 A 0 a_spawnprojectile("XDeath4", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 A 1 a_spawnprojectile("HellionXDeath", 0, 0, random(0, 360), 2, random(0, 160));
		Stop;
		
		
	Death.Head:
		TNT1 A 0 A_FadeIn(1.0, FALSE);
		TNT1 A 0 A_PlaySound("gore/headshot", 2);
		TNT1 AA 0 a_spawnprojectile("XDeath1", 68, 0, random(0, 360), 2, random(60, 120));
		TNT1 A 0 a_spawnprojectile("XDeath2", 68, 0, random(0, 360), 2, random(60, 120));
		TNT1 AAAA 0 a_spawnprojectile("MuchBlood", 68, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("SmallBrainPiece", 68, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Teeth", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Brains2", 68, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("Brains4", 68, 0, random(0, 360), 2, random(0, 160));
		H8LN NNNNNNNN 2 a_spawnprojectile("Bloodmist", 58, 0, random(0, 360), 2, random(0, 160));
		H8LN O 6 A_xScream;
		H8LN PQR 6;
		H8LN T 6 A_NoBlocking;
		TNT1 A 0 A_PlaySound("BODYF",6);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadHellion_H8LNT");
	Stop;
		
	Death.SuperPlasma:
	Death.GreenFire:
	Death.Plasma: Death.Plasma2:
		TNT1 A 0 A_FadeIn(1.0, FALSE);
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("Barrel_explosion_Column");
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 AAA 0 A_SpawnItemEx("TinyBurningPiece", random(-35, 35), random(-35, 35));
		TNT1 AAAA 0 a_spawnprojectile("BluePlasmaFire", 42, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnItemEx("crutch",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_Stop;
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece", random(-45, 45), random(-45, 35));
		TNT1 A 0;
		TNT1 A 0 A_Scream;
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 52, 0, random(0, 360), 2, random(60, 120));
		TNT1 AA 0 a_spawnprojectile("XDeathBurnedMeat", 52, 0, random(0, 360), 2, random(60, 120));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("MuchBlood", 0, 40);
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(60, 120));
		TNT1 A 0 A_NoBlocking;
		XVIP ABCDEFGHIJKLMNOPQ 2;
		XVIP Q -1;
	Stop;
	
	Death.Fire:
		TNT1 A 0 A_FadeIn(1.0, FALSE);
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Playsound("props/redfire");
		TNT1 AAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		XVIP ABCDEFGHIJKLMNOPQ 2;
		XVIP QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ 2 a_spawnprojectile("FlameTrails", 15, 0, random(0, 360), 2, random(70, 130));
		XVIP QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ 10 a_spawnprojectile("Explosion_Smoke", 15, 0, random(0, 360), 2, random(70, 130));
		XVIP Q -1;
	Stop;
	
	Death.Shrink:
		TNT1 A 1 A_PlaySound("Shrink", 3);
/*		TNT1 A 0 A_SpawnItemEx("HellionShrinkFX1", 0, 0,  5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("HellionShrinkFX2", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("HellionShrinkFX3", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("HellionShrinkFX4", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("HellionShrinkFX5", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("HellionShrinkFX6", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("HellionShrinkFX7", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("LilHellion", 1);*/
	stop;
	
	Death.SSG:
	Death.Blast:
		TNT1 A 0 A_XScream;
		TNT1 AA 0 a_spawnprojectile("Gib_HellionArm", 48, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Gib_HellionTorso", 44, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("Gib_HellionHead", 54, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 52, 0, random(0, 360), 2, random(60, 120));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 52, 0, random(0, 360), 2, random(60, 120));
		TNT1 AA 0 a_spawnprojectile("XDeathOrgan1", 24, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("MuchBlood", 0, 40);
		TNT1 AAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(60, 120));
		TNT1 A 0 A_NoBlocking;
		H3LN M 3;
		H3LN MMMMMMMMMMMMMMMM 2 a_spawnprojectile("Brutal_LiquidBlood", 46, 0, random(0, 360), 2, random(0, 45));
		H3LN NOP 7;
		TNT1 A 0 A_SpawnItem("DeadHellion_H3LNP");
	Stop;
	
	Raise:
		HELN TSRQPON 6;
	Goto See;
}
}

CLASS HellionBall : pb_projectile_base
{ 
Default
{
	Damage 20;
	Speed 20;
	RenderStyle "Add";
	Alpha 1;
	Scale 0.9;
	DamageType "Fire";
	//+ThruGhost
	+ForceXYBillboard;
	SeeSound "Afrit/CometFire";
	DeathSound "Afrit/CometHit";
	Decal "DoomImpScorch";
}
states
{
	Spawn:
		HLBL AB 2 Bright
		{
			A_SpawnItemEx("HellionPuff",0,0,0,0,0,0,0,128);
			A_SpawnItemEx("YellowFlare",0,0,0,0,0,0,0,128);
			A_SpawnItemEx("HellionTrail2", random(1,-1), random(1,-1), random(1,-1), 0, 0, 0, 0, 128, 0);
			a_spawnprojectile("CoolandNewFlameTrails", 0, 0, 0, 2, random(0, 20));
		}
	Loop;

	Death:
		TNT1 AAAAAA 0 A_SpawnItemEx("HellionTrailSpark", random(19,-19), random(19,-19), random(19,-19), 0, 0, 0, 0, 128, 0);
		HLBL JKLMN 2 Bright;
	Stop;
}

}

CLASS HellionTrail : pb_special_effect_base
{ 
Default
{
	renderstyle "Add";
	Damage 0;
	Scale 0.45;
	+NOGRAVITY;
	+THRUACTORS;
	Translation "0:255=%[1,1,0]:[1,1,0]";
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("HellionTrailFlash");
		TNT1 A 0 A_Jump(256, "Spawn2", "Spawn3", "Spawn4", "Spawn5", "Spawn6", "Spawn7", "Spawn8", "Spawn9", "Spawn10");
		DLI1 ABCDEFGHIJK 1 bright;
		Stop;
	Spawn2:
		TNT1 A 0;
		DLI2 ABCDEFGHIJK 1 bright;
		Stop;
	Spawn2:
		TNT1 A 0;
		DLI3 ABCDEFGHIJK 1 bright;
		Stop;
	Spawn3:
		TNT1 A 0;
		DLI3 ABCDEFGHIJK 1 bright;
		Stop;
	Spawn4:
		TNT1 A 0;
		DLI4 ABCDEFGHIJK 1 bright;
		Stop;
	Spawn5:
		TNT1 A 0;
		DLI5 ABCDEFGHIJK 1 bright;
		Stop;
	Spawn6:
		TNT1 A 0;
		DLI2 LMNOPQRSTUV 1 bright;
		Stop;
	Spawn7:
		TNT1 A 0;
		DLI3 LMNOPQRSTUV 1 bright;
		Stop;
	Spawn8:
		TNT1 A 0;
		DLI3 LMNOPQRSTUV 1 bright;
		Stop;
	Spawn9:
		TNT1 A 0;
		DLI4 LMNOPQRSTUV 1 bright;
		Stop;
	Spawn10:
		TNT1 A 0;
		DLI5 LMNOPQRSTUV 1 bright;
	Stop;
}

}

CLASS HellionTrail2 : pb_special_effect_base
{ 
Default
{
	renderstyle "Add";
	Damage 0;
	Scale 0.55;
	+NOGRAVITY;
	+THRUACTORS
	Translation "0:255=%[0,0,0]:[1,1,0]";
}

States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Jump(256, "Spawn2", "Spawn3", "Spawn4", "Spawn5", "Spawn6", "Spawn7", "Spawn8", "Spawn9", "Spawn10");
		DLI1 ABCDEFGHIJK 1 bright;
		Stop;
		Spawn2:
		TNT1 A 0;
		DLI2 ABCDEFGHIJK 1 bright;
		Stop;
		Spawn2:
		TNT1 A 0;
		DLI3 ABCDEFGHIJK 1 bright;
		Stop;
		Spawn3:
		TNT1 A 0;
		DLI3 ABCDEFGHIJK 1 bright;
		Stop;
		Spawn4:
		TNT1 A 0;
		DLI4 ABCDEFGHIJK 1 bright;
		Stop;
		Spawn5:
		TNT1 A 0;
		DLI5 ABCDEFGHIJK 1 bright;
		Stop;
		Spawn6:
		TNT1 A 0;
		DLI2 LMNOPQRSTUV 1 bright;
		Stop;
		Spawn7:
		TNT1 A 0;
		DLI3 LMNOPQRSTUV 1 bright;
		Stop;
		Spawn8:
		TNT1 A 0;
		DLI3 LMNOPQRSTUV 1 bright;
		Stop;
		Spawn9:
		TNT1 A 0;
		DLI4 LMNOPQRSTUV 1 bright;
		Stop;
		Spawn10:
		TNT1 A 0;
		DLI5 LMNOPQRSTUV 1 bright;
	Stop;
}

}


CLASS HellionTrailFlash : pb_special_effect_base
{ 
Default
{	
	RenderStyle "Add";
	Scale 0.185;
	Alpha 1;
	+THRUACTORS;
	+NOINTERACTION;
	+NOGRAVITY;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SetScale(scale.x, scale.y -0.0875);
		YA36 C 2 bright A_SpawnItemEx("HellionTrailSpark", random(4,-4), random(4,-4), random(4,-4), 0, 0, 0, 0, 128, 0);
		YA36 C 2 bright;
	Trolololo:
		YAE4 A 0;
		YAE4 A 0 A_SetScale(scale.x -0.01, scale.y -0.01);
		YA36 C 1 bright A_FadeOut(0.2);
	Loop;
}
}

CLASS HellionTrailSpark : pb_special_effect_base
{ 
Default
{	
	RenderStyle "Add";
	Scale 0.0125;
	Alpha 0.85;
	+NOINTERACTION;
	+NOGRAVITY;
}
States
{
	Spawn:
		YAE4 A 0 A_SetScale(scale.x-0.00075);
		YA36 C 3 bright A_ChangeVelocity(frandom(-0.8, 0.8), frandom(-0.8, 0.8), frandom(-0.8, 0.8), 0);
		YA36 C 1 bright A_FadeOut(0.05);
	Loop;
}
}

CLASS HellionPuff : pb_special_effect_base
{ 
Default
{
	Radius 3;
	Height 3;
	RenderStyle "Add";
	Alpha 0.67;
	+NoGravity;
	+NoBlockMap;
	+DontSplash;
	+ForceXYBillboard;
}
States
{
	Spawn:
		TNT1 A 3 Bright;
		HLBL CDEFGHI 3 Bright;
	Stop;
}
}

CLASS ExecutedHellion: pb_blood_and_gore_base
{ 
Default
{
	Scale 1.32;
}
States
{
	Spawn:
		HEL2 C -1;
	Stop;
}

}
	

CLASS DeadHellion: pb_blood_and_gore_base
{ 
Default
{
	Scale 1.32;
}

States
{
	Spawn:
		HELN T -1;
	Stop;
	
	Death:
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath4", 5, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 5, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 5, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_SpawnItem("ExecutedHellion");
	Stop;
}}
	
CLASS DeadHellion_H3LNG: DeadHellion { 
States
{
	Spawn:
		H3LN G -1;
	Stop;
}}
	
CLASS DeadHellion_H3LNL: DeadHellion
{ 
States
{
	Spawn:
		H3LN L -1;
	Stop;
}}
	
CLASS DeadHellion_H8LNT: DeadHellion
{ 
States
{
	Spawn:
		H8LN T -1;
	Stop;
}}

CLASS DeadHellion_H3LNP: DeadHellion { 
States
{
	Spawn:
		H3LN P -1;
	Stop;
}}