
CLASS DeadVoidSpectre: pb_blood_and_gore_base { 
	Default {
	
	Radius 18;
	Height 12;
	Scale 1.1;
	+SHOOTABLE;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CORPSE;
	+FLOORCLIP;
	-SOLID;
	+THRUACTORS;
	BloodType "Green_Blood", "GreenAxeBlood", "GreenAxeBlood";
	+NOBLOODDECALS;
	damagefactor "Crush", 50.0;
	Mass 1000;
	Health 150;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	}
	States
    {
	Spawn:
	NDEM N -1;
	Stop;
	Raise:
	NDEM N 5;
	NDEM MLKJI 5;
	TNT1 A 0 A_SpawnItem("pb_Void_Spectre", 3);
	Stop;
	Death:
	TNT1 A 0 A_FaceTarget();
	TNT1 A 0 A_NoBlocking();
	TNT1 AA 0  a_spawnprojectile("XDeath3", random(25, 35), random(5, -5), random(160, 200), 2, random(-10, 10));
	TNT1 AA 0  a_spawnprojectile("XDeath2", random(25, 35), random(5, -5), random(160, 200), 2, random(-10, 10));
	//TNT1 A 0  a_spawnprojectile("MuchBloodGreen", 20, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreArm", 22, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreLeg", 22, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAA 0  a_spawnprojectile("Bloodmist", 20, 0, random(0, 360), 2, random(30, 90));
	TNT1 A 0 A_SpawnItem("DeadVoidSpectre_ND3ME");
	Stop;
Death.Plasma: Death.Plasma2:
	TNT1 A 0;
	TNT1 AAA 0  a_spawnprojectile("brutal_LiquidBlood", 50, 0, random(0, 360), 2, random(0, 160));
	EXPL AAA 0 a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
	CARB JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 10 a_spawnprojectile("Explosion_Smoke", 1, 0, random(0, 360), 2, random(0, 160));
	CARB J -1;
	Stop;
}
}

CLASS DeadVoidSpectre_ND3ME : DeadVoidSpectre
{ 
	States
	{
	Spawn:
		ND3M E -1;
		Stop;
	Death:
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_NoBlocking();
		TNT1 AA 0  a_spawnprojectile("XDeath3", random(25, 35), random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AA 0  a_spawnprojectile("XDeath2", random(25, 35), random(5, -5), random(160, 200), 2, random(-10, 10));
		//TNT1 A 0  a_spawnprojectile("MuchBloodGreen", 20, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("VoidSpectreHeadPiece", 22, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreArm", 22, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreLeg", 22, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0  a_spawnprojectile("Bloodmist", 20, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 A_SpawnItem("DeadVoidSpectre_ND4MN");
		Stop;
	}
}

CLASS DeadVoidSpectre_ND4MN : DeadVoidSpectre { 
	Default {
	-SHOOTABLE
	Radius 1;
	Height 1;
	}
	States
	{
	Spawn:
		ND4M N -1;
		Stop;
	}
}

CLASS DeadVoidSpectre_ND7MN : DeadVoidSpectre { 
	States
	{
	Spawn:
		ND7M N -1;
		Stop;
	}
}

CLASS DeadVoidSpectre_ND3MK : DeadVoidSpectre { 
	States
	{
	Spawn:
		ND3M K -1;
		Stop;
	Death:
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_NoBlocking();
		TNT1 AA 0  a_spawnprojectile("XDeath3", random(25, 35), random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AA 0  a_spawnprojectile("XDeath2", random(25, 35), random(5, -5), random(160, 200), 2, random(-10, 10));
		//TNT1 A 0  a_spawnprojectile("MuchBloodGreen", 20, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("VoidSpectreHeadPiece", 22, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreArm", 22, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreEyeball", 22, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0  a_spawnprojectile("Bloodmist", 20, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 A_SpawnItem("DeadVoidSpectre_ND3ML");
		Stop;
	}
}

CLASS DeadVoidSpectre_ND3ML : DeadVoidSpectre_ND3ME { 
	States
	{
	Spawn:
		ND3M L -1;
		Stop;
	}
}

CLASS DeadVoidSpectre_ND3MS : DeadVoidSpectre { 
	States
	{
	Spawn:
		ND3M S -1;
		Stop;
	}
}

CLASS DeadVoidSpectre_ND3MW: DeadVoidSpectre { 
	States
	{
	Spawn:
		ND3M W -1;
		Stop;
	}
}

CLASS DeadVoidSpectre_ND4MM : DeadVoidSpectre { 
	States
	{
	Spawn:
		ND4M M -1;
		Stop;
	}
}

CLASS DeadVoidSpectre_ND4MV : DeadVoidSpectre { 
	States
	{
	Spawn:
		ND4M V -1;
		Stop;
	}
}

CLASS DeadVoidSpectre_ND4MZ : DeadVoidSpectre { 
	States
	{
	Spawn:
		ND4M Z -1;
		Stop;
	}
}

CLASS DeadVoidSpectre_ND5ME : DeadVoidSpectre_ND3ME { 
	States
	{
	Spawn:
		ND5M E -1;
		Stop;
	}
}

CLASS DeadVoidSpectre_ND5MJ : DeadVoidSpectre_ND3ME { 
	States
	{
	Spawn:
		ND5M J -1;
		Stop;
	}
}

CLASS DeadVoidSpectre_NDEMW : DeadVoidSpectre_ND3ME { 
	States
	{
	Spawn:
		NDEM W -1;
		Stop;
	}
}

CLASS DeadVoidSpectre_ND4MR : DeadVoidSpectre_ND3ME { 
	States
	{
	Spawn:
		ND4M R -1;
		Stop;
	}
}

CLASS DeadVoidSpectre_ND4MD : DeadVoidSpectre_ND3ME { 
	States
	{
	Spawn:
		ND4M D -1;
		Stop;
	}
}

CLASS VoidSpectreLostHisArm : pb_void_spectre
{ 
Default
{ 
	Health 50;
	+NOPAIN
	-COUNTKILL
	+SHOOTABLE
}
States
{
	Spawn:
	    ND3M M 1;
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_Jump(32, "Colapse");
		ND3M MMNN 4  a_spawnprojectile("brutal_LiquidBlood", 42, 0, random(0, 360), 2, random(0, 45));
		TNT1 A 0;
		ND3M MMNN 4  a_spawnprojectile("brutal_LiquidBlood", 42, 0, random(0, 360), 2, random(0, 45));
		TNT1 A 0 A_Pain();
		ND3M MMNNMMNN 4  a_spawnprojectile("brutal_LiquidBlood", 42, 0, random(0, 360), 2, random(0, 45));
		TNT1 A 0 A_Pain();
		ND3M MNM 5  a_spawnprojectile("brutal_LiquidBlood", 42, 0, random(0, 360), 2, random(0, 45));
	Goto Colapse;
	
	Death.Shotgun:
	Death.Cutless:
	Death:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 AA 0  a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0  a_spawnprojectile("XDeath1", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0  a_spawnprojectile("XDeath3", random(45, 55), random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AA 0  a_spawnprojectile("XDeath2", random(45, 55), random(5, -5), random(160, 200), 2, random(-10, 10));
		//TNT1 A 0  a_spawnprojectile("MuchBloodGreen", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("VoidSpectreHeadPiece", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreEyeball", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0  a_spawnprojectile("Bloodmist", 50, 0, random(0, 360), 2, random(30, 90));
		ND4M OOOO 2  a_spawnprojectile("brutal_LiquidBlood", 40, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_SpawnItem("CrueltyBonus5Health");
		ND4M PPPPQQQQ 2  a_spawnprojectile("brutal_LiquidBlood", 30, 0, random(0, 360), 2, random(30, 110));
		//TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		ND4M RRRRRRRRRRRRRRRRRRRRRR 2  a_spawnprojectile("brutal_LiquidBlood", 20, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("DeadVoidSpectre_ND4MR");
	Stop;
	
	Colapse:
	    TNT1 A 0 A_Scream();
	TNT1 A 0 A_NoBlocking();
	    ND3M GHIJK 5;
	TNT1 A 0 A_SpawnItem("DeadVoidSpectre_ND3MK");
	//TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	Stop;
}
}

CLASS VoidSpectreBlurFX_NDEMA : ACTOR { 
	Default {
	
	+NOINTERACTION;
	+NOCLIP;
	Scale 1.15;
	
	}
	States
	{
	Spawn:
		NDEM A 5 A_FadeOut(0.20);
		loop;
	}
}

CLASS VoidSpectreBlurFX_NDEMB : ACTOR { 
	Default {
	
	+NOINTERACTION;
	+NOCLIP;
	Scale 1.15;
	
	}
	States
	{
	Spawn:
		NDEM B 5 A_FadeOut(0.20);
		loop;
	}
}

CLASS VoidSpectreBlurFX_NDEMC : ACTOR { 
	Default {
	
	+NOINTERACTION;
	+NOCLIP;
	Scale 1.15;
	
	}
	States
	{
	Spawn:
		NDEM C 5 A_FadeOut(0.20);
		loop;
	}
}

CLASS VoidSpectreBlurFX_NDEMD : ACTOR { 
	Default {
	
	+NOINTERACTION;
	+NOCLIP;
	Scale 1.15;
	
	}
	States
	{
	Spawn:
		NDEM D 5 A_FadeOut(0.20);
		loop;
	}
}
