//===========================================================================
//
// Void Spectre
//
//===========================================================================


CLASS pb_void_spectre: proto_pinky// Replaces Spectre
{ 
Default
{	
	GibHealth 35;
	Health 400;
	Scale 1.1;
	Height 52;
	Radius 22;
	Mass 400;
	Speed 15;
	FastSpeed 17;// yes, his fast speed is slower because it would make him sanic fast if it was default
	//SpawnID 1540;
	damagefactor "Crush", 10.0;
	damagefactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	PainChance "Kick", 255;
	damagefactor "TeleportRemover", 0.0;
	Monster;
	damagefactor "Shrapnel", 0.3;
	damagefactor "SSG", 9.0;
	+FLOORCLIP;
	SeeSound "demon/sight";
	AttackSound "demon/melee";
	PainSound "demon/pain";
	DeathSound "demon/death";
	ActiveSound "demon/active";
	damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0; damagefactor "GreenBlood", 0.0;
	BloodType "Green_Blood", "GreenBloodSplat", "Green_Blood";
	BloodColor "DarkGreen";
	DamageType "Eat";
	MaxStepHeight 48;
	MaxDropOffHeight 48;
	//DropItem "NewBlurSphere", 3;
	//DropItem "Demonpickup", 100;
	Obituary "%o was devoured by a Void Spectre.";
	+NOBLOODDECALS;
}
States
{
	Death.Shrink:
		TNT1 A 1 A_PlaySound("Shrink", 3);
/*		TNT1 A 0 A_SpawnItemEx("VoidSpectreShrinkFX1", 0, 0,  5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("VoidSpectreShrinkFX2", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("VoidSpectreShrinkFX3", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("VoidSpectreShrinkFX4", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("VoidSpectreShrinkFX5", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("VoidSpectreShrinkFX6", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("VoidSpectreShrinkFX7", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx("LilVoidSpectre", 1);*/
	Stop;
		
	Spawn:
 		TNT1 A 0;
	watch:
		NDEM A 10 A_Look();
	loop;
		
	Forget:
		TNT1 A 0 A_ClearTarget();
		TNT1 A 0 A_TakeInventory("EnemyMemory", 15);
	SearchPlayer:
	Idle:
		NDEM A 10 A_Look();
		TNT1 A 0 A_SetAngle(angle - 40);
		NDEM A 10 A_Look();
		TNT1 A 0 A_SetAngle(angle + 40);
		NDEM A 10 A_Look();
		TNT1 A 0 A_Wander();
		NDEM A 2 A_Look();
		TNT1 A 0 A_Wander();
		NDEM A 2 A_Look();
		TNT1 A 0 A_Wander();
		NDEM B 2 A_Look();
		TNT1 A 0 A_Wander();
		NDEM B 2 A_Look();
		TNT1 A 0 A_Wander();
		NDEM C 2 A_Look();
		TNT1 A 0 A_Wander();
		NDEM C 2 A_Look();
		TNT1 A 0 A_Wander();
		NDEM D 2 A_Look();
		TNT1 A 0 A_Wander();
		NDEM D 2 A_Look();
		
		TNT1 A 0 A_Jump(128, "SearchPlayer");
		
		TNT1 A 0 A_Wander();
		NDEM A 2 A_Look();
		TNT1 A 0 A_Wander();
		NDEM A 2 A_Look();
		TNT1 A 0 A_Wander();
		NDEM B 2 A_Look();
		TNT1 A 0 A_Wander();
		NDEM B 2 A_Look();
		TNT1 A 0 A_Wander();
		NDEM C 2 A_Look();
		TNT1 A 0 A_Wander();
		NDEM C 2 A_Look();
		TNT1 A 0 A_Wander();
		NDEM D 2 A_Look();
		TNT1 A 0 A_Wander();
		NDEM D 2 A_Look();
	Goto SearchPlayer;
		
	See:
		TNT1 A 0;
		TNT1 A 0 A_CheckSight("SeeNoSee");
		//TNT1 A 0 A_JumpIfInventory("EatMe", 1, "Eat");
		TNT1 A 0 A_SpawnItemEx("FootStep6", 0, 0, 30, 0, 0);
		TNT1 A 0 A_TakeInventory("EnemyMemory", 17);
		//TNT1 A 0 A_SpawnItemEx("VoidSpectreBlurFX_NDEMA", random(-1,1), random(-1,1), 0);
		NDEM AA 2 A_Chase();
		TNT1 A 0 A_Playsound("pinky/step", 4);
		//TNT1 A 0 A_SpawnItemEx("VoidSpectreBlurFX_NDEMB", random(-1,1), random(-1,1), 0);
		NDEM BB 2 A_Chase();
		//TNT1 A 0 A_SpawnItemEx("VoidSpectreBlurFX_NDEMC", random(-1,1), random(-1,1), 0);
		TNT1 A 0 A_SpawnItemEx("FootStep6", 0, 0, 30, 0, 0);
		NDEM CC 2 A_Chase();
		//TNT1 A 0 A_SpawnItemEx("VoidSpectreBlurFX_NDEMD", random(-1,1), random(-1,1), 0);
		TNT1 A 0 A_Playsound("pinky/step", 5);
		NDEM DD 2 A_Chase();
	Loop;
		
	SeeNoSee:
		TNT1 A 0 A_SpawnItemEx("FootStep6", 0, 0, 30, 0, 0);
		//TNT1 A 0 A_SpawnItemEx("VoidSpectreBlurFX_NDEMA", random(-1,1), random(-1,1), 0);
		NDEM AAAAA 1 A_Chase();
		TNT1 A 0 A_Playsound("pinky/step", 4);
		//TNT1 A 0 A_SpawnItemEx("VoidSpectreBlurFX_NDEMB", random(-1,1), random(-1,1), 0);
		NDEM BBBBB 1 A_Chase();
		//TNT1 A 0 A_SpawnItemEx("VoidSpectreBlurFX_NDEMC", random(-1,1), random(-1,1), 0);
		NDEM CCCCC 1 A_Chase();
		TNT1 A 0 A_Playsound("pinky/step", 5);
		//TNT1 A 0 A_SpawnItemEx("VoidSpectreBlurFX_NDEMD", random(-1,1), random(-1,1), 0);
		NDEM DDDDDD 1 A_Chase();
		TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
		TNT1 A 0 A_JumpIfInventory("EnemyMemory", 15, "Forget");
		Goto See;
		
		
	Melee:
		TNT1 A 0;
		TNT1 A 0 A_TakeInventory("EnemyMemory", 100);
		NDEM E 6 A_FaceTarget();
		NDEM F 6 A_FaceTarget();
		TNT1 AA 0 a_spawnprojectile("DemonAttack",40,0,0,0);
		NDEM G 12 a_spawnprojectile("DemonAttack",5,0,0,0);
	Goto See;
		
	Pain:
		NDEM H 2;
		NDEM H 2 A_Pain();
		Goto See;
		
	Possession:
		TNT1 A 0 A_SetInvulnerable();
		NDEM H 3;
		NDEM H 3 A_Pain();
 		TNT1 A 0 A_UnSetInvulnerable();
	Goto See;
		
	Pain.Stun:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx("StunElectrocute", random(-4, 4), random(-4, 4),  random(16, 32), 0, 0);
		NDEM H 1 A_Pain();
		NDEM HHHHHHHHHH 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		NDEM H 1 A_Pain();
		NDEM HHHHHHHHHH 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		NDEM H 1 A_Pain();
		NDEM HHHHHHHHHH 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		NDEM H 1 A_Pain();
		NDEM HHHHHHHHHH 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		NDEM H 1 A_Pain();
		NDEM HHHHHHHHHH 3 A_SpawnItemEx("StunElectrocute", random(-12, 12), random(-12, 12),  random(16, 52), 0, 0);
		NDEM H 1 A_Pain();
	Goto See;
		
	Pain.Shotgun:
		TNT1 A 0 A_Pain();
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(2);
		NDEM H 2;
		NDEM H 2;
	Goto See;
		
	Pain.Kick:
	Pain.ExtremePunches:
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(18);
		NDEM H 6;
		NDEM H 6;
	Goto See;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 A_Jump(96, "Death.Arm");
		TNT1 A 0 A_Jump(128, "MirrorDeath");
		NDEM I 8;
		NDEM J 8 A_Scream();
		NDEM K 4;
		NDEM L 4 A_NoBlocking();
		NDEM M 4;
		TNT1 A 0 A_SpawnItem("DeadVoidSpectre", 1);
		//TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	Stop;
		
	MirrorDeath:
		ND7M I 8;
		ND7M J 8 A_Scream();
		ND7M K 4;
		ND7M L 4 A_NoBlocking();
		ND7M M 4;
		TNT1 A 0 A_SpawnItem("DeadVoidSpectre_ND7MN", 1);
		//TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	Stop;
		
	Death.Arm:
	DeathRemoveArm:
		TNT1 AAAAAAAAA 0;
		//TNT1 A 0  a_spawnprojectile("MuchBloodGreen", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreArm", 35, 0, random(0, 360), 2, random(0, 160));
		ND3M F 8  a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		ND3M G 8 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItemEx("VoidSpectreLostHisArm",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	Stop;
		
	Death.Kick:
	Death.Melee:
	Death.SuperKick:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(5);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
	Goto Death+3;
		
	Death.Shotgun:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfCloser(200, "Death.Strong");
		Goto Death+3;
		
	Death.Strong:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "Death.Strong2");
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AA 0  a_spawnprojectile("XDeath1", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0  a_spawnprojectile("XDeath3", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0  a_spawnprojectile("XDeath3", random(45, 55), random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AA 0  a_spawnprojectile("XDeath2", random(45, 55), random(5, -5), random(160, 200), 2, random(-10, 10));
		//TNT1 A 0  a_spawnprojectile("MuchBloodGreen", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0  a_spawnprojectile("Bloodmist", 50, 0, random(0, 360), 2, random(30, 90));
		
		TNT1 AA 0 a_spawnprojectile("VoidSpectreHeadPiece", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreEyeball", 52, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 AAAAA 0  a_spawnprojectile("XDeath1", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		ND4M SSSSSSS 2  a_spawnprojectile("brutal_LiquidBlood", 40, 0, random(0, 360), 2, random(30, 110));
		ND4M TTTTTT 2  a_spawnprojectile("brutal_LiquidBlood", 40, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Scream();
		ND4M UUUUUU 2  a_spawnprojectile("brutal_LiquidBlood", 30, 0, random(0, 360), 2, random(30, 110));
		//TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		ND4M VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 2  a_spawnprojectile("brutal_LiquidBlood", 20, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("DeadVoidSpectre_ND4MV", 1);
	Stop;
		
	Death.Strong2:
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AA 0 a_spawnprojectile("XDeath1", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", random(45, 55), random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", random(45, 55), random(5, -5), random(160, 200), 2, random(-10, 10));
		//TNT1 AA 0 a_spawnprojectile("MuchBloodGreen", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile("Bloodmist", 50, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 a_spawnprojectile("XDeathVoidSpectreEyeball", 52, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 AAAAA 0 a_spawnprojectile("XDeath1", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		ND4M WWWWW 2 a_spawnprojectile("brutal_LiquidBlood", 40, 0, random(0, 360), 2, random(30, 110));
		ND4M XXXX 2 a_spawnprojectile("brutal_LiquidBlood", 40, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Scream();
		ND4M YYYY 2 a_spawnprojectile("brutal_LiquidBlood", 30, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		ND4M ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ 2 a_spawnprojectile("brutal_LiquidBlood", 20, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("DeadVoidSpectre_ND4MZ", 1);
	Stop;
		
	Death.Saw:
	Death.Cut:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile("XDeathHalfVoidSpectre", 75, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("Instestin", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathStomachGreen", 30, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 30, 0, random(0, 360), 2, random(30, 90));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath4", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath3", 60, 0, random(0, 360), 2, random(0, 160));
		
		ND4M AAAAAAAAAAAAAAAA 1 a_spawnprojectile("brutal_LiquidBlood", 40, 0, random(0, 360), 2, random(30, 110));
		ND4M BC 8;
		ND4M DDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 a_spawnprojectile("brutal_LiquidBlood", 18, 0, random(0, 360), 2, random(30, 110));
		//TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadVoidSpectre_ND4MD", 1);
	Stop;
		
	Death.Tear:
		TNT1 A 0 a_spawnprojectile("XDeathStomachGreen", 30, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Instestin", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath4", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 60, 0, random(0, 360), 2, random(0, 160));
		ND3M OOOOOOOOO 1 a_spawnprojectile("brutal_LiquidBlood", 46, 0, random(0, 360), 2, random(30, 60));
		TNT1 AAAAAAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0 A_Scream();
		ND3M PPPPPPPPP 1 a_spawnprojectile("brutal_LiquidBlood", 25, 0, random(0, 360), 2, random(30, 60));
		ND3M Q 4 A_NoBlocking();
		ND3M R 4;
		ND3M SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 2 a_spawnprojectile("brutal_LiquidBlood", 18, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("DeadVoidSpectre_ND3MS", 1);
		//TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	Stop;
		
	Death.ExtremePunches:
	Death.SSG:
		TNT1 A 0 A_Jump(32, "OWNAGE");
		ND3M T 1 A_FaceTarget();
		ND3M T 1 A_Recoil(5);
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("XDeath2", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("brutal_LiquidBlood", 32, 0, random(170, 190), 2, random(0, 40));
		//TNT1 AAAAAAA 0 a_spawnprojectile("SuperWallredBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAA 0 a_spawnprojectile("Bloodmist", 50, 0, random(0, 360), 2, random(30, 90));
		
		TNT1 AA 0 a_spawnprojectile("XDeathVoidSpectreArm", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathVoidSpectreEyeball", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("VoidSpectreHeadPiece", 52, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		ND3M TTTTTTTTTTTT 1 a_spawnprojectile("brutal_LiquidBlood", 38, 0, random(0, 360), 2, random(30, 110));
		ND3M UUUVVV 3 a_spawnprojectile("brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		ND3M WWWWWWWWWWWWWWWWWWWWWWWW 2 a_spawnprojectile("brutal_LiquidBlood", 15, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("DeadVoidSpectre_ND3MW");
	Stop;
		
	OWNAGE:
		NDEM P 1 A_FaceTarget();
		NDEM P 1 A_Recoil(2);
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 38, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("brutal_LiquidBlood", 32, 0, random(170, 190), 2, random(0, 40));
		//TNT1 AAAAAAA 0 a_spawnprojectile("SuperWallredBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAA 0 a_spawnprojectile("Bloodmist", 50, 0, random(0, 360), 2, random(30, 90));
		
		TNT1 A 0 a_spawnprojectile("XDeathVoidSpectreEyeball", 52, 0, random(0, 360), 2, random(0, 160));
		
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		NDEM PQRSTUV 5;
		//TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		NDEM WWWWWWWWWWWWWWWWWWWWWWWWWWW 2 a_spawnprojectile("brutal_LiquidBlood", 15, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("DeadVoidSpectre_NDEMW");
	Stop;
		
		
	Death.Blast:
		TNT1 A 0 A_Jump(99, "Death.Strong");
		ND3M A 1 A_FaceTarget();
		ND3M A 1 A_Recoil(2);
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAA 0  a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0  a_spawnprojectile("XDeath2", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0  a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0  a_spawnprojectile("brutal_LiquidBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAA 0  a_spawnprojectile("SuperWallredBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0  a_spawnprojectile("Bloodmist", 50, 0, random(0, 360), 2, random(30, 90));
		TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreArm", 42, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreLeg", 22, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreEyeball", 52, 0, random(0, 360), 2, random(0, 160));
		ND3M BCD 8;
		//TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		ND3M EEEEEEEEEEEEEEEEEEEEE 2  a_spawnprojectile("brutal_LiquidBlood", 15, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("DeadVoidSpectre_ND3ME");
	Stop;
		
		
	Death.Desintegrate:
		TNT1 A 0 A_XScream();
		ND4M EEEEE 1  a_spawnprojectile("brutal_LiquidBlood", 45, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_NoBlocking();
		
		TNT1 AAAAA 0  a_spawnprojectile("XDeath1", 38, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAA 0  a_spawnprojectile("brutal_LiquidBlood", 42, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAA 0  a_spawnprojectile("Bloodmist", 35, 0, random(0, 360), 2, random(30, 90));
		TNT1 AAAA 0  a_spawnprojectile("Instestin", 30, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreEyeball", 42, 0, random(0, 360), 2, random(0, 160));
		ND4M FGHIJKLM 6;
		
		TNT1 a 0 
		{
			for(int i = 0; i < 14; i++)
			{
				A_SpawnItemEx("PlasmaParticle", 0, 0, 14,(0.1)*Random(10, 40), 0,(0.1)*Random(-40, 40), Random(0, 360), 128);
				a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
			}
		}
		//TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		ND4M MMMMMMMMMMMMMMMMMMMMMMM 8 a_spawnprojectile("ExplosionSmoke", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItem("DeadVoidSpectre_ND4MM");
	Stop;
		
	Death.CutLEss:
		TNT1 A 0;
		TNT1 A 0 A_Jump(32, "Death.Cut");
		TNT1 A 0 A_Jump(132, "DeathRemoveArm");
		Goto Death;
		
		
	Crush:
	Death.Stomp:
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail8", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AAAAAA 0 bright  a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright  a_spawnprojectile("XDeath2", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright  a_spawnprojectile("XDeath3", 55, 0, random(0, 360), 2, random(30, 180));
		//TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("CrushedRemains");
		TNT1 A 1;
		TNT1 A 1 A_XScream();
		TNT1 A 1 A_NoBlocking();
	Stop;
		
	Death.GreenFire:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAA 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
		
		
		TNT1 A 0  a_spawnprojectile("XDeathBurnedDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  a_spawnprojectile("XDeathBurnedDemonLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0  a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		
		EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0  a_spawnprojectile("GreenFlameTrails", 50, 0, random(0, 360), 2, random(0, 360));
		XBRN AAAA 2 BRIGHT  A_SpawnItem("Green_Flare",0,43);
	Stop;
		
	Death.SuperPlasma:
	Death.Plasma: Death.Plasma2:
	TNT1 A 0;
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	
	TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("Ashes1", 32, 0, random(0, 360), 2, random(0, 180));
	TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("Ashes2", 32, 0, random(0, 360), 2, random(0, 180));
	TNT1 AAAAA 0  a_spawnprojectile("brutal_LiquidBlood", 50, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAAAAA 0  a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(20, 90));
	TNT1 A 0  a_spawnprojectile("XDeathBurnedDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0  a_spawnprojectile("XDeathBurnedDemonLeg", 32, 0, random(0, 360), 2, random(0, 160));
	SPRG GHIJK 6;
	CARB RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR 10 a_spawnprojectile("Explosion_Smoke", 25, 0, random(0, 360), 2, random(70, 110));
	CARB R -1;
	Stop;
	
	Death.Incinerate:
		TNT1 A 0 A_Playsound("MELT");
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("ExplosionParticle", 32, 0, random(0, 360), 2, random(0, 360));
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,32,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-35, 35), random(-35, 35));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-45, 45), random(-45, 35));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("Ashes1", 28, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("Ashes2", 40, 0, random(0, 360), 2, random(0, 180));
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),32,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		S6RN AAAABBBBCCCCCzDDDDDEEEEEFFFFFGGGG 1 BRIGHT Light("IncinerationGlow")
		{
			pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");
			A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),28,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			if(frame > 22)A_Playsound("SZZLL", 3);
		}
		S6RN HHIIHHIIHHIIHHII 2 BRIGHT Light("IncinerationGlow") a_spawnprojectile("ExplosionSmoke", 14, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		S6RN HHIIHHIIHHIIHHII 2 Light("IncinerationGlow") a_spawnprojectile("ExplosionSmoke", 14, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		S6RN HHIIHHIIHHIIHHII 2;
		S6RN JJJJJJJ 12 a_spawnprojectile("ExplosionSmoke", 14, 0, random(0, 360), 2, random(0, 160));
		S6RN J -1;
	Stop;
	
	
	Death.fire:
	Death.Flames:
	Death.Burn:
	TNT1 A 0;
	//TNT1 A 0 A_JumpIfIntargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
	TNT1 A 0 A_Scream();
	TNT1 A 0 A_NoBlocking();
	//TNT1 A 0 A_SpawnItem("BurningDemon", 0, 10)
	TNT1 A 0 A_SpawnItemEx("BurningDemon",0,0,8,0,0,0,0,288);
	Stop;
	
	Death.Fatality:
	TNT1 A 0 A_Pain();
	TNT1 A 0 A_NoBlocking();
	//TNT1 A 0 A_JumpIfIntargetInventory("FistsSelected", 1, 1);
	Goto Death.ExplosiveImpact;
	//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
	//TNT1 A 0 A_GiveToTarget("VoidSpectreFatality", 1);
	Stop;
	
	
	Death.BHFT:
	Death.BHFT:
	Death.RVFT:
	Goto Death.SSG;
	
	XDeath:
	DEath.Explosive:
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_FaceTarget();
	TNT1 AAA 0  a_spawnprojectile("XDeath1", 42, 0, random(0, 190), 2, random(10, 60));
	TNT1 AAAA 0  a_spawnprojectile("XDeath3", 42, 0, random(0, 190), 2, random(10, 60));
	TNT1 AAA 0  a_spawnprojectile("XDeath2", 42, 0, random(0, 190), 2, random(10, 60));
	TNT1 A 0  a_spawnprojectile("XDeath4", 42, 0, random(0, 190), 2, random(10, 60));
	TNT1 A 0 a_spawnprojectile("VoidSpectreXDeath", 0, 0, random(0, 360), 2, random(0, 160));
	Stop;
	
	Death.ExplosiveImpact:
	TNT1 A 0 {self.bNODROPOFF = false;}
	TNT1 A 0;
	TNT1 A 0 ThrustThingZ(0,25,0,1);
	TNT1 A 0 A_FaceTarget();
	TNT1 A 1;
	TNT1 A 0 A_JumpIf(angle < 180, "IsFacingNorth");
	TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayRight");
	TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayLeft");
	Goto XDeath;
	IsFacingNorth:
	TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayRight");
	TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayLeft");
	Goto XDeath;
	
	BlownAwayLeft:
	TNT1 A 0;
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 {self.bNOBLOCKMONST = true;}
	
	TNT1 A 0  a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0  a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0  a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAA 0  a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreEyeball", 52, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreHead", 42, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreLeg", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreArm", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAAAA 0  a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(20, 90));
	
	TNT1 A 0 ThrustThingZ(0,30,0,1);
	TNT1 A 0 A_Xscream();
	ND5M ABCD 5  a_spawnprojectile("brutal_LiquidBlood", 0, 0, 0, 2, 90);
	ND5M DDDDDDDDDD 3 A_CheckFloor("LandBlownAwayLeft");
	LandBlownAwayLeft:
	TNT1 A 0 A_Stop();
	TNT1 A 0  A_SpawnItem("GrowingBloodPool");
	TNT1 A 0 A_SpawnItem("DeadVoidSpectre_ND5ME");
	Stop;
	
	BlownAwayRight:
	TNT1 A 0;
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 {self.bNOBLOCKMONST = true;}
	
	TNT1 A 0  a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0  a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AA 0  a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAA 0  a_spawnprojectile("Instestin", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreEyeball", 52, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreHead", 42, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreLeg", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 A 0  a_spawnprojectile("XDeathVoidSpectreArm", 32, 0, random(0, 360), 2, random(0, 160));
	TNT1 AAAAAA 0  a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(20, 90));
	TNT1 A 0 ThrustThingZ(0,30,0,1);
	TNT1 A 0 A_Xscream();
	ND5M FGHI 5  a_spawnprojectile("brutal_LiquidBlood", 0, 0, 0, 2, 90);
	ND5M IIIIIIIIII 3 A_CheckFloor("LandBlownAwayRight");
	LandBlownAwayRight:
	TNT1 A 0 A_Stop();
	TNT1 A 0  A_SpawnItem("GrowingBloodPool");
	TNT1 A 0 A_SpawnItem("DeadVoidSpectre_ND5MJ");
	Stop;
	
	Raise:
	NDEM N 5;
	NDEM MLKJI 5;
	Goto See;
	
	Pain.KillMe:
	Pain.Taunt:
	TNT1 A 0;
	Goto See;
	Death.KillMe:
	Death.Taunt:
	TNT1 A 0 {self.bSOLID = false;}
	//TNT1 A 0 A_SpawnItem("VoidSpectre");
	Stop;
	
	
	Death.Eat:
	//TNT1 A 0 A_GiveToTarget("EatMe",1);
	Goto Death+3;
	
	Death.Ice:
	Death.Freeze:
	Death.Frost:
	TNT1 A 0 {self.bSHOOTABLE = false;}
	TNT1 A 0 {self.bSOLID = false;}
	//TNT1 A 0 A_SpawnItem("FrozenVoidSpectre");
	Stop;
	
	Death.Massacre:
	Goto Death;
	
}
}
