//===========================================================================
//
// Demon
//
//===========================================================================
CLASS pb_Bull_Demon: proto_pinky// Replaces Demon
{ 
Default
{	
	GibHealth 35;
	//Radius 30
	Health 200;
	Scale 1.1;
	Height 56;
	Radius 22;
	Mass 400;
	Speed 9;
	FastSpeed 11;//yes, his fast speed is slower because it would make him sanic fast if it was default.
	//SpawnID 1500;
	PainChance "Saw", 200;
	PainChance "Cut", 200;
	PainChance "Kick", 255;
	PainChance "ExtremePunches", 255;
	PainChance "Stun", 255;
	damagefactor "Crush", 10.0;
	damagefactor "SSG", 5.0;
	damagefactor "Kick", 0.7;
	damagefactor "Fatality", 0.7;
	damagefactor "SuperPunch", 0.7;
	//damagefactor "Melee", 0.7
	damagefactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	damagefactor "GibRemoving", 0.0;
	damagefactor "SSG", 5.0;
	damagefactor "TeleportRemover", 0.0;
	DamageFactor "CauseObjectsToSplash", 0.0;
	+CANPASS;
	Monster;
	damagefactor "Blood", 0.0; damagefactor "BlueBlood", 0.0; damagefactor "GreenBlood", 0.0;
	damagefactor "Shrapnel", 0.3;
	+FLOORCLIP;
	
	SeeSound "demon/sight";
	AttackSound "demon/melee";
	PainSound "demon/pain";
	DeathSound "demon/death";
	ActiveSound "demon/active";
	BloodType "pb_blood", "BloodSPlatterReplacer", "AxeBlood";
	DamageType "Eat";
	MaxStepHeight 32;
	MaxDropOffHeight 32;
	//DropItem "DemonStrengthRune", 2;
	
	////DropItem "Demonpickup", 100;
}
States
{	
	Spawn:
	watch:
		SARG ZA 10 A_Look();
	loop;

	See:
		//TNT1 A 0 A_JumpIfInventory("ZombieManFatality", 1, "FatalityZombieman");
		//TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
		//TNT1 A 0 A_JumpIfInventory("ImpFatality", 1, "FatalityImp");
		//TNT1 A 0 A_JumpIfInventory("ComandoFatality", 1, "FatalityComando");
		
		TNT1 A 0 A_SpawnItemEx("FootStep6", 0, 0, 30, 0, 0);
		TNT1 A 0 A_TakeInventory("EnemyMemory", 17);
		SARG AA 2 A_Chase();
		TNT1 A 0 A_Playsound("pinky/step", 4);
		SARG BB 2 A_Chase();
		TNT1 A 0 A_SpawnItemEx("FootStep6", 0, 0, 30, 0, 0);
		SARG CC 2 A_Chase();
		TNT1 A 0 A_Playsound("pinky/step", 5);
		SARG DD 2 A_Chase();
	Loop;







	SearchPlayer:
	Idle:
		SARG ZA 10 A_Look();
		TNT1 A 0 A_SetAngle(angle + randompick(-40, 40) );
		SARG ZA 10 A_Look();
		SARG ZA 10 A_Look();
		SARG AABBBBCCCCDDDD 2
		{
			A_Wander();
			A_Look();
		}
	loop;		
		
	Melee:
		TNT1 A 0;
		TNT1 A 0 A_TakeInventory("EnemyMemory", 100);
		////TNT1 A 0 A_JumpIfIntargetInventory("ComeEatMeDemon", 1, "MeleeDown");
		SARG E 6 A_FaceTarget();
		SARG F 6 A_FaceTarget();
		TNT1 A 0 a_spawnprojectile("DemonAttack",40,0,0,0);
		SARG G 12 a_spawnprojectile("DemonAttack",5,0,0,0);
		
		//TNT1 A 0 A_JumpIfInventory("ZombieManFatality", 1, "FatalityZombieman");
		//TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
		//TNT1 A 0 A_JumpIfInventory("ImpFatality", 1, "FatalityImp");
		//TNT1 A 0 A_JumpIfInventory("ComandoFatality", 1, "FatalityComando");
	Goto See;
		
	MeleeDown:
		PDEV A 6 A_FaceTarget();
		PDEV B 6 A_FaceTarget();
		PDEV C 12 a_spawnprojectile("DemonAttack",5,0,0,0);
		//TNT1 A 0 A_JumpIfInventory("ZombieManFatality", 1, "FatalityZombieman");
		//TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
		//TNT1 A 0 A_JumpIfInventory("ImpFatality", 1, "FatalityImp");
		//TNT1 A 0 A_JumpIfInventory("ComandoFatality", 1, "FatalityComando");
		TNT1 A 0 A_Jump(32, "EatFast");
	Goto See;

	Pain:
		SARG H 2;
		SARG H 2 A_Pain();
	Goto See;

	Possession:
		TNT1 A 0 A_SetInvulnerable();
		SARG H 3;
		SARG H 3 A_Pain();
 		TNT1 A 0 A_UnSetInvulnerable();
	Goto See;
		

	Pain.Shotgun:
		TNT1 A 0 A_Pain();
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(2);
		SARG H 4;
	Goto See;
		
	Pain.Kick:
	Pain.ExtremePunches:
		TNT1 A 0 A_Pain();
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(23);
		SARG H 6;
		SARG H 6;
	Goto See;

	Death:
		TNT1 A 0;
		TNT1 A 0 A_Jump(96, "LeftDeath");
		TNT1 A 0 A_Jump(96, 13);
		TNT1 AAA 0;
		SARG I 8;
		SARG J 8 A_Scream();
		SARG K 4;
		SARG L 4 A_NoBlocking();
		SARG M 4;
		TNT1 A 0 A_SpawnItem("DeadDemon1", 1);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	Stop;
		TNT1 AAAAAAAAA 0;
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 a_spawnprojectile("XDeathDemonArm", 35, 0, random(0, 360), 2, random(0, 160));
		SAAR A 8 a_spawnprojectile("XDeath1", 40, 0, random(0, 360), 2, random(0, 160));
		SAAR B 8 A_Scream();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItemEx("PoorPinkyLostHisArm",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	Stop;
		
	LeftDeath:
		S2RG I 8;
		S2RG J 8 A_Scream();
		S2RG K 4;
		S2RG L 4 A_NoBlocking();
		S2RG M 4;
		TNT1 A 0 A_SpawnItem("DeadDemon1Left", 1);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	Stop;
		
	CleanDeath:
		TNT1 A 0;
		TNT1 A 0 A_Jump(96, "LeftDeath");
		SARG I 8;
		SARG J 8 A_Scream();
		SARG K 4;
		SARG L 4 A_NoBlocking();
		SARG M 4;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadDemon1", 1);
	Stop;

	Death.Kick:
	Death.Melee:
	Death.SuperKick:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil(5);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
	Goto CleanDeath;
		
	Death.Shotgun:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfCloser(200, "Death.Strong");
	Goto Death+4;
		
	Death.Strong:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128, "Death.Strong2");
		TNT1 A 0 A_Jump(86, "DeathRemoveArm");
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AA 0 a_spawnprojectile("XDeathBrain1", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBrain2", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", random(45, 55), random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AA 0 a_spawnprojectile("XDeath2", random(45, 55), random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 A 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 50, 0, random(0, 360), 2, random(30, 90));
		TNT1 AA 0 a_spawnprojectile("PinkyHeadPiece", 52, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("PinkyJaw", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		SARH AAAAAAABBBBBB 2 a_spawnprojectile("Brutal_LiquidBlood", 40, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Scream();
		SARH CCCCCC 2 a_spawnprojectile("Brutal_LiquidBlood", 30, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		SARH DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 a_spawnprojectile("Brutal_LiquidBlood", 20, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("DeadDemonNoHead", 1);
	Stop;
		
	Death.Strong2:
		TNT1 AAA 0 a_spawnprojectile("XDeathBrain1", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeathBrain2", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 AAAAA 0 a_spawnprojectile("SmallBrainPieceFast", random(45, 55), random(5, -5), random(170, 190), 2, random(-10, 10));
		TNT1 AAAA 0 a_spawnprojectile("Bloodmist", 50, 0, random(0, 360), 2, random(30, 90));
		TNT1 AA 0 a_spawnprojectile("PinkyHeadPiece", 52, 0, random(0, 360), 2, random(0, 160));
		S4RH A 11;
		S4RH B 12 A_Scream();
		S4RH C 12 A_NoBlocking();
		S4RH D 12;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadDemonNoHead2", 1);
	Stop;
		
	Death.Strong3:
		XDP5 AAABBB 1 a_spawnprojectile("Brutal_LiquidBlood2", 49, 0, random(0, 360), 2, random(30, 60));
		TNT1 AA 0 a_spawnprojectile("XDeath4", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBrain1", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeathBrain2", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", random(45, 55), random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 AA 0 a_spawnprojectile("XDeath2", random(45, 55), random(5, -5), random(160, 200), 2, random(-10, 10));
		TNT1 A 0 a_spawnprojectile("PinkyJaw", 52, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("PinkyHeadPiece", 52, 0, random(0, 360), 2, random(0, 160));
		XDP5 CCCCCCDDDDDDEEEEEEFFFFFFGGGGGG 1 a_spawnprojectile("Brutal_LiquidBlood2", 39 - (frame * 3), 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		XDP5 HHHHHHHHHHH 1 a_spawnprojectile("Brutal_LiquidBlood2", 9, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_SpawnItem("DeadDemonXDP5H", 1);
	Stop;
		
	Death.Saw:
	Death.Cut:
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Jump(108, "DeathCut2");
		TNT1 A 0 a_spawnprojectile("XDeathHalfDemon", 75, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathStomach", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath1", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDEATH5", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("xdeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAA 0 a_spawnprojectile("xdeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 60, 0, random(0, 360), 2, random(0, 160));
		SARC ABCD 9;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadDemonHalf23", 1);
	Stop;
		
	DeathCut2:
		XDP5 AAABBB 1 a_spawnprojectile("Brutal_LiquidBlood2", 49, 0, random(0, 360), 2, random(30, 60));
		TNT1 AA 0 a_spawnprojectile("XDeath4", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("xdeath2", 32, 0, random(0, 360), 2, random(0, 160));
		XDP5 C 6 a_spawnprojectile("XDeathDemonHead", 42, 0, random(0, 360), 2, random(0, 160));
		XDP5 DDDDDD 1 a_spawnprojectile("Brutal_LiquidBlood2", 35, 0, random(0, 360), 2, random(30, 60));
		XDP5 EEEEEE 1 a_spawnprojectile("Brutal_LiquidBlood2", 27, 0, random(0, 360), 2, random(30, 60));
		XDP5 FFFFFF 1 a_spawnprojectile("Brutal_LiquidBlood2", 22, 0, random(0, 360), 2, random(30, 60));
		XDP5 GGGGGG 1 a_spawnprojectile("Brutal_LiquidBlood2", 15, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		XDP5 HHHHHHHHHHH 1 a_spawnprojectile("Brutal_LiquidBlood2", 9, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_SpawnItem("DeadDemonXDP5H", 1);
	Stop;
		
	Death.Tear:
		TNT1 A 0 A_Jump(106, "DeathTear2");
		TNT1 A 0 a_spawnprojectile("XDeathStomach", 30, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath4", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 60, 0, random(0, 360), 2, random(0, 160));
		SARG OOOOOOOOO 1 a_spawnprojectile("Brutal_LiquidBlood2", 46, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_Scream();
		SARG PPPPPPPPP 1 a_spawnprojectile("Brutal_LiquidBlood2", 25, 0, random(0, 360), 2, random(30, 60));
		SARG Q 4 A_NoBlocking();
		SARG RST 4;
		TNT1 A 0 A_SpawnItem("DeadDemonHalf", 1);
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
	Stop;
		
	DeathTear2:
		TNT1 A 0 a_spawnprojectile("XDeathStomach", 30, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath4", 60, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("xdeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		PXD1 AAAAAAAA 1 a_spawnprojectile("Brutal_LiquidBlood2", 46, 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		PXD1 BBBBBBBB 1 a_spawnprojectile("Brutal_LiquidBlood2", 25, 0, random(0, 360), 2, random(30, 60));
		PXD1 CCCCCDDDDDEEEEEFFFFF 1 a_spawnprojectile("Brutal_LiquidBlood2", 19, 0, random(0, 360), 2, random(30, 60));
		PXD1 G -1;
		TNT1 A 0 A_SpawnItem("DeadDemonPXD1G");
	Stop;
		
	Death.SuperPunch:
	Death.ExtremePunches:
	Death.Blast:
	Death.SSG:
		TNT1 A 0 A_Jump(89, "OWNAGE");
		SARC A 1 A_Pain();
		SARC A 1 A_FaceTarget();
		TNT1 A 0 A_SpawnItem("BloodSplasher2");
		TNT1 AAA 0 bright a_spawnprojectile("SuperGoreSpawner", 35, 0, random(170, 190), 2, random(0, 40));
		//TNT1 A 0 a_spawnprojectile("MeatDeath", 0, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("XDeath2", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("XDeath3", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("XDeathDemonArm", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		SARC AAABBBCCCDDD 3 a_spawnprojectile("Brutal_LiquidBlood", 35, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		SARC DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 a_spawnprojectile("Brutal_LiquidBlood", 15, 0, random(0, 360), 2, random(30, 110));
		TNT1 A 0 A_SpawnItem("DeadDemonHalf23");
	Stop;
		
	OWNAGE:
		4N1K A 1 A_Pain();
		4N1K A 1 A_FaceTarget();
		TNT1 AAAAAA 0 a_spawnprojectile("XDeath1", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("XDeath5", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAA 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAAAAAA 0 a_spawnprojectile("xdeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAAA 0 a_spawnprojectile("XDeath4", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAA 0 a_spawnprojectile("Brutal_FlyingBloodFaster", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAAA 0 a_spawnprojectile("SuperWallRedBlood", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 AAAAAAAAAA 0 a_spawnprojectile("Blood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 a_spawnprojectile("XDeathDemonArm", 32, 0, random(170, 190), 2, random(0, 40));
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		4N1K ABCDE 6;
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadDemon4N1KF");
	Stop;
		
	Death.Desintegrate:
		TNT1 A 0 A_XScream();
		TNT1 AAAAAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(20, 90));
		XDP2 AAABBB 1 a_spawnprojectile("Brutal_LiquidBlood2", 45 - frame * 3 , 0, random(0, 360), 2, random(30, 60));
		TNT1 A 0 A_NoBlocking();
		XDP2 CCC 1 a_spawnprojectile("Brutal_LiquidBlood2", 25, 0, random(0, 360), 2, random(30, 60));
		XDP2 DE 3 a_spawnprojectile("SuperWallRedBlood", 46, 0, random(170, 190), 2, random(0, 40));
		TNT1 a 0 
		{
			for(int i = 0; i < 14; i++)
			{
				A_SpawnItemEx("PlasmaParticle", 0, 0, 14,(0.1)*Random(10, 40), 0,(0.1)*Random(-40, 40), Random(0, 360), 128);
				a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
			}
		}

		XDP2 FGHI 3;
		TNT1 a 0 
		{
			for(int i = 0; i < 14; i++)
			{
				A_SpawnItemEx("PlasmaParticle", 0, 0, 14,(0.1)*Random(10, 40), 0,(0.1)*Random(-40, 40), Random(0, 360), 128);
				a_spawnprojectile("ExplosionSmoke", 32, 0, random(0, 360), 2, random(0, 360));
			}
		}
		XDP2 JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 7 a_spawnprojectile("ExplosionSmoke", 60, 0, random(0, 360), 2, random(0, 160));
		XDP2 J -1;
	Stop;
		
	Death.CutLEss:
		TNT1 A 0;
		TNT1 A 0 A_Jump(32, "Death.Cut");
		TNT1 A 0 A_Jump(132, "DeathRemoveArm");
	Goto Death;
		
		
	Crush:
	Death.Stomp:
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("pb_FlyingBloodTrail8", 0, 0, random(0, 360), 2, random(0, 360));
		TNT1 AAAAAA 0 bright a_spawnprojectile("SuperGoreSpawner", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AAAAAA 0 bright a_spawnprojectile("XDeath1", 5, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright a_spawnprojectile("XDeath2", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 AA 0 bright a_spawnprojectile("XDeath3", 55, 0, random(0, 360), 2, random(30, 180));
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("CrushedRemains");
		TNT1 A 1;
		TNT1 A 1 A_XScream();
		TNT1 A 1 A_NoBlocking();
	Stop;
		
	DeathRemoveArm:
	Goto Death+14;
		
	Death.GreenFire:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAA 0 a_spawnprojectile("pb_blood", 30, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonLeg", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		tnt1 AAAAAAAAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("GreenFlameTrails", 50, 0, random(0, 360), 2, random(0, 360));
		XBRN AAAA 2 BRIGHT A_SpawnItem("Green_Flare",0,43);
	Stop;
	Death.SuperPlasma:
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("Ashes1", 32, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAAAAAAAAAA 0 a_spawnprojectile("Ashes2", 32, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAA 0 a_spawnprojectile("Brutal_FlyingBlood", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBurnedDemonLeg", 32, 0, random(0, 360), 2, random(0, 160));
		//   TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 a_spawnprojectile("XDeathBurnedMeat", 32, 0, random(0, 360), 2, random(0, 160));
		SPRG ABCDEF 6;
		CARB JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 10 a_spawnprojectile("Explosion_Smoke", 25, 0, random(0, 360), 2, random(70, 110));
		CARB J -1;
	Stop;
	
	Death.Incinerate:
		TNT1 A 0 A_Playsound("MELT");
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAAAAAAAAA 0 
		{
			pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");
		}
		TNT1 A 0 A_SpawnItemEx("ExplosionFlareSpawner",0,0,32,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-15, 15), random(-15, 15));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-35, 35), random(-35, 35));
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random(-45, 45), random(-45, 35));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("Ashes1", 28, 0, random(0, 360), 2, random(0, 180));
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile("Ashes2", 40, 0, random(0, 360), 2, random(0, 180));
		S6RN AAAABBBBCCCCCzDDDDDEEEEEFFFFFGGGG 1 BRIGHT Light("IncinerationGlow")
		{
			pb_effect_event(effects).show_some_effect(self, "ExplosionParticle");
			A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),28,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
			if(frame > 22)A_Playsound("SZZLL", 3);
		}
		TNT1 A 0 A_SpawnItem("Barrel_explosion_Column");

		S6RN HHIIHHIIHHIIHHIIHHIIHHIIHHIIHHII 2 BRIGHT Light("IncinerationGlow")
		{
			a_spawnprojectile("ExplosionSmoke", 14, 0, random(0, 360), 2, random(0, 160));
			A_SpawnItemEx("RealisticFireSparks1",random(-2,2),random(-2,2),8,0,0,0,0,SXF_NOCHECKPOSITION  ,0);
		}
		S6RN HHIIHHIIHHIIHHII 2;
		S6RN JJJJJJJ 12 a_spawnprojectile("ExplosionSmoke", 14, 0, random(0, 360), 2, random(0, 160));
		S6RN J -1;
	Stop;
	
	
	Death.fire:
	Death.Flames:
	Death.Burn:
		TNT1 A 0;
		//TNT1 A 0 A_JumpIfIntargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_SpawnItem("BurningDemon", 0, 10);
		TNT1 A 0 A_SpawnItemEx("BurningDemon",0,0,8,0,0,0,0,288);
	Stop;
	
	Death.Fatality:
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_JumpIfIntargetInventory("FistsSelected", 1, 1);
		Goto Death.ExplosiveImpact;
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_Jump(256, "DemonFatality1", "DemonFatality2", "DemonFatality3");
	DemonFatality1:
		//TNT1 A 0 A_GiveToTarget("DemonFatality", 1);
		Stop;
	DemonFatality2:
		//TNT1 A 0 A_GiveToTarget("DemonFatality2", 1);
		TNT1 A 0;
	Stop;
	DemonFatality3:
		//TNT1 A 0 A_GiveToTarget("DemonFatality3", 1);
		TNT1 A 0;
	Stop;
	
	
	Death.BHFT:
	Death.BHFT:
		TNT1 A 1 A_Pain();
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		//TNT1 A 0 A_GiveToTarget("DemonFatality", 1);
		TNT1 A 0;
	Stop;
	
	XDeath:
	DEath.Explosive:
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_FaceTarget();
		TNT1 AAA 0 a_spawnprojectile("XDeath1", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 AAAA 0 a_spawnprojectile("XDeath3", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 AAA 0 a_spawnprojectile("XDeath2", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 A 0 a_spawnprojectile("XDeath4", 42, 0, random(0, 190), 2, random(10, 60));
		TNT1 A 0 a_spawnprojectile("BullXDeath", 0, 0, random(0, 360), 2, random(0, 160));
	Stop;
	
	Death.ExplosiveImpact:
	Death.RVFT:
		TNT1 A 0 {self.bNODROPOFF = false;}
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,25,0,1);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 1;
		TNT1 A 0 A_JumpIf(angle < 180, "IsFacingNorth");
		TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayRight");
		TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayLeft");
	Goto XDeath;
	IsFacingNorth:
		TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayRight");
		TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayLeft");
	Goto XDeath;
	
	BlownAwayLeft:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathStomach", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBullLeg12", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathPinkyDemonHead", 42, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(20, 90));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Xscream();
		SRRD ABCD 5 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, 0, 2, 90);
		SRRD DDDDDDDDDD 3 A_CheckFloor("LandBlownAwayLeft");
	LandBlownAwayLeft:
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadDemonSRRDE");
	Stop;
	
	BlownAwayRight:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 a_spawnprojectile("XDeath1", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 {self.bNOBLOCKMONST = true;}
		TNT1 A 0 a_spawnprojectile("Brains2", 50, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathStomach", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathBullLeg12", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathDemonArm", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath2", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 AA 0 a_spawnprojectile("XDeath3", 32, 0, random(0, 360), 2, random(0, 160));
		TNT1 A 0 a_spawnprojectile("XDeathPinkyDemonHead", 42, 0, random(0, 360), 2, random(0, 160));
		TNT1 AAA 0 a_spawnprojectile("Bloodmist", 40, 0, random(0, 360), 2, random(20, 90));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Xscream();
		SRRD FGHI 5 a_spawnprojectile("Brutal_FlyingBlood", 0, 0, 0, 2, 90);
		SRRD GGGGGGGGGG 3 A_CheckFloor("LandBlownAwayRight");
	LandBlownAwayRight:
		TNT1 A 0 A_Stop();
		TNT1 A 0 A_SpawnItem("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadDemonSRRDJ");
	Stop;
	
	Raise:
		SARG N 5;
		SARG MLKJI 5;
	Goto See;
	
	Pain.KillMe:
	Pain.Taunt:
		TNT1 A 0;
	Goto See;

	Death.KillMe:
	Death.Taunt:
		TNT1 A 0 {self.bSOLID = false;}
		TNT1 A 0 A_SpawnItem("Demon");
	Stop;
	
	
	FatalityZombieman:
		SARK DEDEDEDEDE 10  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 a_spawnprojectile("XDeathHalfZombieManDown", 20, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 A_TakeInventory("ZombiemanFatality",1);
		//TNT1 A 0 A_JumpIfInventory("NoFoodHealth", 1, 3);
 	Goto See;
	
	
	FatalitySergeant:
		TNT1 A 0;//A_SetInvulnerable
		SARK FGFGFGFGFG 10  {pb_blood_and_gore_event.much_blood(self);}
		TNT1 A 0 a_spawnprojectile("XDeathHalfZombieManDown", 20, 0, random(0, 360), 2, random(0, 160));
		//TNT1 A 0 A_TakeInventory("SergeantFatality",1);
		//TNT1 A 0 A_JumpIfInventory("NoFoodHealth", 1, 3);
 		TNT1 A 0;//A_UnSetInvulnerable
	Goto See;
	
	FatalityComando:
		TNT1 A 0;//A_SetInvulnerable
		SARK JKJKJKJKJK 10  {pb_blood_and_gore_event.much_blood(self);}
		//TNT1 A 0 A_TakeInventory("ComandoFatality",1);
		//TNT1 A 0 A_JumpIfInventory("NoFoodHealth", 1, 3);
 		TNT1 A 0;//A_UnSetInvulnerable
	Goto See;
	
	FatalityImp:
		TNT1 A 0;//A_SetInvulnerable
		SARK HIHIHIHIHI 10  {pb_blood_and_gore_event.much_blood(self);}
		//TNT1 A 0 A_TakeInventory("ImpFatality",1);
		//TNT1 A 0 A_JumpIfInventory("NoFoodHealth", 1, 3);
 		//TNT1 A 0;//A_UnSetInvulnerable
	Goto See;

	Eat:
		SARK ABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABABAB 10
		{
			A_Look();
			a_spawnprojectile("named_BloodTr", 35, 0, random(0, 360), 2, random(0, 180));
			a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 160));
		}
	Goto watch;
	
	Death.Eat:
		//TNT1 A 0 A_GiveToTarget("EatMe",1);
	Goto Death+3;
	
	EatFast:
		SARK ABABABABABABABABABABABABAB 10
		{
			A_Look();
			a_spawnprojectile("named_BloodTr", 35, 0, random(0, 360), 2, random(0, 180));
			a_spawnprojectile("Brutal_FlyingBlood", 0, 0, random(0, 360), 2, random(0, 160));
		}

	Goto MeleeDown;
	
	
	Death.Ice:
	Death.Freeze:
	Death.Frost:
		TNT1 A 0 {self.bSHOOTABLE = false;}
		TNT1 A 0 {self.bSOLID = false;}
		//TNT1 A 0 A_SpawnItem("FrozenDemon");
	Stop;
}
}



CLASS DemonAttack: BaronBall
{
Default
{	
	Radius 8;
	Height 8;
	DamageType "Eat";
	Projectile;
	Speed 15;
	+RANDOMIZE;
	DamageFunction(random(2,3));
	+RIPPER;
	+FORCEXYBILLBOARD;
	+THRUGHOST;
	RenderStyle "Add";
	Alpha 0.6;
	SeeSound "none";
	DeathSound "none";
	Decal "none";
}

States
{
	Spawn:
		TNT1 A 4 BRIGHT;
	Stop;
	
	Death:
		TNT1 A 0 BRIGHT;
		TNT1 A 0 A_PlaySOund("misc/xdeath1");
		TNT1 A 10;
	Stop;
}
}


