CLASS AracnorbBall : ACTOR { 
	Default {
		
		Projectile;
		+RANDOMIZE;
		+FORCEXYBILLBOARD;
		+DONTSPLASH;
		+BLOODSPLATTER;
		+NOEXTREMEDEATH;
		damagetype "desintegrate";
		radius 2;
		height 2;
		renderstyle "Add";
		alpha 0.9;
		scale .42;
		Speed 20;
		Fastspeed 23;
		Decal "Scorch";
		SeeSound "ImpFire";
		DeathSound "ImpFireImpact";
	}
	states
	{
		Spawn:
			TNT1 A 2 BRIGHT A_SpawnItem("GreenFlareSmall",0,0);
			TNT1 A 0 a_spawnprojectile ("SmallGreenFlameTrails", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 a_spawnprojectile ("GreenTracerSmall", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnItemEx("GreenTrailSparks", random(5,-5), random(5,-5), random(5,-5), 0, 0, 0, 0, 128, 0);
			Loop;
			
		Death:
			TNT1 B 1 A_Explode(15,50,0);
			TNT1 A 0 a_spawnprojectile ("PlasmaParticleSpawner", 0, 0, random (0, 180), 2, random (0, 360));
			TNT1 B 4;
			TNT2 AAAAAAAAA 4 a_spawnprojectile ("PlasmaSmoke", 1, 0, random (0, 360), 2, random (0, 160));
			Stop;
	}
}

CLASS mind_flyer : proto_spider
{ 
	Default {
		
		MONSTER;
		+NOGRAVITY;
		+FLOAT;
		+FLOATBOB;
		+DONTHARMCLASS ;
		Species "Arachnotron";
		Health 300;
		Radius 24;
		Height 56;
		Mass 400;
		Speed 5;
		//SpawnID 1690;
		PainChance 150;
		SeeSound "aracnorb/sight";
		ActiveSound "baby/active";
		PainSound "baby/pain";
		DeathSound "misc/gibbed";
		MeleeSound "demon/melee";
		MeleeDamage 6;
		MissileHeight 36;
		Obituary "%o was zapped by an aracnorb.";
		HitObituary "%o had %p skull chewed by an aracnorb.";
		Scale 0.85;
	}
	States
	{
		Spawn:
			ACNB A 1 A_Look;
			Loop;
		See:
			ACNB A 2 A_Chase;
			Loop;
		Melee:
			TNT1 A 0 A_Playsound("caco/melee");
			ACNB A 3 A_FaceTarget;
			TNT1 A 0 A_Recoil(-1);
			ACNB B 3;
			TNT1 A 0 A_Recoil(-1);
			ACNB C 3;
			TNT1 AAA 0 a_spawnprojectile("DemonAttack",40,0,0,0);
			ACNB B 3;
			ACNB A 5;
			Goto See;
		Missile:
			ACNB B 12 Bright A_FaceTarget;
			ACNB C 2 Bright a_spawnprojectile("AracnorbBall", 34, 0, 0, 0);
			ACNB B 2 BRIGHT a_spawnprojectile("AracnorbBall", 34, 0, 0, 0);
			ACNB D 0 A_Jump(32,"See");
			ACNB B 12;
			ACNB D 0;//A_SpidRefire
			Goto Missile;
		Pain:
			ACNF I 2;
			ACNF I 2 A_Pain;
			Goto See;
		Pain.Kick:
		Pain.ExtremePunches:
			TNT1 A 0 A_Recoil(10);
			ACNF I 6 A_FaceTarget;
			ACNF I 6 A_Pain;
			Goto See   ;
		Pain.Avoid: 
			TNT1 A 0;
			TNT1 A 0 A_Jump(255, "AvoidLeft", "AvoidRight");
			Goto AvoidLeft;
			
		AvoidLeft:
			ACNB A 1 A_FaceTarget;
			TNT1 A 0 ThrustThing(angle*256/360+192, 15, 0, 0);
			ACNB A 5 A_FaceTarget;
			Goto Missile;
		AvoidRight:
			ACNB A 1 A_FaceTarget;
			TNT1 A 0 ThrustThing(angle*256/360+64, 15, 0, 0);
			ACNB A 5 A_FaceTarget;
			Goto Missile;
			
			
		Death:
			ACNB D 0 {self.bFLOATBOB = false;}
			ACNB D 8 A_Scream;
			TNT1 AAAAA 0 a_spawnprojectile ("CeilBloodLauncherLong", 0, 0, random (0, 360), 2, random (50, 130));
			TNT1 AAAA 0 a_spawnprojectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 a_spawnprojectile ("XDeathBrain1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 a_spawnprojectile ("XDeathBrain2", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAA 0 a_spawnprojectile ("BloodMist", 50, 0, random (0, 360), 2, random (60, 90));
			TNT1 AA 0 a_spawnprojectile ("XDeathSpiderNew1", 42, 0, random (0, 360), 2, random (60, 90));
			TNT1 A 0 a_spawnprojectile ("XDeathSpiderNew2", 42, 0, random (0, 360), 2, random (60, 90));
			ACNB E 6 A_NoBlocking;
			ACNB FG 8;
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			ACNB H -1;
			Stop;
			
		Death.SuperPlasma:
		Death.Plasma:
		Death.Plasma2:
		Death.GreenFire:  
			ACNB D 0 {self.bFLOATBOB = false;}
			TNT1 A 0 A_Jump(50, "XDeath");
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 AAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 a_spawnprojectile ("XDeathBurnedMeat3", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL AA 0 a_spawnprojectile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			CARB JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 7 a_spawnprojectile ("PlasmaSmoke", 15, 0, random (0, 360), 2, random (70, 110));
			CARB J -1;
			Stop;
			
		Death.Fire:
			TNT1 A 0;
			ACNB D 0 {self.bFLOATBOB = false;}
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 AAA 0 a_spawnprojectile ("PEPart2", 32, 0, random (0, 360), 2, random (0, 160));
			ACNB DDDD 2 a_spawnprojectile ("FlameTrails", 45, 0, random (0, 360), 2, random (50, 130));
			ACNB EEEE 2 a_spawnprojectile ("FlameTrails", 30, 0, random (0, 360), 2, random (50, 130));
			ACNB FFFF 2 a_spawnprojectile ("FlameTrails", 25, 0, random (0, 360), 2, random (50, 130));
			ACNB GGGG 2 a_spawnprojectile ("FlameTrails", 25, 0, random (0, 360), 2, random (50, 130));
			TNT1 A 0 A_Playsound("props/redfire");
			Goto Burns;
		Burns:
			TNT1 A 0;
			TNT1 A 0 A_GiveInventory("BrutalCounter");
			CARB JJ 2 A_SpawnItem("YellowFlare",0,20);
			ID22 F 0 a_spawnprojectile ("FlameTrails", 20, 0, random (0, 360), 2, random (70, 110));
			CARB JJ 2 A_SpawnItem("YellowFlare",0,20);
			ID22 F 0 a_spawnprojectile ("FlameTrails", 20, 0, random (0, 360), 2, random (70, 110));
			ID22 F 0 a_spawnprojectile ("PlasmaSmoke", 30, 0, random (0, 360), 2, random (70, 110));
			TNT1 A 0 A_JumpIfInventory("BrutalCounter", 30, "Smokes");
			Loop;
		Smokes:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory("BrutalCounter", 60, "Rest");
			TNT1 A 0 A_GiveInventory("BrutalCounter");
			CARB J 5 a_spawnprojectile ("PlasmaSmoke", 30, 0, random (0, 360), 2, random (70, 110));
		Loop;
		
		Rest:
			CARB J -1;
		Stop;
			
			
		Death.Cut:
		Death.Saw:
			ACNB D 0 {self.bFLOATBOB = false;}
			TNT1 A 0 A_Jump(50, "XDeath")    ;
			TNT1 AAA 0 a_spawnprojectile ("Instestin2", 14, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 a_spawnprojectile ("CeilBloodLauncher", 40, 0, random (0, 360), 2, random (50, 130));
			TNT1 AAAA 0 a_spawnprojectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 a_spawnprojectile ("XDeath2", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAA 0 a_spawnprojectile ("PlayerFlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			ACNB JKLM 4;
			TNT1 AAAAAAAAA 0 a_spawnprojectile ("XDeathBrain1", 24, 15, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAA 0 a_spawnprojectile ("Instestin2", 24, 15, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			ACNB NNNNN 1a_spawnprojectile ("Brutal_LiquidBlood2", 28, 0, random (0, 360), 2, random (30, 60));
			ACNB OOOOO 1a_spawnprojectile ("Brutal_LiquidBlood2", 21, 0, random (0, 360), 2, random (30, 60));
			ACNB PPPPPPPP 1a_spawnprojectile ("Brutal_LiquidBlood2", 14, 0, random (0, 360), 2, random (30, 60));
			ACNB P -1;
			Stop   ;
			
			/*	Death.Ice:
				Death.Freeze:
				Death.Frost:
					TNT1 A 0 {self.bSHOOTABLE", 0)
					TNT1 A 0 {self.bSOLID", 0)
					TNT1 A 0 A_SpawnItem("FrozenAracnorb")
					Stop
			*/
		Death.XDeath:
		Death.Blast:
		Death.SSG:
		Death.ExplosiveImpact:
		Death.Crush:
			ACNB D 0 {self.bFLOATBOB = false;}
			ACNB I 2;
			TNT1 A 0 A_Playsound("misc/gibbed",3)   ;
			TNT1 AAA 0 a_spawnprojectile ("Instestin2", 14, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 a_spawnprojectile ("CeilBloodLauncher", 40, 0, random (0, 360), 2, random (50, 130));
			TNT1 AAAAAA 0 a_spawnprojectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAA 0 a_spawnprojectile ("XDeath2", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 a_spawnprojectile ("Aracnorb_Brain", 32, 0, random (0, 360), 2, random (0, 160)) ;
			TNT1 AAAAAAAAAA 0 a_spawnprojectile ("PlayerFlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			POSS STUVW 3;
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			POSS X -1;
			Stop ;
			
		Death.Fatality:
			TNT1 A 0;
			TNT1 A 0 A_Pain;
			TNT1 A 0;
			TNT1 A 0 A_GiveToTarget("GoFatality", 1);
			TNT1 A 0 A_GiveToTarget("AracnorbFatality", 1);
			TNT1 A 0;
			Stop;
			
		Raise:
			ACNB HGFEDA 8;
			ACNB A 0 {self.bFLOATBOB = true;}
			Goto See;
	}
}

CLASS Aracnorb_Brain : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 16;
		Scale 1.5;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		+DOOMBOUNCE;
		+SKYEXPLODE;
		BounceFactor 0.5;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BloodSuper";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			ID22 A 2 a_spawnprojectile("BloodTrails",0,0,180,2);
			
			ID22 B 2 a_spawnprojectile("BloodTrails",0,0,180,2);
			
			ID22 C 2 a_spawnprojectile("BloodTrails",0,0,180,2);
			
			ID22 D 2 a_spawnprojectile("BloodTrails",0,0,180,2);
			Loop;
		Death:
			
			ID22 F 1 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
			ID22 F -1;
			Stop;
			TNT1 A 1;
		Splash:
			TNT1 A 0;
			Stop;
	}
}

CLASS StompedAracnorb: pb_dismembered_monster_base { 
	Default {
		
		+NOBLOOD;
		Health 999999999999;
	}
	States
	{
		Spawn:
			FTAC P -1;
			Stop   ;
	}
}		

CLASS Grell : mind_flyer
{}
	
