CLASS pb_Arachnophyte : proto_spider// replaces Arachnotron
{ 
Default
{		
	Health 625;
	Radius 52;
	Height 56;
	Speed 6;
	PainChance 15;
	Mass 5000;
	MONSTER;
	//SpawnID 1630;
	+NOGRAVITY;
	-FLOATBOB;
	-FLOAT;
	+NORADIUSDMG;
	+DONTHARMSPECIES;
	+DONTHARMCLASS;
	Species "Arachnotron";
	SeeSound "arachnophyte/sight";
	PainSound "arachnophyte/pain";
	DeathSound "arachnophyte/death";
	AttackSound "spider/attack";
	Obituary "%o was perforated by an Arachnophyte.";
	DamageFactor "Crush", 10.0;
	DamageFactor "Avoid", 0.0;
	damagefactor "killme", 0.0;
	DamageFactor "Saw", 0.6;
	BloodType "Brutal_Blood", "BloodSPlatterReplacer", "Brutal_Blood";
	MaxStepHeight 24;
	MaxDropOffHeight 24;
	PainChance "Kick", 255;
	Damage 25;
	Scale 1.15;
	Explosiondamage 128;
	Explosionradius 255;

/*	DropItem "Berserker", 5;
	DropItem "DemonStrengthRune", 1;
	DropItem "Demonpickup2", 255;
	DropItem "Demonpickup", 95;
	DropItem "Demonpickup", 85;*/
	
	PainChance "Stun", 255;
}

States
{
	Death.Blackhole:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_PlaySound("redburn",6,1,1);
		TNT1 AAAA 0 a_spawnprojectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));		
		TNT1 AAAAAAAAAAA 0 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 50, 0, 0, 0, 0, 128);
		ID67 AAABCDEFGHIJK 4 A_SpawnItemEx("PurpleTrailSparks", 0, 0, 50, 0, 0, 0, 0, 128);
		TNT1 A 0 A_StopSound(2);
	Stop;

	Spawn:
		TNT1 AA 0;
		MARP Z 7 A_Look;
		Goto Spawn+2;
	See:
		//TNT1 A 0 A_GiveInventory("ArachnophyteAlerted", 1);
		TNT1 A 0 A_Playsound("cbaron/metal");
		MARP Z 2;
		MARP A 0 A_PlaySound("arachnophyte/engine",6, 1, 1);
		TNT1 A 0 {self.bFLOAT = true;}
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP B 2 ThrustThingZ(0,3,0,0);
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP A 2 ThrustThingZ(0,3,0,0);
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP B 2 ThrustThingZ(0,3,0,0);
		TNT1 A 0 {self.bFLOATBOB = true;}
	SeeContinue:
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP A 2 Bright A_Chase;
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP B 2 Bright A_Chase;
	Loop;
		
		//Brutal Counters are used so the chaingun attack isn't too OP
	Missile:
		TNT1 A 0;
		//TNT1 A 0 A_TakeInventory ("BrutalCounter2", 5);
		//TNT1 A 0 A_JumpIfInventory ("BrutalCounter2", 5, "PrepareToFirePlasma");
		TNT1 A 0 A_Jump(96, "Missile2");
	PrepareToFirePlasma:
		TNT1 A 0 A_PlaySound("BMCHARG");
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP A 2 Bright A_FaceTarget;
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP B 2 Bright A_FaceTarget;
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP A 2 Bright A_FaceTarget;
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP B 2 Bright A_FaceTarget;
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP A 2 Bright A_FaceTarget;
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP B 2 Bright A_FaceTarget;
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP A 2 Bright A_FaceTarget;
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
	FirePlasma:
		TNT1 A 0 A_FaceTarget;
		MARP C 2 BRIGHT a_spawnprojectile("RedPlasmaBall",25,0,0,0);
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP D 2 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP C 2 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP D 2 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		TNT1 A 0 A_FaceTarget;
		MARP C 2 BRIGHT a_spawnprojectile("RedPlasmaBall",25,0,0,0);
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP D 2 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP C 2 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP D 2 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		TNT1 A 0 A_FaceTarget;
		MARP C 2 BRIGHT a_spawnprojectile("RedPlasmaBall",25,0,0,0);
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP D 2 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP C 2 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP D 2 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		TNT1 A 0 A_FaceTarget;
		MARP C 2 BRIGHT a_spawnprojectile("RedPlasmaBall",25,0,0,0);
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP D 2 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP C 2 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP D 2 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		//TNT1 A 0 A_TakeInventory ("BrutalCounter2", 1);
		TNT1 A 0 A_Jump(160, 2);
		TNT1 A 0 A_JumpIfInTargetLOS("FirePlasma", 0, JLOSF_DEADNOJUMP);
		TNT1 AA 0;
	Goto SeeContinue;
		
	Missile2:
		TNT1 A 0 A_PlaySound("DTHDLRST");
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP A 2 Bright A_FaceTarget;
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP B 2 Bright A_FaceTarget;
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP A 2 Bright A_FaceTarget;
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP B 2 Bright A_FaceTarget;
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP A 2 Bright A_FaceTarget;
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP B 2 Bright A_FaceTarget;
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP A 2 Bright A_FaceTarget;
		TNT1 A 0 A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
	FireMachineGun:
		TNT1 A 0 A_FaceTarget;
		MARP K 3 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		TNT1 A 0 a_spawnprojectile("YellowFlareSmall",12,-5,0,0);
		TNT1 A 0 a_spawnprojectile("YellowFlareSmall",12, 5,0,0);
		TNT1 A 0 a_spawnprojectile("ArachnophyteTracer",12, 5,random(-3,3),0);
		TNT1 A 0 a_spawnprojectile("ArachnophyteTracer",12,-5,random(-3,3),0);
		TNT1 A 0 a_spawnprojectile("ArachnophyteTracer",12, 5,random(-3,3),0);
		TNT1 A 0 a_spawnprojectile("BigEmptyCaseSpawn",12, 5,random(-3,3),0);
		TNT1 A 0 ;
		MARP L 3 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		TNT1 A 0 a_spawnprojectile("YellowFlareSmall",12,-5,0,0);
		TNT1 A 0 a_spawnprojectile("YellowFlareSmall",12, 5,0,0);
		TNT1 A 0 a_spawnprojectile("ArachnophyteTracer",12,-5,random(-4,4),0);
		TNT1 A 0 a_spawnprojectile("ArachnophyteTracer",12, 5,random(-3,3),0);
		TNT1 A 0 a_spawnprojectile("BigEmptyCaseSpawn",12, 5,random(-3,3),0);
		MARP K 3 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		TNT1 A 0 a_spawnprojectile("YellowFlareSmall",12,-5,0,0);
		TNT1 A 0 a_spawnprojectile("YellowFlareSmall",12, 5,0,0);
		TNT1 A 0 a_spawnprojectile("ArachnophyteTracer",12,-5,random(-4,4),0);
		TNT1 A 0 a_spawnprojectile("ArachnophyteTracer",12, 5,random(-3,3),0);
		TNT1 A 0 a_spawnprojectile("BigEmptyCaseSpawn",12, 5,random(-3,3),0);
		TNT1 A 0  A_FaceTarget;
		MARP L 3 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		TNT1 A 0 a_spawnprojectile("YellowFlareSmall",12,-5,0,0);
		TNT1 A 0 a_spawnprojectile("YellowFlareSmall",12, 5,0,0);
		TNT1 A 0 a_spawnprojectile("ArachnophyteTracer",12,-5,random(-4,4),0);
		TNT1 A 0 a_spawnprojectile("ArachnophyteTracer",12, 5,random(-3,3),0);
		TNT1 A 0 a_spawnprojectile("BigEmptyCaseSpawn",12, 5,random(-3,3),0);
		MARP K 3 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		TNT1 A 0 a_spawnprojectile("YellowFlareSmall",12,-5,0,0);
		TNT1 A 0 a_spawnprojectile("YellowFlareSmall",12, 5,0,0);
		TNT1 A 0 a_spawnprojectile("ArachnophyteTracer",12,-5,random(-4,4),0);
		TNT1 A 0 a_spawnprojectile("ArachnophyteTracer",12, 5,random(-3,3),0);
		TNT1 A 0 a_spawnprojectile("BigEmptyCaseSpawn",12, 5,random(-3,3),0);
		TNT1 A 0 ;
		//So he's not too OP
		//TNT1 A 0 A_GiveInventory ("BrutalCounter2", 1);
		//TNT1 A 0 A_JumpIfInventory ("BrutalCounter2", 12, "SeeContinue");
		TNT1 A 0 A_Jump(4, "SeeContinue", "PrepareToFirePlasma");
		TNT1 A 0 A_JumpIfInTargetLOS("FireMachineGun", 0, JLOSF_DEADNOJUMP);
	Goto SeeContinue;
		
		
	Pain:
		TNT1 A 0;
		//MARP E 1 A_JumpIfInventory("ArachnophyteAlerted", 1, 2);
		Goto See;
		TNT1 AA 0;
		MARP E 1 A_Pain;
		MARP E 2 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
		MARP E 2;
		MARP E 2 BRIGHT A_SpawnItem("ArachnophyteFireSpawner",0,0,0,0);
	Goto SeeContinue;
		
	Pain.Avoid: 
		TNT1 A 0;
		TNT1 A 0 A_Jump(255, "AvoidLeft", "AvoidRight");
	AvoidLeft:
		MARP C 1 A_FaceTarget;
		TNT1 A 0 ThrustThing(angle*256/360+192, 8, 0, 0);
		MARP C 5 A_FaceTarget;
	Goto Missile;

	AvoidRight:
		MARP C 1 A_FaceTarget;
		TNT1 A 0 ThrustThing(angle*256/360+64, 8, 0, 0);
		MARP C 5 A_FaceTarget;
	Goto Missile;

	Possession:
		TNT1 A 0 A_SetInvulnerable;
		MARP E 3;
		MARP E 3 A_Pain;
		"####" "#" 35;// ACS_NamedExecuteAlways("Pos - Flicker effect");
		TNT1 A 0 A_UnSetInvulnerable;
		Goto See;
		
	Pain.Stun:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx ("StunElectrocute", random (-4, 4), random (-4, 4),  random (16, 32), 0, 0);
		MARP E 1 A_Pain;
		MARP EEEEEEEEEE 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		MARP E 1 A_Pain;
		MARP EEEEEEEEEE 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		MARP E 1 A_Pain;
		MARP EEEEEEEEEE 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		MARP E 1 A_Pain;
		MARP EEEEEEEEEE 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		MARP E 1 A_Pain;
		MARP EEEEEEEEEE 3 A_SpawnItemEx ("StunElectrocute", random (-12, 12), random (-12, 12),  random (16, 52), 0, 0);
		MARP E 1 A_Pain;
		Goto See;
		
	Death.Fatality:
		//TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_BossDeath;
		//TNT1 A 0 A_GiveToTarget("ArachnophyteFatality", 1);
		Stop;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 {self.bFLOATBOB = false;}
		TNT1 A 0 A_Jump(148, "GenericDeath");
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_StopSound(6);
		TNT1 A 0 A_Fall;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		//TNT1 A 0 A_SpawnItemEx ("BarrelKaboom",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_Playsound("Explosion");
		TNT1 AAA 0 a_spawnprojectile ("MetalShard1", 5, 0, random (0, 360), 2, random (30, 160));
		TNT1 AA 0 a_spawnprojectile ("MetalShard2", 5, 0, random (0, 360), 2, random (30, 160));
		TNT1 AAA 0 a_spawnprojectile ("MetalShard3", 5, 0, random (0, 360), 2, random (30, 160));
		TNT1 A 0 a_spawnprojectile ("SpiderPart1", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("SpiderPart2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathSpiderPart5", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathSpiderPart6", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathSpiderPart4", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece", random (-15, 15), random (-15, 15));
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece2", random (-35, 35), random (-35, 35));
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece3", random (-45, 45), random (-45, 35));
		TNT1 A 0 a_spawnprojectile("FireballExplosionFlamesBig", 40, 0, random (0, 360), 2, random (50, 130));
		MARP S 12;
		MARP T 11;
		MARP U 10 A_BossDeath;
		MARP VVVVVVVVVVVVVVVVVVVVVVVVVV 7 a_spawnprojectile ("PlasmaSmoke", 15, 0, random (0, 360), 2, random (70, 110));
		MARP V -1;
	Stop;
		
		
	Death.Cut:
	Death.Saw:
	Death.Tear:
		TNT1 AAAAA 0 a_spawnprojectile ("Instestin2", 14, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile ("CeilBloodLauncher", 40, 0, random (0, 360), 2, random (50, 130));
		TNT1 AAAAA 0 a_spawnprojectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("XDeath2", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAAAAAAA 0 a_spawnprojectile ("BloodMistBig", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathArachnotronHead3", 50, 0, random (0, 360), 2, random (40, 130));
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 {self.bFLOATBOB = false;}
		ARF7 L 2 A_BossDeath;
		TNT1 A 0 A_Fall;
		TNT1 A 0 A_SpawnItemEx ("ArachnophyteFrame",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	Stop;
		
	Death.Plasma:
	Death.SuperPlasma:
	Death.Desintegrate:
	GenericDeath:
	XDeath:
	Death.ExplosiveImpact:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 {self.bFLOATBOB = false;}
		TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		//TNT1 A 0 A_SpawnItemEx ("BarrelKaboom",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 a_spawnprojectile ("NewRocketExploFX", 0, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 ThrustThing(angle*random(0, 360), 12, 0, 0);
		TNT1 A 0 ThrustThingZ(0,random(-10, 10),0,1);
		TNT1 A 0 a_spawnprojectile("FireballExplosionFlamesBig", 40, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 40, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0 A_Playsound("Explosion");
		TNT1 A 0 a_spawnprojectile ("XDeathSpiderPart1", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("SpiderPart1", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("SpiderPart2", 32, 0, random (0, 360), 2, random (0, 160));
		MARP E 3 A_StopSound(6);
		TNT1 A 0 ThrustThing(angle*random(0, 360), 12, 0, 0);
		TNT1 A 0 ThrustThingZ(0,random(-10, 10),0,1);
		TNT1 A 0 a_spawnprojectile("FireballExplosionFlamesBig", 40, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 40, 0, random (0, 360), 2, random (50, 130));
		MARP F 2;
		TNT1 A 0 ThrustThing(angle*random(0, 360), 12, 0, 0);
		TNT1 A 0 ThrustThingZ(0,random(-10, 10),0,1);
		TNT1 A 0 a_spawnprojectile("FireballExplosionFlamesBig", 40, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 40, 0, random (0, 360), 2, random (50, 130));
		MARP G 2;
		TNT1 A 0 ThrustThing(angle*random(0, 360), 12, 0, 0);
		TNT1 A 0 ThrustThingZ(0,random(-10, 10),0,1);
		TNT1 A 0 a_spawnprojectile("FireballExplosionFlamesBig", 40, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 40, 0, random (0, 360), 2, random (50, 130));
		MARP H 2;
		TNT1 A 0 ThrustThing(angle*random(0, 360), 12, 0, 0);
		TNT1 A 0 ThrustThingZ(0,random(-10, 10),0,1);
		TNT1 A 0 a_spawnprojectile("FireballExplosionFlamesBig", 40, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 40, 0, random (0, 360), 2, random (50, 130));
		MARP I 2;
		TNT1 A 0 ThrustThing(angle*random(0, 360), 12, 0, 0);
		TNT1 A 0 ThrustThingZ(0,random(-10, 10),0,1);
		TNT1 A 0 a_spawnprojectile("FireballExplosionFlamesBig", 40, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 40, 0, random (0, 360), 2, random (50, 130));
		MARP J 2;
		TNT1 A 0 ThrustThing(angle*random(0, 360), 12, 0, 0);
		TNT1 A 0 ThrustThingZ(0,random(-10, 10),0,1);
		TNT1 A 0 a_spawnprojectile("FireballExplosionFlamesBig", 40, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 40, 0, random (0, 360), 2, random (50, 130));
		MARP Q 2;
		TNT1 A 0 ThrustThing(angle*random(0, 360), 12, 0, 0);
		TNT1 A 0 ThrustThingZ(0,random(-10, 10),0,1);
		TNT1 A 0 a_spawnprojectile("FireballExplosionFlamesBig", 40, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0 a_spawnprojectile("ExplosionParticle", 40, 0, random (0, 360), 2, random (50, 130));
		MARP R 2;
		
		TNT1 A 0 A_PlaySound("excavator/explode");
		TNT1 A 0 a_spawnprojectile("BigRicoChet");
		TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -30);
		TNT1 A 0 A_SpawnItemEx ("DetectFloorCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("DetectCeilCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("UnderwaterExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		//TNT1 AAA 0 a_spawnprojectile ("FireworkSFXType2", 32, 0, random (0, 360), 2, random (30, 60));
		//TNT1 A 0 A_SpawnItemEx ("NewBarrelExploFX", 15, 0, 20);
		TNT1 A 0 A_SpawnItem("WhiteShockwaveBig");
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece", random (-15, 15), random (-15, 15));
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece2", random (-35, 35), random (-35, 35));
		TNT1 AA 0 A_SpawnItemEx("TinyBurningPiece3", random (-45, 45), random (-45, 35));
		TNT1 A 0 A_Jump(180, 2);
		TNT1 A 0 a_spawnprojectile ("XDeathArachnotronHead3", 50, 0, random (0, 360), 2, random (40, 130));
		TNT1 A 0;
		MARP R 1 A_BossDeath;
		TNT1 AAAAA 0 a_spawnprojectile ("BloodMistExtraBig", 30, 0, random (0, 360), 2, random (20, 90));
		TNT1 AAA 0 a_spawnprojectile ("SuperGoreSpawner2", 32, 0, random (0, 360), 2, random (20, 40));
		TNT1 AAAA 0 a_spawnprojectile ("PEPart2SuperFast", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("SpiderPart1", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("SpiderPart2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathSpiderPart2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathSpiderPart3", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 a_spawnprojectile ("XDeathSpiderPart5", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathSpiderPart6", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathSpiderPart4", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Jump(127, 47);
		MARP Y 1 A_Fall;
		MARP YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY 8 a_spawnprojectile ("PlasmaSmoke", 15, 0, random (0, 360), 2, random (70, 110));
		MARP Y -1;
	Stop;
		TNT1 AAAAAAA 0;
		MARP X 1 A_Fall;
		MARP XXXXXXXXXXXXXXXXXXXXXXX 8 a_spawnprojectile ("PlasmaSmoke", 15, 0, random (0, 360), 2, random (70, 110));
		MARP X -1;
	Stop;
		
	Death.Blast:
	Death.Nailgun:
		TNT1 A 0;
		TNT1 A 0 A_Jump(32, "Death.SSG", "DeathStrong");
	Goto GenericDeath;

	Death.Shotgun:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfCloser(250, 1);
		Goto Death;
	DeathStrong:
		TNT1 AA 0;
		TNT1 AAAA 0 a_spawnprojectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 a_spawnprojectile ("PEPart2SuperFast", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathSpiderPart2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 a_spawnprojectile ("SuperWallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAA 0 a_spawnprojectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 a_spawnprojectile ("XDeathSpiderPart3", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 {self.bFLOATBOB = false;}
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Fall;
		TNT1 A 0 A_StopSound(6);
		MARP M 10 A_XScream;
		MARP N 10 A_Fall;
		MARP O 9;
		MARP P 1 A_BossDeath;
		MARP PPPPPPPPPPPPPPPPPPPPPPP 2 a_spawnprojectile ("Brutal_LiquidBlood3", 13, 0, random (0, 360), 2, random (0, 160));
		MARP P -1;
		Stop;
	Death.SSG:
		TNT1 AAAAA 0 a_spawnprojectile ("Instestin2", 14, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 a_spawnprojectile ("CeilBloodLauncher", 40, 0, random (0, 360), 2, random (50, 130));
		TNT1 AAAAA 0 a_spawnprojectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 a_spawnprojectile ("XDeath2", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAAAAAAA 0 a_spawnprojectile ("BloodMistBig", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnprojectile ("XDeathArachnotronHead3", 50, 0, random (0, 360), 2, random (40, 130));
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 {self.bFLOATBOB = false;}
		ARF7 L 2 A_BossDeath;
		TNT1 A 0 A_Fall;
		TNT1 A 0 A_SpawnItemEx ("ArachnophyteFrame",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		Stop;
		
}
}

CLASS ArachnophyteFireSpawner : ACTOR { 
Default {
	
	+CLIENTSIDEONLY;
	+NOGRAVITY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx("ArachnophyteFire",random(20,25),random(20,25),35,0,0,random(-4,-6),0,128,0);
		TNT1 A 0 A_SpawnItemEx("ArachnophyteFire",random(-20,-25),random(-20,-25),35,0,0,random(-4,-6),0,128,0);
		TNT1 A 0 A_SpawnItemEx("ArachnophyteFire",random(20,25),random(-20,-25),35,0,0,random(-4,-6),0,128,0);
		TNT1 A 0 A_SpawnItemEx("ArachnophyteFire",random(-20,-25),random(20,25),35,0,0,random(-4,-6),0,128,0);
		TNT1 A 1;
		Stop;
}
}

CLASS JetpackFireSpawner : ACTOR { 
Default {
	
	+CLIENTSIDEONLY;
	+NOGRAVITY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItemEx("ArachnophyteFire",random(20,25),random(20,25),35,0,0,random(-4,-6),0,128,0);
		TNT1 A 0 A_SpawnItemEx("ArachnophyteFire",random(-20,-25),random(-20,-25),35,0,0,random(-4,-6),0,128,0);
		TNT1 A 0 A_SpawnItemEx("ArachnophyteFire",random(20,25),random(-20,-25),35,0,0,random(-4,-6),0,128,0);
		TNT1 A 0 A_SpawnItemEx("ArachnophyteFire",random(-20,-25),random(20,25),35,0,0,random(-4,-6),0,128,0);
		TNT1 A 1;
		TNT1 A 0 A_SpawnItemEx("ArachnophyteFire",random(20,25),random(20,25),35,0,0,random(-4,-6),0,128,0);
		TNT1 A 0 A_SpawnItemEx("ArachnophyteFire",random(-20,-25),random(-20,-25),35,0,0,random(-4,-6),0,128,0);
		TNT1 A 0 A_SpawnItemEx("ArachnophyteFire",random(20,25),random(-20,-25),35,0,0,random(-4,-6),0,128,0);
		TNT1 A 0 A_SpawnItemEx("ArachnophyteFire",random(-20,-25),random(20,25),35,0,0,random(-4,-6),0,128,0);
		TNT1 A 1;
		TNT1 A 0 A_SpawnItemEx("ArachnophyteFire",random(20,25),random(20,25),35,0,0,random(-4,-6),0,128,0);
		TNT1 A 0 A_SpawnItemEx("ArachnophyteFire",random(-20,-25),random(-20,-25),35,0,0,random(-4,-6),0,128,0);
		TNT1 A 0 A_SpawnItemEx("ArachnophyteFire",random(20,25),random(-20,-25),35,0,0,random(-4,-6),0,128,0);
		TNT1 A 0 A_SpawnItemEx("ArachnophyteFire",random(-20,-25),random(20,25),35,0,0,random(-4,-6),0,128,0);
		Stop;
}
}

CLASS ArachnophyteFire : ACTOR { 
Default {
	
	+MISSILE;
	+DONTSPLASH;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOGRAVITY;
	+NOTELEPORT;
	+FORCEXYBILLBOARD;
	+THRUACTORS;
	RenderStyle "Add";
	Scale 0.33;
}
States
{
	Spawn:
		F9R1 ABCDEFGHIJKL 1 Bright A_FadeOut;
		Stop;
}
}

CLASS RedPlasmaBall: pb_projectile_base
{ 
Default {
	
	Radius 5;
	Height 5;
	Speed 45;
	Scale 0.35;
	DamageType "Burn";
	Damage 0;
	Decal "Scorch";
	RenderStyle "Add";
	SeeSound "PAILGF3";
	DeathSound "weapons/plasmax";
	Projectile;
}
states
{
	Spawn:
		PBAL HI 1 BRIGHT;
		TNT1 A 0 A_SpawnItemEx("ObeliskTrailSpark", 0, 0, 0, 0, 0, 0, 0, 128);
		TNT1 A 0 A_SpawnItem("RedFlareVerySmall",0,0);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem ("RedPlasmaPuff", 0);
		TNT1 A 0 A_Explode(20,30,1);
		TNT1 AAAAA 19 a_spawnprojectile ("PlasmaSmoke", 1, 0, random (0, 360), 2, random (0, 160));
		Stop;
}
}

CLASS RedPlasmaPuff: BulletPuff { 
Default {
	
	RenderStyle "Add";
	Alpha 0.95;
	+NOBLOCKMAP;
	+NOGRAVITY;
	+CLIENTSIDEONLY;
	Scale 1.1;
	Translation "0:255=%[0,0,0]:[1,0,0]";
}
states
{
Spawn:
	TNT1 AAAA 0 A_SpawnItemEx("ObeliskTrailSpark", 0, 0, 0, 0, 0, 0, 0, 128);
	FIR5 ABCDE 1 Bright A_SpawnItem("RedFlare" ,0);
	FIR5 FGHIJKLMNOP 1 Bright A_FadeOut(0.04);
	stop;
}
}

CLASS CrawlingDyingSpider3 : ACTOR { 
Default {

	Radius 12;
	Height 24;
	Speed 9;
	Health 100;
	PainSound "SP_CRAWL";
	damagefactor "Kick", 0.1;
	damagefactor "Melee", 0.1;
	damagefactor "SuperPunch", 0.1;
	damagefactor "SuperKick", 0.1;
	damagefactor "Extremepunches", 0.1;
	PainChance "Kick", 255;
	PainChance "SuperKick", 255;
	PainChance "SuperPunch", 255;
	PainChance "Extremepunches", 255;
	PainChance 255;
	damagefactor "trample", 2.0;
	+SHOOTABLE;
	+FLOORCLIP;
	//+NOBLOCKMAP
	+LOOKALLAROUND;
	+FRIGHTENED;
	+SOLID;
}
States
{
	Spawn:
		AAHD B 1 A_Look;
	Goto See;
	See:
		AAHD ABCD 10 A_Chase;
		AAHD A 0 A_Pain;
		TNT1 A 0 A_SpawnItemEx("Brutal_FlyingBlood", 0, 0, 10, 0, 0);
		tnt1 a 0 a_jump(25, "gotodeath", "death");
		//TNT1 A 0 A_GiveInventory("DeathTimer1", 1);
		//TNT1 A 0 A_JumpIfInventory("DeathTimer1", 12, "GotoDeath");
	Loop;
	
	GotoDeath:
		TNT1 A 0;
		TNT1 A 0 {self.bNOPAIN = true;}
		AAHD EFGH 5;
		AAHD H -1;
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAAAAAAAAAA 0 a_spawnprojectile ("SmallBrainPiece", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 a_spawnprojectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
		AAHD IJKLMN 5;
		AAHD N -5;
	Stop;

	Pain.SuperPunch:
	Pain.SuperKick:
	Pain.Kick:
	Pain.Extremepunches:
		TNT1 A 0 A_FaceTarget;
		AAHD A 1 A_Pain;
		TNT1 A 0 ThrustThing(angle*256/360+128, 5, 0, 0);
	Pain.ExplosiveImpact:
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		AAHD A 2 A_FaceTarget;	
	Fly:
		AAHD ABCDEFGH 3 A_CheckFloor("See");
		tnt1 a 0 A_JumpIf (vel.z == 0, "See");
		TNT1 A 0;
	Loop;
	
}
}

CLASS ArachnophyteFrame : ACTOR { 
Default {
+NOTELEPORT;
+MOVEWITHSECTOR;
+CORPSE;
Scale 1.15;
}

States
{
	Spawn:
		ARF7 LLLLLLLLLLLLLLLLL 6 a_spawnprojectile ("PlasmaSmoke", 22, 0, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("ShoqueAzul", 20, 0, random (0, 360), 2, random (70, 110));
		TNT1 AA 0 a_spawnprojectile ("Spark_UpOnce", 20, 0, random (0, 360), 2, random (70, 110));
		ARF7 LLLLLL 6 a_spawnprojectile ("PlasmaSmoke", 22, 0, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("ShoqueAzul", 20, 0, random (0, 360), 2, random (70, 110));
		TNT1 AA 0 a_spawnprojectile ("Spark_UpOnce", 20, 0, random (0, 360), 2, random (70, 110));
		ARF7 LLLLLLLLLLLLLLLLLLL 6 a_spawnprojectile ("PlasmaSmoke", 22, 0, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("ShoqueAzul", 20, 0, random (0, 360), 2, random (70, 110));
		TNT1 AA 0 a_spawnprojectile ("Spark_UpOnce", 20, 0, random (0, 360), 2, random (70, 110));
		ARF7 LLLLLLLLLLLLLLLL 6 a_spawnprojectile ("PlasmaSmoke", 22, 0, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("ShoqueAzul", 20, 0, random (0, 360), 2, random (70, 110));
		TNT1 AA 0 a_spawnprojectile ("Spark_UpOnce", 20, 0, random (0, 360), 2, random (70, 110));
		ARF7 LLLLLLLLLLLLLLLLLLLLLLL 6 a_spawnprojectile ("PlasmaSmoke", 22, 0, random (0, 360), 2, random (70, 110));
		TNT1 A 0 a_spawnprojectile ("ShoqueAzul", 20, 0, random (0, 360), 2, random (70, 110));
		TNT1 AA 0 a_spawnprojectile ("Spark_UpOnce", 20, 0, random (0, 360), 2, random (70, 110));
		ARF7 L -1;
	stop;
}
}